### ISSUE TITLE
Update indexExchange adapter to v9

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#100]
1. The indexExchange.js adaptor is requesting an indexURL but that needs to be constructed by cygnus_index_start.
2.  Bids should be based on the global index_slots array (as detailed http://wiki.headertag.com/2015/10/05/i-use-an-existing-tag-manager-for-header-bidding/)
3. Based on the second element you can derive the size from cygnus_index_args another global
{"device":"D","siteID":158710,"slots":[{"id":"1","width":728,"height":90,"siteID":158710},{"id":"2","width":728,"height":90,"siteID":158710},{"id":"3","width":300,"height":250,"siteID":158710},{"id":"4","width":300,"height":600,"siteID":158710},{"id":"5","width":300,"height":250,"siteID":158710},{"id":"6","width":300,"height":600,"siteID":158710},{"id":"T1_1","width":728,"height":90,"siteID":164113},{"id":"T1_2","width":728,"height":90,"siteID":164113},{"id":"T1_3","width":300,"height":250,"siteID":164113},{"id":"T1_4","width":300,"height":600,"siteID":164113},{"id":"T1_5","width":300,"height":250,"siteID":164113},{"id":"T1_6","width":300,"height":600,"siteID":164113}],"parseFn":"cygnus_index_parse_res"}"

**Comment by headertag** [comment]
We will handle these changes and send a push request per Matt's comments. Thanks! =)

**Comment by headertag** [comment]
This is now complete per: https://github.com/prebid/Prebid.js/pull/119

**Comment by headertag** [comment]
@mkendall07 is there a plan in place to merge this change? Let us know how we can help further!

**Comment by mkendall07** [comment]
Hi @headertag 

We plan on integrating this with our next release. Will be merged soon. Thanks!

**Comment by mkendall07** [comment]
closed per https://github.com/prebid/Prebid.js/commit/81d83b558813c70e2e620a77843398ba1856fac1
