### ISSUE TITLE
Uncaught Error: Cannot find module "./constants.json"

### ISSUE THREAD

**Issue by joyofdata** [prebid/Prebid.js#1000]
With 0.19.0 I occasionally get the error:

`Uncaught Error: Cannot find module "./constants.json"`

Could somebody offer me insight on what might cause that issue? I mean obviously there is no file named `constants.json`.

**Comment by matthewlane** [comment]
There is a `constants.json` in the `src` directory. Does this error happen for you during the `gulp build` process?

**Comment by joyofdata** [comment]
No, the build went fine. The error is displayed in the developer console. And the provided location is the (built) `prebid.js` file.

**Comment by matthewlane** [comment]
That is mysterious. One thing that might give us a clue is to try reinstalling node_modules with `npm install`, then run both `gulp build` and `gulp devpack` from the root project directory. Try testing the resulting `build/dist/prebid.js` and `build/dev/prebid.js` files to see if the error persists from one or the other

**Comment by joyofdata** [comment]
will do that tomorrow and report back - thanks

**Comment by joyofdata** [comment]
Error was reported to us from two independent sources which is why considered it immediately as legit. yuge problem. Nonetheless cannot reproduce it. So sad! Rebuilt prebid.js and will open more informative issue next time it comes up - hopefully doesn't!
