### ISSUE TITLE
TCF2.0 consent not picked up in Iframe

### ISSUE THREAD

**Issue by KianGroenen** [prebid/Prebid.js#10018]
## Type of issue
Question

## Description
We work with syndication partners for video content on our publisher sites. We're currently working on implementing Prebid in these video players. The player is placed in an Iframe on the site of the publisher. Google (GAM) is able to pick up the consent when a request happens from inside of the iframe, however it seems this is not the case for Prebid. Is this expected behaviour? If yes, any plans on supporting this kind of integration?

**Comment by patmmccann** [comment]
Is the consent management module installed? Do you have a test page? The module uses the following logic from the IABTL spec to get the consent https://github.com/prebid/Prebid.js/blob/122d62441f9012d0718f6535fc8f9c692deb3827/modules/consentManagement.js#L117

**Comment by patmmccann** [comment]
Closing as stale
