### ISSUE TITLE
Set specific timeout for bidder

### ISSUE THREAD

**Issue by fasenderos** [prebid/Prebid.js#10027]
As per title, is there a way to set specific timeout for each bidder? If not and it's something you consider useful, I'm open to create a PR

**Comment by patmmccann** [comment]
What is your goal, why do you want to vary the timeout per bidder?  If certain bidders are rarely bidding or frequently exceeding a timeout you think is appropriate, you may want to make them a `secondaryBidder`

**Comment by fasenderos** [comment]
Hi @patmmccann here is my situation.
I have 3 adapters and a global timeout of 4 seconds. Sometimes one of the adapter is slow to respont. So if the 1st and 2nd bidder responds in 1 seconds but the 3rd bidder take more time (eg. 5 seconds), the auction goes in timeout.

If I can set a specific timeout (e.g. 3 seconds for each bidder) he auction would be made between the two fastest adapters.
Hope that make sense, let me know if I can obtain the same result in a different manner.

**Comment by fasenderos** [comment]
> If certain bidders are rarely bidding or frequently exceeding a timeout you think is appropriate, you may want to make them a secondaryBidder

I misread your first suggestions, maybe the `secondaryBidder` is the solution
