### ISSUE TITLE
Ad rendered tracking - BID_WON event vs renderAd 

### ISSUE THREAD

**Issue by eladzaa** [prebid/Prebid.js#1003]
## Type of issue
question

## Description
Hello,

In case BID_WON event fired but the ad didn't finish the rendering process in renderAd function, is the BID_WON event still represent an impression? 

How to track rendered ads and rendering failure?

**Comment by ialex** [comment]
The BID_WON event is internal to Prebid has nothing to do witht the Ad Server (DFP) if it is not rendered it will not be recorded by the ad server, you should be able to check on reports the unfilled impressions filtered by the kvps prebid uses.

**Comment by mkendall07** [comment]
@eladzaa 
Currently we don't have a way to track if a ad render failed. DFP will count that impression even if the render fails as well, so BID_WON event should match DFP reporting (roughly speaking).
