### ISSUE TITLE
Industry shifting to "Ad Viewability" - Prebid Ad render loads ads with iFrame is mostly not supported.

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#1005]
## Type of issue
Bug/Feature 

## Description
So many buyers desks are switching their buying preferences to be based on ad viewability only. 
This uses a pixel/s that measure viability based on a heat map script that measures how long the user viewed the ad and if he viewed the entire ad. 

From what i'v been reading and asking around some/most of these viewability checks will not work when loaded from an iframe unless its from the  friendly iFrames of SafeFrames. 

Besides having to use safeframes do you think its a good idea to add an option to prebid to set adrender function to drop the payload within a <div> and not an iframe?

**Comment by terrapop** [comment]
We disabled "Serve into a SafeFrame" for the prebid ads in DFP. Is this wrong?

**Comment by mkendall07** [comment]
@mercuryyy 
We don't use an iframe if the ad loads the contents and not the URL. We can consider adding a suggestion to prebid 1.0 about using ad payloads instead of URLs but I think it's best to leave the option open.

**Comment by mercuryyy** [comment]
Thanks Matt, i just actually realized that if we dont use safeframe regardless if prebid will drop the ad in a div dfp will render it inside its iframe so view ability wont work the same .

The other way to go at it is to render the ad outside dfp and then send the dfp iframe a pixel for tracking so we see the impressions in dfp but we render the ad outside of dfp's iframe.

**Comment by mkendall07** [comment]
Closing this out because I don't think it's actionable.
