### ISSUE TITLE
Undefined uuid on video render

### ISSUE THREAD

**Issue by Prebid-Vertoz** [prebid/Prebid.js#10075]
## Type of issue
Getting hb_uuid=undefined in instream video

## Description
As per the prebid docs we have used the appnexus cache url but we are getting hb_uuid=undefined

Please find the attached screenshot
![prebid_uuid](https://github.com/prebid/Prebid.js/assets/23209608/a90938ac-992e-4ab7-8387-e8b906029aa1)

**Comment by patmmccann** [comment]
Hi,
Please provide a test page reproducing the behavior. Generally, this works for everyone using prebid cache for video so we can't help without instructions to reproduce

**Comment by bweiss-freestar** [comment]
@Prebid-Vertoz can you confirm if you're using the following VAST tag in the creative tag in GAM under the AppNexus line items? 

`https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_uuid%% 
`
It requires the pattern matching macro. 

![Image](https://github.com/prebid/Prebid.js/assets/66563356/095f40c0-88fd-41fc-9ee5-d5a96c2ab0f7)

**Comment by Prebid-Vertoz** [comment]
> Hi, Please provide a test page reproducing the behavior. Generally, this works for everyone using prebid cache for video so we can't help without instructions to reproduce

Below is the test page URL

https://textfeed.howgeneric.com/Beta/pbjs_video.html

**Comment by Prebid-Vertoz** [comment]
> @Prebid-Vertoz can you confirm if you're using the following VAST tag in the creative tag in GAM under the AppNexus line items?
> 
> `https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_uuid%% ` It requires the pattern matching macro.
> 
> ![Image](https://user-images.githubusercontent.com/66563356/244442729-095f40c0-88fd-41fc-9ee5-d5a96c2ab0f7.png)

Yes, we are using same cache creative url

**Comment by Prebid-Vertoz** [comment]
> > Hi, Please provide a test page reproducing the behavior. Generally, this works for everyone using prebid cache for video so we can't help without instructions to reproduce
> 
> Below is the test page URL
> 
> https://textfeed.howgeneric.com/Beta/pbjs_video.html

Any update?

**Comment by patmmccann** [comment]
Closing as stale

**Comment by Prebid-Vertoz** [comment]
Hello @dgirardi,
We apologize for the delayed reply. We done the changes as per above mentioned comments but still we are getting **hb_uuid=undefined**.Please provide your inputs.
Below is the test page URL:

https://textfeed.howgeneric.com/Beta/pbjs_video.html

**Comment by Prebid-Vertoz** [comment]
> @Prebid-Vertoz that page is now showing a 500 error for me.

@dgirardi 
Can please you check it once again.If its again showing 500 error please share us screenshot.

**Comment by dgirardi** [comment]
Currently the issue is that the bid returned by the incrementX 
 adapter does not specify a `mediaType`, so it defaults to 'banner' and does not go through the logic that attaches video-specific parameters like cache IDs.

**Comment by Prebid-Vertoz** [comment]
Thanks for the update we will make the changes and check

**Comment by Prebid-Vertoz** [comment]
> > Currently the issue is that the bid returned by the incrementX adapter does not specify a `mediaType`, so it defaults to 'banner' and does not go through the logic that attaches video-specific parameters like cache IDs.
> 
> Hello @dgirardi, As per our previous conversation,now **mediatype** issue has been fixed in our Adapter (IncrementX) but still showing **uuid** is undefined.Please share your suggestion if anything is missing from our end.

Hello @dgirardi Any update?

**Comment by patmmccann** [comment]
Closing as stale
