### ISSUE TITLE
pbjs.renderAd not called on IE9 & 10 mode

### ISSUE THREAD

**Issue by bboigienman** [prebid/Prebid.js#1008]
## Type of issue
Bug

## Description
On IE11 under IE9 or IE10 mode, pbjs.renderAd is never called (I enabled pbjs_debug=true), it stops at "MESSAGE: Prebid auction cleared".
With IE11 native mode, it's working.

I tested without Prebid integrated, and it's working correctly with IE9 & 10 mode.

## Platform details
Prebid 0.18 with IndexExchange, AOL & Sovrn adapters.
Windows 10 Pro 64-bit, IE11.576.14393.0

**Comment by matthewlane** [comment]
Do you have any stats about pbjs.renderAd getting called or not on other browsers you have tested?

When you test without Prebid integrated, how are you measuring that it's working correctly?

**Comment by rachelrj** [comment]
Hello, what is Prebid integrated?

Is pbj.renderAd on Prebid v18+ working on native IE9 and native IE10?

**Comment by mkendall07** [comment]
@bboigienman @rachelrj 
`pbjs.renderAd()` appears to be working correctly for us in testing. Can you provide any more details with the issue you are seeing?

**Comment by mkendall07** [comment]
if you can provide a URL that would also help.

**Comment by rachelrj** [comment]
@mkendall07 

I am not seeing a problem either. I was trying to ask whether this was an actual issue.

No concerns from me. Sorry for the confusion.

**Comment by mkendall07** [comment]
closing as there hasn't been any other updates. Thanks

**Comment by bboigienman** [comment]
@mkendall07 we've retested on different machines and it's working.
