### ISSUE TITLE
Proper Way to Configure Analytics Adapter with Custom Endpoint

### ISSUE THREAD

**Issue by GLStephen** [prebid/Prebid.js#1009]
## Type of issue
Question on Best Practice

## Description
We are creating an analytics adapter and need to make the endpoint configurable for staging, testing, etc.

What is the best way to handle this? Currently, the CONFIG object is only in the enable event and is not passed in the subsequent track calls. I see a few ways to make this work, but was curious about recommended ways from the Prebid team.

**Comment by mkendall07** [comment]
I would just default the endpoint to your Prod URL, and pass in an override in the config object and use that if it exists.

**Comment by GLStephen** [comment]
@mkendall07 The issue I was encountering was that config is only available on the enable call, and then it only fires on the first track event which was queued prior to enable, but it seems like there may *not* be an event that fired before enable always so a race condition occurs.

**Comment by mkendall07** [comment]
sounds like a bug, we should always call enable first.

**Comment by GLStephen** [comment]
To clarify the enable event does fire, but the enable event itself has logic to run enqueued analytics events. The events are queued prior. However the args variable in the track method only has the config data on the first call. This introduces what seems to be brittle logic relying on the first analytics event to have the config array for the analytics provider and to then set some sort of global variable that later track calls have access to because the config object is not there in later (not engueud calls). This could mean at least in theory that if an event were never enquired the config would never be on the args. I don't know own for sure that could happen but nothing seems to ensure it won't. Forgive me if I'm not making sense or maybe I'm missing a way to make that config data available in subsequent track events.

**Comment by mkendall07** [comment]
@GLStephen 
Feel free to submit a PR, I haven't had a chance to dig into this issue.
