### ISSUE TITLE
FLEDGE/PAAPI module's adUnit level config requirement needs lots of changes on publisher side

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#10105]
## Type of issue
Fledge Module requires Module level config, bidder level config and slot level config too.
Refer: https://github.com/prebid/Prebid.js/blob/master/modules/fledgeForGpt.md 

Module level and bidder level config can be easily applied with less effort.
But publishers will need to make changes for each slot to enable the Fledge/PAAPI on each slot.

Example to enable the Fledge on slot
```
pbjs.addAdUnits({
    code: "my-adunit-div",
    // other config here
    ortb2Imp: {
        ext: {
            ae: 1
        }
    }
});
```

The documentation says, `Absence indicates this is not FLEDGE eligible`. 

My suggestion is to set the default value of `ae` flag to `1` at the slot level internally through the Fledge module, we should not set the flag to `1` if the user has explicitly set it `0`. 

This will avoid the publisher's efforts for modifying all slot-level configs on the setup.
The overall fledge flow will execute only if the module is included and enabled (module and bidder config) by the publisher.

**Comment by patmmccann** [comment]
Perhaps we could consolidate further? eg

`pbjs.que.push(function() {
  pbjs.setConfig({
    fledgeForGpt: {
      enabled: true,
      bidders: ['a','b'],
      enableAllSlots: true
    }
  });
});`

**Comment by pm-harshad-mane** [comment]
yes @patmmccann, this approach also works.

**Comment by patmmccann** [comment]
@pm-harshad-mane committee agrees this is ready for dev; Pubmatic (or anyone) is welcome to pick it up or prebid could pick it up after a bunch on consent related work in the queue. Let us know if you guys begin development

**Comment by laurb9** [comment]
I (openx) can take a stab at implementing this

**Comment by laurb9** [comment]
To confirm, the expected effect of the config statement above is: _only bidders "a" and "b" are enabled for FLEDGE, all adUnits/imps set imp.ext.ae=1 for these bidders if not explicitly set individually_ ?

Should we take the absence of `bidders` property in `fledgeForGpt` to mean _all bidders_ ?
What about `bidders: []`, could be _no bidders_ or _all bidders_ ? It can be overridden per-bidder with `setBidderConfig`.
