### ISSUE TITLE
Rebranding of an adapter, what should be done?

### ISSUE THREAD

**Issue by arago-dsp** [prebid/Prebid.js#10114]
## Type of issue
Question

## Description
Dear prebid.js team, please note that `mediakeys-platform` is rebranding the name of its platform to `arago-dsp`.

In the process of this name change, what should we plan to update on our [current prebid.js adapter](https://docs.prebid.org/dev-docs/bidders/mediakeys.html)?

Do you have a todo list for this kind of change?

Best regards.

**Comment by patmmccann** [comment]
Easiest thing to do is add the new name as an alias to your adapter and do a documentation pr
