### ISSUE TITLE
DFP Native ads in prebid

### ISSUE THREAD

**Issue by danyelb** [prebid/Prebid.js#1012]
## Type of issue
Question

## Description
Can I use prebid with DFP fluid sizes? with Native content ads? Any ideas how to setup them?

Thanks
Daniel

**Comment by mkendall07** [comment]
Currently we do not support Native in prebid, however, we are working on it and should have an update soon.

**Comment by danyelb** [comment]
Hello
do you know how soon? 1 month? 6 months?

thanks

**Comment by matthewlane** [comment]
Less than 6 months. I'll link to this issue when native support is merged
