### ISSUE TITLE
Feature request: continue auction on cmp error

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10121]
@fasenderos wrote on another issue: 
2) In case of an error generated by the ConsentModule, I need the auction to go ahead anyway. Currently this happens only in case of timeout here:
https://github.com/prebid/Prebid.js/blob/a35cda0896d9223ac2f0f6c90e201593b30851e3/modules/consentManagement.js#L213-L221
But the same thing could be done for the cmp callbacks as well, e.g. we can create a new configuration option and replace line 201 with `newConfigOption === true ? done(storeConsentData(undefined), false, msg, ...extraArgs) : done(null, true, msg, ...extraArgs)`
https://github.com/prebid/Prebid.js/blob/a35cda0896d9223ac2f0f6c90e201593b30851e3/modules/consentManagement.js#L198-L211

If you think these changes could be useful, I'm open to make a PR for that.

**Comment by patmmccann** [comment]
@fasenderos what kind of error other than cmp not found are you looking to recover from. Generally if you know gdpr applies but you can't find a cmp, what consent strings would you expect to pass to bidders?

**Comment by fasenderos** [comment]
> @fasenderos what kind of error other than cmp not found are you looking to recover from. Generally if you know gdpr applies but you can't find a cmp, what consent strings would you expect to pass to bidders?

We have some minor websites that didn't use one of the supported CMP, so in that case we need to continue auction without a consent strings

**Comment by patmmccann** [comment]
Why not conditionally configure consent management on cmp presense?

**Comment by patmmccann** [comment]
> We have some minor websites that didn't use one of the supported CMP, so in that case we need to continue auction without a consent strings

So you know the user in Europe but bc the website isnt running a cmp you want to proceed as if the user in consented? That exposes you to enormous legal risk, right?

**Comment by fasenderos** [comment]
> Why not conditionally configure consent management on cmp presense?

Because I have to duplicate part of your ConsentManagment (and keep it updated) to check if the cmp is supported and then run prebid.js that execute the same peace of code. I think that a config option is better.

**Comment by fasenderos** [comment]
> So you know the user in Europe but bc the website isnt running a cmp you want to proceed as if the user consented? That exposes you to enormous legal risk, right?

I might be wrong, but the legal risks exist for the site owner that load our script without a registered cmp, and for the vendors that process user's data without a consent string when the gdpr applies. 

We act as an intermediary and we always send the flag `gdprApplies: true` to our bidders w/o the consent string. Of course we encourage the publisher to add a registered CMP, but we cannot force them and we can still delivery ads from bidders that don't process user's data.

https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/TCF-Implementation-Guidelines.md#what-if-i-dont-receive-the-tc-string
> What if I don’t receive the TC string?
If transparency or consent information is unavailable in situations where TCF applies, you may not be able to process the user's data.

**Comment by fasenderos** [comment]
@patmmccann is the `allowAuctionWithoutConsent` intended for this purpose? Because I found this option in several example code, but I haven't found any documentation nor where it is used in the code

**Comment by patmmccann** [comment]
While the site owner may bear the lion's share of the risk, you have no legal bases for processing user data in the absence of consent. There's no such thing as just an intermediary in Europe any longer, youre a joint controller with the publisher

**Comment by patmmccann** [comment]
Regarding maintaining the CMP locator script, Dems the breaks. Most publisher widget companies have to do this and the IAB publishes it. I'm currently extremely skeptical of implementing an enormous legal landmine for our publishers to precariously step upon into the project. We'll raise in committee today and your welcome to join if you're a prebid.org member. 1 pm eastern us time.

**Comment by fasenderos** [comment]
> You can't pass GDPR enforcement to downstream vendors, while enjoying the benefits of user data yourself.

Please explain this sentence. Because I said the opposite, infact we pass the `gdprApplies` flag to `true` and if there is no consent string **no one may be able to process user's data**. In simple words without a consent string vendors can still bid with UNtargeted ADS, so why block the auction?

Anyway the same result can be obtained by setting a timeout of 1 ms and the auction may go ahead without a consent string, but I don't think this is better

**Comment by AramZS** [comment]
I think this needs to be a publisher choice on what action to take in this case. Should a CMP timeout stop everything or be considered an opt out? This isn't something a module should be able to configure for the site owner. But I think it is reasonable to ask publishers if they want to do this as an option. 

I also think that the assumption should be--once again, if the publisher chooses the option not as a default--that if there is no CMP response the user should be considered opted out to the maximum level and whatever action follows on a user opt out should occur. This doesn't preclude entities from bidding on opted out traffic as long as they follow the rules, and entities exist with an interest in that. It also means that all the normal actions that follow up on opted out traffic should happen if that is the publisher configuration choice.

**Comment by jdwieland8282** [comment]
I understand that you pass `gdprApplies:true` but it sounds like you also process the auction as consented:

```
We have some minor websites that didn't use one of the supported CMP, so in that case we need to continue auction without a consent strings
```
Perhaps I've misunderstood what you are actually doing? 

I understand that in the absence of a consent string, contextual auctions can proceed.

**Comment by fasenderos** [comment]
> What happens if you fallback to static consent indicating the user has not consented to anything? The auctions should proceed at this point, right?

@patmmccann I think that string `undefined` and string `indicating the user has not consented to anything` is exatly the same from the GDPR point of view. But if you think that it's better I can go with that. Did you have an example of this string and/or how to create it?

**Comment by patmmccann** [comment]
Nevermind, that doesnt work either https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/#:~:text=6.%20A%20Vendor%20must,Policies%20and/or%20Specifications.
 We can't manufacture fallback strings. 

and also, 

4. If a Vendor is unable to read or process the contents of a received Signal, the Vendor must assume that it does not have permission to store and/or access information on a device, or to process personal data for any Purpose and/or Special Purpose.

This includes purpose 2. Basically, if the cmp is failing, you don't even have legal bases for purpose 2, basic ads. If you don't want to follow these policies, it might be best to just fork the project.

**Comment by fasenderos** [comment]
> if the cmp is failing, you don't even have legal bases for purpose 2, basic ads.

Exactly, I totally agree with that. Without a consent string, or a full reject string, no one have legal bases even to Purpose 2, whitch say 

> **Use limited data to select advertising**.
> Advertising presented to you on this service can be based on limited data, such as the website or app you are using, your non-precise location, your device type or which content you are (or have been) interacting with (for example, to limit the number of times an ad is presented to you).

So why block the auction? The GDPR is not an Ad Blocker, is a block for vendor to **process** user's data and/or **access** user's device. Serving random ADS (without accessing user data, position, web site etc) don't violate these policies.

**Comment by patmmccann** [comment]
We're closing this out as won't do. CMP errors are not recoverable. Auctions should not occur, as every vendor in prebid does not even have purpose 2 legitimate interest successfully asserted when a cmp fails. OP has a straightforward workaround to not configure the module given their unusual legal interpretation.
