### ISSUE TITLE
Pass window to adapter?

### ISSUE THREAD

**Issue by philipwatson** [prebid/Prebid.js#1013]
## Type of issue
Feature request
## Description

Just wondering if we can pass the browser's window object as an optional parameter when creating an adapter. It would be nice to mock window in our tests and hence increase coverage. As we can't override window's built-in function/properties in a browser environment.

So I'm guessing this would be a one line change. It shouldn't break existing tests. Something like this in prebid.js:

```
$$PREBID_GLOBAL$$.registerBidAdapter = function (bidderAdaptor, bidderCode) {
  utils.logInfo('Invoking $$PREBID_GLOBAL$$.registerBidAdapter', arguments);
  try {
    adaptermanager.registerBidAdapter(bidderAdaptor(window), bidderCode);
  }
  catch (e) {
    utils.logError('Error registering bidder adapter : ' + e.message);
  }
};
```

Then in the adapter implementation we can optionally use the parameter. Going from this: 

```
module.exports = function () {
  return {
    callBids: function (params) {
      doStuff(window)
      ...
  }
}
```

to something like this:

```
module.exports = function (win) {
  return {
    callBids: function (params) {
      doStuff(win);
      ...
  }
}
```

**Comment by mkendall07** [comment]
Interesting. I think it's possible, but even if we don't change the signature right now, you can pass through it in your test and just do `win = win || window` for example.

**Comment by philipwatson** [comment]
Yeah cool... didn't think of that. Thank you.

**Comment by mkendall07** [comment]
cool. I'm gonna close this for now then.
