### ISSUE TITLE
Removing the margin set on the topmost iframe body

### ISSUE THREAD

**Issue by dashiad** [prebid/Prebid.js#10134]
## Type of issue

Question

## Description

We're testing some creatives, running prebid with just one adapter (appnexus), and no SSP. We see prebid creates an iframe inside the adunit div, but the body of that iframe has a margin, so scrollbars appear around the rendered creative.
Is there any way to configure prebid so some styling is applied to that iframe body?
## Test page

![scrollbars](https://github.com/prebid/Prebid.js/assets/1832203/c6c41b65-d89b-4e09-be49-e0585deb43d6)

**Comment by muuki88** [comment]
Are you using AppNexus ( Xandr, Microsoft Advertising) as your ad server?

AFAIK prebid does not apply any CSS to remove the user agent styles, which cause the 8px margin. There are projects like normalize.css that reset browser default styles. However you would need to add them yourself.

**Comment by dashiad** [comment]
We're not using an adserver in this test. We use Appnexus as the only adapter and serve the creative it bids for. There's no adserver call after receiving the bid.
That iframe is created with a fixed width and height, to match the size of the creative received. The inner iframe from appnexus is expecting the available space to be exactly the same, which is the space the creative is also expecting . 
In general, any iframe involved in serving an ad should make sure the page area it's reserving for an ad, it's available for the ad. So, adding the code required to remove any extra margin, padding or border , should be prebid code responsability, not the publisher. 
The inner iframe created by appnexus adds all the needed attributes not to interfere with the creative (while the "body" tag can be edited by us). The iframe created by prebid just sets "frameborder=0", which is insufficient.

I dont think normalize.css can help styling an inner iframe (without explicitly injecting it inside that iframe), and that'd be in the case the publisher can actually access that iframe (and prebid is not being fired from a third party inside an iframe where the publisher has no access). 
Still, we just cannot ask the publishers to implement all those hacks.

**Comment by muuki88** [comment]
Thanks for your detailed response 😃

> We're not using an adserver in this test. We use Appnexus as the only adapter and serve the creative it bids for. There's no adserver call after receiving the bid.

So you render it directly via `pbjs.renderAd`

> That iframe is created with a fixed width and height, to match the size of the creative received. The inner iframe from appnexus is expecting the available space to be exactly the same, which is the space the creative is also expecting .

That's correct.

> In general, any iframe involved in serving an ad should make sure the page area it's reserving for an ad, it's available for the ad. So, adding the code required to remove any extra margin, padding or border , should be prebid code responsability, not the publisher.

From my experience this is usually the ad servers job. Prebid is not an ad server, but a middle layer to perform auctions. 

The rendering part is up to the publisher. An ad server is the most common option, but you can render manually ( what you do ). In that case you have to deal with the nasty details of browser styles.

> The inner iframe created by appnexus adds all the needed attributes not to interfere with the creative (while the "body" tag can be edited by us). The iframe created by prebid just sets "frameborder=0", which is insufficient.

What the rendered creative does is it's own thing, unfortunately.

> I dont think normalize.css can help styling an inner iframe (without explicitly injecting it inside that iframe), and that'd be in the case the publisher can actually access that iframe (and prebid is not being fired from a third party inside an iframe where the publisher has no access).
Still, we just cannot ask the publishers to implement all those hacks.

Yes, you are right. You need to add the CSS inside the rendered iframe. This is actually not that tricky. And if you force the rendering logic up the publisher anyways, then this is a few lines code more.

**Comment by dashiad** [comment]
> From my experience this is usually the ad servers job. Prebid is not an ad server, but a middle layer to perform auctions.
Prebid offers a way to render an ad. And as a middle layer, it should not have side effects. As soon as prebid generates any html, it's intervening in the ad rendering. That margin means that prebid is using space in the page. There are rendered pixels generated by prebid.So, it's breaking that premise of being just a middle layer. 

>The rendering part is up to the publisher.
It's not the publisher who is creating this iframe, it's prebid. If prebid generates any kind of html, instead just serving what it has received from the adserver, it's taking responsability in the rendering of the creative, and should generate html that doesnt interfere with the ad rendering. If the rendering part is up to the publisher, being prebid a publisher tool, it should either generate correct code, or allow the publisher to have control over the code it generates, ie, have options to either disable that iframe completely, or to style it. 

> What the rendered creative does is it's own thing, unfortunately.
The rendered creative, and the code returned by the adserver, it's correct. It's the iframe prebid unconditionally generates, the one that it's producing a problem.

>You need to add the CSS inside the rendered iframe. This is actually not that tricky. And if you force the rendering logic up the publisher anyways, then this is a few lines code more.
It's not about "how many lines of hacky code are needed to solve the issue". It's about prebid being a transparent layer or not. Prebid generates html code, which is not under control of the publisher, or the adserver, and takes page space.
 So, it's intervening in the ad rendering, even if it's not an adserver, not acting just as a middle layer, so it should make sure that the code it generates doesnt break the ad. 
I cant see a simpler (and more correct) way of avoiding this problem, that adding the styling in prebid, or, at least, giving the publisher the option to style the iframe (even if i dont see many scenarios where that spurious, undocumented margin would be ever needed)

**Comment by muuki88** [comment]
Thanks again for the detailed response. Disclaimer, I'm speaking as an ad tech vendor, using prebid since version 0.x, but not on behalf of prebid.js.

I understand your point. However this is, from my experience, an edge case.

* Adding 1-2kb of CSS which isn't used by 99% of users is just dead weight
* IIRC prebid does not create an iframe if already in an iframe
* `renderAd` is one of the first APIs and has been mostly refactored into the prebid universal creative, which supports a variety of use cases

The iframe created by prebid is an interference in rendering, but it's for the purpose of saving publishers from badly written creatives. Back in the days `document.write` was commonly used. If you do not put the creative inside an iframe, it'll thrash your entire page.

The margin for this iframe comes from the browser ( user agent styles ). Prebid is, IMHO, creating the iframe only for safety reasons.

Out of curiosity. What are you expecting your publishers to put on the page by themselves?

**Comment by dashiad** [comment]
I understand the reason why prebid creates an iframe there. But that doesnt mean/need/justify  breaking ads in the process. Iframes generated by adservers are also there for safety reasons, and work perfectly fine displaying the creative.

I dont know if it's an edge case or not (i see many options in prebid that may also be considered "edge"), but it requires less than 50 bytes of new code. 
I can understand a "feature request" to be considered "edge", and not supported. But something that it's already supported, cannot be buggy under the premise of being an edge case, or requiring X bytes more. What is wasteful, is having the functionality there, but breaking ads because it's missing 50 bytes of code (fix margin and padding to 0).

I expect my publishers to write code based in documented behaviour, and try my best to avoid hacky code (there's already enough of it in creative land). 
But, again, it's a matter of responsabilities and feature scope. As you say, that iframe is there to protect the web page from legacy creatives. This is something the publisher could do. And this is something most (all?) adservers already do. 
If prebid chooses to unconditionally add an iframe, it cannot pass the responsability of actually making it work to the publisher. It's accepting the responsability of helping against ads that may break the page, but rejecting the responsability (and at the cost)  of making the ad display correctly.

**Comment by muuki88** [comment]
> I can understand a "feature request" to be considered "edge", and not supported. But something that it's already supported, cannot be buggy under the premise of being an edge case, or requiring X bytes more. What is wasteful, is having the functionality there, but breaking ads because it's missing 50 bytes of code (fix margin and padding to 0).

It's wasteful due to backwards compatibility. That's definitely an issue. The thing is that this is broken since the beginning and no body noticed, reported a bug or ( what I assume ) never encountered it as Prebid creates the iframe conditionally: if not already rendered in an iframe.

> I expect my publishers to write code based in documented behaviour, and try my best to avoid hacky code (there's already enough of it in creative land).

Can you share the specific documentation? 😊 maybe we should extend with the implications of custom rendering implementations.

> But, again, it's a matter of responsabilities and feature scope. As you say, that iframe is there to protect the web page from legacy creatives. This is something the publisher could do. And this is something most (all?) adservers already do.
If prebid chooses to unconditionally add an iframe, it cannot pass the responsability of actually making it work to the publisher. It's accepting the responsability of helping against ads that may break the page, but rejecting the responsability (and at the cost) of making the ad display correctly.

As mentioned before, the iframe is created only when rendered directly. Implementing a custom rendering logic, which is the case here IMHO, involves more work. 

I fully agree with your point that it should be as easy for publishers as possible. What I don't see is, that the target audience are those publishers with no tech resources.

> I dont know if it's an edge case or not (i see many options in prebid that may also be considered "edge"), but it requires less than 50 bytes of new code.

We do use this feature in our ad tech stack as well and add the styles we think are necessary.

**Comment by dashiad** [comment]
>The thing is that this is broken since the beginning

Ok, we can agree on that. 
"Running prebid without an adserver", is the title of a documentation page ([https://docs.prebid.org/dev-docs/examples/no-adserver.html](url). So, at least, it's not "my" edge case, but a supposedly supported scenario.

>Can you share the specific documentation? 😊 maybe we should extend with the implications of custom rendering implementations.

That's prebid documentation. The previous link, contains example code.I dont see in that page, or in the renderAd docs, the requirement for "custom rendering", code to fix the inner iframe, or the requirement to run that code inside an existing iframe, so prebid doesnt add its own. If any of those things is a requirement for this feature to work, it's not documented, and that's what i mean with using documented code. 
But normally, if a library publishes an example code that it's supposed to do one thing, but when run, it has problems, a bug is notified. 

>We do use this feature in our ad tech stack as well and add the styles we think are necessary.

And, when some styles are missing, things are broken, as stated previously.

> What I don't see is, that the target audience are those publishers with no tech resources.

The target should be having working code. But, accepting that view, if a publisher has enough tech resorces, and given this problem, what would be the best way to fix it?

* Try to hack code to wait for the ad to render, then inject css code in the iframe (Bear in mind, that as soon as the ad is inserted in the iframe, scrollbars appear. Depending on the creative, and the time when events are fired,that will create a blink).
* Fork the repo, and add the css code where prebid creates that iframe (ie, fix the bug...and, no, i dont see any scenario where creating the iframe with a margin would break anything else...).

Well, ok, i think i had to notify about this problem. If you dont (want) to see it that way, that's ok, i'll hack something to make it work.

**Comment by muuki88** [comment]
Thanks for your patience with me 😅 I don't have any laptop available and try to find the pieces in my mobile phone.

The documentation is a community effort as is Prebid. If examples are lacking crucial information I'm more than happy to merge documentation improvements.😃

And it's an example. It states at the very beginning "This example demonstrates running an auction and rendering without an ad server." It's demonstrating how it could be done using an iframe. And it demonstrates how it can work. It's not meant to copy and paste this to production. I agree that making an example easy to read, while also covering various pitfalls, is not trivial.

Regarding what needs to be done ( may contain errors as I write this on my phone)

```javascript
// Copied from the docs page
let iframe = document.createElement('iframe');
	      iframe.frameBorder = '0';
	      div.appendChild(iframe);
	      var iframeDoc = iframe.contentWindow.document;
	      pbjs.renderAd(iframeDoc, winningBid.adId);

// Now the ad is rendered and you can insert stuff into the iframe as you like

const styles = iframeDoc.createElement('style');
IframeDoc.head.appendChild(styles);
```

That's IMHO not hacky, but an extension of this implementation.

As mentioned, I don't make any calls if styles should be added conditionally when rendered in an iframe. However I'm more than happy to merge improvements to the documentation 😊

**Comment by muuki88** [comment]
Finally able to update it
