### ISSUE TITLE
Prebid 8 adapter modules : changes in buildRequests

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/Prebid.js#10133]
## Type of issue
Bug

## Description
Running a bid adapter in prebid 8 seem to have a breaking change which I haven't found informations about: objects sent in the buildRequests function no longer are the same than with previous version and some of their attributes are not accessible. For example in the `validBidRequests[]` object, while I can iterate it and find values for the `bidder` or `bidId` attributes, the `auctionId` and `transactionId` attributes are null. Same is for the `bidderRequest` object.

I don't really get why these objects are no longer shared ?

### Actual results
Attached file is what I get when `buildRequests` is called
![buildRequestsObjects](https://github.com/prebid/Prebid.js/assets/63732822/19818368-c9f0-408e-8c97-3bdbcf7e9222)

**Comment by patmmccann** [comment]
Please see #9781 

Sharing these values with bidders is now opt in
