### ISSUE TITLE
Fledge for gpt module: accept auction config from rtd

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10140]
## Type of issue
Feature request

## Description
We may anticipate entities wanting to submit auction config and not bid in the contextual auction ever; are these best as rtd or as bidders?

**Comment by JoelPM** [comment]
I believe the current module supports participating in the Fledge auction w/o submitting a contextual bid. Even if it didn't/doesn't, I think it would be a little weird to have it in the RTD module.

**Comment by patmmccann** [comment]
If a DMP or fledge-only bidder wants to exist, they should submit a bid module as well as an rtd module or just the bid module and we won't require an endpoint call out for the contextual auction somehow.
