### ISSUE TITLE
Bid Adapters, GPID ,and PBAdSlot

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#10187]
## Type of issue
using incorrect data

## Description
A number of bid adapters are setting the 'GPID' with the value of 'pbAdSlot'. This isn't correct. The [background material on this](https://docs.prebid.org/features/pbAdSlot.html) highlights that pbAdSlot pre-dated the TradeDesk's efforts to standardize the GPID.

It's true that the values may be the same, but publishers currently have to set both because the following bid adapters use them interchangeably.

Prebid would like to see all of these bid adapters change their logic so that GPID is set first from GPID, then from pbadslot as a backup. The plan is to eventually drop pbAdSlot entirely.

i.e. instead of

```javascript
  let gpid = deepAccess(bid, 'ortb2Imp.ext.data.pbadslot');
```

The adapters should do something like
``` javascript
   let gpid = deepAccess(bid, 'ortb2Imp.ext.gpid') || deepAccess(bid, 'ortb2Imp.ext.data.pbadslot');
```

## Bidders
- [x] appnexus
- [x] cadentApertureMX
- [ ] colossusssp
- [ ] goldbach
- [x] grid
- [x] gumgum
- [x] kueezRtb
- [ ] mediafuse
- [x] minutemediaplus
- [x] onetag
- [ ] pixfuture
- [ ] richaudience
- [x] sharethrough
- [x] smartadserver
- [x] sonobi
- [x] vidazoo
- [ ] winr
- [x] yieldmo

Separately - 
- [ ] luponmedia is referring to fpd.context.pbAdSlot. fpd.context has been discontinued.

**Comment by lcorrigall** [comment]
PMC: in agreement that we need to move away from pbAdslot. We'll start with outreach to these bidders to make the change.

**Comment by lcorrigall** [comment]
Re-check the list to verify who needs to be contacted.

**Comment by patmmccann** [comment]
'ortb2Imp.ext.gpid' should be honored as some publishers might be configuring it directly according to the community extension

**Comment by fliccione** [comment]
Hello, as Onetag within the "9.0 fixes" Excel sheet, this issue has been marked as a fix to be implemented for version 9 of Prebid.js. However, the logic indicated above is already present within our adapter:

`this['gpid'] = deepAccess(bidRequest, 'ortb2Imp.ext.gpid') || deepAccess(bidRequest, 'ortb2Imp.ext.data.pbadslot');`

Could you confirm that no further interventions are necessary? Thank you.

**Comment by patmmccann** [comment]
I completed all remaining in #11660 

None of these had the concern they were getting them both and treating them independently.
