### ISSUE TITLE
Add the ability to clear cached bids that have expired

### ISSUE THREAD

**Issue by lcorrigall** [prebid/Prebid.js#10189]
## Type of issue
Enhancement

## Description
If `useBidCache` is enabled, Prebid.js will cache all bids and never releases them. On SPAs or other long lived pages that refresh ads this can contribute to increased memory usage. Prebid.js should have the ability to remove cached bids that are past their TTL. There are two options:

### Function Call
Provide a function like `clearExpiredBids` that publishers could call in order to remove all bids past their TTL. This would be simpler to implement but require publishers to to call this on their sites.

### Automatically
Prebid.js will remove bids past their TTL at some (TBD) periodic time.

## Other information
[useBidCache documentation](https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html#setConfig-Use-Bid-Cache)
[https://docs.prebid.org/dev-docs/faq.html#does-prebidjs-cache-bids](Prebld.js Bid Caching FAQ)

**Comment by patmmccann** [comment]
One strategy discussed it a publisher can say at some point 'I dont plan to enableAnalytics'; at which point the event history preserved for this purpose can be released.

**Comment by patmmccann** [comment]
Another suggestion: flush certain event types, not all analytics events
