### ISSUE TITLE
Create PR to version 7.x.x

### ISSUE THREAD

**Issue by norman1565** [prebid/Prebid.js#10193]
## Type of issue
Question

## Description
Hello. Is it still possible to create a pull request to version 7.x.x with my latest changes in adapter?
Since version 8.x.x was released there are couple of new things which can be handle, but I'm wondering if I could just create updates on version before version 8.x.x. If so, should I create PR not to master?

**Comment by patmmccann** [comment]
Yes use branch legacy-7. 54.x
