### ISSUE TITLE
Prebid 9: deprecation warning on pbadslot

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10239]
following #10187 , pbadslot is simply redundant; let's drop it in Prebid 9

**Comment by lcorrigall** [comment]
PMC: We will communicate to the community to stop using pbadslot as it is deprecated, and it will be removed in a later version of Prebid.js.

**Comment by lcorrigall** [comment]
Suggestion: change the default to use the gpid logic for populating pbadslot and gpid.
