### ISSUE TITLE
GPP 1.1 CMP Cancels all auctions, do not fail if tcfapi also exists and gdpr applies

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10245]
Closely related to #9483 ; however, the issue here is a GPP 1.1 CMP cancels all auctions following the logic here https://github.com/prebid/Prebid.js/blob/0ae65f962d0841e38ef9f0c6eb1193b8dc6cfbeb/modules/consentManagementGpp.js#L203

The feature request is: while #9483 is being developed, if a 1.1 CMP is detected,  do not fail when gdpr applies if the __tcfapi is also available.  Please commit this feature to both legacy and 7.54.x. If #9483 is done, this becomes moot and this logic should be deleted from 8.x (but not legacy). 

Test page and screenshot: https://www.derwesten.de/?pbjs_debug=true

![image](https://github.com/prebid/Prebid.js/assets/1683175/5b090f6d-786c-4a8a-8df0-2994cb30c097)

User is aware they could choose not to configure gpp module when they have a gpp 1.1 cmp, but some users may experience a CMP upgrade without expecting it, and we're hoping they don't suddenly break.

**Comment by dgirardi** [comment]
> if a 1.1 CMP is detected, do not fail when gdpr applies if the __tcfapi is also available

How about not failing if CMP version is not 1.0? I can't make sense of the gdpr condition.
