### ISSUE TITLE
Prebid version 8 broke the floors module

### ISSUE THREAD

**Issue by alinador** [prebid/Prebid.js#10255]
## Type of issue
From prebid version 8, the floors price module no longer works.

## Description
In prebid ver 8, the code is trying to find the floor price by AuctionId, but since AuctionId is undefined, it cannot do so. Additionally, the request structure has changed and proxy objects have been added that prevent getting the auctionId.

![image](https://github.com/prebid/Prebid.js/assets/932563/551e768d-2d1c-48c7-aa84-52bb0910491e)

o.auctionId is undefined in the code
![image](https://github.com/prebid/Prebid.js/assets/932563/b071f777-7f7b-4e44-a29d-83120180e8a1)

but when we use debugger to open the proxy object, the auctionId appears to be valid 
![image](https://github.com/prebid/Prebid.js/assets/932563/171cc04a-5fb5-41e6-9e21-67866ee6c6be)

## Steps to reproduce
Using floor price module with prebid ver >=8

### Expected results
Floor prices should be sent to bidders

### Actual results
There is no floor price sent to bidders

## Platform details
Prebid ver >=8

**Comment by dgirardi** [comment]
Thank you for the report! The proxies were introduced as part of the effort to [require opt-in for transaction identifiers](https://docs.prebid.org/dev-docs/pb8-notes.html#transaction-identifiers-are-now-reliable-and-opt-in). The intent is to proxy only within the scope of bid adapters, but I missed that `.getFloor` calls outside of it.

Fix is in https://github.com/prebid/Prebid.js/pull/10257; if it's an option for you, you could also work around the issue by opting in (`pbjs.setConfig({enableTIDs: true})`).
