### ISSUE TITLE
bidRequestScheduling.html is not hitting ix adapter

### ISSUE THREAD

**Issue by tkrishnaviant** [prebid/Prebid.js#10253]
## Type of issue
Bug

## Description
bidRequestScheduling.html is not hitting ix adapter for casalemedia.com.It is Not Hitting this URL 'https://htlb.casalemedia.com/openrtb/pbjs';

## Steps to reproduce
Run gulp serve-fast
Open in Browser link
http://localhost:9999/integrationExamples/videoModule/videojs/bidRequestScheduling.html
Open Developer tools to see the following network requests

https://dsum.casalemedia.com/pbusermatch?origin=prebid&site_id=0&p=1&i=0&gdpr=0&gdpr_consent=&us_privacy=
it is not loading advertisement for casalemedia

**Comment by spormeon** [comment]
its using debugging to "mock" the bid, not make a "real" bid:
![bidRequestScheduling_html_—_Prebid_js](https://github.com/prebid/Prebid.js/assets/8503167/2ea265d5-39fb-44b2-8210-313fac561d2f)
