### ISSUE TITLE
sharethrough uses document.body before it exists

### ISSUE THREAD

**Issue by kitwestneat** [prebid/Prebid.js#1025]
## Type of issue
bug

## Description
We load prebid in the document head section. Occasionally it can happen that prebid runs before document.body is created. The sharethrough adapter, however, uses document.body to load an iframe without checking if it actually exists.

## Steps to reproduce
Load prebid in the <head> section and request bids with sharethrough, do something time consuming in head.

### Expected results
sharethrough waits for document.body to exist before attempting to add an iframe

### Actual results
sharethrough tries to use document.body and throws an error

## Platform details
Prebid commit 3e50de14842c1fa7ff1e7fa5f74d04ae7b9e12ff, chrome browser

**Comment by rizhang** [comment]
#1042 should fix this issue as well, since the adapter will be using ajax to make requests instead of iframes

**Comment by matthewlane** [comment]
Closing as fixed by #1042
