### ISSUE TITLE
Rename GDPR modules (GDPR Enforcement, & Consent Management - GDPR)

### ISSUE THREAD

**Issue by jdwieland8282** [prebid/Prebid.js#10251]
## Type of issue
The Identity PMC would like to ensure that publishers have a clear understanding of what our privacy, regulatory modules do, as well as a clearer understanding of what Bid adapters support prebids enforcement modules. To that end we would like the following modules renamed:

```GDPR Enforcement --> TCF Enforcement```
```Consent Management --> TCF activity support```

We understand that renaming files is a breaking change and should wait until 9.0.  

Once renamed please update http://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders such that the 59 bid adapters that do not have a GVL id are denoted as "not" supporting TCF (FKA GDPR)

**Comment by dgirardi** [comment]
> GDPR Enforcement --> TCF Enforcement

for GPP we decided "enforcement" is a swear word and used "control" instead - should it be "TCF Control"?

> Consent Management --> TCF activity support

IMO this is less clear because `consentManagement` does not actually define any rules for what we are now calling [activities](https://docs.prebid.org/dev-docs/activity-controls.html). I would however like it renamed to `consentManagementTcf` to match the GPP and USP versions.

**Comment by jdwieland8282** [comment]
I don't think Control is descriptive enough, I think it will leave pubs with more questions about what it actually does. How about "TCF Support"?
```GDPR Enforcement --> TCF Support```
```Consent Management - GDPR --> TCF Consent Management ```

**Comment by dgirardi** [comment]
Arguably you don't need the enforcement module to support TCF - the consent management module is enough to pick up consent strings and pass them downstream. The enforcement module allows pubs to stop downstream requests altogether, or control what data they get, according to what's in the consent. 

Either way, I vote for consistency - if we are renaming modules, TCF and GPP should use the same pattern.

Do we want to also rename settings? For example, `consentManagement.gdpr` -> `consentManagement.tcf`. We'd still be left with a bunch of references to `gdpr` that should probably be `tcf` event payloads (which would also show up in analytics), but it would be a lot of work to go through all of those.

**Comment by jdwieland8282** [comment]
I'm good with those naming conventions @dgirardi

**Comment by patmmccann** [comment]
On discussion, we're not attempting to get tens of thousands of publishers to reconfigure their modules, we're simply renaming the modules and the associated files and documentation
