### ISSUE TITLE
Integration with nextjs

### ISSUE THREAD

**Issue by scvsoft-javierrotelli** [prebid/Prebid.js#10265]
## Type of issue
Prebid NPM package is not compatible with NextJS

## Description
Following example from ( https://www.npmjs.com/package/prebid.js ) by extending webpack config in next.config.js:

```
let path = require("path")

module.exports = {
  reactStrictMode: true,
  webpack: (config, { buildId, dev, isServer, defaultLoaders, nextRuntime, webpack }) => {

    config.module.rules.push({
      test: /.js$/,
      include: new RegExp(`\\${path.sep}prebid\\.js`),
      use: [
        {
          loader: "babel-loader",
          options: require("prebid.js/.babelrc.js"),
        },
      ],
    })

    return config
  },
}
```
after this while trying to import prebid.js facing this error:

```
import {getGlobal} from './prebidGlobal.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module

```
## Steps to reproduce
Create a new NextJS project
add `prebid.js` and include it in a page

## Test page
Demo repository here: https://github.com/scvsoft-javierrotelli/next-prebid-test

## Platform details
Tested with Next 12 and 13

## Other information
Reopening #9349

**Comment by dgirardi** [comment]
Thanks you for the repo, that's very helpful. Disclaimer - I am not at all familiar with next / react, and at first glance it looks like they're doing some rather advanced black magic - so this may not work for other reasons; but hopefully it helps.

Replace [this](https://github.com/scvsoft-javierrotelli/next-prebid-test/blob/9770d8a45dbbfc8dff85b9356c17650978aaaf26/pages/index.js#L5-L12
):

```
import pbjs from "prebid.js";
import "prebid.js/modules/rubiconBidAdapter"; // imported modules will register themselves automatically with prebid
import "prebid.js/modules/appnexusBidAdapter";

export default function Home() {
  useEffect(() => {
    pbjs.processQueue();
  }, []);
```


With this: 

```
export default function Home() {
  useEffect(() => {
    (async () => {
      const pbjs = (await import('prebid.js')).default;
      await import('prebid.js/modules/rubiconBidAdapter');
      await import('prebid.js/modules/appnexusBidAdapter');
      pbjs.processQueue();
    })();
  }, []);
```

It got rid of the errors for me, but I haven't tried to actually run an auction:

![image](https://github.com/prebid/Prebid.js/assets/10151381/fd552ae5-af83-4554-b3e8-fcacb8a57746)

let me know if you find more issues.

**Comment by patmmccann** [comment]
Closing as stale, please do let us know if this solved for you @scvsoft-javierrotelli
