### ISSUE TITLE
Feature request: pause auctions when CMP indicates that the user is reviewing their consent choices

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#10266]
## Type of issue
Feature req

## Description

The [GPP 1.1 spec spec](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/cmp-api_1.1/Core/CMP%20API%20Specification.md) recommends that, when a user starts interacting again with the CMP _after_ already having made their choice, 

> CMP is expecting changes, vendors should not use the data but wait and pause their processing.

Currently Prebid continues to use the consent it has, without pausing, until changes are actually made and a new consent string is available. 

This may apply to TCF as well.

**Comment by patmmccann** [comment]
if we discover this applies to tcf, lets handle independently

**Comment by patmmccann** [comment]
IF the cmp fires a not ready event, we should wait for new consent; the current consent is not considered valid.
