### ISSUE TITLE
User ID may use stale USP/GPP consent

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#10276]
## Type of issue
Bug

## Description

The user ID module has some logic to skip UID refresh when TCF consent data has not changed since the last retrieval:

https://github.com/prebid/Prebid.js/blob/c281fc7cb022be04092c4698c2ec5643925bb039/modules/userId/index.js#L829-L830

The logic does not look at GPP or USP - just TCF. Currently, prebid may continue to use user IDs that were retrieved using GPP/USP consent that was later invalidated.

**Comment by patmmccann** [comment]
solution may also fix https://github.com/prebid/Prebid.js/issues/10276
