### ISSUE TITLE
How to "Reload ads without a page refresh"

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#1028]
I understand that Google AdSense now allows to "Reload ads without a page refresh" as long as it is done with DFP and the refresh rate is greater than 30 seconds.

Ref: https://support.google.com/dfp_sb/answer/2694377?hl=en&visit_id=1-636241000930551038-468044932&rd=1

Can I also do this using prebid? If so, is there sample code?

I looked at http://prebid.org/dev-docs/examples/adunit-refresh.html but I do not see how I would specify the >30 second refresh rate.

**Comment by headerbidding** [comment]
I think I figured it out. 
I combine the prebid recommended code:

  var topSlot;
    var middleSlot;
       var bottomSlot;
    
    function refreshSlot(slot) {
        pbjs.que.push(function() {
         pbjs.requestBids({
           timeout: PREBID_TIMEOUT,
           adUnitCodes: [slot.getSlotElementId()],
           bidsBackHandler: function() {
             pbjs.setTargetingForGPTAsync([slot.getSlotElementId()]);
             googletag.pubads().refresh([slot]); 
           }
         });
        }); 
    }
    function refreshSlot1() {
        refreshSlot(topSlot);
    }
    function refreshSlot2() {
        refreshSlot(middleSlot);
    }
    function refreshSlot3() {
        refreshSlot(bottomSlot);
    }  

with the DFP recommended code:

 var topSlot = googletag.defineSlot('/1037380/300x250_prebid', [[300, 250], [250, 250]], 'div-gpt-ad-xxxxxxxxxxxxx-0').setTargeting("test", "refresh").addService(googletag.pubads());

        var middleSlot = googletag.defineSlot('/1037380/728x90_prebid', [[728, 90], [486, 60]], 'div-gpt-ad-xxxxxxxxxxxx-2').setTargeting("test", "refresh").addService(googletag.pubads());

        var bottomSlot = googletag.defineSlot('/1037380/300x600_prebid', [[300, 600], [300, 250], [160, 600]], 'div-gpt-ad-xxxxxxxxxxxxxxx-1').setTargeting("test", "refresh").addService(googletag.pubads());
....
   setInterval(function(){googletag.pubads().refresh([topSlot]);}, 62000);
   setInterval(function(){googletag.pubads().refresh([middleSlot]);}, 62000);
   setInterval(function(){googletag.pubads().refresh([bottomSlot]);}, 62000);
    });
</script>

**Comment by mkendall07** [comment]
yep it's up to the publisher to configure this.
