### ISSUE TITLE
[Event] NYC. Tech Talk about Prebid.js + Video, Tuesday March 7th.

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#1029]
## Type of issue
[Event]
Come listen to us talk about Prebid.js development and the latest addition of Prebid video support!
**Date:**
Tuesday March 7th.
**Time:**
6:00 PM - 8:00 PM
**Location:**
AppNexus, 28 West 23rd St.
4th Floor, New York,
NY, 11231

## Description
Registration is required: http://go.appnexus.com/TechTalks.html

### Expected results
Awesomeness. 

### Actual results
You'll have to find out. 

## Platform details
Offline.

**Comment by Boucher-David** [comment]
There going to be a video of this posted afterwards by chance?

**Comment by mkendall07** [comment]
Should be recorded yes.

**Comment by tedrand** [comment]
Would love to see that when its up!

**Comment by protonate** [comment]
Video of Tuesday's Prebid Tech Talk is up: https://www.youtube.com/watch?v=kSytwSUsV4o

**Comment by tedrand** [comment]
Great vid!
