### ISSUE TITLE
Adquery QID userId module generates multiple nested JSONs on every page refresh

### ISSUE THREAD

**Issue by vfedoseev** [prebid/Prebid.js#10324]
## Type of issue
Bug

## Description
While checking the bid requests coming to our SSP (VIS.X by YOC AG) we've noticed that the user id with the source 'adquery.io' could be the very long string with the multiple nested JSON objects.
Examples:
`{\"source\":\"adquery.io\",\"uids\":[{\"atype\":1,\"id\":\"%7B%22qid%22%3A%22%257B%2522qid%2522%253A%2522%25257B%252522qid%252522%25253A%252522%2525257B%25252522qid%25252522%2525253A%25252522%252525257B%2525252522qid%2525252522%252525253A%2525252522%25252525257B%252525252522qid%252525252522%25252525253A%252525252522%2525252525257B%25252525252522qid%25252525252522%2525252525253A%25252525252522%252525252525257B%2525252525252522qid%2525252525252522%252525252525253A%2525252525252522%25252525252525257B%252525252525252522qid%252525252525252522%25252525252525253A%252525252525252522%2525252525252525257B%25252525252525252522qid%25252525252525252522%2525252525252525253A%25252525252525252522%252525252525252525257B%2525252525252525252522qid%2525252525252525252522%252525252525252525253A%2525252525252525252522%25252525252525252525257B%252525252525252525252522qid%252525252525252525252522%25252525252525252525253A%252525252525252525252522%2525252525252525252525257B%.....%25252525252522%2525252525257D%252525252522%25252525257D%2525252522%252525257D%25252522%2525257D%252522%25257D%2522%257D%22%7D\"}`

If we decode the string it shows that the several objects with the key 'qid' just nested to each other. Example:
{"qid":"{"qid":"{"qid":"{"qid":"a73d8ebb08080df969b2"}"}"}"}

## Steps to reproduce
The issue could be reproducible on this example site: https://www.bankier.pl/wiadomosc/Janusz-Palikot-i-spolki-wniosek-o-upadlosc-i-o-ochrone-8590892.html

1) Open the site in incognito mode
2) In developer tools find the query https://bidder.adquery.io/prebid/qid
3) The JSON similar to this is served:
`{"qid":"a73d8ebb08080df969b2"}`
4) The same JSON (as encoded value) is saved to local storage:
![image](https://github.com/prebid/Prebid.js/assets/8183991/0e7fe83a-bbe0-466d-886a-ef5e505cdb47)
5) Refresh the page
6) The value in local storage is updated to another JSON (with +1 level):
![image](https://github.com/prebid/Prebid.js/assets/8183991/c147cd3c-5fab-4184-9f08-e7592a6b3ff6)
7) with every refresh the value saved in LS gets +1 level to the JSON object.

## Test page
https://www.bankier.pl/wiadomosc/Janusz-Palikot-i-spolki-wniosek-o-upadlosc-i-o-ochrone-8590892.html

### Expected results
The user Id value saved in LS (key=qid) and passed to the bidders (user.ext.eids, name='adquery.io') is always the same.

### Actual results
With every refresh the stored value becomes larger 

## Platform details
Prebid.js - 7.50.0
Integration via Prebid Server

## Other information
[]
UserId module:
(https://github.com/prebid/Prebid.js/blob/b42001167e0bd0bfa4ae93f522f521ceef365950/modules/adqueryIdSystem.js#L77)
I'll also tag @adquery in this issue.

If we should provide any other useful information, please just let us know.

Thank you in advance.

**Comment by ChrisHuie** [comment]
@vfedoseev does #10312 fix this issue as well

**Comment by vfedoseev** [comment]
Hi @ChrisHuie ,
Thank you for checking this issue.
I've read through the changes and on the first sight it seems that the issue with multiple wrappers of the same user id (qid) should be fixed.

We can also re-check it in live environment once the PR is approved, included in the new Prebid.js version and the publisher updated to this version.
