### ISSUE TITLE
Bug Stickyadstv Adaptor

### ISSUE THREAD

**Issue by Deimos01** [prebid/Prebid.js#1033]
## Type of issue
BUG

## Description
The Stickyadstv adaptor is not working in a simple integration

## Steps to reproduce
[http://www.themoneytizer.com/demo/prebid_sticky?pbjs_debug=true](http://www.themoneytizer.com/demo/prebid_sticky?pbjs_debug=true)

### Expected results
The video prebid integration code should return a response from the adcall.

### Actual results
Here the console error : "ERROR: adUnit video has 'mediaType' set to 'video' but contains a bidder that doesn't support video. No Prebid demand requests will be triggered for this adUnit."
## Platform details
Chrome v56.0.2924.87

**Comment by Deimos01** [comment]
Thank you for this quick answer @protonate . But how can i set different partners in the video adunit?
For example appnexusAst & StickyadsTV ? because i think i have to set mediaType: 'video' for appnexusAst, right ?

**Comment by mkendall07** [comment]
@Deimos01 
You need to setup separate adUnits for now. The formats are different though, appnexusAST with mediaType=video is an instream format and the StickyadsTV is a in banner video.
