### ISSUE TITLE
Consent Management: auction not cancelled for vendor not in tcf string

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10359]
## Type of issue
Bug, submitted on behalf of another user

## Description
Enforcement not excluding vendor with no consent in tc string

## Steps to reproduce
Go to https://www.dagenshultsfred.se/?pbjs_debug=true
Visit the page from the EU (module not configured worldwide), click on accept all
Click on the button in the lower left corner to change my settings
In the CMP go to one of the tcf purposes and disable AdForm
Save the consent and reload the page

Example TC String that I get:

CPwcAjAPwcAjAAfOUBDEDSCgAPLAAHLAAAigJMpB9G5USSBDAGpjYosEYAEW5lBoQyAgAgAAAoAACDKAIAQAEEAgIAAAICgAAAAAIEIAAAEIAAAAAAAAIIABAACIAACAIAAAAAAAAAAAQEAAAAAIAAAAAAAAAAAEAAAAgAAAABAIAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIJMpB9G5USSBDAGpjYosEYAEW5lBoQyAgAgAAAoAACDKAIAQAEEAgIAAAICgAAAAAIEIAAAEIAAAAAAAAIIABAACIAACAIAAAAAAAAAAAQEAAAAAIAAAAAAAAAAAEAAAAgAAAABAIAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA4KAGAAuARABEgJkCQAwAFwCIAIkBMgaAGAAuARABEgJkEQAwAFwCIAIkBMg6AGAAuARABEgJkJQAwAFwCIAIkBMhSAGAAuARABEgJkA

 https://iabtcf.com/#/decode shows adform, vendor 50, is not on the list of consented vendors. 
 

## Test page
[](https://www.dagenshultsfred.se/?pbjs_debug=true)

### Expected results
Expected outcome:

I’d thought I should not see any calls to adform (https://adx.adform.net/adx/openrtb) anymore.

 What I can see, is that the publisher has allowAuctionWithoutConsent on. My understanding is that this enables one to run the auction before the tc string is ready (but should stop the auction if the tc string is ready and the vendor does not have consent/no LI).

### Actual results

Adform bidder endpoint is clled

## Platform details
js 8.5, consentmanagement and gdpr installed
![image](https://github.com/prebid/Prebid.js/assets/1683175/ad8cad02-1c9b-45fa-a0f7-0109a1560244)

## Other information
Possible dupe of https://github.com/prebid/Prebid.js/issues/6267#issuecomment-772659677 ; enforcement doesn't appear to be explicitly configured, but user expects their configuration would cause this enforcement.

**Comment by dgirardi** [comment]
The CMP reports "legitimate interest" for purpose 2, so the user choice is ignored.

![image](https://github.com/prebid/Prebid.js/assets/10151381/c7757065-043a-4f23-a537-ccf596f05e9a)

**Comment by dgirardi** [comment]
Small correction @janwinkler - 

> Reality: Prebid only fires bidders is the purpose has consent/LI

Prebid only runs bidders if they either: 

1. have purpose _and_ vendor consent; or
2. have purpose LI.

The expectation, I believe, is that the second clause should check for purpose _and_ vendor LI.

**Comment by janwinkler** [comment]
@dgirardi yes that's even more confusing ;-)
