### ISSUE TITLE
Roll Your Own A9 adapter - Does it work?

### ISSUE THREAD

**Issue by tedrand** [prebid/Prebid.js#1035]
## Type of issue

Question

## Description

This gist has been passed around my team. 

[https://gist.github.com/Heray/277d421bda2b827f43da](https://gist.github.com/Heray/277d421bda2b827f43da)

It is supposedly the code for making a prebid adapter from the A9 source code. I don't know much about A9 but I know this has been requested. Is this method still possible with the changes that have been made to the library since it was published?

**Comment by mkendall07** [comment]
We don't have any official support for the A9 adapter. AFAIK it should still work to add an adapter at run time into prebid.js - that API hasn't changed.

**Comment by tedrand** [comment]
Perfect thanks for the quick response!

**Comment by tedrand** [comment]
Do you think it would be more effective to just run a prebid auction alongside the A9 code?
