### ISSUE TITLE
geolocationRtdProvider: lastfix does not match OpenRTB definition

### ISSUE THREAD

**Issue by lambdarho** [prebid/Prebid.js#10373]
## Type of issue
bug

## Description
Incorrect information passed in the BidRequest coming from geolocationRtdProvider

The geolocationRtdProvider fetches geo information from the browser and applies `lat / lon / lastfix / type` to `ortb2Fragments.global.device.geo`

The problem is that a timestamp is passed to `BidRequest.device.geo.lastfix`, but that does not match the OpenRTB definition.

The `BidRequest.device.geo.lastfix` field should be: 
> Number of seconds since this geolocation fix was established.
Note that devices may cache location data across multiple
fetches. **Ideally, this value should be from the time the actual
fix was taken.**

## Steps to reproduce
Enable the geolocationRtdProvider module, let the browser access `navigator.geolocation.getCurrentPosition` and look at the value passed in under `ortb2Fragments.global.device.geo.lastfix`

### Expected results
Calculate the number of seconds from when the geo information was taken and BidRequest was sent.

### Actual results
The module currently sends a timestamp so the value is interpreted incorrectly.

## Platform details

Prebid.js

**Comment by patmmccann** [comment]
I'm declaring this bugfix non-breaking given the recency of the module merge. Thank you for the report. Your bugfix submission is welcome.
