### ISSUE TITLE
Clean up `utils.js` to reduce bundle size

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#10392]
## Type of issue
improvement

## Description

`utils.js` is simultaneously the largest and least maintained file in the codebase. It can be improved in at least two ways:

 - move logic that is not needed by core into libraries, so that it ends up only in bundles with modules that actually need it. As example, this:
  https://github.com/prebid/Prebid.js/blob/3c70ac772f1b8620015089de778d331619d3b459/src/utils.js#L657-L668
  is only needed by a few appnexus-like bidders.
- refactor usage of "shim" utility functions that are now part of vanilla javascript. For example:
  https://github.com/prebid/Prebid.js/blob/3c70ac772f1b8620015089de778d331619d3b459/src/utils.js#L68-L76
  https://github.com/prebid/Prebid.js/blob/3c70ac772f1b8620015089de778d331619d3b459/src/utils.js#L470-L479
  and many others.

**Comment by pm-harshad-mane** [comment]
Isn't dead code elimination taken care of at the build generation time?
