### ISSUE TITLE
RubiconBidAdapter: Error while converting bidRequest to ORTB imp; request skipped

### ISSUE THREAD

**Issue by EskelCz** [prebid/Prebid.js#10400]
## Type of issue
Bug, probably

## Description
Bid request for Native format fails with an error, trying to set .pos at a `video` object, which for native isn't there.
(Cannot set properties of undefined (setting 'pos'))
This line: https://github.com/prebid/Prebid.js/blob/7.39.0/modules/rubiconBidAdapter.js#L197

## Steps to reproduce
1. Configure magnite adUnit with native mediaType and required assets
2. Run auction

## Test page
[https://playground.cpex.cz/native](https://playground.cpex.cz/native)
(position native-3)

### Expected results
No error

### Actual results
<img width="801" alt="image" src="https://github.com/prebid/Prebid.js/assets/1198558/8d602ad3-a3bb-42d4-8413-d1d9238f4b11">

## Platform details
Prebid 7.39 (but the culprit line is in the latest version as well)

**Comment by robertrmartinez** [comment]
PR: https://github.com/prebid/Prebid.js/pull/10401

**Comment by EskelCz** [comment]
@robertrmartinez That was fast, I'm shocked. :) Thanks a lot for the quick fix.

As for the `event trackers` issue, I must admit I have no idea what is happening there. Can you please elaborate? Is it something I need to handle on our end, or is that another adapter issue?

**Comment by robertrmartinez** [comment]
We updated the Rubicon Adapter to support native somewhat recently.

It sends an ORTB2 Native request to our exchange.

It looks like you still declare your prebid native adUnits using the "Legacy" prebid format:

![image](https://github.com/prebid/Prebid.js/assets/13972794/00aa4ef4-e531-47fe-bf49-8bd0f755130e)

This is transformed into ORTB and then sent.

Well, the Rubicon (Magnite) SSP requires the ORTB native request field called `eventtrackers`

See section `4.7	Event Trackers Request Object` in the [ORTB Native 1.2 Spec](https://iabtechlab.com/wp-content/uploads/2016/07/OpenRTB-Native-Ads-Specification-Final-1.2.pdf)

This is `optional` in ORTB, but our exchange has deemed it as `required` as of now. Unsure if it will change anytime soon, but that was the direction given.

Hope this helps clear it up.

**Comment by EskelCz** [comment]
@robertrmartinez I see, that clears it up. I'll use the ORTB configuration and add an empty eventtrackers array, that's no problem. Thanks a lot

**Comment by EskelCz** [comment]
@robertrmartinez I'm testing the fix in 8.12 and I'm seeing another error in the network request. First it show kind of a misleading warning in console:
<img width="1299" alt="image" src="https://github.com/prebid/Prebid.js/assets/1198558/e4128dff-b016-4ece-a75f-762af47a5494">
You can see it live here: [https://playground.cpex.cz/native](https://playground.cpex.cz/native)

Then in network request is the actual error:
```
"Error in native object for imp with id native-3: Plcmttype is not present or not of int type"
```
Here's the complete request:
https://www.postman.com/solar-sunset-356369/workspace/cpex-public/request/17429252-e68f23ad-0e99-4c31-851e-dc31970103dd?ctx=documentation

This is my adUnit definition:
```
[
    {
        "code": "native-3",
        "mediaTypes": {
            "native": {
                "ortb": {
                    "assets": [
                        {
                            "id": 1,
                            "required": 1,
                            "img": {
                                "type": 1,
                                "wmin": 200,
                                "hmin": 200
                            }
                        },
                        {
                            "id": 2,
                            "required": 1,
                            "title": { "len": 800 }
                        },
                        {
                            "id": 3,
                            "required": 1,
                            "data": { "type": 2 }
                        },
                        {
                            "id": 4,
                            "required": 0,
                            "data": { "type": 1 }
                        }
                    ],
                    "eventtrackers": []
                }
            }
        },
        "bids": [
            {
                "bidder": "rubicon",
                "params": {
                    "siteId": "140646",
                    "zoneId": "3017262",
                    "accountId": "10900",
                    "position": "atf",
                    "sizes": [ 221 ]
                }
            }
        ]
    }
]
```
It's probably some other misconfiguration on my part, but it's hard to debug since the error is from the back-end. Can you please see the issue?

**Comment by bretg** [comment]
Here are the validations done by the server-side rubicon adapter:

if imp.native.ver is 1.2, unpack the imp.native.request field and make the following validations:

- eventtrackers exists and is an array
- context exists and is an integer
- plcmttype exists and is an integer

These are the rules of the exchange.

**Comment by EskelCz** [comment]
@bretg Thanks, I missed that in the docs [https://docs.prebid.org/dev-docs/bidders/rubicon.html#native](https://docs.prebid.org/dev-docs/bidders/rubicon.html#native)
But there is no information what the values of `context` and `plcmttype` mean.

I searched Magnite docs and found it only on this page: [https://resources.rubiconproject.com/resource/xapi-specifications-3-2/#autoid-1-44-native-request-object](https://resources.rubiconproject.com/resource/xapi-specifications-3-2/#autoid-1-44-native-request-object)
But both of the attributes link to non-existent anchors. So I'm stuck. It's perplexing, such a bad documentation for a **required** values. I feel like I'm the first dev trying to configure Native for Magnite.

**Comment by bretg** [comment]
Thanks for the docs bug report @EskelCz. Will report it. I was going to suggest the IAB spec, but sounds like you found that.
