### ISSUE TITLE
Always set plcmt=4 when mediatypes.video.context = outstream; set 2 when possible to resolve

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10406]
## Type of issue
Feature Request

## Description
Always set plcmt=4 when it is missing & (mediatypes.video.context = outstream or video.placement is set to any of (2,3,4)) in core, both for adapters using ortb2 convertor, and also in the mediatypes.video object presented to those who do not. 

Always set plcmt=2 when it is missing & mediatypes.video.context != outstream and [playback method](https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/master/AdCOM%20v1.0%20FINAL.md#list--playback-methods-) is set to any of (2,6)

**Comment by patmmccann** [comment]
Publishers are welcome to override these defaults if they think their in focus muted preroll deserves plcmt=1

**Comment by patmmccann** [comment]
Publishers are welcome to override these defaults if they think their in focus muted preroll deserves plcmt=q

**Comment by hillslatt** [comment]
also i'm highly skeptical that [playback method](https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/master/AdCOM%20v1.0%20FINAL.md#list--playback-methods-) 4 and 5 should ever be considered instream. I can't see a case where there was user intent to watch a video in a player that does not initiate on page load or user interaction.

**Comment by TTD-JudS** [comment]
I don't get involved very often here, but any defaulting to video.plcmt=instream (1) is going to lead to the same mess of misrepresentation that we currently have with video.placement. Is it really that difficult for publishers to add code/configuration for what little true instream inventory exists?

**Comment by fowler446** [comment]
@TTD-JudS Absolutely. We came to the same conclusion in our Prebid Video meetings. plcmt = 1 will need to be explicitly set.

**Comment by patmmccann** [comment]
I will restate the requirements in the description

**Comment by patmmccann** [comment]
@TTD-JudS can you elaborate on this comment: > Our first census of inventory being passed with a video.plcmt signal is disconcertingly inaccurate.

**Comment by TTD-JudS** [comment]
> @TTD-JudS can you elaborate on this comment:
> 
> > Our first census of inventory being passed with a video.plcmt signal is disconcertingly inaccurate.
> 
> Do you see inaccuracies when plcmt is set to 2,3, or 4 or just when set to 1

We don't have great tooling to detect no-content video players. We're working on it now. We are seeing far too much inventory from a small set of larger pubs coming through misrepresented as video.plcmt=1
