### ISSUE TITLE
pbjs.getNoBids() method not working for IncrementX bidder

### ISSUE THREAD

**Issue by Prebid-Vertoz** [prebid/Prebid.js#10421]
## Type of issue
Bug

## Description
Hello @Prebid-Team,

When we call our adapter(IncrementX) and response is NOBID then if we
calling 'pbjs.getNoBids()' Method in console but it not return our adapter
details in nobids.

## Test page

https://textfeed.howgeneric.com/Beta/HB_IncrementX.html

**Comment by dgirardi** [comment]
In that page the adapter does provide a bid, although invalid, so it gets rejected:

![image](https://github.com/prebid/Prebid.js/assets/10151381/3d530463-641c-4452-92a6-1a39acd9273a)

`getNoBids()` only looks at requests that got no bids; rejected bids are instead routed to the 'bidRejected' event.
