### ISSUE TITLE
Smilewanted bid adapter: gvlid is missing

### ISSUE THREAD

**Issue by MaxSmileWanted** [prebid/Prebid.js#10422]
Hello PrebidJS Community,

I've encountered an issue related to the recent changes in TCF v2.2 consent handling in Prebid.js since the version [8.11.0](https://github.com/prebid/Prebid.js/releases/tag/8.11.0).

### Context:
- I've been testing the changes after [this pull request](https://github.com/prebid/Prebid.js/pull/10367/files).
- I've ensured that I've given consent, but not legitimate interest.
- Despite this, my adapter (`smilewanted`) is not being called.
- I receive the following warning in the console when enabling PrebidJS logs: `WARNING: Activity control: TCF2 denied 'fetchBids' for 'bidder.smilewanted'`.

### Consent String TCF v2.2 Configuration:
`CPwVsQAPwVsQAAKAvAFRDSCsAP_AAH_AAAqIJnNV_H__bW9r8X7_aft0eY1P9_j77uQxBhfJk-4F3LvW_JwX52E5NF36tqoKmRoEu3ZBIUNlGJHUTVmwaokVryHsak2cpTNKJ6BEkFMRM2dYCF5vm5tjeQKY5_p_d3fx2D-t7dv839z3z81Xn3d5f--0-PCdU5-9Dfn9fRfb-9IP9_78v8v8_l_rk2_eT13_p8_7_D_-f_87_XWxBQAJMNS4gC7IgJCbQMIoEQIwrCAigUAAAAkDRAQAuDAp2RgE-sBkAIEUARwQAhABRkACAAASABCIAJAigQAAQCAQAAgAQCAQAMDAAOAC0EAgABAdAxTCgAUCwgSISIhTAhKgSCAlsqEEoLhBXCAIssCKARGwUACIJARWAAICxeAwBICViQQJdQbQAAEACAUUoViKT8wBDgmbLVXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA.f_gAAAAAAAAA`

### Steps to Reproduce:

1. Load the latest PrebidJS Version (after [8.11.0](https://github.com/prebid/Prebid.js/releases/tag/8.11.0))
2. Enable PrebidJS logs.
4. Load a page with the `smilewanted` adapter and the above TCF v2.2 configuration.
5. Observe the warning in the console.

### Expected Behavior:
The `smilewanted` adapter should be called as consent has been provided.

### Actual Behavior:
The `smilewanted` adapter is not being called, and the mentioned warning appears in the console.

### Additional Information:
- This issue seems to be related to the changes in how Prebid.js handles TCF v2.2 consent and legitimate interest, especially for Purpose 2.
- Other adapters, like `Smart Adserver`, are working as expected.
- I've reached out to a representative from IAB Europe regarding this issue, and here's their response:

> The pull request indicated in the email appears to ensure that the receiving Vendor has established legitimate interest for purpose 2 prior to being allowed into an auction. This consists in verifying that Legitimate Interest signals are set to 1 for both purpose 2 (in the PurposesLITransparency) and for the receiving Vendor (in the Vendor Legitimate Interest Section).
> As you are relying on consent for purpose 2, you may want to verify with Prebid that having obtained consent for purpose 2 is also ok to be allowed into an auction.

I would appreciate any insights or suggestions on how to resolve this issue. Thank you in advance for your assistance!

Best regards,
Max

**Comment by patmmccann** [comment]
You don't have a gvlid defined in your adapter

**Comment by MaxSmileWanted** [comment]
Oh ok thank you, I will submit a PR to modify that.

Is it related to the fact that we have been marked "No" to TCF-EU Support? : https://docs.prebid.org/dev-docs/bidders/smilewanted.html

**Comment by MaxSmileWanted** [comment]
Here the PR : https://github.com/prebid/Prebid.js/pull/10423

**Comment by patmmccann** [comment]
Pr docs as well to say you support gdpr now, thanks!
