### ISSUE TITLE
List of adapters reading video.placement and not video.plcmt

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10452]
## Type of issue
Feature Request

## Description
#5237 was adopted in Prebid 5, and recently video.placement was deprecated in favor of video.plcmt.

This is a shell issue to grep out which adapters are pulling video.placement but not either using the ortb convertor nor pulling plcmt.

**Comment by patmmccann** [comment]
Tagging as a possible 9.0 consideration

**Comment by itaynave** [comment]
Should remove 
https://github.com/prebid/Prebid.js/tree/master/libraries/ortbConverter/processors/video.js
as placement is not 1 anymore in all instream cases

**Comment by fowler446** [comment]
@ChrisHuie @patmmccann 
Here's the list of all adapters relying on `placement` without `plcmt`:

```
https://github.com/prebid/Prebid.js/blob/master/modules/e_volutionBidAdapter.js#L129
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/beachfrontBidAdapter.js#L29
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/outbrainBidAdapter.js#L357
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/sovrnBidAdapter.js#L30
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/operaadsBidAdapter.js#L528
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/saambaaBidAdapter.js#L125
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/improvedigitalBidAdapter.js#L235
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/admanBidAdapter.js#L146
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/smartxBidAdapter.js#L147
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/spotxBidAdapter.js#L216
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/advangelistsBidAdapter.js#L121
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/openxBidAdapter.js#L148
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/tripleliftBidAdapter.js#L241
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/krushmediaBidAdapter.js#L108
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/iqzoneBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/bluebillywigBidAdapter.js#L21
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/iqmBidAdapter.js#L16
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/datawrkzBidAdapter.js#L230
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/videobyteBidAdapter.js#L21
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/deepintentBidAdapter.js#L17
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/yieldmoBidAdapter.js#L657
Some logic still relies on `placement`

https://github.com/prebid/Prebid.js/blob/master/modules/loyalBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/lkqdBidAdapter.js#L160
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/edge226BidAdapter.js#L59
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/adbookpspBidAdapter.js#L45
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/shinezBidAdapter.js#L335
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/smarthubBidAdapter.js#L54
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/appushBidAdapter.js#L59
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/pgamsspBidAdapter.js#L66
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/waardexBidAdapter.js#L150
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/mgidXBidAdapter.js#L72
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/loganBidAdapter.js#L101
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/gamoshiBidAdapter.js#L160
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/pstudioBidAdapter.js#L42
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/adtrueBidAdapter.js#L45
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/33acrossBidAdapter.js#L38
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/quantcastBidAdapter.js#L52
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/colossussspBidAdapter.js#L176
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/pubmaticBidAdapter.js#L563
still requires deprecated field `placement`

https://github.com/prebid/Prebid.js/blob/master/modules/imdsBidAdapter.js#L14
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/pubCircleBidAdapter.js#L62
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/acuityadsBidAdapter.js#L55
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/dspxBidAdapter.js#L15
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/adagioBidAdapter.js#L67
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/bridBidAdapter.js#L18
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/visiblemeasuresBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/eskimiBidAdapter.js#L24
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/pubgeniusBidAdapter.js#L158
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/kiviadsBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/kueezBidAdapter.js#L419
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/adagioAnalyticsAdapter.js#L272
still relying on deprecated `placement` value

https://github.com/prebid/Prebid.js/blob/master/modules/mobfoxpbBidAdapter.js#L109
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/mediakeysBidAdapter.js#L68
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/yahoosspBidAdapter.js#L373
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/boldwinBidAdapter.js#L112
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/tappxBidAdapter.js#L42
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/insticatorBidAdapter.js#L544
required deprecated `placement` field

https://github.com/prebid/Prebid.js/blob/master/modules/globalsunBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/emtvBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/videojsVideoProvider.js#L150
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/axisBidAdapter.js#L56
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/pubwiseBidAdapter.js#L65
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/cleanmedianetBidAdapter.js#L160
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/beyondmediaBidAdapter.js#L54
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/gothamadsBidAdapter.js#L335
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/mathildeadsBidAdapter.js#L55
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/contentexchangeBidAdapter.js#L55
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/adprimeBidAdapter.js#L106
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/silverpushBidAdapter.js#L22
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/compassBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/adotBidAdapter.js#L200
uses `placement` and no `plcmt`
```

**Comment by patmmccann** [comment]
@K-JBoon i'll take care of it, ty!

**Comment by ChrisHuie** [comment]
Updated List :

https://github.com/prebid/Prebid.js/blob/master/modules/sovrnBidAdapter.js#L30
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/operaadsBidAdapter.js#L528
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/saambaaBidAdapter.js#L125
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/improvedigitalBidAdapter.js#L235
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/admanBidAdapter.js#L146
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/smartxBidAdapter.js#L147
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/spotxBidAdapter.js#L216
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/advangelistsBidAdapter.js#L121
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/openxBidAdapter.js#L148
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/tripleliftBidAdapter.js#L241
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/krushmediaBidAdapter.js#L108
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/iqmBidAdapter.js#L16
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/datawrkzBidAdapter.js#L230
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/videobyteBidAdapter.js#L21
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/loyalBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/lkqdBidAdapter.js#L160
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/edge226BidAdapter.js#L59
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/shinezBidAdapter.js#L335
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/appushBidAdapter.js#L59
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/pgamsspBidAdapter.js#L66
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/waardexBidAdapter.js#L150
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/mgidXBidAdapter.js#L72
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/loganBidAdapter.js#L101
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/pstudioBidAdapter.js#L42
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/adtrueBidAdapter.js#L45
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/quantcastBidAdapter.js#L52
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/pubCircleBidAdapter.js#L62
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/acuityadsBidAdapter.js#L55
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/dspxBidAdapter.js#L15
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/pubgeniusBidAdapter.js#L158
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/kiviadsBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/kueezBidAdapter.js#L419
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/mobfoxpbBidAdapter.js#L109
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/yahoosspBidAdapter.js#L373
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/boldwinBidAdapter.js#L112
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/globalsunBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/emtvBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/videojsVideoProvider.js#L150
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/axisBidAdapter.js#L56
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/pubwiseBidAdapter.js#L65
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/cleanmedianetBidAdapter.js#L160
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/beyondmediaBidAdapter.js#L54
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/gothamadsBidAdapter.js#L335
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/mathildeadsBidAdapter.js#L55
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/contentexchangeBidAdapter.js#L55
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/adprimeBidAdapter.js#L106
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/silverpushBidAdapter.js#L22
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/compassBidAdapter.js#L60
uses `placement` and no `plcmt`

https://github.com/prebid/Prebid.js/blob/master/modules/adotBidAdapter.js#L200
uses `placement` and no `plcmt`

**Comment by karimMourra** [comment]
@itaynave in https://github.com/prebid/Prebid.js/issues/10452#issuecomment-1892286535

> Should remove
https://github.com/prebid/Prebid.js/tree/master/libraries/ortbConverter/processors/video.js
as placement is not 1 anymore in all instream cases

Did you mean to say `plcmt` is not 1 anymore ? I agree that `plcmt` is not 1 for all instream cases, but legacy placement is still 1, by definition cc @patmmccann
