### ISSUE TITLE
GumGum Bid Adapter: Not Passing GPP Consent Object as string

### ISSUE THREAD

**Issue by robertrmartinez** [prebid/Prebid.js#10469]
## Type of issue
[X] - Bug

## Description
When GPP consent is constructed by the gumgum adapter it is set as an object.

But the gumgum adapter sends a GET with query string params.

So this `gppConsent` object needs to be serialized into a JSON string, OR sent as separate fields.

I do not assume to know what the GumGum adserver expects, so I cannot make this change for them. (Though if I was a betting man, I would bet it just needs to be `JSON.stringify`-ed)

## Steps to reproduce
Here is an example:

![image](https://github.com/prebid/Prebid.js/assets/13972794/aad0c2fc-5027-45c8-b00e-7554c8cef3b2)

And the code: 

```js
    if (gppConsent) {
      data.gppConsent = {
        gppString: bidderRequest.gppConsent.gppString,
        gpp_sid: bidderRequest.gppConsent.applicableSections
      }
    } else if (!gppConsent && bidderRequest?.ortb2?.regs?.gpp) {
      data.gppConsent = {
        gppString: bidderRequest.ortb2.regs.gpp,
        gpp_sid: bidderRequest.ortb2.regs.gpp_sid
      };
    }
```

**Comment by robertrmartinez** [comment]
@MartinGumGum As the last person with an edit to the Gum Gum adapter I figured I would tag you!

**Comment by MartinGumGum** [comment]
Hi @robertrmartinez,  could you please send the link where you saw this bug so I can reproduce the issue? and thank you for noticing this.

**Comment by robertrmartinez** [comment]
@MartinGumGum 

I saw it on ladbible: https://www.ladbible.com/entertainment/youtube/max-fosh-explains-uno-reverse-card-sidemen-fc-754399-20230911

![image](https://github.com/prebid/Prebid.js/assets/13972794/e3349657-6971-4acf-a14a-b3235efde9f8)
