### ISSUE TITLE
Pair Id Module: generates multiple eids with same source

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10479]
## Type of issue
Bug

## Description
Google Pair module produces lots of distinct eids with the same source. They should be in a single object according to https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/extensions/2.x_official_extensions/eids.md

cc: @congdu-kun 

## Test page
Hard to reproduce, you have to have a lot of retargeting segments and be a Chrome user I think
firstquarterfinance.com is a site with the Pair module installed

### Expected results

![image](https://github.com/prebid/Prebid.js/assets/1683175/6c3d751c-8f51-4734-bf0f-0cb3809082d3)

### Actual results

![image](https://github.com/prebid/Prebid.js/assets/1683175/070b98d6-ced1-4fc2-842b-003559818427)

This request is then rejected by PBS

**Comment by dgirardi** [comment]
> They should be in a single object according to https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/extensions/2.x_official_extensions/eids.md

I cant' think of any way to read that spec that would warrant that conclusion. That spec does not say that there can be only one EID object per source, or that source must be unique across EID objects. What am I missing?
