### ISSUE TITLE
Sharethrough bid adapter generates invalid sync URLs

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#10478]
## Type of issue
consent being added to domain and throwing error

## Steps to reproduce
in V8.11.0 there is no error , test page: https://cdn.adysis.com/VideoDemo/DemoSite/pages/BBH.html

in V8.13.0 a error is being thrown and it looks like consent is being added onto the domain ( no idea where this is coming from):
![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_BBH8_13_0_html_and_Lee_Westwood_v_Ian_Poulter_v_Jimmy_Bullard__It’s_The_Nuts___-_YouTube_🔊](https://github.com/prebid/Prebid.js/assets/8503167/232ccbc2-ae83-4c01-befb-99f66edb3cd7)

test page: https://cdn.adysis.com/VideoDemo/DemoSite/pages/BBH8.13.0.html

### Expected results
no error to be throw and no domain url with consent on it

### Actual results
error being thrown with domain url being created with what looks like consent etc on it

## Platform details
chrome, mac, V8.11.0 V's V8.13.0

**Comment by dgirardi** [comment]
I believe this was introduced by #10388; sometimes the sharethrough bid adapter will return an invalid user sync URL (paging @jefftmahoney):

![image](https://github.com/prebid/Prebid.js/assets/10151381/640892d6-4c08-479f-8bc3-8df891279146)

I don't think this affects anything beside sharethrough's user syncs, so from a publisher's point of view it should be close to inconsequential.

**Comment by deivydas** [comment]
Hey @spormeon,
This issue should be fixed now.
We have noticed that there was empty strings delivered in some cases as user sync urls.
We have introduced measures in our backend to now have this situation.

**Comment by lcorrigall** [comment]
Can this be closed?

**Comment by spormeon** [comment]
@lcorrigall  fine by me, if @deivydas  is sure its sorted out now, backend logs disapeared?
