### ISSUE TITLE
Getting non-winning KVPs does not work when redefining standard adserverTargeting

### ISSUE THREAD

**Issue by philipwatson** [prebid/Prebid.js#10486]
## Type of issue

Questions. Possible bugs.

## Description

I have a setup where custom (redefined) standard KVPs are used. Simplified example:

```javascript
pbjs.bidderSettings = {
  standard: {
    adserverTargeting: [
      {
        key: "custom_adid",
        val: function (bidResponse) {
          return bidResponse.adId;
        }
      },
      {
        key: "custom_bidder",
        val: function (bidResponse) {
          return bidResponse.bidder;
        }
      },
      // ... etc ...
    ]
  }
};
```
Seems like an ok thing to do after reading https://docs.prebid.org/features/adServerKvps.html#completely-custom-kvps

but have a problem when I switch on `enableSendAllBids` :

```javascript
pbjs.setConfig({
  enableSendAllBids: true
});
```

The problem is that I don't get the custom standard KVPs for all bidders (e.g. `custom_adid_BIDDERCODE`) when calling `pbjs.getAdserverTargeting()` inside the bidsBackHandler. I only get them for the winner (the ones without the `_BIDDERCODE` postfix).

Getting all bidder KVPs (including losers) only works for the out-of-box standard keys: `hb_adid`, `hb_bidder`, etc.

Looking at the code.. the `getBidLandscapeTargeting` function has a line inside targeting.js:

https://github.com/prebid/Prebid.js/blob/50bcec38aa0c671406aacfde9bc570a59a0749fc/src/targeting.js#L646

Was there an oversight there? Could it be replaced with: 

```javascript
const standardKeys = FEATURES.NATIVE ? getStandardKeys().concat(NATIVE_TARGETING_KEYS) : getStandardKeys();
```

Because the `getStandardKeys()` also considers the custom key set.

The same change can be applied to the `getDealBids` function (for scenario when alwaysIncludeDeals == true and enableSendAllBids == false)

https://github.com/prebid/Prebid.js/blob/50bcec38aa0c671406aacfde9bc570a59a0749fc/src/targeting.js#L197C3-L199C116

And another issue related to custom KVPs... the `sortByDealAndPriceBucketOrCpm` function directly uses the out-out-box standard keys: `hb_deal` and `hb_pb`. If the publisher is instead using `custom_deal` and `custom_pb`, this function won't work as intended. 

No urgency for me here. I have a workaround that solves the business problem I had. Just wondering if the issues mentioned here are actual bugs? If so, will it be fixed in a later major version? Or have I misunderstood something?

Found the umbrella issue here: https://github.com/prebid/Prebid.js/issues/8130

**Comment by dgirardi** [comment]
> Just wondering if the issues mentioned here are actual bugs? 

I'd say yes, but at this point they are also features - because unfortunately existing installations are likely to be broken by a fix. Adding more keys can cause others to be dropped due to the limits we put on the amount of data sent through KVPs.

We would like to revamp the whole system in a major version release, as explained in the issue you found.

> If the publisher is instead using custom_deal and custom_pb, this function won't work as intended.

I am not sure why we are sorting bids using KVPs instead of deals or price buckets directly. This seems more of a straightforward fix.

**Comment by philipwatson** [comment]
Thanks for quick reply. Yes totally agree regarding breaking existing installations... and I'm happy there is a revamp planned.

I think a change to sorting may also break existing setups.. because the values for these keys can be computed. For example, the publisher may compute some dealIds to undefined (in order to filter them out). Also not sure you can get the bucket value directly... looks like only from `bid.adserverTargeting`.
