### ISSUE TITLE
33across id module: does not work in Europe; still sends network request

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10495]
## Type of issue
bug

## Description
[](https://github.com/prebid/Prebid.js/blob/5fc475ed7423dcc295dafc6a552097b191f049d5/modules/33acrossIdSystem.js#L77) 33across id module has a gvlid and the module passes gdpr consent strings

Should we just delete the gvlid from the module? 

### Expected results
gdpr enforcement suppresses 33across, or the module suppresses the endpoint call when gdpr applies

### Actual results
33across responds with a we do not support this country error

![image](https://github.com/prebid/Prebid.js/assets/1683175/1d1f9a2a-45a1-4aa5-b1b7-74adb960d881)

**Comment by patmmccann** [comment]
related https://github.com/prebid/prebid.github.io/pull/4866

**Comment by patmmccann** [comment]
33 across drops all strings with usnat now 
![image](https://github.com/prebid/Prebid.js/assets/1683175/65b16313-5c45-42ce-a448-7f73b76e481d)


Should we just remove them from the project?

**Comment by curlyblueeagle** [comment]
@patmmccann Developer from 33Across here. We are looking into the issue regarding US Nat and work on a fix.

**Comment by curlyblueeagle** [comment]
@patmmccann we released a fix yesterday to our servers and seen a big reduction in the number of US Nat requests dropped. Can you please try again? Also do you mind sharing the details of you tests that resulted in requests being dropped? So we can try them at our end too and make sure we haven't missed anything? Thanks.

**Comment by patmmccann** [comment]
Awesome!

**Comment by patmmccann** [comment]
cafedelites.com/?commit=e949a58

**Comment by curlyblueeagle** [comment]
Thanks! The test page now appears to be making calls and getting proper responses from our endpoint. So I am assuming US Nat is no longer an issue.

With respect to GPDR we plan to implement your suggestion https://github.com/prebid/Prebid.js/pull/10714#discussion_r1471795002 in that same PR. Our developer working on it will get back to you over there.

**Comment by patmmccann** [comment]
@curlyblueeagle tyvm! I will mark that pr as closes this issue. Thanks for the engagement!

**Comment by curlyblueeagle** [comment]
No problem, thanks for bringing this to our attention.

**Comment by carlosfelix** [comment]
@patmmccann We have made the GDPR changes based on what was suggested.

Changes have been incorporated to [PR 10714](https://github.com/prebid/Prebid.js/pull/10714)

**Comment by carlosfelix** [comment]
Just a reminder that changes are part of [PR 10714](https://github.com/prebid/Prebid.js/pull/10714), please take a look when you have a chance.

**Comment by patmmccann** [comment]
Excellent thanks for your attention on this!
