### ISSUE TITLE
Analytics - ga events causing very low bounce rate

### ISSUE THREAD

**Issue by pwfsd** [prebid/Prebid.js#105]
Google analytics events need to be fired with nonInteraction set to avoid influencing bounce rate, otherwise each event is considered a user interaction and bounce rate will be effectively 0.

Just add {nonInteraction: true} to all event calls, like this:

window[_gaGlobal]('send', 'event', _category, 'Bids', bidder, cpmCents, {nonInteraction: true});

**Comment by mkendall07** [comment]
Thanks for the info! I'll update the GA calls to reflect the `nonInteraction` value.
