### ISSUE TITLE
getAdserverTargeting no response

### ISSUE THREAD

**Issue by UrTARGET** [prebid/Prebid.js#1050]
## Type of issue

question
## Description

We recently trying to integrate header bidding using pbjs with new openx adapter. But in the test page, we found pbjs.getAdserverTargeting has no responses.
## Steps to reproduce

Here is the link to our test page https://www.indigodaily.com/pbjs_example_gpt.html?pbjs_debug=true
### Expected results
ex:
"/9968336/header-bid-tag-1": {
    "hb_bidder": "openx",
    "hb_adid": "147ac541a",
    "hb_pb": "1.00"
  }
### Actual results
no response
## Platform details

Prebid.js v0.20.0 loaded 
Chrome
macOS Sierra 10.12.3

**Comment by mkendall07** [comment]
Are you sure you are receiving bids from OpenX? I see this response: ```{"div-gpt-ad-1489592576789-0":{"oxb":"300x250_500","ox_pb_won":"true","hb_pb":"5.30","hb_adid":"2f4e52b4536151","hb_bidder":"openx"}}``` Visiting the page

**Comment by mkendall07** [comment]
See here for tips: http://prebid.org/dev-docs/toubleshooting-tips.html#see-all-bids-in-the-console
