### ISSUE TITLE
TypeError: w.apply is not a function

### ISSUE THREAD

**Issue by chucklapointe** [prebid/Prebid.js#10500]
## Type of issue
bug

## Description
I have now idea how this error is impacting revenue or if its impacting anything at all, but I'm getting a TypeError every time Prebid loads that seems to be tied directly to our new Prebid 8.14 installation. We are still receiving bids as per normal.
We have all main modules attached in our build and also running Video + Server adapters.

## Steps to reproduce
1. Go on one of our article pages and wait for Prebid to load: [Test page](https://www.narcity.com/i-tried-all-the-cheap-instant-noodles-at-no-frills-this-brand-makes-the-best-budget-meal)

2. Open up console, you will see this error:

```
prebid8.14.0.js:5 Uncaught (in promise) TypeError: w.apply is not a function
    at prebid8.14.0.js:5:18307
    at prebid8.14.0.js:5:18704
    at Array.forEach (<anonymous>)
    at prebid8.14.0.js:5:18676
    at prebid8.14.0.js:5:156113
    at onResponse (prebid8.14.0.js:35:15050)
    at success (prebid8.14.0.js:35:13626)
    at prebid8.14.0.js:5:35122
```

## Test page
[Test page](https://www.narcity.com/i-tried-all-the-cheap-instant-noodles-at-no-frills-this-brand-makes-the-best-budget-meal)

### Expected results
Error should not be appearing.

## Platform details
Chrome + Safari
Prebid 8.14
Desktop

**Comment by dgirardi** [comment]
Thank you for the report! yes, this will affect revenue, and I suggest holding off on updating until we release the [fix](https://github.com/prebid/Prebid.js/pull/10501).
