### ISSUE TITLE
Safari - All partners has 0 CPM all the time ?

### ISSUE THREAD

**Issue by Sandeep-Patel** [prebid/Prebid.js#1051]
## Type of issue
No bid winners

## Description
I am implementing prebid with 3 partners. I noticed that it works as expected in Chrome and Mozilla the partner response always have 0 CPM in safari. (See attached screenshot). 

I am using below script to print the bid responses table shown in screenshot:
```
var responses = pbjs.getBidResponses();
var output = [];
for (var adunit in responses) {
   if (responses.hasOwnProperty(adunit)) {
      var bids = responses[adunit].bids;
      for (var i = 0; i < bids.length; i++) {
           var b = bids[i];
           output.push({'adunit': adunit, 'bidder': b.bidder, 'cpm': b.cpm, 'msg': b.statusMessage});
      }
  }
}
if (output.length) {
     if (console.table) {
            console.table(output);
     } else {
           for (var j = 0; j < output.length; j++) {
                console.log(output[j]);
          }
     }
} else {
     console.warn('NO prebid responses');
}
```
Am I doing something wrong ? Is this known issue ? 

## Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/2659704/23984428/a867128c-0a6d-11e7-9836-f221d97a73f6.png)

## Platform details
I am using 0.19.0 with Safari

**Comment by mkendall07** [comment]
Most likely bidders are not bidding because of Safari 3rd party cookie restrictions. I don't think there is anything wrong with safari in particular working with prebid.

Interested in hearing from others though.

**Comment by tedrand** [comment]
I would think you would still see bids back occasionally even without the cookie sync. One thing I would suspect is that the slots are being defined before the corresponding DIV is actually on the page. Are you dynamically loading ad units?

**Comment by Sandeep-Patel** [comment]
That is right. I see some bids occasionally. Yes I create the ad unit array dynamically since our different pages have different slits/sizes. I load the initial list of slots on page depending on page type (parameter) and then enrich the array with partner params dynamically.

**Comment by tedrand** [comment]
Creating the ad unit array shouldn't be an issue, I was talking about the actual DIVs with the Ad Unit IDs on the page. Can you provide a URL?

**Comment by Sandeep-Patel** [comment]
I don't have the page ready yet. I have it on QA which is internal only. But to answer your question about DIVs, no we are not creating it dynamically.

**Comment by tedrand** [comment]
Fresh tags on a QA page with no RTB knowledge of the actual site, could just be a test page issue combined with what @mkendall07 was referring to. If you run the Prebid debug console, and see 

`Attempting to set key value for slot:`

and/or your line items are delivering, I'd say there's probably no issue. Debugging in chrome is a good idea.

**Comment by mkendall07** [comment]
closing this out as I think it's related to the dev box you are running.
