### ISSUE TITLE
Formatting Query String doesn't properly encode 

### ISSUE THREAD

**Issue by JoshuaRogan** [prebid/Prebid.js#10514]
## Type of issue
Bug

## Description
One of the two functions that can format a query string doesn't correctly encode values.

Two format Functions: 
https://github.com/prebid/Prebid.js/blob/master/src/utils.js#L135
https://github.com/prebid/Prebid.js/blob/master/src/utils.js#L1165 --> Doesn't properly encode 

## Steps to reproduce
Input any URL with query params into [this function](https://github.com/prebid/Prebid.js/blob/master/src/utils.js#L1165) as an input. 

(See test page for more reproduction steps) 

### CodePen Extracted Example
https://codepen.io/Josh-Rogan/pen/bGOaMWr?editors=0012

In the following code pen, when a query param contains something similar to a URL with query params, it won't properly encode those into the final string. Looking at the console output `description_url` is not properly parsed. 

### Intermittent Live Test Page
_This only works sometimes so may not be the best way to reproduce_

[Live Test Page](https://www.theweathernetwork.com/en/news/weather/forecasts/severe-risk-downpours-return-to-parts-of-ontario-quebec-ottawa-montreal-friday?iu=/19849159/MobileApps-TWN/en-CA/news&placecode=CAQC0783&inAppPurchase=0&autoplayVideo=1&cust_params=current_hour%3D12%26correlator%3D6493654983039265%26platform%3DiPhoneApp%26g%3D0%26ln%3D-79.3100531213724%26ltln%3Dtrue%26lt%3D43.753432463895535%26appleWatchUser%3DFALSE%26ab_rand%3Diphoneapp_2%26prsize%3D400x300%26cppid%3DEE95B4D8882040FDA0874B5BE4CCCB6A%26contviewed%3D2%26newsid%3D4KVQhPEY6hxW0uWm1nE3BD%26product%3Dnews%26appVersion%3D5.77.0.5873%26newscat%3Dtravel%26uaat%3Dfalse&platform=ios&pbjs_debug=true)

Use network tab to find `gampad/ads?` and sometimes you can see where you end up with additional query params like `cust_params` which are not properly within it's variable 

### Expected results
All query params are properly encoded. 

### Actual results
All query params are not encoded. In particular, if any query param value has a `&` it will pollute the real query params with additional query params.  

## Platform details
- Chrome but this can reproduced in any environment 

## Other information

Ideally, we should not be using multiple query string formatting functions. This would be a good opportunity to unify and potentially update to use `URLSearchParams`(https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)  

[Quick Fix](https://github.com/jwplayer/Prebid.js/pull/59)

**Comment by dgirardi** [comment]
I agree that some refactoring is warranted, but unfortunately the "wrong" version is used in many places, with many callers assuming they need to do the encoding themselves - so it cannot be simply "fixed" and I'm not sure we want to try to refactor everything (you cannot always tell from the code whether the inputs are already URL-encoded).

Do you have more details on where specifically this is a problem? Could it be fixed by switching to the alternate version?

**Comment by dgirardi** [comment]
This might be one:

https://github.com/prebid/Prebid.js/blob/32c1bf651254ab6685a44aee9d9ff3ddf7c9d648/modules/dfpAdServerVideo.js#L139-L143

**Comment by dgirardi** [comment]
I am not able to spot the issue from the demo page - but I'm not sure what I'm looking for. The code appears to know that it should encode `cust_params`:

https://github.com/prebid/Prebid.js/blob/6d39d8b2292d031a1d3e599749a7ceda74d379bc/modules/dfpAdServerVideo.js#L104

**Comment by patmmccann** [comment]
Flagging https://github.com/jwplayer/Prebid.js/pull/59 as a possible 9.0 change to debate

**Comment by patmmccann** [comment]
Committee decided not to change the utility without changing all the places it was used to reflect new behavior. We're not actively planning to take on the larger scoped project as the utility is in widespread use.
