### ISSUE TITLE
GAM Macro to pick one cache_id in an adpod

### ISSUE THREAD

**Issue by end0cr1ne** [prebid/Prebid.js#10513]
## Type of issue
Question

## Description
Creatives for adpods are basically cache url's with macros for the cache path and cache ids. In the case of an ad pod the cache_id cust_param(/gampad call) contains multiple values.
What macro can be used in GAM to pick the correct cache id?

### Expected results
https://cache-url/pache/path?uuid=1234

### Actual results
https://cache-url/pache/path?uuid=1234,5678,9101

## Platform details
GAM

**Comment by bretg** [comment]
@end0cr1ne - please help us understand how this is a Prebid.js issue.

Prebid doesn't support VMAP or pods.

**Comment by end0cr1ne** [comment]
I wasn't really sure whom to reach out to. Would you be able to direct me to the correct forum?

**Comment by bretg** [comment]
Sorry, I'm not even clear on what the problem is, so can't recommend a forum. If it's a GAM problem, try https://support.google.com/admanager/?hl=en#topic=7505988
