### ISSUE TITLE
Unify formatting query string functions

### ISSUE THREAD

**Issue by JoshuaRogan** [prebid/Prebid.js#10515]
## Type of issue
Feature Request

## Description
Currently, there are two separate functions which transform properties into a formatted query string: 

https://github.com/prebid/Prebid.js/blob/master/src/utils.js#L111-L118
https://github.com/prebid/Prebid.js/blob/master/src/utils.js#L841-L848--> Doesn't properly encode (Fixed: [Quick Fix Downstream](https://github.com/jwplayer/Prebid.js/pull/59))

Ideally, we should not be using multiple query string formatting functions. This would be a good opportunity to unify and potentially update to use `URLSearchParams`(https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)  

## Other information
https://github.com/prebid/Prebid.js/issues/10514

**Comment by patmmccann** [comment]
What do you mean when you say "this would be a good opportunity"? Do you mean the prebid 9 release?

**Comment by patmmccann** [comment]
This is work is not planned.
