### ISSUE TITLE
docs for #10308, eventHistoryTTL and minBidCacheTTL

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#10524]
## Type of issue
docs missing/ no clue how to use eventHistoryTTL and minBidCacheTTL, could be usefull for if "re-bidding" in video etc but no clue how to use them, cant find anything in any docs anywhere

**Comment by spormeon** [comment]
big thumbs up to these, they seem to totally stop any "hanging" on video re-bids, playlists etc, which been scrathing head about for weeks

**Comment by dgirardi** [comment]
@spormeon I'm glad to hear it but also curious - do you run a lot of auctions on one page? does the hanging get worse as the page gets older?

even with high memory usage we should be able to avoid other performance issues, but we never optimized for this scenario so it's likely that we're not doing it very well.

**Comment by spormeon** [comment]
ye, gets worse longer page "session"/ person sat on page.  I've actually seen it in PPB, where the auction gradually takes longer and longer, leading to timeouts etc and eventually the whole page will "hang" (white screen of death, if try to refresh etc).  I've actually sat and watched it, before this eventHistoryTTl  you got about 5 mins at a guess, with this eventTTL, its not "hung" at all today while been testing it on a playlist that prob 15mins+ and even looped back around, and didnt "hang"

**Comment by patmmccann** [comment]
thanks for the feedback!
