### ISSUE TITLE
"error":"Prebid file not built properly" for Incrementx Adapter

### ISSUE THREAD

**Issue by Prebid-Vertoz** [prebid/Prebid.js#10520]
## Type of issue
Bug

## Description
The Prebid download form here:
http://prebid.org/download.html

Fails if you choose the "IncrementX" adapter:
{"error":"Prebid file not built properly","requestId":"ed750706-67b7-4b5d-ae1f-6d7dd1235cdf"}

## Steps to reproduce
http://prebid.org/download.html
choose IncrementX

## Test page
http://prebid.org/download.html

### Expected results
Prebid download

**Comment by ChrisHuie** [comment]
@Prebid-Vertoz this appears to now be fixed with the above docs change
