### ISSUE TITLE
prebid code gets evaluated by test runner when imported via NPM causing all tests to fail

### ISSUE THREAD

**Issue by hemdagem** [prebid/Prebid.js#10557]
## Type of issue
Bug

## Description
I installed prebid via NPM. The readme is clear in explaining how to import the modules which is useful. It works fine with webpack. However the issue I am having is when I run tests which use the prebid.js code, the test runners try to run the code in node_modules which contains the prebid code:

```/Code/tests/node_modules/prebid.js/src/prebid.js:3
import {getGlobal} from './prebidGlobal.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._compile (/Users/hemangrajyaguru/Code/tests/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.newLoader [as .js] (/Users/hemangrajyaguru/Code/tests/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

Have you encountered this before? Because it now means all the tests fail and all I really want is to execute the prebid code but not worry about the test runner checking the prebid code. I am using my package as a module and using imports.

I have a basic example here:
```import pbjs from 'prebid.js';
import 'prebid.js/modules/rubiconBidAdapter.js';
import 'prebid.js/modules/appnexusBidAdapter.js';

export default class PrebidLoader {

    constructor() {
        pbjs.processQueue();
    }

};
```

Would love to know how to get around this as it's become a blocker.

**Comment by dgirardi** [comment]
> Have you encountered this before?

It may or may not be similar to https://github.com/prebid/Prebid.js/issues/10265

The error message shows that the problem is with the build system / test runner (the tests are not compiled as an es6 module), but I can't try to suggest a fix without knowing what you're using or how you set it up. Are you able to provide a minimal demo repository?

**Comment by hemdagem** [comment]
Here is a minimal demo repository https://github.com/hemdagem/prebid-tests. if you run `npm run test` you will see the error. Thanks.

**Comment by dgirardi** [comment]
Unfortunately that's a little too minimal :) as the README says, prebid source needs to be passed through babel; this applies to tests as well. You mentioned you're using webpack, so if this is your `webpack.conf.js`:

```javascript
const path = require('path');
const fs = require('fs');

module.exports = {
    mode: 'production',
    entry: {
        main: './index.js',
        test: fs.readdirSync('test').map(fn => `./test/${fn}`)
    },
    module: {
        rules: [
            // this separate rule is required to make sure that the Prebid.js files are babel-ified.  this rule will
            // override the regular exclusion from above (for being inside node_modules).
            {
                test: /.js$/,
                include: new RegExp(`\\${path.sep}prebid\\.js`),
                use: {
                    loader: 'babel-loader',
                    // presets and plugins for Prebid.js must be manually specified separate from your other babel rule.
                    // this can be accomplished by requiring prebid's .babelrc.js file (requires Babel 7 and Node v8.9.0+)
                    // as of Prebid 6, babelrc.js only targets modern browsers. One can change the targets and build for
                    // older browsers if they prefer, but integration tests on ie11 were removed in Prebid.js 6.0
                    options: require('prebid.js/.babelrc.js')
                }
            }
        ]
    }
};
```

then you can run mocha with `npx webpack -c webpack.conf.js && npx mocha dist/test.js`. However - Prebid also needs a browser, so if you want to include it in your tests you need to run them in a browser (as it is it will fail to find the `window` object). 

Not sure how much of this is already part of your workflow - mocha supports [in-browser testing](https://mochajs.org/#running-mocha-in-the-browser) but from what I can tell it does not provide a nice CLI option to do so. My solution would be [karma](https://karma-runner.github.io/latest/index.html), but I see there's also lighter solutions like [mocha-headless-chrome](https://www.npmjs.com/package/mocha-headless-chrome).

**Comment by hemdagem** [comment]
Thanks, will close this for now
