### ISSUE TITLE
Floors module conflates skipped and not found

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10568]
## Type of issue
Bug?

## Description
https://github.com/prebid/Prebid.js/blob/dea49c275c2931cd689268ac7d72c6356fbaacbe/modules/priceFloors.js#L396C38-L396C39 marks floors as skipped if a rule is not found, but this should have a different name or perhaps an additional indicator to skipped to delineate randomly skipped vs not found.

**Comment by dgirardi** [comment]
Do you have an example where it is a problem? I think that piece of logic looks for _any_ floor in the auction, I wouldn't call that not found.

**Comment by patmmccann** [comment]
Basically, skip reason - randomization or rule not found as a new attribute

**Comment by dgirardi** [comment]
Looking at the code I think skipped means skipped. Do you have an example where it means no rule found? Or do you mean that it shouldn't say skipped if you set floors without any rules?

**Comment by patmmccann** [comment]
just marking that this is solved internally at https://github.com/cafemedia/adthrive-prebid/pull/395/files and pending submission @whorst

**Comment by patmmccann** [comment]
solved in #11040
