### ISSUE TITLE
RegisterSignal fails if Gam not available

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10565]
## Type of issue
Feature request

## Description
[
RegisterSignalSource 
](https://github.com/prebid/Prebid.js/blob/b7ff9fe201cce20e8e82dfebe9981d1917e888f6/modules/userId/index.js#L674) kicks out if gpt is not ready; but some publishers may prefer to add to the gpt queue

**Comment by dgirardi** [comment]
Looking more into this - `registerSignalSources` is part of the publisher API and Prebid does not invoke it on its own. It's straightforward for publishers to call it only after GPT is loaded, and that's also what our [example](https://docs.prebid.org/dev-docs/publisher-api-reference/registerSignalSources.html) does. I don't think that re-queueing it again adds much value.

**Comment by patmmccann** [comment]
Agreed
