### ISSUE TITLE
Rename fledge configuration options

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#10573]
## Type of issue
Improvement

## Description

`fledgeForGpt` defines two top-level config options, `fledgeEnabled` and `defaultForSlots`. The latter has a very generic sounding name and should probably be scoped down to something like `setConfig({fledge: {enabled: true, default: true}})`. We can also consider renaming config and module to `paapi` if we are now past the codename stage.

**Comment by patmmccann** [comment]
I prefer to keep GPT in the name to distinguish from #9481
