### ISSUE TITLE
url: null  when using url: encodeURIComponent(window.location.href) with dfpAdServerVideo module - video

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#10580]
## Type of issue
I think the fix in #10575 now leads url: null, if using: url: encodeURIComponent(window.location.href),

## Description
using: url: encodeURIComponent(window.location.href),  to auto pick out the page url, now leads to url: null, an offset of #10575 fix , I think

description_url: encodeURIComponent(window.location.href),  still works and return the correct "page url"

## Steps to reproduce
![playlistUIverticalAmazonParallelReBid_html_—_Prebid_Publishers__Workspace_](https://github.com/prebid/Prebid.js/assets/8503167/08977cc4-89e4-4914-b067-ea14f8e097b8)

![DevTools_-_127_0_0_1_5502_prebid_VideoDemo_DemoSite_pages_playlistUIverticalAmazonParallelReBid_html](https://github.com/prebid/Prebid.js/assets/8503167/bd6f18e2-1426-4ced-a583-cdb72c85dddb)

hard code the url and still works as expected:

![playlistUIverticalAmazonParallelReBid_html_—_Prebid_Publishers__Workspace_](https://github.com/prebid/Prebid.js/assets/8503167/5463d1e3-8067-40f9-aaf4-580ac2685edb)

![DevTools_-_127_0_0_1_5502_prebid_VideoDemo_DemoSite_pages_playlistUIverticalAmazonParallelReBid_html](https://github.com/prebid/Prebid.js/assets/8503167/1a81cd6a-1bc5-488c-9d3f-e46b7ffe50cf)

Also does it , if you dont set "url" at all, which is ment to allow ima sdk to "fetch the url" on its own, sort of the "default ima sdk" setting:

![playlistUIverticalAmazonParallelReBid_html_—_Prebid_Publishers__Workspace_](https://github.com/prebid/Prebid.js/assets/8503167/9da8ec14-f4b9-472e-97c1-c5181606517b)

![DevTools_-_127_0_0_1_5502_prebid_VideoDemo_DemoSite_pages_playlistUIverticalAmazonParallelReBid_html](https://github.com/prebid/Prebid.js/assets/8503167/2198d6f8-5521-46cb-9346-264305587718)

## Platform details
mac, chrome, P 8.18.0

**Comment by karimMourra** [comment]
Unassigning myself; based on the code changes, it's not clear that this is caused by #10575 
```
function getDescriptionUrl(bid, components, prop) {
  return deepAccess(components, `${prop}.description_url`) || encodeURIComponent(dep.ri().page);
}
```

it doesn't seem like `encodeURIComponent(dep.ri().page)` would even get called in this scenario.

**Comment by spormeon** [comment]
i've actually been back to P7.37.0 and still does it then, might of just been completely luck found it when testing 8.18.0 and thought had something to do with 10575, it could go way way way back

**Comment by dgirardi** [comment]
@spormeon  I don't understand how to reproduce this. Is it consistent? With what configuration?

**Comment by spormeon** [comment]
the bidsbackhandler video demo in repo gets you it, if add a line to the params:  url:encodeURIComponent(window.location.href),
if hard code
url: 'https://test.com',     it will work

search ima in consule, get/ see the url with the video tag sent on it, check "payload"

p.s. not on my usual machine, so cant post you it to look at , at mo

**Comment by patmmccann** [comment]
@spormeon we're having trouble making heads or tails out of your steps to reproduce. Could you start over and list them in more detail?

**Comment by spormeon** [comment]
my bad on this one, its actually ima sdk doing it, perills of a non authorised (google) test domain
