### ISSUE TITLE
Minified build name

### ISSUE THREAD

**Issue by EskelCz** [prebid/Prebid.js#10583]
## Type of issue
Question

## Description
It's almost a comically small issue, but could you change the name of the production build (produced by `gulp build`) to `prebid.min.js`? I think it's a useful convention. Right now I have to rename it after every build and I would guess I'm not alone. :) The minutes and inefficiencies add up.
Thanks for your consideration.

### Expected results
Minified build be named `prebid.min.js`

### Actual results
The name is the same as the development build: `prebid.js`. Maybe there is some important reason for it that I'm ignorant of. :)

**Comment by dgirardi** [comment]
Currently you can do `gulp build --bundle-name "prebid.min.js"`. Would that suffice? changing the default is breaking and IMO not worth the hassle.

**Comment by patmmccann** [comment]
I agree with @dgirardi

**Comment by EskelCz** [comment]
@dgirardi Ah, that's just what I needed. Thanks a lot.
