### ISSUE TITLE
Bucksense bid adapter: TCF2 denied 'fetchBids' due to missing gvlid

### ISSUE THREAD

**Issue by silviabernardini80** [prebid/Prebid.js#10596]
## Type of issue
Question/support

## Description
Buckense is not recognized as a valid bidder (adapter) since prebid 8.13

## Steps to reproduce

Go to https://www.oggi.it/?prebid-version=prebid8.13.0.js&pbjs_debug=true
Look at console logs
You can see the error:

prebid8.13.0.js?v=0:5 Prebid WARNING: Activity control: TCF2 denied 'fetchBids' for 'bidder.bucksense'

## Test page
https://www.oggi.it/?prebid-version=prebid8.13.0.js&pbjs_debug=true

### Expected results
 Buscksense should be recognized as a valid bidder (adapter) and participate in the auction

### Actual results
We got the alert  written above

**Comment by patmmccann** [comment]
it appears you forgot to put your gvlid in your adapter

![image](https://github.com/prebid/Prebid.js/assets/1683175/646d93d6-e45e-4b0b-9b17-e25c65bffd62)

**Comment by silviabernardini80** [comment]
Thank you very much for support!
We opened the pull request to fix https://github.com/prebid/Prebid.js/pull/10600

Regards
Silvia
