### ISSUE TITLE
GPT interstitial support - deferred rendering

### ISSUE THREAD

**Issue by ourcraig** [prebid/Prebid.js#10594]
## Type of issue
Feature Request

## Description
Currently when the Prebid Universal Creative is returned from Google Ad Manager for an out-of-page GPT interstitial slot, it renders instantly despite not being viewable. Prebid recommends the use of `adUnit.deferredBilling: true` to defer the `onBidBillable` event from firing on ad render, and calling `pbjs.triggerBilling(<deferredBid>)` to fire the `onBidBillable` event when the interstitial becomes viewable. However, it seems that bid adapters are not currently listening for the `onBidBillable` event ([ref](https://github.com/search?q=repo%3Aprebid%2FPrebid.js+onBidBillable&type=code)).

To have wider support for GPT interstitials, I would like to request Prebid support for **deferred rendering** using something like the below:

```
<script src = "https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/%%PATTERN:hb_format%%.js"></script>
<script>
  var ucTagData = {};
  var render = function() {
    try {
      ucTag.renderAd(document, ucTagData);
    } catch (e) {
      console.log(e);
    }
  }
  ucTagData.adServerDomain = "";
  ucTagData.instl = "%%PATTERN:hb_instl%%";
  ucTagData.pubUrl = (ucTagData.instl === "true") ? "*" : "%%PATTERN:url%%";
  ucTagData.adId = "%%PATTERN:hb_adid%%";
  ucTagData.cacheHost = "%%PATTERN:hb_cache_host%%";
  ucTagData.cachePath = "%%PATTERN:hb_cache_path%%";
  ucTagData.uuid = "%%PATTERN:hb_cache_id%%";
  ucTagData.mediaType = "%%PATTERN:hb_format%%";
  ucTagData.env = "%%PATTERN:hb_env%%";
  ucTagData.size = "%%PATTERN:hb_size%%";
  ucTagData.winurl = "%%PATTERN:hb_winurl%%";
  ucTagData.winbidid = "%%PATTERN:hb_bidid%%";
  ucTagData.mobileResize = "hb_size:%%PATTERN:hb_size%%";
  ucTagData.requestAllAssets = true;
  ucTagData.clickUrlUnesc = "%%CLICK_URL_UNESC%%";
  if (ucTagData.instl === "true") {
    window.addEventListener('message', function(event) {
      try {
        var data = JSON.parse(event.data);
        if (data.type === "rewarded" && data.message === "visible") {
          render();
        }
      } catch(e) {
      	console.log(e);
      }
		});
  } else {
    render();
  }
</script>
```

This example PUC checks for `hb_instl:true` and uses it to defer the rendering until GPT fires the `impressionViewable` event.

## Test page
[pbjs-instl-tests](https://github.com/ourcraig/pbjs-instl-tests)
* [deferred-render](https://ourcraig.github.io/pbjs-instl-tests/deferred-render/) shows an example of rendering deferred until the GPT interstitial is triggered

## Other information
* GPT interstitial has a frequency cap of one view per user per hour -- to refresh it use `localStorage.clear()` on the test page
* GPT docs for out-of-page interstitial [here](https://developers.google.com/publisher-tag/samples/display-web-interstitial-ad)

**Comment by patmmccann** [comment]
A couple notes: This feels quite a bit less desirable than pre-rendering from a ux standpoint and will certainly drop the viewability of the units a bunch, and also make the advertiser numbers far from the publisher numbers (which will be by definition 100% if they use GAM). I'd much rather get SSPs to support onBidBillable, and it seems we have some in-roads at Magnite (which is busy re-writing their adapter), Pubmatic (which did the feature, thanks @jlquaccia ), and IX. 

Other than a strong desire to move away from the PUC, this doesnt feel so horrible, except if it delays or derails the preferred path at leader SSP companies.

**Comment by patmmccann** [comment]
Ideal behavior discussed in the committee seems to be:

if an ad unit is tagged with deferred billing, but the ssp does not support it, treat the markup from that ssp as deferred render. PBS demand would go into the deferred render case until PBS adapter has support for triggerBurl

**Comment by patmmccann** [comment]
linking with #5917
