### ISSUE TITLE
Adapters Not Using getConfig for Coppa

### ISSUE THREAD

**Issue by ChrisHuie** [prebid/Prebid.js#10620]
Axis, Minute Media, and Rise bid adapters are not accessing coppa using getConfig. It is a standardized prebid.js rule to do so

**Comment by patmmccann** [comment]
Last time we discussed this, we concluded the opposite, that the goal is to never use getconfig bc that might be wrong, just like tmax

**Comment by ChrisHuie** [comment]
Yeah. Bret and I talked about this a bit but lets further discuss in our next meeting. Policy around coppa for reviewers is that it has to come from getConfig. So reviewers check for this. It makes more sense to come from the ortb2 object but since it has been on the review guide 99% use getConfig. So this would keep it consistent across adapters or on the next major release we switch all the getConfigs over?
