### ISSUE TITLE
TCF2 denied 'fetchBids' for 'bidder.seedtag'

### ISSUE THREAD

**Issue by ybootin** [prebid/Prebid.js#10632]
## Type of issue

Question/support

## Description

We have an issue with our bidder on one publisher where we get this error message `TCF2 denied 'fetchBids' for 'bidder.seedtag'` 
The problem seams to come from a rule from activity controls, but we are unable to understand the exact issue
## Steps to reproduce

Just go on this page
https://www.gpfans.com/nl/f1-nieuws/85664/het-tijdschema-voor-de-grand-prix-van-grootbrittannie/?pbjs_debug=true

and wait for the error message to appear
<img width="739" alt="Capture d’écran 2023-10-20 à 14 17 17" src="https://github.com/prebid/Prebid.js/assets/1788867/709356f2-3d68-451e-b76d-57719c100b20">

## Test page

https://www.gpfans.com/nl/f1-nieuws/85664/het-tijdschema-voor-de-grand-prix-van-grootbrittannie/?pbjs_debug=true

### Expected results
Seedtag should be recognized as a valid bidder (adapter) and participate in the auction

### Actual results
Seedtag bidder rejected from the auction

**Comment by dgirardi** [comment]
I see a different error - it looks like the seedtag module is not on that page - was it updated since this issue?


![Image](https://github.com/prebid/Prebid.js/assets/10151381/e96350f2-488a-4481-99f5-20873ed9e154)

**Comment by ybootin** [comment]
I close it, the problem was coming from the website configuration. The page has been updated and we don't have anymore the issue
