### ISSUE TITLE
fledgeForGpt: clarify contextual bids and IG signals comparison

### ISSUE THREAD

**Issue by onetag-dev** [prebid/Prebid.js#10648]
## Type of issue

Question
## Description

In the context of the fledgeForGpt module, it's not yet clear how the top-level seller (in this case, GPT) compares contextual bids with those derived from IG signals. In cases of FLEDGE eligibility, adapters can return a tuple consisting of contextual bids and FLEDGE Auction Configs inside the `interpretResponse` function. As described in various issues, we should expect that the top-level runner can choose the winning bid between the 'classic' contextual auction and the FLEDGE one.

Is this assumption correct? If so, how is the comparison performed? Does GPT compare the bid value of the contextual winner with that of the FLEDGE auction? It would be great to have some documentation references, thank you.

## Other information

- https://github.com/prebid/Prebid.js/issues/7634

**Comment by patmmccann** [comment]
Wrong forum; please ask the gam team
