### ISSUE TITLE
getConfig cleanup of consent management

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10658]
This is a serious bug in several adapters. Consent management needs to come off the request.

https://github.com/prebid/Prebid.js/blob/56292c4672a0b19bee34840dca93bd3e1e5b8afe/modules/aidemBidAdapter.js#L111
https://github.com/prebid/Prebid.js/blob/56292c4672a0b19bee34840dca93bd3e1e5b8afe/modules/apstreamBidAdapter.js#L295
https://github.com/prebid/Prebid.js/blob/56292c4672a0b19bee34840dca93bd3e1e5b8afe/modules/sirdataRtdProvider.js#L85
https://github.com/prebid/Prebid.js/blob/56292c4672a0b19bee34840dca93bd3e1e5b8afe/modules/madvertiseBidAdapter.js#L56

**Comment by patmmccann** [comment]
@RemiSirdata @gsollazzo @darkstarac please take a look

**Comment by darkstarac** [comment]
@patmmccann Hello Patrick. Sorry to bother you, but it's not very clear to us what fix is needed. Have you got some suggestions on this issue ?

**Comment by darkstarac** [comment]
@patmmccann Hello Patrick ? Any hint on this issue ? As asked before we some clarification about the problem.

**Comment by patmmccann** [comment]
@darkstarac consent should not come from a getConfig call. You should only need to access the request object

**Comment by nouchy** [comment]
> This is a serious bug in several adapters. Consent management needs to come off the request.
> 
> https://github.com/prebid/Prebid.js/blob/56292c4672a0b19bee34840dca93bd3e1e5b8afe/modules/aidemBidAdapter.js#L111
> 
> https://github.com/prebid/Prebid.js/blob/56292c4672a0b19bee34840dca93bd3e1e5b8afe/modules/apstreamBidAdapter.js#L295
> 
> https://github.com/prebid/Prebid.js/blob/56292c4672a0b19bee34840dca93bd3e1e5b8afe/modules/sirdataRtdProvider.js#L85
> 
> https://github.com/prebid/Prebid.js/blob/56292c4672a0b19bee34840dca93bd3e1e5b8afe/modules/madvertiseBidAdapter.js#L56
This has been fix, please see https://github.com/prebid/Prebid.js/pull/11524. Thanks !
