### ISSUE TITLE
prebid.js 8.12 adds loading ads after 30 seconds

### ISSUE THREAD

**Issue by ProcnerKacper** [prebid/Prebid.js#10661]
## Type of issue
help wanted

## Description

I updated from 7 to the latest version of prebid.js 8.12 after that ads started to loading after 30s and no ads were registered. Additionally, I don't see in logs that the consent manager works either.

## Test page

https://cool-idea.pl/chlodnik-doskonaly-przepis-na-ukojenie-i-zdrowe-ochlodzenie-w-upalne-dni,64935?pbjs_debug=true&bidio_debug=true

## Platform details
Prebid.js 8.12, node:12.16.1 

used modules 
  "adfBidAdapter",
  "adponeBidAdapter",
  "consentManagement",
  "criteoBidAdapter",
  "currency",
  "eplanningBidAdapter",
  "openxBidAdapter",
  "rtbhouseBidAdapter",
  "rubiconBidAdapter",
  "smartadserverBidAdapter",
  "sovrnBidAdapter",
  "visxBidAdapter",
  "adagioBidAdapter",
  "schain",
  "sharedIdSystem",
  "voxBidAdapter",
  "medianetBidAdapter"

**Comment by dgirardi** [comment]
On that page it looks like `requestBids` is never called. Could you point me to where in it you set up & call prebid?

**Comment by ProcnerKacper** [comment]
all prebid setup is in the last script tag without source  in head section

**Comment by dgirardi** [comment]
The generated script tag uses `bpbjs` as the prebid global var name, but the Prebid bundle uses the default `pbjs`:

![image](https://github.com/prebid/Prebid.js/assets/10151381/de15a9a6-a9c1-48dd-bc06-71eac9721bbd)
![image](https://github.com/prebid/Prebid.js/assets/10151381/25d9f8ae-7910-48dc-b086-11972fbc9efc)

**Comment by ProcnerKacper** [comment]
thank you! so many hours I spent on this looking for something wrong in the config...
