### ISSUE TITLE
Consent Management module: enrich requests on regs.ext.dsa

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10688]
## Type of issue
Feature

## Description
IABE and IABTL are working on compliance with Digital Services Act for February 17 2024 (https://ec.europa.eu/commission/presscorner/detail/en/qanda_20_2348)
The consent management module should add regs.ext.dsa once the spec is published (late November or early December 2023) if the publisher thinks they are a 'platform'

Spec now available 
https://github.com/InteractiveAdvertisingBureau/openrtb/pull/152/files#diff-5ab9e62a17f36edd71ae458147dbf0150393a53088e3a39620385821dedf6c7d

**Comment by patmmccann** [comment]
Maybe we should write a unit test, we should definitely document how to set the request object.

**Comment by dgirardi** [comment]
Pending: documentation on the dsa control module, also calling out how to configure regs.ext.dsa.

**Comment by dgirardi** [comment]
Proposal: `consentManagementTcf` takes a new config flag

```
setConfig({
    consentManagement: {
         gdpr: {
                dsaPlatform: true
         }
    }
})
```

that when enabled, sets `ext.dsa.required` to 3
