### ISSUE TITLE
User id Module sample rate

### ISSUE THREAD

**Issue by jdwieland8282** [prebid/Prebid.js#10705]
# Problem
Publishers are unable to test and run experiments natively in Prebid and must rely on partners to help set up tests & control groups when they want to test various `setConfig()` objects. 

## example 
A publisher may wish to test CPM change for 2 different `setConfig()`s

### 1
```
 pbjs.setConfig({
     userSync: {
         userIds: [{
             name: "sharedId",
             storage: {
                 type: "cookie",
                 name: "_sharedid",         
                 expires: 365         
             }
         }]
     }
 });
```
### 2
```
 pbjs.setConfig({
     userSync: {
         userIds: [{
             name: "OtherID",
             storage: {
                 type: "cookie",
                 name: "_OtherID",       
                 expires: 365             
             }
         }]
     }
 });
```
## UseCase

1. As a publisher I want to test how my inventory monetizes when I include a userid module subadapter like sharedid, I want to be able to compare the presence of sharedid against no user id at all.
2. 1. As a publisher I want to test how my inventory monetizes when I include a userid module subadapter like sharedid, I want to be able to compare the presence of sharedid against a different user id such as "OtherID"

## Requirements

1. `setConfig()` should support a sample rate int for the test cohort. Where _n_ percent of the time the `setConfig()` loads one way, and _n_ of the time it loads a different way. 
2. Prebid must signal back to the publisher what imps were part of the test and which were part of the control. 
ex.
- configureable response endpoint where Impression id and cohort label (test or control) are logged. 

```
curl --location 'http://pub.com/prebid/experiement?
--header 'Content-Type: application/json' \
--data '{
  "entries": [
    {
      "impression": 12345,
      "cohort": "test" //control
    }
  ]
}'

**Comment by patmmccann** [comment]
I think we documentation we can completely solve: 

`if Math.random() > .5 then set a else set b
if a setconfig(one way)
if b setconfig(other way)
googletag.setTargeting(test=[a or b])
and/or the generic analytics adapter could be aware of the test`

**Comment by 3link** [comment]
@patmmccann Very nice initiative! Thanks for tagging. LGTM.

**Comment by jdwieland8282** [comment]
So long as the requirements are met I'm express support for this implementation approach.

**Comment by dgirardi** [comment]
This is marked in progress - is it in progress?
