### ISSUE TITLE
floor price module should pick the highest matching floor not the first matching floor

### ISSUE THREAD

**Issue by PascalSalesch** [prebid/Prebid.js#10708]
## Type of issue
 - Feature

## Description
The floor price module currently only retrieves the first matching rule via `getFirstMatchingFloor`.
Which sorts the rules by ascending number of occurences of wildcards `*`.

Imo, it would make more sense to pick the highest floor.

## Steps to reproduce

```
{
   "data":{
      "schema":{
         "fields":[
            "device",
            "country"
         ]
      },
      "values":{
         "desktop|*":3,
         "*|ch":5
      }
}
```

### Expected results

I would expect all matching rules to apply. Using the rule with the highest floorRuleValue will accomplish that.

### Actual results

With the above configuration, if you're on a desktop in switzerland (ch) the floorRuleValue will be 3, rather than 5:

```
{
    "floorMin": 0,
    "floorRuleValue": 3,
    "matchingData": "desktop|ch",
    "matchingRule": "desktop|*",
    "matchingFloor": 3
}
```

**Comment by patmmccann** [comment]
It is specifically documented and designed not to do this. Why do you have this expectation?

**Comment by patmmccann** [comment]
This feels like quite a painful change that would affect just as many or more parties negatively in transition pain as it would benefit. OP could easily solve his issues by returning different rules files in different countries rather than having his js be country-aware.
