### ISSUE TITLE
Adding smart bidder to the header bid expert chrome extension

### ISSUE THREAD

**Issue by jdelhommeau** [prebid/Prebid.js#1071]
## Type of issue
headerbid expert new pattern

## Description
Hi guys, could you please add the below pattern in headerbid expert chrome extension to detect smart RTB+ prebid adapter?

prg.smartadserver.com/prebid

Thank you very much.

Julien

**Comment by matthewlane** [comment]
How should the label for this bidder appear: `Smart`, `SmartAdServer`, something else?

**Comment by jdelhommeau** [comment]
Hi @matthewlane ,

Thank you for looking into it. the label should be "SmartRTB+".

Thank you very much.

Julien

**Comment by matthewlane** [comment]
SmartRTB+ is now in Headerbid Expert 1.5.12
