### ISSUE TITLE
if adUrl is passed to renderAd rendered iframe is not visibile

### ISSUE THREAD

**Issue by pez46** [prebid/Prebid.js#10734]
## Type of issue

question

## Description

if adUrl is passed instead of ad in renderAd() function, it calls createInvisibleIframe which has style.width = 0 and style.height = 0, 
so even if width and height attribute is set correctly the style ovverride these properties and iframe remain not visible.
is this the normal behaviour?

![image](https://github.com/prebid/Prebid.js/assets/50925199/e45f493d-2215-4fa1-a9db-fe56577ea2f4)

### Expected results

I think that after inserting iframe in document it should be updated with correct style

## Platform details

prebid8.23.0
nexx360 adapter with test ssP

**Comment by pez46** [comment]
@patmmccann any advice?

**Comment by pez46** [comment]
this is the actual solution, but i think it is a bad workaround:
```
pbjs.onEvent('adRenderSucceeded', (params) => {
   console.log(params);
   const GframeDocument = params.doc;
   const iframeBadStyle = GframeDocument.querySelector("iframe");
   console.log(iframeBadStyle);
				
   iframeBadStyle.style.width = ""+params.bid.width+"px";
   iframeBadStyle.style.height = ""+params.bid.height+"px";			
});
```

**Comment by dgirardi** [comment]
Closing this with https://github.com/prebid/Prebid.js/pull/9647
