### ISSUE TITLE
Prebid outstream player not working

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/Prebid.js#10731]
## Type of issue
The standard prebid.js outstream player is currently not working

## Description
First, sorry for bringing this up here, but my PR is not getting any attention in https://github.com/prebid/prebid-outstream which I guess is because nobody is actively watching it.

I was investigating if I could use this player for a publisher, but I couldn't even get the project to compile due to various TypeScript errors, changes in Prebid.js so the video response wasn't picked up correctly and changes in Fluid player that made it incompatible with the implementation.

I'd be happy if someone could take a look at this PR: https://github.com/prebid/prebid-outstream/pull/32

Thanks!

## Steps to reproduce
See above

**Comment by muuki88** [comment]
Thanks @bjorn-lw . I looked at the PR and merged it. There's currently no release process or anything. Sorry about that :cry:

**Comment by bjorn-lw** [comment]
Thanks!
