### ISSUE TITLE
FledgeForGPT module: Suggest Auction Environment gating should be solely on runAdAuction()

### ISSUE THREAD

**Issue by dmdabbs** [prebid/Prebid.js#10748]
In a conversation with Roni G about auction environment signaling, he shared that PB checks both RAA() and JAIG().

https://github.com/prebid/Prebid.js/blob/b7744ecc5b537ba652be81904bf6273f8a7bb101/modules/fledgeForGpt.js#L115-117

`return 'runAdAuction' in navigator && 'joinAdInterestGroup' in navigator`

PAAPI affords sites independent Permissions-Policies control over IG maintenance and running auctions.  A pub may choose to permit no one or only itself to call `joinAdInterestGroup`. Consider simplifying this to detecting `runAdAuction`.

FWIW, I posted a question to the [open pr](https://github.com/WICG/turtledove/pull/910) for "Feature detecting Protected Audience."

**Comment by patmmccann** [comment]
Do permissions policies delete functions from navigator?

**Comment by rdgordon-index** [comment]
Not entirely clear IMHO - https://github.com/w3c/webappsec-permissions-policy/blob/main/permissions-policy-explainer.md#how-are-features-disabled

**Comment by patmmccann** [comment]
appears to be awaiting an answer here https://github.com/WICG/turtledove/pull/910/files#r1399521249

**Comment by patmmccann** [comment]
Looks like this has been answered and Jaig will remain found in navigator even when permissions restrict It. Is this good to close?

**Comment by dmdabbs** [comment]
Ja.
