### ISSUE TITLE
GAM error for TCF 2.2 using Prebid Universal Creative and jsdelivr

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#10741]
Google Ad Manager (GAM) users who upgrade to TCF 2.2 may get an error message when trying to serve the Prebid Universal Creative: "Ad technology provider not specified in user consent settings"

The instructions at https://docs.prebid.org/adops/gam-creative-banner-sbs.html describe how to set `jsdelivr` as the ad tech provider if you're using the PUC that Prebid hosts there. 

We believe the error coming from GAM with TCF 2.2 is because jsdelivr does not yet exist on the [TCF 2.2 Global Vendor List](https://vendor-list.consensu.org/v3/vendor-list.json). We have reached out to our always-helpful contact at jsdelivr who has confirmed they're looking into the situation.

However, there is not a committed timeline for resolution, so in the meantime, if there are publishers whose revenue is affected by this issue, here are some potential workarounds that you can discuss with your legal counsel.

### 1. Turn off the Creative Consent Check

**Do this only after confirming with your legal counsel.**

1. From the AdManager interface, choose "Privacy & Messaging" from the left-nav bar
2. Select GDPR
3. Click Get Started if it appears
4. Select the 'Settings' tab
5. Unselect both boxes in the "Check creatives for consent" section of the settings page
6. Save

If this doesn't work, go on to the next item

### 2. Disconnect your PUC creatives from jsdelivr

**Do this only after confirming with your legal counsel.**

Edit each GAM creative that loads the Prebid Universal Creative and update the "Associated ad technology providers" to remove jsdelivr, instead choosing "nothing to declare".

### 3. Replace your GAM creatives

(this can probably be done without consulting legal counsel)

Instead of loading the PUC code from jsdelivr like this:
```
<script src = "https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/%%PATTERN:hb_format%%.js"></script>
<script>
  ...
```

You could replace that code with a number of alternatives:

1. Host the PUC yourself, updating cdn.jsdelivr.net/npm/prebid-universal-creative@latest to wherever you're actually hosting it.
2. Copy the contents of https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js into each creative.
3. For non-safeframed banner and outstream-video creatives, you can use the simplified creative body noted at https://docs.prebid.org/overview/prebid-universal-creative.html#alternate-approaches
4. For Banner Safeframes, you could copy the contents of https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/x-domain/creative.html into each creative.

**Comment by patmmccann** [comment]
We'll add the alternatives in (3) to docs.prebid and mark as ready for dev

**Comment by bretg** [comment]
jsdeliver has been added to the TCF 2.2 vendor list.
