### ISSUE TITLE
Feature request: reuse GVL ID of the original adapter with an optional flag

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/Prebid.js#10759]
## Type of issue
bug

## Description
I wanted to update my prebid.js from 8.2 to 8.20 and doing so I now have the following kind of warning in the console : 
`Alias '${alias}' will NOT re-use the GVL ID of the original adapter ('${spec.code}', gvlid: ${spec.gvlid}). Functionality that requires TCF consent may not work as expected.`
I've seen it's related with issue #9717 but I haven't found the logic behind this discussion. Here is my use case (since prebid 1.11) : We are working with more than one appnexus seat on the same adunits. For instance, if for my adunit I have the following bidders : 
```
{bidder:"appnexus",params:{placementId: 12345}},
{bidder:"appnexus",params:{placementId: 67890}}
```
With placementId 12345 related to one appnexus seat and placementId 67890 related to another appnexus seat, then appnexus adapter will make one unique call for both of these placements and will rejected it because one call must be about only one seat. Response from appnexus would be : 
`{"error":"Could not parse valid tag in request"}`
So I am using aliases like this : 
```
pbjs.aliasBidder("appnexus","seat1");
pbjs.aliasBidder("appnexus","seat2");
```
and adunits conf : 
```
{bidder:"seat1",params:{placementId: 12345}},
{bidder:"seat2",params:{placementId: 67890}}
```
This makes that I have two appnexus calls, one for each seat.  For these aliases, it seems to me like it is legitimate to use the original bidder GVL ID. 

Unfortunately now I no longer can. It looks like a breaking change, and I actually don't really understand the logic behind the fact that aliases could not re-use the original bidder's GVL ID. Isn't it the responsability of the who configures it ?

**Comment by dgirardi** [comment]
You can specify gvlid in the options of `aliasBidder` - https://docs.prebid.org/dev-docs/publisher-api-reference/aliasBidder.html

Note that the alias/gvlid behavior was not changed, we just added a warning. As far as I know your aliases would have failed consent checks all along -  but up until 8.11,  bidders often did not actually need consent (only [purpose legitimate interest](https://github.com/prebid/Prebid.js/pull/10367)). With that fix a missing gvlid is more of a problem, that's the reason for warning about aliases.

**Comment by Sir-Will** [comment]
> I think we can improve the message to make it clear that you can still re-use the gvlid, it just won't default to it.

To extend on that, it would be very helpful if the `pbjs.aliasBidder` function accepts an option to make it re-use the gvlid of the bidder.

**Comment by dgirardi** [comment]
That's a good suggestion - tentative name for the option: `useBaseGvlid`

**Comment by patmmccann** [comment]
This strikes me as in the 'i have no idea if this complies with the law but let's just try it bc yolo' category of options. I'm not sure if this is wise to facilitate, as publishers will just see it as button to press to get everything working even if it puts them at target high risk of sharing data with a non-consented party.

**Comment by Sir-Will** [comment]
Is the risk of using the wrong gvlid not higher, than using the base gvlid incorrectly with an alias?

If an SSP wants an alias set, they also share the gvlid. If I want to use a simple alias, I have to look up the gvlid with the risk of finding the incorrect one.

**Comment by patmmccann** [comment]
after chatting with @dgirardi live; I'm convinced it is reasonable to have `useBaseGvlid` as an option defaulting to off. Marking ready for dev
