### ISSUE TITLE
Clean up `constants.json`

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#10829]
## Type of issue
Improvement

## Description

[`constants.json`](https://github.com/prebid/Prebid.js/blob/master/src/constants.json) is included in every bundle, but its contents are not always needed:

 - A good portion of it is used only for native and should be excluded when native is disabled
 - `FLOOR_VALUES` is used exclusively by the pubmatic analytics adapter

**Comment by muuki88** [comment]
@dgirardi would it be sufficient to replace `constants.json` with `constants.js` and all the imports using it?

**Comment by dgirardi** [comment]
@muuki88 yes, with some caveats:

- if something imported only by one module, it should be moved into that module 
- if something's imported only by modules, it should be moved into `libraries`
