### ISSUE TITLE
undefined is not an object (evaluating 'p.width')

### ISSUE THREAD

**Issue by amanjain** [prebid/Prebid.js#1083]
## Description
We keep getting ```undefined is not an object (evaluating 'p.width')``` once a while.

![image](https://cloud.githubusercontent.com/assets/435017/24385510/126651b6-1388-11e7-9877-43c9fe778964.png)

**Comment by mkendall07** [comment]
Do you have any reproduction steps? It looks like this might be inside an adapter, do you know which one?

**Comment by mkendall07** [comment]
Any other info you can provide?

**Comment by dbemiller** [comment]
Closing because there aren't any steps to reproduce, and the issue is stale.
