### ISSUE TITLE
Renaming Yahoo bid adapter module for PB9

### ISSUE THREAD

**Issue by slimkrazy** [prebid/Prebid.js#10836]
## Type of issue
Question

## Description
Hi folks,

We understand that renaming a bid adapter module is a breaking change, so we can only do this on major releases. Just wondering what the process would be for making such a change? Will there be a PB9 branch opened up soon that we can make the change to ourselves or is this something we need to open a issue for that the core maintainers will handle?

**Comment by patmmccann** [comment]
Let's keep this issue to track. I tagged the issue as 9.0. we plan to release in q2

**Comment by patmmccann** [comment]
@slimkrazy you're welcome to proceed to pr the 9.0 branch
