### ISSUE TITLE
Issues when using Prebid.js 8.0 or higher

### ISSUE THREAD

**Issue by codeblue001** [prebid/Prebid.js#10840]
## Type of issue

I am having usings when I update my prebid to 8.0 Or higher

## Description

I am currently using Prebid 7.44.0. I tried to update to the latest version and I noticed a 70% drop in impressions and ad request. I switch back to 7.44.0 and the issue went aware. Then I tried other versions like 8.16.0, 8.18.0, and 8.23.0 and the issue returned again. Then I switched back to 7.44.0 and everything went back to normal. So I am convinced something is wrong.

**Comment by dgirardi** [comment]
Please provide some info about the problem; a good starting point is debug logs from both 7.44 and 8.x.

**Comment by patmmccann** [comment]
#10855 dupe
