### ISSUE TITLE
TCF 2.2 Question around "Legitimate Interest" and auction dynamics

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#10853]
## Type of issue
As tcf2.2 has now in effect made "Legitimate Interest" not a legal basis for advertising.  If a user is selecting "reject/ object to all" for "consent" but not "objecting to all" for "legitamate interest", should an auction still take place for those that are on the "legitamate interest" "list", as it would still pass along the same informnation as those that had been "consented to"?

## Description
same as above

## Steps to reproduce
Auction taking place with companies on the "legitimate interest" list, exactly the same information is being sent in the bid request as is sent when a vendor has been "consented" to
![Adysis_Video_Demo-3](https://github.com/prebid/Prebid.js/assets/8503167/0e04390c-6a2f-4409-a0ef-bbe6cf2199ed)

### Expected results
no auction to take place as "consent" has been rejected for "all".  I would expect "consent" to be the "higher title", thus stopping any auction for any "legitimate interest" vendor

### Actual results
auction still takes place for vendors that have had "consent" rejected, but are still on the "legitimate interest" list.  Also to add, the GAM call is also "blocked out", Amazon also still "calls" but i presume that becasue their a "platform", their apstag bid payload omits the cmp variable, which i presume at this stage means no consent was sent through, so no bid responces etc, needs a double check:
![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_playlistUIverticalAmazonParallelReBid_html](https://github.com/prebid/Prebid.js/assets/8503167/61e35785-04b2-41e7-80e6-06355c60130a)

## Platform details
chrome , mac, shouldnt really be relavant

**Comment by dgirardi** [comment]
The rule (in prebid.js) is that purpose 2, which controls auctions, legitimate interest takes precedence over consent. More details are [here](https://docs.prebid.org/dev-docs/modules/gdprEnforcement.html#basic-enforcement). 

As part of the work for TCF-Canada we plan to make this configurable on each rule. If you need it sooner, it's possible - but cumbersome - to set it up with low level [activity controls](https://docs.prebid.org/dev-docs/activity-controls.html).

**Comment by patmmccann** [comment]
> no auction to take place as "consent" has been rejected for "all". I would expect "consent" to be the "higher title", thus stopping any auction for any "legitimate interest" vendor

This isnt how tcf works
