### ISSUE TITLE
Unable to use the advanced size mapping with banner.sizeConfig object in prebid.js v8 and above

### ISSUE THREAD

**Issue by edchiu2024** [prebid/Prebid.js#10850]
## Type of issue
Question.

## Description
I am unable to use the advanced size mapping with banner.sizeConfig object in prebid.js v8 and above.
The same object works fine with v7 but it threw the error of "ERROR: Detected a mediaTypes.banner object without a proper sizes field. " when I tried to use the sizeConfig. The mediaTypes object would work with just banner and the size without sizeConfig. If anyone could please shed some light if there is any step I am missing, I would really appreciate it. Thank you. 

Here is the mediaTypes object that is throwing the error with v8 but not v7:
               ```
mediaTypes: {
                    banner: {
                        sizeConfig: [

                            { minViewPort: [0, 0], sizes: [[300, 250], [300, 100]] },

                            { minViewPort: [768, 0], sizes: [[728, 90], [300, 250]] },

                        ]
                    },
                }
```

## Platform details
node v16.14
prebid v8.10, 8.20, 8.28

**Comment by dgirardi** [comment]
I am unable to reproduce, that config seems to work for me:

![image](https://github.com/prebid/Prebid.js/assets/10151381/3b59fccc-9930-412f-ae30-c2861a0a6b63)

The warning you get sounds like sizeMappingV2 may not be installed, but I'm not sure why that would be related to 7 vs 8. Could you provide a test page?

**Comment by edchiu2024** [comment]
Thank you very much. Yes, that seems to be the issue of not installing sizeMappingV2 and the issue was resolved! Closing the case.
