### ISSUE TITLE
Banner Rendering Problem with Custom Host

### ISSUE THREAD

**Issue by bugrahankaratas** [prebid/Prebid.js#10852]
Hi Team,
I have a big problem for rendering banner. I use my custom host.
It's my html response but I can't show in banner side. 

-->  <div style='position:relative;display:inline-block;text-align:right;'><a href='//theadx.com/userChoices.php' target='new' style='display:block;width:20px;height:20px;position:absolute;z-index:1000;right:0;top:0;border-radius:0 0 0 2px;transition:all ease .2s; -webkit-transition:all ease .2s; background:rgba(0,0,0,0.32) url(//static.theadx.com/images/theadx-logo-icon.svg) center center no-repeat;' onmouseover='this.style.width=\"60px\";this.style.backgroundColor=\"rgba(0,0,0,0.32)\";this.style.backgroundImage=\"url(//static.theadx.com/images/theadx-logo.svg)\";' onmouseout='this.style.width=\"20px\";this.style.backgroundColor=\"rgba(0,0,0,0.32)\";this.style.backgroundImage=\"url(//static.theadx.com/images/theadx-logo-icon.svg)\";'></a><div style='z-index:-1'><a href='//ssp.theadx.com/click?trid=0220abb2-a04c-4b2c-78d4-0b4180a4f1fb&durl=%2F%2Fapp.theadx.com%2Fgclick%3Frid%3D1586e730-9d6e-11ee-b19f-7d49155b019b%26url%3Dhttps%253A%252F%252Ftheadx.com' target='_blank'> <img src='//cdn.theadx.com/winwords/1309/63943/170253392052.28.jpg' width=320 height=50 style='text-decoration:none;'/> <img src='//app.theadx.com/ixc?rid=1586e730-9d6e-11ee-b19f-7d49155b019b&time=r-1702880662825&sp=rPrDawWcXgg%3D' width='1' height='1' style='display:none;'></a></div></div><img src='//ssp.theadx.com/ixc?rid=0220abb2-a04c-4b2c-78d4-0b4180a4f1fb&time=1702880662&tid=704&min=1702880640' width='1' height='1' style='display:none;'>

Also I can show Prebid's banner. What can I do with this response.

**Comment by patmmccann** [comment]
Your image is broken

**Comment by dgirardi** [comment]
Please provide a test page, or steps to reproduce.
