### ISSUE TITLE
Issue with Prebid.js after 7.44.0

### ISSUE THREAD

**Issue by codeblue001** [prebid/Prebid.js#10855]
## Type of issue

I already opened an issue for this but am currently unable to comment on the issue.Not sure why I keep getting an error "There was a problem saving your comment. Please try again." so I decided to open an issue agian

## Description

I am currently using Prebid 7.44.0. I tried to update to the latest version and I noticed a 70% drop in impressions and ad request. I switch back to 7.44.0 and the issue went aware. Then I tried other versions like 8.16.0, 8.18.0, and 8.23.0 and the issue returned again. Then I switched back to 7.44.0 and everything went back to normal. So I am convinced something is wrong.

## Steps to reproduce

I am not sure, but I use Roxot as my anaylytic tool and as soon as I switch to any of the current versions of prebid, my ad request and impressions plummets, when I switch back to 7.44.0 it goes right back up
## Test page

I will be willing to send a link as a direct message
## Platform details

Prebid.js

## Other information

Sending event logs from prebid doctor
[8.28.0.txt](https://github.com/prebid/Prebid.js/files/13704434/8.28.0.txt)
[7.44.0.txt](https://github.com/prebid/Prebid.js/files/13704435/7.44.0.txt)

**Comment by patmmccann** [comment]
Please provide a test page; we're not interested in DMs
