### ISSUE TITLE
Question - AUCTION_END event, bidder with the highest CPM.

### ISSUE THREAD

**Issue by mpereira96** [prebid/Prebid.js#1085]
## Type of issue
Question

## Description
Hey guys, we were thinking of implementing an event listener in our adapter that would listen to `EVENTS.AUCTION_END` where we would check the bidder with the highest CPM. If this bidder has the same bidder code as our adapter, we would drop a notification URL. Our question is if it would be okay to merge this feature?

**Comment by bretg** [comment]
@mpereira96 - we discussed this and are not going to allow adapters to look at the bids from other bidders. For Prebid 1.0, we're going to provide a callback for adapters to receive notification when their creative has won the auction.

If this doesn't meet your needs, please help us understand the use case you're trying to achieve.
