### ISSUE TITLE
Live Intent Id module needs to remove `process.env` reference

### ISSUE THREAD

**Issue by coreyb-cbs** [prebid/Prebid.js#10864]
## Type of issue
module update needed

## Description
The Live Intent Id module contains code referencing `process.env` which should not be used anymore. I chatted with @dgirardi about this, so he should be able to provide more insight if needed. For us, it's causing runtime errors in our dev environment as we're trying to upgrade ad our ad library to webpack 5 (we load Prebid as a module). We've tried working around this via various webpack config plugins (environmentPlugin, definePlugin, dotenv-webpack, etc) but have not had any luck.

https://github.com/prebid/Prebid.js/blob/master/modules/liveIntentIdSystem.js#L159

**Comment by patmmccann** [comment]
Cc @3link

**Comment by coreyb-cbs** [comment]
I reached out to Chris Paart at Live Intent about this and on Thurs, Dec 21, 2023 he stated:

> We are aware of this "process.env" usage and it is on our team's list to get rid of at the beginning of 2024. I can confirm when that has been completed.

**Comment by 3link** [comment]
@coreyb-cbs Could you please try try changes in [this pull request ](https://github.com/prebid/Prebid.js/pull/10905)and tell me if that works for you?

**Comment by coreyb-cbs** [comment]
@3link Looks good! Thank you!

**Comment by 3link** [comment]
> @3link Looks good! Thank you! 

Thank you for confirming 👍
