### ISSUE TITLE
Prebid 1.0 - module interface

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#1086]
Tracking issue for defining and implementing the module/adapter interface for Prebid 1.0.

This covers the 'Adapters' section of Issue #891. First step is to write a spec and break the implementation into components.

- detailed proposal for how Prebid will store modules including: bidder adapters, analytics adapters, and other plugins such as Express, Digitrust, Currency conversion, etc.
- summary of changes to the adapter API not covered by other tickets:
-- moving to a different source path
-- must return unique auction ID. BidResponses will not be accepted without this ID
-- ability to accept an adapter-specific creative ID for quality purposes
-- set a time-to-live in the bid response
-- provide a callback for adapters to receive notification when their creative has won the auction.

Note that other issues track adapter-related items as well. A guide for adapter authors will be created after the specs are complete.

**Comment by snapwich** [comment]
Initial spec here:

https://docs.google.com/document/d/1GIJ5mZD6_TG5si4eOJjHMAazZUyA5DseMxEC70wjOOE/edit?usp=sharing

**Comment by ndhimehta** [comment]
https://github.com/prebid/Prebid.js/pull/1177
