### ISSUE TITLE
Prebid 1.0 - multiple concurrent auctions.

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#1087]
Tracking issue for the 'multiple concurrent auction' feature of Prebid 1.0 as defined in Issue #891

First deliverable is a spec.

**Comment by mkendall07** [comment]
Engineering work is blocked by:
https://github.com/prebid/Prebid.js/issues/1086
https://github.com/prebid/Prebid.js/issues/1121

**Comment by mkendall07** [comment]
Spec is here: https://gist.github.com/mkendall07/1ef1b27ed3501d7b03fbd72ec455bab4

**Comment by protonate** [comment]
Some progress here on the spec, request for comment:
https://gist.github.com/protonate/e2f271873bec0c5596ff2715d8fdb97f

**Comment by dbemiller** [comment]
Has there been any thought into how analytics adapters will interact with concurrent auctions yet?

There's a little section [here](https://gist.github.com/protonate/e2f271873bec0c5596ff2715d8fdb97f#reporting--analytics)... but I'm wondering things like:

How will analytics adapters separate the data from different auctions? Is this a requirement? If so, will 1.0 analytics adapters need to support multiple instances? Or are we planning to attach an `auctionId` to each event?
