### ISSUE TITLE
Prebid 1.0 - support multiple instances of an adapter

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#1091]
Tracking issue for supporting multiple instances of a demand adapter in Prebid 1.0 (see Issue #891)

**Comment by mkendall07** [comment]
Technical requirements:

- Each adapter must implement the `baseAdapter` "interface" or 1.0 equivalent
- Each adapter must be included as an optional `module` inside the module directory (as per the bundling interface defined for 1.0)

**Comment by bretg** [comment]
This will be done as part of the module design. There will be documentation for how to register the adapter to meet this requirement.
