### ISSUE TITLE
Criteo still requiring a deprecated media param 'placement'

### ISSUE THREAD

**Issue by pieisgood** [prebid/Prebid.js#10914]
https://github.com/prebid/Prebid.js/blob/66893733caf9404a582f6c7db20f9308e35448fe/modules/criteoBidAdapter.js#L677

Placement has been deprecated, plcmt should now be used. Having placement be a requirement for video bidding on Criteo should be corrected.

**Comment by fowler446** [comment]
We should absolutely drop this field from being `required`. Doesn't make sense to require a deprecated field.

**Comment by fowler446** [comment]
@dzhang-criteo any thoughts here? I don't think we should be requiring a deprecated field.

**Comment by patmmccann** [comment]
@fowler446 I submitted a pr, what do you think
