### ISSUE TITLE
Yieldmo requiring deprecated media param 'placement'

### ISSUE THREAD

**Issue by pieisgood** [prebid/Prebid.js#10915]
https://github.com/prebid/Prebid.js/blob/66893733caf9404a582f6c7db20f9308e35448fe/modules/yieldmoBidAdapter.js#L604

This should be updated to support the new plcmt field and not have placement as a requirement since it is now deprecated.

**Comment by patmmccann** [comment]
@fowler446 we'd love for the video committee to weigh in on if requiring deprecated parameters should be disallowed in prebid 9

**Comment by fowler446** [comment]
We should absolutely drop this field from being `required`. Doesn't make sense to require a deprecated field.

**Comment by fowler446** [comment]
Closing this issue in favour of this global list of needed `placement` changes
https://github.com/prebid/Prebid.js/issues/10452
