### ISSUE TITLE
Add RhythmOne to HeaderBid Expert Extension

### ISSUE THREAD

**Issue by nilesh555** [prebid/Prebid.js#1092]
## Type of issue
Identify RhythmOne bidder in HeaderBid Expert. The pattern to identify the bidder is:
tag.1rx.io/rmp/\d+/\d/mvo

## Description
Currently HeaderBid Extension does not identify RhythmOne bidder. 

## Steps to reproduce
n/a

### Expected results
RhythmOne bidder shows in HeaderBid Expert Extension

### Actual results
n/a

## Platform details
n/a

## Other information
n/a

**Comment by matthewlane** [comment]
RhythmOne is now in Headerbid Expert 1.5.12
