### ISSUE TITLE
Question: Use cases for different methods to set timeouts

### ISSUE THREAD

**Issue by rizhang** [prebid/Prebid.js#1093]
In the documentation, there are two ways to set the timeout for bidders to respond with a bid:
1. Use the `setTimeout` function and handle the timeout callback yourself:
```
var PREBID_TIMEOUT = 700;
....
setTimeout(function() {
  sendAdserverRequest();
}, PREBID_TIMEOUT);
```

2. Pass the timeout value into the `bidRequested` function:
```
var PREBID_TIMEOUT = 700;
....
 pbjs.que.push(function() {
   pbjs.requestBids({
      timeout: PREBID_TIMEOUT,
      bidsBackHandler: function() {
        pbjs.setTargetingForGPTAsync();
        googletag.pubads().refresh(); 
      }
   });
});
```

I noticed that using the second method gives you logging information when bidders timeout, so this sounds like the way to go. However the front page of the Dev Docs suggests using the first method. 

When would we use one method over the other to set timeouts? Would there ever be a use case where both will be implemented on a page?

**Comment by mkendall07** [comment]
@rizhang in general the on page timeout (option 1) will be stricter than the requestBids timeout. This is because the requestBids timeout gets set later than the on page timeout. It's up to the user to decide what works best for them.

**Comment by rizhang** [comment]
Oh I see. Thanks for the response @mkendall07.
