### ISSUE TITLE
FledgeForGPT submodule: don't collect auctionConfig when GAM won't run fledge

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10932]
## Type of issue
Feature request

## Description
Gam will not run PAAPI for control_1.* and label_only_1. Let's not solicit auction config when the pub is using gpt.js for paapi running  in these scenarios. 
![image](https://github.com/prebid/Prebid.js/assets/1683175/388a5da7-91f7-42a5-89e7-44dc8ddd098b)

https://support.google.com/admanager/answer/13178817?hl=en

**Comment by bretg** [comment]
I like this feature a lot  if we add a flag to control the behavior.

e.g. something like this:
```
pbjs.que.push(function() {
  pbjs.setConfig({
    fledgeForGpt: {
      enabled: true,
      activeOnLabels: ["treatment*", "label_only_5"], // if not specifed, set always set ae=1
      bidders: ['openx', 'rtbhouse'],
      defaultForSlots: 1
    }
  });
});
```

**Comment by patmmccann** [comment]
copying from slack, one can already ping  navigator.cookieDeprecationLabel and configure the module or not accordingly, so unless people want a default change we can just close this

`
// Feature detect temporary API first
if ('cookieDeprecationLabel' in navigator) {
 // Request value and resolve promise
 navigator.cookieDeprecationLabel.getValue().then((label) => {
   console.log(label);
   // Expected output: "example_label_1"
 });
}
`

**Comment by bretg** [comment]
Maybe someone could drive this pseudo-code home?
```
if ('cookieDeprecationLabel' in navigator) { // Request value and resolve promise 
    navigator.cookieDeprecationLabel.getValue().then((label) => {
        if (label startswith "treatment_" or label=="label_only_5") {
            ... initialize fledgeForGPT ...
        }
    }
}
```

Also, related to https://github.com/prebid/prebid.github.io/issues/5062, if someone can give me the details about what version of PBJS supported what with respect to Privacy Sandbox, I offer to make a page that includes this example and the version info.

e.g. 
- 8.9: fledgeForGpt module, Sec-Browsing-Topics header enabled
- 8.8: topicsFpd module allows for bidders to share topics

Is that it? No other core updates need to be mentioned?

**Comment by dgirardi** [comment]
Enable fledge when there's either no label, or label is "label_only_5" or "treatment_*":
```
Promise.resolve(navigator.cookieDeprecationLabel?.getValue?.()).then(label => {
    pbjs.setConfig({
        fledgeForGpt: {
            enabled: !label || label.startsWith("treatment_") || label === 'label_only_5'
        },
        [...]
    });
});
```

**Comment by bretg** [comment]
Discussed with the team. Here are the version points that should be made:

- 8.22: makes Prebid FPD available to the generateBid, scoreAds, and reportResult functions
- 8.15: adds bid floor signal to the fledgeForGpt module
- 8.9: fledgeForGpt module, Sec-Browsing-Topics header enabled
- 8.8: topicsFpd module allows for bidders to share topics
