### ISSUE TITLE
Video Outstream: prebid,js Error in Example 

### ISSUE THREAD

**Issue by richmadriz** [prebid/Prebid.js#10944]
Error in Example outstream no server,  https://docs.prebid.org/examples/video/outstream/pb-ve-outstream-no-server.html
We are working trying to separate this example but it has an error which happens to us in the same way in our demo.
ms: Error rendering ad (id: 31f3cda2d27635): renderAd was prevented from writing to the main document.

![Imagen de WhatsApp 2024-01-15 a las 09 00 07_2a076f96](https://github.com/prebid/Prebid.js/assets/112421761/f24d4f99-79f5-4918-ace6-01b8cdf4d5c9)

**Comment by richmadriz** [comment]
I tried this already by obtaining a div apart from video1 and obtaining the video1 Id tag itself but it does not work with any div that is in the document either,
<script>
        var pbjs = pbjs || {};
        pbjs.que = pbjs.que || [];

        function callANRenderer(bid, ad) {
            const adResponse = {
                ad: {
                    video: {
                        content: ad,
                        player_width: 640,
                        player_height: 480,
                    }
                }
            }

            bid.renderer.push(() => {
                window.ANOutstreamVideo.renderAd({
                    targetId: bid.adUnitCode,
                    adResponse,
                });
            });
        }

        function render(bid) {
            let ad = bid.ad || bid.vastXml;

            if (ad) {
                callANRenderer(bid, ad)
            } else {
                if (bid.vastUrl) {
                    (async() => {
                        ad = await fetch(resp).then(resp => resp.text());

                        if (typeof ad === 'string') {
                            callANRenderer(bid, ad);
                        } else {
                            console.log('Invalid VAST');
                        }
                    })();
                } else {
                    console.log('Invalid ad');
                }
            }
        }

        const adUnits = [{
            code: 'video1',
            mediaTypes: {
                video: {
                    context: 'outstream',
                    playerSize: [
                        [640, 480]
                    ],
                    mimes: ['video/mp4'],
                    protocols: [1, 2, 3, 4, 5, 6, 7, 8],
                    api: [2],
                    linearity: 1,
                    playbackmethod: [2],
                    skip: 1,
                    renderer: {
                        render,
                        url: "https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js"
                    },
                    maxduration: 30
                }
            },

            bids: [{
                bidder: 'appnexus',
                params: {
                    placementId: 31776638
                }
            }]
        }];

        pbjs.que.push(function() {
            pbjs.addAdUnits(adUnits);
            pbjs.setConfig({
                debug: true,
                cache: {
                    url: 'https://prebid.adnxs.com/pbc/v1/cache'
                }
            });
            pbjs.requestBids({
                timeout: 1000,
                bidsBackHandler: function(bids) {
                    const highestCpmBids = pbjs.getHighestCpmBids('video1');
                    pbjs.renderAd(document.getElementById('myad'), highestCpmBids[0].adId);
                }
            });
        });
    </script>
    
and this in the BODY

    <div id="video1"></div>
    <div id="myad"></div>

**Comment by spormeon** [comment]
can I add this one to the mix, for using IMA as the renderer, doesnt work on site and I cant get it to work locally using both vastXml &/or vastUrl:
`debugging: {
              enabled: true,
              intercept: [
                {
                  when: {
                    adUnitCode: 'outstreamSlotInArticle',
                  },
                  then: {
                    cpm: 20,
                    currency: "GBP",
                    size: "400x225",
                    width: 400,
                    height: 225,
                    // adId: '51844b6ede86d8',
                    mediaType: "video",
                    // vastXml: "<VAST version=\"3.0\"> <Ad id=\"demo15\"> <InLine> <AdSystem version=\"1.0\"> <![CDATA[ Kargo ]]> </AdSystem> <AdTitle> <![CDATA[ Test ]]> </AdTitle> <Impression id=\"imp\"> <![CDATA[ https://x.videobyte.com/tracker?e=imp&brId=test&pid=test ]]> </Impression> <Creatives> <Creative id=\"demo\" sequence=\"1\"> <Linear skipoffset=\"00:00:05\"> <Duration>00:00:12</Duration> <TrackingEvents> <Tracking event=\"skip\"> <![CDATA[ https://x.videobyte.com/tracker?e=skip&brId=test&pid=test ]]> </Tracking> </TrackingEvents> <MediaFiles> <MediaFile id=\"demo_1920x1080\" delivery=\"progressive\" type=\"video/mp4\" bitrate=\"1500\" width=\"1920\" height=\"1080\"> <![CDATA[ https://cdn1.videobyte.com/videos/_house/video_12s_1920x1080.mp4 ]]> </MediaFile> <MediaFile id=\"demo_1280x720\" delivery=\"progressive\" type=\"video/mp4\" bitrate=\"750\" width=\"1280\" height=\"720\"> <![CDATA[ https://cdn1.videobyte.com/videos/_house/video_12s_1280x720.mp4 ]]> </MediaFile> <MediaFile id=\"demo_960x540\" delivery=\"progressive\" type=\"video/mp4\" bitrate=\"500\" width=\"960\" height=\"540\"> <![CDATA[ https://cdn1.videobyte.com/videos/_house/video_12s_960x540.mp4 ]]> </MediaFile> <MediaFile id=\"demo_640x360\" delivery=\"progressive\" type=\"video/mp4\" bitrate=\"250\" width=\"640\" height=\"360\"> <![CDATA[ https://cdn1.videobyte.com/videos/_house/video_12s_640x360.mp4 ]]> </MediaFile> </MediaFiles> </Linear> </Creative> </Creatives> <Pricing model=\"\" currency=\"USD\"> <![CDATA[ 1 ]]> </Pricing> </InLine> </Ad> </VAST>",
                    vastUrl: "https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_ad_samples&sz=640x480&cust_params=sample_ct%3Dlinear&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",
                    ad: "<VAST version=\"3.0\"> <Ad id=\"123\"> <InLine> <AdSystem>PubMatic</AdSystem> <AdTitle>VAST 2.0 Instream Test</AdTitle> <Description>VAST 2.0 Instream Test</Description> <Error> <![CDATA[https://aktrack.pubmatic.com/er=[ERRORCODE]]]> </Error> <Impression> <![CDATA[https://aktrack.pubmatic.com?e=impression]]> </Impression> <Creatives> <Creative AdID=\"123\"> <Linear> <Duration>00:00:30</Duration> <TrackingEvents> <Tracking event=\"creativeView\"> <![CDATA[https://aktrack.pubmatic.com?e=creativeView]]> </Tracking> <Tracking event=\"start\"> <![CDATA[https://aktrack.pubmatic.com?e=start]]> </Tracking> <Tracking event=\"midpoint\"> <![CDATA[https://aktrack.pubmatic.com?e=midpoint]]> </Tracking> <Tracking event=\"firstQuartile\"> <![CDATA[https://aktrack.pubmatic.com?e=firstQuartile]]> </Tracking> <Tracking event=\"thirdQuartile\"> <![CDATA[https://aktrack.pubmatic.com?e=thirdQuartile]]> </Tracking> <Tracking event=\"complete\"> <![CDATA[https://aktrack.pubmatic.com?e=complete]]> </Tracking> </TrackingEvents> <VideoClicks> <ClickThrough> <![CDATA[https://www.pubmatic.com]]> </ClickThrough> </VideoClicks> <MediaFiles> <MediaFile delivery=\"progressive\" type=\"video/mp4\" bitrate=\"500\" width=\"480\" height=\"460\" scalable=\"true\" maintainAspectRatio=\"true\"> <![CDATA[https://staging.pubmatic.com:8443/test/spinning-logo-480x360_video.mp4]]> </MediaFile> <MediaFile delivery=\"progressive\" type=\"video/ogg\" bitrate=\"500\" width=\"480\" height=\"460\" scalable=\"true\" maintainAspectRatio=\"true\"> <![CDATA[https://staging.pubmatic.com:8443/test/spinning-logo-480x360_video.ogg]]> </MediaFile> <MediaFile delivery=\"progressive\" type=\"video/x-flv\" bitrate=\"500\" width=\"400\" height=\"300\" scalable=\"true\" maintainAspectRatio=\"true\"> <![CDATA[https://staging.pubmatic.com:8443/test/PubMatic_test_video.flv]]> </MediaFile> </MediaFiles> </Linear> </Creative> <Creative AdID=\"123\"> <NonLinearAds> <TrackingEvents></TrackingEvents> <NonLinear height=\"50\" width=\"300\" minSuggestedDuration=\"00:00:05\"> <StaticResource creativeType=\"image/jpeg\"> <![CDATA[https://staging.pubmatic.com:8443/test/PubMatic_LetsBeClear_300x50.jpeg]]> </StaticResource> <NonLinearClickThrough> <![CDATA[https://www.pubmatic.com]]> </NonLinearClickThrough> </NonLinear> </NonLinearAds> </Creative> <Creative AdID=\"123\"> <CompanionAds> <Companion width=\"300\" height=\"250\"> <StaticResource creativeType=\"image/jpeg\"> <![CDATA[https://staging.pubmatic.com:8443/test/PubMatic_LetsBeClear_320x250.jpg]]> </StaticResource> <CompanionClickThrough> <![CDATA[https://www.pubmatic.com]]> </CompanionClickThrough> </Companion> </CompanionAds> </Creative> </Creatives> </InLine> </Ad> </VAST>"
                  }
                },
              ]
            }'


https://docs.prebid.org/examples/video/outstream/basic-ima.html

**Comment by dgirardi** [comment]
Also related: https://github.com/prebid/prebid.github.io/issues/5248

**Comment by patmmccann** [comment]
fixed in #12391

**Comment by muuki88** [comment]
Hi @jarrettabello 

Thanks for the detailed looked. I have not seen the issue earlier, thanks for your patience.
To give a quick feedback on your findings

> Also worth noting that the script tag that contains the prebid configuration on the page is a script tag with text/plain `<script type="text/plain" class="optanon-category-C0003">` -- that should be updated to `text/javascript`

This is intentional. While it has changed, due to a migration to consentmanager, it is still `text/plain` and will be inserted after consent.

> By updating the test page with an ad container to inject the ad into the error resolves.

The examples are all part of the docs repo now, so contributing a fix is possible

- https://github.com/prebid/prebid.github.io/tree/master/dev-docs/examples
- https://github.com/prebid/prebid.github.io/tree/master/examples/video

We happily accept pull requests :blush:  If you need any guidance, don't hesitate to ask.
