### ISSUE TITLE
Prebid.js not Loading all bidders together - Bug

### ISSUE THREAD

**Issue by sajokj** [prebid/Prebid.js#1094]
## Type of issue
bug

## Description
Prebid.js not loading all bidders together. As per Headerbid Expert on Chrome. DFP request is not waiting for the prebid or timeout.
DFP start first, then latest the request to bidders are sent. due to this issue, site is under monetized

**Comment by mkendall07** [comment]
This is expected in some cases with bidders that load an external library before bidding.
