### ISSUE TITLE
Ad is not being displayed on html page

### ISSUE THREAD

**Issue by skapoorViant** [prebid/Prebid.js#10951]
## Type of issue
Question

## Description
Trying to display ad with Viant Adapter. Ad is being returned but it is not being displayed on the webpage. I followed hello_world.html in the code to create and test. Any inputs would be helpful. Thanks

## Steps to reproduce
Please find the html code attached.

## Platform details
Prebid.js, google chrome

The commented code in the end is the ad response which is coming.
[adTestViant.txt](https://github.com/prebid/Prebid.js/files/13953622/adTestViant.txt)

**Comment by skapoorViant** [comment]
@dgirardi you can try this URL:
https://qa.vianttech.com/2114_pixie_test_page/adTestViant.html.

The endpoint for viant adapter is production endpoint and it will return 204 from localhost as origin.

**Comment by dgirardi** [comment]
The bid response returned by the adapter has `width` and `height` set to 0, so that's what is set on the iframe around the creative. The ad appears to be rendered normally otherwise.

**Comment by dgirardi** [comment]
Digging a bit more, I see that viant uses `ortbConverter` - that picks `width` and `height` from the ORTB response, `w`/`h` in `seatbid[].bid[]`. Those appear to be missing:

```
{
  "id": "b67ec4fd-7fe1-4033-a567-2a314f691b7f",
  "seatbid": [
    {
      "bid": [
        {
          "id": "db0beeaa-37e0-4631-b2b8-91ad580eda2d-209b4b0f83c55f",
          "impid": "209b4b0f83c55f",
          "price": 9.067962165048543,
          "adid": "96326-440507-2217278",
          "nurl": "https://events-us-east-1.ipredictive.com/d/rtb/v25/prebid/won?zid=prebid_1_0_1&sid=db0beeaa-37e0-4631-b2b8-91ad580eda2d-209b4b0f83c55f&crid=23242298&adid=96326&oid=2217278&cid=440507&spid=851&pubid=464&site_id=3748449002&auid=5774186&algid=1&algrev=1&offpc=9.067961165048544&maxbid=10&optpc=1.1154868602752686&cstpc=9.067961165048544&xts=1705520141&pbap=CgMweDAQBRoBZioGR29vZ2xlMgZDaHJvbWU6BUxpbnV4UgJlbloRUEVSU09OQUxfQ09NUFVURVJgAGoGQkFOTkVSigEBMJABAJoBIDRiZTUwNzU4MjRkZmM5ZWJmY2VhOTYyZjMxODgwOTdjpQEAAAAArQEAAAAAwAEAyAEC0gEGUFVCTElD-gEgZWQ3ZjgzYjAxZWUyODlhZTExMDU0NDAwOTI1OWNkYjWaAgJYUqACALACAvICZU1vemlsbGEvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyMC4wLjAuMCBTYWZhcmkvNTM3LjM2-gIOQ2hyb21lIERlc2t0b3CxAwAAAAAAAAAAygMA2gMQcWEudmlhbnR0ZWNoLmNvbeoDJGI2N2VjNGZkLTdmZTEtNDAzMy1hNTY3LTJhMzE0ZjY5MWI3ZrkEWDm0yHa-xz_ABL8O6gQEODkuMPIEBkNocm9tZdIFKXByZWJpZC13LTY4OTE2YTZjODI2MzRkMDMwOWMyMmEwZTg3ZTE2ZWQ1gAYB&au_pc=${AUCTION_PRICE}&rand=1705433741268",
          "adm": "<div id='adelphic_ads' style='margin:0;padding:0;border:0;width:300;height:250;overflow: hidden;'>\n\n\n\n<a target=\"_blank\" href=\"https://events-us-east-1.ipredictive.com/d/track/click?zid=prebid_1_0_1&sid=db0beeaa-37e0-4631-b2b8-91ad580eda2d-209b4b0f83c55f&crid=23242298&adid=96326&oid=2217278&cid=440507&spid=851&pubid=464&site_id=3748449002&auid=5774186&algid=1&algrev=1&offpc=9.067961165048544&maxbid=10&optpc=1.1154868602752686&cstpc=9.067961165048544&xts=1705520141&pbap=CgMweDAQBRoBZioGR29vZ2xlMgZDaHJvbWU6BUxpbnV4UgJlbloRUEVSU09OQUxfQ09NUFVURVJgAGoGQkFOTkVSigEBMJABAJoBIDRiZTUwNzU4MjRkZmM5ZWJmY2VhOTYyZjMxODgwOTdjpQEAAAAArQEAAAAAwAEAyAEC0gEGUFVCTElD-gEgZWQ3ZjgzYjAxZWUyODlhZTExMDU0NDAwOTI1OWNkYjWaAgJYUqACALACAvICZU1vemlsbGEvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyMC4wLjAuMCBTYWZhcmkvNTM3LjM2-gIOQ2hyb21lIERlc2t0b3CxAwAAAAAAAAAAygMA2gMQcWEudmlhbnR0ZWNoLmNvbeoDJGI2N2VjNGZkLTdmZTEtNDAzMy1hNTY3LTJhMzE0ZjY5MWI3ZrkEWDm0yHa-xz_ABL8O6gQEODkuMPIEBkNocm9tZdIFKXByZWJpZC13LTY4OTE2YTZjODI2MzRkMDMwOWMyMmEwZTg3ZTE2ZWQ1gAYB&ez_p=&rd=https%3A%2F%2Fwww.adelphic.com\">\n\n<img src=\"https://media-cdn.ipredictive.com/image/96326/18b688b840e_300x250.gif\" width=\"300\" height=\"250\">\n</a>\n\n<img id=\"cs_imp\" src=\"https://events-us-east-1.ipredictive.com/d/csimp/pixel?zid=prebid_1_0_1&sid=db0beeaa-37e0-4631-b2b8-91ad580eda2d-209b4b0f83c55f&crid=23242298&adid=96326&oid=2217278&cid=440507&spid=851&pubid=464&site_id=3748449002&auid=5774186&algid=1&algrev=1&offpc=9.067961165048544&maxbid=10&optpc=1.1154868602752686&cstpc=9.067961165048544&xts=1705520141&pbap=CgMweDAQBRoBZioGR29vZ2xlMgZDaHJvbWU6BUxpbnV4UgJlbloRUEVSU09OQUxfQ09NUFVURVJgAGoGQkFOTkVSigEBMJABAJoBIDRiZTUwNzU4MjRkZmM5ZWJmY2VhOTYyZjMxODgwOTdjpQEAAAAArQEAAAAAwAEAyAEC0gEGUFVCTElD-gEgZWQ3ZjgzYjAxZWUyODlhZTExMDU0NDAwOTI1OWNkYjWaAgJYUqACALACAvICZU1vemlsbGEvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyMC4wLjAuMCBTYWZhcmkvNTM3LjM2-gIOQ2hyb21lIERlc2t0b3CxAwAAAAAAAAAAygMA2gMQcWEudmlhbnR0ZWNoLmNvbeoDJGI2N2VjNGZkLTdmZTEtNDAzMy1hNTY3LTJhMzE0ZjY5MWI3ZrkEWDm0yHa-xz_ABL8O6gQEODkuMPIEBkNocm9tZdIFKXByZWJpZC13LTY4OTE2YTZjODI2MzRkMDMwOWMyMmEwZTg3ZTE2ZWQ1gAYB&au_pc=${AUCTION_PRICE}&rr=1705433741268\" style=\"display:none\" height=\"1\" width=\"1\">\n\n\n\n\n\n</div>\n\n<script type=\"text/javascript\" src=\"https://c.betrad.com/surly.js#;ad_w=300;ad_h=250;coid=1839;nid=15932;\"></script>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
          "adomain": [
            "adelphic.com"
          ],
          "iurl": "https://media-cdn.ipredictive.com/image/96326/18b688b840e_300x250.gif",
          "crid": "23242298",
          "cat": [
            "IAB3-1"
          ]
        }
      ],
      "seat": "2222"
    }
  ],
  "bidid": "db0beeaa-37e0-4631-b2b8-91ad580eda2d-209b4b0f83c55f",
  "cur": "USD"
}
```

**Comment by skapoorViant** [comment]
@dgirardi so you are saying the width and height which is mentioned in the adm is not getting picked up by prebid and the response should be have "w" and "h" as additional fields in it. Something like this:

`{
  "id": "a138fc3f-e02b-4403-8d2c-bf461ff338d7",
  "seatbid": [
    {
      "bid": [
        {
          "id": "d437ce71-fd2b-4797-a2f3-a7d50c25910b-2d33aeba9788fc",
          "impid": "2d33aeba9788fc",
          "price": 9.067962165048543,
          "adid": "96326-440507-2217278",
          "nurl": "https://events-us-east-1.ipredictive.com/d/rtb/v25/prebid/won?zid=prebid_1_0_1&sid=d437ce71-fd2b-4797-a2f3-a7d50c25910b-2d33aeba9788fc&crid=23242298&adid=96326&oid=2217278&cid=440507&spid=851&pubid=464&site_id=3748449002&auid=5774186&algid=1&algrev=1&offpc=9.067961165048544&maxbid=10&optpc=1.1154868602752686&cstpc=9.067961165048544&xts=1705520239&pbap=CgMweDAQBRoBZioGR29vZ2xlMgZDaHJvbWU6BE9TIFhCBjEzLjYuMFICZW5aEVBFUlNPTkFMX0NPTVBVVEVSYABqBkJBTk5FUooBATCQAQCaASA4MjE3ODliOTlmOTE2ODMzMGIwNjM3OWM1MzgxMzgwMKUBAAAAAK0BAAAAAMABAMgBAtIBBlBVQkxJQ_oBIGVkN2Y4M2IwMWVlMjg5YWUxMTA1NDQwMDkyNTljZGI1mgICWFKgAgCwAgLyAnVNb3ppbGxhLzUuMCAoTWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxMF8xNV83KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTIwLjAuMC4wIFNhZmFyaS81MzcuMzb6Ag5DaHJvbWUgRGVza3RvcLEDAAAAAAAAAADKAwDaAxBxYS52aWFudHRlY2guY29t6gMkYTEzOGZjM2YtZTAyYi00NDAzLThkMmMtYmY0NjFmZjMzOGQ3uQR_2T15WKilP8AEpwPqBAQ4OS4w8gQGQ2hyb21l0gUpcHJlYmlkLXctNjg5MTZhNmM4MjYzNGQwMzA5YzIyYTBlODdlMTZlZDWABgE&au_pc=${AUCTION_PRICE}&rand=1705433839337",
          "adm": "<div id='adelphic_ads' style='margin:0;padding:0;border:0;width:300;height:250;overflow: hidden;'>\n\n\n\n<a target=\"_blank\" href=\"https://events-us-east-1.ipredictive.com/d/track/click?zid=prebid_1_0_1&sid=d437ce71-fd2b-4797-a2f3-a7d50c25910b-2d33aeba9788fc&crid=23242298&adid=96326&oid=2217278&cid=440507&spid=851&pubid=464&site_id=3748449002&auid=5774186&algid=1&algrev=1&offpc=9.067961165048544&maxbid=10&optpc=1.1154868602752686&cstpc=9.067961165048544&xts=1705520239&pbap=CgMweDAQBRoBZioGR29vZ2xlMgZDaHJvbWU6BE9TIFhCBjEzLjYuMFICZW5aEVBFUlNPTkFMX0NPTVBVVEVSYABqBkJBTk5FUooBATCQAQCaASA4MjE3ODliOTlmOTE2ODMzMGIwNjM3OWM1MzgxMzgwMKUBAAAAAK0BAAAAAMABAMgBAtIBBlBVQkxJQ_oBIGVkN2Y4M2IwMWVlMjg5YWUxMTA1NDQwMDkyNTljZGI1mgICWFKgAgCwAgLyAnVNb3ppbGxhLzUuMCAoTWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxMF8xNV83KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTIwLjAuMC4wIFNhZmFyaS81MzcuMzb6Ag5DaHJvbWUgRGVza3RvcLEDAAAAAAAAAADKAwDaAxBxYS52aWFudHRlY2guY29t6gMkYTEzOGZjM2YtZTAyYi00NDAzLThkMmMtYmY0NjFmZjMzOGQ3uQR_2T15WKilP8AEpwPqBAQ4OS4w8gQGQ2hyb21l0gUpcHJlYmlkLXctNjg5MTZhNmM4MjYzNGQwMzA5YzIyYTBlODdlMTZlZDWABgE&ez_p=&rd=https%3A%2F%2Fwww.adelphic.com\">\n\n<img src=\"https://media-cdn.ipredictive.com/image/96326/18b688b840e_300x250.gif\" width=\"300\" height=\"250\">\n</a>\n\n<img id=\"cs_imp\" src=\"https://events-us-east-1.ipredictive.com/d/csimp/pixel?zid=prebid_1_0_1&sid=d437ce71-fd2b-4797-a2f3-a7d50c25910b-2d33aeba9788fc&crid=23242298&adid=96326&oid=2217278&cid=440507&spid=851&pubid=464&site_id=3748449002&auid=5774186&algid=1&algrev=1&offpc=9.067961165048544&maxbid=10&optpc=1.1154868602752686&cstpc=9.067961165048544&xts=1705520239&pbap=CgMweDAQBRoBZioGR29vZ2xlMgZDaHJvbWU6BE9TIFhCBjEzLjYuMFICZW5aEVBFUlNPTkFMX0NPTVBVVEVSYABqBkJBTk5FUooBATCQAQCaASA4MjE3ODliOTlmOTE2ODMzMGIwNjM3OWM1MzgxMzgwMKUBAAAAAK0BAAAAAMABAMgBAtIBBlBVQkxJQ_oBIGVkN2Y4M2IwMWVlMjg5YWUxMTA1NDQwMDkyNTljZGI1mgICWFKgAgCwAgLyAnVNb3ppbGxhLzUuMCAoTWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxMF8xNV83KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTIwLjAuMC4wIFNhZmFyaS81MzcuMzb6Ag5DaHJvbWUgRGVza3RvcLEDAAAAAAAAAADKAwDaAxBxYS52aWFudHRlY2guY29t6gMkYTEzOGZjM2YtZTAyYi00NDAzLThkMmMtYmY0NjFmZjMzOGQ3uQR_2T15WKilP8AEpwPqBAQ4OS4w8gQGQ2hyb21l0gUpcHJlYmlkLXctNjg5MTZhNmM4MjYzNGQwMzA5YzIyYTBlODdlMTZlZDWABgE&au_pc=${AUCTION_PRICE}&rr=1705433839337\" style=\"display:none\" height=\"1\" width=\"1\">\n\n\n\n\n\n</div>\n\n<script type=\"text/javascript\" src=\"https://c.betrad.com/surly.js#;ad_w=300;ad_h=250;coid=1839;nid=15932;\"></script>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
“w”:300,
“h”:250,
          "adomain": [
            "adelphic.com"
          ],
          "iurl": "https://media-cdn.ipredictive.com/image/96326/18b688b840e_300x250.gif",
          "crid": "23242298",
          "cat": [
            "IAB3-1"
          ]
        }
      ],
      "seat": "2222"
    }
  ],
  "bidid": "d437ce71-fd2b-4797-a2f3-a7d50c25910b-2d33aeba9788fc",
  "cur": "USD"
}`

**Comment by dgirardi** [comment]
Yes; Prebid uses width and height to size the iframe, it doesn't try to figure them out from the creative. You could also set them from the adapter but I think that's going to be more difficult compared to doing it server-side.

**Comment by skapoorViant** [comment]
Hi @dgirardi , I changed the bid response and added "w" and "h" in it, but the ad is still not being rendered, and I am not seeing the adresponse this time in html at all. Previously it was not able to get adSize but this time it is not rendering the overall html at all. Can you please help what is causing this issue again. You can use this link to check: https://qa.vianttech.com/2114_pixie_test_page/Prebid.js/integrationExamples/gpt/adTestViant.html
