### ISSUE TITLE
ortbConverter: send max tmax

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#10964]
## Type of issue
enhancement

## Description
The ortbConverter lib sets the ORTB tmax value to s2sConfig.timeout. This is great, but we have a module that would like to know the actual client-side timeout -- the `timeout` passed to pbjs.requestBids.

Specifically the use case is timeout optimization. We're exploring a server-side module that would help the publisher optimize the timeout value, essentially ignoring `tmax` and experimenting with other, possibly more effective values. But we need to know the ceiling for how far these explorations should go.

We propose passing the client-side timeout value as `ext.tmaxmax`.

**Comment by patmmccann** [comment]
The actual timeout higher than the ceiling, why not just ask the publisher to set an actual ceiling they are comfortable with?

**Comment by bretg** [comment]
Are you suggesting that pubs just set s2sConfig.timeout to be the same as what's sent in pbjs.requestBids() and use that as the ceiling?

I would solidly prefer not to have to (A) document that and (B) get existing pubs to change the page if/when they want to try this feature when it's easy and effective to get the client-side timeout.

**Comment by dgirardi** [comment]
from [here](https://docs.prebid.org/dev-docs/modules/prebidServer.html):

> If the s2sConfig timeout is greater than the Prebid.js timeout, the s2sConfig timeout will be automatically adjusted to 75% of the Prebid.js timeout in order to fit within the auction process.

AFAIK this has never been the case since at least my time with Prebid. Do we want to also implement something like it - maybe a fixed 500ms discount? (percentage doesn't make a lot of sense to me, if I increase client-side timeout it's not like the latency to server also increases).

**Comment by bretg** [comment]
> this has never been the case since at least my time with Prebid

Hmm. Good topic. I think 500ms would be an overly large buffer. The number depends a lot on the user's network proximity to the nearest Prebid Server. Discuss in a future meeting?

**Comment by bretg** [comment]
Discussed. Agreed that a publisher should be able to define the tmaxmax like this:

```
pbjs.setConfig({
   ortb2: {
      ext: {
         tmaxmax: 888
      }
   }
});
```

The ortbConverter library should check for the existence of `ext.tmaxmax` and if not there, set it to the timeout value passed to `requestBids()`

**Comment by bmjoju** [comment]
@bretg I can also add that the below does not seem to be the working

> If the s2sConfig timeout is greater than the Prebid.js timeout, the s2sConfig timeout will be automatically adjusted to 75% of the Prebid.js timeout in order to fit within the auction process.

Tried setting timeout in s2s to 9000 and timeout in requestbids is 600, but tmax is still 9000 in the request.

**Comment by patmmccann** [comment]
@bretg can you remind me, is Magnite picking this up?

**Comment by patmmccann** [comment]
> Tried setting timeout in s2s to 9000 and timeout in requestbids is 600, but tmax is still 9000 in the request.

Should we track this as a different bug?

**Comment by bretg** [comment]
> is Magnite picking this up?

Code for PBS-Java looking at tmaxmax is in QA.

> Tried setting timeout in s2s to 9000 and timeout in requestbids is 600, but tmax is still 9000 in the request.

Not sure how that could be. @bmjoju - what version of PBJS are you running. The latest code in the ortbconverter does this:

```
request.tmax = s2sBidRequest.s2sConfig.timeout;
```

**Comment by bmjoju** [comment]
@bretg It is version v8.31.0. It was this in the documentation that didnt work and you also fixed the docs:

> If the s2sConfig timeout is greater than the Prebid.js timeout, the s2sConfig timeout will be automatically adjusted to 75% of the Prebid.js timeout in order to fit within the auction process.

The tmax is working and set to what im setting timeout to in the s2sConfig. But the docs just said that the timeout in the s2sConfig config would be lowered if the timeout on the banners was higher.

**Comment by jefftmahoney** [comment]
If a publisher did something like define `tmaxmax` _and_ `s2sConfig.timeout`, would it be correct to assume that we'd want the ortbConverter library to go with `tmaxmax`?

**Comment by bretg** [comment]
@jefftmahoney - the comment https://github.com/prebid/Prebid.js/issues/10964#issuecomment-1910838924 suggests 

> The ortbConverter library should check for the existence of ext.tmaxmax and if not there, set it to the timeout value passed to requestBids()

It's not an error condition.
