### ISSUE TITLE
Prebid 9: raise minimum node version from 12 to 16

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#10999]
Since Node 12 is the true minimum version, should I update package.json to that version in this PR? 
Yes, if 12 is actually required, it seems useful to reflect that in package.json

Should I just update circleci to Node 20? 
Yes, no concerns

Should the package.json min Node version be updated to 16?
No, not until prebid 9

For the next major release, it probably makes sense to update the min node version to at least Node 16 but maybe the current LTS?
Seems 16 is fine in prebid 9

_Originally posted by @patmmccann in https://github.com/prebid/Prebid.js/issues/10990#issuecomment-1915077902_

**Comment by dgirardi** [comment]
Let's update to node 20
