### ISSUE TITLE
Way to add script before any adm

### ISSUE THREAD

**Issue by asurovenko-zeta** [prebid/Prebid.js#10991]
## Type of issue
Question

## Description
I need to add the script before any adm to make it render with adm synchronously. I'd like to ask the proper way to do it. 
Thanks!

**Comment by dgirardi** [comment]
I am not sure I understand the question - rendering is done when you call `renderAd` or `setTargetingForGPTAsync`; you can add any logic you wish before that. If this doesn't work for you, please elaborate.

**Comment by patmmccann** [comment]
What sort of script; are you a bidder or publisher?

**Comment by asurovenko-zeta** [comment]
@patmmccann to monitor creative's quality I need to inject a creative checking script before any creative's code, from any source.

**Comment by patmmccann** [comment]
are you a bidder or publisher?
