### ISSUE TITLE
For Safe Frames, recommend sandbox:true in config

### ISSUE THREAD

**Issue by brondsem** [prebid/Prebid.js#1099]
For safe frames to be fully effective, `sandbox: true` should be set.  See [DFP example](https://developers.google.com/doubleclick-gpt/reference#googletag.PubAdsService_setSafeFrameConfig) and [details about the `sandbox`](https://support.google.com/dfp_sb/answer/4578089#SafeFrame) option (which is [widely supported by browsers](http://caniuse.com/#feat=iframe-sandbox) now)

I don't know if this can be set in DFP, or must be set in client JS.

This ticket is mostly informational.  When there are instructions for setting up safe frames, this should be included too.

**Comment by mkendall07** [comment]
@brondsem 
Thanks for the info, but DFP creates the iframe for the safeFrame, and is not controlled by Prebid.js

**Comment by brondsem** [comment]
This is a recommendation for publishers for the GPT code on their site.  It basically tells GPT/DFP to use the sandbox option when it makes the iframes.

I understand it's not something Prebid.js controls, but is just some important info if anyone wants to use safe frames effectively.

**Comment by mkendall07** [comment]
ok thanks. I'm not sure how you set this up in DFP (not sure you can?) so closing this out as it's not actionable by us.
