### ISSUE TITLE
bidObj.size is miss calculated for bid the object in the sovrn adaptor

### ISSUE THREAD

**Issue by pdramos1** [prebid/Prebid.js#110]
the bidobj is calculated incorrectly. 
							bid.width = bidObj.sizes[0][0];
							bid.height = bidObj.sizes[0][1];

So when renderAd is called the width and height are undefined.. and the iframe does not get sized correctly.

**Comment by mkendall07** [comment]
Hey @pdramos1 

Is the fix ready to be merged for this?

**Comment by pdramos1** [comment]
crap.. got totally pulled in 80 directions..
let me do the pull request.
