### ISSUE TITLE
Problem with SpringServe adapter.

### ISSUE THREAD

**Issue by adilets** [prebid/Prebid.js#1100]
I get this response from bidder.springserve.com:
```
pbjs.handleSpringServeCB({"nbr":0,"id":"1","seatbid":[{"seat":"YH","bid":[{"ext":null,"id":"7777-333-444_1","impid":"7777-333-444","crid":null,"price":0.64083135,"adm":"DEBUG BID CONTENT","dealid":""}]}],"cur":"USD"})
```
https://github.com/prebid/Prebid.js/blob/master/src/adapters/springserve.js#L73
has this check: `bid.params.impId === +responseBid.impid `
response from springserve has `responseBid.impid = "7777-333-444"`. Which becomes `NaN` because of preceding `+`

**Comment by matthewlane** [comment]
Closing with #1101 merged
