### ISSUE TITLE
Formalizing Prebid Approach - Privacy Sandbox and CMA Guidance - Request for Input

### ISSUE THREAD

**Issue by GLStephen** [prebid/Prebid.js#11021]
## Type of issue
Community Alignment, Future Documentation, Request for Input

## Description
The publisher committee has discussed ways that Prebid and publishers can contribute to that testing and CMA Guidance located at https://assets.publishing.service.gov.uk/media/649d6a5f45b6a2000c3d455f/20230629_CMA_industry_testing_update_B.pdf and titled "Quantitative testing of Google’s Privacy Sandbox technologies – CMA guidance to third parties on testing"

The document provides guidance from the Competition and Markets Authority (CMA) on the quantitative testing of Google's Privacy Sandbox technologies. It advises third parties, including ad techs, publishers, and advertisers, on testing methods that would contribute to the CMA's assessment of these technologies. The document details two preferred approaches to testing, key metrics to measure, and how participants can submit their results to the CMA. It also discusses the introduction of Chrome-facilitated testing environments and outlines the testing timeline, emphasizing the importance of third-party participation in this testing process to evaluate the effectiveness of the Privacy Sandbox in addressing competition concerns.

We identified that formal definitions of the metrics desired by the CMA would be the first step to getting useful info. That definition could then be used to propose code samples and similar to Prebid members to collect data from testing.

## Process

* identify a few key metrics from this doc - listed below
* quickly identify an accepted technical definition of those items
* discuss how those would be measured
* propose these as foundation for code samples and similar which will be created in a follow on effort

### Timeline

* The CMA is requesting data by End of Q2.
* This definitional work should be done by February 16th (that's fast, but possible)

### Goal

To allow Prebid members to provide valuable input into this process in ways that improve the relevance and comparability of that input across organizations.

### What we Need from You

Your input in into how the below can be measured, or how Prebid contributes to the measurement of these items, is requested. This is a relatively free form discussion.

## Items Under Consideration

* Revenues per impression
* Clicks and conversions per dollar
* Clicks per impression
* Web page latency
* Total unique bid requests served by DSPs/SSPs (as a proxy demand for individual ad techs’ services)
* % of planned campaign budget spent
* Unique viewers
* Average time spent or video completion rates
* Brand lift. 

### Notes

Some of these may not be measurable in Prebid alone, or at all.

**Comment by dgirardi** [comment]
> Some of these may not be measurable in Prebid alone, or at all.

Are there any that may, in your opinion? To me it looks like most need website or adserver analytics (I don't see how involving Prebid would help with those); except for "total unique bid requests served by DSPs/SSPs", which of course needs those platform to disclose their data.

**Comment by GLStephen** [comment]
@dgirardi Until we define them we don't really know, sorry to be overly pedantic, but until we have a working definition it's impossible to say

**Comment by GLStephen** [comment]
I've spent some time reviewing these items and the two that I think Prebid can or should address are:

- revenue per impression
- web page latency

We can at least get answers on those "from the Prebid perspective" even if not the full page and every last programmatic source.

These items I don't think we have proper visibility into, happy to be wrong if anyone has feedback:

- Clicks and conversions per dollar
- Clicks per impression
- Total unique bid requests served by DSPs/SSPs (as a proxy demand for individual ad techs’ services)
- % of planned campaign budget spent
- Average time spent or video completion rates
- Brand lift.

These items I think we could get an approximation of, but likely very inaccurate or not meaningfully comparable to other sources:

- Unique viewers

If there is some agreement on that then I can start speccing out an approach and maybe sample code.

**Comment by patmmccann** [comment]
`SELECT ProtectedAudienceAPIDelivery,
  TRIM(REGEXP_REPLACE(REGEXP_EXTRACT( customtargeting,"cookdep=[^;]+;"),'cookdep=',''),';') cookdep
  ,APPROX_QUANTILES(elapsed, 100)[OFFSET(50)] AS elapsed_time_50
,APPROX_QUANTILES(elapsed, 100)[OFFSET(75)] AS elapsed_time_75
  ,APPROX_QUANTILES(elapsed, 100)[OFFSET(90)] AS elapsed_time_90
FROM (
  SELECT
    *,
    CAST(eventtimeusec2 AS int64)-timeusec2 AS elapsed
  FROM
    `gam-360-data.at_gam_360_data.NetworkImpressions_18190176`
  UNION ALL
  SELECT
    *,
    CAST(eventtimeusec2 AS int64)-timeusec2 AS elapsed
  FROM
    `gam-360-data.at_gam_360_data.NetworkBackfillImpressions_18190176`) b
WHERE
  browser like '%Chrome%' 
  and customtargeting LIKE '%cookdep%'
  AND b._data_date = '2024-03-02'
  AND customtargeting NOT LIKE '%cookdep:;%'

GROUP BY
  1,2`

above is a sql code sample  to measure PAAPI latency in gam dtf files that assumes someone is setting the testing label as a key 'cookdep'
