### ISSUE TITLE
8.32.0 Price floors strange behaviour, that wasn't met at 7.35.0

### ISSUE THREAD

**Issue by Lvovk** [prebid/Prebid.js#11030]
## Type of issue
Bug

## Description
After I have updated Prebid.js version from 7.35.0 to 8.32.0 I have got this: "ERROR: Price Floors: Fields received do not match allowed fields", which was not met before

As I investigated in source code, this problem seems to be caused by fact, that one of adUnits has "floors" param, but other - not

You can see reproduction on this test page: https://prebid-deploy-test.b-cdn.net/prebid_price_floors_8.32.0_bug.html
Firstly I do request bids for adUnitWithFloorParam, which has "floors" param, then I request bids for adUnitWithNoFloorParam, that does not. Actually, this order is not neccessery, if bids for no floors unit will be reqeusted firstly, it will also lead to error. But if bids for both adUnits will be requested together - no error

Is it expected? And wich steps I should take to avoid this?

## Steps to reproduce
You can see reproduction on this test page: https://prebid-deploy-test.b-cdn.net/prebid_price_floors_8.32.0_bug.html
Firstly I do request bids for adUnitWithFloorParam, which has "floors" param, then I request bids for adUnitWithNoFloorParam, that does not. 

## Test page
test page with prebid version 7.35.0, no error
https://prebid-deploy-test.b-cdn.net/prebid_price_floors_7.35.0.html

Test page with prebid version 8.32.0, error met:
https://prebid-deploy-test.b-cdn.net/prebid_price_floors_8.32.0_bug.html

test page with prebid version 8.32.0, where bids for both adUnits requested together, no error:
https://prebid-deploy-test.b-cdn.net/prebid_price_floors_8.32.0_requested_together.html

## Platform details
Prebid version: 8.32.0

**Comment by dgirardi** [comment]
It appears to be just incorrect logging - there's no actual error; ad units are allowed to not have any floors and the auction should (and does) continue without any. Should be fixed with https://github.com/prebid/Prebid.js/pull/11037
