### ISSUE TITLE
Richaudience Bid Adapter: invalid responses on no bid

### ISSUE THREAD

**Issue by Sir-Will** [prebid/Prebid.js#11044]
## Type of issue
Bug

## Description
The bidder richaudience returns an invalid empty bid if there is no bid, this causes it to constantly log warnings and errors about it, and it's very irritating.
This doesn't seem to be a correct way of handling no bid, and it's the only bidder I have encountered it with.

Is there anything which can be done to stop this?

![chrome_2024-02-02_14-58-32](https://github.com/prebid/Prebid.js/assets/5961995/9ce2e524-d46e-4dd4-ad99-dd6d5c0e2bb0)

**Comment by richaudience** [comment]
Hi!
Sorry for this message of error, we know is very confused, but we're working on a new version to solve it. 
This error is when the request returns one response that is not a JSON, this we do when in our endpoint detects any issue in the request.
I need to be able to update the adapter, but this issue blocks the pull request, please you can check as solved for the moment?
Cheers

**Comment by patmmccann** [comment]
> I need to be able to update the adapter, but this issue blocks the pull request, please you can check as solved for the moment?

This issue does not block the pull request, please proceed with your solution

**Comment by patmmccann** [comment]
@richaudience please advise what your plan is here

**Comment by patmmccann** [comment]
@Sir-Will can you provide a link where this happens?

**Comment by patmmccann** [comment]
#11670

**Comment by Sir-Will** [comment]
> @Sir-Will can you provide a link where this happens?

Sorry for the delay. Not sure if it's still needed, but here is the adjusted demo: https://jsfiddle.net/0wfnt12z/4/

**Comment by richaudience** [comment]
Hello,

We made a change to our bidding infrastructure this morning to resolve the issue mentioned in this ticket. Apologies for the delay.

@patmmccann, please let us know if any further changes are needed from our side.

In this demo you can see that it is working correctly: https://jsfiddle.net/60nw7gbs/1/


Thank you.

**Comment by patmmccann** [comment]
@sir-will @richaudience reports fixed, if so can you close out?

**Comment by Sir-Will** [comment]
I don't see the error anymore now, thanks.
