### ISSUE TITLE
Reset the list of slots to be requested between each action for pubmatic

### ISSUE THREAD

**Issue by MahiMitr** [prebid/Prebid.js#1104]
## Type of issue
Bugfix

## Description
Request to ad server incrementally gets bigger with each time the ads are refreshed

## Steps to reproduce

1. Load a ad slot with pubmatic as the bidder
2. Observe the request made to: https://gads.pubmatic.com/AdServer/AdCallAggregator (The slot name is present once)
3. Refresh the ad Observe the request made to: https://gads.pubmatic.com/AdServer/AdCallAggregator (the slot name should be present once
4. Observe the request made to: https://gads.pubmatic.com/AdServer/AdCallAggregator (The slot name is present twice)
    .. continue and watch the number of times the snot name is present grow.

### Expected results

The slot name should only be in the query string once

### Actual results

The slot name is in the query string n times, where n is the number of times that slot has been refreshed.

## Platform details
Current version on all browsers

## Other information

Saw this issue in version 18

**Comment by mkendall07** [comment]
@MahiMitr 
Thanks for the bug report. I believe this issue is resolved with this commit: https://github.com/prebid/Prebid.js/commit/5c2de1e1c07954b1c9d9fd150ccbb5d96ceca99c
available in prebid 0.21.0. Can you confirm?
