### ISSUE TITLE
`buildMasterVideoTagFromAdserverTag()` not selecting winning bid

### ISSUE THREAD

**Issue by ronenst** [prebid/Prebid.js#1105]
## Type of issue
bug (?)

## Description
If an empty bid is received before a winning response `buildMasterVideoTagFromAdserverTag()` will select it as the "winning bid" and not set the correct `description_url`.

## Steps to reproduce
It is possible to reproduce this issue by setting 2 bidders on a video unit where one returns an empty response before the second one returns a winning response. This is difficult to do reliably so I will open a PR with a test case and a fix. 

Assuming the test case assumptions are correct, the issue can be reproduced by applying the unit test without the fix.

### Expected results
`buildMasterVideoTagFromAdserverTag()`  should selected the winning bid for the given ad unit from the list of bids received and set the master tag `description_url` to the winning bid `descriptionUrl`

### Actual results
`buildMasterVideoTagFromAdserverTag()` selects the *first* bid for the given ad unit regardless of whether it's an empty bid or not or if there is a higher CPM bid available and may set `description_url` to the wrong value.

## Platform details
Reproduces on v0.21.0

## Other information
I've done my best to understand the `buildMasterVideoTagFromAdserverTag()` mechanism, but I'm a little fuzzy on the details, I do have doubts that this is an actual bug, hence the (?)

**Comment by mkendall07** [comment]
Thanks for the bug report. @jaiminpanchal27 please check this out.
