### ISSUE TITLE
Removing liveconnect dependency from liveintent prebid user id module

### ISSUE THREAD

**Issue by deepthivenkat** [prebid/Prebid.js#11065]
## Type of issue
Liveintent worked on deciding how we could go about removing the external module dependency. We have a few options and our engineering team would like to have a call with 2 or 3 people from prebid to go over the options and make decisions on the implementation - once the options are set, we will be able to come up with estimates. 

If the prebid team could share 3-4 slots of availability for 30 mins - we will move our schedule around to make the call happen.

**Comment by patmmccann** [comment]
Let's arrange in Slack
