### ISSUE TITLE
Enforcement: stop importing events system in bidders

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#11071]
## Type of issue
feature request

## Description
to prevent the need for any adaptor to import the events system, we should expand the scope of onBidderError to more than just network errors, potentially to support use cases such as failing to understand the response or something of this nature. 

The following bidders currently import events

https://github.com/prebid/Prebid.js/blob/92703399478d918db90ed26a6772e8e4e4cfbeac/modules/holidBidAdapter.js#L8 fyi @kdesput please convert to use onBidWon

We should add the linter rule

**Comment by patmmccann** [comment]
docs: https://github.com/prebid/prebid.github.io/pull/5189

**Comment by patmmccann** [comment]
Summary of to do: fix holid adapter, add a linting rule for bidders not to import events

**Comment by dgirardi** [comment]
Also add linting rule to exclude bidders from importing adLoader
