### ISSUE TITLE
Questionable zmaticoo adapter parameters

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#11081]
## Type of issue
adapter rules

## Description
Looking over the documentation for the zmaticoo bid adapter, found something that escaped code review.
https://github.com/prebid/Prebid.js/pull/10881

1. It requires "bidId" as a parameter. This is probably wrong. bidId should be random, unless they mean something odd, but it's not even listed on their adapter docs
1. It requires a "device" object as a parameter. Clearly not allowed. They need to be reading from the ORTB2.device object, and there's no way they should be requiring IP address. (A) we can't share that data and (B) that should be easy for them get from their endpoint.

Heads up @lxj15398019970

**Comment by patmmccann** [comment]
tagging as 9 to indicate reversion of the merge if this isnt solved beforehand

**Comment by lxj15398019970** [comment]
@patmmccann i hava fixed it

**Comment by lxj15398019970** [comment]
> tagging as 9 to indicate reversion of the merge if this isnt solved beforehand

ok,i have fixed it
