### ISSUE TITLE
Standardize Video Bidder Params

### ISSUE THREAD

**Issue by fowler446** [prebid/Prebid.js#11095]
## Type of issue
feature request

## Description
Many SSPs expect different parameters when it comes to the video mediaTypes object. It would be great to do a sweep and standardize which fields are passed/required. I'm making this issue as a placeholder where we can aggregate these differences in SSPs. Maybe Prebid 9.0 would be a good place to enforce something like this. If we were using typescript we could enforce a video object type. I'm not sure the best way to enforce this otherwise.

There's also a wide variety in the video documentation that bidders supply. A standardization sweep would go a long way here.

**Comment by patmmccann** [comment]
related: https://github.com/prebid/Prebid.js/issues/10452

**Comment by fowler446** [comment]
triplelift playerSize docs are inconsistent with what their module expects:
https://docs.prebid.org/dev-docs/bidders/triplelift.html
https://github.com/prebid/Prebid.js/blob/master/modules/tripleliftBidAdapter.js#L234-L242

**Comment by patmmccann** [comment]
I know we plan to disallow requiring deprecated fields but should we also require that those passing the deprecated field also pass the updated field?

**Comment by fowler446** [comment]
> I know we plan to disallow requiring deprecated fields but should we also require that those passing the deprecated field also pass the updated field?

@patmmccann for sure we should be requiring the new `plcmt` field.

**Comment by fowler446** [comment]
33across requires the old placement field but only supports placement values 1, 2, 3, 4....

**Comment by fowler446** [comment]
Closed this issue in favour of moving the discussion here: https://github.com/prebid/Prebid.js/issues/9988

I think it would be good for us to ditch `playerSize` all together and move towards the openRTB standard of `w` and `h`.
