### ISSUE TITLE
hb_source is missing when the s2s testing adapter is enabled

### ISSUE THREAD

**Issue by premesh** [prebid/Prebid.js#11116]
## Type of issue
Bug

## Description
When the s2s testing module is enabled along side the prebid server adapter there should be an additional KVP sent to GAM (hb_source=s2s) when the bid is originated by PBS 
![image](https://github.com/prebid/Prebid.js/assets/5246343/5027eed5-8c10-4b6c-9306-7ad5f9528f03)

## Steps to reproduce
Enable both the Prebid Server adapter and the s2s testing adapter along with any bidder of your choice. When bids are received and sent to GAM (by winning the auction) you can see there is not an additional key `hb_source` being sent in the request. You will always be able to verify in GAM reporting that this key is not being reported. 
## Test page
Unfortunately i dont have a test page which can force bids to win. If there is a way to do this please let me know and ill setup a test page. 

### Expected results
`hb_source = s2s` is sent along with winning bids to individual ad units 
### Actual results
`hb_source` is not sent at all
## Platform details
PBJS 8.36.0

**Comment by spormeon** [comment]
on the flip side of this, I'm seeing that the "source: client" isnt being sent in 8.36.0 with no custom targeting set & enableSendAllBids: false

![Adysis_Video_Demo-4_png](https://github.com/prebid/Prebid.js/assets/8503167/7b892a86-ad4e-47d2-a322-c39e0a88761d)

![outstreamAmazon_html_—_Prebid_Publishers__Workspace__png](https://github.com/prebid/Prebid.js/assets/8503167/05cb62e0-edc6-4587-befc-cd220d4e7074)

**Comment by bretg** [comment]
@premesh - found that the following configuration has been needed since PBJS 5.0 to enable the hb_source targeting key. 

```
pbjs.setConfig({
        targetingControls: {
          addTargetingKeys: ['SOURCE']
        }
});
```

Will update the s2sTesting module doc.

Please confirm in your environment.

**Comment by premesh** [comment]
Will confirm now @bretg
