### ISSUE TITLE
How to install prebid and ga

### ISSUE THREAD

**Issue by tshaked** [prebid/Prebid.js#1112]
## Custom bidders version with ga
Hey There,
I downloaded the project, customize the "list-of-adapters.json" (to bidders that I work with)
added a line to package.json  - 
"analytics": ["ga"], 

Then run the build like that : 
gulp build --adapters path/to/your/list-of-adapters.json

Still got an error :
"ERROR: Prebid Error: no analytics adapter found in registry for
        ga." ""

someone can help me understand what is the problem?
btw - v0.21.0 this is the version that is generated.

Thanks!

**Comment by tshaked** [comment]
Just to be clear - I run from the project folder: 
gulp build --adapters list-of-adapters.json

**Comment by tshaked** [comment]
SOLVED : Put "ga" in "analytics.json" file.

**Comment by mercuryyy** [comment]
You can build it with Analytics from here now - prebid.org/download.html
as well.

**Comment by tshaked** [comment]
Cool New Feature 👍 👍

**Comment by ptomasroos** [comment]
or you can run

gulp build --adapters list-of-adapters.json --analyticsAdapters list-of-analytics-adapters.json
