### ISSUE TITLE
Adagio Bid Adapter: oRTB validation bug for video.delivery param

### ISSUE THREAD

**Issue by andyblackwell** [prebid/Prebid.js#11132]
## Type of issue
Bug

## Description
The oRTB validation for the video param `delivery` is incorrectly set as an integer, rather than an array of integers, and results in the value being removed and a console warning of:
> WARNING: Adagio: The OpenRTB video param delivery has been skipped due to misformating. Please refer to OpenRTB 2.5 spec.

(^ could also fix the "misformating" spelling error too while in there)

https://github.com/prebid/Prebid.js/blob/8.37.0/modules/adagioBidAdapter.js#L80

https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/main/AdCOM%20v1.0%20FINAL.md
![image](https://github.com/prebid/Prebid.js/assets/372590/a95e93ed-f6d3-4231-92fe-e0d4a3d0271c)

## Steps to reproduce
configure a video bid for adagio and run an auction for it

### Expected results
`video.delivery` param is properly set on the bid request to adagio

### Actual results
`video.delivery` param is removed from the bid request to adagio

**Comment by fowler446** [comment]
@osazos FYI

**Comment by osazos** [comment]
Thanks for pointing that, we will fix it quickly.
