### ISSUE TITLE
Q: Will userSync.syncEnabled.false also disable userSync.userIds ?

### ISSUE THREAD

**Issue by lewisalee-rea-group** [prebid/Prebid.js#11146]
## Type of issue

Question

## Description

Will setting userSync.syncEnabled.false remove iframe/image cookie syncing as well as remove userSync.userIds object?

## Steps to reproduce

`pbjs.setConfig({
    userSync: {
        syncEnabled: false
    },
    userIds: [],
});`

### Expected results
Ideally we would like to disable all iframe/image user syncs while keeping userSync.userIds active and passing through UIDs from the ID module.

## Platform details

Prebid.js V8.23

## Other information

https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html#setConfig-Configure-User-Syncing

**Comment by dgirardi** [comment]
`syncEnabled` does not (or should not) affect user IDs. Setting `syncEnabled: false` should do what you want.

**Comment by lewisalee-rea-group** [comment]
@dgirardi thanks for the feedback

**Comment by ChrisHuie** [comment]
@lewisalee-rea-group did that work? Can we can close this issue?

**Comment by lewisalee-rea-group** [comment]
@ChrisHuie thanks, all good from our end
