### ISSUE TITLE
Question: using prebid on a page already loading prebid

### ISSUE THREAD

**Issue by ilanb1996** [prebid/Prebid.js#11140]
## Question
Im trying to load my prebid handling code for video ads on a page that already has its own prebid handling logic,
the page loads its own prebid. then it loads my code and in my code im also using prebid js to get bids for video ads.
When the page loads my code it seems like my code is somehow overwriting the page's existing ad. unit configuration, im using `pbjs.addAdUnits` to  add my video ads configuration nut when im inspecting the page using professor-prebid is seems like all existing ad units are gone and only my new configuration exists.
Also it seems like im overwriting the pages prebid version to an older one
The page is using 8.23 and im trying to use 7.48
I've seen in the documentation i can override `globalVarName` in the `package.json` of prebid.js, is this the best approach to this issue? 

### Expected results
My ad unit will be displayed in addition to the pages existing ad units

### Actual results
The existing ad units being overwritten with my video ad unit

## Platform details
testing on chrome using prebid.js 7.48

**Comment by patmmccann** [comment]
> I've seen in the documentation i can override globalVarName in the package.json of prebid.js, is this the best approach to this issue?

yes, this is popular
