### ISSUE TITLE
Q: getPAAPIConfig returns empty object

### ISSUE THREAD

**Issue by wsusrasp** [prebid/Prebid.js#11172]
## Type of issue

Question
 
## Description

I am testing new feature introduced in https://github.com/prebid/Prebid.js/pull/10930 (thank you for adding this), but I have some problems with retrieveing configs. This does not seem like a bug, but I cannot find any information on why this happens. I found out that this is due to configs being added to USED variable, which is checked when returning config and when candidate is present in it, it is removed from result. I'd like to ask how should I use the new functionality to actually get the configs, since it seems that I am either calling it incorrectly or at wrong time.

Relevant code: https://github.com/prebid/Prebid.js/blob/master/modules/paapi.js#L155

**Comment by dgirardi** [comment]
If you are using `fledgeForGpt`, it automatically "uses" configs unless you `setConfig({paapi: {gpt: {autoconfig: false}}})`. Otherwise, `getPAAPIConfig` returns configs that it did not already return previously - meaning that if called twice in a row, the second call returns an empty object.

**Comment by wsusrasp** [comment]
This was exactly the case, thank you for quick feedback.
