### ISSUE TITLE
Userid / TCF Module: stop storing consent hashes

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#11183]
The CJEU has affirmed the tc string, and correspondingly the hash of it, are personal data. let's delete the functionality of storing tc string hashes entirely. See https://github.com/prebid/Prebid.js/issues/6386 and https://iabeurope.eu/cjeu-ruling-clarifies-limited-role-of-iab-europe-in-tcf/

**Comment by patmmccann** [comment]
related: https://github.com/prebid/Prebid.js/issues/10276

**Comment by jwrosewell** [comment]
The key point is whether the hashed data can be used, alone or in conjunction with other data, to identify an individual. If it can, then it falls under the definition of personal data according to the UK GDPR and the Data Protection Act 2018. Therefore, it must be handled with the same care as any other personal data, ensuring compliance with data protection principles and individuals’ rights.
