### ISSUE TITLE
Grid / GridNM Bid Adapter bidding but not monetizing

### ISSUE THREAD

**Issue by ChrisHuie** [prebid/Prebid.js#11194]
Issue from another source: 

"Has anyone upgraded to prebid v8.23+ and have successfully got JW Boost (grid/gridNM) bidder to work? JW haven't been able to find any issues with the set-up. However, the bidder is not monetizing at all. They are bidding but not winning I believe their bidder is not compatible with the later version of prebid. Our Head of Tech says there is no error and everything looks fine...The only warning we getting is storage access?."

![image (1)](https://github.com/prebid/Prebid.js/assets/3444727/764925b0-eecb-4201-b272-4ae355cc2f8f)
![image (2)](https://github.com/prebid/Prebid.js/assets/3444727/bfef7c9a-148c-429e-85c8-1a474163cbc1)
![image (3)](https://github.com/prebid/Prebid.js/assets/3444727/b46752cc-532a-4fe5-ad3f-23266efbd4dd)

**Comment by dgirardi** [comment]
that log shows no bids from grid.

**Comment by spormeon** [comment]
plcmt: ?

**Comment by patmmccann** [comment]
Raptive gets bids from Grid on 8.23+

If we could identify OP to engage, happy to reopen.
