### ISSUE TITLE
Pre Bid not working

### ISSUE THREAD

**Issue by yogeshadsparc** [prebid/Prebid.js#112]
Hi Guys,
when i changed existing placement ID with my own AppNexus placement ID , it's stopped working.
Is there any credentials or any variable need to change for AppNexus?

**Comment by mkendall07** [comment]
Hi @yogeshadsparc 
Are you seeing bids returned? Please add `?pbjs_debug=true` into the URL of the page you are testing to see output in the debug console.

**Comment by prebid** [comment]
@yogeshadsparc let us know how we can help. It's also possible that your own placement ID doesn't have ads enabled yet from the server side. Reaching out to your account services folks should solve that issue.
