### ISSUE TITLE
IAS RTD Module: url has been blocked by Firefox's policies

### ISSUE THREAD

**Issue by GuillQuirin** [prebid/Prebid.js#11206]
## Type of issue
BUG

## Description

`Ad Safe Protected tracking pixels is being shimmed by Firefox. See` [https://bugzilla.mozilla.org/show_bug.cgi?id=1717806](https://bugzilla.mozilla.org/show_bug.cgi?id=1717806)` for details.` 

![image](https://github.com/prebid/Prebid.js/assets/11681755/bf2e70ef-ee1a-4074-b9e3-2451e18c6df3)

## Steps to reproduce

- Go on this page [https://www.notretemps.com/jeux/jeux-en-ligne/mots-fleches/force-1/mots-fleches-gratuits-force-1-13-mars-2024-grille-3163](https://www.notretemps.com/jeux/jeux-en-ligne/mots-fleches/force-1/mots-fleches-gratuits-force-1-13-mars-2024-grille-3163)

- Scroll until the newsletter button to find the video player

- The player will execute Prebid and its IAS module

- Firefox will cancel the IAS call and replace with a fake text response

## Test page
[https://jsfiddle.net/6gspm0fr/](https://jsfiddle.net/6gspm0fr/)

## Platform details

Prebid JS v8.25.0
Firefox (Windows) 123.0.1

**Comment by patmmccann** [comment]
Are you in Firefox strict mode? Some others have reported it isn't compatible with advertising

**Comment by patmmccann** [comment]
This is quite a reasonable concern, but not one this project can impact as far as we know? cc @rbarbini-ias @raguilar-ias @bengel-ias do you want to comment or change your documentation?

**Comment by dgirardi** [comment]
There's a discussion here on what to do about strict mode: https://github.com/prebid/Prebid.js/issues/10126 closing this as a duplicate.
