### ISSUE TITLE
Insticator Bid Adapter: faulty video param validation leads to rejected bids

### ISSUE THREAD

**Issue by andyblackwell** [prebid/Prebid.js#11224]
## Type of issue
bug

## Description
- for several **video** params, the validation added in this PR seems incorrect:
  - #10969
  - https://github.com/prebid/Prebid.js/blob/28cceb9a17cfa3048d9211ef9f0c27fc012828cd/modules/insticatorBidAdapter.js#L15-L42
- the `isSubarray()` helper is used for params it doesn't make sense for, and because it uses a `.every()` check, it rejects valid bids
- example: 
  - `protocols` ([oRTB spec list](https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/main/AdCOM%20v1.0%20FINAL.md#list--creative-subtypes---audiovideo-))
  - for a config with: `protocols: [1,2,3,4,5,6,7,8]`
  - even though valid protocols are allowed, just because `1` and `4` are also allowed, the `.every()` check fails and the adapter rejects the bid
  - a `.some()` check makes more sense here, would recommend at least a separate helper for some of these params
- similarly for:
  - `api` ([oRTB spec list](https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/main/AdCOM%20v1.0%20FINAL.md#list--api-frameworks-)) - if the list includes both supported & unsupported apis, the bid gets rejected
  - `playbackmethod` ([oRTB spec list](https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/main/AdCOM%20v1.0%20FINAL.md#list_playbackmethods))
    - for playbackmethod, possibly this one is correct and what they mean, just are losing out on bids if not supporting values: 5-7

### Expected results
- expect a bid that allows at least **some** of the supported values for the mentioned params to be valid

### Actual results
- bid gets rejected as invalid

## Platform details
v8.33.0 +

## Other information
 #10969

**Comment by dgirardi** [comment]
FYI @shubhamc-ins

**Comment by patmmccann** [comment]
@andyblackwell if you PR the adapter we're happy to contact them before merging

**Comment by shubhamc-ins** [comment]
Thanks @andyblackwell for the details.

Actually we have the validation in that particular way since we don't support, e.g [1, 4] for protocols.

But I see your point as well, We will add a patch for it and pass through the values which we support if in case the array contains both supported and unsupported values.
