### ISSUE TITLE
PBS Bid Adapter: support ORTB exp field as bid cache length

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#11230]
## Type of issue
Enhancement

## Description
the PBS bid adapter currently sets the bid cache TTL for PBS bids to s2sConfig.ttl or a default value with this line of code:

```
ttl: s2sBidRequest.s2sConfig.defaultTtl || DEFAULT_S2S_TTL,
```

Server-side bid adapters should be able to set OpenRTB seatbid.bid.exp to define this value.

`exp` is defined in ORTB as "Advisory as to the number of seconds the bidder is willing to wait between the auction and the actual impression."

The proposed new logic for pbsBidAdapter is:

1. Check the bid response for `exp` and use that if available
2. Else, use s2sConfig.defaultTtl
3. Else use DEFAULT_S2S_TTL

**Comment by dgirardi** [comment]
That is the current algorithm. The line you linked sets the fallback value (`context.ttl`) for when `exp` is not set, but `exp` has priority:

https://github.com/prebid/Prebid.js/blob/ecdeb25a4796b5fee82159b9388010b556d45dd0/libraries/ortbConverter/processors/default.js#L90

**Comment by bretg** [comment]
Thanks - didn't look in that library. Closing!
