### ISSUE TITLE
Rhythmone: Multiple requestBids Not Working

### ISSUE THREAD

**Issue by CarsonBanov** [prebid/Prebid.js#1123]
## Type of issue

Bug 
## Description

Similar issue to [this one](https://github.com/prebid/Prebid.js/issues/481).  Upon making a second request to  `pbjs.requestBids` the Rhythmone adapter never returns a bid causing the Prebid auction to hit the timeout.

## Steps to reproduce

Define two ad units. Run requestBids twice - once the first ad unit and a separate one on the second. Then run `pbjs.getBidResponses()` or log the bids in some other way.  Rhythmone won't bid or even return an empty bid.

## Other information

.cc @ehoch @mkendall07 @protonate

**Comment by mkendall07** [comment]
Looks like this fix is in master.
