### ISSUE TITLE
¿Que?

### ISSUE THREAD

**Issue by matthewoates** [prebid/Prebid.js#1124]
## Type of issue
Naming/API

## Description
Trivial gripe, but are we interested in renaming/aliasing the `pbjs.que` to `pbjs.queue`?

see: https://www.merriam-webster.com/dictionary/Que

**Comment by ericso** [comment]
👍

**Comment by snapwich** [comment]
If we do update it, I'd suggest just changing it to `cmd` like googletag uses.  Just as short without the ¿Wat?

**Comment by mkendall07** [comment]
Believe it or not, this was intentional - just to make the code shorter. Maybe not everyone appreciates it but it's documented sufficiently. 

With that said, I'm fine to make an alias to the function  at `pbjs.queue` as well so we don't break existing pages. Feel free to submit a PR.

**Comment by mkendall07** [comment]
or `cmd`.
