### ISSUE TITLE
Prebid file not built properly

### ISSUE THREAD

**Issue by skapoorViant** [prebid/Prebid.js#11251]
## Description
I am trying to download Prebid.js with Viant adapter, and in the downloaded file, it gives me following error:
`{"error":"Prebid file not built properly","requestId":"a803c181-d071-4e8b-b0a4-0d24c2a00c15"}`

## Steps to reproduce
1. Select Viant from the following link and click download prebid.js button
   [https://docs.prebid.org/download.html?version=8.39.0&modules=consentManagement%2CenrichmentFpdModule%2CgdprEnforcement%2CgptPreAuction%2CconsentManagement%2CgdprEnforcement%2CgptPreAuction%2CconsentManagementGpp%2CconsentManagementUsp%2CgppControl_usnat%2CgppControl_usstates%2CviantBidAdapter](url)

Please let us know if there is anything we would need to do from our side to resolve this issue.

**Comment by dgirardi** [comment]
The module name, `viantOrtb`, does not match the bidder code `viant`. [This](https://github.com/prebid/prebid.github.io/pull/5221) should fix the download page.
