### ISSUE TITLE
setTargetingForGPTAsync() not accepting adUnitCodes argument

### ISSUE THREAD

**Issue by andyblackwell** [prebid/Prebid.js#1129]
## Type of issue
Bug

## Description
http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.setTargetingForGPTAsync
As per the documentation `pbjs.setTargetingForGPTAsync` should be able to take an array of adUnitCodes to limit units to set targeting on. But this looks to have not been fully implemented, as that method in the code ignores any arguments passed to it. `adUnitCodes` should be passed to both `targeting.resetPresetTargeting()` and `targeting.getAllTargeting()`. But `targeting.resetPresetTargeting()` doesn't actually accept an array of adUnitCodes either, so seemingly all non-specified units would be cleared regardless, which would cause other problems.

```
/**
 * Set query string targeting on all GPT ad units.
 * @alias module:$$PREBID_GLOBAL$$.setTargetingForGPTAsync
 */
$$PREBID_GLOBAL$$.setTargetingForGPTAsync = function () {
  utils.logInfo('Invoking $$PREBID_GLOBAL$$.setTargetingForGPTAsync', arguments);
  if (!isGptPubadsDefined()) {
    utils.logError('window.googletag is not defined on the page');
    return;
  }

  //first reset any old targeting
  targeting.resetPresetTargeting();

  //now set new targeting keys
  targeting.setTargeting(targeting.getAllTargeting());

  //emit event
  events.emit(SET_TARGETING);
};
```

## Steps to reproduce
https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L239

### Expected results
as documented, that only the passed adUnitCodes targeting would be cleared and set

### Actual results
all adUnitCodes targeting are cleared and set

## Platform details
v0.21.0

**Comment by matthewlane** [comment]
Right you are, this should accept an adUnitCodes param. I've made a note to address this, though feel free to open a PR if you'd like. Thanks for the report

**Comment by mkendall07** [comment]
Let's make sure we get a unit test to cover this as it's part of the public API. Thanks for the bug report.

**Comment by matthewlane** [comment]
`setTargetingForGPTAsync` now takes an `adUnitCodes` parameter with #1158
