### ISSUE TITLE
datablocksBidAdapter: Cannot read properties of undefined (reading 'body') on Chrome 

### ISSUE THREAD

**Issue by igor322** [prebid/Prebid.js#11319]
## Type of issue
Bug

## Description
The function getUserSyncs in the datablocksBidAdapter is throwing the following error after every action ends:
`TypeError: Cannot read properties of undefined (reading 'body')`

## Platform details
Prebid version: v8.42.0
Browser: Chrome (Version 123.0.6312.58 (Official Build) (arm64))
Node: v16.20.1 and v20.11.1
OS: Mac

## Other information
It doesn't happen on edge

**Comment by dgirardi** [comment]
FYI @htang555

**Comment by jefftmahoney** [comment]
It looks like in most other adapter implementations, the code first checks to see if a response is even present (e.g. `if (responses[0].body)` etc.), while no such check is made with the datablocksBidAdapter:

```
  getUserSyncs: function(options, rtbResponse, gdprConsent) {
    const syncs = [];
    let bidResponse = rtbResponse[0].body; // <- making an assumption the response is not undefined
    let scope = this;
```
