### ISSUE TITLE
minBidCacheTTL better memory optimization

### ISSUE THREAD

**Issue by andyblackwell** [prebid/Prebid.js#11310]
## Type of issue
feature request

## Description
currently `minBidCacheTTL` is applied at the auction level, so if you get a single bid with a long TTL, like an hour, then all the bids in the auction stay around for the full hour
https://github.com/prebid/Prebid.js/blob/4577159c0ec31896e5e0bd7654638861a265c189/src/auctionManager.js#L43-L48

any reason we couldn't remove bids as they expire directly, in the auction object?
https://github.com/prebid/Prebid.js/blob/4577159c0ec31896e5e0bd7654638861a265c189/src/auction.js#L156

could leave the auction-level removal as well, as that also frees up memory from all the other stored info in an auction like: requests, nobids, non bids, winning bids, etc

## Other information
#10308

**Comment by patmmccann** [comment]
@andyblackwell great Idea! Does aditude plan to submit the fix?

**Comment by fowler446** [comment]
@patmmccann How about this ^

**Comment by patmmccann** [comment]
closing as stale, picking up at prebid.org
