### ISSUE TITLE
Is there a reason why the Criteo adaptor is not included in the list on the Download page? Would it be possible to add it?

### ISSUE THREAD

**Issue by rmertens** [prebid/Prebid.js#1131]
## Type of issue
Question relating to the Download page on Prebid.org

## Description
Is there a reason why the Criteo adaptor is not included in the list on the [Download](http://prebid.org/download.html) page? Would it be possible to add it?

## Extra information
I'm not 100% sure this is the right place to ask. If not, my apologies!

**Comment by matthewlane** [comment]
It may have been by Criteo's request.

ccing @icaroulle or @Swiiip in case there is further information on this

**Comment by Swiiip** [comment]
Hello, indeed. Please feel free to contact Criteo commercial team to have access to Criteo prebid solution

**Comment by rmertens** [comment]
Out of curiosity, what's the reasoning behind this? 

The commercial team points me to the adapter:
https://github.com/prebid/Prebid.js/blob/master/src/adapters/criteo.js

**Comment by tedrand** [comment]
@rmertens from my very limited understanding from working with this partner for publishers, they have been changing around their adapter and provide integration docs that are a little more version-specific because of this.

**Comment by rmertens** [comment]
Their integration docs just say 'From v0.18 Prebid includes Criteo', and their commercial team tells me to use the raw adapter. It seems to me that the Criteo commercial and technical teams don't communicate well :)

**Comment by matteo-bordin** [comment]
@rmertens thanks for your interest in Criteo Header Bidding adapter! We indeed have provided support to Prebid since v0.18 but at this stage the adapter cannot be automatically built via the classic Prebid download interface. So both messages (from R&D and commercial team) are fully consistent :) Feel free to contact Criteo commercial team if you need additional info on how to build Prebid with Criteo the adapter, and how to configure your Criteo account to benefit from it.

**Comment by dugwood** [comment]
The code is available in their forked repository: https://github.com/criteo-forks/Prebid.js/blob/criteo-1.0/modules/criteoBidAdapter.js

You shouldn't use it without their approval first (as your Criteo account may not be enabled for Prebid).

**Comment by dugwood** [comment]
A little update: Criteo has just been added to Prebid 0.12.0
