### ISSUE TITLE
Reporting discrepancies with v.0.21.0

### ISSUE THREAD

**Issue by tshaked** [prebid/Prebid.js#1132]
## Description
We have moved back to version 0.20.0 after seeing reporting discrepancies in the new version (0.21.0).
Once we moved back to the older version, the discrepancies were gone.

We now want to add new bidders, but when we do so through the PreBid website, it automatically gives us the new version. 

How can we add new bidders to the old version (0.20.0)?

**Comment by mkendall07** [comment]
Most likely related to  this https://github.com/prebid/Prebid.js/commit/f4db964e7819b3b7126c7414cb0e9530099ddb1c

We will be releasing a new version soon and update the download page with the fixed version.

**Comment by miki-rapoport** [comment]
@mkendall07 @tshaked We had the same issue! based on our analysis, this seems to be isolated to IE/Edge and is happening due to lack of support for object.assign , which was used here:  [7c6ecb3](https://github.com/prebid/Prebid.js/pull/1055/commits/7c6ecb331814effad08a33562b6d75120f48ae63)

**Comment by mkendall07** [comment]
@miki-rapoport 
We have a polyfill for `object.assign` https://github.com/prebid/Prebid.js/blob/master/.babelrc 
Do you have any examples of this not working in IE/Edge?

**Comment by miki-rapoport** [comment]
@mkendall07 we actually still have it live on [stage](http://stage.directexpose.com/natalie-portman-welcomes-baby-girl-family/?pbjs_debug=true) and I was able to recreate in IE11. DFP serves the creative code properly, but it never gets to "rendering".

**Comment by ebweb** [comment]
We are having the same issue.  Discrepancies had been a normal 5%-7% per partner, but abut two weeks ago, we added a new partner and used the latest version of PreBid, each partner jumped to a 13-15% discrepency.  We went back to the older Prebid version and the discrepencies were gone, but this week, we had to add a new partner, so we again tested the most current version of PreBid.  And discrpencies immediately jumped back up.

**Comment by headerbidding** [comment]
Is it fixed in version 22.2 ?

**Comment by protonate** [comment]
@ebweb you might try version 0.22.2 without also adding any demand partners or making other changes to your setup.

**Comment by protonate** [comment]
@headerbidding The issue with `Object.assign` support in IE is addressed in 0.22.2.

**Comment by protonate** [comment]
@tshaked @miki-rapoport and others reporting issues, please try the recently released 0.22.2 version as it should address the issues behind discrepancies reported here, specifically support for `Object.assign` in IE.

Closing issue, please open a new ticket if there are continuing concerns or questions about version 0.22.2.
