### ISSUE TITLE
Doceree AdManager : Unable to download PrebidJS file when selecting DocereeAdManager adapter(https://docs.prebid.org/download.html)

### ISSUE THREAD

**Issue by Doceree-techStack** [prebid/Prebid.js#11352]
Please look into the issue which raised earlier https://github.com/prebid/Prebid.js/issues/11329

This issue is not fixed yet and it was closed by making changes in Doceree md file which was wrong and we have raised issue for reverting the changes(https://github.com/prebid/prebid.github.io/pull/5254). The changes should have been made in docereeadmanager.md file as doceree and docereeadmanager are different adapters.  

Please look into this asap

**Comment by bretg** [comment]
I merged the docs PR. But also noticed that doceree.md had the title "Prebid DivReach Bidder Adapter". Given that there was existing DivReach, looked like a copy-paste error to me, so I opened https://github.com/prebid/prebid.github.io/pull/5262 . Will merge when you confirm this was an error @Doceree-techStack .

Anyhow, downloading Doceree and Doceree AdManager from the download seems to work now. Please confirm.

**Comment by Doceree-techStack** [comment]
Downloading Doceree AdManager from the download is working now. But make changes only for docereeadmanager.md file and not doceree.md file as it is not maintained by us. As you have already merged the pull request please revert it.
