### ISSUE TITLE
Custom Build Not Bundling Analytics Adapters

### ISSUE THREAD

**Issue by GLStephen** [prebid/Prebid.js#1136]
## Type of issue
Bug

## Description
gulp build does not seem to be bundling configured adapters as of Version 21. I have not tracked down the issue completely, but I am posting the bug in case it sends up any flares for anyone who did work in this area.

## Steps to reproduce
1. Add an analytics adapter to package.json, even 'ga'

"analytics": [
    "ga"
  ],

2. Run 'gulp build' 

### Expected results

The analytics adapter is included in the build.

### Actual results

The analytics adapter is not included in the build.

## Platform details
Version 21

## Other information
None

**Comment by GLStephen** [comment]
Seems to have been a case of PEBKAC. A fresh clone resolved the issue.

**Comment by mkendall07** [comment]
analytics adapters are specified in `analytics.json` now.

**Comment by GLStephen** [comment]
@mkendall07 Thanks for the info, the issue was more fundamental. An upstream merge left my fork in a weird state. Resolved now.
