### ISSUE TITLE
Bids requests failing if bidder missing

### ISSUE THREAD

**Issue by AntoineJac** [prebid/Prebid.js#1137]
## Description
When settings the videoAdUnit parameters, if one of the bidder is not present in the Prebid.js file, it will make all the request crash... I have tested with the display and if a bidder is not present, other calls are still and correctly made.

## Steps to reproduce
Please reach the following page where some random Appnexus and Rubicon parameters. The prebid.js has been built with only Rubicon adapter. As you will see no requests are made:
http://legba.alwaysdata.net/VideoR.html

I have used exactly the same code with a prebid.js built this time with Rubicon and Appnexus adapters. As you will see this time everything is ok:
http://legba.alwaysdata.net/VideoRA.html

### Expected results
If a bidder is not present in the prebid.js tag, it should skip it but still make the call for the others bidders.

### Actual results
All requests are skipped.

## Platform details

The last version 0.21.0

**Comment by matthewlane** [comment]
I've made a note to fix this, though feel free to open a PR if you'd like. Thanks for the report
