### ISSUE TITLE
${AUCTION_PRICE} macro is not being replaced

### ISSUE THREAD

**Issue by skapoorViant** [prebid/Prebid.js#11387]
Hello Team,

Please find the sample response and event URL. The ${AUCTION_PRICE} macro is not being replaced in event tracking URL, though it is coming as encoded. 
`{
  "dtp": "rtb_response",
  "host_node_name": "i-0de5cb59043dd69d1",
  "host_node_ip": "10.55.8.214",
  "host_node_zone": "us-east-1b",
  "host_node_version": "2.0.5147soak",
  "ep": "/d/rtb/v25/prebid/bidder",
  "ts": "1713831808093",
  "sid": "1d160339-71a4-4aa3-ab4d-84597cf785fb-559ae0e9e63b7089",
  "id": "3c5f7d42-6bc3-45cf-bb5f-e99c3c04b202",
  "seatbid": [
    {
      "bid": [
        {
          "id": "1d160339-71a4-4aa3-ab4d-84597cf785fb-559ae0e9e63b7089",
          "impid": "559ae0e9e63b7089",
          "price": 0.700001,
          "adid": "58612-424808-2152925",
          "nurl": "https://events2-us-east-1.ipredictive.com/d/rtb/v25/prebid/won?zid=prebid_1_0_1&sid=1d160339-71a4-4aa3-ab4d-84597cf785fb-559ae0e9e63b7089&crid=23501042&adid=58612&oid=2152925&cid=424808&spid=851&pubid=464&site_id=3760177370&auid=6040313&algid=1&algrev=1&offpc=0.7&maxbid=0.76&optpc=1.074270486831665&cstpc=0.7&xts=1713918208&pbap=CgMweDAQBhoBZiIBMioFQXBwbGUyBmlQaG9uZToJaVBob25lIE9TQgQxNy40UgJlbloLU01BUlRfUEhPTkVgAGoGQkFOTkVSigECLTWQAQCaASBjMDUzYTc2ZjQ0ODNkYmI3ODA2NmEyYTBmYWY1ZTc0NqUBgxElQq0BWxPAwsABAMgBAdIBBlBVQkxJQ-oBI0lBQjEsSUFCOSxJQUIxNyxJQUI2LTUsSUFCNixJQUIxNC00-gEgZTFjZDkzMDlmMWZjYjE4ZWYwYjkyZjQ5NGEzZTU2M2KCAiQ1ZGNhZWE5Mi1jOGE5LTQwM2UtYWM0NC05OGQzNjkwZjhlNDKKAgdVTktOT1dOkgIMNjguOTkuMzEuMTgzmgIDRTJFoAIAsAIC8gKOAU1vemlsbGEvNS4wIChpUGhvbmU7IENQVSBpUGhvbmUgT1MgMTdfNCBsaWtlIE1hYyBPUyBYKSBBcHBsZVdlYktpdC82MDUuMS4xNSAoS0hUTUwsIGxpa2UgR2Vja28pIENyaU9TLzEyMy4wLjYzMTIuNTIgTW9iaWxlLzE1RTE0OCBTYWZhcmkvNjA0LjH6AgZTYWZhcmmCAwU2ODExNIoDBU9tYWhhkgMDNjUymgMCTkWiAwJVU6oDAjEwsQMAAAAAAAAAALoDBzUwNzQ0NzLCAwM2NTLKAxJDb3ggQ29tbXVuaWNhdGlvbnPSAwR3aWZp2gMSYmFyc3Rvb2xzcG9ydHMuY29t6gMkM2M1ZjdkNDItNmJjMy00NWNmLWJiNWYtZTk5YzNjMDRiMjAyqQQAAABglmIYP7EEAAAAQL9Xnzy5BHsUrkfhemQ_wAQZygQPNjQwLCA4MzAsIDkyMzMw4QSamZmZmZnZP-oEBDE3LjTyBBRDaHJvbWUgTW9iaWxlIG9uIGlPU_oEAk5FggUEMS0tLcoFATHSBSlwcmViaWQtdy04OTkxMjJhMTU2NGM1NTcxNWViMTIwZGE5NzcyNzFjOfoFJTI6d2ViLDIwNTpVUy9ORS9PbWFoYSwyMDA5Oi00NTUsMzE0OjGABgGiBgw2OC45OS4zMS4xODPQBgDiBi8KB1VOS05PV04SJDVkY2FlYTkyLWM4YTktNDAzZS1hYzQ0LTk4ZDM2OTBmOGU0Mg&au_pc=${AUCTION_PRICE}&rand=1713831808093",
          "adm": "<div id='adelphic_ads' style='margin:0;padding:0;border:0;width:300;height:250;overflow: hidden;'>\n\n\n\n<a target=\"_blank\" href=\"https://events2-us-east-1.ipredictive.com/d/track/click?zid=prebid_1_0_1&sid=1d160339-71a4-4aa3-ab4d-84597cf785fb-559ae0e9e63b7089&crid=23501042&adid=58612&oid=2152925&cid=424808&spid=851&pubid=464&site_id=3760177370&auid=6040313&algid=1&algrev=1&offpc=0.7&maxbid=0.76&optpc=1.074270486831665&cstpc=0.7&xts=1713918208&pbap=CgMweDAQBhoBZiIBMioFQXBwbGUyBmlQaG9uZToJaVBob25lIE9TQgQxNy40UgJlbloLU01BUlRfUEhPTkVgAGoGQkFOTkVSigECLTWQAQCaASBjMDUzYTc2ZjQ0ODNkYmI3ODA2NmEyYTBmYWY1ZTc0NqUBgxElQq0BWxPAwsABAMgBAdIBBlBVQkxJQ-oBI0lBQjEsSUFCOSxJQUIxNyxJQUI2LTUsSUFCNixJQUIxNC00-gEgZTFjZDkzMDlmMWZjYjE4ZWYwYjkyZjQ5NGEzZTU2M2KCAiQ1ZGNhZWE5Mi1jOGE5LTQwM2UtYWM0NC05OGQzNjkwZjhlNDKKAgdVTktOT1dOkgIMNjguOTkuMzEuMTgzmgIDRTJFoAIAsAIC8gKOAU1vemlsbGEvNS4wIChpUGhvbmU7IENQVSBpUGhvbmUgT1MgMTdfNCBsaWtlIE1hYyBPUyBYKSBBcHBsZVdlYktpdC82MDUuMS4xNSAoS0hUTUwsIGxpa2UgR2Vja28pIENyaU9TLzEyMy4wLjYzMTIuNTIgTW9iaWxlLzE1RTE0OCBTYWZhcmkvNjA0LjH6AgZTYWZhcmmCAwU2ODExNIoDBU9tYWhhkgMDNjUymgMCTkWiAwJVU6oDAjEwsQMAAAAAAAAAALoDBzUwNzQ0NzLCAwM2NTLKAxJDb3ggQ29tbXVuaWNhdGlvbnPSAwR3aWZp2gMSYmFyc3Rvb2xzcG9ydHMuY29t6gMkM2M1ZjdkNDItNmJjMy00NWNmLWJiNWYtZTk5YzNjMDRiMjAyqQQAAABglmIYP7EEAAAAQL9Xnzy5BHsUrkfhemQ_wAQZygQPNjQwLCA4MzAsIDkyMzMw4QSamZmZmZnZP-oEBDE3LjTyBBRDaHJvbWUgTW9iaWxlIG9uIGlPU_oEAk5FggUEMS0tLcoFATHSBSlwcmViaWQtdy04OTkxMjJhMTU2NGM1NTcxNWViMTIwZGE5NzcyNzFjOfoFJTI6d2ViLDIwNTpVUy9ORS9PbWFoYSwyMDA5Oi00NTUsMzE0OjGABgGiBgw2OC45OS4zMS4xODPQBgDiBi8KB1VOS05PV04SJDVkY2FlYTkyLWM4YTktNDAzZS1hYzQ0LTk4ZDM2OTBmOGU0Mg&ez_p=&rd=http%3A%2F%2Fdhhs.ne.gov%2FPages%2FNebraska-Family-Helpline.aspx%3Futm_source%3Dviant%26utm_medium%3Ddisplay%26utm_campaign%3DOmaha%26utm_content%3DDisplay-Ad2-Refresh-03.2024\">\n\n<img src=\"https://media-cdn.ipredictive.com/image/58612/18e6739a30f_24_10344_NFH_2024_Q1_Digital_Ad2_300x250_v4_LI_030824.gif\" width=\"300\" height=\"250\">\n</a>\n\n<img id=\"cs_imp\" src=\"https://events2-us-east-1.ipredictive.com/d/csimp/pixel?zid=prebid_1_0_1&sid=1d160339-71a4-4aa3-ab4d-84597cf785fb-559ae0e9e63b7089&crid=23501042&adid=58612&oid=2152925&cid=424808&spid=851&pubid=464&site_id=3760177370&auid=6040313&algid=1&algrev=1&offpc=0.7&maxbid=0.76&optpc=1.074270486831665&cstpc=0.7&xts=1713918208&pbap=CgMweDAQBhoBZiIBMioFQXBwbGUyBmlQaG9uZToJaVBob25lIE9TQgQxNy40UgJlbloLU01BUlRfUEhPTkVgAGoGQkFOTkVSigECLTWQAQCaASBjMDUzYTc2ZjQ0ODNkYmI3ODA2NmEyYTBmYWY1ZTc0NqUBgxElQq0BWxPAwsABAMgBAdIBBlBVQkxJQ-oBI0lBQjEsSUFCOSxJQUIxNyxJQUI2LTUsSUFCNixJQUIxNC00-gEgZTFjZDkzMDlmMWZjYjE4ZWYwYjkyZjQ5NGEzZTU2M2KCAiQ1ZGNhZWE5Mi1jOGE5LTQwM2UtYWM0NC05OGQzNjkwZjhlNDKKAgdVTktOT1dOkgIMNjguOTkuMzEuMTgzmgIDRTJFoAIAsAIC8gKOAU1vemlsbGEvNS4wIChpUGhvbmU7IENQVSBpUGhvbmUgT1MgMTdfNCBsaWtlIE1hYyBPUyBYKSBBcHBsZVdlYktpdC82MDUuMS4xNSAoS0hUTUwsIGxpa2UgR2Vja28pIENyaU9TLzEyMy4wLjYzMTIuNTIgTW9iaWxlLzE1RTE0OCBTYWZhcmkvNjA0LjH6AgZTYWZhcmmCAwU2ODExNIoDBU9tYWhhkgMDNjUymgMCTkWiAwJVU6oDAjEwsQMAAAAAAAAAALoDBzUwNzQ0NzLCAwM2NTLKAxJDb3ggQ29tbXVuaWNhdGlvbnPSAwR3aWZp2gMSYmFyc3Rvb2xzcG9ydHMuY29t6gMkM2M1ZjdkNDItNmJjMy00NWNmLWJiNWYtZTk5YzNjMDRiMjAyqQQAAABglmIYP7EEAAAAQL9Xnzy5BHsUrkfhemQ_wAQZygQPNjQwLCA4MzAsIDkyMzMw4QSamZmZmZnZP-oEBDE3LjTyBBRDaHJvbWUgTW9iaWxlIG9uIGlPU_oEAk5FggUEMS0tLcoFATHSBSlwcmViaWQtdy04OTkxMjJhMTU2NGM1NTcxNWViMTIwZGE5NzcyNzFjOfoFJTI6d2ViLDIwNTpVUy9ORS9PbWFoYSwyMDA5Oi00NTUsMzE0OjGABgGiBgw2OC45OS4zMS4xODPQBgDiBi8KB1VOS05PV04SJDVkY2FlYTkyLWM4YTktNDAzZS1hYzQ0LTk4ZDM2OTBmOGU0Mg&au_pc=${AUCTION_PRICE}&uid=tQ5drn1HXb5xiYJxIlRctvCVVyGkxr8KdoxTjIk1X7Je2%2BEm7ljiv4OSAIgMci31&uidt=UNKNOWN&rr=1713831808093\" style=\"display:none\" height=\"1\" width=\"1\">\n\n\n\n\n\n</div>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
          "adomain": [
            "boystown.org"
          ],
          "iurl": "https://media-cdn.ipredictive.com/image/58612/18e6739a30f_24_10344_NFH_2024_Q1_Digital_Ad2_300x250_v4_LI_030824.gif",
          "crid": "23501042",
          "cat": [
            "IAB5-2"
          ],
          "w": 300,
          "h": 250
        }
      ],
      "seat": "2182"
    }
  ],
  "bidid": "1d160339-71a4-4aa3-ab4d-84597cf785fb-559ae0e9e63b7089",
  "cur": "USD"
}`

Tracking event URL

`https://events2-us-east-1.ipredictive.com/d/rtb/v25/prebid/won?zid=prebid_1_0_1&sid=d160c39d-94cd-491e-9a11-0d09d93b2b2e-2043a3a69336f433&crid=23344304&adid=87829&oid=2334233&cid=465149&spid=851&pubid=464&site_id=3760177370&auid=6144152&algid=1&algrev=1&offpc=0.639&maxbid=1.3&optpc=1.072655439376831&cstpc=0.639&xts=1713922006&pbap=CgMweDAQBRoBbSIBMioFQXBwbGUyBmlQaG9uZToJaVBob25lIE9TQgYxNy40LjFSAmVuWgtTTUFSVF9QSE9ORWAAagZCQU5ORVKKAQItNJABAJoBIGJhYmYwZTdmYWRlYjY3YWM4MDcyMjU5Yzk1OWE4Yzk1pQFECyxCrQEJ6o7CwAEAyAEB0gEGUFVCTElD6gEjSUFCMSxJQUI5LElBQjE3LElBQjYtNSxJQUI2LElBQjE0LTT6ASBlMWNkOTMwOWYxZmNiMThlZjBiOTJmNDk0YTNlNTYzYoICJDhmYjRjYTNlLWIxZGEtNDhjNi04NGUzLTZhODVhODYwODBjNYoCB1VOS05PV06SAg03Mi43MS4xOTguMjQxmgICWFKgAgCwAgLyAosBTW96aWxsYS81LjAgKGlQaG9uZTsgQ1BVIGlQaG9uZSBPUyAxN180XzEgbGlrZSBNYWMgT1MgWCkgQXBwbGVXZWJLaXQvNjA1LjEuMTUgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzE3LjQuMSBNb2JpbGUvMTVFMTQ4IFNhZmFyaS82MDQuMfoCBlNhZmFyaYIDBTAzMTA0igMKTWFuY2hlc3RlcpIDAzUwNpoDAk5IogMCVVOqAwIxMLEDAAAAAAAAAAC6Awc1MDg5MTc4wgMDNTA2ygMbQ29uc29saWRhdGVkIENvbW11bmljYXRpb25z0gMEd2lmadoDEmJhcnN0b29sc3BvcnRzLmNvbeoDJDQ1YTNiMDNhLTRkMWItNGNmNy05MzJjLThiOWNiMjAxZjFkYbkEYTJVMCqpQz_ABAXKBA82NDAsIDgzMCwgOTIzMzDhBOSDns2qz9k_6gQEMTcuNPIEDU1vYmlsZSBTYWZhcmn6BAJOSIIFBDEtLS3KBQEx0gUpcHJlYmlkLXctODk5MTIyYTE1NjRjNTU3MTVlYjEyMGRhOTc3MjcxYzn6BR8yMDU6VVMsMjAwOTotMTAzODk4LDUyOToxMDU2NTk2gAYBmQbgehSuR-HaP6IGDTcyLjcxLjE5OC4yNDHQBgDiBi8KB1VOS05PV04SJDhmYjRjYTNlLWIxZGEtNDhjNi04NGUzLTZhODVhODYwODBjNQ&au_pc=$%7BAUCTION_PRICE%7D&rand=1713835606897`

Please let us know on how we can resolve this issue. Thanks.

**Comment by dgirardi** [comment]
Need more details - example response from what? can you provide steps to reproduce?

**Comment by skapoorViant** [comment]
Here's the test page showing the issue:
https://qa.vianttech.com/2114_pixie_test_page/hello_world_viant.html
