### ISSUE TITLE
Multiple redundant adunit resize calls

### ISSUE THREAD

**Issue by polapi** [prebid/Prebid.js#1138]
## Type of issue
Issue or maybe a question?

## Description
I noticed few times that when opening page in new background chrome tab, prebid.js might have chosen bad adunits sizes. I tried to reproduce an issue (without success :/) and I noticed that my prebid debug logs are full of multiplicated statements like:

> AdUnit : adunit1 resized based on device width to : 728,90,468,60

It seems to me this resizing happens for each bid (or bidder) which seems to me quite unnecessery and ineffective. Is there a reason for that?

**Comment by mkendall07** [comment]
@polapi 
Yes this is expected, as it's how the code was written because the `sizeMapping` is scoped to the adUnit level. In the future, we may move this sizeMapping to a global level to avoid.
