### ISSUE TITLE
URL Render Data and size data replacement with calling deprecatedReplaceInURN

### ISSUE THREAD

**Issue by aleskanderl** [prebid/Prebid.js#11392]
## Type of issue
Feature request - PA support with url replacement

## Description
Replacement macros for renderUrl link for specific parameters without usage of "deprecatedReplaceInURN" is currently impossible with google PA feature.
I working on prebid adapter and in prebid we will have firstly the contextual auction in which i will provide to the generateBid auctionConfig in which i will populate few relevant parameters such as Width,Height,Placement name/any other related data of the original contextual auction on which it was activated.

My renderUrl link is build with this structure: (example) "https://domain.com/id=12354667?width=%%AD_WIDTH%%&height=%%AD_HEIGHT%%&renderData=%%RENDER_DATA%%".
In native integration i would be fetching this render url link and replace the relevant params with usage of deprecatedReplaceInURN, however in Prebid i have a problem.

Currently prebid does not support usage of "deprecatedReplaceInURN" so i can not call render macro replacement.

## Steps to reproduce
https://domain.com/id=12354667?width=%%AD_WIDTH%%&height=%%AD_HEIGHT%%&renderData=%%RENDER_DATA%%
Replace this with any values for render data/sizes.

### Expected results
https://domain.com/id=12354667?width=320&height=320&renderData=contextualDataFromAuctionSuchAsPlacementName

### Actual results
https://domain.com/id=12354667?width=%%AD_WIDTH%%&height=%%AD_HEIGHT%%&renderData=%%RENDER_DATA%%

## Platform details
Every version of prebid,

## Other information
I've asked this question on [privacySandbox](https://github.com/privacysandbox/privacy-sandbox-dev-support/discussions/323) git with no answer on similar possibilities.

**Comment by dgirardi** [comment]
What should Prebid do? If I go from https://developer.mozilla.org/en-US/docs/Web/API/Navigator/deprecatedReplaceInURN:

> deprecatedReplaceInURN(UrnOrConfig, replacements)

to me means that it needs to be called at the time a paapi ad is rendered. Prebid does not render them (so far), it's either GAM - where I dont' think we can do anything - or the publisher - who is free to call it. 

We can take this in consideration for https://github.com/prebid/Prebid.js/pull/11379, which adds some rendering logic, but I'm otherwise not sure what the ask is.

**Comment by aleskanderl** [comment]
So basically prebid can not send any signal to GAM for render params?
So the only real option is to publisher to call the deprecateInUrn function by himself?

P.S. Its not even an "ask" its more discussion of how to do it. I m not really sure how to force GAM to have these params, its not a beacon of sort, so i m curious how to do it

**Comment by omriariav** [comment]
Adding context to @aleskanderl - replacing more render URL macros is required for rendering native ad. If GTM is the top layer seller, there should be a way in component auction that it runs to use the deprecatedReplaceInURN. I think the prebid for fledge support this.

**Comment by patmmccann** [comment]
By GTM do you mean gpt.js? 

Prebid does not currently have a component seller, but there is one committed in #11094 . Within that feature, decisionlogic.js is configurable, not provided. The decision logic there is purely exemplary, we may build a repo with more consensus logic intended to be useful in the future.

**Comment by omriariav** [comment]
@patmmccann yes, I meant gpt.js - thank you for the correction. 
Our main challenge is the ability to use the `deprecatedReplaceInURN` as we need to change the render URL to support native ads rendering.

Taboola will bid on its own IGs - and we will need to change the `renderURL` macros to change the rendering logic to support the pre-bid requirements (which is different when we run code on the page directly or when done with our RTB partners when we sell the impression) 

Can you please direct me? Your guidance is crucial in determining if this is achievable.

**Comment by patmmccann** [comment]
> we will need to change the renderURL macros to change the rendering logic to support the pre-bid requirements 

Which requirements are you referring to? Your competitors are certainly using this function and it is not part of their prebid.js code base.

**Comment by patmmccann** [comment]
I would encourage you to study https://github.com/WICG/turtledove/issues/286#issuecomment-1673911874 and beyond. It seems you should use deprecatedURLReplacements.  I would encourage to study the Index exchange or Openx methods of filling in these macros, as they seem to have solved this problem. 

cc @laurb9 @roni-gordon-ix

**Comment by rdgordon-index** [comment]
Can you share the `auctionConfig` that you're using, as well as the associated interest group configuration?

**Comment by laurb9** [comment]
`${AD_WIDTH}` and `${AD_HEIGHT}` (note the different macro style) are replaced by GAM as [documented here](https://developers.google.com/authorized-buyers/rtb/protected-audience-api#macros)

Seller custom parameters can be passed in the component auction config via the `deprecatedRenderURLReplacements` field [documented here](https://github.com/WICG/turtledove/blob/main/FLEDGE.md#21-initiating-an-on-device-auction) (it really is a regular json map of macro to replacement, despite the incorrect example there).

**Comment by omriariav** [comment]
Thanks, @laurb9 - we will test this and provide feedback by the end of this month.

**Comment by omriariav** [comment]
@laurb9 any idea if this change is arriving to Chrome Stable soon?
