### ISSUE TITLE
Update pbsBidAdapter to pass analytics tags to client-side adapters

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#11391]
## Type of issue
Enhancement

## Description
This is the Prebid.js side of https://github.com/prebid/prebid-server/issues/3615 - see that issue for a full background.

In short, we're trying to get server-side details to our client-side analytics adapter and the PBS committee has approved a generic mechanism for doing so... it will return the `ext.prebid.analytics.tags` object in the response. We would like for the pbsBidAdapter to look for this object and make it available to interested analytics adapters. 

We should emit a new event for the server side analytics object being available, and only emit the event when the library is configured by the publisher to do so (the same configuration flag would enable  ext.prebid.analytics.options.enableclientdetails: true in the pbs request) . Analytics adapters could then listen to that event.

**Comment by dgirardi** [comment]
Does it make sense to re-use the SEAT_NON_BID event for this, possibly renaming it (PBS_ANALYTICS ? ) for prebid 9?

**Comment by bretg** [comment]
Will let @robertrmartinez weigh in, but I suspect we're willing to follow Prebid's lead on the implementation.
