### ISSUE TITLE
Pubmatic adapter broken

### ISSUE THREAD

**Issue by CarsonBanov** [prebid/Prebid.js#114]
The pubmatic adapter seems to successfully load the necessary pubmatic script `//ads.pubmatic.com/AdServer/js/gshowad.js` and possibly request bids, but no bids are ever returned.  
When used with Appnexus bidder, the code still returns and sets targeting successfully, but Appnexus always is the winning bidder.  When used as the only bidder, it does not set any targeting:
`MESSAGE: CALLING BIDDER ======= pubmatic` is the only message in the console.

In my testing I am using the `publisherId` given to us by pubmatic and `adSlot` is the title (the DFP name) of the ad slot.  

Any thoughts?   @mkendall07 
Is there any example site where this adapter is implemented successfully?

**Comment by mkendall07** [comment]
Hi @CarsonBanov 

You need to contact PubMatic and have them enable header bidder for your account. This is a prerequisite for PubMatic.
