### ISSUE TITLE
AppNexus Bid Adapter : plcmt and startdelay mapping function not returning correct values

### ISSUE THREAD

**Issue by weylandjung** [prebid/Prebid.js#11400]
https://github.com/prebid/Prebid.js/blob/b557f048770d64371674f08dca21fe3cd8fcc7b3/modules/appnexusBidAdapter.js#L1015-L1036

In the `getContextFromPlcmt` function, when `plcmt` is `2` and  `getContextFromPlcmt` is `0`, it returns out, rather than returning `accompanying_content_pre_roll` as expected.

That's because `(!ortbStartDelay)` in line 1021 evaluates to true, so the function just exits.  This may need to be `(typeof ortbStartDelay !== undefined)`.

**Comment by jsnellbaker** [comment]
Thanks for reporting this; I'll take a look and put together a fix.
