### ISSUE TITLE
Ad is not being rendered on the html page.

### ISSUE THREAD

**Issue by skapoorViant** [prebid/Prebid.js#11419]
Below is the test html page URL on which I am trying display the ad using Viant bid adapter.
[https://qa.vianttech.com/2114_pixie_test_page/hello_world_viant_4.html](url)

The bid response is coming as expected and attached below:
[bidresponse.json](https://github.com/prebid/Prebid.js/files/15155406/bidresponse.json)

**Comment by patmmccann** [comment]
how is this distinct from https://github.com/prebid/Prebid.js/issues/10951?

**Comment by skapoorViant** [comment]
Hello @patmmccann , it's not different at all from the previous issue, all my setup is similar, no change in it, but still it is not showing the creative on html page. I do not see any issues at least from set up perspective from our side, that's why reached out to Prebid team if they can help identify the issue. Thanks.

**Comment by dgirardi** [comment]
https://qa.vianttech.com/2114_pixie_test_page/hello_world_viant_4.html seems to work now. Is it still an issue @skapoorViant? (if the page was using a new GAM creative / line item, it can sometimes take hours to start working properly).

**Comment by skapoorViant** [comment]
@dgirardi I happen to find an alternate way to make it work from prebid documentation, but with my old setup it did not work. If you compare these two test pages, the one with `_old` is similar to my last implementation, just changed the creative size in it, and it did not work. Here are the links below:
[https://qa.vianttech.com/2114_pixie_test_page/hello_world_viant_12_old.html]
[`https://qa.vianttech.com/2114_pixie_test_page/hello_world_viant_12.html`]

**Comment by dgirardi** [comment]
From here it looks like an issue in GAM setup - it's serving an empty creative:

![image](https://github.com/prebid/Prebid.js/assets/10151381/22dc8886-cddc-4170-9c34-f964be905df3)

I think this means that none of the line items / creatives for the slot match the targeting.

**Comment by skapoorViant** [comment]
@dgirardi Not able to understand what does GAM has to do with all this? We are technically using Prebid as SSP and based on the implementation it should be able to render ad with any creative size. And in that test page I am only using one bidder so it should technically always win the bid and render the creative.

**Comment by patmmccann** [comment]
Mystery solved, thanks @dgirardi
