### ISSUE TITLE
Load Prebid Library Inline

### ISSUE THREAD

**Issue by tedrand** [prebid/Prebid.js#1145]
## Type of issue

Question

## Description

Is it possible to load the Prebid library inline as opposed to from an external file? I am having issues with it.

**Comment by andyblackwell** [comment]
It's possible, yes. But you'll need to alter adapters that use any `<script>` tags in their creatives.

so if they have something like:
```
let creative = `<html><head><script>inDapIF=true;</script></head><body></body></html>`;
```
you could convert it to:
```
const _script_ = 'script';
let creative = `<html><head><${_script_}>inDapIF=true;</${_script_}></head><body></body></html>`;
```
which will compile to this and can be loaded inline:
```
var _script_ = 'script';
var creative = '<html><head><' + _script_ + '>inDapIF=true;</' + _script_ + '></head><body></body></html>';
```

**Comment by tedrand** [comment]
Thanks, man, that's really interesting. I wonder why the opening script tag causes those issues.
