### ISSUE TITLE
ORTB Converter: Bidder specific SCHAIN copied to source object

### ISSUE THREAD

**Issue by robertrmartinez** [prebid/Prebid.js#11462]
## Type of issue
Possible bug?

## Description

When the following schain config is set, the intention is it is only sent to that bidder:

This is probably specific for Prebid Server integrations with prebid.js since it has multiple bidders in the call, so the ORTB Converter does not have the logic needed to filter out this schain from the top level since it is just checking if the bidder is in the call?

```
pbjs.setBidderConfig(
  {
    bidders: ['myBidder'],
    config: {
      schain: {
        validation: 'relaxed',
        config: {
          ver: '1.0',
          complete: 1,
          nodes: [
            {
              asi: 'prebid.com',
              sid: 1234567,
              hp: 1
            }
          ]
        }
      }
    }
  }
);
```

When the ORTB Converter does its logic to generate the Prebid Server request, it correctly seems to set this here:

ext.prebid.schains = 
```
[
    {
        "bidders": [
            "myBidder"
        ],
        "schain": {
            "ver": "1.0",
            "complete": 1,
            "nodes": [
                {
                    "asi": "prebid.com",
                    "sid": 12345678,
                    "hp": 1
                }
            ]
        }
    }
]
```

But, it is also copied over to the `request.source.ext.schain` object like so:

```
        "schain": {
            "ver": "1.0",
            "complete": 1,
            "nodes": [
                {
                    "asi": "prebid.com",
                    "sid": 12345678,
                    "hp": 1
                }
            ]
        }
```

I am wondering if this is expected behavior, should the ORTB converter not set this here and just leave the bidder level one shown before?

## Test page
https://jsfiddle.net/1zpfas58/1/

Call to PBS Screenshots:

ext.prebid.schains:
<img width="1114" alt="image" src="https://github.com/prebid/Prebid.js/assets/13972794/1283a0be-7479-4102-841c-85ecee2619d3">

source.ext.schain:
<img width="827" alt="image" src="https://github.com/prebid/Prebid.js/assets/13972794/2736c28c-c28e-456e-9d7b-0ea51886154c">

### Expected results
I am not too sure (I am not too keen on how schains should work!)

But I _believe_ the top level source.ext.schain should NOT be there?

### Actual results
Top level schain is sent

**Comment by dgirardi** [comment]
I am not sure. The current logic is

https://github.com/prebid/Prebid.js/blob/5438945e9d8de671a2b15db2f5fee1b9aa5b885d/modules/prebidServerBidAdapter/ortbConverter.js#L200

This replaced the previous logic that instead of the most commonly used just picked a random one:

https://github.com/prebid/Prebid.js/blob/0c69238d05017b372e4d527d02ad71bbeb0aca71/modules/prebidServerBidAdapter/index.js#L858-L859

I don't remember if at the time I thought that made sense (now I don't think it does) or if there was any discussion.

Should we just remove it?

**Comment by lcorrigall** [comment]
Discussed in PMC: should not set bidder specific schains to the global schain
