### ISSUE TITLE
Namespace for pbjs

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#115]
Hi,

Is there any plan to eventually namespace this project? While it will not be an issue for publishers, it could impact networks trying to use it and distribute it as it might conflict with some publisher's sites.

It would be nice to specify a top-level namespace other than pbjs pre-build.

Thanks,

Chris

**Comment by mkendall07** [comment]
Hi @cwbeck,

Do you mean another alias that is longer? `pbjs` is the global namespace as of now.

**Comment by cwbeck** [comment]
Hi @mkendall07 

Correct, `pbjs` is the global namespace, but would it be possible to set this as a variable in the build so we could for example have `abcd` instead? This would prevent any conflicts whereby pbjs was already in use by someone else.

**Comment by ojotoxy** [comment]
I agree, this would be very helpful!

**Comment by ojotoxy** [comment]
Maybe it would be helpful if prebid.js could be require'd like a library from other code, and that when used this way, the global variable would have a randomized name to prevent conflicts from other usages?

**Comment by Heray** [comment]
Assigning back to @protonate - as soon as the commit was closed.

**Comment by mkendall07** [comment]
merged
