### ISSUE TITLE
Yahoo Adapter reading video.placement and not video.plcmt (Prebid 9)

### ISSUE THREAD

**Issue by DeepthiNeeladri** [prebid/Prebid.js#11533]
**Type of issue**
Question

**Description**
Hi,

I have a question regarding reading video.placement and not video.plcmt. our adserver does not yet support video.plcmt yet, so we will still need to make sure we can read video.placement or do a mapping if the former is sent. Will this will have any problem once user updates to Prebid 9.
https://github.com/prebid/Prebid.js/issues/10452
https://github.com/prebid/Prebid.js/blob/master/modules/yahoosspBidAdapter.js#L373
uses `placement` and no `plcmt`
https://github.com/prebid/Prebid.js/blob/master/modules/yahoosspBidAdapter.md 
docs have `placement`. Could use an update

Thanks,
Deepthi

**Comment by patmmccann** [comment]
Why not have your js adapter pass it up and ignore it server side until you've completed the work to transition?
