### ISSUE TITLE
Feature request: simple way to flush the bid cache

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/Prebid.js#11560]
## Type of issue
Question

## Description
We use Prebid in a SPA setting, and have bid caching enabled.
The docs ( https://docs.prebid.org/dev-docs/faq.html#does-prebidjs-cache-bids ) state the following:

> for the same AdUnit,
on the same page view,
for the same user, and
up to a certain Time-to-Live (TTL) or until the bid wins and is displayed.

Looking at the code we find the following:

```
export let filters = {
  isActualBid(bid) {
    return bid.getStatusCode() === CONSTANTS.STATUS.GOOD
  },
  isBidNotExpired,
  isUnusedBid
};

export function isBidUsable(bid) {
  return !Object.values(filters).some((predicate) => !predicate(bid));
}
```
Which filter out bids based on TTL.

What we do not find is the logic where bids are removed when a page change happens.

So two questions:

* Does bid caching work correctly in a SPA context when a page change happens ( and if so, just for my curiousity, how ? )
* If not, how can we clear bids from Prebid when a page change occurs ?

**Comment by dgirardi** [comment]
There is no logic to flush the cache - AFAIK a single page app is a single "page view". The terminology we use may be confusing or outdated, the idea is the cache is cleared (together with everything else) when a new page is loaded.

There's also no straightforward way to flush the cache  - yet, I'll use this issue as a feature request. For the time being you can simulate it with [`bidCacheFilterFunction`](https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html#setConfig-Use-Bid-Cache), for example:

```javascript
const flushBidCache = (() => {
    let lastFlush;
    pbjs.setConfig({
        bidCacheFilterFunction(bid) {
            return !lastFlush || bid.requestTimestamp >= lastFlush;
        }
    })
    return () => {
        lastRefresh = new Date().getTime();
    }
})();
```

**Comment by yashraj02** [comment]
1. Maybe we can detect/check whether the url of the page is the same or it has changed.
2. If url is same -> do nothing
3. If url has changed -> delete cached bids [But in this scenario do we need to also consider re-auction? Because the user has lost cached bids & there's no bids in place]

**Comment by patmmccann** [comment]
@yashraj02 you should be able to add an event listener for any event you want, including a url change, and clear cache with the function in #11912
