### ISSUE TITLE
variable margins on body tag of first iframe

### ISSUE THREAD

**Issue by HendrikPetertje** [prebid/Prebid.js#1157]
## Type of issue
"Bug"

## Description
When an ad-placement is rendered on the page the first body tag sometimes has a margin set to 0 and sometimes not defined causing the iframe body to fall back on its default browser-provided body margin. This behaviour is causing scrollbars or overlapping adverts on our sites as the new width and height caused by this margin suddenly exceed the provided limit.

## Steps to reproduce
run header-bidding against for example "wideorbit" or "rubicon" and render the adverts with `pbjs.renderAd()`

### Expected results
either one of the below:
-A consistent margin from all advert providers in all their ads.
- prebid.js inserting the "marin: 0" within the `renderAd()` scope.
- The ability to do a callback when pbjs.renderAd() has resolved into a rendered ad, allowing the developer to manually override or insert margin on the first body tag.

### Actual results
- inconsistent margins on the first body tag, no callbacks or emitted events when prebid.js resolves causing making a solution to be very hacky.

## Platform details
prebid.js: 478b384 (several commits after 0.21.0)

## Other information
Advert example:
![screen shot 2017-04-26 at 10 34 49](https://cloud.githubusercontent.com/assets/3583395/25425651/de122a4c-2a6c-11e7-8e42-39780cf67ab2.png)

Random occurrence of ad having a margin:
![screen shot 2017-04-26 at 10 36 21](https://cloud.githubusercontent.com/assets/3583395/25425683/f797131a-2a6c-11e7-9684-dc57f82f1e23.png)

Random occurrence of ad not having a margin:
![screen shot 2017-04-26 at 10 42 31](https://cloud.githubusercontent.com/assets/3583395/25425720/1c96eadc-2a6d-11e7-977b-b87dddae6ab9.png)

**Comment by mkendall07** [comment]
Assume this was related to the creative served?

**Comment by fernandolobao** [comment]
Did someone find a fix for this? I'm implementing the 1.31 version of prebid and this is happenning with 90% of ads.

**Comment by jsnellbaker** [comment]
@fernandolobao I don't believe there were any changes made for this issue.  If you are still seeing a problem, can you provide a test page that demonstrates the issue so we could review?

**Comment by HendrikPetertje** [comment]
We eventually went the hacky way with this. Google DFP would return an iframe object to us that has margin and padding set to 0, so this is happening purely when rendering prebid.js ads without google dfp. we are actually dealing with some very "high-end" advertisers nowadays that attempt to make scrollable ads, our hacky code also deals with that.

So right now we have this:

```
function createAdFrame() {
  const iframe = document.createElement('iframe');
  iframe.setAttribute('scrolling', 'no');
  iframe.setAttribute('marginheight', '0');
  iframe.setAttribute('marginwidth', '0');
  iframe.setAttribute('frameborder', '0');
  iframe.style.cssText = 'border: 0; padding: 0; margin: 0';
  return iframe;
}

function renderAdNow(ad) {
  const iframe = createAdFrame(); // Here we create an iframe-object that has margin set to 0
  ad.placementDiv.appendChild(iframe); // here we insert the iframe into the HTML dom
  const doc = iframe.contentDocument; 
  pbjs.renderAd(doc, pbjs.getHighestCpmBids(ad.adName)[0].adId); // And here we render the ad
}
```

Not a beauty-contest winner, but it gets the job done.
