### ISSUE TITLE
fledgeForGPT module may assume Prebid adunit.code matches GPT slot

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#11584]
## Type of issue
Potential bug

## Description

In today's Tools meeting, @florianerl reported a potential issue with the fledgeForGPT module - that it's not working when the Prebid Adunit.code doesn't match a GPT slot. It's valid for Prebid adunit.codes to be divId other even a [customSlotMatching](http://docs.prebid.org/dev-docs/publisher-api-reference/setTargetingForGPTAsync.html) function value.

Perhaps this line of code is near the source of the potential issue -- could this be generalized to first check if adunit.code is a GPT slot, and if not, check for div or customSlotMatching?

https://github.com/prebid/Prebid.js/blob/f6040c445428071cf4547b5663fd2d2e86bc74c6/modules/fledgeForGpt.js#L37

Unfortunately I don't have first hand data or a test page, but we've had issues before along these lines, so it seems plausible. So the first step would be to see if we have test cases that cover the divid and customSlotMatching scenarios.

**Comment by dgirardi** [comment]
the current logic expects the ad unit code to be either a GAM ad unit path or the div ID:

https://github.com/prebid/Prebid.js/blob/78f93cd29ee0955c6ddf2cf20f5251ac8e8c66e1/src/utils.js#L798

`customSlotMatching` is a parameter to `setTargetingForGptAsync`. We can replicate it for `setPAAPIConfigForGPT` - or we could extract it into a configuration parameter.

**Comment by ptomasroos** [comment]
Just bumped into this when I was about to enable fledge on my ad slots which purely uses customSlotMatching

**Comment by adtechnology** [comment]
When will this be fixed?

**Comment by patmmccann** [comment]
fixed in #11714
