### ISSUE TITLE
How to install prebid and build 5.20.4

### ISSUE THREAD

**Issue by marcosviniciusdesouza650** [prebid/Prebid.js#11596]
## Type of issue

HELLO, I need help building my Prebid.js 5.20.4, I know it is obsolete, but I need to change the version I currently have, so I need to build a new one. I downloaded the file from here: [5.20.4](https://github.com/prebid/Prebid.js/releases/tag/5.20.4), but I need to know which node.js  version to use. Today I'm using v18.17.0. 

I follow the steps for installation, but I get an error when I use `npm ci` or `npm install`. I open the Windows terminal, as administrator, in C:\Windows\System32> use `npm install -g gulp`.
```
I receive the message:
changed 141 packages in 6s

14 packages are looking for funding
  run `npm fund` for details.
```

now in C:\Users\Marcos Vinicius\Desktop\Prebid.js
, I use `npm ci`, erro:

```
> npm ERR! code 1
> npm ERR! path C:\Users\Marcos Vinicius\Desktop\Prebid.js\node_modules\fibers
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node build.js || nodejs build.js
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@10.1.0
> npm ERR! gyp info using node@18.17.0 | win32 | x64
> npm ERR! gyp info find Python using Python version 3.8.0 found at "C:\Users\Marcos Vinicius\AppData\Local\Programs\Python\Python38-32\python.exe"
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
> npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
> npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS Failure details: undefined
> npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS Failure details: undefined
> npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS Failure details: undefined
> npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS Failure details: undefined
> npm ERR! gyp ERR! find VS looking for Visual Studio 2015
> npm ERR! gyp ERR! find VS - not found
> npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
> npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
> npm ERR! gyp ERR! find VS For more information consult the documentation at:
> npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
> npm ERR! gyp ERR! stack at VisualStudioFinder.fail (C:\Users\Marcos Vinicius\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:116:11)
> npm ERR! gyp ERR! stack at VisualStudioFinder.findVisualStudio (C:\Users\Marcos Vinicius\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:72:17)
> npm ERR! gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> npm ERR! gyp ERR! stack at async createBuildDir (C:\Users\Marcos Vinicius\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:95:26)
> npm ERR! gyp ERR! stack at async run (C:\Users\Marcos Vinicius\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js:81:18)
> npm ERR! gyp ERR! System Windows_NT 10.0.22631
> npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Marcos Vinicius\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
> npm ERR! gyp ERR! cwd C:\Users\Marcos Vinicius\Desktop\Prebid.js\node_modules\fibers
> npm ERR! gyp ERR! node -v v18.17.0
> npm ERR! gyp ERR! node-gyp -v v10.1.0
> npm ERR! gyp ERR! not ok
> npm ERR! node-gyp exited with code: 1
> npm ERR! Please make sure you are using a supported platform and node version. If you
> npm ERR! would like to compile fibers on this machine please make sure you have setup your
> npm ERR! build environment--
> npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
> npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
> npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
> npm ERR! Alpine users please run: `sudo apk add python make g++`
> npm ERR! 'nodejs' n�o � reconhecido como um comando interno
> npm ERR! ou externo, um programa oper�vel ou um arquivo em lotes.
```

The package.json for this version looks like this:
`>{
>   "name": "prebid.js",
>   "version": "5.20.4",
>   "description": "Header Bidding Management Library",
>   "main": "src/prebid.js",
>   "scripts": {
>     "test": "gulp test",
>     "lint": "gulp lint"
>   },
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/prebid/Prebid.js.git"
>   },
>   "keywords": [
>     "advertising",
>     "auction",
>     "header bidding",
>     "prebid"
>   ],
>   "globalVarName": "pbjs",
>   "author": "the prebid.js contributors",
>   "license": "Apache-2.0",
>   "engines": {
>     "node": ">=8.9.0"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.8.4",
>     "@babel/preset-env": "^7.8.4",
>     "@jsdevtools/coverage-istanbul-loader": "^3.0.3",
>     "@wdio/browserstack-service": "^6.1.4",
>     "@wdio/cli": "^7.5.2",
>     "@wdio/concise-reporter": "^7.5.2",
>     "@wdio/local-runner": "^7.5.2",
>     "@wdio/mocha-framework": "^7.5.2",
>     "@wdio/spec-reporter": "^7.5.2",
>     "@wdio/sync": "^7.5.2",
>     "ajv": "5.5.2",
>     "babel-loader": "^8.0.5",
>     "body-parser": "^1.19.0",
>     "chai": "^4.2.0",
>     "coveralls": "^3.1.0",
>     "deep-equal": "^2.0.3",
>     "documentation": "^13.2.5",
>     "es5-shim": "^4.5.14",
>     "eslint": "^7.27.0",
>     "eslint-config-standard": "^10.2.1",
>     "eslint-plugin-import": "^2.20.2",
>     "eslint-plugin-node": "^11.1.0",
>     "eslint-plugin-prebid": "file:./plugins/eslint",
>     "eslint-plugin-promise": "^5.1.0",
>     "eslint-plugin-standard": "^3.0.1",
>     "execa": "^1.0.0",
>     "faker": "^5.5.3",
>     "fs.extra": "^1.3.2",
>     "gulp": "^4.0.0",
>     "gulp-clean": "^0.3.2",
>     "gulp-concat": "^2.6.0",
>     "gulp-connect": "^5.7.0",
>     "gulp-eslint": "^4.0.0",
>     "gulp-footer": "^2.0.2",
>     "gulp-header": "^2.0.9",
>     "gulp-if": "^3.0.0",
>     "gulp-js-escape": "^1.0.1",
>     "gulp-replace": "^1.0.0",
>     "gulp-shell": "^0.8.0",
>     "gulp-sourcemaps": "^3.0.0",
>     "gulp-terser": "^2.0.1",
>     "gulp-util": "^3.0.0",
>     "is-docker": "^2.2.1",
>     "istanbul": "^0.4.5",
>     "karma": "^6.3.2",
>     "karma-babel-preprocessor": "^8.0.1",
>     "karma-browserstack-launcher": "1.4.0",
>     "karma-chai": "^0.1.0",
>     "karma-chrome-launcher": "^3.1.0",
>     "karma-coverage": "^2.0.1",
>     "karma-coverage-istanbul-reporter": "^3.0.3",
>     "karma-es5-shim": "^0.0.4",
>     "karma-firefox-launcher": "^2.1.0",
>     "karma-ie-launcher": "^1.0.0",
>     "karma-mocha": "^2.0.1",
>     "karma-mocha-reporter": "^2.2.5",
>     "karma-opera-launcher": "^1.0.0",
>     "karma-safari-launcher": "^1.0.0",
>     "karma-script-launcher": "^1.0.0",
>     "karma-sinon": "^1.0.5",
>     "karma-sourcemap-loader": "^0.3.7",
>     "karma-spec-reporter": "^0.0.32",
>     "karma-webpack": "^3.0.5",
>     "lodash": "^4.17.21",
>     "mocha": "^5.0.0",
>     "morgan": "^1.10.0",
>     "opn": "^5.4.0",
>     "resolve-from": "^5.0.0",
>     "sinon": "^4.1.3",
>     "through2": "^4.0.2",
>     "url-parse": "^1.0.5",
>     "webdriverio": "^7.6.1",
>     "webpack": "^3.0.0",
>     "webpack-bundle-analyzer": "^3.8.0",
>     "webpack-stream": "^3.2.0",
>     "yargs": "^1.3.1"
>   },
>   "dependencies": {
>     "babel-plugin-transform-object-assign": "^6.22.0",
>     "core-js": "^3.13.0",
>     "core-js-pure": "^3.13.0",
>     "criteo-direct-rsa-validate": "^1.1.0",
>     "crypto-js": "^3.3.0",
>     "dlv": "1.1.3",
>     "dset": "2.0.1",
>     "express": "^4.15.4",
>     "fun-hooks": "^0.9.9",
>     "just-clone": "^1.0.2",
>     "live-connect-js": "2.0.0"
>   }
> }`

**Comment by patmmccann** [comment]
We can only suggest trial and error, we only support recent releases
