### ISSUE TITLE
How to extract device openRTB object from in prebidJs adapter from prebid request

### ISSUE THREAD

**Issue by skapoorViant** [prebid/Prebid.js#11597]
## Description
I am trying to extract device ip and demographics info from html request which is passed to the adapter. So far I am only getting user-agent and language but nothing else. Is there a way I can get rest of the information from it?

**Comment by dgirardi** [comment]
I'm not sure I understand the question - everything that is available to bid adapters is under `bidderRequest.ortb2`. `device.ip` is usually not set as it's typically available server side. User data is present only if the publisher sets it up directly or through other modules.

**Comment by skapoorViant** [comment]
@dgirardi but is there a way to get lat long values from the request?

**Comment by dgirardi** [comment]
there's `user.geo` and `device.geo`, as per ORTB, but they're only filled in if the publisher decides to fill them in, either directly or by including an RTD module.
