### ISSUE TITLE
ortbConverter library should support GVL for aliases

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#11628]
## Type of issue
enhancement

## Description

There are two ways to define GVL IDs for aliases:

1. with aliasBidder

```
pbjs.aliasBidder('rubicon', 'rubiconalias', {gvlid: 52});
```

2. with gvlMapping

```
pbjs.setConfig({
    gvlMapping: {
        rubiconalias: 52
    }
});
```

The desire is that the output of the `ortbConverter` library include

```
"ext": {
  "prebid": {
    "aliasgvlids": {
      "rubiconalias": 52
    }
  }
}
```

Will provide a test page offline.

**Comment by patmmccann** [comment]
Looks ready Bret, is your team contributing?

**Comment by bretg** [comment]
I've opened an internal ticket, but no committed timeline

**Comment by robertrmartinez** [comment]
PR ready for feedback: https://github.com/prebid/Prebid.js/pull/11699
