### ISSUE TITLE
Create a bidderSettings object or setPriceGranularity() method for Video 

### ISSUE THREAD

**Issue by AntoineJac** [prebid/Prebid.js#1164]
## Description
Create a bidderSettings object or a setPriceGranularity method for video different from the one from display. 

### Expected results
Right now the bidderSettings object or setPriceGranularity() will be the same for video and display , however the publisher are most of the time a granularity different between this 2 channels. It would be great to have also a bidderVideoSettings object and setPriceGranularityVideo() to be able to differentiate these 2 channels.

Thanks,

Antoine Jacquemin

**Comment by mkendall07** [comment]
@AntoineJac 
Custom price buckets and granularity is an option for now. What is the proposal for vide bucket granularity?

**Comment by AntoineJac** [comment]
@mkendall07, thanks for the response. I am working on a prebid integration with a customer using Prebid video and display. But most of the time publisher would like a different granularity between display and video ads. It would be great to have a specific method for video, for instance:
pbjs.setPriceGranularityVideo("low");
pbjs.setPriceGranularity("low");

OR

pbjs.bidderVideoSettings = {
    standard: {
         [...]
    },
    appnexus: {
         [...]
    },
    rubicon: {
         [...]
    },
}
pbjs.bidderSettings = {
    standard: {
         [...]
    },
    appnexus: {
         [...]
    },
    rubicon: {
         [...]
    },
}

Best,

Antoine
