### ISSUE TITLE
Prebid Timeout Changed

### ISSUE THREAD

**Issue by arupdebnath31** [prebid/Prebid.js#11651]
## Type of issue
It is a Bug related to the prebid timeout.

## Description

We are noticing that the prebid timeout value is changed on a refresh call and setting the value rather than the expected value. The timeout value is found as expected on the first call but the value is changed on a refresh call. 

## Steps to reproduce

We have created a test page (provided in the next section), you have to see the console for PrebidTimeout1 & PrebidTimeout2. You will see the prebid timeout changes. You have to stay on the browser console. 

## Test page

https://www-q.motorsport.com/test/adgrid/

User: m0t007
Pass: m0t007

FYI, This is a Basic Prebid page, we just replaced the adUnit code with our own. 

### Expected results
We need the PrebidTimeout value to stay constant at 1800 (for this test page)

### Actual results

We found the values of PrebidTimeout1/PrebidTimeout2 changing from 1800
![image_2024_06_03T07_04_19_822Z](https://github.com/prebid/Prebid.js/assets/36239709/433539a9-be82-4bb7-80db-6630b7e48b31)
![image_2024_06_03T07_07_46_598Z](https://github.com/prebid/Prebid.js/assets/36239709/323c9b13-d117-489c-839d-38d5bcbd138f)

## Platform details

We have used your latest Prebid js file which you provided on the Basic test page. 

## Other information

You can reach out to gao.gram@gmail.com and arupdebn@gmail.com if you need any further assistance or updates.

**Comment by dgirardi** [comment]
`pubads_imp.js` is setting the timeout to 1. I do not know why.

![image](https://github.com/prebid/Prebid.js/assets/10151381/ceed17a9-64d0-4391-aac0-d7ae799298f9)

**Comment by patmmccann** [comment]
This appears to be related to https://github.com/codywilson1/prebid.github.io/blob/4927581ba8bcd998d4823cb1f99d5243ae109988/adops/gam-hbt-step-by-step.md?plain=1#L10

Have you enabled it?

**Comment by arupdebnath31** [comment]
No, We didn't enable it. 


![Image](https://github.com/prebid/Prebid.js/assets/36239709/d8902e6f-e4f6-4fa0-892d-4e7c968d6a0d)

**Comment by soman** [comment]
@patmmccann Let us know if anything is needed from us.

**Comment by arupdebnath31** [comment]
Guys, its seems like its not prebid related issue. Thanks for looking into it. @patmmccann

**Comment by codywilson1** [comment]
Hi, I'm an engineer on Google Ad Manager. We dug into this and it seems that we mistakenly enabled some closed beta functionality on a portion of traffic to this site. We have a fix in progress, but in the meantime the feature that caused this has been disabled. Please reach out to your Ad Manager account manager if you have further questions.

**Comment by Slind14** [comment]
> Hi, I'm an engineer on Google Ad Manager. We dug into this and it seems that we mistakenly enabled some closed beta functionality on a portion of traffic to this site. We have a fix in progress, but in the meantime the feature that caused this has been disabled. Please reach out to your Ad Manager account manager if you have further questions.

Was this disabled everywhere? We have a lot of different sites (with different GAMs) that are or were affected.

**Comment by audren49** [comment]
Hi, I work at motorsport.com 
I can confirm the fix from @codywilson1 seems to be working. 
Please give details as to when it was applied? Could you also please make sure that this close beta functionality is being turned off everywhere? Or in particular on those domains: autosport.com , motorsport.com , motor1.com , insideevs.* , rideapart.com .
We saw an impact on our revenue.
