### ISSUE TITLE
Filter or go over bid responses before choosing winning bid

### ISSUE THREAD

**Issue by Shaishiff** [prebid/Prebid.js#1166]
## Type of issue
Question/Feature

## Description
Is it already possible, or if you can somebody please explain (in general) how to implement a feature like that ?

### Expected results
General idea is to have a callback fired when bids are back before just before choosing the winning bid for each ad unit, giving the publisher an additional option to add logic for choosing the winning bid.
Examples: 
- Block all ads from a specific advertiser according to "ad" code returned in bid response.
- Have a complex logic of floor prices depending on all bid responses.

**Comment by mkendall07** [comment]
@Shaishiff 
In the requestBids callback you may invoke additional APIs and use the callback function return object map to inspect bids. For example:

```
pbjs.requestBids({
	bidsBackHandler: function(bidObjMap) {
        var bidObj = bidObjMap["adUnitCode"];
        bidObj.bids.forEach(function(bid){
           //do something with `bid`
        });
	}
  });
```
