### ISSUE TITLE
Rubicon in PostBid is failing due to split error

### ISSUE THREAD

**Issue by Jrex90** [prebid/Prebid.js#1167]
## Type of issue
I am not quite sure wether this is a bug or not, but in the bidder params the Rubicon site is supposed to be an array, although the Postbid script is asking for a string to use .split on (rp_zonesize)

here is what I have used:   

var adUnitSizes = [[160,600]];

    // Add your post-bid tag IDs here:
    var adUnitBids = [
        {
            bidder: 'adform',
            params: {
               mid: '392833'
            }
        },
        {
            bidder: 'rubicon',
            params: {
                accountId: '13906',
                siteId: '110334',
                zoneId: '643312',
                rp_zonesize: "9"
            }
        }
    ]
  
but I get an "Uncaught TypeError: Cannot read property 'split' of undefined". If I change the sizes to rp_zonesite, which I can see is called in the script, and make the size into a string, like so:

rp_zonesize: "9" 

it seems to be working correctly. 

(I am using the newest version of the Postbid 2.1.1)

Perhaps I am missing something here?

**Comment by surensilva** [comment]
Hi @Jrex90,

If you want control of the sizes at the bidder level for Rubicon, then you should specify the sizes in the following way:
```
var adUnitBids = [
    {
        bidder: 'adform',
        params: {
           mid: '392833'
        }
    },
    {
        bidder: 'rubicon',
        params: {
            accountId: '13906',
            siteId: '110334',
            zoneId: '643312',
            sizes: [9]
        }
    }
]
```

`rp_zonesize` is a part of our SmartTag method of integration and is not used at all in our adapter. If you have any further issues, please do let me know.

**Comment by Jrex90** [comment]
Thanks @surensilva 

Although I did try your method, but all I got was the following error "Uncaught TypeError: Cannot read property 'split' of undefined"

**Comment by surensilva** [comment]
Hi @Jrex90,

Is there a test page you could share with me?. Im unable to reproduce the issue you are having.

Kind Regards,

Suren

**Comment by bretg** [comment]
@Jrex90 - is this still a problem for you? If so, please post a minimal test page.

**Comment by Jrex90** [comment]
Hi @bretg 

Thanks for writing. I managed to fix the problem, no need to investigate any further, thanks

**Comment by bretg** [comment]
Cool - glad it's resolved.
