### ISSUE TITLE
Alias bidders

### ISSUE THREAD

**Issue by ehoch** [prebid/Prebid.js#117]
So we have multiple bidders built on top of "appnexus" that are telling us to use the AppNexus adapter. Is there a way to alias the appnexus bidder so it can report the bidder type to DFP as the different partners?

**Comment by ialex** [comment]
I haven't implemented appnexus but one of our bidders asked us to us the same adapter and the targeting was set properly to the bidder name in this case brealtime, is there a chance that it will be the same for other bidders?

**Comment by ehoch** [comment]
@ialex This is actually for brealtime. Would you mind sharing the config you used that you were able to choose "brealtime" as the bidder but use the AppNexus adapter?

**Comment by ialex** [comment]
Somehow it appears on DFP as brealtime on the targeting reports
{
          "bidder": "appnexus",
          "params": {
            "placementId": 56095465
          }
        }

**Comment by ehoch** [comment]
Thank you. While we're hijacking this thread, how did you handle adjustment for their rev share with gross vs net?

**Comment by ialex** [comment]
we haven't done that it's going to be a discrepancy between DFP and Brealtime i suppose if you figure it out mail me at alejandro at monetizemore.com

**Comment by mkendall07** [comment]
@ehoch & @ialex 
We are currently working to support this feature. Stay tuned.

**Comment by BartVB** [comment]
I'm running into the same problem. It seems to be pretty hard to get into contact with AppNexus, currently only able to use Prebidding through two other networks.

Was planning on fixing this myself but I guess I'll wait :) My plan was to make it possible to access the data in 'adUnits' in the bidResponse object. But great news, @mkendall07 !

As a side note; it would be fantastic if the bids could be pooled per adapter. Currently some pages need 8 requests to Appnexus/jpt while that could be one request. Same with AppNexus/imptr.

**Comment by Heray** [comment]
@BartVB combining the ad calls/imp trackers are also in the work. Since it's more bidder specific we don't keep track of the work here. But we expect it to come out some time in Q1 2016.

**Comment by BartVB** [comment]
@Heray Great news, thanks!

**Comment by BartVB** [comment]
I switched to the new pbjs.aliasBidder() functionality. In my limited testing this seems to work great, thanks!

**Comment by mkendall07** [comment]
This is released in 0.5.0 so closing
