### ISSUE TITLE
idImportLibrary.js should be controlled by Activity Controls 

### ISSUE THREAD

**Issue by AramZS** [prebid/Prebid.js#11705]
## Type of issue

Bug

## Description

Activity Controls do not turn off the idImportLibrary.js module. Since that module is explicitly collecting personal data it should be subject to all the concerns of GPP, USPAPI and TCF. If it isn't reading out and considering those systems, than publishers should be able to deactivate it on their own systems through Activity Controls.

**Comment by patmmccann** [comment]
lets treat in tcf similar to #11536

**Comment by patmmccann** [comment]
@aramzs we don't really have a ready made activity here, propose tying to enricheids?

**Comment by patmmccann** [comment]
Enrisheids, while it does not exactly cover this activity; this activity has no value if enricheids is false, so the tying is convenient. We can document on the module that this particular activity will disable it.
