### ISSUE TITLE
GDPR issues

### ISSUE THREAD

**Issue by simplo** [prebid/Prebid.js#11759]
## Type of issue
Get a Warning using Iubenda GDPR

## Description
I got this errors:
27005 ms: consentManagement.gpp config not defined, exiting consent manager module.
27006 ms: consentManagement.usp config not defined, using defaults.
27008 ms: USP CMP not found. Resuming auction without consent data as per consentManagement config.
I'm using Iubenda and the __tcfapi is present and working

### Expected results
GDPR recognized and profiled bidding allowed if consent

### Actual results
Warning says the CMP is not found and the gdpr config is not setted, even if I have this:
pbjs.que.push(function() 
			{
				pbjs.setConfig({
				   consentManagement: {
					 gdpr: {
					   cmpApi: 'iab',   // activates the enforcement module
					   defaultGdprScope: true,
					   rules: [{        // these are the default values
						 purpose: "storage",
						 enforcePurpose: true,
						 enforceVendor: true
					   },{
						 purpose: "basicAds",
						 enforcePurpose: true,
						 enforceVendor: true
					   },{
						 purpose: "measurement",
						 enforcePurpose: true,
						 enforceVendor: true
					   }]
					 }
				   }
				 });
                pbjs.addAdUnits(adUnits);
                pbjs.requestBids
				({
                    bidsBackHandler: initAdserver,
                    timeout: PREBID_TIMEOUT
                });
				
            });

## Platform details

Every broswer
We are using prebid 8.51.0

**Comment by dgirardi** [comment]
The warning is about GPP and USP, not GPDR. They would  happen when the `consentManagementGpp` / `consentManagementUsp` modules are included but cannot find their matching CMP.

If you are not interested in GPP/USP I recommend not including those modules. None of the logs you posted are relevant to GDPR, so it's not clear if that's working as intended.

**Comment by simplo** [comment]
Hi Demetrio, thank you for your reply.
Ok, mu fault! I thought GPP and GDPR where in the same module.
Now I disabled GPP and all is fine.
Thank you!
