### ISSUE TITLE
AppNexus S2S prebidServer adapter issues.

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#1176]
Hi,

I appreciate we are an early adopter here, but experiencing some issues in initial testing: -

```
pbjs.setS2SConfig({
    accountId : 'd296f9ad-b275-4771-9d42-de70f6e70504',
    enabled : true,
    bidders : ['appnexusAst'],
    timeout : 1000,
    adapter : 'prebidServer',
    endpoint : 'http://prebid.adnxs.com'
});
```

We are getting the following error: -

![screen shot 2017-05-04 at 12 19 36](https://cloud.githubusercontent.com/assets/425262/25701466/6ff0c466-30c4-11e7-8b08-4a5e4e2ffe40.png)

Everything seems to be correctly setup: -

![screen shot 2017-05-04 at 12 19 19](https://cloud.githubusercontent.com/assets/425262/25701479/83d7bc96-30c4-11e7-921d-739a66fe5d46.png)

I have tried with rubicon and index too and received the same error.

**Comment by mercuryyy** [comment]
Only appnexus and facebook adapters are supported atm, index and pubmatic following soon.

so you need to be using the appnexus adapter and not the appnexusAst

**Comment by mkendall07** [comment]
`appnexusAst` adapter doesn't work yet.

**Comment by cwbeck** [comment]
@mercuryyy thanks for the update. I was just going off the list of adapters in prebid-server project. we'll hold fire on implementing this.

**Comment by mkendall07** [comment]
@cwbeck 
your endpoint is wrong in the config. Drop `endpoint : 'http://prebid.adnxs.com'` altogether and it will default correctly.

**Comment by cwbeck** [comment]
@mkendall07 

Good spot, I lifted that from: https://prebid.adnxs.com/documentation/

Using the default endpoint I now get (as @mercuryyy suggested, appnexusAst is not yet supported)

```
{"tid":"e58a08e9-add3-4932-9915-087e73ae9785","status":"OK","bidder_status":[{"bidder":"appnexusAst","error":"Unsupported bidder"}]}
```

**Comment by mkendall07** [comment]
Yep, that's expected at this point.
