### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by EskelCz** [prebid/Prebid.js#11777]
Question/Request

## Description
Can you please enable the "Discussions" tab for this repository?
You have it enabled for the `prebid-server` project, which I think doesn't need it as much as this one.
<img width="525" alt="image" src="https://github.com/prebid/Prebid.js/assets/1198558/6e0647ac-5811-42d2-912f-be3a73fadb6d">

I know I can ask a question here and on stackoverflow, but here it feels inappropriate/polluting and StackOverflow doesn't feel very active. Not sure how frequented it is by the development team currently. I think the Discussions here would feel more "official".

What do you think? Is there a reason for it not being enabled?
Thanks for your consideration.

**Comment by patmmccann** [comment]
We decided not to enable it a year or two ago because it is just one more place all of our volunteers would need to go check for more things to address. What's the utility? We don't use stackoverflow but we also have a slack.

**Comment by EskelCz** [comment]
I would think that the utility is obvious, it's right there in the repository, open to everyone.
I'm working professionally with prebid daily and didn't know about your Slack. Is it open for outsiders? Also it's kind of weird to join your Slack space to just ask a single question. It's a walled garden that doesn't come up in Google search for the issue and some people don't even have it.
What other places are the volunteers checking?

**Comment by EskelCz** [comment]
Also you might get new occasional volunteers, people who wouldn’t commit to going elsewhere.

**Comment by patmmccann** [comment]
We decided not to do this; you're welcome to join the prebid organization and you'll be invited to our slack. If we turned this on, it would split conversations between slack and this place and generate general overhead and confusion for participants.

**Comment by EskelCz** [comment]
@patmmccann I think you are insulating yourself from external communication. Not good for an open source project.
