### ISSUE TITLE
rubiconBidAdapter tests: please migrate `querystring` to `URLSearchParams`

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#11795]
The rubiconBidAdapter tests rely on `querystring`:

https://github.com/prebid/Prebid.js/blob/babd603318475dd6a021fd7420095197dfdd2646/test/spec/modules/rubiconBidAdapter_spec.js#L11

With 9, this had to be explicitly included as a dependency - probably because it was included indirectly through now-removed other dependencies (https://app.circleci.com/pipelines/github/prebid/Prebid.js/21362/workflows/c1660a29-4ce6-4a7b-8dca-b790cf024784/jobs/38114)

Nowadays parsing query strings can be done without relying on an external library - the tests should be updated to use [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

**Comment by dgirardi** [comment]
@harpere @robertrmartinez tagging you as I'm not sure you've acknowledged this yet

**Comment by robertrmartinez** [comment]
Acking now @dgirardi !

Will get it done.
