### ISSUE TITLE
Issue with criteo bidder

### ISSUE THREAD

**Issue by jdelhommeau** [prebid/Prebid.js#118]
Hi,

It seems that in version 0.4.1, criteo adaptor is not using the varname parameter to setup the variable, but rather name the variable "crtg_varname_[nid]" where [nid] is the "nid" parameter setup by the user.

The variable should rather be named after the varname parameter in the bidder.

Best Regards,
julien

**Comment by hjeong12** [comment]
Hi julien,
fixed #120.
Please let me know, if it's not correct. 

Thanks,
Hyejung

**Comment by jdelhommeau** [comment]
That should do the trick! :)

Thank you.
