### ISSUE TITLE
PV9.0.0 Criteo error

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#11807]
## Type of issue
400 error being thrown in PV9.0.0 for criteo,  error is not there in PV8.52.0.  I think the endpoint is not even up and running? 
## Description
get this error in V9 for criteo:

![Screenshot_15_06_2024__07_53](https://github.com/prebid/Prebid.js/assets/8503167/6001ba62-9799-4ec7-a7e4-aecbc7bbccf5)

this seems unusual to me in the call, an "empty" bidder param/ varaibale:

![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_outstreamAmazonPUC-less1_html](https://github.com/prebid/Prebid.js/assets/8503167/6536a788-a55e-4a1e-9c7d-418b7ca5e63b)

## Test page
https://cdn.adysis.com/VideoDemo/DemoSite/pages/outstreamAmazonPUC-less1.html

### Expected results

no 400 error, auction should complete 

### Actual results
400 error

## Platform details
PV9.0.0 , chrome, mac

**Comment by patmmccann** [comment]
@TheMediaGrid @FlorentDancy @leonardlabat fyi

**Comment by FlorentDancy** [comment]
Thanks for the heads up @patmmccann , I notified the team in charge of Prebid at Criteo!

**Comment by FlorentDancy** [comment]
For info, fix in progress, should be released this week

**Comment by spormeon** [comment]
@FlorentDancy Any idea what the problem is as smaato throws the same error but i not sure/ no clue if its related at moment, but your prob could give me a "start point" to look at

**Comment by FlorentDancy** [comment]
@spormeon I just know that instead of responding with a 400 we should respond with a 204, which is the fix that I mentioned above.

I don't know why this specific case would reply with a 204 though.

**Comment by dgirardi** [comment]
@FlorentDancy what's the status on this?

**Comment by FlorentDancy** [comment]
I believe this should be fixed by now, @spormeon do you confirm?

**Comment by spormeon** [comment]
not seen the 400 since, so presume its fixed.
