### ISSUE TITLE
Missing Richaudience Module in 9.0.0 release

### ISSUE THREAD

**Issue by david-societe** [prebid/Prebid.js#11800]
## Type of issue
Missing module in 9.0.0 

## Description
The richaudienceBidAdapter module is missing in source code 9.0.0.zip

This file is in the release : 
Prebid.js-9.0.0/modules/richaudienceBidAdapter.md

This file is missing : 
Prebid.js-9.0.0/modules/richaudienceBidAdapter.js

Thx

**Comment by patmmccann** [comment]
It was deleted because of #11044

**Comment by david-societe** [comment]
Thx

Le ven. 14 juin 2024 à 16:23, Patrick McCann ***@***.***> a
écrit :

**Comment by richaudience** [comment]
Hello @patmmccann & @david-societe,

We made a change to our bidding infrastructure this morning to resolve the issue mentioned in the ticket: #11044 


Thank you.
