### ISSUE TITLE
Unruly invalid SSL cert for domain in adapter

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#11806]
I keep getting a error for unruly, seems to be an outdated SSL cert on this domain, its included in the adapter etc: 
 
targeting.unrulymedia.com/unruly_prebid

![Certificate_Viewer____targeting_unrulymedia_com_and_Privacy_error](https://github.com/prebid/Prebid.js/assets/8503167/955ba5c1-73c6-4673-92ab-17f40d856e6a)

anyone here from unruly to sort it out or can someone "tag" them to get it sorted out?

**Comment by patmmccann** [comment]
@bhainesnexxen did the last commit

https://github.com/prebid/Prebid.js/commit/1488d8c10c7f56081a8cad3abc8475f7f7543739

His email is linked from there

**Comment by bhainesnexxen** [comment]
Thanks for letting us know. We had a server in a cluster of load balancers in the EU that failed to restart correctly.

**Comment by spormeon** [comment]
@bhainesnexxen ok thanks, seems to be fixed now, will close out
