### ISSUE TITLE
Prebid v9.0.0 error during build and download

### ISSUE THREAD

**Issue by KhaiHJN** [prebid/Prebid.js#11810]
## Type of issue
bug

## Description
Im getting this error in my prebid.js file when downloading the file from the webpage `{"error":"Prebid file not built properly","requestId":"d38ba04a-6132-4233-9553-3a85e5c226b1"}`. Its happening because of First Party Data Enrichment has been chosen (also default checkmark on)

## Steps to reproduce
Press download Prebid.js on https://docs.prebid.org/download.html 

### Expected results
The whole prebid script.

### Actual results
`{"error":"Prebid file not built properly","requestId":"d38ba04a-6132-4233-9553-3a85e5c226b1"}`

## Platform details
Macos Google Chrome Version 125.0.6422.142 (Official Build) (arm64)

## Other information
Maybe this is also related https://github.com/prebid/Prebid.js/issues/11805

**Comment by patmmccann** [comment]
Are you saying you can solve just by unchecking that box?

**Comment by patmmccann** [comment]
Appears so, that module no longer exists

**Comment by patmmccann** [comment]
https://github.com/prebid/prebid.github.io/pull/5429 should fix
