### ISSUE TITLE
Error in prebid.js v8.35 download

### ISSUE THREAD

**Issue by JoelHutchinson** [prebid/Prebid.js#11811]
## Type of issue
bug

## Description
When I try to download a prebid.js file from https://docs.prebid.org/download.html, with any of the following modules:
- [Consent Management - TCF](https://docs.prebid.org/dev-docs/modules/consentManagementTcf.html)
- [TCF Control](https://docs.prebid.org/dev-docs/modules/tcfControl.html)
- [First Party Data Enrichment](https://docs.prebid.org/dev-docs/modules/enrichmentFpdModule.html)
 
I get an error in the prebid.js file {"error":"Prebid file not built properly","requestId":"85f1b883-aa0a-4e34-87bf-428d0643d714"}

## Steps to reproduce
Download a prebid.js file from https://docs.prebid.org/download.html for version 8.35, with any of the following modules:
- [Consent Management - TCF](https://docs.prebid.org/dev-docs/modules/consentManagementTcf.html)
- [TCF Control](https://docs.prebid.org/dev-docs/modules/tcfControl.html)
- [First Party Data Enrichment](https://docs.prebid.org/dev-docs/modules/enrichmentFpdModule.html)

## Test page
[](https://docs.prebid.org/download.html?modules=consentManagementGpp%2CconsentManagementTcf%2CconsentManagementUsp%2CenrichmentFpdModule%2CgppControl_usnat%2CgppControl_usstates%2CgptPreAuction%2CtcfControl%2C33acrossBidAdapter)

### Expected results
Downloads whole prebid.js without error

### Actual results
Downloads empty prebid.js file with error

## Platform details

Any prebid.js version
Google Chrome: Version 125.0.6422.141 (Official Build) (64-bit)
Ubuntu 22.04.4 LTS

## Other information
https://github.com/prebid/Prebid.js/issues/11805
https://github.com/prebid/Prebid.js/issues/11810

**Comment by modessef1** [comment]
I have exactly the same problem for 8.52.0 version

**Comment by patmmccann** [comment]
If you uncheck first party enrichment you should have no problem with 9, it no longer exists

**Comment by modessef1** [comment]
So how can I download version 8.X now since there is a common downloader for 9.X and 8.X, and the names are already renamed for 9?

**Comment by patmmccann** [comment]
> So how can I download version 8.X now since there is a common downloader for 9.X and 8.X, and the names are already renamed for 9?

This is currently not possible for users wanting the 8.x gdpr modules; we're working on a fix for later today.
