### ISSUE TITLE
Fixed: Richaudience Bid Adapter: invalid responses on no bid

### ISSUE THREAD

**Issue by richaudience** [prebid/Prebid.js#11823]
Hello,

We made a change to our bidding infrastructure this morning to resolve the issue mentioned in this ticket. Apologies for the delay.

@patmmccann, please let us know if any further changes are needed from our side.

In this demo you can see that it is working correctly: https://jsfiddle.net/60nw7gbs/1/

Thank you.

_Originally posted by @richaudience in https://github.com/prebid/Prebid.js/issues/11044#issuecomment-2176432436_

**Comment by patmmccann** [comment]
Ok, please PR master branch to add your adapter
