### ISSUE TITLE
navigator.userAgentData.getHighEntropyValues is not working on Chrome on iPhone

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#11835]
## Type of issue
NOT A PREBID BUG/ISSUE

## Description
Here is demo page provided by Chrome Team, https://user-agent-client-hints.glitch.me/ on the page https://developer.chrome.com/docs/privacy-security/user-agent-client-hints

On Desktop, you can see `navigator.userAgentData.getHighEntropyValues` returns the data but it does not return any data on Chrom eon iPhone. 

Prebid relies on this API to populate device details
https://github.com/search?q=repo%3Aprebid%2FPrebid.js%20getHighEntropyValues&type=code

Am I missing something?

## Steps to reproduce
Visit https://user-agent-client-hints.glitch.me/ on Dsktop and mobile devices.

## Test page
https://user-agent-client-hints.glitch.me/

### Expected results
The API should return data on both Desktop and mobile devices. 

## Platform details
Tested on iPhone 14, Chrome 126

**Comment by patmmccann** [comment]
Maybe post at https://github.com/WICG/ua-client-hints/issues

**Comment by patmmccann** [comment]
Also I bet our friends at 51 degrees may have information cc @jwrosewell

**Comment by pm-harshad-mane** [comment]
Thanks @patmmccann , opened https://github.com/WICG/ua-client-hints/issues/367

**Comment by pm-harshad-mane** [comment]
Got below Feedback on https://github.com/WICG/ua-client-hints/issues/367

```
As Chrome for iOS uses WebView, I don't believe it supports any JavaScript APIs not part of Safari on iOS: 

https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/getHighEntropyValues
```

**Comment by pm-harshad-mane** [comment]
Closing as it is as per design .

**Comment by pm-harshad-mane** [comment]
Closing as it is as per design.
