### ISSUE TITLE
Various modules: not using our communication methods 

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#11838]
## Type of issue

Bug

## Description

The last three here
https://github.com/search?q=repo%3Aprebid%2FPrebid.js++sendbeacon+path%3A%2F%5Emodules%5C%2F%2F&type=code

cwire, 33across, sirdata should all import sendbeacon

**Comment by patmmccann** [comment]
Article espousing benefits of keepalive https://www.stefanjudis.com/today-i-learned/fetch-supports-a-keepalive-option-to-make-it-outlive-page-navigations/

**Comment by patmmccann** [comment]
Plan: somehow hide use of sendbeacon in the existing pattern and migrate the three adapter using it on their behalf.

**Comment by dgirardi** [comment]
Why is this blocked @patmmccann ?
