### ISSUE TITLE
Various adapters: use vidazoo utils

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#11865]
Twist, shine, tagoras, and kueez should all make use of vidazoo utilities for improved code maintainability 

Cc @uditalias

  Whoa there, partner! 🌵🤠 We wrangled some duplicated code in your PR:

- [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L49-L65) has 18 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L220-L236)
- [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L70-L98) has 30 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L242-L270)
- [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L99-L116) has 19 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L271-L287)
- [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L117-L160) has 45 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L290-L333)
- [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L168-L179) has 13 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L420-L430)
- [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L223-L252) has 31 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L452-L480)
- [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L258-L329) has 73 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L340-L410)
- [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L331-L343) has 14 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L170-L182)
- [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L362-L385) has 25 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L131-L163)
- [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L384-L397) has 15 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L117-L130)
- [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L423-L431) has 10 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L56-L64)
- [`modules/tagorasBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/tagorasBidAdapter.js#L12-L24) has 14 duplicated lines with [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L28-L40)
- [`modules/tagorasBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/tagorasBidAdapter.js#L26-L39) has 15 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L29-L42)
- [`modules/tagorasBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/tagorasBidAdapter.js#L66-L95) has 31 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L246-L103)
- [`modules/tagorasBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/tagorasBidAdapter.js#L103-L132) has 31 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L290-L319)
- [`modules/tagorasBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/tagorasBidAdapter.js#L143-L172) has 31 duplicated lines with [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L193-L222)
- [`modules/tagorasBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/tagorasBidAdapter.js#L220-L258) has 40 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L381-L175)
- [`modules/tagorasBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/tagorasBidAdapter.js#L259-L266) has 9 duplicated lines with [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L339-L346)
- [`modules/tagorasBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/tagorasBidAdapter.js#L275-L334) has 61 duplicated lines with [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L383-L442)
- [`modules/shinezRtbBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/shinezRtbBidAdapter.js#L146-L163) has 19 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L199-L215)
- [`modules/shinezRtbBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/shinezRtbBidAdapter.js#L153-L243) has 92 duplicated lines with [`modules/twistDigitalBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/twistDigitalBidAdapter.js#L208-L329)
- [`modules/kueezRtbBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/modules/kueezRtbBidAdapter.js#L68-L98) has 32 duplicated lines with [`libraries/vidazooUtils/bidderUtils.js`](https://github.com/prebid/Prebid.js/blob/1d205d0e086d68a90131880f4c2f8f1a982f0aae/libraries/vidazooUtils/bidderUtils.js#L246-L96)

Reducing code duplication by importing common functions from a library not only makes our code cleaner but also easier to maintain. Please move the common code from both files into a library and import it in each. Keep up the great work! 🚀

_Originally posted by @github-actions[bot] in https://github.com/prebid/Prebid.js/issues/11821#issuecomment-2186493770_

**Comment by uditalias** [comment]
@patmmccann On it.
