### ISSUE TITLE
Visx: Duplication check results

### ISSUE THREAD

**Issue by Goncakkd** [prebid/Prebid.js#11875]
> Whoa there, partner! 🌵🤠 We wrangled some duplicated code in your PR:
> 
> * [`modules/luponmediaBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1bf5cb47749bf421300ded951801d132dc952f3e/modules/luponmediaBidAdapter.js#L277-L283) has 8 duplicated lines with [`modules/visxBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1bf5cb47749bf421300ded951801d132dc952f3e/modules/visxBidAdapter.js#L277-L283)
> * [`modules/gridBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1bf5cb47749bf421300ded951801d132dc952f3e/modules/gridBidAdapter.js#L513-L525) has 14 duplicated lines with [`modules/visxBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1bf5cb47749bf421300ded951801d132dc952f3e/modules/visxBidAdapter.js#L321-L333)
> * [`modules/carodaBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1bf5cb47749bf421300ded951801d132dc952f3e/modules/carodaBidAdapter.js#L199-L204) has 7 duplicated lines with [`modules/visxBidAdapter.js`](https://github.com/prebid/Prebid.js/blob/1bf5cb47749bf421300ded951801d132dc952f3e/modules/visxBidAdapter.js#L277-L283)
> 
> Reducing code duplication by importing common functions from a library not only makes our code cleaner but also easier to maintain. Please move the common code from both files into a library and import it in each. Keep up the great work! 🚀

Hello, check for duplicated code prevents us to merge it. Touching the code of the other bid adapters doesnot make sense. Can you please help us?

_Originally posted by @Goncakkd in https://github.com/prebid/Prebid.js/issues/11860#issuecomment-2191101496_

**Comment by patmmccann** [comment]
In the case of caroda, you both do the exact same transformation of the results of parseSizesInput from utils. Why not add that transformation utility to utils and modify both adapters to import and use it? 

I'm the case of grid you both define the exact same function, just add a library file for it an import it in both places

**Comment by dgirardi** [comment]
The utility already exists - this:

```
      const sizes = parseSizesInput(bannerParams.sizes);
      const format = sizes.map(size => {
        const [width, height] = size.split('x');
        const w = parseInt(width, 10);
        const h = parseInt(height, 10);
        return { w, h };
      });
```

is equivalent to:

```
const format = sizesToSizeTuples(bannerParams.sizes).map(sizeTupleToRtbSize)
```

with both [`sizesToSizeTuples`](https://github.com/prebid/Prebid.js/blob/f6e1008ad9216c86801d706ca875f13e3976bbf4/src/utils.js#L135-L150) and [`sizeTupleToRtbSize`](https://github.com/prebid/Prebid.js/blob/f6e1008ad9216c86801d706ca875f13e3976bbf4/src/utils.js#L173-L175) from utils

**Comment by Goncakkd** [comment]
> In the case of caroda and lupin, you all do the exact same transformation of the results of parseSizesInput from utils. Why not add that transformation utility to utils and modify all three adapters to import and use it?
> 
> In the case of grid you both define the exact same function, just add a library file for it and import it in both places
> 
> This is a community run project and you're a valuable part of it! You're welcome to improve code quality in any adapter.

You are right for improving code quality but when i changed something their code,  i am alike the owner of their code. I mean i am getting more and more issues for their code. I fixed duplication issue for my code but i have more because of the other ones. You can see on this comment-> https://github.com/prebid/Prebid.js/pull/11860#issuecomment-2194970762

**Comment by patmmccann** [comment]
Great job! You can ignore the new ones, they are not on visx.
