### ISSUE TITLE
Pubmatic bid adapter: support ortb2Imp deals

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#11880]
Adding some detail here, a publisher should be able to define a pmp like this https://docs.prebid.org/dev-docs/adunit-reference.html#first-party-data ; not just via your adapter parameters. It is a requirement you support the standard openrtb way of forming a bid request when you provide a parameter. The most frequent publisher complaint about prebid is bidder parameters having redundant implementations of the same information

> 
> ```
>    code: "test-div",
>    mediaTypes: {
>        banner: {
>            sizes: [[300,250]]
>        }
>    },
>    ortb2Imp: {
>             "pmp": {
>                "private_auction": 0,
>                "deals": [
>                    {
>                        "id": "5678",
>                        "bidfloor": 1.75,
>                        "bidfloorcur": "USD",
>                        "wseat": [
>                            "16"
>                        ],
>                        "at": 3
>                    },
>                    {
>                        "id": "1234",
>                        "bidfloor": 2,
>                        "bidfloorcur": "USD",
>                        "wseat": [
>                            "3539"
>                        ],
>                        "at": 1
>                    },
>                .....
>    // ...
> });`````
> ```

@patmmccann I am doing the changes based on your comment, but I do see the same json which I used is also being used by pubmatic adapter. Please check the link: [pubmatic](https://github.com/prebid/Prebid.js/blob/ad2af8f06a144efc483300fb4a2b2e448357c586/modules/pubmaticBidAdapter.js#L598)
Is prebid enforcing this change for all the adapters to standardize the adUnits?

_Originally posted by @skapoorViant in https://github.com/prebid/Prebid.js/issues/11864#issuecomment-2192759370_

All adapters must support standard locations in addition to their parameters

**Comment by pm-harshad-mane** [comment]
@patmmccann we agree that All adapters must support standard locations in addition to their parameters. 
@kapil-tuptewar is looking into it, will respond soon.

**Comment by pm-harshad-mane** [comment]
@kapil-tuptewar can you please share update?

**Comment by kapil-tuptewar** [comment]
@pm-harshad-mane adapter specific changes are done. We are discussing this with server side team, once we get clarity I will raise a PR.
