### ISSUE TITLE
server-side adapter(s2s) to receive the ae:1 paapi flag

### ISSUE THREAD

**Issue by warrrrren** [prebid/Prebid.js#11894]
## Type of issue
Question

## Description
How do you configure a server-side adapter(s2s) to receive the ae:1 paapi flag?

## Steps to reproduce
NA

## Test page
NA -Question

### Expected results
Specified bidders on the prebid server should receive the ae:1 flag in their bid-requests.

### Actual results
Despite enabling and configuring the paapi and fledgeForGpt modules, the ae flag is not included in the s2s bid requests.

## Platform details
pbjs v8.38

**Comment by dgirardi** [comment]
You didn't specify how you are configuring, but I think there's a bug where `defaultForSlots: 1` is not picked up by the PBS adapter. Setting `ortb2Imp: {ext: {ae: 1}}` on each ad unit should work around it. Could you confirm that's what you are seeing, or if not, could you please provide more info?

**Comment by warrrrren** [comment]
Hi @dgirardi yes, I was trying to use `defaultForSlots: 1 `. If I set `ae:1` at an ad unit level will the bidder filter under the `paapi` config still apply?

**Comment by dgirardi** [comment]
@warrrrren no. I'll have a fix shortly that will enforce them on the response side (discarding PAAPI from bidders that are not enabled). `ae: 1` may still need to be set globally - bidder level  requires https://github.com/prebid/prebid-server/issues/2335 which is still open.

**Comment by patmmccann** [comment]
PBS 2335 is underway :)
