### ISSUE TITLE
labelAll ignores value

### ISSUE THREAD

**Issue by hmodes-qm** [prebid/Prebid.js#11911]
## Type of issue

potential bug

## Description
We're setting a label to include/exclude bidders from certain page types. The label is 'sod_true' or 'sod_false'. Bidders (i.e. seedtag) should only be called if the label's value is set to 'sod_true'. Here's the bidder config:

```
    		bidder: 'seedtag',
                labelAll: ['sod_true'],
    		params: {
          		publisherId: 'xxx',
          		adUnitId: 'yyy',
          		placement: 'inScreen',   
                },
```
I can see in Prebid's debugging mode that the label is set to 'sod_false'
![image (3)](https://github.com/prebid/Prebid.js/assets/67893326/9969184a-268c-458d-812d-8a2ab5be85e5)
However I can also see that seedtag is beeing called despite labelAll

![seedtag_label](https://github.com/prebid/Prebid.js/assets/67893326/4839decc-dc63-40bf-bee4-bf3d2f33520b)

## Steps to reproduce

Visit https://www.fupa.net/league/bundesliga on a mobile device. The label is logged as:

`        const labels = getCustomLabels();
	        console.log('Labels:', labels);`

### Expected results
seedtag not beeing called when the label is not 'sod_true'
### Actual results
seedtag beeing called although labelAll doesn't match the actual provided label
## Platform details
Prebid  v8.39.0

Chrome

Mobile device (simulated iPhone)

**Comment by dgirardi** [comment]
Since version 8, labels require the `sizeMapping` module. It looks like we fail to mention it in our docs.
