### ISSUE TITLE
districtmDMX adapter: result bid missing bidId from _bidsRequested

### ISSUE THREAD

**Issue by PsychodelEKS** [prebid/Prebid.js#1191]
## Type of issue
bug

## Description
districtmDMX adapter served bids (passed to bidsBackHandler) do not have any attribute to match them with bids from _bidsRequested.

## Steps to reproduce
1. Configure districtmDMX adapter to bid any placement
2. register any function as a bidsBackHandler to observe passed results
3. get bid from districtmDMX 

### Expected results
districtmDMX bid contains adId which matches bidId from corresponding requsted bid (_bidsRequested)

### Actual results
there is adId, but it does not match _bidsRequested[*].bidId

## Platform details
independant

## Other information
Made a hack myself, though there may be better solution (I used additional attribute requestBidId not to interfere with anything):
```
--- src/adapters/districtmDMX.js	(revision 1f910686a4adff1223941ca89a98a1b349cfbfcf)
+++ src/adapters/districtmDMX.js	(revision )
@@ -32,6 +32,8 @@
       bidmanager.addBidResponse(bidObject.placementCode, bid);
     }
 
+    bid.requestBidId = bidObject.bidId;
+
     return bid;
   };
 
```

**Comment by mkendall07** [comment]
@stevealliance can you fix?

**Comment by stevealliance** [comment]
Just got your message, working on it

**Comment by stevealliance** [comment]
@PsychodelEKS  I check other object and no one return the bidId ... correct me if I'm wrong.
Example of Appnexus  obj return in the callback

adId:"717335e1501291"
adUnitCode:"div-gpt-ad-12345678-2"
adUrl:"http://nym1-ib.adnxs.com/ab?e="
adserverTargeting:Object
alwaysUseBid:true
bidder:"appnexus"
bidderCode:"appnexus"
cpm:0.02709
creative_id:65361706
dealId:undefined
getSize:function ()
getStatusCode:function ()
height:250
pbAg:"0.00"
pbDg:"0.02"
pbHg:"0.02"
pbLg:"0.00"
pbMg:"0.00"
requestId:"d5792e87-3d68-43f9-a7ec-c4965fc5f7c7"
requestTimestamp:1494621098493
responseTimestamp:1494621098699
size:"300x250"
statusMessage:"Bid available"
timeToRespond:206
width:300

**Comment by PsychodelEKS** [comment]
@stevealliance that's not necessary bidId, it can be anything one can use to match bid response with particular bid request from ```pbjs._bidsRequested```, the correct and straight forward solution is to set ```bid.adId``` to the ```bidRequest.adId```. Please refer to https://github.com/prebid/Prebid.js/issues/943 as an example.

**Comment by PsychodelEKS** [comment]
@stevealliance actually bid factory supports bidRequest as a second parameter (first one is bid status), and if it is provided, ```bid.adId``` is set to ```bidRequest.bidId``` automatically. [Code](https://github.com/prebid/Prebid.js/blob/master/src/bidfactory.js#L18,L25).
