### ISSUE TITLE
How does consentManagement work in prebid 9.x.x?

### ISSUE THREAD

**Issue by oskarcokl** [prebid/Prebid.js#11921]
## Type of issue
Question

## Description
I'm trying to upgrade our prebid to version 9.4.0 but am unsure on how the consentManagement works now. I see that the module doesnt exist anymore and that it was replaced by consentManagementTcf. But when I build with that package it doesnt seem to do anything. I cant find it in the `installedModules` property on the prebid object and adapters also dont seem to be getting any sort of gdpr information when I look in the network tab. 
When building I see that consentManagementTcf is added and I can also find the file in `build/dist`.
Am I missing something? Do I need to ad any other modules to make it work. 
Our current working version is 8.20.0

### Expected results
Sending gdpr information to adapters

### Actual results
No information is being sent to adapters

## Platform details
prebid.js version 9.4.0

### Other information
This is our modules.json file I built the 9.4.0 version with

```json
[
  "consentManagementTcf",
  "connectadBidAdapter",
  "adfBidAdapter",
  "appnexusBidAdapter",
  "pubmaticBidAdapter",
  "criteoBidAdapter",
  "openxBidAdapter",
  "smartyadsBidAdapter",
  "admixerBidAdapter",
  "ixBidAdapter",
  "smartadserverBidAdapter",
  "sovrnBidAdapter",
  "adkernelBidAdapter",
  "ipromBidAdapter",
  "schain",
  "currency",
  "luponmediaBidAdapter",
  "adxpremiumAnalyticsAdapter",
  "rubiconBidAdapter",
  "adyoulikeBidAdapter",
  "eplanningBidAdapter",
  "rtbhouseBidAdapter",
  "criteoIdSystem",
  "amxBidAdapter",
  "userId",
  "sharedIdSystem",
  "prebidServerBidAdapter",
  "adponeBidAdapter",
  "seedtagBidAdapter",
  "nextMillenniumBidAdapter",
  "teadsBidAdapter",
  "smilewantedBidAdapter",
  "adtelligentBidAdapter",
  "adagioBidAdapter",
  "adagioAnalyticsAdapter",
  "express",
  "id5IdSystem",
  "betweenBidAdapter",
  "richaudienceBidAdapter",
  "bidscubeBidAdapter"
]
```

**Comment by spormeon** [comment]
@oskarcokl  think you need "tcfControl" as well

**Comment by oskarcokl** [comment]
Thanks @spormeon that fixed it.
