### ISSUE TITLE
Issue: Ad Calls Prevented When document.body Isn’t Ready

### ISSUE THREAD

**Issue by lksharma** [prebid/Prebid.js#11927]
**Description**
In version 9.4 and later, a change was introduced that prevents ad calls from being made if `document.body` isn’t ready. This issue is linked to the changes made in [this commit](https://github.com/prebid/Prebid.js/pull/11863/files), which added a location method for cross-frame creatives.

_Affected Version:_ 9.4+
_Introduced in:_ [PR #11863](https://github.com/prebid/Prebid.js/pull/11863/files)
_Test Page:_ https://30f9d51a.demo-ann.pages.dev/testpage

**Steps to Reproduce**

1. Visit the Test Page: Open the [test page](https://30f9d51a.demo-ann.pages.dev/testpage.html) provided.
1. Check the Console: Observe the console for errors related to appendChild caused by [adRendering.js#L258](https://github.com/prebid/Prebid.js/blob/master/src/adRendering.js#L258)
1. verify no ad calls are made for configured bidder (ex: /openrtb/pbjs)

**Expected Behavior**
Ad calls should be made regardless of whether document.body is fully loaded or not and no Uncaught error should be thrown by pbjs

**Actual Behavior**
When document.body isn’t ready, the following error is thrown, preventing ad calls from going out:

```javascript
TypeError: Cannot read properties of null (reading 'appendChild')
    at insertLocatorFrame (adRendering.js:258:19)
    at pbjsInstance.processQueue (prebid.js:979:21)
```

**Analysis**

- The error originates from the insertLocatorFrame function in [adRendering.js#L258](https://github.com/prebid/Prebid.js/blob/master/src/adRendering.js#L258).
- The issue arises when pbjs is loaded synchronously or when document.body isn’t available at the time of appendChild call.
- This problem does not occur when pbjs is loaded asynchronously because the script execution is deferred until document.body is available.

**Proposed Solution**
Ensure that document.body is ready before attempting to call appendChild. A potential solution is to check for the existence of document.body before executing insertLocatorFrame.

```javascript
export function insertLocatorFrame() {
  if (!window.frames[PB_LOCATOR]) {
    const frame = createInvisibleIframe();
    frame.name = PB_LOCATOR;
    if (document.body) {
      document.body.appendChild(frame);
    }
  }
}
```

**Comment by olafbuitelaar** [comment]
this should solve it; https://github.com/prebid/Prebid.js/pull/11926

**Comment by lksharma** [comment]
Thank you

**Comment by patmmccann** [comment]
Thank you!

**Comment by patmmccann** [comment]
Do we think this warrants a patch release to 9.4?

**Comment by lksharma** [comment]
A patch release for version 9.4 makes sense to me since it affects the ability of ad calls to go through.
