### ISSUE TITLE
timeoutBuffer config redundat?

### ISSUE THREAD

**Issue by bozghiyy** [prebid/Prebid.js#11959]
## Type of issue
Question. Might be a better one for documentation, but wanted to ask first.

## Description
I was looking through config options and seems that `timeoutBuffer` is not used in the code anymore.
I can only see it in `config.js`: [https://github.com/search?q=repo%3Aprebid%2FPrebid.js%20timeoutBuffer&type=code](https://github.com/search?q=repo%3Aprebid%2FPrebid.js%20timeoutBuffer&type=code) so this config is redundant from what I am seeing. 
I see documentation still exists: [https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html#set-timeout-buffer](https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html#set-timeout-buffer)

Is this doing anything?
If not, isn't better to remove if from `config.js` and documentation?

## Other information
I cannot find a PR when the use of `timeoutBuffer` was removed from auction.

**Comment by dgirardi** [comment]
It was referenced until https://github.com/prebid/Prebid.js/pull/10379, but as far as I can tell it already had no effect then. Going as far back as 1.0, bids were timed out [after the auction timeout](https://github.com/prebid/Prebid.js/blob/377c4c21f0e922c0549c3deaea327928bece3b12/src/auction.js#L107),  and [after the auction timeout + timeoutBuffer](https://github.com/prebid/Prebid.js/blob/377c4c21f0e922c0549c3deaea327928bece3b12/src/auction.js#L228), which is always too late if timeoutBuffer is positive.

>  If not, isn't better to remove if from config.js and documentation?

Agreed.
