### ISSUE TITLE
sharedId TCF2 accessDevice denied with P1 enabled

### ISSUE THREAD

**Issue by eldzis** [prebid/Prebid.js#11967]
## Type of issue
bug

## Description
SharedId TCF2 denies accessDevice even though purpose 1 is set to true by the CMP
![image](https://github.com/user-attachments/assets/873a7d66-569d-43a2-8c80-0bb27b4f1f25)

![image](https://github.com/user-attachments/assets/0e7ebd1a-cfea-4c86-89e5-bb6a28392453)

Works as expected in prebid v8.42.0
![image](https://github.com/user-attachments/assets/7ee920a2-21ef-4290-835a-2019a6a0e0e8)

## Steps to reproduce
Consent to a CMP and refresh the page.

## Test page
/

### Expected results
Allowed access to accessDevice for sharedID module

### Actual results
Access denied

## Platform details
Prebid 9.4.1

**Comment by patmmccann** [comment]
Sharedid relies on publisher consent, not vendor consent

**Comment by patmmccann** [comment]
See #11536
