### ISSUE TITLE
NoBid response from prebid server has no adUnitCode, addBitResponse discards it

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#1196]
## Type of issue
Bug

## Description
NoBid response from prebid server has no adUnitCode, addBitResponse discards it, auction doesn't stop until timeout

## Steps to reproduce
Initialize auction with pubmatic or rubicon working through prebidServer. Receive no-bid response

### Expected results
response has ad unit code, addBitResponse accepts it, when other bids arrive, auction is complete

### Actual results
response has not ad unit code, addBitResponse produces warning: "No adUnitCode supplied to addBidResponse, response discarded", auction doesn't end until timeout

## Platform details
0.24.0-pre
node v6.9.5
Fedora 25
Browser Chrome 58

## Other information
Prebid server response:

{
    "tid": "44b005c6-10d6-4aa5-958a-d750f7dc6762",
    "status": "OK",
    "bidder_status": [{
        "bidder": "pubmatic",
        "response_time_ms": 35,
        "no_bid": true
    }, {
        "bidder": "rubicon",
        "response_time_ms": 213,
        "num_bids": 1
    }, {
        "bidder": "indexExchange",
        "ad_unit": "ad_cs_9493688_728_90",
        "response_time_ms": 91,
        "no_bid": true
    }],
    "bids": [{
        "bid_id": "2d379517db8e53",
        "code": "ad_cs_9493688_728_90",
        "creative_id": "4320530",
        "bidder": "rubicon",
        "price": 0,
        "adm": "creative here");",
        "width": 728,
        "height": 90
    }]
}

**Comment by mkendall07** [comment]
Thanks for the report. Will address in a future release.
