### ISSUE TITLE
How top verify S2S is working/running?

### ISSUE THREAD

**Issue by pribeh** [prebid/Prebid.js#1197]
I have a support request. How can I verify that my prebid HB process is successfully being passed through prebidserver/S2S?

I believe I have its all configured right,I have an account setup with AppNexus' prebid server, I've made sure to add the adaptor for prebidserver, ads are running, but I still am at a loss as to how to verify that it's using the prebid server. If anybody would like a url let me know.

```
<script>   
   var PREBID_TIMEOUT = 750;

   var adUnits = [{
         code: '***',
         sizes: [[728, 90], [320, 50]],
         sizeMapping: [ ] ...
    }];
   
   var pbjs = pbjs || {};
   pbjs.que = pbjs.que || [];
   
   pbjs.que.push(function() {
     pbjs.setPriceGranularity("high");
   });
     
   pbjs.setS2SConfig({
     accountId : 'b***',                            //string:required: account ID obtained in step 1 
     enabled : true,                             //boolean:required: enables s2s - default false
     bidders : ['****','***','****'],   //array[string]:required: of bidder codes to enable S2S.
                                                 //Note these must have been including in the Prebid.js build from Step 2. 
     timeout : 1000,                             //number:optional timeout in ms for bidders called via the S2S endpoint.
                                                 //default value is 1000 
     adapter : 'prebidServer',                   //string:optional: Adapter code for S2S code. Defaults to 'prebidServer'
     endpoint : 'http://prebid.adnxs.com'        //string:optional: will override default endpoint for prebid server.
   });

 </script>
 <!-- Prebid Config Section END -->
 
 <!-- Prebid Boilerplate Section START. No Need to Edit. -->
 <script type="text/javascript" src="****/js/prebid.js" async></script>
 <script>
   var googletag = googletag || {};
   googletag.cmd = googletag.cmd || [];
   googletag.cmd.push(function() {
       googletag.pubads().disableInitialLoad();
   });

   pbjs.que.push(function() {
       pbjs.addAdUnits(adUnits);
       pbjs.requestBids({
           bidsBackHandler: sendAdserverRequest
       });

     pbjs.bidderSettings = {
       standard: {
           alwaysUseBid: false,
           adserverTargeting: [{
               key: "hb_bidder",
               val: function(bidResponse) {
                   return bidResponse.bidder;
               }
           }, {
               key: "hb_adid",
               val: function(bidResponse) {
                   return bidResponse.adId;
               }
           }, {
               key: "hb_pb",
               val: function(bidResponse) {
                   return ((bidResponse.pbHg) * RATE).toFixed(2);
               }
           }]
       }
   }

    });

   function sendAdserverRequest() {
       if (pbjs.adserverRequestSent) return;
       pbjs.adserverRequestSent = true;
       googletag.cmd.push(function() {
           pbjs.que.push(function() {
               pbjs.setTargetingForGPTAsync();
               googletag.pubads().refresh();
           });
       });
   }

   setTimeout(function() {
       sendAdserverRequest();
   }, PREBID_TIMEOUT);

 </script>
 <!-- Prebid Boilerplate Section END -->
```

**Comment by mkendall07** [comment]
If you look at the the network in developer console, filter for `auction` to see the response from `https://prebid.adnxs.com/pbs/v1/auction` - if you see bids - things are working.

**Comment by pribeh** [comment]
Thanks @mkendall07. That url does not appear to be showing up under network. Any debugging steps you might recommend? Here's the url to a page containing the prebid above code:

http://www.pomofo.com/article/hilarious-girl-made-powerpoint-presentation-ask-out-her-crush-too-bad-hes-dead-inside

**Comment by dmitriyshashkin** [comment]
Yeah, there is an obvious problem. There is a js error in the console: Uncaught TypeError: pbjs.setS2SConfig is not a function

This happens because pbjs object is not initialized until prebid.js script is loaded. Instead of calling setS2SConfig directly, you should wrap it into lambda function and add to pbjs.que array (just as you do with other pbjs calls). So it should look something like that:
 
`pbjs.que.push(function() {
pbjs.setS2SConfig({
     accountId : 'b***',
     enabled : true,
     bidders : ['****','***','****'],
     timeout : 1000
   });
});`

Please note that I removed "adapter : 'prebidServer', endpoint : 'http://prebid.adnxs.com'". First of all you can omit those, because there are default values available. Secondly endpoint : 'http://prebid.adnxs.com' is not a correct value of endpoint even though it is listed in documentation. So just omit those two values.

**Comment by dmitriyshashkin** [comment]
Added a ticket to address the wrong endpoint value in documentation https://github.com/prebid/prebid.github.io/issues/248

**Comment by pribeh** [comment]
@dmitriyshashkin Thanks! That seemed to do the trick. I was wondering that myself and tried it before the documentation pointed me in the other direction. It should be updated in the docs for sure.

**Comment by mkendall07** [comment]
Docs are updated. Thanks
