### ISSUE TITLE
Question re S2S integration together with Client Side HB

### ISSUE THREAD

**Issue by Shaishiff** [prebid/Prebid.js#1198]
Hey, a question regarding Prebid Server -
In case I use the S2S integration with a demand partners which are still not integrated with S2S (but has an adaptor for regular client side HB), will prebid know to combine both into a single auction ? Or will client side HB simply won't work at all in case I'm using S2S ?

Thanks.

**Comment by dmitriyshashkin** [comment]
You can combine client-side integration and a server side one. Those bidders that are not listed in setS2SConfig will still works a they used to.


BTW, it's relatively easy to setup a test page. It's absolutely trivial if you have a prebid server account, but even if you don't have one yet, it takes some minor effort to setup server side on your own computer for testing purposes. All it took me is to 1) install go 2) run go get 'prebid server' 3) run glide install 4) run go build 5) run the server. Detailed instruction is listed on prebid-server github page

**Comment by Shaishiff** [comment]
@dmitriyshashkin Thanks for your answer. Do you also know where can I find the current list of demand partners which support Prebid S2S ?
In the docs I only see:
"What demand partners work with Prebid Server?
We're announcing our full partner set soon -- stay tuned."

Thanks again.

**Comment by dmitriyshashkin** [comment]
I guess you can use the list of adapters from prebid-server repository:
https://github.com/prebid/prebid-server/tree/master/adapters

But be cautious, version deployed to prebid.adnx.com might be slighly different, some adapters might still be not fully functional. I was able to verify that appnexus, pubmatic, rubicon and indexExchange do work with some minor bugs. Still haven't tested them in production though.

**Comment by Shaishiff** [comment]
@dmitriyshashkin cool, thanks !
