### ISSUE TITLE
cannot add prebid.js as a yarn dependency

### ISSUE THREAD

**Issue by hadidon** [prebid/Prebid.js#1199]
## Type of issue

Bug

## Description

When adding prebid.js as a yarn dependency, some modules are not found.

## Steps to reproduce

yarn add prebid.js
import prebid from 'prebid.js'

### Expected results
Build success 

### Actual results
Module not found: Can't resolve 'polyfill' in...

## Platform details

prebid: 0.23.1
Browser: Chrome 58.0.3029.110 (64-bit)
OS: OSX El Capitan 10.11.6
node: v7.8.0
yarn: v0.21.3

**Comment by mkendall07** [comment]
Curious how your using the import `prebid` ? This may in fact be broken, we don't see a lot of usage like this. Typically the package is required and then built from there to be included in a larger bundle.
