### ISSUE TITLE
oms / brightcom's bid adapters prevent any aliases in isBidRequestValid()

### ISSUE THREAD

**Issue by andyblackwell** [prebid/Prebid.js#12047]
## Type of issue
`oms` / `brightcom` bid adapters prevent aliases in `isBidRequestValid()` validation
adapters: `omsBidAdapter`, `brightcomBidAdapter`, `brightcomSSPBidAdapter`
`oms` is supposed to replace `brightcom` & `brightcomSSP`, and has them as default aliases (`brightcom` & `bcmssp`), but rejects bids using those aliases

## Description
`isBidRequestValid()` unnecessarily checks if `bid.bidder` is an exact value matching the adapter's BIDDER_CODE var, which prevents any aliasing of the bidder, including any builtin aliases:
- v8.52.0:
  - brightcom: https://github.com/prebid/Prebid.js/blob/8.52.0/modules/brightcomBidAdapter.js#L123-L125
  - brightcomSSP: https://github.com/prebid/Prebid.js/blob/8.52.0/modules/brightcomSSPBidAdapter.js#L125-L127
  - oms: https://github.com/prebid/Prebid.js/blob/8.52.0/modules/omsBidAdapter.js#L139-L141
- v9.7.0:
  - oms: https://github.com/prebid/Prebid.js/blob/9.7.0/modules/omsBidAdapter.js#L139-L141

## Steps to reproduce
use `brightcom` or `bcmssp` with the `oms` bid adapter, or create and use a custom alias for any of the adapters

### Expected results
aliases work as expected

### Actual results
aliased bids rejected with:
> WARNING: Invalid bid sent to bidder

## Platform details
prebid v8.52.0 & v9.7.0

**Comment by patmmccann** [comment]
#10924 responsible?
