### ISSUE TITLE
Prebid Analytics Client Side & S2S 

### ISSUE THREAD

**Issue by chefbenjamin** [prebid/Prebid.js#1205]
Question

We are working on a custom prebid analytics ( which is client side today ) and a discussion point today was around S2S and how that might impact our current analytics as we migrate partners to the S2S setup. 

When running S2S will this pass back any data ? or do we need to think about S2S prebid analytics in a different way ? 

Benjamin

**Comment by mkendall07** [comment]
Hey Benjamin - yes we are sending data from S2S adapter. We need to add some logic for no bid's (see this [PR](https://github.com/prebid/Prebid.js/pull/1204) for example) but the idea is that we preserve the client side analytics as much as possible even with S2S demand.

**Comment by chefbenjamin** [comment]
Thanks Mike thats perfect for what we are thinking about.
