### ISSUE TITLE
device.(w|h): use screen.(width|height) instead of (innerWidth|innerHeight)

### ISSUE THREAD

**Issue by justadreamer** [prebid/Prebid.js#12065]
## Type of issue
enhancement

## Description
The proposed change is to replace [these lines](https://github.com/prebid/Prebid.js/blob/dc6c0c35ead5f44f3fc35852a84956a6c9036bed/src/fpd/enrichment.js#L102-L103) in `src/fpd/enrichment.js`:
```js
      const w = win.innerWidth || win.document.documentElement.clientWidth || win.document.body.clientWidth;
      const h = win.innerHeight || win.document.documentElement.clientHeight || win.document.body.clientHeight;
```
with 
```js
      const w = window.screen.width;
      const h = window.screen.height;
```

- screen API [docs](https://developer.mozilla.org/en-US/docs/Web/API/Screen)

## Motivation
1. **Consistency, DRYness.** Many adapters already do this anyway overriding the fpd implementation (f.e. see [ixBidAdapter](https://github.com/51Degrees/Prebid.js/blob/377f1265a424f5910369384e3eb9b43d6419028e/modules/ixBidAdapter.js#L2097-L2098), [adplusBidAdapter](https://github.com/51Degrees/Prebid.js/blob/6f4fb5b78a4bc31a1f84b59ec5b98d4e3bcf0179/modules/adplusBidAdapter.js#L127-L128), [adxcgAnalyticsAdapter](https://github.com/51Degrees/Prebid.js/blob/980a11ef264e7e360499f44c377c2dd3cd0c75a4/modules/adxcgAnalyticsAdapter.js#L126), [adxpremiumAnalyticsAdapter](https://github.com/51Degrees/Prebid.js/blob/ed2b8239e269d0f09b8044b39d94c91f0eff69df/modules/adxpremiumAnalyticsAdapter.js#L33), [brightMountainMediaBidAdapter](https://github.com/51Degrees/Prebid.js/blob/37ab555c840803dde2ef4971ee53955afbdecea6/modules/brightMountainMediaBidAdapter.js#L178-L179), [sharethroughBidAdapter](https://github.com/51Degrees/Prebid.js/blob/264db8c0286feaa7f2ec7e738d2509796f9c1920/modules/sharethroughBidAdapter.js#L46-L47), [saambaaBidAdapter](https://github.com/51Degrees/Prebid.js/blob/df66cdb1b90ddde1aaa7960b9f3c09eb89242ee8/modules/saambaaBidAdapter.js#L284-L289)) 
2. **Following the standard.** oRTB spec actually prescribes that device.(w|h) is the physical size of the **screen** in pixels, not browser window size
![image](https://github.com/user-attachments/assets/f3702683-3d21-44d4-8f64-22a5e00f2ffa)

## Alternative
Remove this code from the `src/fpd/enrichment.js` completely and let FPD module / RTD submodules take care of this.

## Other considerations 
*(can be extracted into a separate issue)* 

Given oRTB spec literally says "physical size of the screen in pixels" - perhaps it makes more sense to set it in physical pixels, not logical aka CSS pixels?  Then it would be:

```js
      const pxratio = window.devicePixelRatio || 1;
      const w = window.screen.width * pxratio;
      const h = window.screen.height * pxratio;
```
[`devicePixelRatio`](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) is usually more than 1 on retina and HD displays.  Thus it is desirable to either satisfy the spec or make it more precise if the industry expects device.(w|h) value to be expressed in CSS pixels. 

cc: thanks @patmmccann and @BohdanVV for raising this point as part of this PR review comment https://github.com/prebid/Prebid.js/pull/12005#discussion_r1686538409

**Comment by patmmccann** [comment]
Interesting information from Safari as an aside 
![image](https://github.com/user-attachments/assets/d9a75a54-921b-4911-a114-08c809f8030f)

**Comment by patmmccann** [comment]
proposal extension: continue to pass inner height and width as device.ext.vpw and vph
