### ISSUE TITLE
perBuyerSignals is being clobbered if it's a string

### ISSUE THREAD

**Issue by maco** [prebid/Prebid.js#12079]
## Type of issue
Bug 🐞 

## Description
According to the PAAPI [spec](https://github.com/WICG/turtledove/blob/main/FLEDGE.md?plain=1#L268) (see also the [commit history](https://github.com/WICG/turtledove/commit/53d99af9fa76078ecfb7a52b9b240c523398d559) for clarification), regarding perBuyerSignals:

> All fields that accept arbitrary metadata (auctionSignals, sellerSignals, and perBuyerSignals dictionary values) must be JSON-serializable values (i.e. supported by JSON.stringify())

We're using a string, and Prebid.js doesn't check for this case, instead assuming it will be an `Object` in every case.  This string format is intentional, as it makes it easy to use a checksum to confirm that no one has fraudulently modified our bidding data.

## Steps to reproduce
Drop this test in `test/spec/modules/paapi_spec.js` at line 159, just after the one it's obviously based on ("should not override existing perBuyerSignals")

```
            it('should not override existing perBuyerSignals, even when PBS is a string', () => {
              const original = 'original';
              igb1.pbs = {
                prebid: deepClone(original)
              };
              sinon.assert.match(getBuyerAuctionConfig().perBuyerSignals[igb1.origin], {
                prebid: original
              });
            });
```

I believe the code that replaces the string with an object is [setFPD()](https://github.com/prebid/Prebid.js/blob/0d021fe4714e2180ef6fd26e97d9309d92b1854e/modules/paapi.js#L139), when  called from `addPaapiConfigHook()` 's [`if (igb && checkOrigin(igb))` block](https://github.com/prebid/Prebid.js/blob/0d021fe4714e2180ef6fd26e97d9309d92b1854e/modules/paapi.js#L168-L171)

### Expected results

The string value we pass as `perBuyerSignals` will be returned to us as an identical string.

### Actual results

Our `perBuyerSignals` value is lost.

**Comment by dgirardi** [comment]
That test case asserts that when perBuyerSignals is an _object_ with a property `prebid` that is a string, it should not be overridden by prebid's enrichments. And indeed it fails, but it's different from how I interpret your description ("perBuyerSignals is being clobbered if it's a string"). From my testing a string perBuyerSignals is left intact.

Are you losing a string in `perBuyerSignals.prebid`, or should I be seeing an issue when the entire signal is a string?

**Comment by patmmccann** [comment]
🔨 📶

**Comment by patmmccann** [comment]
> The string value we pass as perBuyerSignals will be returned to us as an identical string.

This is not a reasonable expectation, and goes against both where the google ads and openrtb teams are headed. See https://github.com/WICG/turtledove/issues/1211 and https://github.com/InteractiveAdvertisingBureau/openrtb/pull/175/files#diff-407630e60468e9a631ed6267e70ab5b99b67fdd674651a555bb46225b73ffc74R380

**Comment by maco** [comment]
Alright, in that case I'll close this.
