### ISSUE TITLE
feature: adding and tracking `refresh` depth param 

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#12083]
## Type of issue
Feature request

## Description
ORTB has a standard `refresh` parameter that defines the refresh depth (https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/main/2.6.md#objectrefresh). Would prebid.js be able to keep track and increment this based on the calls to `requestBids` ? Seems like something that would be useful vs having the pub try and configure it properly with each call.

**Comment by patmmccann** [comment]
You linked the develop branch

**Comment by mkendall07** [comment]
> You linked the develop branch

Fixed the link thanks. `bid.bidderRequestsCount` seems to be holding the same information as `refresh.count` which is great, but there are additional fields inside `refresh.refsettings` that could be interesting to set such as the `reftype` and `minint`. 

Would it make sense for the ORTB2 converter to pick this up at least from `bid.bidderRequestCount` and merge with (if any) settings on the imp ORTB2 setting?

**Comment by mkendall07** [comment]
sounds like a good topic to bring to the PMC.

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/issues/11184#issuecomment-1985865618 may be "the sense of the publishers" on this. what's the goal on providing this?

**Comment by mkendall07** [comment]
thanks for the link @patmmccann. I agree that automatically sending half the data (just refresh depth which can be inferred) is a bit half baked. I'll close this for now. Thx
