### ISSUE TITLE
Multiple bids with the same id should not be allowed

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#1208]
## Type of issue
Bug

## Description
I've noticed it previously with komoona legacy adapter (https://github.com/prebid/Prebid.js/issues/972), now I see the same issue with [pubgears.](https://ibb.co/eO24i5). Attached is the list of bids I got for the same ad unit, ad id is in the 6-th column. Some bidders create more than one bid response for the same bid request, both bids get the same ad id. Prebid choses ad id of the best bid, but when renderAd is called with this adId as the parameter, prebid might not chose the same bid that won the auction.

It causes discrepancy, and might be used to abuse the system.

## Steps to reproduce
Call createBid twice, each time pass the same bid request object as the second parameter. Choose 0$ as cpm of the first bid and 100$ as the cpm of the second bid. Chose a winning bid id and pass it to renderAd.

### Expected results
Second createBid call procuses an error message, because the response for this bid request is already registered in the system.

### Actual results
No error is produced, 100$ bid wins the auction, but renderAd chooses 0$ bid.

## Platform details
Prebid version 0.24-pre

## Other information
https://github.com/prebid/Prebid.js/issues/972

**Comment by mkendall07** [comment]
Good find. We'll take a look and address
