### ISSUE TITLE
`hb_pb: ""` with custom price granularity inside `pbjs.setBidderConfig`

### ISSUE THREAD

**Issue by CMDezz** [prebid/Prebid.js#12098]
## Type of issue

Bug

## Description

`priceGranularity` worked like a charm with `low`, `medium` and `high` but there is `""` with `custom granularities` when i used it with `pbjs.setBidderConfig`

## Steps to reproduce
- This is the config
```           
pbjs.setBidderConfig({
    bidders: ['bidder'],
    config: {
        // "priceGranularity": "high", //worked as normal
        priceGranularity: {  // hb_pb become undefined
            buckets: [
                {
                    "precision": 2,
                    "max": 10,
                    "increment": 0.01
                }
            ]
        },
    }
})
```
- This is response from bidder adapter: 
```
{
    "ad": "ad_2000038474",
    "adUnitCode": "/19968336/prebid_native_example_1",
    "cpm": 0.7526081296409829,
    "creativeId": "2000038474",
    "currency": "USD",
    "height": 250,
    "impid": "0632a073c745d6c",
    "netRevenue": false,
    "requestId": "3090bf0e713b45",
    "ttl": 300,
    "width": 300
}
```
- This is result after targeting: 
```
{
    "hb_bidder": "bidder",
    "hb_adid": "54690138071e21",
    "hb_size": "0x0",
    "hb_source": "client",
    "hb_format": "banner",
    "hb_adomain": "",
    "hb_crid": "2000309476",
    "hb_pb":"",
}
```
- What i am expecting: 
```
 "hb_pb": "0.75",
```

**Comment by dgirardi** [comment]
Does this work for you?

```
pbjs.setBidderConfig({
    bidders: ['bidder'],
    config: {
        priceGranularity: 'custom',
        customPriceBucket: {
            buckets: [
                {
                    "precision": 2,
                    "max": 10,
                    "increment": 0.01
                }
            ]
        },
    }
});
```

You config should automatically get [translated](https://github.com/prebid/Prebid.js/blob/22d913e59e75f01ac7a3b35cfd7989db3e1c2136/src/config.js#L90-L103) into that and I believe there's a bug where it doesn't when it's set via `setBidderConfig`. But I get a different result (empty string, `hb_pb: ""`, rather than undefined), so I'm wondering if you're seeing something else.

**Comment by CMDezz** [comment]
> Does this work for you?
> 
> ```
> pbjs.setBidderConfig({
>     bidders: ['bidder'],
>     config: {
>         priceGranularity: 'custom',
>         customPriceBucket: {
>             buckets: [
>                 {
>                     "precision": 2,
>                     "max": 10,
>                     "increment": 0.01
>                 }
>             ]
>         },
>     }
> });
> ```
> 
> You config should automatically get [translated](https://github.com/prebid/Prebid.js/blob/22d913e59e75f01ac7a3b35cfd7989db3e1c2136/src/config.js#L90-L103) into that and I believe there's a bug where it doesn't when it's set via `setBidderConfig`. But I get a different result (empty string, `hb_pb: ""`, rather than undefined), so I'm wondering if you're seeing something else.

Sorry for the mistake. Yes, we saw the same thing, it was an `""` with `hb_pb`. 
Thank you for your solution, it worked for me.
