### ISSUE TITLE
Calling addBidResponse with response that doesn't have matching request can prematurely end auction

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#1210]
## Type of issue
bug/improvement

## Description
addBidresponse function in bid manager has the following code:
`const { requestId, start } = getBidderRequest(bid.bidderCode, adUnitCode);`
Later the start variable is used to calculate timeToRespond. If timeToRespond is larger than cbTimeout, callback is executed and the auction is over. If there is no matching request found, start is equal to null and timeToRespond is equal to the responseTimestamp. So if adapter passes wrong bidderCode / adUnitCode it ends the auction. I'm not quite sure if it is a bug, but decided to report just in case. Took me some time to notice a problem in my code. Probably some safety check should be implemented.

## Steps to reproduce
call addBidResponse with wrong adUnitCode or bidderCode

### Expected results
error message is generated, BidResponse is ignored

### Actual results
auction is ended prematurely

## Platform details
prebid version 0.24-pre

**Comment by mkendall07** [comment]
I thought @protonate fixed this already...

**Comment by pkayfire** [comment]
Can confirm we're seeing this on our production setup as well. For now, we're disabling that check in addBidResponse if the bidResponse returns a statusMessage of `Bid returned empty or error response`
