### ISSUE TITLE
Analytics Adapters need "missed" events (or: make events.getEvents public)

### ISSUE THREAD

**Issue by thomaslsimpson** [prebid/Prebid.js#1211]
## Type of issue
Feature Request

## Description
Implementing an Analytics Adapter (that is loaded separately) requires adding code to catch events from Prebid that fire before the adapter is loaded. The events themselves are available already via a call to events.getEvents but this method is not part of the public API.

If adapters could get provided the previous events during the enableAnalytics call, or provided a way to get the previous events, this issue would vanish. 

If there were no issue with making the getEvents method from the events module part of the public API for Prebid, this would solve the problems as well.

## Steps to reproduce
For now, you have to hook the pbjs events you care about, store them and then process them when your adapter is loaded.

### Expected results
This preload storage code should be able to be done away with, since the information is already available. Either by a (probably optional?) call after enableAnalytics or by putting getEvents in the public interface.

**Comment by mkendall07** [comment]
This isn't high on our priority list but you could submit a PR for review and we can take a look. Thanks for the suggestion.
