### ISSUE TITLE
DFP delivering Prebid line items with no demand

### ISSUE THREAD

**Issue by mrkfgs** [prebid/Prebid.js#1214]
## Type of issue
Bug?

## Description
After installing prebid.js on my site, I started to notice that after a few page views/refreshes ads started to show blank. Upon further testing using DFP console and prebid debug tools I realized that DFP was showing prebid line items that had no winners, which resulted in blanks being served. Shouldn't AdSense serve if there are no winners? I'm not sure what the issue is at this point. Here's my site if anyone is interested in checking things out. Thanks in advance for the help! https://multitrackmaster.com

<img width="1385" alt="screen shot 2017-05-19 at 9 35 03 am" src="https://cloud.githubusercontent.com/assets/660340/26250166/345de41a-3c77-11e7-9324-83f9d72c1642.png">
<img width="1342" alt="screen shot 2017-05-19 at 9 37 50 am" src="https://cloud.githubusercontent.com/assets/660340/26250167/345ff84a-3c77-11e7-9cd1-0c70c967b086.png">

**Comment by GLStephen** [comment]
Do you have the targeting set properly on the lineitems?

**Comment by mrkfgs** [comment]
Yes, I believe so. Here's a screenshot of my one of my line items.
<img width="843" alt="screen shot 2017-05-19 at 10 19 04 am" src="https://cloud.githubusercontent.com/assets/660340/26252031/1cc858ca-3c7d-11e7-8825-53521c5f72f2.png">

**Comment by mrkfgs** [comment]
The problem was that I had setTargeting values hardcoded in my DFP ad unit. Removing them solved the issue!
