### ISSUE TITLE
It is possible to specify conflicting info on ad units and ortb2imp

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#12166]
It is possible to do this: 

`
pbjs.requestBids({
   adUnits: [{
    code: 'test-div',
      mediaTypes: {
        banner: {
            sizes: [[300,250]], battr = [3]
        }
    },
    ortb2Imp: {
        banner: { battr = [4] }
    }
   }]
});`

And many publishers specify params for imp.video.* in the mediatype.video object, not the ortb2Imp.video object. 

Some adapters look for battr in the latter (ttd), some in the former (pubmatic) and most just use params (we need to clean that up). 

Proposal: the ortb2Imp object in the bid request contains the full banner and video objects from the mediatype, and vice versa, but conflicts always resolve to the media type. 

This has some impacts on PAAPI bidders, which are reliant on ortb2Imp being detailed

**Comment by pm-harshad-mane** [comment]
> And many publishers specify params for imp.video.* in the mediatype.video object, not the ortb2Imp.video object.

We, Prebid, can keep only one way of defining these params ( a major version change ), preferably through `ortb2Imp`.

**Comment by patmmccann** [comment]
>> the ortb2Imp object in the bid request contains the full banner and video objects from the mediatype,

> We can do this only for specific fields that we decide should be mirrored.

Doh, let's scope this down to just battr and these ones https://github.com/prebid/Prebid.js/pull/11970/files#diff-a4386e7142e703699b5a905fc06783725a5eccecb33fa0b1f6b5ab4466fb8286 ?

**Comment by patmmccann** [comment]
outcome: ortb2Imp should win in the case of conflict

**Comment by patmmccann** [comment]
1)  for fields only in mediaTypes that are valid imp objects (eg imp.secure or imp.battr), they can be copied into ortb2Imp.
2)  for fields only in ortb2Imp, they can be copied into mediatypes.
3) If ortb2Imp and mediatypes.banner or mediaTypes.video or mediaTypes.native have different values for some field where they are both defined, than copy from ortb2Imp into mediatypes and publish a warning.
