### ISSUE TITLE
Bid from Yandex always response with 403

### ISSUE THREAD

**Issue by banghawe** [prebid/Prebid.js#12164]
## Type of issue
Question

## Description
I integrate Prebid.js and Yandex as bidder, my site is approved and the ad placement status is running on their dashboard. I ask Yandex team but they ask me to ask Prebid team instead.
This is the site where the bidding should happen => https://banghawe.com/game/253/colorful-assort
This is Yandex ad placement => R-A-11644614-1
![image](https://github.com/user-attachments/assets/f4560732-175a-4fcb-b1ed-858b6a7e5c09)
Thanks

## Test page
https://banghawe.com/game/253/colorful-assort

### Expected results
Should return with response 204 for no bid or 200 with bid

### Actual results
Bid response is 403

## Platform details
Prebid.js 9.11

**Comment by dgirardi** [comment]
> they ask me to ask Prebid team instead

well, I can confirm that it indeed appears to return a 403. I hope this was helpful @chernodub .

**Comment by patmmccann** [comment]
403 with "bad partner" in the response payload 
![image](https://github.com/user-attachments/assets/b3d7b352-88b0-4ea1-bf16-fa86dc2d33cb)

**Comment by chernodub** [comment]
Hi @dgirardi @banghawe, thanks for reaching out to me directly!

As far I see, the problem happens because of the missing `Referer` header. I asked my team to contact @banghawe directly via email and help to set up the adapter.
