### ISSUE TITLE
Settings ortb2 first party data during beforeRequestBids

### ISSUE THREAD

**Issue by EskelCz** [prebid/Prebid.js#12165]
## Type of issue
Question

## Description
Is `pbjs.setConfig({ ortb2 })` supposed to work within the `beforeRequestBids` event handler?
I can see that the key is being rewritten at a later time, but the setConfig didn't work for me. So just to be sure if that is expected or not. Thanks.

## Platform details
Prebid 8.49, MacOS

**Comment by dgirardi** [comment]
It is expected behavior; first party data from `setConfig` is "frozen" at the time of `requestBids`. Otherwise it wouldn't always be clear where it applies (there can be multiple auctions running; and each one may have passed it through some modules already).

**Comment by EskelCz** [comment]
Ok, thanks for the information
