### ISSUE TITLE
`onTimeout()` fired for bids recieved before Auction Timeout.

### ISSUE THREAD

**Issue by dqureshiumar** [prebid/Prebid.js#12176]
## Type of issue
Bug

## Description
We are recording `onTimeout()` event getting called for all bidders, if any of the bidder's bid in current auction times out.

## Test page
https://jsfiddle.net/umerrqq/t61e2zkm/4/

## Steps to reproduce

In Chrome Developer Tools enable Network Throttling to **Slow 3g** for timing out bidders
![Screenshot from 2024-08-22 18-24-26](https://github.com/user-attachments/assets/441b2753-3ef3-45ab-b501-f354a6ff1ee6)

We are using bidders who have implemented `onBidWon` and `onTimeout` events in their respective Bid Adapter
1. Media.net Bid Adapter
2. AdQuery Bid Adapter

### Case 1: 

Media.net Bidder Won (mocked Bid) - onTimeout and onBidWon event is fired for the same bidder

![Screenshot from 2024-08-27 13-37-40](https://github.com/user-attachments/assets/038ca671-691d-4713-9585-1f0db11b8c7a)

![Screenshot from 2024-08-27 13-37-48](https://github.com/user-attachments/assets/80d32c46-5694-4233-bdca-4620a17657dc)

### Case 2: 

Ad Query Bidder Won(mocked Bid) - onTimeout and onBidWon event is fired for the same bidder

![Screenshot from 2024-08-27 13-39-13](https://github.com/user-attachments/assets/5733a3ab-12e6-4188-af15-e00d51380e21)

### Prebid Events

1. Bid Timeout Event - The below image shows adquery bidder’s snm appears is **TIMEOUT**
![Screenshot from 2024-08-27 15-34-00-edited (1)](https://github.com/user-attachments/assets/f6e024fd-bdc5-412d-b599-06a122762497)

2. Auction End Event -  in `auctionEnd` event, under `bidsReceived` array, the bidder's snm is **RENDERED**.
![Screenshot from 2024-08-27 15-39-04-edited](https://github.com/user-attachments/assets/8a4be8d1-0863-4013-8caf-dc59308897b0)

### Expected results
`onBidWon` should've fired and NOT the `onTimeout` event
### Actual results
Both `onBidWon` and `onTimeout` events got fired.

## Platform details
Prebid 9.11.0

### Other Information
1. To mock a Bidder Response, we are using Professor Prebid chrome extension
2. Additionally use [ModResponse](https://chromewebstore.google.com/detail/modresponse-mock-and-repl/bbjcdpjihbfmkgikdkplcalfebgcjjpm) to throttle a specific bidder

**Comment by ChrisHuie** [comment]
Closing with merged pr #12177
