### ISSUE TITLE
Issue With Rubicon adapter on Safari

### ISSUE THREAD

**Issue by jdelhommeau** [prebid/Prebid.js#122]
It seems there is a bug in the Rubicon adaptor with safari and edge browser.

this line is not working in Safari (tested by me) and neither in edge (so I was told, I didn't test)

line 879 in prebid.js : var rubiconObj = iframeObj.contentWindow.RubiconAdServing;

the contentWindow variable is undefined in Safari. In order for it to work, we need to  change the line to:

var rubiconObj = iframeObj.window.RubiconAdServing;

**Comment by ialex** [comment]
You could change that line to:

    var rubiconObj = iframeObj.contentWindow.RubiconAdServing || iframeObj.window.RubiconAdServing;

That way if the first doesn't exists the second will be used

**Comment by hjeong12** [comment]
fixed in  #130
