### ISSUE TITLE
Subscribing for prebid events

### ISSUE THREAD

**Issue by Andrey9300** [prebid/Prebid.js#12269]
## Type of issue
Question

## Description
In prebid 9+ I can't subscribe for analytics, because adapter and adapterManager become private.
As I understand, the right way to have analytics is to publish an analytics module to prebid.
Actually, I don't understand why I can't subscribe to events to support my own monitoring in my project.
I'm be glad if you recommend me how to solve subscription for prebid events.

## Platform details
Prebid.js 9+

**Comment by dgirardi** [comment]
Events are available through `onEvent`: https://docs.prebid.org/dev-docs/publisher-api-reference/onEvent.html
There's also a generic analytics module: https://docs.prebid.org/dev-docs/modules/genericAnalyticsAdapter.html

**Comment by patmmccann** [comment]
are you a publisher or a module maintainer?

**Comment by Andrey9300** [comment]
Yep, I forgot to say that I'm a publisher and build prebid via npm with some modules.
 
I think `onEvent` might fit to me.

The next small thing that it is now I can't get constant with names of all events from `prebid.js/src/constants.json`. But it is fine, but quite strange)

**Comment by dgirardi** [comment]
> I can't get constant with names of all events

the reason for this and disabling most other imports in general is that they are not part of the public API, so they're subject to change without notice - which would break anyone depending on them. For the public API we take care to limit breaking changes to major version releases, but it's not feasible to do that for the entire codebase.

**Comment by Andrey9300** [comment]
Yes, you are right.

Thank you for help!
