### ISSUE TITLE
Issue with Rubicon adapter in case of no ad

### ISSUE THREAD

**Issue by jdelhommeau** [prebid/Prebid.js#123]
Sometime Rubicon fastlane code send back a response stating no ads available.
This is not well interpreted by prebid.js which is looking for an ad and fail on the line 888:

                       var sizeArray = size.dim.split('x');

size is undefined, which cause an error:

Error parsing rubicon response bid: 'undefined' is not an object (evaluating 'size.dim') 

This is the no ad response from Rubicon which is mis interpreted.

![image](https://cloud.githubusercontent.com/assets/14938467/11527793/3b23f8a4-98e3-11e5-9ec8-7b105278b189.png)

**Comment by hjeong12** [comment]
fixed #130
