### ISSUE TITLE
Difference between S2SConfig timeout and PREBID_TIMEOUT = 500;

### ISSUE THREAD

**Issue by pribeh** [prebid/Prebid.js#1236]
When using S2S right now there's a timeout option. Sorry if this sounds like a dumb question but what's the difference between the timeout set in S2SConfig and then in PREBID_TIMEOUT? And should we be using both or does one override the other? Thanks

**Comment by mkendall07** [comment]
Not a dumb question, we have to clarify this in the docs but the S2SConfig timeout is the amount of time prebid server allows for it's bidders to respond. So it should never be greater than the PREBID_TIMEOUT on page, and should in reality be adjusted for the roundtrip time to prebid server. So I think having `PREBID_TIMEOUT = 700` and `S2SConfig : {timeout : 500}` is reasonable for example.

**Comment by pribeh** [comment]
Great, thanks @mkendall07 ! That's clear to me now. Definitely worth putting that in the docs.
