### ISSUE TITLE
ImpactifyBidAdapter - Already removed syncStore returned into bidder and prevent any bidRequest for prebid.js >= 8.22.0

### ISSUE THREAD

**Issue by vlyby-nadja** [prebid/Prebid.js#12377]
## Type of issue
Bug

## Description
Because of former issues, this line was removed with Prebid version 7.48.0 (https://github.com/prebid/Prebid.js/pull/9890/files), but returned in version 8.22.0:
https://github.com/prebid/Prebid.js/commit/5bea60769c2e05a81b8e51e664cc0c1a5e0cfc65#diff-dda596ef1d4adade492fe9fbd9bdb7148b0477abd765595acc6300b6aac24f27R164

Problem is, the syncStore is undefined and the bidder is not able to generate any bidRequest:
![image](https://github.com/user-attachments/assets/845e0c78-109e-4408-99da-f5cb71cfd407)

## Steps to reproduce
Using the bidder on a page with a CMP including usp consent data.

## Test page
-

### Expected results
Without this line in the bidder the bidRequest can be generated.

### Actual results
No bidRequest can be generated.

## Platform details
Prebid.js >= 8.22.0

**Comment by dgirardi** [comment]
cc @filipeneves @timpactifyo91 @thomasdseao
