### ISSUE TITLE
OpenRTB 2.6

### ISSUE THREAD

**Issue by EskelCz** [prebid/Prebid.js#12395]
## Type of issue
Question

## Description
Recently we have received a request from Magnite representative, to upgrade some OpenRTB fields to version 2.6.
Specifically:
```
$.imp.video.ext.videotype to $.imp.rwdd
$.source.ext.schain to $.source.schain
$.user.ext.eids to $.user.eids
```
At first we replied that they probably mean Prebid Server, because I assume this would need to change in bid adapters, but now they replied that it applies to Prebid.js as well.
Since I don't see any mention of the issue here, I'm quite confused what is going on. I thought Magnite is deeply involved in Prebid development, so I wouldn't except any misinformed instructions or demanding something not already covered by current Prebid releases. But I see in the bid requests that they are in ORTB 2.5, so I have to figure out how to comply with it.
Thanks for any guidance.

**Comment by patmmccann** [comment]
Cc @bretg @harpere 

Fwiw magnite doesn't make ortb requests so this seems odd

**Comment by dgirardi** [comment]
With regards to fields that changed name from 2.5 to 2.6, Prebid's strategy has been to pick the 2.6 name for newly added fields, but not change those that were already implemented. The alternative would be to repeat their contents in both, since swapping the name is a breaking change; every downstream consumer is forced to accept both names for the same reason, so the end result would be an increase in traffic for no advantage.

**Comment by EskelCz** [comment]
It's this email, maybe I am misunderstanding it's meaning: [http://mail.magnite.com/v/NzAyLUVZTy00MDcAAAGT89Gdj12Ka_b2c59oyDZrdkRjT_GbmA6ihr9Rti2WvHMpG6DBrHDUXdPhUUba9MV1w72h7qs=](http://mail.magnite.com/v/NzAyLUVZTy00MDcAAAGT89Gdj12Ka_b2c59oyDZrdkRjT_GbmA6ihr9Rti2WvHMpG6DBrHDUXdPhUUba9MV1w72h7qs=)
However Anne-Cathrin Voltmer (avoltmer at magnite.com) confirmed it applies to requests from Prebid.js as well.

**Comment by patmmccann** [comment]
My reading of this is that you can safely ignore it. Magnite is not going to suddenly start ignoring schains or eids in the location Prebid.js puts it. If they did, their business would surely fail.

**Comment by robertrmartinez** [comment]
Thanks for bringing this up @EskelCz 

This is mostly for other integrations.

Our current `Banner` implementation `fastlane.json` is a GET interface which obviously is not affected by this.

Video + Native go through PBS which then forwards a POST, which we will change as needed.

All to say, nothing is required for Prebid integrations for publishers, we will handle that as it comes in.

This is mostly for other integrations not explicitly controlled by our teams!

Thanks.

**Comment by EskelCz** [comment]
@robertrmartinez Ok, thanks for the clarification. We have also received a revised answer from our Magnite representative, so all is well. :) Closing.
