### ISSUE TITLE
Setting EIDs without user ID module

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#12396]
## Type of issue

Feature request

## Description

Publishers or 3rd party scripts should be able to set EIDs and have them picked up by adapters without the need to include any userID module.

## Other information

With https://github.com/prebid/Prebid.js/pull/12110, EIDs set as first party data are picked up by the userID module an and included in `userIdAsEids`. However, if the userId module is not present, `userIdAsEids` is also missing and many adapters would not see any ID.

Options are:

 - update every adapter to look at `ortb2.user.ext.eids` instead of userIdAsEids;
 - move the `userIdAsEids` logic out of userId and into core.

Also related: deprecation of the legacy `userId` (https://github.com/prebid/Prebid.js/issues/11377)

**Comment by patmmccann** [comment]
Use cases: 

Another script or browser extension plans to inject eid for bidder utility however prebid does not have userid module installed.

My preference is option 1

**Comment by patmmccann** [comment]
On committee discussion, we may patch some popular adapters to do  look at ortb2.user.ext.eids instead of or in addition to userIdsAsEids
