### ISSUE TITLE
 Commit #9647 has changed the behaviour of renderAd preventing the ANOutstreamVideo.js renderer from displaying a video ad.

### ISSUE THREAD

**Issue by dbirkbeck** [prebid/Prebid.js#12390]
## Type of issue
Bug

## Description
The ANOutstreamVideo.js renderer requires access to the top level web page to properly render ads. (It creates it's own iframe as needed.)

Commit #9647 (prebid release 8.25.0) changed the behaviour of the renderAd function disallowing writing to the main document. This breaks the ANOutstreamVideo.js renderer.

It is obvious that no one tested this change against prebid's own example web pages located at:
https://docs.prebid.org/examples/video/outstream/pb-ve-outstream-no-server.html

## Steps to reproduce
Enter the current Prebid outstream reference (no ad server) URL in a web browser and append the prebid debug query string as follows:
https://docs.prebid.org/examples/video/outstream/pb-ve-outstream-no-server.html?pbjs_debug=true

Watch for a message similar to the following in the web browser console:
ERROR: Error rendering ad (id: <>): renderAd was prevented from writing to the main document.

## Test page
https://docs.prebid.org/examples/video/outstream/pb-ve-outstream-no-server.html?pbjs_debug=true

### Expected results
The ANOustreamVideo.js renderer should be allowed to display a collapsable video ad.

### Actual results
The following error message is logged to console instead of a video ad being rendered:
ERROR: Error rendering ad (id: <>): renderAd was prevented from writing to the main document.

## Platform details
All releases of Prebid after and including 8.25.0
All platforms

**Comment by patmmccann** [comment]
interestingly #10944 also flagged but we missed the relationship
