### ISSUE TITLE
AOL adapter removed

### ISSUE THREAD

**Issue by ikhemissi** [prebid/Prebid.js#124]
Hi,

I was wondering why the AOL adapter was removed ?!

Best regards,
Iheb

**Comment by mkendall07** [comment]
Hi @ikhemissi 

We wanted to have it vetted by AOL directly before committing to a release. They have given us the go ahead so we will be merging it and will be included in the next release.

**Comment by ikhemissi** [comment]
Ah! OK, I see.
Thank you very much @mkendall07 and @prebid team

**Comment by mkendall07** [comment]
Just merged it to master https://github.com/prebid/Prebid.js/commit/ea0e35285d78ed536ba618e5993a94a96f906e04

**Comment by ikhemissi** [comment]
Thanks @mkendall07  ;-)
