### ISSUE TITLE
gdprApplies is undefined at Object.getUserSyncs non-GDPR country

### ISSUE THREAD

**Issue by Roi467** [prebid/Prebid.js#12414]
## Description
When trying to run an auction from a non-GPDR country, it throws an error
```
Cannot read properties of undefined (reading 'gdprApplies')
at Object.getUserSyncs

```
![1](https://github.com/user-attachments/assets/f1334a4c-7620-43f4-a340-81d185e73667)

## Steps to reproduce
try to run an auction with a non-GDPR country 
in my particular case, it was with holidBidder

## Other information

I found the issue I tried to get the `pbjs.getConsentMetadata` the gdpr was `undefined` 
and with a GDPR country, I got the full structure of the gdpr (include the gdprApplies)
![3](https://github.com/user-attachments/assets/27f7c201-a868-4689-a7a9-98f2ce6dc0df)
![2](https://github.com/user-attachments/assets/10a7c1fe-a0b3-4192-92ba-3edd878125d8)

**Comment by dgirardi** [comment]
This appears to be a bug specific to holid and iframe syncs. A workaround while waiting for the fix is to disable iframe syncs for holid, for example:

```
pbjs.setConfig({
    userSync: {
        filterSettings: {
            iframe: {
                bidders: ['holid'],
                filter: 'exclude'
            }
        }
    }
});
```
