### ISSUE TITLE
prebid server can respond with a bid a status=no_cookie at the same time

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#1241]
## Type of issue
Bug

## Description
With appnexus bidder prebid server can respond with a bid, even though the status field of the response would be "no_cookie". Example of such response can be found below. In that case prebidServer adapter will not pass that bid to bid manager.

```
{
    "tid": "26d45068-c591-4b9d-8871-8f04aa0e4846",
    "status": "no_cookie",
    "bidder_status": [{
        "bidder": "appnexus",
        "response_time_ms": 148,
        "num_bids": 1
    }],
    "bids": [{
        "bid_id": "1c8b93f7c9fbc9",
        "code": "ad_cs_9493688_728_90",
        "creative_id": "63718300",
        "bidder": "appnexus",
        "price": 1.491,
        "adm": "",
        "width": 728,
        "height": 90
    }]
}
```

## Steps to reproduce
1) Setup appnexus bidder to work through prebid-server
2) Clear all cookies / go to incognito mode
3) Get a bid from appnexus (can be done through appnexus debug placement id)

### Expected results
Bid is passed to bid manager and can be seen through pbjs.getBidResponses() call.

### Actual results
Bid is not passed to bid manager and can not be seen through pbjs.getBidResponses() call.

## Platform details
Prebid.js v 0.25-pre
Chrome/Fedora25

**Comment by mkendall07** [comment]
fixed in master.
