### ISSUE TITLE
Discrepancies in impressions 

### ISSUE THREAD

**Issue by tshaked** [prebid/Prebid.js#1242]
Hi There,
We've noticed discrepancies in impressions in specific bidders (all the rest are ok)(bidders with discrepancies -springserve,districtm)
prebid version - v.0.20.0
The numbers vary between 15%-25%.
The discrepancy is found only in desktop and not in mobile or tablet.
So probably it's not time zone issue.
Any ideas for this problem?

Thanks!

**Comment by matthewlane** [comment]
#1130 fixed certain cases of discrepancies and was released in v0.22.2. Are you able to test with this version or newer and measure a change in numbers for those bidders?

**Comment by headerbidding** [comment]
I am getting a 19% impression discrepancy and a 18% revenue discrepancy with bRealtime using v 0.22.2 - 0.24.1.  
bRealtime suggests to "reach out to prebid.js" since "we have limited transparency when it’s not our technology."

**Comment by mkendall07** [comment]
Discrepancy seem to increase with refreshing bids. You should only refresh bids that you can reasonably know that you can display.

**Comment by headerbidding** [comment]
I don't beleive I am refreshing bids.
This is my ad code:
http://www.flixxy.com/prebid.htm

**Comment by headerbidding** [comment]
We are still seeing the 20% impression discrepancies in version 28, but only with the brealtime / appnexus adapter.

**Comment by headerbidding** [comment]
We are still seeing the 20% impression discrepancies (and 25% revenue discrepancies) in version 31 with the brealtime / appnexus alias.  Appnexus support has been investigating for over a week now, but no success so far...

**Comment by headerbidding** [comment]
bRealtime 20% impression discrepancies (and 25% revenue discrepancies) still exist in version 0.33.0
bRealtime has been in touch with Appnexus support since over one month.  We have given Appnexus support read access to our DFP.  Issue has not been resolved yet.

**Comment by mkendall07** [comment]
hey @headerbidding - it's better to work with each ssp directly to resolve issues. I'm going to close this out.

**Comment by headerbidding** [comment]
@mkendall07   UPDATE: Appnexus Support has been working on this for 6 weeks now (with access to our DFP and Google Analytics Account) and still has not figured it out...
