### ISSUE TITLE
How to upload new adapter

### ISSUE THREAD

**Issue by chensMMG** [prebid/Prebid.js#1243]
## Type of issue
Question

## Description
We are about to upload new adapter, what is the proper way to do that.
Are we supposed to do a pull request straight to the master branch or create a new branch?

**Comment by jaiminpanchal27** [comment]
@chensMMG http://prebid.org/dev-docs/bidder-adaptor.html

**Comment by chensMMG** [comment]
I have done all of that and im ready to upload it to Prebid.js branch.
My question was what to do next, open new branch and upload the project with my files or do a pull request straight to the master.

**Comment by dbemiller** [comment]
[Create a fork](https://help.github.com/articles/fork-a-repo/) and open a PR with the changes.
