### ISSUE TITLE
Odd error just can't track down: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'ext')

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#12430]
## Type of issue
Bug I think,  Its an error which I just cant track down to where its coming from, it doesn't "seem" to effect anything as far as I can see

## Description
this is all i've got on it:
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'ext')
    at Object.getUserSyncs (<anonymous>:55:7110)
    at <anonymous>:12:34796
    at Object.e [as registerSyncs] (<anonymous>:12:32748)
    at Object.S [as runWithBidder] (<anonymous>:12:68014)
    at <anonymous>:77:15414
    at Array.forEach (<anonymous>)
    at <anonymous>:77:15340
    at onResponse (<anonymous>:77:15467)
    at success (<anonymous>:77:13460)
    at <anonymous>:12:40889

## Steps to reproduce
I dont know how to reproduce at this stage

## Test page
https://cms.adysis.com/unlock-your-ultimate-listening-experience-a-review-of-the-sony-wh-xb910n-wireless-headphones/

### Expected results

no error fired

### Actual results

error fired

## Platform details
P9.19.0 , seems to not be related to a version , I went back to 9.14.0 and still there,  chrome, mac

**Comment by patmmccann** [comment]
your issue is here https://github.com/prebid/Prebid.js/blob/f71023d281a3def5cbc66b40b84c7bc8919a80df/modules/datablocksBidAdapter.js#L449

**Comment by spormeon** [comment]
@patmmccann  ah har, what a plonker, wrong id, been chasing that for 2 weeks lol, thanks. close out i guess
