### ISSUE TITLE
adsupply_spec.js fails when using different globalVarName

### ISSUE THREAD

**Issue by derdeka** [prebid/Prebid.js#1244]
## Type of issue
BUG

## Description
When changing globalVarName in package.json to a different name, adsupply_spec.js fails to pass.

## Steps to reproduce
Edit globalVarName in package.json from "pbjs" to "mypbjs", then run `gulp serve`

### Expected results
Passing Tests.

### Actual results
 Uncaught ReferenceError: mypbjs is not defined
  at test/spec/adapters/adsupply_spec.js:8908

## Platform details
Windows 10 1511, node 6.9.1, prebid.js 0.24.1

**Comment by jaiminpanchal27** [comment]
@derdeka Thanks for highlighting this bug. We added $$PREBID_GLOBAL$$ macro after many adapters were already merged to master. At this stage it will be difficult to contact each one and ask them to update their spec files. 
Also with Prebid 1.0 already in progress we will make sure that such issues do not arise in future.
