### ISSUE TITLE
Prebid does not select highest bid when more than one bid per bidder/adapter in "send all bids" mode.

### ISSUE THREAD

**Issue by kizzard** [prebid/Prebid.js#1246]
## Type of Issue
Bug (Possibly feature request if working as intended)

## Description
When in "Send all Bids" mode, if two bidder IDs are configured for the same adapter against the same ad unit, the bidder specific key value is not necessarily the highest bid of the two responses.

## Steps to reproduce
1. Run demo page: https://jsfiddle.net/ry8h1hg2/
2. Monitor calls to DFP. Compare the hb_pb key with hb_pb_aol. note that sometimes, the hb_pb_aol key is lower than hb_pb even though both bids are from the AOL adapter.

### Expected results
The bid submitted by the bidder specific key (hb_pb_aol) should be the highest of all bids submitted by that adapter for that ad unit.

### Actual results
The bid submitted by the bidder specific key (hb_pb_aol) is not always the highest of all bids submitted by that adapter for that ad unit (it may be the last received bid although I am having trouble confirming this)

Here is an example of the prev_scp query parameter in the DFP ad call showing this behavior. Note that this is for a single multi-size 300x250/728x90 ad unit:

`hb_size_aol=728x90&hb_pb_aol=0.16&hb_adid_aol=3b23281593c0488&hb_bidder_aol=aol&hb_size=300x250&hb_pb=0.21&hb_adid=23fe003c94653a&hb_bidder=aol`

## Platform details
All browsers, Prebid 0.24.1

## Other information
Using multiple IDs for the same bidder for the same ad unit is often used for multi-size units.

**Comment by aneuway2** [comment]
Hey @kizzard have you by chance checked out http://prebid.org/dev-docs/prebid-troubleshooting-guide.html I'd run through the *List your Bids and Bidders* section to *Check the Ad Server’s Auction* (up to Are the key-values being set in the ad server?)

Maybe its possible that the second bid was received after the timeout, and thus never was sent to the ad server? `pbjs.getBidResponses();` should be able to tell you time to respond on the bid response.

**Comment by kizzard** [comment]
Hi @aneuway2 - Thanks for your reply! It's not possible that the second bid was received after the timeout because I'm diagnosing this by actually checking the GPT ad requests and teasing out the key values (you can see them in my "Actual Results" section, which shows that *both* results are indeed sent to DFP, but the generic hb_pb and hb_pb_aol values don't match.

You should be able to reproduce this behavior pretty easily with my demo page (let me know if you're not getting bids)

**Comment by aneuway2** [comment]
okay, I was able to reproduce on that JS fiddle. I suspect that `hb_pb` is getting the highest bid while `hb_pb_aol` is getting the last returned bid for that bidder that occurs before the timeout. (not sure what the fix would be for this though, or if my hunch checks out)

![screen shot 2017-06-07 at 9 46 50 am](https://user-images.githubusercontent.com/23339146/26881946-f4077724-4b66-11e7-832c-88620d635802.png)
![screen shot 2017-06-07 at 9 47 29 am](https://user-images.githubusercontent.com/23339146/26881950-f80cd3aa-4b66-11e7-805d-fc7770d331f7.png)

**Comment by kizzard** [comment]
Hi @aneuway2, yes I agree that your hunch is the most likely explanation.

The problem here is most likely an assumption that there would only ever be a single bid per bidder, per ad unit (therefore we don't do any work to select the highest), which is not necessarily the case.

A suggested fix would be to modify the code that sets the bidder specific key values to check to see if there already exists a bidder specific key value, and if so, only override it if the price is higher.

**Comment by kizzard** [comment]
Hi @aneuway2 and @protonate , any thoughts here?

**Comment by gramorris** [comment]
Just a note to say this also affects bidders that return multiple bids for multiple sized slots e.g. IndexExchange. In the case attached this was a slot where one request was made to Index for 300x250 and 300x600 sizes and Index returned two bids. Although the highest bid is in hb_pb the lowest is in [hb_pb_indexExchange

![screen shot 2017-06-29 at 13 50 04](https://user-images.githubusercontent.com/6436641/27688383-4f33e214-5cd2-11e7-9e71-34cf96a0e16f.png)
![screen shot 2017-06-29 at 13 53 01](https://user-images.githubusercontent.com/6436641/27688382-4f31454a-5cd2-11e7-8090-f66b0895298e.png)

**Comment by jnsprngs** [comment]
Adding that this bug severely reduces the data quality coming into DFP and therefore makes it hard to monitor and analyze prebid. Discrepancies between DFP and bidder reporting are inconsistent and unpredictable. It should also be investigated whether this issue extends into prebid analytics adapters. I think this bug is a big deal.

**Comment by gramorris** [comment]
The big deal is that revenue (possibly significant) is silently lost as a result of the highest bid not being selected. I certainly wouldn't recommend anyone use the send all bids functionality until it's resolved.

**Comment by mkendall07** [comment]
thanks for the nudge guys. Will look into this ASAP.

**Comment by bretg** [comment]
I suspect this is related to https://github.com/prebid/Prebid.js/issues/1267

@harpere, please confirm relatedness as part of your research?

**Comment by mkendall07** [comment]
@gramorris @jnsprngs @kizzard 
I opened #1427 to fix this issue. Thanks for the report.
