### ISSUE TITLE
GPP Consent — MSPA Activity Control has invalid logic denying features when consent is granted

### ISSUE THREAD

**Issue by andyblackwell** [prebid/Prebid.js#12482]
## Type of issue
MSPA Activity Control for GPP has invalid logic denying features when consent is granted

## Description
![image](https://github.com/user-attachments/assets/78b6daed-893a-4032-81aa-a4c697675648)

line in question: https://github.com/prebid/Prebid.js/blob/fe4a2cc660eae9bb30b596ca964baf2bc3b8cd33/libraries/mspa/activityControls.js#L24C5-L24C34

from the specs looks like this should be `cd.PersonalDataConsents === 1`, so it would only return true from `isBasicConsentDenied()` if "No Consent"

[Global-Privacy-Platform/Sections/US-National tech specs](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/32423f153fe2d0139289030a48d0d0a7ce5a756b/Sections/US-National/IAB%20Privacy%E2%80%99s%20Multi-State%20Privacy%20Agreement%20(MSPA)%20US%20National%20Technical%20Specification.md)

### Expected results
user syncs and user ids should not be restricted when consent granted

### Actual results
user syncs and user ids are restricted when consent granted

**Comment by dgirardi** [comment]
This is by [design](https://docs.prebid.org/features/mspa-usnat.html#commentary):

> // The CMP claims to have consent for an 'unrelated' activity.
> // Prebid views this as a logical impossibility and an invalid CMP response
> PersonalDataConsents=2

However, it looks like it might in fact be a possibility - we may need to reconsider.  What CMP are you using?

**Comment by andyblackwell** [comment]
OneTrust

**Comment by andyblackwell** [comment]
if I understand it correctly?? if the site pops a consent modal with the correct notices and the user grants consent, then PersonalDataConsents should equal 2 signaling consent was granted

from the prebid logic I linked to the value "2" doesn't seem to be considered in combination with any other signals when determined invalid, it's the second thing checked, all by itself.
the comment above this line alludes to some other assumptions, but I don't see any other checks done to verify whatever invalid state it's assuming.
> // you cannot consent to what you were not notified of
> cd.PersonalDataConsents === 2 ||

it also disregards if a 'no consent' signal was passed "1", but not sure how an explicit 'consent granted' signal was decided to mean 'consent denied' though, maybe just lost in the mess of all these confusing rules.

I'm definitely not an expert on GPP, but seems more like that line should be changed to reject only if `cd.PersonalDataConsents === 1`

**Comment by andyblackwell** [comment]
actually, looks like there is a discrepancy in the documents for this value, maybe that's the malfunction?

this one says this throughout: 1=yes consent, 2=no consent
https://www.iabprivacy.com/IAB%20MSPA%20Technical%20Signaling%20Implementation%20Guidelines%20v1.3%201.26.24.pdf
![image](https://github.com/user-attachments/assets/efc5be96-9d71-49c7-8428-e624b5393306)


but the docs in here all say the opposite: 1=no consent, 2=yes consent
https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/32423f153fe2d0139289030a48d0d0a7ce5a756b/Sections/US-National/IAB%20Privacy%E2%80%99s%20Multi-State%20Privacy%20Agreement%20(MSPA)%20US%20National%20Technical%20Specification.md
![image](https://github.com/user-attachments/assets/d64186cc-cb8a-4fee-897a-daa181270ff4)

**Comment by andyblackwell** [comment]
Ha sorry you're getting tripped up on my words, not asking you to change anything after you mentioned legal decision, but am highlighting the IAB docs have labeled the values backwards in one of those places, which likely led to my confusion on the value that was set in a consent response. It likely meant 2(no consent), but I read the (prob incorrect) docs that said 2=consent. I'll go file an issue over there pointing that out.

**Comment by patmmccann** [comment]
any chance you could flag at https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform as an issue?

**Comment by andyblackwell** [comment]
womp lol, when you google "mspa PersonalDataConsents" the first result is a link to an outdated legal doc on the iab website with the flipped values (thanks google), looks like the final legal doc does match the github tech docs.

am pretty sure at this point either OneTrust is doing something wrong, or the publisher has badly misconfigured their cmp settings. Either way, closing this ticket.

**Comment by andyblackwell** [comment]
ok, yeah it's OneTrust just casually putting a dropdown for this alongside other things that at the surface seem like you should enable, so will just have to be extra cautious with pubs using OneTrust.

**Comment by patmmccann** [comment]
@andyblackwell Onetrust product is aware of this thread, but hasnt sent me any more messages beyond acknowledging that
