### ISSUE TITLE
Prebid 1.0: pageOptions configuration object API implementation

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#1248]
https://gist.github.com/mkendall07/51ee5f6b9f2df01a89162cf6de7fe5b6#pageoptions-obj---new

**Comment by bretg** [comment]
We discussed this yesterday, and agreed that setConfig covers the need here. The page can pass each adapter parameters through setConfig, and adapters can read them with getConfig.

Example setConfig in the page:
``` javascript
pbjs.setConfig({myBidder: {
    accountId: 1234
 }
});
```
Each adapter that supports page-params would then use getConfig to look for them:
```javascript
   let pageParams=$$PREBID_GLOBAL$$.getConfig('myBidder');
   // if pageParams exists, incorporate them into bid requests
```
