### ISSUE TITLE
If prebid-server responses with status=no_cookie, all individual usersync pixels are ignored

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#1251]
## Type of issue
Bug

## Description
If user has no uuid2 cookie and also lacks uuids for some particular bidders, prebid server response has status no_cookie, but at the same time response includes user sync urls for individual bidders. This was implemented in the following PR https://github.com/prebid/prebid-server/pull/28
But pbjs just checks response.status field and if it's value is "no_cookie", it ignores all the usersync pixels. Sample of response below:
```
{
    "tid": "07b462dd-9a21-49fa-89f4-ade3b2d287c0",
    "status": "no_cookie",
    "bidder_status": [{
        "bidder": "rubicon",
        "no_cookie": true,
        "usersync": {
            "url": "https://pixel.rubiconproject.com/exchange/sync.php?p=prebid",
            "type": "redirect"
        }
    }]
}
```
The easiest way to fix this and https://github.com/prebid/Prebid.js/issues/1241 is to treat no_cookie status the same as ok status.

## Steps to reproduce
1) Erase all your cookies from adnxs.com or use incognito
2) Setup rubicon to work through prebid server
3) Request bids

### Expected results
Rubicon's usesync pixel is fired

### Actual results
Rubicon's usesync pixel is not fired until the next session

## Platform details
Prebid v 0.25-pre

## Other information
server-side functionality was changed in https://github.com/prebid/prebid-server/pull/28
similar to https://github.com/prebid/Prebid.js/issues/1241

**Comment by mkendall07** [comment]
This is resolved in master
