### ISSUE TITLE
Incorrect bidRequestsCount for bids with Twin AdUnits.

### ISSUE THREAD

**Issue by Pratik733** [prebid/Prebid.js#12522]
## Type of issue

Bug

## Description

[`bidRequestsCount`](https://github.com/prebid/Prebid.js/blob/4ae7e1b92364f116fd1f3829582e8bf921526858/src/adapterManager.js#L111) shows incorrect count when a [Twin-Adunit](https://docs.prebid.org/dev-docs/adunit-reference.html#twin-adunit-codes) is mapped. This happens when a bidder receives multiple bids with same adUnitCode within an single auction.

## Test page

Js fiddle Links :-

1. Twin Adunit - https://jsfiddle.net/wavy6t3x/
2. Normal Adunit - https://jsfiddle.net/ojq0fx3e/ Use the following code in console to get "bidRequested" event

```js
console.table(window.pbjs.getEvents()
    .filter((ev) => ev.eventType === "bidRequested")
    .map(e => e.args.bids).flat()
    .map(({bidder, bidRequestsCount}) => ({bidder, bidRequestsCount})))
```

## Results

| bidder | normal adunit bidRequestCount | twin adunit bidRequestCount |
|--------|-------------------------------|-----------------------------|
| appnexus | 1 | 3 |
| medianet | 1 | 3 |
| ix | 1 | 3 |

### Expected results

- The `bidRequestsCount` for each unique bid Object should be `1` for first Auction. If there are multiple bid Object even though they contain same adUnitCode, each should have its own counter reflecting the appropriate `bidRequestsCount`.

### Actual results

- The `bidRequestsCount` value is seen to be `3` for all bids.

### Proposal

1. **Unique Identification for Each AdUnit (Even with Shared AdUnitCode):**
   - Each adunit Code's auction count should be incremented only once for every GAM refresh() irrespective of the twinAdunits it might have.
2. **Rename `bidRequestsCount` to `adUnitAuctionCount`:**
   - The metric `bidRequestsCount` currently gives impression that it is a counter for number of bid request invocations for a given adUnit.
   - If the metric is intended to track auction participation rather than individual bid requests, renaming it to `adUnitAuctionCount` would improve clarity.

**Comment by patmmccann** [comment]
Unclear if this is a bug, https://github.com/prebid/Prebid.js/pull/4448 calls it the number of requests and IX and sharethrough and Yahoo all have the ability to have multiple requests with different placements on an ad unit, without the need to even have twins. 

Perhaps a third option, expose a new metric with a new name meeting your proposal item 1 definition: "Each adunit Code's auction count should be incremented only once for every GAM refresh() irrespective of the twinAdunits it might have."

The problem is this ties us to gam, so perhaps requestBids

**Comment by dgirardi** [comment]
>  "Each adunit Code's auction count should be incremented only once for every GAM refresh() irrespective of the twinAdunits it might have."

I'm not sure we can do this reliably without asking publishers some other identifier to distinguish twins of an ad unit. The second auction could have the same ad unit appear with a different set of twins.

**Comment by Pratik733** [comment]
@patmmccann @dgirardi  
We, at Media.net raised this change (PR #2940) a while back, assuming the bidRequestCounter for an adUnit serves as the auctionCounter. We missed considering the twin adUnit cases, which are now leading to the erroneous scenarios mentioned above in the issue. Original idea was to increment the auction count regardless of any twin adUnits it might have.

**Comment by patmmccann** [comment]
We're not sure if anyone relies on the current definition, marking ready for dev to implement a new metric with the proposed definition

**Comment by Pratik733** [comment]
@patmmccann 
Should we go ahead and raise a PR implementing a new metric i.e auctionCount at slot level?

**Comment by patmmccann** [comment]
Please do, also please document both and attach to your pr. Thank you! 🎉
