### ISSUE TITLE
TCF2 denied 'fetchBids' for 'bidder'

### ISSUE THREAD

**Issue by AnniAdops** [prebid/Prebid.js#12534]
I am not sure if these warnings we get in the debug https://borsen.dk/?pbjs_debug=true is mere warnings or do they actually effect the stop of sending bid request to the bidder as being the error.

TCF2 denied 'fetchBids' for 'bidder.omgzero' 

and 

WARNING: Alias 'omgzero' will NOT re-use the GVL ID of the original adapter ('adform', gvlid: 50). Functionality that requires TCF consent may not work as expected.

We seem to have an issue with an alias bidder and error is we stopped sending bidrequest to the bidder. 

I can see there is a few prior cases to this TCF2 denied 'fetchBids' for 'bidder' but i am not sure what the solution is to fix it? 

We run prebid version: Prebid.js v9.16.0 and that was updated a month ago, but issue with not sending any bid request forbidder OMGZero started nov. 26-27.

**Comment by AnniAdops** [comment]
Hi and thanks a lot - 

There hasnt been any changes in the CMP which is the odd part. 
I saw the newest version of prebid was released on now 27., but as i wrote we havent updated the version from Prebid.js v9.16.0 which was done in october. 

As far as i know we have the aliasBidder in place, but it seems that is not working anymore for OMGZero (OMGZero is the same entity for purposes as Adform ), but i am not sure if the script needs to be changed somehow: 
 
pbjs.que.push(function () {
        
        pbjs.aliasBidder("adform", "omgzero");
        
 
        pbjs.addAdUnits(adUnitConfigs);
        pbjs.setConfig(getConfig());
 
        pbjs.setBidderConfig({
            "bidders": ['omgzero'],
            "config": {
                "schain": {
                    "validation": "relaxed",
                    "config": {
                        "ver": "1.0",
                        "complete": 1,
                        "nodes": [
                            {
                                "asi": "adform.com",
                                "sid": "1737",
                                "hp": 1
                            }
                        ]
                    }
                }
            }
        });
 
Do you think it would help if we rolled back to a prior version of Prebid?

**Comment by AnniAdops** [comment]
Do you think we can add 

  reuse_gvl_id: true

to make it work?

pbjs.aliasBidder("adform", "omgzero", {reuse_gvl_id: true});

**Comment by dgirardi** [comment]
The option is called `useBaseGvlid`. Please refer to the [documentation](https://docs.prebid.org/dev-docs/publisher-api-reference/aliasBidder.html).

**Comment by patmmccann** [comment]
try `pbjs.aliasBidder("adform", "omgzero",  {useBaseGvlid: true});`
