### ISSUE TITLE
DFP : vconp & vpa managing playback methods ?

### ISSUE THREAD

**Issue by GuillQuirin** [prebid/Prebid.js#12562]
Hello

Google recommends us to set the "vconp" & "vpa" param in the adrequest in order to improve the video monetization, I can see [in the code](https://github.com/prebid/Prebid.js/blob/39e6418bb05501dbe1180bda44865c6b0ba938f2/modules/dfpAdServerVideo.js#L136) they depends on the playback method.

However I'm wondering how to [declare the playback method](https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/main/AdCOM%20v1.0%20FINAL.md#list--playback-methods-) when the player initiates as usual, and then, keep playing its playlist (ie : value 1 + 7).

Is it impossible to declare these 2 parameters together ?

Thank you

**Comment by patmmccann** [comment]
If you set 1,7 as an array for mediaTypes.video.playbackmethod and we set vconp based on presense on 7 in the array, does that solve? 
![image](https://github.com/user-attachments/assets/a0a1b29e-3825-48f9-91f5-1a826695a2e0)

**Comment by dgirardi** [comment]
As a workaround, You can set those parameters directly using the [`params` option of buildVideoUrl](https://docs.prebid.org/dev-docs/publisher-api-reference/adServers.dfp.buildVideoUrl.html). For example, 

```
pbjs.adServers.dfp.buildVideoUrl({
    // ...
    params: {
        vconp: '2',
        vpa: 'auto'
    }
});
```
