### ISSUE TITLE
Do Appnexus Alias Bidders work with S2S yet ? 

### ISSUE THREAD

**Issue by chefbenjamin** [prebid/Prebid.js#1261]
General enquiry to see if Appnexus Alias Bidders work with S2S yet? ie Defy or brealtime for example. 
If so any quirks or things we need to think about here when deploying or testing ? 

Can they use the same line items as client side ?

**Comment by dmitriyshashkin** [comment]
Only districtm works ATM. Same LI's can be used, the only problem I found so far is that if your Appnexus LI or campaign is targeted by query string, or by a segment that is tied to query string, then the targeting won't work.

**Comment by aneuway2** [comment]
FYI, the list of Prebid Server adaptors are listed here: https://github.com/prebid/prebid-server/blob/0d092cd76eb721896938eb217dd2fab96b4fd73c/pbs_light.go#L398
