### ISSUE TITLE
Dynamic "prebid.org/download.html" Page suggestion.

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#1262]
on - prebid.org/download.html why not make a drop down to choose which version to compile then automate it so when you push to git users can instantly compile new version from the download page, and display a notice msg for people testing new releases.

**Comment by mkendall07** [comment]
We should be able to build this out sometime in the future. Stay tuned. Thanks

**Comment by mkendall07** [comment]
this is out now.
