### ISSUE TITLE
Infinite Scroll - Ads loading on scroll

### ISSUE THREAD

**Issue by caroline723** [prebid/Prebid.js#1266]
This is a question on how to implement Prebid on a site that loads ad units as a user scrolls. 

In this case the page in question loads the top three ads first, then the next three further down and so on. The ads will also refresh if a user were to scroll back up. There are a total of 4 groups of three ad units that load at different intervals on the page. 

Does anyone know what we need to add to the Prebid code to make this work? Will this example work for the described issue: http://prebid.org/dev-docs/examples/adunit-refresh.html

If so can someone shed some light on how to implement? The example doesn't seem to fit since the ads aren't refreshing but load are different GPT ad units that load at different times. I almost feel as if the Prebid code needs to be copied for each "group" of ads.

**Comment by bretg** [comment]
For a dynamic div, the only trick is to call requestBids with just the AdUnit codes that need to be run. e.g.

```
    function dynamicDiv() {
        // dynamically create div
        var newDiv = document.createElement("div");
        newDiv.id="div-prebid-test-slot-2";
        document.body.appendChild(newDiv);

        googletag.cmd.push(function () {
          bottomSlot = googletag.defineSlot('YOUR_SLOT_ID', [[300, 250]], 'div-prebid-test-slot-2').addService(googletag.pubads());

          googletag.pubads().enableSingleRequest();
          googletag.enableServices();
        });
       pbjs.que.push(function () {
         var adUnit2 = [{
                      [... your adunit here...]
                }]
             }];

        pbjs.addAdUnits(adUnit2);   // won't be called except on button press
        pbjs.enableSendAllBids();

        pbjs.requestBids({
            bidsBackHandler: function (bidResponses) {
                initAdserver();
            },
            adUnitCodes: ['div-prebid-test-slot-2']  // the magic -- run the auction only for the new div
        });
        // Load GPT when timeout is reached.
        setTimeout(initAdserver, PREBID_TIMEOUT);
   });
  }
```

**Comment by priyankabehera** [comment]
Hello, I am implementing infinite scroll and on each scroll, 10 more items and 2 ad slots are loading with the same ad name. 
All the div are generating dynamically.
For, this if I am using the below code which was provided above then no bid is passing successfully.

dynamic div: div-prebid-test-slot-2

```
pbjs.requestBids({
            bidsBackHandler: function (bidResponses) {
                initAdserver();
            },
            adUnitCodes: ['div-prebid-test-slot-2']  // the magic -- run the auction only for the new div
        });
```
In my case dynamic div : div-gpt-ad-div' + timeStamp
If I am passing the codeName the bids are passing successfully but when we again load more next time it doesn't point to new dynamic ad.

```
pbjs.requestBids({
                                    bidsBackHandler: function( bidResponses )
                                    {
                                        googletag.cmd.push( function()
                                        {
                                            pbjs.setTargetingForGPTAsync( ['/121/Homepage/HP_Refresh'] );
                                          
                                        });
                                    },
                                    timeout: 3000,
                                    adUnitCodes: ['/121/Homepage/HP_Refresh'],
                                    //adUnitCodes: ['div-gpt-ad-div' + timeStamp],
                                });
```

Thank you in advance.
