### ISSUE TITLE
integrationExamples/gpt/creative_rendering example will not work with unfriendly frame

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#1268]
## Type of issue
Bug

## Description
This page gives a recommendation on how to traverse through frames until parent window is found
https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/creative_rendering.html

But if one of the frames in the chain is not friendly (different domain, for example) `if (w.$$PREBID_GLOBAL$$)` will result in exception. I would recommend placing this if inside the try block.

**Comment by mkendall07** [comment]
it's not meant to serve into an unfriendly iframe. If that's the desired behavior, use the creative found here https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/x-domain/creative.html
