### ISSUE TITLE
Troubleshooting DFP line items against prebid

### ISSUE THREAD

**Issue by veeba** [prebid/Prebid.js#127]
Can somebody check and help me with this: http://sport.ba/theme/Sport/te/prebid.html

I created prebid, in DFP i created line-items with range from 0.1 to 1.5. 
On that ad-unit I also add Network line-item (Example of 300x250) to shows if no sales.

This errorr is showing in console: 
Uncaught ReferenceError: require is not defined(anonymous function) @ prebid.js:6

I cannot see any console.log about bidding?

**Comment by ialex** [comment]
The prebid.js file looks wrong to me, you need to build it by downloading this repo and executing 
    gulp build
you will have prebid build in dist/ copy that file to your site and follow the example to setup Prebid.

**Comment by veeba** [comment]
Thanks. I fixed that - http://sport.ba/theme/Sport/te/prebid.html

**Comment by mkendall07** [comment]
Thanks for helping out @ialex 

Btw you can download the compiled code from the release page directly https://github.com/prebid/Prebid.js/releases/download/0.4.1/Prebid.js_0.4.1.zip

**Comment by mkendall07** [comment]
@veeba 

You can add `pbjs_debug=true` to the query to view output from prebid.js
http://sport.ba/theme/Sport/te/prebid.html?pbjs_debug=true

I see you have 1 bidder (rubicon) but no bid responses. Maybe try increasing the timeout?

**Comment by veeba** [comment]
Increased :)

**Comment by mkendall07** [comment]
Cool, you got a bid! Now you just need to create a matching line item in DFP for that keyword target

![image](https://cloud.githubusercontent.com/assets/1870166/11594383/ae1541c0-9a77-11e5-91e9-0126d167d4d6.png)

**Comment by veeba** [comment]
How to do that?

**Comment by mkendall07** [comment]
@veeba  check out http://prebid.org/adops/step-by-step.html for detailed instructions

**Comment by veeba** [comment]
I did all of that, but with line-items 0.1, 0.2, 0.5, 0.7, 1 and 1.5

**Comment by mkendall07** [comment]
probably need to create higher buckets for CPMs. The bid I received was for $3.00, so you need to create higher value line items. Also you can create a line item for CPM > x for a catch all

**Comment by veeba** [comment]
I created, and tested. For ex. there is 3.00 line-item, and if bid is 3.00 nothing happened (it passback ad). I expect to see real ad, why is that not happening?

**Comment by veeba** [comment]
Can somebody help me. I created line-items but if bid is for ex. 3.00 that line-item is not called? Why?

**Comment by mkendall07** [comment]
Everything on your page looks good. I think you have an issue on your DFP setup. Make sure all the line items  have the proper priorities. 

Also - you can also hardcode targeting to ensure your line items are being targeting correctly: 
`googletag.defineSlot(topSlotCode, topSlotSizes, 'div-gpt-ad').setTargeting("hb_pb", "3.00").addService(googletag.pubads());

**Comment by prebid** [comment]
congrats @veeba your page looks like it's working now with rubicon running! Anything else we can help with?

**Comment by veeba** [comment]
Thanks :)
My next step is start prebid for Sync DFP tags :+1:

**Comment by veeba** [comment]
@prebid  @mkendall07 @ialex 
One more question :)
Can somebody explain how can I find details "nid" and "cookiename" in Criteo, also "jstag_url", "pgid" and "unit" in OpenX. Where can I find that (from tag or somewhere from platfroms?). 
Thanks again

**Comment by BartVB** [comment]
Answered here: https://github.com/prebid/Prebid.js/issues/135

**Comment by prebid** [comment]
Thanks @BartVB! Really appreciate the help!
