### ISSUE TITLE
Remove casale.js for clarity

### ISSUE THREAD

**Issue by headertag** [prebid/Prebid.js#128]
Hello team! Now that indexExchange.js is finalized can you remove casale.js for clarity?

https://github.com/prebid/Prebid.js/blob/master/src/adapters/casale.js

Thanks!

**Comment by mkendall07** [comment]
Done, thanks @headertag

**Comment by prebid** [comment]
What should be the correct params at:
http://prebid.org/dev-docs/bidders.html#casale-index

**Comment by headertag** [comment]
@prebid please advise if the following details are sufficient to update the bidders page.

name: siteID
scope: required
description: the default site if for all slots
example: 123456

name: tier2SiteID
scope: optional
description: the default tier 2 site id for all slots, will create a tier 2 slot for all slots
example: 123457

name: tier3SiteID
scope: optional
description: the default tier 3 site id for all slots, will create a tier 3 slot for all slots
example: 123458

name: sqps
scope: optional
description: sqps object defining the sqps slot information
example: {width: 728, height: 90, siteID: 123456}



bid.params:
These values are in the normal params key, they define per slot values.

name: id
scope: required
description: the slot id
example: '1'

name: siteID
scope: optional
description: The site id for this slot
example: 123456

name: tier2SiteID
scope: optional
description: The tier 2 site id for this slot
example: 123457

name: tier3SiteID
scope:optional
description: The tier 3 site id for this slot
example: 123458

**Comment by prebid** [comment]
@mkendall07 the params do not comply to our convention - take a look at the example at https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/pbjs_example_gpt.html

```
{
       bidder: 'indexExchange',
       siteID: 'TO ADD',
       timeout: 'TO ADD',
       params: {
              id: 'TO ADD',
       }
}
```
The `siteID` and `timeout` and other parameters outside of `params` should really be inside. Do you mind make that quick update? This is urgent as we do not want to make breaking changes for index's adaptor.

Thanks!

**Comment by headertag** [comment]
Fixed in https://github.com/prebid/Prebid.js/pull/139

**Comment by mkendall07** [comment]
Thanks @headertag  for the fix. I've merged now. 

@prebid we need to update prebid.org - https://github.com/prebid/prebid.github.io/issues/7
