### ISSUE TITLE
publish to NPM ? 

### ISSUE THREAD

**Issue by avifoxi** [prebid/Prebid.js#129]
I would like to include this in my project via npm, but don't want to steal anyone's thunder by publishing a library I haven't contributed to.

Any plans to publish there ? 

Tnx!

**Comment by mkendall07** [comment]
Hi @avifoxi 

We will be publishing to NPM on the next release. Thanks for the request.

**Comment by avifoxi** [comment]
@mkendall07 great - looking forward

**Comment by mkendall07** [comment]
Published - https://www.npmjs.com/package/prebid.js
