### ISSUE TITLE
SafeFrames Bug

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#1291]
So im loading safeFrame from a http:// page im randomly getting this error:

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://tpc.googlesyndication.com') does not match the recipient window's origin ('https://tpc.googlesyndication.com').
a @ pb0088.js:2
o @ pb0088.js:2

What happens is some ads do load in safeFrame but some give a blank ad due to some kind of issue inforcing https://tpc.googlesyndication.com even tho i'v set the safeFrame creatives to 

<script>
var urlParser = document.createElement('a');
urlParser.href = '%%PATTERN:url%%';
var publisherDomain = urlParser.protocol + '//' + urlParser.hostname;
var adServerDomain = urlParser.protocol + '//tpc.googlesyndication.com';
function renderAd(ev) {
    var key = ev.message ? 'message' : 'data';
    var adObject = {};
    try {
      adObject = JSON.parse(ev[key]);
    } catch (e) {
      retur

......

**Comment by cwbeck** [comment]
@mercuryyy how are you getting on with SafeFrames? What are you using to implement them?

**Comment by ialex** [comment]
Can you share the creative make sure that the google syndication url uses https

**Comment by mercuryyy** [comment]
@cwbeck im using DFP 

the creative is  the regular prebid safeframes creative - https://github.com/prebid/Prebid.js/tree/master/integrationExamples/gpt/x-domain

**Comment by cwbeck** [comment]
@mercuryyy ok thanks. When using DFP's safe frame alongside Prebid are there any major issues you have encountered? any demand issues as third parties verification tools spot it's a safe frame?

**Comment by lanceloti** [comment]
Hi @mercuryyy. In DFP creative settings you've checked "SSL compatible" as yes? And are you using only one creative associated on all line items?

**Comment by mercuryyy** [comment]
@cwbeck  @lanceloti  So there are some demand issues but nothing major. In dfp creative setting i actually set SSL Compatible to auto detect from the default "yes" because my pages are not SSL it caused some issues. 

I'd really hope more people try to use safeFrames so we can get more data.

**Comment by cwbeck** [comment]
@mercuryyy thanks. We are implementing this now (outside of dfp), so hopefully we'll get some data on this.

**Comment by mercuryyy** [comment]
@cwbeck Any news on this?

**Comment by mkendall07** [comment]
@mercuryyy are you still seeing this error? It's possible DFP is testing forcing HTTPS request even on HTTP pages. Unfortunately I'm not sure if we can detect when they switch it.
