### ISSUE TITLE
bidmanager times out before saving last bid

### ISSUE THREAD

**Issue by kitwestneat** [prebid/Prebid.js#1298]
## Type of issue
bug

## Description
When prebid receives a bid after the timeout, it executes the callbacks before saving the bid. This has the effect of ignoring the bid for those who rely on callbacks.

## Steps to reproduce
It's easy to reproduce if you put a breakpoint right before the responseTimestamp is set. 

### Expected results
All bids, including the one that triggered the timeout, are added to bids received when the callbacks are called. 

### Actual results
The last bid is ignored.

**Comment by mkendall07** [comment]
@kitwestneat we will fix this as part of prebid 1.0
