### ISSUE TITLE
Aardvark adapter depends on port

### ISSUE THREAD

**Issue by dbemiller** [prebid/Prebid.js#1300]
The unit tests for the Aardvark adapter check URL equality with `rtkreferer=localhost:9876`.

This couples the unit tests to the context in which they're running.... and it's especially fragile here because karma will choose different ports if that one's in use.

These tests are making the prebid validation & release process more painful, and need to be fixed.

**Comment by dbemiller** [comment]
@dejanstrbac you're the most recent official contributor on this adapter... could you or someone from your company look into this?

**Comment by matthewlane** [comment]
Closing as the aardvark adapter and test aren't in 1.x. Will make sure ports aren't in newly submitted tests
