### ISSUE TITLE
Fragile test fails in prebid-core on IE11

### ISSUE THREAD

**Issue by dbemiller** [prebid/Prebid.js#1302]
## Type of issue
Bug

## Description
A test is failing on IE11, Windows 8.1.

Computers can't habitually ignore errors like humans can. Failures like these prevent us from automating the release validation process.

## Steps to reproduce
Run `gulp test --browserstack` with the `bs_ie_11_windows_8.1` browser active.

### Expected results
The tests should pass reliably.

### Actual results
I see the following failure:

```
IE 11.0.0 (Windows 8.1 0.0.0) Unit: Prebid Module video adserverTag should return original adservertag if there are no bids for the given placement code FAILED
	expected 'https://pubads.g.doubleclick.net:443/gampad/ads?sz=640x480&iu=/19968336/header-bid-tag-0&impl=s&gdfp_req=1&env=vp&output=xml_vast2&unviewed_position_start=1&url=www.test.com' to equal 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/19968336/header-bid-tag-0&impl=s&gdfp_req=1&env=vp&output=xml_vast2&unviewed_position_start=1&url=www.test.com'
	Error
	   at AssertionError (/Users/dbemiller/code/Prebid.js/test/spec/unit/pbjs_api_spec.js:1917:8)
	   at assert (/Users/dbemiller/code/Prebid.js/test/spec/unit/pbjs_api_spec.js:6249:8)
	   at assertEqual (/Users/dbemiller/code/Prebid.js/test/spec/unit/pbjs_api_spec.js:6766:8)
	   at Anonymous function (/Users/dbemiller/code/Prebid.js/test/spec/unit/pbjs_api_spec.js:5836:6)
	   at Anonymous function (/Users/dbemiller/code/Prebid.js/test/spec/unit/pbjs_api_spec.js:1556:8)
```

## Platform details
Windows 8.1, Browser IE11

**Comment by mkendall07** [comment]
this should be relatively easy to fix I think. Looks like the secure port is being dropped in IE but not in other browsers.

**Comment by matthewlane** [comment]
In my testing it seems to be the opposite? From this https://github.com/prebid/Prebid.js/blob/000e4532bda25ae25228a352b5d30364c158a4a9/src/url.js#L29
IE 11 returns a port of 443, Chrome and other browsers don't return anything, when checked with `gulp test --browserstack`. I'm not sure why this happens
