### ISSUE TITLE
AppnexusAST ends refresh auctions prematurely when trying to handle error

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#1304]
## Type of issue
Bug

## Description
When AST executes callBids it saves request in `bidRequests` array. Bid requests accumulate upon subsequent callBids calls. So during refresh auction bidRequests holds requests from all previous auctions. If the server responds with an error, handleResponse method issues a response for every request logged in `bidRequests` array. And as bidRequests has requests from previous auctions, it produces too many responses. Which makes bid manager think that all bidders have sent responses even when they haven't. Auction ends prematurely which results in the revenue drop: we've seen almost 50% drop in our refresh revenues.

The easiest way to fix this is to clear `bidRequests` array in the beginning of `callBids` method.

## Steps to reproduce
1) Create test page with two bidders. First one uses AST adapter, the second one must have a delayed response or do not issue a bid response at all. AST one must have erroneous settings, so each request should result in an error.
2) Add a significant timeout (eg 10 seconds)
3) Refresh ads every n minutes, wait for the second iteration

### Expected results
The second auction ends after 10 seconds through the timeout mechanism

### Actual results
The second auction ends after AST receives an erroneous response

**Comment by mkendall07** [comment]
Thanks for the bug report! Will look into this ASAP
