### ISSUE TITLE
API for bidder parameters

### ISSUE THREAD

**Issue by kcramu** [prebid/Prebid.js#1309]
## Question

Please suggest how to programmatically pull all bidder parameters?

## Description

As a SSP, I want to programmatically add new bidders for my publishers. I want to know if Prebid.js provides an API to pull the list of bidders and bidder parameters.

**Comment by mkendall07** [comment]
Currently no, although this is a great idea!

**Comment by aneuway2** [comment]
Hey @kcramu wile there isnt an API, doesn't `pbjs.adUnits` give you want you need? That object has the list of bidders and parameters that PBJS uses to run the auction

**Comment by iamcarrico** [comment]
I, too, would like this. 

My personal use case, is that we build the configuration on the frontend depending on what is available on that page. Would love to be able to get the list of required and optional params from a partner— to see if we actually have that config available. 

Some sample code that is kinda what I am going for— 

```js
var bids = [];
var bidders = ["appnexus"];

Object.keys(bidders).forEach(bidder => {
  var params = {};
  var allParams = true;
  var bidderParams = prebidInfoforSlot[bidder] || {};
  var defaultBidderParams = prebidSettings.defaultConfig[bidder] || {};

  // Allow us to disable a single slot or partner by configuration.
  if (bidderParams.disabled || defaultBidderParams.disabled) { return; }

  pbjs.bidderParams(bidder).forEach(function(param) {
    var value = bidderParams[param] || false;

    if (!value) {
      value = defaultBidderParams[param] || false;
    }

    if (!value) {
      allParams = false;
    } else {
      params[param] = value;
    }
  });

  if (!allParams) { return; }

  bids.push({ bidder, params });
});
```

Where I have the variable `prebidInfoforSlot` set to all the prebid information I know about that slot, and we go into all the params to get everything we need for that bid. If all required params exist, then we will add it to the `bids` variable. 

I dont have on here the difference between required and optional— but I think the general gist is here.
