### ISSUE TITLE
No ad impressions recorded

### ISSUE THREAD

**Issue by lakexyde** [prebid/Prebid.js#1314]
## Type of issue

Question
## Description

I recently setup Prebid on my site following the examples on the website. I currently have two bidders (pulsepoint & underdogmedia) in place. In my Roxot panel, I can see Ad requests being sent but no ad impressions are recorded. Underdog media mentioned something about using version 0.20so the setup can work as expected.

Please I need your help in getting this to work
### Expected results
Ad requests and impressions recorded
### Actual results
Ad impressions not recorded
## Platform details

0.24.1

**Comment by mkendall07** [comment]
@lakexyde if you are using a Roxot product please contact them for support. Thanks
