### ISSUE TITLE
Post Prebid Implementation we see 50% discrepancy with respect to ad request numbers.

### ISSUE THREAD

**Issue by jamesfebin** [prebid/Prebid.js#1317]
We used to get 100K ad requests a day on DFP. Post Prebid implementation we are only receiving 50K ad requests a day now. We verified by creating a 1 pixel ad unit. Still a 50% discrepancy. Any one knows what's going on?

**Comment by mkendall07** [comment]
Can you provide more details please? Version of prebid, when did this start occurring, any changes to the setup. Are you using SafeFrame etc.

**Comment by jamesfebin** [comment]
Our prebid version is v0.24.1 . Since we implemented header bidding we have this issue. We are using a friendly iframe. No, we are not using safeframe.

**Comment by mkendall07** [comment]
ok that's helpful. Can you describe how you are measuring things? Your saying that a creative (postbid) setup in DFP caused the number of DFP requests to get cut in half? Doesn't really make sense to me.
