### ISSUE TITLE
districtmDMX Uncaught TypeError: Cannot read property 'auction' of undefined

### ISSUE THREAD

**Issue by nanek** [prebid/Prebid.js#1323]
## Type of issue
Bug

## Description
districtmDMX Uncaught TypeError: Cannot read property 'auction' of undefined from L40 in the adapter.

https://github.com/prebid/Prebid.js/blob/fd7ae19b65da98599590914ee310157c66dd6780/src/adapters/districtmDMX.js#L40

## Steps to reproduce
I'm not able to reproduce, however I log high occurrences from our error logging each day.

### Expected results

No errors thrown.

## Platform details
Prebid 0.23

## Other information
`window.hb_dmx_res` likely exists, but for some reason `window.hb_dmx_res.auction` does not.

**Comment by mkendall07** [comment]
@stevealliance was the most recent commiter on this file. Please add a check for this into the adapter. Thanks.

**Comment by stevealliance** [comment]
@nanek sorry for the late response this notification was on my spam box do you still have a problem with our library?

**Comment by nanek** [comment]
I wrapped it in a try/catch to silence the error. I expect it still occurs.

**Comment by stevealliance** [comment]
Please can you give me your URL?

Thanks

**Comment by mkendall07** [comment]
closing this out as no response was given on this issue.
