### ISSUE TITLE
Timeout workflow in dfp integration examples

### ISSUE THREAD

**Issue by Niksok** [prebid/Prebid.js#1329]
## Question
Hello,

in API you have timeout parameter available in method pbjs.requestBids. It is described here: http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.requestBids.

But in DFP integration examples this parameter isn't used at all, the global timeout used instead. Here is the example I am referring to: http://prebid.org/dev-docs/examples/basic-example.html.

It looks like inside the specific adaptor work cycle there is no possibility to understand that prebid work is interrupted by timeout. Could you please let us know how can we catch (within the adaptor work cycle) the situation that timeout is fired?

Thanks in advance,

**Comment by mkendall07** [comment]
What's the use case for the adapter knowing that the timeout occurred?

**Comment by Niksok** [comment]
We need to collect and send adapter statistics.
