### ISSUE TITLE
Gulp serve doesn't rebuild bundle

### ISSUE THREAD

**Issue by dbemiller** [prebid/Prebid.js#1334]
## Type of issue
Bug

## Description
`gulp serve` doesn't rebuild the bundle when javascript changes.

## Steps to reproduce
Run `gulp serve`. Then change something in any file.

## Other information
I fixed a bug like this in #1276... but I think it was reintroduced in #1177. The build commands shifted around a bit, but I'd bet the root cause is probably something similar.

**Comment by matthewlane** [comment]
Fixed in master
