### ISSUE TITLE
events.js: Error executing handler: TypeError: Cannot read property 'appnexus' of undefined

### ISSUE THREAD

**Issue by salvoaranzulla** [prebid/Prebid.js#134]
Hi,

I'm receiving this error in my dev server:

![screenshot 2015-12-09 19 08 49](https://cloud.githubusercontent.com/assets/5984607/11694103/84e3b3c4-9ea8-11e5-999a-b01a656f234e.png)

To solve, I have changed 

Before:	if(code && pbjs.bidderSettings[code]){
After: 	if(code && pbjs.bidderSettings && pbjs.bidderSettings[code]){

in bidmanager.js

What do you think?

**Comment by mkendall07** [comment]
Thanks for the bug report @salvoaranzulla 

Added the fix.
