### ISSUE TITLE
$PREBID_GLOBAL$$ not respected in some Adapters

### ISSUE THREAD

**Issue by stefanosaittamrf** [prebid/Prebid.js#1340]
## Type of issue
Bug

## Description
The following Adapters are not respecting the global naming convention, but they hardcode the `pbjs` variable instead.

- [eplanningBidAdapter.js](https://github.com/prebid/Prebid.js/blob/master/modules/eplanningBidAdapter.js)
- [jcmBidAdapter.js](https://github.com/prebid/Prebid.js/blame/master/modules/jcmBidAdapter.js)  

## Steps to reproduce
- Open the files linked before [eplanningBidAdapter.js:241](https://github.com/prebid/Prebid.js/blob/master/modules/eplanningBidAdapter.js#L241) & [jcmBidAdapter.js:8](https://github.com/prebid/Prebid.js/blob/master/modules/jcmBidAdapter.js#L8)

### Expected results

I expect to don't have any `pbjs` hardcoded value into the final bundle

### Actual results
I can see the variable, this will make the adapter fails if the global name is different from the defualt, plus it will eventually fail on avoid conflicts for multiple loads of prebid.js (3rd party)

## Platform details
All

## Other information
None

**Comment by jaiminpanchal27** [comment]
Tagging official contributors of both the adapters.
@sebaperez and @JCarterGw submit a PR with this fix. Thanks

**Comment by dbemiller** [comment]
I looked into this.

The JCM adapter is using JSONP, but it looks like their server's response assumes that `pbjs` is the global var.

If it's important to you, you'll either have to get a hold of @JCarterGw or talk to them directly... there's nothing that can be done from our end.

**Comment by mkendall07** [comment]
The adapters should follow the standards of using the macro for `pbjs` global. If this fails at runtime, it's an issue on the adapter's endpoint and should be resolved there.

**Comment by dbemiller** [comment]
Yes. In the case of JCM, that's what needs to happen. @JCarterGw doesn't seem to be paying attention though anymore.
