### ISSUE TITLE
Index ignores unsupported sizes, bid manager still expects bid response

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#1341]
## Type of issue
Bug

## Description
`bidsBackAll` method in `bidmanager` compares the number of requests with the number of responses. As indexExchange issues a response for every size in the ad unit, bidsBackAll counts all the sizes to determine the number of requests. But if some size is not supported by indexExchange, it will be ignored inside the adapter and there won't be any response for this size. So the number of requests will always exceed the number of responses. Which means that the only condition on which the auction ends is the timeout.

Not sure what's the best way to fix that. As a temporary measure, I've modified the `bidmanager` to count only those sizes that are supported by Index Exchange. But I had to copy the list of supported sizes to `bidmanager` and it doesn't seem to be a good practice. But if it's ok, I can submit my fix as a PR.

## Steps to reproduce
1. Set up an ad unit with two sizes: [300, 250] and [300, 610]
2. Add indexExchange as the only bidder to this ad unit
3. Setup a lengthy timeout, say, 10 seconds
4. Request the bids

### Expected results
Auction ends as soon as response from indexExchange is received

### Actual results
Auction ends only after 10 seconds

## Platform details
prebid v 0.25

**Comment by ptomasroos** [comment]
There is some custom code for this already in here, can probably be fixed in a similar way? https://github.com/prebid/Prebid.js/blob/fd7ae19b65da98599590914ee310157c66dd6780/src/bidmanager.js#L52-L71

**Comment by mkendall07** [comment]
@indexexchange should adjust their adapter to send bid responses back so we can get rid of the workaround in that bit of the code.

**Comment by michaelharris2** [comment]
Hi.  We're looking into this and will have a fix out shortly.

**Comment by mkendall07** [comment]
Since this is fixed, we need to drop this https://github.com/prebid/Prebid.js/blob/master/src/bidmanager.js#L52 now
