### ISSUE TITLE
Can't add new module

### ISSUE THREAD

**Issue by chensMMG** [prebid/Prebid.js#1344]
I have some issues changing the code to the new version.
I have performed the following steps:

1. Open new file under modules folder with the name "marsmediaBidAdapter".
2. Open new file under modules folder with the name "marsmediaAnalyticsAdapter".
3. Open new file under test\spec\modules folder with the name "marsmediaBidAdapter_spec".
4. Copy all adapters logic from the old version to the new ones  ( mentioned above ) with some path changes.
5. Running the command "gulp serve".

After running, I took the "prebid.js" file from the folder build\dev and put it in my test file (the same one that worked fine in version 0.25).
When I loaded the test page, it seems that no adapter is loaded.

Then I tried to run the command "gulp serve --modules=marsmediaBidAdapter" and got this error:
"Message: invalid modules: marsmediaBidAdapter"

Why all of the adapters don't load?

**Comment by dbemiller** [comment]
If you search the `build/dev/prebid.js` file for your `marsmediaBidAdapter` source code, is it in there?

"My code doesn't appear in the bundle" and "the adapter in my code doesn't get registered" are two very different problems.

**Comment by chensMMG** [comment]
I have found the slution in another issue, just need to replace the next line in gulpHelpers file:
`var moduleName = file.split(new RegExp('[.' + path.sep + ']'))[0];`

to:
`var moduleName = file.split(new RegExp('[.\\' + path.sep + ']'))[0];`

@dbemiller My adapter is working just not included in the bundle.

**Comment by dbemiller** [comment]
aha, ok. Yeah, that issue was also fixed in #1332.
