### ISSUE TITLE
Prebid Server is responding no_bid.

### ISSUE THREAD

**Issue by vishalgarale** [prebid/Prebid.js#1349]
We have two ad unit slots, one having valid AppNexus placement id, another having invalid AppNexus placement id. When a call goes to Prebid Server it returns no_bid for all ad units. 

Eg. Consider adunit1 and adunit2, valid Appnexus placement id APNX1 (5823300), invalid Appnexus placement id APNX2 (5823302). 

If we call like 
AdUnit1 - APNX1
AdUnit2 - APNX1

Prebid server responded with valid bids.

If we call like 
AdUnit1 - APNX1
AdUnit2 - APNX2

Prebid server responded with invalid bids. 

What is Prebid servers internal implementation? If one platform does not give bid then will it return no bid?

**Comment by mkendall07** [comment]
This is a internal implementation of the AppNexus bidder platform not prebid.js or Prebid Server.
