### ISSUE TITLE
Criteo and OpenX tag details

### ISSUE THREAD

**Issue by veeba** [prebid/Prebid.js#135]
Can somebody explain how can I find details "nid" and "cookiename" in Criteo, also "jstag_url", "pgid" and "unit" in OpenX. Where can I find that (from tag or somewhere from platfroms?). 
Thanks again

**Comment by BartVB** [comment]
You can get them from your account manager.
But be aware; both networks have several solutions for publishers and the 'standard' products do not work with prebid.org. You need at least 100MM impressions to get access to the OpenX bidder interface. Not sure what the requirements are with Criteo but you'll need the 'Criteo RTA' product.

**Comment by mkendall07** [comment]
@veeba 

Going to close this issue out, let us know if you need further help. Also thanks @BartVB  for helping out here.
