### ISSUE TITLE
There is no support for IE9

### ISSUE THREAD

**Issue by Niksok** [prebid/Prebid.js#1350]
## Type of issue
Bug

## Steps to reproduce
Run any page with prebid.js, for example http://prebid.org/dev-docs/examples/basic-example.html

### Expected results
We must see rendered creatives and do not see any errors in console
### Actual results
We do not see any creatives and have an error in console - 
SCRIPT438: Object doesn't support property or method 'defineProperty'
prebid.js, line 3 character 11663
## Platform details
prebid.js v0.25.0
Updated : 2017-06-15

Windows 7, Internet Explorer 9

## Other information
I think update doc is needed

**Comment by mkendall07** [comment]
IE 9 sees very little traffic these days and as such we have deprecated support of it (as has MSFT). I updated the readme to reflect IE 10+ support.
