### ISSUE TITLE
Unable to download prebid.js from http://prebid.org/download.html

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#1354]
URL:
client-test.devnxs.net/downloads/prebid_20170705194908.js.gz

Error message:
Not Found

The requested URL /downloads/prebid_20170705194908.js.gz was not found on this server.

Apache/2.2.15 (CentOS) Server at client-test.devnxs.net Port 80

**Comment by mkendall07** [comment]
@headerbidding 
Can you try again? we had a glitch yesterday and all previously generated files were deleted. Thanks

**Comment by headerbidding** [comment]
Thanks. It works now!
