### ISSUE TITLE
Is Prebid ready for the DFP v201608 deprecations?

### ISSUE THREAD

**Issue by robthehall** [prebid/Prebid.js#1363]
## Type of issue

Mostly a question, but maybe it'll lead to a code change.

## Description

DFP is sunsetting some portion of their header bidding API. (See [their posting](http://googleadsdeveloper.blogspot.com/2017/07/sunset-of-dfp-api-v201608.html) on the subject.) Is Prebid ready for this?

## Steps to reproduce

I don't have steps to reproduce. I searched issues and the code, but was unable to confirm or deny that prebid will be affected by this deprecation.

### Expected results

No deprecated API calls used.

### Actual results

Google warning that deprecated API calls used, maybe.

## Platform details

prebid v0.22.2
* We can upgrade, but I didn't see anything addressing the deprecation in the release logs.

We also have a direct OpenX integration on site, so it's possible it's their code that's triggering Google's deprecation notice. Our company has reached out to them, but I wanted to check here too.

## Other information

Here's the warning Google emailed us:

> Dear publisher,

> We posted on our [API blog](http://googleadsdeveloper.blogspot.com/2017/07/sunset-of-dfp-api-v201608.html) the details of the DFP API sunset. If you are receiving this notification email, it is because you are currently using a deprecated version (v201608) of the DFP API within the following applications (if available):
> * bidder

> In order for your business to be unaffected, it is imperative that you update the API by August 31, 2017. After this date, the API will stop working ([deprecation schedule](https://developers.google.com/doubleclick-publishers/docs/deprecation)).

> For release notes as to what’s changed in the new API, check out [this](https://developers.google.com/doubleclick-publishers/docs/rel_notes) link. The most up-to date libraries can be found under “Version v201705” in the left bar under “Reference.” In addition, [developers forum](https://developers.google.com/doubleclick-publishers/community) is a great resource for you to discuss how to best make use of the API.

> Note: v201611 will enter deprecation shortly and will be sunset completely by November 2017.

> Please let us know if you have any questions.

> Thanks,
> The DFP Support Team

**Comment by polapi** [comment]
I think all the prebid.js does is marking ad slots with keys and values. It does not interact with DFP API and initializing prebid.js in DFP code does not require any special calls to DFP code API. Anyway, I am using DFP and I have not received such email.

**Comment by mkendall07** [comment]
That's correct, Prebid.js doesn't interact with any DFP APIs. Thanks for checking.

**Comment by robthehall** [comment]
Thanks everyone!
