### ISSUE TITLE
OpenX's revenues are not recorded

### ISSUE THREAD

**Issue by salvoaranzulla** [prebid/Prebid.js#138]
I'm trying to use OpenX inside Prebid.js: all creativities seem to be perfect. After I have gone live, I have discovered that earnings are not recorded by my OpenX's dashboard:

<img width="1197" alt="screenshot 2015-12-12 09 47 14" src="https://cloud.githubusercontent.com/assets/5984607/11761107/59964c54-a0b5-11e5-959a-13979995e292.png">

My configuration is very easy:

![screenshot 2015-12-11 04 40 58](https://cloud.githubusercontent.com/assets/5984607/11761102/44343d58-a0b5-11e5-934c-df7a7385e929.png)

Do you have this problem?

Thanks

**Comment by BartVB** [comment]
You didn't specify the 'Page ID' (pgid), according to the documentation this is a required parameter:
http://prebid.org/dev-docs/bidders.html

Are you sure that you have access to the OpenX bidder interface? Apparently OpenX has a couple of different types of accounts for publishers. The 'default' account type is unable to receive individual bids on impressions.

**Comment by salvoaranzulla** [comment]
Hi Bart,

Yes, I have the right account. I think pgid is used to do 1 ad requests:

http://docs.openx.com/ad_server/adtagguide_structured_structure_page.html

**Comment by BartVB** [comment]
Ah, indeed. It looks like either the pgid or unit parameters are required.

Also check what happens in the network tab of your browsers development tools. Is a call being made to OpenX? What does OpenX respond?

**Comment by salvoaranzulla** [comment]
>> Ah, indeed. It looks like either the pgid or unit parameters are required.

Yes, it's correct: ither the pgid or ad unit id.

>> Is a call being made to OpenX? 

Yes, sure.

>> What does OpenX respond?

It's the same response of OpenX Bidder. 

For the moment, I have solved loading OpenX Bidder:

 		        var OpenXAdaptor = function OpenXAdaptor() {
		            return {
		                callBids: function(p) {
		                    pbjs.loadScript('//ox-d.[my-account].servedbyopenx.com/w/1.0/jstag?nc=[my-account]', function() {
		                            pbjs.bidsAvailableForAdapter('openx');
		                    });
		                }
		            };
		        };
		        pbjs.registerBidAdapter(OpenXAdaptor, 'openx');

And 

			        		{
			        			bidder: 'openx'
			        		},

Thanks

**Comment by ConsumedMedia1** [comment]
At Consumed Media, we had the same problem, in that OpenX doesn’t record revenue with Prebid. Our sister company, bRealtime, was able to get us working using their Biddr+ header bidding solution. Their’s is the only one that works correctly with OpenX. Let me know if you want their help.

**Comment by salvoaranzulla** [comment]
Hi, 

I have solved loading original OpenX Bidder's script.

**Comment by Heray** [comment]
@salvoaranzulla mind help us understand how you solved this issue? This could benefit a lot of us. Thanks!

**Comment by salvoaranzulla** [comment]
@Heray  I have created a "fake" adaptor: 

            var OpenXAdaptor = function OpenXAdaptor() {
                return {
                    callBids: function(p) {
                        pbjs.loadScript('//ox-d.[my-account].servedbyopenx.com/w/1.0/jstag?nc=[my-account]', function() {
                                pbjs.bidsAvailableForAdapter('openx');
                        });
                    }
                };
            };
            pbjs.registerBidAdapter(OpenXAdaptor, 'openx');

And I have added this bidder on 1 ad unit: 

                        {
                            bidder: 'openx'
                        }

In this way, you can load original OpenX Bidder script. You need to configure DFP with a different order and different line items.

**Comment by protonate** [comment]
Closing as the OP has resolved the issue. Thanks @salvoaranzulla for posting your solution.
