### ISSUE TITLE
I'm not getting any preview for this Prebid.js scripts. Please help

### ISSUE THREAD

**Issue by ghost** [prebid/Prebid.js#1380]
<html>
<head>
  
  
  <script src="/cdn-cgi/apps/head/aC41_t5fLkA0S-YYLJEba_WMBMg.js"></script><script> 
    var PREBID_TIMEOUT = 5000;
    var adUnits = [{   
    	code: 'div-gpt-ad-1499359229491-0', 
        sizes: [[320,50]],
        bids: [{
        	bidder: 'sovrn',
            params: {
            	tagid: '491213'
            }
     },{
            bidder: 'openx',
            params: {
            	unit: '539093190',
                delDomain: 'pixfuture-d.openx.net'
            }
        }]
     },{    
   		code: 'div-gpt-ad-1499359229491-1', 
        sizes: [[728,90]],
        bids: [{
        	bidder: 'sovrn',
            params: {
            	tagid: '491210'
            }
     },{
     		bidder: 'openx',
            params: {
            	unit: '539093189',
                delDomain: 'pixfuture-d.openx.net'
            }
        }]
     },{
     	code: 'div-gpt-ad-1499359229491-2', 
        sizes: [[300,250]],
        bids: [{
        	bidder: 'sovrn',
            params: {
            	tagid: '491211'
            }
      },{
      		bidder: 'openx',
            params: {
            	unit: '539093187',
                delDomain: 'pixfuture-d.openx.net'
            }   
        }]
     },{
      	code: 'div-gpt-ad-1499359229491-3', 
        sizes: [[300,600], [160,600]],
        bids: [{
        	bidder: 'sovrn',
            params: {
            	tagid: '491215'
            }
     },{
     		bidder: 'openx',
            params: {
            	unit: '539093186',
                delDomain: 'pixfuture-d.openx.net'
            }
        }]
     }];  
     	pbjs.addAdUnits(bidResponses);
    	pbjs.addCallback('adUnitBidsBack', function (adUnitCode) {
            console.debug('ad unit bids back for:'+ adUnitCode);
    });

     pbjs.bidderSettings = {
   	 standard: {
        adserverTargeting: [
            {
                key:"hb_bidder",
                val: function (bidResponse){
                     return bidResponse.bidderCode;
                }
            },{
            	key:"hb_adid",
                val: function (bidResponse){
                     return bidResponse.adId;
                }
            },{
            	key:"hb_pb",
                val: function (bidResponse){
                     return bidResponse.pbMg;
                }
            },{
            	key:"pbecp",
                val: function (bidResponse){
                     return bidResponse.pbMg;
                }
            }
        ]
    },
   	openx: { 	
  	alwaysUseBid: true, 	
   		adserverTargeting: [
        	{ 	
      			key: "oxb",
      			val: function(bidResponse) {
         	var bid;
         		if (bidResponse.cpm < 1) {
            	bid = ((Math.floor(bidResponse.cpm * 20) / 20) * 100).toFixed(0);
         	} else if (bidResponse.cpm < 5) {
            	bid = ((Math.floor(bidResponse.cpm * 10) / 10) * 100).toFixed(0);
         	} else if (bidResponse.cpm < 20) {
            	bid = ((Math.floor(bidResponse.cpm * 2) / 2) * 100).toFixed(0);
         	} else {
            	bid = "2000";
        	}
         		return bidResponse.width + "x" + bidResponse.height + "_" + bid;
      	},{
    alwaysUseBid: false,
    adserverTargeting: [
        	{
         		key: "hb_bidder",
         		val: function(bidResponse) {
            	return bidResponse.bidderCode;
         	}
      	},{
        		key: "hb_adid",
         		val: function(bidResponse) {
            	return bidResponse.adId;
         	}
      	},{
         		key: "hb_pb",
         		val: function(bidResponse) {
            	return bidResponse.pbMg;
         	}
      	},{
         		key: "hb_size",
         		val: function(bidResponse) {
            	return bidResponse.size;
         }
       },{
         		key: "ox_pb_won",
         		val: function(bidResponse) {
            	if (bidResponse.bidderCode.indexOf('openx') !== -1) {
               		return "true";
            	}
            		return "false";
           }
        }]
      };
     });
     function(){
    	var e=document,t=e.createElement("script");
        	e.location.protocol;
        	t.type="text/javascript";
        	t.src="//lakeontariounited.com/ads/prebid.js";
    	var n=document.getElementsByTagName("head")[0];
    		n.insertBefore(t,n.firstChild)
        }();
        var pbjs=pbjs||{};
   		pbjs.que=pbjs.que||[];
    	pbjs.retries=0;
     </script>
    
     <script>
     var googletag = googletag || {};
     googletag.cmd = googletag.cmd || [];
     googletag.cmd.push(function() {
        googletag.pubads().disableInitialLoad();
     });
     pbjs.que.push(function() {
        pbjs.addAdUnits(adUnits);
        pbjs.requestBids({
            bidsBackHandler: sendAdserverRequest
        });
     });
     function sendAdserverRequest() {
        if (pbjs.adserverRequestSent) return;
        pbjs.adserverRequestSent = true;
        googletag.cmd.push(function() {
            pbjs.que.push(function() {
                pbjs.setTargetingForGPTAsync();
                googletag.pubads().refresh();
            });
        });
     }
     setTimeout(function() {
     sendAdserverRequest();
     }, PREBID_TIMEOUT);
  </script>
  <script>
     (function () {
         var gads = document.createElement('script');
          gads.async = true;
         gads.type = 'text/javascript';
         var useSSL = 'https:' == document.location.protocol;
         gads.src = (useSSL ? 'https:' : 'http:') +
                '//www.googletagservices.com/tag/js/gpt.js';
         var node = document.getElementsByTagName('script')[0];
         node.parentNode.insertBefore(gads, node);
     })();
  </script>

  <script>
    var globalslot = null;
    googletag.cmd.push(function () {
    googletag.defineSlot('/9482313/header-bid-tag-ATF', [[728, 90], [320, 50]], 'div-gpt-ad-1499621595757-0').addService(googletag.pubads());
    googletag.defineSlot('/9482313/header-bid-tag-BTF', [[728, 90], [320, 50]], 'div-gpt-ad-1499621595757-1').addService(googletag.pubads());
    googletag.defineSlot('/9482313/header-bid-tag-LSB1', [300, 250], 'div-gpt-ad-1499621595757-2').addService(googletag.pubads());
    googletag.defineSlot('/9482313/header-bid-tag-LSB2', [[160, 600], [300, 600]], 'div-gpt-ad-1499621595757-3').addService(googletag.pubads());
    googletag.pubads().enableSingleRequest();
    googletag.enableServices();
    });
  
  
   </script>
   </head>

<body>

<h2>Prebid.js Test</h2>

<h5>Test case_1 - 728x90</h2>

<div id='div-gpt-ad-1499621595757-0'>
<script>
googletag.cmd.push(function() { googletag.display('div-gpt-ad-1499621595757-0'); });
</script>
</div>

<h5>Test case_2 - 728x90</h2>

<div id='div-gpt-ad-1499621595757-1'>
<script>
googletag.cmd.push(function() { googletag.display('div-gpt-ad-1499621595757-1'); });
</script>
</div>

<h5>Test case_3 - 300x250</h2>

<div id='div-gpt-ad-1499621595757-2' style='height:250px; width:300px;'>
<script>
googletag.cmd.push(function() { googletag.display('div-gpt-ad-1499621595757-2'); });
</script>
</div>

<h5>Test case_4 - 300x600</h2>

<div id='div-gpt-ad-1499621595757-3'>
<script>
googletag.cmd.push(function() { googletag.display('div-gpt-ad-1499621595757-3'); });
</script>
</div>
    
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-11418628-1', 'auto');
    ga('send', 'pageview');
    pbjs.cmd.push(function () {
        pbjs.enableAnalytics({
            provider: 'ga',
            options: {
                global: 'ga', 
                enableDistribution: false 
            }
        });
    });
</script>

</body>

</html>

**Comment by mkendall07** [comment]
@silviasam It would be helpful if you provided a link to the page with the issue.

**Comment by silviasam** [comment]
Hi Matt, 

Thanks for the response 

https://lakeontariounited.com/ads/prebid_test.html

**Comment by silviasam** [comment]
Can you get me in touch Google Chat? silviasam91@gmail.com

**Comment by protonate** [comment]
There appear to be syntax issues with the test page and the structure of bidder settings should be checked against Prebid.js examples.
