### ISSUE TITLE
Missing prebid version in bundled code

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#1387]
## Type of issue
bug/feature

## Description
Previously, the build step appended the build version to the build like so:
```
/* prebid.js v0.21.0
Updated : 2017-04-03 */
```
This info is missing in 0.26.0 builds. 

I would propose we add some additional information to the build, such as the modules that were bundled and the core version.

```
/* prebid.js v0.xx.x. modules=openxBidAdapter,rubiconBidAdapter,sovrnBidAdapter... /*
```

## Steps to reproduce
run `gulp serve`

## Platform details
prebid 0.26.0

## Other information
@prebid/core  for input.

**Comment by snapwich** [comment]
Added a fix for the header missing.  It was an accidental regression when we moved `prebid.js` to be `prebid-core.js`.

The inclusion of the modules in the comment could be a tricky one as that isn't determined until bundle time whereas the header is currently added during the webpack step to the `prebid-core.js` file.  We could defer adding the header until bundling always, but then it could be annoying for those that manually bundle.  I dunno, I could go either way.
