### ISSUE TITLE
Using appnexusAst adapter on IE 11 error

### ISSUE THREAD

**Issue by photonx** [prebid/Prebid.js#1410]
Hello. Every time i try to use appnexusAst on ie11 (and i see the same errors in other adapters) it return this error "InvalidStateError: xhr construction". 

In this example the errors can be seen
http://acdn.adnxs.com/prebid/alpha/unrulydemo.html 

Here are the errors with debug:
https://www.screencast.com/t/wRydDqWhKz

**Comment by mkendall07** [comment]
@photonx 
thanks for the bug report. I opened a PR to fix.
