### ISSUE TITLE
bidsBackHandler firing before bids are back or timeout reached

### ISSUE THREAD

**Issue by kevinlisota** [prebid/Prebid.js#1414]
We are experimenting with prebid. Not sure if this is a bug, or simply a question about our implementation.

We are having issues with ad requests being sent to DFP before the prebid targeting has been set.  Ad requests are being made and are not timing out, but the bidsBackHandler function on requestBids seems to fire early, even before the first request is sent to a bidder.

Our setup is following the example docs, following this sequence:

1) pbjs.enableSendAllBids
2) pbjs.enableAnalytics
2) pbjs.addAdunits
2) pbjs.requestBids with a bidsBackHandler callback function
3) The bidsBackHandler function fires setTargetingforGPTAsync, then calls googletag refresh to fetch the ads.

Ad requests are made and successfully returned with bids, but no GPT targeting is being set before sending to DFP. Here is a sequence from pbjs_debug:

![image](https://user-images.githubusercontent.com/4521682/28585780-3f47b6ba-7126-11e7-9991-6c8a1885dfd8.png)

Despite this setup, you'll see that setTartgetingfor GPTAsync is invoked early, in fact earlier than requestBids.

I can't seem to figure out why the bidsBackHandler is firing so early, seemingly before requestBids is invoked, which doesn't make sense given this code block

```
                pbjs.que.push(function() {
                    pbjs.enableSendAllBids();
                    pbjs.enableAnalytics({
                        provider: 'ga',
                        options: {
                            global: 'ga'
                        }
                    });
                    pbjs.addAdUnits(pbSlots);
                    pbjs.requestBids({
                        bidsBackHandler: sendAdserverRequest(gptAdSlots, pbSlots, apsSlots)
                    });
                });
                setTimeout(function() {
                    sendAdserverRequest();
                }, PREBID_TIMEOUT);
```
Anyone seen an issue like this?

**Comment by mkendall07** [comment]
what's the value of `PREBID_TIMEOUT` ? seems like that might be triggering the out of order requests.

**Comment by kevinlisota** [comment]
I have it set at 1000, trying to make sure nothing times out, although I'm only requesting one bidder and two slots, which seems to be returning in 250ms or so.

**Comment by mkendall07** [comment]
could be a number of things. Can you share the test page? what's the result of running these commands : http://prebid.org/dev-docs/toubleshooting-tips.html#see-all-bids-in-the-console

**Comment by kevinlisota** [comment]
I think I figured this out, though I'm not quite well-versed enough in Javascript to know why this happens.

I was working off the [example page](http://prebid.org/dev-docs/examples/basic-example.html) and defined the `sendAdServerRequest` function above the spot that it was being called. So my code looked like this
```
    function sendAdserverRequest() {
        if (pbjs.adserverRequestSent) return;
        pbjs.adserverRequestSent = true;
        googletag.cmd.push(function() {
            pbjs.que.push(function() {
                pbjs.setTargetingForGPTAsync();
                googletag.pubads().refresh();
            });
        });
    }
some more code here
    pbjs.que.push(function() {
        pbjs.addAdUnits(adUnits);
        pbjs.requestBids({
            bidsBackHandler: sendAdserverRequest
        });
    });
```
Using that code, setTargetingforGPTAsync was always being invoked before requestBids, so no prebid targeting was ever set.

Then i switched it to an anonymous callback function like so:
```
    function sendAdserverRequest() {
        if (pbjs.adserverRequestSent) return;
        pbjs.adserverRequestSent = true;
        googletag.cmd.push(function() {
            pbjs.que.push(function() {
                pbjs.setTargetingForGPTAsync();
                googletag.pubads().refresh();
            });
        });
    }
some more code here
    pbjs.que.push(function() {
        pbjs.addAdUnits(adUnits);
        pbjs.requestBids({
            bidsBackHandler: function(bidResponses){
                sendAdserverRequest();
        });
    });
```
Then it behaved as expected. I am unaware of the difference in how Javascript is invoking the `sendAdserverRequest` function in these two cases.

**Comment by protonate** [comment]
Closing as resolved, @kevinlisota please open a new issue if things aren't working as expected.
