### ISSUE TITLE
ERROR: Error trying to write ad. Cannot find ad by given id

### ISSUE THREAD

**Issue by Bigandt** [prebid/Prebid.js#1424]
## Type of issue
I just started working with Prebid.
I get: ERROR: Error trying to write ad. Cannot find ad by given id : 29ce13c65a0f533. Instead of the ad I see a blank from DFP.
Link to the page: http://www.bold.dk/

## Description
The console shows me the following:
**1st bidding round:**
![selection_004](https://user-images.githubusercontent.com/19621064/28660886-1323af22-72b5-11e7-877d-efeb5d609b57.png)

**2nd and 3rd bidding round:**
![selection_005](https://user-images.githubusercontent.com/19621064/28660890-199417de-72b5-11e7-8689-67ed1744ba36.png)

**error:**
![selection_006](https://user-images.githubusercontent.com/19621064/28660897-1d314984-72b5-11e7-8edf-e0c7c8942d8b.png)

## Platform details
I have seen the issue in Google Chrome and in Safari

## Other information
It seems related to this issue  #https://github.com/prebid/Prebid.js/issues/484
but I still can't figure out what is wrong.

Any help would be appreciated.
Thanks.

**Comment by aneuway2** [comment]
@Bigandt , you're running multiple auctions for the same ad unit? Prebid isn't setup to handle that since the adids will be reset for each auction thats occurring.

I wouldn't recommend it because SSPs might be keen to seeing why so many bids requests are being made but so little ads served, but if you are going down this route, why not just have 1 auction with the ad units added into it multiple times:

```
bids: [{
     bidder: 'biddername',
     params: { ad: '1234' }
},
{
     bidder: 'biddername',
     params: { ad: '1234' }
}]
```

**Comment by Bigandt** [comment]
@aneuway2, thanks for your help.

**Comment by jccomet** [comment]
Hi,

I've got a quite similar issue.
For a given adunit :
1. I add an adunit into predbid adunits.
2. I run a first prebid auction.
3. After ad has been rendering by DFP (whether prebid has won or not), I remove the adunit from prebid.
After a while, I do refresh the positions, by
4. Adding again the adunit into prebid adunits (same code but it has been removed and added again)
5. Running another auction.

Then, when prebid wins, I've got the error : 
ERROR: Error trying to write ad. Cannot find ad by given id : xxxxxx

Please find an example here (screen shot on reload) : 
![image](https://user-images.githubusercontent.com/16593777/60982933-5c638480-a339-11e9-8b1c-d14cadcab99a.png)
