### ISSUE TITLE
utils.extend() destroys arrays

### ISSUE THREAD

**Issue by BartVB** [prebid/Prebid.js#143]
I'm currently implementing Criteo RTA. A part of the implementation is:

```javascript
    pbjs.bidderSettings = {
        criteo: {
            alwaysUseBid : true,
            adserverTargeting: [{
                key: "criteo",
                val: function (bidResponse) {
                    return bidResponse.keys;
                }
            }
            ]
        },
```

This should result in [setTargeting(key, value)](https://developers.google.com/doubleclick-gpt/reference?hl=en#googletag.PubAdsService_setTargeting) being called where 'value' is an array of zones which are present in the Criteo cookie.

Alas this doesn't work because:
https://github.com/prebid/Prebid.js/blob/master/src/utils.js#L99

replaces the array with an Object. I fixed this by replacing this code with simply:

```javascript
exports.extend = function(target, source){
	target = target || {};

	this._each(source,function(value,prop){
        	target[prop] = source[prop];
	});
	return target;
};
```

This also brings it more into accordance with [Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) where only one level of properties is copied.

**Comment by prebid** [comment]
@mkendall07 @jdelhommeau mind take a look?

**Comment by nickjacob** [comment]
maybe to avoid any breaking changes/still fix the array issue we could just change line 103 from:

```javascript
		if (typeof source[prop] === objectType_object) {
```

to

```javascript
		if (this.isA(source[prop], 'Object')) {
```

@BartVB  would that work for criteo?

**Comment by protonate** [comment]
@nickjacob @BartVB @mkendall07 does this work? Is it preferable to copy arrays as arrays or is the `object Object` cast a requirement of the current implementation?

And does this solve this issue?

**Comment by mkendall07** [comment]
@protonate You'll need to source for callers of the function to determine how it's used today. I'm not sure if it will work right if it is changed.

**Comment by protonate** [comment]
I believe this is no longer needed, if any updates please reopen. Closing.

**Comment by BartVB** [comment]
Apologies for the late response! Got sidetracked.

I've tested this with current master and that code still destroys arrays.

The solution which @nickjacob suggests solves the problem for me. Thanks!
