### ISSUE TITLE
updating to v0.27.0-pre from v0.25, targeting not being set

### ISSUE THREAD

**Issue by kevinlisota** [prebid/Prebid.js#1439]
We were using the v0.25, built and downloaded from the download page with the following adapters:
- sovrn
- AOL
- Audience Network
- Google Analytics

We are only sending bids via the sovrn adapter at the moment. With v0.25, the bids were sent & received, and targeting was properly set.

Yesterday I built from source with the same adapters, so version is v0.27.0-pre. No other code changes were made, and bids are successfully sent & received to sovrn, but targeting is not being set before ads are refreshed.

Running the troubleshooting steps on v0.27.0-pre as follows. Timeout is 1s, which is way more than enough time for this one bidder to respond.
1) `pbjs.getBidResponses()` shows bid responses as expected
2) `pbjs.getAdserverTargeting()` shows the three adunit objects, but the objects are empty. On v0.25 of prebid.js, these would show the targeting key-value pairs.
3) DFP console shows no targeting being set by prebid

pbjs_debug output
![image](https://user-images.githubusercontent.com/4521682/28747115-492fbcc6-744c-11e7-8704-d8d22e1089a4.png)

This is followed by:
INFO: Invoking pbjs.setTargetingForGPTAsync 
MESSAGE: Emitting event for: setTargeting
MESSAGE: Prebid auction cleared

**Comment by snapwich** [comment]
0.26 introduced the concept of modules which are specified differently than adapters were in previous versions.  Did you specify the bid adapter modules from the CLI as specified in the updated README.md?

**Comment by kevinlisota** [comment]
I followed that readme using a modules.json file. The resulting prebid.js definitely contains the module code for the ones I specified. Just stumped on why the bids come back, but aren't set.

**Comment by mkendall07** [comment]
@kevinlisota 
can you post a page or fiddle that reproduces the issue please?

**Comment by kevinlisota** [comment]
Let me get a test page up. I'm only running in production at the moment, and I can't leave the broken script in place.

However, I have discovered exactly the commit where it breaks, along with some additional debugging output.

Our sovrn adapter works fine up until the [Modernizing build dependencies](https://github.com/prebid/Prebid.js/commit/4b04890723aeb280b84a37175ab0015aa82e912e) commit. It is broken on all subsequent builds.

This request sends out a request for 4 bids from Sovrn and receives 4 bids back. Note that there are 3 warnings about bids being overwritten. No targeting is being set.

<img width="396" alt="prebid-debug" src="https://user-images.githubusercontent.com/4521682/28859531-a1cbc902-770c-11e7-94e0-f6476986e122.PNG">

I am building prebid.js on Windows as well. Not sure how that would impact it, but I suppose it could.

I'll try to get a test page going that doesn't load our production code.

**Comment by mkendall07** [comment]
@kevinlisota thanks for the additional details. ok let me know if you get a test page setup. If you can't do that, maybe a copy of the config will suffice to test.

**Comment by mkendall07** [comment]
@kevinlisota are you still seeing this issue?

**Comment by kevinlisota** [comment]
@mkendall07 Sorry for the delay. Indeed I still see this issue. I've spun up a test page to try and diagnose. I'm going to email to you

**Comment by mkendall07** [comment]
hmm this may have gotten lost in my inbox. Can you create a new issue if it's still a problem?
