### ISSUE TITLE
v1 auction request timeout / canceled

### ISSUE THREAD

**Issue by smartbidder1** [prebid/Prebid.js#1440]
## Type of issue
server bug?

## Description
last week I've created a demo of Server to Server header bidding with prebid.js and appnexus server.
it was working great, but since yesterday https://prebid.adnxs.com/pbs/v1/auction requests are cancelled by chrome and when I try to do them with fiddler, I am getting server time out.

## Steps to reproduce
create a simple server to server demo setup with DFP, https://prebid.adnxs.com/pbs/v1/auction requests would die.

### Expected results
A real response from https://prebid.adnxs.com/pbs/v1/auction.
### Actual results
Server time out.

## Platform details
Prebid.js, chrome.

## Other information
my code:
https://pastebin.com/a6GQEqbE

**Comment by mkendall07** [comment]
can you try again? We had an issue over the weekend but should be resolved now.

**Comment by smartbidder1** [comment]
now working again thanks.
why am I always getting unsupported bidder error when I am trying other bidders then appnexus? such as adblade and sovrn?
where is the list of the supported S2S bidders.
