### ISSUE TITLE
Adapter Aliasing for AOL and AppNexus AST Broken with recent commit

### ISSUE THREAD

**Issue by ehoch** [prebid/Prebid.js#1455]
## Type of issue
bug

## Description
Adapter aliases no longer works with recent commits.

## Steps to reproduce
1. Use latest build, include an adapter such as AOL that uses aliases for bid
2. Inspect ?pbjs_debug and you'll see errors related to aliasing "adaptermanager.aliasBidAdapter: aol bidder does not currently support aliasing"

### Expected results
Aliasing to work

### Actual results
Aliasing no longer works

## Platform details
Latest Prebid.js, Node 7.10

## Other information
I had to roll back to commit (1d827006701113ce2cb679c9cddaad8a3bf8c25c) where AOL aliasing still works. It's something after that.

**Comment by mkendall07** [comment]
@ehoch not seeing this with a fresh build from master. How are you building?

**Comment by mkendall07** [comment]
@ehoch I see the issue now. I switched to use one of the aliases and I got the error. Thanks for the bug report.
