### ISSUE TITLE
Prebid DFP setup with Adsense

### ISSUE THREAD

**Issue by jamesfebin** [prebid/Prebid.js#1466]
# Question
I am trying to setup header bidding for a publisher. His DFP account don't have the link AdSense/AdEx Option like mentioned here https://support.google.com/dfp_premium/answer/188529?hl=en. (Some people told me I have to contact google and enable this, but there is no DFP support email ) 

Hence, I am unable to make the dynamic allocation work. Is there any workaround? 

**I have enabled AdSense at inventory level, but without dynamic allocation this only decreased my revenue.**

**Comment by polapi** [comment]
It's not really prebid.js problem.

You should contact AdSense support to enable link (their first response would be the accounts are already linked, you need to push them more to have linked accounts sections enabled).

As for going without dynamic allocation - disable prebid line items which have CPM below your AdSense RPM. That way you won't loose revenue.

**Comment by polapi** [comment]
By the way. I wonder if committing to dynamic allocation with AdSense makes sense. When I go to my AdSense account I can drill down to ad types and it says there are like 10% of CPM ad types (remaining ones are pay by click). Does any one know if only CPM type ads compete or there is also some estimation of CPM done for click based ads?

**Comment by headerbidding** [comment]
Yes, AdSense estimates the CPM for click based ads.
