### ISSUE TITLE
Compression failed with Yuicompressor & Closure

### ISSUE THREAD

**Issue by Broutard** [prebid/Prebid.js#1471]
## Type of issue
Bug

## Description
Yuicompressor & Google Closure compilers crash due to your ".native" variable.
`native` is a reserved word in ECMAScript v3 (https://www.w3schools.com/js/js_reserved.asp).

## Steps to reproduce
Run `/usr/bin/java -jar yuicompressor.jar --type js prebid.js`

### Actual results
Many errors like :
```
missing name after . operator :
prebid.js
        })),
            i = Object.keys(e.native);
        return n.every((function(e) {
```

Works fine if I replace all ".native" with ".xnative" (for example)

**Comment by mkendall07** [comment]
@matthewlane can you check this? It could impact our implementation.
