### ISSUE TITLE
Appnexus/AppnexusAST adapter : Bid on CPC return 0 CPM

### ISSUE THREAD

**Issue by Midgorn** [prebid/Prebid.js#1473]
## Type of issue
If Appnexus or Appnexus AST return a winning bid on CPC (or CPA i think) , the adapter (/jpt or AST) return a 0 CPM, so it never win.

### Expected results
Have an estimated WIn CPM return instead of 0.

**Comment by GLStephen** [comment]
How accurate would an estimated CPA/CPC be? Just curious in relation to reporting, etc.

**Comment by mkendall07** [comment]
@mjacobsonny for comment

**Comment by mjacobsonny** [comment]
@Midgorn -- This is a known issue, and something that is on the internal AppNexus backlog.

@GLStephen -- Hard to say for sure how accurate any eCPM would be derived from a CPC/ CPA strategy, but it would be the same calculation/ value used in AppNexus' optimization algorithms.
