### ISSUE TITLE
Feature: Inherit standard bidderSettings

### ISSUE THREAD

**Issue by BartVB** [prebid/Prebid.js#148]
It's great that there is a 'bidCpmAdjustment' bidder setting in Prebid.js but this is a bit hard to use because bidderSettings are not inherited.

In my 'standard' settings I assign some price buckets. One of the bidders that I use needs a CPM adjustment, but if I want to do this through 'bidCpmAdjustment' I need to copy/paste the pricebuckets to the relevant bidderSettings section. It would be really nice if I could do something like:

```javascript
        foobarnetwork: {
            bidCpmAdjustment : function(bidCpm){
                return bidCpm * 0.7;
            },
            inheritStandard: true
        },
       standard: {
         etc
```

or, maybe even better, if this were the default.

**Comment by prebid** [comment]
Indeed @BartVB and thanks for the great feedback! This feature is definitely still in Alpha and your feedback is very helpful. Like you said, `inheritStandard` is not even needed - it should just be the default.

@mkendall07 do you see any issue with the inheritance? Seems like a really small change.

**Comment by Reduxmedia** [comment]
I did this simply, for the "other" bidder..

        // Copy the default bidderSetting to AppNexus
        if(pbjs.bidderSettings["appnexus"] === undefined)
            pbjs.bidderSettings["appnexus"] = pbjs.bidderSettings["standard"];
           
than simply defined thebidCpmAdjustment function for the new bidder.

**Comment by mkendall07** [comment]
we can add this as a feature. Thanks for the feedback @BartVB

**Comment by BartVB** [comment]
Thank you for considering this and for Prebid.org!

@Reduxmedia great workaround :)

**Comment by mkendall07** [comment]
@BartVB  I have staged the update and will merge after verifying some more tests. You can see the unit test here: https://github.com/prebid/Prebid.js/blob/148_inherit_bid_settings/test/test.js#L177

**Comment by prebid** [comment]
Thanks @BartVB and @Reduxmedia!

**Comment by mkendall07** [comment]
Fixed in https://github.com/prebid/Prebid.js/releases/tag/0.5.0
