### ISSUE TITLE
How to make a pull request to previos prebid versions (0.25 and 0.24)?

### ISSUE THREAD

**Issue by PWyrembak** [prebid/Prebid.js#1481]
## Type of issue
Question.

## Description
How to make pull requests for previous prebid versions? For now the newest version is v26. We are going to make a pull request for trustx adaptor with prebid v26. Can we somehow make a pull request for *v25* & *v24*? We have several publishers who are currently using v24 and a lot of them currently using v25, so this is important for us.

**Comment by dbemiller** [comment]
We don't officially support this. It's a rare request, we release new versions frequently, and it takes much more manpower than we have to maintain patch branches and releases.

If the publishers aren't willing or able to upgrade, you can always check out the tag for the version you're targeting, add your adapter to it, and follow the [Prebid 0.25 Build Optimization](https://github.com/prebid/Prebid.js/blob/0.25.0/README.md#build-optimization) docs to build it yourself.
