### ISSUE TITLE
When bid is not winning, masterTag is made incorrect

### ISSUE THREAD

**Issue by olya-fb** [prebid/Prebid.js#1484]
## Type of issue

Bug

## Description

When giving masterTag to function `pbjs.buildMasterVideoTagFromAdserverTag`, if the bid is not a winning bid, the masterTag returns with description_url not url-encoded.

## Steps to reproduce

it's in the function `adserver.appendQueryParams`: now it is:

      adserver.appendQueryParams = function() {
        var bid = adserver.getWinningBidByCode();
        if (bid) {
          this.urlComponents.search.description_url = encodeURIComponent(bid.descriptionUrl);
          this.urlComponents.search.cust_params = getCustomParams(bid.adserverTargeting);
          this.urlComponents.search.correlator = Date.now();
        }
      };

meaning, if it doesn't find bid, `bid.descriptionUrl` isn't encoded, and after call to `adserver.appendQueryParams` the url components are joined anyway, and before that, when the query string was divided to components, uri encoding went away.

so there is a case when masterTag returns incorrect.

the function, I think, should be changed to be:

      adserver.appendQueryParams = function() {
         this.urlComponents.search.description_url = encodeURIComponent(bid.descriptionUrl);
         var bid = adserver.getWinningBidByCode();
         if (bid) {
           this.urlComponents.search.cust_params = getCustomParams(bid.adserverTargeting);
           this.urlComponents.search.correlator = Date.now();
         }
      };

## Platform details

Prebid 0.26.1

**Comment by mkendall07** [comment]
@olya-fb 
thanks for the report. We'll take a look. At a minimum we will fix this in prebid 1.0 if not before.
