### ISSUE TITLE
eslint should enforce valid JSDoc comments using (valid-jsdoc) plugin

### ISSUE THREAD

**Issue by rmloveland** [prebid/Prebid.js#1486]
## Type of issue

Feature request

## Description

As we move towards using the JSDoc comments for our API docs on Prebid.org, we should add some automagic validations that the JSDoc is accurate and up to date.  From the [valid-jsdoc plugin homepage](http://eslint.org/docs/rules/valid-jsdoc):

- If comments are invalid because of typing mistakes, then documentation will be incomplete.

- If comments are inconsistent because they are not updated when function definitions are modified, then readers might become confused.

It certainly seems like it will prove helpful in reminding people to update JSDocs along with any code changes.  I haven't really had a chance to play with it yet, nor investigate whether it has any potential unwanted side effects.  Based on reading the docs it seems fairly robust.

I'm not sure if this would be considered too onerous, or helpful, or maybe a little of both. :-)  What do you think?

## Other information

For more information about this plugin, see [the valid-jsdoc plugin's homepage](http://eslint.org/docs/rules/valid-jsdoc).

Relates to https://github.com/prebid/Prebid.js/issues/1408.

**Comment by dbemiller** [comment]
Definite +1 to linting the JSDocs to make sure they're valid.

Less certain about the tool. `documentation.js`, which I presume we'll be using to generate the docs, also comes with a `documentation lint` command: https://github.com/documentationjs/documentation#user-guide

Do you know offhand what the difference is between the two?

**Comment by rmloveland** [comment]
> Definite +1 to linting the JSDocs to make sure they're valid.

Yay!

> Less certain about the tool. documentation.js, which I presume we'll be using to generate the docs, also comes with a documentation lint command: https://github.com/documentationjs/documentation#user-guide

I have not gotten that far yet.  Right now I'm playing with the `jsdoc` tool just to get familiar, but I will also start using `documentation.js`.

> Do you know offhand what the difference is between the two?

Nope - need to investigate further.

**Comment by dbemiller** [comment]
For what it's worth, I stumbled on this yesterday in the `documentation.js` FAQs: https://github.com/documentationjs/documentation/blob/master/docs/FAQ.md#why-use-documentation-instead-of-writing-a-markdown-file-by-hand

So... the `eslint` rule probably works just fine. `eslint` is also already integrated into our CI... so it'll be easier to integrate with the project too (just add it to the `.eslintrc.js` file and you're done)
