### ISSUE TITLE
AudienceNetwork adapter bug: If the page url has hashtag, the sdk query string will be dropped when the request goes to an.facebook.com

### ISSUE THREAD

**Issue by brianxieseattle** [prebid/Prebid.js#1497]
## Type of issue
Bug

## Description
If the page url that hosting prebid to call AudienceNetwork has a hashtag such as 
https://www.testweb.com/?page=here#path=root

The request to Facebook will fail.

## Steps to reproduce
1. Have a web site that url looking like 
https://www.testweb.com/?page=here#path=root
2. Put Prebid.js with AudienceNetwork adapter on the web site and inspect the success or failure of the call

### Expected results
The outgoing request should be something like
https://an.facebook.com/v2/placementbid.json?placementids[]=12345678&adformats[]=native&testmode=false&pageurl=https://www.testweb.com/?page=here#path=root&sdk[]=5.5.web

### Actual results
The outgoing request looks like
https://an.facebook.com/v2/placementbid.json?placementids[]=12345678&adformats[]=native&testmode=false&pageurl=https://www.testweb.com/?page=here
and the response comes back as the failure

## Platform details
does not matter

## Other information
Root cause seems to be:
AudienceNetwork adapter uses the following codes to construct the request url
```
    const pageurl = location.href;
    const search = {
      placementids,
      adformats,
      testmode,
      pageurl,
      sdk
    };
    
        const url = format({
      protocol: 'https',
      host: 'an.facebook.com',
      pathname: '/v2/placementbid.json',
      search
    });
```
sdk part is after the pageurl part

The format function from url.js is 

```
export function format(obj) {
  return (obj.protocol || 'http') + '://' +
         (obj.host ||
          obj.hostname + (obj.port ? `:${obj.port}` : '')) +
         (obj.pathname || '') +
         (obj.search ? `?${formatQS(obj.search || '')}` : '') +
         (obj.hash ? `#${obj.hash}` : '');
}
```
It will treat hashtag as the last optional part and drops everything after.

The fix could be either of the following one:
1. AudienceNetwork adapter should consider encoding the pageUrl before sending to the format function. Meanwhile, it should also consider the length of the url as some browsers could not handle the url length which is larger than 1024
2. The generic format function should encode everything in the search part to protect itself. 

Please evaluate which route is probably the better fix.

**Comment by lovell** [comment]
Hello, #1502 provides a possible solution within the Audience Network adaptor.

In terms of long URLs, the oldest browser supported by Prebid.js is IE10 and I believe this can correctly handle these even if it only displays the first 2083 chars of them.

**Comment by brianxieseattle** [comment]
This is great. Thanks for looking into the fix.

**Comment by brianxieseattle** [comment]
This is great. Thanks for looking into the fix.

**Comment by matthewlane** [comment]
Closing with #1502 merged
