### ISSUE TITLE
Example page with `gulp serve` not working

### ISSUE THREAD

**Issue by ogupte** [prebid/Prebid.js#15]
Example page not working

Steps to reproduce:
1. run `gulp serve`
2. go to http://localhost:9999/integrationExamples/gpt/pbjs_example_gpt.html

**Comment by ogupte** [comment]
in the console i'm seeing a lot of 404 responses for resources

**Comment by mkendall07** [comment]
fixed the path issue with locating `prebid.js`. The other errors are because the bidder IDs are not properly defined. I suppose we could try to validate them first but it's not a high priority for us right now.
