### ISSUE TITLE
Ad units order and bid calls order

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#150]
Seems that the order of ad units requesting bids is called in the order they are configured which is fine, i remember reading that the bids call order it is random to have a fair competition for bidders but i cannot find in source code where it is randomized i may be missing something or is it calling the bids as they are configured?.

**Comment by BartVB** [comment]
As far as I know (and see in network traces) the bidders are called in the order that they are configured.
I'm using that to send requests to slow bidders first, but in most instances the requests are processed almost in parallel by the (desktop) browser. Could be that resource limited browser (i.e. on mobile devices) behave quite differently. Need to do some more testing there on mobile.
