### ISSUE TITLE
Empty objects in pbjs.getAdserverTargeting() 

### ISSUE THREAD

**Issue by nueq22** [prebid/Prebid.js#1503]
I'm use prebid v.0.23 with komoona adapter. 
```
pbjs.requestBids({
     bidsBackHandler: function(bidResponses) {
          console.log(bidResponses);
	  var targetingParams = pbjs.getAdserverTargeting();
	  console.log(targetingParams);
	  container.innerHTML = JSON.stringify(targetingParams);
    }
});
```
In bidResponses i have bids with all object keys like (adId, ad, etc...). But in pbjs.getAdserverTargeting() i have object  like this: 
`{"ad-block-1":{},"ad-block-2":{}}`
Why getAdserverTargeting return empty object for my bidRespones??

**Comment by mkendall07** [comment]
@nueq22 
it's hard to know without looking at the live URL. Do you have anything else we can look at?

**Comment by matthewlane** [comment]
Version 1.1.0 included a fix for empty objects returned from `pbjs.getAdserverTargeting`. Please try this version and reopen an issue if you still experience an issue, thanks
