### ISSUE TITLE
Upgrade from 0.25-pre to 0.27-pre causes a lot of missing bids, indexExchange adapter seems to cause a lot of missing responses

### ISSUE THREAD

**Issue by ptomasroos** [prebid/Prebid.js#1517]
## Type of issue
Bug

## Description

Yesterday at 15.30 we upgraded to 0.27 from running 0.25-pre for at least 2 months successfully.

I'm not sure if this has todo that timeout is being handled more strictly in terms of the bids back queue but we do see that after this upgrade a lot of bidResponses are being processed after the 

INFO: Invoking pbjs.setTargetingForGPTAsync 

Please let me know over Skype / Email in anyway if you would like to have access since its still running on one of our domains before ramping up (which we can't at the moment) since something has changed fundamentally.

<img width="827" alt="screen shot 2017-08-23 at 05 45 39" src="https://user-images.githubusercontent.com/1064547/29598027-9ec7f31e-87c6-11e7-84b6-ad6e7b31c67e.png">

**Comment by ptomasroos** [comment]
Same timeframe 

<img width="258" alt="screen shot 2017-08-23 at 05 56 09" src="https://user-images.githubusercontent.com/1064547/29598220-cef686a8-87c7-11e7-842b-23a959352409.png">

green = inits
yellow = bids
light blue = resp-empty
dark blue = impressions
pink = timeout
red = missing
orange = resp-ok

inits and bids are steady
response empty drops
response ok drops
response missing spikes
impressions are steady == inits
response timeout is lower than before

**Comment by ptomasroos** [comment]
After removing indexExchange which was introduce with the deploy things flipped

![screen shot 2017-08-23 at 09 55 15](https://user-images.githubusercontent.com/1064547/29604889-33d4bbf0-87e9-11e7-963b-070714e8a049.png)

Just thinking out loud if it could be related to https://github.com/prebid/Prebid.js/pull/1487/files

The other strange thing as you've noticing in the graph is that init's are steady == traffic but by running indexExchange other bidders are performing worse since these numbers are not percentages but absolute you see that response-OK is increasing after it got removed.

**Comment by ptomasroos** [comment]
Just wanna add for clarification

resp-timeout == bidder marked as bidTimedout
resp-empty == when receiving a bid empty or missing aka 200 but decided not to bid on the impression
resp-missing == no bid response in the events outputted by Prebid.js, i'm wondering how this even can happen since if there is no bidResponse with a bid or empty response and no bidTimedout. either there should be a response or there should be a timeout.

**Comment by ptomasroos** [comment]
https://github.com/prebid/Prebid.js/issues/1341 feels related as well.

**Comment by ehoch** [comment]
I'm seeing similar results and we're also running with Index Exchange. I'm going to see if I can narrow things down to the exact commit, but I would guess it's this since we're not running any non IX sizes:

https://github.com/prebid/Prebid.js/commit/d3cd2917c264d3388b2be45ee8e6b767e803ce5c

**Comment by mkendall07** [comment]
Thanks for the report @ptomasroos . I sent you an email.

**Comment by ehoch** [comment]
@mkendall07 Can confirm it's the commit I references. I'm running at a build at the commit right before https://github.com/prebid/Prebid.js/commit/d3cd2917c264d3388b2be45ee8e6b767e803ce5c and it's gone away.

Feel free to ping me on /r/adops Slack or email for more info. But can we get that reverted while you investigate? There's some other commits after it I'd love to test out.

**Comment by mkendall07** [comment]
Confirmed the issue. PR is here: https://github.com/prebid/Prebid.js/pull/1529

**Comment by ptomasroos** [comment]
Running current master all is working as expected
