### ISSUE TITLE
Misleading documentation for AOL adapter

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#152]
I have been checking some sites using AOL's adaptor and all of them use sizeId but my account manager didnt share those sizeIds. i have found an incomplete list by checking on publishers configuration:

sizeId   Size
170      300x250
225      728x90
154      160x600
3055    320x50
2988    320x100

Do you guys know where i can get this information for all sizes?

In the integration example they use these params:
{
                bidder: 'aol',
                params: {
                    placement: 'TO ADD',
                    network: 'TO ADD'
                }
            }
But in the documentation network doesn't appear i can tell there are some optional parameters but may be worth mention them on the documentation: http://prebid.org/dev-docs/bidders.html#aol

**Comment by prebid** [comment]
Hey @ialex, I got the below response from AOL:

"The size ID is actually not required. The size of the bid is determined by the placement ID that you are calling. So you can set size ID just to 0. It will be neglected anyway in your integration. The placement ID is what matters and the placement ID is supplied to publishers by our team. The placement ID implies the size ID that is defined in our system. "

Does that help?

**Comment by ialex** [comment]
@prebid Tried adding just placement and network to the configuration and removed alias and sizeId but the adaptor doesnt make any calls to adtech.com* i have seens on aplus.com the adaptor working maybe @nickjacob can help on this.

**Comment by mkendall07** [comment]
@ialex  which version of prebid.js are you using? It should be working with the latest release 0.5.0. Can you post your AOL configuration?

**Comment by nickjacob** [comment]
@ialex I tested it without the sizeId & alias (the adapter will generate an alias) and it worked/inferred the sizeId. Can you post your config? I've seen an issue before where if the network is set as a float (instead of a string, e.g `'10001.1'` it'll error out.

**Comment by ialex** [comment]
{
        "bidder": "aol",
        "params": {
          "network": "10202.1",
          "placement": "3634177"
        }
      }

Im using version 0.4.1 because i havent changed my config on some sites to remove casale or create an alias but i updated the AOL adaptor to latest on master, the network is set as string.

**Comment by nickjacob** [comment]
are you getting a 4XX from AOL or is it just not sending any request? Calls
should be to adtechus.com unless you override the "server" param

On Mon, Jan 11, 2016 at 5:41 PM, Alejandro Villanueva <
notifications@github.com> wrote:

> {
> "bidder": "aol",
> "params": {
> "network": "10202.1",
> "placement": "3634177"
> }
> }
>
> Im using version 0.4.1 because i havent changed my config on some sites to
> remove casale or create an alias but i updated the AOL adaptor to latest on
> master, the network is set as string.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prebid/Prebid.js/issues/152#issuecomment-170714633>.
>



-- 
 Lead Engineer, A Plus | nick@aplus.com | 617-680-0337

**Comment by ialex** [comment]
using the configuration posted it doesnt send any request to AOL (adtechus.com) im not overriding server param, if i add alias in the params it does send the request.

**Comment by nickjacob** [comment]
does the version you're using have the `_generateAlias` method in the aol adapter? In the first version of the aol adapter there wasn't any fallback for alias (eg @ this commit - https://github.com/prebid/Prebid.js/blob/07d9b849108794ff6509825a26b6c96e1e097b58/src/adapters/aol.js)

current line: https://github.com/prebid/Prebid.js/blob/master/src/adapters/aol.js#L133

**Comment by ialex** [comment]
Thanks for your support the adaptor was not the latest sorry for taking your time. using latest adaptor and providing just placement and network as string works properly.
