### ISSUE TITLE
Bidder alias breaking change

### ISSUE THREAD

**Issue by therazor** [prebid/Prebid.js#1528]
## Type of issue
Possible regression or undocumented breaking change

## Description
It was possible to introduce build-time bidder aliases prior to v0.26, but that method doesn't work anymore

## Steps to reproduce
Use build alias [discussed in issue 780](https://github.com/prebid/Prebid.js/issues/780#issuecomment-259646198)

### Expected results
Bidder is aliased

### Actual results
Bidder in not aliased 

## Platform details
0.26+

## Other information
https://github.com/prebid/Prebid.js/issues/780

**Comment by mkendall07** [comment]
@therazor 
Yes this was a breaking change, most likely not well communicated. Sorry for the confusion. Aliases can be added at runtime (http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.aliasBidder) or at build time (in the individual adapter module files).
