### ISSUE TITLE
Prebid not awarding auction wins to highest bidder

### ISSUE THREAD

**Issue by risenhoover** [prebid/Prebid.js#1531]
## Type of issue
Prebid.js seems to be running a corrupt auction consistently across my partners. 

## Description
In my prebid configuration, I have five DSPs, and the configuration is served via DFP with AdSense competing. I have recently brought on a new partner that bids significantly higher than the others. However, they are only winning a fraction of their total bids.

From Google Analytics, I see the following numbers: bids: 17K, timeouts: 6.7K, wins: 1.5K. This despite the fact that their bids are much higher than other prebid partners, and much higher than average adsense rpm numbers.  It seems like they should have 17K - 6.7K - 1.5K= 8.8k more wins that are actually recorded.

## Steps to reproduce
Here is a test page: https://fintel.io/activists?pbjs_debug=true

### Expected results
I would expect to see 8.8K more wins. 

## Other information
<img width="902" alt="screen shot 2017-08-24 at 8 15 55 am" src="https://user-images.githubusercontent.com/918174/29673645-b7159780-88a4-11e7-815a-3cc0e335e01e.png">

**Comment by risenhoover** [comment]
The auction in question is a mobile placement that replaces the top of page adsense wide banner on mobile deliveries.

**Comment by mkendall07** [comment]
Sorry not really following your numbers. Do you have bidder specific information on CPM? Also google analytics samples (https://support.google.com/analytics/answer/2637192?hl=en) so you shouldn't rely on the data for revenue purposes. 

I'd recommend enabling sending all bids, and then using hte DFP keyword reports to investigate further.

**Comment by mkendall07** [comment]
also check your line item set up in DFP - you could be missing price buckets or rounding problems could cause you to lose vs adX etc.

**Comment by risenhoover** [comment]
Thanks for responding so quickly. I've checked and rechecked the price buckets and I will check them again. What specifically should I be looking for? How should I check for rounding errors? 

Regarding the GA numbers: I understand that GA samples, but even so, the discrepancy seems to be statistically significant. The partner with the highest bid for every auction they participate in only wins 10% of those auctions. How can this happen?

**Comment by mkendall07** [comment]
did you find anything on this? By rounding errors I meant that that your price buckets in DFP didn't match what prebid was sending.
