### ISSUE TITLE
Display ad manually

### ISSUE THREAD

**Issue by chensMMG** [prebid/Prebid.js#1532]
## Type of issue
Prebid.js with fraud detection.

## Description
I have a product that use fraud detection functions, I need to run prebid.js script and fraud detection simultaneously and show the ad only for clients which are not detected as fraud.
Most important that the ad appears only after the fraud detection is finished.
Do you have any solution for this case?

**Comment by mkendall07** [comment]
No, I don't think we can support this type of use case today.
