### ISSUE TITLE
Sending Regs object  in  bid request  to prebid server

### ISSUE THREAD

**Issue by PubMatic-OpenWrap** [prebid/Prebid.js#1539]
## Type of issue

Feature request
## Description

To send Regs object to Prebid Server, Regs object specifies any industry, legal,  or governmental regulations in force for the request. The  Regs object contains _"coppa"_ flag  which signals
 whether or not the request falls under Children’s Online Privacy Protection Act (“COPPA”) compliance 

## Other information

https://www.iab.com/wp-content/uploads/2015/06/OpenRTB-API-Specification-Version-2-3.pdf, Section 3.2.16

**Comment by mkendall07** [comment]
thanks. Feel free to open a pull request.
