### ISSUE TITLE
AOL calls are cancelled on Chrome for 300ms timeout

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#1547]
## Type of issue

Bug
## Description

![aol_issue](https://user-images.githubusercontent.com/8835908/29873282-63c1b418-8db0-11e7-937a-e6088d5366c9.png)
When you keep timeout value lesser, example 300ms.
Calls to AOL are aborted.
This was observed on version 0.24.1

## Steps to reproduce

When you keep timeout value lesser, example 300ms.
Calls to AOL are aborted.
This was observed on version 0.24.1

### Expected results
Calls to AOL are aborted.

### Actual results
Calls to AOL should not be aborted.

## Platform details

Prebid 0.24.1
Chrome latest
Windows 8

**Comment by mkendall07** [comment]
We cannot control how long a partner takes to respond to a bid. We cancel XHR requests after the timeout, so in this case AOL is taking longer than the 300ms timeout. You should increase the timeout if you want AOL bids if that's the latency being observed. You can also contact AOL.
