### ISSUE TITLE
StorageManager works with string values only

### ISSUE THREAD

**Issue by sergey-roxot** [prebid/Prebid.js#1548]
## Type of issue

Question

## Description

When I set integer value to local storage by StorageManager, I cant get it back. StorageManager's get method returns an empty array.  

## Issue
Are there any reasons StorageManager works only with string values?
https://github.com/prebid/Prebid.js/blob/c63673c97521c0b03209f7ea471939e3a24ec1e3/src/storagemanager.js#L25

**Comment by protonate** [comment]
This should certainly do something other than dropping ints on the floor, will take a look at it.

**Comment by matthewlane** [comment]
Looks like storagemanager.js was removed at some point, closing
