### ISSUE TITLE
IndexExchange tests should not depend on port

### ISSUE THREAD

**Issue by dbemiller** [prebid/Prebid.js#1553]
## Type of issue
Bug

## Description
When the default Karma port is in use, the IndexExchange tests fail.

## Steps to reproduce
Change the karma.conf port in `karma.conf.maker.js` to point to 9877. This emulates the Karma behavior if port 9876 is blocked. Then run `gulp test`. See also: the 'port' option in the Karma docs: http://karma-runner.github.io/1.0/config/configuration-file.html

### Expected results
Tests should pass

### Actual results
Tests fail with the following:

```
HeadlessChrome 0.0.0 (Mac OS X 10.12.5) indexExchange adapter - Video request to prebid should make request with specified values when valid HTML5 required bid request parameters are present FAILED
	AssertionError: expected 'http://localhost:9877/?id=37693349' to contain 'http://localhost:9876/'
	    at Context.<anonymous> (http://localhost:9877webpack:///test/spec/modules/indexExchangeBidAdapter_video_spec.js:80:60 <- test/spec/modules/indexExchangeBidAdapter_video_spec.js:12843:72)
HeadlessChrome 0.0.0 (Mac OS X 10.12.5) indexExchange adapter - Video request to prebid should make request with specified values when valid FLASH required bid request parameters are present FAILED
	AssertionError: expected 'http://localhost:9877/?id=37693349' to contain 'http://localhost:9876/'
	    at Context.<anonymous> (http://localhost:9877webpack:///test/spec/modules/indexExchangeBidAdapter_video_spec.js:119:60 <- test/spec/modules/indexExchangeBidAdapter_video_spec.js:12882:72)
```

## Other information
Same issue as #1300... just with different tests.

**Comment by matthewlane** [comment]
Closing with the IndexExchange adapter and test not in 1.x. Will make sure ports aren't in newly submitted tests
