### ISSUE TITLE
PreBid AMP Implementation cross origin issue with remote.html

### ISSUE THREAD

**Issue by jordanhines** [prebid/Prebid.js#1562]
I'm using amazon S3 to host remote.html.

But I'm getting following error in browser console ( draw3p function ), which fails sending the creative to AMP page to render, I do see bidder responses coming through for the partners I'm running.

`Error: Blocked a frame with origin "https://s3.amazonaws.com" from accessing a cross-origin frame.
    at Zc (https://3p.ampproject.net/1504040004635/f.js:82:23)
    at HTMLIFrameElement.<anonymous> (https://3p.ampproject.net/1504040004635/f.js:81:346)`

Any thoughts on what I should be doing to resolve this?

thanks in advance.

**Comment by mkendall07** [comment]
@jordanhines make sure you are using the right creative type (ie this one https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/amp/creative.html)

**Comment by jordanhines** [comment]
@mkendall07 yes, using the right creative. wondering if I have a set any CORS configuration on S3 bucket.

thank you

**Comment by jordanhines** [comment]
Sorry, the issue was caused by a different <amp-ad> unit provided by Media.net which is not a placement participating in PreBid. No issue here. Closing the thread.

thank you
