### ISSUE TITLE
Huddled Masses adaptor on Download page 

### ISSUE THREAD

**Issue by HuddledMasses** [prebid/Prebid.js#1586]
## Description
We can see Huddled Masses is only placed in Partner list, but we can’t get the customized prebid.js of Huddled Masses. What is the reason for that?
Please let us know ASAP how to fix it. 

@bretg @Prebid-Vertoz could you please check?

**Comment by mkendall07** [comment]
@HuddledMasses 
You need to create a bidder params page on the docs site for you bidder to be listed in the downloads page now.

Please submit a PR to the [docs repo](https://github.com/prebid/prebid.github.io) to add a file for your adapter to the [bidders directory](https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders) so your adapter's params will appear on the [bidders page](http://prebid.org/dev-docs/bidders.html).
