### ISSUE TITLE
No winnings bids available

### ISSUE THREAD

**Issue by krackmoe** [prebid/Prebid.js#1590]
## Description
I am using the javascript snippets to show all bids and show all winning bids. The response of my prebid script returns some bidders that return "Bid available". But if i want to see the winning bidders i dont get any winning bidder. Is this a bug in the prebid library or am i doing something wrong?

### Expected results
Winning bidder

### Actual results
No winning bidder

## Platform details
prebid.js v0.29.0-pre
Updated : 2017-09-11
Chrome
npm

**Comment by mkendall07** [comment]
we can't help troubleshoot without further information. A test or live page is usually best to figure out what's going on.
