### ISSUE TITLE
indexExchange/Casale's adapter not working...

### ISSUE THREAD

**Issue by investorguide-david** [prebid/Prebid.js#160]
tried using the latest dist version (today's) and the previous build.  Tried matching the docs, as well as a ridiculously huge number of other permutations.  The call to cygnus on casalemedia.com never even shows in inspect network which leads me to believe it's something in prebid.

```javascript
bids: [
  { bidder: 'indexExchange', params: { id:"2", width:300, height:250, timeout: '300', siteID: 'ID' } },
  { bidder: 'indexExchange', timeout: '300', siteID: 'ID', params: { id:"2", width:300, height:250, timeout: '300', siteID: 'ID' } }
]

```
ID is the normal int from IE.  

We have other bidders confirmed working.  Index/Casale does not.

Tried with ````?pbjs_debug=true```` and debugging reports ````adloader.js:loadScript: Error attempting to request empty URL ````

**Comment by investorguide-david** [comment]
tried with ````?pbjs_debug=true````

removed ````bidder: 'index'```` and ````bidder: 'indexexchange'````.  However, debugging reports ````adloader.js:loadScript: Error attempting to request empty URL ````

**Comment by mkendall07** [comment]
Thanks @investorguide-david  for reporting the issue. Could you please post your configuration for IndexExchange?

**Comment by investorguide-david** [comment]
I tried a ton of permutations (see above in the original post)

**Comment by mkendall07** [comment]
Ah missed that, thanks. Please try changing `siteID` & timeout to a number (omit the quotes). 

```{
	bidder: 'indexExchange',
	params: {
		id: "2",
		timeout: 300,
		siteID: ID
	}
```

**Comment by investorguide-david** [comment]
heh, that was it.  Looks like you already updated the example too.  Closing.

**Comment by chaqu170** [comment]
I know this is closed already, but in our own experience, especially with manual testing, we forget to make sure that the width and height values are numbers instead of strings.

So changing something like this
`"sizes":[["728","90"]]`
to this
`"sizes":[[728,90]]`
worked for us, in addition to changing siteID to a number.
