### ISSUE TITLE
Prebid + DFP ignoring bids that aren't multiples of $0.10

### ISSUE THREAD

**Issue by raustaburk** [prebid/Prebid.js#1607]
I don't know if this is a bug or an issue with my setup. I used the DFP API to set up 900 line items ranging from $0.01 to $9.00, but the only ones delivering are multiples of $0.10 even though the setup is identical for all of them.

I have my granularity set to $0.01 with a custom price bucket (see code below), but I don't think that's the problem. Looking at my ad partner's numbers they're only winning about 2-5% of what they bid on, and they're only competing against AdSense, so I believe bids that aren't multiples of $0.10 aren't even making it to DFP.

This is my granularity code. I originally used pbjs.setPriceGranularity(customGranularity) before changing it to the following, but neither solved the problem.
```
const customGranularity = {
                              "buckets" : [{
                                  "precision": 2,
                                  "min" : 0,
                                  "max" : 9,
                                  "increment" : 0.01
                                }]
                            };
                            pbjs.setConfig({
                                priceGranularity: customGranularity
                            });
```

Any ideas? Thanks.

**Comment by mkendall07** [comment]
what's the keys getting sent to the adserver? Do you have a test page? The best way to debug this is to use DFP debug console to see what is winning.

**Comment by raustaburk** [comment]
How can I see what keys prebid is sending? Is there a raw output somewhere?

I have it running live on http://animalinyou.com

This is what I get when I run the DFP debug console:

> Overlay status: Displayed
> Ad unit did not fetch. 
> Ad unit did not render. 
> Ad fetch count: 0
> Iframe type: FriendlyIframe
> Query ID: none

It's rendering AdSense and the right ad units, and my ad partners are reporting a few impressions. However, they're only winning about 5% of the impressions so I think I'm just not seeing any of their ads.

**Comment by raustaburk** [comment]
How do I see the raw keys being sent to the server? I tried pbjs_debug=true, and I see that it's requesting bids from Sovrn and Conversant as well as recording GA events, but it doesn't actually say what the bids are.

DFP console shows that everything is working fine but I'm only getting AdSense.

No test page, it's live here: http://animalinyou.com

**Comment by raustaburk** [comment]
I figured it out, I was setting the granularity after requesting the bids. After moving setConfig() to the top everything works fine.
