### ISSUE TITLE
bidder vs adapter [feature request]

### ISSUE THREAD

**Issue by investorguide-david** [prebid/Prebid.js#161]
Right now, an adapter implies that the bidder is also the exchange using their own adapter.  We've come across at least 1 DSP that is requesting to use AppNexus's adapter.  The default should be that the bidder = adapter, but you should be able to specify the bidder as someone else, despite what adapter they're using.

**Comment by mkendall07** [comment]
@investorguide-david 
Thanks for the suggestion. Have you reviewed the alias bidder functionality? It should accomplish what you are trying to do for the AppNexus adapter. https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/gpt_aliasingBidder.html#L77

**Comment by investorguide-david** [comment]
wow, that's literally exactly what we were looking for.  Thanks much.  Closing.

**Comment by investorguide-david** [comment]
@mkendall07 I know the issue is closed, but this raises another question... I know now that you just call the bidder alias function so that BRT can have its own attribution while using AppNexus' adapter (we pushed them out of staging into live recently). Does this mean we as a pub can take any demand that's on AppNexus with eCPM inventory and traffic them through AppNexus' Prebid adapter with an alias?  Or does each one of these partners have to have something enabled with AppNexus for HB functionality?

**Comment by mkendall07** [comment]
@investorguide-david 

It's possible to alias multiple AppNexus adapters with the current functionality, there isn't anything required to be enabled for it to work. Hope that helps.
