### ISSUE TITLE
Support DFP GPT Light

### ISSUE THREAD

**Issue by pribeh** [prebid/Prebid.js#1612]
##Feature request

Support for DFP / GPT Light: https://developers.google.com/doubleclick-gpt/gpt_light

Here's a rundown on how someone managed to use a shim to get prebid working with GPT light: https://www.captaincodeman.com/2017/05/03/prebidjs-header-bidding-with-dfp-light-glade

Any thoughts? Are the maintainers interested in supporting this?

**Comment by mkendall07** [comment]
sounds like a good idea to have support for this. Thanks for bringing it up. We'll take a look

**Comment by mercuryyy** [comment]
This looks pretty good. @mkendall07  @prebid maybe add native support to GPT light in PB 1.0 ?

**Comment by mkendall07** [comment]
good idea for a module. We accept PRs.
