### ISSUE TITLE
Question: The Xaxis XHB module is always setting the bid response cpm to 0. Is this excluding them from winning any bids?

### ISSUE THREAD

**Issue by JohannesEH** [prebid/Prebid.js#1620]
## Question

In [line 135 of xhbBidAdapter.js](https://github.com/prebid/Prebid.js/blob/434956353fec8c0155e2e5505d34ac81d1a9b050/modules/xhbBidAdapter.js#L135) it seems as if the cpm is set to 0. Does this exclude the xaxis bid adapter from being part of the winning bids. I can see at least one place ([in line 93 of targeting.js](https://github.com/prebid/Prebid.js/blob/434956353fec8c0155e2e5505d34ac81d1a9b050/src/targeting.js#L93)) where bid responses must have a cpm > 0 to be considered. Should bids be ale to win if they are returning cpm 0?

**Comment by mkendall07** [comment]
Xaxis built their adapter to always set a special key (see here https://github.com/prebid/Prebid.js/blob/434956353fec8c0155e2e5505d34ac81d1a9b050/modules/xhbBidAdapter.js#L17) So even if the bid doesn't "win" the auction the key is still set.

**Comment by JohannesEH** [comment]
Ok, but doesn't that defeat the purpose of prebid/postbid? I mean, I don't know what their bid was, so how do I know I'm making any money in my ad server if I choose them over a direct campaign or any backfill partners I might have setup? Also, they do send a CPM and an AD back in the response so why not just use those?

**Comment by mkendall07** [comment]
That is true, however, the model is a pre negotiated deal so you should have some idea of it's value to you. This can be discussed with Xaxis of course.

**Comment by mkendall07** [comment]
closing as answered.
