### ISSUE TITLE
 difficulty with the prebid setup / with lazy load

### ISSUE THREAD

**Issue by LarsVestergaard** [prebid/Prebid.js#1622]
I am reaching out to you because I have a bit difficulty with the prebid setup that I hope somebody may be able to help me with.?
I am trying to set up prebid on a site, that is using DFP as adserver and has a scroll-based lazy load setup. I have a bit problem with the "bidsBackHandler: sendAdserverRequest" part since each adslot loads separately in a lazy load setup and not in one single request as in the basic example at prebid.org.

I hope someone can help

**Comment by mkendall07** [comment]
You can invoke prebid individually per adslot if you want. 
Check out the examples here: http://prebid.org/dev-docs/examples/adunit-refresh.html

Specifically take a look at the `refreshBid1` method.

**Comment by bretg** [comment]
You can populate AdUnits one-at-a-time, but note that Prebid 0.x doesn't support concurrent auctions, so the page currently has to make sure that no more than one requestBids() is outstanding. This is fixed with [Prebid 1.0](http://prebid.org/blog/announcing-prebid-1-0).

**Comment by LarsVestergaard** [comment]
Thanks guys, we will look into it

**Comment by YOzaz** [comment]
Just for the matter of interest - @bretg, is it still true? I see there's a queue builder inside requestBids() function for parallel calls (checking 0.32.0).

**Comment by snapwich** [comment]
That queue builder has been there for some time.  You can do requestBids more than once, however the other auctions will be deferred until the previous finish; that is until 1.0 lands with support for true concurrent auctions.

**Comment by YOzaz** [comment]
Brilliant, thank you!

**Comment by barmbrus** [comment]
@bretg and @snapwich, is it actually required to start separate auctions for lazy loading adslots?

Can one not just load the ads by individually executing the following GPT request when that slot comes into view?
`googletag.pubads().refresh([lazyLoadingAdSlot]);`

So, have a prebid auction with all adslots and only load the ads when needed.

**Comment by YOzaz** [comment]
@barmbrus in that case you're in a risk of hitting timeout / expiry for an ad correlator. Or in other words, winning ads do expire within short period of time, and at the moment when you'd be executing `refresh` call (or `renderAd` through DFP) - it may be rejected by the bidder.
