### ISSUE TITLE
Please include Centro adapter on the download page http://prebid.org/download.html

### ISSUE THREAD

**Issue by Niksok** [prebid/Prebid.js#1623]
## Question

Hello Prebid team!
Can you please to include Centro adapter to this download page http://prebid.org/download.html?

**Comment by mkendall07** [comment]
@Niksok 
It looks like your adapter documentation md file is formatted wrong here: https://raw.githubusercontent.com/prebid/prebid.github.io/master/dev-docs/bidders/centro.md

Please remove the `+` from each line. That should resolve the issue on the download page.

**Comment by mkendall07** [comment]
this is resolved.
