### ISSUE TITLE
How to destroy prebid+googletag slot?

### ISSUE THREAD

**Issue by edejin** [prebid/Prebid.js#1636]
## Type of issue
question

## Description
How to destroy prebid+googletag slot?

## Steps to reproduce
googletag.destroySlots(rightSlot) return false

## Test page
http://jsbin.com/hazumaduba/edit?js,output

**Comment by mkendall07** [comment]
This is DFP question, but I think the correct answer is you need to pass an array like so:
`console.log('destroy', googletag.destroySlots([rightSlot]));`
That seems to return `true` in your test. 
Reference https://developers.google.com/doubleclick-gpt/reference#googletag.destroySlots
