### ISSUE TITLE
Occasional test fails - Fake XHR

### ISSUE THREAD

**Issue by snapwich** [prebid/Prebid.js#1639]
## Type of issue
**Bug**

## Description
This issue is to track a persistent issue with the hooks failing and breaking the tests:
```Bash
HeadlessChrome 0.0.0 (Mac OS X 10.11.6) Trion adapter tests "after each" hook FAILED
	Error: Uncaught TypeError: Fake XHR onreadystatechange handler threw exception: Cannot read property 'seatbid' of undefined (node_modules/sinon/pkg/sinon.js:4469)
HeadlessChrome 0.0.0 (Mac OS X 10.11.6): Executed 1053 of 1430 (1 FAILED) (skipped 1) (0 secs / 2.904 secs)
HeadlessChrome 0.0.0 (Mac OS X 10.11.6) Trion adapter tests "after each" hook FAILED
	Error: Uncaught TypeError: Fake XHR onreadystatechange handler threw exception: CannotHeadlessChrome 0.0.0 (Mac OS X 10.11.6): Executed 1053 of 1430 (1 FAILED) (skipped 1) (18.494 secs / 2.904 secs)
```

## Steps to reproduce
Run the tests a lot; not easy to reproduce otherwise.

## Platform details
OSX, node 6.9.1, npm 3.10.8; but also seems to break occasionally in Travis-CI

## Other information
Some similar issues fixed in #1626, but this issue remains and seems a bit more difficult to track down the cause of.

**Comment by mkendall07** [comment]
Problem might fix itself with prebid 1.0. Not sure it's worth tracking down or not at this point.

**Comment by tedrand** [comment]
Is there a way to re-run the Travis-CI tests when this happens on a PR update?

**Comment by dbemiller** [comment]
@tedrand I think one of the project collaborators have to do it.

I think by now everyone who reviews prebid PRs knows about this... so if tests fail, we always check to see if it's a true failure.

I agree with @mkendall07, though... unit tests for adapters are _much_ less complicated in prebid 1.0. There's a good chance these will fix themselves naturally.

**Comment by snapwich** [comment]
It should be noted that this is still an issue in prebid 1.0. My latest pull-request #1976 failed twice in a row due to these errors before passing on the third try.
