### ISSUE TITLE
AppNexusAst adaptor no longer supports aliasing via API

### ISSUE THREAD

**Issue by ehoch** [prebid/Prebid.js#1643]
## Type of issue
bug

## Description
Since the new 1.0 adaptor changes (a4d3ce7dfc6d0b19d1876e8060282f4eac4010cf), AppnexusAst no longer supports aliasing via the pbjs.aliasBidder API command. Using the new aliases: [] syntax in the registerBidder does work, however.

**Comment by jaiminpanchal27** [comment]
Thanks @ehoch for reporting this. We will fix this asap.

**Comment by gramorris** [comment]
This is the case with 0.29 also.

**Comment by jaiminpanchal27** [comment]
This is fixed in https://github.com/prebid/Prebid.js/releases/tag/0.30.1
