### ISSUE TITLE
Improve Bid object

### ISSUE THREAD

**Issue by kir-roxot** [prebid/Prebid.js#1647]
## Type of issue
Feature request

## Description
We think that currently bidders do not provide enough information about their bids to address all publisher’s needs. OpenRTB, which is a de facto standard in the S2S world, has many important parameters that are not available in prebid.js. We want to continue improving communication between publishers and demand partners and suggest adding the following OpenRTB parameters in the Bid object:
- iurl
- adomain
- cid

**Comment by mkendall07** [comment]
@kir-roxot 
thanks for the suggestion. We accept PRs, i think this could be easily added to the existing bid.
