### ISSUE TITLE
The standard OpenRTB adapter

### ISSUE THREAD

**Issue by elljoh** [prebid/Prebid.js#1648]
## Type of issue
* **Question**

## Description

#891 mentions the "standard OpenRTB adapter" per the following:
> Any adapter using the OpenRTB protocol must alias the standard OpenRTB adapter provided by the Prebid core framework.

Could someone point to a module/branch/repo for the standard OpenRTB adapter?

Thanks.

**Comment by mkendall07** [comment]
hey @elljoh we didn't find too many bidders that are using ORTB protocol so we did not build it. that said if you have the time to implement a spec for it, that probably is helpful. I would suggest using the baseAdapter to implement the openRTBBase adapter, which other adapters could then implement a spec for.

**Comment by elljoh** [comment]
Ok. Thanks. I'm looking into rationalizing the Yieldbot request/response API to make use of OpenRTB since we have a few things to do in order to support #891.

**Comment by elljoh** [comment]
Thanks

**Comment by chefbenjamin** [comment]
this would be an interesting addition to prebid overall and something we would be interested in testing.
