### ISSUE TITLE
Make all bidResponse parameters required

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#1649]
## Type of issue
Make Prebid 1.0 treat more bidResponse fields as required

## Description
We agreed while specing the interface for Prebid 1.0 that may more parameters are required for bidResponses.  All parameters noted as 'required' in the bid object table should cause the bid to be rejected if not present. This will enable it to be caught by unit tests.

http://prebid.org/dev-docs/bidder-adapter-1.html#interpreting-the-response

## Steps to reproduce
Currently there are several parameters not required

```
const bidResponse = {
        requestId: bidRequest.bidId,
        bidderCode: spec.code,
        cpm: CPM,
        width: WIDTH,
        height: HEIGHT,
        creativeId: CREATIVE_ID,
        dealId: DEAL_ID,
        referrer: REFERER,
        ad: CREATIVE_BODY
    };
```

### Expected results

The bid response fail somehow because there are 3 missing params:
```
        currency: CURRENCY,
        netRevenue: true,
        ttl: TIME_TO_LIVE,
```
### Actual results

Doesn't fail.

It's not clear how the adapter would learn about the missing attributes. Need to discuss.

**Comment by bretg** [comment]
Discussed with the team -- the platform will log missing attributes to the console.

**Comment by jaiminpanchal27** [comment]
Closing this as its done in this PR https://github.com/prebid/Prebid.js/pull/1738
