### ISSUE TITLE
Unit tests failing in IE 10

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#1656]
## Type of issue
Bug

## Description
Usage of `__lookupSetter__` is preventing tests to run in IE 10.
https://github.com/prebid/Prebid.js/blob/master/test/spec/utils_spec.js#L530

Log:
IE 10.0.0 (Windows 8 0.0.0) ERROR
  Object doesn't support property or method '__lookupSetter__'
  at webpack:///test/spec/utils_spec.js:530:4 <- test/spec/utils_spec.js:639

## Steps to reproduce
Run tests in IE 10

## Other information
@grevory @harpere 
Introduced in #1229

**Comment by harpere** [comment]
Since Prebid is no longer officially supporting IE 10, this is no longer an issue.   Uncommenting these tests: #1958

**Comment by mkendall07** [comment]
@harpere 
Not sure we decided that yet?
