### ISSUE TITLE
Prebid 1.0 bidder adapter, no library loading at runtime? 

### ISSUE THREAD

**Issue by guillaume-sticky** [prebid/Prebid.js#1659]
## Description
Question regarding the new bidder adapter implementation for Prebid 1.0 

## Platform details
Prebid 1.0

I'm updating our bidder adapter  for freewheel-ssp. 
Before Prebid 1.0 we were using the adloader to load our librarie at run time, allowing us to create and send the ad request and fill a bid response with the ad.

I can see in the [new requirements ](http://prebid.org/dev-docs/bidder-adapter-1.html#required-adapter-conventions) that all code must be present in the adapter and no library can be loaded at runtime.

So the question is:  How are we suppose to use our library if we can't load it at runtime?
Is there a mecanism to include it in the prebid.js build only if our bidder adapter has been enabled?

**Comment by mkendall07** [comment]
@guillaume-sticky 
We'd like you to add the minimum amount of JS needed directly into the bidder module to make a Ajax (XHR) call to request for bids. At this time, we don't have a mechanism to allow 3rd party javascript to run to fetch demand.

**Comment by guillaume-sticky** [comment]
That was my guess,  we'll see what we can do. Thanks for your answer.

**Comment by bretg** [comment]
We'll leave this ticket open until prebid.org describes the requirement for 3rd party javascript.
