### ISSUE TITLE
Document callback events

### ISSUE THREAD

**Issue by prebid** [prebid/Prebid.js#167]

**Comment by protonate** [comment]
Events are emitted that can be handled by the bid adapter callbacks. These events are:
```
    allRequestedBidsBack
    adUnitBidsBack
    bidWon
```

Handlers can be registered for this events using the `pbjs.onEvent` API call. To de-register a handler use the `pbjs.offEvent` API call.

More info is available PR #204 where the `onEvent` and `offEvent` are defined, including an example of how to implement this API methods.

NOTE: the `addCallback` and `removeCallback` API methods are now deprecated in favor of `onEvent` and `offEvent`.

Closing this, please comment and reopen if further info or clarification is needed.
