### ISSUE TITLE
Prebid in AMP without master iframe

### ISSUE THREAD

**Issue by alexmrf** [prebid/Prebid.js#1672]
## Type of issue
Question

## Description
The solution proposed for AMP in the [documentation](http://prebid.org/dev-docs/how-prebid-on-amp-works.html) uses a master iframe to load prebid only once and do all the bids from this iframe.
My question is, **which are the drawbacks of loading prebid and doing the bid in every single amp-ad isolatedly**?

**Comment by protonate** [comment]
This would work at the cost of making additional requests for Prebid.js from each iframe, though this may be acceptable depending on your setup as additional requests would load from cache. It would also put your configuration out of the main development path, which wouldn't amount to much difference today, but the road map includes incorporating Fast Fetch and possibly making single bid requests for multiple ad slots. In short, if you have a compelling reason or curiosity, try it, and let us know how it works out.

**Comment by alexmrf** [comment]
OK thanks!!

BTW, *Fast Fetch* prevent the usage of a custom `remote.html`. How do you plan to solve this?

**Comment by protonate** [comment]
There are some details to work out but the intended AMP [Real Time Callout](https://github.com/ampproject/amphtml/issues/11321) mechanism will provide a means for publishers to supply their own targeting data. Prebid.js works by running an auction and then setting targeting keys on ad slots based on the results of that auction, so RTC would be an integration point for Prebid.js that should work with AMP Fast Fetch.
