### ISSUE TITLE
Prebid 1.0 video bid validation throws error

### ISSUE THREAD

**Issue by jsalis** [prebid/Prebid.js#1679]
## Type of issue
Bug

## Description
Validation for video bids throws an error.

![image](https://user-images.githubusercontent.com/5342031/31460033-03f7804a-ae93-11e7-962c-5d66d15f0b84.png)

## Steps to reproduce

Add the Beachfront bid adapter to the video example page. (I think any valid video bid will reproduce it)
Run the auction.

```javascript
var videoAdUnit = {
    code: 'video1',
    sizes: [640, 480],
    mediaType: 'video',
    bids: [{
        bidder: 'appnexusAst',
        params: {
            placementId: '9333431',
            video: {
                skipppable: false,
                playback_methods: ['auto_play_sound_off']
            }
        }
    }, {
        bidder: 'beachfront',
        params: {
            bidfloor: 0.01,
            appId: '206eca8c-f7c5-46fd-c848-b8f041214e77'
        }
    }]
};
```

## Other information
#1680

**Comment by jaiminpanchal27** [comment]
Fixed and merged in #1680
