### ISSUE TITLE
Renaming of Huddled Masses adapter

### ISSUE THREAD

**Issue by HuddledMasses** [prebid/Prebid.js#1685]
## Question
What is the process of renaming our existing Huddled Masses adapter? 

## Description
Hi Team, we are planning to move to new domain. What are the exact steps, requiremends to rename the adapter and how much time will it take?

**Comment by mkendall07** [comment]
should be straight forward. Update your adapter with the new name, renaming the file at the same time. 

Please use the prebid 1.0 adapter spec when rebuilding the adapter. http://prebid.org/dev-docs/bidder-adapter-1.html

Consider adding an alias for huddleMasses previous adapter code to the new one to help pubs transition.

**Comment by HuddledMasses** [comment]
@mkendall07 thank you! 
Here is our pull request: #1701 
How long will it take, to review and to publish?

**Comment by mkendall07** [comment]
thanks. Are you able to update to the new bidder format? See https://github.com/prebid/Prebid.js/blob/master/modules/appnexusAstBidAdapter.js for example.

That is preferred.

**Comment by dbemiller** [comment]
I merged this. Just beware @HuddledMasses that the adapter isn't compatible with 1.0... so when we merge in the prebid-1.0 branch, it'll be deleted.

If you want it to stay in the project longer than a month or two, please submit a PR to update your adapter: http://prebid.org/dev-docs/bidder-adapter-1.html

**Comment by dbemiller** [comment]
We're planning to release later today, so it'll be available live soon.
