### ISSUE TITLE
Video - javascript error when Rubicon is the only bidder and it returns empty bid or error

### ISSUE THREAD

**Issue by gwtomlinson** [prebid/Prebid.js#1688]
## Type of issue
Bug

## Description
For video header bidding, when Rubicon is the only bidder configured and it returns an empty bid or error, we get a javascript error:

`ERROR: Error executing bidsBackHandler" TypeError: Cannot read property 'adserverTargeting' of undefined`

in `pbjs.adServers.dfp.buildVideoUrl`. Video doesn't play.

## Steps to reproduce
Take the example JWPlayer code from [here](http://prebid.org/examples/video/jwPlayerPrebid.html), replace appnexusAst bidder with rubicon and invalid IDs (to force an error), turn on debugging, view console.

## Test page
[jsfiddle](https://jsfiddle.net/bdv8zgf7/)

### Expected results
No javascript error, video should still play. `pbjs.adServers.dfp.buildVideoUrl` should still return a valid URL.

### Actual results
Javascript error, video doesn't play. `pbjs.adServers.dfp.buildVideoUrl` doesn't return.

## Platform details
prebid v0.30.1.
Tested on MacOS 10.12.6, Chrome 61.

**Comment by gwtomlinson** [comment]
![screen shot 2017-10-13 at 09 07 07](https://user-images.githubusercontent.com/10497208/31536283-ef34f34a-aff5-11e7-9c84-0a55ad23321f.png)

**Comment by mkendall07** [comment]
I think this issue is consistent across video bidders, so most likely not a rubicon adapter issue.
