### ISSUE TITLE
Adjustment of Price from Bidders

### ISSUE THREAD

**Issue by prebid** [prebid/Prebid.js#17]
As a publisher, I'd like to adjust the price from bidders to account for the fee, so that what it's bidding reflects what I'd make. This is because some bidders today bid in the gross amount (vs net).

**Comment by ehoch** [comment]
Is there a currently recommended way of doing this?

**Comment by prebid** [comment]
Hi @ehoch, this is one of the features high in our queue. We're working on analytics currently and this will be our next feature to work on.
