### ISSUE TITLE
Support / Targeted Browsers?

### ISSUE THREAD

**Issue by ericperez** [prebid/Prebid.js#170]
I searched through the docs but I could not find anywhere that states which browsers are supported and/or targeted for use with Prebid.js. Are those published anywhere? Thanks.

**Comment by ojotoxy** [comment]
In my testing it does run without errors in IE8, but I have only tried a few adapters.

**Comment by protonate** [comment]
At this point we are supporting IE9+ and modern browsers. IE8 is expected to require a polyfill in some cases which is not yet in place. We will update the README with this info, thanks @ericperez for the question.

**Comment by protonate** [comment]
README has been updated [here](https://github.com/prebid/Prebid.js/commit/fec58d1314a154cba2b6f69474edce98d30c5bf6). Closing.
