### ISSUE TITLE
AppnexusAST video config

### ISSUE THREAD

**Issue by GEMI** [prebid/Prebid.js#1700]
## Question
How should I pass in a custom to video renderer when using AppnexusAST?

## Description
Video bids have very limited parameters:
```
        bidder: 'appnexusAst',
        params: {
          placementId: '5768085',
          video: {
            skippable: true,
            playback_method: [ 'auto_play_sound_off' ]
          }
        }
```

However, the video player itself can accept many settings:

```
    "adText": "Ad",
    "showMute": true,
    "showVolume": true,
    "showProgressBar": false,
    "allowFullscreen": true,
    ...
```

Right now it seems that this config is hardcoded inside the **appnexusAstBidAdapter.js** file.

`config: { adText: 'AppNexus Outstream Video Ad via Prebid.js' },`

**Comment by matthewlane** [comment]
Hi, looks like passing custom render options isn't currently supported. I've made a note to address this and will link to this ticket when the update is submitted, though PRs are always welcome
