### ISSUE TITLE
Analytics adapters use ajax module that implements a timeout for requests. Some data might be lost

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#1718]
## Type of issue
Bug

## Description
Some of the analytics adapters are using ajax.js to send ajax requests. But ajax.js implements timeout that is equal to the timeout of the auction. It leads to some of the analytical data being lost.

The initial idea behind t/o was to improve page's performance by aborting the bid requests that were too late to respond so they won't affect the auction outcome. I don't think that the same logic can be applied to analytic queries.

I see two issues here:

1) It seems to be impossible to change t/o for a specific ajax request. Ajax.js always uses the global option
2) Developers of analytics adapters seem to be oblivious to the existence of the timeout

It's easy to fix the first issue, by allowing to set timeout in options array (last argument of function call). Fixing the second issue can be trickier. One option I can think of is implementing another ajax function specifically for analytics adapters that won't have any t/o at all. It can use the original ajax function ofc, just with different t/o parameter.

**Comment by mkendall07** [comment]
@dmitriyshashkin 
Thanks - yes this was raised previously as a potential issue. Feel free to to submit a PR for 1). For 2) I think we can make a note in the docs alerting analytics adapters to this new feature.

**Comment by mkendall07** [comment]
@dmitriyshashkin 
Looks like this was fixed in the 1.0 branch - so we should be good once that's merged back to master (as pointed out by @dbemiller ) thanks. https://github.com/prebid/Prebid.js/blob/prebid-1.0/src/ajax.js

**Comment by matthewlane** [comment]
Closing with 1.0 now being the master branch
