### ISSUE TITLE
s2sTesting module unit test fails in Prebid 1.0

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#1723]
## Type of issue
Bug/Refactor

## Description
s2sTesting module unit test needs to be fixed for 1.0 due to changes in adaptermanager and config modules.

## Steps to reproduce
Add tests to `prebid-1.0` branch and run tests

## Other information
@harpere #1678

**Comment by harpere** [comment]
unit tests and adaptermanager problems fixed in #1829, though waiting for the prebidServerAdapter to be finished to run end-to-end tests.

**Comment by snapwich** [comment]
New updates in #1846
