### ISSUE TITLE
Question: How do I "alias" appnexus with brealtime?

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#1731]
I am not so much of an expert in Java code compiling…
This is how I usually build the prebid.js:

npm install
git pull
gulp build --modules=aolBidAdapter,appnexusBidAdapter,conversantBidAdapter,sovrnBidAdapter

However, there is no module for brealtime.
How do I "alias" appnexus with brealtime?
brealtime sent me this code:

i.default.registerBidAdapter(new t, "appnexus"), i.default.aliasBidAdapter("appnexus", "brealtime")

but I do not know what to do with it.

Can anyone help?

**Comment by headerbidding** [comment]
How do I "create alias brealtime from existing appnexusBidAdatper" ?

**Comment by jaiminpanchal27** [comment]
Its already created, you don't need to update anything. Just replace [this line](https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/hello_world.html#L25)
with `bidder: 'brealtime'` and it should work.

**Comment by headerbidding** [comment]
bidder: 'brealtime' was already in place, so I just compiled and it works! Hurrahh!!!
THANK YOU!

**Comment by headerbidding** [comment]
@jaiminpanchal27  I have been getting discrepancies (impressions and revenue) of over 20% with appnexus alias bidders (brealtime and oftmedia) even with version 0-29-0.  
I believe that a "alias" bug has been fixed in version 0-30-1.  (Pull Request #1652)
Is that fix included in 0-31-0?  (Bugs fixed in 0-30-1 disappeared from the version history documentation for some reason.)

**Comment by headerbidding** [comment]
<deleted>

**Comment by headerbidding** [comment]
I just looked at yesterdays report and the brealtime impression discrepancies are due to impressions not counted because of "invalid IP address". 
I don't understand why the bid went out in the first place.
Can you explain?

**Comment by mkendall07** [comment]
@headerbidding 
I'd suggest opening a support ticket with AppNexus. Thanks

**Comment by headerbidding** [comment]
Done!
