### ISSUE TITLE
Document HTTPS Compatibility

### ISSUE THREAD

**Issue by Heray** [prebid/Prebid.js#175]
Except for the old Rubicon adaptor, all adaptors and Prebid.js supports HTTPS. Document this on Prebid.org.

**Comment by ehoch** [comment]
Can we also just make it a requirement for adding an adapter to make it https compatible? Seems like an easy change for a lot of these:

https://github.com/prebid/Prebid.js/blob/master/src/adapters/pulsepoint.js#L7-L8
https://github.com/prebid/Prebid.js/blob/master/src/adapters/springserve.js#L10

Do we prefer doing the "//" style or the AOL style of window.location.protocol ?

I can do the PRs for those two adapters, both of which have hosts that support SSL, assuming their creatives will do the same..

**Comment by mkendall07** [comment]
@ehoch 
Thanks for pointing those out. Feel free to submit the PR with using `https`

**Comment by mkendall07** [comment]
These are fixed now.
