### ISSUE TITLE
Two (or more) sizes competing for the same ad unit

### ISSUE THREAD

**Issue by gitsh84** [prebid/Prebid.js#1752]
## Type of issue
Question

## Description
Is there an easy way (or does Prebid.js supports) the scenario where I have an ad unit which can support 2 or more sizes (e.g. an ad unit with a size of 300x250 can also theoretically display 320x50, another example is  300x600 -> 300x250) send each bidder the 2 options (300x250 and 320x50) and then choose the higher CPM to display ?
From what I understand currently most bidders don't support multiple ad sizes per a single placement.

Thanks !

**Comment by gramorris** [comment]
Yes Prebid supports this. There are a lot of bidders that do support multiple ad sizes - any bidder running on the AppNexus platform for example. For those that don't support multiple sizes you just put two bids in the bid array, one for each size, and PreBid will make two requests. The creative size is passed from PreBid to GPT which will resize the slot if necessary.

**Comment by gitsh84** [comment]
@gramorris Got it. Thanks !

**Comment by gitsh84** [comment]
@gramorris Got it. Thanks !
