### ISSUE TITLE
hb_ adserver key names are hard-coded everywhere

### ISSUE THREAD

**Issue by mattpr** [prebid/Prebid.js#1754]
## Type of issue
Feature request

## Description
`hb_` adserver key names are hard-coded everywhere.  

The same mechanism as `$$PREBID_GLOBAL$$` (webpack search/replace) can be used...but I understand that is brittle and some improvements are already planned there.

In the course of addressing #1508 and #1510, perhaps this can also be addressed.

## Use Case
Some publishers may run more than one prebid based setup in parallel.  The most common use case is during a transition phase (two prebid setups).  These two prebid setups would be conducting auctions for the same adserver placements.  Having the ability to easily customize the key names used for adserver targeting can allow two prebid sets and two adserver line item sets to co-exist and compete against each other.  

We are assuming the two prebid instances are using different names for `$$PREBID_GLOBAL$$`.

There is an additional requirement that timeout/bidsBackHandler needs to be coordinated between the two prebid setups (so both are able to set their targeting before sending the request to the adserver), but this can be done easily.

**Comment by mkendall07** [comment]
@mattpr 
Supporting multiple instances of prebid.js isn't on our roadmap. I'd accept a PR to remove the hardcoded key value names though.
