### ISSUE TITLE
mediaType video and Prebid 1.0: 'getWinningBids' is undefined.

### ISSUE THREAD

**Issue by guillaume-sticky** [prebid/Prebid.js#1758]
## Description
Question regarding the new bidder adapter implementation for Prebid 1.0 using video ads (VAST)

## Platform details
Prebid 1.0

I'm updating our bidder adapter  for freewheel-ssp. As you may know we are playing video ads.
I've seen there is a new parameter in the bid response:  "vastXml"

I've tried to implement it in existing test pages using players like JW,
like this one:
http://prebid.org/examples/video/jwPlayerPrebid.html

it is using prebid.js v0.31.0.

When trying to build prebid 1.0 myself and launch it in my own test page (which is the same as the JW one with currency config added)  I'm getting this error:

console {debug: ƒ, error: ƒ, info: ƒ, log: ƒ, warn: ƒ, …} "ERROR: Error executing bidsBackHandler" TypeError: (0 , _targeting.getWinningBids) is not a function
    at Object.buildDfpVideoUrl [as buildVideoUrl] (prebid.js:8068)
    at Object.bidsBackHandler (prebid_JW.html?pbjs_debug=true:101)

_targeting.getWinningBids is 'undefined' inside "buildDfpVideoUrl"
After being called and responding with a valid bidResponse object:

`[{"requestId":"328b1a68733fb1","bidderCode":"stickyadstv","cpm":"0.2000","width":0,"height":0,"creativeId":"[AdswizzAd28517153]","currency":"EUR","netRevenue":true,"ttl":360,"vastUrl":"https//ads.stickyadstv.com/www/delivery/swfIndex.php?reqType=AdsSetup&protocolVersion=2.0&zoneId=2003","mediaType":"video"}]`

Did I miss something during the build? (a module for video mediaType maybe?)
Is my bidResponse well formatted?  (I tried VastUrl and VastXML without any luck)
Is there a sample page using prebid 1.0 for video mediaType online yet?

**Comment by mkendall07** [comment]
@guillaume-sticky 
There might be an issue with this on the 1.0 branch - we will check it out.

For now, I'd suggest to test your changes against master branch. Thanks

**Comment by guillaume-sticky** [comment]
The page for deveopping Bidder adaptor specified that you "will no longer be accepting pull requests for adapters that are not compliant with Prebid 1.0 conventions" for almost a month.

http://prebid.org/dev-docs/how-to-add-a-new-video-bidder-adaptor.html

Moreover I'm trying to implement a video bidder adaptor using the new vastXML parameter which is available only on Prebid 1.0.
 
Let me know when this is fixed. 
Thx.

**Comment by mkendall07** [comment]
@guillaume-sticky 
All prebid 1.0 adapters are going against master. You can implement it there, in fact that's what we are asking. 

Here is an example: https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter.js#L206

**Comment by guillaume-sticky** [comment]
Indeed, I confirm our bidder adapter is working fine with the current master.
event with the vastXml feature for video mediaType. 
 
Thanks.
