### ISSUE TITLE
New Optimera Adaptor for 1.0

### ISSUE THREAD

**Issue by mcallari** [prebid/Prebid.js#1759]
## Type of issue
Feature Request

## Description
Adding Optimera's bid adapter for public use. Optimera's technology allows publishers to target viewability data to automate viewability optimization for any line item or PMP. Optimera does not push bids but instead targeting data via the deal ID space.

test parameters for validating bids

- Optimera will pass targeting data via hb_deal_optimera, will never pass a size therefore 0x0, will never pass a price therefore 0.00. For example:
hb_deal_optimera=RB_K,300x250K,300x600K&hb_size_optimera=0x0&hb_pb_optimera=0.00&hb_adid_optimera=86a7b6905fe174&hb_bidder_optimera=optimera

```
{
  bidder: 'optimera',
  params: {
    custom: {
      clientId: '1234'
    }
  }
}
```
An external lib is needed and can be added to the site's footer:
```
<script src="https://s3.amazonaws.com/elasticbeanstalk-us-east-1-397719490216/external_json/oPS.js"></script>
```
contact email of the adapter’s maintainer
kcandiotti@optimera.nyc

- [x] official adapter submission

## Other information
Test Page:
http://optimeratest.us-east-1.elasticbeanstalk.com/releaseProjects/prebid/demonstrationPage.php
@kcandiotti

Relates to PR: [https://github.com/prebid/Prebid.js/pull/1617](url)

**Comment by matthewlane** [comment]
Thanks for submitting, the PR is assigned in the queue for review
