### ISSUE TITLE
Tracker extension points for non-usersync trackers

### ISSUE THREAD

**Issue by samuelhorwitz** [prebid/Prebid.js#1762]
## Type of issue
Feature request

## Description
While it is not urgent and we are fine with leaving it out for now, our team at Kargo would like to drop a pixel tracker upon receipt of an ad inside Prebid. However doing so is disallowed due to the fact that it would be chaotic and potentially slow to just allow people to add trackers randomly in their adapter code.

It would be nice if certain events had tracker callback hooks or some other solution where you could register that you would like a tracker to fire that isn't tied to user syncing. For example, inside of response handling.

The issue was brought up here initially https://github.com/prebid/Prebid.js/pull/1729#discussion_r146594903

**Comment by mkendall07** [comment]
@samuelhorwitz 
Why not user usersync functionality for this?

**Comment by optimatic58** [comment]
Not sure if this is the correct place to request this feature (we were directed here).  We would simply like to be able to record failure/error logs at our end via ajax call.  This would allow us to proactively address any issues that may be causing ad failure.  Perhaps deferred ajax calls can be supported as suggested by @dbemiller or a way for us to log and review a sample of those errors to troubleshoot any potential issues.

**Comment by mkendall07** [comment]
so the way I look at this is that anything that causes a request to fire that isn't related to fetching demand is unnecessary. So we probably should not have named the functionality "user syncing". It really just means anything that is not a demand fetch. So it's totally appropriate to put other pings into the user syncing queue. Thanks
