### ISSUE TITLE
migrate PrebidServerBidAdapter to 1.0

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#1768]
## Type of issue
Request

## Description
Migrate the prebidServerBidAdapter to 1.0

## Steps to reproduce
n/a

## Test page
Standard Prebid Server test page with Prebid 1.0

### Expected results
Ad delivered

### Actual results
prebidServerBidAdapter not currently supporting 1.0 changes

## Platform details
all

## Other information
n/a

**Comment by YOzaz** [comment]
Whenever you're working on this - you may want to look at events being raised as well: https://github.com/prebid/Prebid.js/issues/1852

**Comment by bretg** [comment]
Merged
