### ISSUE TITLE
User Targeting Bid Adapter Support

### ISSUE THREAD

**Issue by cdoher01** [prebid/Prebid.js#1783]
## Type of issue
Question

## Description
Hi,
To enable user targeting across our network we set an iframe so that we can use the cookie store or local store name-spaced by our domain.

We would need this information to be part of the bid request that we send out.
I am wondering if its okay to add this iframe as part of our bid adapter setup? 

Thanks!

**Comment by cdoher01** [comment]
Hey @dbemiller & @matthewlane do you have thoughts on this question? Thanks

**Comment by matthewlane** [comment]
I'm not sure I follow what is meant by adding the iframe as part of your bid adapter setup, do you have an example page or code demonstrating what that might look like?

**Comment by dbemiller** [comment]
Sounds like they're trying to use localStorage from another domain... something like this? https://jcubic.wordpress.com/2014/06/20/cross-domain-localstorage/

I don't see anything in the Prebid 1.0 proposal about that... so if it's been discussed, I haven't heard anything about it specifically.

@mkendall07 (project lead) is on vacation until next week, so don't take this answer as binding, but... my guess is that it'll probably be allowed. Adapters are allowed to make multiple server requests to fetch bids, and it sounds like this setup is basically a "two-request" bid. As long as you're not loading and running external javascript, I think it'd be fine.

**Comment by yieldmo-rao** [comment]
@dbemiller , that is correct, we're trying to do something similar. There might be some data in localStorage stored under our domain (which may have been stored previously before the user opened a page that uses Prebid), that we would like to retrieve. We would then be sending this data to our servers when making the request to allow us to get more relevant bids. Obviously, we'll be adding timers and other guards to make sure that it doesn't take too long.

**Comment by cdoher01** [comment]
Thanks for the responses! We will plan to put together a PR where we can discuss with more granularity.
