### ISSUE TITLE
indexExchange/Casale doesn't return bid

### ISSUE THREAD

**Issue by jch1001** [prebid/Prebid.js#179]
I'm trying to set up indexExchange/Casale and see the request is being sent to casalemedia.com in inspect network but never get a bid return. indexExchange/Casale's bid never show up in debugging reports. 

`{                
  bidder: 'indexExchange',
                params: {
                    id: '1',
                    siteID: 000000                
                }
}`

**Comment by protonate** [comment]
The bidder name for indexExchange is "brealtime", so the config should look like:
```
{
    bidder: 'brealtime',
    params: {
        placementId: '2251610'
     }
}

**Comment by protonate** [comment]
Closing, please reopen if there is additional info.

**Comment by headerbidding** [comment]
Hmmmm.  indexExchange/Casale  and brealtime/CPXI are two very different companies.

**Comment by mkendall07** [comment]
Yep, re-opening.

@jch1001  please send us your params so we can investigate. THanks

**Comment by mkendall07** [comment]
@headertag,

Would you be able to exist checking into this issue?

**Comment by headertag** [comment]
@jch1001 if you setup a simulation bidder with siteID 222222 you should get back a clear text bid. See the bottom portion of this article: http://wiki.headertag.com/2015/10/05/i-use-an-existing-tag-manager-for-header-bidding/ it will always return a $10.00 bid.
