### ISSUE TITLE
pbjs.renderAd is not replacing ${AUCTION_PRICE} in adUrl

### ISSUE THREAD

**Issue by klawil** [prebid/Prebid.js#1794]
## Type of issue
Bug

## Description
When a bid is returned with `adUrl` instead of `ad`, the auction price is not replaced in `adUrl`.

## Steps to reproduce
1. Create a bid with an `adUrl` parameter (used to create an iframe with source `adUrl` instead of rendering HTML)
2. Render that ad using `pbjs.renderAd`

## Test page
http://jsfiddle.net/bz3aL37x/6/

### Expected results
The `adUrl` should have the `${AUCTION_PRICE}` replaced with `1` and be set as the source of the iframe.

### Actual results
The `url` parameter has the `${AUCTION_PRICE}` replaced with `1` while `adUrl` is used as the source of the iframe.

## Platform details
All browsers, verified in Prebid v0.32.0

## Other information
PR to fix the issue is being created and will be linked here when submitted
_Edit: Pull request is #1795_

**Comment by mkendall07** [comment]
this is resolved.
