### ISSUE TITLE
Why GZIP for Prebid 1.0?

### ISSUE THREAD

**Issue by hipstern** [prebid/Prebid.js#1807]
I noticed there is a new requirement for Prebid 1.0 for servers to return GZIP response.
Why is this the case? I don't see the value in such a strict rule given that Prebid does not even know the response format/size to begin with.
Would love to understand this better please.

**Comment by mkendall07** [comment]
@hipstern 
Some server responses can be quite large and gzip is a no brainer for [performance](
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer#text_compression_with_gzip ) optimization.That said, it doesn't have to be gzip compression, it can be any form of compression that is readily supported by user agents such as `compress`, `deflate`, `identity` etc.
