### ISSUE TITLE
New Adapter - Huddled Masses for approval 

### ISSUE THREAD

**Issue by HuddledMasses** [prebid/Prebid.js#1808]
## Type of issue
New Adapter for approval

## Description
Hi Team. We uploaded new pull request #1806 
How long will it take to approve it? This is for us super urgent priority, it needs to get done ASAP.
Thanks!

**Comment by HuddledMasses** [comment]
@mkendall07 hi, any update on this? i see you are assigned to pull request #1806 
Thanks!

**Comment by mkendall07** [comment]
There is no need to open issues pointing your pull requests. We have a large number of pull requests we are reviewing and will get to them in the order they are received. Thank you.
