### ISSUE TITLE
Yieldbot and Criteo sending back invalid bids

### ISSUE THREAD

**Issue by jch1001** [prebid/Prebid.js#182]
Can someone please help me with Yieldbot and Criteo sending back invalid bids: "Bid returned empty or error response"? I verified all values for params, I can't figure out what I might be doing wrong.

Here is my config for Yieldbot:

> {
        bidder: 'yieldbot',
        params: {
            psn: 'String',
            slot: 'String'
        }
    }

response:

> {"bidderCode":"yieldbot","width":0,"height":0,"statusMessage":"Bid returned empty or error response","adId":"8c35ed5bc","requestTimestamp":1454695054654,"responseTimestamp":1454695054988,"timeToRespond":334,"cpm":0,"adUnitCode":"div-gpt-ad-847186732-1","bidder":"yieldbot"},

and Criteo:

>{
        bidder: 'criteo',
        params: {
            nid: '0000',
            cookiename: 'crtg_rta',
            varname: 'crtg_content'
        }
    }

response: 

> {"bidderCode":"criteo","width":0,"height":0,"statusMessage":"Bid returned empty or error response","adId":"77da7d5f3","requestTimestamp":1454695054662,"responseTimestamp":1454695054944,"timeToRespond":282,"cpm":0,"adUnitCode":"div-gpt-ad-847186732-1","bidder":"criteo"

**Comment by BartVB** [comment]
First thing that I would check is looking up these bids in the Network tab of you browsers Developer Tools. What request is being made and what do Yieldbot and Criteo return?

**Comment by protonate** [comment]
@jch1001 if you send me the actual config values for Yieldbot params `psn` and `slot` I can test the adapter response as well. My email is on my Github profile.

**Comment by jlai1001** [comment]
The reason I was getting empty/invalid bids from Criteo was I didn't have high enough cookie value so Criteo wasn't bidding at all.

**Comment by jch1001** [comment]
The reason I was getting empty/invalid bids from Criteo was I didn't have enough cookie value and Criteo didn't think it was worth buying and wasn't bidding at all.
