### ISSUE TITLE
Adapter instance communication

### ISSUE THREAD

**Issue by elljoh** [prebid/Prebid.js#1820]
## Question
If an adapter needs to share request parameter state to optimize requests, or indeed to support SRA as indicated in #891, is `postMessage()` to `window.parent` the recommended technique.

Or do you expect to have an adapter context object/API to support adapter instance communication?

In some respects, I read the two requirements below as somewhat opposed.

Thanks, John

Ref: #891 

> All adapters must support the creation of multiple instances.

> Adapters should support a single request architecture (SRA), making a single bid request per page load which supports multiple adunits and multiple sizes per adunit.

**Comment by mkendall07** [comment]
Hey @elljoh 
Each adapter instance would send it's own request. The single request architecture is meant for each instance running. So you shouldn't need to coordinate between the difference instances.  Hope that clarifies.

**Comment by elljoh** [comment]
@mkendall07 thanks. it occurs to me that I may have been misinterpreting what "adapter instance" means.

Incorrectly I have, _for some reason_ (?), been carrying a mental model of an adapter instance being related to a bid request for a particular slot... more akin to an "execution" :\

Whereas an "adapter instance" is a newly instantiated and registered adapter object.

My concern was that, for example, an adapter instance might wish to keep a count of bid requests and provide this or other variables kept in memory as Url query parameters in the bid request in order to optimize demand partner bids.

For a page visit if there is a single adapter instance, keeping state w/in the adapter implementation  is fine.

However, there are scenarios where this could be a limitation. For example:
1. If a demand partner optimizes bids according to a page visit session and there are > 1 adapter instances, publisher monetization may not be optimal; and
2. There is state from session to session that would also be desirable for optimization of bids.
  * An example of this might be https://github.com/prebid/Prebid.js/blob/prebid-1.0/modules/kargoBidAdapter.js#L25

Based on **#2**, [kargoBidAdapter.js](https://github.com/prebid/Prebid.js/blob/prebid-1.0/modules/kargoBidAdapter.js) is it acceptable in Prebid 1.0 implementations to use `cookie`, `sessionStorage` and `localStorage` in adapter implementations? This does give adapters the ability to maintain instance state across sessions.

...and indeed gives some form of communications b/w adapter instances, although simply `postMessage` or some other Prebid.js adapter API handling of this might be my preference when adapter instances are sandboxed.

**Comment by mkendall07** [comment]
@elljoh 
Sorry for the late reply. Yes we are allowing use of `cookie` and `localStorage`. That can be used if desired to coordinate between instances of adapters.
