### ISSUE TITLE
nanointeractiveBidAdapter is erroring on interpreting bid response

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#1827]
## Type of issue
bug.

## Description
Because of a change in the bidderFactory, the object passed back to `interpretResponse` has changed. You need to access the `body` object off the `serverResponse` here:
https://github.com/prebid/Prebid.js/blob/master/modules/nanointeractiveBidAdapter.js#L40

example: `serverResponse.body.forEach ...`

@nanointeractive

**Comment by radepopovic** [comment]
@mkendall07 , Thanks for the info, we will fork the project and fix the bug.

**Comment by matthewlane** [comment]
Closing with #2082 merged
