### ISSUE TITLE
Huddled Masses adapter is not downloading 

### ISSUE THREAD

**Issue by HuddledMasses** [prebid/Prebid.js#1831]
## Type of issue
Question

## Description
Once we get the link to download HM prebid, it shows error 404

![image](https://user-images.githubusercontent.com/26742091/32825701-990b035c-c9ee-11e7-99dd-54229c28a3db.png)

**Comment by HuddledMasses** [comment]
@mkendall07 Hi, can you please help with it?

**Comment by mkendall07** [comment]
The build isn't available yet. Will be on Monday

**Comment by mkendall07** [comment]
this should be fixed.
