### ISSUE TITLE
PreBid AMP - deprecation of remote.html

### ISSUE THREAD

**Issue by gramorris** [prebid/Prebid.js#1832]
## Description
I couldn’t see this mentioned anywhere in the issues or in the AMP docs so thought I’d post. I’m not sure if there’s a solution yet but it does seem at first look to be a change that will break the current PreBid AMP implementation.

https://github.com/ampproject/amphtml/issues/11834

**Comment by gramorris** [comment]
Apologies i’ve Just found the following closed issue:
https://github.com/prebid/Prebid.js/issues/1672

with the proposal of as a solution:
https://github.com/ampproject/amphtml/issues/11321

It will be our intention to be active around this issue so if there’s an opportunity to be involved in testing any proposed solution we’d be happy to be.

**Comment by mkendall07** [comment]
@gramorris 
We are currently working on a solution for header bidding within AMP. The proposal will use Prebid Server as the endpoint in the AMP RTC config. It will not be possible to load prebid.js into AMP any longer though once remote.html is fully deprecated.

**Comment by gramorris** [comment]
Thanks Matt. Somewhat disappointing we won’t be able to use PreBid.js to feed data in to an RTC response, better bring forward our work on PreBid server! Do you have any timescales on the RTC implementation?

**Comment by mkendall07** [comment]
@gramorris 
Hopefull Q1. I've opened a new ticket in the prebid server to track progress there.

**Comment by mkendall07** [comment]
https://github.com/prebid/prebid-server/issues/263
