### ISSUE TITLE
Bidder included multiple times on same ad unit

### ISSUE THREAD

**Issue by YOzaz** [prebid/Prebid.js#1841]
## Type of issue
Question

## Description
Hi guys! Have a question about Prebid.js configuration.
Some adapters do support multiple ad unit sizes on one placement (e.g. Rubicon), while others don't.
What if we want to bid on same ad unit, but with multiple placements / sizes? E.g. for PulsepointLite, an example would be:

```javascript
{
	code: "div-gpt-ad-1474617169903-0",
	sizes: [
		[300, 600],
		[160, 600]
	],
	bids: [{
		bidder: "pulseLite",
		params: {
			cf: "300X600",
			cp: 561431,
			ct: 606839
		}
	}, {
		bidder: "pulseLite",
		params: {
			cf: "160X600",
			cp: 561431,
			ct: 621588
		}
	}]
}
````
Will it work fine and will bid on both placements, or is it adapter-specific?
Tried looking through documentation, but couldn't find anything related.

### Expected results
Multiple bids on same adapter with different configurations, with one combined CPM result (or multiple?).

### Actual results
Can't test it properly, I'm seeing PulsePoint being called - but not sure which placement config is used.

## Platform details
v0.33.0

**Comment by bretg** [comment]
@anand-venkatraman -- could you take a look at this question?

**Comment by mkendall07** [comment]
@prebid/pulsepoint any thoughts?

**Comment by GeneGenie** [comment]
I've tested the same configuration with AppNexus, and it doesn't work properly. Prebid picks first available bid. Even if both bids available, and the second has higher price, first bid is accepted as winner. 

But it still can be adapter implementation issue!?
