### ISSUE TITLE
Currency module fails with error if prebid.org cannot be resolved

### ISSUE THREAD

**Issue by amelzer** [prebid/Prebid.js#1843]
## Type of issue
Bug

## Description

Prebid.org had some DNS issues resulting in a failure of the currency module.
<img width="529" alt="screen shot 2017-11-16 at 12 04 25" src="https://user-images.githubusercontent.com/1628866/32893269-1db0af22-cad9-11e7-9b29-2e304e5f5b6f.png">
<img width="720" alt="screen shot 2017-11-16 at 12 05 09" src="https://user-images.githubusercontent.com/1628866/32893273-239e27e8-cad9-11e7-8608-d70521246b74.png">

This also lead to no bids being returned.
<img width="776" alt="screen shot 2017-11-16 at 14 19 34" src="https://user-images.githubusercontent.com/1628866/32893302-3b816834-cad9-11e7-9a13-8dd75b31631f.png">

## Steps to reproduce

1. Bundle prebid with currency module and indexExchange bid adapter
2. Fake `net::ERR_NAME_NOT_RESOLVED` response for `GET http://currency.prebid.org/latest.json`
3. Set AdServer currency to EUR with `pbjs.setConfig()`
4. Define adslot with indexExchange header bidding
5. Open test page with `?pbjs_debug=true&pbjs_ix_debug=sandbox`
6. Log latest bids

## Test page
I wan't able to create that setup in jsfiddle (seems like URL parameters get ignored) :(

### Expected results
Bid response contains dummy bid from indexExchange. Dummy ad from indexExchange is shown.

### Actual results
Bid response is empty. Fallback ad is shown.

## Platform details
Prebid 0.33-pre with currency module and indexExchange Adapter

## Other information

No problems when ```    pbjs.setConfig({
        currency: {
            adServerCurrency: 'EUR'
        }
    });``` is removed.

**Comment by bretg** [comment]
Thanks @amelzer - was there a page impact, or just console error logs?

Not much we can do about the feature not working if the DNS entry can't be resolved, but we can make sure the failure is as graceful as possible.

It should be noted that the DNS issue was a regrettable one-off problem caused during the transfer of the name service from one provider to another.

**Comment by amelzer** [comment]
Well, it led to no bids being received at all, so the page impact would be: Prebid will not work for that side at all, regardless what currency the bids will come in.

I suggest the following:
If the currency modules fails because the currency file cannot be fetched, remove bidders that have a different currency than specified in adServerCurrency.
That will prevent from Prebid failing totally on that page and allow bidders with the same currency to deliver ads.

**Comment by amelzer** [comment]
Another method would be allowing the developer to provide a fallback themselves.
This could also be combined with the above suggestion.

**Comment by amelzer** [comment]
Addendum: This is can also be tested with a file URL returning a 404

`pbjs.setConfig({
            currency: {
                adServerCurrency: 'EUR',
                conversionRateFile: 'https://httpstat.us/404'
            }
        }))`

**Comment by bretg** [comment]
Thanks @amelzer -- we'll be able to get someone on this in January -- would welcome a community fix before then.

**Comment by amelzer** [comment]
@bretg I can definitely take this on as a community fix, but I'd need some support re: setup. Currently tests are not even running because they are running out of memory ^^

**Comment by mkendall07** [comment]
@amelzer 
Suggest you make the change agains the prebid-1.0 branch - tests should be more stable there.

**Comment by snapwich** [comment]
@amelzer I attempted to recreate the issue but it seems to be working as intended.  If the currency file is down the bids that are already in the proper `adServerCurrency` get sent through still and work as normal, it's only the bids that are NOT in the proper `adServerCurrency` and can't be converted (because currency rates wasn't loaded) that are blocked.  

That seems like the ideal solutions.  I don't think we want to submit bids that are in the improper currency.

**Comment by bretg** [comment]
@amelzer - how about this as an alternate solution: we offer another option on the currency config where the page can specify default rates if the currency conversion service is down. e.g.

```
pbjs.setConfig({
    "currency": {
       "adServerCurrency": "JPY",
       "granularityMultiplier": 108,
       "defaultRates": { "USD": { "JPY": 110.21 }}
    }
});
```

**Comment by bretg** [comment]
@snapwich has implemented the defaultRates feature. This allows pubs to set up defaults in case the currency file fails to load.
