### ISSUE TITLE
Rubicon bidder support for aliasing

### ISSUE THREAD

**Issue by CultureG** [prebid/Prebid.js#185]
Hi,

When I try to use the **aliasBidder** method on Rubicon, like this: 
`pbjs.aliasBidder('rubicon', 'rubiconAlias');`
Prebid.js returns the following error:
> adaptermanager.aliasBidAdapter: rubicon bidder does not currently support aliasing.

Is there a way to make it work ?

Thanks

**Comment by mkendall07** [comment]
Hey @CultureG,

We currently do not support aliasing Rubicon. I'll leave this ticket open as a feature request

**Comment by prebid** [comment]
@mkendall07 mind add Rubicon dev into this thread?

**Comment by Heray** [comment]
@CultureG if you could help bring in a Rubicon developer and sign off on this request, we're happy to assist with the new feature. Archiving this issue for now until we have a Rubicon developer onboard.
