### ISSUE TITLE
Getting wrong size in bid response with Audience network adaptor

### ISSUE THREAD

**Issue by TaipeidogLee** [prebid/Prebid.js#1851]
## Type of issue
Getting wrong size in bid response with Audience network adaptor

## Description
Just found if I use the latest Prebid.js(0.33) downloaded from prebid site, the size in my bid response always shows '3x0', so the DFP returns a 3x0 size creative. However in the bid asked to AN, the size is correct. 
https://an.facebook.com/v2/placementbid.json?placementids[]=340593302966493_499764643716024&adformats[]=300x250&testmode=true&pageurl=&sdk[]=5.5.web

If I use the 'fullwidth' format in bid params then the size is correct.
Also if I switch the prebid.js to older version (0.25), size is also correct.

## Test page
http://deanlee-test1-aws-php.us-west-2.elasticbeanstalk.com/HB_test.html?anhb_testmode=true

### Expected results
showing 300x250 ad

### Actual results
showing 3x0 ad

## Platform details
0.33 prebid, osx, chrome

<img width="673" alt="screen shot 2017-11-20 at 11 49 44 am" src="https://user-images.githubusercontent.com/11287204/33001712-88af57ec-cdea-11e7-9230-08ea9991d22e.png">

**Comment by bretg** [comment]
@TaipeidogLee - did this happen in previous versions?

@lovell - any suggestions about this one? 

There's another issue #1854 around the AN adapter, but this doesn't look to be related. There hasn't been a change to the adapter in some time. Perhaps there was a change on the AN API that isn't reflected in the adapter?

**Comment by TaipeidogLee** [comment]
Hi @bretg , I have not checked the previous version but only checked v0.33 and v0.25, v0.25 works though. Any ways I can get other versions?
thanks.

**Comment by lovell** [comment]
Hello, I've no immediate ideas about what could be causing this - perhaps something expecting to split a string but fed an array or vice versa? Will speak with a few people at Facebook.

**Comment by TaipeidogLee** [comment]
Hi, I got some help saying the code in adaptor should be modified as in image attached, since I am not using npm or yarn to install prebid on me end and I can't change it accordingly on obfuscated version so can anyone help to confirm and update this? thanks.

![23675070_192166604693653_743290489555077496_o](https://user-images.githubusercontent.com/11287204/33059365-e07cffbc-cece-11e7-8cae-ea04cdaab1c2.jpg)

**Comment by lovell** [comment]
@TaipeidogLee Thank you, I agree, we'll get this fixed. It was introduced in v0.32 by commit 403a991 so if you can use v0.31 you'll avoid this problem for now.

**Comment by TaipeidogLee** [comment]
Hi @lovell , thanks for prompt response.
Is there any way for user to choose different version or prebid on prebid site? not every developer are using npm or yarn.

**Comment by lovell** [comment]
PR for this at #1873
