### ISSUE TITLE
Audience Network valid responses are ignored

### ISSUE THREAD

**Issue by deivydas** [prebid/Prebid.js#1854]
If looks that this line causes issues:
https://github.com/prebid/Prebid.js/blob/d3833882813453d98bbb032d0b0cb695f15db32c/modules/audienceNetworkBidAdapter.js#L150

because even a valid response contains errors:
{
   "request_id": "8797624672905347435",
   "errors": [
      "236175133536307_236175516869602 : ",
      "236175133536307_274908712996282 : "
   ],
   "bids": {
      "236175133536307_274908786329608": [
         {
            "placement_id": "236175133536307_274908786329608",
            "bid_id": "25932153539800049",
            "bid_price_cents": 0.090360563631711,
            "bid_price_currency": "usd",
            "bid_price_model": "cpm"
         }
      ],
      "236175133536307_274908856329601": [
         {
            "placement_id": "236175133536307_274908856329601",
            "bid_id": "6693112309205707761",
            "bid_price_cents": 7.96033432,
            "bid_price_currency": "usd",
            "bid_price_model": "cpm"
         }
      ],
      "236175133536307_274681203019033": [
         {
            "placement_id": "236175133536307_274681203019033",
            "bid_id": "3809462616607173617",
            "bid_price_cents": 7.84327058,
            "bid_price_currency": "usd",
            "bid_price_model": "cpm"
         }
      ]
   }
}

**Comment by bretg** [comment]
@lovell - please take a look?

**Comment by lovell** [comment]
Hello, the Audience Network adaptor behaviour has always been to bail as soon as any errors are reported, but I can see why this may not be desired or expected. I'll see what we can do to improve this.

**Comment by matthewlane** [comment]
Closing with #2052 merged
