### ISSUE TITLE
33AcrossAdapter unit tests failing in 1.0

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#1855]
## Type of issue
Bug

## Description
Unit tests are failing in `prebd-1.0` branch due to usage of `utils.getBidderRequestAllAdUnits`.
This function no longer exists in 1.0 branch.
As of now i have skipped failing tests. Please update.

## Steps to reproduce
Your adapter is merged in 1.0 branch.
Checkout https://github.com/prebid/Prebid.js/tree/prebid-1.0 and test

## Other information
@curlyblueeagle

**Comment by curlyblueeagle** [comment]
@jaiminpanchal27  `utils. getBidderRequestAllAdUnits` is used in the adapter at the point `userSync` in order to obtain bid params. Is there another method to used to get the same?

**Comment by jaiminpanchal27** [comment]
@curlyblueeagle `getUserSync` received `responses` as 2nd argument. Not sure if that can work for you. 
I will discuss with the team if we can also pass `bidderRequests` and let you know. 
Thanks

**Comment by curlyblueeagle** [comment]
@jaiminpanchal27 Unfortunately, our server responses do not contain the bid param that I am looking for. It would be super helpful to have `bidderRequests` also passed in. Thank you.

**Comment by mkendall07** [comment]
@curlyblueeagle 
you can submit a PR against the prebid-1.0 branch with that change to send through bidderRequests

**Comment by curlyblueeagle** [comment]
@mkendall07 OK I'll update the adapter, but before I do that can I get some clarity on what a `bidderRequests` object looks like? I'm assuming it will contain bids for all ad units from all bidders. Am I right?

**Comment by mkendall07** [comment]
@curlyblueeagle 
it should just be the request for the current adapter.

**Comment by jaiminpanchal27** [comment]
Fixed in #1917
