### ISSUE TITLE
[Currency] Request latest.json over https

### ISSUE THREAD

**Issue by amelzer** [prebid/Prebid.js#1858]
## Type of issue
Feature Request / Bug

## Description
`latest.json` is currently requested over `http` which leads to some browsers blocking the request if the prebid bundle with currency module is used in a site being servedwith `https`

## Steps to reproduce
1. Build prebid bundle with currency modules
2. Use in a site with https
3. `pbjs.setConfig({
        currency: {
            adServerCurrency: 'EUR'       
 }
    })`

### Expected results
Currency conversion can be set up

### Actual results
![screen shot 2017-11-21 at 13 36 51](https://user-images.githubusercontent.com/1628866/33072916-88f1d072-cec1-11e7-86ce-c4fc9bf20bdd.png)

Currency conversion can not be set up.

## Platform details
e.g. Chrome Browser

## Other information
Tied to #1843 as failing to set up currency conversion leads to prebid not working at all (no bid responses at all)

**Comment by YOzaz** [comment]
That's more than fixing one symbol unfortunately... (I think). Whole prebid.org will have to be put on SSL.

**Comment by bretg** [comment]
This is a known issue as noted in the [doc](http://prebid.org/dev-docs/modules/currency.html). Issue #1834 was directly tied to our being able to fix this feature. The plan is to make it happen early in January.

**Comment by bretg** [comment]
Ironic that stale-bot closed this at just about the same time we were launching the feature.

Good news -- https://currency.prebid.org/latest.json is now available.

**Comment by bboigienman** [comment]
Should we use conversionRateFile parameter to use https URI instead of the http one or Prebid will guess it automatically (and from which version)?
