### ISSUE TITLE
Criteo adapter native integration problem

### ISSUE THREAD

**Issue by mergut** [prebid/Prebid.js#1869]
## Type of issue
Bug

## Description
The Criteo adapter has a `nativeCallback` bidder parameter for native integrations:
http://prebid.org/dev-docs/bidders.html#criteo

This parameter is used in the adapter to request a native ad:
https://github.com/prebid/Prebid.js/blame/0d7b35d7cd84ce519aec1c15c8245616fdca86f5/modules/criteoBidAdapter.js#L52

The problem is that the JSON copy function used inside `adapterManager.js` causes the callback to be lost.
https://github.com/prebid/Prebid.js/blame/0d7b35d7cd84ce519aec1c15c8245616fdca86f5/src/adaptermanager.js#L171

### Expected results
Criteo adapter should return a bid with a native ad.

### Actual results
Criteo adapter returns a bid with a banner ad.

## Platform details
Prebid v0.33.0 + criteoBidAdapter

**Comment by mkendall07** [comment]
this is the same issue as https://github.com/prebid/Prebid.js/issues/1878
