### ISSUE TITLE
Can't specify 'renderer' function for the bid

### ISSUE THREAD

**Issue by danoykin** [prebid/Prebid.js#1878]
## Type of issue
Bug

## Description
The 'renderer' property is ignored in the setup like:
  var adUnits = [{
	code: "div-gpt-ad-1438287399331-0",
	sizes: [[300, 250], [300, 600]],
	bids: [{
	  bidder: "rubicon",
	  params: {
		accountId: "4934",
		siteId: "13945",
		zoneId: "23948",
		sizes: [15]
	   },
	   renderer : {
		render : function(bid) {
			// my custom render function
		},
		url : 'http://'
	   }
        }]
  }];

## Other information
The problem is inside adaptermanager.js, lines 170-171:
  // client side adapters
  let adUnitsClientCopy = utils.cloneJson(adUnits);

The cloneJson() doesn't clone function() objects. So the 'render' property is lost on clone.

**Comment by mkendall07** [comment]
Thanks for the report. Feel free to submit a PR or we will fix it next sprint.
