### ISSUE TITLE
When Huddled Masses adapter will be included into the new release? 

### ISSUE THREAD

**Issue by HuddledMasses** [prebid/Prebid.js#1879]
## Type of issue
Huddled Masses adapter is not available on download page 

## Description
there is no answer on my question. When will you have a new release? 

![image](https://user-images.githubusercontent.com/26742091/33174520-13947838-d061-11e7-90c7-eabc952c292a.png)

**Comment by HuddledMasses** [comment]
@mkendall07 @rmloveland any update on this?

**Comment by bretg** [comment]
I see Huddled Masses on the download page now. http://prebid.org/download.html
