### ISSUE TITLE
Loading script multiple times - Calling requestBids

### ISSUE THREAD

**Issue by dbabaioff** [prebid/Prebid.js#188]
For some adapters, like AOL and Yieldbot - Calling ```pbjs.requestBids(...)``` multiple times (if you refresh individual ad units for example) loads the adaptor script multiple times.
Yieldbot script - ```//cdn.yldbt.com/js/yieldbot.intent.js```
AOL script - ```//aka-cdn.adtechus.com/dt/common/DAC.js````

**Comment by mkendall07** [comment]
Thanks for raising the issue @dbabaioff .

I think the easiest solution would be to implement a cache on our `adLoader.loadScript` functionality. We will include this soon.

**Comment by mkendall07** [comment]
PR https://github.com/prebid/Prebid.js/pull/242  adds a caching mechanism to `adLoader.loadScript` 
Adapters have to opt into the functionality.

**Comment by dbabaioff** [comment]
Is there a way to enable to all adapters by default?

**Comment by mkendall07** [comment]
@dbabaioff 
Could you explain what you mean? All adapters should be available in the default build.

**Comment by dbabaioff** [comment]
"Adapters have to opt into the functionality."
@mkendall07 I mean, enable cache on ```adLoader.loadScript``` by default on all adapters.

The function ```loadScript``` (prebid v0.7) accepts a new argument ```cacheRequest``` - if cacheRequest it's true then the function will cache the script - but this argument is never used.

**Comment by mkendall07** [comment]
@dbabaioff 
Gotcha. Yeah we have to look at them 1 by 1 and make sure that it won't break anything by enabling it. Will target it for the 0.8.0 release. That's why this ticket is still open.

**Comment by protonate** [comment]
PR #466 has been merged which will now load script with cache enabled by default. Closing.
