### ISSUE TITLE
Bidders' Param - Design Question

### ISSUE THREAD

**Issue by CathyHuangtw** [prebid/Prebid.js#1887]
## Type of issue
A question about bidders' param

## Description
We would like to ask for your suggestions for our bidder’s param.
The case is that siteId is one of the required params to our endpoint but we want to implement the adapter in a way publishers don’t need to fill this param in every single ad unit they have on the same site.
Based on [this document ](http://prebid.org/dev-docs/bidder-adapter-1.html)for Prebid 1.0
> Adapters may not use the $$PREBID_GLOBAL$$ variable: Instead, they must load any necessary functions and call them directly.

We won't use pbjs global object to add our own tag for the use of general param. But it doesn't seem to be a good idea to use window object, either. It also causes testability problems... What we wanted to do was :
```
      window.c1x_pubtag = {
        siteId: '9999',
        pixelId: '12345', //optional
      };
```
Of course I can just let siteId be one of the params in bids.params(which seems to be a common way that other adapters do), I am just wondering is there a better way to implement since we are updating our bidder adapter.

**Comment by mkendall07** [comment]
we've discussed a page level bidder param, however, have not had the chance to implement it. We'd accept a PR that allows a `setConfig` object with global bidder params if you want to work on that feature.

**Comment by CathyHuangtw** [comment]
We'd like to work on that feature and contribute to this project :)
Here's a proposal for the page level bidder params.
```javascript
pbjs.setConfig({
  bidderParams: [{
    'c1x': {
      'pixelId': '12345',
      'siteId': '9999'
    }
  }, {
    'appnexus': {
      'testId': 'abcd'
    }
  }, {
      'biddercode': {
        'siteId': '7890'
      }
   }]
});
```
We will add the params to ad units when the bidder code in its target bids matches with the bidder code in above ```setConfig``` object.
What do you think? And please let me know which branch should I checkout from to add this new feature. I suppose to do that from ```prebid-1.0 ``` ?
