### ISSUE TITLE
`standard` bidderSettings is broken in 1.0

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#1898]
## Type of issue
bug
## Description
Add the following to the hello world example page:

```
            pbjs.bidderSettings = {
                standard: {
                    bidCpmAdjustment: function (bidCpm, bid) {
                       return 10;
                    }
                  }
                };
```

Results in the following error:
![image](https://user-images.githubusercontent.com/1870166/33399669-742d7392-d521-11e7-8acd-4d8d9f3275a4.png)

## Platform details
prebid-1.0 branch master

**Comment by jaiminpanchal27** [comment]
Fixed in #1905
