### ISSUE TITLE
Huddled Masses Adapter is not downloading 

### ISSUE THREAD

**Issue by HuddledMasses** [prebid/Prebid.js#1907]
## Type of issue
The Huddled Masses Adapter is not downloading. 

## Description

![image](https://user-images.githubusercontent.com/26742091/33476097-60fea962-d689-11e7-9950-59be121048ea.png)

**Comment by HuddledMasses** [comment]
@bretg I see the Huddled Masses adapter on download page, but once we receive an email with a link for download, there is an error: NOT FOUND. 

We are waiting for this already couple of weeks. The pull request is here: #1806 
Can you fix it ASAP? Thanks!

**Comment by HuddledMasses** [comment]
@bretg @mkendall07 @rmloveland 

Team, now we can download HM Adapter, but instead of HM file we receive Appnexus JS file. 
<img width="837" alt="screen shot 2017-12-04 at 10 31 19 am" src="https://user-images.githubusercontent.com/26742091/33543487-e5175e3a-d8df-11e7-9695-6d4ed28ed313.png">
[prebid_20171204082241.js.gz](https://github.com/prebid/Prebid.js/files/1526244/prebid_20171204082241.js.gz)

Please check this.

**Comment by mkendall07** [comment]
@HuddledMasses 
The error was mistakingly made and reverted several hours ago. 

Your adapter will be available later today when we update to 0.34.0 on the download site

**Comment by mkendall07** [comment]
this is resolved.
