### ISSUE TITLE
Polyfills polluting global namespace, causing errors 

### ISSUE THREAD

**Issue by snapwich** [prebid/Prebid.js#1911]
## Type of issue
**bug**

## Description
The `core-js` polyfills are exporting a global variable named `core`.  This breaks some sites that may already be using a global variable named `core` on their site.

## Steps to reproduce
Use a global variable named `core` on your site and include Prebid.js.  It will be overwritten by the `core-js` library.

**Comment by mkendall07** [comment]
just don't use `core`, problem solved. :)

**Comment by snapwich** [comment]
Unfortunately at least one of our client's proprietary frameworks is intent on that using that global.  However, I'm more worried about the clients using `core` without realizing its in contention and creating obscure bugs.

**Comment by mkendall07** [comment]
This is resolved in master
