### ISSUE TITLE
npm install fails on Karma 0.13

### ISSUE THREAD

**Issue by BartVB** [prebid/Prebid.js#192]
When I do:
'rm -rf ./node_modules && npm cache clean && npm install'

npm fails with:
https://gist.github.com/BartVB/63553f7c42e7eb88e968

For now I've fixed this by changing the version requirement for Karma in package.json from ^0.13.2 to ^0.12.1
This is on a Debian 8.2 machine.

**Comment by protonate** [comment]
I was able to test a clean install on a Debian 8.2 Docker image without running into the "peer invalid" issue. Do you have Karma installed globally, and if so which version?

**Comment by mkendall07** [comment]
@BartVB 
We can't reproduce this issue so most likely an environment setup problem.
