### ISSUE TITLE
Headerbid Expert, OpenX not showing on certain page

### ISSUE THREAD

**Issue by Takawari** [prebid/Prebid.js#1926]
## Type of issue
Possible small bug in Headerbid expert URL detection

## Description
In Headerbid expert, on some pages OpenX is not shown when used for header bidding

## Steps to reproduce
Go to the test page below and open Headerbid Expert

## Test page
https://image.online-convert.com/convert-to-jpg

### Expected results
See DFP and OpenX header bidding in Headerbid expert

### Actual results
Only DFP showing in Headerbid expert

**Comment by mkendall07** [comment]
@Takawari 
thanks for the report! It looks like we need to add the following pattern to HeaderBidding expert for openX: `.openx.net/w/1.0/arj`

You can submit a pull request here: https://github.com/prebid/headerbid-expert/blob/master/bidderPatterns.js#L8

**Comment by Takawari** [comment]
Pull request created: [https://github.com/prebid/headerbid-expert/pull/2](https://github.com/prebid/headerbid-expert/pull/2)
