### ISSUE TITLE
New Gulp setup doesn't create a prebid.min.js file

### ISSUE THREAD

**Issue by BartVB** [prebid/Prebid.js#193]
The new build setup only creates build/dist/prebid.js which is an uglified version of the script.

In the old setup bot prebid.js (full file) and prebid.min.js (uglified) were created. This made it much easier to quickly edit Prebid when testing it's implementation. In the current setup you need a working NodeJS/npm setup for even the most trivial change. Only having the minified version also makes it more complicated to debug Prebid in the browser.

**Comment by mkendall07** [comment]
Hi @BartVB 
Sorry about that. We weren't sure if having this was useful, but it seems that it is so we will add it back in.

@protonate please add back the non-minified version of prebid and and also the minified version to the `build/dist` directory. Thanks!

**Comment by protonate** [comment]
The un-minified version of the build is found at [`build/dev/prebid.js`](https://github.com/prebid/Prebid.js/blob/master/build/dev/prebid.js). The minified version is now `build/dist/prebid.js`. If it is preferable I can change as follows.
```
.
+-- _config.yml
+-- _drafts
|   +-- begin-with-the-crazy-ideas.textile
|   +-- on-simplicity-in-technology.markdown
+-- _includes
|   +-- footer.html
|   +-- header.html    
```
The dev and debug process is not yet documented and I will update the README today with the following info.

To test and debug take the following steps.

* `gulp test --watch` Runs the tests and keeps the test runner browsers open (currently Chrome and Firefox only) 
* Click DEBUG button on a test runner page 
* View the developer console, and you will see console.logs for the test results
* View Sources and you will a `base/test/spec` directory containing the tests
* Each test file is built with the Prebid.js code, so you can set breakpoints in the test or in the prebid code itself

**Comment by BartVB** [comment]
Oops, sorry! Didn't check properly, it's there indeed :+1: 

Thank you!

**Comment by jamesmehorter** [comment]
FYI, the `gulp serve` command generates the source and min versions of prebid.js. Whereas `gulp build` only generates the minified version.
