### ISSUE TITLE
Default bid settings per adapter

### ISSUE THREAD

**Issue by BartVB** [prebid/Prebid.js#194]
Quite a few adapters have bid/adUnit settings which are common for all bids. For example 'network' for AOL, 'jstag_url' for OpenX, 'rp_site' for Rubicon, etc.

It would be nice if you could set default values for these settings in the 'pbjs.bidderSettings' section.

**Comment by protonate** [comment]
Assigning to @Heray for review.

**Comment by Heray** [comment]
We are concerned that it'd take a lot of documentation to explain to developers which fields are global level, and which fields are tag level. It's one of those simplicity vs. efficiency tradeoff we have to make. Archiving this ticket for now until header bidding partners also raised the issue.
