### ISSUE TITLE
Multiple adapters reusing the same code

### ISSUE THREAD

**Issue by ffeast** [prebid/Prebid.js#1948]
## Type of issue
Question

## Description
Hi
What's the recommended way to implement multiple adapters reusing the same codebase that only differs in ENDPOINT_URL / ADAPTER_SYNC_URL? 
Thanks

**Comment by mkendall07** [comment]
This isn't something that's supported. What's the use case here? Interested if you have a proposal too.

**Comment by ffeast** [comment]
That's exactly what I need, thanks
