### ISSUE TITLE
How can my prebidAdapter be added to your system?

### ISSUE THREAD

**Issue by brnsk-1945** [prebid/Prebid.js#1949]
## Type of issue
question, adapter support, integration

##  Description
According to documentation [http://prebid.org/dev-docs/bidder-adapter-1.html](url) I have created 3 files:

mynameBidAdapter.js
mynameBidAdapter.md
mynameBidAdapter_spec.js

What are the next steps with these files? Where can I read about it?
Should I email them to  info@prebid.org ?

**Comment by dbemiller** [comment]
You'll need to submit a pull request. I'd suggest following Github's docs here: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Depending on your background, you may also want need to learn some basic Git: http://rogerdudler.github.io/git-guide/

**Comment by brnsk-1945** [comment]
@dbemiller Thank you a lot. I Know how to create pull request. I couldnt find any info about  creating pull requests. Should have  i guessed about it? Would be great if you added some info about it into documentation.

**Comment by mkendall07** [comment]
@brnsk-1945 
What other info are you looking for exactly? When you open the PR there will be a template to fill out. That should be enough information.

**Comment by brnsk-1945** [comment]
@mkendall07  Probably I made you misunderstand the question. If I have never used GIT, how should I know what to do with these 3 files  then? Where exactly in your documentation is it mentioned that I have to make a pull request?

**Comment by dbemiller** [comment]
It's [at the top of the CONTRIBUTING.md](https://github.com/prebid/Prebid.js/blob/master/CONTRIBUTING.md#contributing-to-prebidjs) file, which is linked [from the main README](https://github.com/prebid/Prebid.js#Contribute)

**Comment by brnsk-1945** [comment]
Guys I`m not gonna prove you anything. I am just saying that on the page http://prebid.org/dev-docs/bidder-adapter-1.html there is nothing mentioned neither about pull request nor CONTRIBUTING.md. I ve spent the whole  day trying to get how to work with you and now I am writing to adapter. Is it made on purpose to weed out many of  those who want to work with you?

**Comment by mkendall07** [comment]
I see. Yeah we can update the linked page to include a reference to contributing and next steps. Thanks for the input!

**Comment by mkendall07** [comment]
Opened a ticket for our docs team to update: https://github.com/prebid/prebid.github.io/issues/494
