### ISSUE TITLE
Bidder does not currently support aliasing

### ISSUE THREAD

**Issue by smartbidder1** [prebid/Prebid.js#1960]
## Type of issue
alias support

## Description
I want to use a different bidder name so I will see that in the analytics data, I've tried aliasing but almost every bidder doesn't support aliasing.
I've tried: Openx, Sonobi, and Sharethrough.
## Steps to reproduce
pbjs.aliasBidder('sharethrough', 'sharethrough_alias');

**Comment by mkendall07** [comment]
Are you seeing an error? What's the issue exactly?

**Comment by smartbidder1** [comment]
the error is `adaptermanager.aliasBidAdapter: openx bidder does not currently support aliasing.`
I want to be able to create an alias to openx or every other adapter so I can separate the analytics data.

**Comment by mkendall07** [comment]
@smartbidder1 what version of prebid? All adapters in prebid 1.0 should support aliasing I believe, but if you are using an older version it might not be supported.

**Comment by smartbidder1** [comment]
@mkendall07 you are right, but 1.0.0 is missing a lot of bidders and we can't use it at this moment.
any solution for 0.34?

**Comment by dmitriyshashkin** [comment]
@smartbidder1 are you sure that you use 0.34? I'm quite confident that both OpenX and Sharethrough support aliasing in 0.34

Unfortunately, there is unlikely any solution for Sonobi. You can try implementing aliasing support yourself, and then include the modified adapter into your own build of prebid. It's not that difficult, I've done this with other bidders with varying success, but the approach has obvious downsides.

**Comment by mahammer** [comment]
Same issue here. Just build 0.34.1 and tried to alias:
`pbjs.aliasBidder(` "featureforward", "brightcomff");`
as Brightcom uses Feature Foward, doesn't work:
`prebid.js:3 featureforward bidder does not currently support aliasing. adaptermanager.aliasBidAdapter`

**Comment by mkendall07** [comment]
We didn't require adapters to support aliasing in pre 1.0 release. So support was in an opt in basis. Looking at featureforward adapter in the legacy branch (0.34.1) it doesn't support aliasing. They also have not submitted a 1.0 compliant adapter yet. The core library cannot do much about this unfortunately. I would suggest you contact your SSPs that don't support 1.0 yet and ask when they will be compliant.

Alternatively, you can fork and modify the bidders themselves as mentioned by @dmitriyshashkin
