### ISSUE TITLE
Prebid Video - No bids returning

### ISSUE THREAD

**Issue by Projectkelsen** [prebid/Prebid.js#1971]
We have successfully implemented prebid 0.34 for display and are now working on setting up an prebid for video dependently. We are working with JW self-hosted video player and have run into issues with bids not being returned and no ads being rendered.

We have been troubleshooting for about a week now and nothing seems to be working. 

Here is a test page to see: 
https://www.cimahub.com/media/15507/widget?wid=6d0713479285a2e49d04092018afcaf1&ccid=73&pid=108&domain=www.diariolasamericas.com

**Comment by mkendall07** [comment]
@Projectkelsen 
Sorry for the delay in responding. Where you able to get this to work? Generally issues with bids not returned need to be troubleshooted with the specific SSP(s) you don't receive bids from. Thanks
