### ISSUE TITLE
Prebid js problem

### ISSUE THREAD

**Issue by Paolo8913** [prebid/Prebid.js#1972]
Hi all, in some sites i have this error in console and prebid ( and dfp line item) doensn't work. 

What i have to do?

prebid.js:4 Uncaught TypeError: (0 , _.registerBidder) is not a function
    at Object.101 (prebid.js:4)
    at n (pb209150.js:41)
    at Object.100 (prebid.js:4)
    at n (pb209150.js:41)
    at window.pbjsChunk (pb209150.js:41)
    at window.pbjsChunk (prebid.js:3)
    at prebid.js:4

This is a test page:  http://www.gossippiu.com/2017/12/costanzo-dichiarazioni-vita-privata-belen-rodriguez.html

**Comment by jaiminpanchal27** [comment]
You are loading two version of prebid on your test page. 
I see following in the logs.
`INFO: Prebid.js v0.32.0-pre loaded `
`INFO: Prebid.js v0.34.0 loaded `

Append query param `?pbjs_debug=true` to see logs. I also see bunch of other errors but those maybe due to loading two prebid.js versions.

**Comment by Paolo8913** [comment]
@jaiminpanchal27 Thank you, but i have the same error also on other sites that hadn0t that problem of duplicate prebid. 
Also in this site:  http://www.direttaradio.it/

**Comment by Paolo8913** [comment]
@jaiminpanchal27, just another thing. I see, as you said,  that another adv concessionaire had set up previd v 32.0 instead of mine prebid v34 and this is causing some conflicts.
I want change my prebid to their versions. 
So this is what i have done:
1) i donwloaded from https://github.com/prebid/Prebid.js/releases the version 32. 
29 i deleted the previous prebid v 34
2) I Copied and pasted into prebid.js the ssps' adapter v32 i need. 
it's ok?
here the prebid js: https://cdn.b4u-advertising.it/prebid/prebid32.js

**Comment by jaiminpanchal27** [comment]
you can download it from here http://prebid.org/download.html
Select the ssps/modules you need and it will generate the build.

**Comment by Paolo8913** [comment]
@jaiminpanchal27 yes but it download the last version 34. i need the version 32

**Comment by jaiminpanchal27** [comment]
Ohh yes correct.
In that case you need to create build programatically.
Instructions are over here https://github.com/prebid/Prebid.js

Install
```
$ git clone https://github.com/prebid/Prebid.js.git
$ cd Prebid.js
$ yarn install
```

Build
```
gulp build --modules=openxBidAdapter,rubiconBidAdapter,sovrnBidAdapter
```

**Comment by Paolo8913** [comment]
@jaiminpanchal27 , about the same error on this sites, you can help me?
http://www.ascoltitv.it/
www.direttaradio.it
www.ascoltitv.it
www.atleticalive.it
