### ISSUE TITLE
a few missing bugfixes in the conversion from bidmanager.js -> auction.js

### ISSUE THREAD

**Issue by kitwestneat** [prebid/Prebid.js#1984]
## Type of issue
Bug / Refactor

## Description
The move from bidmanager.js to auction.js is missing a couple changes:
220e3161203c324e0d5102d0dc5b4930a856caac
6cf71d002735c63744c0266236386b97a2f10f58
fbf0840488e76016563a1c8759fbc6c42a7d8ac8

bidderFactory.isValid is missing a change as well:
8e0ce694e58c5f55004179adedd1e6c616463ab3

With that last one, it seems less likely that a bid response will not be able to find the matching request in the new system since the bid requests are bound to the bid response function, but it still seems like good practice to verify it since a failure will break the auction.

I can readd them if you all agree they should be in there, would you all prefer separate commits or a single commit?

**Comment by mkendall07** [comment]
@kitwestneat 
Thanks a lot for catching this. Would prefer individual PRs for these if you have the time. Thanks!
