### ISSUE TITLE
Prebid, bids are available but no winning bid. Bidder settings are don't seem set in the network request

### ISSUE THREAD

**Issue by EM-LuisGalaz** [prebid/Prebid.js#1989]
## Type of issue
Question

## Description
I have not been able to implement prebid for one page, even though there are a lot of correct implementations. AppNexus support has risen the issue that it could be because in the network tab there doesn't seem to be any settings passed. 
That is, when you go to the "network tab" in "chrome console" you can filter requests by "gdfp" and in the header for the petitions you can see a number of query params, among those params there is "hb_x, y and z". For successful bids, the params get set (we have a number of successful implementations on other sites), however in this case there are no query params. 
When do those bidder settings get set on the network requests? 

## Test page
https://jsfiddle.net/xhk2e0sp/

**Comment by mkendall07** [comment]
@EM-LuisGalaz 
That just means there is no demand being fetched (no bids). You should check with each SSP to see if you are setup to run on the particular domain. Thanks
