### ISSUE TITLE
Legacy branch support timeline

### ISSUE THREAD

**Issue by ffeast** [prebid/Prebid.js#1999]
## Type of issue
Question

## Description
For how long will the legacy branch be supported? 
Are there any plans to stop accepting pull-requests after a certain period of time?
Thanks

**Comment by matthewlane** [comment]
The legacy branch will be supported through Q1 of 2018. Bug fixes and minor PRs will be accepted through then. New adapters and major rewrites or features are no longer accepted on the legacy branch
