### ISSUE TITLE
Coding Style/Standards Guidelines?

### ISSUE THREAD

**Issue by ericperez** [prebid/Prebid.js#200]
Hello,

Is there a guideline for coding standards that this project adheres to? I ask because I see many differences between different source files such as tabs versus spaces for indenting, spaces/no spaces after brackets, spaces/no space after conditionals e.g. `if(something)` versus `if (something)`, lines breaks/no line breaks for 'else' lines, etc. It would be good to get them all standardized so the code is more cohesive. Thanks.

**Comment by mkendall07** [comment]
@ericperez 
We are currently working on some style guidelines. Please stay tuned.

**Comment by protonate** [comment]
This PR defines code quality and style standards and brings the code base up to those standards (mostly). #210

**Comment by protonate** [comment]
PR #210 is merged. We'll keep this issue open to provide documentation.

**Comment by protonate** [comment]
#210 has been released with [Prebid 0.7.0](https://github.com/prebid/Prebid.js/releases/tag/0.7.0). The .jscs and .jshint files in project root can be incorporated into your IDE to assist with conforming code commits to code style. Closing.
