### ISSUE TITLE
AMP equivalent of pbjs.bidderSettings

### ISSUE THREAD

**Issue by amanjain** [prebid/Prebid.js#2000]
## Description
We are setting up prebid on our AMP site. We used to do the following setup in non-prebid version:
`pbjs.bidderSettings = {
    standard: {
        adserverTargeting: [{
            key: 'some_key',
            val: function(bidResponse) {
                return bidResponse.pbHg;
            }
        }]
    }
};
`

What will be the equivalent setup in AMP + prebid scenario?

**Comment by bretg** [comment]
@amanjain - bidderSettings shouldn't be different for an AMP environment. See the `getTargeting()` function on http://prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html -- `window.context.master.pbjs.getAdserverTargeting()` holds the results of bidderSettings.

Are you seeing something different?

**Comment by bretg** [comment]
@amanjain - closing this issue. Please re-open with more details as needed.
