### ISSUE TITLE
Adding auction fields to response

### ISSUE THREAD

**Issue by GEMI** [prebid/Prebid.js#2002]
## Type of issue
Question

## Description
Some fields from prebid aution response and not available in adapters or in the responses.
For example **auction_id** and **cpm_publisher_currency**.

How would it be possible to read this information inside the **getBidResponses** callback?

**Comment by mkendall07** [comment]
@GEMI 
You should be able to read the pub currency from `getConfig`.  Not sure about auction_id but what do you need that for?
