### ISSUE TITLE
Colossus Adapter

### ISSUE THREAD

**Issue by HuddledMasses** [prebid/Prebid.js#2007]
## Type of issue
Hi Team, under release 1.0.0. we don't see Colossus Adapter. Should we make any update? Please let us know. 

## Description
Снимок экрана 2018-01-03 в 18.14.35

**Comment by jaiminpanchal27** [comment]
@HuddledMasses You need to update your adapter to make it 1.0 compliant. Guidelines are given here http://prebid.org/dev-docs/bidder-adaptor.html
