### ISSUE TITLE
Optimizing prebid.js filesize by removing adapters

### ISSUE THREAD

**Issue by ojotoxy** [prebid/Prebid.js#201]
I disable most of the adapters inside prebid.js by commenting out lines in adaptermanager.js.

This is to save on file size.

Since the switch to webpack, this no longer reduces the file size. The prebid.js bundle includes all adapters, even those who's require() statement has been removed.

How can I configure prebid.js to only include certain adapters?

Side note: I can't post with the prebid.js tag on stackoverflow because of "not enough reputation to create a new tag".

**Comment by protonate** [comment]
One quick workaround is to remove the unwanted `src/adapters` files themselves.

We are looking into a solution for building only with required adapters.

**Comment by ojotoxy** [comment]
Thanks for the quick response, that fix works for now.

**Comment by protonate** [comment]
PR #206 restores the ability to exclude adapters by editing adaptermanager.js.
