### ISSUE TITLE
Override ad unit sizes in bid request

### ISSUE THREAD

**Issue by mmilleruva** [prebid/Prebid.js#2010]
## Type of issue
Question/Feature Request

## Description
Is it possible to override adunit sizes for a specific bid request in that ad unit. Looking at the example below, my adunit accepts 2 sizes. I only want the first bid request to be able to bid on 300x250 sizes.

The primary use case for this is to allow for premium inventory sizes that I would only allow certain partners to bid on. Or if we have a partner with lower quality ads, we don't let them buy the larger inventory sizes

```
var adUnits = [
        {
            code: 'test-ad',
            sizes: [[300, 250], [300, 600]],
            bids: [
{
                    bidder: 'onedisplay',
                    sizes: [[300,250]],
                    params: {
                        dcn: '2c9d2b50015a5aa95b70a9b0b5b10012',
                        pos: 'header'
                    }
                },
                {
                    bidder: 'onedisplay'
                    params: {
                        placement: '3611253',
                        network: '9599.1',
                        bidFloor: '0.80',
                        keyValues: {
                            test: 'key'
                        }
                    }
                }
            ]
        }
    ];
```

**Comment by mkendall07** [comment]
@mmilleruva 
I believe you can do this with labels http://prebid.org/dev-docs/publisher-api-reference.html#labels

You'd define a subset of sizes on the label and then label the bidder and it should get the subset of sizes in the request.

**Comment by bretg** [comment]
Actually not sure that's going to work @mkendall07. Labels aren't associated with sizes -- they're just tags that can be used to conditionally include/exclude bids.  The sizeConfig feature supports overriding sizes, but that would be for all bids in the AdUnit.

I think that for a single bid in the AdUnit to have a subset of sizes, the bidder adapter would need to support that. Apparently not many do. So I think this is an enhancement request to allow per-bidder override of the sizes seen by each adapter.

**Comment by GeneGenie** [comment]
I'm also voting for bid size.
