### ISSUE TITLE
Supporting new Bid Adapter on older Prebid version

### ISSUE THREAD

**Issue by vedantseta** [prebid/Prebid.js#2012]
## Question

We are trying to add a new bidder Adapter, however what we see is many publishers are using older versions of Prebid including 0.17, 0.23, 0.31 and more. 
 
1. Can we place a pull request on older versions of Prebid? 
 Or we have to place pull request on latest version i.e. 1.1.1 (i.e. publishers have to update to current Prebid version to integrate us). 
2. Is there any other alternative to integrate our Bid Adapter in their current Prebid version? Assuming publisher is generating Prebid code from the website (http://prebid.org/download.html)

**Comment by mkendall07** [comment]
@vedantseta 
You can submit a pull requests against master (1.2-pre release) which would require the publisher to upgrade or you can submit against the `legacy` branch which is pegged to pre 1.0 release (0.34.x stable). We may do periodic releases of 0.34.x if there is bug fixes that are merged. Only 1.0 adapter formats are supported going forward though.
