### ISSUE TITLE
AppNexus Param: RandomKey - What is it? How to use it? How to report off of it?

### ISSUE THREAD

**Issue by KevinTBN** [prebid/Prebid.js#202]
There is this parameter for AppNexus (http://prebid.org/dev-docs/bidders.html) in PreBid of  "randomeKey" (I don’t know if that is miss-spelled on purpose or is that is a mistake) that can be passed to AppNexus. I can't seem to figure out what purpose this serves or how to leverage this parameter. We would like to send a value through here to help us with our reporting (to distinguish what impressions were sent from which site). but we can’t figure out how to pull this key in any reports.  I’ve been trying to through the Publisher JSON reports (https://wiki.appnexus.com/display/sdk/Publisher+Analytics+Report#PublisherAnalyticsReport-Example) and it doesn’t seem to be coming through any of the dimensions there either.  Any insights?

**Comment by g10r** [comment]
i think its miss-spelled

**Comment by KevinTBN** [comment]
I've also tried it by spelling it correctly, but it still doesn't pass anything into reporting. Or anything into AppNexus as far as I can tell - I would really like to be able to leverage this parameter if someone could help me figure out its purpose.

**Comment by mkendall07** [comment]
@KevinTBN 
Thanks for pointing out the typo, it's corrected now. Regarding the purpose, its mainly for buy side demand to identify specific attributes about the supply. Currently we don't offer reporting on this field. Also note that `randomKey` is just an example and any string value here would send data through as well.
