### ISSUE TITLE
AppNexus adapter Markdown file - native example needs update

### ISSUE THREAD

**Issue by rmloveland** [prebid/Prebid.js#2021]
## Type of issue

Improvement, I think?

## Description

The AN adapter supports native aspect ratios, but the Markdown file showing how to create a native ad unit does not show this functionality.

## Other information

Native aspect ratios PR: https://github.com/prebid/Prebid.js/pull/1634

**Comment by mkendall07** [comment]
@rmloveland 
we accept PRs ;)
