### ISSUE TITLE
CDN Hosted Version

### ISSUE THREAD

**Issue by ehoch** [prebid/Prebid.js#203]
Should we reach out to a Fastly / MaxCDN, or one of the other CDNs I see hosting open source projects?

**Comment by mkendall07** [comment]
@ehoch 
We have the latest version on our CDN here: http://acdn.adnxs.com/prebid/prebid.js

**Comment by ehoch** [comment]
@mkendall07 Oh, or we could reach out to those nice folks at AppNexus. Maybe some versioning in the URL while I have you?

**Comment by mkendall07** [comment]
http://acdn.adnxs.com/prebid/static/0.6.0/prebid.js

These are maintained for at least 3 releases.

**Comment by ehoch** [comment]
:+1:

**Comment by CLKeenan** [comment]
@mkendall07 any plans on hosting the latest version (0.8.1)? Looks like the latest version is 0.7.0

Thanks!
