### ISSUE TITLE
Colossus Adapter upgrade to 1.0.0 version 

### ISSUE THREAD

**Issue by HuddledMasses** [prebid/Prebid.js#2030]
## Type of issue
Update of Colossus Adapter in #2029 - there is an error in tests 

## Description
We are trying to resolve the issue https://travis-ci.org/prebid/Prebid.js/builds/328125144?utm_source=github_status&utm_medium=notification 
an error appears once ChromeHealess is launched.
This application is not dealing with out adapter. Is there any problem with Travis-ci? 
if not, what we should do on our side to complete testes and to upgrade adapter? 

Thanks!

**Comment by mkendall07** [comment]
@HuddledMasses 
see https://github.com/prebid/Prebid.js/issues/2042 to resolve
