### ISSUE TITLE
Prebid JS returns bids but no ad is shown.

### ISSUE THREAD

**Issue by EM-LuisGalaz** [prebid/Prebid.js#2037]
## Type of issue
Prebid JS returns bids but no ad is shown

## Description
I have a setup in which I can successfully get bids back from all bidders, however, no bids ever show up. For this I have followed the documentation for adOps and have made sure that the price buckets are ok. In fact, we have several other implementations with no problem. 

I am assuming that the problem occurs once prebid pushes the attributes to the googletag. Does this make sense? If this was the case then I don't know why no ad is winning once the values are sent over to DFP. 

Other than configuring the price buckets, what could be the issue here? 
I am using prebid v.34 

Thank you very much for your help.

**Comment by mkendall07** [comment]
@EM-LuisGalaz 
It's usually helpful to use the google console troubleshooter for these types of issues: 
https://www.monetizemore.com/blog/troubleshoot-dfp-google-publisher-console/
https://support.google.com/dfp_premium/answer/2462712?hl=en

You should be able to figure out why the prebid line item isn't winning using this tool
