### ISSUE TITLE
SizeConfig and Labels - unexpected behavior?

### ISSUE THREAD

**Issue by rmloveland** [prebid/Prebid.js#2043]
## Type of issue

Bug

## Description

I have test pages where `mediaQuery` should match the page size, and the `labelAny` targeting on the ad unit matches the `labels` on the `sizeConfig` object, but an ad is not displayed.

## Steps to reproduce

See cases and links to test pages in the table below.

The table below describes the behavior I've observed around the intersection of media queries, supported ad sizes, and labels targeting. Each case links to a test page showing that case. What I'm seeing seems to contradict [the documentation](http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-Configure-Responsive-Ads) (but it's possibly I am totally misunderstanding how this is supposed to work!)

<table>
<thead>
<tr>
<th class="right" scope="col">case number</th>
<th class="left" scope="col">mediaQuery exists and/or matches?</th>
<th class="left" scope="col">ad size is in list of sizesSupported?</th>
<th class="left" scope="col">sizeConfig has labels?</th>
<th class="left" scope="col">adUnit has labelAny targeting sizeConfig label?</th>
<th class="left" scope="col">Ad is displayed?</th>
<th class="left" scope="col">Labels/sizing warning emitted?</th>
<th class="left" scope="col">JSFiddle link</th>
</tr>
</thead>
<tbody>
<tr>
<td class="right">1</td>
<td class="left">yes</td>
<td class="left">no</td>
<td class="left">no</td>
<td class="left">no</td>
<td class="left">
<font color="green">YES</font>
</td>
<td class="left">no</td>
<td>
<a href="https://jsfiddle.net/prebid/tgz2fou9/1/">sizeconfig-test-01</a>
</td>
</tr>

<tr>
<td class="right">2</td>
<td class="left">yes</td>
<td class="left">no</td>
<td class="left">yes</td>
<td class="left">yes</td>
<td class="left">
<font color="red">NO</font>
</td>
<td class="left">yes</td>
<td>
<a href="https://jsfiddle.net/prebid/L96vmnLm/">sizeconfig-test-02</a>
</td>
</tr>

<tr>
<td class="right">3</td>
<td class="left">yes</td>
<td class="left">yes</td>
<td class="left">yes</td>
<td class="left">yes</td>
<td class="left">
<font color="red">NO</font>
</td>
<td class="left">yes</td>
<td>
<a href="https://jsfiddle.net/prebid/grb47rsh/">sizeconfig-test-03</a>
</td>
</tr>

<tr>
<td class="right">
<ac:inline-comment-marker ac:ref="23b78c2e-03e2-427b-a12f-367b305d67b1">4</ac:inline-comment-marker>
</td>
<td class="left">no</td>
<td class="left">yes</td>
<td class="left">yes</td>
<td class="left">yes</td>
<td class="left">
<font color="red">NO</font>
</td>
<td class="left">yes</td>
<td>
<a href="https://jsfiddle.net/prebid/13r9gtng/">sizeconfig-test-04</a>
</td>
</tr>

<tr>
<td class="right">5</td>
<td class="left">yes</td>
<td class="left">yes</td>
<td class="left">yes</td>
<td class="left">no</td>
<td class="left">
<font color="green">YES</font>
</td>
<td class="left">no</td>
<td>
<a href="https://jsfiddle.net/prebid/33aL3t9y/">sizeconfig-test-05</a>
</td>
</tr>

<tr>
<td class="right">6</td>
<td class="left">no</td>
<td class="left">yes</td>
<td class="left">yes</td>
<td class="left">no</td>
<td class="left">
<font color="green">YES</font>
</td>
<td class="left">no</td>
<td>
<a href="https://jsfiddle.net/prebid/t1nssk3w/">sizeconfig-test-06</a>
</td>
</tr>

<tr>
<td class="right">7</td>
<td class="left">no</td>
<td class="left">no</td>
<td class="left">yes</td>
<td class="left">no</td>
<td class="left">
<font color="green">YES</font>
</td>
<td class="left">no</td>
<td>
<a href="https://jsfiddle.net/prebid/tu3491y9/">sizeconfig-test-07</a>
</td>
</tr>
</tbody>
</table>

Based on the above, I have questions:

- If the mediaQuery matches the page size, and the labelAny targeting on the ad unit matches the label on the sizeConfig, isn't that supposed to work? Or is it not matching in an obvious way that I'm missing?

- As far as I can tell the labels match (they are the same strings), and should fire with labelAny - what am I not seeing?

- What is the exact nature of the interaction between labels and media queries? I would imagine they get `AND`ed together? Or?

- It appears to be the case that if there is an ad that matches the ad unit's size, it doesn't matter if the media query matches and the ad size is not listed in the supported sizes. I think this is what is meant in [the docs](http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-Configure-Responsive-Ads) by

    > So the adUnit.sizes is a subset of the sizes defined from the
    > resulting intersection of sizesSupported sizes and adUnit.sizes.

- The error message `WARNING: callBids executed with no bidRequests.  Were they filtered by labels or sizing?` doesn't really help at all, since there are two interacting features, either of which could be failing to work. Is there some way to trace the operation of the matching and print something that shows me the steps? (AKA a backtrace? (for this mini pattern matching interpreter))

### Expected results

Ad should serve when `mediaQuery` matches the page size, the ad size is in the list of supported sizes, and the `labelAny` array includes a label from the ad unit. 

### Actual results

Ad does not serve when the above conditions are in place.

**Comment by mkendall07** [comment]
@snapwich mind taking a look when you get a chance?

**Comment by snapwich** [comment]
@rmloveland At a glance I think all your test pages are setting sizeConfig incorrectly.

You have `var sizeConfig = [ ... ]; pbjs.setConfig(sizeConfig)` when it should be `pbjs.setConfig({sizeConfig: sizeConfig});`

If you're still having issues with sizeConfig after that change, let me know and I can dig in further.

**Comment by rmloveland** [comment]
OK, fixing the `setConfig` syntax caused all but two of the examples above to work as I expected.  This was narrowed to only one after reading the [docs](http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-Configure-Responsive-Ads), which answered my question about #7 with this line:

> If a label conditional (e.g. labelAny) doesn’t exist on an ad unit, it is automatically included in all requests for bids.

This leaves just #4 that I have questions about.

<hr />

In [this updated version of test case #4](https://jsfiddle.net/prebid/13r9gtng/3/):

- The prebid.org test ad's size is in `sizesSupported` (300x250)
- The `labelAny` on the ad unit is targeting the label `widescreen` in the first object in the `sizeConfig` array
- The first object in the `sizeConfig` array doesn't specify a `mediaQuery` (it's commented out)

Given the above, I would expect "no `mediaQuery`" to mean "match any size" and lead to relying on just the label targeting.  However the match appears to fail, and no ad is shown.  This leads me to believe `mediaQuery` is a required property in the `sizeConfig` object(s)?  Uncommenting the `mediaQuery` in the fiddle and expanding the fiddle's output area gets the test ad to serve, which seems to confirm this.

Is this the expected behavior?

**Comment by snapwich** [comment]
I think that's expected behavior.  We didn't cover the case of the `mediaQuery` property missing in the design doc (just went and re-read it), but I would consider that an error case.  

I would rather someone explicitly state that they accept any screen size then have our code assume that to be the case since such a rule (match all screen sizes) isn't very useful in this module.  The design doc says "We don't recommend structuring your sizeConfig such that multiple mediaQueries match, but it is possible.", and a rule that matches all would lead to that undesired scenario frequently.

It's possible we could throw an error for a missing `mediaQuery`...  I could get behind that.

**Comment by rmloveland** [comment]
> It's possible we could throw an error for a missing mediaQuery... I could get behind that.

+1

I would definitely be in favor.  Then we could update the documentation to note that the `mediaQuery` is required, and share the rationale you just laid out re: multiple queries matching.
