### ISSUE TITLE
Question: Is there a way to adjust bids only for certain ad units?

### ISSUE THREAD

**Issue by millieone** [prebid/Prebid.js#2049]
We know how to adjust bids for certain bidders for example to make gross bids, net.

Now however we're trying to figure out if we can adjust bids for certain ad units.  '

A google certified partner wants us to have prebid compete vs their ADx setup in our DFP but they don't have a way of making Adx account for their commissions. We'd like to test this only on a few ad units at first. Hence the need.

**Comment by mkendall07** [comment]
@millieone 
Yes you can do this with checking the bid object that is passed through the bidCpmAdjustment function.

Example:

```
bidCpmAdjustment: function (bidCpm, bid) {
  if(bid.adUnitCode === "code"){
        return bidCpm * 0.7;
  }
  //no adjustment
  return bidCpm
}
```

**Comment by bretg** [comment]
Agree with this solution. Closing. @millieone - please re-open with details as needed. Thanks.
