### ISSUE TITLE
exports.bidResponseReceivedCount in bidmanager references old object

### ISSUE THREAD

**Issue by ohashd** [prebid/Prebid.js#205]
In the initbidResponseReceivedCount function in bidmanager, when it sets bidResponseReceivedCount equal to {}, it creates a new object and the reference stored in bidmanager's exports still references the old object.

Easy fix is to delete the properties instead of making a new object ie:

`for (var prop in bidResponseReceivedCount) {
	delete bidResponseReceivedCount[prop];
}`

**Comment by mkendall07** [comment]
Thanks @ohashd 
We will review.

**Comment by protonate** [comment]
This was fixed in PR #200 which is now in master. Thanks for reporting the bug. Closing.
