### ISSUE TITLE
[Question] download page is 0.34.0 tag but legacy branch is 0.34.1 ?

### ISSUE THREAD

**Issue by jcswart** [prebid/Prebid.js#2055]
Is there a reason the download page seems to provide code from `0.34.0` but the legacy branch is based behind `0.34.1` ?

What is the purpose of the legacy branch?

**Comment by jcswart** [comment]
@dbemiller or @matthewlane any insight?

**Comment by jcswart** [comment]
@mkendall07 any information?

**Comment by mkendall07** [comment]
No particular reason. We'll be updating soon. The legacy branch is there for maintenance support until pubs move over to 1.x

**Comment by mkendall07** [comment]
to be clear, we'll be cutting a 0.34.2 release and the download page will offer that option.

**Comment by jcswart** [comment]
Thank you that is sufficient to help me progress on what I need to do. I need to support 1.0 and pre-1.0. I'll be opening a PR against the legacy branch soon.
