### ISSUE TITLE
Need example without SRA enabled

### ISSUE THREAD

**Issue by arjha** [prebid/Prebid.js#2074]
Hi....
Any specific reason why you always use SRA in all your examples. I know SRA is recommended by DFP but, what if I do not want to use SRA. Is there any adverse effect with any bidder or browser without SRA? 
Can you provide some examples which do not use SRA.
I will be very grateful if you will help me on this.

**Comment by bretg** [comment]
@arjha - all you have to do is drop the enableSingleRequest() call from your GPT code. e.g. commenting out the GPT call:
{code}
// googletag.pubads().enableSingleRequest();
{code}

> Is there any adverse effect with any bidder or browser without SRA?

Performance -- when the browser has to make multiple requests to DFP, there's an additional penalty in overhead of setting up extra connections.

If this doesn't work for you, please go ahead and re-open with a detailed description of the problem. Thanks.
