### ISSUE TITLE
question

### ISSUE THREAD

**Issue by aryan-solo** [prebid/Prebid.js#2081]
Question

## Description
i want to know if there is a way to get allavailablebids and winbids and then send it to a url (post) to save all details. do i need to make a custom analytic adaptor ? my use case is simple i dont want to add extra code on to clients website.   

i have a js code where i make XMLHttpRequest() request to my backend , where i pass in:
			var winningBids = pbjs.getAllWinningBids();
  			var allRes=pbjs.getBidResponses();

is there a way to do it without adding js code into a website header.
it would be very kind if someone provided me a step by step approach , i am a rookie so any help would be really great.

**Comment by aryan-solo** [comment]
is it possible to make a $$PREBID_GLOBAL$$.sendAllandWinnningBids   function in which i could make a post request to the url which will save my data

**Comment by bretg** [comment]
If this functionality is mean to be ongoing, this function is definitely an analytics adapter. Sorry to say, but it's difficult to imagine how it could be done without adding code. 

If on the other hand, it's something you intend to run from the javascript console just for debugging, that's feasible and we may be able to post some code here to get you started. 

But it sounds to me like you want analytics -- so if you end up building a basic analytics adapter, we'd be happy to have you submit that PR.

**Comment by bretg** [comment]
Closing -- I believe what you're asking for is analytics and can't see a shortcut. 

Please re-open if I've misunderstood your needs.
