### ISSUE TITLE
Review currency file generation

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#2091]
## Description

There are two functions in the Prebid Org AWS Lambda. One of them generates the currency conversion file daily while the other monitors staleness of the file.

This review is related to enabling downloading the currency file over HTTPS 

Notes:
- The file is stored in an S3 bucket: currency.prebid.org
- A CloudFront distribution is setup to publish the S3 file around the world
The logs for the lambda functions wind up in CloudWatch

Next steps:
- inspect the functions
- define the email alias that the alerting script sends email to. I propose a new address along the lines of alerts@prebid.org to enable inbox sorting
- figure out a migration plan from Rubicon's AWS to Prebid's. Proposal:
-- update DNS currency.prebid.org to have a much shorter TTL, like say 5 mins. 
-- after a few days, update DNS currency.prebid.org to point to the new CloudFront address instead of the current one and increase the TTL back to a day
-- immediately move the currency.prebid.org alias from the Rubicon-based CloudFront config to Prebid CloudFront

**Comment by mkendall07** [comment]
@bretg 
left my comments here: https://github.com/prebid/currency-file-generator/pull/1#discussion_r166117050

**Comment by bretg** [comment]
@mkendall07 - believe we're good on this now.

I found from AWS support that we'll need to have them help us transfer the cname -- https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/
