### ISSUE TITLE
Chrome Snippet in Prebid 1.00

### ISSUE THREAD

**Issue by chefbenjamin** [prebid/Prebid.js#2094]
The Chrome Browser snippet here http://prebid.org/dev-docs/toubleshooting-tips.html has been great for debugging setups with new adapters , just curious with all the deprecated features from .34 to 1.0 detailed here  http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.allBidsAvailable does the snippet still work properly or are there changes that need to be done to the snippet going forward in a 1.00+ world ? 

We use All Bids and Winning Bids the most.

**Comment by bretg** [comment]
snippet updated

**Comment by chefbenjamin** [comment]
@bretg we've found adding into the snippet ; 

size: bid.size, 

as it provides insight into the size thats been bid on a handy addition for when using multi size.
