### ISSUE TITLE
Yieldmo bid adapter unit test failing in iOS

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#2098]
## Type of issue
Bug

## Description
@merrdy We run unit tests on browserstack in [these](https://github.com/prebid/Prebid.js/blob/master/browsers.json) browsers
One of your test https://github.com/prebid/Prebid.js/blob/master/test/spec/modules/yieldmoBidAdapter_spec.js#L147 test is failing in iOS

## Steps to reproduce
Run tests in iOS

**Comment by merrdy** [comment]
@jaiminpanchal27 That makes sense. I'll make a fix and issue a pr by end of day today. Thanks for the heads up.

**Comment by merrdy** [comment]
@jaiminpanchal27 PR is up

**Comment by jaiminpanchal27** [comment]
Fixed in #2100
