### ISSUE TITLE
Appnexus AST aliasing not possible?

### ISSUE THREAD

**Issue by olya-fb** [prebid/Prebid.js#2103]
## Type of issue

I'm not sure if it's a bug or some feature.

## Description

We wanted to have in our project a possibility to choose, which adapter to alias for brealtime, defymedia and districtm: appnexus or appnexusAst.

I now found, that brealtime and defymedia are hardcoded into the appnexus adapter, and the aliasBidder function doesn't allow changing the alias.

But when I use districtm aliasing, on appnexusAst it says, bidder doesn't support aliasing. Yet I see some posts on issues here, that suppose people had used aliasing through appnexusAst at least in the past.

We have version 0.29.0.

So, my questions are:

1. Is there the only way to redefine alias from appnexus to another adapter, to change the appnexus adapter file, commenting there the aliasBidder lines? Or is there a possibility to redefine aliases?

2. Does appnexusAst support aliasing? Is it a temporary issue of 0.29, that it's not working? 

3. Is there a version where it was working? Do you have some maybe temporary workarounds for that?

Thank you!

## Platform details

Prebid 0.29.0

## Other information

https://github.com/prebid/Prebid.js/issues/1455
https://github.com/prebid/Prebid.js/issues/322

**Comment by jaiminpanchal27** [comment]
In latest legacy version 0.34.2, appnexusBidAdapter has all the aliases defined and appnexusAst has not. So if you want to use brealtime, defymedia and any other for appnexusAst than you can create a prebid.js build with only appnexusAst adapter and than call 
`$$PREBID_GLOBAL$$.aliasBidder('appnexusAst', 'brealtime')
$$PREBID_GLOBAL$$.aliasBidder('appnexusAst', 'defymedia')` 
to add them as alias. 

So to answer your questions
1. Build prebid.js with either appnexus/appnexusAst adapter and use `aliasBidder` method. There is no way to remove existing aliases. 
If you want to include both you can comment lines [229..235](https://github.com/prebid/Prebid.js/blob/legacy/modules/appnexusBidAdapter.js#L229) and use method `aliasBidder`.
2.  Yes appnexusAst supports aliasing. You can use latest legacy version 0.34.2
3.  Please try 0.34.2. There was a bug with creating aliases when we switched to use new bidderFactory pattern to create adapters but i am not sure that was in 0.29.0

**Comment by olya-fb** [comment]
thank you! I removed appnexus adapter from the build, upgraded to 0.34.4 and it worked (on 0.29.0 it continued to give that error of "appnexusAst doesn't support aliasing"). Thank you very much for your help!
