### ISSUE TITLE
Paid Request: Developer 

### ISSUE THREAD

**Issue by pav7** [prebid/Prebid.js#212]
I am looking into implementing prebid on my medium sized group of sites. I use DFP small biz and have less than 5 SSPs. Because I use relatively basic discussion forum publishing software I don't have a developer on staff. I have a webmaster that can place the code in the proper sections of the templates. I can do the DFP set up. Just need someone to work with me to oversee implementation the javascript development.  If you are interested or know someone interested, please contact me rob at enthuseddigital dot com. Preferably would like to work with someone who is contributing to the prebid.js project. Thanks very much.

**Comment by bfleischman** [comment]
Hey Pav,

My name is Brad Fleischman and I represent bRealTime. We have extensive experience implementing prebid.js and custom header bidding frameworks. Our team will be able to set up and manage the integration for you with no development resources required on your end.

You can see more information on our header bidding products here: brealtime.com/publishers/biddr

Would you mind shooting me an email so I can provide you with more details? My email is bfleischman@brealtime.com
