### ISSUE TITLE
Our version of gulp-webdriver depends on github dependency which sometimes fails

### ISSUE THREAD

**Issue by snapwich** [prebid/Prebid.js#2138]
## Type of issue
bug

## Description
The version of `gulp-webdriver` we have in our package.json depends on the master branch of a github repo which [can cause build failures when accessing github](https://github.com/webdriverio/gulp-webdriver/issues/37) or other issues since its dependency is not fixed to a version (`master` is always the latest).

I don't see it being referenced in this project other than in package.json.  Can it be removed?  If not, can we update to a [later version](https://github.com/webdriverio/gulp-webdriver/releases/tag/v2.0.3) that removes that dependency?

**Comment by snapwich** [comment]
This issue is still causing occasional fails in our internal build process.  Reopening.

**Comment by snapwich** [comment]
still an issue

**Comment by jsnellbaker** [comment]
@snapwich This should have been addressed per the PR that @thewizarodofoz noted.

Please review and close if we're good at this point.  Thanks!
