### ISSUE TITLE
Pubmatic adaptor not working for certain accounts

### ISSUE THREAD

**Issue by jdelhommeau** [prebid/Prebid.js#214]
Hi,

It seems there is a bug in the Pubmatic adaptor. prebid.js doesn't handle the response properly, causing pubmatic response to always been considered as no bid response.

In the code in Pubmatic adaptor, we have below lines:

![pubmatic1](https://cloud.githubusercontent.com/assets/14938467/13280492/bd2d4908-dade-11e5-992a-a775aa50d291.png)

As you can see by the code and the comment, we expect the response to be of the form bidstatus=0;bid=0.0000;bidid=39620189@320x50;wdeal=

While actually, Pubmatic response is of the form: 
"bidstatus;1;bid;0.3554;bidid;/3845/ebay.es.search/RTM_391@728x90;wdeal;"

We should update the pubmatic adaptor to use the correct response format.

Here is an example implementing pubmatic which fails: https://jsfiddle.net/mohsink4u/1fshL465/6/

Julien

**Comment by jdelhommeau** [comment]
As per Pubmatic team, it seems the response change depending on which adserver the publisher is using. If using DFP, then the response I provided will be used (with key;value). If using another adserver, then the response used currently (with key=value) will be used.
We should be able to manage both case.

I am still unclear how pubmatic detect the adserver, especially since prebid code executing before the adserver code, they shouldn't be able to detect it runlive. If it's a setup at the account level for the publisher, it might be possible to force pubmatic to always send abck the non DFP response (the one we manage today).

Will keep you posted.

**Comment by tr-coull** [comment]
We had this issue with the Pubmatic adapter, and have made a Pull Request to have our solution added to the main Prebid.js project: https://github.com/prebid/Prebid.js/pull/186

Basically the params may be in either of those formats ("key=value;key2=value2;" or "key;value;key2;value2"), so I've checked for the presence of "=" in the incoming string and written additional different processing if it's not found. There may be a better way to do it so please feel free to suggest another solution!

**Comment by jdelhommeau** [comment]
@tr-coull indeed, this is the issue and your fix seems the best way to do it from prebid.js POV.
In case of my test, I was actually able to ask Pubmatic to change the response type for my pubmatic account, to it matches the key=value. It took them less than half a day between the moment I asked them and the moment the change was effective, so it might also be a good way to quickly fix this if you have issue right now.

**Comment by protonate** [comment]
I believe we just need a test for PR #186 and that it then can be merged. We'll reach out to Pubmatic for that. In the meantime, another workaround is to fork this repo and use @tr-coull's changes to build your prebid.js. Since @jdelhommeau has the expected response type now this may be unnecessary.

**Comment by mkendall07** [comment]
This has been fixed. closing
