### ISSUE TITLE
Name of media type

### ISSUE THREAD

**Issue by moonshells** [prebid/Prebid.js#2145]
## Type of issue
Question

## Description
I saw Prebid.js use `mediaTypes` for Client side adapter and maps it to `media_types` for Prebid Server, for the bid response, prebidServerBidAdapter uses `mediaType`, what is the reason to use different names of media type?

**Comment by mkendall07** [comment]
I think it comes down to convention (prebid server preferring underscore vs camelCase) and in terms of the bid, it's not a `mediaTypes` value (plural) it's just `mediaType` singular because a bid cannot have multiple types where as a adUnit can request multiple types. Hopefully that is clear.
