### ISSUE TITLE
Receiving bidderTimeout events for "No bid" responses

### ISSUE THREAD

**Issue by aurelienjoneau** [prebid/Prebid.js#2146]
## Type of issue
Question

## Description
Hey guys, while starting to implement this solution : #2035 , I noticed that i'm receiving `bidderTimeout` events for all "No bid" responses that are given back, right before the `auctionEnd `event.

@snapwich, Do you know how to distinguish real timeout events and "No bid" responses ?

**Comment by snapwich** [comment]
actually just submitted a pull-request instead; it is a small bug fix.
