### ISSUE TITLE
How to set up post-bidding with Prebid.js?

### ISSUE THREAD

**Issue by joyofdata** [prebid/Prebid.js#215]
Hello,

am I correct that all provided examples refer to pre-bidding? All I could find on post-bid is conceptual information on it in the "What is post-bid?" section. I would appreciate if somebody could provide information on how to set up post-bid.

Kind Regards

Raffael

**Comment by CultureG** [comment]
You can check this example : 
http://prebid.org/examples/postbid.html

**Comment by mkendall07** [comment]
@joyofdata 
Postbid can be accomplished 2 ways.
1) The configuration for prebid is loaded directly on page and no ad server call is made (that is example here http://prebid.org/examples/postbid.html)
2) The whole configuration from #1 can be loaded as a creative into your ad server call and return to the page.
