### ISSUE TITLE
Are the Appnexus Prebid trafficking Docs Current for 1.0 ?

### ISSUE THREAD

**Issue by chefbenjamin** [prebid/Prebid.js#2156]
We are in the process of migrating from 0.34 to 1.31 and we've had a few hiccups to say the least.

Can someone on the Appnexus side, confirm that these trafficking instructions http://prebid.org/adops/setting-up-prebid-with-the-appnexus-ad-server.html

are still current for trafficking within Appnexus Ad Server for Prebid 1.0+ or if there are changes required to trafficking for 1.0 setup.

**Comment by mkendall07** [comment]
Hey Benjamin,

There should be no changes AFAIK. Any particular problem that you are encountering?

**Comment by chefbenjamin** [comment]
@mkendall07 maybe its related to what you've been going back on forth with Brent on. Basically only seeing one actual render per page load where there are plenty of high bids and we are seeing winners for each slot, but only 1 render. Lets see if we can fix the issue at present first and then see if that is causing the 1 render issue as it might go away when resolved.
