### ISSUE TITLE
Danmarketplace Adapter Issue <> Bidder Name longer than 12 symbols

### ISSUE THREAD

**Issue by danmarketplace** [prebid/Prebid.js#2165]
## Type of issue
question

## Description
Hello Prebid team! Could you help us? Our adapter (danmarketplace) has bidder name more than 12 symbols, and we noted it in doc file as biddercode_longer_than_12: true. But we have a problem with adTargeting keys, key hb_adid_danmarketplace is truncated to 20 symbols and server can't read it and call the creative for render properly when using hb_adid_danmarketplace macro. What should we do in this situation?

**Comment by mkendall07** [comment]
@danmarketplace 
This is a limtation on the DFP side, so prebid enforces it. You should truncate your macro as well in DFP to 20 characters to match.
