### ISSUE TITLE
smartadserverBidAdapter use just the first bids in buildRequests method

### ISSUE THREAD

**Issue by vlouppe** [prebid/Prebid.js#2166]
## Type of issue
Bug

## Description
smartadserverBidAdapter take only one bid before the ad server request 

https://github.com/prebid/Prebid.js/blob/9b56b11bc8d7b5e4a45c985eb6aa97824cb07708/modules/smartadserverBidAdapter.js#L34

## Steps to reproduce
Set adUnits with more than one smartadserver's bid. The first is only used.

## Test page
No test page, it's pretty obvious.

**Comment by matthewlane** [comment]
cc @Spacedragoon
