### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by HuddledMasses** [prebid/Prebid.js#2169]
## Type of issue
Timeout issue - 1.x Colossus adapter 

## Description
In the process of transition our publishers to colossus prebid adapter 1.x we noticed that very often we don't fit the timeouts on the page. 
Previously, a timeout of 900 ms was set up for every ad request. And we never had an issue with it.
Now, with a multi-query, there is a timeout for a response of 1200 ms for 6 placements.
Is there a recommended timeout set up for a publisher with such number of placements (in our case 6) in the query? 

Thanks!

**Comment by mkendall07** [comment]
The timeout is completely up to the publisher to control. Generally we recommend 1000ms or less but you can advise the publisher as you wish.
