### ISSUE TITLE
{undefined:{}} from getAdserverTargeting

### ISSUE THREAD

**Issue by terebentina** [prebid/Prebid.js#2174]
## Type of issue
bug

## Description
Using `0.34.3`, one of the vendors returns `statusMessage: "Bid returned empty or error response"` (indexExchange for a video ad). In `bidsBackHandler` I console log `pbjs.getAdserverTargeting()`.
If I set `enableSendAllBids: true` in `pbjs.setConfig` then the log shows `{"undefined":{}}`. If I comment out that config, the log properly shows just `{}`.

If another vendor completes successfully, along with the unsuccessful Index, the log shows:
`{ "undefined": {}, "video0": {....} }` (or `{ "video0": {....} }` if Index is successful too.

## Steps to reproduce
comment/uncomment the `enableSendAllBids: true` line below
```
    window.pbjs.que.push(() => {
      window.pbjs.setConfig({
        usePrebidCache: true,
        enableSendAllBids: true,
      });

      window.pbjs.requestBids({
        timeout,
        adUnits,
        bidsBackHandler(bids) {
          console.log('HB complete. targetingParams:', JSON.stringify(window.pbjs.getAdserverTargeting()));
        },
      });
    });
```

### Expected results
`{}`

### Actual results
`{"undefined":{}}`

## Platform details
prebid 0.34.3, chrome, windows 10

**Comment by mkendall07** [comment]
@terebentina 
Thanks for the bug report. We'd review a PR for this but we might not get to it right away as our focus is on 1.x master branch going forward.
