### ISSUE TITLE
Add feature to run single test

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#2176]
## Type of issue
Feature

## Description
We cannot run single test anymore.

To increase speed of executing unit tests we updated the stack and tried [alternative usage](https://github.com/webpack-contrib/karma-webpack#alternative-usage) of karma-webpack

**Comment by vedantseta** [comment]
on it, will be sending PR in couple of days.

**Comment by jaiminpanchal27** [comment]
@vedantseta Did you get a chance to work on this ?
