### ISSUE TITLE
Revshare

### ISSUE THREAD

**Issue by yogeshadsparc** [prebid/Prebid.js#2179]
Hi,

is there any way to add revshare in prebid setup?

Regards,
Yogesh Ingale

**Comment by mkendall07** [comment]
@yogeshadsparc 
what do you mean add revshare? You can adjust the bids with bidderSettings if you would like:
http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.bidderSettings
See bidCpmAdjustment

**Comment by yogeshadsparc** [comment]
Thanks, mkendall07 for the quick reply.
what do you mean add revshare?  It's a revenue share option on bidder level. eg. for DistrictmDMX bidder they have "revShare" parameter in adunit.
Is there any inbuilt "revShare" parameter option  in prebid js?

**Comment by mkendall07** [comment]
no, each individual bidder may or may not support that type of input. There is no generic support on the adUnit.

**Comment by yogeshadsparc** [comment]
Ok. Thanks.
