### ISSUE TITLE
Ad Units for Infinite Scroll page

### ISSUE THREAD

**Issue by yogeshadsparc** [prebid/Prebid.js#2185]
Hi @mkendall07 ,
Is there any way to create or assign adunits to dynamically created div on the page? 
e.g on mobile view on every scroll new adslot is generated dynamically, how can add or setup bid to that adslot?

I tried with replacing div id with adunit path in prebid adunit setup, but it's not working for me.
e.g ref. https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/pbjs_partial_refresh_gpt.html

Please let me know how can I implement this with prebid.

**Comment by mkendall07** [comment]
The best way is to add an additional adUnit and requestBids again. you can copy the old adUnit if you want and just update the adUnit.code.
