### ISSUE TITLE
All bids available for JS code

### ISSUE THREAD

**Issue by lukasznowicki** [prebid/Prebid.js#2186]
## Type of issue
Question maybe feature request

## Description
Hi guys, is there a way to know exactly when we get last winning bid?
I need all winning bids with its CPM and I need to use it in my javascript code, so I'm looking for exact place where I can be sure that no more 'bidWon' event is coming.

**Comment by mkendall07** [comment]
The bidWon event is triggered by the ad render. Since the prebid ad doesn't always win, it's impossible for us to say when the last one will come. So unfortunately we don't have this event and won't be able to implement it.

**Comment by GeneGenie** [comment]
pbjs has a method getAllWinningBids, 
you can use it in pair with gpt pubads service events. 
https://developers.google.com/doubleclick-gpt/reference#googletageventsslotonloadevent
https://developers.google.com/doubleclick-gpt/reference#googletageventsslotrenderendedevent

You can call pbjs method (maybe add 10ms timeout) when slots which you're interested in are loaded/rendered, and make win/lose decisions.
