### ISSUE TITLE
Change hb_uuid key to => hb_cache_id

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#2189]
Currently for video bids, we cache using the uuid. This key is passed as `hb_uuid`. Unfortunately we also are using the same key as `hb_cache_id` for Prebid Server. We need to unify these keys.

I propose we change the current `hb_uuid` key in prebid.js to match prebid server `hb_cache_id`

**Comment by jaiminpanchal27** [comment]
We have added `hb_cache_id` with this PR https://github.com/prebid/Prebid.js/pull/2363
We will be deprecating the usage of `hb_uuid`

**Comment by bretg** [comment]
So my recollection is that we decided not to do this. Mainly because there's too big of an installed base to change everyone's ad server creatives. But seems like there was another reason -- like a difference between the needs of video and mobile?
