### ISSUE TITLE
PubMatic adapter bug on IE?

### ISSUE THREAD

**Issue by adamnewsnow** [prebid/Prebid.js#219]
On all versions of IE I see the following error inside the PubMatic adapter:

SCRIPT5: Access is denied

This occurs on this line of code in the PubMatic adapter:

		//todo make this more browser friendly
		var iframeDoc = iframe.contentWindow.document;

Searching the web, it appears that there are issues with accessing contentWindow for a programatically-created IFRAME on IE.

**Comment by pdramos1** [comment]
You probably want something like this for older IE's 
	doc.parentWindow.frameElement.
Where doc is a handle to the generated iframe. 
I have some general shim stuff that I need to put out that will make prebid more old IE friendly. (not necessarily adaptor specific at all)

**Comment by mkendall07** [comment]
@adamnewsnow 

Yes we will fix this. Thanks for pointing it out.

**Comment by adamnewsnow** [comment]
@mkendall07 I'm currently testing a fix, which is as simple as modifying createInvisibleIframe as follows:

-       f.src = 'about:self';
+       f.src = 'about:blank';

So far this works on all versions of IE I've tested.

**Comment by adamnewsnow** [comment]
Update: the above fix works on all versions of IE from 13 down to 10; on IE9 there is a strange issue which looks like an order of evaluation problem: "progKeyValueMap is undefined". It looks like the <script> tag which reads progKeyValueMap executes before the PubMatic JS has completed. I haven't been able to fix this issue.

**Comment by mkendall07** [comment]
This will be fixed when the pubmatic branch is merged.
