### ISSUE TITLE
Check all bids snippet needs investigation/update

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#2190]
The rendered ad snippet isn't working for all cases.

I ran this on a site with 2 rendered bids and it told me 1 wasn't rendered.

![image](https://user-images.githubusercontent.com/1870166/36618015-829e2d84-18b7-11e8-80dd-fd67acac65c5.png)

```
(function() {
  var responses = ga_pbjs.getBidResponses();
  var winners = ga_pbjs.getAllWinningBids();
  var output = [];
  Object.keys(responses).forEach(function(adUnitCode) {
    var response = responses[adUnitCode];
    response.bids.forEach(function(bid) {
      console.log(bid);
      output.push({
        adunit: adUnitCode,
        size: bid.size,
        adId: bid.adId,
        bidder: bid.bidder,
        time: bid.timeToRespond,
        cpm: bid.cpm,
        msg: bid.statusMessage,
        rendered: !!winners.find(function(winner) {
          return winner.adId==bid.adId;
        })
      });
    });
  });
  if (output.length) {
    if (console.table) {
      console.table(output);
    } else {
      for (var j = 0; j < output.length; j++) {
        console.log(output[j]);
      }
    }
  } else {
    console.warn('NO prebid responses');
  }
})();```

**Comment by chefbenjamin** [comment]
Just checking to see if there has been any progress here.

**Comment by mkendall07** [comment]
@chefbenjamin 
I think this might actually be related to your implementation. I'll send an email

**Comment by mkendall07** [comment]
sorry scratch that. It looks like the issue is that `pbjs.getAllWinningBids();` is not returning all winning bids after all.

**Comment by chefbenjamin** [comment]
@mkendall07 ok cool. let me know if you want me to test something.

**Comment by chefbenjamin** [comment]
@snapwich happy to share with you, but prefer to send privately. Best email address ?

**Comment by snapwich** [comment]
@chefbenjamin rsnapp@rubiconproject.com
