### ISSUE TITLE
Audience Network - If Native Format is passed ANY size should work

### ISSUE THREAD

**Issue by jfb716** [prebid/Prebid.js#2196]
## Type of issue
Bug

## Description
In the adapter you have 300x250 and 320x50 as the only accepted sizes (which is correct), but if a publisher is running native we should accept any size since it'll be native on their site and not a standard IAB size like 300x250 and 320x50.  You actually wouldn't want to run native through those sizes since that wouldn't be true native.  

## Steps to reproduce

This configuration doesn't fire the AN endpoint but it should since i'm passing 'native' as the format:

var adUnits = [{
              code: 'div-gpt-ad-1',
              sizes: [[728, 90]],
              bids: [{
                  bidder: 'audienceNetwork',
                  params: {
                     placementId: '154187914959322_519264628451647',
                     format: 'native'
                  }
              }]
          }];

## Test page

I have this live here: https://jfb716.github.io/ 

If you change the adUnit size to 300x250 or 320x50 you see the bid request triggers. 

### Expected results

If 'native' is passed in the adUnit configs, we should not do a size check since native can be any size the publisher wishes.  

### Actual results

The endpoint doesn't trigger, doesn't get past the invalid size check.  

## Platform details
N/A - happening across the board, not platform specific

## Other information
N/A

CC @lovell

**Comment by snapwich** [comment]
@lovell maybe native needs an exception here, like video does?  https://github.com/prebid/Prebid.js/blob/master/modules/audienceNetworkBidAdapter.js#L29

**Comment by lovell** [comment]
Hello, thanks for reporting this problem, I plan to submit a PR to address this in the next couple of days.

**Comment by snapwich** [comment]
@lovell would you mind looking at #2199 while you're at it as well to see if it's an issue?  Thanks.

**Comment by lovell** [comment]
PR for this at #2203.

**Comment by jfb716** [comment]
Hey @lovell technically the Fullwidth should only work when configured for a 300x250.  We wouldn't ever want this to server through a 320x50 because it would look really bad and cause problems on a publishers site. Native should work for any and all sizes, but fullwidth i would restrict to 300x250.  Let me know what you think.

**Comment by lovell** [comment]
@jfb716 That's a good question. The `fullwidth` format "extends beyond the 300x250 frame" so perhaps it might make sense to future-proof and remove the existing size limitation here also, even if most ads will still be using IAB dimensions for now.

https://developers.facebook.com/docs/audience-network/web/fullwidth

**Comment by jfb716** [comment]
@lovell I spoke to the team and the consensus is to restrict fullwidth to only 300x250 if possible (messaged you on facebook).   Let me know if that's feasible, thanks for your help!

**Comment by lovell** [comment]
This was fixed in v1.5.0 via commit https://github.com/prebid/Prebid.js/commit/c54a1795c73314db07071e8437681694762e8658

**Comment by jfb716** [comment]
Hey @lovell! We just realized this is only in the 1.0+ library, is there any way to get it into the pre 1.0 library as well?  Thanks!
