### ISSUE TITLE
prebid is returning a size that was not requested.

### ISSUE THREAD

**Issue by EM-LuisGalaz** [prebid/Prebid.js#2200]
# Description
I am defining an adUnit as:
```
{
        code: "home_8115",
        sizes: [
            [970, 300],
            [970, 250],
            [970, 90],
            [728, 90]
        ],...
```

however, I am getting a bid back that has an adUnit with a size that is not included in the requested array:

![screenshot from 2018-02-26 16-07-42](https://user-images.githubusercontent.com/13157675/36701135-7ece76dc-1b0f-11e8-9d78-215b9ad71378.png)

This also happens for other adUnits, and it happens randomly.  The google tag is also defined with the correct sizes:

```
googletag.defineSlot("/4403/th/kidzworld/home", [
            [970, 300],
            [970, 250],
            [970, 90],
            [728, 90],
        ], "home_8115").
```

### Expected results
Is the size not defined by that one specified at the adUnit request?

## Platform details
I am using prebid 0.34.3. tested on multiple versions of chrome for linux and windows.

**Comment by snapwich** [comment]
@EM-LuisGalaz does this only happen with indexExchange?  Or is it happening with other bidders as well?

**Comment by EM-LuisGalaz** [comment]
I only have indexExchange for this prebid implementation.

But this problem seems to only happen in chrome. I've been testing in firefox and have not been able to reproduce the wrong behavior there.

**Comment by EM-LuisGalaz** [comment]
Also, one thing I have noted is that the "erroneous" size has always been part of the sizes defined for the first adUnit defined in the adUnits array. 

That is, if I just change the order in which the adUnits are defined, then the size that starts to "take over" when not called, will change. 
For example, if I have size "728x90" as a size for the first adUnit (adUnits[0]) then there might be an adUnit that does not define "728x90" but that the displayed ad ends up being a "728x90". If I switch the order and have a "300x600" in the first adUnit (I put the 728x90 as any element other than the first), then suddenly the ad that is only requesting 728x90 will come up with a 300x600.

**Comment by mkendall07** [comment]
We don't actually validate sizes that are returned by prebid demand partners. So it's possible index Exchange is just sending back sizes that aren't on the request. Some bidders do this

**Comment by EM-LuisGalaz** [comment]
Ok, we'll check this with the bidder then.

In the mean time, this seems to be resolved by removing: pbjs.setTargetingForGPTAsync()

Thanks @mkendall07
