### ISSUE TITLE
Include in documentation the need to enable Fastlane on the Rubicon Project Side 

### ISSUE THREAD

**Issue by caseybryan** [prebid/Prebid.js#223]
I have noticed a few existing Rubicon Project publishers trying to get setup and met with a error because they didn't get the proper authorization from the RP team. 

Can we include in the documentation a note to say something like: Fastlane adapter utilization requires setup and approval from the Rubicon Project team, even for existing Rubicon Project publishers. Please reach out to your account team or globalsupport@rubiconproject.com for more information.

**Comment by mkendall07** [comment]
@caseybryan 

Thanks will do

**Comment by mkendall07** [comment]
Fixed.
