### ISSUE TITLE
prebidServerBidAdapter /cookie_sync requesting too many syncs

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#2242]
## Type of issue
possible bug

## Description
Prebid Server /cookie_sync calls are going out for all bidders in the AdUnit rather than just bidders in s2sConfig

We believe that only server-side bidders should be part of /cookie_sync

## Steps to reproduce
- set up s2sConfig with 1 server-side bidder
- set up an AdUnit with 3 bidders, including the server-side bidder
- watch the /cookie_sync payload

### Expected results

/cookie_sync payload contains only the 1 bidder defined in s2sConfig

### Actual results

/cookie_sync payload contains all 3 bidders in the AdUnit

## Other information

prebidServerBidAdapter specifically gets the list of bidderCodes from the AdUnit
```
in prebidServerBidAdapter.js line 106 :@param  {Array} bidderCodes list of bidders to request user syncs for. which is based on bidderCodes from adaptermanager.js
let bidderCodes = getBidderCodes(adUnits);
```

**Comment by bretg** [comment]
@mkendall07 - if you agree this is an issue, will assign it internally

**Comment by mkendall07** [comment]
sure

**Comment by bretg** [comment]
Did assign this internally, just hasn't reached the top of the queue.

**Comment by jsnellbaker** [comment]
@bretg I looking over the current code in the `prebidServerAdapter.js` file and it looks like this issue has already been addressed.  

The `queueSync` function that uses the `bidderCodes` variable and generates the POST request is pulling from the `s2sconfig.bidders` field.
https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter.js#L100

I setup a test page with the `appnexus` and `rubicon` bidders included in the `adUnits` object and only `appnexus` in the s2sconfig and only `appnexus` was included in the cookie_sync request.  Would you be able to take another look to confirm if everything is working as expected?

Thanks.

**Comment by JoyceBabu** [comment]
How can I limit the requests when using AppNexus Prebid Server with AMP page, since we don't have access to `s2sConfig`?

**Comment by mkendall07** [comment]
@bretg 
can this be closed? 
@JoyceBabu 
This isn't applicable to AMP since prebid.js doesn't load. Thanks

**Comment by bretg** [comment]
Closing - thanks.
