### ISSUE TITLE
prebidserverBidderAdapter does not set vastUrl

### ISSUE THREAD

**Issue by muncha** [prebid/Prebid.js#2243]
## Type of issue
Feature request

## Description
prebidserverBidderAdapter.js  sets the vastXML to the received adm if available. It should also set the vastUrl based on the nurl if received.

**Comment by muncha** [comment]
I can go ahead and fix this. I'm not sure if it needs to be assigned to me, or should I just put in a pull request?

**Comment by mkendall07** [comment]
thanks for the report. A pull request is fine.

**Comment by muncha** [comment]
It doesn't look like I can really set up a test for this right now. The only s2s adapter that I know of that uses vastUrl is the one I'm working on (beachfront), and that's still in the works.

This is only a one line change, btw, but it's my fist PR, so I'd like to go through the process, though it would probably be easier for you to just drop it into #2206.

**Comment by muncha** [comment]
Maybe it makes more sense for me to just post a comment on #2206 for this? It's just a one line change, and it would be for include_app_device branch, not master, and the contributing instructions  don't really cover that. So maybe before you do the final merge for #2206 you would just drop in :

`if (bid.nurl) { bidObject.vastUrl = bid.nurl; }`

appropriately before or after the corresponding line for bidObject.vastXML? I'm also not sure what you would want in the case that both a adm and a nurl were both received for video, or if that would ever happen.

I was looking forward to doing a PR, but since this one wouldn't be on master, it's extra complicated (not supported?). I'll have my beachfront adapter ready for a PR on prebid-server shortly, and that is PR to master, so that should be straight forward.
