### ISSUE TITLE
Index Exchange/Casale Adapter Not Available in 1.x.x

### ISSUE THREAD

**Issue by spencerbeggs** [prebid/Prebid.js#2256]
## Type of issue
Question

## Description
The Index Exchange/Casale adapter was available in the 0.34.4 release of prebid.js, but in the 1.x.x branch it is no longer available as an option. Are there plans to readd it or should we use a different technique to use Index Exchange with the current API?

**Comment by YOzaz** [comment]
In fact, there are some important adapters still missing:

- Triplelift
- Unruly (https://github.com/prebid/Prebid.js/pull/2207 - PR?)
- SpotX (no plans for 1.x, afaik)
- IndexExchange
- Criteo

**Comment by chefbenjamin** [comment]
I know that Index and Criteo both have them in development.

**Comment by spencerbeggs** [comment]
I received this reply from IX this morning:

> [A]t this time we have not yet established our Prebid 1.0 adapter as we focused on our own Wrapper initiatives in Q1. However, it will be our priority to start and complete our adaptor next month.

**Comment by mercuryyy** [comment]
Im also only waiting on Index to move to 1.x.x 
Dont see the logic for such a big company to not address this quickly everybody else has.

**Comment by L1quid** [comment]
Criteo says their 1.0 adapter is in beta now and is expected to launch in the next few weeks.

**Comment by chefbenjamin** [comment]
We have the Criteo 1.0 Beta Adapter working, but not in production yet.

**Comment by gramorris** [comment]
Quick update on this. I’ve been told by IX their 1.0 adapter is due in Q2 but not imminent. We are preparing for the possibility of having to go to 1.0 for GDPR without IX.

**Comment by mercuryyy** [comment]
Same here, we changed to 1.0 without IX. To bad. Hopefully they can come around soon.

**Comment by YOzaz** [comment]
Same. Waiting for IX to publish their adapter - but moving to 1.x without them.
