### ISSUE TITLE
The ads cannot be refreshed because the GPT implementation Javascript is not yet loaded.

### ISSUE THREAD

**Issue by sajokj** [prebid/Prebid.js#2259]
## Type of issue
Some times none of the ads are loaded, not sure anyone experienced this issue when they implement prebid

## Description
At times I see all adunits are blank and no DFP calls has been made and DFP console gives and error
"The ads cannot be refreshed because the GPT implementation Javascript is not yet loaded."
## Steps to reproduce
90% of times it works but at times it give this error.

**Comment by bretg** [comment]
Suggestions:
1) review Google's guidelines: https://developers.google.com/doubleclick-gpt/common_implementation_mistakes

2) post a minimal test page that exhibits the behavior

**Comment by mgarabedian** [comment]
For anyone coming across this error message from DFP, you cannot manually display or refresh ads before googletag.pubadsReady is true. It will result in this error.
