### ISSUE TITLE
Prebid.org site example shows old Adapter setup

### ISSUE THREAD

**Issue by caseybryan** [prebid/Prebid.js#226]
Can we please update the example on: http://prebid.org/dev-docs/getting-started.html to include the new Rubicon Project Fastlane adapter to keep it consistent with the documentation for 0.6.  It shows "zonesize" which will not work.

**Comment by mkendall07** [comment]
@caseybryan  thanks for reporting the issue. I've created https://github.com/prebid/prebid.github.io/issues/18 to track it.
