### ISSUE TITLE
Struggle_download_prebid.js

### ISSUE THREAD

**Issue by PublisherFR** [prebid/Prebid.js#2264]
## Type of issue
bug

## Description
By clicking in the email for downloading the prebid.js => we get an error page 

```
> Not Found
> The requested URL /downloads/prebid_20180312120713.js.gz was not found on this server.
> Apache/2.2.15 (CentOS) Server at client-test.devnxs.net Port 80
```

## Steps to reproduce
Go to: http://prebid.org/download.html
Select bidders (in our case: we chose: CriteoBidAdapter; PiximediaBidAdapter; QuantumBidAdapter; RubiconBidAdapter)
Click on GET Custom prebid.js
check you email inbox
click in the email

Here is the email that we received:
```
Thank you for choosing Prebid.js! 

You have requested to compile Prebid.js with the below header bidding partners: 
-CriteoBidAdapter
-PiximediaBidAdapter
-QuantumBidAdapter
-RubiconBidAdapter

The compiled prebid.js file with the above demand partners has been minimized to kb. Please download the file from this link and unzip it. 
Important: verify the md5 sum we have computed before using: undefined

Thank you! 
Prebid Team 
```

Many thanks in advance for your help

**Comment by mkendall07** [comment]
Thanks for the report. Will look into it

**Comment by PublisherFR** [comment]
Hello Matt, Hope you're doing fine. I'm curious, did you have the time to check and understand why we aren't able to download Prebid.js? Do you have any recommandation?
Looking forward to hearing from you. 
Maya from GMC Media

**Comment by mkendall07** [comment]
hi @PublisherFR 
The problem is that QuantumBidAdapter is not available in pre 1.x releases of prebid. This adapter is only supported in Prebid > 1.5. Thanks
