### ISSUE TITLE
Where can I find documentation about the bid-caching feature ?

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#2271]
## Type of issue
Question

## Description
Where can I find documentation about the bid-caching feature ?
When this feature is released ?
I saw the feature mentioned on issue https://github.com/prebid/Prebid.js/issues/2225

**Comment by pm-harshad-mane** [comment]
Hello @mkendall07 ,

Can you help us here ?

**Comment by mkendall07** [comment]
bid caching in the context of that ticket just meant "in memory" I believe. As in we hold the bid in internal data structures.
