### ISSUE TITLE
Question: How to install prebid code under WordPress

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#2280]
I am new to WordPress.
Question: What do I need to know to install the prebid code under WordPress?

**Comment by bretg** [comment]
Sorry, but we're not able to provide support for wordpress. Judging by Wordpress's site, you can't add Javascript, which would make adding Prebid.js impossible. https://en.support.wordpress.com/code/

**Comment by headerbidding** [comment]
Really, no support for WordPress?

 

WordPress, long known to be the No. 1 content management system (CMS) in use online, has reached a new milestone: 

It now powers 25 percent of all sites across the web. That's according to the newest data from W3Techs, a company that tracks the usage of different web technologies.

https://martechtoday.com/wordpress-used-on-25-percent-of-all-websites-report-151115

 

re Javascript, I did a Google Search and found this:

https://calderaforms.com/2016/11/how-to-load-custom-javascript-in-wordpress/

 

Please re-open the question. I am sure someone has figured out the best way to implement prebid.js with WordPress.
