### ISSUE TITLE
PubMatic - Ad tracker not being fired

### ISSUE THREAD

**Issue by mjwhaley** [prebid/Prebid.js#229]
We have recently added Pubmatic into the header and its bidding/rendering ads lovely. But Pubmatic aren't counting the impressions at all. 

Has anyone seen issues with Pubmatic's ad tracker not being fired?

**Comment by mkendall07** [comment]
@Heray 
Anyone using PubMatic that could chime in?

**Comment by mjwhaley** [comment]
@jdelhommeau @Heray I'm in contact with Pubmatic and they believe that everything from PreBid 5.0 isn't working correctly. It's looking like it's not completely sending the whole URL string of the bid and thus the won impression isn't being tracked by Pubmatic. Pubmatic are seeing every ad request, the winning ad is being delivered and rendered to the page, but Pubmatic are counting nothing.

**Comment by mkendall07** [comment]
@mjwhaley 
I checked the code and it looks like Pubmatic is returning a `tracking_url` that is not being fired. Can you send me your configuration details for Pubmatic so i can test this quickly?

**Comment by mjwhaley** [comment]
@mkendall07 I have a test page running here
http://streamamp.co.uk/advertising_github_prebid_6/

**Comment by mkendall07** [comment]
@mjwhaley 

Can you try with this build of prebid.js and see if it resolves the issue?
[prebid.js.zip](https://github.com/prebid/Prebid.js/files/163476/prebid.js.zip)

**Comment by mjwhaley** [comment]
@mkendall07 I have amended the follow page with the new build of prebid.js 
http://streamamp.co.uk/advertising_github_prebid_6/

**Comment by mjwhaley** [comment]
@mkendall07 Pubmatic and Myself are running some tests and will confirm back soon. Initial tests are looking positive though. Thanks for the help.

**Comment by mkendall07** [comment]
@mjwhaley 
Good to hear. Please keep me posted.

**Comment by mjwhaley** [comment]
@mkendall07 This is now working and tracking paid impressions in Pubmatic. Thanks for all of you help. When do you think you will be updating the normal pull of prebid.js to reflect this change?

**Comment by mkendall07** [comment]
@mjwhaley 
I merged the fix to master.
