### ISSUE TITLE
dfp.buildVideoUrl bug with the url option?

### ISSUE THREAD

**Issue by terebentina** [prebid/Prebid.js#2291]
## Type of issue
bug?

## Description
I am trying to figure out if this is a bug or not. When calling `dfp.buildVideoUrl()` with the `url` option the code is splitting the url into its parts and then rebuilding it in `buildUrlFromAdserverUrlComponents()`. However, it seems to me that any `cust_params` that might have been there in the initial url is getting overwritten here: https://github.com/prebid/Prebid.js/blob/master/modules/dfpAdServerVideo.js#L126-L129
Which doesn't seem to be the case when calling  `dfp.buildVideoUrl()` with the `params` option: https://github.com/prebid/Prebid.js/blob/master/modules/dfpAdServerVideo.js#L88-L93

## Platform details
This is the same in the latest 0.x and on `master` as well.

**Comment by mkendall07** [comment]
@terebentina 
this sounds like a bug.

**Comment by jsnellbaker** [comment]
@terebentina Can you provide a sample URL you were using where you saw the issue occur?

**Comment by terebentina** [comment]
Not really, nothing public yet but I can try to create a jsfiddle maybe using one of yours as a base but it probably won't happen this week. I simply noticed that when calling `buildVideoUrl()` with the url, my custom params weren't there anymore but they were when using `params`. I started investigating my code (see maybe I encoded the cust_params wrong or something) and dug down till I found this issue in prebid. I am working with 0.x for now but it looks like the same code for 1.x as well.

**Comment by jsnellbaker** [comment]
@terebentina as you may have seen with the note above, I have put together a fix for this issue.  Please feel free to checkout the branch (note - the branch is for 1.x) and test it out; if you're still encountering an issue - please let me know the details so we can investigate further.

**Comment by jsnellbaker** [comment]
@terebentina  This should be fixed now in 1.7 release.  If you continue to see any issues, please let us know.
