### ISSUE TITLE
Get Refresh counter in buildRequests for same adUnit in Bidder Adapter

### ISSUE THREAD

**Issue by vedantseta** [prebid/Prebid.js#2295]
## Type of issue
Feature

## Description

Bidders doesn't come to know if  `buildRequests` is called multiple times for same slot. It would be better to have counter for the same.

**Comment by mkendall07** [comment]
What's the use case?

**Comment by vedantseta** [comment]
@mkendall07 , Certain bidders might not want to bid on refresh slots on specific domains.

**Comment by vedantseta** [comment]
Is PR accepted for this?

**Comment by mkendall07** [comment]
so, basically a counter to know how many times `requestBids` was invoked? I'm ok with a global counter but I don't want to store it by bidder. Too much state to carry around.
