### ISSUE TITLE
Get bidder timeout in buildRequest 

### ISSUE THREAD

**Issue by vedantseta** [prebid/Prebid.js#2296]
## Type of issue
feature request

## Description

Publisher can pass timeout while calling `requestBids`, in `buildRequest` bidder spec, that timeout is not passed. If timeout is passed, bidder can respond accordingly.

**Comment by vedantseta** [comment]
@jsnellbaker , is PR accepted for this?

**Comment by jaiminpanchal27** [comment]
@vedantseta Why would bidder need a timeout on the server ? Shouldn't bidder respond as soon as possible ?

**Comment by ruturajv** [comment]
@jaiminpanchal27 This gives the bidder / adapter a chance to add more data lookups and logic before bidding.

**Comment by jaiminpanchal27** [comment]
@vedantseta You can submit a PR for this. Thanks

**Comment by vedantseta** [comment]
@jaiminpanchal27 , [Here](https://github.com/prebid/Prebid.js/blob/8719aefad0dc91d3789ed858c98997d5521f8ea2/src/adapters/bidderFactory.js#L203) spec.buildRequests is called with an extra param bidderRequest which contains timeout. Curious why this param isn't added in the [prebid documentation](http://prebid.org/dev-docs/bidder-adaptor.html#building-the-request)?

Seems this PR is unnecessary.

**Comment by jaiminpanchal27** [comment]
Oh yes you are right. That bidderRequest was added later on and docs were not updated. Thanks for pointing out. 
I have created issue https://github.com/prebid/prebid.github.io/issues/682 and will fix soon.
