### ISSUE TITLE
why prebid-server adapter initiates cookie_sync call before auction (in setS2sConfig) ?

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#2299]
## Description
We have a query regarding pribid-server adapter executing cookie_sync end-point in setS2sConfig.
Refer: https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter.js#L100

Scenario:
In a scenario, say there are 4 client-side adapters and 4 server side adapters.
Lets say we are initiating requestBids call immediately after calling setS2sConfig.
Then when bids are requested, 4 client-side adapters will make call to their respective servers. 
Number of HTTP calls = 4
Also prebid-server adapter will make one call to prebid server to get bids from server-side configured adapters.
Number of HTTP calls = 4+1 => 5
prebid-server adapter will also initiates cookie_sync call to probed-server which might result in 4 syncup URLs for 4 server-side adapters.
Number of HTTP calls = 5 + 1 + 4 => 10

Problem:
Initiating cookie_sync for server-side adapters nearly at time of auction and when page is loading content may impact the adapters executing on client-side (they might get lower priority in call stack and they may timeout).

Our Thought:
If prebid-server adapter does user-sync with some delay, may be post auction, then number of calls initiated will be 5 during auction.
Any way for for a first impression for a user making parallel calls to auction and user-sync will not help in terms of user-match-rate.
So we can execute user-sync for server-side partners post auction to avoid impact on client-side adapters.

Please share your thoughts.

**Comment by mkendall07** [comment]
@pm-harshad-mane 
yes it's a good callout. We attempted to do some of that here https://github.com/prebid/Prebid.js/commit/d566700089066fce4a2b9400999360b246c0435a#diff-730364dfb4460a9d1e2ae8853ba583b2 but it turned out to not work very well.

Open to suggestions how we might optimize this.

**Comment by pm-harshad-mane** [comment]
Hi @mkendall07 ,
I think we should delay the cookie-sync until end of auction.

**Comment by pm-harshad-mane** [comment]
Call to cookie-sync end-point = 1
Number of calls made to sync one server-side adapter = 2 (one to adapter and one to push the adapter's uid into prebid-server cookie domain)
Additionally If adapter syncs with some DSPs then there might be 2 calls per DSP.

And if we do not let adapters to sync with their DSPs then adapter's match rate will drop with DSPs resulting into lower bids.

**Comment by bretg** [comment]
I'm sure the idea was to try to get the exchange IDs ASAP. /cookie_sync doesn't set DSP IDs -- that's part of the "userSync" functionality which is after the auction.

Do you have any tangible evidence that cookie_sync activity is affecting the auction?
