### ISSUE TITLE
Notify bidder on adRenderFailed event

### ISSUE THREAD

**Issue by vedantseta** [prebid/Prebid.js#2303]
## Type of issue
feature request
## Description

A new `adRenderFailed` event is created which fires when ad render fails. Even bidder should be notified if ad render fails because of ad code. This can be callback to public function in bidder spec similar to `getUserSyncs `, `interpretResponse` etc. and receiving bid data. 

## Other information
This is extension of #2210 .

**Comment by mkendall07** [comment]
closing this out since no one has picked up on the work
