### ISSUE TITLE
Hardcoded non-ssl urls

### ISSUE THREAD

**Issue by dwick** [prebid/Prebid.js#231]
There are a few different places where `http` is hardcoded:

Can be made protocol relative:
https://github.com/prebid/Prebid.js/blob/b8de2b6c286a390e0cb19d0a69a76580fd38ad13/src/adapters/pulsepoint.js#L7-L8
https://github.com/prebid/Prebid.js/blob/b8de2b6c286a390e0cb19d0a69a76580fd38ad13/src/adapters/springserve.js#L10

Unsure, can't find vendor docs:
https://github.com/prebid/Prebid.js/blob/b8de2b6c286a390e0cb19d0a69a76580fd38ad13/src/adapters/rubiconLegacy.js#L96

If anyone has a clue about the last one I'd be glad to fix it.

**Comment by mkendall07** [comment]
@dwick 
For the last one `rubiconLegacy` we will remove
