### ISSUE TITLE
sizeConfig[Conditional Ad Units] does not work when s2sConfig is enabled.

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#2315]
trying to set sizeConfig from this doc for 1.7 prebid http://prebid.org/dev-docs/conditional-ad-units.html

When using the new sizeConfig[Conditional Ad Units] the adunits for the s2s are null and for bidders not in s2s it send them correctly. 

I tested few configuration and when sizeConfig is enabled with  the new Conditional Ad Units it does not send the ad units to s2s bidders.

once i remove the bidders from s2sConfig everything fires correctly.

**Comment by mkendall07** [comment]
@mercuryyy 
do you have an example page?

**Comment by mercuryyy** [comment]
@mkendall07  i used this pull and it fixes some of the issues - https://github.com/javipm/Prebid.js

Any configuration you put in with sizeconfig and then enable a bidder in s2s it wont send the bids to the s2s adapter

**Comment by jsnellbaker** [comment]
@mercuryyy  This should be fixed now in 1.7 release.  If you continue to see any issues, please let us know.
