### ISSUE TITLE
getBidLandscapeTargeting ignores adUnitCodes paramter

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#2327]
## Type of issue
bug

## Description
`getBidLandscapeTargeting` method receives adUnitCodes parameter but never uses it. As the result when I can setTargetingForGPTAsync and specify `adUnit` parameter, targeting is being set on all units instead of just the one I sent as a parameter.

## Steps to reproduce
1. Create 2 units
2. Run auction
3. Call pbjs.setTargetingForGPTAsync('ad_unit_code_1')

### Expected results
Targeting is being set on the ad unit 1, but not on the ad unit 2

### Actual results
Targeting is being set on both ad units.

## Platform details
1.7.0-pre but the bug also exists in 0.34 branch

**Comment by jsnellbaker** [comment]
@dmitriyshashkin Thanks for submitting this issue, we'll investigate.

**Comment by jsnellbaker** [comment]
@dmitriyshashkin This should be fixed now in 1.7 release.  If you continue to see any issues, please let us know.
