### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#233]
npm WARN package.json prebid.js@0.6.0 No repository field.
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer gulp-karma@0.0.4 wants karma@>=0.10 <=0.13
npm ERR! peerinvalid Peer karma-chai@0.1.0 wants karma@>=0.10.9
npm ERR! peerinvalid Peer karma-coverage@0.2.7 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-html-reporter@0.2.7 wants karma@>=0.11
npm ERR! peerinvalid Peer karma-ie-launcher@0.1.5 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-junit-reporter@0.3.8 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-nyan-reporter@0.2.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-opera-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.2.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.5 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-safari-launcher@0.1.1 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-sinon@1.0.4 wants karma@>=0.10

npm ERR! System Darwin 15.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/user/Sites/prebid-build/Prebid.js
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/user/Sites/prebid-build/Prebid.js/npm-debug.log
npm ERR! not ok code 0

**Comment by BartVB** [comment]
Could be related to:
https://github.com/prebid/Prebid.js/issues/192

**Comment by mkendall07** [comment]
@cwbeck 
Can you post what you have installed globally: `npm list -g --depth=0`

**Comment by cwbeck** [comment]
Update: Upgrading to latest version of Node/NPM on Mac resolved this issue. (now running v4.3.2).
