### ISSUE TITLE
sovrn creative id is random

### ISSUE THREAD

**Issue by smartbidder1** [prebid/Prebid.js#2374]
## Type of issue
bug

## Description
when requesting an ad from sovrn bidder `http://ap.lijit.com/rtb/bid?src=prebid_prebid_0.34.1` the response contains id, impid and nurl.
none of those parameters are unique per ad (creative id), and we can't identify an ad in that way (to blacklist for example).
any other partner are indeed returning a creative id (appnexus, Rubicon etc..)

in their RTB bidder on this URL: `http://ap.lijit.com/bidder` they indeed return a creative id.
can we tag them to add this also to their prebid bidder? what is the difference between the two endpoints anyway? why aren't we using the second one?
any suggestions? 

example of a returned bid from /bidder: (with creative id)
```{"id":"fb1f5b05-4487-4d1d-8d41-eb5f952dc5de","seatbid":[{"bid":[{"id":"a_531089_9b546a83bf044df9b8174524ccdf2363","impid":"doNotChange","price":0.2447500079870224,"nurl":"http://vap4ewr1.lijit.com/bidder/impression?bannerid=110833&campaignid=3299&rtb_tid=d984053f-f07b-4190-8305-352846a341a8&rpid=58&seatid=17104&zoneid=531089&cb=05301897&tid=a_531089_9b546a83bf044df9b8174524ccdf2363","adm":"<span class=\"PubAPIAd\"  id=\"05D5D69E-E9C8-4477-8A54-C5B2A04CB1B1\"><script type='text/javascript' src='http://image3.pubmatic.com/AdServer/layer?pubid=137711&nwid=252834&ts=1523353154&cid=17105&pimprid=d984053f-f07b-4190-8305-352846a341a8&uimprid=05D5D69E-E9C8-4477-8A54-C5B2A04CB1B1&mid=OpenRTBIntegration88044&plen=700&a=0.445&t=BWGZW09V0VUTVE9PT0maWQ9MCZjaWQ9MTcxMDUmY2Y9MSZmcD0wLjQ0NSZwcD0wLjQ0NSZ0cD0wJnNodj0wLjAwMDAwMCZwZT0wLjAwMDAwMCZwdWJpZD0xMzc3MTEmbmJmPTEmY3A9MC40NDUmc3Rwcj0wLjAwMDAwMCZzdHBlPTAuMDAwMDAwJnN0cGNhcD0wLjAwMDAwMCZwMj0zOjAuMDAwMDAwJmNsZW49MzQzJmNyPSUzQ3NjcmlwdCUyMHNyYyUzRCUyN2h0dHAlM0ElMkYlMkZhLW5qLjFyeC5pbyUyRnJ0YmRlbGl2ZXIlMkZqcyUzRmV4Y2lkJTNEcHVibWF0aWMlMjZwaWNrdXAlM0Q1NzhhYTE2ZmJmNTgxMWEzYjJkMDY5OWNkZTc4Nzg3YyUyNnpyayUzRDJhYWY3NmNiZGQzNGVlOGIyZDk3ZDJlYTQzNWVhOWRhJTI2emRzJTNEN2ViYjlhZWMwZWNmMmIyMzQ2NTlhOTQwMDYyM2YyOTQlMjZpbXAlM0Q2N2E1Yjc3ZGEyN2Q2ODk2ZmNjNjc4ZjEwM2NlZWIyOSUyNnJ0YnNlcnZlJTNEMSUyNnp3cCUzRCU3QlBTUE0lN0QlMjZwdiUzRDElMjZwcmMlM0RaWDAuMTMxNjU3Nzk2ODg5MzczMDclMjclM0UlM0MlMkZzY3JpcHQlM0U=='></script><iframe width=\"0\" scrolling=\"no\" height=\"0\" frameborder=\"0\" src=\"http://ads.pubmatic.com/AdServer/js/showad.js#PIX&ptask=DSP&SPug=1&fp=1&mpc=10&u=4688D265-2F10-4B85-ABDE-FF4FBB1EF105&p=137711&s=137812&d=2&cp=0&sc=0&rs=0&os=0\" style=\"position:absolute;top:-15000px;left:-15000px\" vspace=\"0\" hspace=\"0\" marginwidth=\"0\" marginheight=\"0\" allowtransparency=\"true\" name=\"synciframe\"></iframe></span> <!-- PubMatic Ad Ends --><iframe width=\"0\" scrolling=\"no\" height=\"0\" frameborder=\"0\" src=\"http://image3.pubmatic.com/AdServer/layer?pubid=137711&nwid=252834&ts=1523353154&cid=17105&pimprid=d984053f-f07b-4190-8305-352846a341a8&uimprid=05D5D69E-E9C8-4477-8A54-C5B2A04CB1B1&mid=OpenRTBIntegration88044&plen=1564&a=0.445&t=EVHZW09SUFXTVE9PT0maWQ9MCZjaWQ9MTcxMDUmY2Y9MSZmcD0wLjQ0NSZwcD0wLjQ0NSZ0cD0xJnNodj0wLjAwMDAwMCZwZT0wLjAwMDAwMCZwdWJpZD0xMzc3MTEmbmJmPTEmY3A9MC40NDUmc3Rwcj0wLjAwMDAwMCZzdHBlPTAuMDAwMDAwJnN0cGNhcD0wLjAwMDAwMCZwMj0zOjAuMDAwMDAwJmNsZW49OTkxJmNyPWh0dHAlM0ElMkYlMkZha3RyYWNrLnB1Ym1hdGljLmNvbSUyRkFkU2VydmVyJTJGQWREaXNwbGF5VHJhY2tlclNlcnZsZXQlM0ZvcGVySWQlM0QxJTI2cHViSWQlM0QxMzc3MTElMjZzaXRlSWQlM0QxMzc4MTIlMjZhZElkJTNENjEyMjk1JTI2YWRUeXBlJTNEMTAlMjZhZFNlcnZlcklkJTNEMjQzJTI2a2VmYWN0JTNEJTdCUFNQTSU3RCUyNmtheGVmYWN0JTNEJTdCUFNQTSU3RCUyNmthZE5ldEZyZXF1ZWN5JTNEMCUyNmthZHdpZHRoJTNENzI4JTI2a2FkaGVpZ2h0JTNEOTAlMjZrYWRzaXplaWQlM0Q3JTI2a2x0c3RhbXAlM0QxNTIzMzUzMTU0JTI2aW5kaXJlY3RBZElkJTNEMCUyNmFkU2VydmVyT3B0aW1pemVySWQlM0QyJTI2cmFucmVxJTNEMC4xJTI2a3BibXRwZmFjdCUzRCU3QlBTUE0lN0QlMjZ0bGRJZCUzRDIwMjkyMjk4JTI2cGFzc2JhY2slM0QwJTI2ZWtlZmFjdCUzRCU3QlBTUE0lN0QlMjZla2F4ZWZhY3QlM0QlN0JQU1BNJTdEJTI2ZWtwYm10cGZhY3QlM0QlN0JQU1BNJTdEJTI2c3ZyJTNEQklEODg0NjYlMjZpbXBySWQlM0QwNUQ1RDY5RS1FOUM4LTQ0NzctOEE1NC1DNUIyQTA0Q0IxQjElMjZvaWQlM0QwNUQ1RDY5RS1FOUM4LTQ0NzctOEE1NC1DNUIyQTA0Q0IxQjElMjZjb3VudHJ5JTNEREUlMjZjcklEJTNEY3ItOWNweDJkM3kyYXJmdjglMjZ1Y3JpZCUzRDU3OTU4OTc2MzA3MTU3MTQ3MzAlMjZjbnRyeUlkJTNENTglMjZjYW1wYWlnbklkJTNEMTcxMDUlMjZjcmVhdGl2ZUlkJTNEMCUyNnBjdHIlM0QwLjAwMDAwMCUyNndEU1BCeXJJZCUzRDEyMjklMjZ3RHNwSWQlM0Q1OTQlMjZ3YklkJTNEMiUyNndySWQlM0QyMzc4MTk3JTI2d0FkdklEJTNENjIwODIlMjZpc1JUQiUzRDElMjZydGJJZCUzRDEzRDNBMjNELUJBMDMtNEEzNi04RjJDLTA0NUM4RUUzRkJEMCUyNmRvbWFpbiUzRHd3dy5qcG9zdC5jb20lMjZwYWdlVVJMJTNEaHR0cCUyNTNBJTI1MkYlMjUyRnd3dy5qcG9zdC5jb20lMjUyRiUyNmxwdSUzRGtlbXBpbnNraS5jb20==\" style=\"position:absolute;top:-15000px;left:-15000px\" vspace=\"0\" hspace=\"0\" marginwidth=\"0\" marginheight=\"0\" allowtransparency=\"true\" name=\"pbeacon\"></iframe><script type=\"text/javascript\">\nvar zoneId=\"531089\",\nhost=\"ap.lijit.com\",\np=location.protocol,url=(\"https:\"===p?p:\"http:\")+\"//\" + host +  \"/res/sovrn.containertag.new.min.js?cid=3&zid=\"+ zoneId + \"&v=4\",scr=document.createElement(\"script\");scr.id=\"ct\",scr.src=url,scr.type=\"application/javascript\",scr.async=!1;var s0=document.getElementsByTagName(\"script\")[0];s0.parentNode.insertBefore(scr,s0);\n</script><script id=\"sovrn_standalone_beacon\" src=\"http://vap4ewr1.lijit.com/www/sovrn_beacon_standalone/sovrn_standalone_beacon.js?iid=13401930\"></script>","adomain":["kempinski.com"],"crid":"cr-9cpx2d3y2arfv8","w":728,"h":90}]}]}```

example of a returned bid from /bid/rtb: (no creative id)
```{"id":"42c85f909020c7e","seatbid":[{"bid":[{"id":"a_496632_452a54c7327b4741841f4e78be10e30f","impid":"273b68d855ae7eb","price":0.14704999327659607,"nurl":"http://vap6iad1.lijit.com/rtb/impression?bannerid=6473&campaignid=662&rtb_tid=bdc9c40b-363c-4ce0-af1a-e32e3f760189&rpid=3&seatid=100242&zoneid=496632&cb=62581389&tid=a_496632_452a54c7327b4741841f4e78be10e30f","adm":"%3Cscript%20language%3D'JavaScript'%20src%3D'https%3A%2F%2Ftags.mathtag.com%2Fnotify%2Fjs%3Fexch%3Dlij%26id%3D5aW95q2jLzE0LyAvTlRSa1pUazVOR1V0Tmpjd1lTMDVNekU0TFRBd01EQXRNREF3TURBd01EQXdNREF3LzQwNzI1NDkxMDY5MDc1NjUwNTUvNTUyMjU4NC8zMzAwMTM2LzE3L3NEMEJyV3RJUkpPZmhWSXdRNkNhbkxRSjJidDNpZk9RTlBPbkxvRzQ1alUvMS8xNy8xNTIyOTM5NDUzLzAvNjc4OTA5Lzc3NzUyNTU5MC8yMDc2MjkvNDk1ODM2LzEvMC8yL01EQXdNREF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF0TURBd01EQXdNREF3TURBdy8wLzAvMC8wLzAvNDA3MjU0OTEwNjkwNzU2NTA1NS9ld3Iv%2FuYPK-WQAgTy1nweUiaar00Zo_ww%26sid%3D3300136%26cid%3D5522584%26nodeid%3D1250%26price%3D0.173%26group%3Dus-east%26auctionid%3D4072549106907565055%26bp%3Da_bhcjba%263pck%3D%40CKURLE%40'%3E%3C%2Fscript%3E%3Cscript%20type%3D%22text%2Fjavascript%22%3E%0Avar%20zoneId%3D%22496632%22%2C%0Ahost%3D%22ap.lijit.com%22%2C%0Ap%3Dlocation.protocol%2Curl%3D(%22https%3A%22%3D%3D%3Dp%3Fp%3A%22http%3A%22)%2B%22%2F%2F%22%20%2B%20host%20%2B%20%20%22%2Fres%2Fsovrn.containertag.new.min.js%3Fcid%3D3%26zid%3D%22%2B%20zoneId%20%2B%20%22%26v%3D4%22%2Cscr%3Ddocument.createElement(%22script%22)%3Bscr.id%3D%22ct%22%2Cscr.src%3Durl%2Cscr.type%3D%22application%2Fjavascript%22%2Cscr.async%3D!1%3Bvar%20s0%3Ddocument.getElementsByTagName(%22script%22)%5B0%5D%3Bs0.parentNode.insertBefore(scr%2Cs0)%3B%0A%3C%2Fscript%3E","w":160,"h":600}]}]}```

@sovrnoss @aprakash-sovrn

**Comment by aprakash-sovrn** [comment]
Hey, thanks for pointing this out. We will investigate and prioritize.

**Comment by smartbidder1** [comment]
I've just checked all the rest of the bidders that our clients are working with, Pulsepoint shares the same bug.

querying `bid.contextweb.com/header/tag` won't return creative ID but querying  `bid.contextweb.com/header/s/ortb/prebid-s2s` will indeed return a creative ID.
@anand-venkatraman

**Comment by aprakash-sovrn** [comment]
Hi @smartbidder1, we understand the importance of relaying accurate creative id's and are actively working on a fix.

Thanks!
