### ISSUE TITLE
Send unminified custom Prebid.js

### ISSUE THREAD

**Issue by sinuhepop** [prebid/Prebid.js#2389]
## Type of issue
Feature request

## Description
If I recall correctly, some time ago when a custom js was sent from [download page](http://prebid.org/download.html) content was not minified. I think it could be interesting to do it again for some reasons:

- I have one strange error due to "_double minimization_". I minimize my resources using another tool and it seems that something is working incorrectly. Minimized file fails, but unminimized works. I had a similar experiencie years ago with another minified resource.
- Sometimes it's useful to debug code
- The effort for building an unminified file is not trivial

For all this, I think it could be interesting to receive both files (original and minified) in sent zip. Or at least, a checkbox to select which version.

**Comment by snapwich** [comment]
> The effort for building an unminified file is not trivial

Hopefully this should be _pretty_ trivial; if not, it may be a failing of documentation.  You can use the `gulp build-bundle-dev` command which doesn't seem to be mentioned in the README.md.

e.g.
```
git clone git@github.com:prebid/Prebid.js.git
cd Prebid.js
npm install
gulp build-bundle-dev --modules=rubiconBidAdapter,appnexusBidAdapter
```

As for how the download page acted in the past, that's probably a question for @mkendall07

**Comment by sinuhepop** [comment]
Yes, it's what I did. It's pretty trivial if you are working under a Node.js ecosystem ;)

**Comment by mkendall07** [comment]
cool. I don't remember ever sending unminified source. if it did it was a bug :) 
going to close this - might consider it in the future when re-build the download page but not going to commit for now.
