### ISSUE TITLE
Add Server Side or Client Side to Snippet 

### ISSUE THREAD

**Issue by chefbenjamin** [prebid/Prebid.js#2399]
## Type of issue
Feature 

## Description
For the all bids chrome snippet http://prebid.org/dev-docs/toubleshooting-tips.html#see-all-bids-in-the-console
Can we add a new column which indicates if the bid is client side or server side. Not sure what the column should be called. 

@jaiminpanchal27 we had discussed this here, https://github.com/prebid/Prebid.js/issues/2238#issuecomment-379769983 just adding a dedicated ticket here

**Comment by jaiminpanchal27** [comment]
@chefbenjamin Thanks for creating an issue. Will create a PR soon

**Comment by chefbenjamin** [comment]
Curious if this is being added ?
