### ISSUE TITLE
Adserver-Targeting empty with v0.34.6

### ISSUE THREAD

**Issue by EderlMarkus** [prebid/Prebid.js#2400]
Hey, I'll need your help, as this might look like a bug:

I'm trying to display the prebid Test-300x250 from Appnexus (ID: 10433394) as used here: http://prebid.org/dev-docs/getting-started.html

If I'm using v0.34.6 with the Appnexus-Adapter, it is not being displayed as the Targetings stay empty.

![image](https://user-images.githubusercontent.com/38421306/38797759-d8205888-415f-11e8-9092-4ae70980e08f.png)

However, if I'm using v1.6.0 I'm getting it fine:
![image](https://user-images.githubusercontent.com/38421306/38797873-36a3aedc-4160-11e8-9b31-4030bd3796cc.png)

I know the obvious Answer would be: just use v1.6.0, but I need v0.34.6 for the Xaxis-Adapter which is only available in v0.34.6.

Is there a known issue, that appenexus is not working in v0.34.6? 

Here are my used scripts:
v0.34.6:
https://adstatics.secondhandapp.com/Markus/Prebid/prebid_16042018.js
v1.6.0:
https://adstatics.secondhandapp.com/Markus/Prebid/prebid_16042018_2.js

Thanks for every help!

**Comment by mkendall07** [comment]
@EderlMarkus 
I don't think we've updated the appNexus adapter for awhile on the legacy branch. It should be working. Are you just not receiving bids possibly?

**Comment by EderlMarkus** [comment]
@mkendall07 
thanks for your fast reply!

currently it seems with v1.6.0 I'm recieving bids and they are rendered:
![image](https://user-images.githubusercontent.com/38421306/38853855-db2bd7ea-421e-11e8-9167-694708c5a314.png)

but with v.0.34.6 I'm not even getting responses:
![image](https://user-images.githubusercontent.com/38421306/38853887-f7401c16-421e-11e8-82e6-87b3dce2a3fe.png)

I'm using the placementId 10433394 here for the 300x250 as described in the "getting-started" instruction-page (http://prebid.org/dev-docs/getting-started.html)

**Comment by mkendall07** [comment]
@EderlMarkus 

can you share a link to the broken page?

**Comment by EderlMarkus** [comment]
Nothing so far, I'm guessing? :( Is there anything else I can provide or help with?
