### ISSUE TITLE
Komoona adapter not returning proper keys for empty bids

### ISSUE THREAD

**Issue by ncolletti** [prebid/Prebid.js#2415]
## Description
I am seeing komoona 1.x adapter send console.errors when they have an empty bid ore error response. 

The function isValid runs from the bid response of komoona which does not return proper keys to Prebid and spits out the console.error: "Invalid bid from komoona. Ignoring bid. Bidder komoona is missing required params..."

## Test page
Can provide if needed.

### Expected results
no console.error warning and a $0.00 response in pbjs.getBidResponses

## Platform details
Prebid 1.6 engine and latest komoona adapter

**Comment by aprakash-sovrn** [comment]
I believe this may be an issue with the legacy adapter in Prebid.js version 0.34.7 as well.

**Comment by bretg** [comment]
@tzafrirb can you take a look?
