### ISSUE TITLE
Acceptance tests in project

### ISSUE THREAD

**Issue by unrulydevelopers** [prebid/Prebid.js#2418]
## Type of issue
Question/ feature request

## Description
Hi,

In the required files section of the documentation it mentions providing a test ad in the .md file that "...helps us to ensure future Prebid.js updates do not break your adapter". Is this used to run an acceptance test? Or are there plans to run acceptance tests in the future?

If not, are we able to submit a PR with an acceptance test that hits our test page under /integrationExamples/gpt/ ?

Cheers,
Unruly developers

**Comment by jaiminpanchal27** [comment]
@unrulydevelopers Usually reviewer uses test param with [hello_world](https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/hello_world.html) page to test creative. 

We do not ask anyone for test page because we have observed that pages are not actively maintained.

**Comment by bretg** [comment]
Yes, you can refer to https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/unruly_example.html in your .md file.
