### ISSUE TITLE
RealVu Analytics unit test failure in mobile safari

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#2421]
## Type of issue
Bug

## Description
RealVu Analytics test https://github.com/prebid/Prebid.js/blob/master/test/spec/modules/realvuAnalyticsAdapter_spec.js#L69
fails in mobile safari

## Other information
@tchibirev

**Comment by tchibirev** [comment]
Hi Jaimin,
Yes, I review it, the realvuAnalyticsAdapter_spec.js has to be modified promptly. I will submit correction in a few days.
Thanks,
Igor Tchibirev
CTO |RealVu
295 Madison Avenue, 27th Floor, New York, NY 10017
o: +1(212) 375-9412x704, www.realvu.com

**Comment by jaiminpanchal27** [comment]
Thanks @tchibirev

**Comment by tchibirev** [comment]
@jaiminpanchal27 
I removed ".skip" but do not see the fail. Can you give me a clue how to reproduce the bug?
How do you include mobile Safari into gulp test? Thanks

**Comment by jaiminpanchal27** [comment]
@tchibirev We had to remove mobile safari browsers because browserstack stopped supporting mobile emulators recently and they now only support real mobile devices. With real devices config our tests were not triggered. We have reached their support for help. I will update here once we add mobile devices back.
