### ISSUE TITLE
[1.8.0&0.34.8] Concurrent issue with buildVideoUrl and setTargetingForGPTAsync

### ISSUE THREAD

**Issue by Slind14** [prebid/Prebid.js#2442]
`setTargetingForGPTAsync` tends to break `buildVideoUrl`. 

- If `setTargetingForGPTAsync` is executed first the url returned by `buildVideoUrl` is without targeting params. 
- If `buildVideoUrl` is executed first and the prebid cache failed display ads don't load (until the timeout kicks in to load dfp only) [1.8 only]

In terms of performance it makes sense to executed the async function as early as possible. In terms of revenue it makes also sense to load the display ads first. Unfortunately this causes a concurrency issues where the video url returned is without targeting.

**Comment by Slind14** [comment]
> If setTargetingForGPTAsync is executed first the url returned by buildVideoUrl is without targeting params.

Unfortunately I encountered further issues with both 1.8 and 0.3 where this did appear with `buildVideoUrl` being called first. It's not happening 9 out of 10 times like the other one but isn't extremely rare either.

**Comment by mkendall07** [comment]
yes that's a possibility

**Comment by mkendall07** [comment]
I believe @jaiminpanchal27 is working on this issue.

**Comment by Slind14** [comment]
Top, thank you. :)
