### ISSUE TITLE
Intent to Implement: Update bid pool logic to select highest cpm bid in case of multiple bids

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#2448]
## Type of issue
Feature Request

## Description
While running concurrent auctions there can be multiple bids from same bidder for same adUnit. As of now we use FIFO (First In First Out) to select bid to take part in auction.

#### Problem with above approach
Chance of decrease in revenue for some publishers because there can be a second bid having higher cpm and not getting selected to take part in auction due to FIFO.

#### Solution
Select highest cpm bid if you find multiple bids in the pool

**Comment by mercuryyy** [comment]
Any chance this to be released in next 1.9 ?

**Comment by mercuryyy** [comment]
@jaiminpanchal27   Having issues with some bidders with discrepancies when refreshing ads and not choosing bids from the new requested bids pool.

Can you possibly consider these changes for the next pb release?

**Comment by jaiminpanchal27** [comment]
@mercuryyy Sure will try to take this one.
