### ISSUE TITLE
appnexus video bids not considered valid by Prebid

### ISSUE THREAD

**Issue by kitwestneat** [prebid/Prebid.js#2449]
## Type of issue
bug/question

## Description
We are trying to set up Appnexus outstream video bidding on our site, but running into some problems. Our Appnexus contacts recommended that we file an issue here to document it.

Essentially the issue we are seeing is that our bid requests are returning bids with what appears to be a VAST tag in the rtbBid.rtb.video.content field, but this field is never used by the Prebid Appnexus module, likely due to a missing renderer_url field. 

From looking at the source, it looks like the appnexus module requires that outstream video bids return a renderer_url field, but our bids from Appnexus aren't returning that. Are we doing something wrong that would cause appnexus to not return a renderer_url field?

## Steps to reproduce
- get a bid from appnexus that doesn't have renderer_url set, here's an example:
{
        "uuid": "40ac356427aeca5",
        "tag_id": 12445762,
        "auction_id": "4040684562921651374",
        "nobid": false,
        "no_ad_url": "http://nym1-ib.adnxs.com/it?e=wqT_3QKeBqAeAwAAAwDWAAUBCIO0itYFEK755bK5ptmJOBjZud3wxcnLzm4qNgkAAAkCABEJBywAABkAAADAzMwsQCEREgApEQkAMQkJ8HgYQDDC0PcFOPwbQPwbSABQAFiArTRgAGib0k54AIABAZIBA1VTRJgBAaABAagBAbABALgBAMABAMgBAtABANgBAOABAPABAIoCO3VmKCdhJywgMTE5NzMzMywgMTUyMjcwMjg1MSk7dWYoJ3InLCA1NTM5MTY2MCwgLh4A8IeSAu0BIUh5NVVjUWlobnFFS0VLenJ0Qm9ZQUNDQXJUUXdBRGdBUUFCSThnWlF3dEQzQlZnQVlLRUVhQUJ3QUhnQWdBRUFpQUVBa0FFQm1BRUJvQUVCcUFFRHNBRUF1UUh6cldxa0FBQVVRTUVCODYxcXBBQUFGRURKQVFBQUFBQUFBUEFfMlFFCQxoQUR3UC1BQkFQVUJBQUNnUUpnQ0FLQUNBTFVDBSEETDAJCPBETUFDQU1nQ0FPQUNBT2dDQVBnQ0FJQURBWkFEQUpnREFhZ0RvWjZoQ3JvRENVNVpUVEk2TkRFeE5RLi6aAi0hbHdpX2xnNvAA8JxnSzAwSUFBb0FEb0pUbGxOTWpvME1URTHYAgDgAsHuK-oCQ2h0dHA6Ly9hbGx0aGF0c2ludGVyZXN0aW5nLmNvbS90ZXN0L3ByZWJpZC0xLjEtdGVzdC5odG1sP3ZpZGVvX3Rlc3SAAwCIAwGQAwCYAxegAwGqAwDAA6wCyAMA2AO1wJIB4AMA6AMA-AMCgAQAkgQNL3V0L3YzL3ByAVTwXJgEAKIEDTY5LjEyNC4yMjEuNDSoBM2xJrIEDggBEAQYoAYg2AQwADgCuAQAwATkuowVyAQA0gQNODgyI05ZTTI6NDExNdoEAggA4AQA8ASs67QaiAUBmAUAoAX__w0CFAHABQDJBUmfFPA_0gUJCQkMYAAA2AUB4AUB8AXeAvoFBAgAEACQBgGYBgA.&s=2ca57af7913aa5eb24bf9cca7b62d974a8ca7790&referrer=http%3A%2F%2Fallthatsinteresting.com%2Ftest%2Fprebid-1.1-test.html%3Fvideo_test",
        "timeout_ms": 0,
        "ad_profile_id": 718657,
        "ads": [{
            "content_source": "rtb",
            "ad_type": "video",
            "notify_url": "http://nym1-ib.adnxs.com/vast_track/v2?info=YwAAAAMArgAFAQkDmsJaAAAAABGufFmWM2UTOBkDmsJaAAAAACCs67QaKAAw8gY4_BtAxf8pSJeQY1DC0PcFWN4CYgJVU2gBcAF4AIABAogBAZABoAaYAdgEoAEAqAGs67Qa&event_type=1",
            "usersync_url": "http%3A%2F%2Facdn.adnxs.com%2Fib%2Fstatic%2Fusersync%2Fv4%2Fasync_usersync.html",
            "buyer_member_id": 882,
            "creative_id": 55391660,
            "media_type_id": 4,
            "media_subtype_id": 64,
            "cpm": 3.599452,
            "cpm_publisher_currency": 3.599452,
            "is_bin_price_applied": false,
            "publisher_currency_code": "$",
            "client_initiated_ad_counting": true,
            "rtb": {
                "video": {
                    "player_width": 800,
                    "player_height": 600,
                    "duration_ms": 30000,
                    "playback_methods": ["auto_play_sound_off"],
                    "frameworks": [],
                    "content": "<...lots of XML...>"
                }
            }
        }

### Expected results
Video bids would work.

### Actual results
The video bids we get from our appnexus placement are accepted as valid by Prebid.

**Comment by jaiminpanchal27** [comment]
@kitwestneat This looks like an issue with placement setup. 

For outstream bids, prebid requires a renderer on the bid or pub-defined renderer on adunit. So i am assuming its the latter since bid is valid.

Can you share the page so that we can look in detail

**Comment by kitwestneat** [comment]
Sure, it's at:
http://allthatsinteresting.com/test/prebid-1.1-test.html?video_test

The video bid is tag 6 on the first call to http://ib.adnxs.com/ut/v3/prebid

**Comment by jaiminpanchal27** [comment]
Checked the request payload to that call and its missing `ad_types:["video"]`. Appnexus adapter adds that to payload when it finds `adUnit.mediaTypes.video` object. See here https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L318

I see that you are generating adUnits programmatically so there might be some bug with `build_ad_unit` function

**Comment by kitwestneat** [comment]
Thanks for taking a look. It looks like that ad_types code was added in
Prebid 1.2, we're using prebid 1.1. Does that mean that outstream video is
not supported before 1.2?

Here is the bidrequest we are sending prebid:
{
    "code": "div-gpt-ad-1452277890523-0_video",
    "sizes": [
        [800, 600]
    ],
    "bids": [{
        "bidder": "appnexus",
        "params": {
            "placementId": "12445762",
            "video": {
                "playback_method": ["auto_play_sound_off"]
            }
        }
    }, {
        "bidder": "appnexusAst",
        "params": {
            "placementId": "12445762",
            "video": {
                "playback_method": ["auto_play_sound_off"]
            }
        }
    }],
    "mediaTypes": {
        "video": {
            "context": "outstream"
        }
    }
}

We are using http://prebid.org/dev-docs/show-outstream-video-ads.html as
our guide fwiw.

**Comment by jaiminpanchal27** [comment]
Tested this with 1.1.1 version and works fine. https://jsfiddle.net/ahnmL4rv/
Getting a proper bid response from appnexuAst (alias of appnexu adapter)

**Comment by kitwestneat** [comment]
Any advice on what we should try next?

**Comment by mkendall07** [comment]
This is a an issue with the placement/creative setup. Please open a AppNexus support ticket.
