### ISSUE TITLE
Best vesion of node to use to build the project

### ISSUE THREAD

**Issue by ojotoxy** [prebid/Prebid.js#245]
Some commit (not sure which) broke building this project with older versions of node (At least on 0.10.x). There were no helpful build error messages, it just created a broken prebid.js...

I updated to node 5.x and it built successfully. I think it had to due with things like 'let', 'const', and '=>'...

Bottom line, it would be great to document the best version of node to use when building this!

Thanks!

**Comment by mkendall07** [comment]
@ojotoxy 
Yes we will do that, sorry for the confusion. I believe > 4.x.x should work but 5.x might be required with latest changes. We check and will include it in the readme
