### ISSUE TITLE
Native ads not working without adUnit.sizes

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#2462]
## Type of issue
Bug

## Description
Test page: https://jsfiddle.net/6r217wza/
Native ads should not require size to be mentioned on adUnit. Above test page will work if you uncomment the adUnit.sizes

Debug mode shows `callBids executed with no bidRequests.  Were they filtered by labels or sizing?`
Reason for filtering is [here](https://github.com/prebid/Prebid.js/blob/master/src/adaptermanager.js#L50l)

**Comment by snapwich** [comment]
@jaiminpanchal27 the size mapping probably needs to be refactored.  When I originally wrote it there was no such thing as `mediaTypes`, so it operates on `adUnit.sizes` alone.  But now I guess it should expect and operate on one or the other?
