### ISSUE TITLE
Post-bid in versions 1.X

### ISSUE THREAD

**Issue by yehonatanshac** [prebid/Prebid.js#2467]
## Type of issue
bug

## Description
I tried to work with appnexus adapter of version 1.2 in post-bid configuration and I see that the referrer url in the HTTP header is the google frame. It doesn't recognize the website itself as an origin url. There was an additional parameter in the body of the HTTP request in 0.X versions.
I see that the version used in the post-bid example (http://prebid.org/dev-docs/examples/postbid.html) is actually 0.34.8. Does it mean post-bid is not supported in prebid 1?

**Comment by mkendall07** [comment]
Postbid still works fine with prebid 1.x. It's up to each individual adapter to support referral information via it's own mechanisms. AppNexus unfortunately does not support passing referral information anymore.
