### ISSUE TITLE
Feature request - limit the number of wins per bidder

### ISSUE THREAD

**Issue by orzilca** [prebid/Prebid.js#2486]
## Type of issue
Feature Request

## Description
It would be nice if it was possible to limit the number of possible wins per bidder.
Lets say I run 7 units on my page, and I wish to avoid giving more than 4 units per bidder because of contract or something:

```javascript
pbjs.setConfig({
   ...
   "maximumWinsPerBidder": 4,
   ...
});
```

Of course, the 4 highest wins of that bidder will be used, and on other units, the 2nd bidder in line will take the impression.

**Comment by mkendall07** [comment]
Hey @orzilca 
Why would a publisher want to use a setting like this?
