### ISSUE TITLE
Support for the legacy google analytics library (ga.js)

### ISSUE THREAD

**Issue by kazinov** [prebid/Prebid.js#251]
Hey,

As I understand currently `pbjs.enableAnalytics` function works only with new [analytics.js](https://developers.google.com/analytics/devguides/collection/analyticsjs/) version of the library. But my current project currently is on old [ga.js](https://developers.google.com/analytics/devguides/collection/gajs/). And for now it's quite painful to migrate. Are you interested in adding a support for the legacy version?
I will work on a PR then.

**Comment by mkendall07** [comment]
@kazinov 
We are not currently on planning to support legacy ga.js.
