### ISSUE TITLE
bRealTime adapter cannot be downloaded from http://prebid.org/download

### ISSUE THREAD

**Issue by SachinEbizon** [prebid/Prebid.js#2511]
bRealTime adapter cannot be downloaded for Prebid version 1.7.0 from http://prebid.org/download.html. It downloads appnexus instead of bRealTime.

**Comment by jaiminpanchal27** [comment]
@SachinEbizon `bRealTime` is an alias of AppneuxAdapter so this is the expected behaviour. See here for aliases https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L32
