### ISSUE TITLE
Openx - creative ID issue

### ISSUE THREAD

**Issue by smartbidder1** [prebid/Prebid.js#2515]
## Type of issue
bug

## Description
when requesting an ad from Openx bidder the response contains four parameters: adunitid, adid, brand_id and adv_id, none of them are unique per creative.
example:
`
         "adunitid":539181151,
         "adid":539921606,
         "brand_id":"13355",
         "adv_id":"152d07b1-da41-4c40-ad18-fe74c269534a:537073292",
`
there is a high importance of relaying on accurate creative id's for blacklists and debugging & reporting of bad ads.

https://github.com/prebid/Prebid.js/issues/2374 for example had the same issue but they have fixed it already (very fast I might say).

@jimee02 

one example with two different creatives with the same parameters:
`      {
         "adunitid":539874157,
         "adid":539936320,
         "idx":"2",
         "type":"html",
         "html":"<div id='beacon_WJ87Ww7l81ZgdZxuc1hE1qeH2B' style='position: absolute; left: 0px; top: 0px; visibility: hidden;'><img src='http://delivery-europe-west-1.openx.net/w/1.0/ri?ef=&ph=99b069cd-78e4-45e6-85da-d821a10d799d&ts=2DAABBgABAAECAAIBAAsAAgAAAWocGAp2MUNpaU11NkVVHBaIr8Lzmeqe91kWwYfHhP_v-d65AQAcFtykyt2r0tjVNhaPt5j5sLXwgPcBABbQqKOvCxUEOCQ0OTEzNzZmOS03ZTVhLTRhN2EtYTlkMy01MmQ2NWQxOTMxOWUALBwVAgAcFQIAHBUCAAAcJtrN7oIEFQQVBCbwzO6CBBb-2LCCBNbiPRbiPRbiPRYUFhQWFBYUFuRVABwcLBaAsYqku-yDrSoW67K12efigOelAQAAFpzamIAEFs6Y9oIEFoCZ9oIEFuSY9oIEFRgcFLAJFMACABUEJuRVFuRVFuRVETUOACwcFuKn6ubx4sCMSBb3wsKe47CdtPMBACbQqKOvCxUCBiic2piABBbOmPaCBBbkmPaCBBaAmfaCBBgKMTYwNDY4NzY0OBasQRbkVSUEFoIYGAM5OTkVApaIpJ4TESgCT1gIfgNydGIADDw4DXNvdXRod2VzdC5jb20AAAA'/></div><script src='http://presentation-ams1.turn.com/server/ads.js?code=6554469&aid=43285848&tuid=4336931516641768200&uimpd=1wVddKc3CgEPn9uSGH2uK9Y7jg4YHXan6w-RVRqNixmTrI6ZMvrCJSaqW1_i1g5Ad-fc2xSVKAfOAYrfi2q1bngVUaa81rE5Va5TPoJV_1Ntn4-ZNPeiesLCUWGi5Q0pMIlxWeHujtiWU4hIRmxZhGDbLcisF5vf52pYjnxx7sgLDq60qaLSM9lSDH_P7r3m2LfHLNhuhT3pi82fEsIKY-zMcLaIqUa9FRu7ru1ABYiO8vlfPXWpaqs2mGKBeioBLVoFw0MMd10MSbTdO6NlgKEXei357Vh72EJueJkSm54_6mg1515k-ENWS4ZVVCXg-0uDuku1n-3Fae08OWag9tUf-tJOQdfOKN203qZph-UKJavIWx6QQAMbKHA7bv633uPPFn1JcGM0Kkmmoe73nGk0F6b051lHno8swdAVmRjQzxV4vUc1fbOBN5XYGdY41F5skBN4BIzKo2be5RbqTVVZVNdugxsQ3HWP-GpdjXvCgd2BUb6kblw7j7JPfDEbyVdjFIcHRX70IuE0OJWBiu-EhBZNQbaDRmwVP5XZHE7Mwp53dg9o0HBLrTj27kashotQYsHzJlsRlBtfDGy5lSd8qCm-Rno1fhIx7bVDI0_u8DKSD5KGt6pM_K7F3O8cdLZofmdfOvkgJvcWQYHF9RidEeRRZ2FCEhvcgjZw8fb0kWxsvzRF14fCH32FjvH4Bmv5wYQyHYVwSUg1ZcLFeh7jkQM2i161bNAI6tqdhWSRhUsTB-BpJBA-gHtPLk6B-hoelPtQ61MqirSBX0CZGgLnIrH1AhA8mFIl4c6hZS4mbCuc5ZPXqvQIY0by7uZVuyO_ZB6T-4JKV3oV6uKqyRNpg0oPZNuQt65BWlSfxxTC3ucqEogl0gJloaSqGHamv&acp=AAABY0q-sI6STI2vtGaqTruCWrRgATdycSJOjw'></script>",
         "framed":1,
         "is_fallback":0,
         "ts":"2DAABBgABAAECAAIBAAsAAgAAAWocGAp2MUNpaU11NkVVHBaIr8Lzmeqe91kWwYfHhP_v-d65AQAcFtykyt2r0tjVNhaPt5j5sLXwgPcBABbQqKOvCxUEOCQ0OTEzNzZmOS03ZTVhLTRhN2EtYTlkMy01MmQ2NWQxOTMxOWUALBwVAgAcFQIAHBUCAAAcJtrN7oIEFQQVBCbwzO6CBBb-2LCCBNbiPRbiPRbiPRYUFhQWFBYUFuRVABwcLBaAsYqku-yDrSoW67K12efigOelAQAAFpzamIAEFs6Y9oIEFoCZ9oIEFuSY9oIEFRgcFLAJFMACABUEJuRVFuRVFuRVETUOACwcFuKn6ubx4sCMSBb3wsKe47CdtPMBACbQqKOvCxUCBiic2piABBbOmPaCBBbkmPaCBBaAmfaCBBgKMTYwNDY4NzY0OBasQRbkVSUEFoIYGAM5OTkVApaIpJ4TESgCT1gIfgNydGIADDw4DXNvdXRod2VzdC5jb20AAAA",
         "cpipc":3953,
         "auct_win_is_deal":0,
         "pub_rev":"3953",
         "brand_id":"4182",
         "adv_id":"152d07b1-da41-4c40-ad18-fe74c269534a:537073294",
         "creative":[
           {
             "width":"160",
             "height":"600",
             "target":"_blank",
             "mime":"text/html",
             "media": "<script src='http://presentation-ams1.turn.com/server/ads.js?code=6554469&aid=43285848&tuid=4336931516641768200&uimpd=1wVddKc3CgEPn9uSGH2uK9Y7jg4YHXan6w-RVRqNixmTrI6ZMvrCJSaqW1_i1g5Ad-fc2xSVKAfOAYrfi2q1bngVUaa81rE5Va5TPoJV_1Ntn4-ZNPeiesLCUWGi5Q0pMIlxWeHujtiWU4hIRmxZhGDbLcisF5vf52pYjnxx7sgLDq60qaLSM9lSDH_P7r3m2LfHLNhuhT3pi82fEsIKY-zMcLaIqUa9FRu7ru1ABYiO8vlfPXWpaqs2mGKBeioBLVoFw0MMd10MSbTdO6NlgKEXei357Vh72EJueJkSm54_6mg1515k-ENWS4ZVVCXg-0uDuku1n-3Fae08OWag9tUf-tJOQdfOKN203qZph-UKJavIWx6QQAMbKHA7bv633uPPFn1JcGM0Kkmmoe73nGk0F6b051lHno8swdAVmRjQzxV4vUc1fbOBN5XYGdY41F5skBN4BIzKo2be5RbqTVVZVNdugxsQ3HWP-GpdjXvCgd2BUb6kblw7j7JPfDEbyVdjFIcHRX70IuE0OJWBiu-EhBZNQbaDRmwVP5XZHE7Mwp53dg9o0HBLrTj27kashotQYsHzJlsRlBtfDGy5lSd8qCm-Rno1fhIx7bVDI0_u8DKSD5KGt6pM_K7F3O8cdLZofmdfOvkgJvcWQYHF9RidEeRRZ2FCEhvcgjZw8fb0kWxsvzRF14fCH32FjvH4Bmv5wYQyHYVwSUg1ZcLFeh7jkQM2i161bNAI6tqdhWSRhUsTB-BpJBA-gHtPLk6B-hoelPtQ61MqirSBX0CZGgLnIrH1AhA8mFIl4c6hZS4mbCuc5ZPXqvQIY0by7uZVuyO_ZB6T-4JKV3oV6uKqyRNpg0oPZNuQt65BWlSfxxTC3ucqEogl0gJloaSqGHamv&acp=AAABY0q-sI6STI2vtGaqTruCWrRgATdycSJOjw'></script>",
             "tracking":{
               "impression":"http://delivery-europe-west-1.openx.net/w/1.0/ri?ef=&ph=99b069cd-78e4-45e6-85da-d821a10d799d&ts=2DAABBgABAAECAAIBAAsAAgAAAWocGAp2MUNpaU11NkVVHBaIr8Lzmeqe91kWwYfHhP_v-d65AQAcFtykyt2r0tjVNhaPt5j5sLXwgPcBABbQqKOvCxUEOCQ0OTEzNzZmOS03ZTVhLTRhN2EtYTlkMy01MmQ2NWQxOTMxOWUALBwVAgAcFQIAHBUCAAAcJtrN7oIEFQQVBCbwzO6CBBb-2LCCBNbiPRbiPRbiPRYUFhQWFBYUFuRVABwcLBaAsYqku-yDrSoW67K12efigOelAQAAFpzamIAEFs6Y9oIEFoCZ9oIEFuSY9oIEFRgcFLAJFMACABUEJuRVFuRVFuRVETUOACwcFuKn6ubx4sCMSBb3wsKe47CdtPMBACbQqKOvCxUCBiic2piABBbOmPaCBBbkmPaCBBaAmfaCBBgKMTYwNDY4NzY0OBasQRbkVSUEFoIYGAM5OTkVApaIpJ4TESgCT1gIfgNydGIADDw4DXNvdXRod2VzdC5jb20AAAA",
               "inview":"http://funtomic-d.openx.net/w/1.0/rvi?ef=&ts=2DAABBgABAAECAAIBAAsAAgAAAWocGAp2MUNpaU11NkVVHBaIr8Lzmeqe91kWwYfHhP_v-d65AQAcFtykyt2r0tjVNhaPt5j5sLXwgPcBABbQqKOvCxUEOCQ0OTEzNzZmOS03ZTVhLTRhN2EtYTlkMy01MmQ2NWQxOTMxOWUALBwVAgAcFQIAHBUCAAAcJtrN7oIEFQQVBCbwzO6CBBb-2LCCBNbiPRbiPRbiPRYUFhQWFBYUFuRVABwcLBaAsYqku-yDrSoW67K12efigOelAQAAFpzamIAEFs6Y9oIEFoCZ9oIEFuSY9oIEFRgcFLAJFMACABUEJuRVFuRVFuRVETUOACwcFuKn6ubx4sCMSBb3wsKe47CdtPMBACbQqKOvCxUCBiic2piABBbOmPaCBBbkmPaCBBaAmfaCBBgKMTYwNDY4NzY0OBasQRbkVSUEFoIYGAM5OTkVApaIpJ4TESgCT1gIfgNydGIADDw4DXNvdXRod2VzdC5jb20AAAA",
               "click":"http://funtomic-d.openx.net/w/1.0/rc?ef=&ts=2DAABBgABAAECAAIBAAsAAgAAAWocGAp2MUNpaU11NkVVHBaIr8Lzmeqe91kWwYfHhP_v-d65AQAcFtykyt2r0tjVNhaPt5j5sLXwgPcBABbQqKOvCxUEOCQ0OTEzNzZmOS03ZTVhLTRhN2EtYTlkMy01MmQ2NWQxOTMxOWUALBwVAgAcFQIAHBUCAAAcJtrN7oIEFQQVBCbwzO6CBBb-2LCCBNbiPRbiPRbiPRYUFhQWFBYUFuRVABwcLBaAsYqku-yDrSoW67K12efigOelAQAAFpzamIAEFs6Y9oIEFoCZ9oIEFuSY9oIEFRgcFLAJFMACABUEJuRVFuRVFuRVETUOACwcFuKn6ubx4sCMSBb3wsKe47CdtPMBACbQqKOvCxUCBiic2piABBbOmPaCBBbkmPaCBBaAmfaCBBgKMTYwNDY4NzY0OBasQRbkVSUEFoIYGAM5OTkVApaIpJ4TESgCT1gIfgNydGIADDw4DXNvdXRod2VzdC5jb20AAAA"
             }
           }
         ]
        },
      `

`  {
         "adunitid":539874156,
         "adid":539936320,
         "idx":"3",
         "type":"html",
         "html":"<div id='beacon_YsKz6CIJg_XsvPXENu2-tNXDWZ' style='position: absolute; left: 0px; top: 0px; visibility: hidden;'><img src='http://delivery-europe-west-1.openx.net/w/1.0/ri?ef=&ph=99b069cd-78e4-45e6-85da-d821a10d799d&ts=2DAABBgABAAECAAIBAAsAAgAAAWwcGApIVUtsWlFncHRRHBaIr8Lzmeqe91kWwYfHhP_v-d65AQAcFua8moWuy5uqrQEWjcHax-j-uoLiAQAW0KijrwsVBDgkNDkxMzc2ZjktN2U1YS00YTdhLWE5ZDMtNTJkNjVkMTkzMTllACwcFQIAHBUCABwVAgAAHCbYze6CBBUEFQQm8MzuggQW_tiwggTW4j0W4j0W4j0WFBYUFhQWFBbkVQAcHCwWgLGKpLvsg60qFuuytdnn4oDnpQEAABac2piABBbOmPaCBBaAmfaCBBbkmPaCBBUYHBSwCRTAAgAVBCbkVRbkVRbkVRE1DgAsHBb6mdrw5_u28pUBFsO8nqXb9MecpgEAJtCoo68LFQIGKJzamIAEFs6Y9oIEFuSY9oIEFoCZ9oIEGAoxNjA0Njg3NjQ4FqxBFuRVJQQWghgYAzk5ORUCloiknhMRKAJPWAh-A3J0YgAMPDgNc291dGh3ZXN0LmNvbQAAAA'/></div><script src='http://presentation-ams1.turn.com/server/ads.js?code=6554469&aid=43285848&tuid=4336931516641768200&uimpd=16wjvsOffjbw9drgSwaXBQrpfaLAmkP0ZDerA7FokX0XrI6ZMvrCJSaqW1_i1g5AdGLc5AcKH9m0GTGgnfQ2N1gVUaa81rE5Va5TPoJV_1Ntn4-ZNPeiesLCUWGi5Q0pMIlxWeHujtiWU4hIRmxZhGDbLcisF5vf52pYjnxx7sgLDq60qaLSM9lSDH_P7r3m2LfHLNhuhT3pi82fEsIKY-zMcLaIqUa9FRu7ru1ABYiNAGQfVJAAC-3J_qKKXnxpEBd-TR-mUW_CjlZP02QuSzUXei357Vh72EJueJkSm54_6mg1515k-ENWS4ZVVCXg-0uDuku1n-3Fae08OWag9tUf-tJOQdfOKN203qZph-UKJavIWx6QQAMbKHA7bv633uPPFn1JcGM0Kkmmoe73nGk0F6b051lHno8swdAVmRjSZdR1Qf95EztwffWjuffIzYpMIED58vasBsrW8aF2jqvEQRR82chjm5NQ0E-Z_UYcu4VaV3_Mcn7_ApEuRz7fNGHXEuxRXzBARyF-1oNEsd-ZLdERRzx3MqsgN_ys-IWNCyCBAviByBGd6DwKxqxR9XhNta_hLsWJVWWKR9hFkXqb2dmIo3xFY8M8ciViJm1hbT-KvTy6lqXzDyPZYg88fSSujjaIGulovL3MjFpOqKH0FhKn7Ib6Z6fyKQHnqIHk8WFRKgaduWa4k-RoIPHO_gkbEEpimWgqzIhlZxnqrVXhrXsU_1EWcadrsvb4ZojhuYb__eZVK0Clvz5Rueq7h0SReXDC4l7UZflvpeeSi1kgDFezEYhU2vAWraJvwx1RNGuSu5mUNCxX8Q8pyJOmJkn1N15dHAd1dZhMkCK44hFf6A77egKq7TRwiL-FgyTeoIW5Wcs1l1xDv-b5K34Ya&acp=AAABY0q-sJTxydsEeol4vhwE9yFja9BU9GJnNg'></script>",
         "framed":1,
         "is_fallback":0,
         "ts":"2DAABBgABAAECAAIBAAsAAgAAAWwcGApIVUtsWlFncHRRHBaIr8Lzmeqe91kWwYfHhP_v-d65AQAcFua8moWuy5uqrQEWjcHax-j-uoLiAQAW0KijrwsVBDgkNDkxMzc2ZjktN2U1YS00YTdhLWE5ZDMtNTJkNjVkMTkzMTllACwcFQIAHBUCABwVAgAAHCbYze6CBBUEFQQm8MzuggQW_tiwggTW4j0W4j0W4j0WFBYUFhQWFBbkVQAcHCwWgLGKpLvsg60qFuuytdnn4oDnpQEAABac2piABBbOmPaCBBaAmfaCBBbkmPaCBBUYHBSwCRTAAgAVBCbkVRbkVRbkVRE1DgAsHBb6mdrw5_u28pUBFsO8nqXb9MecpgEAJtCoo68LFQIGKJzamIAEFs6Y9oIEFuSY9oIEFoCZ9oIEGAoxNjA0Njg3NjQ4FqxBFuRVJQQWghgYAzk5ORUCloiknhMRKAJPWAh-A3J0YgAMPDgNc291dGh3ZXN0LmNvbQAAAA",
         "cpipc":3953,
         "auct_win_is_deal":0,
         "pub_rev":"3953",
         "brand_id":"4182",
         "adv_id":"152d07b1-da41-4c40-ad18-fe74c269534a:537073294",
         "creative":[
           {
             "width":"160",
             "height":"600",
             "target":"_blank",
             "mime":"text/html",
             "media": "<script src='http://presentation-ams1.turn.com/server/ads.js?code=6554469&aid=43285848&tuid=4336931516641768200&uimpd=16wjvsOffjbw9drgSwaXBQrpfaLAmkP0ZDerA7FokX0XrI6ZMvrCJSaqW1_i1g5AdGLc5AcKH9m0GTGgnfQ2N1gVUaa81rE5Va5TPoJV_1Ntn4-ZNPeiesLCUWGi5Q0pMIlxWeHujtiWU4hIRmxZhGDbLcisF5vf52pYjnxx7sgLDq60qaLSM9lSDH_P7r3m2LfHLNhuhT3pi82fEsIKY-zMcLaIqUa9FRu7ru1ABYiNAGQfVJAAC-3J_qKKXnxpEBd-TR-mUW_CjlZP02QuSzUXei357Vh72EJueJkSm54_6mg1515k-ENWS4ZVVCXg-0uDuku1n-3Fae08OWag9tUf-tJOQdfOKN203qZph-UKJavIWx6QQAMbKHA7bv633uPPFn1JcGM0Kkmmoe73nGk0F6b051lHno8swdAVmRjSZdR1Qf95EztwffWjuffIzYpMIED58vasBsrW8aF2jqvEQRR82chjm5NQ0E-Z_UYcu4VaV3_Mcn7_ApEuRz7fNGHXEuxRXzBARyF-1oNEsd-ZLdERRzx3MqsgN_ys-IWNCyCBAviByBGd6DwKxqxR9XhNta_hLsWJVWWKR9hFkXqb2dmIo3xFY8M8ciViJm1hbT-KvTy6lqXzDyPZYg88fSSujjaIGulovL3MjFpOqKH0FhKn7Ib6Z6fyKQHnqIHk8WFRKgaduWa4k-RoIPHO_gkbEEpimWgqzIhlZxnqrVXhrXsU_1EWcadrsvb4ZojhuYb__eZVK0Clvz5Rueq7h0SReXDC4l7UZflvpeeSi1kgDFezEYhU2vAWraJvwx1RNGuSu5mUNCxX8Q8pyJOmJkn1N15dHAd1dZhMkCK44hFf6A77egKq7TRwiL-FgyTeoIW5Wcs1l1xDv-b5K34Ya&acp=AAABY0q-sJTxydsEeol4vhwE9yFja9BU9GJnNg'></script>",
             "tracking":{
               "impression":"http://delivery-europe-west-1.openx.net/w/1.0/ri?ef=&ph=99b069cd-78e4-45e6-85da-d821a10d799d&ts=2DAABBgABAAECAAIBAAsAAgAAAWwcGApIVUtsWlFncHRRHBaIr8Lzmeqe91kWwYfHhP_v-d65AQAcFua8moWuy5uqrQEWjcHax-j-uoLiAQAW0KijrwsVBDgkNDkxMzc2ZjktN2U1YS00YTdhLWE5ZDMtNTJkNjVkMTkzMTllACwcFQIAHBUCABwVAgAAHCbYze6CBBUEFQQm8MzuggQW_tiwggTW4j0W4j0W4j0WFBYUFhQWFBbkVQAcHCwWgLGKpLvsg60qFuuytdnn4oDnpQEAABac2piABBbOmPaCBBaAmfaCBBbkmPaCBBUYHBSwCRTAAgAVBCbkVRbkVRbkVRE1DgAsHBb6mdrw5_u28pUBFsO8nqXb9MecpgEAJtCoo68LFQIGKJzamIAEFs6Y9oIEFuSY9oIEFoCZ9oIEGAoxNjA0Njg3NjQ4FqxBFuRVJQQWghgYAzk5ORUCloiknhMRKAJPWAh-A3J0YgAMPDgNc291dGh3ZXN0LmNvbQAAAA",
               "inview":"http://funtomic-d.openx.net/w/1.0/rvi?ef=&ts=2DAABBgABAAECAAIBAAsAAgAAAWwcGApIVUtsWlFncHRRHBaIr8Lzmeqe91kWwYfHhP_v-d65AQAcFua8moWuy5uqrQEWjcHax-j-uoLiAQAW0KijrwsVBDgkNDkxMzc2ZjktN2U1YS00YTdhLWE5ZDMtNTJkNjVkMTkzMTllACwcFQIAHBUCABwVAgAAHCbYze6CBBUEFQQm8MzuggQW_tiwggTW4j0W4j0W4j0WFBYUFhQWFBbkVQAcHCwWgLGKpLvsg60qFuuytdnn4oDnpQEAABac2piABBbOmPaCBBaAmfaCBBbkmPaCBBUYHBSwCRTAAgAVBCbkVRbkVRbkVRE1DgAsHBb6mdrw5_u28pUBFsO8nqXb9MecpgEAJtCoo68LFQIGKJzamIAEFs6Y9oIEFuSY9oIEFoCZ9oIEGAoxNjA0Njg3NjQ4FqxBFuRVJQQWghgYAzk5ORUCloiknhMRKAJPWAh-A3J0YgAMPDgNc291dGh3ZXN0LmNvbQAAAA",
               "click":"http://funtomic-d.openx.net/w/1.0/rc?ef=&ts=2DAABBgABAAECAAIBAAsAAgAAAWwcGApIVUtsWlFncHRRHBaIr8Lzmeqe91kWwYfHhP_v-d65AQAcFua8moWuy5uqrQEWjcHax-j-uoLiAQAW0KijrwsVBDgkNDkxMzc2ZjktN2U1YS00YTdhLWE5ZDMtNTJkNjVkMTkzMTllACwcFQIAHBUCABwVAgAAHCbYze6CBBUEFQQm8MzuggQW_tiwggTW4j0W4j0W4j0WFBYUFhQWFBbkVQAcHCwWgLGKpLvsg60qFuuytdnn4oDnpQEAABac2piABBbOmPaCBBaAmfaCBBbkmPaCBBUYHBSwCRTAAgAVBCbkVRbkVRbkVRE1DgAsHBb6mdrw5_u28pUBFsO8nqXb9MecpgEAJtCoo68LFQIGKJzamIAEFs6Y9oIEFuSY9oIEFoCZ9oIEGAoxNjA0Njg3NjQ4FqxBFuRVJQQWghgYAzk5ORUCloiknhMRKAJPWAh-A3J0YgAMPDgNc291dGh3ZXN0LmNvbQAAAA"
             }
           }
         ]
        }`

**Comment by harpere** [comment]
So this is only for the OpenX adapter?  I think @jimee02 is a contributor to the OpenX adapter

**Comment by smartbidder1** [comment]
@harpere We've investigated almost every adapter with thousands of ads, currently the ones with issue are Appnexus, Sonobi and Openx.
Sovrn has already fixed their problem and Appnexus & Sonobi are working on it also.

so yea, @jimee02 is the relevant person here.

**Comment by jimee02** [comment]
Hi @smartbidder1, I'm currently checking with the team about the feasibility of this.  I'll update you as soon as I can.

**Comment by smartbidder1** [comment]
great @jimee02 , thank you for that, awaiting for this update.

**Comment by smartbidder1** [comment]
@jimee02 is there any update? since the issue has been gone into stale now.

**Comment by smartbidder1** [comment]
@jsnellbaker  can you please add a "bug" label?

**Comment by smartbidder1** [comment]
any update? @jimee02

**Comment by bwoolcott** [comment]
@smartbidder1 our Prebid code should handle this, but, we may need to switch this on for your specific OpenX instance - I can check on that for you if you'd like to ping me with your OpenX instance name
