### ISSUE TITLE
GDPR-compliance for Prebid Server cookiesyncs

### ISSUE THREAD

**Issue by dbemiller** [prebid/Prebid.js#2516]
Prebid.js cookie syncs with Prebid Server violate GDPR. See https://github.com/prebid/prebid-server/issues/501 for more details.

If the GDPR module is included, please include the following properties in the `POST /cookie_sync` request body to Prebid Server:

```
{
  "gdpr": 1,
  "gdpr_consent": "vendor-consent-string"
}
```

If GDPR is in effect:
- `gdpr` should be 1
- `gdpr_consent` must be the [Unpadded base64-URL](https://tools.ietf.org/html/rfc4648#section-5) 
 encoded [vendor consent string](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md#vendor-consent-string-format-). This should be the same as you use in `request.user.ext.consent` for `/openrtb2/auction` payloads.

If GDPR is not in effect:
- `gdpr` should be 0
- `gdpr_consent` should be undefined

If the GDPR status is uncertain:
- `gdpr` should be undefined
- `gdpr_consent` is optional, but you should send it if you have it.

If the GDPR module is _not_ included, then the status is uncertain. `gdpr` should be undefined, and `gdpr_consent` is optional.

Let me know if you have any questions or concerns.

Thanks!

**Comment by bretg** [comment]
While we're address this, can we cover https://github.com/prebid/Prebid.js/issues/2242 ?  I think this is the same piece of code. We haven't been able to get to it.

**Comment by jsnellbaker** [comment]
@dbemiller if the module is disabled, does that fall into the 'GDPR is not in effect' bucket or should we just not add the `gdpr` and `gdpr_consent` fields at all to the POST request?

**Comment by jsnellbaker** [comment]
@bretg I will aim to include that issue you noted as part of my changes here.

**Comment by dbemiller** [comment]
@jsnellbaker in that case, don't add the `gdpr` or `gdpr_consent` fields at all to the POST request.

**Comment by dbemiller** [comment]
@jsnellbaker safe to close this?

**Comment by jsnellbaker** [comment]
Yes - this change was merged in as part of the 1.11.0 release.
