### ISSUE TITLE
Incorrect Key Values breaking Prebid Implementation

### ISSUE THREAD

**Issue by JBSteve** [prebid/Prebid.js#2517]
## Type of issue
Bidder key values being set incorrectly and therefore negating Header Bidding.

## Description
Using version 1.7, we are seeing bids come back in the debug console in the following format:

MESSAGE: Attempting to set key value for slot: div-gpt-ad-1496430710640-0 key: `hb_pb_appnexus` value: 1.40

According to our AdOps, the highlighted portion above is incorrect, should not include the bidder name and should simply be `hb_pb`

## Steps to reproduce

1)  View browser console output at:   [https://jambase7.staging.wpengine.com/?pbjs_debug=true](https://jambase7.staging.wpengine.com/?pbjs_debug=true)

2)  Filter for `hb_pb_` in the console output

## Test page

See URL in step 1 to reproduce above

### Expected results

Again, according to our AdOps, bids should be returned in this format (note: `highlighted`):

MESSAGE: Attempting to set key value for slot: div-gpt-ad-86753098675309-2 key: `hb_bidder value: appnexus`
MESSAGE: Attempting to set key value for slot: div-gpt-ad-86753098675309-2 key: `hb_adid value: 32025d44c57c0be`
MESSAGE: Attempting to set key value for slot: div-gpt-ad-86753098675309-2 key: `hb_pb value: 1.60`

### Actual results

MESSAGE: Attempting to set key value for slot: div-gpt-ad-1447374351391-3 key: `hb_pb_appnexus value: 0.70`
MESSAGE: Attempting to set key value for slot: div-gpt-ad-1447374351391-3 key: `hb_adid_appnexus value: 205e227e25047d43`
MESSAGE: Attempting to set key value for slot: div-gpt-ad-1447374351391-3 key: `hb_bidder_appnexus value: appnexus`

## Platform details

Prebid 1.7 - Chrome v66.0.3359.139 - Windows 10 

## Other information

N/A

**Comment by jaiminpanchal27** [comment]
@JBSteve I am not able to reproduce above given results.

This page https://jambase7.staging.wpengine.com/?pbjs_debug=true is using Prebid 1.10
In Prebid 1.x `enableSendAllBids` is true by default. 
So targeting would have 
- winning bid key value pairs without appending bidderCode
- key value pairs for all other bids including winning bid.
