### ISSUE TITLE
Documentation of GDPR-compliant adapters and behavior?

### ISSUE THREAD

**Issue by kmjennison** [prebid/Prebid.js#2519]
Is there documentation on how each adapter will handle GDPR? (Related: the GDPR consentManagement module, #2213.)

In particular, it would be nice to know:

1. Which adapters are supporting the consentManagement module?
    * If they're not already, will they be updated by May 25?
    * I believe this info is only currently available by looking at release notes or module source code
2. What are the bidders' behaviors if `gdprConsent.gdprApplies` is not defined (and `allowAuctionWithoutConsent` is true) or the consentManagement module isn't being used? Possible bidder behaviors are:
    * never return bids (globally)
    * return non-personalized ad bids (globally)
    * return personalized ad bids (globally) -- this is probably most concerning to publishers seeking compliance
    * bidder detects EU traffic, and if EU, never return bids
    * bidder detects EU traffic, and if EU, return non-personalized ad bids

I'd understand if you consider this out of scope of core Prebid (particularly no. 2). However, I'd guess many publishers are uncertain how partners are handling consent, and Prebid seems like a good place to centralize the knowledge.

**Comment by hdjvieira** [comment]
On the [Prebid.js consentManagement docs page](http://prebid.org/dev-docs/modules/consentManagement.html), there is a list of GDPR compliant adapters at the end.
