### ISSUE TITLE
BID_TIMEOUT event defunct

### ISSUE THREAD

**Issue by dejanstrbac** [prebid/Prebid.js#2524]
## Type of issue
Bug

## Description
BID_TIMEOUT will never fire

## Steps to reproduce
For example:

`pbjs.onEvent('bidTimeout', function....);
`

The callback function will never get called even after blocking the endpoints of the adapters, e.g. via /etc/hosts or network requests blocking in the browser. Even internally the requests will not be marked as timedout as doneCbCallCount will always increase to 1, showing them as complete.

The reason for this is the following code in `src/adapters/bidderFactory.js`:

```

     function afterAllResponses(bids) {
        done();
        registerSyncs(responses, bidderRequest.gdprConsent);
      }

      const validBidRequests = bidderRequest.bids.filter(filterAndWarn);
      if (validBidRequests.length === 0) {
        afterAllResponses();
        return;
      }

```

Note that done() will be called regardless of the responses, which in this case will never arrive, yet doneCbCallCount on the request objects will always be set to 1. This is a logic error and makes analytics data of timed out bidders impossible.

## Platform details
Prebid.js 1.10.0

**Comment by jaiminpanchal27** [comment]
@dejanstrbac Why should prebid emit `bidTimeout` event in case of failed requests before timeout ?
By blocking in /etc/hosts xhr will error immediately. You have to delay it somehow to emit bidTimeout

**Comment by mkendall07** [comment]
maybe we need a new event for bidder error?

**Comment by hheexx** [comment]
Is this the reason documentation does not use this feature but setTimeout ?
http://prebid.org/dev-docs/getting-started.html

**Comment by hheexx** [comment]
How do you track them?

**Comment by mkendall07** [comment]
is this still an issue or should it be closed?

**Comment by ChrisHuie** [comment]
No comments or progress made toward a pr around this issue.
