### ISSUE TITLE
Best way to add GDPR consent support

### ISSUE THREAD

**Issue by unrulydevelopers** [prebid/Prebid.js#2529]
## Type of issue
Question

## Description
We are looking to add GDPR  consent support to our adaptor. We noticed that most seemed to pull out the consent data in the adaper itself - is there any reason that we cannot pass the whole bidderRequest onto our exchange code?

i.e. the second parameter in the following: `buildRequests: function(validBidRequests, bidderRequest)`

**Comment by mkendall07** [comment]
you may pass the whole request if you would like to your endpoint.
