### ISSUE TITLE
Is there ETA to update your chrome extension to include missing bidders or Open Source it?

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#253]
There are some bidders missing in the extension for new adaptors merged like pulsepoint, rubicon(fastlane), adspring etc. new bidders patterns needs to be added to the extension.

**Comment by mkendall07** [comment]
@ialex 
We are working on it now. Should be soon.

**Comment by ialex** [comment]
It has been updated with some new adapters and know you guys will update it eventually to support all so i will close this issue thanks for the update and future updates <3

**Comment by CLKeenan** [comment]
Is there a published list of the HB partners that are included in the current version? Will help with debugging to know what partners to expect not to be shown.
