### ISSUE TITLE
Publisher-side renderer

### ISSUE THREAD

**Issue by benjaminclot** [prebid/Prebid.js#2535]
## Type of issue
Question

## Description
How does one specify a publisher-side renderer? The renderer feature is a great idea but is "officially" limited to outstream. My company uses Prebid to also render other "special" formats like skins, interstitials, etc. from standard bids (i.e. from any provider), so we've been doing things a bit differently but it has a hacky feeling to it and there must be (is?) a better solution.

As of now, we use the bidWon event to tweak the winning bid (the request was passed multiple sizes, among them 1800x1000) and inject a renderer like so:
```javascript
pbjs.onEvent('bidWon', function(bid) {
  // this is a skin
  if (bid.width === 1800 && bid.height === 1000) {
    bid.renderer = {
     // this JS URL seems to be a mandatory parameter but we don't actually use it,
     // the renderSkin function is already defined beforehand...
     // documentation needs to be made clearer on how to "install" a renderer
      url: 'https://foo.bar/skin.js',
      render: function(bid) {
        renderSkin(bid);
      }
    };
  }
});
```

Thus, the bid gets modified but:
- if bidWon was triggered at another time this could fail
- we edit a private(?) bid object

**Comment by benjaminclot** [comment]
Could I get some inputs from maintainers? @mkendall07 @matthewlane @jaiminpanchal27 @snapwich 
The fact that it has not even triggered a discussion worries me a bit.

**Comment by mkendall07** [comment]
@benjaminclot 
We haven't implemented a generic render function. I'd be happy to review  proposal / PR for it though. The team is quite busy with GDPR at the moment. Thanks

**Comment by dugwood** [comment]
@benjaminclot I'm having the same hard time, most of the time for interstitial it's okay, but for skins it's a nightmare :-(

For example, served by AppNexus today: https://speedata.fr/suzuki/creations/5b18f9f36e3db/5b18fb6a6f683/index.html

 - not centered
 - served with non-friendly iframe in the Prebid's iframe (iframe#prebid > html > body > div > iframe:src=...)
 - impossible to display correctly
 - can't be resized for responsive websites

In the end, the ad is loaded, but never seen!

@mkendall07 can it be opened again? Can we force a standard object for all bidders? As @benjaminclot said, every publisher will have his own function. It works most of the time, but when some ads are crappy:
 - ad isn't displayed (will stay in the hidden iframe)
 - ad tests will run, ending in statistics sent even if ad's not displayed
 - bidder may consider that we're cheating
 - can't passback on the second bid (really too late, and bid may already be lost)

**Comment by dugwood** [comment]
FYI I've changed my way of dealing with skins: I always load these in a specific iframe that is used as background of the whole website. This way it's displayed 100% of the time, possibly with issues (responsive is not my friend here), but at least it's displayed.
