### ISSUE TITLE
[Bug] getHighestCpmBids not updating on refresh and AppNexus not recording impression

### ISSUE THREAD

**Issue by Slind14** [prebid/Prebid.js#2539]
## Type of issue
Bug

## Description
When refreshing ads with prebid, AppNexus does not track these impressions probably due to the adid not updating. When getting `getHighestCpmBids()` it contains the old bids from the first impression.

## Steps to reproduce
1. load and check  `console.table(pbjs.getHighestCpmBids())`, specifically `adid`
2. refresh the add (button) and check `console.table(pbjs.getHighestCpmBids())` => records are unchanged and do not match bid network request response

## Test page
https://jsfiddle.net/prebid_org/61uzp29t

### Expected results
`getHighestCpmBids` containing the new ads

### Actual results
`getHighestCpmBids` not updating (containing the old ads

## Other information
https://appnexustraders.slack.com/archives/C77SFBW5P/p1526394189000702

**Comment by jsnellbaker** [comment]
Hi @Slind14 Thanks for reporting this issue/bug.  I'll start to investigate and see if we can get it addressed.

**Comment by jsnellbaker** [comment]
@Slind14 When I was testing this out and monitoring the refreshed calls, it seems like the bids we received did have different `adid` values.  

If you enable debug mode (either in `setConfig` or appending `?pbjs_debug=true` in the page url), and look for the line in the console titled `Bids Received for Auction with id: ....` there is a copy of the `bidsReceived` object for that auction.  When I inspected these objects, that's where I saw different values for the `adid` field.  

Additionally, when I was monitoring the Network tab and looking for the impression trackers (filter by `/it`), there were distinct URLs executed for each refresh with a slightly different hash used each time.  

I do see that the getHighestCpmBids function is returning the 'oldest' bid and I'm investigating that function further, but it doesn't seem like there's a tracking issue.  Please let me know your thoughts when you get the chance.

**Comment by mercuryyy** [comment]
@jsnellbaker i was also able to get a deferent adid, but my dfp reporting for appnexus is about 20-30% higher impression count then appnexus dashboard since i started refreshing. i refresh appnexus every 60 seconds. 

The overall revenue in dfp and appnexus reporting differs by 5% where total impressions is 20-30%

I though it might have something to do with https://github.com/prebid/Prebid.js/issues/2448
since sometimes it does not pick the new winning bids and uses the old bid.

**Comment by Slind14** [comment]
Yes, they have a new adid, are looking different and are sending a different impression tracking request. Yet they are not being counted from all I can tell. The major discrepancies in reporting started for me the day I implemented ad refresh and primarily reflect AppNexus.

**Comment by marcoms77** [comment]
hello,
did you found a solution for getHighestCpmBids not updating on refresh problem? 
thank you

**Comment by Slind14** [comment]
I worked around it by using all the data, filtering on auction id and checking which one the highest bid is my self.

**Comment by depinski** [comment]
I'm seeing this behavior also. The subsequent refresh auctions set hb_ data using bids from the first auction for ads which already served and which do not have a higher cpm than in the auction done in the refresh. I've identified this by keeping track of bids I'm expecting to receive back myself and not seeing the new adids in the hb_ params. I saw similar behavior in 0.34.x but there my solution was to simply clear out the hb_ params for ads that had already served and it would affect only a single placement. Issue is still present in 1.10 but now seems to affect all placements.

**Comment by mkendall07** [comment]
@depinski 
>The subsequent refresh auctions set hb_ data using bids from the first auction for ads which already served and which do not have a higher cpm than in the auction done in the refresh

That definately should not be happening. Do you have a test page? 
@Slind14 can you confirm this is the issue you are seeing? Sounds like not based on this comment https://github.com/prebid/Prebid.js/issues/2539#issuecomment-389766575

**Comment by mercuryyy** [comment]
@jsnellbaker Any update? this is related to the "FIFO" issue
https://github.com/prebid/Prebid.js/issues/2448  @jaiminpanchal27
