### ISSUE TITLE
Bug New Rubicon Adapter

### ISSUE THREAD

**Issue by Deimos01** [prebid/Prebid.js#254]
Hi,

I just discovered a bug for the new Rubicon adapter.
When rubicon is winning the bid, they can't render and display the ads on the websites who are using prebid in multiple iframes (adserver, adnetwork ...) . We have an error in the console : 

> 
Uncaught TypeError : Cannot read property 'renderCreative' of undefined

So i remplaced this line :

`;(function (w, fe) { w.rubicontag.renderCreative(fe, "XXXX", "XX"); }(window.top, (document.body || document.documentElement)));
`
By :

`;(function (w, fe) { w.rubicontag.renderCreative(fe, "XXXX", "XX"); }(parent.window, (document.body || document.documentElement)));`

**parent.window** instead of **window.top** line 216 in prebid.js

It's working and I think it's better (iframe or not).

Thank you,

**Comment by mkendall07** [comment]
@Deimos01 
Thanks for bug report. This change looks good to me.
@bretg mind taking a look as well.

**Comment by bretg** [comment]
Good catch - thanks @Deimos01.  Working with the team to test a more robust approach. Hope to have a pull request in the next day or two.

**Comment by bretg** [comment]
@mkendall07 -- pull request 265

**Comment by protonate** [comment]
PR #265 has been merged to master manually with [this commit](cb8c12b54d2eb348b62ba3efb35f6e57835e217d). Closing.

**Comment by protonate** [comment]
Reopening, will close with release of v0.8.0.

**Comment by protonate** [comment]
Released with 0.8.0
