### ISSUE TITLE
Prebid 1.0 does not get the entire page url when in an iframe

### ISSUE THREAD

**Issue by ix-prebid-support** [prebid/Prebid.js#2547]
## Type of issue
Bug

## Description
We can only retrieve the page domain rather than the entire page URL, via utils.getTopWindowUrl(), when Prebid is loaded in an iframe  

## Steps to reproduce
Set up a test page (e.g. http://localhost/prebid1.0/safeframe-parent.html) with an iframe.Prebid is loaded inside the iframe and has Index adapter configured 

### Actual results
The bid request to IX (http://as.casalemedia.com/cygnus) has the property `page`, which indicates the page url, set as `http://localhost` which is retrieved using `utils.getTopWindowUrl()` in the adapter 

### Expected results
The property `page` should be set as the entire page url i.e. `http://localhost/prebid1.0/safeframe-parent.html`

**Comment by mkendall07** [comment]
@ix-prebid-support 
I'm not sure the best way to fix this as other adapters may now be reliant on the broken behavior. Possibly we should fix it and also introduce a method that returns just the host portion of the referrer that those adapters can use.

**Comment by mkendall07** [comment]
@ix-prebid-support 
Please see the new referer detection module for support. https://github.com/prebid/Prebid.js/blob/master/src/refererDetection.js#L130
