### ISSUE TITLE
Invalid git tag - 0.34.10

### ISSUE THREAD

**Issue by vzhukovsky** [prebid/Prebid.js#2548]
## Type of issue
Bug

## Description
For some reason git tag 0.34.10 points to Prebid 1.11.0.

## Steps to reproduce
The following link demonstrates the issue:

https://github.com/prebid/Prebid.js/blob/0.34.10/package.json

**Comment by mkendall07** [comment]
@jsnellbaker 

can you fix?

**Comment by jsnellbaker** [comment]
I have recreated the tags and the `package.json` now has the proper version under the 0.34.10 tag.
