### ISSUE TITLE
Bug on adapterLoader not being loaded by babel

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#255]
The error below shows up on fresh clone, and fresh npm install trying to build prebid, i was able to build removing ES6 syntax on adapterLoader file

happens on OSX

gulp build
[23:05:48] Using gulpfile ~/Projects/PrebidGithub/gulpfile.js
[23:05:48] Starting 'clean'...
[23:05:48] Starting 'hint'...
[23:05:48] Starting 'jscs'...
[23:05:52] Starting 'webpack'...
[23:05:57] Starting 'devpack'...
[23:05:57] Finished 'clean' after 8.53 s
{ [Error: /Users/alex/Projects/PrebidGithub/loaders/adapterLoader.js:3
const fs = require('fs');
^^^^^
Use of const in strict mode.
 @ multi main]
  message: '/Users/alex/Projects/PrebidGithub/loaders/adapterLoader.js:3\nconst fs = require(\'fs\');\n^^^^^\nUse of const in strict mode.\n @ multi main',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function] } }
{ [Error: /Users/alex/Projects/PrebidGithub/loaders/adapterLoader.js:3
const fs = require('fs');
^^^^^
Use of const in strict mode.
 @ multi main]
  message: '/Users/alex/Projects/PrebidGithub/loaders/adapterLoader.js:3\nconst fs = require(\'fs\');\n^^^^^\nUse of const in strict mode.\n @ multi main',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function] } }
src/adapters/triplelift.js: line 1, col 5, 'CONSTANTS' is defined but never used.

1 error
[23:07:07] Finished 'jscs' after 1.3 min
[23:07:07] Finished 'hint' after 1.3 min
[23:07:07] Starting 'quality'...
[23:07:07] Finished 'quality' after 72 μs

**Comment by protonate** [comment]
What version of Node are you running? With the ES2015 syntax support we added a dependency of Node 4.x or greater, though this hasn't been well documented. An upgrade to Node should resolve this issue. More info is [here](https://nodejs.org/en/docs/es6/).

This is also discussed in [this issue](https://github.com/prebid/Prebid.js/issues/245).

**Comment by ialex** [comment]
node --version
v0.12.6
