### ISSUE TITLE
Prebid.js give publishers revenue with first price auction or second price auction ?

### ISSUE THREAD

**Issue by hereisethanhunt** [prebid/Prebid.js#2568]
## Type of issue

This is a question for gaining insight on prebid . 
Prebid.js give publishers revenue with first price auction or second price auction ?

## Description
I am trying to understand prebid.js . So far I know, after creating line items, and creatives and generating tags using gpt, we use prebid.js script functions to start bidding auction where the results of bids are sent to the corresponding line items . 

For eg. if the bid received is 2.32 & 2.21 , it is fetched in line item capped to 2.30(as the custom granuality we set) and in line item capped to 2.20(as set) . so hb_pb becomes 2.30 and 2.20 . Now the max bid is 2.30 , so how much will the publisher receive ?? Will he receive 2.30 , or will he receive 1 cent more than the second highest bidder(in this case 2.20) i.e 2.21 .

I am not able to understand do second price auction happens in prebid.js or its as straightforward as making the highest bid as publishers revenue ?

Also my second question is - how to set a bidfloor for bidders who dont have bidfloor parameters as mentioned in docs. 
For eg. appnexus doesnt have bidfloor parameter , so how can i implement flooring using appnexus bidder.

Anyone please clarify on this.  

## Platform details

prebid version 1.0

**Comment by dmitriyshashkin** [comment]
1) It's first price auction. Actually, most sps are going the first price nowadays
2) You can use cpm adjustment http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.bidderSettings If bid's cpm is lower than the floor, reduce it to 0. But ofc the bidder won't know that you're applying the floor. Another option would be to deactivate the LI corresponding to lower CPMs in DFP The best option ofc would be to set the floor in each SSPs publisher console. This way ssp will send this floor to in bid requests and buyers will have a chance to react to it and adjust their behavior

**Comment by hereisethanhunt** [comment]
Thanks a ton. Because of you guys, prebidjs rocks. I need to ask one thing, do all ssp publisher console have the option to set bidfloor?  I mean, in some we can set while creating the adunits too, but some dont have that param., so do they have such setup in their console? Can u clarify, sorry if i am heading to the wrong direction

**Comment by dmitriyshashkin** [comment]
Well, yes, not every SSP allows you to set the floor and it might be difficult to set different floors for different devices/regions. Some SSPs don't have a console at all. So I guess you can use approach 1 or 2 and if possible specify floor in the bidder params or in publisher's console.
