### ISSUE TITLE
Sonobi adapter producing TypeError in getUserSyncs

### ISSUE THREAD

**Issue by gramorris** [prebid/Prebid.js#2570]
## Type of issue
bug

## Description
When bids come back from Sonobi and are adjusted we're seeing the following error:

TypeError: Cannot read property 'forEach' of undefined
    at Object.getUserSyncs

## Steps to reproduce
We are adjusting the bids but as far as I can tell it's happening every request on all of our sites.

## Platform details
Version 1.11.0

**Comment by JonGoSonobi** [comment]
@gramorris The error should get caught and logged appropriately. Is this not the case? Can you provide a link to the site that its happening on?
