### ISSUE TITLE
ix/indexExchange ignores unit if media type is not set

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#2574]
## Type of issue
Bug

## Description
According to the docs, media type field for ad unit is optional. Yet ixBidAdapter expects it to bet, otherwise, it just ignores that banner. Seen a major drop in impressions since updated to 1.x

``` 
if (utils.deepAccess(validBidRequest, 'mediaTypes.banner') ||
        validBidRequest.mediaType === 'banner') {
        bannerImp = bidToBannerImp(validBidRequest);
        bannerImps.push(bannerImp);
}
```

## Steps to reproduce
Create an ad unit, add ix to bidders, do not specify the media type.

### Expected results
Index competes for the impression

### Actual results
Index excludes this unit from bid request. "Imp" field in https request to cygnus server is empty

## Platform details
Prebid 1.11

**Comment by jaiminpanchal27** [comment]
@dmitriyshashkin Not able to reproduce. Here is the test page https://jsfiddle.net/8z103Lpc/
I can see the call to http://as.casalemedia.com/cygnus...  and get `{id: "3cf1af3371e3d4"}` as response.

**Comment by rachelrj** [comment]
This happens with us as well. Also if the size is not set as a param (bidder param), will error out also.

**Comment by rachelrj** [comment]
There should also be some sort of communication that `siteID` changed to `sideId`. This has been a major issue for upgrades.

**Comment by aprakash-sovrn** [comment]
Hi @jaiminpanchal27,
It doesn't look like prebid.js is loading on your fiddle, I get a 404 on the call to `https://fiddle.jshell.net/build/dev/prebid.js`. Also, I believe the call to http://as.casalemedia.com/cygnus... is still made without a `mediaTypes` field, but with an empty `imp` array (as the code snippet pointed out by @dmitriyshashkin skips adding the bid to the imp array without that field).

The size as a bidder param is also an interesting change. Is the publisher only allowed to specify one size in bid requests to ix now?

**Comment by ptim** [comment]
regarding @rachelrj 's comment about size - I found the docs ambiguous, and opened an issue over here: https://github.com/prebid/Prebid.js/issues/2590

**Comment by aprakash-sovrn** [comment]
@ix-prebid-support, are you able to shed light on some of these issues?
