### ISSUE TITLE
Internet connection speed Issue on Prebid 1.X

### ISSUE THREAD

**Issue by Deimos01** [prebid/Prebid.js#2580]
Hello guys, I think I found a tricky problem linked to the new Prebid version (1.X).

## Type of issue
Bug related to timeout and SSP response time.
## Description
So we updated our Prebid version for our network from 0.34.6 to 1.11.0. But 2 days after the migration, we lost millions of daily impression requests on all our SSP (30%-25%).
After a long investigation, I found that Prebid 1.11.0 is not dealing well with slow/medium internet connection speed.
It seems that SSP are taking longer to answer with Prebid 1.11.0 than with Prebid 0.34.6

## Steps to reproduce
You have to compare 2 webpages with version 1.11.0 and version 0.34.6 with a slow/medium internet connection speed.
## Test page
Here is the [1.11.0 demo](https://www.themoneytizer.com/demo/prebid1_11?pbjs_debug=true) page and here is the [0.34.6 demo](https://www.themoneytizer.com/demo/prebid0_34?pbjs_debug=true) page.
You have exactly the same Prebid wrapper setup on both pages (same formats, same SSP, same timeout of 1000ms).

Now you have to simulate a 3G connection speed by using the Network debugging tool on Google Chrome.
<img width="628" alt="Network speed connection" src="https://user-images.githubusercontent.com/5635647/40314878-d73dac38-5ce7-11e8-86e5-1af8f128ea9c.png">
You can try with 3G Fast or Slow.
So you will have a lot of "xhr timeout after  1000 ms" with the version 1.11.0 from different SSPs and 0 timeout with the 0.34.6 or just a few with the Slow connection speed.
<img width="1236" alt="1.11.0" src="https://user-images.githubusercontent.com/5635647/40315146-95a04672-5ce8-11e8-8717-920711717452.png">
1.11.0 (a lot of timeouts)

<img width="276" alt="0.34.6" src="https://user-images.githubusercontent.com/5635647/40315300-f960a2e2-5ce8-11e8-9605-655bdf26229a.png">
0.34.6 (0 timeout)

### Expected results
The SSP response time should not be impacted by the Prebid version.

## Platform details
Google Chrome Version 66.0.3359.181  - Prebid 0.34.6 vs Prebid 1.11.0

## Other informations
Some SSPs have the same endpoint URL and exactly the same code in both versions. So I don't understand why you have a really slow response time in one version (1.11.1) and it's working correctly in the other version (0.34.6). So it's probably a Prebid library problem.

Thank you,

**Comment by snapwich** [comment]
@jaiminpanchal27 do you mind investigating this?  I imagine if this issue has to do with Prebid.js core code then it'd most likely revolve around the auction refactoring.

**Comment by jaiminpanchal27** [comment]
@snapwich Will check.

**Comment by mkendall07** [comment]
You seem to have a race condition in your test page. A call to `addAdUnits` is not inside the pbjs.que. 

![image](https://user-images.githubusercontent.com/1870166/40331408-475e0d4c-5d1e-11e8-9266-31fbd6dfb769.png)

**Comment by Deimos01** [comment]
@mkendall07 No I think it's because my wrapper code is executed before Prebid.js is totally loaded, probably because of the (really) slow connection.
I'm not able to reproduce this error, you should try with 3G Fast connection speed to avoid this error and see the timeout errors.

**Comment by Deimos01** [comment]
Okay I found the solution.
The old way to declare the timeout directly as a parameter in the Adunit was not working anymore in the 0.34.6 version.
`var Adunits=[{
 code: 'mydiv',
 timeout: 2000,
 sizes: "[[300,250]]" ...`
So the real bidderTimeout was the default timeout of Prebid (3000ms) on our previous setup and not 1000ms.
Anyway, the conclusion of this situation is that 25% of our adrequests to some SSPs are taking longer than 1000ms.

Thank you.
