### ISSUE TITLE
ConsentManagement module problem with multiple calls to requestBids

### ISSUE THREAD

**Issue by rale** [prebid/Prebid.js#2586]
## Type of issue
Bug

## Description
If more than one call to requestBids is made while the GDPR ConsentManagement module is enabled, all but the last call are dropped.

## Steps to reproduce
- Enable consentManagement module
- Create two separate ad units, calling requestBids separately for each one, before consent is loaded

### Expected results
Both auctions should run.

### Actual results
Only the last auction is run.

## Platform details
Prebid 1.11.0

## Other information
I took a look at consentManagement.js, and it appears as though requestBidsHook is overwriting the context each time requestBids is called.

**Comment by mkendall07** [comment]
looks like you are correct. Thanks for the bug report. @jsnellbaker please address. Thanks

**Comment by jsnellbaker** [comment]
@rale Thanks for reporting this bug.  I have put together a fix that addresses this problem (#2612).  We'll try to get it included soon.

**Comment by mkendall07** [comment]
this is resolved.
