### ISSUE TITLE
Question: Is there an easy way to disable header bidding for testing purposes?

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#2587]
Question: Is there an easy way to disable header bidding for testing purposes without removing all the code?

**Comment by snapwich** [comment]
You could just comment out the `pbjs.requestBids` calls.

Or if you want to add a little code, you could do it programatically.

```javascript
var pbjs = {
  que: [function() {
    pbjs.requestBids = function() {};
  }]
}
```

**Comment by headerbidding** [comment]
Thank you!
I commented out the pbjs.requestBids line and it works fine.
(If I wanted to do the code snippet, where would I insert it?)

**Comment by snapwich** [comment]
if you wanted to use the code snippet you'd put it somewhere before where you load the prebid.js library.

**Comment by headerbidding** [comment]
So that would be before:
<script type="text/javascript" src="/prebid.js" async></script> 
Correct?

**Comment by snapwich** [comment]
yes
