### ISSUE TITLE
We as advertiser want to load each placement seperatly

### ISSUE THREAD

**Issue by adtechnology** [prebid/Prebid.js#259]
[API Reference](http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs) is not uptodate.
Need a callback when using pbjs.requestBidsForAdUnit or other way to call single placements one by one...

**Comment by mkendall07** [comment]
@adtechnology 
Could you explain the use case a bit more? We have a way to request single ad units but I'm not sure it will work properly in your use case...

**Comment by adtechnology** [comment]
Sure, we use to reload certain ads on user action, but only if they are visible at the moment of interaction, so it can happen that only one single placement has to be reloaded and we would like to pass them througt prebid first.

How would this be possible?

**Comment by protonate** [comment]
Related #268

**Comment by mkendall07** [comment]
@adtechnology 
You can use `pbjs.requestBids()` and pass in the adunit(s) you want in the request here: http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.requestBids. 

We are also working on #268 which should improve this type of functionality so closing this ticket.
