### ISSUE TITLE
ix/indexExchange adunit config docs error?

### ISSUE THREAD

**Issue by ptim** [prebid/Prebid.js#2590]
## Type of issue

IX Documentation / adunit configuration

(this is a documentation issue, but it's in the prebid module source, so I figure this is the appropriate place...)

## Description

I think the line linked should read: `siteId: '4622',`... is that right?
https://github.com/prebid/Prebid.js/pull/2496/files#diff-a2f2834ff17b6a970602a20e6ad5db67R150

I need to confirm that the `siteId` need not be unique between sizes in a single placement (please see the example - looks like a typo)

CC @indexexchange 

**Example**
```javascript
var adUnits = [{
    code: 'banner-div-a',
    mediaTypes: {
        banner: {
            sizes: [
                [300, 250],
                [300, 600]
            ]
        }
    },
    bids: [{
        bidder: 'ix',
        params: {
            siteId: '4622',
            size: [300, 250]
        }
    }, {
        bidder: 'ix',
        params: {
            siteId: '6242', // should this read '4622'?
            size: [300, 600]
        }
    }]
}];
```

**Comment by jnsprngs** [comment]
Index emailed out a supplemental PDF with a few details on implementation. In it they said, "Please note that you can re-use the existing siteId within the same flex position."


So I would take that as confirmation that they want you to use the same siteId within a adUnit for the n different sizes you want to support in that adUnit.
