### ISSUE TITLE
consent management module: incorrect field for consentString

### ISSUE THREAD

**Issue by jbartek25** [prebid/Prebid.js#2591]
## Type of issue

bug

## Description

The current implementation of the consent management module expects "metadata" field in the CMP API getVendorConsents' return object to contain the consent string which is incorrect as per [CMP API spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md#vendorconsents) the "metadata" field contains just what it says - metadata like timestamps, version of CMP, version of vendor list, etc. The correct field containing the consent string should be "consentData" in the return object of the getConsentData command.

**Comment by jsnellbaker** [comment]
Based on some internal discussion, the spec isn't explicitly clear about what parts of the consent information should be included in the consentData field from a getConsentData request vs what's listed as part of the metadata field from the getVendorConsents.  

That said, to err on the side of the caution and adherence to the spec - we're putting together a change that will use the `getConsentData` request to obtain the 'consentString' value.  We're still going to include the unparsed vendorConsent information for any bidders who wish to use this information directly in their adapter code.

**Comment by jsnellbaker** [comment]
This has been fixed.
