### ISSUE TITLE
GDPR Debug Options

### ISSUE THREAD

**Issue by GLStephen** [prebid/Prebid.js#2593]
The Consent Module doesn't seem to toss debug information nor expose functions to see status. We're working on debugging status of Consent integration and trying to determine how to verify status in various configs (EU, Non-EU, etc.)

Am I missing something?

**Comment by GLStephen** [comment]
@mkendall07 I'm working on tracing that the auction was delayed by the CMP existence, whether consent was activate or not, a "state indicator" if you will, that the CMP UI completing activated the auction and what data was passed to bidders. I would like to see it in the stream of existing debug information. If it's not available then I can submit a PR. I wanted to make sure I wasn't going to duplicate work that existed, was in process or that I just wasn't seeing.

**Comment by mkendall07** [comment]
Makes sense. We don't have it of you want to submit a pr
