### ISSUE TITLE
How to retrieve gdprConsent Object on my bidsBackHandler function ?

### ISSUE THREAD

**Issue by elbidone** [prebid/Prebid.js#2596]
## Type of issue
Question

## Description
I need to send to my Ad Server gdrConsent values (consentString and gdprApplies). How can I get these values on from the bidsBackHandler function ?

Thanks

**Comment by dmitriyshashkin** [comment]
I don't think the prebid's consent module has any public api. I'd suggest calling cmp framework directly. Something like that: window.__cmp('getConsentData', null, function(d){console.log('concent cb', d.consentData)})

**Comment by dmitriyshashkin** [comment]
Not the best solution as the local cookie name is not fixed by the standard. Besides, why bother with polling when there is a way to pass a callback?
