### ISSUE TITLE
AOL Adapter ADTECH_URI

### ISSUE THREAD

**Issue by Deimos01** [prebid/Prebid.js#260]
Hi,

I'm using the AOL adapter with a french network Adtech ID so the  adcall URL is not working with the US version of JS :

`ADTECH_URI = (window.location.protocol) + '//aka-cdn.adtechus.com/dt/common/DAC.js',`

but :
`
ADTECH_URI = (window.location.protocol) + '//aka-cdn.adtech.de/dt/common/DAC.js',`

So maybe you should add a parameter to configure this ADTECH_URI.

Thank you !

**Comment by mkendall07** [comment]
@Deimos01 
Thanks for the info. We'll add it to the next release.

**Comment by mjwhaley** [comment]
@Deimos01 @mkendall07 We pass the european Adtech url as part of the param's to get round this issue.
                bidder: 'aol',
                params: {
                   network: '1111',                   
	           placement: '1111111',
                   server: 'adserver.adtech.de',
                   alias: '1111'
 						}

This does seem to do the trick.

**Comment by mkendall07** [comment]
@mjwhaley 
Is that supported in the 0.7.0 version of prebid?

**Comment by mjwhaley** [comment]
@mkendall07 I haven't tried this method with 0.7.0 yet. I'm still running on 0.6

**Comment by protonate** [comment]
There is a new AOL consolidated library that is in master as of [this commit](https://github.com/prebid/Prebid.js/commit/4277d8baf543d4aecf2110a8d30b544e768a1bc9). This may be a solution. At the moment both @Deimos01 and @mjwhaley have proposed workarounds for version prior to Prebid 0.7.0. The new consolidated library will be released with version 0.8.0 next week. 

Closing, please reopen if additional questions or info.
