### ISSUE TITLE
bower and npm support for 0.7.0

### ISSUE THREAD

**Issue by galaxyblur** [prebid/Prebid.js#261]
Background: our implementation loads prebid.js as a dependency through bower. We also use npm for other modules.

bower: Seems that in the latest release, 0.7.0, the "build" directory was added to .gitignore, which means that I cannot include prebid.js at runtime from the build directory unless I first run gulp within prebid.js, which is not an existing pattern and, in my opinion, breaks the public API of prebid.js (and thus should've been loudly announced and used a major version bump, following semver.org).

Seems like the front-end space as a whole might be moving away from bower, so I tried npm instead. However, the latest version of prebid.js published to the official npm index is 0.5.0. If you truly support npm, and include instructions on using npm in your README, you should actually maintain support with every version.

**Comment by protonate** [comment]
We need to bring npm and bower versions up to latest and will address this soon, thanks for pointing it out.

**Comment by galaxyblur** [comment]
@protonate Thanks, much appreciated

**Comment by protonate** [comment]
npm is now updated with latest version, 0.8.1, and will be maintained with current releases. We will no longer be distributing via bower.
