### ISSUE TITLE
Appnexus prebid server endpoint (400) bad request

### ISSUE THREAD

**Issue by RajasekarPR** [prebid/Prebid.js#2623]
400 - Bad Request

I have upgraded to the latest version of Prebid.js and I am getting bad request for below appnexus prebid server.

https://prebid.adnxs.com/pbs/v1/openrtb2/auction - Bad Request . Why is it so ?

And it just works fine with previous version 1.11.0 

Need a help on this.

**Comment by dbemiller** [comment]
@RajasekarPR can you past the JSON payload from the request body?

**Comment by RajasekarPR** [comment]
I just configured the below configuration for prebid Server in setConfig

 s2sConfig: {
            accountId: '**************************',
            bidders: ['districtm', 'conversant', 'pulsepoint', 'rubicon'],
            defaultVendor: 'appnexus'
        }
And this same configuration works perfectly with existing version

**Comment by mkendall07** [comment]
@RajasekarPR 
We also need the adUnit information for those bidders to replicate the issue. Thanks.

**Comment by RajasekarPR** [comment]
Request Body:

"{"code":"dfp-el-1","mediaTypes":{"banner":{"sizes":[[300,250],[300,600]]}},"bids":[{"bidder":"districtm","params":{"placementId":"11795799"},"crumbs":{"pubcid":"8d06dc2f-6698-479f-8556-7c8e39d4f0f6"}},{"bidder":"conversant","params":{"site_id":"113002","secure":true},"crumbs":{"pubcid":"8d06dc2f-6698-479f-8556-7c8e39d4f0f6"}},{"bidder":"yieldbot","params":{"psn":"5n4q","slot":"desktop_puk_rec"},"crumbs":{"pubcid":"8d06dc2f-6698-479f-8556-7c8e39d4f0f6"}},{"bidder":"pulsepoint","params":{"cf":"300X250","cp":560781,"ct":598651},"crumbs":{"pubcid":"8d06dc2f-6698-479f-8556-7c8e39d4f0f6"}},{"bidder":"rubicon","params":{"accountId":16590,"siteId":136378,"zoneId":641312},"crumbs":{"pubcid":"8d06dc2f-6698-479f-8556-7c8e39d4f0f6"}},{"bidder":"appnexusAst","params":{"placementId":"11992539"},"crumbs":{"pubcid":"8d06dc2f-6698-479f-8556-7c8e39d4f0f6"}},{"bidder":"sharethrough","params":{"pkey":"5zG333txChag43FCP7schd5W"},"crumbs":{"pubcid":"8d06dc2f-6698-479f-8556-7c8e39d4f0f6"}},{"bidder":"openx","params":{"unit":"540028117","delDomain":"egton-d.openx.net"},"crumbs":{"pubcid":"8d06dc2f-6698-479f-8556-7c8e39d4f0f6"}}],"transactionId":"8d62ff6b-dcc3-44f1-83b4-3a7b8d615168","sizes":[[300,250],[300,600]]}"

**Comment by paulm999** [comment]
We're seeing the same issue, all worked fine on the previous release. 

If using Sovrn, the error is:
Invalid request format: request.imp[0].ext.sovrn failed validation.
tagId: tagId is required

Tagid exists in the code and I can see it in the header request:
[{id: "site72890", ext: {sovrn: {tagid: "567536"}},…},…]

If using DistrictM, the error is:
Invalid request format: request.imp[0].ext contains unknown bidder: districtm. Did you forget an alias in request.ext.prebid.aliases?

**Comment by RajasekarPR** [comment]
I have used endpoint without RTB protocol now. And it's working fine now.

s2sConfig: {
            accountId: '***********************',
            bidders: ['districtm', 'conversant', 'yieldbot', 'pulsepoint', 'rubicon', 'appnexusAst', 'sharethrough', 'openx'],
            timeout: 1e3,
            adapter: 'prebidServer',
            endpoint: 'https://prebid.adnxs.com/pbs/v1/auction',
            syncEndpoint: 'https://prebid.adnxs.com/pbs/v1/cookie_sync',
            cookieSet: !1,
            enabled: !0
        }

Modified the above configuration and it's works as expected :) :)

**Comment by RajasekarPR** [comment]
But getting bad request only using endpoint with RTB protocol. Don't know why .  Something Crazy ...................................

**Comment by dbemiller** [comment]
Thanks for the details.

The `sovrn` error looks legitimate. In Prebid Server they expect `tagId`, not `tagid`. See https://github.com/prebid/prebid-server/blob/master/static/bidder-params/sovrn.json

You'd have to get in touch with the Sovrn devs... but perhaps they need to add a mapping here, if the params in PBS and Prebid.js differ? https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter.js#L207

Alternatively they could just submit a PR to the PBS repo making it accept `tagid`... but it depends on which way they want to go.

**Comment by dbemiller** [comment]
This:

> Invalid request format: request.imp[0].ext contains unknown bidder: districtm. Did you forget an alias in request.ext.prebid.aliases?

is almost certainly a bug somewhere in `Prebid.js`. PBS expects the Aliases to be sent in the request . like this: https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md#bidder-aliases

I know they _intend_ to send these aliases in the request:
- https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter.js#L470
- https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter.js#L547

...but I don't have any insight into the Prebid.js implementation details to suggest what might be going wrong there.

**Comment by RajasekarPR** [comment]
I have sent alias for bidder 'districtm' and something crazy on the prebid.js implementation and it makes somewhere going wrong there. 

Thanks for your valuable information dbemiller .Your help is much appreciated :)

**Comment by dbemiller** [comment]
to be clear @RajasekarPR @paulm999: did you both update `Prebid.js` versions _and_ switch PBS endpoints from `/auction` to `/openrtb2/auction` at the same time?

Does this bug occur in the previous release if you use `/openrtb2/auction` there? Does it occur in the current release if you use `/auction`?

**Comment by RajasekarPR** [comment]
Issue has been fixed when using appnexus endpoint without using RTB protocol in Latest Version of Prebid.js (1.12.0)

And it previous versions, the issue is not happened even when the appnexus endpoint used RTB protocol.

**Comment by mercuryyy** [comment]
Im also getting a 400 error for prebid.adnxs.com/pbs/v1/openrtb2/auction
legacy endpoint works fine.

Any update on fix?

**Comment by dbemiller** [comment]
@mercuryyy are you seeing one of the same errors reported by others here?

> If using Sovrn, the error is:
> Invalid request format: request.imp[0].ext.sovrn failed validation.
> tagId: tagId is required

or

> If using DistrictM, the error is:
> Invalid request format: request.imp[0].ext contains unknown bidder: districtm. Did you forget an alias > in request.ext.prebid.aliases?

Or do you see a different issue?

**Comment by dbemiller** [comment]
Regarding the sovrn issue, I let @aprakash-sovrn, who wrote the Prebid Server adapter, know about it. He/she said they'd look into it.

**Comment by dbemiller** [comment]
@RajasekarPR some more followups:

I used your `s2sconfig` & bidder params, and got a 400 with an error about the Conversant params:

```
Invalid request format: request.imp[0].ext.pulsepoint failed validation.
cf: Does not match pattern '^[0-9]+x[0-9]+$'
```

This is being fixed here : https://github.com/prebid/prebid-server/pull/536

However... once that was fixed, your request worked fine.

For those getting `districtm` errors, did you build `Prebid.js` with the `appnexus` module? If not, then the alias won't get defined anywhere.

**Comment by jsnellbaker** [comment]
To add to @dbemiller previous comment on the `districtm` or alias related errors, please provide a copy of the adunits/s2sconfig configuration you're using as it would help us investigate and pinpoint the issue.

**Comment by RajasekarPR** [comment]
{"bidder":"pulsepoint","params":{"cf":"300X250","cp":560781,"ct":598651},"crumbs":{"pubcid":"8d06dc2f-6698-479f-8556-7c8e39d4f0f6"}}

**Comment by jsnellbaker** [comment]
@RajasekarPR That's resulting in the regx error that @dbemiller mentioned earlier when I'm testing it.  Do you have a configuration that's currently seeing the alias error that was mentioned earlier in this thread?

**Comment by RajasekarPR** [comment]
yes .

**Comment by jsnellbaker** [comment]
@RajasekarPR Can you provide a copy of the adunit/s2sconfig that's currently returning the alias error so we can take a look?

**Comment by RajasekarPR** [comment]
@dbemiller  while these prebid server changes moved to prebidserveradapter. So that I can take the latest from latest version of Prebid.js ?

**Comment by freegames66** [comment]
I have the same problem. When i use `endpoint: 'https://prebid.adnxs.com/pbs/v1/auction',` <= It does not return a 400 error. However, I'm not sure the prebid server is actually working.

What is the difference between: 
`endpoint: 'https://prebid.adnxs.com/pbs/v1/auction',`
and
`endpoint: 'https://prebid.adnxs.com/pbs/v1/openrtb2/auction',`

Does anybody have a solution for this?

**Comment by dbemiller** [comment]
There are a _lot_ of differences between the two.

`https://prebid.adnxs.com/pbs/v1/auction` hasn't been maintained for a very long time now. It tends to lie (return 200s with no bids) when you're sending it bad data, doesn't support all the bidders in [the docs](http://prebid.org/dev-docs/prebid-server-bidders.html), and sometimes uses different bidder params.

`https://prebid.adnxs.com/pbs/v1/openrtb2/auction` is actively maintained. It returns 400s if it gets bad input (rather than silently returning no bids), [has documentation](https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md), and stays up to date with the prebid.org docs.

If you're seeing a 400 through `/openrtb2/auction`, most likely either:

1. Your Prebid.js ad units for s2sconfig are somehow wrong.
2. There's a bug in Prebid Server
3. There's a bug in Prebid.js.

We need more info to help debug, though. Open a new issue and include:

1. Your Prebid.js ad units & s2sconfig
2. The HTTP Request and Response bodies in the call made to Prebid Server. You can get these using the network tab of the dev tools in Chrome or Firefox

We should be able to sort it out from there.

**Comment by freegames66** [comment]
This is my prebid config: [https://www.freegames66.com/assets/js/hb/v7/bid5.js](https://www.freegames66.com/assets/js/hb/v7/bid5.js)
Please help me check this @dbemiller 

Thank you in advance!

**Comment by freegames66** [comment]
Can anyone help me look at this issue?
