### ISSUE TITLE
New Rubicon Adapter Not Working (in some cases)

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#263]
We have been using the old rubicon adapter for some time and it renders the ad without issue. The new rubicon adapter is causing some issue and it is mainly due to this:

```
<script type="text/javascript">;(function (w, fe) { w.rubicontag.renderCreative(fe, "test-div", "2"); }(window.top, (document.body || document.documentElement)));</script>
```

Taken from the bid response:

```
ad:"<script type="text/javascript">;(function (w, fe) { w.rubicontag.renderCreative(fe, "test-div", "2"); }(window.top, (document.body || document.documentElement)));</script>"
adId:"14d7cdb6a21a83"
adUnitCode:"test-div"
...
statusMessage:"Bid available"
timeToRespond:316
width:728
```

We load our wrapped prebid code into an friendly frame to protect our publishers sites from namespace pollution from our code, prebid code and that of adapters. - Because of this `window.top` is not the correct place to be looking. When publishers opt for unfriendly frames with back reference to top-most window will not be allowed either.

While we can work around this, I would just like to flag it as an issue.

**Comment by mkendall07** [comment]
@cwbeck 
Thanks for the report. This is duplicate issue #254
