### ISSUE TITLE
Server call failed for appnexus, rubicon after upgrading to latest Prepid. 

### ISSUE THREAD

**Issue by ShashankSureshMindEra** [prebid/Prebid.js#2637]
## Type of issue
QUESTION

## Description
 Upgraded to Prebid v1.11.0 and facing the below error messages (please see attached). 

## Test page
None

## Platform details
Prepid v1.11.0. Google Chrome. Mac OS. 

<img width="447" alt="screen shot 2018-05-29 at 3 39 31 pm" src="https://user-images.githubusercontent.com/39624042/40652752-c818d4e2-6356-11e8-9256-5348e205ab01.png">
<img width="483" alt="screen shot 2018-05-29 at 3 39 25 pm" src="https://user-images.githubusercontent.com/39624042/40652757-caa80372-6356-11e8-9bf3-7b9de16366b3.png">

**Comment by Deimos01** [comment]
I think you have this message because the timeout is reached for these SSPs. What is your bidder timeout ?

**Comment by mkendall07** [comment]
are you seeing this issue consistently? It could also have just been a network connectivity issue. Do you have a test page?

**Comment by Deimos01** [comment]
We were facing the same issue during our migration. Unfortunately 1200ms is a value too low for some 
internet connection speeds or some geos.
If you have a world wide audience, you should setup a 2000ms timeout (which is very long, I agree) to face this issue.

**Comment by ShashankSureshMindEra** [comment]
@mkendall07 : http://www.bounty.com/?pbjs_debug=true 

@Deimos01 : Let me try increasing the timeout. The page is indeed slow. It takes forever to load.

**Comment by mkendall07** [comment]
The test page you have is using prebid v0.32.0 not 1.10. Did you revert it?

**Comment by ShashankSureshMindEra** [comment]
Ah my bad. I am using resource overrides to use my local files which is a v11.0

**Comment by ShashankSureshMindEra** [comment]
@mkendall07 http://www.bounty.com/?pbjs_debug=true 
I have updated the files now. You should be able to see v1.11.0 now.

**Comment by sabadsha447** [comment]
@ShashankSureshMindEra Hey man, I know it's a long time, just checking my luck.
So i have been facing the same issue, It's saying "ERROR: Server call for adtelligent failed:  0. Continuing without bids." same for all other bidders, for the past 7 days same issue, I didn't change anything on my server it just suddenly started happening.
Just wanted to know how you have been able to fix this issue? I would be grateful if you can help me out, ik chances are too little, as it's 5 years old thread.
