### ISSUE TITLE
AppNexus Adapter - Iframe Issue

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#264]
Hi,

We are having an issue with the AppNexus adapter due to the iframe requirement. The return from the adapter is an `adUrl` requiring an iframe. This creates an unfriendly iframe which significantly limits the types of adverts which can run as any script loaded within is unable to access the ad iframe content window and not the page window. We have a requirement to run interactive banner adverts that trigger overlays.

Is there any way to get JS returned instead?

**Comment by mkendall07** [comment]
@cwbeck 
We released a beta for AppNexus adapter in 0.7.0. If you want to build the adapter, follow the instructions  in the release notes: https://github.com/prebid/Prebid.js/releases.

This should build a friendly iframe instead of a unfriendly.

**Comment by cwbeck** [comment]
@mkendall07 - I missed this. Built, tested and working perfectly.

Many thanks!

**Comment by mkendall07** [comment]
Great! 

Please give us any feedback you have on the new adapter.
