### ISSUE TITLE
AppnexusAst upgrade to V1.12 - alias bidder - double key-value sent to DFP

### ISSUE THREAD

**Issue by haroldpussat** [prebid/Prebid.js#2642]
## Type of issue
Question

## Description
We are trying to update our prebid version from 0.34 to 1.12, in order to get the module consentManagement working. I download the V1.12 from prebid.org
In 0.34 version, we have appnexusAst, criteo, Smart
For 1.12, we'll keep appnexus, criteo and Smart. We'll add Adyoulike and Rubicon, (plus module consentManagement and analytics adomik)

We already have our DFP lineItem targeted with appnexusAst key-values (like hb_pb_appnexusAst=XX and so on).
As I'm currently testing the new version 1.12 on our internal domain, I found that appnexus is now the only adapter and that appnexusAst have been renamed. So the targeting key value are now named hb_pb_appnexus instead of hb_pb_appnexusAst
My lineItems are not called with this news key-values.
I try to set alias on my js with
`pbjs.aliasBidder('appnexus', 'appnexusAst');`

The alias Bidder is set after my config 
`pbjs.que.push(function() {
		pbjs.setConfig({
			priceGranularity:customPriceGanularity,
			bidderSequence: "random",
			enableSendAllBids: true,
			bidderTimeout: PREBID_TIMEOUT,
			debug: true,
		});
	});`

And as a result, it seems the key-values to DFP are doubled (appnexus and appnexusAst are sent to DFP)
I can see this on my debug console

`MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_source_appnexusAs value: client
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_format_appnexusAs value: 
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_size_appnexusAst value: 300x250
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_adid_appnexusAst value: 10fe3c24ba27143
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_bidder_appnexusAs value: appnexusAst
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_pb_appnexusAst value: 0.220355
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_format_criteo value: banner
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_source_criteo value: client
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_size_criteo value: 300x600
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_pb_criteo value: 0.26
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_adid_criteo value: 20deb4ff78f3bba
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_bidder_criteo value: criteo
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_format_appnexus value: banner
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_source_appnexus value: client
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_size_appnexus value: 300x250
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_pb_appnexus value: 0.22
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_adid_appnexus value: 10fe3c24ba27143
prebid.js:3 MESSAGE: Attempting to set key value for slot: pub_pave1 key: hb_bidder_appnexus value: appnexus`

And also on my DFP ad request details
![image](https://user-images.githubusercontent.com/23049515/40668617-4a07b816-6365-11e8-9b26-88613f57d6bb.png)

Maybe I'm using the aliasBidder in a wrong way. What I want is to get appnexusAst key-value to be sent to DFP and not the appnexus key-value with prebid.js v1.12.
I have more than 8000 lineItem to update if it's not possible send appnexusAst key-value.

## Steps to reproduce
See the initial description

## Test page
If needed, I can provide one

### Expected results
Using the alias, I just want the key-values appnexusAst to be sent to DFP and not the appnexus key-value

### Actual results
Key-value for appnexus and appnexusAst are sent to DFP

## Platform details
PRebid.js 1.12, Chrome (latest, and beta)

**Comment by mkendall07** [comment]
Do you have a test page to see this issue live? 
`pbjs.aliasBidder('appnexus', 'appnexusAst');` is not required because we already have a alias in the bidder. All you need to do is setup your adunit bidders to use `appnexusAst` instead of `appnexus`.

**Comment by haroldpussat** [comment]
Thanks for the quick feedback.
See the  test page : http://www.precom-multimedia.com/interne/hpu/prebid-lpm-consent/

@mkendall07 : How can I do this ? [All you need to do is setup your adunit bidders to use appnexusAst instead of appnexus]

**Comment by haroldpussat** [comment]
Ok, sorry, I did write to quickly. I'll update the adunit bidders using appnexusAst instead of appnexus and remove the aliasBidder, in order to test

**Comment by haroldpussat** [comment]
With this setup, I still have the double key-value sent to DFP
Plus, the hb_pb_appnexusAst is not correctly rounded (0.239452 instead of 0.23), see screenshot below
![image](https://user-images.githubusercontent.com/23049515/40669772-ff32866a-6367-11e8-991d-bdb1917468da.png)

**Comment by mkendall07** [comment]
@haroldpussat 
Your custom adserver keys are doing this:
![image](https://user-images.githubusercontent.com/1870166/40690774-8cac9996-6376-11e8-9042-ad13c0b71c93.png)
Change them to `appnexus` and it should resolve the issue.

**Comment by haroldpussat** [comment]
Thanks for the feedback. The issue was on my side and was due to confusion.
It works now, I set appnexusAst as the bidder in adunit param, erase the bidderSetting for key rewrite, comment the aliasBidder and now  it's ok. The Ast key are well sent to DFP.
