### ISSUE TITLE
Impression Loss on Header Bidding Expert Chrome extension

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#266]
We have a site where we have two bidders Sovrn and Rubicon(fastlane) since the extension hasn't been updated we cannot see calls logged to Rubicon on the extension, but it says that some bidder could be delaying the load for the GPT. 

What does impression loss mean in this case, if gpt is taking more time to load isn't it giving more room to bidder to return bids and set targeting? 

Why does it recommends to set a shorter timeout?

**Comment by prebid** [comment]
Hi @ialex, could you provide a link to the site you are referring, so that we can add the missing pattern match for Rubicon?

Attaching a screenshot of your headerbid expert would also help. Thanks!

**Comment by ialex** [comment]
@prebid http://refugeforums.com/refuge/forums/canadian-hunters-forum.12/  TIMEOUT = 500
