### ISSUE TITLE
Link from the email "Your customized Prebid.js download link enclosed" is not available (404)

### ISSUE THREAD

**Issue by jarnix** [prebid/Prebid.js#2662]
## Type of issue
This looks like a bug

## Description
I go on the download page, make my selection, and click download, I enter my email, then receive the email, the link in the email gives me a 404.

My selection was:
-AppnexusBidAdapter
-AudienceNetworkBidAdapter
-IxBidAdapter
-RubiconBidAdapter
-ConsentManagement

## Steps to reproduce
As the description says

## Test page
The url provided in the email is:
http://client-test.devnxs.net/downloads/prebid_20180531144845.js.gz

### Expected results
Downloading of the compressed js file.

### Actual results
A 404

## Platform details
Chrome, link sent in gmail

**Comment by jarnix** [comment]
Hum the email is strange also:

The compiled prebid.js file with the above demand partners has been minimized to ** empty string ** kb. Please download the file from this link and unzip it. 
Important: verify the md5 sum we have computed before using: **undefined**

**Comment by mkendall07** [comment]
@jarnix 
Did you download 1.x or legacy? `IxBidAdapter` is not available in legacy

**Comment by jarnix** [comment]
Sorry I forgot to mention this: yes it was on 1.x

**Comment by mkendall07** [comment]
I'm not able to reproduce the issue. Are you sure you selected 1.x? 
Here's the link to my build: http://client-test.devnxs.net/downloads/prebid_20180531152908.js.gz

**Comment by jarnix** [comment]
Hum maybe then I chose the 0.34, it's true that I did a few tests and I get the undefined + 404 only with the 0.3 version.

So maybe the email would need to say that the file could not be generated or the adapter should not be listed when I request the 0.34 version.

**Comment by mkendall07** [comment]
yes I understand it's a bit challenging right now. We have a new download page in the works that will be much better. stay tuned.

**Comment by jarnix** [comment]
I understand :) Cheers
