### ISSUE TITLE
bidders do third party block checks on new users

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#2669]
## Type of issue
Performance of auction

## Description
On a user they haven't seen before, most bidders will set a cookie and 302 to themselves to determine if setting it was successful. This is a very common practice in adtech, as no one wants to maintain key-value stores and logs of failed sets. However, in this scenario, some bidders seem to be slow at this 302 and it can delay the auction substantially. It would be very nice if adapters were allowed to do this check for successful cookie set after a delay and returned their bids immediately without a redirect. 

## Steps to reproduce
Open up almost any site with several prebid partners in an incognito chrome window.

## Test page
https://thestir.cafemom.com/celebrity_moms/185735/mila_kunis_says_she_is has an example of AOL exhibiting this behavior. 

### Expected results
Self handshakes should be delayable

### Actual results
Self handshakes seem to be treated differently than other user sync delays.

**Comment by dmitriyshashkin** [comment]
But use syncs happen after the auction and shouldn't be able to delay it. Or am I missing something?

**Comment by patmmccann** [comment]
bidders are 302'ing to their own url to check for successful cookie setting, this self handshake is not delayable right now.

**Comment by patmmccann** [comment]
this 302 behavior was occurring on endpoint calls, not syncs, back in 2018. I can't find an example of it still occurring.
