### ISSUE TITLE
Uncaught ReferenceError: pbjs is not defined

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#267]
Easiest way to reproduce - include prebid.js onto the page, while omitting all the inline code. 

<script type="text/javascript" src="/build/dev/prebid.js" async></script>

Apparently prebid.js where pbjs object is declared is not the first module to be included into the final build. Yet some of the adapters are trying to add methods to pbjs.

**Comment by cwbeck** [comment]
We noticed this too in the last couple of builds. Easiest way to avoid is the prepend with:

```
var pbjs = pbjs || {};
pbjs.que = pbjs.que || [];
```

We just add this to the top of the prebid lib.

**Comment by mkendall07** [comment]
Thanks for pointing this out. Strange because we are already doing this:https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L4

It's possible that our compile process is moving this line. We'll investigate that.

**Comment by protonate** [comment]
Thanks @dmitriyshashkin for reporting the bug, fixed with PR #271.

**Comment by protonate** [comment]
Released with [0.8.0](https://github.com/prebid/Prebid.js/releases/tag/0.8.0)
