### ISSUE TITLE
Criteo - no creative ID

### ISSUE THREAD

**Issue by smartbidder1** [prebid/Prebid.js#2672]
Type of issue
bug

Description
when requesting an ad from Criteo bidder the response doesn't contain a unique creative ID.
there is a high importance of relaying on accurate creative id's for blacklists and debugging & reporting of bad ads.

#2374 for example had the same issue but they have fixed it already (very fast I might say).

@ahubertcriteo @Spark-NF

**Comment by smartbidder1** [comment]
@Spark-NF @ahubertcriteo anything?

**Comment by IsraeliAdblocker** [comment]
@Spark-NF @ahubertcriteo ?

**Comment by smartbidder1** [comment]
@mafaigna

**Comment by mkendall07** [comment]
Ping
