### ISSUE TITLE
getAdserverTargeting sometimes returns targets with adid from previous auctions

### ISSUE THREAD

**Issue by drdmitry** [prebid/Prebid.js#2676]
## Type of issue

Question

## Description

**pbjs.getAdserverTargeting()** sometimes getting targetings with AdIds which were used in previous auctions (and Ad was rendered). How to use AdIds returned in the latest requestBids call ?

![image](https://user-images.githubusercontent.com/4129726/40976854-9c92a5c2-68cf-11e8-8cd3-c6e150bb3371.png)

## Steps to reproduce

When requesting bids multiple times using **pbjs.requestBids**, sometimes **pbjs.getAdserverTargeting()** call inside bidsBackHandler returns targeting with AdIds from the previous requestBids calls.

## Test page

https://jsbin.com/xaruyupeku/edit?html,output
Open page, open console, click refresh button and check that targeting.adid is equals bid.adid

### Expected results
**pbjs.getAdserverTargeting()** should return targetings with AdIds from the last requestBids call.

### Actual results
**pbjs.getAdserverTargeting()** sometimes returns targetings with AdIds from the previous calls.

## Platform details

Prebid.js 1.12.0

## Other information

enableSendAllBids: true

**Comment by jaiminpanchal27** [comment]
@drdmitry I had a local PR with the fix. I think this might be the reason for #2648 
I will be pushing my branch now and ask everyone to test with that prebid.js build if it solves the impression problem. 

Thanks.

**Comment by derdeka** [comment]
Thanks @drdmitry, @jaiminpanchal27, this solves the "negative yield" bug for us, as an already rendered ad is served multiple times, but paid only once.

Additionally we still have a drop in impressions as described in #2648.

**Comment by mercuryyy** [comment]
@jaiminpanchal27 ran the "getAdservertargeting-bugfix" build seems to fix the problem but not the issue in https://github.com/prebid/Prebid.js/issues/2648

Perhaps should consider changing core behavior for action functions?

**Comment by johngeorgewright** [comment]
I opened this pull request a little while ago:

https://github.com/prebid/Prebid.js/pull/2697

To me it looks like Prebid is retrieving bids that have expired only. But obviously the tests then went berserk, and I thought... "this can't be right, I must be misunderstanding the logic here". But the more I test this version with prod data, the more it seems that this might be the solution. Does it work for anyone else?

**Comment by rmertens** [comment]
We also see this issue of rendering ads from previous auctions (on both 1.13 and 1.14).

**Comment by mercuryyy** [comment]
@jaiminpanchal27 will you include the branch as a regular pull for next release?

**Comment by mercuryyy** [comment]
@jaiminpanchal27 any plans to include an official push?

**Comment by jaiminpanchal27** [comment]
@mercuryyy It will be included in today's release

**Comment by jaiminpanchal27** [comment]
#2685 related issue.

**Comment by jaiminpanchal27** [comment]
@drdmitry Can you check if Prebid 1.15 has resolved your issue or not

**Comment by drdmitry** [comment]
@jaiminpanchal27, Yes, issue is resolved. Thanks.
