### ISSUE TITLE
wrong highest bid returned

### ISSUE THREAD

**Issue by renebaudisch** [prebid/Prebid.js#2685]
## Type of issue
Seems like a bug

## Description
Comparing "getHighestCpmBids" to "getAdserverTargeting" brings different results.

## Steps to reproduce
It is happening only a few times so I cannot reliable reproduce, but when visiting https://www.formel1.de/news/grand-prix-berichte/2018-06-06/rennvorschau-montreal-mercedes-spielverderber-hypersoft you could see this happens sometimes.

## Test page
https://www.formel1.de/news/grand-prix-berichte/2018-06-06/rennvorschau-montreal-mercedes-spielverderber-hypersoft

### Expected results
"getHighestCpmBids" may not have lower CPM then "getAdserverTargeting"

### Actual results
"getHighestCpmBids" sometimes gives lower CPM then "getAdserverTargeting"

## Platform details
doesn't matter

## Other information
A screenshot showing the issue:
![prebid_bug](https://user-images.githubusercontent.com/15980546/41041334-099706f2-699f-11e8-9107-4835f4e9c9bd.png)

**Comment by renebaudisch** [comment]
Closing when nobody even took a look is a very bad user experience...
It's not my fault that jaiminpanchal27 did not answer after14 days...

**Comment by jaiminpanchal27** [comment]
@renebaudisch Sorry for not looking at this one. This might be because of this https://github.com/prebid/Prebid.js/issues/2676. 
We have a fix for this coming today.

**Comment by renebaudisch** [comment]
So it's related, OK, thx, could you connect the issues?

**Comment by renebaudisch** [comment]
I will close it when I checked that 1.15 will solve this...

**Comment by jaiminpanchal27** [comment]
@renebaudisch Can you check and update the issue ?

**Comment by renebaudisch** [comment]
looks good
