### ISSUE TITLE
Sharethrough Adapter getUserSyncs function erroring

### ISSUE THREAD

**Issue by nodeful** [prebid/Prebid.js#2689]
## Type of issue
ShareThrough Bidder Adapter bug

## Description
![screen shot 2018-06-07 at 10 27 09](https://user-images.githubusercontent.com/8472525/41091592-d05d2fb0-6a3e-11e8-9a79-75f17cad876d.png)

![screen shot 2018-06-07 at 10 26 57](https://user-images.githubusercontent.com/8472525/41091566-be62b88e-6a3e-11e8-9ee5-6861b0f31a6e.png)

## Platform details
Prebid v1.11.0
macOS
Chrome 66.0.3359.181

## Other information
Logic added in this commit 157ee5b8026b73a427cfd431c14d4b8788e672cd

**Comment by harpere** [comment]
@jchau87 or @chriscpan can you take a look?

**Comment by jchau87** [comment]
Added an extra check for `serverResponses[0].body` in this PR:
https://github.com/prebid/Prebid.js/pull/2762/files#diff-cfc0ecf4a8eb3aa3f773e6bb3bdd977eR76

**Comment by nodeful** [comment]
Haven't seen these errors lately. Thanks for looking into it. Closing
