### ISSUE TITLE
ga.js fails to send pre-existing events

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#269]
The is a code in ga.js that sends all events fired before enableAnalytics called. And it seems to be inconsistent with the current events implementation:

    if (eventObj.eventType === BID_REQUESTED) {
      //bid is 1st args
      bid = args[0];
      sendBidRequestToGa(bid);
    } 

So it expects args to be a list with numeric indices, yet here is the code from event.js that stores the fired events:

    var eventPayload = args[0];

...

    eventsFired.push({
      eventType: eventString,
      args: eventPayload,
      id: key
    });

As the result "bid" in ga.js is undefined and sendBidRequestToGa function does nothing. If I change `bid = args[0];` to `bid = args;` it works like a charm.

**Comment by protonate** [comment]
PR #274 contains this fix, thanks for reporting the bug.

**Comment by protonate** [comment]
Reopening, will close with release of v0.8.0.

**Comment by protonate** [comment]
Released with [0.8.0](https://github.com/prebid/Prebid.js/releases/tag/0.8.0)
