### ISSUE TITLE
Consent management hook being called multiple times in requestBids test suite

### ISSUE THREAD

**Issue by snapwich** [prebid/Prebid.js#2707]
## Type of issue
bug

## Description
The consent management requestBids hook is not being properly cleaned up in the test suite.  In the process of writing some `requestBids` tests I was stepping through code in `test/spec/unit/pbjs_api_spec.js` and each of the `requestBids` calls were going through the consent management hook multiple times before `requestBids` was being ran.

It doesn't seem to cause any issues but it probably slows down our tests.  It could be an issue in the consent management spec or it could be an issue with the hooks removal function; haven't dug that far yet.

### Expected results
Stepping through any of the `$$PREBID_GLOBAL$$.requestBids()` calls in `test/spec/unit/pbjs_api_spec.js` calls the consent management hook either once or not at all.

### Actual results
Stepping through calls the consent management hook a lot of times before actually calling `requestBids`.

## Other information
@jsnellbaker

**Comment by jsnellbaker** [comment]
@snapwich I am calling the `$$PREBID_GLOBAL$$.requestBids.removeHook(requestBidsHook);` in the `afterEach` sections for the various unit tests in `consentManagement_spec.js` which I thought would clean up the hooks.

I'll take a look at this again.

**Comment by jsnellbaker** [comment]
Found the issue - there were other unit tests in the `prebidServerBidAdapter_spec.js` and `smartadserverBidAdapter_spec`that created a hook but didn't remove it.  I'll make a PR shortly to fix these tests.
