### ISSUE TITLE
AppnexusAST blacklist error when browsing from Europe

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#2712]
## Type of issue
AppnexusAST blacklist error when browsing from Europe

## Steps to reproduce
My prebid.js contains adapters for AppnexusAST and Sovrn. The error occurs whether or not I include the GDPR adapter in the prebid.js
If I set the Hola VPN to France, I get the error.
If I browse from the US, there is no such error.

## Test page
http://www.flixxy.com/appnexus-blacklist-error.htm?pbjs_debug=true

### Expected results
Should not get an error.  No bids are OK.
### Actual results
AppnexusAST blacklist error
## Platform details
Windows 10, Chrome

## Other information
Screenshot:
![image](https://user-images.githubusercontent.com/16692770/41240825-6c3e76f0-6d69-11e8-8351-747344a73b2f.png)

**Comment by mkendall07** [comment]
@headerbidding 
please open a ticket with AppNexus support for this issue. Thanks

**Comment by headerbidding** [comment]
i found out that appnexus blacklists hola
