### ISSUE TITLE
ConsentManagement should not install a __cmp function on window

### ISSUE THREAD

**Issue by mergut** [prebid/Prebid.js#2714]
## Type of issue
Bug

## Description
ConsentManagement module installs a `__cmp` function on global `window` when there is no implemented CMP on the page.
Then other code on the page relies on this function to get consent but the callback is never called.
Because the function installed by the module is tied to a particular Prebid instance and does not execute the callback passed as the last parameter.

## Steps to reproduce
Enable ConsentManagement module, run an auction then check `window.__cmp` value.

Run this on the console:
`window.__cmp("getConsentData", null, function () { console.log(arguments) })`

### Expected results
`window.__cmp` should be `undefined`.

### Actual results
`window.__cmp` is a function, but when called does not provide a response.

## Platform details
1.14.0

**Comment by jsnellbaker** [comment]
@mergut Thanks for reporting this issue; I'll take a look and address it.
