### ISSUE TITLE
Appnexus prebid server unsupported bidders

### ISSUE THREAD

**Issue by sgagnierH** [prebid/Prebid.js#2717]
## Type of issue
Bidders in this list return "unsupported bidder" to an auction
http://prebid.adnxs.com/pbs/v1/info/bidders

## Description

- indexExchange should probably be listed as ix on the prebid server
- openx is listed, but return unsupported bidder
- audienceNetwork is listed and works fine in prebid.js mode, but in server mode returns a 400 error
![unsupportedbidder](https://user-images.githubusercontent.com/19825599/41295013-72d42474-6e27-11e8-8331-d53b6cf822c8.JPG)

## Steps to reproduce
Just request a bid with those bidders with appnexus prebid server enabled.

### Expected results
Bids!

## Platform details
Prebid.js 1.13.0, AppNexus' prebid server

**Comment by dbemiller** [comment]
It looks like you're using `prebid.adnxs.com/pbs/v1/auction` as your endpoint. That's been unmaintained in Prebid Server for a long time... do you still see this issue if you use `prebid.adnxs.com/pbs/v1/openrtb2/auction`?

If so, could you post your `s2sconfig` and prebid.js ad units?

**Comment by sgagnierH** [comment]
You're right, I was not on /openrtb2/ link. Iswitched to it because ix was displaying errors actually. So back to it. Now, I can get openx bids.

if I include "ix" in the bidders, I get a 400 from prebid server. (Invalid request: request.imp[0].ext contains unknown bidder: ix. Did you forget an alias in request.ext.prebid.aliases?)

If I put indexEchange, it's simply ignored because the bids are sent to "ix", and according to docs from Index

audienceNetwork still sends a 400 on S2S but works great direct.

s2sConfig: {
              accountId: 'xx',
              bidders: ["appnexus","rubicon","openx","audienceNetwork"],
              defaultVendor: 'appnexus',
              enabled: true,
              timeout: 2000,
              adapter: 'prebidServer',
              endpoint: 'https://prebid.adnxs.com/pbs/v1/openrtb2/auction',
              syncEndpoint: 'https://prebid.adnxs.com/pbs/v1/cookie_sync',
              cookieSet: true,
              cookieSetUrl: 'https://acdn.adnxs.com/cookieset/cs.js',
},

for AdUnits, tried many different. Works like a charm on AppNexus, Rubicon, and all adapters in direct mode, so can't see what can be wrong in S2S.

Tried to add an alias for indexExchange to ix without success.

**Comment by mkendall07** [comment]
@sgagnierH 
Yeah looks like index renaming their bidder is going to cause us issues. I don't think changing the bidder name in PBS is a great idea since that would be a breaking change.
@dbemiller would the best thing to do here to put a alias into PBS for indexExchange in the Prebid.js PBS adapter?

**Comment by dbemiller** [comment]
probably, yeah :(. It's not really possible for Prebid Server to rename an adapter because that lives directly in the DB.

If Index is ok with it, it would be a bit cleaner to add `indexExchange` as an alias inside their adapter, rather than adding a special case to the PBS adapter.

I believe the PBS adapter forwards all those aliases in the request.

**Comment by bretg** [comment]
Interesting one. Is the alias in the PBJS adapter, PBS adapter, or both?

**Comment by chefbenjamin** [comment]
Last time i spoke with Index ( 3 weeks ago) they were not yet actually supporting the deployment of them via prebid server at this time. They will in the future but initial performance wasnt that great. Things might have changed tho...

**Comment by dmitriyshashkin** [comment]
So what's the current situation with this issue? What is the proposed solution
