### ISSUE TITLE
ga.js doesn't report timeouts

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#272]
Here is the code from ga.js:

    function sendBidTimeouts(bid) {

      if (bid && bid.bidder) {
        ... report timeout to GA 
      }

So basically, unless Bid has "bidder" property, nothing happens. Bidmanager.js has the following logic:

    // alias the bidderCode to bidder;
    // NOTE: this is to match documentation
    // on custom k-v targeting
    bid.bidder = bid.bidderCode;

Unfortunately the bid response event is fired a few lines earlier, so the bid object  passed to ga.js doesn't have the property. So the timeout is not reported to Google Analytics. Setting "bidder" property while reporting a bid response fixes he problem. But the documentation [here ](http://prebid.org/dev-docs/bidder-adaptor.html) doesn't mention this property at all.

**Comment by mkendall07** [comment]
@dmitriyshashkin 
Thanks for reporting the issue. The GA feature is a beta feature that we have not focussed on much. We'll investigate these issues and fix them. Thanks

**Comment by protonate** [comment]
PR #274 contains this fix, thanks for reporting the bug.

**Comment by mkendall07** [comment]
merged into master.

**Comment by protonate** [comment]
Reopening, will close with release of v0.8.0.

**Comment by protonate** [comment]
Released with [0.8.0](https://github.com/prebid/Prebid.js/releases/tag/0.8.0)
