### ISSUE TITLE
NPM & Dependencies

### ISSUE THREAD

**Issue by renebaudisch** [prebid/Prebid.js#2730]
## Type of issue
Feature Request

## Description
I'm using npm version of prebid but I do not use gulp or yargs normally, but since it's not included in dependencies of your package.json but in devDeps ist not installed when using npm i prebid.js.

## Steps to reproduce
Open a new project, 
npm i prebid.js
cd node_modules/prebid.js
use gulp as described in readme.md

## Test page
-

## Platform details
NPM

## Other information
I suggest either changing
`npm i prebid.js` to `npm i prebid.js --dev`
or adding gulp and yargs to package.json dependencies
and would do a PR if you tell me what's your fav.

**Comment by mkendall07** [comment]
yeah I agree we should probably move gulp to dependencies. Thanks for pointing it out.

**Comment by mkendall07** [comment]
@jsnellbaker 
Is this still applicable with gulp-cli ? My sense is yes but you're the expert here.

**Comment by jsnellbaker** [comment]
@mkendall07 I tested this out and it's still a problem even with the changes we implemented with `gulp 4` and `gulp-cli`.  

The `gulp-cli` is just the command-line interface for gulp.  We still need a 'local' version of `gulp` installed in the project folder in order to process/handle the commands.  However it's not inclusive to just the `gulp` package; it seems we'd need to include all the packages the prebid.js gulpfile imports (`lodash`, `gulp-util`, etc).  Otherwise it complains that it `Cannot find module 'xyz'` when you run any of the gulp commands.

**Comment by renebaudisch** [comment]
Hi, isn't it possible to solve this by using peer dependencies? => https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by jsnellbaker** [comment]
@renebaudisch Can you elaborate on how peer dependencies would help the situation?  I'm not sure I see the benefit here.

**Comment by renebaudisch** [comment]
@jsnellbaker I ain't so familiar with this peer dependency stuff but as far as I understood this type exists to install modules mandatory for other included modules. So if I install prebid.js as modul and there are peer dependencies these packages get's installed also, but I'm not sure I understood correctly. I would do a PR if I would be sure about that :)

**Comment by jsnellbaker** [comment]
Hi @renebaudisch 

Sorry for the delay here.  From my understanding - peer dependency is mainly used to ensure that the needed packages (eg gulp) are at the same version level as used in your main project.  If you main project needed gulp 3.9.1 and Prebid.js needed gulp 4 as a peer dependency - when the install process happens, it'll try to check/enforce the same version and (in this case) it'll complain saying they're incompatible.  

It's different from marking as a normal dependency where NPM would just install a dedicated version of `gulp` just for `Prebid.js`, regardless of the version the base project may potentially use.

In general terms though, these packages don't really need to be exposed like this for everyday use when you're treating `Prebid.js` as a dependent package for another project.  If you're planning to make your own build of Prebid.js or interact with it as if you were developing it, what you can do is navigate to the sub-folder where it was installed by NPM for your project and run the `npm install` there.  If you're in the main folder for Prebid.js, NPM will automatically install all the `devDependencies` packages which will give you the framework to interact with the Prebid.js project as needed.

**Comment by renebaudisch** [comment]
OK, that's what i'm doing, I just hoped there would be a nicer way to include producing prebid.js while generating the main project.
