### ISSUE TITLE
Komoona Random Creative ID

### ISSUE THREAD

**Issue by smartbidder1** [prebid/Prebid.js#2746]
## Type of issue
bug

## Description
when requesting an ad from Komoona bidder the response doesn't contain a unique creative ID.
it looks like a random generated session ID rather then a unique ad ID.
there is a high importance of relaying on accurate creative id's for blacklists and debugging & reporting of bad ads.

I can see that most of your ads are coming from Pubmatic, and they *do* give a unique ad ID when you sends an OPENRTB request to their endpoint that looks like this: "crid":"cr-9cpx2d3y2arfv8"
so please forward this third-party ID when you encounter one. 

https://github.com/prebid/Prebid.js/issues/2374 for example had the same issue but they have fixed it already (very fast I might say).

@tzafrirb @itayo155

**Comment by smartbidder1** [comment]
@mkendall07 who is in charge on Komoona bidder?

**Comment by tzafrirb** [comment]
Hi, we are looking into and we will fix  it on our side 

Best
Tzafrir

**Comment by smartbidder1** [comment]
Thank you @tzafrirb Tzafrir,
any time-frame for this change?

**Comment by smartbidder1** [comment]
any update? @tzafrirb

**Comment by IsraeliAdblocker** [comment]
@tzafrirb  @itayo155 waiting for more than two months now.

**Comment by smartbidder1** [comment]
@tzafrirb  @itayo155  waiting for more than two months now.

**Comment by mkendall07** [comment]
I'm closing since it doesn't benefit anyone from sitting in the github issue queue and the prebid core team is unable to do anything to fix it. 

@smartbidder1  feel free to open an issue directly with Komoona
