### ISSUE TITLE
can u please check why its always blink ?

### ISSUE THREAD

**Issue by alimehdipak** [prebid/Prebid.js#275]
can u please check why its always blink ?

http://feedgag.com/tests.html

**Comment by chrishepner** [comment]
`/assets/js/pbjs-event-logger.js` doesn't exist and the prebid.js library isn't being loaded.

**Comment by alimehdipak** [comment]
Hi @chrishepner  Thanks for your Reply , 
i have added pbjs-event-logger.js loader , 
and what do you mens Prebid,js library isnt being loaded ?
i need to ads these files in my server ?
![screenshot_29](https://cloud.githubusercontent.com/assets/518852/14101686/6568ad16-f5af-11e5-8bd6-aff2ed2113b9.jpg)

**Comment by mkendall07** [comment]
@alimehdipak 

I just checked the page and see an ad - can you verify this issue is resolved?

**Comment by protonate** [comment]
This appears to be resolved, closing, reopen if you still have questions.
