### ISSUE TITLE
Prebid Server http/https question

### ISSUE THREAD

**Issue by dbemiller** [prebid/Prebid.js#2750]
This issue was recently opened in Prebid Server: https://github.com/prebid/prebid-server/issues/569

I introduced a pull request to fix it: https://github.com/prebid/prebid-server/pull/572

See these two comments by @bretg:
- https://github.com/prebid/prebid-server/pull/572#issuecomment-398868625
- https://github.com/prebid/prebid-server/pull/572#issuecomment-398875441

The requirements are:

- Insecure page, insecure ad iframe: allow `http` ads
- Insecure page but secure ad iframe: require `https` ads
- Secure page, secure ad iframe: require `https` ads
- Secure page but insecure ad iframe: shouldn't happen, but require `https` ads

In Prebid.js, endpoints for PBS vendors look like this:

```
 'appnexus': {
    ...
    endpoint: '//prebid.adnxs.com/pbs/v1/openrtb2/auction',
    ...
  },
```

In Prebid Server, we will allow `http` ads if the request we get uses `http`, and require `https` ads if the request we get uses `https`.

My question is: does that make the right request . type (`http` or `https`) under the conditions that @bretg described?

If not, consider this a feature request to fix it :). You can do this by either:

1. Making the call use `http` or `https` in those circumstances.
2. Explicitly setting `imp[i].secure` to `1` to require `https` ads, and `0` to allow `http` ads.

(2) is much more robust (less prone to proxies that ruin things)... but both should work.

**Comment by mkendall07** [comment]
The only scenario we cannot support currently would be: `Insecure page but secure ad iframe: require https ads` 
Is that really required though?

**Comment by dbemiller** [comment]
> Is that really required though?

From me, no :). I'm just relaying what @bretg said in PR comments, because they weren't really things which it's possible to address server-side.

He did say that it was a real edge case that they ran into last year which broke pages, though. So... will leave it to you all to prioritize.
