### ISSUE TITLE
Load prebid and GPT libraries in parallel

### ISSUE THREAD

**Issue by BartVB** [prebid/Prebid.js#276]
When implementing prebid.org I didn't like the fact that GPT was only loaded after all the bids were back. This resulted in a browser that was idly waiting for bid responses while it could be loading and parsing the GPT libraries.

It was fairly trivial to change this behaviour. I changed this example:
http://prebid.org/dev-docs/examples/basic-example.html

to what I have been using for a couple of months now:
http://jsfiddle.net/48pLvsqw/1/

The main changes:
- Add `googletag.pubads().disableInitialLoad();` before `googletag.enableServices();`
- Remove loading GPT from `initAdserver()`
- Call `googletag.pubads().refresh();` in `initAdserver()`

This has been working flawlessly for me and this results in a rather nice speed boost because loading, parsing and running GPT takes quite a bit of time.

**Comment by mkendall07** [comment]
@BartVB 
We've been looking into this ourselves and trying to solve. Looks like we missed `googletag.pubads().disableInitialLoad(); `. Thanks so much for pointing it out! We'll be working on updating our examples!

**Comment by pdramos1** [comment]
+1 here for seeing the solution. We are looking at this as well from our end at sovrn. Excited to see the end result.

**Comment by mkendall07** [comment]
There is a PR for this. Should be merged today > https://github.com/prebid/Prebid.js/pull/288

**Comment by pdramos1** [comment]
just saw that!

**Comment by protonate** [comment]
Released with [0.8.0](https://github.com/prebid/Prebid.js/releases/tag/0.8.0)
