### ISSUE TITLE
Yieldbot adapter server call failed

### ISSUE THREAD

**Issue by RajasekarPR** [prebid/Prebid.js#2768]
Recently I have upgraded the Prebid to 1.15.0 version.

Got the below error in console. Don't know why is it .

![capture](https://user-images.githubusercontent.com/39621436/41856659-480d7862-78b3-11e8-96fd-71aca1554760.PNG)

Kindly do the needful. Is this error occurs because it is not supported by the prebid server ?

**Comment by mercuryyy** [comment]
Looks like a safe frames issues you using safe frames in dfp creative settings?
 
to your question yieldbot is not in prebid server or s2s adapter.

**Comment by RajasekarPR** [comment]
Without using prebid server adapter, it works fine. But after adding the prebid server adapter in the latest version, it throws this error.

I have not included the yieldbot in s2s config, since it is currently not supported by the Prebid Server.

Only for the yieldbot it throws the error.

**Comment by mercuryyy** [comment]
We also use prebidServer adapter and yieldbot on client side but i cant reproduce your error from yieldbot

**Comment by dbemiller** [comment]
Looks a bit like a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) error.

**Comment by RajasekarPR** [comment]
This error occurs only from the localhost. In further environments it's working fine. Thanks for your information @mercuryyy @dbemiller . :)

**Comment by RajasekarPR** [comment]
Getting this error sometimes in higher environments too. Kindly do the needful.
