### ISSUE TITLE
IndexExchange - Small Issue

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#277]
Updated to latest version of the indexExchange adapter manually.

When using sandbox, the bid returns as height 0 and width 0 even though the CPM is $10. (process as described here: http://wiki.headertag.com/2016/01/11/how-mediation-works-with-prebid/)

It is now working correctly, but it would be nice to see the advert rendering...

```
ad:"<a target='_blank' href='http://www.indexexchange.com'><div style='width: 728px; height:90px;background-color: #de496e;'><h1>&lt;header_tag&gt; certification testing: 1_1000 (1459266033)<iframe style='display:block; visibility:hidden; width: 0px; height: 0px;' src='http://as.casalemedia.com/ifnotify?dfp_1_1000'></iframe></h1></div></a>"
adId:"3f2fc209963e4f"
bidder:"indexExchange"
..
cpm:10
height:0
width:0
..
```

**Comment by mkendall07** [comment]
@cwbeck 
I'm not seeing this issue. Configuration is:
 ```{
  bidder: 'indexExchange',
  params: {
    id: "1",
    siteID: 999990
   }
 },```
![image](https://cloud.githubusercontent.com/assets/1870166/14187161/a9732e68-f74f-11e5-9a0a-c02e16d03684.png)

**Comment by cwbeck** [comment]
@mkendall07 curious. I'll pull the latest adapter in from your master and test again - hopefully later today.

**Comment by cwbeck** [comment]
@mkendall07 - we still have the same issue.

![screen shot 2016-04-04 at 13 56 09](https://cloud.githubusercontent.com/assets/425262/14248560/1b9ac71a-fa6d-11e5-8df4-f29c23112ad8.png)

We have a slightly custom setup with regards to rendering ad units. We overlay additional information for our adops team (quick debug) and sandbox the prebid code in a friendly iframe to avoid global namespace pollution. We are live with Adform, Appnexus, Rubicon, AOL, Sovrn, Pulse Point and a few others with no issues.

Here is our tag (post render) size is 0x0 as this is what you have told using the in the bid response.

![screen shot 2016-04-04 at 13 58 44](https://cloud.githubusercontent.com/assets/425262/14248707/ea02a71c-fa6d-11e5-8cd5-d1f97f502edf.png)

My guess is this is somehow due to iframe issues.

Here are the requests:

![screen shot 2016-04-04 at 14 04 53](https://cloud.githubusercontent.com/assets/425262/14248849/a3ac4a60-fa6e-11e5-908c-ecc49067ecbc.png)

![screen shot 2016-04-04 at 14 05 51](https://cloud.githubusercontent.com/assets/425262/14248854/aafd7122-fa6e-11e5-824f-2fc8f3197dee.png)

Response:

```
...
index_slot_to_size = {}, index_slots_render = [], index_slots_add = [];
var cygnus_tid = 4,
    OPEN_MARKET = "IOM",
    PRIVATE_MARKET = "IPM";
cygnus_index_parse_res({
    "seatbid": [{
        "bid": [{
            "adomain": ["58371"],
            "adid": "1487603",
            "impid": "1",
            "id": "1",
            "ext": {
                "pricelevel": "_1000",
                "dspid": "46",
                "advbrandid": "25661",
                "advbrand": "LA Tourism & Convention Board"
            },
            "adm": "<a target='_blank' href='http://www.indexexchange.com'><div style='width: 728px; height:90px;background-color: #de496e;'><h1>&lt;header_tag&gt; certification testing: 1_1000, siteID: 999990 (1459774314)<iframe style='display:block; visibility:hidden; width: 0px; height: 0px;' src='http://as.casalemedia.com/ifnotify?dfp_1_999990_1000'></iframe></h1></div></a>"
        }],
        "seat": "2439"
    }],
    "cur": "USD",
    "id": "361718412"
});
0
```

**Comment by cwbeck** [comment]
This has been fixed as of latest: https://raw.githubusercontent.com/indexexchange/Prebid.js/master/src/adapters/indexExchange.js
