### ISSUE TITLE
Pricing Granularity Change

### ISSUE THREAD

**Issue by scottalan** [prebid/Prebid.js#2770]
## Type of issue
Question

## Description
I'm working on a module here https://github.com/heshanlk/prebidjs that integrates with a the [DFP](https://www.drupal.org/project/dfp) module's [7.x-2.x](https://cgit.drupalcode.org/dfp/tree/?h=7.x-2.x) branch in Drupal. I may need to account for differences based on the [prebidjs](http://prebid.org/download.html) library versions. I've been reading through the [releases](https://github.com/prebid/Prebid.js/releases). 

Could you please tell me what version the "old" Pricing Granularity changed from `auto, low, medium, high, dense` to the newer pricing structure?

- Precision
- Minimum
- Maximum
- Increment

I was wondering if this was as simple as library version < 1.0.0, for example.

Thanks

**Comment by mkendall07** [comment]
Both are currently supported.

**Comment by mkendall07** [comment]
Here is the docs: 
http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-Price-Granularity
```
pbjs.setConfig({ priceGranularity: "medium" })
```
etc

**Comment by scottalan** [comment]
@mkendall07 Thanks for the prompt response.
