### ISSUE TITLE
Google Analytics not logging timed out bidder code

### ISSUE THREAD

**Issue by YOzaz** [prebid/Prebid.js#2771]
## Type of issue
Bug

## Description
Google Analytics adapter not logging in bidder name / code for timed out events. Other events are working fine.

## Steps to reproduce
Compile Prebid.js with GA adapter included, and inspect events logged - event label will be empty for Timeout.
My guess would be either missing eventValue mixing things up: https://github.com/prebid/Prebid.js/blob/master/modules/googleAnalyticsAdapter.js#L239, or something is wrong with filtering here: https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L618

## Test page
See here: https://www.mummypages.co.uk/?pbjs_debug=true, inspect Network tab, filter with "Timeouts" keyword.

### Expected results
Event label contains bidder code.

### Actual results
Event label is empty.

## Platform details
Prebid.js 1.15.0, Chrome.

## Other information
(none)

**Comment by snapwich** [comment]
This was most likely fixed with: https://github.com/prebid/Prebid.js/pull/2741

**Comment by YOzaz** [comment]
Yes, sorry - didn't pay attention this was not included in 1.15.0. Thanks.
