### ISSUE TITLE
Rubicon always bids 0 + Error: http://ads.rubiconproject.com/header/undefined.js

### ISSUE THREAD

**Issue by minarini** [prebid/Prebid.js#278]
Hi guys, 
I've been trying to implement rubicon as a bidder  (here: http://guitadigital.com/larissa/?pbjs_debug=true)... already have all the params, but there are 2 problems:

a) When I pointed the pbs.src to my prebid.js  (http://guitadigital.com/larissa/wp-content/uploads/2016/03/prebid.js) the prebid console shows an error in the file "http://ads.rubiconproject.com/header/undefined.js" which I have no idea how to solve.

b) When I use another prebid.js instead (http://sport.ba/theme/Sport/te/prebid.js, for example), there isn't any errors, but rubicon always returns a bid value of 0.

Anyone knows if there's anything else that I've to do? :/ 

Thanks

**Comment by mkendall07** [comment]
Hi @minarini 
It looks like your using the Rubicon paramaters that are outdated. Please see this page (search for Rubicon) http://prebid.org/dev-docs/bidders.html.

You need to use `accountId`, `siteId`, and `zoneId`

**Comment by minarini** [comment]
@mkendall07 Thank you for the tip :)
but even though I have changed the parameters, the rubicon object isn't even being created. 
Plus, the problem in the file http://ads.rubiconproject.com/header/undefined.js continues. :/

**Comment by mkendall07** [comment]
@minarini 
The request is going out to `http://ads.rubiconproject.com/header/11554.js` - which is returning 404. You need to contact Rubicon to enable header bidding on your account. That should resolve the issue.
