### ISSUE TITLE
Number of user syncs exceeded for sharethrough

### ISSUE THREAD

**Issue by YOzaz** [prebid/Prebid.js#2781]
## Type of issue
Not sure.

## Description
At the moment, `userSync` module defaults to 5 syncsPerBidder: http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-ConfigureUserSyncing-UserSyncProperties. However, even with a standard Sharethrough configuration and default networks enabled, there are at least 15 cookie sync URLs returned, especially if consent is gathered for all of them.
Not sure which side should fix it - is it Sharethrough who'd have to consolidate sync into one request (if that's possible at all), or we should change default userSync value to something like 50.
We've observed same issue for TripleLift adapter as well.
By the way, "0" (zero) value should allow all syncs to go through, but it's not working - still doesn't go through this line: https://github.com/prebid/Prebid.js/blob/master/src/userSync.js#L155.

## Steps to reproduce

**Sample call**
![image](https://user-images.githubusercontent.com/5859318/41992035-0e65938a-7a50-11e8-872c-8298c9a24695.png)

**Sample response**
![image](https://user-images.githubusercontent.com/5859318/41992055-1d154bdc-7a50-11e8-80ad-49e3d3ba2093.png)

## Test page
https://www.mummypages.co.uk/husband-learns-how-to-apply-make-up-after-his-wife-loses-sight?pbjs_debug=true&gdpr_debug=true&pbjs_table=true
(check on mobile emulator)

### Expected results
User syncs should be allowed for default configuration.

### Actual results
Some user syncs are blocked.

## Platform details
Prebid.js (1.16.0-pre), Consent module, Sharethrough adapter, default networks enabled, Chrome mobile emulator (iPhone 6/7/8).

**Comment by ConcourseMedia** [comment]
This issue is still occurring and is partially responsible for some lost bids on sharethrough.

**Comment by YOzaz** [comment]
@ConcourseMedia try increasing amount of userSyncs temporary. But yes, it is still actual.

**Comment by YOzaz** [comment]
@ConcourseMedia well it worked in our case.
Setting it to 0 (zero) doesn't work - I've inspected pbjs code, and this check has been removed in 1.x.
But setting it to something like 999 should do the trick. Check if you're using syntax correctly:
```js
pbjs.setConfig({
   userSync: {
      syncsPerBidder: 999
   }
});
```

**Comment by bjorn-lw** [comment]
This one just came and bit me. Can the documentation please be updated so that it doesn't state that zero allows unlimited number of user syncs?

**Comment by jsnellbaker** [comment]
Thanks all for commenting on this issue.  At the moment, I would suggest to do what @YOzaz recommended and set a higher value for the `syncsPerBidder` field if you find there is a large number of pixels to sync for a particular bidder.  

I did verify the `0` value for the field isn't working and we'll look to fix this bug.  I'm not sure how soon it'll be addressed; I'll update this issue when a fix is ready.  

As an additional note - we're planning to make some changes in the 2.0 API for userSyncs to hopefully make things more clear.  I don't have any definite details to share yet, but wanted to mention it as a heads up.
