### ISSUE TITLE
Adding video to media types causes s2s to not bid for banner ad types

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#2798]
If setting up for example

ad unit 1 = 728x90  media type "banner"
ad unit 2 = 300x250  media type "banner, video"

When using openRTB with s2s adapter what will happen bidders on s2s that support video will bid for both ad units.
bidders on s2s who support only banner type will only return bids for ad unit 1 even tho ad unit 2 is set to multi format. 
bidders on client side will all work fine.

PB 1.15

**Comment by mercuryyy** [comment]
Any Information on this?
@dbemiller I saw you merged some fixes to PBS i assume they are live on appnexus endpoint? if you run the digitest.php URL i send you that did not fix the problem

**Comment by dbemiller** [comment]
Not live. This is the relevant PR: https://github.com/prebid/prebid-server/pull/604

To be clear, I don't think that will solve your problem on its own. It's a tangential bug that I discovered while looking at your page.
