### ISSUE TITLE
RequireJS requirement

### ISSUE THREAD

**Issue by acookcpxi** [prebid/Prebid.js#28]
We're having issues attempting to implement on a site that does not already have RequireJS implemented - could the integration example file be updated to include RequireJS and exaplin for people who do not use it regularly how to implement? As it is now our site breaks when we follow the integration example that is posted...

**Comment by ialex** [comment]
Can you share your code on how you are trying to implemment it?

**Comment by Heray** [comment]
Hey @acookcpxi, if you're trying to implement prebid.js, see the latest release as a good place to start:
https://github.com/prebid/Prebid.js/releases

If you're trying to contribute to the repo, I think `require()` is part of the Gulp tool when you're building the Javascript. In the final prebid.js, there would be no `require()` call.

@mkendall07, could you also help out here?

**Comment by mkendall07** [comment]
Hi @acookcpxi,

We actually don't use `requireJS` in this project at all. `Browserify` (http://browserify.org) is used to build all the modules and bundle one prebid.js file. Consuming this file should not require any additional dependencies. If you post a link to your code I'd be happy to point out more.

**Comment by acookcpxi** [comment]
Thanks, I hadn’t done the gulp step as I was just including the file that was downloaded from GIT…

From: mkendall
Reply-To: "prebid/Prebid.js"
Date: Wednesday, August 19, 2015 at 4:52 PM
To: "prebid/Prebid.js"
Cc: Alex Cook
Subject: Re: [Prebid.js] RequireJS requirement (#28)


Hi @acookcpxi<https://github.com/acookcpxi>,

We actually don't use requireJS in this project at all. Browserify (http://browserify.org) is used to build all the modules and bundle one prebid.js file. Consuming this file should not require any additional dependencies. If you post a link to your code I'd be happy to point out more.
