### ISSUE TITLE
How to get google CPM in realtime - Prebid

### ISSUE THREAD

**Issue by Delashmate84** [prebid/Prebid.js#2800]
We are using DFP and prebid,

Incase google win the auction - can I know in the browser what was the bid of google that won the auction?

I am trying to figure in google analytics exactly how much revenue I got for each dimension in my site.. (since in DFP I can't have multiple key-value reporting..)

Thanks!

**Comment by paweljw** [comment]
The rule of thumb is "what happens at Google, stays at Google". Google makes their decisions after the auctions are done and does not return anything to indicate its price if it decides to buy the impressions. I believe there's no way to do what you want :(

**Comment by GLStephen** [comment]
There are significant limitations on Google data in terms of real-time availability.  You can get bidlandscape data, but not when it is associated with very many other dimensions and it is delayed 36-48 hours. Using it for impression by impression data is not really feasible, though it's possible to get other insights across the inventory.
