### ISSUE TITLE
ANOutstreamVideo.js + [All Renderers] Is being downloaded from bid Request even if bid isn't won or renderAd fired

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#2805]
http://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js

Is the Video renderer for appnexus bids, other renderers from others bidders will probably behave the same.

When bids are requested from bidders, the renderer .js file will be downloaded to the client browser even if the video bids is not the highest cpm or the renderAd been fired from the dfp creative.

Those renderer's files are usually very large in appnexus case 167kb no reason to download this file if the video bid is not the winning bid or more so if renderAd has not been called.

Another note, even if we set our own renderer file in the adunit config it will still download the bidders renderer when the bid is requested.

**Comment by lanceloti** [comment]
I'm using a proprietary Outstream Player and ANOutstreamVideo.js is downloaded sometimes too.

**Comment by mkendall07** [comment]
@mercuryyy 
Thanks for the report. Do you have test page handy?

**Comment by mkendall07** [comment]
@lanceloti 
Got a test page I could look at?

**Comment by lanceloti** [comment]
Sorry from delay: http://maringa.odiario.com/ads/adplayer-instream.php?pbjs_debug=true

**Comment by bwoolcott** [comment]
@mkendall07 is this still an issue?

**Comment by lanceloti** [comment]
Hello guys.

It still an issue to me. See this test page: https://maringa.odiario.com/ads/outstream.php

1) Even I setting other render URL ANOutstreamVideo.js is downloaded first.

2) Render funcion is called before complete download of our player, so I need to set a timeout until script is ready.
