### ISSUE TITLE
Prebid is not updating window.pbjs on requesting new bids for adunitcodes

### ISSUE THREAD

**Issue by nikhil-gujarathi** [prebid/Prebid.js#2810]
Hi Guys,

Currently we are using prebid (1.15.0) for Appnexus and in that I am facing one issue, where prebid is not updating the window variable pbjs on requesting new bids for a particular adunit code.

Scenario:
1. First, call prebid for three adunits ('a','b','c'), after receiving the bids do not call pbjs.renderAd for any adunits.
2. Then, call pbjs.requestBids for one adunit say 'a'. After receiving the bids we can see new bids in response. But, when we pbjs.getAdserverTargetingForAdUnitCode('a'), then we will see the bids which we received in the first call.

Before using 1.15.0, we were on 0.31 and in that we don't have this issue.

Can I please get some guidance how I can implement this? I just wanted to know which bid values I can send to DFP?

Note: Due to some business requirements, I can't use pbjs.setTargetingForGPTAsync() to set the bid values to DFP params.

**Comment by andyblackwell** [comment]
I believe if the cpm is the same it uses the older bid, as long as it hasn't been used yet and the bid hasn't expired (bid TTL)

**Comment by jaiminpanchal27** [comment]
@nikhil-gujarathi Does that answer your question ?
