### ISSUE TITLE
Gumgum Creative ID issue

### ISSUE THREAD

**Issue by smartbidder1** [prebid/Prebid.js#2820]
## Type of issue
bug

## Description
when requesting an ad from Gumgum bidder the response doesn't contain a unique creative ID, the same ID is shared among multiple ads.
there is a high importance of relaying on accurate creative id's for blacklists and debugging & reporting of bad ads.

I can see that most of your ads are coming from Appnexus, and they *do* give a unique ad ID when you sends an OPENRTB request to their endpoint, you just need to pass it along.

An example can be see in this response:
```{"ad":{"id":24874,"width":728,"height":90,"ipd":1900,"markup":"<div style=\"_CLEARCSS_;position:relative;width:728px;height:90px;margin:0 auto\">\n \t<!--[iframe]-->\n<script src=\"http://sin1-ib.adnxs.com/ab?e=wqT_3QKfCPQ0AR8EAAADANYABQEIq9f32QUQxqOckYCVkJRsGKmen8OI1brPcSo2CTLO34RCxPA_Ed9TOe0peec_GQAAAGC4HgdAIRSWeEDZFOo_KcWPMXctofI_MQAAAIA9Cvc_MKiCvQY4lg9AzAVIAlDP3KgyWPDLXmAAaJPNeHii9QSAAQGKAQNVU0SSAQNVU0SYAdgFoAFaqAEBsAEAuAECwAEFyAEC0AEJ2AEA4AEA8AEAigKTAXVmKCdhJywgMjYxNjgxMywgMTUzMDc4NDY4Myk7dWYoJ3InLCAxMDU1MjQ4MTUsIDE1MzA3ODQ2ODMpO3VmKCdjJywgMjMyMzE4NTEsIDE1MzA3ODQ2ODMpO3VmKCdnJywgNjE0MTM2NiwgMTUzMDc4NDY4Myk7dWYoJ2knLCA4NDg2MzocAPDAkgKJAiFXei03bndqci1va0xFTV9jcURJWUFDRHd5MTR3QURnQVFBQkl6QVZRcUlLOUJsZ0FZTmtDYUFCd0FuZ0dnQUVFaUFFR2tBRUJtQUVCb0FFQnFBRURzQUVBdVFHckQ2Q1ZnekhzUDhFQngzOV94aktoOGpfSkFhNFgycTJDTWV3XzJRRm1NYkg1dURib1AtQUJfT1V6OVFFQUFBQUFnQUlBaUFMc29Za0drQUlCbUFJQW9BSUFxQUlCdFFJQQEkAHYNCKh3QUlBeUFJQTBBSUUyQUlHNEFJQTZBSUEtQUlBZ0FNQmtBTUFtQU1CcUFQBexkdWdNSlUwbE9NVG96TlRZepoCLSEtUWt2dFE2DAEoOE10ZUlBQW9BRG8yMAD0PAHYArYG4AK2twrqAosBaHR0cDovL3d3dy5kYWlseS1jaG9pY2VzLmNvbS9wZXJmZWN0bHktdGltZWQtcGhvdG9zLXRha2VuLXJpZ2h0LWJlZm9yZS1kaXNhc3Rlci8_dXRtX3NvdXJjZT11cG9uaXQmc2Vzc2lvbl9zZXR1cD1kZXNrdG9wX2RlZmF1bHRfb2tvX3Vwb25pdIADAIgDAZADAJgDFKADAaoDAMADrALIAwDYA7_MkwHgAwDoAwD4AwOABACSBAkvb3BlbnJ0YjKYBACiBA02OC4xMTkuNjMuMjEwqAS6LLIEDAgAEAAYACAAMAA4ALgEAMAEAMgEANIEDTcxNiNTSU4xOjM1NjPaBAIIAeAEAPAEz9yoMvoEEgkAAACgiQhAQBEAAABAI2JBQIgFAZgFAKAF_____wUEuAGqBSQyZWViZjAxZC1jMTdkLTRlOGEtODk1MS0yYTU0ZmQzODZkODTABQDJBQAAAQIU8D_SBQkJAQoBAWjYBQHgBQHwBYaaEvoFBAgAEACQBgCYBgC4BgA.&s=b820f66b11d7d970d48a6f38c2cad558976b6e30&referrer=http%3A%2F%2Fwww.test.com&pp=0.73354\"></script>\n\t    <!--[/iframe]-->\n</div>","ii":true,"du":null,"price":0.5134779989719391,"impurl":"http://jp-g2.gumgum.com/ad/view/enc/k9ExIYRDenC7Msg_6UKfiJXq6D3VPw03TLItR077mwKP0o3kqloIh0ssgCZPqcBm0cuktwLEvBRN-AY6LcukY-z5iCDYVmwJ8z2X7Hw7cftJcPM4SN1bCRtOmwuQKFLMxi40Fl8JHufvYlLyGcMmBR0Ty4ObeRU2FUP4rCRPZeCy5mCr7IzmulgPJVdOWqDpPG6lbCbHswRT-vMyi34i4QpNj-UjJ-tTJ8sscwX9Ge7uhuI4UVQtUm1V8aPq92hAx18keAthTeHb9VZDVL9xzQa4y0Jc_e1ajdkt8SXVBd-e_JAX2s_WaYQ2xBXlsBRYkEdni0_cKaKbnOsIPiG49EdUsWB_BELFuvOxxNdgdmx2Rn6XEQchbNa_5L7v9xHdBTHfkd_qvxc8qc-GS8H1f5eziDU88g-WZKfRKygF95FVa-Q5lNbiIkX5kfybII4uWUFkKEUy1pSaXMuq7A1gDud99TWNCBhic4ZTJ1RnM_-j5bdh9EK7QTaqPQy1xdEFCEbq_ncBko6ekpHFsWKULZKb9GSLMOFEv_ht9WdQKxwjspZnJHnuUioJTyug9Shy?c=0.51347799897193912000","v50url":"http://jp-g2.gumgum.com/ad/viewable50/enc/HGFDEcn7CPiKfhofBtvRGUUfdO38URZSx8cXe8OMFZu-UvfOTE0j1ULH-WZ4PWV6odY6N5z_OiThRw_-pyPPkFm6x9hhDyCzA96SOmTki9GbRumjaAeVTwo9Ai_fSjKj9Xkj2Unhq7ymyKIH26yWveJK82WqZurswbtM8H6Df_1xyepzuT_J_p62epaIr9RiyaojH9bwa3fCla79CQOZyjw-NnuH_fUd0uBF79792h8OZgAjdVIfO4oZhcJyqwp1AEFIAP19A8HJuF6nWJ_VYw9CDKJwqmZZxXKQruNY8p9Wf7ydBiiwqoLiVKTb_spsVEB6tOsJDpRWFAKUOA_FOJDpucW2dEcUUj-Mm9K_JeFwCYnxBGY1TTrvOAdLwe8iKmvY6kvmNl8","v100url":"http://jp-g2.gumgum.com/ad/viewable100/enc/HGFDEcn7CPiKfhofBtvRGUUfdO38URZSx8cXe8OMFZu-UvfOTE0j1ULH-WZ4PWV6odY6N5z_OiThRw_-pyPPkFm6x9hhDyCzA96SOmTki9GbRumjaAeVTwo9Ai_fSjKj9Xkj2Unhq7ymyKIH26yWveJK82WqZurswbtM8H6Df_1xyepzuT_J_p62epaIr9RiyaojH9bwa3fCla79CQOZyjw-NnuH_fUd0uBF79792h8OZgAjdVIfO4oZhcJyqwp1AEFIAP19A8HJuF6nWJ_VYw9CDKJwqmZZxXKQruNY8p9Wf7ydBiiwqoLiVKTb_spsVEB6tOsJDpRWFAKUOA_FOJDpucW2dEcUUj-Mm9K_JeFwCYnxBGY1TTrvOAdLwe8iKmvY6kvmNl8","clsurl":"http://jp-g2.gumgum.com/ad/close?si=10302&ga=true&spi=1&t=acpsnezf&ab=24874&pv=&pu=http%3A%2F%2Fwww.test.com&lt=&to=&ts=1530784681128&er=0.7335399985313416"},"pxs":{},"pag":{"t":"acpsnezf"},"thms":10000,"cw":"<img src=\"//c.gumgum.com/px.gif?1530784681128\" onload=\"(function(a,b){b.src='//js.gumgum.com/gumgum.js',a.parentNode.replaceChild(b,a)})(this,document.createElement('script'))\"><gumgum-ad product=\"3\" fromAS='AD_JSON'></gumgum-ad>","bidRequest":{"id":"317845c3e793037","tmax":3000,"tId":"4d618179-afa4-435a-aad3-8735815b0400","pi":3,"sizes":[[728,90],[728,90],[728,250],[728,169]],"url":"https://g2.gumgum.com/hbid/imp","method":"GET","data":{"si":10302,"pi":3,"gdprApplies":true,"gdprConsent":null,"vw":1910,"vh":300,"sw":1920,"sh":1080,"pu":"http://www.test.com","ce":true,"dpr":1}}}```

the given creative ID was 24874 (which is shared among multiple other creatives) when in fact the creative ID came from Appnexus and it was 105524815.

https://github.com/prebid/Prebid.js/issues/2374 for example had the same issue but they have fixed it already (very fast I might say).

@jaiminpanchal27 @mxcoder @davidmh

**Comment by mxcoder** [comment]
Thanks, we're looking into the issue.

**Comment by smartbidder1** [comment]
Any update? @mxcoder

**Comment by mxcoder** [comment]
We're almost ready to ship the fix for this on our AdServer. I'll ping you here when it should be out.

**Comment by mxcoder** [comment]
Hi @smartbidder1 , our team has told me that this is in production now, you should be seeing the original creative ID in the response now. Can you check?

**Comment by smartbidder1** [comment]
Are you referring to the ad.id in the json response struct? if so, yes I can see that.

**Comment by mxcoder** [comment]
@smartbidder1 

This ID comes directly from the Bidder system, which is why we cannot guarantee its uniqueness, but it should be a unique id per creative.
