### ISSUE TITLE
Fail fast in debug mode

### ISSUE THREAD

**Issue by dbemiller** [prebid/Prebid.js#2827]
## Type of issue

Feature request

## Motivation

This morning, I spent about a few hours debugging some PBS issues through a publisher's page. One thing which slowed the debugging process was that one of the test pages defined two `adUnit` objects with the same `code`. The Prebid ecosystem _generally_ worked ok this way, but it did cause some bugs as well.

## Observations

Fail-fast behavior makes debugging faster. If Prebid.js threw an error that said something like "two ad units have the same code, which is not legal", it would have saved us a ton of time.

The louder the failure, the easier it is to catch notice problems. For example, a `console.error` message is helpful, but it would be harder to miss if no ads showed up on the page.

At the same time, there's some performance cost to validating input like this.

## Proposal

Make Prebid.js throw an error and refuse to run the auction on bad inputs, but only in debug mode.

(this doesn't have to be done all at once... stricter validation could be added one case at a time. The more strictly you validate, and the better the error messages, the easier it'll be to debug prebid stuff).

**Comment by GLStephen** [comment]
@dbemiller it might be good to introduce a &pbjs_validate=1 type of parameter. This way debug is kept as debug mode and a stricter validation can be toggled.

**Comment by dbemiller** [comment]
Yeah, that's totally reasonable too.
