### ISSUE TITLE
Rubicon requests sizes which should be filtered by media query

### ISSUE THREAD

**Issue by drdmitry** [prebid/Prebid.js#2843]
## Type of issue

Bug

## Description

When using Media queries withing configuration, Prebid is filtering the bid.sizes based on the matched media query, but not filtering MediaTypes.banner.sizes.
Rubicon adapter uses sizes from MediaTypes.banner.sizes first, and if not present then from bid.sizes.

This causes an issue, that adapter is using the size (from MediaTypes.banner.sizes), which should actually be filtered.

## Steps to reproduce

1 Set media queries in Prebid via setConfig
2 Have several sizes defined for the AdUnit via MediaTypes.banner.sizes
3 Request bids

```
    var adUnits = [{
        code: 'div-gpt-ad-1460505748561-0',
        mediaTypes: {
            banner: {
                sizes: [[160, 600], [300, 600]]
            }
        },
        bids: [{
            bidder: 'rubicon',
            params: {
               accountId: '111', // dummy id
               siteId: '111', // dummy id
               zoneId: '111, // dummy id
            }
        }],
        labelAny: ['size-160', 'size-300']
    }];
```

sizeConfig is below
(note: max-width = 4999px is used to be always matched for the issue illustration)
```
            sizeConfig: [
              {
                mediaQuery: '(min-width: 5000px)',
                sizesSupported: [ [ 160, 600 ], [ 300, 600 ] ],
                labels: [ 'size-160',  'size-300']
              },
              {
                mediaQuery: '(min-width: 300px) and (max-width: 4999px)',
                sizesSupported: [ [ 160, 600 ] ],
                labels: [ 'size-160' ]
              },
              {
                mediaQuery: '(min-width: 0px) and (max-width: 299px)',
                sizesSupported: [],
                labels: []
              }
            ]
```

## Test page

https://jsbin.com/buburecuxu/edit?html,output

### Expected results
Rubicon adapter requests bid with the size_id = 9 (160x600) only.

### Actual results
Rubicon adapter requests bid with the size_id = 9 (160x600) and alt_size_id = 10 (300x600) and we receive bid with the size 300x600, which should be filtered by Prebid based on Media query.

## Platform details

Prebid 1.16, Chrome

## Other information

#2607

**Comment by derdeka** [comment]
@snapwich - as you merged #2607: Should mediaTypes.banner.sizes also be filtered by prebid core?

**Comment by snapwich** [comment]
it should.  I'll take a look

**Comment by derdeka** [comment]
@snapwich Did you have a chance to look into this issue?

**Comment by drdmitry** [comment]
If that could help, please find below the explanation:

Here in `getBids`, `adUnit.sizes` are filtered by applying labels on the adUnit level.
https://github.com/prebid/Prebid.js/blob/f32605ab23356653b31b6087850443a21b1a3326/src/adaptermanager.js#L48-L63

Later in `getBids`, `filteredAdUnitSizes` (`adUnit.sizes` filtered before) are filtered by applying labels on the bid level.
And creating the bid, with the final `sizes` (`bid.sizes`).
https://github.com/prebid/Prebid.js/blob/f32605ab23356653b31b6087850443a21b1a3326/src/adaptermanager.js#L78-L89

But `bid.mediaTypes.banner.sizes` was copied from `adUnit` and was not filtered.
https://github.com/prebid/Prebid.js/blob/f32605ab23356653b31b6087850443a21b1a3326/src/adaptermanager.js#L57

This means that (as we think) either Prebid should update `bid.mediaTypes.banner.sizes` (assign the same `filteredAdUnitSizes` value when creating bid) or Rubicon adapter should use `bid.sizes` first and if value does not exist - use `bid.mediaTypes.banner.sizes`.
