### ISSUE TITLE
WARNING: Usage of adUnits.sizes will eventually be deprecated.  Please define size dimensions within the corresponding area of the mediaTypes.<object> (eg mediaTypes.banner.sizes).

### ISSUE THREAD

**Issue by ShashankSureshMindEra** [prebid/Prebid.js#2853]
## Type of issue
QUESTION 

## Description
In the console, I see the warning message " WARNING: Usage of adUnits.sizes will eventually be deprecated.  Please define size dimensions within the corresponding area of the mediaTypes.<object> (eg mediaTypes.banner.sizes). "

As per the ticket 2248, I tried the below but it did not work. 

"mediaTypes": {
                        "banner": {
                           "sizes": [
                                [
                                    320,
                                    50
                                ]
                            ]
                        }
                    },

Any help will be much appreciated. 

## Test page
https://lipsum.com/?pbjs_debug=true
Use the attached .txt file with Resource Overrides. 
[example.txt](https://github.com/prebid/Prebid.js/files/2197254/example.txt)

## Platform details
Prebid v1.15.0 
OS - Mac

## Other information
https://github.com/prebid/Prebid.js/issues/2248

**Comment by YOzaz** [comment]
Hi, see here: https://github.com/prebid/Prebid.js/issues/2248#issuecomment-405467313.

**Comment by jsnellbaker** [comment]
@ShashankSureshMindEra From the conversation in the other issue, it seems like this was addressed.  If so, please close out this issue.

If you still have some outstanding questions, please reply here and I'll be happy to help.
