### ISSUE TITLE
add digitrust function to utils

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#2859]
## Type of issue
cross-adapter utility library request

## Description
DigiTrust is an optional module for pubs, but in order for adapters to support it, there's a small function that could be made a standard part of utils. This will save adapters from duplicating code.

## Suggested code
Based on the code implemented in the Rubicon bid adapter:
```
exports.getDigiTrustQueryParams=function (defaultMemberId) {
  function getDigiTrustId(defaultMemberId) {
    let digiTrustUser = window.DigiTrust && (config.getConfig('digiTrustId') || window.DigiTrust.getUser({member: defaultMemberId}));
    return (digiTrustUser && digiTrustUser.success && digiTrustUser.identity) || null;
  }

  let digiTrustId = getDigiTrustId(defaultMemberId);
  // Verify there is an ID and this user has not opted out
  if (!digiTrustId || (digiTrustId.privacy && digiTrustId.privacy.optout)) {
    return [];
  }
  return {
    'dt.id': digiTrustId.id,
    'dt.keyv': digiTrustId.keyv,
    'dt.pref': 0
  };
}
```

## Other information
Note that similar code is also used in the prebidServerBidAdapter 

More info on DigiTrust at http://prebid.org/dev-docs/modules/digitrust.html

**Comment by mkendall07** [comment]
can this just go into a module?

**Comment by bretg** [comment]
The point of this utility function would be for simplified adapter support of the module. Each adapter needs to do the same things to look for DigiTrust config -- this makes it a one-liner for each.

Publishers still wouldn't be able to use DigiTrust without including the pseudo-module. Note that we don't currently have real module support for DigiTrust yet -- until their library is converted to an NPM package, which is on our list.

**Comment by mkendall07** [comment]
closing this in favor of https://github.com/prebid/Prebid.js/issues/3046
Bret I think we should figure out how to put this into a module still.
