### ISSUE TITLE
sizeConfig not honoured after window resize due to unexpired bids from previous auctions being used

### ISSUE THREAD

**Issue by chrissjhitc** [prebid/Prebid.js#2861]
## Type of issue

Question

## Description

Unexpired, unused bids from previous auctions can be selected as the winning bid, but if the window has since been resized then these bids can be for a size that is no longer eligible due to the sizeConfig rules. 

We’ve avoided this issue by using a new adUnit and code each time we call request bids after a window resize, but should Prebid be ensuring any bids from previous auctions are also still valid for the sizeConfig rules before using them in the current auction? 

## Platform details
Prebid 1.16.0

**Comment by jaiminpanchal27** [comment]
@chrissjhitc Thanks for reporting. I think Prebid core should handle this.

**Comment by snapwich** [comment]
This fix will be included in the 1.29 release.
