### ISSUE TITLE
Sovrn bid caching TTL misconfigured as milliseconds rather than seconds

### ISSUE THREAD

**Issue by andyblackwell** [prebid/Prebid.js#2884]
## Type of issue
Bug

## Description
Confirmed with our reps that the correct Sovrn bid caching TTL is 60 seconds, but the current config has it set to 60,000 seconds. Is simply set as milliseconds instead of seconds.
https://github.com/prebid/Prebid.js/blob/1.16.0/modules/sovrnBidAdapter.js

### Expected results
Bid caching TTL set to 60 seconds

### Actual results
Bid caching TTL set to 60,000 seconds

## Platform details
prebid 1.*

**Comment by bszekely-s1** [comment]
Are you seeing any issues as a result of this misconfiguration? As similar issue occurred with Index, whereby lowering the TTL looks to have addressed an issue with Index ads rendering expired bids. We are still adjusting the TTL to determine optimal rate. Curious to see where your issues were.

**Comment by andyblackwell** [comment]
This was found as part of our upgrade to prebid 1.*, which we just started testing in production this week.

We contacted all of our reps to verify the bid ttl settings, because some were obviously wrong, and we plan on utilizing bid caching in different ways. Trying to fix potential issues before they happen.

Created issues here to highlight to others the ones we know are currently wrong.
