### ISSUE TITLE
AudienceNetwork bid caching TTL misconfigured

### ISSUE THREAD

**Issue by andyblackwell** [prebid/Prebid.js#2885]
## Type of issue
BUG

## Description
From the docs, AudienceNetwork "web bids are valid for 10 minutes", but currently it takes the bidderTimeout prebid config which is in milliseconds and applies it as the bid TTL.
`const ttl = Number(config.getConfig().bidderTimeout);`
https://developers.facebook.com/docs/audience-network/advanced/ortb-bidding

### Expected results
A bid TTL of 10min (600 seconds)

### Actual results
bid TTL is equal to the bidderTimeout config

## Platform details
1.*

**Comment by mkendall07** [comment]
yeah this looks like a bug. @lovell

**Comment by lovell** [comment]
Thanks both, I'll take a look.
