### ISSUE TITLE
Rubicon bid caching TTL misconfigured

### ISSUE THREAD

**Issue by andyblackwell** [prebid/Prebid.js#2889]
## Type of issue
BUG

## Description
Our Rubicon rep just confirmed their bids have a TTL of 60 seconds, but their adapter is currently configured at 300 seconds (5min).

## Platform details
1.*

**Comment by bretg** [comment]
Bid re-use is a topic that hasn't been well-communicated to the account team.

Technically, 300 seconds is correct. There is a new message going to the account team that bid caching must be used only in certain limited scenarios - basically just refreshes on the same adunit in the same page.

And with the recent news/controversy around bid caching, this policy is being reviewed.
