### ISSUE TITLE
How to determine the correct value for `jstag_url` regarding OpenX?

### ISSUE THREAD

**Issue by joyofdata** [prebid/Prebid.js#289]
Hello!

OpenX requires a `jstag_url` to be set. But I fail to understand where this URL is supposed to be taken from or how it is constructed.

Could somebody help me with that?

Kind Regards

**Comment by ialex** [comment]
When you sign up for OpenX Header Bidding they will give you that URL.

**Comment by protonate** [comment]
Thanks @ialex, @joyofdata if you have further questions please reopen or create a new issue. Closing.
