### ISSUE TITLE
Consent Management Module - gdpr consent is undefined.

### ISSUE THREAD

**Issue by RajasekarPR** [prebid/Prebid.js#2905]
I have included the consent management module along with the prebid server , while testing the i got the gdpr consent as undefined. 

Configuration :
![image](https://user-images.githubusercontent.com/39621436/43380985-ba43ff66-93f0-11e8-8741-6ede8d9b147c.png)

Undefined data:

![image](https://user-images.githubusercontent.com/39621436/43381039-ea3871a2-93f0-11e8-89d4-2e7cc8494931.png)

Prebid Version : 1.17.0

Why it is undefined data?

**Comment by jsnellbaker** [comment]
@RajasekarPR Do you have a test page setup that's actively returning this `undefined` result?  There are a few reasons to get undefined, some related to the CMP.  Seeing it in action would help explain it.
