### ISSUE TITLE
Ga tracker should respect tracker name prefix (or allow you to configure it)

### ISSUE THREAD

**Issue by bborn** [prebid/Prebid.js#291]
When using multiple GA trackers, you can give each one a name, in which case when you send an event, you need to prefix it with the tracker name:

`ga('mytracker.send', 'event', 'Prebid.js Load Time Distribution', dis, bidder, 1, _disibleInteraction);`

instead of:

`ga('.send', 'event', 'Prebid.js Load Time Distribution', dis, bidder, 1, _disibleInteraction);`
(only works for unnamed trackers)

Since Prebid hardcodes this, it fails when using a tracker name. Instead it should pull the tracker prefix from the ga settings, or else allow the user to configure in `enableAnalytics`

**Comment by bborn** [comment]
More: this happens also in my case because we use Tag Manager to initialize our GA tracker. GTM gives the tracker a name:

<img width="545" alt="screen shot 2016-03-31 at 11 45 14 am" src="https://cloud.githubusercontent.com/assets/3760/14183454/0d6d69ac-f736-11e5-8918-cadbdafb43d6.png">

And then PB analytics events fail because they don't use the name prefix:

<img width="828" alt="screen shot 2016-03-31 at 11 45 36 am" src="https://cloud.githubusercontent.com/assets/3760/14183470/228f81b2-f736-11e5-8917-940530a687cf.png">

That should be 
`ga("gtm1459442374366.send", "event", "Prebid.js Bids", "Requests", "yieldbot", 1, {nonInteraction: true})`

**Comment by mkendall07** [comment]
@bborn 
Yes we are aware of this but it's not a high priority on our backlog right now. We'll leave this open as a tracker.

**Comment by protonate** [comment]
Released with [0.8.0](https://github.com/prebid/Prebid.js/releases/tag/0.8.0)
