### ISSUE TITLE
sending multi bid for the same adapter

### ISSUE THREAD

**Issue by yanfaingold** [prebid/Prebid.js#2922]
i noticed only some adapters allow multi bid request so i wonder is there any way i can make prebid to send request separately for each bidder? like in config? so i would be able to send multi bid request for the same adapter since they have different campaigns this is a necessity.

**Comment by akira28** [comment]
I'm facing the same issue with Rubicon, that supports video, but you can send just one of video and banner. Any workaround to send multi-format just for the bidders that supports it?

**Comment by yanfaingold** [comment]
is using aliasBidder can solve this issue?

**Comment by akira28** [comment]
As this has not been neither acknowledged nor solved marking it as stale doesn't seem to be correct. In my very humble opinion as this is affecting more than 1 user, I would rather add a label or something to avoid setting it stale (or close) until there's time from core devs or contributors to find a workaround or definitive solution. Just my 2 cents :)

**Comment by mkendall07** [comment]
Can you dig into the issue a bit more? What's the exact problem?

**Comment by bwoolcott** [comment]
@akira28 and @yanfaingold any follow ups to @mkendall07's request for more information on the exact problem?
