### ISSUE TITLE
Video example with Video.js and IMASDK

### ISSUE THREAD

**Issue by josepowera** [prebid/Prebid.js#2927]
## Type of issue
Looking for example of integration 

## Description
As a publisher we are looking for integration of prebid video with the following stack:
Prebid - IMASDK +IMASDK-videojs plugin - videojs player
https://github.com/googleads/videojs-ima

There is a similar example for Prebid- videojs-vast-vpaid plugin - videojs player in http://prebid.org/examples/video/videojs-demo.html

Demo of VideoJs+IMASDK:
https://codepen.io/imasdk/pen/wpyQXP

It would be great to have something similar to http://prebid.org/examples/video/videojs-demo.html just with IMASDK as public example.

The other great benefit is that http://googleads.github.io/videojs-ima/examples/advanced/   already supports VMAP with pre, mid and postroll

**Comment by josepowera** [comment]
.

**Comment by ReinoutStevens** [comment]
You can pass the result of `buildUrl()` to google ima. You can find a simple example here: https://github.com/googleads/googleads-ima-html5/blob/master/simple/ads.js
replace the link of line 42 `adsRequest.adTagUrl` with the result of `buildUrl()`, and you should be good to go
