### ISSUE TITLE
Migrate currency.prebid.org to a different CDN

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#2929]
## Type of issue
Environment update

## Description
We're spending more money on hosting the currency conversion file at currency.prebid.org than we'd like. The file is being generated daily out of an AWS Lambda function and hosted on CloudFront.

Taking ideas for a less expensive approach that's still dynamic. e.g. can we script something for jsdelivr?

**Comment by ptomasroos** [comment]
Or put cloudflare in front with a caching rule? Would save abuot 90% of the traffic most likely and its free.

**Comment by mkendall07** [comment]
@bretg 
is cloudfront already caching?
