### ISSUE TITLE
`utils.getTopWindowLocation` not supported on firefox browsers?

### ISSUE THREAD

**Issue by rjvelicaria** [prebid/Prebid.js#2938]
## Type of issue

Question, but maybe an oversight/bug as well.

## Description

On Firefox browsers [tested on quantum and v48], calling `utils.getTopWindowLocation` retrieves `about:blank`.  
This fails to get the real top window location for several reasons:
* Firefox doesn't support location.ancestorOrigins
* Mozilla's [concept of the referrer](https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer#Notes) differs from how chromium implements it.

Is there another utils function we can use to get the top window location to support firefox browsers?  Or if not, can we support firefox browsers on the `utils.getTopWindowLocation` fn.

## Steps to reproduce
any basic prebid setup in an iframe + firefox browser

### Expected results
```javascript
utils.getTopWindowLocation()
>> localhost
``` 
(or what your dev env host is)

### Actual results
```javascript
utils.getTopWindowLocation()
>> about:blank
``` 
(or what the iframe src is set)

## Platform details
Firefox Quantum, or any firefox v48 onwards

**Comment by mkendall07** [comment]
Seems like a bug. I'd review a PR for a fix. thanks for the report.

**Comment by thewizarodofoz** [comment]
@rjvelicaria I tried reproducing this by loading the [hello world](https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/hello_world.html) example in an iFrame and logging the output of `utils.getTopWindowLocation()`.

My findings are:
1. The output is the same in Chrome 68 and in Firefox 61.
2. The output is similar to a [`Location`](https://developer.mozilla.org/en-US/docs/Web/API/Location) object and not a string.

Can you maybe set up a full example to reproduce this?

**Comment by rjvelicaria** [comment]
Hi @thewizarodofoz,
I'll try and get a page for it.
I was using a v1.18.0 of prebid before but I'll try both versions to see if there's any changes.

**Comment by rjvelicaria** [comment]
codepen: https://codepen.io/anon/pen/MqEQrN?editors=1000

how it behaves on chrome v68:
![screen shot 2018-09-06 at 11 33 05 am](https://user-images.githubusercontent.com/25090246/45177915-20b3d780-b1c9-11e8-85e6-32389c541e1e.png)

how it behaves on firefore v61.0.2:
* for firefox, code sometimes works if it loads on the first time.  Try loading the same codepen again on another tab and check the values reported.
![screen shot 2018-09-06 at 11 34 42 am](https://user-images.githubusercontent.com/25090246/45177927-2ad5d600-b1c9-11e8-98cf-5b208d94847b.png)

**Comment by thewizarodofoz** [comment]
I submitted a pull request. It's not perfect because there will be a different behaviour between Chrome and Firefox in cross-domain situations, but I believe it's better than the current situation.

**Comment by rjvelicaria** [comment]
#3067
