### ISSUE TITLE
chrome extension always reports impression loss

### ISSUE THREAD

**Issue by pav7** [prebid/Prebid.js#294]
I have the chrome extension installed on two computers. I have never returned a positive response from the extension. I either get impression loss because DFP took too long, or I get "under monetized" because one bidder is not loading with the rest. If I were to gauge performance solely using the responses I get from the extension, my conclusion would be either that my set-up is never, ever loading an effective impression to DFP or my conclusion would be that the extension does not work. Fortunately, I do check my bidders' UIs for prbid revenue and GA reports that both indicate to me that auctions are happening and bidders are winning impressions. The prebid auctions nearly match my page views so that indicates the auction is working. 

I'd be curios to know if the individual performance of the extension can be affected by hardware/connection. I have one hard wired older PC and one wifi PC. Both are overdue for replacement. Probably the best way to test this, since the extension returns results on every website that is enabled for prebid (regardless of whether or not you own the site), is to visit a site enabled for prebid that the publisher believes to have a flawless set-up. If I go to that site and still see errors, maybe the issue is my computers/connection not the extension. In turn it would be helpful is someone out there would be willing to visit my site and send me the extension results they are getting.

**Comment by mkendall07** [comment]
@pav7 
The chrome extension does it's best to evaluate the page and offer recommendation on optimization. It doesn't indicate that your site is completely broken or that bidders are not winning for example. Feel free to post your page here for us to take a look if your concerned that it's not implemented correctly

**Comment by mkendall07** [comment]
@pav7 closing this. Please re-open if you would like us to check your site.
