### ISSUE TITLE
Sovrn examples in markdown file do not return test creatives.

### ISSUE THREAD

**Issue by mannzer** [prebid/Prebid.js#2944]
## Type of issue
bug in .md file

## Description
According to http://prebid.org/dev-docs/bidder-adaptor.html#required-files:
modules/exampleBidAdapter.md is required to provide:
* A test ad unit that will consistently return test creatives.

The example in https://github.com/prebid/Prebid.js/blob/master/modules/sovrnBidAdapter.md consistently returns a response object lacking a "seatbid" array.

## Steps to reproduce
Create a simple test using the example provided at https://github.com/prebid/Prebid.js/blob/master/modules/sovrnBidAdapter.md

## Test page
http://jsfiddle.net/z5vqLew9/2/ (does not run as needs an example prebid.js file)

### Expected results
A response object with a non-empty "seatbid" array

### Actual results
The response object is always missing its "seatbid" array, e.g.: {"id": "50f33d92bdd8ee" }

## Platform details
master branch as of 2018-08-08

#### Notes
The .md file appears to contain another bug as the third example adUnit contains a "size" field instead of "sizes".

**Comment by aprakash-sovrn** [comment]
We are working on getting this set up, thanks for pointing it out.
