### ISSUE TITLE
Move prebid.js to open source cdn

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#2949]
## Type of issue
Feature

## Description
Prebid release pushes files on appnexus cdn and we also publish to npm.
We would like to move this to some open source cdn like [jsDelivr](https://www.jsdelivr.com/)

**Comment by vedantseta** [comment]
How would user specified modules be included as provided by [Prebid Download](http://prebid.org/download)? or would this contain all modules by default?

**Comment by snapwich** [comment]
Speaking of which, making a lambda job (or other service) that works on built prebid-core and module files would be much easier if we started publishing the build results to NPM.  It's something I've thought about in the past that I think we should be doing; currently we only publish the source files.

**Comment by bretg** [comment]
Closing this. Will leave the "consumer NPM package" open.
