### ISSUE TITLE
secureCreative -> receiveMessage throws an error when no adObject is found 

### ISSUE THREAD

**Issue by OhadTs1985** [prebid/Prebid.js#2953]
## Type of issue
Bug
## Description
When two instances of Prebid runs in the same scope the _secureCreatives.js_ module of instance no.1 might listen to events thrown by a creatives that runs in a cross domain iframes which has been created by instance no.2. This results in the _receiveMessage_ handler not finding adObject (sets as undefined) and an error thrown when the _sendAdToCreative_ method tries to access the adObjects.adId (line 56 in the secureCreative.js module).

**Comment by mkendall07** [comment]
Thanks for the bug report. It might expedite a solution if you provided an example of this.

**Comment by bwoolcott** [comment]
@OhadTs1985 do you have an example of this or a test page you could point us to?
