### ISSUE TITLE
Rubicon Outstream: Ignoring bid: Video bid does not have required vastUrl or renderer property

### ISSUE THREAD

**Issue by lanceloti** [prebid/Prebid.js#2957]
## Type of issue
bug

## Description
I'm testing Rubicon with outstream video context but getting this error: Invalid bid from Rubicon. Ignoring bid: Video bid does not have required vastUrl or renderer property

## Steps to reproduce
Configure Rubicon as bidder in a video outstream adunit.

## Test page
http://maringa.odiario.com/ads/adplayer-outstream.php?pbjs_debug=true

### Expected results
Show the video ad
### Actual results
An error in console

## Platform details
Prebid 1.18 e 1.19

## Other information
https://github.com/prebid/Prebid.js/pull/2683

![screenshot_60](https://user-images.githubusercontent.com/17436827/43923593-a141dd98-9bf8-11e8-820f-f7e491351c18.png)
![screenshot_61](https://user-images.githubusercontent.com/17436827/43923595-a163b3e6-9bf8-11e8-9807-23b0680ed5c9.png)

**Comment by mkendall07** [comment]
@bretg to review.

**Comment by lanceloti** [comment]
I'm trying instream context and gotting similar error on bid response.
![screenshot_78](https://user-images.githubusercontent.com/17436827/44681624-7d6c0100-aa17-11e8-9e27-f434fb3cbabd.png)

**Comment by bretg** [comment]
I think the instream issue should be cleared up with 1.24 and #3082. 

Will check out the outstream issue... don't see why that error should be appearing.

**Comment by bretg** [comment]
Figured it out.

Rubicon does not return a renderer. The publisher must supply a `renderer` in the adunit. See http://prebid.org/dev-docs/show-outstream-video-ads.html

            var adUnits = [{
                code: 'video1',
                mediaTypes: {
                    video: {
                        playerSize: [640, 480],
                        context: 'outstream'
                    }
                },
                renderer: {
                      url: 'RENDERER_JS_URL',
                      render: function (bid) {
                            RENDEROBJ.renderAd({  // call the function defined by the RENDERER_JS_URL
                                    targetId: bid.adUnitCode,
                                    adResponse: bid.adResponse,
                           });
                      }
                },
                bids: [{
                    ...

If the `renderer` object isn't in the AdUnit, you'll see the "Video bid does not have required vastUrl or renderer property" error.

Please re-open if this doesn't resolve the issue.

**Comment by lanceloti** [comment]
It make sense, but Rubicon's adResponse is completely different from AppNexus, so I'll need to handle this case by case, right?

Thanks.
