### ISSUE TITLE
`gulp build ` not generating prebid.js in dist folder.

### ISSUE THREAD

**Issue by vishalgarale** [prebid/Prebid.js#2960]
`gulp build ` not generating prebid.js in dist folder.

**Comment by mkendall07** [comment]
can you provide more details please? 
Env? 
Node/npm version?
Error message?
branch/tag?

I just tested this out on master and it worked fine. Thanks

**Comment by vishalgarale** [comment]
Node version - v8.10.0
Npm version - 3.5.2

I was working on a master branch only, somehow it was not generating. Now today tired pull and build again, and its generated.

Thanks, @mkendall07
