### ISSUE TITLE
districtmDmx bid adapter - updates requested

### ISSUE THREAD

**Issue by jsnellbaker** [prebid/Prebid.js#2961]
## Type of issue
request

## Description
The districtmDMX adapter file name is out of sync with its bidder code.  The file name uses `districtmDmx` while the code is `districtmDMX` 

This is causing some issues with an internal tool we use in conjunction with Prebid.js.

@stevealliance Can you update the file names so they're consistent with the code style?

Additionally can you also update the [docs repo](https://github.com/prebid/prebid.github.io)?  The bidder params on this page (https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/districtmdmx.md) uses the incorrect version of the bidder code and the bidder gets rejected from the auction if used as documented.

**Comment by stevealliance** [comment]
@jsnellbaker, I will update the name file again.
To look exactly like you wanted

**Comment by jsnellbaker** [comment]
We'd have to fully extend that throughout the auction; so that if someone were to set:
`AppNexus` in their adunits - it would naturally resolve to `appnexus` when it's figuring out who the bidder is.

I can look into implementing that if that's something we want to do.

**Comment by mkendall07** [comment]
I was thinking more at build time looking for the files to produce - however, than it's inconsistent which isn't great. Let's table that for now.
