### ISSUE TITLE
Consortium IDs 

### ISSUE THREAD

**Issue by brittanyzellman** [prebid/Prebid.js#2964]
## Type of issue
Feature Request

## Description
There should be a way to leverage consortium ids without each adapter needing to do it's own sync. Can this call be done once by Prebid and then passed in the params of the buildRequest object? Although this would add one additional call on page load, this one call could be leveraged by any/all units on the page. 

## Platform details
Prebid.js version 1.x

**Comment by chefbenjamin** [comment]
great idea - I second this

**Comment by brittanyzellman** [comment]
Would it be feasible for Prebid to support all three?

**Comment by mkendall07** [comment]
Sorry which 3 are you speaking of?

**Comment by brittanyzellman** [comment]
IAB, App Nexus, and The Trade Desk. Sorry, should've specified. 
This could also be modular, in the sense that a publisher would get to pick which id to pass in the bid.

**Comment by ezberry** [comment]
This makes the most sense to me if it's done the same way that bidders themselves are, so publishers can setup which ones to use and different ID consortia could build adapters. Then the actual implementation wouldn't depend on any particular choice of who to support.

**Comment by mike-chowla** [comment]
I'm getting a lot questions about consortium ids.   Making support modular with adapters for fetching ideas is a good approach since publishers will want to pick which ones to use and it fits Prebid.org's values of being neutral and open.

Full support would be having a round of one or more id fetches before the auctions starts with the ids made available to all bidders.

**Comment by mkendall07** [comment]
We'd also like help! Feel free to comment on the other thread or start development if you'd like :) just let us know what you'd be interested in contributing. Thanks!
