### ISSUE TITLE
DistrictmDMX not compiling right for 0.34.18

### ISSUE THREAD

**Issue by e1superman** [prebid/Prebid.js#2967]
## Type of issue
If you try to config and download prebid with DistrictmDMX it results in an empty file, with an error.

## Description
Here is the prebid.js file, and error.
{"error":"Prebid file not built properly","requestId":"fc697742-5464-494a-a612-ca5265bbd35f"}

## Steps to reproduce
Configure any prebid file for 0.34.18 with DistrictmDMX (even alone, and download to see the error)

**Comment by mkendall07** [comment]
Thanks for the report. This is a known issue and should be resolved when https://github.com/prebid/Prebid.js/issues/2961 is fixed.
