### ISSUE TITLE
need for refactoring/redesign of end of auction/done callback logic

### ISSUE THREAD

**Issue by jsnellbaker** [prebid/Prebid.js#2971]
## Type of issue
request

## Description
Creating a specific issue to track the point raised in:
https://github.com/prebid/Prebid.js/issues/2648#issuecomment-396234253

Summary - The code that handles the end of an auction and related done callbacks needs to be reviewed and potentially refactored/redesigned as the current implementation is fragile and may have possible gaps in logic.

Copying the text here for easy reference:

I did stumble across some very... suspicious... code surrounding the end of auctions.

The `bidderFactory` generates an object with a [`callBids(..., done)`](https://github.com/prebid/Prebid.js/blob/master/src/adapters/bidderFactory.js#L161) function. However, it [doesn't get called](https://github.com/prebid/Prebid.js/blob/master/src/adapters/bidderFactory.js#L183) under certain circumstances.

In `auction.js`, the callback [sent by the `bidderFactory`](https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L197) to the bidders [increments a counter](https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L153) which is then used to figure out [when the auction is over](https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L170). It looks like `auction.js` [tries to compensate for this](https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L247)... but that's a _really_ fragile design.

For example, the "fix" won't happen if `bidResponse.videoCacheKey` is true, which it will be [if Rubicon bids are involved](https://github.com/prebid/Prebid.js/blob/master/modules/rubiconBidAdapter.js#L450).

That's just one example that I see off the top of my head... but there may be many other logical discrepancies between the two too. It's simply not safe to write two logic branches in different parts of the code and require them to stay in sync.

My general suggestion would be to simplify the code which determines when auctions end, make sure it's written in a single file, write good tests for it, and see if the problem goes away.

**Comment by jaiminpanchal27** [comment]
We already have issue for this https://github.com/prebid/Prebid.js/issues/2482
Since it is explained here in depth i will close the other one.

**Comment by jsnellbaker** [comment]
Jotting down potential notes/scenarios to keep in mind for this topic:
- when an outstream adunit and an instream adunit are requested in the same auction. 
(previous solution had the outstream be cached when it didn't need to and may have ended the auction early before the instream has a chance to finish)
- when two instream adunits are requested in the same auction.  Both should be cached (when it's enabled) and handled properly.  
(previous solution would have ended the auction after processing the first instream adunit)

**Comment by jaiminpanchal27** [comment]
This is done.
