### ISSUE TITLE
What is pgid in OpenX? 

### ISSUE THREAD

**Issue by JuanCaicedo** [prebid/Prebid.js#298]
@mkendall07 and @protonate I saw you both did some work on the OpenX adapter. The docs say that `pgid` is required, but I was told by our rep at OpenX that they do not use any value like that. They did give me values for `jstag_url` and `unit`.

What is `pgid` and how can we ask OpenX for it? Is it possible it's not required?

**Comment by mkendall07** [comment]
@JuanCaicedo 
`pgid` is not required (page id).
