### ISSUE TITLE
Provide control for the publisher to turn off bid caching

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#2992]
## Type of issue
feature request

## Description
Though PBJS has a strictly-limited form of bid-caching, given the recent concern over bid caching in the industry, some publishers may wish to side-step any issues and turn the bid-reconsider feature off entirely.

Suggested implementation would be a call to `setConfig`.

**Comment by thewizarodofoz** [comment]
I would be happy to help implementing this. @bretg could you maybe point me in the right direction?

**Comment by bretg** [comment]
@thewizarodofoz - if you're still up for helping here, a possible implementation would be:

{code}
pbjs.setConfig({bidCache: {
  useOnRefresh: true
}});
{code}

Default value is currently proposed to be false, though this may have an impact to header bidding performance that pubs should be aware of.

Then just check bidCache.useOnRefresh before considering bids that are in the cache.

**Comment by thewizarodofoz** [comment]
@bretg I will submit a PR soon!

**Comment by freegames66** [comment]
Any update about this feature? 
Recently, I received a notification from **districtm** that they were not allowed to use bid caching. So, how to turn it off?

**Comment by bretg** [comment]
Yes - more relevant than ever. Assigning to @snapwich. Rich, the desire is to make it configurable for now so there's recourse in case a pub is impacted.
