### ISSUE TITLE
Cross-Origin Read Blocking (CORB) 

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#2994]
## Description
I am getting Cross-Origin Read Blocking (CORB) error messages 

## Steps to reproduce
Open test page in Google Chrome and open Console.

## Test page
https://www.flixxy.com/prebid.htm?pbjs_debug=true

## Platform details
Prebid Version 1.20   - Windows 10 - Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)

## Other information
Details:
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.google.com/ads/measurement/l?ebcid=ALh7CaTT8MSOW2pqY3VX3Cc0z7BxGByibWncoryfEJEBt-lWWaUKfmrcWI9FncOqFK6rJVyVH_5zr0kBl7jW5e81_pLW0DsKkQ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Does anyone know how to fix this?

**Comment by mercuryyy** [comment]
Im seeing the same errors anyone else?

**Comment by mkendall07** [comment]
Seems like a new feature in chrome that doesn't have a lot of support yet. 
Kind of ironic that the request that is blocked is originated from google. 

This doesn't have anything to do with prebid though so I'm going to close.
