### ISSUE TITLE
Remove support for cookieSet

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#2998]
## Type of issue
cleanup

## Description
In older versions of Prebid Server, the cookieSet feature was used to improve uids cookie rate. This feature is no longer used by any of the major Prebid Server host companies.

I propose removing the feature and cleaning up the documentation.

**Comment by mkendall07** [comment]
yeah I'm +1 on this.

**Comment by bwoolcott** [comment]
@mkendall07 @bretg Does this need further discussion or do we need a PR for this?

**Comment by mkendall07** [comment]
This is done
