### ISSUE TITLE
dfp lazyloading + header bidding 

### ISSUE THREAD

**Issue by amanjain** [prebid/Prebid.js#300]
Trying to create ad slots dynamically. It only loads ads for the last ad slots.

For example: After every page scroll we create 6 ad slots, but the bid array is only populating for the last slow. Any insights/examples?

**Comment by mkendall07** [comment]
Do you have some code we can look at?

**Comment by protonate** [comment]
@amanjain checking in on this. At present Prebid makes one request for bids at a time. You should wait for the bids back handler to be called before making another `requestBids()` call. We are working on a feature that will handle multiple bid requests in Prebid itself.

Please reopen if additional info.
