### ISSUE TITLE
Change default timeout buffer to `timeoutBuffer: 400`

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#3004]
Based on feedback in https://github.com/prebid/Prebid.js/issues/2648 I'd like to increase the default `timeoutBuffer` to 400ms.

**Comment by work-related-questions** [comment]
Sorry to bother, but can you please explain what does 'timeoutBuffer' do exactly ?
I've seen some comments that adding this to setConfig has helped some publishers with performance drops, but from what I can gather, it is just an addition to the global timeout and ends up adding another '400'ms (just an example) before DFP is being called ?

**Comment by mkendall07** [comment]
it extends the time that bidders have to return a bid after the auction closes. It's used to offset the "time slippage" of the `setTimeout` behavior in browsers.

**Comment by jaiminpanchal27** [comment]
Done here https://github.com/prebid/Prebid.js/blob/master/src/config.js#L25
