### ISSUE TITLE
Question about TIMEOUT vs PREBID_TIMEOUT vs FAILSAFE_TIMEOUT

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#3007]
## Question

The timeout in the Prebid Basic example changed from: 
var TIMEOUT = 2000;

To:
var PREBID_TIMEOUT = 1000;
var FAILSAFE_TIMEOUT = 3000;

I could not find any documentation on the PREBID_TIMEOUT and FAILSAFE_TIMEOUT

Can anyone explain?

**Comment by SliriK** [comment]
If I am not mistaken, the PREBID_TIMEOUT is somewhat similiar (if not the same) to the old TIMEOUT variable. This is the maximum time to wait for the auction before calling the ad server (and of course, any bid responses received after this timout will be ignored).

The FAILSAFE_TIMEOUT is intended for the cases in which for some reason the Prebid did not load properly or some other issue occurs. In such cases, this timeout is used to give back the control to the ad server (the initAdserver() function).
