### ISSUE TITLE
Object.freeze JS error in IE11 with Google Maps SDK + Prebid.js

### ISSUE THREAD

**Issue by FGoessler** [prebid/Prebid.js#3008]
## Type of issue
Bug

## Description
Prebid.js is using the `Object.freeze` function in its [bidderFactory](
https://github.com/prebid/Prebid.js/blob/master/src/adapters/bidderFactory.js). When the Google Maps SDK (e.g. from `https://maps.googleapis.com/maps/api/js?v=3&libraries=places`) is on the page as well, calling `getBidResponses` causes an JS error in Internet Explorer 11 (and probably below).

JS Error / Stacktrace:
```
TRACE: TypeError: Cannot define property '$jscomp_hidden_0.4609663612124215': object is not extensible
at c (https://maps.googleapis.com/maps/api/js?v=3&libraries=places&client=XXXXX&channel=XXXX&callback=google.loader.callbacks.maps:110:195)
at Object[a] (https://maps.googleapis.com/maps/api/js?v=3&libraries=places&client= XXXXX&channel= XXXX&callback=google.loader.callbacks.maps:110:270)
at getSpec (XXXXX-prebid.js)
```

It looks like the Google Maps JS SDK installs a polyfill for a `WeakMap` and overwrites the `Object.freeze` while doing so. This overwrite then causes issues when being called from within the prebid.js `bidderFactory`. 
One idea we have is that the returned `spec` object is already `frozen` and while trying to freeze it again, the polyfill tries to add a property and this then fails since it is `frozen` already.

As we cannot fix this on the Google Maps SDK side of things I adjusted the prebid code to wrap the Object.freeze call with a try-catch block and just return the plain spec object in case of an error from the freeze function. This solved the issue for us.
See changes [here](https://github.com/Scout24/Prebid.js/commit/8394c68e92dc0efcdbcced55c3f3c88ead282569).

## Steps to reproduce
- Have a page with prebid.js in place. 
- Include a Google Map in there via their JS SDK (v3).
- Run it in Internet Explorer 11
- Call `pbjs.getBidResponses()`

## Test page

We have no live test page right now.

### Expected results

No JS Error occurs.

### Actual results

JS Error `TypeError: Cannot define property '$jscomp_hidden_0.4609663612124215': object is not extensible` occurs.

## Platform details
- Tested prebid version 1.19.0 and up, but probably already happens with earlier versions.
- Internet Explorer 11 on Windows 8

## Other information
Proposed fix in our fork: https://github.com/Scout24/Prebid.js/commit/8394c68e92dc0efcdbcced55c3f3c88ead282569

We highly appreciate any feedback on this issue and its fix. We know it's not a clean solution, but no error free prebid in IE is also no option for us. Did maybe anyone encounter a similar issue?

**Comment by mkendall07** [comment]
Thanks for the report. Sounds like this a bug in the Google Maps SDK then though? Do you have a simple fiddle you can demonstrate the issue? For example, just use `Object.freeze` and load the maps SDK.

**Comment by FGoessler** [comment]
Sorry for the delay. I‘ll hopefully have time to create a simple example soon. 

I also agree that this is more an issue of the Google Maps SDK but Prebid is the way easier to adjust and communicate with partner here.
