### ISSUE TITLE
Add logLevel setting

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#3013]
## Feature request

Always log errors or add a logLevel setting to adjust the verbosity of the logging facility.

## Description

The [logError method in src/utils](https://github.com/prebid/Prebid.js/blob/1.21.0/src/utils.js#L282-L286) logs errors only  when the debug mode is turned on.

From a developer perspective this was unclear that errors are swallowed and not logged if your are not in debug mode. I would expect errors to always be logged.
We had an issue in our bidsBackhandler and didn't see any errors.

I can image two solutions.

### Turn on error logging on by default

This would mean to remove the `debugIsOn` check in the `logError` method.
However users wouldn't be able to turn the logging off.

### Add a log level setting

Add an additional configuration parameter `logLevel` with values like `debug | warn | error | none ` and let the user decide which logging granularity is required.

## Steps to reproduce

Throw an exception in the bidback handler.

### Expected results

The exception should be logged.

### Actual results

Nothing is logged

## Platform details
Prebid version 1.15 (also present until 1.2.1)

**Comment by mkendall07** [comment]
thanks for the suggestion. The trend here has been to not pollute the console log area but I can see how this can be frustrating for developers. Open to community feedback on this one.

**Comment by muuki88** [comment]
> The trend here has been to not pollute the console log area

I could not agree more :smiley: Especially when it comes to external creative scripts, which are sometimes way too noisy.

By adding a `logLevel` settin which defaults to `none`, we would have the same behaviour, but the flexibility to control the noise we want to have :)

**Comment by thewizarodofoz** [comment]
I vote for not polluting the console log area. IMO error logs are for developers while developing. And since the debug flag already controls the logging behaviour, maybe a meet-in-the-middle solution will be to document this behaviour better so that developers will be more aware.

**Comment by thewizarodofoz** [comment]
@muuki88 Just to make sure we are on the same page - are you familiar with the `pbjs_debug` query param? It can be used to [trigger debug mode](https://github.com/prebid/Prebid.js/blob/e643997d45f0fbefc3e75e08e8513a080bd34ef9/src/utils.js#L304) on the fly without having to leave `pbjs.setConfig({ debug: true });` in production code.

**Comment by muuki88** [comment]
Yes 😉. However this triggers all log messages. If I only want to have error logging in production, this doesn't help much 🤷🏻‍♂️. The suggestion would be a more fine grained control with either log levels or a configurable logger.

The more I think about it, the better I like the idea of a logger interface. The logger could be part of the configuration and if none is set, we use the default one as implemented right now

**Comment by muuki88** [comment]
I can draft a small PR if this would help to clarify my idea 👩‍🔧

**Comment by muuki88** [comment]
If there's no interest, I'll close this issue 😥
