### ISSUE TITLE
Secure bid requests for the AOL adapter

### ISSUE THREAD

**Issue by kizzard** [prebid/Prebid.js#302]
Hi,

Is there a way to switch AOL bid requests to secure? I see the pubtaglib is already being called using the secure CDN URL, but the secure property of the bid request is hard coded to false in the adapter.

Thanks.

**Comment by kizzard** [comment]
Thanks Steven

**Comment by kizzard** [comment]
My mistake, that was a fork - I suppose this issue should remain open until merged?

**Comment by protonate** [comment]
We can leave it open until we do a version release, now slated for Monday. @steven-hadfield's commit is now merged to master, however.

**Comment by kizzard** [comment]
Awesome, thanks!

**Comment by protonate** [comment]
Released with [0.8.0](https://github.com/prebid/Prebid.js/releases/tag/0.8.0)
