### ISSUE TITLE
"error":"Prebid file not built properly"

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#3039]
## Type of issue
I get an
{"error":"Prebid file not built properly","requestId":"0ac779bc-1154-4e21-9c03-134c515e4f16"}
when I try to download Version 1.22 (or Version 1.20) of the adapter containing:
Appnexus/DistrictM/Serverbid/Sovrn/Sonobi

**Comment by headerbidding** [comment]
More info:
Appnexus
Serverbid
Sovrn 
works.

**Comment by headerbidding** [comment]
Appnexus/Serverbid/Sovrn/Sonobi also works.

When I try to add the DistrictMDMZ adapter, i get the {"error":"Prebid file not built properly",

**Comment by mkendall07** [comment]
This is because DistrictMDMX didn't name their file correctly. It won't work until they fix it properly.

**Comment by mkendall07** [comment]
@stevealliance 
Your bid adapter file needs to be named `districtmDMXBidAdapter.js`. The convention is `${bidderCode}BidAdapter.js`

**Comment by stevealliance** [comment]
@mkendall07  Just to let you know I've updated the file it's on my open PR.

Thanks

**Comment by mkendall07** [comment]
Thanks. 
Linking here: https://github.com/prebid/Prebid.js/pull/3023/files
