### ISSUE TITLE
Utils is not defined (Reference Error - Pulsepoint Adapter)

### ISSUE THREAD

**Issue by RajasekarPR** [prebid/Prebid.js#3040]
I have installed the latest version of Prebid.Js (1.22.0) and i am getting the below error when debugging the prebid in my local. 

Error Message : Error Processing Command  : Utils is not defined reference error  . The exact error in pulsepoint 

![image](https://user-images.githubusercontent.com/39621436/44900787-2752d280-ad23-11e8-88be-643cf6affa47.png)

Kindly do the needful.

**Comment by jaiminpanchal27** [comment]
@RajasekarPR There is a PR for this fix here https://github.com/prebid/Prebid.js/pull/3033
