### ISSUE TITLE
Ad unit container doesn't resize properly due to a simple error

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#3041]
## Type of issue
Bug

## Description
So this fix https://github.com/prebid/Prebid.js/pull/2947/files was implemented incorrectly. When you change `style.width` or `style.height` you should use `newValue + 'px'` instead of just `newValue`. Right now `style.width` / `style.height` assignments make no effect

## Steps to reproduce
Create a 970x250 add running on 728x90 unit. Let this ad to win

### Expected results
Div and iframe containing ad are resized to 970x250

### Actual results
Div and iframe containing ad remain to be 728x90. Add is cropped mercilessly, measured viewability goes to zero, everyone panics

**Comment by ZLester** [comment]
Fixed by https://github.com/prebid/Prebid.js/pull/3066/commits/ef801ae348968223784b09e641f79391b9f16e5b, this can be closed
