### ISSUE TITLE
Unable to download Gambid bid adapter

### ISSUE THREAD

**Issue by arikkfir** [prebid/Prebid.js#3049]
## Type of issue
Error downloading Prebid.js with the Gamoshi (gambid) bid adapter.

## Description
When downloading Prebid.js with `Gamoshi` bid adapter selected, the downloaded file looks like this:
```
{"error":"Prebid file not built properly","requestId":"ef2fccba-cbdc-44fb-ad70-2c8f1d77a4e1"}
```

## Steps to reproduce
1. Navigate to [Prebid.js download page](http://prebid.org/download.html)
2. Check the `Gamoshi` bid adapter check-box
3. Download the bid adapter.

### Expected results
A valid Prebid.js file.

### Actual results
A JSON file containing:
```
{"error":"Prebid file not built properly","requestId":"ef2fccba-cbdc-44fb-ad70-2c8f1d77a4e1"}
```

## Other information
I noticed in prebid/Prebid.js#3039 that the `JS` file must be named according to a certain [convention](https://github.com/prebid/Prebid.js/issues/3039#issuecomment-417693497) but it seems, however, that the gambid adapter follows that convention. Am I missing something?

**Comment by arikkfir** [comment]
@mmoses FYI.

**Comment by mkendall07** [comment]
@arikkfir 
this is working for me. Please try again?

**Comment by arikkfir** [comment]
That's odd, it does work now.

It definitely did not work on Thursday (tried multiple times). Since I actually received a JSON file containing an error from Prebid (see description), I'm guessing some kind of temporary downtime of the JS custom-builds server?

**Comment by mkendall07** [comment]
Yeah we have an issue with the download page. It has to be manually addressed every time we have a release
