### ISSUE TITLE
Yieldmo adapter not setting creativeId 

### ISSUE THREAD

**Issue by beth92** [prebid/Prebid.js#3054]
## Type of issue

bug

## Description

In the interpretResponse function for this adapter, a `createNewBid` function is invoked which sets creativeId to response.creativeId. However, the response from the server has snake case, not camel case, so should be reading `response.creative_id`. 

https://github.com/prebid/Prebid.js/blob/master/modules/yieldmoBidAdapter.js#L114

## Steps to reproduce

Set `pbjs_debug=true` query parameter. Emulate smartphone and send requests via prebid to yieldmo. Observe network requests panel to see response from yieldmo server. When a bid comes back (i.e. body is non-empty) check pbjs logs or call `pbjs.getBidResponses()` to observe that prebid records no yieldmo bid even though one was sent. 

## Platform details

Prebid.js version 1.19
Chrome 66 
(emulating user agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Mobile Safari/537.36) 
## Other information

Created PR with proposed fix: #3053

**Comment by bretg** [comment]
Merged #3053

**Comment by harquail** [comment]
Thank you very much @beth92 !
