### ISSUE TITLE
requestBids({timeout) / config.bidderTimeout does not update pbjs.cbTimeout value

### ISSUE THREAD

**Issue by jarrettabello** [prebid/Prebid.js#3057]
## Description
pbjs.cbTimeout value equals 200 regardless of the configuration of the timeout via config.bidderTimeout or through requestBids({timeout: n) . Previously in at least 0.34 pbjs.cbTimeout would reflect the timeout configured per session/ auction

## Steps to reproduce
Attempt to set the auction timeout through either configuration or requestBids and compare against the pbjs.cbTimeout value

### Expected results
pbjs.cbTimeout = config.bidderTimeout || requestBids({timeout})

### Actual results
pbjs.cbTimeout = 200

## Platform details
v1.18.0-pre

**Comment by bretg** [comment]
@jarrettabello - have you checked this recently? cbtimeout being set to 200 was removed in https://github.com/prebid/Prebid.js/pull/3028

**Comment by jarrettabello** [comment]
Thanks @bretg our application is running v.1.180, so no. Sorry for the duplication.. I searched the project for cbTimeout and didn't find any issues. Shimmed that app for now. Thanks again!
