### ISSUE TITLE
Secure Creative resize works only in quirks mode

### ISSUE THREAD

**Issue by florevallatmrf** [prebid/Prebid.js#3065]
## Description
When using the secure creative flow, the creative resizing works only when the browser is in quirks mode (ie without a `<!DOCTYPE html>` at the beginning of the document). 
## Steps to reproduce
1. Setup header bidding for an adslot
2. Serve the target Admanager creative as a safeframe, size 1x1
3. Request the creative from prebid using post message
4. The creative is received

## Test page
JSFiddle showing the resize not working: http://jsfiddle.net/florevallatmrf/z89nwvbp/
Unfortunately JSFiddle always adds a `doctype` to the result, so I can't provide a link of it working without it. 

### Expected results
The slot (both containing div and safeframe) should resize.

### Actual results
The slot stays as a 1x1 block. 

## Platform details
Prebid v1.23.0
Tested in Chrome 68 & Safari 11.

## Other information
We changed this in our fork of Prebid, I will open a Pull request on this side too.

**Comment by muuki88** [comment]
@florevallatmrf nice to see people using safe frames. Have encountered any other issues with prebid and safe frames so far?

**Comment by florevallatmrf** [comment]
No, we haven't used them in production yet, for now the resizing has been my biggest pain!

**Comment by muuki88** [comment]
Thanks for sharing @florevallatmrf :hugs: We haven't rolled out any safe frames as well, because we are very uncertain how advertisers react (especially with cookie syncing, etc.).
