### ISSUE TITLE
getTopWindowLocation, getTopFrameReferrer, getAncestorOrigins will be deprecated soon

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#3072]
## Type of issue
Feature

## Description
We have added referer detection module #3067 here. 
We will be deprecating getTopWindowLocation, getTopFrameReferrer, getAncestorOrigins methods from utils.js

**Comment by pm-harshad-mane** [comment]
Hello @jaiminpanchal27 ,
utils.getTopWindowUrl() refers to utils. getTopWindowLocation, are we planning to deprecate utils.getTopWindowUrl and utils.getTopWindowReferrer as well?

**Comment by pm-harshad-mane** [comment]
Hello @jsnellbaker ,
can you please answer above query?

**Comment by jaiminpanchal27** [comment]
@pm-harshad-mane Yes we will deprecate those as well. In this sprint i am working on adding location object and canonical url to refererInfo.  
We will add everything to `bidRequest.refererInfo` and ask all adapter to update. 

You can find info here http://prebid.org/dev-docs/bidder-adaptor.html#referrers

**Comment by pm-harshad-mane** [comment]
Thank you @jaiminpanchal27

**Comment by jaiminpanchal27** [comment]
3.0 is released. Closing this one
