### ISSUE TITLE
Question - Why targetingSet bids are marked as UsedBids?

### ISSUE THREAD

**Issue by GeneGenie** [prebid/Prebid.js#3079]
Hello guys. 

It's understandable when Rendered bids are filtered during an auction on the same unit, but why targetingSet bids also filtered? Is it made intentionally? What is the logic behind this? 
I can imagine following scenario: 
targetingSet bid has lost in DFP auction so let's take another ad maybe it wins!?

But if next bid has even less cpm then already targetingSet bid?

Thank you

**Comment by mkendall07** [comment]
it's done intentionally so we don't send 2 bids to DFP for the same ad. 
For example:
1st auction sets targeting for bids to DFP
DFP takes a long time to respond
meanwhile, the publisher runs a 2nd auction and set's targeting again. If DFP decides to pick the ad from the 1st auction here we will possible try and render it twice.

**Comment by mkendall07** [comment]
at some point (after DFP renders - and the bid didn't win) we should release those bids that are marked as used, but that's not implemented yet.
