### ISSUE TITLE
Node version issue

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#3088]
What is wrong with v10.4.1? It was working perfectly for Prebid < 1.24

```
$ yarn install
yarn install v1.7.0
(node:29081) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by ZLester** [comment]
When installing via `yarn` with no `yarn.lock` I resolve `upath@1.0.5`, which is compatible with Node v10. As Prebid doesn't commit a `yarn.lock`, try rebuilding your local `yarn.lock` and see if that solves the issue. If all else fails, you can use `yarn config set ignore-engines true`.

**Comment by mkendall07** [comment]
I believe there was a build issue with node > 10 so that's why we added the engines file. Feel free to use the workaround though if it's working ok for you.
