### ISSUE TITLE
Gourmet Ads Bid adapter name

### ISSUE THREAD

**Issue by RajasekarPR** [prebid/Prebid.js#3089]
Bid adapter adapter name for gourmet ads bidder ?

I am getting unknown module for this.

Kindly do the needful.

**Comment by RajasekarPR** [comment]
Thanks .

**Comment by jsnellbaker** [comment]
@RajasekarPR  `gourmetads` is one of the aliases for the `appnexusBidAdapter`.  

See here:
https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L33

If you include the `appnexusBidAdapter` module when you're building Prebid.js - you should be good to use it.

**Comment by RajasekarPR** [comment]
@jsnellbaker Thanks. Done .
