### ISSUE TITLE
Auction ends prematurely [1.24.0]

### ISSUE THREAD

**Issue by dugwood** [prebid/Prebid.js#3091]
## Type of issue
Bug

## Description
After updating from 1.23.0 to 1.24.0 a drop in revenues occurred.

## Steps to reproduce
Upgrade to 1.24.0 and look for the auction's end. If you have some debug, you'll see that auction ends before some valid bids.
Note that reading the releases' page didn't show any new parameter involved.

## Test page
No test page as I've reverted back to 1.23.0 in production.

### Expected results
All bids should arrive before auction ends.

### Actual results
Auction ends in the middle of bids. Most probably Criteo (the fastest bid response) cut all other (but Criteo is also cut by other bidders sometimes).

## Platform details
Compiled on Linux Debian, Node 8.11.4, npm 5.6.0

## Other information
Change to 1.23.0 at 11:45, reverted at 17:00.

Sent bids (for AppNexus) vs returned bids (darker green):
![image](https://user-images.githubusercontent.com/5517743/45500869-00af8580-b780-11e8-876d-a18141fc5ffe.png)

Revenues (still only AppNexus):
![image](https://user-images.githubusercontent.com/5517743/45501150-be3a7880-b780-11e8-81f8-19bc4020c813.png)

Sent bids for Criteo, less impacted as it's the fastest:
![image](https://user-images.githubusercontent.com/5517743/45501246-ecb85380-b780-11e8-91d6-a792cb5b1978.png)

**Comment by jaiminpanchal27** [comment]
@dugwood Can you share the url of the page ?

**Comment by dugwood** [comment]
@jaiminpanchal27 I've reverted back... I'll try to setup one, I'll let you know.

**Comment by dugwood** [comment]
@jaiminpanchal27 for a limited period of time:
https://www.lacoccinelle.net/prebid.html?20190916#debug-ads-for-skyboard-670168053

You should see some debugs, hide the «Zone 17980» and just focus on «Zone 438».

For example I can see:
![image](https://user-images.githubusercontent.com/5517743/45501977-09ee2180-b783-11e8-831b-ffbb53baf538.png)

=> here AppNexus answers within the 2000ms timeout, but rubicon wins. The «Winner» is a message sent in the bidsBackHandler... so the auction is already ended.

**Comment by dugwood** [comment]
Numbers in gray are the time in milliseconds.

To enable Prebid debug, use the following url:
https://www.lacoccinelle.net/prebid.html?20190916#debug-ads-for-skyboard-670168053&pbjs_debug=true
(as GET parameters are forbidden)

**Comment by jaiminpanchal27** [comment]
@dugwood Thanks. Checking now

**Comment by jaiminpanchal27** [comment]
@dugwood Found the bug. We will do the patch release tomorrow. Thanks for contribution.

**Comment by dugwood** [comment]
Thanks @jaiminpanchal27, it seems to work much better:
https://www.lacoccinelle.net/prebid.html?20190916#debug-ads-for-skyboard-670168053&pbjs_debug=true
