### ISSUE TITLE
Getting console error messages for Prebid.js (1.22.0)

### ISSUE THREAD

**Issue by RajasekarPR** [prebid/Prebid.js#3093]
![image](https://user-images.githubusercontent.com/39621436/45544780-e932d400-b835-11e8-82ae-af98c86d45b3.png)

I am getting the above error message when debudding the prebid.js in console.

Kindly do the needful.

**Comment by jaiminpanchal27** [comment]
@RajasekarPR These are not Prebid errors. Prebid core has provided user sync feature to all bidders to drop pixels.
