### ISSUE TITLE
Optimization of Prebid.js's speed

### ISSUE THREAD

**Issue by Heray** [prebid/Prebid.js#31]
I noticed there's a 30-50ms lag between when Prebid.js finished loading and when the first pre-bid calls are initiated.

![screen shot 2015-08-19 at 3 08 09 pm](https://cloud.githubusercontent.com/assets/288183/9366236/207f6224-4684-11e5-8b6d-c36a2cab725c.png)

This is a Chrome capture on page: http://prebid.org/header-bidding-demo.html

**Comment by BartVB** [comment]
Same here. But as far as I can tell this is your browser parsing the Javascript.


![Google Chrome gpt/prebid timeline](https://cloud.githubusercontent.com/assets/32803/11171058/8911864e-8be6-11e5-9a83-cf80e8936715.jpg)

 I'm not exactly a prebid.js or Javascript expert but I think it should be possible to reduce this parsing time by helping the JS engines a bit. This seems to be a useful article:
http://ariya.ofilabs.com/2012/07/lazy-parsing-in-javascript-engines.html
Or this older article:
http://googlecode.blogspot.nl/2009/09/gmail-for-mobile-html5-series-reducing.html
Not very elegant but functional :)

**Comment by Heray** [comment]
Thanks @BartVB ! We are adding a new feature (coming up soon), that allows Prebid to inform GPT send out the impression immediately after the timeout hits, without having to wait for GPT to load. Closing the ticket for now.

**Comment by BartVB** [comment]
That's great and this would really help reduce latency on a page level, but it would still be really nice if it were possible to make prebid.js faster.
Eliminating redundant adapters resulted in a big improvement for us.
