### ISSUE TITLE
Prebid.org download page - Prebid.js 1.24.1 wrong filesize

### ISSUE THREAD

**Issue by razorlegacy** [prebid/Prebid.js#3101]
## Type of issue
Bug
Prebid.js 1.24.1 filesize is 91 bytes when I click download.

## Description
Prebid.js 1.24.1 filesize is 91 bytes when I click download.

## Steps to reproduce
Selected Fidelity, Openx, Pollux, Sovrn, and Underdog Media. Also selected modules GDPR and Common Publisher ID. I then click download and the file downloaded is only 91 bytes in size.

## Test page
{"error":"Prebid file not built properly","requestId":"7cf6d300-4d70-4270-94f4-1868d926ed61"}

### Expected results
Complete file download

## Platform details
Windows 10 and Prebid.js 1.24.1

**Comment by jsnellbaker** [comment]
@razorlegacy Thanks for reporting this; we're looking into it.

**Comment by jsnellbaker** [comment]
@razorlegacy The issue with the download page should be fixed at this time.  Please let us know if you're experiencing any further trouble.
