### ISSUE TITLE
Change in Bid result type mix after Prebid version update

### ISSUE THREAD

**Issue by jarrettabello** [prebid/Prebid.js#3105]
## Type of issue
Question

## Description
Upgrading from Prebid version 0.34 to 1.18 immediately impacted our mix of bid results

![screen shot 2018-09-19 at 3 32 26 pm](https://user-images.githubusercontent.com/2837550/45776832-2a562a00-bc22-11e8-9d66-75dc0174f77f.png)

I have not been able to find any information on the subject and I am wondering if anyone has any insight as to a methodology change in terms of bid results. 

Appreciate any insight!

**Comment by mkendall07** [comment]
@jarrettabello 
can you explain how you are measuring the bid results?

**Comment by jarrettabello** [comment]
@mkendall07 I figured it out. Prior to 1.x Prebid registered non-bids. Post 1.x non-bids are not registered at all. This change affected my analytics logic. Going to have to re-write with bidderDone event after a long day of research!
