### ISSUE TITLE
Pubmatic destroys bid sizes

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/Prebid.js#3111]
## Type of issue
Bug

## Description

Since Prebid 1.18 Pubmatic supports multi-size adslots ( https://github.com/prebid/Prebid.js/pull/2887 ). When passing an adslot without '@widthxheight' the sizes of the `mediatypes.banner.sizes` is used. Pubmatic bid adapter destructively modifies this array, messing up other adapters (in our case `ixBidAdapter`).

The offending line is [L266](https://github.com/prebid/Prebid.js/blob/master/modules/pubmaticBidAdapter.js#L266)

When you pass `@widthxheight` in adslot `sizes` is removed on [L120](https://github.com/prebid/Prebid.js/blob/master/modules/pubmaticBidAdapter.js#L120), which may also be an issue of the object is shared across different adapters.

Also note that the first size is ignored for some reason due to the `splice` call. This is probably due to the first size already being taken on [L122](https://github.com/prebid/Prebid.js/blob/master/modules/pubmaticBidAdapter.js#L122).

## Steps to reproduce

Have a pubmatic bid without the size defined in the adslot name.

## Test page
http://jsfiddle.net/2qwfp0zh/

### Expected results
Index bidAdapter should not complain

### Actual results
Index bidAdapter is a sad panda because the sizes are messed up

**Comment by jsnellbaker** [comment]
This particular issue has been fixed at the adapter level; I will open a new issue for a fix at the core level to avoid this issue happening again accidentally with other adatpers.
