### ISSUE TITLE
AppNexus bidder apparently ignoring network rev-share setting

### ISSUE THREAD

**Issue by satnamps** [prebid/Prebid.js#312]
I tested out the Appnexus bidder and I used a managed campaign for the same to target a placement.  I set the Line Item CPM to be 3.10 and added a pricing rule to let the publisher have 50% of network revenue.  However on inspecting the response to JPT call I saw that the CPM listed is still 3.1.  Is this by design for managed campaigns OR am I missing something?

This is how the JPT response looks like

pbjs.handleAnCB({  
   "result":{  
      "cpm":31000,
      "width":300,
      "height":250,
      "creative_id":27321827,
      "media_type_id":1,
      "media_subtype_id":1,
      "ad":"http://nym1.ib.adnxs.com/ab?e=wqT_3QL4BMh4AgAAAwDWAAUBCK2ZoLgFEPGSvtq4vf2QDhjSh9--h5Gp13wgASotCc3MzMzMzAhAEc0BCBDMCEAZAAUBCPA_IREbACkRCagw5ISuAzjzDkDzDkgCUOPLgw1Y-aIfYABozJICeLODBIABAYoBA1VTRJIBAQbwUpgBrAKgAfoBqAEBsAEAuAEBwAEDyAEA0AEA2AEA4AEA8AEAigI6dWYoJ2EnLCAzOTc5OTMsIDE0NjAxNDUzMjUpO3VmKCdyJywgMjczMjE4MjcsMh4A8IqSAskBIS15NkxJd2lwa05NQ0VPUExndzBZQUNENW9oOHdBRGdBUUFSSTh3NVE1SVN1QTFnQVlLSUdhQUJ3QUhnQWdBRUFpQUVBa0FFQm1BRUJvQUVCcUFFRHNBRUF1UUhOek16TXpNd0lRTUVCemN6TXpNek1DRURKQVpaTHN2VnByZjhfMlFFQUFBAQMkRHdQLUFCQVBVQgEOREFKZ0Npb2FJbkEyZ0FnQzFBZwEWBEM5CQhsRGdBZ0RvQWdENEFnQ0FBd0UumgIlIXhBaVphUTbMABwtYUlmSUFRbwlM8KAwLtgC4QfgAqz-CeoCNGh0dHA6Ly93d3cudW5kZXJzdGFuZGluZy1oZWFsdGguY29tLz9wYmpzX2RlYnVnPXRydWWAAwCIAwGQAwCYAwWgAwGqAwCwAwC4AwDAA6wCyAMA2AMA4AMA6AMA-AMDgAQAkgQEL2pwdJgEAKIEDTE3Mi44NS40Ny4xNDioBACyBAgIABAAGAAgALgEAMAEAMgEAA..&s=238b7427a8c4973893cc0996fbbcac61482d9cd0&referrer=http%3A%2F%2Fwww.understanding-health.com%2F%3Fpbjs_debug%3Dtrue"
   },
   "callback_uid":"107f35e483263d"
});

**Comment by headerbidding** [comment]
I ran into this issue as a publisher, when I found that AppNexus and DFP reports agreed in impressions but were off a fixed percentage in Revenue and eCPM.

**Comment by jchandler6** [comment]
Hi @satnamps We are currently looking into a bit of code that can be implemented to take off the rev-share, might look something like this:

pbjs.bidderSettings = {
    	appnexus: {
      	bidCpmAdjustment : function(bidCpm){
          return bidCpm * .85;
                                   }
            }
};

**Comment by mkendall07** [comment]
@satnamps this is expected behavior when using managed campaigns. Please reach out to your account  manager if you have any questions.
