### ISSUE TITLE
'Promise' is Undefined in IE11

### ISSUE THREAD

**Issue by RajasekarPR** [prebid/Prebid.js#3126]
getting the below error in IE11, because of this no ad's are loading in the page.

'Promise' is undefined.

![image](https://user-images.githubusercontent.com/39621436/46063635-05fece00-c18b-11e8-9850-539e07c435b3.png)

Kindly do the needful as soon as possible.

**Comment by bwoolcott** [comment]
@RajasekarPR That JS file does not look to be part of Prebid.js. Looks like it might be related to DistrictM user sync code

**Comment by mkendall07** [comment]
agreed - please contact districtM.
