### ISSUE TITLE
Number of user syncs exceeded for "aol"

### ISSUE THREAD

**Issue by ddagino** [prebid/Prebid.js#3127]
## Type of issue
Bug

## Description
After updating Prebid.js to v1.25.0, I'm seeing the following warning message in the console with `pbjs_debug` turned on: `WARNING: Number of user syncs exceeded for "aol"`

I see the aolBidAdapter underwent a refactoring to give it native user syncs support. I'm new to Prebid.js and I don't know really understand what that means and whether this is a bug or a feature—but I'm guessing bug, hence this report.

## Steps to reproduce
1. Build Prebid.js v1.25.0 with the aolBidAdapter module.
2. Create webpage with a script that performs basic Prebid initialization steps (addAdUnits, setConfig, setBidderSettings, etc.).
3. Open said webpage with debug mode enabled by appending `?pbjs_debug=true` to the URL.
3. Observe WARNING message in console.

## Test page
N/A

### Expected results
To not see any WARNING messages in the console.

### Actual results
WARNING message in console.

## Platform details
Prebid.js: 1.25.0
OS: OSX 10.13.6
Browser: Chrome Canary 71.0.3559.0

## Other information
Native user syncs support for AOL: commit 4baf2e4

**Comment by kizzard** [comment]
I don't *think* this is a bug - it's most likely that our bid responses contain more sync pixels than configured as the max in your config (5 default), so the adapter is trying to drop more than allowed (maybe someone from Prebid core can confirm that's what this message means). In theory it shouldn't be a problem, as we detect which pixels did not trigger and try to drop them again later.
cc @vzhukovsky

**Comment by harpere** [comment]
that is correct.  for performance reasons we limit the number of syncs.  But the publisher can configure this as they want.  see http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-Configure-User-Syncing
closing.  please re-open if necessary.

**Comment by ddagino** [comment]
Thank you for the follow-up @harpere.

I spoke with an engineer at AOL recently and they confirmed that they send more than 5 userSyncs but anything over 5 can be safely ignored and the syncs that aren't delivered will be queued for later delivery.

**Comment by kizzard** [comment]
@ddagino that engineer was me 👍

**Comment by ddagino** [comment]
@kizzard lol, guess I should have checked the profile. Thanks Jeremy!
