### ISSUE TITLE
YieldlabBidAdapter is not using bidRequest.params.adSize as customsize in bidResponse

### ISSUE THREAD

**Issue by vi-oder-was** [prebid/Prebid.js#3128]
## Type of issue
Bug

## Description
The customsize is not used within the bidResponse. Instead it uses the primary size of the array bidRequest.sizes.

## Steps to reproduce
see screenshot below

### Expected results
The bidResponse should use the bidRequest.params.adSize as width and height for the response.

### Actual results
The bidResponse contains the wrong size and doesn't match to the creativeId for Yieldlab deal. The deal doesn't appear.

## Platform details
prebid 1.24.1

## Other information
![image](https://user-images.githubusercontent.com/43609048/46081663-5bdc7180-c19d-11e8-9d54-0e0aa301b07a.png)

Introduced in #3035

**Comment by phtechno** [comment]
Hello everybody,
we need a posibility to handle different adsizes between the adslots and the response. Like "Sitebars" in our case. We have two adslots for "Sitebars" (responsive) and for "HalfpageAds" (300x600). Both have the slot size 300x600, but we can not differentiate if we have no indicator (like adsize) to do that.
Exactly for this case we need this bug as a feature to give the responsive a custom size.

Do you have another suggestion?
