### ISSUE TITLE
Running PreBid from within a Desktop app. 

### ISSUE THREAD

**Issue by mjwhaley** [prebid/Prebid.js#313]
@mkendall07 
We have been experimenting with trying to get the prebid running with a desktop app, but are seeing two issues, which are very likely linked. 

1 - The bids are firing and coming back. But none of the platforms are seeing the requests at all. 
2 - The winning bid is being selected by DFP and the ad is being requested from the winning and again nothing is registering. 

Do ideas on where we should start trouble shooting?

**Comment by mkendall07** [comment]
@mjwhaley 
Sounds like the requests are being blocked/filtered out by the demand partners. You should check the headers being sent by each bidder and make sure that it's not sending anything weird vs what a standard browser would send.

**Comment by protonate** [comment]
@mjwhaley were you able to get your implementation to work?

**Comment by mkendall07** [comment]
closing as didn't hear back from OP on this.
