### ISSUE TITLE
Appnexus outstream expects the Prebid adUnitCode to match div id

### ISSUE THREAD

**Issue by nanek** [prebid/Prebid.js#3138]
## Type of issue
Feature request.

## Description
Appnexus outstream expects the Prebid adUnitCode to match the div id of the ad unit. Can we make this a configuration setting instead?

https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L480

## Steps to reproduce

Currently we use our DFP ad unit identifier as our Prebid.js adUnit code and a different id for the div id and with this setup, banner ads work as expected. However outstream ads expects the the adUnitCode to match the div id. We tested changing our Prebid.js adUnitCode to match the div id, however viewability for all ad units dropped which we are not yet able to explain. Therefore instead of changing our adUnitCode to be something different, we would like to update the appnexus outstream adapter to be able to pass a divId for it to use.

**Comment by mkendall07** [comment]
@nanek 
Could you provide additional details on why the viewability dropped when changing the div ID? While we could implement this feature, I don't see a strong use case for it. It also complicates the logic for where we expect to render the Ad from the user's perspective.

**Comment by nanek** [comment]
Thanks for the response.

Viewability drops for our entire site and all ad units when switching adUnitCode. I wasn't able to determine the drop in viewability cause. Unfortunately the risks of changing the adUnitCode and dropping viewability site wide, is not worth the benefit of enabling appenxus outstream.

Prebid docs recommend DFP slot element id if using DFP, over a divId. http://prebid.org/dev-docs/adunit-reference.html

Tests and fixtures don't use a divId. They use what looks like a DFP slot element id, https://github.com/prebid/Prebid.js/blob/4e8955e5e7425859a1b00ddaf61cfd948677e572/test/fixtures/fixtures.js#L45

I haven't tested other outstream adapters outside of appnexus yet, however I don't see any other references to adUnitCode in a quick glance. As far as I can tell, only appnexus outsteam contains this constraint of using the divId.

**Comment by nanek** [comment]
I was able to identify the issue with viewability dropping, so this is no longer an issue for us.

We use https://github.com/turbolinks/turbolinks and smartadserver was taking the adUnit.code value (the divId) and injecting CSS into the document HEAD that would hide any div that had an id that was not prefixed with a value they expected. This CSS would persist between pageviews as the HEAD element retained the injected CSS and would hide ads from other partners until an actual page refresh.

I've also learned that other adapters such as teads also expects the adUnit.code to be the divId.

**Comment by mkendall07** [comment]
hey @nanek 
glad you got it working! I also just realized you can do this (specific to the AppNexus renderer anyway), by appending this to adUnit:
```
renderer: {
                    url: 'http://cdn.adnxs.com/renderer/video/ANOutstreamVideo.js',
                    render: function(bid) {
                        ANOutstreamVideo.renderAd({
                            targetId: 'myCustomDivId',
                            adResponse: bid.adResponse,
                        });
                    }
                },
```
