### ISSUE TITLE
Weird Analytics Data

### ISSUE THREAD

**Issue by bborn** [prebid/Prebid.js#314]
I'm using the latest build of Prebid.js (from master), and seeing GA analytics events reporting as expected in the console using the analytics debugger. But when I created the reporting spreadsheet (as described here: http://prebid.org/dev-docs/analytics-ga.html) I see some strange results:

- Bid rates over 100% (208% in one case)
- Timeout rates over %100
- Really long load times (13,000) that don't correlate with what the Header Bid extension is measuring

Not sure if this is something wrong with my setup, or with the reporting integration. Happy to share access to our data if that would help troubleshoot.

**Comment by fjudit** [comment]
I have the same issue and saw some of the formulas were wrong. The problem as soon as I run it again I got the same issue. anyone can help with this?

**Comment by kmjennison** [comment]
Depending on your setup, part of the problem might be that the spreadsheet template assumes there is one ad on the page. The "requests" event is fired once per bidder (so the requests count for a particular bidder should be effectively equivalent to your page views), but the "bids" event is fired once **per ad unit** per bidder. So, if you have 3 ad units on a page, and a bidder bids on every single request, you should see 3x as many bid events as request events.

In our case, we've temporarily solved this by multiplying the requests in our report by the number of ad units on our page.

**Comment by brondsem** [comment]
I ran into this as well.  @kmjennison is correct from what I can tell - there is one request per bidder, so the spreadsheet should NOT compare bids or timeouts or wins against requests.  Those percentages are all completely inaccurate by default (unless you happen to have just one ad on a page).  That isn't a common case, so the default spreadsheet should be changed.

**Comment by mkendall07** [comment]
We aren't maintaining the GA spreadsheet anymore. Feel free to share an updated version if you have it. Thanks

**Comment by brondsem** [comment]
Should http://prebid.github.io/dev-docs/analytics-ga.html#step-2-copy-the-demo-dashboard be updated to reflect that then?
