### ISSUE TITLE
Gulp - Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by aneuway2** [prebid/Prebid.js#3144]
## Type of issue
bug

## Description
I've recently updated my forked code with the master code here and i'm having issues getting gulp to run:

```
gulp build --adaptors=appnexusBidAdaptor
[20:31:16] Using gulpfile /var/www/html/.pkg/Prebid.js/gulpfile.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

## Steps to reproduce
```git clone https://github.com/aneuway2/Prebid.js.git
cd Prebid.js
npm install
gulp build --adaptors=appnexusBidAdaptor
```

### Expected results
Build is inititated through gulp

### Actual results
TypeError

## Platform details
NPM: 3.10.8
OS: Ubuntu 14.04.5 LTS
Node: 6.9.1
Gulp CLI version 3.9.1
Gulp Local version 4.0.0

**Comment by YOzaz** [comment]
This needs to be mentioned in the docs.
New build needs `gulp-cli` installed.
```
npm i -g gulp-cli
```
More here: https://github.com/gulpjs/gulp-cli/issues/84.

**Comment by aneuway2** [comment]
Thanks @YOzaz -- I ran into issues running that on the existing code i had.

Was able to blow it away and then git clone and run this successfully:
```npm install && npm i -g gulp-cli```
