### ISSUE TITLE
Prebid 1.27.0 increased 30% in filesize

### ISSUE THREAD

**Issue by benjaminclot** [prebid/Prebid.js#3169]
## Type of issue
Question

## Description
The Criteo adapter just increased our Prebid's compiled file size by 30% (from 150KB to 210KB)... 👎 

## Steps to reproduce
Use the Criteo adapter

## Platform details
Prebid.js 1.27.0

## Other information
On top of using [external JS](https://github.com/prebid/Prebid.js/pull/2370#issuecomment-396246559) and ignoring usersync preferences (no [`getUserSyncs()`](http://prebid.org/dev-docs/bidder-adaptor.html#registering-user-syncs) function whatsoever) the Criteo adapter now has to [sign](https://github.com/prebid/Prebid.js/pull/3110) the localStorage cache in order to safely [`eval()`](https://github.com/prebid/Prebid.js/pull/2370#issuecomment-381756477) it. So that means including an external library.

Are we to understand Criteo can do whatever they want @mkendall07?

**Comment by akira28** [comment]
Maybe it has already been asked, but why Criteo is allowed to use `eval`? Is the only adapter using it, and this causes the import of js-encrypt (more than 35kb gzipped)
