### ISSUE TITLE
Close pull request

### ISSUE THREAD

**Issue by omerko** [prebid/Prebid.js#3171]
## Type of issue
Question

## Description
I created a pull request that got some unnecessary files commited into it. While trying revert these file changes I got other file changes by mistake.
I want to close this pull request and open a new one instead since it got complicated to roll back changes now.
Can you please close this for me?
https://github.com/prebid/Prebid.js/pull/3090

Thanks

**Comment by jsnellbaker** [comment]
The requested PR has been closed.
