### ISSUE TITLE
Bundle size increased a lot in 1.27.0

### ISSUE THREAD

**Issue by felipemsantana** [prebid/Prebid.js#3174]
## Type of issue
Bug

## Description
From version 1.26.0 to 1.27.0 the bundle size increased by about 50%.
It was 126K and now it is 185K

## Steps to reproduce
Enter in http://prebid.org/download.html
Select the following adapters/module
- AOL
- Appnexus
- Criteo
- Rubicon
- Currency

Generate the bundle for versions 1.26.0 and 1.27.0, then compare the size.

**Comment by snapwich** [comment]
It's most likely from the Criteo adapter and its additional RSA encryption added in 1.27 for "FastBid."  It required the inclusion of some extra libraries: https://github.com/prebid/Prebid.js/pull/3110

**Comment by bwoolcott** [comment]
https://github.com/prebid/Prebid.js/issues/3169
