### ISSUE TITLE
Why does currency module includes DFP Express code?

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#3176]
Refer: http://prebid.org/dev-docs/modules/currency.html

In section, "Step 1: Bundle the module code", it is mentioned that "gulp build --modules=currency,bidderAdapter1,bidderAdapter2" 
This command will build the following files:
build/dist/prebid-core.js - the base Prebid code
build/dist/currency.js - additional code for the currency feature
build/dist/prebid.js - a combined file with the base Prebid code and the DFP express code

Can somebody explain why does it include DFP express code?

**Comment by pm-harshad-mane** [comment]
Hello @mkendall07 and @jsnellbaker ,
Can you answer this query?

**Comment by mkendall07** [comment]
Not sure. Have you looked at the code?

**Comment by snapwich** [comment]
@pm-harshad-mane I think that is a typo.  I think it means "a combined file with the base Prebid code and the currency code"

**Comment by pm-harshad-mane** [comment]
Thanks @snapwich
