### ISSUE TITLE
How to integrate DFP Express Module

### ISSUE THREAD

**Issue by soman** [prebid/Prebid.js#3178]
## Type of issue
question

## Description
DFP Ad does not trigger when i have using pbjs.express();

## Test page
http://stage.thisoldhouse.com/header_bidder/test_prebid_appnexus_with_dfp_express.html

### Expected results
I need to integrate DFP Express module with prebid version 1.18.0

**Comment by bretg** [comment]
You're right @soman, our Express module documentation left a lot to be desired. I've updated it. Please take a look at http://prebid.org/dev-docs/modules/dfp_express.html, particularly the new example, to see if it answers your questions.

**Comment by headerbidding** [comment]
@bretg  Could you please explain what DFP Express is. 
I use DFP (now called GAM) but I am mot familiar with the "Express" part.
I did a search, but could not find a definition. 
Please explain.

**Comment by headerbidding** [comment]
What is DFP Express?
I did a search, but could not find a definition.
Can anyone explain???

**Comment by bwoolcott** [comment]
@headerbidding The DFP Express module documentation is linked above (http://prebid.org/dev-docs/modules/dfp_express.html) and the actual module code is here: https://github.com/prebid/Prebid.js/blob/master/modules/express.js

**Comment by headerbidding** [comment]
@bwoolcott  Yes, I had looked at it. Unfortunately it does not explain what DFP Express is.

**Comment by bretg** [comment]
@headerbidding - I'm open to ideas as to how to improve this page, but it does explain that Express is "a simplified alternate installation mechanism for publishers that have Google Publisher Tag (GPT) ad calls in their pages."

It then goes on to list the key points:

* You build a Prebid.js package that contains the extra module code and optionally the page's AdUnits.
* One or two lines of javascript are added to a page already coded with GPT ad calls.
* The module intercepts ad behavior by overriding certain GPT APIs, coordinating the appropriate header bidding behavior, and then calling DoubleClick.
* Bidder parameters for the auction are determined by linking the GAM/DFP slots to the Prebid AdUnits
* Currently supports display formats only (i.e not video)

So - please help us understand what concept needs to be better defined.

**Comment by headerbidding** [comment]
Reading it over again, I finally understood it.
Thank you!

Suggestion: It would keep it more simple and consistent to replace "DoubleClick" with "GAM/DFP"

**Comment by bretg** [comment]
Good to hear. It's on our list to update the site to deal with the DFP name change... will handle "DoubleClick" then as well. Thanks.

**Comment by andreadd** [comment]
Thank you, very useful. So using the express module I don't have to create any order or creativity for Prebid in DFP? Ad units are enough? I just implemented the "minimal example".

Another thing, I think you forgot something here at the end, brackets are unbalanced.

2) Append the following lines to the file:

var adUnits = [
  {
    code: '/111111/slot-name',
    mediaTypes: {
      banner: {
        sizes: [[300,250]]
      }
    },
    bids: [
    {
      bidder: 'rubicon',
      params: { account: 1001, siteId: 113932, zoneId: 535510 }
    }
  }];
pbjs.express(adUnits);



Shouldn't it be instead:

      params: { account: 1001, siteId: 113932, zoneId: 535510 }
    },]
  }];
pbjs.express(adUnits);


Thank you!
