### ISSUE TITLE
How to integrate GDPR ConsentManagement Module

### ISSUE THREAD

**Issue by soman** [prebid/Prebid.js#3179]
## Type of issue
question

## Description
I have build prebid.js with consentManagement module but i am not clear about below lines:

pbjs.setConfig({
  consentManagement: {
    cmpApi: 'iab',
    timeout: 8000,
    allowAuctionWithoutConsent: false
  }
});

When i should use cmpApi: 'iab' and cpmAPi: 'static'?

## Test page
http://stage.thisoldhouse.com/header_bidder/test_prebid_undertone.html

### Expected results
Need help to integrate GDPR ConsentManagement Module.

**Comment by jsnellbaker** [comment]
@soman To use the GDPR consentManagement module, you'll need to a CMP setup separately on the page along side your Prebid code.

The CMP (Consent Management Platform) collects the user's consent information (if it's needed), and stores the information.  When Prebid and the consentManagement load, it'll make a request to the CMP's API and attempt to collect the consent information.  Once collected, the module will automatically disseminate to the bidders to forward the information along to their systems.

The module's config settings relate to how the module should perform (ie with the `timeout` and `allowAuctionWithoutConsent` fields) and what type of CMP request it should make (ie `cmpApi` - which the `iab` value tells the module to make the IAB compliant CMP API request).

If you already have the consent information previously stored or somehow available, then you can use the `static` value for the `cmpApi` field to directly pass the information to Prebid.  You'll have to format the consent data to the style that's expected, but it'll save the cost/effort of the additional request that's normally made to the CMP to collect the information.  

Additional information on that setup can be found here: http://prebid.org/dev-docs/modules/consentManagement.html#page-integration

Please let me know if you have any questions about the above.

**Comment by soman** [comment]
@jsnellbaker This is test page - https://stage.thisoldhouse.com/header_bidder/test_prebid_gdpr_with_test_placementid.html
How i will confirm the GDPR consentManagement module integration is perfect? Would you plz help me to debug module integration?

How to see bidderRequest object?

Thanks

**Comment by jsnellbaker** [comment]
If you append `?pbjs_debug=true` in the page URL's query section and open the console tab in the browser's developer tools, you should see the log messages from prebid as it loads on the page.  Part of these messages will include a message that looks like:
`INFO: Bids Requested for Auction with id: 63e89319-f203-4ac7-9873-4c386c1d67c5 : params`

There's an expandable object in that log line that contains the `bidRequest` array object for your prebid auction.  Note - this is the same as the `bidderRequest` object that's passed to each adapter (the name just changes later on).  If you dig into that object in the console, you'll see something like the following:
 
<img width="1037" alt="screen shot 2018-11-01 at 8 50 47 am" src="https://user-images.githubusercontent.com/31102355/47852819-49b0ad00-ddb3-11e8-8974-7bf4a5803560.png">

If you notice there's a property named `gdprConsent`.  This property object contains all the information that was requested by the consentManagement module from the CMP you implemented on the page.  In my case, I didn't see any prompts load from the CMP to ask my consent - so the `gdprConsent` object has no data.  If it was prompting information - these fields should be populated accordingly.
