### ISSUE TITLE
Pull request failed on CircleCI

### ISSUE THREAD

**Issue by omerko** [prebid/Prebid.js#3180]
## Type of issue
Question

## Description
I have a pull request that fails on CircleCI and I'm unable to know the reason:
https://github.com/prebid/Prebid.js/pull/3172

How can I know why it fails?

**Comment by jsnellbaker** [comment]
If you click on the details link of the ci/circleci check in the PR, it should load the status details as to why the test failed.

In this case, it appears there are linting errors in the code you're changing.  Here is a copy of the error message:
```
/home/circleci/Prebid.js/modules/undertoneBidAdapter.js
  115:1  error  Expected indentation of 8 spaces but found 10  indent
  116:1  error  Expected indentation of 8 spaces but found 10  indent
  117:1  error  Expected indentation of 6 spaces but found 8   indent
  118:1  error  Expected indentation of 6 spaces but found 8   indent
  119:1  error  Expected indentation of 8 spaces but found 10  indent
  120:1  error  Expected indentation of 8 spaces but found 10  indent
  121:1  error  Expected indentation of 6 spaces but found 8   indent

✖ 7 problems (7 errors, 0 warnings)
  7 errors, 0 warnings potentially fixable with the `--fix` option.
```

Please let me know if you have any additional questions about checking the circleci test.
