### ISSUE TITLE
xaxis / xhb adapter not working

### ISSUE THREAD

**Issue by nikkoi** [prebid/Prebid.js#3191]
## Type of issue
We're having extensive problems getting the xaxis / xhb adapter working in prebid 1.x+ versions. 

## Description
Everything is working fine in versions prior to 1, but we haven't been able to get a single impressions through with the 1.x version, even though we've done a lot of debugging with the xaxis team. 

## Steps to reproduce
Use the xhb adapter with prebid 1.x+

Is there anyone that can confirm that it actually works for them. And if so, did you have any problems setting it up?

**Comment by nikkoi** [comment]
Here is an example, two bids are available, but it doesn't even attempt to set them as key values. How is this possible? @daniel-hoffmann thoughts?

![screenshot-2](https://user-images.githubusercontent.com/1727721/47209461-158fc200-d399-11e8-9609-64ac8e93a22b.png)
![screenshot-1](https://user-images.githubusercontent.com/1727721/47209462-16285880-d399-11e8-957d-9190da7e48de.png)

**Comment by nikkoi** [comment]
Yeah, we got this sorted using custom adserver targeting and always use bids. But if this is intended way of working, I would at least document it in the adapters .md file, that it doesn't work without specifying custom targeting.

**Comment by jsnellbaker** [comment]
This should be addressed in the next release (1.31.0) via the above PR.
