### ISSUE TITLE
Make AudienceNetwork adapter sizes configurable

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#3194]
## Type of issue
Feature Request

## Description

Rubicon Project hosts Prebid.js packages for publishers, some of whom have chosen to use the AudienceNetworkBidAdapter. The problem with this adapter as it stands is that it limits sizes to precisely two:
```
const isValidSize = size => includes(['300x250', '320x50'], size);
```

Some publishers, however, want to monetize other sizes through AudienceNetwork, which would require hacking the adapter to allow more sizes. Such hacks are unsupportable for integrators like us -- imagine upgrading weekly to the next version of Prebid.js and then having to re-apply dozens of publisher-specific size hacks.

@lovell - is this size limitation part of AudienceNetwork's terms? If not, it's pretty clear the solution is to allow the publisher to configure the sizes. e.g.

```
pbjs.setConfig({
   "audienceNetwork": {
       "sizes": [[300, 250], [300, 600], [720x90]]
   }
```
There is precedence for adapter-specific config like this.

Then in the code, you would just call getConfig to see if there's an expanded size list.

Would you be willing to support this config?

**Comment by lovell** [comment]
Hello, I've been told that any publishers requiring other sizes should get in touch with their Facebook Audience Network contact for more information.
