### ISSUE TITLE
Amazon parameters question?

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#32]
In the documentation the only param needed is `aaxId` but i dont see any reference to it in the amazon adaptor just a reference to `aid`, so it must be aaxId or aid, maybe aid just refers to the slot id but im confused.

http://prebid.org/bidders.html#amazon

**Comment by ialex** [comment]
Correct param is `aid` seems that doesnt matter the ammount of ad unit you have on your page you should always include just one configuration for all ads. correct me if im wrong.

**Comment by mkendall07** [comment]
@ialex - you are correct. Feel free to update the example page with a PR.

**Comment by ialex** [comment]
i will
