### ISSUE TITLE
Bid Caching Performance?

### ISSUE THREAD

**Issue by godoggie** [prebid/Prebid.js#3205]
## Type of issue
Question

## Description
Upon analyzing pv/impression and cpm performance between v0.34 and v1.27 I do not see any significant difference. Per documentation (link below) Prebid 1.x is now leveraging client side bid caching?  I am working within all parameters noted (same page/ad unit/user/ttl) and have also validated that previous (cached) bids are winning occasionally.

So is anyone seeing a significant bump from bid caching or am I missing something here?
thanks.

## Other information
http://prebid.org/dev-docs/faq.html#does-prebidjs-cache-bids

**Comment by bretg** [comment]
PBJS re-uses bids only in specific scenarios -- the page has to be set up to refresh adunits. Otherwise, you wouldn't/shouldn't see any difference.

Does the page you're testing do adunit refreshes?

**Comment by godoggie** [comment]
Yes, regular refreshes on ad units. Same page, same user/session. 
Tracing code reveals a VERY low percentage of bids from a previous auctions ever win and no real bump in CPM from competing ad server supply.

**Comment by patmmccann** [comment]
What's a good way to validate cached bids win occasionally?
