### ISSUE TITLE
Prebud code freeze?

### ISSUE THREAD

**Issue by omerko** [prebid/Prebid.js#3208]
## Type of issue
Question

## Description
Hi
I wanted to know if Prebid enforces some sort of deployment freeze practice at this time of the year, since I know a lot of companies in the industry have such policy.

I want to know to be aware if there is a time were I won't be able to release adapter changes.
Thanks

**Comment by mkendall07** [comment]
There is no defined code freeze policy, however, based on member company's availability there could be delays in merging with folks on holiday etc.

**Comment by omerko** [comment]
Got it
Thanks
