### ISSUE TITLE
Prebid Video - 'id' referencing?

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#3209]
It would seem the 'id' needs to be passed correctly to Prebid video outstream formats. This is fine, but we load Prebid JS into a friendly iframe to prevent conflicts with a number of our publishers. Taking a look at some of the adapters (AppNexus for example) the 'doc' [document] reference is not passed. It might, therefore, be able to find the correct div element in the topmost window [window.top].

I've not spent a huge amount of time checking each adapter, but it would at least seem that some of the major ones would be incorrectly referencing the ad unit div element: -

```
  renderer.setEventHandlers({
    impression: () => utils.logMessage('AppNexus outstream video impression event'),
    loaded: () => utils.logMessage('AppNexus outstream video loaded event'),
    ended: () => {
      utils.logMessage('AppNexus outstream renderer video event');
      document.querySelector(`#${adUnitCode}`).style.display = 'none';
    }
  });
  return renderer;
```

https://github.com/prebid/Prebid.js/blob/24dd19aef0867972544e9f40fa18f2fa2f4578e4/modules/appnexusBidAdapter.js#L213

**Comment by mkendall07** [comment]
@cwbeck 
Are you asking if there is a way to pass `document` into the AppNexus renderer? If so, we currently do not support that. I'll chat with the video team and see if it's a possibility.

**Comment by cwbeck** [comment]
@mkendall07 -My original question was around the ability to pass ```document```. I'm now thinking of changing the prebid namespace to avoid issues instead of using an iframe. I don't suppose if you know if prebid namespaces are fully supported by renderers?
