### ISSUE TITLE
Publish latest version(s) to NPM

### ISSUE THREAD

**Issue by scottdonaldson** [prebid/Prebid.js#321]
I noticed the version on NPM is a bit out of date (v0.5.0: https://www.npmjs.com/package/prebid.js). Could you publish the latest released versions to NPM?

**Comment by mkendall07** [comment]
@scottdonaldson 
Yes we are going to update as soon as we release the `0.8.1` tag

**Comment by mkendall07** [comment]
The latest tag has been published to NPM.
