### ISSUE TITLE
[question] ANOutstreamVideo.js docs and source-code?

### ISSUE THREAD

**Issue by jcswart** [prebid/Prebid.js#3211]
## Type of issue
Question about *ANOutstreamVideo.js* renderer.

## Description

I'm trying to debug an issue with rubicon video, I'm using http://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js as the renderer but it is difficult to debug because there is: no documentation, no available source code repository, or at the very least non-minified code.

I have completed exhausted my google-fu on this one and any help would be appreciated.

**Comment by mkendall07** [comment]
@jcswart 
It's not open source code. What's your issue? Thanks

**Comment by jcswart** [comment]
Would you mind providing a specification for `ANOustreamVideo.renderAd` function? What are the possible key/value combinations for the object argument.

Thanks!

**Comment by mkendall07** [comment]
@jcswart 
Sorry for the delayed response. you can see the params here:
https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L498

**Comment by lanceloti** [comment]
To work with Rubicon you'll need to implement a custom render.

https://github.com/prebid/Prebid.js/issues/2957
