### ISSUE TITLE
How to use brealtime with appnexusAst?

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#322]
Hi,

Using prebid checked out @ tag/0.8.0, we seem to be unable to alias appnexusAst with brealtime?

```
"adapters": [
    "adform",
    "aol",
    "appnexusAst",
    "indexExchange",
    "pulsepoint",
    "rubicon",
    "sovrn",
    "brightcom",
    "sonobi",
    { "appnexusAst": {"alias": "brealtime"} }
]
```

Any ideas? All other adapters in that list are tested and working as expected.

C.

**Comment by mkendall07** [comment]
hey @cwbeck - this actually doesn't work yet sorry. Still figuring out what the new bidder interface will look like with aliasing...

**Comment by ehoch** [comment]
@mkendall07 Any update here? We'd love to switch to appnexusAst, but since it overrides the appnexus bidder and doesn't support aliasing, I can't figure out how to run the Ast adaptor alongside brealtime and DistrictM (both of which alias the original appnexus bidder)

**Comment by ialex** [comment]
What's the advantage of using AppnexusAst adaptor? my main complain is that the regular adaptor uses 1 request per bid and if you have multiple bidders (pagescience, districtm, appnexus, brealtime) using it they can take a lot of time to respond if you have many call (they usually respond less than 200ms).

I would like that it handles everything in one request like the sovrn adaptor does.

**Comment by ehoch** [comment]
@mkendall07 Gentle poke here to find out the status. For bidders aliasing AppNexus (e.g. bRealTime, DistrictM, etc), what is preventing us from running them via the Ast bidder as well?

**Comment by BartVB** [comment]
Any news? We're currently using two aliassed AppNexus bidders. This currently results in 6 separate requests to AppNexus. Would be fantastic if we could reduce this to one or two bid calls.

**Comment by mkendall07** [comment]
all, sorry for the delays here. We are working on a new AppNexus bidder adapter that will support aliasing and also single call for multi placement. Thanks

**Comment by ehoch** [comment]
@mkendall07 Out of curiosity, will all of the various aliased AppNexusAst bidders be combined into a single request? As in a single request will get results for all of the bidders at once?

I heard this was supported with the AST endpoint if member ids were specified. Curious if that will make the cut to Prebid.js.

**Comment by mkendall07** [comment]
@ehoch 
No, unfortunately it will not be able to support that. The limitation is on the endpoint, we cannot submit multiple member ID auction requests. We will need to continue to alias and submit multiple requests in that case (although, the placements will be grouped).

**Comment by mkendall07** [comment]
This is resolved on master with https://github.com/prebid/Prebid.js/commit/80d89d73e6952abb32bace4cce2e4ba248918539

**Comment by sonemic** [comment]
This doesn't seem to be resolved.  If we edit adapters.json to be, for example

```
[
    "sovrn",
    "springserve",
    {
      "appnexusAst": {
        "alias": "brealtime"
      }
    },
    {
      "appnexusAst": {
        "alias": "districtm"
      }
    }
]
```

In the console, we see multiple instances of "ERROR: undefined ad type not supported" that occurs in handleResponse() and no bids are processed.

**Comment by matthewlane** [comment]
@sonemic, I'm looking into the errors you are seeing. Would you mind letting me know the bidder params you are using? Thanks

**Comment by ehoch** [comment]
I'm actually running into the same issue when I alias for bRT, District M, etc when testing the new Ast adaptor. I'm only setting placementId with them.

**Comment by mkendall07** [comment]
@ehoch 
Can't seem to replicate the behavior. Can you email me your config objects?

**Comment by mercuryyy** [comment]
Same Issue here ("ERROR: undefined ad type not supported"),  @mkendall07 i'v sent you an email with a test page to see the behavior

**Comment by mercuryyy** [comment]
looks like this solved the problem:

when building list-of-adapters 

use

    {
      "appnexus": {
        "alias": "brealtime"
      }

not 

{ "appnexusAst": {"alias": "brealtime"} }

**Comment by mkendall07** [comment]
@mercuryyy 
That config you posted will not use the appNexusAst adapter (which is fine if you don't want to use it). 

@ehoch @cwbeck 
It looks like this error is just kicked out when a no bid is returned from the adserver, however, it's not actually broken. I'm more concerned if you are seeing decreased performance due to any updates we made. Where you using appnexusAst before or just appnexus?

**Comment by mercuryyy** [comment]
Thanks @mkendall07 i was under the impression it is the same, Im not able to find any documentation detailing the differences or which is preferred to use if using brealtime or another supported appnexus partner.

**Comment by cwbeck** [comment]
@mkendall07 we used appnexus before, but moved to appnexusAst as we required friendly frames for our direct campaigns. Not looked into performance, but old appnexus adapter will not actually work for our needs. We can use it for brealtime and other partners who require it however.

**Comment by sonemic** [comment]
@mkendall07 :
Just an update: we fixed the console logging issue (basically the same change that @matthewlane submitted), rebuilt prebid.js and tried using it in production for a day, and our revenue from appnexusAst-based bidders dropped 75% vs appnexus. If I had to guess, I'd say that correlates with only being able to win one bid per page rather than per unit, but I'm not sure.  To answer your previous question: with bRealTime, we have a placementId param, and for District M, a placementId and seatId (the latter param might not actually be required, but I doubt it's related to this issue).

**Comment by mercuryyy** [comment]
I also see the same results as sonemic is describing, using  brealtime with appnexus gets a much higher bid response rate then using it with appnexusAst

**Comment by mkendall07** [comment]
@sonemic 
Can you please reach out to AppNexus support? We'd like to investigate this issue. Thank you.

**Comment by sonemic** [comment]
Sure, just submitted a ticket with AppNexus support.

**Comment by mkendall07** [comment]
@sonemic 
Just to let you know, the appnexusAST adapter when you tested it was not sending cookies with the request. We have fixed it in master, if you want to try again.

**Comment by sonemic** [comment]
@mkendall07 thanks! I can confirm that it works properly now; we've switched to using the AST adapter exclusively.

**Comment by chaqu170** [comment]
@sonemic @mercuryyy - I'm curious how appnexusAst is performing for you now that some time has passed?

**Comment by kumasauce** [comment]
@sonemic @mercuryyy 
Hey! Did you continue to use the AppnexusAST adapter exclusively? Switching exclusively to AppnexusAST for us lowers bid response rate and average CPM slightly, but we haven;t run it for more than 1-2 days. Can you please follow up on your results when you get a moment? Thanks!

**Comment by sonemic** [comment]
We are not using it at the moment (for completely unrelated reasons that are temporary) - but yes, we used it for months with no change in CPMs, and we were happy with how much it reduced the amount of requests and bandwidth consumed.
