### ISSUE TITLE
Feature request - extracting canonical URL

### ISSUE THREAD

**Issue by omerko** [prebid/Prebid.js#3221]
## Type of issue
Feature request

## Description
I need to retrieve the canonical url from the <link rel="canonical".. > element <link (https://www.w3.org/TR/capability-urls/#canonical-urls)

Up till now I used the utils.getWindowTop() function to get the document and run a query on the top level DOM.
But since this function is about to get deprecated, there needs to be some alternative to get the canonical URL.
I suppose it's a common thing for adapters to do, having this as a utility function can be useful.

**Comment by jsnellbaker** [comment]
This issue was fixed and included in the 1.31.0 release (that just came out yesterday).  If you have any additional questions/concerns on this topic, please let us know and we'll be happy to help.
