### ISSUE TITLE
MediaTypes are not respected by multiple bidders

### ISSUE THREAD

**Issue by dugwood** [prebid/Prebid.js#3222]
## Type of issue
Feature request

## Description
Setting up mediatypes with something other than `banner` is really difficult: AppNexus and Teads (if not other) are answering with `banner` to a mediaTypes request with only `video`

## Steps to reproduce
Ask for only `mediaTypes=video`, as shown here:
http://prebid.org/examples/video/outstream/outstream-no-adserver.html
=> answer doesn't take care of the video media type.

## Test page
https://www.sortiraparis.com/prebid-test#debug-ads-for-skyboard-670168054&pbjs_debug=true
And look for the «Zone 22974»

### Expected results
Only `bid.mediaType = 'video'` should be returned as we asked only for that:
![image](https://user-images.githubusercontent.com/5517743/47436304-89213d00-d7a6-11e8-8ec5-d1c5f1c9a33a.png)

### Actual results
```
Zone 22974
   25 Enabling format
   26 Added div#unq_fmt_22974_3
   33 Available width: 624px
   33 Bidders: teads:v, appnexusAst:v    <= here the «v» stands for «video» only
  626 teads          banner (1x1)     : 0      (net)   Time: 175   <=  a 1x1 banner!!
  746 appnexusAst    banner (300x250) : 0      (net)   Time: 300   <= a 300x250 banner!!
 1155 No Prebid winner, fallback to house ads
```
`banner` is seen from time to time, along with wrong sizes (1x1 instead of the video size sent).

## Platform details
Prebid.js: 1.28.0
Browser / OS: not relevant
node, npm: not relevant

## Other information
These bids should be discarded. Although it would be great to be able to setup various mediaTypes depending on the bidder. For example I want AppNexus to serve video, but Teads to serve native, on the same adUnit.

**Comment by bretg** [comment]
@mkendall07 - perhaps a core change to enforce the media is desirable here?

**Comment by mkendall07** [comment]
seems reasonable to enforce `mediaType` at the core level since we can't know what any bidder will return.
