### ISSUE TITLE
Rubicon and differnet mediaTypes

### ISSUE THREAD

**Issue by salvoaranzulla** [prebid/Prebid.js#3246]
## Type of issue

It's a bug with Prebid 1.30.0 and Rubicon adapter.

## Description

I'd like to run different mediaTypes (banner and video "outstream") in the same adUnit. I'd like tu run display+outstream with AppNexus and just banner with Rubicon.

If I edit my mediaTypes in this way:

                    mediaTypes: {
                        video: {
                            context: 'outstream'
                        },
                        banner: {
                            sizes: [
                                [300, 250],
                                [336, 280]
                            ]
                        }
                    },

Rubicon shows us this error:

WARNING: Rubicon bid adapter Warning: outstream video is sending invalid size id, converting size id to 203.
WARNING: Rubicon bid adapter Warning: video and banner requested for same adUnit, continuing with video request, multi-format request is not supported by rubicon yet.

So their fix https://github.com/prebid/Prebid.js/pull/3167 doesn't work. 

## Steps to reproduce

If you need, here my configuration: https://pastebin.com/4n3thFxu

**Comment by robertrmartinez** [comment]
@salvoaranzulla 

Hi! We will get a permanent fix in for the next PBJS release `1.31.0` this coming Tuesday.

However, if you want an immediate workaround you can try to specify the banner sizes you want inside of the rubicon params object like so:

```
{
  bidder: 'rubicon',
  params: {
    accountId: '14710',
    siteId: '81044',
    zoneId: '396682',
    sizes: [15, 16]
  }
}
```

Where 15 and 16 are the rubicon size ids we map from your banner sizes in your example.

This effectively overrides the multiformat adUnit to be banner for Rubicon purposes.

Here is our full list of supported size mappings:

```
{
  1: '468x60',
  2: '728x90',
  5: '120x90',
  8: '120x600',
  9: '160x600',
  10: '300x600',
  13: '200x200',
  14: '250x250',
  15: '300x250',
  16: '336x280',
  19: '300x100',
  31: '980x120',
  32: '250x360',
  33: '180x500',
  35: '980x150',
  37: '468x400',
  38: '930x180',
  39: '750x100',
  40: '750x200',
  41: '750x300',
  43: '320x50',
  44: '300x50',
  48: '300x300',
  53: '1024x768',
  54: '300x1050',
  55: '970x90',
  57: '970x250',
  58: '1000x90',
  59: '320x80',
  60: '320x150',
  61: '1000x1000',
  64: '580x500',
  65: '640x480',
  67: '320x480',
  68: '1800x1000',
  72: '320x320',
  73: '320x160',
  78: '980x240',
  79: '980x300',
  80: '980x400',
  83: '480x300',
  94: '970x310',
  96: '970x210',
  101: '480x320',
  102: '768x1024',
  103: '480x280',
  108: '320x240',
  113: '1000x300',
  117: '320x100',
  125: '800x250',
  126: '200x600',
  144: '980x600',
  159: '320x250',
  195: '600x300',
  199: '640x200',
  213: '1030x590',
  214: '980x360',
  229: '320x180',
  232: '580x400',
  257: '400x600'
}
```


Please reach out to me if you have any questions!

Thank you again for bringing this issue up.
