### ISSUE TITLE
Refresh bids not working on IE11 - v1.28.0

### ISSUE THREAD

**Issue by arjitsachdeva** [prebid/Prebid.js#3259]
## Type of issue

We're seeing a console error in the refreshBids call on all ad units, only on IE11. It is working fine on all other browsers including Edge. Screenshot attached:

<img width="1419" alt="screen shot 2018-11-03 at 1 46 39 am" src="https://user-images.githubusercontent.com/5327819/47938705-efc2fb00-df0a-11e8-8cf7-2312ae1968d9.png">

The function for refresh is the standard one from prebid examples:

`function refreshBids() {
 pbjs.que.push(function() {
 pbjs.requestBids({
 timeout: PREBID_TIMEOUT,
 bidsBackHandler: function() {
 pbjs.setTargetingForGPTAsync();
 googletag.pubads().refresh();
 }
 });
 });
 }
`

## Platform details
Prebid = v1.28.0 , browser = IE 11, OS = Windows 10.

**Comment by mkendall07** [comment]
hmm are you sure the error is not from `ima3.js` ? We do test our code against IE 11 so I'd be surprised if this issue was inside prebid.js.

**Comment by arjitsachdeva** [comment]
Thanks for the response, @mkendall07 . Yes, I don't think it's an ima issue because the same refresh code was working fine on all browsers and broke only on IE11. 

However, I just updated prebid to the latest v1.30 release and it seems that the refreshBids function worked well on IE 11. I'll keep you posted after a couple more tests for a confirmation.
