### ISSUE TITLE
How to check prebid performance?

### ISSUE THREAD

**Issue by soman** [prebid/Prebid.js#3262]
## Type of issue
question

## Description
How to check prebid performance? Would you please give some information so that i can check prebid performance. I have added 2 test page. One is with dfp express and another one is without dfp express.

## Test page
With DFP Express:
https://stage.thisoldhouse.com/header_bidder/test_prebid_appnexus_with_dfpexpress.html?pbjs_debug=true

Without DFP Express:
https://stage.thisoldhouse.com/header_bidder/test_prebid_appnexus_without_dfpexpress.html?pbjs_debug=true

**Comment by headerbidding** [comment]
What is DFP Express?

**Comment by bwoolcott** [comment]
@soman Have you looked through the prebid.org troubleshooting documentation and followed those steps?

http://prebid.org/dev-docs/prebid-troubleshooting-guide.html
http://prebid.org/dev-docs/troubleshooting-tips.html
http://prebid.org/dev-docs/common-issues.html
http://prebid.org/videos/
etc.

**Comment by bretg** [comment]
You can also make use of the "Header Bidder Expert" chrome extension -- https://chrome.google.com/webstore/detail/headerbid-expert/cgfkddgbnfplidghapbbnngaogeldmop?hl=en

@headerbidding - DFP Express is the optional module described at http://prebid.org/dev-docs/modules/dfp_express.html
