### ISSUE TITLE
Logging data from bidWon, bidRequest, bidTimeout events to a database. 

### ISSUE THREAD

**Issue by mjwhaley** [prebid/Prebid.js#3268]
We are starting to log some of the data from the following events into Google BigQuery 

bidWon
bidRequest
bidTimout

We are looking to be have much more granular knowledge of SSP bids/timeouts and bids won revenues. 

**This is where we are facing some issues**. The first step to this is being able to reconcile bidWon events  at some level to SSP revenue data. From current stats we are seeing around 15/20% less impressions and revenue in our data table compared to the SSP data. 

All our stats show that our data collection servers are running perfectly. Is there a possibility of the bidWon event not always happening and thus not being able to be recorded?

Any help would be greatly appreciated.

**Comment by jaiminpanchal27** [comment]
@mjwhaley 
Since you specifically asked for bidWon event, creative rendered is firing some impression tracker and the same is not reflected via analytics adapter.

Which analytics adapter are you using ? There are some who queue up all the data and hit the endpoint on AUCTION_END event.

**Comment by mjwhaley** [comment]
@jaiminpanchal27 Thanks for your response. 

We aren't using an analytics adapter at all. We are recording the data and then going to use Google Data Studio and Salesforce Analytics via Google BigQuery to visualise the data. 

Right now it's the bidWon event we are focusing on. I'm expecting our records to be slightly higher than the SSP data and thus we should be able to create live ish data on revenues etc. Do you think this is a realistic goal?

Have you also had any experience of any of the analytics adapters and if so what have been your experiences? 

One of the dev guys working on this project will also jump in with some specifics on exactly how we are collecting the data.
