### ISSUE TITLE
banner mediaTypes always added in bid despites provided mediaTypes in adUnits config

### ISSUE THREAD

**Issue by jdelhommeau** [prebid/Prebid.js#3269]
## Type of issue
Bug

## Description
If you try to setup an adUnit with mediaType video only, the mediaType banner is automatically added when calling the different bidders, which results in bidders making call for both video and banner instead of video only

## Steps to reproduce
1 - Create a basica prebid test page with a video mediaTypes:
pbjs.addAdUnit({
    code: 'video1',
    mediaTypes: {
        video: {
            context: 'outstream',
            playerSize: [640, 480]
        }
    },
    renderer: {
        options: {
            adText: 'This text was configured in the ad unit',
        }
    },
    ...
});

2 - check which mediaTypes are passed to bidders. It will contain both banner and video

## Test page
The bug is present on the demo page for outstream on prebid.org: http://prebid.org/examples/video/outstream/outstream-no-adserver.html

### Expected results
Only video mediaTypes should be passed to bidders, not banner

### Actual results
both banner and video mediaTypes are passed to bidders

## Platform details
Tested on prebid 1.30. It affects all bidders

## Other information
I was able to track down the issue to this part of the code:  https://github.com/prebid/Prebid.js/blob/7fe95d89464cbc95adf3446cd8e39bb499f2c321/src/adaptermanager.js

the getBids function. It seems to be adding banner mediaTypes when building the bid object that will be passed to bidders.

**Comment by snapwich** [comment]
Definitely a bug.  Made a pull-request with a fix.

**Comment by ReinoutStevens** [comment]
I submitted a similar issue a couple days earlier: https://github.com/prebid/Prebid.js/issues/3256
You may want to close my report

**Comment by benjaminclot** [comment]
Maybe for 2.0: being able to force a mediatype at the bid level could be a great feature.
