### ISSUE TITLE
bidResponse fired after auctionEnd fired before timeout 

### ISSUE THREAD

**Issue by tianyi-cong** [prebid/Prebid.js#3270]
We recently upgrade Prebid from 0.34 to 1.24, I noticed bidsBackHandler got triggered before the timeout, but there are more bid responses come in after that. That never happened before, so I'm trying to figure out what could be the issue as it should only be triggered either timeout or got all bid responses back.

With 0.34, When bidsBackHandler got triggered, I can see all the bids(include fill and no fill) in the bidResponses, but with 1.24, I can only see some of the bids.

![screenshot-newtab-2018 11 06-18-46-04](https://user-images.githubusercontent.com/2996196/48101245-5cccde00-e1f4-11e8-80d7-80e81c115680.png)

Any idea what I missed?

**Comment by jaiminpanchal27** [comment]
@tianyi-cong There was a bug introduced in 1.24 release. We did a patch release https://github.com/prebid/Prebid.js/releases/tag/1.24.1

Here is the fix we did https://github.com/prebid/Prebid.js/pull/3096

**Comment by tianyi-cong** [comment]
Ah, I see. I need to update the library ASAP then. I guess I need to pay more attention to the new releases. Thanks for the help @jaiminpanchal27!
