### ISSUE TITLE
Update logic in sizeMapping - sizesSupported respects active label(s) in adUnit

### ISSUE THREAD

**Issue by jsnellbaker** [prebid/Prebid.js#3277]
## Type of issue
Feature Request

## Description
The interaction between the `sizes` fields in an `adUnit` (whether `adUnit.sizes` or `adUnit.mediaTypes.banner.sizes`) and the sizeConfig is not entirely intuitive and (depending on your perspective) does some unexpected things in certain scenarios.  The logic that's used in these scenarios should change.

### Summary of the proposed changes
We would have the labels defined in the `adUnit` help influence which sets of sizes are read from the sizeConfigs and determine when the filtering on the sizes are done.  

Specifically:
* Instead of reading all the sizes from **all** the active configs, we would instead read all the sizes from only the configs that were active and had a label in the `adUnit`.
* If multiple configs were active and multiple matching labels were used in an adUnit, then we would pool together the sizes from those specific active configs as used the combined list as the filter.
* If the labels were defined but didn't match an active config, the the adUnit would not be included in the request.
* When no labels are defined in an adUnit - the sizes are not filtered by the sizeConfig.

This would help to support more tricky/complex scenarios that require dynamic configs and could help the underlying logic for the sizeConfig to be more intuitive for end-users.

### Some additional context on these scenarios
One scenario is when multiple configs are considered active/valid by the `mediaQuery` - the list of sizes in the `sizesSupported` fields from **all** of these active configs are pooled together into one giant list.  This new list is used as the filtering mechanism against the sizes defined in the adUnit object (whether the `mediaTypes.banner.sizes` or `adUnit.sizes`).  

The fact that **all** configs are used can lead to some confusion.  On the surface - it's easy to assume that the label you defined in the `adUnit` (or `adUnit.bids`) would have influential factor on the sizes that are chosen from the sizeConfigs to act as a filter.  You set a label for a specific sizeConfig, thus associating it to those sizes.  Instead these labels do not play at part at all when we determine the list of permitted sizes; they really only act as a separate filter used later in the logic.

Another scenario is when you have the sizeConfig defined but an adUnit does not use a label.  The `sizes` from your adUnit still get filtered by the sizeConfig based on whichever config matched the mediaQuery.  If a label wasn't included, a user may expect that the sizeConfig would not affect the adUnit object at all.

The root of these expectations is that you link a label with a set of sizes with a particular screen dimension when you setup the config.  Because all these fields are linked in the same config, it's easy to assume this link still persists when you go to apply the label in the adUnit config.

### Use Case Reference
To demonstrate an example in reference to the points raised in the context, suppose the following setup...

**sizeConfig**
```
"sizeConfig": [
          {
            "mediaQuery": "(min-width: 1024px)",
            "labels": ["rail"],
            "sizesSupported": [[300, 250], [300, 600]]
          }, {
            "mediaQuery": "(min-width: 1024px)",
            "labels": ["desktop"],
            "sizesSupported": [[728, 90], [970, 90], [970, 250]]
          }, {
            "mediaQuery": "(min-width: 728px) and (max-width: 1024px)",
            "labels": ["tablet"],
            "sizesSupported": [[300, 250], [320, 50], [320, 100], [728, 90]]
          }, {
            "mediaQuery": "(min-width: 0px) and (max-width: 728px)",
            "labels": ["phone"],
            "sizesSupported": [[320, 50], [320, 100], [300, 250]]
          }, {
            "mediaQuery": "(min-width: 1440px)",
            "labels": ["post-large"],
            "sizesSupported": [[728, 90]]
          }, {
            "mediaQuery": "(min-width: 0px) and (max-width: 1440px)",
            "labels": ["post-small"],
            "sizesSupported": [[320, 50], [320, 100], [300, 250]]
          }
        ]
```

**one adUnit** (of many that use different combinations of sizes/labels):
```
{
        "labelAny": ["desktop", "tablet", "phone"],
        "code": "dfp-post-001-0",
        "bids": [
          {
            "bidder": "appnexus",
            "params": {
              "placementId": 13825632
            }
          }, {
            ... // other bids here
          }
        ],
        "mediaTypes": {
          "banner": {
            "sizes": [[320, 50], [728, 90], [300, 250], [320, 100], [970, 90], [970, 250]]
          }
        }
      },
```

The adUnits are setup in such a way to dynamically handle different environments, so we list all the potential sizes and then would rely on the sizeConfig to only use the ideal sizes for that environment.

So suppose we load the page with a laptop that had a screen width of 1600px.  

With today's logic, this would activate 3 of the sizeConfigs: 'desktop', 'rail', 'post-large'.  These 3 configs would result in a pool of permitted sizes like the following `[[728, 90], [970, 90], [970, 250], [300, 250], [300, 600]]`.

When we use this pool of permitted sizes as a filter against the adUnit - that would in turn result the following sizes to be used in the request object for this bid: `[[728, 90], [970, 90], [970, 250], [300, 250]]`.  

This is where the confusion can enter.  When we look at the adUnit, we could assume the `desktop` config would take effect and would result in seeing only the sizes from that config get included in the bidRequest.  Instead we have this 'seemingly' random `[300, 250]` enter in the bidRequest and it's not obvious that its because of the `rail` config.

With the new logic - would we only have the `[[728, 90], [970, 90], [970, 250]]` sizes included in the request because the `desktop` was tied to the adUnit.

Please let me know of any feedback on the above; especially of any scenarios that do rely on the existing logic that's used when multiple configs are active.

**Comment by benjaminclot** [comment]
Isn't this more a bugfix than a feature? 🤔

**Comment by patrick-mcdougle** [comment]
Can we address concerns in #2860 as part of requirements gathering for this?
