### ISSUE TITLE
Prebid 2.0 - List of Planned Changes

### ISSUE THREAD

**Issue by jsnellbaker** [prebid/Prebid.js#3278]
## Type of issue
Feature Request

## Description
The 2.0 release of Prebid.js will be coming in relatively near future.  Below is a running list of items that are currently slated to be included in the 2.0 release of Prebid.js.  

- add an enable/disable toggle to bid caching and turn off bid caching by default. 

The goal of the 2.0 release is to include a number of key updates that are considered breaking changes; it is not planned to be a large release like 1.0 was.

If there are any other key items/issues that need to be included that would require a breaking change, please share here so we can review.

**Comment by snapwich** [comment]
I noticed you mentioned fixing the confusing interaction between `adUnit.sizes` and `adUnit.mediaTypes.banner.sizes` in the size mapping issue.  Maybe 2.0 is a good time to remove `adUnit.sizes` entirely?

**Comment by mkendall07** [comment]
We are going to proceed with a very small change with 2.0, with the only publisher facing breaking change being to disable bid caching by default.

**Comment by bretg** [comment]
Prebid.js 2.0 released last week. Closing the tracking issue.
