### ISSUE TITLE
Benefit of Publisher Common ID

### ISSUE THREAD

**Issue by soman** [prebid/Prebid.js#3288]
## Type of issue
question

## Description
I have created a test page. I am able to see below json from pbjs.requestBids
"crumbs":{
         "pubcid":"c4a4c843-2368-4b5e-b3b1-6ee4702b9ad6"
      },

I will be very happy if someone explain to me what is the benefit of 'pubcid'?

## Test page
https://stage.thisoldhouse.com/header_bidder/test_prebid_appnexus_with_publisher_common_id.html?pbjs_debug=true

**Comment by bretg** [comment]
It's just a way to create a pub-specific advertising ID for a user -- provided as a service to publishers so they don't have to do it themselves.

Please watch https://github.com/prebid/Prebid.js/issues/3046 for the implementation of an ID module that should have broader impact.
