### ISSUE TITLE
Mobile Interstitial with Rubicon

### ISSUE THREAD

**Issue by Deimos01** [prebid/Prebid.js#329]
Hi guys,

I'm trying to bid on the format Mobile Interstitial Portrait (320x480) with rubicon.
The bid is working, i have a lot of bids in my rubicon report, but it's impossible to display the ad.
I saw this variable in prebid.js : 
```
var RUBICON_SIZE_MAP = {
	    '728x90': 2,
	    '160x600': 9,
	    '300x600': 10,
	    '300x250': 15,
	    '320x50': 43,
	    '300x1050': 54,
	    '970x250': 57
	  }; 
```

I added '320x480': 67, in the size_map, but it's not working.

Here my error 
![image](https://cloud.githubusercontent.com/assets/5635647/14738939/e2dd44ae-0884-11e6-96f3-6bfda9b33db9.png)

Dimensions array response is false. How can i do ?

Thank you !

**Comment by mhc-gh** [comment]
Please contact your Rubicon Account Director and they will add the server side configuration that needs to be set in addition to the client side addition to the size map.

**Comment by Deimos01** [comment]
Hi @mhc-gh 

Thank you for your answer.

I did what you told me but i still have the same error (48 hours after the Rubicon server side activation).
Should i change something else in the client side configuration exept adding the format size like i did in the size map ?

**Comment by Deimos01** [comment]
It was a problem of CDN cache of Rubicon JS
