### ISSUE TITLE
TripleLift creative ID issue

### ISSUE THREAD

**Issue by smartbidder1** [prebid/Prebid.js#3290]
## Type of issue
bug

## Description
when requesting an ad from triplelift bidder the response contains id, impid and nurl.
none of those parameters are unique per ad (creative id), and we can't identify an ad in that way (to blacklist for example).
any other partner are indeed returning a creative id (appnexus, Rubicon etc..)
https://github.com/prebid/Prebid.js/issues/2374 for example had the same issue but they have fixed it already (very fast I might say).

@brittanyzellman

**Comment by brittanyzellman** [comment]
@smartbidder1 
https://github.com/prebid/Prebid.js/pull/3324
sorry for the delay here.

**Comment by bretg** [comment]
Closing this issue, released with 1.34
