### ISSUE TITLE
How do I know if a user has clicked on the skip button or an outstream video Ad has ended? 

### ISSUE THREAD

**Issue by freegames66** [prebid/Prebid.js#3293]
How do I know if a user has clicked on the skip button or an outstream video Ad has ended? 
Are there any events for them?

![capture](https://user-images.githubusercontent.com/33347377/48465677-3e7b6980-e816-11e8-8de8-57fed44baa55.PNG)

**Comment by jsnellbaker** [comment]
Prebid.js doesn't have any tracking for VAST events.  This would likely be something at the adserver level, since they're the ones who setup the creative and would enable tracking for these events (if it's available for outstream type ads).
