### ISSUE TITLE
Video Js - Prebid Instream Client-Side Adapter

### ISSUE THREAD

**Issue by sudhakarsukumar** [prebid/Prebid.js#3294]
http://prebid.org/examples/video/videojs-demo.html  - while skipping the ads the ad gets played continuously and the video content was not playing.

**Comment by bwoolcott** [comment]
@sudhakarsukumar are you just pointing out an issue with the test/example page? Or an issue you're having with Prebid video in production?

**Comment by bretg** [comment]
Agreed this seems to be a problem with the player used on the example page. Maybe due to the fact that there's no content specified, so nothing to skip to. In any case, I've opened https://github.com/prebid/prebid.github.io/issues/1057 over on the docs repo, so will close this one out.
