### ISSUE TITLE
net::ERR_CERT_SYMANTEC_LEGACY - Appnexus Prebid Server

### ISSUE THREAD

**Issue by freegames66** [prebid/Prebid.js#3299]
Today, I received an SSL error with prebid.adnxs.com (Check out the screenshot below)
I'm using Google Chrome Version 70.0.3538.102 (Official Version) (64 bit)

![ssl1](https://user-images.githubusercontent.com/33347377/48541140-8cfc3700-e8ee-11e8-9bef-fc5b7922798d.PNG)
![ssl](https://user-images.githubusercontent.com/33347377/48541139-8cfc3700-e8ee-11e8-9a17-833bc9001b66.PNG)

I have checked on Firefox and this error does not appear. However, I got the 400 error - Bad Request for endpoint: 'https://prebid.adnxs.com/pbs/v1/openrtb2/auction'

![screenshot_1](https://user-images.githubusercontent.com/33347377/48541207-bb7a1200-e8ee-11e8-968f-f15a5d5fe94c.jpg)

Is there anyone can let me know the cause and how to fix these errors?

**Comment by freegames66** [comment]
Anybody has the same problem as me?

**Comment by jsnellbaker** [comment]
@freegames66 Can you share the page where you're seeing this error?  I tested one of our test pages that use Prebid Server and I wasn't seeing these errors.

**Comment by freegames66** [comment]
@jsnellbaker Pls help me check this problem on this page: https://www.freegames66.com/sports/return-man-3/

And what about 400 error - Bad Request on firefox?

**Comment by jsnellbaker** [comment]
I was having trouble trying to enable the debug settings (by appending `?pbjs_debug=true` to the url) as the page immediately reloaded without the query params.

However when I checked the auction URL in the Network tab - I looked at the response and saw the following:
```
Invalid request: request.imp[0].ext.rhythmone failed validation.
path: path is requiredzone: zone is requiredplacementId: Invalid type. Expected: string, given: integer
```

When I checked the request structure, I saw the rhythmone object only contained `placementId` and it appeared to have an integer value instead of a string value like the error indicated.  

So the 400 errors are due to the invalid params being passed for this bidder.  They should clear up if these params are updated to the proper format.

The following page can help as a reference if needed (just choose `rhythmone` and then `see the bidder params for` option from the dropdown):
http://prebid.org/dev-docs/prebid-server-bidders.html 

I still haven't seen the cert errors; are you still seeing them?

**Comment by freegames66** [comment]
@jsnellbaker Thank you for helping me find the cause of the 400 error.

I still see cert errors. Have you using google chrome 70.xxx version?  I saw an article talking about this issue. It only appears on Google chrome 70.xxx -> https://knowledge.digicert.com/alerts/ALERT2566.html

**Comment by jsnellbaker** [comment]
@freegames66 I am using Chrome 70.x (specifically `Version 70.0.3538.102 (Official Build) (64-bit)`).  I'm checking internally with some folks to see if they can advise.

**Comment by freegames66** [comment]
@jsnellbaker I have change rhythmone placmentId to string:
`{
                                bidder: 'rhythmone',
                                params: {
                                    placementId: '76924'
                                }
                            }`

But, I continue get error:
```
Invalid request: request.imp[0].ext.rhythmone failed validation.
path: path is required zone: zone is required
```

what is **path** and **zone** for rhythmone adapter? I don't see this on http://prebid.org/dev-docs/bidders.html#rhythmone

**Comment by jsnellbaker** [comment]
@freegames66 I'm not sure what the values should be.

@Rajeshk08 and/or @jstocker76 
Could you take a look at the question above in regards to the `rhythmone` adapter bidder params?  The bidder params seem to be out of sync between PBS and Prebid.js.

@freegames66 In regards to the cert error in Chrome, could you provide the IP address your currently using?  Someone is taking a look but they noted this would be helpful to have.

**Comment by freegames66** [comment]
IP Address | 117.5.172.195
-- | --

**Comment by jsnellbaker** [comment]
@freegames66 Where are you located?

**Comment by freegames66** [comment]
@jsnellbaker I'm from Viet Nam.

**Comment by freegames66** [comment]
![1](https://user-images.githubusercontent.com/33347377/48570630-58609d80-e937-11e8-8887-775399241baa.PNG)

**Comment by jsnellbaker** [comment]
@freegames66 Thanks for all the information.  I just received word that there was something on our end and we just rectified the problem.  The error should no longer be showing at this time.  Can you confirm?

**Comment by freegames66** [comment]
@jsnellbaker All is fine now. Thank you very much for your support and your time!

I also got a response from my account manager at Rhythmone. If anyone is experiencing 400 bad requests like me, set your Rhythmone adapter to something like:
```
{
	bidder: 'rhythmone',
	params: {
		placementId: '76924',
		path: 'mvo',
		zone: '1r'
	}
}
```

**Comment by jsnellbaker** [comment]
Thanks @freegames66 for the confirmation; if we're all good on this ticket then - I'm going to close it out.
