### ISSUE TITLE
The highest bid isn't winning

### ISSUE THREAD

**Issue by whatisjasongoldstein** [prebid/Prebid.js#3309]
## Type of issue

Bug?

## Description

The highest bid is not always the bid assigned by `pbjs.setTargetingForGPTAsync` when `enableSendAllBids=false`.

## Steps to reproduce

Compare `pbjs.getBidResponses()` to `pbjs.getAdserverTargeting()`. In our testing with the IX module, we saw ixBidAdapter return two bids for a slot, and the lower dollar amount was assigned.

### Expected results

The higher bid is passed to GPT.

### Actual results

The lower bid was passed to GPT.

## Platform details

Prebid 1.30.0, Chrome.

## Other information

Our use of the ixBidAdapter requests bids on every size an ad position can serve. (So one bidder object is added to the unit per size.)

**Comment by YOzaz** [comment]
I can't 100% confirm, but from our observation that's something we've noticed as well.

**Comment by headerbidding** [comment]
This should be fixed!

**Comment by bwoolcott** [comment]
@whatisjasongoldstein is this only an issue for the IX bid adapter or are you seeing it as a general Prebid issue? Also, when checking pbjs.getAdserverTargeting() did you also compare those values to the request query string params (scp query) in the call to GPT to confirm KV targeting there? Looking to confirm if this is a targeting issue or just an issue of what's contained in getAdserverTargeting

**Comment by Deimos01** [comment]
After some investigations, we also observed something new (and weird) with the behavior of the `pbjs.getAdserverTargeting` function.
At the end of the auction process, pbjs.getAdserverTargeting() is sending back the right values. The highest CPM bid is sent to the adserver. As you said @whatisjasongoldstein "the correct ones were being sent to the network request".
Then after the bidWon event and the `renderAd()`, the `pbjs.getAdserverTargeting()` function seems to return a new value.

![explanation](https://user-images.githubusercontent.com/5635647/49773543-8a0f1f00-fcbf-11e8-92fe-df9bd74b6aea.PNG)
I think it's a new behavior related to the bid pool logic and bid caching system. The bid has to be deleted after the rendering so the 2nd winning bid is returned by `pbjs.getAdserverTargeting()`.
In my opinion, it's not a bug but a new dynamic behavior.

**Comment by whatisjasongoldstein** [comment]
That makes sense and is consistent with our testing. Closing.
