### ISSUE TITLE
User Sync Module - Allow multiple user syncs for long page sessions (e.g. on gaming sites)

### ISSUE THREAD

**Issue by DubKF** [prebid/Prebid.js#3320]
## Type of issue
Feature Request

## Description
For rather long user sessions as they are typical e.g. for online gaming it might be useful to allow more than 1 user sync per page load at least as long as a common Identity framework isn't widely used. 

Currently this is not possible, because a private variable "hasFired" is being set after the 1st sync and prevents future calls in the same session. There's also no option to reinitiate the userSync again because the class constructor is not exposed.

Typically, many providers limit the matching with their buyers to a fixed amount of pixels, even in the case where iframes are used. This means a later matching request within the same (long) session might successfully synchronize user information with different buyers and potentially allow a better monetization in the session. 

While it used to be allowed in older versions, but is impossible to achieve with the newest version.

## Steps to reproduce
A [flag disables sync after the 1st try](https://github.com/prebid/Prebid.js/blob/master/src/userSync.js#L78) and will cause further syncs to be [prevented](https://github.com/prebid/Prebid.js/blob/master/src/userSync.js#L64)

## Expected Results
It would be ideal to have a new configuration option, which could e.g. support a limited number of syncs within the same session (and perhaps also have an "unlimited" setting). 

Potentially a new timeout for flushing the sync-queue again could also be introduced to limit the page impact further.

**Comment by mkendall07** [comment]
Instead of a configuration option, couldn't you just fire `triggerUserSyncs` ? Does this not work? If it doesn't work I think we should fix it.

**Comment by pm-manasi-moghe** [comment]
Hi,

Is there an ETA for this fix?

**Comment by mkendall07** [comment]
this is included in 2.2.0 release.
