### ISSUE TITLE
flatmap-stream package deleted

### ISSUE THREAD

**Issue by Saigredan** [prebid/Prebid.js#3330]
## Type of issue
BUG

## Description
According to current news, e.g. https://www.zdnet.com/article/hacker-backdoors-popular-javascript-library-to-steal-bitcoin-funds/,  flatmap-stream is down, which means  event-stream down, which means gulp connect and gulp replace are down. That implies general problem with building Prebid.
Are there any plans to fix this issue?

**Comment by muuki88** [comment]
Fix in `gulp-connect` https://github.com/AveVlad/gulp-connect/pull/259

**Comment by Saigredan** [comment]
Also need a change in gulp-replace verson in package.json up to at least 0.6.0

**Comment by GLStephen** [comment]
Is there any guidance regarding effected versions of Prebid?

**Comment by muuki88** [comment]
AFAIK distributions aren't affected as only build dependencies (`gulp-connect`, `gulp-replace`) used the malicious dependency.

**Comment by GLStephen** [comment]
> AFAIK distributions aren't affected as only build dependencies (`gulp-connect`, `gulp-replace`) used the malicious dependency.

Ok, thanks for the confirmation.

**Comment by jsnellbaker** [comment]
I will put together some changes for these gulp packages, however it seems we need to wait on the `gulp-connect` and `gulp-footer` updates.  Will keep an eye on this.

**Comment by Saigredan** [comment]
@jsnellbaker why not using temporal forks?

**Comment by whatisjasongoldstein** [comment]
So I'm not able to install Prebid _at all_ right now?

**Comment by Austinb** [comment]
This was merged in as part of https://github.com/prebid/Prebid.js/releases/tag/1.35.0 and appears to be working now.  Was able to `npm install` and do a custom build without issue.

Many thanks to @jsnellbaker, @jaiminpanchal27 & @mkendall07
