### ISSUE TITLE
Telaria adapter - GenerateUrl: Bid sizes is empty

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/Prebid.js#3331]
## Type of issue

When requesting a video ad the method `generateUrl` expects `bid` to have a `sizes` array. In our test setup this appears to be empty for Telaria.

We pass `playerSize`, so a size should be known:

```
var videoAdUnit = {
      code: 'video',
      mediaTypes: {
        video: {
          context: 'instream',
          playerSize: [640, 480],
        },
      },
``` 

## Test page
http://jsfiddle.net/9uchz0mb/1/

## Platform details

Prebid 1.33.0
The bug does not occur in version 1.32.0. This PR may have modified the behavior ( https://github.com/prebid/Prebid.js/pull/3274 )

You may get cors errors as only our validated domains work. The described error occurs before this though.

**Comment by bretg** [comment]
@telariaEng - please take a look

**Comment by telariaEng** [comment]
@bretg thanks for bringing this to our attention :) the adapter was relying on the sizes array to get the player size. We will update it to use mediatypes.video.playerSize instead.
