### ISSUE TITLE
aol adapter: not possible to register bidder alias as bid gets invalid

### ISSUE THREAD

**Issue by derdeka** [prebid/Prebid.js#3353]
## Type of issue
bug

## Description
It is currently not possible to register an alias for aol adapter as the bids are getting invalid within 'isBidRequestValid'.

## Steps to reproduce

1. register alias: `$$PREBID_GLOBAL$$.aliasBidder('aol', 'oath');`
2. configure and run bids with alias 'oath'

## Test page
none

### Expected results
Able to use 'oath' as alias for aol bidder.

### Actual results
Invalid bid when using alias 'oath'.

## Platform details
Prebid 1.31.0, 1.32.0, 1.33.0, 1.34.0

## Other information
none

**Comment by bretg** [comment]
@vzhukovsky - is this something you can help with?

I also sent email to the address listed as the adapter's maintainer.

**Comment by vzhukovsky** [comment]
Hi.

Thanks for reporting it.

Looking into that
