### ISSUE TITLE
Version went from 1.35.0-pre.js to prebid.1.33.0-pre.js

### ISSUE THREAD

**Issue by pbrisson** [prebid/Prebid.js#3362]
## Type of issue
Question

## Description
I always keep my version up-to-date and it went from 1.35.0-pre to 1.33.0-pre after my last sync with the repo.

## Other information
See commit: https://github.com/prebid/Prebid.js/commit/650aa3a7205b3890d9990c9282abada047bdfbaa

**Comment by jsnellbaker** [comment]
@pbrisson Thank you for pointing this out.  I just corrected the version in the file.  `master` should be update to date now if you want to resync.
