### ISSUE TITLE
EMXDigital outstream does not set VAST url

### ISSUE THREAD

**Issue by nanek** [prebid/Prebid.js#3364]
## Type of issue
Bug

## Description

emxdigital alias using appnexus bid adapter configured for outstream with a renderer.

Example response from network with rtb.video.content VAST xml.
![screen shot 2018-11-30 at 10 10 36 am](https://user-images.githubusercontent.com/6188/49674314-8f5e3680-fa3f-11e8-9180-3286481b4141.jpg)

Prebid bidResponse object, does not map the VAST xml from the network response above into any parameter. I'd expect to see it under `ad` or `vastUrl`.
![screen shot 2018-11-30 at 10 08 20 am](https://user-images.githubusercontent.com/6188/49674313-8f5e3680-fa3f-11e8-829c-616728c06c4a.jpg)

The server response from http://ib.adnxs.com/ut/v3/prebid includes `rtb.video.content` instead of `rtb.video.asset_url` which is what the adapter appears to be looking for. https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L263

There is no VAST XML to pass to our renderer.

Should the server return something different? Or should the appnexus adapter be update to also look for rtb.video.content? Or have I missed something else?

## Platform details
Prebid.js 1.26

**Comment by jsnellbaker** [comment]
This issue was actually related to the `appnexusBidAdapter`.  I reviewed the setup and created a PR to address the issue.

Since we're receiving vast XML code instead of a vast URL, I updated the bid field the adapter populates to `bid.vastXml` and fixed where we're looking in the raw bid response to get the data.
