### ISSUE TITLE
Alternate way to render native ads through Prebid.

### ISSUE THREAD

**Issue by nanek** [prebid/Prebid.js#3366]
## Type of issue
Request for feedback.

## Description

From https://github.com/prebid/Prebid.js/pull/3224#issuecomment-435960020 I created an example that demonstrates another approach to rendering native ads through prebid using the existing renderer option:
https://gist.github.com/nanek/cfcd43a1dc343dabfad505eb4e63653c

- No need to create additional DFP line items, targeting hb_format=native. Can use existing banner line items.
- No concerns over passing KVPs that are too long, as no additional KVPs are required to be passed to DFP. This is more of an issue when using single request mode for DFP. 
- No concerns over encoding characters DFP does not allow.
- You lose DFP click tracking metrics.

- The ad is not rendered in an iframe. Is this an issue?
- Are there other downsides or concerns?

This seems to work using existing prebid.js without modifications. I'm interested in any feedback on this approach. Thanks!

/cc @mkendall07

**Comment by mkendall07** [comment]
@nanek 
Thanks for your suggestion! Some quick feedback/questions from @mjacobsonny 
1) how does the publisher prevent a banner ad from serving into the slot?
2) can it compete with any managed native LIs?
3) are there any issues with responsiveness/ responsive slots?

**Comment by mkendall07** [comment]
Closing this as we introduced the `sendId` method: 
http://prebid.org/dev-docs/show-native-ads.html#1-configure-which-assets-to-send-as-placeholders
