### ISSUE TITLE
Prebid server now supports limits on user syncs

### ISSUE THREAD

**Issue by hhhjort** [prebid/Prebid.js#3367]
## Type of issue
Feature request

## Description
Prebid server now supports limits on user syncs. Old behavior was PBS would send all missing user syncs when requested. Still does if no limit is set. But limits are good for limiting the number of pixels dropped on a page.

## Steps to reproduce
N/A

## Test page
PR that added the feature
https://github.com/prebid/prebid-server/pull/759

## Platform details
N/A

## Other information
PR that added the feature
https://github.com/prebid/prebid-server/pull/759

**Comment by bretg** [comment]
Ok. To make use of this in PBJS, we need to support a new s2sConfig parameter. e.g. `userSyncLimit: N`.

We would need to update `prebidServerBidAdapter` to pass `userSyncLimit` through to PBS as `limit`.

Assigning to @mkendall07 for prioritization

**Comment by mkendall07** [comment]
We can probably tackle this in Q1 2019.
