### ISSUE TITLE
DFP ad request won't be made if prebid.js isn't loaded yet

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#337]
Line https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/pbjs_example_gpt.html#L24
Needs to come out of `pbjs.que.push`.

**Comment by mkendall07** [comment]
Fixed in example page, leaving ticket open for visibility.

**Comment by BartVB** [comment]
Good catch, thanks!
