### ISSUE TITLE
Teads: Adapter doesn't respect media types - sizes don't work

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#3373]
## Type of issue

bug

## Description

The [Teads Adapter](https://github.com/prebid/Prebid.js/blob/master/modules/teadsBidAdapter.js#L119), still uses the deprecated `bid.sizes` property and doesn't differentiate between `banner` and `video` media types. 

This 

cc: @valsouche 

## Steps to reproduce

Use a `video` only ad unit. See #3222

### Expected results

Teads should use the `mediaTypes` sizes for video and/or banner instead of the deprecated `sizes` property.

## Platform details

- prebid version `1.35.0`

## Other information

- #3222 - this issue already mentioned the problem, but didn't get fixed
- #3274 - IMHO due to this, teads somehow worked before 1.33.0

**Comment by muuki88** [comment]
This is especially weird as the `bid.sizes` property should include the videos sizes. At least if I read [this code in der `adapterManager.js`](https://github.com/prebid/Prebid.js/blob/master/src/adaptermanager.js#L280-L295) correctly.

It almost looks as if the video player sizes override the banner.

The [OpenX adapter handles the video playerSize explicitly](https://github.com/prebid/Prebid.js/blob/27107e27911861af2235c2efcc4f029fb5e2c1ab/modules/openxBidAdapter.js#L313-L327).

**Comment by muuki88** [comment]
The reasons for this behavior is buried in the [`getBids` function, which simply used the `mediaTypes.banner.sizes`](https://github.com/prebid/Prebid.js/blob/7fe95d89464cbc95adf3446cd8e39bb499f2c321/src/adaptermanager.js#L97) and discards everything that has been done before.

**Comment by muuki88** [comment]
The [getBids function](https://github.com/prebid/Prebid.js/blob/master/src/adaptermanager.js#L97) seems to set the sizes only from `mediaTypes.banner.sizes` and nothing else. Is the size mapping even applied there?

**Comment by valsouche** [comment]
In this pull request (https://github.com/prebid/Prebid.js/pull/3377), @bretg says that playerSize is an optional field. But like @muuki88 said, for some reason, if from a video adunit mediatypes there is no `playerSize` bid sizes =`[]`, even if there is a sizes property on the adUnit.

It looks like only banner sizes are copy in adUnit.sizes.

Is it something expected ? 

Thanks in advance,
Val.

**Comment by muuki88** [comment]
Before this ticket is getting stale.

@valsouche are opening a PR to fix this?

**Comment by muuki88** [comment]
@valsouche Any ETA for this one?

**Comment by muuki88** [comment]
Should be fixed in the next release.
