### ISSUE TITLE
Cross Domain integration example is out of date

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#3381]
## Type of issue
Feature Request

## Description
Cross domain implementation method is not current

## Steps to reproduce
https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/x-domain/creative.html does not have the new preferred method suggested in https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/creative_rendering.html

## Test page

**Comment by mkendall07** [comment]
hey @patmmccann 
are you referring to this line? 
`window.parent.postMessage(message, publisherDomain);`
Where the assumption is that the pbjs library is the direct parent of the iframe?

**Comment by patmmccann** [comment]
The x-domain example is missing the for loop to get to top by walking up
through the parents
