### ISSUE TITLE
resetPresetTargeting not available for setTargetingForAst

### ISSUE THREAD

**Issue by markuspovelainen** [prebid/Prebid.js#3396]
Seems that the `resetPresetTargeting` is missing from `setTargetingForAst`. https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L211-L222

This is a problem on SPA sites using Appnexus ad server as the prebid library sets the old key-values for ad placements when you move to the next page.

**Comment by mkendall07** [comment]
this is resolved with https://github.com/prebid/Prebid.js/pull/3448

**Comment by markuspovelainen** [comment]
I'm sorry to say but it doesn't clear the prebid globals for targeting. Meaning if you get a bid from page 1 and do SPA-style page change to page 2 which you don't get bid prebid still has the previous values in globals which will be set as a keywords to Appnexus on page 2. Seems that for for gpt global clean up is defined here: https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L190
ping @mkendall07

**Comment by deekshithraop** [comment]
Hey @markuspovelainen would you be able to setup a test page where we can see this actually happening please.
