### ISSUE TITLE
[Telaria] getBidderRequest can not find corresponding bid due to mismatching bidder code

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/Prebid.js#3398]
## Type of issue
The telaria adapter returns bids with bidder code "TremorVideo".
This results in utils/getBidderRequest not being able to match the bidder id "TremorVideo" to any bids, as the bid either has the code "telaria", "tremor" or "tremorvideo".

So even when using the alias "tremorvideo" it won't ever match "TremorVideo".

## Description
The reply we get the following bid response from Telaria: 

```
{"cur":"USD","id":"a1e734226d2d48a08ddc120a8895f097","seatbid":[{"seat":"TremorVideo","bid":[{"adomain":[],"price":0.0,"id":"a1e734226d2d48a08ddc120a8895f097","adm":"vast stuff","impid":"1"}]}]}
```

Looking at the telariaBidAdapter:

```
else if (bidResult.seatbid && bidResult.seatbid.length > 0) {
      bidResult.seatbid[0].bid.forEach(tag => {
        bids.push(createBid(STATUS.GOOD, bidderRequest, tag, width, height, bidResult.seatbid[0].seat));
      });
```

So, the `bidResult.seatbid[0].seat` is taken out of the reply, and used as the bidder code.

The prebid method `auction.addBidResponse(adUnitCode, bid)` calls `getBidRequests`, which tries to match "telaria" (or "tremor" or "tremorvideo" if you use one of the aliases) to "TremorVideo", which does't work.

## Test page
https://jsfiddle.net/yeqjf7r4/
Test page uses our own build of prebid as the Telaria adapter has other issues in the latest version of prebid. The underlying issue still remains.

## Platform details

prebid 1.31.0
Telaria bid adapter is broken on more recent builds

**Comment by ReinoutStevens** [comment]
@telariaEng tagging you as this is probably relevant

**Comment by telariaEng** [comment]
@ReinoutStevens thanks for tagging. I do have an open PR and I don't mind adding 'TremorVideo' to the alias list. But I think the proper fix would be to check the bidder code against the aliases while ignoring the case.

**Comment by ReinoutStevens** [comment]
Thanks for the quick response :+1:

**Comment by mkendall07** [comment]
has this been resolved? @telariaEng

**Comment by ReinoutStevens** [comment]
Obviously I dont work at Telaria, but this is how I see the current state:

Telaria has 2 aliases, tremor and tremorvideo. The adapter used to set TremorVideo as bidder on a bid. In their PR ( https://github.com/prebid/Prebid.js/pull/3377 ) they modified the behavior and do a to lowercase, so now tremorvideo should be set. This means we can use tremorvideo as bidder code, and it should work.

However, this does not fix the underlying issue: I would expect when I request a bid using 'telaria' that the biddercode set by the adapter would be 'telaria', and not tremor or tremorvideo. This could be due to a misunderstanding of the aliases on Telaria's part (or on my part, and this behavior is fine). In case this behavior is fine then prebid should look at aliases as well in the `getBidRequests()` function.

**Comment by ReinoutStevens** [comment]
I am unsure whether I need to open a new issue or hijack this one:
With prebid 1.37.0 I can request a bid as telaria, which does not throw any errors, but the hb_bidder remains set to tremorvideo, which causes problems with our dfp setup (as telaria != tremorvideo). Obviously we can change our dfp setup and request tremorvideo ads, but the issue remains that an ad requested for telaria is sent to dfp as a bid from tremorvideo.
If desired I can open a new issue for this
