### ISSUE TITLE
NATIVE mediatype doesn't allow SSP to control the render

### ISSUE THREAD

**Issue by brittanyzellman** [prebid/Prebid.js#3400]
## Type of issue
Request for alternate mediatype or documentation update

## Description
In programmatic advertising, "Native" largely represents an impression that takes on the look and feel of the page. However, Prebid NATIVE only allows a component-based transmission where it opines that the SSP passes the components/assets while adserver renders. However, most SSPs have rendering technology that materially adds value to the ad experience. To unlock this capacity,  the current workaround deployment is utilize to the BANNER mediatype where the rendering mechanism (js) is passed in the `adm` that assembles "native" ad experiences.  However, using the BANNER mediatype is misleading and confusing to publishers that want to integrate through Prebid because entities like TripleLift, are not listed under NATIVE in your documentation. The inquiry is to provide a way for companies like TripleLift to be supported under the NATIVE format while allowing them to bring their own renderer. Is it feasible to have a new mediatype representing SSPs that control the render (over native pipes), or two different categories of the NATIVE mediatype? If these are not possible, can the documentation be updated to avoid confusion pertaining to SSPs that are playing in the Native space but need to transact over the BANNER mediatype due to the limitations of the render in NATIVE?

**Comment by kaseyfan** [comment]
Hey Prebid team -- any thoughts on the above? Let us know what we can do to provide more clarity.

**Comment by mkendall07** [comment]
thanks for the reminder. @mjacobsonny for comment

**Comment by kaseyfan** [comment]
Hi @mjacobsonny - Have you had a chance to review? Standing by if you have any questions/initial feedback.
