### ISSUE TITLE
[Question] how to encode custom parameter for bid

### ISSUE THREAD

**Issue by Journerist** [prebid/Prebid.js#3404]
## Type of issue
Bug

## Description
DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

## Steps to reproduce
add custom parameters with not latin1 chars like > “ <. After sending the requests the error will occur. In the code occurrences like openxBidAdapter.js, line 261: 
`let formattedCustomParams = window.btoa(customParamsForBid.join('&'));` will fail due to that. 

## Questions

How to handle parameter encoding in general? Usually, you encode and decode things when you encode them base64. But I am not sure what happens on the consumer side. I can only encode my params for things that can not be converted but this does not feel like a proper solution:

```
      try {
        window.btoa(customParameter);
        return customParameter;
      } catch (e) {
        return unescape(encodeURIComponent(customParameter));
      }
```

Any other ideas?

**Comment by mkendall07** [comment]
@prebid/openx for comment

**Comment by mkendall07** [comment]
@bwoolcott ping on this

**Comment by jimee02** [comment]
Hey @Journerist, 
On the consumer side, our system will be able to decode the base64 string into its proper key/value pairs.  The quickest way around this is to use the following snippet to convert the string to UTF-8 compatible strings prior to feeding them into our custom params field.

https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_2_%E2%80%93_escaping_the_string_before_encoding_it

@mkendall07, I've noticed that several other adapters also use window.btoa.  Is there any interest in hosting a util to convert UTF-16 to UTF-8?  The code is available here: https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_1_%E2%80%93UTF-16_%3E_binary_UTF8-in-16
