### ISSUE TITLE
GPT responsive ads without prebid sizeConfig?

### ISSUE THREAD

**Issue by webdeveloperpr** [prebid/Prebid.js#3409]
## How to implement GPT responsive ads without using the sizeConfig?

This ticket was issued to gather more information on how to implement responsive ads with prebid.js without using prebid's sizeConfig

## googletag sizeMapping without using sizeConfig

googletag provides a way to show/hide ads based on media queries and it 
specifies the adSizes to display on the specific media query.

We need to tell prebid which ads to fetch based on the sizes defined on the 
slot without using the sizeConfig.

**Why not use the sizeConfig?**

The size config defined global settings for requesting bids. We want to bid on 
the exact sizes defined in the googletag sizeMap instead.

case 1:

- window width is 1000px

In this we only want to fetch bids for the **large** ad slot. So we tell prebid
the sizes that we want to bid on by setting the `metiaTypes.banner.sizes` 
property.

**sizeMapping**

```javascript
var mapping1 = googletag.sizeMapping().
    addSize([1024, 768], [970, 250]). // large  <- current breakpoint
    addSize([980, 690], [728, 90]). // medium
    addSize([640, 480], 'fluid'). //sm
    addSize([0, 0], [88, 31]). // xs
    build();
```

We define the sizes in `metdiaTypes.banner.sizes` from the large size above.

**prebid adUnit**

```javascript
pbjs.addAdUnits([{
    code: "ad-slot-1",
    mediaTypes: {
        banner: {
            sizes: [
                [970, 250],
            ]
        }
    },
    bids: [{
            bidder: "pulsepoint",
            params: {
                "cf": "728X90",
                "cp": 123456,
                "ct": 123456
            }
        },
    ]
}]);
```

case 2:

This is a continuation of case1

- window width is 1000px (large) breakpoint
- We move down to 980px (medium) breakpoint

The window width is (large) and the (medium) breakpoint was triggered. Now
we have to update the prebid adUnit config to fetch the new bids.

**sizeMapping**

```javascript
var mapping1 = googletag.sizeMapping().
    addSize([1024, 768], [970, 250]). // large <----- old breakpoint
    addSize([980, 690], [728, 90]). // medium <------ new breakpoint
    addSize([640, 480], 'fluid'). //sm
    addSize([0, 0], [88, 31]). // xs
    build();
```

We define the (medium) sizes in `mediaTypes.banner.sizes` property before
requesting bids.

**prebid adUnit**

```javascript
pbjs.addAdUnits([{
    code: "ad-slot-1",
    mediaTypes: {
        banner: {
            sizes: [
                [728, 90], // medium <----- Replaced [970, 250]
            ]
        }
    },
    bids: [{
            bidder: "pulsepoint",
            params: {
                "cf": "728X90",
                "cp": 123456,
                "ct": 123456
            }
        },
    ]
}]);
```

My solution right now is to change the sizeConfig before the bidRequest. 

Is this an acceptable solution?

Is anyone doing this?

**Comment by webdeveloperpr** [comment]
Also how would I be able to see all the registered adUnits?

**Comment by lafentres** [comment]
If this works for you, I don't see why it would be a problem.

I used to use the GPT sizeMapping before using Prebid. When we first switched to using Prebid, I looked at using sizeConfig but the global setting didn't work the way I needed them too. The way I handle different breakpoints now is by storing all the breakpoint info for a given ad and then calling a function to determine which breakpoint is the correct one based on screen size. This is useful for me at least, since there are other things that depend on the breakpoint (like the bids that I need to send, etc). I've included a rough example of the way I store things. I prefer this was because I can store everything I need all in one place and it works well with the way our ad units are set up. 

```
adSlotConfig['example_banner'] = {
        name: 'example_banner',
        targeting: {
            'pos': 'top',
        },
        breakpoints: [
            {
                minWidth: 970,
                minHeight: 0,
                sizes: [[970, 90], [728, 90]],
                bids: [
                    bidder1Tags['top'],
                    bidder2Tags['top'],
                    bidder3Tags['top'],
                ]
            },
            {
                minWidth: 728,
                minHeight: 0,
                sizes: [[728, 90]],
                bids: [
                    bidder1Tags['top'],
                    bidder2Tags['top'],
                    bidder3Tags['top'],
                ]
            },
            {
                minWidth: 0,
                minHeight: 0,
                sizes: [[320, 50]],
                bids: [
                    bidder1Tags['top'],
                ]
            }
        ]
    };
```

**Comment by webdeveloperpr** [comment]
Very nice! I ended up with a similar solution but using the GPT sizeMap.

Here I call the function and pass the slotId with the slot sizes for the current breakpoint
https://github.com/webdeveloperpr/react-ads/blob/master/src/components/Ad/index.js#L65-L91

Here is the function that the ad can define to generate the bids dynamically.
https://github.com/webdeveloperpr/react-ads/blob/master/examples/Prebid/index.js#L5-L21

Then I unset the old bids from the pbjs.adUnit array and set the new ones.

https://github.com/webdeveloperpr/react-ads/blob/master/src/utils/Bidder/prebid/index.js#L31-L36
