### ISSUE TITLE
iframes should not be injected into <head>

### ISSUE THREAD

**Issue by mbova** [prebid/Prebid.js#3413]
## Type of issue
Bug

## Description
Currently iframes get injected into the head. Google has said this can cause a problem with them reading all the meta tags because the iframes implicitly close the head and push the meta tags into the body. [source](https://www.reddit.com/r/TechSEO/comments/87pxsu/i_am_john_mueller_webmaster_trends_analyst_at/dwh3hd9/)

They recommend to inject just before the closing `</html>` tag instead of at the top of the `<head>`

## Steps to reproduce
Load page using prebid
watch for iframes to inject into `<head>`

### Actual results

<img width="1058" alt="screen shot 2018-11-28 at 2 51 47 pm" src="https://user-images.githubusercontent.com/1504785/50614796-9e51d080-0ea7-11e9-9500-2a7a4da62b74.png">

**Comment by mkendall07** [comment]
thanks for the feedback - this makes sense to me.

**Comment by snapwich** [comment]
closed via #3415
