### ISSUE TITLE
The vast tag I got from prebid is not working on google IMA

### ISSUE THREAD

**Issue by mistynight89** [prebid/Prebid.js#3420]
Hi. I generated vast tag using example code from your example page like below.
![prebid1](https://user-images.githubusercontent.com/22162797/50712322-0b4b9e80-103f-11e9-8cf7-382b14fbc2c8.PNG)

The tag I got is below
https://pubads.g.doubleclick.net/gampad/ads?env=vp&gdfp_req=1&output=vast&unviewed_position_start=1&correlator=1546548816841&sz=640x480&url=http%3A%2F%2Fadmaru.com%2Ftest%2Fprebid_out.html&iu=/19968336/prebid_cache_video_adunit&cust_params=hb_format%3Dvideo%26hb_source%3Dclient%26hb_size%3D640x360%26hb_pb%3D5.00%26hb_adid%3D24d7772b9d2275%26hb_bidder%3Dappnexus%26hb_format_appnexus%3Dvideo%26hb_source_appnexus%3Dclient%26hb_size_appnexus%3D640x360%26hb_pb_appnexus%3D5.00%26hb_adid_appnexus%3D24d7772b9d2275%26hb_bidder_appnexus%3Dappnexus%26hb_uuid%3D12865c7c-01fe-4949-af61-a1c77ada1645%26hb_cache_id%3D12865c7c-01fe-4949-af61-a1c77ada1645

Then, I tried to use this vast tag on google IMA player.

I set the vast tag to global variable, and then I try to use this tag in IMA player.
But it show the errors.
![prebid2](https://user-images.githubusercontent.com/22162797/50712331-17376080-103f-11e9-9961-96c3b1e4c06f.PNG)
The test page is 
http://admaru.com/test/prebid_out.html

However,  I put the vast tag in the IMA player file, and it shows the video.
Test page link
http://admaru.com/test/prebid_out2.html

I have no idea what makes this issue.

**Comment by mkendall07** [comment]
@mistynight89 
It doesn't look like you have the right URL(s) for the google resources. Please check the setup with the IMA player.
