### ISSUE TITLE
Rubicon Adapter - Size Map needs updating, extra sizes.   

### ISSUE THREAD

**Issue by mjwhaley** [prebid/Prebid.js#343]
@mkendall07 Might be worth updating the Rubicon size mapping within the adapter as currently its missing the 468x60 and 970x90 sizes. The full sizes we are using are below. 

var RUBICON_SIZE_MAP = {
    '468x60': 1,
    '728x90': 2,
    '160x600': 9,
    '300x600': 10,
    '300x250': 15,
    '320x50': 43,
    '300x1050': 54,
    '970x90': 55,
    '970x250': 57
  };

**Comment by mkendall07** [comment]
Thanks @mjwhaley 

@bretg - is there any other sizes missing in the Rubicon adapter? It would be good to get them all in.

These are current ones:
```
var RUBICON_SIZE_MAP = {
    '728x90': 2,
    '160x600': 9,
    '300x600': 10,
    '300x250': 15,
    '320x50': 43,
    '300x1050': 54,
    '970x250': 57
  };```

**Comment by bretg** [comment]
@mkendall07 - will review the sizes today. The wrinkle is that there's another list of sizes at the account level - even if a size is on the prebid list, they could currently have to request the size to be added for their account. Will see if this can be ironed out.

**Comment by bretg** [comment]
@mkendall07 - pull request 345. Note I took the opportunity to add a call to 'setIntegration', which was going to be a separate issue and pull request anyhow.

Also note that we're looking into simplifying the size map - ideally not needing it in both the Prebid adapter and our underlying code.

**Comment by protonate** [comment]
#345 has merged, closing.
