### ISSUE TITLE
Criteo entry in Prebid.js does not comply with 'use strict' 

### ISSUE THREAD

**Issue by Tigerroad** [prebid/Prebid.js#3433]
## Type of issue
Bug

## Description
The Criteo entry in Prebid.js does no comply with the 'use strict' directive which is declared.
The line 'utc=t.getTime()+6e4*t.getTimezoneOffset(),new Date(utc)' dores not comply with 'use strict'
MVC Bundling is fails because of javascript declaring to be strict and not complying 

## Steps to reproduce
Download latest (1.37.0) containing Criteo Adapter and search for: "utc=t.getTime()+6e4*t.getTimezoneOffset(),new Date(utc)"

### Expected results
javascript should either comply with 'use strict' directive or directive should be removed

### Actual results
javascript doesn't comply with 'use strict' and MVC Bundling fails

## Platform details
Prebid.js v1.37.0

**Comment by mkendall07** [comment]
@jsfaure can you look into this please?

**Comment by jsfaure** [comment]
Hi, sorry for the delay.
So, yes, it appears that some part of the referenced libraries don't comply with the strict mode.
I will try to update them.

**Comment by jsfaure** [comment]
Here a first PR: https://github.com/kjur/jsrsasign/pull/389
Need to be replicated here as well: https://github.com/travist/jsencrypt/blob/master/lib/jsrsasign/asn1-1.0.js
