### ISSUE TITLE
"Modules" are no longer listed for download at http://prebid.org/download.html

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#3439]
Modules are no longer listed for download at http://prebid.org/download.html
(I was trying to get the Publisher Common ID module)

Windows 10 - Chrome Browser - (also Firefox and Edge browser)

![image](https://user-images.githubusercontent.com/16692770/51003779-12265580-1506-11e9-8ce3-eebd1494f67d.png)

**Comment by bretg** [comment]
Fixed. Sorry for missing that in the website revision. Thanks for pointing it out.

**Comment by headerbidding** [comment]
Thanks!
