### ISSUE TITLE
"error":"Prebid file not built properly"

### ISSUE THREAD

**Issue by freegames66** [prebid/Prebid.js#3441]
I get an error when I download prebid.js version 1.37.0

> {"error":"Prebid file not built properly","requestId":"4243fa31-bee3-4abd-9f09-af015709274c"}

Adapter include: oneVideo, beachfront, gambid, 33across, emx_digital, rhythmone, appnexus, aol, districtmDMX, conversant, gumgum, sonobi

Modules include: 
GDPR ConsentManagement
DFP Video
Publisher Common ID

**Comment by freegames66** [comment]
Update: I tried excluding each adapter. This problem is caused by the "gamoshi" adapter. Hope it fixed soon.

**Comment by korys** [comment]
I have the same issue with Clickonometris. What's exactly the problem with building scripts. Did something changed recently, because I'm sure it worked earlier.
