### ISSUE TITLE
Removing prebid targeting keys?

### ISSUE THREAD

**Issue by webdeveloperpr** [prebid/Prebid.js#3450]
I'm currently fetching bids and setting targeting using `pbjs.setTargetingForGPTAsync([codeArr])` 

Here is an example of the targeting keys that are being added to the slot.

![screen shot 2019-01-15 at 10 16 14 am](https://user-images.githubusercontent.com/7534346/51189908-0bedfb80-18af-11e9-8b71-cc175c27f2ee.png)

 The problem that I am running into is that I want to remove the non bidder specific keys. Those are the ones in red boxes. I looked at the API docs and couldn't find anything related. Is there a way to actually achieve this without creating a manual implementation?

**Comment by webdeveloperpr** [comment]
this is the current solution after calling the code below after `pbjs.setTargetingForGPTAsync([codeArr])`

```javascript
const removeStandardTargeting = () => {
    var googletag = window.googletag || {};
    googletag.cmd = googletag.cmd || [];
    googletag.pubads().getSlots().forEach(slot => {
        slot.setTargeting('hb_bidder', null);
        slot.setTargeting('hb_adid', null);
        slot.setTargeting('hb_format', null);
        slot.setTargeting('hb_source', null);
        slot.setTargeting('hb_size', null);
        slot.setTargeting('hb_pb', null);
    });
};
```

**Comment by mkendall07** [comment]
@webdeveloperpr 
yeah you can just disable send all bids. http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-Send-All-Bids
```
pbjs.setConfig({ enableSendAllBids: false })
```
