### ISSUE TITLE
[Question] How do I change debug URL params?

### ISSUE THREAD

**Issue by sathwik77** [prebid/Prebid.js#3454]
## Type of issue
question

## Description
I want to change debug URL from pbjs_debug=true to something like customString=true. Is it possible?
I tried changing `"DEBUG_MODE": "pbjs_debug"` to  `"DEBUG_MODE": "customString_debug"` in constants.json file and compiled it. But it doesn't seem to work.
Any suggestions?

**Comment by mkendall07** [comment]
it's not supported unfortunately. We accept pull requests though!

**Comment by jpmohan1111** [comment]
Its seems to work for me. I used "DEBUG_MODE": "prebid_debug" in constants.json and '/?prebid_debug=true' in the url.

**Comment by bretg** [comment]
@sathwik77 - please re-open as required -- seems like it's possible, but if not, we're happy to review a pull request.
