### ISSUE TITLE
Possibly a bug in 1.36 in onetagBidAdapter.js

### ISSUE THREAD

**Issue by olya-fb** [prebid/Prebid.js#3459]
## Type of issue

Bug

## Description

In the code:

  if (typeof bid === 'undefined' || bid.bidder !== BIDDER_CODE || typeof bid.params === 'undefined') {
    return false;
  }

  if (typeof bid.params.pubId !== 'string' || bid.sizes === 'undefined' || bid.sizes.length === 0) {
    return false;
  }

I think instead of 
bid.sizes === 'undefined' 
it was intended to have 
typeof bid.sizes === 'undefined'

otherwise it will fail in the next check (about length) - unless they set somewhere bid.sizes to be 'undefined' if it doesn't exist

## Platform details

1.36

## Other information

https://github.com/prebid/Prebid.js/blob/master/modules/onetagBidAdapter.js

**Comment by bretg** [comment]
@OneTagDevOps - please take a look?
