### ISSUE TITLE
[RFC] Allow adapters to get some information about why they lost the transaction

### ISSUE THREAD

**Issue by gpolaert** [prebid/Prebid.js#3463]
Allowing the adapter to access to some specific information about the transaction may help them to improve their adapter.

Like the timeout hook in the adapter, Prebid can provide a way to get information about the reason why they lost.

To ensure that each publishers will still get the most of the demand and their partners, we have to chose which data we can provide.

For instance, Prebid can provide for each transaction

```js
{
 state: 'BID_LOST',
 numberOfRequests: 4,
 numberOfBidders: 3,
 avgBidCpm: 2.345,
 stdBidCpm: 0.32,
 bidPosition: 2, // 1 means 'WIN'
 auctionDurationMs: 234,
....
}
``` 

What do you think?

**Comment by mkendall07** [comment]
If it's publisher opt in I don't see why it would be a problem.

**Comment by bretg** [comment]
I'd rather not build this unless we have publisher support saying they'd use it. Seems like it could cause a scad of extra network traffic on the web page... imagine there are 5 bidders on the page and all of them want to know why they "lost". That's at least 4 extra calls for the browser, and probably 5 if the ad server doesn't choose header bidding. I'm not aware of many pubs that will be happy with weighing down their users like that without a tangible benefit.

Instead, this sort of information should all be available to the publisher via their analytics adapter. That's one call out of the browser that logs all relevant info for them to be able to optimize their demand path. They may choose to share that info with bidders.
