### ISSUE TITLE
Issue: Add a Creative on DFP

### ISSUE THREAD

**Issue by ibadullah25** [prebid/Prebid.js#347]
Hello,

I am trying to Add a Creative on DFP but having few errors:

When I paste the Prebid creative code on DFP it shows this error: http://prntscr.com/b2r3wu

Additionally, it says creative size is set to 1x1. However my DFP shows -1x-1 size: http://prntscr.com/b2r4y6

Any help would be really appreciated. Thank you

**Comment by mkendall07** [comment]
@ibadullah25 
You should be OK to add the creative anyway, as the DFP message is just a warning. Make sure you select the size override functionality after the creative is added. The steps are described here: http://prebid.org/adops/step-by-step.html#step-3-attach-the-creative-to-the-line-item

**Comment by ibadullah25** [comment]
@mkendall07 

Thank you for your response.

DFP is not allowing me to add a creative using -1x-1 size: http://prntscr.com/b36ubs

**Comment by mkendall07** [comment]
I see. Maybe just select a different size and use the override functionality. I believe that should work. You could try DFP forums for more info on the `-1x-1` size as that sounds like a DFP bug...
