### ISSUE TITLE
Registering a custom global name when importing prebid.js as a module

### ISSUE THREAD

**Issue by bwnodak** [prebid/Prebid.js#3479]
## Type of issue
Question and/or Feature Request

## Description
I'm importing prebid.js as a module thanks to v1.38, which is awesome, thank you so much for implementing this.

I notice this registers `window.pbjs`, which becomes a problem if another instance of prebid is on the page of a different version, or with different bidders registered. To get around this previously, I'd set the `globalVarName` in package.json, but installing with npm seems to preclude this as a viable solution.

Is there a good way to change the global name when using prebid.js as an npm module? I've written a script to be run during the app build process that renames the `globalVarName` in `/node_modules/prebid.js/package.json`, but it's quite a hack.

## Platform details
prebid.js@1.38+

**Comment by snapwich** [comment]
With the release of 2.0 I've added an option to the babel-plugin that writes the global.

If you're using the loader instructions in the README, you should be able to pass the variable using the loader with something similar to the following:

```javascript
let options = require('prebid.js/.babelrc.js');
options.plugins[0] = [options.plugins[0], {
  globalVarName: 'pbjs'
}];

...
// and then in webpack config
use: {
  loader: 'babel-loader',
  options: options
}
```

**Comment by bretg** [comment]
@yonbeastie - Going to assume that snapwich has you covered here. Re-open as needed.

**Comment by holms** [comment]
@snapwich is there's any way to change this var from prebid_js_build_generator repo? I've really need to generate prebid.js with my own globalVarName. Is there's a way just to pass some ENV param, let's say for a Dockerfile..? Or if this requires some PR I'd be happy to contribute.

**Comment by gglas** [comment]
Closing this issue, following here https://github.com/prebid/prebid-js-build-generator/issues/15

**Comment by Tharushan** [comment]
> With the release of 2.0 I've added an option to the babel-plugin that writes the global.
> 
> If you're using the loader instructions in the README, you should be able to pass the variable using the loader with something similar to the following:
> 
> ```js
> let options = require('prebid.js/.babelrc.js');
> options.plugins[0] = [options.plugins[0], {
>   globalVarName: 'pbjs'
> }];
> 
> ...
> // and then in webpack config
> use: {
>   loader: 'babel-loader',
>   options: options
> }
> ```

Note for people still using this fix, as it was reworked in new Prebid.Js versions you will need to use something like : 

```
let options = require('prebid.js/prebid.js/babelConfig.js')({
  globalVarName: 'pbjs'
});

...
// and then in webpack config
use: {
  loader: 'babel-loader',
  options: options
}
```
