### ISSUE TITLE
DFP adops: Mass edit of "inventory sizes" for prebid line items

### ISSUE THREAD

**Issue by pav7** [prebid/Prebid.js#348]
When I created my prebid line items, I added the inventory sizes 728x90, 160x600, and 300x250. Now I want to add a 320x50. Is my only option to manually add 320x50 to the 1000 line items? From what I can find, there are a lot of mass edits you can make but it does not appear that inventory sizes is one of them. Thanks for any help. 

![inventorysizes](https://cloud.githubusercontent.com/assets/17439437/15192879/2b4f6efc-1789-11e6-8977-42c7453d497f.jpg)

**Comment by mkendall07** [comment]
@pav7 Not sure about that. Could you ask on the DFP forums and see if you can get an answer?

**Comment by pav7** [comment]
I asked on DFP forums and also asked one of my bidders' ad ops departments. It is not possible to mass update the inventory on line items. So upon set-up, I guess it would be best to mark off both active and possible planned creative sizes to avoid this. 

 As a result I am going to recreate my line items from scratch with a script.
