### ISSUE TITLE
PubNX Adapter not present in prebid js

### ISSUE THREAD

**Issue by prebid-pubnx** [prebid/Prebid.js#3482]
## Type of issue
Related to new adapter not available in release.

## Description
We have our adapter 'pubnx'. Code was merged 14 days ago. And was added to 1.38.0 Release. 
Now version 1.39 is released. Still we can not see our adapter when we download prebidjs with 'pubnx' selected as adapter. Can someone look into this.

## Steps to reproduce
Please download prebidjs file with pubnx selected.

### Expected results
PubNX Adapter , its endpoint should be available in downloaded prebid js.

### Actual results
PubNX adapter is not present

**Comment by bretg** [comment]
Fixed with #1140
