### ISSUE TITLE
cdn hosted new version of prebid.js

### ISSUE THREAD

**Issue by Anish-Mohan** [prebid/Prebid.js#3490]
## Type of issue
need latest version of cdn hosted prebid.js without downloading it

## Description
 also tried this http://acdn.adnxs.com/prebid/prebid.js , but i cant get new version of prebid from here

**Comment by bretg** [comment]
Sorry, we do not provide hosting for Prebid.js on a CDN. You will need to build it and put it on a CDN for your usage.
