### ISSUE TITLE
Custom Global Name w/ Universal Creative

### ISSUE THREAD

**Issue by GLStephen** [prebid/Prebid.js#3502]
## Type of issue
Question

## Description
I have a couple of questions about renaming the PBJS variable and interaction with universal creative. Does the universal creative need to be custom built to support renaming PBJS? The UC site doesn't specify, but there does seem to a fixed reference to PBJS. The UC also seems to do some renaming when it loads to a local ucTag. Does the UC support renaming PBJS?

**Comment by bretg** [comment]
You're right @GLStephen - that's not ideal. There's only two lines of code that assume pbjs is the variable name, but that's two-too-many.

Assigning to @idettman - we'll try to get to this within a couple of weeks.

**Comment by GLStephen** [comment]
@bretg @idettman I have a PR that follows the same process as Prebid.js. It has a a variable in the pckage.json and a new replace command in the webpack.fonf.js file. I'll submit it. There are two places in the renderingManager but the sinon.spy hook needed to match also.
