### ISSUE TITLE
Google Analytics Spreadsheet Displaying Weird Values

### ISSUE THREAD

**Issue by millieone** [prebid/Prebid.js#351]
I am trying to do the GA tracking for the first time.

When I ran the spreadsheet for the first time it said something about updating to the latest version.

When I look at the results I get values like this:
![image](https://cloud.githubusercontent.com/assets/17550944/15220145/1391683a-182c-11e6-9f9c-79a242093af5.png)

I do notice in the raw data doing a custom report there are no requests for the bidders. Is that causing the issue? I just want to make sure it is not related to the spreadsheet updating and thsi being widespread.

Could it be related to throttling? I didn't turn off off enableDistritbution as now I only have 3 bidders but my site does get decent traffic.

Below is my GA code in case I set that up wrong as the docs didn't say where to put the pbjs.que.push function in realtion to the    ga('create', 'XXX', 'auto'); and ga('send', 'pageview'); I put it after.

`
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'XXX', 'auto');
  ga('send', 'pageview');

pbjs.que.push(function() {
    pbjs.enableAnalytics({
        provider: 'ga',
        options: {
            global: 'ga', // <string> name of GA global. Default is 'ga'
            enableDistribution: true,
        }
    });
});

`

**Comment by Heray** [comment]
The request number not present shouldn't have anything to do with the spreadsheet. @protonate could you help take a look real quick on why the request data is not logged? Could it be possible that `enableDistribution` is set to true?
