### ISSUE TITLE
Disable SRA for prebid server

### ISSUE THREAD

**Issue by thomashmc1** [prebid/Prebid.js#3526]
## Type of issue
Question

## Description
Currently when a publisher setup s2s request with multiple adUnits in the page, it always end up sending out SRA with multiple impressions to prebid server, is there a way to configure it so that for each adUnit in the page it will send out a one request to prebid server?
Example:
2 adUnits in page -> 2 request to prebid-server

**Comment by bretg** [comment]
You would need to set up two auctions.

```
     pbjs.requestBids({
                    adUnitCodes: ["firstAdUnit"],
                    bidsBackHandler: handler1,
                    timeout: PREBID_TIMEOUT
     });
     pbjs.requestBids({
                    adUnitCodes: ["secondAdUnit"],
                    bidsBackHandler: handler2,
                    timeout: PREBID_TIMEOUT
     });
```
