### ISSUE TITLE
Prebid 2.1.0 release documentation

### ISSUE THREAD

**Issue by lewismoore10100** [prebid/Prebid.js#3535]
## Type of issue
Documentation (Release)

## Description
In Prebid 2.1.0 release note, *Unruly: add userSync functionality* links to the wrong git commit, #3472 it should link to #3460 

## Steps to reproduce
Seen here https://github.com/prebid/Prebid.js/releases

**Comment by bretg** [comment]
fixed. thanks for the correction.
