### ISSUE TITLE
Bidder Codes hard to find in New Prebid Web Site 

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#3538]
I had trouble finding the bidder codes page in the new web site. i.e.: http://prebid.org/dev-docs/bidders 

Iooked for it in the "Adapter" sub menu.
(After much searching, I found it finally in the "Reference" section)

Suggestion: Also add it to the "Adapter" section.

**Comment by bretg** [comment]
Thanks for the feedback @headerbidding - we've made a couple of changes:
- relabeled that left-nav section "Adding an Adapter"
- promoted the Publisher API and the Bidder Params right into the top 'Product' menu. These are two of the most popular pages on the site, so makes sense.

**Comment by headerbidding** [comment]
Thank you!!
