### ISSUE TITLE
I2I 3.0 list of planned changes

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#3556]
## Type of issue
I2I 
## Description
This is a placeholder for the Prebid.js 3.0 release. Issues will be linked here for potential inclusion into a 3.0 release. Filter link: https://github.com/prebid/Prebid.js/issues?q=is%3Aissue+is%3Aopen+label%3A%223.0+API+Change%22

Target Release Date:
Q2/Q3 2019

Issue list: 

 - https://github.com/prebid/Prebid.js/issues/3277
 - https://github.com/prebid/Prebid.js/issues/4005
- https://github.com/prebid/Prebid.js/issues/2959 (rendered bids being returned when they are not available 
- #3072 (new referrer functionality) 
- Remove PBS legacy endpoint support in PBS adapter #4172

**Comment by jaiminpanchal27** [comment]
We should ask all adapters to update their code and start using http://prebid.org/dev-docs/bidder-adaptor.html#referrers

https://github.com/prebid/Prebid.js/issues/3072

**Comment by mkendall07** [comment]
closing this in favor of using labels. Link to see 3.0 features:
https://github.com/prebid/Prebid.js/labels/3.0%20API%20Change
