### ISSUE TITLE
Sync call made to PubMatic by default

### ISSUE THREAD

**Issue by yoaap** [prebid/Prebid.js#356]
Hi Team,

I'm using the latest version of Prebid. The calls being made to PubMatic are sync by default (They need this to be async). I had a word with PubMatic tech team and below is the sync call to Pubmatic  being triggered through Prebid:

http://gads.pubmatic.com/AdServer/AdCallAggregator?SAVersion=1000&pageURL=http%3A%2F%2Fwww.wittyfeed.com%2Fstory%2F19570%2F1%2Fronaldinho-the-legend-and-the-reason-we-are-in-love-with-football%3Fi%3D2&inIframe=1&kadpageurl=http%3A%2F%2Fwww.wittyfeed.com%2Fstory%2F19570%2F1%2Fronaldinho-the-legend-and-the-reason-we-are-in-love-with-football%3Fi%3D2&pubId=143834&kltstamp=2016-5-12%2017%3A8%3A27&timezone=5.5&screenResolution=1440x900&ranreq=0.2652110827127292&adslots=%5BWittyFeed_story_sidebar_ATF%40300x250%2CWittyFeed_story_sidebar_BTF%40300x250%2CWittyFeed_story_top_ATF_leaderboard%40728x90%2CWittyFeed_story_middle_leaderboard%40728x90%2CWittyFeed_story_bottom_leaderboard%40728x90%5D&lmk=1463053107478

The call is by default sync without callback in response. To make it async, a variable 
var pm_async_callback_fn= 'pm_async_callback’; needs to be set by PreBid.

This will pass a callback function name in call e.g:
http://gads.pubmatic.com/AdServer/AdCallAggregator?SAVersion=1000&pageURL=http%3A%2F%2Fwww.wittyfeed.com%2Fstory%2F19570%2F1%2Fronaldinho-the-legend-and-the-reason-we-are-in-love-with-football%3Fi%3D2&inIframe=1&kadpageurl=http%3A%2F%2Fwww.wittyfeed.com%2Fstory%2F19570%2F1%2Fronaldinho-the-legend-and-the-reason-we-are-in-love-with-football%3Fi%3D2&pubId=143834&pm_cb=pm_async_callback&kltstamp=2016-5-12%2017%3A8%3A27&timezone=5.5&screenResolution=1440x900&ranreq=0.2652110827127292&adslots=%5BWittyFeed_story_sidebar_ATF%40300x250%2CWittyFeed_story_sidebar_BTF%40300x250%2CWittyFeed_story_top_ATF_leaderboard%40728x90%2CWittyFeed_story_middle_leaderboard%40728x90%2CWittyFeed_story_bottom_leaderboard%40728x90%5D&lmk=1463053107478

Let me know if there's any work around for this issue.

Thanks,
Animesh

**Comment by mkendall07** [comment]
@yoaap 
Thanks for the info. We'll need to update the PubMatic adapter to support this async version. Shouldn't be a big code change. Feel free to submit a PR if you already have an implementation available.

**Comment by yoaap** [comment]
Hi Matt,

We don't have implementation available with us. Let me know if there's any way I can help you with this.

Thanks,
Animesh

**Comment by mohsink4u** [comment]
Hi Guys,

This is how PubMatic tag looks like. 
<script type="text/javascript">
var pm_optimize_adslots = ['site2_section2@300x250','site3_section3@300x250'];
var pm_pub_id = 7777;
var pm_async_callback_fn= 'pm_async_callback';
</script>
<script type="text/javascript" src="http://ads.pubmatic.com/AdServer/js/gshowad.js">
</script>

adding this component is going to fix this. 
var pm_async_callback_fn= 'pm_async_callback';

Can we have an timeline on this fix. Multiple publishers are facing this issue.

regards,
Mohsink4u

**Comment by mkendall07** [comment]
@mohsink4u 
Do you have an implementation guide from Pubmatic? To be clear, the current implementation is "async" because it renders the entire pubmatic content into an iframe and listens to the iframe "ready" event. So once the script has been loaded we trigger the callback. While not ideal, it's not "sync".

**Comment by mohsink4u** [comment]
You can find PubMatic's implementation guide in ticket : https://github.com/prebid/Prebid.js/pull/186
the name of the PDF is Decision Manager Standard 2.4 Technical Integration Guide_1.pdf
and you will need to look for the info in page number 10.

Please let know if this helps.
Mohsink4u

**Comment by dverbru** [comment]
Hi,
This issue is currently preventing us (as a big publisher) to adopt Prebid.js to integrate with PubMatic. Are there any plans on starting with this soon?

**Comment by mkendall07** [comment]
@dverbru , @mohsink4u 
PR is up for this change: https://github.com/prebid/Prebid.js/pull/453

**Comment by mkendall07** [comment]
This is resolved.

**Comment by mohsink4u** [comment]
Great to know. Is there any specific build number for this....or how to get the code alongwith with this fix?

Mohsin

**Comment by dverbru** [comment]
Awesome, thank you very much!

**Comment by matthewlane** [comment]
@mohsink4u This fix is in [Prebid 0.11.0](https://github.com/prebid/Prebid.js/releases/tag/0.11.0)
