### ISSUE TITLE
Two "prebid.js" files on the same page

### ISSUE THREAD

**Issue by nikhil-gujarathi** [prebid/Prebid.js#3560]
I am using prebid.js for appnexus, rubicon and sortable. Dynamically, we add the Prebid.js in the head section of the page. But, after that publisher also adds the prebid.js (only appnexus). 
Due to this, prebid is throwing an error in console saying that "ERROR: Trying to make a request for bidder that does not exist".
I saw issue #492. But just looking for options, so that we can run both the scripts independently.

**Comment by freegames66** [comment]
The same problem. I am using ads of Valueimpression and Adinplay. They are using two different prebid.js versions. This causes advertising conflicts. Are there any solutions to this problem?

**Comment by jbartek25** [comment]
You can run multiple instances of Prebid.js without any problem as long as they use different global variable name, not all pbjs. Pick a new name in [package.json](https://github.com/prebid/Prebid.js/blob/master/package.json#L20), rebuild Prebid.js and rename pbjs in the corresponding config on your page to the new name.
