### ISSUE TITLE
Sortable adapter causes an error due to an error in a variable name

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#3566]
## Type of issue
BUG

## Description
Sortable used a different letter case for a variable. They declared it as `syncUrl` and later referenced as `syncurl`. This results in an error.
**https://github.com/prebid/Prebid.js/blob/master/modules/sortableBidAdapter.js#L138**

## Steps to reproduce
Create a build that includes sortable adapter. Run it on some page together with GDPR content management

### Expected results
No errors raised

### Actual results
```
Uncaught ReferenceError: syncurl is not defined
    at Object.getUserSyncs (sortableBidAdapter.js:139)
    at registerSyncs (bidderFactory.js:324)
    at afterAllResponses (bidderFactory.js:185)
    at utils.js:910
    at Object.onFailure [as error] (bidderFactory.js:315)
    at XMLHttpRequest.x.onreadystatechange (ajax.js:51)
```

## Platform details
Prebid v 2.2.0

**Comment by jaiminpanchal27** [comment]
@bgahagan @shannonAB Please verify and update

**Comment by pm-harshad-mane** [comment]
Hello @jaiminpanchal27 ,

I think the issue is fixed and can be closed,
Refer https://github.com/prebid/Prebid.js/blob/master/modules/sortableBidAdapter.js#L138
