### ISSUE TITLE
 'getSlotElementId' of undefined issue with Universal Creative

### ISSUE THREAD

**Issue by gchicoye** [prebid/Prebid.js#3579]
## Type of issue
Bug

## Description
While using the Universal Creative on 2.2.0 Prebid.js, I get trying to show Appnexus ads this error:
```
prebid.js:3 Uncaught TypeError: Cannot read property 'getSlotElementId' of undefined

    at o (prebid.js:3)
    at prebid.js:3
    at Array.forEach (<anonymous>)
    at prebid.js:3
    at a (prebid.js:3)
```
It revert to this part of Prebid.js code:
```
(function(e){return e})).getSlotElementId()):window.apntag?(n=t,(r=window.apntag.getTag(n))&&r.targetId):t),
```

## Steps to reproduce
Check the test page

## Test page
https://bit.ly/2SgXiFt

### Expected results
An Ad
### Actual results
A blank ad

## Platform details

Prebid 2.2.0, Chrome

**Comment by mkendall07** [comment]
Thanks for the bug report. I'm not able to see the error on your test page. Do you know if it only occurs when certain bidders respond with a bid or some other condition perhaps?

**Comment by gchicoye** [comment]
Hi,

You might have more chances here.
https://bit.ly/2tCzUs7

Thanks!

Gabriel

**Comment by jsnellbaker** [comment]
@gchicoye I've been periodically reloading these test pages to try to replicate the issue, but each time the creative template that was used was the basic `renderAd` code instead of the Universal Creative code.
