### ISSUE TITLE
getWinningBidTargeting calls googletag.pubads().getSlots() but I don't use DFP

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#358]
So after #349 getWinningBidTargeting calls to googletag.pubads().getSlots(). I use AppNexus instead of DFP, so googletag is not defined for me and this call leads to an error.

I've assumed that using DFP is not a requirement with prebid.

**Comment by mkendall07** [comment]
@dmitriyshashkin 
It is not. We will fix it. Thanks for bringing it to our attention

**Comment by mkendall07** [comment]
@dmitriyshashkin 
I pushed a fix on this branch, want to test it out quick for us? https://github.com/prebid/Prebid.js/tree/remove-dfp-dependency
