### ISSUE TITLE
bidId missing from response event

### ISSUE THREAD

**Issue by TheMaskMaker** [prebid/Prebid.js#3587]
## Type of issue
Bug

## Description
When a call to requestBids contains multiple of the same bid adapter for the same placement, there is no way to correlate each individual bid in the request event object to the resulting response event object. The transaction and request ids of the request are the same for each individual bid. The bidId is unique, but it is not returned in the response event object. The bidId must be returned in the response object for correlation to exist.

**Comment by TheMaskMaker** [comment]
Please advise if more information is required or some protocol of issue posting is amiss. This is an active issue but seems to be marked as stale. I am unfamiliar with github repo protocol any advise would be welcome.

**Comment by jaiminpanchal27** [comment]
@TheMaskMaker Can you share jsfiddle or sample config for above scenario ?

**Comment by TheMaskMaker** [comment]
I made a fiddle example of our code and got permission, and, of course, we are no longer able to reproduce! It seems like we can now see the requestId of the response map to the bidID of the sub-request. Closing this issue, thanks your your assistance.
