### ISSUE TITLE
Multiple auction responses

### ISSUE THREAD

**Issue by Alejandro-MartinG** [prebid/Prebid.js#3592]
I am using Prebid in a environment of multiple acutions and this work perfectly but I have some doubts with the responses. I tried to make my own debug logs executing `pbjs.getBidResponses();` and printing a table but I find a "race condition" when Prebid fire 2 request sometimes I can only see the last response duplicated.

Can you give some feedback about if It's possible solve this "race condition"?

Note: I am using Prebid 1.39.0 alongside DFP.

Thanks

**Comment by jaiminpanchal27** [comment]
@Alejandro-MartinG pbjs.getBidResponses() should return the bid responses for last auction. There was some bug with getting the last auction id. We fixed that here. https://github.com/prebid/Prebid.js/pull/3492
Can you try 2.0 and see if it improves.

**Comment by Alejandro-MartinG** [comment]
Thank you @jaiminpanchal27 !
I gonna test the last version of Prebid.

Do you know if in the future Prebid will return all auction responses?
