### ISSUE TITLE
Optimera plugin sometimes doesn't return impressions with AppNexus

### ISSUE THREAD

**Issue by mcallari** [prebid/Prebid.js#3597]
## Type of issue
Bug

## Description
Optimera's configuration requires the use of size 0,0 which, in some instances, causes the AppNexus ad server to respond to ad requests but not fill impressions. 

## Steps to reproduce
* Configuration using AppNexus
* Define sizes without [0,0]
* Deliver Ads for one day, check AppNexus UI numbers versus DFP delivered impressions
* Add size [0,0] and repeat.
* If fill rate is about the same then there is no issue.

**Comment by mkendall07** [comment]
could you clarify what you mean by ad server response but not fill?
