### ISSUE TITLE
Specific time out for each Ad unit

### ISSUE THREAD

**Issue by gauzerin** [prebid/Prebid.js#360]
Hi has anyone built something like that? 

We want to serve ATF mobile adunits with timeout of only 500-700ms to guarantee highest possible view ability. At the same time we want to keep auction open a bit longer for the rest of ad units in hope that more valuable bids will come in.

**Comment by protonate** [comment]
I believe this can be accommodated with Prebid Auctions #386 in that separate auctions can be created for the different timeout requirements.

**Comment by mercuryyy** [comment]
This is a great idea @gauzerin, @protonate looks like the prebid actions are closed, will you consider adding this option for the next release? most bidders after 2x3 frequency cap, their response time doubles as their direct demand cap is reached and they call other exchanges but they still return high cpm, sometimes even higher cpm's at 3000ms+. 

having the ability to set timeout x to above the fold units and y to other units can increase revenue by a lot.

**Comment by protonate** [comment]
A workaround would be to run to separate auctions -- calls to `pbjs.requestBids` -- with the two different timeout configurations.

**Comment by mercuryyy** [comment]
@protonate will something like this fly? 

How will this run in dfp single request ? since we using diffrent timeouts will it still show the first ad units in the correct timeouts ? 

        pbjs.addAdUnits(adUnitsOne);
        pbjs.requestBids({
timeout: 1000,
            bidsBackHandler: sendAdserverRequest
        });

        pbjs.addAdUnits(adUnitsTwo);
        pbjs.requestBids({
timeout: 2000,
            bidsBackHandler: sendAdserverRequest
        });

**Comment by protonate** [comment]
Making two calls to `requestBids` will result in two ad server DFP calls, and the first call should complete before making the second call, perhaps by hooking in to the `auctionEnd` event. When #477 is merged you will be able to fire both requests and they will be queued sequentially. One caveat of this workaround is that DFP single request roadblocks and line items would need to be split between the two requests.

**Comment by protonate** [comment]
@mercuryyy have a look here for the expected parameter names for `requestBids`
http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.requestBids

Timeout values can be passed as `timeout`.

```
 pbjs.addAdUnits(adUnitsOne); pbjs.requestBids({ timeout: 1000, bidsBackHandler: sendAdserverRequest }); 
 pbjs.addAdUnits(adUnitsTwo); pbjs.requestBids({ timeout: 2000, bidsBackHandler: sendAdserverRequest }); 
```

Note that we are passing an object to `requestBids` with expected property names not individual arguments as you had it with `var PREBID_TIMEOUT=2000`.

**Comment by mercuryyy** [comment]
Many thanks.

**Comment by protonate** [comment]
Closing as answered -- this behavior can be accomplished in an implementation rather than within prebid core.
