### ISSUE TITLE
Purpose/further specs for userSync timeout

### ISSUE THREAD

**Issue by tr-coull** [prebid/Prebid.js#3600]
## Type of issue
Question

## Description
We recently tested switching on pixel & iframe userSync with the default settings. Though we can't be 100% sure, it looked like this caused a decrease in impressions and some unexpected bid request timeouts. We need to use a "global" 3s timeout, as our pbjs implementation is loaded into a VPAID iframe which may be destroyed by the host, or cleaned up by our own code after 3s, or when there is no auction winner. We therefore have the PrebidTimeout set to 2500ms and the FailsafeTimeout set to 2750ms.

My question is, why is the default `syncDelay` for userSync 3s? The docs ( http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-ConfigureUserSyncing-HowUserSyncingWorks ) suggest this is the time before the adapters are allowed to *start* sync functions. Or is it the time they are allowed to complete sync activity? When does the syncing actually start in terms of the auction process/handling?

We are testing again, specifically setting `syncDelay` to 150ms to see if that improves anything, though if a longer time is better, this may not help.

## Platform details
Prebid.js v2.1.0

**Comment by mkendall07** [comment]
it's the time delay after the auction to start the user sync activity. The idea behind the delay is to stay out of the critical path of the auction/actual ad delivery. Reducing it will trigger it closer to the auction completion.
