### ISSUE TITLE
prebid.js size

### ISSUE THREAD

**Issue by mahammer** [prebid/Prebid.js#3603]
I am really wondering why pbjs 2.x is such a behemoth?
The pbjs 1.x builds with the adapters I needed are around 180kb.
Now enter pbjs 2.x is moving towards 350kb.

That's a lot to load, especially on mobile devices.
Could someone tell my why it grew or had to grow so much in size?
The more you have to load, the later the auction can start, the less it becomes headerbidding ;)

**Comment by GLStephen** [comment]
In PB 2.0 a few adapters contribute more net size. Particularly Criteo.

**Comment by mahammer** [comment]
Ah. Just tested 2.4 with just the GDPR module comes in at 122kb
So there's literally 220kb of adapter piled on top.
