### ISSUE TITLE
clean-up and update the test/fixtures/fixtures.js test data

### ISSUE THREAD

**Issue by jsnellbaker** [prebid/Prebid.js#3604]
## Type of issue
Refactor/Clean-up

## Description
The test objects located in the `test/fixtures/fixtures.js` file seem slightly dated and incorrect in some parts.

For example, at this point [here](https://github.com/prebid/Prebid.js/blob/master/test/fixtures/fixtures.js#L628) in the `getAdUnits()` function - the returned object more resembles a bidderRequest object rather than a typical adUnit.

Additionally, there are new fields that have been put into practice (like `adUnit.mediaTypes`) while some other fields have been discouraged (like `adUnit.sizes`).

We should review these test objects and bring them up to date and ensure they're being used correctly.  Further if there are any gaps (ie missing fields or types of objects), we should fill aim to fill them if possible.

**Comment by gglas** [comment]
@ChrisHuie to work on it

**Comment by ChrisHuie** [comment]
still fixing. Revised test fixtures soon.
