### ISSUE TITLE
Bug in Prebid 2.4.0

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#3606]
Moving from 2.3 to 2.4 has caused a bug that halts Prebid. I wasn't aware there we any breaking changes in 2.4?

![screenshot 2019-03-01 at 15 09 04](https://user-images.githubusercontent.com/425262/53647559-b9d22100-3c35-11e9-8d0b-a5f2aee91c99.png)

![screenshot 2019-03-01 at 15 08 56](https://user-images.githubusercontent.com/425262/53647573-bf2f6b80-3c35-11e9-82b8-232f32fd8a91.png)

**Comment by GLStephen** [comment]
Not to be overly pedantic, but a breaking change is a change which intentionally breaks functionality. This looks like it might be a plan old bug if it's an issue in Prebid at all. Given the section of code it looks like a misconfig in a bidder's params, but I didn't dive deeply into it.

**Comment by mkendall07** [comment]
definitely not intentional if it's there. Can you provide a test page?

**Comment by cwbeck** [comment]
@GLStephen - yes badly phrased!! I just saw some references to a feature around management of adunits which may or may not be linked to this bug: https://github.com/prebid/Prebid.js/pull/3527

@mkendall07 - I'll see what I can do. this is all compiled into a bigger project and staged locally. we use switcharoo to test against sites before we deploy.

**Comment by mkendall07** [comment]
@cwbeck 
if you can reproduce with a minimal setup using JSfiddle that also works.

**Comment by cwbeck** [comment]
@mkendall07 - clearing out NPM cache and re-installing seems to have done the trick.
