### ISSUE TITLE
[Native] not correct replacing placeholders of image and icon 

### ISSUE THREAD

**Issue by naoto0822** [prebid/Prebid.js#3607]
## Type of issue

With version 2.4.0 and up ( about #3573 ).

## Description

If `image` and `icon` configured `sendId: true` in Ad Unit config,  placeholders(`hb_native_image:adid` or `hb_native_icon:adid`) is not correctly replaced but  replaced `[object Object]`.
Placeholders of `title`, `body`... is correct replaced.

Please teach me workaround or correct implementation.

reference following:
http://prebid.org/dev-docs/show-native-ads.html#sending-asset-placeholders

## Steps to reproduce

DFP creative template.html
https://gist.github.com/naoto0822/3745224fec29c5992590df5663eb2c8c

DFP creative template css
https://gist.github.com/naoto0822/b7bce5104c448e8f444aaefb4c5d1ec5

Ad Unit configure
https://gist.github.com/naoto0822/8f5fe2da7c401c2501983689f9e40aad

### Actual results

Image didn't displayed.
![image](https://user-images.githubusercontent.com/1576894/53730456-56592500-3ebb-11e9-9889-a6e1e4fa2550.png)

and background url is replacing `[object Object]`.

![image](https://user-images.githubusercontent.com/1576894/53730421-36296600-3ebb-11e9-966b-ccb6f819a1f5.png)

### Expected results

![image](https://user-images.githubusercontent.com/1576894/53730996-c6b47600-3ebc-11e9-8372-55c6cdf37b8a.png)

## Platform details

prebid.js >= 2.4.0

**Comment by matthewlane** [comment]
@naoto0822 Thanks for the bug report. This issue will be fixed with #3609

**Comment by naoto0822** [comment]
@matthewlane Thanks for quick response!

**Comment by lanceloti** [comment]
I'm havving same issue with call to action button (hb_bidder_cta). 

cta text is "Try it now!" and DFP doesn't support "!" (exclamation), so I changed to sendId = true and now cta is "undefined".

![Screenshot_624](https://user-images.githubusercontent.com/17436827/67230748-407d7d80-f414-11e9-9b37-a5eae4577dfa.png)
![Screenshot_623](https://user-images.githubusercontent.com/17436827/67230749-407d7d80-f414-11e9-8870-1f95e54b4dec.png)

**Comment by jsnellbaker** [comment]
@lanceloti Can you open this as a new issue and provide a test page (or a copy of the adUnit config) so we can investigate?

Thanks!
