### ISSUE TITLE
Latest Universal Creative and Google Safeframe doesn't work with Prebid <= 1.23

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/Prebid.js#3616]
## Type of issue
Bug

## Description
When using Safeframe, the latest universal creative doesn't render an ad with Prebid.js v 1.23 and below. If you uncheck safeframe in GAM it works.

No error messages are being output.

I would assume a version of the universal creative that correlates with the prebid.js version being used will work, but not tested.

## Steps to reproduce
See above

## Other information
It would probably be enough to just document this behavior, but if the fix is simple it would be great to have as the "Guide to DFP Setup" states that "Serve into a safeframe" can be checked or unchecked, both should work, and the creative being shown is the latest.

**Comment by bretg** [comment]
Thanks @bjorn-lw .   Added a note to the 'step-by-step' doc.

![Screen Shot 2019-03-08 at 5 17 01 PM](https://user-images.githubusercontent.com/4412838/54059204-582a2d80-41c6-11e9-971c-181d6dc42503.png)

We be happy to review a PR with a fix to the Universal Creative and/or PBJS.
