### ISSUE TITLE
Recommendation for Lazy Loading setup

### ISSUE THREAD

**Issue by mwaqarakram94** [prebid/Prebid.js#3620]
Hey,

I have gone over a lot of setups that used different types of lazy loading integration with prebid. 

Can someone please guide me which one is the best one in 2019? 

Thank you so much

**Comment by bretg** [comment]
http://prebid.org/dev-docs/examples/adunit-refresh.html

If there's anyone who feels there's a better way to do this, please submit a PR for that page. Thanks.
