### ISSUE TITLE
Prebid Server Adapter: BidRequest with currency

### ISSUE THREAD

**Issue by adriafolchmrf** [prebid/Prebid.js#3627]
## Type of issue
Question

## Description
We are trying to send the cur parameter in the payload to the prebid server but we are not seeing any way to define this by configuration. This is specified in the BidRequest on the IAB documentation found in the next link: https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf

Is there any plan to implement this feature? Should we better open a PR to implement it?

**Comment by bretg** [comment]
Good find. I've opened a ticket on the Rubicon side to address this. Might be a couple weeks until we get to it. If you need it sooner, you'd be welcome to submit a change -- I think it's a pretty small fix around this line -- https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter/index.js#L486

**Comment by jsnellbaker** [comment]
@bretg @idettman 

It looks like this currency request/issue was addressed by:
https://github.com/prebid/Prebid.js/pull/3951 

Can you confirm when you have the chance?
Thanks.

**Comment by bretg** [comment]
Yup, fixed with 2.26. the prebidServerBidAdapter will automatically take the `currency.adServerCurrency` and forward to PBS as `cur`
