### ISSUE TITLE
Aliases in S2SConfig and SyncEndpoint issue

### ISSUE THREAD

**Issue by adriafolchmrf** [prebid/Prebid.js#3628]
## Type of issue
Bug

## Description
When specifying aliases in prebid as suggested in the documentation (http://prebid.org/dev-docs/get-started-with-prebid-server.html) we are seeing that in the payload to the syncEndpoint we are not using the proper bidder name but the alias instead, therefore failing due to not finding the bidder in the server.

## Steps to reproduce
Adding any alias in the bidders inside the s2sConfig will send them directly to the syncEndpoint without checking for the proper bidder name.

### Expected results
Only sending actual bidders to the syncEndpoint

### Actual results
Everything set in the s2sConfig.bidders is sent to syncEndpoint

## Platform details
Prebid 1.23

**Comment by jaiminpanchal27** [comment]
@adriafolchmrf Thanks for reporting this. 
When publisher is using alias `s2sConfig.bidders` list, PBS adapter should find the actual bidderCode and use that to send to userSyncEnpoint.

**Comment by adriafolchmrf** [comment]
Just added a PR #3640 to discuss the approach to solve this bug.

Thanks
