### ISSUE TITLE
There should be a lightweight way of building prebid

### ISSUE THREAD

**Issue by kitwestneat** [prebid/Prebid.js#363]
For people who just need to compile prebid, it would be nice if there were a more minimal package.json and corresponding gulpfile. It currently requires 300M+ of support packages to compile.

**Comment by ialex** [comment]
Try the online downloader: http://prebid.org/download.html

**Comment by kitwestneat** [comment]
I'm modifying prebid though, so that's unfortunately not an option.

**Comment by mkendall07** [comment]
@kitwestneat 
While I agree there is a lot of dev package dependencies, most have a specific purpose. We'll make an effort to clean up / remove what is not needed but I don't see this as major issue at this time.
