### ISSUE TITLE
How do I find an advertiser winning instream video ads?

### ISSUE THREAD

**Issue by Van0128** [prebid/Prebid.js#3635]
Hello friends. Currently, we are using header bidding through prebid.js code and building up the report system with header bidding.
We have display ads and video ads. We also work with SSPs partners such as appnexus, pubmatic, rubicon, ... and ADX.
For display ads, we found the winning advertiser.
For video ads, we use the IMA SDK player. However, we do not know when ADX beat other bidders.
This makes our report be misleaded. 
Has anyone here ever encountered the same issue?
Looking forward to hearing from you!
Thank you!

**Comment by bretg** [comment]
Prebid doesn't currently have the ability to inject another layer of a VAST XML wrapper to support header bidding analytics. I'd say there are two choices:

1) add additional tracking on the advertiser/DSP side when the VAST trackers are entered
2) break out line items in the ad server so reporting can be done there
