### ISSUE TITLE
Advangelists Bidder adapter not showing on download page

### ISSUE THREAD

**Issue by trchandraprakash** [prebid/Prebid.js#3636]
Hi, Can you please let me know when Advangelist's bidder adapter will get listed in Download page.
Here - http://prebid.org/download.html
I see it got release with this version - https://github.com/prebid/Prebid.js/releases/tag/2.5.0
Let me know if anything pending from my side. Thanks.

**Comment by trchandraprakash** [comment]
I see Advangelists bidder on Download page now, Thanks.  https://github.com/prebid/prebid.github.io/pull/1177
Now I am not able to download prebid.js bundled with my adapter, can you please let me know what would be next step.
Here is the error i am seeing
{"error":"Prebid file not built properly","requestId":"28b9ca68-21dd-46b1-83b3-8636b3b3371e"}

Thanks.

**Comment by jaiminpanchal27** [comment]
@trchandraprakash Your adapter file name and bidderCode mentioned in markdown file [here](https://raw.githubusercontent.com/prebid/prebid.github.io/master/dev-docs/bidders/advangelists.md) should be same. 

In your case:  
Your adapter file name is : advangelistsBidAdapter.js
bidderCode in markdown file should be : `advangelists`

**Comment by trchandraprakash** [comment]
Hi Jaimin,

Thanks for getting back. I have updated markdown file and it is available
on this pull request.
https://github.com/prebid/prebid.github.io/pull/1208

Thanks & Regards
Chandra Prakash

**Comment by jaiminpanchal27** [comment]
Closing as it is resolved
