### ISSUE TITLE
Instream video with DFP

### ISSUE THREAD

**Issue by jamesvard** [prebid/Prebid.js#3638]
Hello, I'm using header bidding.
I have bidder SSPs like rubicon, appnexus, oneVideo ... I also use ADX
I had trouble getting the bidder to win the instream video ad between bidder and ADX
Can anyone here help me?
Thank you!

**Comment by bretg** [comment]
If you have your line items set up properly (http://prebid.org/dev-docs/show-video-with-a-dfp-video-tag.html), then you can inspect what kind of bids are coming in from each of the SSPs. e.g. with http://prebid.org/dev-docs/troubleshooting-tips.html#see-all-bids-in-the-console
