### ISSUE TITLE
utils.getTopWindowUrl() returns improper url - gumgum adapter

### ISSUE THREAD

**Issue by wayne-gumgum** [prebid/Prebid.js#3644]
## Type of issue
Prebid util function bug

## Description
It seems that gumgum's "pu", or page url parameter is being mishandled inside iframes. We are experiencing an issue where the topUrl is not being read properly using prebid's built-in util function (getTopWindowUrl).

**GumGum Adapter code**
```
try {
    topWindow = global.top;
    topScreen = topWindow.screen;
    topUrl = utils.getTopWindowUrl()
  } catch (error) {
    utils.logError(error);
    return browserParams
  }

  browserParams = {
    vw: topWindow.innerWidth,
    vh: topWindow.innerHeight,
    sw: topScreen.width,
    sh: topScreen.height,
    pu: topUrl,
    ce: utils.cookiesAreEnabled(),
    dpr: topWindow.devicePixelRatio || 1,
    jcsi: getJCSI()
  }
```
See screenshots below for expected and actual values for topUrl.

## Steps to reproduce
This issue is happening on publishers that are integrating prebid HB and implementing GumGum as an official provider. To visualize this issue in chrome dev tools, please see below:

## Test page
https://www.thefader.com/2019/03/15/teyana-taylors-issues-hold-on-video-features-tyler-the-creator-asap-rocky-lori-harvey-and-more

Please visit the above page on Chrome -> inspect element using mobile emulator -> type in 'hbid' as a search parameter under the network tab and refresh the page. Click the call where the appropriate product id under the query string parameters (**pi: 2** in this case) 

### Expected results
![Screen Shot 2019-03-15 at 4 42 31 PM](https://user-images.githubusercontent.com/48607085/54467300-71405a80-4741-11e9-8ecd-ebc390cfda38.png)

### Actual results
![Screen Shot 2019-03-15 at 3 29 58 PM](https://user-images.githubusercontent.com/48607085/54467310-7dc4b300-4741-11e9-9de8-32c53983428b.png)

## Platform details
prebid.js v1.26.0
chrome v72.0.3626.121
.nvmrc 7.0

**Comment by bretg** [comment]
Please try bidderRequest.refererInfo as described in http://prebid.org/dev-docs/bidder-adaptor.html#referrers

That field is set by the more sophisticated https://github.com/prebid/Prebid.js/blob/master/src/refererDetection.js
