### ISSUE TITLE
Impressions discrepancy with Converant

### ISSUE THREAD

**Issue by orzilca** [prebid/Prebid.js#3650]
## Type of issue
Question

## Description
Having an average discrepancy of 20%-25% in impressions with **Converant**.
Is anyone else experiencing such issue?

### Expected results
Impressions discrepancy of less than 5% (acceptable discrepancy level)

### Actual results
More than 20%

## Platform details
Prebid.js version 1.17

**Comment by bretg** [comment]
Please take this issue up with your conversant account contact or mediapsr@conversantmedia.com. For the record, Prebid.js 1.17 is almost a year old, and many performance improvements have been made. You should consider upgrading to a more recent version.
