### ISSUE TITLE
Timeouts aren't cleared between bids

### ISSUE THREAD

**Issue by kitwestneat** [prebid/Prebid.js#366]
Because the setTimeout call is never cleared, if two bid requests happen within the prebid timeout, bidmanager.executeCallback will be run prematurely, at the timeout of the first bid request. bidmanager.executeCallback should call clearTimeout on setTimeout handle.

**Comment by mkendall07** [comment]
@kitwestneat 
This will be resolved once https://github.com/prebid/Prebid.js/pull/353 is merged

**Comment by kitwestneat** [comment]
Great, thanks. BTW it seems as if the passing convention for bidsBackHandler has changed in v9.x. Is there any documentation available about this change?

**Comment by mkendall07** [comment]
Hmm might have been an inadvertent change. Mind posting what you are seeing as the delta?

**Comment by kitwestneat** [comment]
In 0.8.1 it is passing the bids in as { placement1 : bids: [bid1,bid2,...], placement2: bids: [...] }.

0.9.1 is sending them as [bid1,bid2,...]

The bigger problem in 0.9.1 is that older bid responses are sent along with new bid responses, and I'm unsure how to clear the old ones. I'm using pbjs.requestBids with adUnitCodes, and bidBackHandler set in the requestObj. 

Ah actually looking at the 0.9.1 code, it looks like passing adUnitCodes and adUnits is no longer supported, is that correct?

**Comment by mkendall07** [comment]
@kitwestneat 
Thanks for reporting. Those changes were not expected. We are working on addressing those points. Thanks

**Comment by protonate** [comment]
This is resolved in master with PR #371, closing.
