### ISSUE TITLE
Feature Request: Auction ID in bidsBackHandler arg 

### ISSUE THREAD

**Issue by TheMaskMaker** [prebid/Prebid.js#3669]
## Type of issue
Feature Request

## Description
bidsBackHandler does not return any means of obtaining the auctionID of a winnerless auction. This prevents the backhandler from acting on such auctions, as it does not know what they are or that they even exist.

Right now, the first arg of bidsBackHandler is of the form:
```
{
    adunitcode: bids[...],
    adunitcode: bids[...],
}
```
and if bids is empty, the adunitcode does not even show up.

Ideally, the properties of the returned data would be of the form: 
```
{
   adunitcode: {
       bids[...],
       auctionId: "3423a31a"
   },
   adunitcode: {
       bids[...],
       auctionId: "324324afff"
   },
}
```
And even if bids is empty, the auctionid will be present.

To avoid a breaking change, this new data structure could be a third arg for now, until the next relevant release.

**Comment by TheMaskMaker** [comment]
bump

**Comment by patmmccann** [comment]
What's the goal of this?
