### ISSUE TITLE
How to change prebid globalVarName in the newer versions?

### ISSUE THREAD

**Issue by belezebu** [prebid/Prebid.js#3678]
# Type of issue
Question

## Description
Hello! I've updated the prebid version to 2.7.0 and added the required changes to my webpack configuration file. Meanwhile I'm still using babel 6. After this pull request, https://github.com/prebid/Prebid.js/pull/3491/commits it is now possible to change the prebid global var name as a babel plugin option. How the object options available in Prebid.js/plugins/pbjsGlobals.js is populated and how can I change the prebid global var name?

Thanks for the help!

**Comment by snapwich** [comment]
an example of how to change the global var name is available in #3479

**Comment by belezebu** [comment]
Thanks for the help @snapwich!

**Comment by snapwich** [comment]
np
