### ISSUE TITLE
Object.assign - version 0.9

### ISSUE THREAD

**Issue by dbabaioff** [prebid/Prebid.js#368]
The prebid code is using from version 0.9 (https://github.com/prebid/Prebid.js/pull/349) Object.assign() - this ES6 function is not supported on IE and some mobile browsers.
To solve this issue I see two options: include a polyfill to make Object.assing work on older browsers or create a simple extend function and use it instead the Object.assign.

**Comment by mkendall07** [comment]
@dbabaioff 
Thanks for pointing this out. We will use https://babeljs.io/docs/plugins/transform-object-assign/ to polyfill.

**Comment by mkendall07** [comment]
https://github.com/prebid/Prebid.js/pull/369
