### ISSUE TITLE
Google Consent in GDPR ConsentManagement Module

### ISSUE THREAD

**Issue by ix-prebid-support** [prebid/Prebid.js#3684]
## Type of issue
Feature Request

## Description
Quantcast now offers the ability to accept user consent for Google in an effort to help better align CMPs to support Google Consented Providers Solution (CPS). Curious if this is something that's being looked at or if we should allocate some resource to this?

## Platform details
Prebid.js and prebid-server

## Reference material
Quantcast press release: https://www.quantcast.com/blog/quantcast-choice-supporting-google-products-with-new-consent-options/
Quantcast implementation documentation: https://help.quantcast.com/hc/en-us/articles/360019833693-Quantcast-Choice-support-for-Google-
Google policy: https://www.google.com/about/company/user-consent-policy.html

**Comment by bretg** [comment]
@ix-prebid-support - we're not looking at this. Please feel free to submit an "Intent-to-Implement" issue describing your proposal. Ideally it would be a modification to the existing GDPR module.

**Comment by ix-prebid-support** [comment]
Thank-you @bretg this makes perfect sense. Let me regroup internally and we will plan some next steps for this. Thanks!
