### ISSUE TITLE
Finteza adapter is an analytics adapter, not a bid one

### ISSUE THREAD

**Issue by finteza** [prebid/Prebid.js#3715]
## Type of issue
Bug

## Description

[Finteza adapter](https://github.com/prebid/Prebid.js/blob/master/modules/fintezaAnalyticsAdapter.md) is an analytics adapter, not a bid one.
Please fix it in the [releases](https://github.com/prebid/Prebid.js/releases/tag/2.7.0) and add the adapter to the [download page](http://prebid.org/download.html).

**Comment by mkendall07** [comment]
@finteza 
It looks like analytics adapters have to be added manually to the download page unfortunately.

Please open a pull request against this file: https://raw.githubusercontent.com/prebid/prebid.github.io/master/download.md

You can add it like so:

```
<div class="col-md-4">
  <div class="checkbox">
    <label>
      <input type="checkbox" analyticscode="code" class="analytics-check-box" /> Name
    </label>
  </div>
</div>
```
