### ISSUE TITLE
Listed on appnexusBidAdapter.js

### ISSUE THREAD

**Issue by viddyrizkiyansah** [prebid/Prebid.js#3721]
##Question

## Description
Please Advice, how the process if we want to registered our bidder (Bigmobile) on appnexus adapter like on sample below : https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L41 
( aliases: ['appnexusAst', 'brealtime', 'emxdigital', 'pagescience', 'defymedia', 'gourmetads', 'matomy', 'featureforward', 'oftmedia', 'districtm'],) 

so when publisher download appnexus adapter, in line 41, there's 'namebrealtime', 'emxdigital', 'pagescience and how we (bigmobile) registered bigmobile on appnexus adapter, is it possible ? 

Note : And we also want to confirmed that we want to included it on someone’s wrapper

Thank you

**Comment by jsnellbaker** [comment]
@viddyrizkiyansah I'm reaching out internally on this request.

**Comment by viddyrizkiyansah** [comment]
Hi @jsnellbaker Thank you for your kind respond....
