### ISSUE TITLE
prebid.org Homepage Demo Ad Always Returns a "House Ad"

### ISSUE THREAD

**Issue by ericperez** [prebid/Prebid.js#374]
I noticed that after refreshing the test/demo ad on the prebid.org homepage (and pbjs_demo.html) many times that I only ever get the "House Ad" returned. I expected it to return a 'real' ad at least some of the time but I have yet to see one.

**Here's the console output from the [pbjs_demo.html](http://prebid.org/examples/pbjs_demo.html) page in Chrome:**
pbjs_demo.html:225 Are all bids available? : false
pbjs_demo.html:227 Targeting params:
pbjs_demo.html:228 Object {}
pbjs_demo.html:230 Dumping all bid objects to console:
pbjs_demo.html:231 {"div-gpt-ad-1438287399331-0":{"bids":[]}}
_pbjs-event-logger.js:58 Uncaught TypeError: window.top.drawLog is not a function(anonymous function) @ pbjs-event-logger.js:58_

**When I click the 'Refresh this ad' on the homepage I get something like the following:**
Are all bids available? : false
VM84 pbjs_demo.html:227 Targeting params:
VM84 pbjs_demo.html:228 Object {}
VM84 pbjs_demo.html:230 Dumping all bid objects to console:
VM84 pbjs_demo.html:231 {"div-gpt-ad-1438287399331-0":{"bids":[]}}
pbjs-draw-log-diagram.js:80 {"loadPBJS":{"displayName":"Load Prebid.js","start":1,"end":2},"timer":{"displayName":"Adserver Timer","start":1,"end":402},"bids":[],"loadGPT":{"displayName":"Load GPT(DFP)","start":402,"end":460},"targeting":{"displayName":"Set Targeting","start":462,"end":462}}
pbjs-draw-log-diagram.js:103 [["Load Prebid.js",1,1,"Load Prebid.js\nDuration: 1ms\nStart: 1ms, End: 2ms","color:#ec971f;opacity:0.6",""],["Adserver Timer",1,401,"Adserver Timer\nDuration: 401ms\nStart: 1ms, End: 402ms","color:#ec971f;opacity:0.6",""],["Load GPT(DFP)",402,58,"Load GPT(DFP)\nDuration: 58ms\nStart: 402ms, End: 460ms","color:#ec971f;opacity:0.6",""],["Set Targeting",462,1,"Set Targeting\nDuration: 1ms\nStart: 462ms, End: 463ms","color:#ec971f;opacity:0.6",""]]

**Comment by mkendall07** [comment]
@ericperez 
This hasn't been my experience. It's possible that the bidder has blacklisted you for a ad response if it thinks it fraudulent. Otherwise you should see this: 
![image](https://cloud.githubusercontent.com/assets/1870166/15588036/022cb124-235a-11e6-8af8-d4a922c3bc24.png)
