### ISSUE TITLE
No ads displayed on integration page with GPT

### ISSUE THREAD

**Issue by piotr-yuxuan** [prebid/Prebid.js#3741]
## Type of issue
Question, possibly a bug

## Description
On upstream HEAD `http://localhost:9999/integrationExamples/gpt/hello_world.html` displays no ad.

## Steps to reproduce
On 8a5fb798ee45e2aed4cb5119757e392f94df146a (or any other recent upstream commit) execute:
```
npm install && gulp serve
```

## Test pages

- http://localhost:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true

I've set up an integration page without GPT for Emoteev adapter in https://github.com/prebid/Prebid.js/compare/master...Adikteev:hello-world-emoteev-standalone and I was able to get an ad displayed. This leads me think it might be an issue with GPT integration test setup.

### Expected results
Some ad is displayed

### Actual results
No ad is displayed

**Comment by jsnellbaker** [comment]
@piotr-yuxuan 

If you setup a localhost alias in your hosts file (eg `127.0.0.1 test.localhost`) and load the `hello_world` page with that alias, do you still see the issue?

The `appnexus` bidder has some logic to filter out requests when they're coming from just `localhost`.

**Comment by jsnellbaker** [comment]
After rereading your notes - I saw you mentioned you were testing the emoteev adapter.  If this was the case and you weren't using the appnexus bidder that's on the page by default, can you provide a jsfiddle or a copy of your prebid setup so I can review further?

**Comment by piotr-yuxuan** [comment]
As said, the test page is `hello_world.html`, the standard Prebid test page. I also made another test page to try an auction out of GPT.

On https://github.com/prebid/Prebid.js/compare/master...Adikteev:hello-world-emoteev-standalone:

#### hello_world.html

- http://test.localhost:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true triggers `onBidWon` and an ad is displayed.
- http://localhost:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true doesn't trigger `onBidWon` and no ad is displayed despite a valid bid response being received.

#### hello_world_emoteev.html

- http://test.localhost:9999/integrationExamples/gpt/hello_world_emoteev.html?pbjs_debug=true doesn't trigger `onBidWon` and no ad is displayed despite no meaningful change from `HEAD` and despite a valid bid response being received.
- http://localhost:9999/integrationExamples/gpt/hello_world_emoteev.html?pbjs_debug=true doesn't trigger `onBidWon` and no ad is displayed despite no meaningful change from `HEAD` and despite a valid bid response being received.

#### hello_world_emoteev_standalone.html

This is a page I added to understand better this behaviour

- http://test.localhost:9999/integrationExamples/gpt/hello_world_emoteev_standalone.html?pbjs_debug=true triggers `onBidWon` and an ad is displayed.
- http://localhost:9999/integrationExamples/gpt/hello_world_emoteev_standalone.html?pbjs_debug=true triggers `onBidWon` and an ad is displayed.

**Comment by piotr-yuxuan** [comment]
As said, the test page is `hello_world.html`, the standard Prebid test page. I also made another test page to try an auction out of GPT.

On https://github.com/prebid/Prebid.js/compare/master...Adikteev:hello-world-emoteev-standalone:

This page has been validated a few weeks ago and was displaying ads. No changes occured since then.

#### hello_world_emoteev_standalone.html

This is a page I added to understand better this behaviour

- ✅ http://test.localhost:9999/integrationExamples/gpt/hello_world_emoteev_standalone.html?pbjs_debug=true triggers `onBidWon` and an ad is displayed.
- ✅ http://localhost:9999/integrationExamples/gpt/hello_world_emoteev_standalone.html?pbjs_debug=true triggers `onBidWon` and an ad is displayed.

#### hello_world.html

- ✅ http://test.localhost:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true triggers `onBidWon` and an ad is displayed.
- 🚫 http://localhost:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true doesn't trigger `onBidWon` and no ad is displayed despite a valid bid response being received.

#### hello_world_emoteev.html

- 🚫 http://test.localhost:9999/integrationExamples/gpt/hello_world_emoteev.html?pbjs_debug=true doesn't trigger `onBidWon` and no ad is displayed despite no meaningful change from `HEAD` and despite a valid bid response being received.
- 🚫 http://localhost:9999/integrationExamples/gpt/hello_world_emoteev.html?pbjs_debug=true doesn't trigger `onBidWon` and no ad is displayed despite no meaningful change from `HEAD` and despite a valid bid response being received.

**Comment by jsnellbaker** [comment]
@piotr-yuxuan Thanks for the updated details.  

In regards to the `hello_world` page result; if that is using the default `appnexus` bidder info, then it is expected that the `localhost:9999` host won't return a bid.  You would have to use an alias for that to work due to the filtering that's in place on the appnexus adserver when it detects `localhost` in the referrer.

In regards to the `hello_world_emoteev` page, I tried to set it up with the size changes.  I did not see a bid return from the adserver.  Instead I saw the following error return:
`[{"error":"No matching placement found for ad-space id 5084"}]`

This caused the bid response to be rejected by Prebid since the adapter just passed the server's result (ie this error). 

<img width="1792" alt="Screen Shot 2019-04-11 at 2 07 35 PM" src="https://user-images.githubusercontent.com/31102355/55980771-314a9580-5c63-11e9-823b-8a167c26589e.png">

This seems like a potential setup issue on the adserver end.  Could you check to ensure that side is setup properly?  Maybe some just expired or was deactivated by accident.

**Comment by piotr-yuxuan** [comment]
Looks like you didn't tried it atop this diff: https://github.com/prebid/Prebid.js/compare/master...Adikteev:hello-world-emoteev-standalone, the second commit addresses this issue 😉

**Comment by piotr-yuxuan** [comment]
Well, GPT ad unit doesn't know about some custom size (720 x 200). We changed it and now it's resolved.
