### ISSUE TITLE
Object.assign & Array.find are not supported in IE/oder versions of Safari

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#375]
Recent refactoring introduced into the code new language features, that are not supported in older browsers. Namely Object.assign & Array.find. https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

Still documentation claims that prebid supports IE9+

**Comment by mkendall07** [comment]
@dmitriyshashkin 
We are addressing those issues in a new release. https://github.com/prebid/Prebid.js/pull/373 and https://github.com/prebid/Prebid.js/pull/369 are the related fixes.

**Comment by mkendall07** [comment]
fixes for IE should be in master now. Please reopen if you still see issues.
