### ISSUE TITLE
Sovrn adapter requires undocumented parameter

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#376]
It seems to me that #349 has broken the sovrn adapter:

    var bidObj = pbjs._bidsRequested.map(bidSet => bidSet.bids.filter(bid => bid.params && bid.params.impId === id));

I suppose that bid.params.impId is the parameter I should pass with adUnits. Yet it is not documented here http://prebid.org/dev-docs/bidders.html#sovrn and I have no idea where I can get it's value.

So after I updated to 0.9.1 I stopped seeing sovrn bids. I was able to resolve the issue by bringing back pbCallbackMap.

**Comment by mkendall07** [comment]
@protonate 
Can you review this?

**Comment by cliffliang** [comment]
It should be a lowercase i in impId.

`var bidObj = pbjs._bidsRequested.map(bidSet => bidSet.bids.filter(bid => bid.params && bid.params.impid === id));`

**Comment by protonate** [comment]
Thanks for reporting the issue @dmitriyshashkin and for the fix @cliffliang, we'll include it in a pending bug fix release v0.9.2.

**Comment by ojotoxy** [comment]
I do not see that the lowercase 'impid' is available in the params object. Furthermore I don't see how applying map to the bidsRequested array can possibly return the correct object.

It seems like this sort of operation would be required to find the right bid object:

pbjs._bidsRequested.filter(function(bidder){ return bidder.bidderCode === 'sovrn' })[0].bids.filter(function(bid){ return bid.impid === '1234' })[0]


Of course impid is apparently not available and it should do better error checking...

**Comment by protonate** [comment]
PR #379 attempts a fix by setting `imp.id` to the bidId of the bid request in `_requestBids`.  Then the bid can be located in `bidsRequested` array in the `sovrnResponse` callback, assuming that `imp.id` is returned as the `sovrnBid.impid`. I'm not getting seatbids back so cannot confirm this at the moment.

**Comment by mkendall07** [comment]
this is resolved in master.
