### ISSUE TITLE
my git account can't git push my branch

### ISSUE THREAD

**Issue by wqi1972** [prebid/Prebid.js#3773]
## Description

I can use my git account wqi1972 pull source file at https://github.com/prebid/Prebid.js, but when I push my branch, it fails.

![unnamed](https://user-images.githubusercontent.com/4923189/56517491-e4cc4900-64f1-11e9-942a-3031a6994bdb.png)

**Comment by mkendall07** [comment]
@wqi1972 
please fork the repo first before attempting to push a branch. Thanks.
