### ISSUE TITLE
Prebid implementation of IAB Native 1.1

### ISSUE THREAD

**Issue by torbenbrodt** [prebid/Prebid.js#378]
I wonder if you plan any dedicated support for IAB Native 1.1 / OpenRTB 2.4.
In my interpretation the adapters currently accept "html" as placementCode
`bidmanager.addBidResponse(placementCode, bid);`
 
But instead it could accept a IAB Native object similar to
```
"native": {
    "link": {
        "url": "http://i.am.a/URL"
    },
    "assets": [{
        "id": 123,
        "required": 1,
        "title": {
            "text": "Learn about this awesome thing"
        }
    }, {
        "id": 124,
        "required": 1,
        "img": {
            "url": "http://www.myads.com/thumbnail1.png"
        }
    }, {
        "id": 128,
        "required": 1,
        "img": {
            "url": "http://www.myads.com/largethumb1.png"
        }
    }, {
        "id": 126,
        "required": 1,
        "data": {
            "value": "My Brand"
        }
    }, {
        "id": 127,
        "required": 1,
        "data": {
            "value": "Learn all about this awesome story of someone using myproduct."
        }
    }]
}
```
 
Pro
 - This allows to connect Native Ads more easily (plista, outbrain, Taboola & Co)
 - This allows to combine different vendors from different sources
 - Publisher could have a common layout across the different Native Ads vendors
 
Con
 - huge implementation efforts / could not find a javascript wrapper for IAB Native we can leverage
 
The current specs can be found at http://www.iab.com/wp-content/uploads/2016/01/OpenRTB-Native-Ads-Specification-Draft.pdf
 
As outlined this has pros and cons. What do you think about it?

**Comment by mkendall07** [comment]
@torbenbrodt 

We have not had the request to support this yet. Is there any bidders that currently that it?

**Comment by protonate** [comment]
Closing as inactive, please reopen if additional info.
