### ISSUE TITLE
UserId module OpenrRTB user.ext.eids

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#3790]
## Type of issue
Suggestion: If UserId module passes information of supported partners in ORTB user.ext.eids format then it will be easier for ORTB supporting bidders like PubMatic to support all userId partners without making changes for every partner. 

## Description
ORTB.user.ext.eids has a provison to pass external user ids in ORTB, which can be easily supported. f UserId module passes information of supported userId partners in ORTB user.ext.eids format then it will be easier for ORTB supporting bidders like PubMatic to support all userId partners without making changes for every userId partner. Then an ORTB supporting bidder will simply copy the userId object into payload.user.ext.eids, this will avoid the repeating efforts for each provider getting added in userId object like TTD, DigiTrust and new ones coming.

Also rather than duplicating the userId object in every bid object can we send userId object along with validBids separately?

**Comment by bretg** [comment]
@pm-harshad-mane - the current design places all IDs under user.ext.tpid (which stands for third party ID). This seems sufficient for you're asking -- just copy that object which could contain an array of IDs.

```
{
  "user": {
    "buyeruid": "...",
    "ext": {
         "tpid": [ 
          { 
            "source": "tdid",
           "uid": "11111"
        }
      ]
    }
  }
}
```
> Also rather than duplicating the userId object in every bid object

Not understanding this -- the user object is outside the imp object.

**Comment by bretg** [comment]
I believe we addressed this with https://github.com/prebid/Prebid.js/issues/3900 and https://github.com/prebid/Prebid.js/pull/3935

**Comment by pm-harshad-mane** [comment]
We can ask User Id submodules to decide the format they want to use, if adapter wants to change the format then the adapter can make changes in adapter code.
Now, adapters like PubMatic, Rubicon, Pulsepoint need to create the OpenrRTB user.ext.eids object and need to make code changes to support each new userId submodule
