### ISSUE TITLE
Dependencies disappear

### ISSUE THREAD

**Issue by tandrewnichols** [prebid/Prebid.js#3795]
## Type of issue
Question, maybe bug

## Description
Is there something different about your setup, as far as publishing to npm goes? If I install this module as a dependency, none of it's dev dependencies are installed (even though `npm config get production` is `false`). This doesn't happen with other packages I install. I can fix this by `npm explore prebid.js -- npm install`, but _then_, any and every time I install _another_ node module, the dev dependencies for this module get blown away (npm trying to be helpful I assume). Again, this doesn't happen with other packages. Why does this matter? Because I can't use `gulp` to build a custom prebid script if gulp isn't there. I've tried researching this . . . it's not impossible that I'm doing something weird, but like I said, this doesn't happen with any other module. I've tried this with npm versions 5.6.0, 6.2.0, and 6.5.0.

## Steps to reproduce

```
# Part 1
mkdir foo && cd foo
npm init -y
npm install prebid.js
ls node_modules/gulp # -> No such file or directory

# Part 2
npm explore prebid.js -- npm install
ls node_modules/prebid.js/node_modules/gulp # -> exists
npm install express
ls node_modules/prebid.js/node_modules/gulp # -> No such file or directory
ls node_modules/gulp # -> No such file or directory
```

### Expected results
Gulp and other dev dependencies should be installed so that `gulp build` works.

### Actual results
It's not and `gulp build` fails. Even if I install `gulp` globally, then I get errors on _other_ modules, like `gulp-util`.

## Platform details
Prebid.js: 2.12.0 and 2.11.0
OS: MacOS 10.13.6
node: 9.11.2, 10.9.0
npm: 5.6.0, 6.2.0, 6.5.0 (and probably more)

**Comment by mkendall07** [comment]
AFAIK there isn't anything special we do for publish (it's basically `npm publish`). Perhaps the fix is to add `gulp` into `dependencies` and out of `DevDependencies`

@snapwich do you have any thoughts on this?

**Comment by tandrewnichols** [comment]
I wondered if having `node_modules` in .npmignore could cause. Like, it doesn't _seem_ like it should, but I can't see anything else unique about this repo.

**Comment by snapwich** [comment]
It sounds like things are working as they should.

Prebid.js isn't a normal npm package, as you've probably noticed, in that it requires a parameterized build process to create a useable package (specifying only prebid modules you intend to use).  You probably shouldn't be listing Prebid.js as a direct npm dependency _unless_ you are using it as one: https://github.com/prebid/Prebid.js#usage-as-a-npm-dependency.  Doing so requires you to bundle Prebid.js yourself (using webpack or such) and explicitly importing the portions of Prebid.js you intend to use, in which case devDependencies should _not_ be installed as they are _only_ intended for building and/or testing Prebid.js directly.

Other packages you reference that are installing gulp are either listing gulp as a dependency (which could be correct depending on their use case, but is not appropriate for ours), or have a prepare script which causes devDependencies to be installed _for their own build process_.  Expecting a local gulp to be present as a devDependency of a dependency is basically treating that gulp as implicit dependency, which is a bad thing and you shouldn't be reliant on it.

If you intend to build Prebid.js manually using gulp and want to include Prebid.js as an explicit dependency of your project I'd suggest including Prebid.js as a git subtree or git submodule and then creating a build script within your project that installs Prebid.js' dependencies (using `npm install`), runs the gulp build, and then copies the build files to the appropriate locations. You also might be interested in the [Prebid.js Packager](https://github.com/prebid/Prebid.js-packager) which does basically that in bulk.

**Comment by tandrewnichols** [comment]
Ok, let me clarify. The last case is the one I'm interested in. We have a custom build script to generate our prebid script using gulp. I'm personally not interested in a submodule. In my experience that doesn't do anything except cause pain. I've never tried a subtree. Specific implementation isn't the issue though. Something definitely _isn't_ working "normally" (even if it's "as it should" from prebid's perspective) because by default when I install a module, the dev dependencies are installed for that module (this is configurable of course, but I'm not doing anything to tell npm to only install production deps). Like if I install jasmine as _either_ a dev or production dependency, all it's dependencies (and transient dependencies) are installed. When I install _this_ module, that doesn't happen. Everything you said above makes sense, except that gulp, gulp-utils, etc. _are_ listed as dev dependencies, so when I install this module (without setting the npm production flag), those dependencies should be there and for some reason they're not.

**Comment by tandrewnichols** [comment]
I definitely wouldn't advocate for moving gulp to `dependencies` as it's not a production dependency.

**Comment by snapwich** [comment]
Can you try installing `jasmine` in an empty directory?  e.g.
```
mkdir foo && cd foo
npm init -y
npm install jasmine
```

If I do that then `grunt` is not installed in either `node_modules` or `node_modules/jasmine/node_modules` even though it is listed as a devDependency of `jasmine`.

If I had to guess you're either seeing implicit dependencies that have been hoisted by other dependencies or there's something different about your package's configuration.

**Comment by tandrewnichols** [comment]
Ok, I stand corrected. You're correct, grunt is not there. Maybe older versions of npm installed dev dependencies by default. Or maybe I'm crazy.

**Comment by snapwich** [comment]
Cool, let me know if you have anymore issues related to creating a custom build script for Prebid.js, I might be able to provide advice as I have undertaken similar tasks before, including creating the Prebid.js packager (I can answer any questions you might have there as well).
