### ISSUE TITLE
User ID Trade Desk issue

### ISSUE THREAD

**Issue by lukacmi** [prebid/Prebid.js#3796]
## Type of issue
Bug

## Description
Trade Desk User ID integration only works on HTTP sites.

`Mixed Content: The page at was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://match.adsrvr.org/track/rid?ttd_pid=xxxxx&fmt=json'. This request has been blocked; the content must be served over HTTPS.
`
## Steps to reproduce
https://github.com/prebid/Prebid.js/blob/master/modules/userId.js#L87

### Expected results
It should be protocol agnostic.
https://match.adsrvr.org/track/rid?ttd_pid=${submoduleConfigParams.partner}&fmt=json

### Actual results
http://match.adsrvr.org/track/rid?ttd_pid=${submoduleConfigParams.partner}&fmt=json

## Platform details
All HTTPS sites

## Other information
FYI @idettman

**Comment by khatibda** [comment]
yeah, we just ran into this (Granite Media).  for now, pubs who have this issue can use the url parameter and it will supersede the partner param bug...

`    pbjs.setConfig({
        usersync: {
            userIds: [{
                name: "unifiedId",
                params: {
                    //partner: "{yourId}",
                    url: "//match.adsrvr.org/track/rid?ttd_pid={yourId}&fmt=json",
                },
                storage: {
                    type: "cookie",
                    name: "pbjs-unifiedid",      
                    expires: 60             
                }
            }],
            syncDelay: 1000  
        },
    });`

**Comment by bretg** [comment]
Good find. Prebid.org doc updated http://prebid.org/dev-docs/modules/userId.html#examples

**Comment by bretg** [comment]
Confirmed that this issue is resolved in PR #3831
