### ISSUE TITLE
Misleading docs for downloading script

### ISSUE THREAD

**Issue by JuanCaicedo** [prebid/Prebid.js#38]
From reading the [docs](http://prebid.org/publisher-api.html#load-the-prebidjs-library), it seems you would be able to add that code into your page to load this library. However, https://cdn.site.com/prebid.js isn't a real url, so I guess that this code is more to suggest that if you have a CDN you're using, this is the pattern you could follow. I think this could be made much more explicit, I was definitely confused.

Also, is there a better way to load the most up to date version? Right now it seems like you have to manually download from [here](http://prebid.org/getting-started.html#download) and host it yourself.

**Comment by ialex** [comment]
that's not a valid URL so you can download the library there or you can clone the repo and run `gulp build` to get the latest version it will be placed in Prebid.js/dist/build/

**Comment by mkendall07** [comment]
Hi @JuanCaicedo, 
Thanks for the note. I've clarified in the readme about the need to server `prebid.js` locally or on a CDN.
