### ISSUE TITLE
Use PrebidJs in nodeJS

### ISSUE THREAD

**Issue by montu1996** [prebid/Prebid.js#3810]
## Use PrebidJS as server side

Hello,
i want to use prebid.js lib to get ad data and store inside the database. I haven't found anything in doc to get ad and store inside the database. can you guys please help me to acheive this.

**Comment by mkendall07** [comment]
@montu1996 
Prebid.js is only built to run in the browser and does not target nodejs as a run time. I don't believe this will be successful.
