### ISSUE TITLE
investigate auction end event not emitting without specifying timeout

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#3813]
## Type of issue
If you requestBids without specifying a timeout and the default 3 second timeout is used, no auction end event is emitted.

**Comment by khatibda** [comment]
hi - publisher here.  to follow up, we use:

pbjs.requestBids({
  adUnitCodes,
});

we assumed it would default to a timeout of 3000ms.  most things behave normally on our page as a result of this.  however we just discovered that auctionEnd never fires.  this is now a new problem because UserID usersync callback seems to be based on this event firing.

if we explicitly call a timeout, then everything fires and works as expected. 
pbjs.requestBids({
  adUnitCodes,
  timeout: 3000,
});

lemme know if you need additional info

**Comment by jsnellbaker** [comment]
Hi @khatibda,

Do you have a URL available with the setup (and issue) you mentioned above so I can review further?  Thanks.

**Comment by khatibda** [comment]
@jsnellbaker.  i don't have a live url at present because we resolved why including the timeout property explicitly.  are you able to reproduce locally?  if not, i can look into pushing a test page with the bug still present.

**Comment by jsnellbaker** [comment]
I was trying some ways to artificially induce the scenario, but I was seeing the auctionEnd event emit successfully during those attempts.  If you can put something together that reliably reproduces the behavior, I would greatly appreciate it.

**Comment by khatibda** [comment]
@jsnellbaker here's your test page:
https://www.workandmoney.com/s/best-emerging-college-majors-394f2c2138404506?dbg_tests=pbjsTimeoutOff-enabled&pbjs_debug=true

notice how the auctionEnd doesn't get logged. 

if you toggle into the control bucket (with the timeout property explicitly included in requestBids), you should see auctionEnd get logged.

https://www.workandmoney.com/s/best-emerging-college-majors-394f2c2138404506?dbg_tests=pbjsTimeoutOff-control&pbjs_debug=true

**Comment by jsnellbaker** [comment]
@khatibda Thanks for providing the test pages.  I believe I found the cause for the auctionEnd event to not fire. 

Basically, the event is hidden by a flag that's only active when you pass a function in the `bidsBackHandler` in the `pbjs.requestBids` function.  

In the case of your first page, it's only passing the `adUnitCodes` property on the `requestBids` call.  Whereas your second page, is passing `adUnitCodes`, `timeout`, and `bidsBackHandler`.

I tried to look through the code in your build file (`story.bbfaf41df20c6a33695c.js`) while attempting to debug the prebid code on your test page.  Is there some extra logic you put together to not require the `bidsBackHandler` and still allow the prebid data pass to your ad server?  Or is the missing property on the test page not expected?

**Comment by khatibda** [comment]
you are absolutely right, and we should have micro-tested this double difference.  in my local environment, if we include bidsBackHandler and not the timeout property, it works (auctionEnd fires).  if we include only the timeout and not the bidsBackHandler, it doesn't work.  so this confirms your theory.

that said...does this mean any pub who doesn't include bidsBackHandler isn't firing auctionEnd?  isn't that most pubs?  seems like a more specific problem, but also a bigger one!

**Comment by jsnellbaker** [comment]
I'm not sure that it's most pubs.  That said, I'll take a look at the logic and see if it can be handled better.

**Comment by khatibda** [comment]
test page is coming down, this feels like it was reviewed/addressed.
