### ISSUE TITLE
All bidders should be called over HTTPS

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#3815]
## Type of issue
Feature

## Description
Post recent announcement about Chrome browser, forcing all third-party cookies to be set with the secure flag, we should call all the bidders with HTTPS protocol only otherwise bidder servers will not get the respective server domain tracking cookies.

Chrome has not made it clear that since when this flag will be mandatory, but they mentioned that first, they are making SameSite flag mandatory with Chrome 76 scheduled to release on 30th July and later they will make Secure flag mandatory for third-party-cookies.

Prebid should be ready for this change, so we must call all bidders over HTTPS and all user-sync related calls should also be on HTTPS. 

Moreover, once we start calling bidders with HTTPS, we should also inform all server-side components (with specific flags) that creative/content should be served with HTTPS only so that there will not be any case of mixed-content (secure call serving non-secure content).

**Comment by bretg** [comment]
So any suggestions for what this would actually entail? Prebid.org cannot make assumptions or modify the endpoints for 200+ adapters, nor control what usersync pixels they return.

The only thing that seems practical is to attempt to communicate a "best practice" to the adapter community through the prebid.org website.
