### ISSUE TITLE
Request for Bid "Streaming"

### ISSUE THREAD

**Issue by woggle23** [prebid/Prebid.js#3823]
## Type of issue
Feature

## Description
At present Prebid doesn't provide a means to obtain the _current_ highest bidder at anytime during an auction, it's only available once the auction has completed. However, in some situations we don't control the auction timeout, as such, (previously) we weren't able to return any bids to the client. To resolve this, we updated our approach to listen to each bid (via `onBidResponse`), and forward the higher bids to our client, that way whenever their timeout occurs they have the highest bid response at that moment.

This works well enough for the simple case of sorting bids by cpm. However, we'd like to use Prebid's `bid caching`. The simple solution for us would be to call `getAdserverTargeting` when each bid response is received. The problem here is the same as the above, the adserverTargeting is only available once the auction has completed. Furthermore, the new bid isn't added to `_bidsReceived` until after the `onBidResponse` event has been fired.

Happy to implement a solution, interested in feedback on the idea.

**Comment by bretg** [comment]
@mkendall07 - is this true?
> adserverTargeting is only available once the auction has completed

I thought that targeting was available at any time. i.e. if the page wanted to close the auction early, it could call `setTargetingForGPTAsync` and get whatever bid were back.

**Comment by bretg** [comment]
Found this code snippet that makes me agree this does seem to be an issue:
```
  auctionManager.getBidsReceived = function() {
    return _auctions.map((auction) => {
      if (auction.getAuctionStatus() === AUCTION_COMPLETED) {
        return auction.getBidsReceived();
      }
    }).reduce(flatten, [])
      .filter(bid => bid);
  };
```
So I agree there should be an option to take whatever bids are back when the page calls `setTargeting`.

**Comment by gglas** [comment]
@woggle23 @patmmccann and the community discussed today, would you be interested in reengaging?

**Comment by patmmccann** [comment]
hi @woggle23 

Getting current highest bid appears to be a very useful feature. One use case is setting a threshold to call the ad server or a render function before the timeout. Another use case is quickly ending auctions with current status on lazy units that are about to come into the viewpoint or units on an exit intent pop up. We'd love your contribution, and are curious if you're still willing to commit?

**Comment by woggle23** [comment]
Hi @gglas / @patmmccann 

Yes, happy to help. My current requirement is simply to be able to retrieve the highest bid for a given adUnit code regardless of whether or not is in progress. So, for my purpose, I just applied [this](https://github.com/prebid/Prebid.js/pull/6342) to my fork of Prebid.js. 

But I appreciate this may not be what you're after, so happy to take another approach.

**Comment by patmmccann** [comment]
This seems really helpful, did you leave your pr in draft on purpose? People tend not to look at pr's until they come out of draft

**Comment by woggle23** [comment]
I left if in draft as I didn't really expect it to be the approach taken. Although I didn't realise it wouldn't really be looked at in that state - cheers for the heads up; updated for review.

**Comment by patmmccann** [comment]
It is looking like your proposal is quite well received and overdue :) Thank you very much for the contribution. To integrate it in I think we'll need an example on how to use it. Do you use it conjunction with https://developers.google.com/publisher-tag/samples/lazy-loading by any chance, ending the auction just before the fetch height?
