### ISSUE TITLE
Can't download the wrapper

### ISSUE THREAD

**Issue by joycetsaiLTN** [prebid/Prebid.js#3847]
## Type of issue
Ran into an issue when downloading the wrapper file.

## Description
Ran into an issue when downloading the wrapper file.

## Scrennshoot
https://drive.google.com/file/d/1MxtD8guw2l_GFir6GNNAUwlhpKAzRuTz/view?usp=sharing

**Comment by chratcliff** [comment]
Same for me, for a couple days now. It fails to generate the list of versions.

**Comment by durangatan** [comment]
Likewise!

**Comment by adopsgal** [comment]
Me as well, I've been trying for a few days.

**Comment by adopsgal** [comment]
Still seeing the following error in console: 

Access to XMLHttpRequest at 'http://js-download.prebid.org/download' from origin 'http://prebid.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
