### ISSUE TITLE
What is the difference between `pbAg` and `cpm`?

### ISSUE THREAD

**Issue by joyofdata** [prebid/Prebid.js#385]
Can somebody tell me what is the difference between `pbAg` and `cpm` in the object informing about a returned bid?

![image](https://cloud.githubusercontent.com/assets/3748975/15716166/82281938-2821-11e6-9e26-c8a9990b9dd3.png)

**Comment by ialex** [comment]
It is the Price Bucket configured for your setup that means you are using the auto Price Bucket that will pbAg is the value that will be send in the targeting to DFP, and CPM is the original value returned by the ad network. You can read more about price buckets in the link below

http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.setPriceGranularity
