### ISSUE TITLE
30% Revenue Drop when upgrading from .34 to 2.16

### ISSUE THREAD

**Issue by millieone** [prebid/Prebid.js#3859]
## Description
We finally decided to upgrade. We were hesitant to upgrade above .34 as we had heard of revenue drops from people upgrading to 1.X. Upgraded from .34.16 to 2.16 yesterday on part of the site. Only one day of data but a 30% drop in revenue.  Should this correct itself over time?

Would like tips on what to do to optimize. We are getting bids from all our partners. 8 bidders. Doing some sizemapping but nothing else unusual. No GDPR.

Our new timeout:
var PREBID_TIMEOUT = 1000;
  | var FAILSAFE_TIMEOUT = 3000;

Previous:
PREBID_TIMEOUT=900;var MAX_RETRIES=15;

There was a previous post on here where people upgrading to 1.X suggested adding this:
pbjs.setConfig({ userSync: { syncsPerBidder: 50 }, maxRequestsPerOrigin: 1, timeoutBuffer: 400 });

Should we do something like that?  Do we have too many bidders for 2.X?  Not to sound like a jerk, but what's the point of upgrading if revenue doesn't go up?

Here's a test page: https://www.letsrun.com/archive/2019/05/24/?testpb=yes

## Test page

Here's  link to what we have up: https://www.letsrun.com/archive/2019/05/24/?testpb=yes

**Comment by headerbidding** [comment]
My Chrome HeaderbidExpert plugin says:

Under Monetized
Problem: Rubicon, Openx, Pubmatic, Criteo had less time to bid, because they loaded much later than the other bidders.
How to fix: Load all bidders together.
Problem: AppNexus, Rubicon, Pubmatic, Criteo's bids did not count, because they responded later than the ad server request was sent out.
How to fix: Load these bidders earlier, or experiment with extending the timeout without causing impression loss.

![image](https://user-images.githubusercontent.com/16692770/58658828-70a27380-82ef-11e9-8cdb-6781b75afacf.png)

**Comment by millieone** [comment]
Thanks for the info @headerbidding   The headerbidding expert tool is picking up partners that are from the waterfall. You said, "Rubicon, Openx, Pubmatic, Criteo" all were late bidding but none of them are in the HB setup.   

I may try adjusting some of the setting that some people did when upgrade to 1.X


pbjs.setConfig({ userSync: { syncsPerBidder: 50 }, maxRequestsPerOrigin: 1, timeoutBuffer: 400 });

**Comment by headerbidding** [comment]
I think the defaults currently are:  
syncsPerBidder: 5, syncDelay: 3000, maxRequestsPerOrigin: 4, enableSendAllBids: true, timeoutBuffer: 400
(I am not an expert. Let me know if you come across anything.)

**Comment by millieone** [comment]
@headerbidding as for letting them drop 50 cookies, we have not implemented that. But there was this thread:
https://github.com/prebid/Prebid.js/issues/2648#issuecomment-401735019
which talked about a revenue drop from going to 0.x to 1.X  And that was a suggested solution. Also it is discussed here: https://www.reddit.com/r/adops/comments/9tcgwm/upgrading_to_prebid_1x_leads_to_20_drop_in/

Perhaps this issue got sorted out? 

With a week+ of data now I don't think revenue is down 30%, but we're still looking for ways to optimize and we don't see an uplift.

**Comment by headerbidding** [comment]
Perhaps someone more experienced here can help?
By the way, why do you have prebid header bidding AND a waterfall?

**Comment by donthexyz** [comment]
We had similar issues of loss in revenue when upgrading from Prebid 0.34. The only reason we did upgrade is that Amazon AUM more than made up the loss from Prebid so our overall Revenue even increased slightly.

See here: https://www.reddit.com/r/adops/comments/a42ki1/prebid_1x_upgrade_ab_test_with_aum_amazon_prebid/

We did initially have `maxRequestsPerOrigin : 1` but after A/B testing saw no performance difference compared to the default of 4.

**Comment by headerbidding** [comment]
@donthexyz: Have you done the "AUM Parallel Integration alongside Prebid" exactly per the Amazon suggested script?

**Comment by donthexyz** [comment]
Amazon actually did it for me and yes it was the parallel integration. I have not tweaked it.

**Comment by millieone** [comment]
@donthexyz  did you do anything with the  { syncsPerBidder: 50 }, or timeoutbuffer? or just leave at defaults?

**Comment by donthexyz** [comment]
we left it at defaults

**Comment by bretg** [comment]
Re-read last year's impression thread. It boiled down to:

1) everyone's a little different -- folks will need to try various parameter settings, preferably with A/B testing
2) `maxRequestsPerOrigin:1` seemed to help some
3) raising the `timeoutBuffer` helped others. The default in recent versions is 400ms. (This essentially gives bidders more time, so makes sense that bid rates would go up)
4) make sure you're not setting the Prebid Timeout and the Failsafe timeout to the same value. (see http://prebid.org/dev-docs/getting-started.html)
5) geographic location matters

FWIW - I think `syncsPerBidder` is a red herring.

**Comment by bretg** [comment]
@millieone - any update on your experience here?

**Comment by bretg** [comment]
@millieone - going to let stalebot close this one out if we don't get an update. Or anyone else having issues after upgrade and tuning.
