### ISSUE TITLE
Will I eventually be able to use the download tool for prebid 0.9.2 instead of 0.8.1?

### ISSUE THREAD

**Issue by chaqu170** [prebid/Prebid.js#387]
Will I eventually be able to use the download tool for prebid 0.9.2 instead of 0.8.1? In the mean time, I'm going to figure out how to set up nodejs and gulp, but I thought I should ask anyway.

**Comment by mkendall07** [comment]
Yes we will update sometime next week after giving it some "burn in" time.

**Comment by mkendall07** [comment]
@protonate 
Can you upload the 0.9.2 build directory to the release page so people can download it there without building?

**Comment by protonate** [comment]
@chaqu170 Prebid v0.9.2 is now available via the download page on prebid.org:
prebid.org/download.html
