### ISSUE TITLE
Proposal: set cookie domain in pubcid / userid on main domain, not subdomain

### ISSUE THREAD

**Issue by adxcgcom** [prebid/Prebid.js#3873]
## Type of issue
Feature request

## Description
It is useful to have one pubCommonId for domain, not for each subsite. 

As a possibile solution: in pbjs.setConfig publisher should set storage domain for cookie.

## Steps to reproduce
In fresh browser open Prebid auction with pubCommonId / unifiedId module enabled.

After checking LOCAL set cookies in Chrome: Application->cookies we see that both modules  set cookie domain to 

subdomain.domain.com

it would be better to have this set at 
domain.com  (without subdomain), the same as other cookies.

### Expected results
Set cookie domain to 
domain.com

### Actual results

Cookie domain is set to
subdomain.domain.com

**Comment by mkendall07** [comment]
@idettman 
can you take a look at this?

**Comment by idettman** [comment]
The file `modules/userId/index.js` contains the setCookie call used by all the submodules, so the main domain could be passed as the `domain` argument for `setCookie(key, value, expires, sameSite, domain, done)`. I'll create a PR for this fix

**Comment by idettman** [comment]
PR will be opened shortly

**Comment by josepowera** [comment]
[PR-7773](https://github.com/prebid/Prebid.js/pull/7773)
