### ISSUE TITLE
Out of date user id module support documentation

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#3882]
## Description
Multiple pull requests for adapters supporting the user id module have not updated the documentation

## Test page
http://prebid.org/dev-docs/modules/userId.html

### Expected results
Index, sharethrough, pubmatic list which id's are supported

### Actual results

Bidder | IDs Supported
-- | --
beachfront | unifiedId/tradedesk
conversant | pubCommon
livewrapped | pubcommon
openx | pubcommon
rubicon | unifiedId/tradedesk
sonobi | pubCommon, unifiedId/tradedesk

## Other information
https://github.com/prebid/Prebid.js/pull/3744
https://github.com/prebid/Prebid.js/pull/3819
https://github.com/prebid/Prebid.js/pull/3834

**Comment by bretg** [comment]
Looking at PR #3744, IX doesn't actually support the UserID module.

The other two added to the docs site in https://github.com/prebid/prebid.github.io/pull/1339 and are now showing on http://prebid.org/dev-docs/modules/userId.html#adapters-supporting-the-user-id-module
