### ISSUE TITLE
User id module remove storage requirements

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#3883]
## Type of issue
Feature request

## Description
1. Remove storage requirements from User id module. I have an id system which cannot store user id in local storage or cookie for more than 1 hour. It needs to hit the endpoint once every hour and get the latest user id.

**Comment by pm-harshad-mane** [comment]
Hello @jaiminpanchal27 ,
if the end-point needs to be hit every hour and not on every impression then the id-provider will need to store the id for at least an hour, then I think we need to store it somewhere (cookie, local-storage).
Am I missing something?

**Comment by jaiminpanchal27** [comment]
Merged in #3930
