### ISSUE TITLE
SendAllBids Bid Cap

### ISSUE THREAD

**Issue by r-schweitzer** [prebid/Prebid.js#3888]
## Type of issue
Feature

## Description 
This the same issue as described in #3800 

In certain scenarios, Prebid may generate a large number of targeting keys after an auction has completed. An issue could arise when Prebid needs to send all these keys (and their values which can vary in length) to GAM or any other ad server, as this data is typically sent over as query-data in the ad server's request URL and some systems may have limits to the query-data's size.

In such scenarios, commonly what happens is that the query-data is truncated at the designated point and the ad server processes what keys came through and acts accordingly with that data-set. In Prebid's case, this can lead to issues with the Prebid ad being properly rendered (such as if some data points for a native bid were missing) or delivery issues if the Prebid line-item/campaign was targeting off of certain keys that were dropped.

### Proposed Solution
Prebid.js will offer a new config setting that will cap the number of bids made per ad unit when sendAllBids is enabled. This limiter setting will take in a number which will represents the bidCap (defaulted to zero). When bids are capped at zero sendAllBids will function normally. When the bidCap is set to 2 for example, only the targeting for the top 2 bids will be sent to the ad server for each adunit.

An example of the setting:

`pbjs.setConfig({
    bidCap: 2
  })`

**Comment by pm-harshad-mane** [comment]
Hello @r-schweitzer ,
Can you please share a test-page where with this scenario?

@mkendall07 @jsnellbaker I think the issue is due to large values stored in native assets key-value pairs as other key-value pairs do not have large values. Can we avoid sending native assets in key-value pairs and share an API which will return requested asset from a specified creative(using bid-id)? this will help us avoid sending native-assets related key-value pairs.

**Comment by r-schweitzer** [comment]
@pm-harshad-mane I believe in CafeMedia's case it has more to do with the number of bidders we use and number of ad slots we can have on a page when sendAllBids is enabled with SRA. I do not have a test page where this is occurring currently but I ran a test locally on the following url:

https://www.comicsands.com/chick-fil-a-rodney-bullard-2637626462.html?utm_content=inf_10_3759_2&utm_source=facebook&utm_campaign=GTAK&tse_id=INF_336771307b5311e9b433ab68d22425b2

**This was one of the requests to GAM:**
`https://securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=1074491867785985&correlator=876309817301527&output=json_html&callback=googletag.impl.pubads.callbackProxy1&impl=fifs&adsid=AGt39rRTOUd-q6r_PRSJBbFQbjp2E0HTi23V6NJ4jM6vC8kRV4e8CSARIjcxagpSRdiHLGAWBQDgIbmxCYTC&jar=2019-05-28-17&json_a=1&eid=21061508%2C21060611%2C21060697%2C21061864%2C21062150%2C21062414%2C21062421&vrg=2019052001&guci=2.2.0.0.2.2.0.0&plat=1%3A32776%2C2%3A16809992%2C8%3A32776&sc=1&sfv=1-0-33&ecs=20190528&iu_parts=18190176%2CAdThrive_Header_1%2C5ae7428aedbe613495a432b0%2CAdThrive_Sidebar_1%2CAdThrive_Sidebar_9%2CAdThrive_Content_1%2CAdThrive_Content_2%2CAdThrive_Content_3%2CAdThrive_Content_4%2CAdThrive_Content_5%2CAdThrive_Content_6%2CAdThrive_Content_7%2CAdThrive_Content_8%2CAdThrive_Content_9%2CAdThrive_Footer_1&enc_prev_ius=%2F0%2F1%2F2%2C%2F0%2F3%2F2%2C%2F0%2F4%2F2%2C%2F0%2F5%2F2%2C%2F0%2F6%2F2%2C%2F0%2F7%2F2%2C%2F0%2F8%2F2%2C%2F0%2F9%2F2%2C%2F0%2F10%2F2%2C%2F0%2F11%2F2%2C%2F0%2F12%2F2%2C%2F0%2F13%2F2%2C%2F0%2F14%2F2&prev_iu_szs=320x50%7C728x90%7C320x50%7C300x50%7C320x100%7C468x60%7C1x1%7C728x250%2C320x50%7C300x250%7C300x600%7C320x50%7C160x600%7C300x1050%7C300x50%7C320x100%7C250x250%7C120x240%7C1x1%7C300x420%2C320x50%7C300x250%7C300x600%7C320x50%7C160x600%7C300x1050%7C300x50%7C320x100%7C250x250%7C120x240%7C1x1%7C300x420%2C320x50%7C728x90%7C300x250%7C320x50%7C336x280%7C300x50%7C320x100%7C468x60%7C250x250%7C120x240%7C1x1%7C300x300%7C552x334%7C728x250%2C320x50%7C728x90%7C300x250%7C320x50%7C336x280%7C300x50%7C320x100%7C468x60%7C250x250%7C120x240%7C1x1%7C300x300%7C552x334%7C728x250%2C320x50%7C728x90%7C300x250%7C320x50%7C336x280%7C300x50%7C320x100%7C468x60%7C250x250%7C120x240%7C1x1%7C300x300%7C552x334%7C728x250%2C320x50%7C728x90%7C300x250%7C320x50%7C336x280%7C300x50%7C320x100%7C468x60%7C250x250%7C120x240%7C1x1%7C300x300%7C552x334%7C728x250%2C320x50%7C728x90%7C300x250%7C320x50%7C336x280%7C300x50%7C320x100%7C468x60%7C250x250%7C120x240%7C1x1%7C300x300%7C552x334%7C728x250%2C320x50%7C728x90%7C300x250%7C320x50%7C336x280%7C300x50%7C320x100%7C468x60%7C250x250%7C120x240%7C1x1%7C300x300%7C552x334%7C728x250%2C320x50%7C728x90%7C320x50%7C320x100%7C468x60%2C320x50%7C728x90%7C320x50%7C320x100%7C468x60%2C320x50%7C728x90%7C320x50%7C320x100%7C468x60%2C320x50%7C728x90%7C320x50%7C970x90%7C300x50%7C320x100%7C468x60%7C1x1&fluid=height%2Cheight%2Cheight%2Cheight%2Cheight%2Cheight%2Cheight%2Cheight%2Cheight%2Cheight%2Cheight%2Cheight%2Cheight&fsbs=1%2C1%2C1%2C1%2C1%2C1%2C1%2C1%2C1%2C1%2C1%2C1%2C1&prev_scp=location%3DHeader%26sequence%3D1%26amznbid%3D2%26amznp%3D2%26hb_size_appnexus%3D728x90%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D29596d80924a4ceb%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D28121e2089c8a911%26hb_bidder_rubicon%3Drubicon%26hb_size_ix%3D728x90%26hb_pb_ix%3D99.00%26hb_adid_ix%3D2735596de63559c4%26hb_bidder_ix%3Dix%26hb_deal_rubicon%3D1123456%26ix_pb%3D9%26ix_size%3D728x90%26O2%3D15_10%26O%3D2735596de63559c4%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dfalse%26hb_size%3D728x90%26hb_pb%3D99.00%26hb_adid%3D2735596de63559c4%26hb_bidder%3Dix%26utc_hour%3D17%26refresh%3D00%7Clocation%3DSidebar%26sequence%3D1%26amznbid%3D2%26amznp%3D2%26hb_size_criteo%3D300x600%26hb_pb_criteo%3D99.00%26hb_adid_criteo%3D8c2e5b30-08e0-437d-b308-b250e3432cf2%26hb_bidder_criteo%3Dcriteo%26hb_size_appnexus%3D300x250%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D29696cca6e574048%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D282e6bde4af21a6%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dfalse%26hb_size%3D300x600%26hb_pb%3D99.00%26hb_adid%3D8c2e5b30-08e0-437d-b308-b250e3432cf2%26hb_bidder%3Dcriteo%26utc_hour%3D17%26refresh%3D00%7Clocation%3DSidebar%26sequence%3D9%26amznbid%3D2%26amznp%3D2%26hb_size_triplelift%3D300x420%26hb_pb_triplelift%3D95.00%26hb_adid_triplelift%3D279ff68104cbea16%26hb_bidder_triplelift%3Dtriplelift%26hb_size_criteo%3D300x600%26hb_pb_criteo%3D99.00%26hb_adid_criteo%3Dc2c22a4d-d46b-4758-90fb-5d7a5f0d136b%26hb_bidder_criteo%3Dcriteo%26hb_size_appnexus%3D300x250%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D297d0b1e5a14a949%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D283224801ca2f1cd%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dfalse%26hb_size%3D300x600%26hb_pb%3D99.00%26hb_adid%3Dc2c22a4d-d46b-4758-90fb-5d7a5f0d136b%26hb_bidder%3Dcriteo%26utc_hour%3D17%26refresh%3D00%7Clocation%3DContent%26sequence%3D1%26amznbid%3D2%26amznp%3D2%26hb_size_criteo%3D300x250%26hb_pb_criteo%3D99.00%26hb_adid_criteo%3D58e9b97f-70a2-4b3b-9e1b-4202be1caf17%26hb_bidder_criteo%3Dcriteo%26hb_size_appnexus%3D320x50%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D298ea85c759f14e2%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D2840eb69f948631%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dfalse%26hb_size%3D300x250%26hb_pb%3D99.00%26hb_adid%3D58e9b97f-70a2-4b3b-9e1b-4202be1caf17%26hb_bidder%3Dcriteo%26utc_hour%3D17%26refresh%3D00%7Clocation%3DContent%26sequence%3D2%26amznbid%3D2%26amznp%3D2%26hb_size_criteo%3D300x250%26hb_pb_criteo%3D99.00%26hb_adid_criteo%3Dbadb313c-f90b-4236-b382-42ed3f917df0%26hb_bidder_criteo%3Dcriteo%26hb_size_appnexus%3D300x50%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D2990f17dc6a47c76%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D286631d912e68e27%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dfalse%26hb_size%3D300x250%26hb_pb%3D99.00%26hb_adid%3Dbadb313c-f90b-4236-b382-42ed3f917df0%26hb_bidder%3Dcriteo%26utc_hour%3D17%26refresh%3D00%7Clocation%3DContent%26sequence%3D3%26amznbid%3D2%26amznp%3D2%26hb_size_triplelift%3D552x334%26hb_pb_triplelift%3D95.00%26hb_adid_triplelift%3D28090cf67aff463f%26hb_bidder_triplelift%3Dtriplelift%26hb_size_appnexus%3D728x90%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D300a5ed2880fe82f%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D2879f8ec00c1830a%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26hb_deal%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dtrue%26hb_size%3D728x90%26hb_pb%3D99.00%26hb_adid%3D2879f8ec00c1830a%26hb_bidder%3Drubicon%26utc_hour%3D17%26refresh%3D00%7Clocation%3DContent%26sequence%3D4%26amznbid%3D2%26amznp%3D2%26hb_size_appnexus%3D728x90%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D3014a1bc9c1c2d0f%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D2886f790d27d444d%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26hb_deal%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dtrue%26hb_size%3D728x90%26hb_pb%3D99.00%26hb_adid%3D2886f790d27d444d%26hb_bidder%3Drubicon%26utc_hour%3D17%26refresh%3D00%7Clocation%3DContent%26sequence%3D5%26amznbid%3D2%26amznp%3D2%26hb_size_appnexus%3D728x90%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D302bad86caa5df4%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D289e018fc21de92d%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26hb_deal%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dtrue%26hb_size%3D728x90%26hb_pb%3D99.00%26hb_adid%3D289e018fc21de92d%26hb_bidder%3Drubicon%26utc_hour%3D17%26refresh%3D00%7Clocation%3DContent%26sequence%3D6%26amznbid%3D2%26amznp%3D2%26hb_size_appnexus%3D728x90%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D3030e0e4bfd9b2db%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D290afa2534eae0eb%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26hb_deal%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dtrue%26hb_size%3D728x90%26hb_pb%3D99.00%26hb_adid%3D290afa2534eae0eb%26hb_bidder%3Drubicon%26utc_hour%3D17%26refresh%3D00%7Clocation%3DContent%26sequence%3D7%26amznbid%3D2%26amznp%3D2%26hb_size_appnexus%3D728x90%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D3041630d745cd54f%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D29130e2b5a198317%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26hb_deal%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dtrue%26hb_size%3D728x90%26hb_pb%3D99.00%26hb_adid%3D29130e2b5a198317%26hb_bidder%3Drubicon%26utc_hour%3D17%26refresh%3D00%7Clocation%3DContent%26sequence%3D8%26amznbid%3D2%26amznp%3D2%26hb_size_appnexus%3D728x90%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D3053e9dde4d469dd%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D292fc86b0c78c33%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26hb_deal%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dtrue%26hb_size%3D728x90%26hb_pb%3D99.00%26hb_adid%3D292fc86b0c78c33%26hb_bidder%3Drubicon%26utc_hour%3D17%26refresh%3D00%7Clocation%3DContent%26sequence%3D9%26amznbid%3D2%26amznp%3D2%26hb_size_appnexus%3D728x90%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D3061a5b9665ed166%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D293890cee8ad11bc%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26hb_deal%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dtrue%26hb_size%3D728x90%26hb_pb%3D99.00%26hb_adid%3D293890cee8ad11bc%26hb_bidder%3Drubicon%26utc_hour%3D17%26refresh%3D00%7Clocation%3DFooter%26sequence%3D1%26ATF%3Dtrue%26sticky%3Dtrue%26amznbid%3D2%26amznp%3D2%26hb_size_districtm%3D728x90%26hb_pb_districtm%3D86.00%26hb_adid_districtm%3D278efafa9ee4b822%26hb_bidder_districtm%3Ddistrictm%26hb_size_appnexus%3D728x90%26hb_pb_appnexus%3D99.00%26hb_adid_appnexus%3D3072bd47e1e2448a%26hb_bidder_appnexus%3Dappnexus%26hb_size_rubicon%3D728x90%26hb_pb_rubicon%3D99.00%26hb_adid_rubicon%3D294bf38079564c67%26hb_bidder_rubicon%3Drubicon%26hb_deal_rubicon%3D1123456%26hb_deal%3D1123456%26xfloor%3D100%26dynmultd%3Dbc_p3_s1.5_i0.15%26hb_pmp%3Dtrue%26hb_size%3D728x90%26hb_pb%3D99.00%26hb_adid%3D294bf38079564c67%26hb_bidder%3Drubicon%26utc_hour%3D17%26refresh%3D00&eri=5&cust_params=siteId%3D5ae7428aedbe613495a432b0%26siteName%3DComic%2520Sands%26verticals%3DEntertainment%252CNews%26abgroup%3Ddynflr%253Abuyrules%252Cloglevel%253Aoff%252Chbho%253Arhythmone_ebda%252Cpbs2s_appnexus%253Aoff%252Cpbs2s_districtm%253Aoff%252Cpbs2s_sovrn%253Aoff%252Cpbs2s_openx%253Aoff%252Cpbs2s_rubicon%253Aoff%252Croxot%253Aoff%252Cto_initial%253A2800%252Cto_refresh%253A1600%26bucket%3Ddebug%26topics%3DEA%26marmalade%3Dtrue%26domain%3Dwww.comicsands.com%26hi_au%3Danimatedfooter%252Cexpandablefooter%252Cinterscroller%252Cminiscroller%252Cnativemobilecontent%252Cnativedesktopcontent%252Cnativedesktopsidebar%252Coutstreamdesktop%252Coutstreammobile%26vpwxvph%3D1458x365%26fpv%3D0&cookie=ID%3D808cbb20909351e9%3AT%3D1559058034%3AS%3DALNI_MbLN6JiF3RvUZsfeGDLTf5V5ryyZQ&cdm=www.comicsands.com&bc=31&abxe=1&lmt=1559065670&dt=1559065670728&dlt=1559065656869&idt=5816&frm=20&biw=1458&bih=365&oid=3&adxs=230%2C1108%2C1108%2C242%2C242%2C242%2C242%2C242%2C242%2C230%2C230%2C230%2C365&adys=198%2C198%2C1216%2C941%2C1970%2C2803%2C4309%2C5559%2C6222%2C11034%2C11924%2C12856%2C275&adks=2943349940%2C3088919114%2C4247656138%2C2129144637%2C1400346103%2C3294542502%2C1586135530%2C3084902355%2C174421251%2C1366243098%2C2421800524%2C2346135019%2C3931962363&ucis=1%7C2%7C3%7C4%7C5%7C6%7C7%7C8%7C9%7Ca%7Cb%7Cc%7Cd&ifi=1&u_tz=-240&u_his=12&u_h=1080&u_w=1920&u_ah=1057&u_aw=1920&u_cd=24&u_nplug=3&u_nmime=4&u_sd=1&flash=0&url=https%3A%2F%2Fwww.comicsands.com%2Fchick-fil-a-rodney-bullard-2637626462.html&loc=https%3A%2F%2Fwww.comicsands.com%2Fchick-fil-a-rodney-bullard-2637626462.html%3Fpbjs_debug%3Dtrue&dssz=77&icsg=10485760&std=0&rumc=1736939392355300&rume=1&vis=1&dmc=8&scr_x=0&scr_y=0&trunc=1`
