### ISSUE TITLE
`alwaysUseBid` broken since 0.8.1

### ISSUE THREAD

**Issue by kmjennison** [prebid/Prebid.js#389]
The `alwaysUseBid` setting appears to be broken. Instead of always sending the bid to the ad server, it does nothing. I think this functionality was accidentally removed in the prebid.js refactoring prior to 0.9.0: https://github.com/prebid/Prebid.js/commit/2ad8150b73110c199bfc73f916589b3f3f016a7f#diff-f8e049a1b6d4f9aa96fca41d2f7aa11dL286

To reproduce, add a custom bidder setting to `pbjs.bidderSettings` in `pbjs_example_gpt.html`, such as:
```
brightcom: {
    alwaysUseBid: true,
    adserverTargeting: [
        {
            key: "custom_test_key",
            val: function (bidResponse) {
                return bidResponse.bidderCode;
            }
        }
    ]
}
```

When brightcom responds with a bid, we'd expect the `custom_test_key` key to be part of the targeting object when you call `pbjs.getAdserverTargeting()`. However, it is not.

If you redo this test on the commit for the 0.8.1 release, `custom_test_key` is part of the targeting as expected.

I'm working on a fix for this and should have a PR soon.

**Comment by protonate** [comment]
Thanks for reporting the issue and for the PR, I'll have a look.

**Comment by mkendall07** [comment]
this fix has been merged.
