### ISSUE TITLE
adUnits.sizes is overwritten when mediaType.banner.sizes & mediaType.video.playerSize coexists

### ISSUE THREAD

**Issue by kenju** [prebid/Prebid.js#3903]
## Type of issue

A question (this can be a bug I think)

## Description

Let's say, we define both 

- `mediaTypes.banner.sizes`
- `mediaTypes.video.playSize`

> this example is taken from this official documentation:
> http://prebid.org/dev-docs/show-multi-format-ads.html

```javascript
 pbjs.addAdUnits({
        code: 'div-banner-outstream-native',
        mediaTypes: {
            banner: {
                sizes: [
                    [300, 250],
                    [300, 50]
                ]
            },
            video: {
                context: 'outstream',
                playerSize: [640, 480]
            },
        },
    });
```

This is because, `src/Prebid.js` overwrites `adUnits.sizes` with `mediaType.video.playerSize` once after `mediaType.banner.sizes` are set.

https://github.com/prebid/Prebid.js/blob/5ba930d20f2aeb4318372af9afda0b676fc820e0/src/prebid.js#L77-L107

Here is an implementation of [utils.getAdUnitSizes](https://github.com/prebid/Prebid.js/blob/cde8f166224b3c74b78f79bbf019367be8adf8e6/src/utils.js#L152-L179)

The question is, is it intentional, or should we merge `mediaTypes.banner.sizes` and `mediaTypes.video.playSize` so that we can set all sizes to `adUnits.sizes`?

NOTE: we are using [v1.14.0](https://github.com/prebid/Prebid.js/tree/1.14.0). I am not sure whether this is related.

## Steps to reproduce

- Define both `mediaTypes.banner.sizes` and `mediaTypes.video.playSize`
- See `pbjs.adUnits` afterwards, and see that `adUnits.sizes`  from the console

## Test page

- Define both `mediaTypes.banner.sizes` and `mediaTypes.video.playSize`
  - let's say, `mediaTypes.banner.sizes == [[300, 250], [300, 200]]` and `mediaTypes.video.playSize == [300, 280]`
- See `pbjs.adUnits` afterwards, and see that `adUnits.sizes` 

### Expected results
- expected: `[[300, 250], [300, 200], [300, 280]]`

### Actual results
- actual: `[300, 280]`

## Platform details

Prebid.js

## Other information

Nope.

**Comment by GgermanCrunchmind** [comment]
Having the same problem, still relevant.

**Comment by patmmccann** [comment]
This is deprecated

https://github.com/prebid/Prebid.js/issues/4118
