### ISSUE TITLE
Bug in currency module

### ISSUE THREAD

**Issue by salvoaranzulla** [prebid/Prebid.js#3909]
## Type of issue

Bug

## Description

There is a bug in currency module. If you specify "rates" manually and "defaultRates" at the same time, "defaultRates" overwrites "rates".

### Expected results

I think you should fix this line:

https://github.com/prebid/Prebid.js/blob/master/modules/currency.js#L63 

with 

if (typeof config.defaultRates === 'object' && !currencyRatesLoaded)

**Comment by snapwich** [comment]
I agree that `rates` should ideally trump `defaultRates` although I'm kind of curious on your use case where you're using both?  I've always seen these two features as mutually exclusive.
