### ISSUE TITLE
DigiTrustIdSystem does not build facade object if an ID is found by the userId system

### ISSUE THREAD

**Issue by goosemanjack** [prebid/Prebid.js#3911]
## Type of issue
Bug. 

## Description
The slim deployment of DigiTrust via the userId system only builds the facade when an ID must be generated. If an ID is already present at load all the DigiTrust APIs are not available.

## Steps to reproduce
1. Deploy prebid
2. Open digitrust_Simple.html page. In JS console check window.DigiTrust to confirm object exists.
3. Reload page. In JS console check window.DigiTrust to see it is undefined

## Test page
https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/digitrust_Simple.html
One must deploy Prebid to use this page

### Expected results
The DigiTrust facade should be built any time the digitrustIdSystem is included and the full DigiTrust library is not. The window.DigiTrust object should be present in both situations after load.

### Actual results
window.DigiTrust == undefined when an ID already exists for browser.

## Platform details
Chrome browser, other browsers

**Comment by goosemanjack** [comment]
I am currently working through an updated unit test fixture and should submit soon.

**Comment by goosemanjack** [comment]
There is an active PR. I am waiting for review. The CircleCI has an intermittent timeout failure on Safari that I'm not sure is tied to our unit test. Will make a couple more checks.

https://github.com/prebid/Prebid.js/pull/3918

**Comment by bretg** [comment]
#3918 merged.
