### ISSUE TITLE
Error tryin to use prebid.js with SSR rendering where the window object is not available

### ISSUE THREAD

**Issue by webdeveloperpr** [prebid/Prebid.js#3912]
## Type of issue
Feature

## Description
Seems like prebidJS assumes that the window object is always available on the client. We have a React SSR application that imports prebid and it fails on the server because window is not available

### Expected results

I am expecting the application to still be running even without the window object, or maybe a function that to initiate prebid instead of running as soon as you import it.

### Actual results

```
ReferenceError: window is not defined
    at Object.<anonymous> (/home/betancourtl/static-ads/lib/static-atlas.js:9169:1)
    at __webpack_require__ (/home/betancourtl/static-ads/lib/static-atlas.js:30:30)
    at Object.<anonymous> (/home/betancourtl/static-ads/lib/static-atlas.js:8220:72)
    at Object.__webpack_exports__.a (/home/betancourtl/static-ads/lib/static-atlas.js:9159:30)
    at __webpack_require__ (/home/betancourtl/static-ads/lib/static-atlas.js:30:30)
    at Object.<anonymous> (/home/betancourtl/static-ads/lib/static-atlas.js:8075:68
```

That points to this file https://github.com/prebid/Prebid.js/blob/master/src/prebidGlobal.js

## Platform details
Node + ReactSSR

Anyone knows how to the prebid.js working correctly server side using the npm modules way?

Example

```
import prebid from 'prebid.js';
import 'prebid.js/modules/rubiconBidAdapter';
```

**Comment by snapwich** [comment]
I can look into this.  Ideally it should probably be using `global` rather than `window` and I can probably fix that, however I'm not positive that you won't run into further issues with Prebid.js exporting itself onto the server-side global.  Usually when it comes to SSR applications there are methods to avoid code execution in certain contexts (client vs server), does your SSR framework provide something?

**Comment by webdeveloperpr** [comment]
I ended up using `require` statements to load prebid inside a function. This seems to work fine.

```javascript
/**
 * @description
 * Loads the prebid header bidders.
 */
const init = () => {
    const prebid = require('prebid.js').default;
    require('prebid.js/modules/rubiconBidAdapter');
    require('prebid.js/modules/openxBidAdapter');
    require('prebid.js/modules/criteoBidAdapter');
    require('prebid.js/modules/ixBidAdapter');
    require('prebid.js/modules/teadsBidAdapter');
    require('prebid.js/modules/optimeraBidAdapter');
    require('prebid.js/modules/kargoBidAdapter');
    require('prebid.js/modules/dfpAdServerVideo');
    // required to process existing pbjs.queue blocks and setup any further pbjs.queue execution
    prebid.processQueue();
    var pbjs = window.pbjs || {};
    pbjs.que = pbjs.que || [];
    pbjs.que.push(() => {
        setConfig(pbjs);
        setTargeting(pbjs);
    });
};

```
