### ISSUE TITLE
EMX Digital import reference error

### ISSUE THREAD

**Issue by DecayConstant** [prebid/Prebid.js#3917]
## Type of issue
Bug @EMXDigital 

## Description
The EMX Digital adapter has reverted to importing files by absolute paths, not relative paths.  They had fixed the issue previously: https://github.com/prebid/Prebid.js/pull/3731#discussion_r274086132

## Steps to reproduce
Try importing the EMX Digital adapter.
```javascript
import prebid from 'prebid.js'
import 'prebid.js/modules/emx_digitalBidAdapter'
```

That results in this error message: 
```
ERROR in ./node_modules/prebid.js/modules/emx_digitalBidAdapter.js
Module not found: Error: Can't resolve 'src/utils' in '/Users/user/dev/video-player/node_modules/prebid.js/modules'
```

## Other information
The regression happened in this PR: https://github.com/prebid/Prebid.js/pull/3840

**Comment by jsnellbaker** [comment]
@DecayConstant Thanks for raising this issue; I found there were import syntax issues for several other adapters as well.  I'll put together a fix for this in a bit.
