### ISSUE TITLE
Update AppNexus test params

### ISSUE THREAD

**Issue by mannzer** [prebid/Prebid.js#3931]
## Type of issue
The AppNexus adapter does not meet the stated requirements at http://prebid.org/dev-docs/bidder-adaptor.html

## Description
The requirements state: "A test ad unit that will consistently return test creatives. This helps us to ensure future Prebid.js updates do not break your adapter. Note that if your adapter supports video (instream and/or outstream context) or native, you must also provide example parameters for each type."

## Steps to reproduce
Use any of the IDs listed on https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.md

### Expected results
"A test ad unit that will consistently return test creatives." as stated in the requirements.

### Actual results
{"version":"3.0.0","tags":[{"uuid":"21c192f95c187","tag_id":10433394,"auction_id":"4473092687993829924","nobid":true,"ad_profile_id":27079},{"uuid":"30471182076023","error":"member"},{"uuid":"401a03a3390036","error":"member"},{"uuid":"5ef2e99d5ff725","error":"member"},{"uuid":"62986998e109a2","error":"member"}]}

**Comment by mkendall07** [comment]
Hi @mannzer 
Thanks for letting us know. We'll take a look and see if they need updated. 

BTW I think if you audited the adapters you'd find a majority do not have live params. it's a big issue unfortunately

**Comment by jsnellbaker** [comment]
Hi @mannzer 

Can you provide a copy of the test-page you used (or at least a copy of the request's data payload object)?  

I setup a test with the hello_world using all the adUnit examples from the `appnexusBidAdapter.md` file and the response from the AN endpoint didn't show the member errors.  Did you happen to have another appnexus adUnit/bid present at the same time you did your test?

**Comment by lanceloti** [comment]
Hi, this member error occurs when you mix placements from different accounts.

**Comment by mannzer** [comment]
I was using just the ids listed on the example, no others from other accounts.  This also happens when just a single ID is used.  I do notice they seem to work here: http://prebid.org/examples/native/ but can't reproduce that response anywhere else.

**Comment by mannzer** [comment]
This seems to have been remedied on the upstream side as I now see test bids working (with no changes to my code).  Thank you!
