### ISSUE TITLE
Rubicon Outstream & Prebid Universal Creative: Cannot read property 'crid' of undefined

### ISSUE THREAD

**Issue by lanceloti** [prebid/Prebid.js#3934]
## Type of issue
Bug

## Description
I don't know if it is a Rubicon adapter problem or Prebid Universal Creative one.

Prebid Univeral Creative is trying to get the VAST response intead of calling custom render of adunit.

If I use the older prebid creative it works fine.

## Steps to reproduce
Configure one Outstream adunit with Rubicon as bidder. DFP creatives must use safe-frame and Prebid Universal Creative.

## Test page
Rubicon won't bid on fiddler domain, so it's hard to test.

### Expected results
Custom render of adunit must be called

### Actual results
Error trying to render ads

## Platform details
Prebid 2.20

![rubicon-bid-response-2](https://user-images.githubusercontent.com/17436827/59868326-0cf7ed00-9367-11e9-92cd-116e3d403edc.png)
![rubicon-bid-response](https://user-images.githubusercontent.com/17436827/59868327-0cf7ed00-9367-11e9-85c0-83a768aa2fd8.png)
![rubicon-creative-vast](https://user-images.githubusercontent.com/17436827/59868329-0d908380-9367-11e9-86a9-0dd60ca34901.png)
![rubicon-error](https://user-images.githubusercontent.com/17436827/59868331-0d908380-9367-11e9-9758-61819b99ac6f.png)

**Comment by Jobeso** [comment]
Did you find a solution for that?

**Comment by lanceloti** [comment]
@Jobeso nop... I'm using legacy creative for now.
