### ISSUE TITLE
Prebid.js SSP impression tracking and viewability broken since v2.3.0 on Edge and IE11

### ISSUE THREAD

**Issue by tkwillis** [prebid/Prebid.js#3939]
## Type of issue
Bug

## Description
On upgrading from Prebid 1.37 to 2.11.0 we encountered a large discrepancy between DFP and all ur Prebid Partners. We isolated to IE11/Edge. Impressions for these browsers in SSP consoles were effectively 0 on v2.11.0.  Upon further investigation DFP/GAM viewability for Edge/IE11 was zero. Roughly 10% of impressions for us, so small but not insignificant. We rolled back and discrepancy recovered.

There was no console error in IE/Edge. On Testing different versions of Prebid, I isolated it to being introduced in Prebid.js v2.3.0. 

On further testing I believe it was introduced by https://github.com/prebid/Prebid.js/pull/3524

document.open does not appear to work properly on IE11/Edge.

if that bug was for Firefox only, will:

          if(navigator.userAgent.toLowerCase().indexOf('firefox') > -1){
            doc.open('text/html', 'replace');
          }

suffice as a solution to add to ~/src/prebid.js?

## Steps to reproduce
Build any version of prebid.js v2.3.0+, on Edge/IE when DFP/GAM serves the prebid impression, check the viewability on the line in the GAM report.

## Test page
NA

### Expected results

Prebid won ads should show viewability in GAM reports for Edge and IE11 and impression tracking pixels should fire for SSPs and DFP/GAM.

### Actual results

impression tracking not firing on Edge and IE.

## Platform details
Versions of prebid.js v2.3.0+ onwards on Windows Browsers:  IE11 and Edge.

**Comment by ssick** [comment]
I can confirm this issue. We rolled back the prebid.js version from 2.9.0 to 1.21.0 eventually after we had discovered that there were problems with viewability.

Thanks for the detailed analysis!

**Comment by sgallo0692** [comment]
can you clarify on the firefox example provided? This doesn't impact firefox, does it?

**Comment by GLStephen** [comment]
@sgallo0692 this  was the code added in #3524 
'''
doc.open('text/html', 'replace');
'''
I think that @tkwillis suggestion is to wrap it in a browser check since the unintended consequence seems to be an IE/Edge issue.

**Comment by tkwillis** [comment]
Yep, that right, the bugfix for a firefox issue, caused the issue on IE/Edge

**Comment by jsnellbaker** [comment]
Hi @tkwillis,

Wanted to give an update here; I did some digging into this issue and your suggested fix.  The code you provided looks like it could address the tracking problem in Edge browsers.  

Given the nature of the fix, I need to sync with the rest of the Prebid group to see if this type of browser-specific approach is the way we want to implement the fix or if there's another way that should be used.  I will follow-up on this matter.

Thank you though for reporting this issue and putting together all the related information, it was very helpful!

**Comment by tkwillis** [comment]
Hi @jsnellbaker,

Thanks for the update. Yeah, I understand about the need to discuss, that's what I kind of meant when I said will the fix suffice.

At any rate it tested ok and I put it into production with v2.18.0 late last week. We checked yesterday and so far GAM looks fine and SSP consoles are within an acceptable discrepancy range.

Thanks for picking this up. Looking forward to see it fixed one way or another in the main release.

**Comment by jsnellbaker** [comment]
This issue should be fixed via the PR https://github.com/prebid/Prebid.js/pull/3980

This change has been approved and should be part of the Prebid.js 2.23.0 release (scheduled to go out later today).
