### ISSUE TITLE
Support a delayAuction config flag for userId module to prefetch user ids

### ISSUE THREAD

**Issue by smenzer** [prebid/Prebid.js#3952]
## Type of issue
Feature Request

## Description
Today, the userId module waits `syncDelay` ms after the bid requests are sent to demand partners before it attempts to retrieve user ids from id providers that the publisher has configured. This means that, on the first page view for a user (and potentially more depending upon timeouts, etc), ids from the userId module will never be available for bid adapters to listen to and send to their rtb partners. This is problematic for publishers, especially in environments where 3rd party cookies are blocked, because the 1st page load can represent a significant revenue stream for them.

I would like to suggest that a new configuration option, `delayAuction` (or something named similarly), is supported. If set by the publisher, the bid requests will be delayed up to this many ms while the id requests from the userId module are happening. If the `delayAuction` config is not set, then the auction should not be delayed and the `syncDelay` settings should be used.

## Expected behavior
* If `delayAuction` is set, delay sending bid requests for that many ms. As soon as possible in the loading of the prebid code and publisher configuration, make the requests to the id providers that the publisher has configured.
* If the response(s) from the id provider(s) come back within `delayAuction` ms of the bid requests being ready to be sent, make them available to the bid adapters. This shouldn't be all or nothing...any providers that return in time should be included, those that do not return in time are not included. The results from the id providers should be stored based on the publisher's configuration as normal (usually in a 1st party cookie).
* If the response(s) from the id provider does NOT return within `delayAuction` ms of the bid requests being ready, the bid requests should be sent without the id(s) being available. Prebid should still try to wait for the response and if it is received eventually (even if it is after the bid requests go out, or after the auction completes), the response should be stored based on the publisher's configuration; this way the next page view does not need to make a request. This is essentially the behavior that exists today, just that the userId request would happen earlier in the process.
* If both `delayAuction` and `syncDelay` are set, I would suggest that `delayAuction` is used.

## Other information
Related to the [userId](https://github.com/prebid/Prebid.js/blob/master/modules/userId.js) module

**Comment by mutdmour** [comment]
PR still WIP. Will try to finish this soon. https://github.com/prebid/Prebid.js/pull/4115

**Comment by bretg** [comment]
Released with 2.35
