### ISSUE TITLE
Extend ESLint

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#3964]
## Type of issue
Feature Request

## Description
With new submodules pattern implemented recently here, we are not allowing any module to import other modules. Modules can only import what is in src folder. Contributors adding code to modules may not know of this requirement and reviewers too may miss while approving pull requests. I think eslint can rescue us here.

Extend ES lint to throw error when modules are importing other modules. Also another good to have feature with this would be to make sure modules use relative path while importing.

Sample code which should throw error

```
// Consider two files 
// File 1 modules/currency.js
// File 2 modules/sampleBidAdapter.js

// sampleBidAdapter.js
...
import * from './currency'; // This should not be allowed.
...
...
```

```
// Consider two files 
// File 2 modules/sampleBidAdapter.js

// sampleBidAdapter.js
...
import * from 'src/utils'; // This should not be allowed.
import * from '../src/utils'; // Correct way to import module
...
...
```

**Comment by Fawke** [comment]
Hi Jaimin,

I've submitted a PR https://github.com/prebid/Prebid.js/pull/3970 for this issue. Unfortunately, Circle CI is failing, I've to figure out why.
