### ISSUE TITLE
Malware - Auto Redirect Ads

### ISSUE THREAD

**Issue by ekg987** [prebid/Prebid.js#3971]
## Type of issue
Question

## Description
Mobile Auto Redirect Ads

## Platform details
~~The site experiencing this issue is currently running with prebid 0.  Update to the latest prebid version will be live any day now.~~ Multiple sites using both both prebid 0 and prebid 1.X.

## Other information
We just started seeing a major uptick in these mobile redirect ads.  I've read through the discussions on previous issues surrounding this but have a couple questions.  ~~Is the upgrade to at least prebid 1.X enough to get rid of these redirect ads (if possible would anyone be able to explain why or point me to documentation)?~~  While I know it is recommended, is it also a necessity to enable safeframes and sandboxing?

**Comment by bretg** [comment]
Sorry, Prebid.js can't help with the scourge of auto-redirect ads. Safeframes are the way to go.
