### ISSUE TITLE
Kargo Bidder tries to define _sessionId in frozen spec object.

### ISSUE THREAD

**Issue by webdeveloperpr** [prebid/Prebid.js#3991]
## Type of issue
Bug

## Description
Looks like kargoBidAdapter is crashing when fetching bids because it tries to update the spec object. The spec object gets frozen by the registerBidder() fn.

<img width="822" alt="Screen Shot 2019-07-11 at 5 08 27 PM" src="https://user-images.githubusercontent.com/7534346/61087155-cdbb3a00-a402-11e9-85cb-120284da0485.png">

I tracked that fn call in the kargoBidAdapter and it lead me here:

https://github.com/prebid/Prebid.js/blob/2be5cc7ccbc89c940c1e2e253a989e4a351167e2/modules/kargoBidAdapter.js#L186-L192

the spec object then gets passed here where it gets frozen.

https://github.com/prebid/Prebid.js/blob/2be5cc7ccbc89c940c1e2e253a989e4a351167e2/src/adapters/bidderFactory.js#L166-L170

From MDN

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

> A frozen object can no longer be changed; freezing an object prevents new properties from being added to it, existing properties from being removed, prevents changing the enumerability, configurability, or writability of existing properties, and prevents the values of existing properties from being changed. In addition, freezing an object also prevents its prototype from being changed. freeze() returns the same object that was passed in.

## Steps to reproduce
Try to request bids using kargoBidAdapter on a page and use the debug query param
`pbjs_debug=true`

### Expected results
Expect the bidder not to crash.

### Actual results
bidder crashes.

**Comment by webdeveloperpr** [comment]
Looks like it was fixed by #3998

**Comment by bretg** [comment]
Yup fixed with #3998
