### ISSUE TITLE
Request to update pbjs.setPriceGranularity documentation 

### ISSUE THREAD

**Issue by thehumanpuck** [prebid/Prebid.js#400]
Documentation says that the "high" option uses 5 cent buckets, but in the code it looks like we are using 1 cent buckets.

Screenshot showing current documentation:
![2016-06-09 10_27_05-publisher api reference for header bidding](https://cloud.githubusercontent.com/assets/8421855/15933229/f2e56c5a-2e2c-11e6-96d6-b5cf7062b3d9.png)

**Comment by mkendall07** [comment]
@thehumanpuck 
Thanks. Added a PR to fix.

**Comment by mkendall07** [comment]
Merged
