### ISSUE TITLE
I2I: Require all SSPs to use secure endpoints (3.x)

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#4005]
## Type of issue
I2I

## Description
Using relative protocols is now considered an anti-pattern (https://www.paulirish.com/2010/the-protocol-relative-url/). We recently saw issues with SafeFrame and non secure creatives causing discrepancies. As a result, we would like to propose all bidder adapters need to use a secure endpoint at all times (regardless if the webpage is secure or not). 

We are putting this into the 3.x changes because we consider it to be breaking.

**Comment by bwoolcott** [comment]
@mkendall07 were there any changes recently (GPT changes or something along those lines?) that led to the increase in discrepancies? Or has this potentially been happening for a while now on non-secure pages that are using safeframes?

**Comment by mkendall07** [comment]
@bwoolcott my understanding is that GPT made a change that made all safeFrames use secure connections regardless of the parent page being secure or not. This led to non secure creatives being rejected.

**Comment by pm-harshad-mane** [comment]
Chrome 80, scheduled to release on 4th Feb 2020 needs all third party cookies to be marked as **Secure** and with **SameSite=None**. To get cookies marked with **Secure** attribute, the call from browser to server should be Secure(HTTPS) so we should prioritize the HTTPS support from all adapters. 
Also, publishers may not update the Prebid code quickly so having these changes ready sooner will give pubs enough time to update their production code.
