### ISSUE TITLE
Join Prebid Organization!

### ISSUE THREAD

**Issue by Heray** [prebid/Prebid.js#401]
@pdezwart @Studnicky @pdramos1 @ericperez @cliffliang @JohnBuonomo @mattjone @naegelin @relegit @ikhemissi @matan-ybrant @indexexchange @amandelindex @nginadfoundation @anand-venkatraman @bjorn-wo @elljoh @protonate @mkendall07 @matthewlane 

You are tagged here because you’ve contributed great code to the prebid adaptors! Thank you! Here are a few things that we can together make supporting and upgrading the adaptors easier:

1, Please join the Prebid Github Organization (invitation emailed on June 8) and also join the [Teams](https://github.com/orgs/prebid/teams) for the adaptors you’ve contributed. Benefits to you:

- Know about the latest new features to the adaptor API (such as adding Deal ID, latency improvements, etc)
- Get notified when users have questions or need help for your adaptor.

2, Please provide an email of yours. Benefits to you:

- You will get notified every time a user downloaded prebid.js with your adaptor in it, so that you know who’s using your adaptor and provide support. (https://github.com/prebid/Prebid.js/issues/399 In Progress)
- For any urgent bug fixes, you will get emails directly if Github doesn’t find you.

To send the information, or if you have any concerns, email paul@prebid.org or leave a comment here.

Thank you!
Prebid

**Comment by indexexchange** [comment]
Hi Paul,

Sounds like an excellent idea -- I'll be in touch with contact info via e-mail.
