### ISSUE TITLE
Audience Network 320x50 Size / format

### ISSUE THREAD

**Issue by kayhia** [prebid/Prebid.js#4014]
## Type of issue
Question: What's the correct way to request bids for the 320x50 size/format from Audience Network?

## Description
In the prebid params, I see Audience Network has: format and placementId. We're currently trying to bid for 320x50 size. Is this achieved through "format: 320x50"? We've done it this way for the 300x250. What happens if the format is 320x50, but the placement from AudienceNetwork is set to 300x250?

**Comment by bretg** [comment]
Adding @lovell

**Comment by lovell** [comment]
`[300, 250]` and `[320, 50]` are `sizes` provided via `addAdUnits`. This is the same way that all prebid adapters work and is documented at http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.addAdUnits

For Audience Network, the `format` property is optional, if specified should be one of “native”, “fullwidth” or “video”. This is documented at http://prebid.org/dev-docs/bidders/audienceNetwork.html

There's an example adding it all together at https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/audienceNetwork_dfp.html
