### ISSUE TITLE
Criteo violates the required adapter conventions by loading external libraries

### ISSUE THREAD

**Issue by mannzer** [prebid/Prebid.js#4031]
## Type of issue
BUG

## Description
Criteo violates the required adapter conventions by loading external libraries

## Steps to reproduce
1. Read http://prebid.org/dev-docs/bidder-adaptor.html#required-adapter-conventions
2. note: "In order to provide a fast and safe header bidding environment for publishers, the Prebid.org team reviews all adapters for the following required conventions:"
...
"No loading of external libraries: All code must be present in the adapter, not loaded at runtime."
3. Observe: https://github.com/prebid/Prebid.js/blob/master/modules/criteoBidAdapter.js#L62

## Test page
https://github.com/prebid/Prebid.js/blob/master/modules/criteoBidAdapter.js#L62

### Expected results
I expect the Prebid.org team to "review all adapters for the following required convention:", including: "No loading of external libraries: All code must be present in the adapter, not loaded at runtime."

### Actual results
The Criteo adapter appears to have been in violation for over a year.

## Other information

https://github.com/prebid/Prebid.js/pull/2370

There was extensive discussion here and this same issue was raised.  No answer was given.
@mkendall07

**Comment by mkendall07** [comment]
Hi @mannzer 
We have an exception to the policy if the bidder submits their code and follows the process outlined here: https://github.com/Prebid-org/prebid-js-external-js-template#policy

I'll link this to the adapter page so it doesn't cause confusion in the future. Thanks

**Comment by patmmccann** [comment]
https://github.com/Prebid-org/prebid-js-external-js-criteo/blob/master/dist/prod.js 404's though, I submitted a new issue to update the link
