### ISSUE TITLE
Native 1.2 assetsurl

### ISSUE THREAD

**Issue by jbartek25** [prebid/Prebid.js#4036]
## Type of issue
question

## Description
[OpenRTB native ads spec 1.2](https://www.iab.com/wp-content/uploads/2018/03/OpenRTB-Native-Ads-Specification-Final-1.2.pdf) defines _assetsurl_ field which if present should be called to fetch the actual native ad assets. The actual call should be made from the client device to give a buyer access to cookie and header data. I've been thinking where to implement the _assetsurl_ call: Prebid adapter? Not possible to make ajax call from interpretResponse. bidsBackHandler? Possible to call _assetsurl_ but then would have to include mapping of oRTB fields to DFP key-values.
Could you please suggest the best way how to implement _assetsurl_ until Prebid fully supports Native 1.2 (not sure if that's planned at all)?

**Comment by jsnellbaker** [comment]
@snapwich Would you be able to take a look at this and help comment?

**Comment by snapwich** [comment]
Sounds like this should happen in the `pbjs.renderAd` call so you can fetch the creative assets upon display. Is it possible to use a custom Renderer @jaiminpanchal27 ? I wasn't involved with that code but it looks like it can be used to do custom ad rendering?

**Comment by jaiminpanchal27** [comment]
As far as I know, for native we cannot use custom rendering as of now because we use universal creative to render native. See template here http://prebid.org/adops/setting-up-prebid-native-in-dfp.html 

[Renderer module](https://github.com/prebid/Prebid.js/blob/master/src/Renderer.js) in Prebid is not tied to any format so we can extend this if publishers want custom native rendering.

**Comment by snapwich** [comment]
possibly related: #3366

**Comment by jbartek25** [comment]
How about extending [assetRequest handler](https://github.com/prebid/Prebid.js/blob/master/src/secureCreatives.js#L48) called by universal creative when replacing native asset placeholders? _assetRequest_ would call _assetsurl_, map oRTB fields to Prebid native KVPs and respond back to universal creative. This would work with existing renderer. The limitation is that _assetsurl_ would only be called when asset placeholders are enabled. I wouldn't think that is a problem since rendering native ads without placeholders has been suffering from issues with special characters and dropped KVPs when request URL is too long. What do you think?

**Comment by snapwich** [comment]
Seems like it would work? Although I'm probably not familiar enough with Native to be making the final call.

**Comment by jbartek25** [comment]
Thanks for the input
