### ISSUE TITLE
Launching Deals

### ISSUE THREAD

**Issue by Heray** [prebid/Prebid.js#404]
Prebid is releasing the deals API next week and we've validated the adaptors for Pubmatic, TripleLift, AppNexus, and bRealTime work for deals. @prebid/triplelift @prebid/pubmatic @prebid/committee to confirm and raise any concerns. @prebid/rubicon: [spec here](https://gist.github.com/Heray/7781a7c940ed1c8215a294f369833cf1)

Below is the release note:

===
Prebid is making it easier for publishers to run deals in header bidding! 

#### Benefits:

- No development change is required to enable deals! If your pages are using the standard key-values, simply upgrade to the latest prebid.js to enable deals.

- Easy ad ops setup with a complete [step by step guide](http://prebid.org/adops/deals.html). Setup deal line items in a few minutes.

#### How to implement it?

In order to enable deals for prebid, the ad ops setup are slightly different from the standard header bidding setup. Specifically:

+ From the ad ops side, you'll create separate orders and line items that target the deal ID key-values. These line items will be at different priorities than your standard header bidding line items. Follow the step by step [Deals Ad Ops Guide](http://prebid.org/adops/deals.html) to implement.

+ From the dev side, if your page is using the standard prebid.js key-values, no change is required. 

Note that the initial list of bidders that support deals are: Pubmatic, TripleLift, AppNexus, bRealTime. More bidder adaptors are implementing deals currently. If you'd like to check progress on a bidder, create a [Github issue](https://github.com/prebid/Prebid.js/issues).

**Comment by ialex** [comment]
Funny coincidence Issue is #404 and the Deals Link to the guide return 404

**Comment by Heray** [comment]
Good catch @ialex. Fixed.

**Comment by protonate** [comment]
This functionality is now available in master, closing.
