### ISSUE TITLE
WARNING: Invalid bid sent to bidder quantcast:

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#4047]
quantcast seems to be throwing this warning, where as all other bids i have don't, when using multi format boxes

WARNING: Invalid bid sent to bidder quantcast: {"bidder":"quantcast","params":{"publisherId":"XXXXXXX"},"crumbs":{"pubcid":"fdccbcf6-8042-459d-b72e-6f1f8ea123a4"},"nativeParams":{"image":{"required":true,"sizes":[150,50]},"title":{"required":true,"len":80},"sponsoredBy":{"required":true},"clickUrl":{"required":true},"privacyLink":{"required":false},"body":{"required":true},"icon":{"required":true,"sizes":[50,50]}},"renderer":{"options":{"adText":"Advertisement"}},"mediaTypes":{"banner":{"sizes":[[300,250],[728,90],[250,250],[468,60],[320,50]]},"native":{"image":{"required":true,"sizes":[150,50]},"title":{"required":true,"len":80},"sponsoredBy":{"required":true},"clickUrl":{"required":true},"privacyLink":{"required":false},"body":{"required":true},"icon":{"required":true,"sizes":[50,50]}},"video":{"context":"outstream","playerSize":[[550,310]],"mimes":["video/x-flv","video/mp4","application/x-shockwave-flash","application/javascript","video/webm"],"playbackmethod":[2],"minduration":0,"maxduration":30,"protocols":[2,3],"linearity":1,"api":[2]}},"adUnitCode":"inreedvid5Slot","transactionId":"c3359a31-4e4c-44ae-8a40-1bd6ab70dbdf","sizes":[[300,250],[728,90],[250,250],[468,60],[320,50]],"bidId":"43d09b8bb90ffce","bidderRequestId":"41e0128c5ac0e3f","auctionId":"bb8e5c29-2c4c-46a8-9bfd-4fa748caf184","src":"client","bidRequestsCount":1}

**Comment by jsnellbaker** [comment]
@jacekburys-quantcast @dpapworth-qc 
Could you take a look into the above?

**Comment by dpapworth-qc** [comment]
@spormeon the bid looks like native inventory. The quantcast adapter only supports display and video inventory.

**Comment by dpapworth-qc** [comment]
i will check to see how we support multiformats.

**Comment by spormeon** [comment]
@dpapworth-qc       its a multi format unit, so banner, native & video,  all other adapters fall gracefully where they don't have vid, native or banner

**Comment by dpapworth-qc** [comment]
@spormeon thanks for flagging, I will look into what's going on.

**Comment by dpapworth-qc** [comment]
@spormeon so, it looks like we are rejecting the bid request because the video included is outstream. I don't think this is the correct way to filter outstream video (so something we should fix on the adapter), but is this something you can disable in the interim?

Are you able to provide a test page where I can see how you are configuring Prebid? My email is dpapworth@quantcast.com, if you want to contact me directly.

**Comment by dpapworth-qc** [comment]
@spormeon I have created a fix that filters the unsupported video context, rather than marking the bid request as invalid. I will try to submit a patch on Monday, after we have reviewed internally at QC.

**Comment by spormeon** [comment]
@dpapworth-qc   great, also for native as think it throws the same if native in there?

**Comment by dpapworth-qc** [comment]
@spormeon I will make sure that we ignore all inventory types that we don't currently support.

**Comment by dpapworth-qc** [comment]
@jsnellbaker are you able to review the above PR?

**Comment by jsnellbaker** [comment]
@dpapworth-qc I will take a look

**Comment by spormeon** [comment]
@dpapworth-qc The latest release seems to have fixed the "Invalid bid sent to bidder quantcast"  but now there seems to be a "Invalid bid from quantcast. Ignoring bid: Bidder quantcast is missing required params"  quantcast is only bidding on "banner" now using publisherId: xxxxxx , not video
prebid 2.29.0

**Comment by dpapworth-qc** [comment]
@spormeon are you able to share the configuration you are using?

**Comment by dpapworth-qc** [comment]
So having looked at the code, the error appears to stem from the response that QC is sending on receiving the bid from the browser. I will check what's being sent back for video creatives.

**Comment by spormeon** [comment]
@dpapworth-qc just on a "normal banner" like this:
{
code: 'XXXXXXXX',
mediaTypes: {
banner: { sizes: [[300, 600],[300, 250],[250, 250],[1, 1]] },
},
bids: [

**Comment by dpapworth-qc** [comment]
@spormeon are you able to include the response you are seeing from qcx.quantserve.com/qchb?

**Comment by spormeon** [comment]
@dpapworth-qc 
{"bidderCode":"quantcast","bids":[{"height":250,"statusCode":0,"width":300}],"requestId":"321b0c2b79d7c17e"}

**Comment by dpapworth-qc** [comment]
ah. thanks. looks like an empty bid - i suspect we don't have any inventory available. this isn't an error with the adapter, but we should probably be sending an empty object in this case.

**Comment by spormeon** [comment]
or a warning , rather than an error?, such as:

WARNING: No valid banner bids from xxxxx bidder
my OCD goes wild looking at errors lol

**Comment by dpapworth-qc** [comment]
:) This error is generated by the Prebid code, and not the adapter itself. I am looking at fixing this on our end.

**Comment by dpapworth-qc** [comment]
@spormeon i've deployed a fix for the above error, so you shouldn't see an error when quantcast returns no bids.
