### ISSUE TITLE
multiple hb_native_image & hb_native_linkurl in native ads

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#4059]
i'm not sure where to ask this, so asking it here,  i'm trying to get native ads working and im coming across some unusual things in that i keep getting multiple hb_native_image & hb_native_linkurl  returns, such as:

hb_native_image:104df19a869aa2c3,hb_native_image:109d7bfc7d44dc13,hb_native_image:114a333a1bc49e34,hb_native_image:1189017d48786a57,hb_native_image:159909171c973231,hb_native_image:1573e8a4c52eb209

&
hb_native_linkurl:104df19a869aa2c3,hb_native_linkurl:109d7bfc7d44dc13,hb_native_linkurl:114a333a1bc49e34,hb_native_linkurl:1189017d48786a57,hb_native_linkurl:159909171c973231,hb_native_linkurl:1573e8a4c52eb209

i'm not sure if this is appnexus sending multiple ones or if its related to:
useBidCache: true

anyway, when it sends multiple i cant get the ad to render, when it send one on the string the ad renders  Is this know of or am i doing something wrong and should try to parse the multiple ones?

**Comment by spormeon** [comment]
bit more info on this, it seems to be sending 'all the bids" info in the targeting , not the "winning bids" one, most unusual to me?

![DevTools_-_adops_golfwrx_com_tweaktownhjgjhg756676native_html-2](https://user-images.githubusercontent.com/8503167/62476591-39dd5380-b79f-11e9-8265-507d275d41aa.png)

**Comment by jsnellbaker** [comment]
@spormeon thanks for reporting this issue.

I was able to replicate it on my end and I'm working on putting together a fix so that the winning's bid info is set in the main key and the bidder data is set properly in the bidder specific variant.

**Comment by spormeon** [comment]
@jsnellbaker ok, thanks.  more info over on this issue as well:

https://github.com/prebid/Prebid.js/issues/3999
