### ISSUE TITLE
passback tag not working in post bid example

### ISSUE THREAD

**Issue by jabal999** [prebid/Prebid.js#407]
I am playing around with the post bid solution and I found a bug. The example on the site states:

```
var iframe = document.getElementById('postbid_if');
var iframeDoc = iframe.contentWindow.document;
iframeDoc.write(passbackTagHtml);
```

The loading and rendering of the document in an iframe happens independently from the parent document. This means the document is probably already closed when the code issues a document.write(). This means the pass back tag is not rendered correctly. The browser keeps loading. The standard solution to this is to open and close the document manually. This will replace the document, but this should not be a problem, since it should have been blank. I suggest the following code:

```
iframeDoc.open("text/html", "replace");
iframeDoc.write(passbackTagHtml);
iframeDoc.close();
```

See this reference for more information:
[](http://www.w3schools.com/jsref/met_doc_open.asp)

Cheers,
Jasper

**Comment by mkendall07** [comment]
@jabal999 
What is the bad behavior you are seeing? Do you have sample code costed somewhere to look at?

**Comment by jabal999** [comment]
I can give you example code. You will have to host it yourself. I have tested this in Chrome, but the concept is generic. I see my w3schools link has been removed. Maybe this link will survive: http://stackoverflow.com/questions/27854494/are-document-open-and-document-close-necessary

`<html>
<head>
<script>
  var tagWidth = 300;
  var tagHeight = 250;

  var bids = [{
        bidder: 'appnexus',
        params: {
            placementId: '6901013'
        }
  }];
    
  var bidTimeOut = 1000;
  var passbackTagHtml = '<scr'+'ipt type="text/javascript">console.log("hello world!")</scr'+'ipt>';
</script>

<script type="text/javascript" src="//acdn.adnxs.com/prebid/static/0.7.0/prebid.js" async></script>

<script>
  var pbjs = pbjs || {};
  pbjs.que = pbjs.que || [];

  var doNotChange = 'doNotChange';

  pbjs.que.push(function() {
    var adUnits = [{
      code: doNotChange,
      sizes: [[tagWidth, tagHeight]],
      bids: bids
    }];

    pbjs.addAdUnits(adUnits);

    pbjs.requestBids({
      timeout: bidTimeOut,
      bidsBackHandler: function() {
        var iframe = document.getElementById('postbid_if');
        var iframeDoc = iframe.contentWindow.document;
        var params = pbjs.getAdserverTargetingForAdUnitCode(doNotChange);

        // If any bidders return any creatives, render the ad with the top bid.
        if (params && params['hb_adid']){
          pbjs.renderAd(iframeDoc, params['hb_adid']);
        } else {
          // If no bidder return any creatives, run passback.
          iframe.width = tagWidth;
          iframe.height = tagHeight;
          console.log(passbackTagHtml);
          //iframeDoc.open("text/html", "replace");
          iframeDoc.write(passbackTagHtml);
          //iframeDoc.close();
        }
      }
    });
  });
</script>
</head>

<body style="margin:0;padding:0">
<iframe id='postbid_if' FRAMEBORDER="0" SCROLLING="no" MARGINHEIGHT="0" MARGINWIDTH="0" TOPMARGIN="0" LEFTMARGIN="0" ALLOWTRANSPARENCY="true" WIDTH="0" HEIGHT="0"></iframe>
</body>

</html>`

**Comment by mkendall07** [comment]
@jabal999 
Ah yes, the iframe doesn't indicate that it is loaded if you don't invoke `close`. 

Please open a PR: https://github.com/prebid/prebid.github.io/blob/master/examples/postbid.html

**Comment by mkendall07** [comment]
Closing this here, as it should be tracked as a doc issue on the docs repo.
