### ISSUE TITLE
Can a bid-adapter write a data-object within the pbjs data object (or a standalone object)

### ISSUE THREAD

**Issue by AskRupert-DM** [prebid/Prebid.js#4098]
Had a question around bid-adapters.

Wanted to see if there was any guidelines or restrictions around adapters exposing a data object with request/response information available beyond the standard 'pbjs' data that's available.

Notably wanted to expose publisherId, auctionId and storedRequestId for example that can be exposed for other non-prebid analytic adapters to be able to use/reference within their analytics - would a bid adapter be allowed to write/create an object on page with such information (either as its own object or within the pbjs object that already gets written out/set on page).

**Comment by bretg** [comment]
Assigning to @mkendall07 - my take is that data general to the auction would be ok. The forbidden thing is for bid adapters to try to grab bids, parameters, etc from other adapters.
