### ISSUE TITLE
Errors in the prebid que are not reported 

### ISSUE THREAD

**Issue by JuanCaicedo** [prebid/Prebid.js#41]
If an error gets thrown inside of the prebid que, it does not get bubbled up, so it fails silently and makes debugging harder.

I can add some code examples about how to recreate this if it would be helpful.

**Comment by prebid** [comment]
Apologies that the docs are not clear enough. Please add `?pbjs_debug=true` to the page URL. Prebid.js will log warnings and helpful auction messages.
http://prebid.org/publisher-api.html#how-to-debug
