### ISSUE TITLE
Error in yieldmo adapter when synchronously executing code in html head

### ISSUE THREAD

**Issue by mhlm** [prebid/Prebid.js#4107]
When synchronously executing the code in html head, the DOM is not yet formed, therefore window.document.body will be null. Because of this, an error first appears in this line (https://github.com/prebid/Prebid.js/blob/20969809c65a2e8d6f16069432135f98386e4900/modules/yieldmoBidAdapter.js#L307
), and then in this (https://github.com/prebid/Prebid.js/blob/801f0fb3ad9b8891cced991bf35095db4c2084a7/modules/yieldmoBidAdapter.js#L312).

**Comment by elberdev** [comment]
@jaiminpanchal27 We're looking to revise this to create a safer fallback
