### ISSUE TITLE
Missing ucTagData.env

### ISSUE THREAD

**Issue by jakubkowalczyk-pl** [prebid/Prebid.js#4110]
## Description
I have created the creative in the google ad manager.
I don't know if something went wrong, but some properties of ucTagData object are empty.
I attached the screen from the website where the creative was rendered(for example "env" property is empty). Is it bug?

![2019-08-23 15_11_02-Window](https://user-images.githubusercontent.com/5808163/63596774-4a256900-c5bc-11e9-9a85-1f2e992fd672.png)

## Platform details
Windows 10, Google Chrome 76, Prebid.js 2.26.0

**Comment by bretg** [comment]
@jakubkowalczyk-pl  - e.g. the cacheHost, cachePath, and uuid fields will only be populated for video. Can we close this?
