### ISSUE TITLE
Rubicon video error

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#4121]
this error seems to have appeared since v 2.29.0:
ERROR: Got error from PBS Java openRTB: [object Object]

**Comment by bretg** [comment]
@spormeon - this is from the Rubicon adapter. We need either a page where this is happening or the ext.errors.rubicon from the response to prebid-server.rubiconproject.com/openrtb/auction

**Comment by spormeon** [comment]
this what you need?
{"id":"f12ae546-30c6-452a-91a7-1813e15cd37e","seatbid":[],"cur":"USD","nbr":2,"ext":{"debug":{"httpcalls":{"rubicon":[{"uri":"https://exapi-eu.rubiconproject.com/a/api/exchange.json?tk_sdc=eu","requestbody":"{\"id\":\"f12ae546-30c6-452a-91a7-1813e15cd37e\",\"imp\":[{\"id\":\"inreedvid5Slot\",\"video\":{\"mimes\":[\"video/x-flv\",\"video/mp4\",\"application/x-shockwave-flash\",\"application/javascript\",\"video/webm\"],\"minduration\":0,\"maxduration\":45,\"protocols\":[1,2,3,4,5,6,7,8,9,10],\"w\":550,\"h\":310,\"linearity\":1,\"skipmin\":0,\"skipafter\":0,\"playbackmethod\":[2],\"pos\":0,\"api\":[1,2,3,4,5,6],\"ext\":{\"rp\":{\"size_id\":203}}},\"secure\":0,\"exp\":300,\"ext\":{\"rp\":{\"zone_id\":896644,\"track\":{\"mint\":\"\",\"mint_version\":\"\"}}}}],\"site\":{\"domain\":\"golfwrx.com\",\"page\":\"http://adops.golfwrx.com/golfwrxarticlewedge-native.html\",\"publisher\":{\"ext\":{\"rp\":{\"account_id\":16924}}},\"content\":{\"language\":\"en\"},\"ext\":{\"rp\":{\"site_id\":151312},\"amp\":0}},\"device\":{\"ua\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36\",\"ip\":\"82.38.245.161\",\"ext\":{\"rp\":{}}},\"user\":{\"id\":\"JZY1B5P5-1X-GF6M\",\"buyeruid\":\"JZY1B5P5-1X-GF6M\",\"ext\":{\"consent\":\"BOmGlQrOmUeWUAKAZBENCj-AAAAqJ7_______9______9uz_Ov_v_f__33e8__9v_l_7_-___u_-33d4-_1vf99yfm1-7ftr3tp_87ues2_Xur__79__3z3_9phP78k89r7337Mw-v83og\"}},\"test\":1,\"at\":1,\"tmax\":1000,\"source\":{\"tid\":\"f12ae546-30c6-452a-91a7-1813e15cd37e\"},\"regs\":{\"ext\":{\"gdpr\":1}}}"}]},"resolvedrequest":{"id":"f12ae546-30c6-452a-91a7-1813e15cd37e","imp":[{"id":"inreedvid5Slot","video":{"mimes":["video/x-flv","video/mp4","application/x-shockwave-flash","application/javascript","video/webm"],"minduration":0,"maxduration":45,"protocols":[1,2,3,4,5,6,7,8,9,10],"w":550,"h":310,"linearity":1,"skipmin":0,"skipafter":0,"playbackmethod":[2],"pos":0,"api":[1,2,3,4,5,6]},"secure":0,"exp":300,"ext":{"rubicon":{"accountId":16924,"siteId":151312,"zoneId":896644,"video":{"language":"en","size_id":203}}}}],"site":{"domain":"golfwrx.com","page":"http://adops.golfwrx.com/golfwrxarticlewedge-native.html","content":{"language":"en"},"ext":{"amp":0}},"device":{"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36","ip":"82.38.245.161"},"user":{"id":"JZY1B5P5-1X-GF6M","ext":{"consent":"BOmGlQrOmUeWUAKAZBENCj-AAAAqJ7_______9______9uz_Ov_v_f__33e8__9v_l_7_-___u_-33d4-_1vf99yfm1-7ftr3tp_87ues2_Xur__79__3z3_9phP78k89r7337Mw-v83og"}},"test":1,"at":1,"tmax":1000,"cur":["USD"],"source":{"tid":"f12ae546-30c6-452a-91a7-1813e15cd37e"},"regs":{"ext":{"gdpr":1}},"ext":{"prebid":{"cache":{"vastxml":{"returnCreative":false}},"targeting":{"includewinners":true,"includebidderkeys":false,"pricegranularity":{"ranges":[{"precision":2,"min":0,"max":2,"increment":0.01},{"precision":2,"min":2.1,"max":20,"increment":0.1}]}}}}}},"errors":{"rubicon":[{"code":999,"message":"open circuit"}]},"responsetimemillis":{"rubicon":0},"tmaxrequest":1000}

**Comment by bretg** [comment]
So 8 days ago, Rubicon had performance problems that would have resulted in `open circuit` errors like this. Those errors should have subsided as capacity was added. Are you still receiving them?

In any case, that error message was pretty useless and shouldn't be at the error level. I've opened https://github.com/prebid/Prebid.js/pull/4157 to tune the Rubicon logged messages.

**Comment by spormeon** [comment]
Yep I was still seeing it today

**Comment by bretg** [comment]
Can you give me another URL where it's happening? adops.golfwrx.com is password protected.

**Comment by spormeon** [comment]
It's on my test bed which is password protected.

**Comment by bretg** [comment]
Please capture the JSON that's posted to the endpoint and paste it here?

**Comment by spormeon** [comment]
it seems to have gone today, although i did update to 2.30.0 yesterday if there was anything in there that could of fixed it?
p.s i'm in the UK

**Comment by spormeon** [comment]
oh, hang on its back, what bit do you need? what i put above but for today?

**Comment by bretg** [comment]
I'm looking for the request body.

1) bring up dev tools, search for a call to prebid-server.rubiconproject.com/openrtb2/auction
2) find the POST body
3) paste here

thanks

**Comment by spormeon** [comment]
enough, or need more of it?
{id: "9625f7b3-9a1a-497c-ae98-14d1ed2036e6", seatbid: [], cur: "USD", nbr: 2,…}
cur: "USD"
ext: {debug: {,…}, errors: {rubicon: [{code: 999, message: "open circuit"}]},…}
debug: {,…}
httpcalls: {rubicon: [{uri: "https://exapi-eu.rubiconproject.com/a/api/exchange.json?tk_sdc=eu",…}]}
rubicon: [{uri: "https://exapi-eu.rubiconproject.com/a/api/exchange.json?tk_sdc=eu",…}]
0: {uri: "https://exapi-eu.rubiconproject.com/a/api/exchange.json?tk_sdc=eu",…}
requestbody: "{"id":"9625f7b3-9a1a-497c-ae98-14d1ed2036e6","imp":[{"id":"inreedvid10Slot","video":{"mimes":["video/x-flv","video/mp4","application/x-shockwave-flash","application/javascript","video/webm"],"minduration":0,"maxduration":45,"protocols":[1,2,3,4,5,6,7,8,9,10],"w":300,"h":250,"linearity":1,"skipmin":0,"skipafter":0,"playbackmethod":[2],"pos":0,"api":[1,2,3,4,5,6],"ext":{"rp":{"size_id":203}}},"secure":0,"exp":300,"ext":{"rp":{"zone_id":896644,"track":{"mint":"","mint_version":""}}}}],"site":{"domain":"golfwrx.com","page":"http://adops.golfwrx.com/golfwrxarticlewedge-native.html","publisher":{"ext":{"rp":{"account_id":16924}}},"content":{"language":"en"},"ext":{"rp":{"site_id":151312},"amp":0}},"device":{"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36","ip":"82.38.245.161","ext":{"rp":{}}},"user":{"id":"JZY1B5P5-1X-GF6M","buyeruid":"JZY1B5P5-1X-GF6M","ext":{"consent":"BOmGlQrOmXYbvAKASBENCj-AAAAqJ7_______9______9uz_Ov_v_f__33e8__9v_l_7_-___u_-33d4-_1vf99yfm1-7ftr3tp_87ues2_Xur__79__3z3_9phP78k89r7337Mw-v83og"}},"test":1,"at":1,"tmax":1000,"source":{"tid":"9625f7b3-9a1a-497c-ae98-14d1ed2036e6"},"regs":{"ext":{"gdpr":1}}}"
uri: "https://exapi-eu.rubiconproject.com/a/api/exchange.json?tk_sdc=eu"
resolvedrequest: {id: "9625f7b3-9a1a-497c-ae98-14d1ed2036e6",…}
at: 1
cur: ["USD"]
0: "USD"
device: {,…}
ip: "82.38.245.161"
ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
ext: {prebid: {cache: {vastxml: {returnCreative: false}},…}}
prebid: {cache: {vastxml: {returnCreative: false}},…}
cache: {vastxml: {returnCreative: false}}
vastxml: {returnCreative: false}
returnCreative: false
targeting: {includewinners: true, includebidderkeys: false, pricegranularity: {,…}}
includebidderkeys: false
includewinners: true
pricegranularity: {,…}
ranges: [{precision: 2, min: 0, max: 2, increment: 0.01}, {precision: 2, min: 2.1, max: 20, increment: 0.1}]
0: {precision: 2, min: 0, max: 2, increment: 0.01}
increment: 0.01
max: 2
min: 0
precision: 2

**Comment by bretg** [comment]
That's the response -- looking for the request. Or the full response from the `resolvedrequest` attribute on down.

**Comment by spormeon** [comment]
try this one, that it?
{"id":"ff01ac3f-1b62-4ae5-bd19-2f47f3e98c00","test":1,"cur":["USD"],"source":{"tid":"ff01ac3f-1b62-4ae5-bd19-2f47f3e98c00"},"tmax":1000,"imp":[{"exp":300,"id":"inreedvid10Slot","secure":0,"ext":{"rubicon":{"accountId":16924,"siteId":151312,"zoneId":896644,"video":{"language":"en","size_id":203}}},"video":{"context":"outstream","playerSize":[[300,250]],"mimes":["video/x-flv","video/mp4","application/x-shockwave-flash","application/javascript","video/webm"],"playbackmethod":[2],"minduration":0,"maxduration":45,"protocols":[1,2,3,4,5,6,7,8,9,10],"linearity":1,"api":[1,2,3,4,5,6],"pos":0,"w":300,"h":250}}],"ext":{"prebid":{"cache":{"vastxml":{"returnCreative":false}},"targeting":{"includewinners":true,"includebidderkeys":false,"pricegranularity":{"ranges":[{"precision":2,"min":0,"max":2,"increment":0.01},{"precision":2,"min":2.1,"max":20,"increment":0.1}]}}}},"site":{"page":"http://adops.golfwrx.com/golfwrxarticlewedge-native.html","content":{"language":"en"}},"regs":{"ext":{"gdpr":1}},"user":{"ext":{"consent":"BOmGlQrOmXYbvAKASBENCj-AAAAqJ7_______9______9uz_Ov_v_f__33e8__9v_l_7_-___u_-33d4-_1vf99yfm1-7ftr3tp_87ues2_Xur__79__3z3_9phP78k89r7337Mw-v83og"}}}

**Comment by bretg** [comment]
I'm getting a Rubicon error status 16 out of that request:
```
                        "responsebody": "{\"id\":\"ff01ac3f-1b62-4ae5-bd19-2f47f3e98c00\",\"bidid\":\"3fc2ae50-ec1d-401c-a5b5-5255ee8dc31c\",\"seatbid\":[{\"bid\":[]}],\"nbr\":1,\"statuscode\":16}",
```
Status 16 means that your combination of account/site/zone/size isn't recognized:
```
                    "accountId": 16924,
                    "siteId": 151312,
                    "zoneId": 896644,
                    "sizeId": 203
```
I ran this several times and am not seeing the 'open circuit' error.

In any case, I agree that the Rubicon setup is incorrect here, but it isn't a Prebid issue. I've merged https://github.com/prebid/Prebid.js/pull/4157 to downgrade the javascript console error to a warning. I think you saw the 'open circuit' error last week when there were capacity challenges, but now you're seeing a general error that requires SSP support.

Please contact your Rubicon account team for the correct set of values to obtain outstream video ads.

(Yes, I work for Rubicon, but am not directly in a position to figure out the right values for you here. If your account team member doesn't jump on this, you can ping me in this thread again.)
