### ISSUE TITLE
Eplanning bid adapter will never return test bid.

### ISSUE THREAD

**Issue by GeneGenie** [prebid/Prebid.js#4132]
### Type of issue
Bug

### Description
Eplanning adapter has  "t" bid param which should return test bid from cdn in any case. 

### Steps to reproduce
Add two eplanning bids with params:   
{t:1}
and
{ci:"123"} 

### Expected results
adapter should return static sample response from http://i.e-planning.net/layers/t_pbjs_2.json
## Other information
[Function that checks that request isTest](https://github.com/prebid/Prebid.js/blob/master/modules/eplanningBidAdapter.js#L139) can only return true if test request is the last in array, COZ  forEach is used instead of reduce

**Comment by bretg** [comment]
@matimar , @Nistenf - can you help here?

**Comment by Nistenf** [comment]
Yep, that isTestRequest function looks wrong. I'll report it internally so we can fix it. Thanks for letting us know.

**Comment by Nistenf** [comment]
@bretg how important is this fix? We probably have a PR incoming (in about a month, month and a half) for our adapter and we could include this fix in it.

**Comment by bretg** [comment]
Medium priority
