### ISSUE TITLE
IdentityLink Id not syncing due to CORS error from Endpoint

### ISSUE THREAD

**Issue by pm-shashank-jain** [prebid/Prebid.js#4133]
## Type of issue
Bug

## Description
IdentityLink Id config is set in config but not synced due to CORS error from the api endpoint -> https://api.rlcdn.com/api/identity/envelope?pid=999

## Steps to reproduce
1. Include latest prebid
2. Set config for IdentityLink in pbjs.setConfig
3. Observe Network Pane/ console for CORS error in endpoint

## Test page
https://jsfiddle.net/shashankjain/w6bgehun/4

### Expected results
ID should be synced

### Actual results
Getting CORS error in console

## Platform details
Prebid version -> 2.30.0 (acdn.adnxs.com/prebid/not-for-prod/1/prebid.js)

## Other information
Guide followed from here -> http://prebid.org/dev-docs/modules/userId.html#identitylink

**Comment by bretg** [comment]
@mamatic - please take a look

**Comment by ian-lr** [comment]
Hi @pm-shashank-jain, 

Two questions for you:
- Are you using the pid "999" in the call? If so, we'll need to provide you with a live pid to work properly. 
- What geoIP are you calling us from? This will currently only return envelopes in the US and Canada. 

Thanks!

**Comment by pm-shashank-jain** [comment]
Hello @ian-lr ,
To answer your questions :
1. Yes I used pid 999. If this can not be used , can you please provide working Id for testing and validtion.
2. I've used geo of Both APAC and US and still getting the same error.

**Comment by ian-lr** [comment]
Thanks, @pm-shashank-jain. I'll create and send you a working pid for the configuration. Can you email me directly -- ian (at) liveramp.com ?

**Comment by pm-shashank-jain** [comment]
@ian-lr dropped you an email

**Comment by pm-shashank-jain** [comment]
Thanks @ian-lr for the help
Closing this issue as was able to get identityLink working after a valid pid, geo(US,Canada) and certain required cookies.
