### ISSUE TITLE
Remove BID_TARGETING_SET as criteria for a "used bid"

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#4148]
## Type of issue
I2I.

## Description
Currently we mark bids as used if they are rendered or set in an auction (`BID_TARGETING_SET`). This means that we will not be able to use a bid (aka, via bid caching) if it is not ultimately rendered in the 1st auction. [code link](https://github.com/prebid/Prebid.js/blob/master/src/targeting.js#L25)

This makes bid caching somewhat ineffective in most cases when bid caching is enabled. 

We will therefore remove the criteria of `BID_TARGETING_SET` from a used bid and the bid will only be marked as used if it has been rendered. 

Risks:
There is a slight risk of sending the same bid to the ad server multiple times if subsequent ad server calls are made repeatedly in a short period of time (such that the 1st ad call did not have time to renderer before the next ad call is made). 
Since this is a bad practice (to rapidly refresh ads) we think the risk is worth the tradeoff.

Open for comments.

**Comment by pm-harshad-mane** [comment]
Looking at the risk of rendering the same bid twice, can we add a logic to use a bid in one auction only at a given time, maybe something like ```bid.inUse = true``` flag.

**Comment by mkendall07** [comment]
>Looking at the risk of rendering the same bid twice, can we add a logic to use a bid in one auction only at a given time, maybe something like bid.inUse = true flag.

That is basically the same thing that `BID_TARGETING_SET` does. So the question becomes, when does the status change to `bid.inUse = false`  if we don't get a callback that the ad did not render?

**Comment by pm-harshad-mane** [comment]
Mostly after getting the bids from Prebid, a publisher would call the guaranteed server (say GAM).
If bid from Prebid is rendered then we can know that now we need to unset bid.inUse for other bids in a given auction.
But if a bid from Prebid is not rendered then we do not have a way to know when to unset bid.inUse.
To handle the above scenario, can we add a timeout based logic that assumes the max-time until which the bid will be rendered if it wins. We can keep this timeout fairly big like 3000ms and also let publisher configure it as some pubs may fetch bids from Prebid for lazy-loading ad-slots.

**Comment by madma** [comment]
> Since this is a bad practice (to rapidly refresh ads) we think the risk is worth the tradeoff.
Bad practice but seen quite often in production on publisher sites. Personally, I have seen as bad as 30sec refreshes / re-running of the auction. It would be nice to see support for observables so AJAX requests could be terminated. That or something like others suggested using `setTimeout` in order to effectively expire a bid if it has not been rendered within a certain amount of time .

**Comment by patmmccann** [comment]
pretty sure this is good to close, as it is now changed to rendered

**Comment by ChrisHuie** [comment]
Closing because changed to render #6020
