### ISSUE TITLE
PChain integration

### ISSUE THREAD

**Issue by benjaminclot** [prebid/Prebid.js#4159]
## Type of issue
Question

## Description
Is PChain integration planned? Along with [sellers.json](https://iabtechlab.com/wp-content/uploads/2019/07/Sellers.json_Final.pdf), PChain seems required by TTD and many SSPs.

**Comment by oscarmarimrf** [comment]
Any news about this? We'd need to integrate PChain too.
Thanks!

**Comment by j03w** [comment]
there is this https://github.com/prebid/Prebid.js/blob/master/modules/schain.js but only pubmatic and oneVideo supports it

**Comment by bretg** [comment]
My understanding is that TradeDesk prefers schain and will be converting any pchains they get into schain format.

Obviously Prebid would rather not build support for pchain if schain is going to be the preferred solution. 

If anyone has data to back up building out pchain, please share.

**Comment by bretg** [comment]
I'm with Rubicon Project -- our exchange will support schain in Q4. In the meantime, we're exploring options with TradeDesk: either we'll get an extension on the deadline for key supply or we'll reformat schain to pchain in our adapters so TradeDesk can convert it right back to schain.

**Comment by iantri** [comment]
Hello,

Centro's view is also that SupplyChain is optimal. While pchain similar in concept (and definitely an inspiration in building SupplyChain), there are various usability reasons why the SupplyChain spec more clearly addresses DSP needs. 

If the resulting pchain uses domains as advertising system identifiers (as opposed to TAG ID), then it's workable to convert on receipt of a bid request, but not ideal.  Reliable and straightforward identification of intermediaries really does depend on expressing advertising systems as domains.

**Comment by bretg** [comment]
Going to close this one out -- if anyone needs pchain, we'll review the PR for a new module.
