### ISSUE TITLE
Prebid v0.10.0 Release

### ISSUE THREAD

**Issue by protonate** [prebid/Prebid.js#416]
A release of a new version of Prebid is out. 

### v0.10.0 release notes
https://github.com/prebid/Prebid.js/releases/tag/0.10.0

### Test Procedures
Automated unit tests
Browserstack Karma tests for [these browsers](https://github.com/prebid/Prebid.js/blob/master/karma.conf.js#L27)
Manual smoke tests for each bidder adapter
Feature tests for these [examples](http://prebid.org/dev-docs/examples/basic-example.html)

### Test Results
Automated tests OK
Browserstack tests OK
Manual smoke tests OK (WideOrbit not bidding)
Feature tests OK

**Comment by chaqu170** [comment]
What happened to v0.10.0? I don't see the info any more (I was able to earlier today), and the link for https://github.com/prebid/Prebid.js/releases/tag/0.10.0 gives me a 404.

**Comment by mkendall07** [comment]
@chaqu170 
Sorry the tag got removed. It's back now.
