### ISSUE TITLE
I2I - remove `min` from priceGranularity

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#4171]
## Type of issue
I2I 

## Description
Currently the custom `priceGranularity` bucket object looks like this:
```
"precision": 2,  //default is 2 if omitted - means 2.1234 rounded to 2 decimal places = 2.12
      "min" : 0,
      "max" : 5,
      "increment" : 0.01  // from $0 to $5, 1-cent increments
```
This proposal would drop the `min` attribute - since this doesn't support any use cases and can be confusing and easy to mis-configure (such as a gap in the price buckets configured) The `min` value will be assumed as the previous bucket `max` - this is how PBS implements the feature (https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md#targeting)

**Comment by bretg** [comment]
Confirmed that PBS-Java ported the PBS-Go change that eliminated the 'min' attribute.

**Comment by mkendall07** [comment]
@bretg - cool. Does that mean we can go ahead with this change in PBJS?

**Comment by bretg** [comment]
yes

**Comment by ptomasroos** [comment]
This can be closed @bretg @mkendall07 ? ^

**Comment by mkendall07** [comment]
yep, thanks
