### ISSUE TITLE
Error on Creatives using safe frame

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#418]
The creative fails if the creative is setup in a safe frame:

![image](https://cloud.githubusercontent.com/assets/94527/16198511/d2a29dc6-36cb-11e6-930f-c9d6a0bdbb37.png)

This happened with a Publisher we were setting up recently, Google made it the default option we had to remove safe frame option from creatives to make it work. The problem is that the safe frame cannot access window.parent.pbjs.renderAd and it prevents the ads to render when the creatives load.

Seems that Google will push for safe frames everywhere. is support for safe-frames planned?

ref: https://support.google.com/dfp_sb/answer/6141925?hl=en

**Comment by mkendall07** [comment]
@ialex 
For now, we just recommend the publisher disable safeframe.

**Comment by alberteltawil** [comment]
Are there any plans to find a solution for Prebid.js to work within SafeFrames?
