### ISSUE TITLE
OpenX Adapter's video `openrtb` parameter doesn't behave as documented

### ISSUE THREAD

**Issue by DecayConstant** [prebid/Prebid.js#4186]
## Type of issue
Bug in OpenX Adapter or incorrect documentation about the video `openrtb` parameter.

## Description
The documentation for OpenX video bid requests (Here: https://docs.openx.com/Content/developers/containers/prebid-video-adapter.html and here: https://github.com/prebid/Prebid.js/blob/master/modules/openxBidAdapter.md ) indicates that the proper structure of the requests looks like this: 

```javascript
var videoAdUnit = {       
   code: 'video1',
   mediaTypes: {
      video : {
         playerSize: [640, 480],
         context: 'instream'
      }
   }, 
   bids: [{            
      bidder: 'openx',             
      params: {
         unit: '1611023124',
         delDomain: 'PUBLISHER-d.openx.net',
         openrtb:{
           imp: [{
             video: {
               mimes: ['video/x-ms-wmv, video/mp4']
            }
          }]
        }
      }                      
   }]     
};
```

However, this does not work.  Both the [OpenX Adapter code](https://github.com/prebid/Prebid.js/blob/master/modules/openxBidAdapter.js#L342)  and the the [OpenX tests](https://github.com/prebid/Prebid.js/blob/master/test/spec/modules/openxBidAdapter_spec.js#L1111) indicate this is the correct format: 

```javascript
params: {
     unit: '1611023124',
     delDomain: 'PUBLISHER-d.openx.net',
    // undocumented `video` object wraps `openrtb`
     video: {
       openrtb:{
         imp: [{
           video: {
             mimes: ['video/x-ms-wmv, video/mp4']
          }
        }]
      }
    }
} 
```

As a result, setting up `openrtb` according to the documentation does nothing. There also seems to be more undocumented behavior related to the contents of `video`.    So either the code needs to be updated to match the documentation, or the documentation needs to change to match the code. 

## Steps to reproduce
Try to use the `openrtb` parameter on an OpenX video bid request as documented.

**Comment by jimee02** [comment]
@DecayConstant, I've created a ticket to updated our docs page and have updated prebid and our adapter to match the code.

**Comment by jimee02** [comment]
@jsnellbaker, can we consider this issue closed?
