### ISSUE TITLE
[Feature] User Module should be able to get the top frame url

### ISSUE THREAD

**Issue by Swiiip** [prebid/Prebid.js#4211]
## Description
With the deprecation of the getTopFrameReferrer (https://github.com/prebid/Prebid.js/blob/master/src/utils.js#L249) function, we can no longer access the top frame url from within the User Module without reimplementing it. The top frame url is only accessible from within bid adapters through the bidderRequest.refererInfo parameter. It woud be interesting to expose an api in User Module to do it.

**Comment by jaiminpanchal27** [comment]
Closing this as we have a module for this https://github.com/prebid/Prebid.js/blob/master/src/refererDetection.js

We were talking with Criteo on Prebid.org Slack and they updated their code to use above module
