### ISSUE TITLE
Currency module error: Cannot read property 'cpm' of undefined

### ISSUE THREAD

**Issue by OG84** [prebid/Prebid.js#4214]
## Type of issue
Bug

## Description
We see the following error

```
ERROR: Error executing handler: events.js TypeError: Cannot read property 'cpm' of undefined
    at n.getCpmInNewCurrency
    ...
```

![image](https://user-images.githubusercontent.com/5689965/65246605-356ebf00-daef-11e9-8028-95cfe3123449.png)

We have a fingerprinted prebid js with following adapters:
```
[
  "appnexusBidAdapter",
  "criteoBidAdapter",
  "ixBidAdapter",
  "openxBidAdapter",
  "rubiconBidAdapter",
  "pubmaticBidAdapter",
  "consentManagement",
  "rubiconAnalyticsAdapter",
  "currency"
]
```

## Platform details
Prebid 2.23.0 / Chrome 76

## Other information
Could this be related to 

https://github.com/prebid/Prebid.js/pull/3845
or
https://github.com/prebid/Prebid.js/pull/3856
?

**Comment by jsnellbaker** [comment]
Hi @OG84 

Can you provide a copy of your prebid setup (or preferably a test-page/jsfiddle) that demonstrates the error so we can review?  Thanks.

**Comment by OG84** [comment]
Thx for the quick reply. I cannot reproduce it anymore with the latest version 2.32.0

So i guess i just close and reopen if necessary.
thx 👍
