### ISSUE TITLE
schain module breaks in IE11

### ISSUE THREAD

**Issue by DecayConstant** [prebid/Prebid.js#4237]
## Type of issue
Bug

## Description
The schain module uses `Object.values` which is not supported in IE11: https://github.com/prebid/Prebid.js/blob/master/modules/schain.js#L136

This crashes the prebid code when running in IE11.

## Steps to reproduce
Try to use the schain module in IE11.

**Comment by ehoch** [comment]
@pm-harshad-mane

**Comment by pm-harshad-mane** [comment]
Looking into it on priority 👍

**Comment by pm-harshad-mane** [comment]
Hello @ehoch and @DecayConstant ,
Code changes are merged to PrebidJS master.

**Comment by pm-harshad-mane** [comment]
Hello @DecayConstant ,

Can you please close the issue?
