### ISSUE TITLE
Changing globalVarName as an option during dowloading?

### ISSUE THREAD

**Issue by jianfai** [prebid/Prebid.js#4244]
Type of issue: 
Feature request

Description: 
As we run Prebid on publisher's website that also runs Prebid, we need to change the globalVarName from 'pbjs' to 'abc_pbjs' to avoid conflicting with Publisher's Prebid. We do this during compiling Prebid. 

Would it be possible to have this feature available as an option when downloading Prebid.js on http://prebid.org/download.html?

**Comment by mkendall07** [comment]
seems like a reasonable thing to do. We'll add it to the backlog.

**Comment by bretg** [comment]
This is low enough priority that we're probably not going to get to it anytime soon. The workaround is just to build from the command line and change the global in package.json.

If someone wants to help, the Download repo is https://github.com/prebid/prebid-js-build-generator, but this isn't a trivial change. It would require a fair amount of refactoring to rebuild the package with the new global and the user will have to wait for it long enough that email may be the better option. And cleanup would be a necessity.

**Comment by gglas** [comment]
@jianfai we've discussed, and because this can be accomplished post-download when it needs to be executed, we can't justify prioritizing the work.  If you'd be interested in joining prebid and working to deliver it, we'd be happy to work with you to help you implement the changes.
