### ISSUE TITLE
i2i: Unbundle PubCommon ID and Unified ID from the User ID module build

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#4252]
## Type of issue
I2I

## Description
Unbundle PubCommon ID and Unified ID from the User ID module build. That is, when building the with the userId module, PubCommon and Unified ID will not automatically be included in the prebid.js build

**Comment by harpere** [comment]
thoughts on standardizing the `userIds[].name` param naming format?  Currently some of the names end with `Id` and others don't, while all of the corresponding module names end with `IdSystem`.

**Comment by jsnellbaker** [comment]
This task has been completed.  It was included as part of the 3.0 release.
