### ISSUE TITLE
Bidding floors?

### ISSUE THREAD

**Issue by brondsem** [prebid/Prebid.js#426]
A few bidders (aol, sekindo) have parameters for a floor.  Is there a way to implement a floor in prebid itself, so it works with any bidder?  We have a request to set that up, but don't see a way to do it with prebid.  It would also have to consider each ad unit, so we could have different floors not just a single global one.

Thanks for any pointers for how this might be possible.

**Comment by mkendall07** [comment]
@brondsem 
Correct there is no feature in prebid that does this. Why not just implement the floor in the adserver? Just don't listen to bids coming in under the floor.

**Comment by brondsem** [comment]
With different floors in different situations, against thousands of line items, it starts to get complex, so we were just checking the options on the prebid side.  Thanks.

**Comment by mkendall07** [comment]
@brondsem 
You can always adjust bids yourself or manually set adserver targeting after getting the bid responses (omitting bids below the floor). I think we have several hooks were this could be done. 

Hopefully this helps

**Comment by mkendall07** [comment]
@brondsem 
Could you describe the feature your after? Would it just be a universal floor that is applied to all bidders?

**Comment by hereisethanhunt** [comment]
Hi, how can we set a bidfloor manually for bidders who doesnt support bidfloor ? Please tell me the function which does that. it would be really helpful.
