### ISSUE TITLE
emx_digital error in 2.34.0

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#4260]
hi,   this error has started appearing in prebid 2.34.0  any ideas what is wrong?

![DevTools_-_adops_golfwrx_com_ulrick_newsbreak_html](https://user-images.githubusercontent.com/8503167/66212413-c5973180-e6b5-11e9-85bb-b374351a0e58.png)

**Comment by EMXDigital** [comment]
Thanks for bringing this to our attention. We are investigating this ticket and will confirm when we have more information. It is our understanding this does not occur on every bid response, but for only certain small % of creatives. Thanks.

**Comment by spormeon** [comment]
ok, add to that , that some outstream ads seem to be loading and then only playing on float over, where as before they we're auto playing, with sound off in P2.34.0

**Comment by EMXDigital** [comment]
Can you share the pbjs request with video settings for the ad unit? Or a page we can look at? Our exchange listens for these values to determine if we should send back an auto play/click to play/etc video ad.

Thanks!

Nick Colletti || Senior Software Engineer ||
EMX Digital
T +1 646 868 7379 
M
