### ISSUE TITLE
ERROR: Sub-optimal JSON received from Quantcast server

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#4261]
as in the tilte, not sure if its anything to worry about/ how to fix it?
ERROR: Sub-optimal JSON received from Quantcast server

**Comment by bretg** [comment]
Adding @dpapworth-qc, @jacekburys-quantcast to comment

**Comment by dpapworth-qc** [comment]
@spormeon not sure what you mean by this. Could you provide an example response?

**Comment by spormeon** [comment]
its an error that console throws

**Comment by dpapworth-qc** [comment]
OK, I see that's a log message generated by our adapter, presumably because we're not sending any bid responses. We shouldn't be logging anything unless the response is an error. I will look at creating a PR for this. Thanks for flagging.

**Comment by spormeon** [comment]
ok, its in the errors not warnings,  think you had another one like this about a month back and was me that flagged it up then?

**Comment by dpapworth-qc** [comment]
i think so, i can see any reason why we would want to log an error when we return no bids - that's expected behaviour.
