### ISSUE TITLE
how to be a bid provider

### ISSUE THREAD

**Issue by jstocker76** [prebid/Prebid.js#427]
The company that employs me (as an engineer) has aspirations to add a bid provider to prebid that utilizes our ORTB ad exchange.  Is there some gate keeping process for this, or do I just code it up, check it in, and release the kraken?

**Comment by ialex** [comment]
@jstocker76 following the development i can say you can build the adapter for your company and make sure it works then send a PR for review hints:

* You will need to include your adapter in package.json
* Make sure your code is covered in tests
* Provide example of usage on integrationExamples folder
* Follow the JS code style
* Provide test parameters that return live bids

**Comment by mkendall07** [comment]
@ialex 
Good list, thanks. 
@jstocker76 
also take a look at http://prebid.org/dev-docs/bidder-adaptor.html and source code under adapters for examples.
