### ISSUE TITLE
Appnexus logging video media type requests as banner instead

### ISSUE THREAD

**Issue by arjitsachdeva** [prebid/Prebid.js#4279]
## Type of issue
Bug

## Description
I have set up only one mediaType = video in the prebid configuration, with context = instream. The problem is that most of the Impression requests are appearing as 'banner' media type on the Appnexus reporting panel instead of video.

## Steps to reproduce
This is the prebid code I have used:

`
      pbjs = pbjs || {};

      pbjs.removeAdUnit();

      pbjs.que = pbjs.que || [];
      var videoAdUnits = {
        code: "video1",
        mediaTypes: {
          video: {
            playerSize: [419, 236],
            context: "instream"
          }
        },
        bids: [
        {
          bidder: "oneVideo",
          params: {
            video: {
              playerWidth: 419,
              playerHeight: 236,
              mimes: ["video/mp4", "application/javascript"],
              protocols: [2, 5],
              floor: 2,
              api: [2],
              bidfloor: 2
            },
            pubId: "Test",
            bidfloor: 2
          }
        },
        {
          bidder: "rhythmone",
          params: {
            placementId: "82926"
          }
        },
        {
          bidder: "appnexus",
          params: {
            placementId: 15674944,
            video: {
              skippable: true,
              playback_method: ["auto_play_sound_off"]
            },
            reserve: 2
          }
        },
        {
          bidder: "districtm",
          params: {
            placementId: "16324023"
          }
        }
      ]
      };

      pbjs.que.push(function() {
        pbjs.aliasBidder("appnexus", "districtm");

        pbjs.addAdUnits(videoAdUnits);
        pbjs.setConfig({
          cache: {
            url: "https://prebid.adnxs.com/pbc/v1/cache"
          },
          userSync: {
            filterSettings: {
              iframe: {
                bidders: "*", // '*' represents all bidders
                filter: "include"
              }
            }
          },
          bidderTimeout: 3000,
          useBidCache: true
        });

        pbjs.requestBids({
          bidsBackHandler: function(bids, timedOut) {
            debugLog(bids);

            //Render the VAST tag from the highest bid
          }
        });
      });`

### Expected results
100% of the Impression requests on Appnexus panel should have been classified into the 'video' media type.

### Actual results
More than 60-70% of Impression requests are getting classified under 'banner' media type instead.

## Platform details
Prebid version: 2.34.0. Using the instream client side example via the latest video.js player.

**Comment by spormeon** [comment]
is you're appnexus placement setup for "video" or is it a sizeless by any chance and its thinking its a 419x236 banner?

**Comment by arjitsachdeva** [comment]
@spormeon : Appreciate the response. The media type in the placement has been setup as 'Standard VAST' (screenshot attached). Do you see any other anomalies here? 
<img width="824" alt="Screen Shot 2019-10-10 at 5 28 00 PM" src="https://user-images.githubusercontent.com/5327819/66566752-58870e80-eb83-11e9-97a9-b97301c537bf.png">

**Comment by spormeon** [comment]
can you screenshot all the tab, think there is about 4 of them?

**Comment by spormeon** [comment]
then fill the video tab in as required:
![Screenshot_2019-05-04_09_46_38_png](https://user-images.githubusercontent.com/8503167/66567685-aab63880-eb5f-11e9-88aa-3c24b1dbd0be.png)

**Comment by arjitsachdeva** [comment]
These are the screenshots of all the tabs in the settings panel:

<img width="1653" alt="Screen Shot 2019-10-10 at 5 42 01 PM" src="https://user-images.githubusercontent.com/5327819/66567778-8ff6ba80-eb85-11e9-98bc-beda0ef56eb4.png">
<img width="1652" alt="Screen Shot 2019-10-10 at 5 42 12 PM" src="https://user-images.githubusercontent.com/5327819/66567780-908f5100-eb85-11e9-8a50-dcca4d9a2ec9.png">
<img width="1654" alt="Screen Shot 2019-10-10 at 5 42 22 PM" src="https://user-images.githubusercontent.com/5327819/66567781-908f5100-eb85-11e9-8ca8-6a85b0f24f94.png">
<img width="1660" alt="Screen Shot 2019-10-10 at 5 42 29 PM" src="https://user-images.githubusercontent.com/5327819/66567784-9127e780-eb85-11e9-812d-d2ea64400541.png">
<img width="1653" alt="Screen Shot 2019-10-10 at 5 42 37 PM" src="https://user-images.githubusercontent.com/5327819/66567785-9127e780-eb85-11e9-9349-6eaa4c34c6f2.png">
<img width="1655" alt="Screen Shot 2019-10-10 at 5 42 44 PM" src="https://user-images.githubusercontent.com/5327819/66567787-9127e780-eb85-11e9-914a-9428bf35ea33.png">

**Comment by spormeon** [comment]
ye its video 4 i  think you need, i'd try like i put above, add them all basically and sizeless, then vast 2 click all the frameworks & all the mime types.  Get it going , then work back on turn stuff off dont need?

**Comment by spormeon** [comment]
if you got a Im , i.M. happy to chat on there through it? whattsapp or something?

**Comment by arjitsachdeva** [comment]
Got it. So it's something to do with the Appnexus dashboard settings in your opinion, right? The prebid code seems correct? 

Also, Skype would be great if you're on it! I'm at: sachdeva.arjit

**Comment by mkendall07** [comment]
hey @arjitsachdeva 
Please open a support ticket with AppNexus if you need more support.
