### ISSUE TITLE
DigiTrust Id submodule fails if site intializes outside the Prebid module

### ISSUE THREAD

**Issue by goosemanjack** [prebid/Prebid.js#4280]
## Type of issue
This is an unanticipated use case where a site has taken the DigiTrust Prebid integration, but has the older DigiTrust initialization code still in place. The site is using the Prebid integration, then explicitly calling DigiTrust.initialize instead of initializing with Prebid. That is outside our instructions and anticipated usage patterns. The mock DigiTrust object should be extended to stub the initialize method and potentially pass in the member and site Id values.

DigiTrust.initialize({member: "xxx",site: "yyy",redirects: true});

## Description
Missing "initialize" method from stub DigiTrust object.

## Steps to reproduce
Set up with Prebid DigiTrust integration, no independent library. Attempt to initialize DigiTrust outside the Prebid loader with DigiTrust.initialize(...)

## Test page
http://www.recipebridge.com/

### Expected results
No error, works

### Actual results
Exception in console DigiTrust.initialize is not a function

**Comment by bretg** [comment]
Are you planning on submitting a PR for this @goosemanjack

**Comment by goosemanjack** [comment]
Yes, I will be. I just needed a tracking issue to ensure it doesn't get lost. This is an edge case we didn't account for, but saw in the wild.

**Comment by goosemanjack** [comment]
Touching issue. There is a PR #4369 
https://github.com/prebid/Prebid.js/pull/4369
This is a minor, isolated change and should just require a quick review.

**Comment by goosemanjack** [comment]
touch prior to test update. Am traveling but will try to get code out.

**Comment by goosemanjack** [comment]
Touching issue. I'm just back from vacation and getting in the groove again. Will try to resolve everything prior to end of year.

**Comment by goosemanjack** [comment]
Need to round out mocks and see if unit test is practical
