### ISSUE TITLE
IE10 js error - prebit core

### ISSUE THREAD

**Issue by aasmyan87** [prebid/Prebid.js#4285]
there is an error in IE 10 version
https://www.screencast.com/t/ucG2MLI9
since USA users use IE a lot I think it does worth fixing

**Comment by bretg** [comment]
Please provide more info -- the screenshot shows amazon-adsystem.com, which isn't Prebid.js.

**Comment by pm-harshad-mane** [comment]
I suspect the issue with auction.js using a Set, https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L107
I think we can use Set as it is used in adpod module https://github.com/prebid/Prebid.js/blob/master/modules/adpod.js#L23

**Comment by pm-harshad-mane** [comment]
@aasmyan87 I do not have a machine with IE 10 so I couldn't test.
I have made change here https://github.com/pm-harshad-mane/Prebid.js/tree/set_fix
Diff is simple: https://github.com/prebid/Prebid.js/compare/master...pm-harshad-mane:set_fix
Can you verify on your end and let us know?

**Comment by bretg** [comment]
Thanks for looking into this @pm-harshad-mane, but how big is that library? I'm not fond of the idea of adding any bytes at all to support IE10:
- it's 7 years old
- it's under 0.5% of web traffic
- it's already end-of-life on all popular versions of Windows
- it will only be supported on its last versions of Windows (Server 2012 and Embedded 8 Standard) until Jan. 31, 2020

I think we need to let it rest in peace.

**Comment by pm-harshad-mane** [comment]
I agree with you @bretg .
If the shared code works then @aasmyan87 can copy those changes in his local environment.
Also, shall we remove the said library reference from https://github.com/prebid/Prebid.js/blob/master/modules/adpod.js#L23

**Comment by mkendall07** [comment]
@aasmyan87 
We no longer support ie 10, we are currently supporting modern browsers and IE 11. Thanks
