### ISSUE TITLE
Get prebid js adapter using js

### ISSUE THREAD

**Issue by throne1986** [prebid/Prebid.js#4302]
I have app in which I want user to add adapters via select options, and download the prebid js based on adapters he selected is it possible to apply this using JavaScript??

**Comment by pm-harshad-mane** [comment]
@throne1986 are you trying to build something like http://prebid.org/download.html ?
If yes, then you may refer to https://github.com/prebid/prebid-js-build-generator this is the Repo that powers download link.

**Comment by bretg** [comment]
The Prebid.org download page uses a server-side build script to combine desired modules. Doing it purely in-browser javascript may be possible, but may take some hacking and we can't promise we won't break it in the future. We recommend you use `gulp build` with our gulpfile.

**Comment by throne1986** [comment]
@pm yes exactly like the prebid.hs download, thank you I Will check it out
