### ISSUE TITLE
freewheel-ssp adapter - Update all end points to https

### ISSUE THREAD

**Issue by sumit116** [prebid/Prebid.js#4307]
## Type of issue

Improvement
## Description

While doing an internal review for point 2 of the adapter’s section of http://prebid.org/blog/pbjs-3, I observed something unusual in your adapter. I saw more endpoints than the usual bid endpoint and usersync endpoint. Can you clarify on that all these endpoints are needed and whether they can be updated to `https` protocol or may be you can make the updates yourself?

## Following change need to be addressed:
- All the endpoints or any other thrid party urls used by the adapter needs to be updated to secure (https).
## Platform details

Prebid 3.0
## Other information

http://prebid.org/blog/pbjs-3

**Comment by sumit116** [comment]
Hi @guillaume-sticky, can you check this issue?

**Comment by wx0122** [comment]
Hi @sumit116 , guillaume does not work in the company at all. In our current adapter, we support both HTTP and HTTPS. Do you mean we should only pass HTTPS urls?

**Comment by xwang202** [comment]
Hi @sumit116 , guillaume does not work in freewheel-ssp adapter anymore. In our current adapter, we support both HTTP and HTTPS. Do you mean we should only pass HTTPS urls?

**Comment by sumit116** [comment]
Hi @xwang202, Yes, as a part of work for the next release of prebid (3.0), we are updating all adapters to use only secure urls for all endpoints and any other urls used by them.

**Comment by pm-harshad-mane** [comment]
Hello @sumit116 ,
Looks like this issue has been addressed in https://github.com/prebid/Prebid.js/pull/4294 
Can we close this issue?

**Comment by sumit116** [comment]
Hi @pm-harshad-mane, thanks for the update. Closing it now.
