### ISSUE TITLE
quantcast adapter - Update all end points to https

### ISSUE THREAD

**Issue by sumit116** [prebid/Prebid.js#4308]
## Type of issue

Feature Request
## Description

While doing an internal review for point 2 of the adapter’s section of http://prebid.org/blog/pbjs-3, I observed something unusual in your adapter. I saw more endpoints (test url) than the usual bid endpoint and usersync endpoint. Can you clarify on that all these endpoints are needed and whether they can be updated to https protocol or may be you can make the updates yourself?
## Following change need to be addressed:
- All the endpoints or any other thrid party urls used by the adapter needs to be updated to secure (https).
## Platform details

Prebid 3.0
## Other information

http://prebid.org/blog/pbjs-3

**Comment by sumit116** [comment]
Hi @dpapworth-qc, can you check this issue?

**Comment by dpapworth-qc** [comment]
👍 i will investigate this and make a PR the changes required for pbjs-3.

**Comment by dpapworth-qc** [comment]
@sumit116 apologies for not looking at this. i am working on this now.

**Comment by dpapworth-qc** [comment]
@sumit116 added a PR, but the Rubicon merge (see #4449) is stopping all tests from executing.

**Comment by dpapworth-qc** [comment]
Merged master, should be good for review and merging.
