### ISSUE TITLE
outcon adapter - Update all end points to https

### ISSUE THREAD

**Issue by sumit116** [prebid/Prebid.js#4309]
## Type of issue

Improvement
## Description

While doing an internal review for point 2 of the adapter’s section of http://prebid.org/blog/pbjs-3, I observed something unusual in your adapter. I saw more endpoints than the usual bid endpoint and usersync endpoint. Can you clarify on that all these endpoints are needed and whether they can be updated to `https` protocol or may be you can make the updates yourself?

## Following change need to be addressed:
- All the endpoints or any other thrid party urls used by the adapter needs to be updated to secure (https).
## Platform details

Prebid 3.0
## Other information

http://prebid.org/blog/pbjs-3

**Comment by sumit116** [comment]
Hi @TinchoF , can you check this issue?

**Comment by pm-harshad-mane** [comment]
Hello @sumit116 ,

Can we close this issue?

**Comment by sumit116** [comment]
Verified in master branch, all endpoints are changed to secure in outconBidAdapter.js, hence closing this issue.
