### ISSUE TITLE
zedo adapter - Update all end points to https

### ISSUE THREAD

**Issue by sumit116** [prebid/Prebid.js#4310]
## Type of issue

Improvement
## Description

While doing an internal review for point 2 of the adapter’s section of http://prebid.org/blog/pbjs-3, I observed something unusual in your adapter. I saw secure and non-secure urls used for all endpoints and no protocol (http or https) is prefixed with the urls. Can you clarify on that all these endpoints are needed and whether they can be updated to `https` protocol or may be you can make the updates yourself?

## Following change needs to be addressed:
- All the endpoints or any other thrid party urls used by the adapter needs to be updated to secure (https).
## Platform details

Prebid 3.0
## Other information

http://prebid.org/blog/pbjs-3

**Comment by sumit116** [comment]
Hi @skazedo , can you check this issue?

**Comment by skazedo** [comment]
@sumit116  - I have submitted a pull request for this. Can you check it. Thanks

**Comment by sumit116** [comment]
> @sumit116 - I have submitted a pull request for this. Can you check it. Thanks

Hi @skazedo, sorry I missed to read your comment. Can you share the PR link here?

**Comment by skazedo** [comment]
Here is the pull request - https://github.com/prebid/Prebid.js/pull/4395. It has been merged to master.
