### ISSUE TITLE
setting custom Key Value via adapter even if no bid exists 

### ISSUE THREAD

**Issue by AskRupert-DM** [prebid/Prebid.js#4313]
I had a question regarding bid-adapters setting (custom) key-value pairs/ad-server targeting when no bid is returned ?

A publisher recently asked if we could set a kvp to tell them when a bid was not returned for instance due to invalid traffic as well as timeout information as key-value pairs so wanted to see if this would be allowed as typically keys are only sent when a valid bid response exists ? (Which would also raise a question whether this is even technically possible if were allowed)

**Comment by bretg** [comment]
The right way to solve the publisher's desire for reporting is for them to use an analytics module. See http://prebid.org/overview/analytics.html. Smaller pubs may be able to use a free Google Analytics account which would provide some nice reports covering no-bids, timeouts, response times, etc. http://prebid.org/overview/ga-analytics.html. Mid-size and larger pubs have a range of interesting analytics choices from various vendors in the Prebid ecosystem.

**Comment by AskRupert-DM** [comment]
that makes sense thanks  - happy to close this

**Comment by AskRupert-DM** [comment]
Sorry - reopening this as I have a further question. As an SSP we want to provide publishers with a status code for no bid - eg: no inventory match, no bid due to IVT (Invalid/bot traffic), invalid stored request, etc, etc - what/where would we return this information from PBS for analytics adapters to pick this up ? 

Otherwise thought was we'd just return a ext object with the status code/reason and pass that back  as a KVP via the adapter (assuming that will be technically possible).
