### ISSUE TITLE
Ad targeting values lost, when an array is used

### ISSUE THREAD

**Issue by brondsem** [prebid/Prebid.js#432]
When targeting is set to an array, e.g.:
`.setTargeting('tpc', ['snare', 'monitoring', 'sysadministration', 'system', 'networking', 'security'])`

Then the `scp` param in the GPT pubads call should be like:
`tpc=snare,monitoring,sysadministration,system,networking,security&...`

But when prebid is used, only the last value is there:
`tpc=security&...`

**Comment by mkendall07** [comment]
Thanks for the report. We'll check it out

**Comment by mkendall07** [comment]
I think the approach to clearing each slot is a little heavy handed. We will revert back to the original approach of setting keys to empty strings.

**Comment by tabro** [comment]
Any news on this one?

**Comment by mkendall07** [comment]
Testing the fix here: https://github.com/prebid/Prebid.js/pull/446 once confirmed it will be merged to master.

**Comment by mkendall07** [comment]
This is merged to master.
