### ISSUE TITLE
Adding topRTB adapter in Prebid.org

### ISSUE THREAD

**Issue by topRTB** [prebid/Prebid.js#4326]
Hi,
  Our adapter topRTB has not been listed in http://prebid.org/download.html. But added in Prebid.js  
  Could you please tell us what we have to do to add the adapter in http://prebid.org/download.html.

**Comment by bretg** [comment]
You need to submit a docs PR to create a file similar to https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/aardvark.md

This was mentioned (briefly) at http://prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter
