### ISSUE TITLE
Ablida Bid Adapter

### ISSUE THREAD

**Issue by bokos** [prebid/Prebid.js#4330]
## Type of issue
Question, feature request

## Description
Hello,
sorry to be a bother. I was asked to open an issue regarding my pull request. It hasn't been reviewed yet after 14 days. Can you give an estimate when I can expect some progress?

## Other information
PR: https://github.com/prebid/Prebid.js/pull/4256

**Comment by bretg** [comment]
Sorry for the delay. The PR has been re-assigned.
