### ISSUE TITLE
custom analytics

### ISSUE THREAD

**Issue by yehosef** [prebid/Prebid.js#434]
I would like to pass the analytics to my own logging platform for monitoring - but it seems I have to use Google Analytics, which I don't want to do.

Would it be possible to have a custom callback to take the report of partners, bids, times, etc. and handle myself?

**Comment by matthewlane** [comment]
Yes, this will be possible once #297 is merged

**Comment by mkendall07** [comment]
@yehosef 
There are some examples in master now on how to do this, see https://github.com/prebid/Prebid.js/blob/master/src/adapters/analytics/example2.js

**Comment by yehosef** [comment]
Thanks!
