### ISSUE TITLE
how to set up with Vue/React SPA/PWA ?

### ISSUE THREAD

**Issue by vesper8** [prebid/Prebid.js#4342]
It's been asked before how to set this up with a single-page-application or progressive-web-app built with popular frameworks such as React, Angular or Vue.. but the issue was either ignored and closed by the stale bot or with some promising replies that were never followed up on.. these questions are very old in any case.. with all that's changed since.. is it now possible to use this feasibly and easily with such setups? Would appreciate some feedback from anyone that's succeeded.. Thank you

**Comment by terrapop** [comment]
Similar problem problem here:

https://github.com/prebid/Prebid.js/issues/5712

**Comment by harpere** [comment]
For React applications there's this: 
https://www.npmjs.com/package/react-prebid
https://github.com/eBayClassifiedsGroup/react-advertising#readme
