### ISSUE TITLE
Feature: Support position parameter in adUnit 

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#4349]
## Type of issue
Feature request

## Description
Many bidders support the ```position``` parameter in ORTB 2.5 format.
The position is a piece of valuable information. 
We can pass this in adUnit object, a common-place for all bidders,  http://prebid.org/dev-docs/adunit-reference.html#adunit
It can be made a mandatory parameter considering the importance of the information.

**Comment by bretg** [comment]
Option 1) consider position a piece of adunit-specific first party data. Pubs would set `adunit.context.position` and adapters would read from that conventional location.

Option 2) position is important enough that it should be standalone. Pubs would set `adunit.position` and adapters would read from that conventional location.

In either case, the values are 'atf' or 'btf'. If unknown, nothing should be provided. 

Thoughts?

**Comment by pm-harshad-mane** [comment]
Hello @bretg ,
Sorry for the late reply.
Option #2 sounds good to me

**Comment by bretg** [comment]
Based on the OpenRTB spec, there's an argument to be made that it makes sense to ask for `pos` in AdUnit.mediatypes.banner.pos.

@mkendall07 ?
