### ISSUE TITLE
gulp commands don't run under Node 4.x after last release

### ISSUE THREAD

**Issue by mhipszki** [prebid/Prebid.js#437]
with the last change https://github.com/prebid/Prebid.js/commit/e1224866815814198535786961f18e219f66ac90 the gulp commands are not running anymore as the ES6 spread operator has been used in `gulpfile.js`

e.g.
```javascript
gulp.task('devpack', function () {
  webpackConfig.devtool = 'source-map';
  return gulp.src([...helpers.getAnalyticsSources(analyticsDirectory), 'src/prebid.js'])
    .pipe(webpack(webpackConfig))
    .pipe(replace('$prebid.version$', prebid.version))
    .pipe(gulp.dest('build/dev'))
    .pipe(connect.reload());
});
```

the README says you need at least *Node 4.x*, however the spread op is only supported from 5.x upwards, see http://node.green/#spread-------operator

should the docs be updated to say e.g. *Node 4.x with the `--harmony` flag or 5.x* ?

**Comment by matthewlane** [comment]
Thanks reporting this @mhipszki. I'll get a fix in
