### ISSUE TITLE
update addEventListener in secureCreatives.js to window.addEventListener

### ISSUE THREAD

**Issue by vkimcm** [prebid/Prebid.js#4371]
## Description
addEventListener in listenMessagesFromCreative function in secureCreatives.js might need to be changed to window.addEventListener.  We had some issues where request_ad messages from safeframe creatives where not being received, causing big discrepancies, and this update fixed the issue. (especially with connatix javascript)

**Comment by bretg** [comment]
@vkimcm - I would suggest going ahead and making a code PR for this.
