### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://tpc.googlesyndication.com') does not match the recipient window's origin

### ISSUE THREAD

**Issue by eyang414** [prebid/Prebid.js#4381]
## Type of issue
Bug

## Description
It looks like prebid.bidWon() event is trying to fire, but throws this error when trying to run _sendAdToCreative(), which has a source.postMessage() function.  
![image](https://user-images.githubusercontent.com/22535690/67594657-d5dd8200-f732-11e9-88b4-b68fb4390a53.png)

Line 64: 
[https://github.com/prebid/Prebid.js/blob/a1ccdf0f6d390dcddc595e4e9d7492ec7b377944/src/secureCreatives.js](url)

I have noticed that the 'source' is sometimes set as _Window_, which then causes the error.  This _Window_ variable is definitely linked to GPT as it contains the code written inside the GPT Creative code snippets. ([https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/x-domain/creative.html](url))
renderAd()
requestAdFromPrebid()
listenAdFromPrebid()
all seen within the _Window_ variable
![image](https://user-images.githubusercontent.com/22535690/67595139-eb06e080-f733-11e9-91ca-6cba6670bd87.png)

**When the 'source' is set to _global_, there is NO error.
![image](https://user-images.githubusercontent.com/22535690/67595169-fe19b080-f733-11e9-8351-69d3b0541800.png)

So far I have only noticed this issue with our 300x600 display slot, which can also serve 160x600 and 300x250.  I wonder if there is something with this variable slot size that can cause this issue.  

Does the prebid team have any idea what might be causing this issue? Why might the event 'source' sometimes be _global_ and other times _Window_?
### Expected results
Prebid ad renders
### Actual results
No ad renders. The postMessage error is thrown.
## Platform details
Prebid version: 2.27.0
Windows Google Chrome

## Other important information
This could be linked to [https://github.com/prebid/Prebid.js/issues/4371](url)

**Comment by doctornick42** [comment]
@eyang414 Hello! Could you please share your solution? We kinda found a way to make it work on a test sample by passing `window.location.origin` implicitly too, but I'm still not sure that our solution won't bring any troubles in some specific cases in the future. By the way, do you use prebid-universal-creative?
