### ISSUE TITLE
districtmdmx adapter - ensure adapter returns secure inventory only

### ISSUE THREAD

**Issue by sumit116** [prebid/Prebid.js#4398]
## Type of issue
bug

## Description
Adapter passes `secure` field in request payload based on which adapter server might return insecure inventory if the field is set to `false`. So we should assign only `true` to
`obj.secure = window.location.protocol === 'https:' ? 1 : 0;` in districtmDMXBidAdapter.js.

## Platform details
Prebid-3.0

## Other information
https://github.com/prebid/Prebid.js/pull/4294#issuecomment-547558981

**Comment by jaiminpanchal27** [comment]
@stevealliance Can you review

**Comment by stevealliance** [comment]
Ok I will open a PR can I send this to the current version of prebid? ... I believe you will use the same version since it will be compatible?

Thanks

**Comment by stevealliance** [comment]
PR #4406 was closed and that update https was inforced!
@jaiminpanchal27  please closed this one
