### ISSUE TITLE
Bug in mediaTypePriceGranularity for outstream video

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#4399]
## Type of issue
Bug

## Description
[mediaTypePriceGranularity](http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-MediaType-Price-Granularity) is a feature added a while back to support the scenario where pubs want to have different sets of line items for banner and for video.

The logic implemented is simple:
- if the bid is mediaType banner, use the priceGranularity defined for banner.
- if the bid is mediaType video, use the priceGranularity defined for video.

Obvious right?

Wrong.

Turns out that outstream-video is really more like banner, even though the mediaType is video:
1) it generally uses banner line items
2) it uses the Prebid Universal Creative like banner

## Steps to reproduce
Set up an outstream test page with mediaTypePriceGranularity config

### Expected results

outstream bids use banner granularity

### Actual results

outstream bids use video granularity

## Possible Solutions

We discussed this in the Prebid.js PMC and need to discuss the right solution:

1) consider this a bug and fix it in 2.x: user banner pricegranularity when video.context=outstream
2) consider this a bug but wait for 3.0
3) add config to let the publisher decide how to handle it. 
    3a) `setConfig({mediaTypePriceGranularity: { outstreamUsesBanner: true }});`
    3b) `setConfig({mediaTypePriceGranularity: { video-outstream: "medium" }});`

**Comment by jaiminpanchal27** [comment]
Another approach can be to add context to video
```
pbjs.setConfig({'mediaTypePriceGranularity': {
    'video': {
      'outstream': customConfig,
      'instream': customConfig1,
      'adpod': customConfig2,
    },
    'banner': 'medium',
    'native': 'medium'
  }
});
```

**Comment by bretg** [comment]
I like the general idea of this suggestion @jaiminpanchal27 , except would prefer not to make a breaking change. Even if we found a way for the code to properly distinguish between mediaTypePriceGranularity.video-as-a-customGranularity and mediaTypePriceGranularity.video-as-an-object-of-granularities, I think it could be confusing for pubs.

Another option is:
```
pbjs.setConfig({'mediaTypePriceGranularity': {
    'video': customConfig,
    'video-outstream': customConfig1,
    'banner': 'medium',
    'native': 'medium'
  }
});
```
When PBJS core goes to determine the granularity for a video bid, it would first look for an entry in mediaTypePriceGranularity.video-CONTEXT. If that's not there, then it would fall back to mediaTypePriceGranularity.video.

This would allow pubs to decide how outstream line items are handled.

One problem is that Prebid Server would not be able to follow this pattern because it currently doesn't know whether a video bid is outstream or whatever. But that's a bigger problem and we can solve the mediaTypePriceGranularity sub-problem when we solve the bigger one.

**Comment by bretg** [comment]
This is still in progress, but is behind CCPA.
