### ISSUE TITLE
Prevent Duplicate Alias User Syncs

### ISSUE THREAD

**Issue by r-schweitzer** [prebid/Prebid.js#4408]
## Type of issue
Bugfix

## Description
Prebid currently registers and limits userSync calls based on the bidder name. When Aliases are used, this causes duplicate sync requests as the sync URL is the same as in the original adapter. 

## Proposed Solution
This fix will instead look at how many times the URL is used instead of how many times a bidder name was used in determining how to limit syncs.

https://github.com/prebid/Prebid.js/pull/4435

**Comment by bretg** [comment]
Closing this issue -- will track the issue with the PR #4435
