### ISSUE TITLE
Bug: AudienceNetwork (api change) bid responses not consistently matching to correct bid requests

### ISSUE THREAD

**Issue by andyblackwell** [prebid/Prebid.js#4415]
## Type of issue
Bug

## Description
If more than one placement id is sent in a request, the adapter no longer consistently matches the responses back to the correct bid request. I think there must have been an api change at some point to trigger this, I believe the api used to respond in with the bids in the same order they were sent, but that is no longer the case. And I'm not 100% sure, but I also think that no bids used to be included in the response so that the ordering was kept in tact, but they aren't included at the moment. No idea when their endpoint changed though.

The adapter will need some refactoring to rectify. Currently uses the hacky technique of storing data via bid request indexes, and matching up a response based on its response index, which no longer works.

I dug into it when I noticed a 300x250 banner placement was being rendered as native, and a couple other occurrences of mismatched formats/sizes.

## Steps to reproduce
\- make a call for multiple ads and audienceNetwork placement ids, sizes, and formats. (troubleshooting will be sporadic depending on how they bid)
\- you can use the dev flag to get test bids: `?anhb_testmode=1` (think you still need to be logged into facebook for these to work)
\- you'll have to manually verify, or step through the code to watch as mismatches happen

### Expected results
no criss-crossing of formats/sizes between bids that were requested in the same api call

### Actual results
criss-crossing of formats/sizes between bids that were requested in the same api call

## Platform details
I'm on 2.18, but nothing has changed in the adapter to have fixed this since that verion

**Comment by andyblackwell** [comment]
here's a diff of the changes I made to fix this you could use as a starting point: https://www.diffchecker.com/8fGOSoem

**Comment by bretg** [comment]
Adding @lovell

**Comment by lovell** [comment]
Thank you for reporting this Andy, I expect to update the AudienceNetwork adapter at some point within the next few weeks to address it.

**Comment by andyblackwell** [comment]
Can we get a bug label on this one too, to prevent stale bot from auto-closing?

**Comment by patmmccann** [comment]
AN deprecated, should we close?

**Comment by andyblackwell** [comment]
bah! this comment is how I found out they're shutting it down, so sad 😞 😢 
thanks facebook...
