### ISSUE TITLE
Safeframe resize fix doe not select correct element

### ISSUE THREAD

**Issue by vkimcm** [prebid/Prebid.js#4418]
## Type of issue
bug

## Description
https://github.com/prebid/Prebid.js/pull/3988

There were still issues with above fix, our footer was not getting resized because footer div was not the last element of the parent, rather close button element is.  We need different solution that does not use last-child css.

**Comment by andyblackwell** [comment]
In case you happen to use a custom build and also use GAM like us, we changed the selectors to this, which works better for us:
`['div[id^="google_ads_iframe"]', 'iframe[id^="google_ads_iframe"]']`
