### ISSUE TITLE
Support for Deals in other adapters?

### ISSUE THREAD

**Issue by tr-coull** [prebid/Prebid.js#444]
We are interested in using Deals with Pubmatic and other bidders which are not listed here as ones whose adapters support Deals (TripleLift, AppNexus, bRealTime). Is it a case of arranging the deals with the bidders directly and updating the current adapters to support reading the Deal id returned and setting it in the bid object created by the adapter?

Additional question: it seems that the bidder will know when they want to respond with the id of a deal we've arranged with them, with no extra info being sent in the bid request - so any code handling the bid response picks up there's a deal id and acts accordingly from then on?

**Comment by mkendall07** [comment]
@tr-coull 
>s it a case of arranging the deals with the bidders directly and updating the current adapters to support reading the Deal id returned and setting it in the bid object created by the adapter?
Yes that's correct. If you do work on integrations for dealId, please submit a PR for the adapters your working with so it will be in the framework. 

The 2nd question I believe depends on the bidder, however, must should not require any additional params.

**Comment by tr-coull** [comment]
Great thanks. It appears that with most bidders, our account with them will be updated to support the deals made so no additional params are required, but the possible values for existing ones will be expanded to include deals. For example, with Pubmatic, I believe they will give us a new set of values to use as 'adSlot' in their bid request when working with deals - i think!

It's still early days but if we get Deals working with any of the adapters which don't currently support them, we'll make a PR so hopefully others can use it.
