### ISSUE TITLE
rubiconBidAdapter_spec.js is using describe.only, stopping other tests from running

### ISSUE THREAD

**Issue by dpapworth-qc** [prebid/Prebid.js#4449]
## Type of issue

Bug

## Description

The Rubicon adapter tests are using describe.only in one of the tests. (See https://github.com/prebid/Prebid.js/blob/master/test/spec/modules/rubiconBidAdapter_spec.js#L2314). This appears to stop all other tests from running. Once this is removed, all tests are run, but some of the Rubicon tests are failing.

## Steps to reproduce

Run 'gulp test':

> $ gulp test
[16:40:03] Using gulpfile ~/dev/local/Prebid.js/gulpfile.js
...
> 
> Finished in 0.034 secs / 0.002 secs @ 16:40:57 GMT+0000 (GMT)
> 
> SUMMARY:
✔ 5 tests completed
[16:40:57] Finished 'test' after 34 s
[16:40:57] Finished 'test' after 54 s

(Note, only 5 tests are run)

Removing the .only shows that some of the Rubicon tests are failing.

> $ gulp test
[16:43:22] Using gulpfile ~/dev/local/Prebid.js/gulpfile.js
...
>
> Finished in 4.832 secs / 2.511 secs @ 16:44:20 GMT+0000 (GMT)
>
> SUMMARY:
>✔ 4648 tests completed
>ℹ 4 tests skipped
>✖ 6 tests failed
>
>FAILED TESTS:
>  the rubicon adapter
>    buildRequests implementation
...

@tjeastmond this looks related to the changes you merged recently.

**Comment by harpere** [comment]
closing.  this should be fixed now.
