### ISSUE TITLE
Which major browsers are supported?

### ISSUE THREAD

**Issue by chaqu170** [prebid/Prebid.js#445]
Hi, 

I'm just wondering if anyone knows which major browsers are supported? Specifically, I was curious about IE and Edge, but I'd be interested in all the other browsers in general.

Thanks!

**Comment by mkendall07** [comment]
@chaqu170 
We support IE 8+ and latest version of modern browsers on Windows and Mac. I don't believe we have any test cases for Edge browser currently.

**Comment by protonate** [comment]
The BrowserStack configuration in `./karma.conf` runs tests in IE 13 (Edge) on Windows 10: https://github.com/prebid/Prebid.js/blob/master/karma.conf.js#L28 and this section lists the other browser and OS configurations to test and support.
