### ISSUE TITLE
Aliasing Rubicon adapter does not work for video bidding

### ISSUE THREAD

**Issue by mgriego** [prebid/Prebid.js#4453]
## Type of issue
Bug

## Description
Aliasing the Rubicon adapter when performing video auctions using the new PBS/OpenRTB endpoint fails due to the adapter forcing the `bidderCode` back to `rubicon`.

## Steps to reproduce
Alias the Rubicon adapter, ie `pbjs.aliasBidder('rubicon', 'rubiconAlias');`
Run a video bid with the `rubiconAlias` bidderCode.

### Expected results
Bids are returned and handled using the `rubiconAlias` bidderCode.

### Actual results
Bids are assigned to the built in `rubicon` bidder code.

## Platform details
Prebid 2.39

## Other information
`bidderCode` is being forced here:
https://github.com/prebid/Prebid.js/blob/master/modules/rubiconBidAdapter.js#L551

**Comment by mgriego** [comment]
@robertrmartinez Can you tell me if it's strictly necessary to set the `bidderCode` to the `seat` value of the response?  Or can we safely do this?:
```
bidderCode: bidRequest.bidderCode
```

**Comment by robertrmartinez** [comment]
Hi Michael!

Thanks for bringing this to our attention. Let me go over it with our team
here and make the appropriate changes ASAP.

**Comment by robertrmartinez** [comment]
Sorry for this we have the fix ready though!

https://github.com/prebid/Prebid.js/pull/4460

**Comment by mgriego** [comment]
Awesome!
