### ISSUE TITLE
OpenX endpoint not compressing responses

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#4466]
## Type of issue

Performance

## Description

A publisher pointed out that OpenX's endpoint isn't sending responses compressed, as evidenced by lack of a `Content-Encoding` header.

## Steps to reproduce

Call an OpenX endpoint through a compression tester like https://www.whatsmyip.org/http-compression-test

```
https://ziffdavis-d.openx.net/w/1.0/arj?ju=https%3A%2F%2Fmashable.com%2Fcategory%2Fsocial-good%2F&jr=&ch=UTF-8&res=412x732x24&ifr=false&tz=300&tws=412x660&be=1&bc=hb_pb_2.1.9&dddid=e33cb352-952d-4b52-b429-26aabb893df7&nocache=1573484913419&gdpr_consent=BObzkKNObzkt0ASABAENCF-AAAAkF7_______9______9uz_Ov_v_f__33e8__9v_l_7_-___u_-33d4-_1vf99yfm1-7ftr3tp_87ues2_Xur__59__3z3_tphLgA&gdpr=0&aus=300x250&divIds=gpt-ad-8&auid=540870103&
```

### Expected results

Response comes back compressed.

### Actual results

Not compressed.

**Comment by bretg** [comment]
@jimee02 or @lambdarho - is this something you guys could escalate within OpenX?

**Comment by lambdarho** [comment]
Hi @bretg, 

We are looking into this.  At first glance, we seemed to remember it used to be there, but will find out.

**Comment by bretg** [comment]
@lambdarho - any status on this? Also, please take note of https://github.com/prebid/Prebid.js/pull/4485 -- would like to make sure that you approve of openxoutstream being removed. The relationship between yieldmo and openx isn't clear.

**Comment by jimee02** [comment]
@bretg, Thanks for letting me know.  I'm ok with openxoutstream being removed.  I'm still have an open ticket to get our api to compress our responses.

**Comment by kkharma** [comment]
we pushed a fix to compress responses, so this should be resolved now.  i confirmed via the steps to reproduce listed above.
