### ISSUE TITLE
AOL bidder placementCode param in wrong place?

### ISSUE THREAD

**Issue by thomaslsimpson** [prebid/Prebid.js#447]
in src/adapters/aol.js, on line 89, the placementCode is being pulled from the bid directly:
```
bidmanager.addBidResponse(bid.placementCode, bidResponse);
```
should this not be from the **params** in the bid like:
```
bidmanager.addBidResponse(bid.params.placementCode, bidResponse);
```
... or am I just confused?

**Comment by mkendall07** [comment]
@thomaslsimpson 
`bid.placementCode` is correct, as this is a param that is automatically added to the `bid` object. The data inside `bid.params` is custom to each bidder. Hopefully that clarifies.
