### ISSUE TITLE
native erros with safeframe i think

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#4473]
I'm getting errors all the time when native ads win, the ads display correctly etc but it always throws these sort of errors, anything to worry about/ can be fixed?

![DevTools_-_adops_golfwrx_com_newsbreak-requirejs_html](https://user-images.githubusercontent.com/8503167/68992792-4b3aff00-0868-11ea-9a11-409ad3415e68.png)

**Comment by jaiminpanchal27** [comment]
@spormeon Can you share a jsfiddle or steps to reproduce the errors

**Comment by spormeon** [comment]
@jaiminpanchal27   do you have an I.M' er i can contact you on, i can give you login to my test bed , where it is?

**Comment by spormeon** [comment]
not stale, @jaiminpanchal27 was going to try and replicate this on local machine as spoke to him on a chat elsewhere, didn't hear anything back?

**Comment by spormeon** [comment]
still not stale
