### ISSUE TITLE
Feature: reduce network requests by dropping bidders

### ISSUE THREAD

**Issue by orzilca** [prebid/Prebid.js#4474]
## Type of issue
Feature Request

## Description
Auctions create lots of network requests.
Not all bidders respond throughout a user session, mainly because they:
- capped the user impressions
- not interested in this user

Such bidders can be dropped from the auction in order to reduce amount network requests and auction page load.

Ex:
Auction with 5 bidders: b1, b2, b3, b4, b5
Pageview 1 -> b1 won an impression
Pageview 2 -> b1 won an impression
Pageview 3 -> b1 did not bid
Pageview 5 -> b1 did not bid
Pageview 5 -> b1 did not bid
in the next bid request, b1 will be dropped and only b2-b5 will be auctioned.

This is based on the assumption that if a bidder hasn't responded for X auctions, he will not respond to any auction after X+1 also.

X should be configurable via setConfig()

**Comment by bretg** [comment]
This is an interesting optimization, but Prebid.js doesn't have state across page views. Cookies and localstorage are considered potential privacy issues. 

I think this could be done using the "pre-auction" hook described in https://github.com/prebid/Prebid.js/issues/4149. Publishers willing to store their own state can build a set of functions that store state and alter the auction with any algorithm they choose.

**Comment by patmmccann** [comment]
This seems relevant to some ssp's and not others, eg a retargeting ssp. We don't have a way of differentiating those in core right now, only publishers do, so I think this should be outside of core.

**Comment by orzilca** [comment]
I think its more of a publisher call rather than the SSP.

As a publisher, I can decide if I want to auction a certain bidder.
Auctioning bidders that consistently do not bid on a user throughout a session is waste of resources and might actually harm the entire page performance, especially on slow network or devices with weak performances.

Also - I believe that reducing unnecessary requests to SSPs can improve their ROI on the publisher (requests costs money) - so there's a mutual benefit here..

Another way to tackle this maybe is for me to handle the logic by myself somehow and just to hook into pre-auction as @bretg suggested.. interesting idea.

**Comment by bretg** [comment]
Ok - will assume that a pre-auction filter will work as a solution here. PR https://github.com/prebid/Prebid.js/pull/4539 should be merged in a release or two.
