### ISSUE TITLE
.setTargetingForGPTAsync setting incorrect targets when using same adUnitPath

### ISSUE THREAD

**Issue by Xoben** [prebid/Prebid.js#448]
We use the same adUnitPath for one page and use targeting for the different ad spots 

2 ads are defined with the same adUnitPath

googletag.defineSlot('/0000/slm.townhall/home', [[728,90],[970,90],[970,250]], 'div-gpt-728x90_1').addService(googletag.pubads())**.setTargeting('pos', '728x90_1');**

googletag.defineSlot('/0000/slm.townhall/home', [[300,250]], 'div-gpt-300x250_1').addService(googletag.pubads())**.setTargeting('pos', '300x250_1');**

when calling .setTargetingForGPTAsync because the adUnitPath is the same it attempts to reset each ad with an array of adUnitPaths

Attempting to set key value for slot: div-gpt-728x90_1 key: pos value: 728x90_1
Attempting to set key value for slot: div-gpt-728x90_1 key: pos value: 300x250_1

Attempting to set key value for slot: div-gpt-300x250_1 key: pos value: 728x90_1
Attempting to set key value for slot: div-gpt-300x250_1 key: pos value: 300x250_1

Is there a way around this problem....

**Comment by mkendall07** [comment]
@Xoben 
Thanks for reporting the issue. I believe this will be resolved when https://github.com/prebid/Prebid.js/pull/446 is merged.

**Comment by Xoben** [comment]
I just pulled down that code and looks like it fixed the problem.  Ty sir
