### ISSUE TITLE
Prebid Brightcove plugin behavior when no ads are available

### ISSUE THREAD

**Issue by Engywook2005** [prebid/Prebid.js#4481]
## Type of issue
Bug

## Description
I am working on a project integrating prebid with BCVideo_PrebidVastPlugin (as described here: http://prebid.org/dev-docs/plugins/bc/bc-prebid-plugin-integration-studio.html). 

The main issue: If I set options.dfpParameters.params.iu to an id which has not yet been approved by our demand partners, the content video plays behind an opaque div element. I'm reaching out to Brightcove as well; that said I have not encountered this issue outside of using BCVideo_PrebidVastPlugin. 

Questions below are part of my own attempt to troubleshoot.

* Is the github repo for this plugin https://github.com/prebid/prebid-js-plugin-brightcove? 
* In the options object (passed to renderAd) I specify a prebidPath of //s3.amazonaws.com/media.pgmcdn.com/AdTech/_common/IronWrapper/prebid/2.38.0/prebid.js. I see that loading, but I also see http://acdn.adnxs.com/prebid/not-for-prod/1/prebid.js (the default) loading. Is there something I'm overlooking that I need to do to narrow the field down to 1 prebid.js?
* window.pbjs is coming up undefined. If I need to access pbjs, how can I do that with this plugin?
* The player I'm working with is set to not autoplay. As far as I am able to tell, though, the BCVideo_PrebidVastPlugin is telling the player to play the content video before renderAd. Am I correct about this, and if so is there a way to prevent BCVideo_PrebidVastPlugin from calling player.play?
* Does BCVideo_PrebidVastPlugin dispatch an events so we can respond to, for example, all bids complete?
* I am attempting to pass dfpParamaters.cust_params and am not seeing my key value pairs on the ad calls.

If I'm not posting this in the proper forum, please let me know where I should take this.

## Steps to reproduce
1. Run the plugin in Brightcove with an iu that is not recognized by demand partners

## Test page
I am working on getting one together, but will need to resolve the issue with cust_params to be able to demonstrate the issue.

### Expected results
No ad plays, preroll plays visibly.

### Actual results
No ad plays, entire video plays underneath opaque element.

## Platform details
Observed with: 
Prebid 2.36.0
Mac OS
Chrome

**Comment by graphicdeveloper** [comment]
Hi, @Engywook2005 - Thanks for bringing this to our attention! I'm one of the devs who's done work on the prebid plugin. We've started looking at your scenario and will update you as we learn more. Two quick requests off the top:

1) Can you please re-post everything you you shared above in a new issue over in the actual plugin repo? That's a better place for it. >> https://github.com/prebid/prebid-js-plugin-brightcove

2) When you create your new ticket, can you also add a comment with your exact plugin options JSON? That will help us reproduce your setup exactly for debugging purposes.

Thanks!

**Comment by Engywook2005** [comment]
@graphicdeveloper done. New issue is https://github.com/prebid/prebid-js-plugin-brightcove/issues/139. Should I close this issue?

**Comment by ynisman** [comment]
Yes, close this issue. We will track it now using prebid/prebid-js-plugin-brightcove#139.
Thank you.

**Comment by graphicdeveloper** [comment]
Yes, as my esteemed colleague said, please do close this issue. Thanks, @Engywook2005! :-)
