### ISSUE TITLE
Prebid-Communication with the JWPlayer

### ISSUE THREAD

**Issue by phtechno** [prebid/Prebid.js#4484]
Hi everybody,

we updated the prebid-libary on our pages a few days ago.
From v2.26.0 to v2.35.0

Since this update our JWPlayer communicates directly to Prebid to play "Prerolls".

Is there any possibility to disable this feature?

The problem is we need a request to our adserver before we use prebid-bids. The new feature has the result that our adserver will be only requestet if there is no prebid-bid.

Regards
Stephan

**Comment by bretg** [comment]
@phtechno - this isn't an explicit prebid feature. It is up to the player to decide when to call the ad server, not Prebid.js. Please work with your JWPlayer contact to narrow down what's happening here.
