### ISSUE TITLE
Appnexus requires schain object to be under 'ext'

### ISSUE THREAD

**Issue by arjitsachdeva** [prebid/Prebid.js#4487]
## Type of issue
Our Appnexus AM informed us that the schain object needs to be under the 'ext' key as per how their system works currently. However, the prebid documentation is sending the 'schain' object at the bidder request key level. 

I'm not sure if this would require a change in the Appnexus adapter itself which is out of our scope or is there a way in prebid to send the schain object under the 'ext' key instead?

## Platform details

Prebid 2.40

**Comment by bretg** [comment]
@jaiminpanchal27 - the appnexus adapter is passing schain to your endpoint at the root level. The suggestion here is that this is supposed to be under `ext.schain`?

```
    const payload = {
      tags: [...tags],
      user: userObj,
      sdk: {
        source: SOURCE,
        version: '$prebid.version$'
      },
      schain: schain
    };
```

**Comment by jaiminpanchal27** [comment]
@arjitsachdeva Let me check with my colleagues and get back to you.

**Comment by arjitsachdeva** [comment]
Sure thing, @jaiminpanchal27 ! Appreciate it.
