### ISSUE TITLE
Add Units Tests to the Framework

### ISSUE THREAD

**Issue by prebid** [prebid/Prebid.js#45]

**Comment by johngeorgewright** [comment]
:+1: Any thoughts on how you intend on doing this?

We've been looking to possibly move our code base on to a framework like this and we've been keeping a close eye on Prebid.js. However, I'm going to find it hard to keep this project a contender until I can prove that it will work and continue to work :bug: free as more people start maintaining it. A high percentage of test coverage will help dramatically.

**Comment by hjeong12** [comment]
@johngeorgewright  Hi John, I'm working on this using Karma.

**Comment by prebid** [comment]
@johngeorgewright: We're committed to keeping the code base bug free and well maintained. Since the codebase now is stable and almost feature complete, we're switching effort to writing unit tests. Would like to periodically check with you to see how comfortable you're with the test coverage.

**Comment by protonate** [comment]
PR #174 adds support for Karma and Istanbul for running tests and generating reports, and tests will be added soon to bring up coverage to reliable levels.

**Comment by protonate** [comment]
Closing as we now have test coverage in place and will be continuing to add additional tests going forward.
