### ISSUE TITLE
Outstream video support when player is embedded in the response

### ISSUE THREAD

**Issue by tadam75** [prebid/Prebid.js#4503]
## Type of issue
Feature request

## Description
Following the discussion with @jsnellbaker on this PR : https://github.com/prebid/Prebid.js/pull/4367

We would like a way to fit in your outstream video integration, when the ad-markup that we respond contains the player and the content, and can't be separated.

## Test page
It's hard to have a fiddle working on this topic.
But I have created a branch (**issue/outstream**) on our repository, so that you can test it :
https://github.com/smartadserver/Prebid.js/tree/issue/outstream
I changed the outstream.html test and replaced the video ad unit by the Smart one, and changed in the googletag defineSlot function, "prebid_outstream_adunit_1" by "header-bid-tag-0".

If you build&run the code, and go to http://localhost:9999/test/pages/outstream.html , you should see the outstream video ad playing, but "as a banner".

**Comment by bretg** [comment]
This is also related to https://github.com/prebid/Prebid.js/issues/4312
I've asked the video taskforce to deliberate.
