### ISSUE TITLE
Exceeded rate limit for sending hits - google Analytics

### ISSUE THREAD

**Issue by webdeveloperpr** [prebid/Prebid.js#4505]
## Type of issue
Question

## Description

I'm using the google analytics prebid adapter and after sending the 20th event I start getting this message.

> Exceeded rate limit for sending hits 

I'm using the google analytics debugger to see all the events going out.
https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna This is how I can see the message.

I looked up the message and it seems like ga only allows sending a max of 20 hits. After that you have to wait some time until ga can start sending events again.

The documentation confirms that sending 20 events is the max limit.

reference: https://developers.google.com/analytics/devguides/collection/analyticsjs/limits-quotas#analyticsjs

So the question is, is there a way to somehow Queue up the events and slowly fire them to prevent hitting this 20 hits cap? 

Has anyone ran into this issue and found a solution?

## Steps to reproduce
Use the googleAnalytics adapter .
Download the google analytics debugger: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna

### Expected results
All events make it successfully to ga.

### Actual results
Some events make it successfully to ga.

## Platform details
prebid.js browser

**Comment by bretg** [comment]
Sorry, but analytics events are all separate - spread across users, browsers, machines. There's no global mechanism to throttle Prebid so GA is happy.

The solution is to either upgrade to the paid GA or find another analytics provider. http://prebid.org/overview/analytics.html
