### ISSUE TITLE
broken link on website and some wrong font names

### ISSUE THREAD

**Issue by usta** [prebid/Prebid.js#4510]
I have hit a couple more 404s so I made a full scan  ( instead of opening new issue entries for each of them) 

Status    ----	URL	 -----    Source link text
400 Bad Request	http://fonts.googleapis.com/css?family=Open+Sans+Condensed	link/href
404 Not Found	https://www.nexstardigital.com/ad-serving-and-management/	LKQD Ad Serving and Management [302 from http://www.lkqd.com/ad-serving-and-management/]
404 Not Found	https://app.mopub.com/account/register/	MoPub.com
404 Not Found	https://www.pubwise.io/pubwise	Website [301 from https://pubwise.io/pubwise/]
404 Not Found	https://www.vuble.tv/us/prebid/	Website [301 from https://vuble.tv/us/prebid/]
404 Not Found	https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Mobile In-App Consent APIs v1.0 Draft for Public Comment.md	IAB GDPR recommendations
404 Not Found	https://www.adup-tech.com/en	www.adup-tech.com [301 from http://www.adup-tech.com/en]
400 Bad Request	https://fonts.googleapis.com/css?family=R	link/href
404 Not Found	https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent string and vendor list formats v1.1 Final.html	Vendor Consent String
404 Not Found	http://prebid.org/assets/images/favicon.png	link/href
404 Not Found	http://prebid.org/assets/images/apple-touch-icon.png	link/href
404 Not Found	http://prebid.org/prebid-mobile/code-integration-ios.html	Android code integration
404 Not Found	http://prebid.org/prebid-mobile/code-integration-android.html	iOS code integration
404 Not Found	http://prebid.org/examples/multi_format_example.html	Multi-Format Example
404 Not Found	http://prebid.org/dev-docs/dev-docs/modules/currency.html	Currency module
404 Not Found	http://prebid.org/examples/pbjs_demo.html?pbjs_debug=true	/pbjs_demo.html?pbjs_debug=true
404 Not Found	http://prebid.org/examples/native/	Prebid.org Native Examples
404 Not Found	http://prebid.org/dev-docs/contact@adagio.io	contact@adagio.io
404 Not Found	http://prebid.org/examples/bidders/sonobi-video-example.html	Sonobi Video
404 Not Found	http://prebid.org/dev-docs/{{site.baseurl}}/dev-docs/adunit-reference.html	The adUnit banner documentation
404 Not Found	http://prebid.org/dev-docs/{{site.baseurl}}/dev-docs/getting-started.html	Getting Started for Developers
404 Not Found	http://prebid.org/dev-docs/{{site.baseurl}}/dev-docs/bidders/bidders.html	tremor
404 Not Found	http://prebid.org/examples/native/native-demo.html	Prebid Native Example
404 Not Found	http://prebid.org/examples/native	Prebid Native Examples
404 Not Found	http://prebid.org/prebid-mobile/gdpr.html	Prebid Mobile Guide to European Ad Inventory and Providing Notice, Transparency and Choice
404 Not Found	http://prebid.org/prebid-mobile/pbm-api/ios/pbm-bannerad-ios.html	Banner Ad Unit
404 Not Found	http://prebid.org/prebid-mobile/pbm-api/ios/pbm-interstitial-ad-ios.html	Interstitial Ad Unit
404 Not Found	http://prebid.org/prebid-mobile/pbm-api/ios/pbm-api-ios.html	Prebid Mobile API - iOS
404 Not Found	http://prebid.org/prebid-mobile/pbm-api/ios/pbm-targeting-params-ios	first party data section of the Targeting
404 Not Found	http://prebid.org/prebid-mobile/pbm-api/android/banneradunit-android.html	Banner Ad Unit
404 Not Found	http://prebid.org/prebid-mobile/pbm-api/android/interstitialadunit-android.html	Interstitial Ad Unit
404 Not Found	http://prebid.org/prebid-mobile/pbm-api/android/adunit-android.html	Ad Unit
404 Not Found	http://prebid.org/prebid-mobile/pbm-api/ios/pbm-api-android.html	Prebid Mobile API - android
404 Not Found	http://prebid.org/prebid-mobile/code-integration-android	Coding Integration for Android
404 Not Found	http://prebid.org/adops/ads.google.com/home/tools/manager-accounts/	Google
404 Not Found	http://prebid.org/adops/support.google.com/admanager/answer/6222493?hl=en	Google support:
404 Not Found	http://prebid.org/adops/ https://support.google.com/admanager/answer/1711021?hl=en	Video Solutions advertising overview:
404 Not Found	http://prebid.org/dev-docs/dev-docs/publisher-api-reference.html	priceGranularity
404 Not Found	http://prebid.org/examples/video/outstream/outstream-dfp.html	Outstream with Google Ad Manager
404 Not Found	http://prebid.org/examples/video/outstream/outstream-no-adserver.html	Outstream without an Ad Server
404 Not Found	http://prebid.org/prebid-server/developers/configuration.md	Configuration
404 Not Found	http://prebid.org/config/config.go	config/config.go
404 Not Found	http://prebid.org/analytics/core.go	analytics/core.go
404 Not Found	http://prebid.org/analytics/config/config.go	analytics/config/config.go
404 Not Found	http://prebid.org/analytics/filesystem	filesystem
404 Not Found	http://prebid.org/prebid-server/developers/stored-request.md	stored request docs
404 Not Found	http://prebid.org/stored_requests/backends	Other backends
404 Not Found	http://prebid.org/prebid-server/developers/contributing.md	contribute it
404 Not Found	http://prebid.org/static/bidder-params	here
404 Not Found	http://prebid.org/prebid-server/developers/configuration.html	configure
404 Not Found	http://prebid.org/examples/pbjs_demo.html	Prebid sample ad
404 Not Found	http://prebid.org/modules/userId.html	userId module
404 Not Found	http://prebid.org/examples/modules/pub_common_id_optout.html	example

**Comment by GLStephen** [comment]
Please submit this to the website repo? https://github.com/prebid/prebid.github.io
