### ISSUE TITLE
33accross is not working through PBS

### ISSUE THREAD

**Issue by alejandrofcarrera** [prebid/Prebid.js#4559]
## Type of issue
Bug about bidder

## Description
Regarding with another [issue](https://github.com/prebid/prebid-server/issues/1117) we have seen at the end of the testing that 33accross is throwing an exception when we enable it. I saw this another [issue](https://github.com/prebid/Prebid.js/issues/4035) that it was closed automatically and might be the same issue but now there is a live example to test it.

## Steps to reproduce
Open the provided link and check the console.

## Test page
https://ebook.education.investing.com/pbs/33accross.html?pbjs_debug=true

### Expected results
No exceptions.

### Actual results
ERROR: TypeError: Cannot read property 'bidId' of undefined

## Platform details
Prebid.js v2.43.0
Prebid Server adapter + 33accross configuration.

## Other information
This [website](https://ebook.education.investing.com/pbs/33accross.html) is working well.

**Comment by bretg** [comment]
I sent email to the Prebid Server adapter maintainer alias for 33across. Also, maybe @thomas-33across can route this request?

**Comment by thomas-33across** [comment]
Hello @bretg we will look into the issue, thank you

**Comment by thomas-33across** [comment]
Hello @alejandrofcarrera can you give me the stack trace of the error? since the test page is minified version of prebid.js, it's hard to do debug there.  Thank you

**Comment by alejandrofcarrera** [comment]
Yes. Even better, i unminified the pbjs bundle, so you can see it on (console) the above link.

Anyway, this is the trace:
```
ERROR: TypeError: Cannot read property 'bidId' of undefined
    at fill_server_issue.html?pbjs_debug=true:7838
    at Array.forEach (<anonymous>)
    at fill_server_issue.html?pbjs_debug=true:7794
    at Array.forEach (<anonymous>)
    at Object.interpretResponse (fill_server_issue.html?pbjs_debug=true:7793)
    at fill_server_issue.html?pbjs_debug=true:7898
    at Object.success (fill_server_issue.html?pbjs_debug=true:7915)
    at XMLHttpRequest.onreadystatechange (fill_server_issue.html?pbjs_debug=true:3061)
```

**Comment by thomas-33across** [comment]
@alejandrofcarrera Thank you for unminified the bundle, and provide the trace.  The issue is not related to Prebid, but more of how our exchange handle the test bid case.  when our exchange see the `test:1` in the request, we will randomly generate a `impid` to short circuit the test process.  But this issue will not happen in Porduction.  we will create an internal ticket to fix the issue on our end.  Thank you

**Comment by alejandrofcarrera** [comment]
Dear @thomas-33across i didn't know anything about "test cases". We are using a real production configuration for this website in order to have the full-stack running. This parameter `is_debug=true` in PBS dictionary settings is doing this ? I thought this field was for enabling the debug log, but no to request test bids to the adapters. Can you provide more info ? Thanks.

**Comment by alejandrofcarrera** [comment]
I can say, this URL without any field like `debug` is working with 33accross adapter. https://remnant.s3.eu-west-3.amazonaws.com/prebid/fill_server_no_debug.html Can you check on your side if you are getting the good request ? Thanks @thomas-33across 👍

**Comment by alejandrofcarrera** [comment]
I can say, this URL without any field like `debug` is working with 33accross adapter. https://remnant.s3.eu-west-3.amazonaws.com/prebid/fill_server_no_debug.html Can you check on your side if you are getting the good request ? 

Also, can you send me an email with your corporate address to talk privately about user_sync with 33accross? > alejandro.f@investing.com

Thanks @thomas-33across 👍

**Comment by alejandrofcarrera** [comment]
btw @thomas-33across, why when i am adding [pbjs_debug=true](https://ebook.education.investing.com/pbs/33accross.html?pbjs_debug=true) you are returning a test case ? in theory this query param is to enable debug logs on pbjs client side and no more.

**Comment by bretg** [comment]
This gets into a pending feature within Prebid Server and the PrebidServerBidAdapter.

https://github.com/prebid/prebid-server/issues/745

Prebid Server Java currently supports two different flags on the request:
- test:1 -- this is the openrtb standard `test` flag, which is defined as being not-billable. it causes extra debugging info, but is also passed through to bidders who might react differently to test requests.
- ext.prebid.debug:1 -- this is a new softer option that adds the debug info to the response, but does not pass the 'non-billable test' flag through the adapters.

Once the Go version of Prebid Server supports ext.prebid.debug, we will have a decision to make about how PBJS should handle ?pbjs_debug=true.

**Comment by thomas-33across** [comment]
@alejandrofcarrera you can send an email to headerbidding@33across.com to initiate the discussion.  Thank you

**Comment by alejandrofcarrera** [comment]
Understood @bretg what do you suggest ? Use the Java version or keep using the Go version, because i don't know if there is any way to enable debug mode on the server without sending this kind of flags, would be great.

I think we can close the issue when @thomas-33across fixes on their side the sending of unhandled parameters when test:1 is sent throught PBS.

**Comment by bretg** [comment]
Adding @SyntaxNode to prioritize for PBS-Go in 2020.
