### ISSUE TITLE
Post-Bid Tag won't connect to Rubicon

### ISSUE THREAD

**Issue by digitalthrottle** [prebid/Prebid.js#457]
I can't seem to get the Post-Bid tag to connect to Rubicon. The passback works fine, so that's good. I'm connected to Fastlane and Rubicon Support has confirmed the site and zone are in good standing.

Anyone have luck with Post-Bid with Rubicon? Here is the latest try at settings:
(I've tried using single quotes and double quotes - still no ping to Rubicon)

```
<html>
<head>
<script>
  // Define the creative's size here:
  var tagWidth = 728;
  var tagHeight = 90;

  // Add your bids of the defined size for this ad unit here:
  var bids = {
      bidder: 'rubicon',
      params: {
         accountId: "10912",
		 siteId: "25904",
		 zoneId: "141306",
                 sizes: [2],
}
    };
```

**Comment by bretg** [comment]
Will get time next week to look at this -- haven't set up post-bid before. In the meantime, do you see any requests going out to to optimized-by.rubiconproject.com? If so, please post.

**Comment by bretg** [comment]
Used the Postbid example at http://prebid.org/dev-docs/examples/postbid.html and modified in JSFiddle to include your parameters -- works for me. Couple of possible problems with the javascript you provided above: 1) var bids should be an array 2) extra trailing comma after the sizes parameter.  #1 may the problem. If not, please post the full Post-bid tag you're using.

**Comment by digitalthrottle** [comment]
Fixed it!

Thanks so much.

Bryan Robb
President
Digital Throttle, LLC
[DigitalThrottleEmailLogo_R]
bryan.robb@digitalthrottle.com<mailto:bryan.robb@digitalthrottle.com> | www.digitalthrottle.com<http://www.digitalthrottle.com/>
Office (949) 713-0944 x101 | Cell (949) 683-6550 | Fax (949) 544-0465
30200 Rancho Viejo Road, Suite H | San Juan Capistrano, CA 92675

About Us
We sell online advertising through hundreds of independent automotive, racing, boating & powersports sites.

**Comment by bretg** [comment]
Glad to hear.
