### ISSUE TITLE
Prebid Adurl

### ISSUE THREAD

**Issue by yogeshadsparc** [prebid/Prebid.js#458]
Hi Guys,

I wanted to know can we use script tag as adurl in prebid ?
e.g . **adUrl: "<script src="http://xyz.com/ttj?id=75523&cb=[CACHEBUSTER]" TYPE="text/javascript"></script>"**.

If yes then there is any way in prebid to handle this type of tags ?

**Comment by mkendall07** [comment]
@yogeshadsparc 
Currently we don't support this type of ad, however, you could make it work by building a snippet of code that executes the URL. 

For example:
```
bid.ad = '<script src="' + scriptUrl + '"></scr' + 'ipt>';
```

**Comment by yogeshadsparc** [comment]
@mkendall07 
Thank you so much.
It's working like a charm.
