### ISSUE TITLE
Generic RTB payload support

### ISSUE THREAD

**Issue by itaynave** [prebid/Prebid.js#4586]
## Type of issue
feature request

## Description
Most adapters use RTB payload and in params they use RTB structure.
As such, it would be great if there will be a function that automatically validates and create the 
generic RTB payload that adapters can use.
Adapters that will want to use it will just add their extensions into the payload 
It can reduce the adapters size significantly and since this will be a shared code all bugs and best practices for creating an RTB payload will be handled in one place

The function will get the adapter configuration, will validate RTB parameters and will return RTB payload object

### Expected results
Encourage adapters to use similar configuration and payload based on RTB standard
Smaller code
Less bugs

**Comment by KevinBrogan** [comment]
I can give an example of the inconsistency that exists in the adapters for video:
Rubicon requires maxduration in the adUnit.mediaTypes.video.maxduration property. Index Exchange requires maxduration in the adUnit.bids.ix.params.video.maxduration property.

maxduration is an openrtb spec property and I think that it, as well as any other rtb properties, should all be included in the adUnit.mediaTypes.video path. Some adapters will silently ignore parameters that they don't support which have been included in the mediaTypes.video path, while others will blindly include everything including the context parameter which isn't part of OpenRTB.

index exchange takes it even further and includes every property in the bids.ix.video path and puts them in the openRTB video parameter.

I would really like to see a more consistent interface. OpenRTB properties are all shared between bidders so it makes sense to have all the openRTB parameters be included at the adunit level. Only extension parameters should be included in the bids path.
