### ISSUE TITLE
Creating line items with DFP API

### ISSUE THREAD

**Issue by nhagen** [prebid/Prebid.js#46]
What has been done in looking into making a `prebid/LineItemMaker` type project that uses DFP's API to generate line items? Prebid.js is great, but it seems like line item creation is still too large of a barrier.

**Comment by prebid** [comment]
@nickjacob is working on one. CC'ing him here.

At the bottom of this blog (comment section), some pubs are working on a Github project:
http://blog.pubnation.com/when-ads-compete-you-win-ad-optimization-using-header-bidders/

**Comment by JuanCaicedo** [comment]
@nhagen I'm the person that worked on this at Curiosity Media / PubNation. We just released the code we use to do this. Hope it helps!

https://github.com/spanishdict/example-dfp-line-item-generator

**Comment by protonate** [comment]
Closing as this isn't on our current roadmap. @JuanCaicedo thanks for the link to your solution, @nhagen, hope that helped you with the line item creation barrier.

**Comment by kmjennison** [comment]
I also created a tool to automate DFP setup (because the other repo listed above is no longer maintained):
https://github.com/kmjennison/dfp-prebid-setup

Hope this helps those who are looking 😃
