### ISSUE TITLE
Previd.js uses Document.write

### ISSUE THREAD

**Issue by Ueland** [prebid/Prebid.js#4605]
## Type of issue
Prebid.js uses Document.write which negatively affects performance

## Description
Also mentioned in #2856 but issue got closed even thought the bug is still there. The use of Document.write causes Chrome to issue a warning stating that this will affect performance, potentially causing a delay in page rendering with many seconds.

## Platform details
Latest version of Prebid and Chrome

## Other information
 #2856
https://developers.google.com/web/updates/2016/08/removing-document-write

**Comment by snapwich** [comment]
I don't think you should be seeing any errors related to `document.write` from Prebid.js. If you look at the google link you posted:

```
The document.write() is in a top level document. _The intervention does not apply to document.written scripts within iframes as they don't block the rendering of the main page._
```

Prebid.js only writes to iframes, or specifically the doc passed to `pbjs.renderAd` which should be an iframe. Do you have an example where you have been seeing this warning stemming from using Prebid.js?
