### ISSUE TITLE
Extending the Real Time Data Module

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#4610]
## Type of issue
Intent-to-Implement

## Description
We're planning to generalize the Browsi Viewability module into a more generic 'Real-Time Data' interface.

The general idea is that the Real Time Data infrastructure provides:

- a consistent external interface paradigm
- controlling the delay of the Prebid auction
- an internal interface to sub-modules that can evolve with requirements

RTD Sub-Modules are a diverse bunch. These are the known effects the RTD system needs to support:

1. adding ad server targeting variables to influence the ad server decision
2. adding values to the bidRequest to influence the auction
3. support ad servers other than GAM
4. inspect bidResponse values and modify them as needed
5. modify Prebid config (e.g. auction timeout)

Not all sub-modules need to delay the auction, so there should be a way for sub-modules to:

- tell the core that the doesn't need to wait on its account. If the core determines that no module needs to delay the auction, then the auction shouldn't be delayed.
- provide a default value should a timeout occur

## Proposed External Interface

The proposed interface of the Real-Time Data is fairly straight-forward:
```
    pbjs.setConfig({
        realTimeData: {
            auctionDelay: 100,    // global to all sub-modules
            dataProviders:[{          
                name: "SUB-MODULE-NAME",
                params: {
                    // sub-module specific parameters
                }
            }]
        }
    });
```

Each sub-module should be able to pass data to bid adapters on a bidrequest. e.g.
```
bidrequest[].realTimeData={"sub-mod-code":{},"sub-mod-2":{}}
```

## Next Steps

A technical team will review the current internal interface in the [real-time data module](https://github.com/prebid/Prebid.js/tree/master/modules/rtdModule) and propose how to extend it to support the additional use cases.

**Comment by ydennisy** [comment]
Hey @bretg @pm-harshad-mane 
I would like to ask if you plan to continue work on this module?
It seems that `browsi` are already available through this method, we would like to our own module to the project - can you let me the process for doing so?
All the best,
Dennis

**Comment by bretg** [comment]
@omerBrowsi is working on a proposal for a new internal interface for the Real Time Data module. Any estimate on the timing Omer? You can just clean up the Google Doc we're working on, move it to the Prebid.js docs GDrive, and share the link here for comment.

**Comment by omerBrowsi** [comment]
@bretg 
Here is the document, I took the main points from our doc and organized a bit.
https://docs.google.com/document/d/13RW3wNP1_8CU7yz12rSuMdFupbLnnntyJMJSufdspsM/edit?usp=sharing

How can I move it to Prebif.js GDrive?

**Comment by bretg** [comment]
Thanks Omer. Moved to the Prebid.org drive -- https://docs.google.com/document/d/1A9mPkH8PiuqmrtKmIao42_losnopwrCGLtLJPv3L4oM/edit#heading=h.e5j9q2huzhvm

Community comments welcome. Would specifically ask @pm-harshad-mane, @jaiminpanchal27, @ydennisy, @bszekely1 to take a look

**Comment by ydennisy** [comment]
@bretg looks good to me!

**Comment by bretg** [comment]
Development timeline will come from @omerBrowsi and @pm-harshad-mane

**Comment by ydennisy** [comment]
@omerBrowsi @pm-harshad-mane just wondering if you guys have any timelines planned for working on this issue?

**Comment by patmmccann** [comment]
just noting https://github.com/prebid/Prebid.js/pull/1617 and https://github.com/prebid/Prebid.js/pull/2056 and natural fits for this functionality

**Comment by omerBrowsi** [comment]
pull request - https://github.com/prebid/Prebid.js/pull/5519

**Comment by bretg** [comment]
The first PR has been merged -- there will be followup PRs, but the issue can remain closed.
