### ISSUE TITLE
New adaptor submission

### ISSUE THREAD

**Issue by yogeshadsparc** [prebid/Prebid.js#462]
Hi all,

Please let me know the procedure to submit new adaptor code in prebid js.

**Comment by matthewlane** [comment]
@yogeshadsparc Please see the documentation for adding a new bidder adaptor here: http://prebid.org/dev-docs/bidder-adaptor.html

Adaptors submitted will need > 80% code coverage. This doc on testing may also be helpful in preparing for a pull request: http://prebid.org/dev-docs/testing-prebid.html

**Comment by yogeshadsparc** [comment]
@matthewlane ,

I already implemented new adaptor its working fine on my local, but i need to submit it so it can be use publicly.

**Comment by BartVB** [comment]
Do do this you can follow the documentation @matthewlane mentioned. If you're new to GitHub, here's a detailed guide on creating a pull request:
http://hisham.hm/2016/01/01/how-to-make-a-pull-request-on-github-a-quick-tutorial

**Comment by protonate** [comment]
Closing as answered. Please reopen if additional info or questions.
