### ISSUE TITLE
vertamediaBidAdapter and emx_digitalBidAdapter missing in Prebid 3.0

### ISSUE THREAD

**Issue by dimahajan** [prebid/Prebid.js#4631]
## Type of issue

Missing Adapter
## Description

I am upgrading prebid 2.35.0 to 3.0.0 and am unbale to get adapters in dist for vertamediaBidAdapter and emx_digitalBidAdapter.
I have also checked the release notes but mentioned nothing about this adapter.

**Comment by GeneGenie** [comment]
@dimahajan you can use adtelligentBidAdapter instead of vertamedia
