### ISSUE TITLE
What is the breaking change in 3.0.0?

### ISSUE THREAD

**Issue by ausminternet** [prebid/Prebid.js#4632]
## Type of issue
Question

## Description

There are only maintenance and bugfix commits in the release note, therefore I'm wondering why it is a new major release?

**Comment by GLStephen** [comment]
@ausminternet One of the major changes was Bid adapters were required to update to https and sizes are now required to be under mediaTypes. There is more than that however. There is a blog post which covers it. https://prebid.org/blog/pbjs-3

**Comment by ausminternet** [comment]
Thx for your quick reply!

It would be helpful, if this info were included in the release notes for the 3.0.0 Release (https://github.com/prebid/Prebid.js/releases/tag/3.0.0). Especially, since they are linked from the prebid.js Homepage if you search for the release notes. Is there a way to change them?

**Comment by andyblackwell** [comment]
Noticed some bidders were also removed in v3, because they haven't been updated yet. It would be nice for those to be listed somewhere, kind of important to know.

**Comment by bretg** [comment]
Posted a list of the adapters that haven't yet been ported to https://github.com/prebid/Prebid.js/issues/4650
