### ISSUE TITLE
Missing adapters 

### ISSUE THREAD

**Issue by jnevirauskas** [prebid/Prebid.js#4650]
## Type of issue
Bug

## Description
I found that there are missing these modules: audienceNetworkBidAdapter, smartadserverBidAdapter

**Comment by orzilca** [comment]
"As a consequence of some changes introduced to 3.0, the following adapters were temporarily removed as they were non-compliant (eg still using deprecated functions). Once they make the necessary updates to their files, these adapters can add themselves back to Prebid.js; just need to open a new PR."

https://github.com/prebid/Prebid.js/releases/tag/3.0.0

**Comment by bretg** [comment]
This is the list of adapters that haven't yet been ported to the master branch.

    7xbidBidAdapter.js
    a4gBidAdapter.js
    admanBidAdapter.js
    adspiritBidAdapter.js
    adtelligentBidAdapter.js
    advertlyBidAdapter.js
    andbeyondBidAdapter.js
    arteebeeBidAdapter.js
    audienceNetworkBidAdapter.js
    bizzclickBidAdapter.js
    brainyBidAdapter.js
    bridgewellBidAdapter.js
    colombiaBidAdapter.js
    contentigniteBidAdapter.js
    dailyhuntBidAdapter.js
    danmarketBidAdapter.js
    decenteradsBidAdapter.js
    dgadsBidAdapter.js
    envivoBidAdapter.js
    eywamediaBidAdapter.js
    fairtradeBidAdapter.js
    fyberBidAdapter.js
    gammaBidAdapter.js
    giantsBidAdapter.js
    gjirafaBidAdapter.js
    gxoneBidAdapter.js
    huddledmassesBidAdapter.js
    innityBidAdapter.js
    inskinBidAdapter.js
    interactiveOffersBidAdapter.js
    iqmBidAdapter.js
    kummaBidAdapter.js
    lemmaBidAdapter.js
    lifestreetBidAdapter.js
    oneplanetonlyBidAdapter.js
    openxoutstreamBidAdapter.js
    optimaticBidAdapter.js
    orbitsoftBidAdapter.js
    peak226BidAdapter.js
    platformioBidAdapter.js
    polluxBidAdapter.js
    polymorphBidAdapter.js
    pubnxBidAdapter.js
    rdnBidAdapter.js
    rexrtbBidAdapter.js
    rockyouBidAdapter.js
    rtbdemandadkBidAdapter.js
    rtbsolutionsBidAdapter.js
    saraBidAdapter.js
    seedingAllianceBidAdapter.js
    serverbidBidAdapter.js
    serverbidServerBidAdapter.js
    smartadserverBidAdapter.js
    smartyadsBidAdapter.js
    sortableBidAdapter.js
    supply2BidAdapter.js
    tpmnBidAdapter.js
    trafficrootsBidAdapter.js
    ucfunnelBidAdapter.js
    uolBidAdapter.js
    vertamediaBidAdapter.js
    vertozBidAdapter.js
    videoreachBidAdapter.js
    weboramaBidAdapter.js
    xendizBidAdapter.js
    yieldbotBidAdapter.js
    yieldnexusBidAdapter.js
    yieldoneBidAdapter.js
    zedoBidAdapter.js

- You can get a current list by diffing the modules/*BidAdapter.js files in the master branch vs the 2.44.xx-legacy branch
- Adapter owners have been contacted.
- We will maintain the 2.44.x branch with important updates until major adapters have ported
