### ISSUE TITLE
CCPA / USPrivacy field not containing expected value

### ISSUE THREAD

**Issue by brondsem** [prebid/Prebid.js#4664]
## Type of issue
Bug

## Description
With consentManagementUsp module enabled, I see ajax bids with us_privacy: "1---" but it should be "1YNN" or similar.

## Steps to reproduce
* enable consentManagementUsp
* be in California
* use a CMP that exposes __uspapi
* inspect network panel for bid requests and see that us_privacy string is only "1---" but `__uspapi('getUSPData', 1, (uspData, success) => { console.log(uspData, success) })` has  values like "1YNN"

## Platform details
* be on 3.0 or 3.1.1
* Chrome

**Comment by brondsem** [comment]
After more digging, the issue is that the CMP was not fully loaded & initialized when prebid.js started (since we run prebid.js very soon).  So prebid needs to be delayed until consent information is available.  It'd be great if prebid had a way to assist with that, but so far I think it may be require CMP-specific hooks to determine when the consent string is ready.

**Comment by jsnellbaker** [comment]
@harpere can you comment here?
