### ISSUE TITLE
Running gulp test on travis ci

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#467]
Is there a reason why are we not running tests on travis-ci?

I couldnt properly run the test using PhantomJS 

22 07 2016 17:17:06.174:WARN [web-server]: 404: /testsrc
Missing error handler on `socket`.
TypeError: Cannot read property '19590470' of null

using NODE_ENV='ci' gulp test

**Comment by protonate** [comment]
We do have Github integrated with Travis-CI, for example: https://travis-ci.org/prebid/Prebid.js/builds/146763291

Do you mean from Gulp / CLI?

**Comment by ialex** [comment]
@protonate but travis runs `build` and i think now that we have test it should be executing `test`

```
$ npm install -g gulp
$ gulp build
````

**Comment by mkendall07** [comment]
@ialex your right, it doesn't look like tests are being executed. I addressed with #469
