### ISSUE TITLE
Gzip compression on library scripts

### ISSUE THREAD

**Issue by protonate** [prebid/Prebid.js#468]
Recent performance audits show that a number of scripts could be gzipped to improve overall performance.

The following scripts are not gzipped. If possible please gzip your libraries.
~~- AppNexus http://ib.adnxs.com/jpt~~
- SpringServe http://bidder.springserve.com/display/hbid
- Brightcom https://hb.iselephant.com/auc/ortb  
  ~~\* Sekindo https://live.sekindo.com/live/liveView.php~~  
- Kruxlink https://link.krxd.net/hb
- AdMedia http://b.admedia.com/banner/prebid/bidder/
- AOL http://adserver.adtechus.com/pubapi/3.0/10077.1/3671670/0/0/ADTECH
- Rubicon http://optimized-by.rubiconproject.com/a/api/fastlane.json

@prebid/appnexus 
@prebid/springserve 
@prebid/brightcom 
@prebid/aol 
@prebid/rubicon 

@sekindo 
@nedstankus 
@sethyates 
@devmusings

**Comment by protonate** [comment]
Also please reply to this issue when the gzipped version is in place.

**Comment by sekindo** [comment]
We will take care of it early next week
Thanks

**Comment by sekindo** [comment]
Done! (sekindo liveView)

**Comment by indexexchange** [comment]
@protonate -- the IndexExchange bidding endpoint should have gzip compression enabled:

Request URL: http://as.casalemedia.com/headertag?v=9&x3=1&fn=cygnus_index_parse_res&s=....

 >GET /headertag HTTP/1.1
 >Host: as.casalemedia.com
 >Accept-Encoding: gzip, deflate

< HTTP/1.1 200 OK
< Server: Apache
< Vary: Accept-Encoding
< Content-Encoding: gzip
< Content-Length: 2859
< Content-Type: text/javascript

Can you clarify on which requests you were not able to achieve compression?

**Comment by protonate** [comment]
I'm not seeing a `content-encoding` response header for the `./headertag` resource.
```
$ curl -I -H 'Accept-Encoding: gzip,deflate' http://as.casalemedia.com/headertag
HTTP/1.1 301 Moved Permanently
Date: Wed, 27 Jul 2016 16:09:16 GMT
Server: Apache/2.2.15 (CentOS)
Access-Control-Allow-Origin:
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT
Access-Control-Max-Age: 1000
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token
Location: http://as.casalemedia.com/headertag/
Connection: close
Content-Type: text/html; charset=iso-8859-1
```

**Comment by indexexchange** [comment]
@protonate -- I'm seeing something different (I quoted the URL since it contains ampersands which the shell doesn't like):

```
roni@rgordon:~$ curl -I -L -H 'Accept-Encoding: gzip, deflate' 'http://as.casalemedia.com/headertag?v=9&x3=1&fn=cygnus_index_parse_res&s='
HTTP/1.1 200 OK
Server: Apache
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 20
Content-Type: text/javascript
X-N: S
Expires: Thu, 28 Jul 2016 16:25:07 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Thu, 28 Jul 2016 16:25:07 GMT
Connection: keep-alive

```

**Comment by protonate** [comment]
Ah, I was redirecting to development, apologies, I'm seeing a gzipped response for the `./headertag` endpoint.

**Comment by mkendall07** [comment]
Bump on this. Any adapter updates?

**Comment by bretg** [comment]
The RubiconProject endpoint will start rolling out compression support mid-late January... QA in progress.

**Comment by protonate** [comment]
The AppNexus `/jpt` endpoint is now has compression enabled.

**Comment by mkendall07** [comment]
This is requirement in prebid 1.0

**Comment by matan-ybrant** [comment]
Brightcom is now gzipped.
