### ISSUE TITLE
UniversalCreative fail,  page => secure frame+prebid.js => fif + uctag.js

### ISSUE THREAD

**Issue by GeneGenie** [prebid/Prebid.js#4682]
## Description
In case when prebid.js, is hosted in secure frame instead of topmost window, uctag.js thinks that  prebid.js is not reachable  and makes postMessaging instead of  getting parent windows looking for pbjs. 
Also since the current uctag location is not secure frame, but it thinks that it is, it takes default url as a postMessage post-back location, making it impossible to receive an ad html.

## Steps to reproduce
1. Load page  a.com/page1
2. page1 should load iframe  with src= b.com/iframe2
3. iframe2 page should have a prebid.js script and any valid auction configured.
4. configure dfp to serve Non secure creative. 
result: uctag.js wont render creative because: 
**isCrossDomain** method returns true  (but relatively to prebid.js it is not a crossdomain) and in this case "tpc.googlesyndication.com"  is written into **adServerDomain**  field of message (but uctag is on about:blank)

**Comment by jsnellbaker** [comment]
@GeneGenie I'll take a look into this behavior.  To help, do you happen to have a test page demonstrating this behavior handy?  It'll help in the setup/testing.

**Comment by GeneGenie** [comment]
@jsnellbaker  i'll try to set it up. but i'll ask you to add  domains in hosts file :)

**Comment by GeneGenie** [comment]
@jsnellbaker no hosts required: 

http://player.unocdn.com/prebid/pbBug/index.html    demonstrates the problem
page loads secure frame  on player.adtelligent.com  and the error appears 


if you load https://player.adtelligent.com/prebid/pbBug/index.html
ad should render without any problems

**Comment by jsnellbaker** [comment]
Hi @GeneGenie 
Thanks for supplying those testpages.  I reviewed the behavior and put together a change in the PUC repo that should address the issue you were seeing.  See PR link above.
