### ISSUE TITLE
Audience Network 3.x support

### ISSUE THREAD

**Issue by josephtyler** [prebid/Prebid.js#4694]
Does anyone know if the Audience Network module will be included in Prebid 3.x anytime soon?

## Type of issue

Question

## Description

Audience Network 3.x support.

**Comment by jsnellbaker** [comment]
Hi @lovell 
I saw your name tagged on the majority of commits for the audience network bid adapter.  When you get a chance, can you comment here on this question?

Thanks!

**Comment by lovell** [comment]
Yes, support for Audience Network in Prebid.js v3 is currently under development.

**Comment by khatibda** [comment]
@lovell any sense for rough ETA?  we are debating whether to wait for that adapter before going live with the new prebid, or just proceed and temporarily pause you.  if your adapter is coming in a week or 2 we'll wait, if you think timing is longer than that we're likely just to move ahead.  any guidance would be much appreciated!

**Comment by lovell** [comment]
I guess this will partly depend on the Prebid.js review, merge and release process, especially as there appears to be a higher than usual number of open PRs to migrate other adapters.

If you're already building your own Prebid.js bundle to include specific adapters then I might be able to provide a patch file to allow you to do some preliminary testing and therefore help you make a decision.

**Comment by khatibda** [comment]
@lovell oh a patch file would be terrific.  (yes we roll our own bundle).  thanks in advance!  let us know if you need any more info, we're standing by.

separately, if you have an official PR you can share once ready, we will gladly advocate for its priority in the review queue.  this is a high priority adapter!

**Comment by jsnellbaker** [comment]
@lovell Please feel free to tag me on the PR when it gets created; I'll keep an eye out and help with the review process.

**Comment by khatibda** [comment]
@lovell just checking in, any ETA on the PR or the patch file?  thanks in advance, you guys are kind of a big deal!

**Comment by khatibda** [comment]
@lovell @bretg hi - any status update on this?  i am confident this is holding up a bunch of 3.x upgrades.

**Comment by robertrmartinez** [comment]
@khatibda 

Hi, I am making the changes to get the adapter into the master branch now.

Hoping to get it done soon and reviewed and merged.

**Comment by robertrmartinez** [comment]
@khatibda @bretg @jsnellbaker @lovell 

I have made a PR which addresses this.

I think I fixed (The only issue) which was the usage of `getTopWindowUrl`

https://github.com/prebid/Prebid.js/pull/4769

**Comment by bretg** [comment]
Thanks @robertrmartinez
