### ISSUE TITLE
Outstream video render sample?

### ISSUE THREAD

**Issue by godoggie** [prebid/Prebid.js#4699]
## Type of issue
question

## Description
Hi, I'm looking for a working example of using a prebid bidder for outstream video that does NOT have a renderer embedded into it. All working examples I have seen so far leverage the appnexus adapter that seems to have the renderer baked in.  (IE http://prebid.org/dev-docs/show-video-with-a-dfp-video-tag.html)

My current use case does include dfp but willing to look at no server solutions too.  Can anyone suggest a working generic outstream video renderer that works with adapters that do NOT include a renderer? 

I have looked at the implementation below but it seems that only appnexus bidders return a legit "bid.adResponse" that will work with "ANOutstreamVideo.js" renderer.

`pbjs.addAdUnit({
    code: 'video1',
    mediaTypes: {
        video: {
            context: 'outstream',
            playerSize: [640, 480]
        }
    },
    renderer: {
        url: 'http://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js',
        render: function (bid) {
            ANOutstreamVideo.renderAd({
                targetId: bid.adUnitCode,
                adResponse: bid.adResponse,
            });
        }
    },
    ...
});` 

Any ideas or direction would be greatly appreciated.
thanks!

## Platform details
prebid 3+

**Comment by Hamper** [comment]
@godoggie did you find any solution? Also, if used cutom renderer then renderers from adapters that have own renderer not used?

**Comment by patmmccann** [comment]
Agreed we need to hash this out a bit

**Comment by patmmccann** [comment]
@ChrisHuie let's slack about this one, would love to talk it out and collaborate to knock this out

**Comment by patmmccann** [comment]
@fowler446 is this something you'd be interested in taking a crack at?

**Comment by fowler446** [comment]
@patmmccann Yes I am! Thanks for raising this to my attention.

**Comment by fowler446** [comment]
@godoggie This should help get you in the right direction. Particularly the part about unpacking the various different bids from SSPs https://github.com/prebid/prebid.github.io/pull/3871/files#diff-bb7640bf2c0f03364df070b2e13261ada40692c99352b9998ad0390ffa7050e3R32
