### ISSUE TITLE
Video Reach Bidder Adapter 3.x support

### ISSUE THREAD

**Issue by res-io** [prebid/Prebid.js#4715]
## Type of issue

Question
## Description

Currently the Video Reach Bidder Adapter is missing for Prebid 3.x
Is the support planned?

**Comment by jsnellbaker** [comment]
Hi @VideoReach 

I saw your user was tagged for the previous commits on the video reach bid adapter.  When you have the chance, can you comment on this question?

Thanks!

**Comment by jsnellbaker** [comment]
Video Reach adapter updated themselves for 3.x via https://github.com/prebid/Prebid.js/pull/4762

This PR was merged as part of 3.4.0 release (which went out yesterday, Jan 23).  

Closing this issue at this time; if there are any questions, please respond.
