### ISSUE TITLE
TCF 2.0 support in Prebid

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#4716]
## Type of issue
Query

## Description
When Prebid.js will start supporting TCF 2.0? what is the plan?

**Comment by bretg** [comment]
Jaimin has offered to head up the Intent-to-Implement.

**Comment by bjorn-lw** [comment]
From what I understand Google will require TCF 2.0 to support personalized ads once IAB has launched the new version.

https://support.google.com/admanager/answer/9461778?hl=en

**Comment by afewcc** [comment]
Not sure if you have started working on this, but if needed, I can offer help for the ITI as we have started looking into TCF v2 support on our side.

**Comment by jaiminpanchal27** [comment]
@afewcc Thanks for reaching out.  I will be opening Intent to implement for review tomorrow. Please review once complete

**Comment by jaiminpanchal27** [comment]
I2I here https://github.com/prebid/Prebid.js/issues/4801
