### ISSUE TITLE
win bid key values not passed to DFP

### ISSUE THREAD

**Issue by jonimin** [prebid/Prebid.js#4719]
## Type of issue

prebid auction run successfully, pbjs.getBidResponses() return bids but pbjs.getAdserverTargeting() always return empty   

## Test page
1. go to https://www.floor8.com/posts/temptation-island-s-ben-knobloch-tells-all-on-what-really-happened-with-ashley-howland-after-leaving-the-show-01dwg35s1mgh
2. ad unit - 175840252/floor8.com/index/article/300x250_prebid_yoni_1

### Expected results
verify pb key values passed on gpt tag:
hb_bidder: "ix"
hb_adid: "312f40ef3f1910f"
hb_pb: "0.00"
hb_size: "300x250"
hb_source: "client"
hb_format: "banner"

### Actual results
key values not passed as a result i have zero pb line items win in DFP

## This is my prebid code
var googletag = googletag || {};
googletag.cmd = googletag.cmd || [];
googletag.cmd.push(function() {
    googletag.pubads().disableInitialLoad();
});

s1=document.createElement('script');
s1.src='https://assets.minutemediacdn.com/prebid/prebid2.44.0.js';
document.body.appendChild(s1);

var PREBID_TIMEOUT = 1000;
var FAILSAFE_TIMEOUT = 3000;

var PREBID_TIMEOUT = 1000;
var FAILSAFE_TIMEOUT = 3000;

//todo with
var adUnits = [
    {
        code: '/175840252/index/floor8.com/article/300x250_prebid_yoni_1',
        mediaTypes: {
            banner: {
                sizes: [[300, 250],[320, 50]]
            }
        },
        bids: [{
	            bidder: 'ix',
	            params: {
	                siteId: "417122",
	                size: [300, 250]
	            }
	        },
	        {
	            bidder: 'ix',
	            params: {
	                siteId: "417122",
	                size: [320, 50]
	            }
	        },
	        {
	            bidder: 'sovrn',
	            params: {
	                tagid: "652624",
	            }
	        },
	        {
	            bidder: 'triplelift',
	            params: {
	                inventoryCode: "Floor8_Mobile_MPU_300x250_Flex_prebid_Yoni",
	            }
	        },
	        {
		        bidder: 'audienceNetwork',
		            params: {
		                placementId: "172716066688371_433126090647366"
	            	}
	            }
        ]
    },
   }

var pbjs = pbjs || {};
pbjs.que = pbjs.que || [];
adUnits = adUnits.slice(0,adUnitsOnPage.length)
pbjs.que.push(function() {
    pbjs.addAdUnits(adUnits);
    pbjs.requestBids({
        bidsBackHandler: initAdserver,
        timeout: PREBID_TIMEOUT
    });
});

pbjs.que.push(function() {
       pbjs.enableAnalytics([{
           provider:'sovrn',
           options: {
               affiliateId: 264726
           }
       }]);
})

function initAdserver() {
	if (pbjs.adserverRequestSent) return;
            pbjs.adserverRequestSent = true;
            googletag.cmd.push(function() {
                pbjs.que.push(function() {
                    pbjs.setTargetingForGPTAsync();
                    googletag.pubads().refresh();
                });
            });
}

// in case PBJS doesn't load
setTimeout(function() {
    initAdserver();
}, FAILSAFE_TIMEOUT);

function displayAdUnit(placeHolder, adUnitHierarchy) {
	googletag.cmd.push(function () {
            googletag.defineSlot(adUnitHierarchy, [[300, 250]], placeHolder).addService(googletag.pubads());
            googletag.pubads().enableSingleRequest();
            googletag.enableServices();
        });
}

displayAdUnit('test_ad_place_holder_1','/175840252/floor8.com/index/article/300x250_prebid_yoni_1')

**Comment by jsnellbaker** [comment]
Hi @jonimin 

I reviewed the setup and I think it's the following:
the adUnit.code is setup as `/175840252/index/floor8.com/article/300x250_prebid_yoni_1`
but the GAM slot id is setup as `/175840252/floor8.com/index/article/300x250_prebid_yoni_1`

Judging from the other adUnits defined in the config script file used on the test page, I think if you swap the `/index/floor8.com` parts around in the adUnit.code - it should start to work.

Can you give this a try?

**Comment by bretg** [comment]
I think Jason's provided a reasonable explanation for the issue here @jonimin - I'm going to close this. Re-open as needed.
