### ISSUE TITLE
0.11.0 Not loading analytics sources

### ISSUE THREAD

**Issue by jalbersmead** [prebid/Prebid.js#472]
It seems the analyticsDirectory value in gupfile.js is pointing to the wrong location.  Instead of _../analytics_ it should be _./src/adapters/analytics_ or at least that's what I had to do to get it to build correctly.

**Comment by jaiminpanchal27** [comment]
Thanks for contacting us @jalbersmead 
We will look into this and get back to you as soon as possible.

**Comment by mkendall07** [comment]
@jalbersmead 
What's your build look like? Are you adding a custom adapter into ` ./src/adapters/analytics` ? AFAIK that should work ok. If you have fork can you link it?

**Comment by jalbersmead** [comment]
I didn't fork it since it was just a change to the _gulpfile.js_.  I also realized that the documentation for enabling the GA analytics was missing an important step:  In _package.json_, you have to specifically enable an analytics adapter.  I filed an issue with the prebid.github.io project for that one.

**Comment by mkendall07** [comment]
@jalbersmead 
So just so I understand correctly, you are just trying to load GA adapter for analytics correct?

**Comment by jalbersmead** [comment]
Correct.  Nothing custom, just the default one included in the 0.11.0 source

**Comment by protonate** [comment]
GA analytics should work if you add `'ga'` to the `analytics` array in `package.json`.

**Comment by matthewlane** [comment]
`analyticsDirectory` in `gulpfile.js` is used to bundle an analytics library from an adjacent directory with Prebid, so it's pointing at the correct location. Since `ga` is within the Prebid src directory you should be abel to add it to `analytics` in `package.json` as @protonate mentioned and run `gulp build` to build with ga analytics.

**Comment by mkendall07** [comment]
Closing this as you should be able to use the method specified by @protonate to resolve.
