### ISSUE TITLE
conditional media types in multi-format configuration (setbidderconfig?)

### ISSUE THREAD

**Issue by godoggie** [prebid/Prebid.js#4727]
## Type of issue
question

## Description
Looking for help/example of configuring media types at a bidder level in a multi format configuration.  

IE, all bidders eligible for banner ads but only "bidder_X" supports video.  I'd like to leverage a single ad unit configured multi-format (banner & video) without all the bidders requesting both media types?  Is this possible?

I was hoping that the "setbidderconfig" function may help with this but does not seem to. Tried a few variations and it seems whatever media types set when configuring the ad unit are applied to all bid requests.  

So.. is it possible to have a multi-format prebid configuration where not all bidders subscribe to every media type listed?

thanks.

## Test page
https://jsfiddle.net/w8e6kLx3/

## Platform details
Prebid 3+

## Other information
http://prebid.org/dev-docs/show-multi-format-ads.html
http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.setBidderConfig

**Comment by spormeon** [comment]
are you on the slack adops channels, I can give you a hand if go some way of contacting you on pm etc?

**Comment by bretg** [comment]
Prebid merges AdUnits with the same code together. So you should be able to define the same adunit twice; once for banner once for outstream. So I think something like this should work, though to be honest, I'm not quite sure how `banner+video-bidder` receives this: whether as two bidRequests or json-merged. If someone confirms, I'll add it to the website docs.

```
var adUnits = [
	{
		code: 'mixed-adslot',
		mediaTypes: {
			banner: {
				sizes: [[300,250]]
			}
		},
		bids: [{
			bidder: 'banner-only-bidder',
			params: {
				placementId: 12345678
			}
		},
		{
			bidder: 'banner+video-bidder',
			params: {
				placementId: 13232385
			}
		}
		]
	},
	{
		code: 'mixed-adslot',
		mediaTypes: {
			video: {
				context: "outstream',
				playerSize: [640,480]
			}
		},
		bids: [{
			bidder: 'banner+video-bidder',
			params: {
				placementId: 13232385,
				video: {
					skippable: true,
					playback_method: ['auto_play_sound_off']
				}
			}
		}
		]
	}
];
```

**Comment by godoggie** [comment]
Thanks @bretg, your answer is just what i was looking for. Upon debugging the bid requests they are requesting the expected media types.  Appreciate the insight.
