### ISSUE TITLE
Why digitrust callback triggered twice ?

### ISSUE THREAD

**Issue by ckybonist** [prebid/Prebid.js#4728]
## Type of issue

bug and or question

## Description

The `callback` was triggered twice by userId module. 

```js
pbjs.setConfig({
  userSync: {
    userIds: [{
      name: "pubCommonId",
      storage: {
        type: "cookie",
        name: "_pubcid",       // create a cookie with this name
        expires: 365           // expires in 1 years
      }
    }, {
      name: "digitrust",
      params: {
        init: {
          member: 'example_member_id',
          site: 'example_site_id'
        },
        callback: function (digiTrustResult) {
          if (digiTrustResult.success) {
            console.log('Success in Digitrust init', digiTrustResult.identity.id);
          } else {
            console.error('Digitrust init failed');
          }
        }
      },
      storage: {
        type: "html5",
        name: "pbjsdigitrust",
        expires: 60
      }
    }]
  }});
```

## Steps to reproduce

Just use the example on [userId document](http://prebid.org/dev-docs/modules/userId.html#digitrust)

## Test page

- https://jsfiddle.net/kychu/hc2eb960/10/
- Open console and you'll see two messages:
```
Success in Digitrust init
xxxxxxxxx
```
NOTE: xxxxxx means the id value

### Expected results
Only executed / triggered the callback once.

### Actual results
Callback has been executed twice.

## Platform details

- Prebid.js: 2.44.0
- JSFiddle Prebid.js: https://acdn.adnxs.com/prebid/not-for-prod/1/prebid.js
- Browser: Google Chrome 79.0.3945.117

**Comment by bretg** [comment]
@goosemanjack - can you take a look?

**Comment by goosemanjack** [comment]
Will do. Will update this ticket when I find something.

**Comment by goosemanjack** [comment]
PR #4745 
Thank you for reporting this. This PR fixes the issue.
