### ISSUE TITLE
Question: Lazy load with MULTIPLE ad units

### ISSUE THREAD

**Issue by tornajoe** [prebid/Prebid.js#4729]
## Type of issue
Question.

## Description
The prebid.org site mentions how to do INDIVIDUAL ad unit refresh/infinite scroll.
http://prebid.org/dev-docs/examples/adunit-refresh.html
I'm trying to apply this to do lazy loading for a page and have each unit load when it is X viewports from being in view. I've been able to integrate DFP fine, but when I add prebid, it doesn't work properly.

The console gives me the following message. `MESSAGE: No adUnits configured. No bids requested.`

I've tried referencing other question topics made here such as 
https://github.com/prebid/Prebid.js/issues/1622
https://github.com/prebid/Prebid.js/issues/1266
I seemingly have the same setup/concept but get results that do not work.

## Steps to reproduce
On my test page (below), I have 3 DFP test units using 3 different PB adUnits. I set the timeouts, use the standard prebid setup with pbjs.que.push (that worked before I tried instituting lazy load), then pbjs.addAdUnits for all 3 adUnits (I thought this might be what was tripping me up, but I tried adding this for individual units and it still didn't work). Then I execute a scroll event listener that cycles through an object containing info for each DFP item, which leads to the following...

`pbjs.que.push(function() {
	pbjs.requestBids({
		timeout: PREBID_TIMEOUT,
		adUnitCodes: [details['LI']],
		bidsBackHandler: function() {
			pbjs.setTargetingForGPTAsync([details['LI']]);
			details['refresh']();
		}
	});
});`
with details['LI'] being the line item in DFP ('/#####/unit') as per the [prebid documentation](http://prebid.org/dev-docs/examples/adunit-refresh.html).
When I remove prebid, DFP items load properly, it's when I add in prebid that it does not work and I get the response `MESSAGE: No adUnits configured. No bids requested.` in the console.

## Test page
https://tradecraft.s.llnwi.net/v1/PBlazy.html?pbjs_debug=true
This page is setup with just 3 placements, one at the top, one a ways down in the middle and one at the bottom. When the first scroll happens, the function will start to determine if an ad is within X viewports and if so, execute. (I will work on getting it to have ones immediately in view to load instantly but want to figure this PB issue out first).

### Expected results
prebid works!

### Actual results
no bids are going through (and potentially more that I can't see not working)

## Platform details

prebid ver. 2.44, issue seen on all OS's

## Other information

https://github.com/prebid/Prebid.js/issues/1622
https://github.com/prebid/Prebid.js/issues/1266

Any help (or just guidance in the right direction) would be greatly appreciated. Thanks!

**Comment by bretg** [comment]
Your adunit codes are div IDs. e.g.
```
window.Bot300xFlexHG = {code: 'div-gpt-ad-1573351642602-0', mediaTypes: {banner: {sizes: [[300, 250], [336, 280], [500, 300]] }}, bids: [
  | {bidder: 'aol', params: { placement: '5159069', network: '11772.1'}},
  | {bidder: 'appnexus', params: { placementId: '17690048'}},
  | {bidder: 'ix', params: { siteId: '427838', size: [300, 250]}},
  | {bidder: 'rubicon', params: {siteId: '294778', zoneId: '1484768', accountId: '21666'}},
  | {bidder: 'sovrn', params: { tagid: '655971'}},
  | ]};
```
When you call requestBids, the adUnitCodes array there needs to refer to `div-gpt-ad-1573351642602-0` rather than `/21854935662/TestAd_3`. Or set the adunit codes appropriately.
