### ISSUE TITLE
Not seeing any events for Prebid.js CPM Distribution or Prebid.js Load Time Distribution event categories

### ISSUE THREAD

**Issue by CLKeenan** [prebid/Prebid.js#473]
I'm using 0.10.0 in production. I'm only seeing events within the 'Prebid.js Bids' passed through to Google Analytics. This then causes the CPM Distribution and Load Time Distribution sheets to fail (#DIV/0! error) within the Google Sheets/Analytics reports. 

Is it know that events within those categories are no longer being passed through? If so, is there a plan to update the Spreadsheet Demo to still provide the CPM and Load Time distribution reports? I'd find them to be very valuable!

Thanks,
-Chris

**Comment by CLKeenan** [comment]
Realized that enableDistribution needs to be set to 'true' in order to pass through those event categories. This presents an issue for me as I have 7 bidders and it's suggested to not set enableDistribution to true if you have more than 4. Any suggestions?

**Comment by mkendall07** [comment]
@CLKeenan 
You can enable it if you want to, however, ga limits the # of events that are sent in the first 2 seconds of the page load. So just be aware that the data might be incomplete. Thanks

**Comment by CLKeenan** [comment]
@mkendall07 - thanks for the quick response. One more question if you have time; do you know if the data that comes through would be randomly distributed? As in, over enough time, will the data be a representative set even with the potentially missing data? Or will the same set/type of data always be missing?

Just trying to understand if I'd be able to trust the data that comes through to make decisions on.

**Comment by mkendall07** [comment]
It would not be completely random, as it is derived from events that relate to external factors that may behave in a somewhat consistent manner. For example, if a bidder always responds late, it's bid response event will be late and the events queue may always be maxed out at that time. 

I would suggest enabling it and sampling the data and seeing if there is any glaring omissions.

**Comment by CLKeenan** [comment]
Makes sense. That's what I was afraid of. I might do some A/B testing and load 3 bidders in one set and 4 bidders in the other while gathering the data.
