### ISSUE TITLE
Doubt - Prebid key values in ad request

### ISSUE THREAD

**Issue by mgis92** [prebid/Prebid.js#4742]
Hi all,
I have a quick doubt that I think you will solve it in one minute!

In many times we are seeing in our requests that all the parameters that prebid have to send, are not sent. I am talking about the following parameters:

hb_format=
hb_source=
hb_size=
hb_pb=
hb_adid=
hb_bidder=

Those parameters have to be sent every time, or only in the cases when there is an win bid by Prebid? 
There are cases that I can see win bids but the parameters are not sent in the request. 

On another hand, what minimum pricing rules you recommend to use for working with Prebid? I  am not sure if our current pricing rules are too strong for Prebid.

**Comment by ptomasroos** [comment]
Only in the case there is a bid available in the client, those keys will get passed to the ad server.

**Comment by bretg** [comment]
Agree with ptomasroos, but here's some more background that may help...

This is the documentation on when PBJS sends ad server variables http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-Send-All-Bids

There are a several controls that constrain how many targeting variables are sent through to the ad server: enableSendAllBids, sendBidsControl, auctionKeyMaxChars 

Importantly, the adserverTargeting option in bidderSettings can also affect which variables are sent. Here's a note from that section of the documentation:

```
Note that once standard.adserverTargeting is specified, you’ll need to fully manage the targeting – the default hb_ targeting variables will not be added.
```

> what minimum pricing rules you recommend to use for working with Prebid

There aren't any minimum prices for sending ad server targeting variables except 0.01. If the bid price is 0, it's not a bid.
