### ISSUE TITLE
0.11.0 no default analytics adapter

### ISSUE THREAD

**Issue by mhipszki** [prebid/Prebid.js#475]
Guys,

we've added an option to generate Prebid.js bundle with a specific list of adapters in #420 merged into `master` in #424 and released in https://github.com/prebid/Prebid.js/releases/tag/0.11.0

Just noticed that in the same release the way analytics can be turned on has been changed (0.11.0 actually broke our GA tracking).

I'm not sure if the Dev Docs have been updated in accordance to this change when the Prebid Analytics API has been created?

see http://prebid.org/dev-docs/analytics-ga.html and https://github.com/prebid/Prebid.js/commit/e1224866815814198535786961f18e219f66ac90

The current way of defining analytics adapters has the same limitations as defining the bidding adapters had had before #424 (changing `package.json`).

Thinking of a solution to enable users defining their own set of analytics adapters, we could change `loaders/analyticsLoader.js` similar way we've changed `loaders/adapterLoader.js` to load the list of analytics adapters from a specific `.json` file instead of `package.json`

I'm happy to send in a PR for that like I did for the custom adapters list.

**Comment by mkendall07** [comment]
@mhipszki 

Going to take a look at #472 before replying here. I think it makes sense tho.

**Comment by mkendall07** [comment]
A note on GA: Since we are working on a 3rd party neutral API for analytics (it's technically still in progress) we opted to remove default bundling of GA. Sorry about breaking the builds, we missed communicating that in the release notes.

**Comment by mhipszki** [comment]
@mkendall07 np, I saw that issue before raising this one

The natural API makes sense.

Actually, this one might be better called `bundling Prebid.js with specific analytics adapters` or similar?

**Comment by mhipszki** [comment]
@mkendall07 I've created a PR containing a refactored and tested version of the `loaders/getAdapters.js` module I had created in #424

the PR is intended to be a prerequisite of this improvement (bundling specific analytics adapters)

could you please take a look?

**Comment by brondsem** [comment]
Which PR is that, #476?  Would love to see that get some traction so we can use analytics from a stable release soon.  Thanks.

**Comment by mhipszki** [comment]
@brondsem yup that's the one, however that's just the prerequisite of fixing this issue

**Comment by protonate** [comment]
GA analytics should work if you add `'ga'` to the `analytics` array in `package.json`.

**Comment by mkendall07** [comment]
@mhipszki 
I'm going to close this out as technically this is expected. We still review the PR you have outstanding for the refactor of analytics adapter which makes sense.
