### ISSUE TITLE
bid adpater's onBidWon function not called for instream video bids

### ISSUE THREAD

**Issue by jsnellbaker** [prebid/Prebid.js#4768]
## Type of issue
Bug

## Description
While reviewing the surrounding code for something else, I noticed that the `auctionManager.addWinningBid` logic used to call a bid adapter's `onBidWon` function was not being triggered for `instream` video bids.

The `addWinningBid` logic is invoked in the following areas for the other media types:
- banner > https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L317
- outstream video > https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L317
- native > https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L317 & https://github.com/prebid/Prebid.js/blob/master/src/secureCreatives.js#L58 (since there different paths to handle for native)

I believe this is just an unfortunate oversight and not an intentional decision to omit `instream` video.  

I will work on putting together a fix soon.

**Comment by ChrisHuie** [comment]
closing issue from #5481
