### ISSUE TITLE
Index exchange bid adapter invalid for more then one player sizes

### ISSUE THREAD

**Issue by Hamper** [prebid/Prebid.js#4781]
## Type of issue
Bug

## Description
In documentation of IX bid adater written that adUnit can have more then one player size (it can be useful for outstream) like
```javascript
playerSize: [
  [300, 250],
  [300, 600]
]
```
It checked in https://github.com/prebid/Prebid.js/blob/3.4.0/modules/ixBidAdapter.js#L383

But in this case we get error
```
Detected incorrect configuration of mediaTypes.video.playerSize.  Please specify only one set of dimensions in a format like: [[640, 480]]. Removing invalid mediaTypes.video.playerSize property from request.
```
regarding to https://github.com/prebid/Prebid.js/blob/3.4.0/src/prebid.js#L112

## Platform details
Prebid.js 3.4.0

**Comment by jsnellbaker** [comment]
@ix-prebid-support Can you take a look at this?

**Comment by ix-prebid-support** [comment]
Hi @Hamper 

The IX Bid Adapter does **_not_** support a multi-size configuration for the `playerSize` in video ad units. 

Like you have shown, the Prebid.js library enforces a single-size configuration for `playerSize`. We will be updating our documentation and examples to reflect the correct functionality.

Thank you for bringing this to our attention!
_ix-prebid-support_

**Comment by Hamper** [comment]
There is no way to use IX adapter for outstream with more then one size in separate bids in one adunit?

**Comment by ix-prebid-support** [comment]
@Hamper
Since `playerSize` is configured per adUnit, and `playerSize` is restricted to a single size, Prebid does not support outstream adunits with multiple sizes in separate bids.
