### ISSUE TITLE
Advertly Adapter in voilation of "required conventions"

### ISSUE THREAD

**Issue by mannzer** [prebid/Prebid.js#4794]
## Type of issue
Adapter violates "required conventions"

## Description
Dev docs at http://prebid.org/dev-docs/bidder-adaptor.html clearly state:
"_Adapters may not create or trigger any network requests or pixels_ outside of the requests that wrapper creates on behalf of the adapter from the return values of buildRequests() and getUserSyncs() or are included in a winning and rendered creative."

## Steps to reproduce
1. Read the docs: http://prebid.org/dev-docs/bidder-adaptor.html
2. Behold: https://github.com/prebid/Prebid.js/blob/master/modules/advertlyBidAdapter.js#L100

### Expected results
The adapter should "_not create or trigger any network requests or pixels_ outside of the requests that wrapper creates on behalf of the adapter from the return values of buildRequests() and getUserSyncs() or are included in a winning and rendered creative."

### Actual results
The adapter makes ajax calls, presumably for tracking, outside the controlled, monitored, and publisher permitted routes.  Ideally the inclusion of the ajax module https://github.com/prebid/Prebid.js/blob/master/modules/advertlyBidAdapter.js#L5 should be a red flag in most circumstances.

## Platform details
GitHub

## Other information

This was last requested by @jsnellbaker and reviewed/approved/merged by @robertrmartinez in #4738

**Comment by mkendall07** [comment]
Agreed this is a violation. Looks like we just missed it.
@Advertly please remove this https://github.com/prebid/Prebid.js/blob/master/modules/advertlyBidAdapter.js#L51 part
