### ISSUE TITLE
Yieldbot: Multiple requestBids Not Working

### ISSUE THREAD

**Issue by ehoch** [prebid/Prebid.js#481]
So we currently split our ad auctions up amongst our ATF and BTF units and run multiple Prebid auctions. Unfortunately, the Yieldbot adaptor does not work with this.

Easy to replicate. Define two ad units. Run requestBids twice - once the first ad unit and a separate one on the second . Then run yieldbot.dumpLog() in the console.

You'll see that only the initial ad slot that is defined gets a call to getSlotCriteria() with the handleUpdateState() is run. You'll only get bid responses on the initial slots.

**Comment by protonate** [comment]
I believe that PR #498 can address this if the Yieldbot adapter can be updated to set the bid response ID to match the bid request ID in these locations:
https://github.com/prebid/Prebid.js/blob/master/src/adapters/yieldbot.js#L51
https://github.com/prebid/Prebid.js/blob/master/src/adapters/yieldbot.js#L70

**Comment by mkendall07** [comment]
is this still an issue?

**Comment by ehoch** [comment]
@mkendall07 Yes unfortunately.

**Comment by mkendall07** [comment]
@elljoh @amcmillan01
Either of you want to try and fix this? Been open for a long time.

**Comment by elljoh** [comment]
@mkendall07 Yes. Please assign to me.

**Comment by CarsonBanov** [comment]
@elljoh You might try removing the cache=true flag from the `adloader.loadScript` call in the adapter and just letting their script load twice.  
See:
https://github.com/prebid/Prebid.js/blob/master/src/adapters/yieldbot.js#L110
https://github.com/prebid/Prebid.js/pull/466/files#diff-74a5dc55dc79589eecd119f347c94a28R110

**Comment by elljoh** [comment]
We have identified problem and expect to have a PR submitted in the next couple of days to reference a fix for this issue.
