### ISSUE TITLE
Remove mediaQuery declaration as an empty string in sizeConfig

### ISSUE THREAD

**Issue by Fawke** [prebid/Prebid.js#4810]
## Type of issue
Bug

## Description
Under the current design (as of v3.x), a publisher can declare **mediaQuery** string as empty in global sizeConfig object.

The implication of this is inconsistent behaviour when a publisher chooses to declare mediaQuery as an empty string, the current implementation may choose wrong Ad size for a given viewport size. For details and an example, click [here](https://github.com/prebid/Prebid.js/pull/4691#issuecomment-571538911).

Related - https://github.com/prebid/Prebid.js/pull/4691

A fix could be to completely block empty mediaQuery string declaration. Since this solution could be a breaking change for some publishers who're already using empty mediaQuery declaration in sizeConfig, the change should go in the next major release.

**Comment by gglas** [comment]
@Fawke hey Neelanjen -- did 4691 resolve this issue and we can close it out?

**Comment by Fawke** [comment]
@gglas Hi Gareth -  No, we didn't resolve this issue in https://github.com/prebid/Prebid.js/pull/4691. It was a breaking change, so @mkendall07  suggested the change should go out as part of a next major release. It was supposed to be 4.0, but that didn't happen. We can include in now, in 5.0. It's a small edge case in the core sizesMapping module which can lead to some unexpected behaviour.

**Comment by patmmccann** [comment]
Closing with the merge to 5
