### ISSUE TITLE
SpotX configuration since addition of videoCacheKey

### ISSUE THREAD

**Issue by nanek** [prebid/Prebid.js#4815]
## Type of issue
Question

## Description
https://github.com/prebid/Prebid.js/pull/4706 adds videoCacheKey to SpotX responses in Prebid 3.3.0. However this breaks rendering of SpotX instream without additional configuration. Can the SpotX docs be updated to indicate what the proper configuration should be? Specifically do we need to create custom GAM video creatives that specify a different VAST URL?

http://prebid.org/dev-docs/show-video-with-a-dfp-video-tag.html#notes-on-prebid-cache Notes `If pbjs.setConfig({cache: {URL}}) is defined` however I believe these docs are out of date and cache.url is always required since https://github.com/prebid/Prebid.js/pull/1904.

I use 
````
    cache: {
      url: 'https://prebid.adnxs.com/pbc/v1/cache',
    }
````

Lastly as I understand it videoCacheKey effectively overrides anything else based on https://github.com/prebid/Prebid.js/pull/2143. http://prebid.org/dev-docs/show-video-with-a-dfp-video-tag.html#notes-on-prebid-cache indicate "In general, video-enabled bidders must supply bid.videoCacheKey, bid.vastXml, or bid.vastUrl on their responses, and can provide any combination of the three." However in practice, I don't think you can use the vastUrl if a videoCacheKey is provided. Please let me know if I've misunderstood this.

Thanks for any suggestions!

**Comment by lukacmi** [comment]
@nanek I am not from SpotX, but you can resolve this by changing GAM creative to
https://search.spotxchange.com/ad/vast.html?key=%%PATTERN:hb_cache_id%%

This only applies to SpotX adapter due to #4706 change. Hope this helps.

**Comment by jarnix** [comment]
Hi,
This forces to do a creative per bidder and it's a not easy to maintain. Did you find a better solution?

**Comment by nanek** [comment]
Agreed. I just revert #4706 in my custom build.
