### ISSUE TITLE
How to Change Cap Default for setPriceGranularity("medium");

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#482]
So i'm using             pbjs.setPriceGranularity("medium");
but i dont want to have 200 line items i want to change the cap default from 20 to 8.00 for example how can this be done ? 

many thanks.

**Comment by mercuryyy** [comment]
I ended up creating 200 Line items ;/ but a solution can still be helpful for someone that wants to use 0.10 increments but cap it not at 20.00 cpm  default.

**Comment by mkendall07** [comment]
@mercuryyy 
This can be accommodated by using a custom price bucket setting. See http://prebid.org/dev-docs/examples/custom-price-bucket.html
