### ISSUE TITLE
[I2] 4.x release proposal

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#4824]
## Type of issue
Intent to implement [I2I]

## Description
Proposal for 4.x release. 

1. Removing the AudienceNetwork adapter as FB has announced they will focus on mobile and stop bidding by April 11th. 
1. Stricter device access controls (https://github.com/prebid/Prebid.js/issues/4747) 
1. Removal of the Quantum bidder (deprecated) 
1. Fully removing `adUnit.sizes` (from internal structures and modules) 
1. Stronger enforcement for bidders return bid meta data (https://github.com/prebid/Prebid.js/issues/3115#issuecomment-546774948) needs refinement. 
1. https://github.com/prebid/Prebid.js/issues/3873 - Proposal: set cookie domain in pubcid / userid on main domain, not subdomain -  needs review
1. TCF phase #?

This is still early and subject to change (subtractions/additions). Comments welcome for additions

**Comment by patmmccann** [comment]
Is TCF 2.0 considered breaking?

**Comment by patmmccann** [comment]
#3897 seems useful, to change where pubcid sets the cookie

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/issues/3115#issuecomment-546774948

**Comment by mkendall07** [comment]
Thanks @patmmccann 
TCF 2.0 should not be a breaking change AFAIK from the publisher perspective. We will/should handle both at the same time.

**Comment by patmmccann** [comment]
A couple bidders (optimera and ias) are not really bidders. In 4.x should these be folded into the RTD module?

**Comment by ehoch** [comment]
@jaiminpanchal27 @mkendall07 Can we also add a recommendation to consume Video OpenRTB params from `mediaTypes.video` and deprecate doing it as part of the bidder params?

I'd really like to see 5.0 make this a required change for adapters and 4.0 could really help with this encouragement.

I'll be updating the documentation hopefully this week, but here's an issue to reference what the heck I'm talking about:

https://github.com/prebid/Prebid.js/issues/5237

**Comment by GLStephen** [comment]
This was merged as well. https://github.com/prebid/Prebid.js/pull/5402

**Comment by patmmccann** [comment]
as was #5401
