### ISSUE TITLE
Symbol.toStringTag: HTMLFormElementPrototype is not extensible exception

### ISSUE THREAD

**Issue by PsychodelEKS** [prebid/Prebid.js#4836]
## Type of issue
bug

## Description
Exception in latest FireFox browser when including prebid.js on page with frozen HTMLFormElement proto:
`TypeError: can't define property Symbol.toStringTag: HTMLFormElementPrototype is not extensible`

## Steps to reproduce
User prebid.org to generate latest version of prebid (confirmed on 3.6.0-pre and 3.7.0-pre) (adapters selection does not matter) include it on the page with proto freezing code:
```javascript
  try {
    Object.freeze(HTMLFormElement.prototype)
  } catch (e) {
  }
```

## Test page
https://jsfiddle.net/qmeo81ay/

### Expected results
There should be no uncaught exceptions

### Actual results
There is an exception which brakes HB functionality

## Platform details
FireFox 72.0.2 (64-bit)

## Other information
The error seems to be caused by the following piece of code from
`node_modules/core-js/library/modules/web.dom.iterable.js`

```javascript
require('./es6.array.iterator');
var global = require('./_global');
var hide = require('./_hide');
var Iterators = require('./_iterators');
var TO_STRING_TAG = require('./_wks')('toStringTag');

var DOMIterables = ('CSSRuleList,CSSStyleDeclaration,CSSValueList,ClientRectList,DOMRectList,DOMStringList,' +
  'DOMTokenList,DataTransferItemList,FileList,HTMLAllCollection,HTMLCollection,HTMLFormElement,HTMLSelectElement,' +
  'MediaList,MimeTypeArray,NamedNodeMap,NodeList,PaintRequestList,Plugin,PluginArray,SVGLengthList,SVGNumberList,' +
  'SVGPathSegList,SVGPointList,SVGStringList,SVGTransformList,SourceBufferList,StyleSheetList,TextTrackCueList,' +
  'TextTrackList,TouchList').split(',');

for (var i = 0; i < DOMIterables.length; i++) {
  var NAME = DOMIterables[i];
  var Collection = global[NAME];
  var proto = Collection && Collection.prototype;
  if (proto && !proto[TO_STRING_TAG]) hide(proto, TO_STRING_TAG, NAME);
  Iterators[NAME] = Iterators.Array;
}
```

This definitely is some edge-case, but still, if the proto extending code is needed, may be it needs some isFrozen/isExtensible/isSealed check adding to prevent exceptions (or try/catch at least).

**Comment by GimpyPrime** [comment]
Observed the same bug across multiple browsers. Here are a handful of errors

**Chrome 64.0.3282.140**
TypeError: Cannot define property 'Symbol.toStringTag': object is not extensible

**Chrome 70.0.3538.102**
TypeError: Cannot define property 'Symbol.toStringTag': object is not extensible

**IE11**
TypeError: Cannot define property 'Symbol(Symbol.toStringTag)_4.stdfegve52t': object is not extensible

**Firefox 72.0**
can't define property Symbol.toStringTag: HTMLFormElementPrototype is not extensible

**Mozilla rv:11.0**
TypeError: Cannot define property 'Symbol(Symbol.toStringTag)_4.h10z07gou43': object is not extensible

Oddly enough we don't get a single error of this kind in Safari. That said we do get a large number of undefined errors. Leading us to believe it may be related, but so far we are not sure.

This is the most common **Safari 13** error and it may or may not be related.
undefined is not an object (evaluating 'a.default')

It appears this last one is an issue with the importing of the adapterManager within Prebid.js.  Unclear how 'a' could be undefined but is something is going wrong on...
const adapterManager = require('./adapterManager').default;

Like I said this last one could be unrelated, just found it odd that Safari 13 had no errors with toStringTag but the prebid adapters all seem to fail loading intermittently.

**Comment by GimpyPrime** [comment]
It turns out we are getting this error in Safari and Safari Mobile as well, it just doesn't explicitly reference toStringTag. Here it is...

**Safari 13** 
Attempting to define property on object that is not extensible

**Comment by GimpyPrime** [comment]
We noticed the polyfills issue to be more common on pages running multiple versions of Prebid. It may be trying to extend after already frozen by a previously run version. We may attempt upgrading the Core JS library to a newer version at some point hoping that this is resolved. For now we had to move several sites back to Prebid 1.x.
