### ISSUE TITLE
Critical vulnerability with criteo-direct-rsa-validate dependency

### ISSUE THREAD

**Issue by shoutez** [prebid/Prebid.js#4851]
## Type of issue
Once `npm audit` is ran on the project, there is a **critical vulnerability** with a dependency of `criteo-direct-rsa-validate`. 

## Description
Critical vulnerability with `js-yaml` is documented at https://www.npmjs.com/advisories/788. When executing `npm audit fix` or `npm audit fix --force` the vulnerability problem is not fixed.
 
![Screen Shot 2020-02-12 at 3 57 08 PM](https://user-images.githubusercontent.com/2768250/74376565-5db5cd80-4db0-11ea-877f-f29f38bc5d08.png)

## Steps to reproduce
1. Clone project
2. Install dependencies by running `npm install`
3. Run `npm audit`

### Expected results
Run `npm  audit` and don't receive any `critical vulnerability` message.

### Actual results
Receiving `critical vulnerability` message when executing `npm audit`

**Comment by jsnellbaker** [comment]
The above PR addressed the reported issue; it will be part of Prebid 3.8.0

Closing this issue at this time.
