### ISSUE TITLE
[Feature] Consent Module re-read consent

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/Prebid.js#4858]
## Feature Request
The consent module stores the consent string and reuses it across requests, even when the user changes their consent at a later point.

## Description
The consent module reads the consent string once, and keeps using it for the rest of the session. As a result, prebid does not notice if users later change their consent in the same session.

For new users it makes sense to fire off the first auction without consent ( and without tracking ), as the user won't accept/change his settings in time for the first auction. By the time ads are refreshed the user has given his consent, and so later auctions/refreshes should use this new consent string. This is especially needed for SPA's, where no actual page changes occur and prebid remains loaded.

Either always fetching the updated consent string would be an option, or exposing a method that reset/re-reads the consent data would be handy.

**Comment by bretg** [comment]
@jaiminpanchal27 - please cover this scenario in #4801?

**Comment by timhanlon** [comment]
I'm building a Chrome extension to help people verify their CMP implementations are functional, and just uncovered this behaviour.

Looks like it'd be a trivial fix: https://github.com/prebid/Prebid.js/blob/master/modules/consentManagementUsp.js#L161

If people are relying on this behaviour, perhaps it could go behind a `consentManagement` param...something like `checkConsentBeforeSubsequentAuctions` or `alwaysCheckConsent`?

Would you accept a PR?
