### ISSUE TITLE
Defining userSync.filterSettings.iframe only disables image syncing in v3.7.1

### ISSUE THREAD

**Issue by Austinb** [prebid/Prebid.js#4864]
## Type of issue
Bug or undocumented change in default behavior when moving from v2.x to v.3.x

## Description
In version 3.7.1 (and 3.3.0) when you specify the `userSync.filterSettings` it overwrites the defaults rather than being merged with the defaults.  If you define the `userSync.filterSettings.iframe` settings the default `userSync.filterSettings.image` settings from https://github.com/prebid/Prebid.js/blob/master/src/userSync.js#L9 are lost. This effectively disables image pixel syncing unless you define it explicitly or use the `userSync.filterSettings.all` property. 

In the v2.x series it did not do this (verified in both v2.39.0 and v2.34.0 with currently active deployments).

## Steps to reproduce
If you have your pb.js config defined with the following
```js
{
    userSync: {
        filterSettings: {
            iframe: {
                bidders: '*', 
                filter: 'include',
            },
        },
    },
}
```
The response from the `config.getConfig` calls in https://github.com/prebid/Prebid.js/blob/master/src/adapters/bidderFactory.js#L335 only contains the defined settings above.  As a result the value of `pixelEnabled` is `false` a couple of lines down.

## Test page
Not available

### Expected results
If the image syncing is supposed to be enabled by default then it should always be enabled unless otherwise explicitly disabled in the `userSync.filterSettings.image` key.

### Actual results
If the `userSync.filterSettings.image` setting is not defined when defining `userSync.filterSettings.iframe` image syncs are disabled. 

## Platform details
Building Prebis.js on:
Ubuntu 18.04.3
Node JS v10.17.0
Npm 6.13.6

## Other information
Did a quick search and was unable to find any specific change that affected this but I did not spend a lot of time searching either.  I did find some comments in https://github.com/prebid/Prebid.js/pull/4241/files referencing that the `permittedPixels.image` should remain `true` by default which leads me to believe this is a bug and not an undocumented change in default behavior. If I have some time I will step through and see what change broke the default behavior.

**Comment by Austinb** [comment]
After having dug around a bit I think this issue stems from the removal of the old `userSync.pixelEnabled` value.  Before it the system was defaulting using that since it was true.  Now since that setting is gone and it appears the `config.setDefaults()` at https://github.com/prebid/Prebid.js/blob/master/src/userSync.js#L6 does not do what it is supposed to do the image syncing ends up disabled if you pass anything for `userSync.filterSettings`. 

From what I can tell by the time that `config.setDefaults()` is called the `userSync.filterSettings` values have already been overwritten by the values passed when calling `setConfig()` when setting up the Prebid.js calls.  I am not quite following the order of operations as to when the userSync file is called but that might be part of the issue.

**Comment by Austinb** [comment]
After having dug around a bit I think this issue stems from the removal of the old `userSync.pixelEnabled` value. Before it the system was defaulting using that since it was true. Now since that setting is gone and it appears the `Object.assign()` at https://github.com/prebid/Prebid.js/blob/master/src/config.js#L298 is (and has been) overwriting the `userSync.filterSettings` key since it already exists in the defaults from https://github.com/prebid/Prebid.js/blob/master/src/userSync.js#L6.

Output of before https://github.com/prebid/Prebid.js/blob/master/src/config.js#L298 I get the following:
```js
{
auctionDelay: 0
​filterSettings: {
​​image: Object { bidders: "*", filter: "include" }
}
​​​syncDelay: 3000
​syncEnabled: true
​syncsPerBidder: 5
}
```

The value of `option` after that line is as follows:
```js
{
auctionDelay: 0
​filterSettings: {
​​iframe: Object { bidders: "*", filter: "include" }
}
​​​syncDelay: 3000
​syncEnabled: true
​syncsPerBidder: 5
}
```

So either there needs to be no more default, a default another way or that code needs to be expanded to check for objects and merge keys.

**Comment by Austinb** [comment]
Wanted to bump this and make sure it is not over looked.

**Comment by jsnellbaker** [comment]
@Austinb Thanks for the bump & reporting it - I'll take a look at this.
