### ISSUE TITLE
Appnexus Outstream Video Complete Event/Callback?

### ISSUE THREAD

**Issue by godoggie** [prebid/Prebid.js#4866]
## Description
Looking for information on how to determine when an outstream video ad has finished/ended. The input parameters are limited to the adUnitCode and adResponse.  

renderer: {  
        url: 'https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js',
        render: function (bid) {
            ANOutstreamVideo.renderAd({
                targetId: bid.adUnitCode,
                adResponse: bid.adResponse,
            });
        }
    },

Ideally the ANOutstreamVideo.js would support a callback parameter or ability to subscribe to some sort of notification but I do not see any of those options.

Any ideas would be appreciated.
thanks!

## Platform details
3.5+

**Comment by patmmccann** [comment]
@Fawke @jsnellbaker curious if the AppNexus player has this callback?

**Comment by patmmccann** [comment]
related to #4699
