### ISSUE TITLE
Prebid.js with VMAP Response

### ISSUE THREAD

**Issue by johndpknt** [prebid/Prebid.js#4869]
Hello Team,

I have been trying to working on a project where I need to send a VMAP response to the client through prebid.js to satisfy multiple video ad placements on a single video. I couldn't locate relevant VMAP documents on prebid.org. 

Can anyone please suggest to me does this support VMAP or only VAST is supported?

Thanks in Advance

**Comment by bretg** [comment]
We don't support VMAP at this point. Prebid Server supports video pods as described in http://prebid.org/prebid-video/video-overview.html What company are you with? Maybe you can get them to join Prebid.org? We could use more video-focused member companies to help drive the video roadmap and implementation. http://prebid.org/partners/partners.html
