### ISSUE TITLE
Server side Header Bidding integrated with Google Ad Manager (integration via API access)

### ISSUE THREAD

**Issue by manikandangithub** [prebid/Prebid.js#4883]
## Type of issue
Server side header bidding integration via DFP

## Description
I have a scenario where SSHB's(Server-side header bidding) hb_pb value passes into DFP via API and delivers the banners based on the exchange bidding concept. Is there any possibility to achieve this.

**Comment by patmmccann** [comment]
The google product team seems very unlikely to support server side ad server calls, but please let me know if you hear differently.
