### ISSUE TITLE
Timeout reporting is never called

### ISSUE THREAD

**Issue by therazor** [prebid/Prebid.js#489]
We are using the GA analytics adapter with a 1s timeout.
Out of a few million page impressions, we cannot see any prebid timeout event recorded in GA.

The implementation seems to be there, but the [triggering function](https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L703) `sendTimeoutEvent()` is never called.
There are no references in the code other than inside tests.

Anything I'm missing?

**Comment by mkendall07** [comment]
@therazor 
You should add  the `$$PREBID_GLOBAL$$.sendTimeoutEvent();` call into your callback handler on `requestBids()`.

**Comment by therazor** [comment]
I see, that would certainly work, but is there any reason it's not called automatically when a timeout is provided to `pbjs.requestBids` or `pbjs.bidderTimeout`?

Perhaps worth updating the examples?

**Comment by mkendall07** [comment]
I don't recall why it's not hooked it. It might have been dropped accidentally during a refactor. 
If you want you can submit a PR for including this in the callback.

**Comment by therazor** [comment]
I'll submit a PR soon.

Related issue: #272
