### ISSUE TITLE
WHY? -  Error: ENOENT: no such file or directory, open '.../Prebid.js/dist/prebid.min.js'

### ISSUE THREAD

**Issue by jononomo** [prebid/Prebid.js#49]
I did the following:

1. git clone https://github.com/prebid/Prebid.js.git

2. sudo npm install

3. gulp build

![screen shot 2015-09-28 at 2 10 26 pm](https://cloud.githubusercontent.com/assets/5942683/10135023/e57d1fbe-65ea-11e5-9d39-3e703d38aa76.png)

**Comment by mkendall07** [comment]
There seems to be an issue with deleting the dist directory. I've commented it out for now until I can figure out root cause. Can you pull the update and try again?

**Comment by jononomo** [comment]
Thanks - doesn't crash any more now...

![screen shot 2015-09-28 at 3 42 06 pm](https://cloud.githubusercontent.com/assets/5942683/10136994/a05495cc-65f7-11e5-8601-2441f299117c.png)
