### ISSUE TITLE
OneVideoAdapor : Priority Between Vastxml and VastUrl

### ISSUE THREAD

**Issue by DeepthiNeeladri** [prebid/Prebid.js#4910]
Hi Team,

If we send both vastxml and vastUrl, then what's the priority between these two params? Adapter will take which param as the response xml?

**Comment by DeepthiNeeladri** [comment]
@bretg  can u help here

**Comment by bretg** [comment]
@jsnellbaker  - can you do the research here? I'll document the results.

I don't think this has anything to do with OneVideo, but is rather a general question about Prebid core -- what happens if an adapter provides both VastXML and VastURL?

**Comment by jsnellbaker** [comment]
@bretg So in reviewing a few things, I have found the following.  There are different results depending on the type of video bid and the presence of Prebid Cache being used or not, so I created a rough outline of the behaviors:

When `cache` is enabled and video is not `outstream`:
- if `vastUrl` and `vastXml` are both present - there will be a slight bias in prebid core towards using the `vastXml`.
- if either exists, that is fine; Prebid core will handle it.

In our `videoCache.js` file, we check for the `vastXml` and use that.  If it's not detected, we take the `vastUrl` and wrap it in some stock VAST-wrapper code.  The resulting VAST XML (from either route) goes to Prebid Cache, where we'll get back the `videoCacheKey`.

If `cache` was disabled and the bid was not `outstream`:
- if the bid contains both, it should be accepted by Prebid core.  If the pub was using the `dfpAdServerVideo` module in this case, the `vastUrl` will be encoded and stored in the GAM video ad URL under the `description_url` param (this is in place of absent `videoCacheKey`).  The `vastXML` does not appear to be directly used from what I can tell in this scenario. 
- if the bid only contained the `vastXml`, the bid gets rejected by Prebid core.


Regardless of the presence of `cache`, if the bid is `outstream`:
- we primarily check for the existence of a `renderer` object in the `bid` or in the `bidRequest/adUnit`.  If that `renderer` is missing, the bid is rejected.  

The assumption here is that the renderer will presumably read from either the `vastUrl` or `vastXml` (or another custom field unique to the bidder) to understand how to render the video ad.  Outstream bids do not rely on Prebid Cache to help them render.

I hope the above makes sense, please let me know if there are any questions or if anything is unclear.

**Comment by bretg** [comment]
> if vastUrl and vastXml are both present - there will be a slight bias in prebid core towards using the vastXml

Thanks @jsnellbaker - does "slight bias" mean anything? Will it prefer vastXml over vastUrl all the time or only in some conditions?
