### ISSUE TITLE
Prebid.js file conflict

### ISSUE THREAD

**Issue by shilpakal** [prebid/Prebid.js#492]
I am using header bidding ,so placing prebid.js on publisher page in head section.

The same publisher has some other ad servers which is also placing prebid.js on the publisher.

Which is causing conflict, how to solve this issue?

**Comment by ialex** [comment]
@shilpakal the solution is to include all networks into just one configuration, lets say brealtime is has their own script on the page(which includes prebid) and you are including prebid with openx  and pulsepoint, you should ask Brealtime for the tag ids and include them in the script you are configuring and controlling.

**Comment by mkendall07** [comment]
Agree with @ialex. There should really be no reason to run 2 instances of prebid on page. This will cause increased latency and overhead for no reason.
