### ISSUE TITLE
ALL BID ADAPTERS READ THIS: need a map of bidderCodes to vendor ID

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#4924]
As part of #4867 , we need to establish a mapping of bidder code to TCF Global Vendor List ID (GVL ID).

e.g.

appnexus: 32
rubicon: 52
pubmatic: 76
openx: 69
ix: 10

We're asking for everyone's help to self-identify your bidder-code-to-GVL-ID mapping.

Please add a comment to this issue

**Comment by leonardlabat** [comment]
Hello @bretg 

criteo: 91

**Comment by anand-venkatraman** [comment]
pulsepoint: 81

**Comment by smenzer** [comment]
we're a userId module, but here it is for record keeping anyway

id5id: 131

**Comment by pm-harshad-mane** [comment]
Confirming PubMatic: 76.

**Comment by epouradier** [comment]
Verizon Media (`aol`, `onevideo`, `onedisplay`, `onemobile`): 25

**Comment by osazos** [comment]
adagio: 617

**Comment by ptomasroos** [comment]
@bretg How will this work in the case of running an alias for a bid adapter?

**Comment by aleksatr** [comment]
aardvark: 169

**Comment by onaydenov** [comment]
fidelity: 408

**Comment by SublimeLeo** [comment]
sublime: 114

**Comment by jessberman** [comment]
SpotX: 165

**Comment by GeneGenie** [comment]
Adtelligent: 410

**Comment by derdeka** [comment]
@bretg Do you plan to extend the bidder interface to provide such metadata directly from bidders?

**Comment by bretg** [comment]
Yes - it's going to be come part of the spec. See https://github.com/prebid/Prebid.js/pull/5018

**Comment by vedantseta** [comment]
Media.net : 142

**Comment by pycnvr** [comment]
Conversant: 24

**Comment by dpapworth** [comment]
Quantcast: 11

**Comment by jaiminpanchal27** [comment]
Updated all bidders listed in this issue with their GVL ID in https://github.com/prebid/Prebid.js/pull/5018

**Comment by bretg** [comment]
Closing this -- any further updates should be done as part of individual pull requests.
