### ISSUE TITLE
Infinite Scroll - Ads loading on scroll

### ISSUE THREAD

**Issue by priyankabehera** [prebid/Prebid.js#4926]
## Type of issue

This is a question based on the #1266 .

## Description

Hello, I am implementing infinite scroll and on each scroll, 10 more items and 2 ad slots are loading with the same ad name.
All the div are generating dynamically.
For, this if I am using the below code which was provided above then no bid is passing successfully.

dynamic div: div-prebid-test-slot-2

```
pbjs.requestBids({
            bidsBackHandler: function (bidResponses) {
                initAdserver();
            },
            adUnitCodes: ['div-prebid-test-slot-2']  // the magic -- run the auction only for the new div
        });
```
In my case dynamic div : div-gpt-ad-div' + timeStamp
If I am passing the codeName the bids are passing successfully but when we again load more next time it doesn't point to new dynamic ad.

```
pbjs.requestBids({
                                    bidsBackHandler: function( bidResponses )
                                    {
                                        googletag.cmd.push( function()
                                        {
                                            pbjs.setTargetingForGPTAsync( ['/121/Homepage/HP_Refresh'] );
                                          
                                        });
                                    },
                                    timeout: 3000,
                                    adUnitCodes: ['/121/Homepage/HP_Refresh'],
                                    //adUnitCodes: ['div-gpt-ad-div' + timeStamp],
                                });
```
Thank you in advance.

**Comment by bretg** [comment]
Seems like there may be a misunderstanding about how Prebid.js maps AdUnits to GPT ad slots.

pbjs.setTargetingForGPTAsync does this:
```
Loop through AdUnits specified
      Loop through GPT slots
             if the GPT slot name matches AdUnit.code, we found a match. Add this AdUnit's bids to that GPT slot and be done with this AdUnit
             else if the div element ID associated with the GPT slot matches AdUnit.code, we found a match Add this AdUnit's bids to that GPT slot and be done with this AdUnit  
```

So if you're using /121/Homepage/HP_Refresh as the slot name for the refreshed ads, a general pattern for infinite scroll would be:

1) create dynamic div
2) associate that div with GPT slot /121/Homepage/HP_Refresh (var newSlot = googletag.defineSlot('/121/Homepage/HP_Refresh', [[300, 250]], dynamic_div_id).addService(googletag.pubads());
3) call for an auction as usual

Note that on pages where users scroll quickly, some publishers are going one step further: running the auction and putting the results in whatever dynamic div happens to be in view at the time. See the 'customSlotMatching' feature in http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.setTargetingForGPTAsync
