### ISSUE TITLE
event for: auctionEnd (3 actions called but it only displays 2 "auctionEnd" events)

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#494]
So this might be normal operation but i think im missing something here, i have 3 ad units set, they are all showing they got a bid returned but when adx,adsense wins the action i only see 2

"MESSAGE: Emitting event for: auctionEnd"

now in some cases i will see rubicon win all 3 ad units and render the tag and display correctly so im not sure why its not show 3 "MESSAGE: Emitting event for: auctionEnd" 

P.S same behavior in 0.11.0 stable.

INFO: Prebid.js v0.12.0-pre loaded 
pb.js:1 INFO: Invoking pbjs.setPriceGranularity : params :  ["medium"]
pb.js:1 INFO: Invoking pbjs.addAdUnits : params :  [Array[3]]
pb.js:1 INFO: Invoking pbjs.requestBids : params :  [Object]
pb.js:1 MESSAGE: Emitting event for: auctionInit
pb.js:1 MESSAGE: CALLING BIDDER ======= rubicon
pb.js:1 MESSAGE: Emitting event for: bidRequested
pb.js:1 MESSAGE: Rubicon Project bidding complete: 1502
pb.js:1 MESSAGE: Emitting event for: bidAdjustment
pb.js:1 MESSAGE: Emitting event for: bidResponse
pb.js:1 MESSAGE: Emitting event for: bidAdjustment
pb.js:1 MESSAGE: Emitting event for: bidResponse
pb.js:1 MESSAGE: Emitting event for: bidAdjustment
pb.js:1 MESSAGE: Emitting event for: bidResponse
pb.js:1 INFO: Invoking pbjs.setTargetingForGPTAsync 
MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-0 key: hb_bidder value: rubicon
pb.js:1 MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-0 key: hb_adid value: xxx
pb.js:1 MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-0 key: hb_pb value: 0.60
pb.js:1 MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-0 key: hb_size value: 300x250
pb.js:1 MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-1 key: hb_bidder value: rubicon
pb.js:1 MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-1 key: hb_adid value: xxx
pb.js:1 MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-1 key: hb_pb value: 0.40
pb.js:1 MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-1 key: hb_size value: 728x90
pb.js:1 MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-0 key: hb_bidder value: rubicon
pb.js:1 MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-0 key: hb_adid value: xxx
pb.js:1 MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-0 key: hb_pb value: 0.80
pb.js:1 MESSAGE: Attempting to set key value for slot: div-gpt-ad-xxx-0 key: hb_size value: 728x90
pb.js:1 MESSAGE: Prebid auction cleared
pb.js:1 MESSAGE: Emitting event for: auctionEnd
pb.js:1 MESSAGE: Prebid auction cleared
pb.js:1 MESSAGE: Emitting event for: auctionEnd

**Comment by mercuryyy** [comment]
Bump please ;o

**Comment by jaiminpanchal27** [comment]
@mercuryyy 
In current implementation, we have 3 scenarios where we emit this AUCTION_END event. 
1) from requestBids function after timeout occurs
2) when all bids are back
3) if any bid response comes after timeout

This is kind of confusing, AUCTION_END event should be called once only, so we will correct this behaviour in next release. Thanks for notifying this to us.

**Comment by mercuryyy** [comment]
@jaiminpanchal27 i was troubleshooting this for a few hours, i tried running it on 0.11 and 0.12.pre same behavior. 

My main problem is i can't really tell if im loosing impressions. dfp adx,adsense is at 0.6 avg  now only rubicon is bidding out of 8,000,000 actions they reported they bidded on 6,000,000 but only won a fraction of that. (500,000) but their avg cpm for paid bids is 1.4.

So im not sure exactly whats going on but i'll try the next public release and report back. 

Thanks.

**Comment by protonate** [comment]
This should now be resolved in master, closing.

**Comment by GeneGenie** [comment]
This doesn't seem to be fixed in 1.1.1
