### ISSUE TITLE
Custom Price Granularity in 3.0 - Not Applying?

### ISSUE THREAD

**Issue by GLStephen** [prebid/Prebid.js#4968]
## Type of issue
Bug

## Description
Custom price granularity does not appear to be properly working in Prebid 3.0. I know changes were made here to remove the min setting, but build notes said they should not interfere if they continued to exist in configs. Is there some other change around this? I've verified this config works in a 2.x build.

## Steps to reproduce
This config:

```
"priceGranularity": {
  "buckets": [
    {
      "precision": 2,
      "min": 0,
      "max": 0.99,
      "increment": 0.01
    },
    {
      "precision": 2,
      "min": 1,
      "max": 20,
      "increment": 0.05
    }
  ]
},
```

Console log says:

```
Prebid MESSAGE: Using custom price granularity
```

Results in this bidResponse:

```
{....
cpm: 3.044547
...
currency: "USD"
...
pbLg: "3.00"
pbMg: "3.00"
pbHg: "3.04"
pbAg: "3.00"
pbDg: "3.00"
pbCg: "3.04"
...}
```

Results in this targeting:

```
hb_format: "banner"
hb_source: "client"
hb_size: "300x250"
hb_pb: "3.04"
hb_adid: "152686fb652cb6c"
hb_bidder: "appnexus"
```

I would expect:

```
hb_pb: 3.00
```

**Comment by bretg** [comment]
Updated the documentation to reflect this situation:

- API reference
- 3.0 blog post
- The next release notes will highlight the issue

**Comment by wqi1972** [comment]
I test the issue on 2 News Corp websites, for my test I use setting 
```		
pbjs.setConfig({priceGranularity: {"precision":"2","buckets":[{"min":0,"max":0.05,"increment":0.01},{"min":0.05,"max":8.00,"increment":0.05},{"min":8.00,"max":50.00,"increment":0.50}]}});
```
And I can't reproduce the issue.
One example
```
cpm: 0.924415
pbMg: "0.90"
pbHg: "0.92"
pbAg: "0.90"
pbDg: "0.92"
pbCg: "0.90"
hb_pb: "0.90"
```
btw, one website uses prebid.js: v3.1.1, one website uses: v3.9.0

**Comment by GLStephen** [comment]
@wqi1972 set the ranges to not overlap. Set the max of the first bucket .04 and the min of the second to .05. In 2.x it works as expected. In 3.x the behavior diverges. We've definitely verified the issue but the behavior is reliant on the previous treatment of min and max for the second or follow on bucket.

**Comment by wqi1972** [comment]
Got it, and I do reproduce the issue now.
If I am not mistaken, the issue is: if there is no overlap, then the pricing calculation started from previous Max value, instead of current Min Value.
e.g.
```
cpm: 0.725049
pbMg: "0.70"
pbHg: "0.72"
pbAg: "0.70"
pbDg: "0.72"
pbCg: "0.69"
hb_pb: "0.69"
```

**Comment by GLStephen** [comment]
@wqi1972 yes, that's the issue.

**Comment by wqi1972** [comment]
I think I figured it out. Inside src/cpmBucketManager.js, it gets current bucket min value from previous bucket max value.
Change line 92 inside src/cpmBucketManager.js to the following code will fix the issue.
```
      bucket.min = bucket.min || bucketFloor;
```
