### ISSUE TITLE
Skipping invalid request from <bidder>

### ISSUE THREAD

**Issue by mlapeyre3** [prebid/Prebid.js#4976]
## Type of issue
Bug / Question

## Description
Hi, recently we added the support of video adunit to our bidder (see https://github.com/prebid/Prebid.js/pull/4367). However, we had to partially remove the outstream part from our PR (i.e: we only support video instream format). Our bidder is displayed as supporting video format (http://prebid.org/dev-docs/bidders.html#smartadserver).

The problem is when the publisher wants to configure a multi-format adunit (http://prebid.org/dev-docs/examples/multi-format-example.html). If he sets both a banner and a video outstream mediatypes, then we will see the following WARNING in the console:
`WARNING: Skipping invalid request from smartadserver. Request type undefined must be GET or POST`
And none of the bidRequest, either from the banner or the video outstream type, are sent. We would expect the outstream bidRequest to be skipped but the banner one to be sent correctly. How can we proceed here?

## Steps to reproduce
* Go to one of the test pages
* Open the console
* See the WARNING log
* See that no requests are sent to smartadserver.com/prebid/v1

## Test page
* https://www.parismatch.com/Actu/Sante/Epidemie-de-coronavirus-Il-faut-eviter-que-tous-les-gens-qui-toussent-se-ruent-aux-urgences-1670895?pbjs_debug=true
* https://expansion.mx/?pbjs_debug=true
* https://www.quien.com/?pbjs_debug=true

### Expected results
* Multi-format adUnit fires a call corresponding to the banner mediatype to our endpoint smartadserver.com/prebid/v1
* The calls corresponding to the video outstream mediatype are not sent

### Actual results
* No calls are sent (neither the banner or the video outstream one)

## Platform details
* Prebid.js 3.4.0+

## Other information
* https://github.com/prebid/Prebid.js/pull/4367

**Comment by theighost** [comment]
Hi,

I am having the same issue, did this get solved?
