### ISSUE TITLE
Change `bidResponse.adId` to `bidId`

### ISSUE THREAD

**Issue by protonate** [prebid/Prebid.js#499]

**Comment by CarsonBanov** [comment]
@mkendall07 Can we close this in favor of https://github.com/prebid/Prebid.js/issues/509 ?  Also, is there any way to re-remind the adapter maintainers to use the signature seen here: https://github.com/prebid/Prebid.js/pull/567/ (`bid = bidfactory.createBid(1, bidObj);`)?  That would help everyone out and move towards a standardized approach for all adapters.

**Comment by mkendall07** [comment]
@CarsonBanov Yeah I think we can do that... 

@protonate I forget the intent behind this... what was the reason?

**Comment by protonate** [comment]
The two issues are related but not duplicative. #509 is to inform bidder adapter maintainers that it can and should be the way to relate bid requests and responses. #499 is an internal core code refactor to change the property name of a bid response ID (`adId`) to match the property name of a bid request ID (`bidId`).

**Comment by CarsonBanov** [comment]
Thanks for the clarification.  I think it makes sense to keep this one open then.  Hopefully https://github.com/prebid/Prebid.js/issues/509 will be done by the adapter maintainers sooner rather than later!

**Comment by mkendall07** [comment]
bump @protonate  gonna do this?

**Comment by protonate** [comment]
@mkendall07 I think we should hold off on this. Bid responses have an `adId` which fits with the targeting key `hb_adid`, and we are not going to change the targeting key name, so may as well leave bid response ID as `adId`. Closing.
