### ISSUE TITLE
pbjs.getBidResponses() returns same bids after 1hour

### ISSUE THREAD

**Issue by JulienVerkest** [prebid/Prebid.js#4991]
## Type of issue
bug

## Description
I've an ad on a webmail page with refresh system: a setInterval function with a timer set at 40s which execute a window.pbjs.requestBids method. When the user stays 1 hour on the page same bids request are sent... Curious... 

## Example

 If I store all the bids sent by the pbjs.getBidResponses() method during 1 hour,  two last adId and requestId are the same.

```
bids: Array(1)
bidderCode: "ix"
adId: "996d610944cb721"
requestId: "96081179cdd1297"

bids: Array(1)
bidderCode: "ix"
adId: "996d610944cb721"
requestId: "96081179cdd1297"
```

## Platform details
Prebid 2.44.7 Chrome Firefox

**Comment by sumit116** [comment]
Hi @JulienVerkest, can you provide more info to reproduce this like the publisher page?

**Comment by jaiminpanchal27** [comment]
Closing as we could not reproduce this and no response from reporter. Please reopen if you have more information
