### ISSUE TITLE
TCF 2.0 Support for Legacy v2.x

### ISSUE THREAD

**Issue by EMXDigital** [prebid/Prebid.js#4994]
## Type of issue
Question

## Description
Looking for plans for TCF 2.0 support.  Will it be on v2.x legacy, or only on v3.x?

## Steps to reproduce
N/A

## Test page
N/A

### Expected results
N/A

### Actual results
N/A

## Platform details
N/A

## Other information
N/A

**Comment by bretg** [comment]
@EMXDigital - Definitely only on 3.x

What's driving you to want to stay on 2.x -- some adapter that hasn't ported?

**Comment by EMXDigital** [comment]
Our concern for 2.X is for some of our publisher partners that have been unable to update yet due to limited resources on their development teams. 

CCPA coverage has been enough for some of those partnerships on 2.X, but with TCF it will force those integrations to need to move up to 3.X which is a large jump (12+ versions) to have to ingest. We understand the desire to sunset the legacy 2.X functionality, but we wanted to make sure there was no chance of v2.X supporting TCF v2 before messaging that everyone will need to update in order to stay compliant with privacy frameworks.

We saw #5001 come in which is a change request that could greatly improve the pain points we've been seeing in the market.

**Comment by bretg** [comment]
We aren't going to port TCF2 to 2.x. Closing this issue.
