### ISSUE TITLE
utils.setCookie needs to use Secure with SameSite=none

### ISSUE THREAD

**Issue by goosemanjack** [prebid/Prebid.js#5011]
## Type of issue
Bug

## Description
When a cookie is specified as 'none' for a value of SameSite the cookie should automatically be written with the Secure flag. Currently this produces a warning in Chrome as below:

digiTrustIdSystem.js:89 A cookie associated with a resource at http://prebid.local/ was set with `SameSite=None` but without `Secure`. It has been blocked, as Chrome now only delivers cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.

## Steps to reproduce
Using the DigiTrust test page "integrationExamples/gpt/digitrust_simple.html" you will get the above warning. This is due to how utils.setCookie is behaving.

## Test page
"integrationExamples/gpt/digitrust_simple.html" in source tree

### Expected results
No warning. Cookie written with Secure option.

### Actual results
Warning of impending doom.

**Comment by goosemanjack** [comment]
I have submitted a PR that makes this change in the new storageManager module.
#5064 
For reference:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

**Comment by bretg** [comment]
Closing this issue since the PR has been opened and partly reviewed.
