### ISSUE TITLE
Bug: no syncs for aliases

### ISSUE THREAD

**Issue by GeneGenie** [prebid/Prebid.js#5014]
- [x] Bug

## Description
Bug related to this [PR](https://github.com/prebid/Prebid.js/pull/4435):

## Steps to reproduce
Start auction with any aliased bidder e.g brealtime
Use any alias bidder in auction. 

### Expected results
getUserSyncs should be triggered
### Actual results
Syncs are not called for any aliased adapters

**Comment by goremachine** [comment]
I can confirm this issue. Weirdly enough we noticed an issue today and investigated it, but it took us 2 hours longer to figure out that it is indeed the aliases.
Tested it with 2.42.0 and everything works fine, but with everything current, also 3.x, both user defined aliases as well as adapter defined aliases don't work. They never appear in the queue for creating sync pixels or iframes.

**Comment by GeneGenie** [comment]
original  PR was intended to add "uniq only syncs" which is in general a good idea but in broke the   limitSyncsPerBidder  concept, maybe it's a good idea to move original changes to separate module which will use   bidResponseHook with notice that it will disable limitSyncsPerBidder  feature, or support this feature :)

**Comment by katedye** [comment]
@GeneGenie or @goremachine is it that aliased bidders will not drop a pixel/sync or that they will not access the cookies that already exist? For instance, if a publisher had only emx and not appnexus, would the call to the alias EMX send the proper cookies? My apologies if i'm using the wrong verbage here.

**Comment by GeneGenie** [comment]
@katedye  no syncs for aliases at all. 
The code checks "If bidderCode is an alias, then do nothing"

**Comment by GeneGenie** [comment]
Why is it stale? I vote for rolling back these changes https://github.com/prebid/Prebid.js/pull/4435

**Comment by bretg** [comment]
@gglas to discuss with the team and figure out a path-forward

**Comment by GeneGenie** [comment]
Hello @bretg, any news about this?

**Comment by gglas** [comment]
hey @GeneGenie we have discussed internally and are sharing thoughts with the larger group - expect updates this week

**Comment by gglas** [comment]
hey @GeneGenie this was resolved in https://github.com/prebid/Prebid.js/pull/4879
