### ISSUE TITLE
Bug: Universal creative issue related to new google host  

### ISSUE THREAD

**Issue by GeneGenie** [prebid/Prebid.js#5026]
## Type of issue
- [x] BUG bro

## Description
Hello my dear friends, it seems that google tests new domain or performs features AB testing in host other than **tpc.**
constant.safeframe.googlesyndication.com

It's happening in 2-3% of loads, and for some reason there is a default hardcoded value in Universal creative   that refers to "tpc.googlesyndication"   instead of window.location.host   as a source target host

## Steps to reproduce
Refresh a page with dfp setup dozen times

<img width="1417" alt="Screen Shot 2020-03-24 at 18 54 18" src="https://user-images.githubusercontent.com/1539907/77455650-cc039c00-6e02-11ea-903f-b2ba50880472.png">

**Comment by bretg** [comment]
@jaiminpanchal27 or @idettman - I know we're getting ready for a PUC release soon - any chance we can get this one in?

**Comment by smenzer** [comment]
Any updates on this?

**Comment by bretg** [comment]
We've become aware of a situation that's going to drive this change -- probably as a fire drill. @harpere to post a proposal soon.

**Comment by harpere** [comment]
addressed in this PR:  https://github.com/prebid/prebid-universal-creative/pull/104

**Comment by lanceloti** [comment]
I've created a log in ucTag.RenderAd try/cath and I'm receiving this error somethimes: "TypeError: Cannot read property 'postMessage' of undefined"

**Comment by bretg** [comment]
@lanceloti - please open a new issue with whatever details you might have - a test page would be ideal.
