### ISSUE TITLE
Blacklisting domains

### ISSUE THREAD

**Issue by estavillo** [prebid/Prebid.js#5031]
## Type of issue
Question

## Description
We're receiving a lot of traffic from domains that we don’t want to serve our ads in, we would like to have a blacklist that would need to be loaded externally (in order for it to be updated without having to upgrade prebidjs) We want to stop bids coming from those websites, without having to make a call to our backend servers, the blacklist will be a static file.

Has anyone had a similar situation? What would be the best approach to accomplish this?

**Comment by bretg** [comment]
This is out of scope for Prebid.js at this point. In general, domain suppression is an SSP function -- please work with your bidders. Issue #3115 tracks the general enhancement in this area.
