### ISSUE TITLE
Question: utils.isSafariBrowser includes iOS-Chrome and iOS-FireFox

### ISSUE THREAD

**Issue by r-ishigami** [prebid/Prebid.js#5033]
## Type of issue

Question

## Description

utils.isSafariBrowser regular expressions include `iOS x Chrome` and `iOS x FireFox` .
Is it a specification?

https://github.com/prebid/Prebid.js/blob/7c456268913024c77b72aa0d0b0230b0d509aba4/src/utils.js#L817-L819

- iPhone Chrome UserAgent

```
Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/80.0.3987.95 Mobile/15E148 Safari/604.1
```

- iPhone FireFox UserAgent

```
Mozilla/5.0 (iPhone; CPU OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/23.0  Mobile/15E148 Safari/605.1.15
```

## Proposal

```javascript
export function isSafariBrowser() {
  return /^((?!chrome|android|crios|fxios).)*safari/i.test(navigator.userAgent);
}
```

## Relation

https://github.com/prebid/Prebid.js/issues/3095

**Comment by bretg** [comment]
Thanks @r-ishigami - PR opened, you're welcome to review.

**Comment by r-ishigami** [comment]
Thanks, @bretg :-) Reviewed it.
