### ISSUE TITLE
The RegExp of webpack config in the README is wrong

### ISSUE THREAD

**Issue by pinkiebala** [prebid/Prebid.js#5038]
## Type of issue
README typo

## Description
In `Usage (as a npm dependency)` > `With Babel 7:`

``new RegExp(`\\${path.sep}prebid\.js`),`` is trying to match `/prebid.js`,
but this regex will output like this: `/\/prebid.js/`,
the `.` here will match any charactor, not character `.` literally .

``new RegExp(`\\${path.sep}prebid\\.js`),``, two backslash,  is the correct pattern.
This will output as `/\/prebid\.js/`

### Expected results
`/\/prebid\.js/`

### Actual results
`/\/prebid.js/`

**Comment by jsnellbaker** [comment]
Created a PR for this fix.  Thanks for the report.
