### ISSUE TITLE
Using an alias with prebid server does not appear to work

### ISSUE THREAD

**Issue by josephtyler** [prebid/Prebid.js#5041]
## Type of issue

Bug (possible)

## Description

I have a set up where I'm using triplelift's adapter for display (client side). I'm trying to then create an alias of the triplelift adapter, called tripleliftVideo, for video (s2s).

The issue I'm seeing is that the s2s request references our arbitrary alias name, not the bidders name. 

Example:

![image](https://user-images.githubusercontent.com/436729/77793944-45300880-7028-11ea-9db0-f76b8b6ead61.png)

We're obviously not getting any bids in this scenario, and my assumption is that the bid request should refer to "triplelift" not "tripleliftVideo".

Here's the relevant code:

```
pbjs.aliasBidder('triplelift', 'tripleliftVideo');
```

and 

```
pbjs.setConfig({
    s2sConfig: {
        bidders: ['tripleliftVideo'],
        ....
    }
});
```

## Test page

https://www.workandmoney.com/s/best-discontinued-breakfast-foods-7053c0df7b224d99?dbg_tests=3lvideo-enabled&cb=1

If you visit this test page, you'll see a request made to appnexus' s2s endpoint that references "tripleliftVideo".

### Expected results

Bid responses.

**Comment by bretg** [comment]
Setting the alias in Prebid.js will cause it to be routed to the local triplelift adapter. Instead of that, let Prebid Server route to the alias. Try this:

```
pbjs.setConfig({
    s2sConfig: {
        bidders: ['tripleliftVideo'],
        ....
        extPrebid: {
            "aliases": {
                 "tripleliftVideo": "triplelift"
             }
        }
    }
});
```

Remove the call to pbjs.aliasBidder()

Assuming this works for you, will document it somewhere.

**Comment by khatibda** [comment]
ok we're trying and will revert, thanks

**Comment by khatibda** [comment]
i think this actually worked (can't be 100% sure because we have other problems in tandem, but i'm like 90% sure so far). thank you.

**Comment by bretg** [comment]
Cool. Will close it out. Re-open if needed. I've updated the Pub API doc on prebid.org with this scenario.
