### ISSUE TITLE
Live intent id system issue with storageManager

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#5048]
## Type of issue
bug, question

## Description
We have introduced storageManager with this PR https://github.com/prebid/Prebid.js/pull/5018. I have updated all the bidders, user id modules in the PR. For now I am skipping all the tests as they are failing and I need more info to understand how you are using utils here https://github.com/prebid/Prebid.js/blob/master/modules/liveIntentIdSystem.js#L86 so you can update to use storage manager. 

Also I have removed findSimilarCookies function since Prebid approved the usage of live-connect module. Let me know if that needs to be added again. 

## Other information
@melgenek @jankoulaga https://github.com/prebid/Prebid.js/pull/4803

**Comment by jankoulaga** [comment]
Hey @jaiminpanchal27 live-connect-module expects any object with the same signature are your storage manager(https://github.com/liveintent-berlin/live-connect/blob/master/src/handlers/storage-handler.js#L6). If you could just add `findSimilarCookies` you can just pass the storage manager to live-connect constructor, and that would be all.

**Comment by jankoulaga** [comment]
@jaiminpanchal27 let us know if you need any help!

**Comment by jaiminpanchal27** [comment]
@jankoulaga I have included your changes in my PR and tests are also passing. Please do test on the page after this release. 
I would also request you to add your GVL ID.

**Comment by bretg** [comment]
which PR @jaiminpanchal27 ?

**Comment by jaiminpanchal27** [comment]
@bretg I did change as part of https://github.com/prebid/Prebid.js/pull/5018. Here is the commit https://github.com/prebid/Prebid.js/pull/5018/commits/74e38b7eaff8c47a1f1abf6aff8ddca7d0904f25

**Comment by bretg** [comment]
This PR has been merged. Closing the issue.
