### ISSUE TITLE
CircleCI pipelines - assess impact

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#5071]
CircleCI announced they are introducing pipelines to free projects https://discuss.circleci.com/t/rollout-of-pipelines-functionality/34651
We need to make sure this is compatible with our plan/workflow.

**Comment by sumit116** [comment]
Hi @mkendall07 , I went through the docs and found that there are two ways for us to enable pipelines. We can go with either of them: 
1. We add a configuration in config.yml file. I have already raised a PR with the change (https://github.com/prebid/Prebid.js/pull/5119)
2. Upgrade circleci from 2.0 to 2.1 which by deafult has pipeline features enabled.

Please let me know which way can we proceed? Also, we would need to change the project settings on circle ci UI to see the new UI with pipelines enabled.

**Comment by sumit116** [comment]
Fixed with https://github.com/prebid/Prebid.js/pull/5119.
