### ISSUE TITLE
Pubmatic

### ISSUE THREAD

**Issue by wingman80** [prebid/Prebid.js#508]
Hi,

Pubmatic informed us that the parameter "kadpageurl" should be implemented inside prebid.

I didn't found anything in the dev-guide and/or in the Pubmatic Bidder-Params.

Anyone solved this issue?

Cheers

**Comment by mkendall07** [comment]
I've not heard of this param. Are you able to get more information from Pubmatic?

**Comment by mkendall07** [comment]
Please reopen if you have more info.

**Comment by tr-coull** [comment]
Not sure if you figured this out but we have done it by adding _window.kadpageurl_ where _window.pm_pub_id_, _window.pm_optimize_adslots_ and _window.pm_async_callback_fn_ are in the pubmatic adapter, currently around here https://github.com/prebid/Prebid.js/blob/master/src/adapters/pubmatic.js#L56

You will then see 'kadpageurl' on the request that goes out to http://gads.pubmatic.com/AdServer/AdCallAggregator
