### ISSUE TITLE
Load more issue in rendering Ad

### ISSUE THREAD

**Issue by priyankabehera** [prebid/Prebid.js#5084]
## Type of issue

This is a question and a request as well.

## Description

There is a site where I am implementing the infinite scroll through ajax. The site is in WordPress. The site is https://sneakernews-com-develop.go-vip.co/?pbjs_debug=true. 

Whenever I load more, the setTargeting event fire but pbjs.renderAd doesn't fire and no ad are rendered. In the network as well the key, value is not getting set in the server request call.

Can anybody help me here with what is went wrong?

## Steps to reproduce

https://sneakernews-com-develop.go-vip.co/?pbjs_debug=true. 

1. Check-in chrome browser
2. Go to console
3. Scroll down and load more
4. New prebid will load but it will not show the ad.

**Comment by pansensoyi** [comment]
Did you try to refresh the slots?

**Comment by priyankabehera** [comment]
> Did you try to refresh the slots?

Yes, I have tried to refresh the slots.

**Comment by priyankabehera** [comment]
I am adding my code which is used for after load more ajax.
