### ISSUE TITLE
YieldMo optimization opportunity.

### ISSUE THREAD

**Issue by DecayConstant** [prebid/Prebid.js#5098]
I was investigating a Chrome performance profile, looking for bottlenecks in my own code, but I noticed this in a Prebid `callBids` call.  YieldMo's own `buildRequests` is **much** slower than any other bid adapter.  It's caused by the DOM manipulations that occur in the `isSuperSandboxedIframe()` function.

I don't know what that's for and if it's really necessary, but could you reorder the checks that happen in `getEnvironment()` so that the most common results are checked for first so you avoid the additional unnecessary checks for the less common environments? Or is the order of those checks important?

<img width="1663" alt="Caramel_Chicken_-_Vietnamese_Caramel_Chicken_-_Rasa_Malaysia" src="https://user-images.githubusercontent.com/718653/78820416-5fa9a080-799d-11ea-8542-e83d76e94ae2.png">

https://github.com/prebid/Prebid.js/blob/9eec929dfc67eeb04604987edfa1e78633f43bea/modules/yieldmoBidAdapter.js#L222-L244

**Comment by snapwich** [comment]
@HolzAndrew ^

**Comment by mglowackiym** [comment]
Thank you for surfacing this. We will review internally and evaluate possible solutions.

**Comment by HolzAndrew** [comment]
@snapwich @DecayConstant I have alerted my team to this and we are adding it to our roadmap to address. Thank you!
