### ISSUE TITLE
Teads Bid Adapter Error

### ISSUE THREAD

**Issue by res-io** [prebid/Prebid.js#5106]
## Type of issue
Bug

## Description
The teads Bid Adapter emitted an uncaught error when parsing their bidRequest

## Steps to reproduce
Compile teads with prebid.js > 3.0

### Expected results
Get bids back from the adapter

### Actual results
The exception in the screen

## Platform details
FF, Chrome

## Other information
Screenshot
![image](https://user-images.githubusercontent.com/2357752/78995071-db445280-7b41-11ea-9590-7036b518d5e8.png)

Maybe @valsouche from Teads could help here

**Comment by res-io** [comment]
I think it will be fixed here:
https://github.com/prebid/Prebid.js/pull/5122/commits
Waiting for approval.

**Comment by valsouche** [comment]
Hello, 
We are on it.
You can use the 3.13 version to fix your problem, it was introduce in the 3.14. 
There is no difference but the TCF v2.

Thanks for feedback !

**Comment by smenzer** [comment]
looks like https://github.com/prebid/Prebid.js/pull/5122 was merged. Can we close this one out?

**Comment by res-io** [comment]
Yes the issue has been resolved.
