### ISSUE TITLE
[Question] Regarding Britepool Identifiers

### ISSUE THREAD

**Issue by pm-shashank-jain** [prebid/Prebid.js#5115]
## Type of issue
Question  

## Description
Q.1 Does the identifiers(aaid dtid idfa ilid etc.) mentioned in the description are constant values for a publisher and where will publisher get these Ids from ?
Q.2 Does the list of identifiers tend to change ? 

## Other information
Identifier as per below mentioned docs : `Where identifier in the params object is the key name. At least one identifier is required. Available Identifiers aaid dtid idfa ilid luid mmid msid mwid rida ssid hash`
http://prebid.org/dev-docs/modules/userId.html#britepool

**Comment by smenzer** [comment]
@pm-shashank-jain It may be worth reaching out directly to Britepool for more details on their solution - looks like their contact info is prebid@britepool.com.
