### ISSUE TITLE
Prioritized bidder list within timeout

### ISSUE THREAD

**Issue by manhhailua** [prebid/Prebid.js#512]
I want to make a list of bidder with priority as order. Such as:
`pbjs.bidderOrder(['appnexus', 'aol'...])`
Within timeout, appnexus ad will be render even if aol bids have higher cpm. If there is no bid response from appnexus within timeout, aol ad will be render...
Can I do this with prebid.js?

**Comment by mkendall07** [comment]
No, this isn't possible directly today. If you want to, I would suggest reviewing all the bids from http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.getBidResponses and manually sending the "winning" bid based on your own logic.
