### ISSUE TITLE
[Question]: Supporting two Bidder Codes is it possible in Prebid Adaptor

### ISSUE THREAD

**Issue by DeepthiNeeladri** [prebid/Prebid.js#5125]
## Type of issue
We need to Change our Bidder code to 'oneVideo' to 'verizonMediaVideoExchange' 

## Description
The problem is we can't do this change right away I am thinking of 2 approches here let me know do we have problem from pre bid side.
Approach 1 :  Change Bidder code to 'oneVideo' to 'verizonMediaVideoExchange' 
eg: In version 3.15.2 we made the change so till version 3.15.1 we can support Bidder code  'oneVideo'  right ?

Approach 2: Support both Bidder code  'oneVideo'  and 'verizonMediaVideoExchange'  is it possible to support both?

## Steps to reproduce

https://github.com/prebid/Prebid.js/blob/master/modules/oneVideoBidAdapter.js

**Comment by bretg** [comment]
You can support both codes with the "alias" feature. No need to rename your file. There are a number of bidder adapters that do this already. See for instance https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js and https://github.com/prebid/Prebid.js/blob/master/modules/gamoshiBidAdapter.js 

On the documentation side, you should open a separate Pull Request against https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders. See https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/cleanmedia.md for instance -- it has a metadata line "aliasCode: gamoshi" linking that alias to the actual code that implements it.
