### ISSUE TITLE
Aol bidder, hb_bidder key value not showing in reports but other bidder do.

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#513]
This might have an effect on other operations of the script but when i run a key value report on dfp i dont see hb_bidder=aol reporting but i do get ads render for aol and reporting on aol UI

while other bidder are reporting in dfp key value report. see attachment image.

also when debugging console does show "Setting key value hd_bidder=aol"  so i have absolutely no idea why dfp wont report it but will report other bidders. 

![screen shot 2016-08-10 at 6 17 23 pm](https://cloud.githubusercontent.com/assets/7463132/17573403/2d28a90a-5f28-11e6-9659-1799a4290ff9.png)

**Comment by mkendall07** [comment]
@mercuryyy 
Do you set the key manually? Reason I ask is because you copied `hd_bidder=aol` - notice h**d** and not h**b**

**Comment by mercuryyy** [comment]
yeah that my typo, i do see the key set in console as hb_bidder=aol 
im using default

`    var pbjs = pbjs || {};
    pbjs.que = pbjs.que || [];

    pbjs.que.push(function() {
        pbjs.setPriceGranularity("medium");
    });`

**Comment by mercuryyy** [comment]
Ok looks like this solved the problem.

need to manually add the key value input in dfp, hb_bidder was set to "free form" but aol was not added.
see attached image.

![screen shot 2016-08-11 at 11 06 40 am](https://cloud.githubusercontent.com/assets/7463132/17593423/d4bb1794-5fb3-11e6-8bfa-b18783ef26b3.png)

**Comment by mkendall07** [comment]
Great! Thanks for sharing.
