### ISSUE TITLE
Advanced Size Mapping module doesn't build through website.

### ISSUE THREAD

**Issue by harterc1** [prebid/Prebid.js#5130]
## Type of issue
Website bug / Build error

## Description
If you try to build through http://prebid.org/download.html with the "Size Mapping" module checked, the downloaded `prebid.X.js` file claims the build is broken.

## Steps to reproduce
1. Go to http://prebid.org/download.html
2. Check "Size Mapping" under "Modules"
3. Hit the "Get Prebid.js!" button
4. The downloaded `prebid.3.16.0.js` file will be only a few bytes and will include something like:
```
{"error":"Prebid file not built properly","requestId":"e670b416-483f-468e-b8f2-eac82bbb8264"}
```

**Comment by bretg** [comment]
Thanks for the bug report - fixed.
