### ISSUE TITLE
pbjs.requestBids() fails if digitrust saved object has null for data

### ISSUE THREAD

**Issue by maxim-novikov** [prebid/Prebid.js#5141]
## Type of issue
bug

## Description
If digitrust module is enabled and initialization is failed, local stored object stores null as 'data' variable. pbjs.requestBids() function fails encountering it.

## Steps to reproduce
Run prebid-enabled page with digitrust module enabled and configured on clean Firefox browser (to ensure digitrust failure). Reload page, so that digitrust stored object applies before first pbjs.requestBids() call. Error message appears on the console. 

## Test page
https://www.warhistoryonline.com/videos/digitrust.fail.v0.html?pbjs_debug=true

## Platform details
Prebid.js 3.16+

## Other information
While the issue is clearly observable on the latest Firefox, it appears to happen on the latest Chrome as well, provided the digitrust initialization fails for whatever reason, so one would assume it's browser-independent.

![exhibit a](https://user-images.githubusercontent.com/4518331/79685633-e6cf0200-8242-11ea-803a-d2947dd111f1.png)
![exhibit b](https://user-images.githubusercontent.com/4518331/79685634-e7679880-8242-11ea-9d3f-5c0396f899ec.png)

**Comment by samtingleff** [comment]
@goosemanjack please take a look

**Comment by goosemanjack** [comment]
Somehow this slipped me. I will take a look.

**Comment by goosemanjack** [comment]
Had to clear some items off my plate. Tomorrow looks promising to work on this.

**Comment by goosemanjack** [comment]
(From Sam) not sure if it is the same issue, but #5141 provides a public test page at https://www.warhistoryonline.com/videos/digitrust.fail.v0.html?pbjs_debug=true

**Comment by goosemanjack** [comment]
There was a null check missing in the call chain. A PR has been submitted:
https://github.com/prebid/Prebid.js/pull/5333
