### ISSUE TITLE
Not able to genrate prebid.js file.

### ISSUE THREAD

**Issue by wandrzejczak** [prebid/Prebid.js#5152]
## Type of issue
I'm not able to generate the Prebid JS file from https://prebid.org/download.html.
The website generates file with code:
`{"error":"Prebid file not built properly","requestId":"b15a5a9e-d523-49bb-b0a0-9b21965fc813"}`

## Steps to reproduce
On Chrome, Firefox, Edge try to select AppNexus adapter and download.

### Expected results
Prebid JS file? :D

### Actual results
`{"error":"Prebid file not built properly","requestId":"b15a5a9e-d523-49bb-b0a0-9b21965fc813"}`

## Platform details
On Chrome, Firefox, Edge try to select AppNexus adapter and download.

**Comment by bretg** [comment]
Are you selecting any other adapters? This is working for me to build PBJS 3.18 and 3.17 with the AppNexus adapter.

**Comment by bretg** [comment]
@wandrzejczak - are you still having this problem?

**Comment by wandrzejczak** [comment]
I've just checked and I don't have a problem.
Everything looks ok now.

**Comment by wandrzejczak** [comment]
I've just checked and I don't have a problem. 
Everything looks ok now.

**Comment by unbracketed** [comment]
I am seeing these errors since yesterday.  I've tried with different versions in the 8.x series.  I'm selecting three adapters (Criteo, IndexExchange, Rubicon) and the Google analytics module.

**Comment by unbracketed** [comment]
@bretg I appreciate you taking a look.  I'm still getting errors, trying with v8.37.0:

https://docs.prebid.org/download.html?modules=consentManagement%2CconsentManagementGpp%2CconsentManagementUsp%2CenrichmentFpdModule%2CgdprEnforcement%2CgppControl_usnat%2CgppControl_usstates%2CgptPreAuction%2CcriteoBidAdapter%2CixBidAdapter%2CrubiconBidAdapter%2CgoogleAnalyticsAdapter

Result:

`{"error":"Prebid file not built properly","requestId":"f53fe0f3-3ac6-40a7-a1e2-973a14eeec37"}`

**Comment by bretg** [comment]
@unbracketed - the Google Analytics module was removed in 8.0. https://docs.prebid.org/dev-docs/pb8-notes.html
