### ISSUE TITLE
Prebid Var - timeToRespond is x2 value then the network ms respond time

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#519]
Please see attached images

Note, second image is the rubicon "fastlane" json file in console network tab i cut the image like that so i dont get howled by @mkendall07

So you can see network ms is at 400ms to get the response from rubicon but prebid timeToRespond is reporting 800 RESULTING is loss of actions bidding 

tested on a chrome with all extension off. 

![screen shot 2016-08-11 at 3 36 48 pm](https://cloud.githubusercontent.com/assets/7463132/17602266/e4d69420-5fd9-11e6-8008-c7ccab50c3c2.png)
![screen shot 2016-08-11 at 3 37 46 pm](https://cloud.githubusercontent.com/assets/7463132/17602274/eda7daf0-5fd9-11e6-8700-63a760e14876.png)

**Comment by mkendall07** [comment]
The time to respond is total time it takes from the initial request to load the bid responses. I can't see from the screen shot but there should be 2 requests (or more) to rubicon for bids. 

![image](https://cloud.githubusercontent.com/assets/1870166/17602520/f6bc823e-5fda-11e6-930d-379d95769de8.png)

Red is the library and yellow is the actual bid requests. The timeToRespond is the summation of this time.

**Comment by mercuryyy** [comment]
what you see in the screenshot is the fastlane json the "ads.rubiconproject.com/header/xxxxx.js" was loaded from cache still took 25ms so even together i still 300-350ms off the mark 


![screen shot 2016-08-11 at 3 58 47 pm](https://cloud.githubusercontent.com/assets/7463132/17602925/cb3ac81c-5fdc-11e6-8a80-d9e1c469ac5e.png)

**Comment by mkendall07** [comment]
ok, can you drop the other bidders and see if that improves? I suspect it's just getting bogged down processing other responses.

**Comment by mercuryyy** [comment]
It improved but still about 200ms off the mark

**Comment by mkendall07** [comment]
@mercuryyy can you share your test page (email is my profile). Thanks

**Comment by mercuryyy** [comment]
@mkendall07 also notice aol in network "adtech" filter 120-130ms and in prebid 350ms

**Comment by mkendall07** [comment]
I profiled this on a page without any content and only 1 bidder and the timeToRespond was about 5ms off. So I believe the functionality is recording in reality what is happening on the page and due to the fact of all the other JS on page it's slowing down significantly the time between initial request and when recording the response. The code is here if you want to take a look: https://github.com/prebid/Prebid.js/blob/master/src/bidmanager.js#L88

**Comment by mercuryyy** [comment]
Thanks!  I'll keep at it to see why the other js lagging it off I'm only loading jqeury and a 4kb js but it makes sense adding another 300 ms from the head to page load
