### ISSUE TITLE
Pull Request not being followed up or merged

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/Prebid.js#5198]
## Type of issue
PR not being merged.

## Description
I have a a PR (#5151) that was approved by Matt Kendall pretty quickly after being submitted, but after that nothing has happened. Tagging and commenting doesn't help and it has been in limbo for 12 days now. I suspect Mr Kendall is sick or busy with other things, but I don't really know how to escalate this thing other than posting this issue. I'm afraid I'm looking at missing yet another release now.

Terribly sorry if this was just due to lack of time or resources.

**Comment by mkendall07** [comment]
No need to open a separate issue. We get to all the PRs eventually. The problem with this particular PR is that already approved it so I was not receiving pings. Sorry about that.
