### ISSUE TITLE
[Question] Creating a PR for a new RTD module.

### ISSUE THREAD

**Issue by ydennisy** [prebid/Prebid.js#5205]
## Type of issue
Question

## Description
I would like to understand the process to add a new module to this project.

Our module could use a very similar implementation to `browsi` as a `rtdModule`, is there currently a process for this - or shall we make a PR following a the current `browsi` structure both here and in the documentation repository? 

PS. We would also be happy to contribute to the project and take on https://github.com/prebid/Prebid.js/issues/4610 

Thanks in advance,
Dennis

**Comment by bretg** [comment]
Appreciate the offer here, but there's a project starting to take a pretty good shape. Hope to release a spec for public comment in the next couple of weeks.

Closing this issue, go ahead and ping #4610 weekly for progress reports.
