### ISSUE TITLE
gulp test --file doesn't work

### ISSUE THREAD

**Issue by smenzer** [prebid/Prebid.js#5211]
## Type of issue
bug

## Description
I'm trying to use `gulp test --file 'XXX' to make the testing process more efficient (rather than running all +5k tests every time I make a small change to my test file). Depending on the file I select, I get different error messages, but it always fails.

## Steps to reproduce
- `gulp test --file 'test/spec/api_spec.js'` produces 
```
Uncaught ReferenceError: require is not defined at test/spec/api_spec.js:1:14
```

- `gulp test --file 'test/spec/adUnits_spec.js'` produces 
```
Uncaught ReferenceError: require is not defined at test/spec/adUnits_spec.js:2:16
```

- `gulp test --file 'test/spec/modules/userId_spec.js'` produces 
```
Uncaught SyntaxError: Cannot use import statement outside a module at test/spec/modules/userId_spec.js:1:1
```

- `gulp test --file 'test/spec/modules/criteoIdSystem_spec.js'` produces 
```
Uncaught SyntaxError: Cannot use import statement outside a module at test/spec/modules/criteoIdSystem_spec.js:1:1
```

### Expected results
I would expect that only the tests contained in the specified test file would be run AND that they would work just like when running `gulp test` (which does work fine)

### Actual results
Errors (as shown above)

## Platform details
```
$ npm version
{ 'prebid.js': '3.19.0-pre',
  npm: '6.4.1',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '4',
  nghttp2: '1.39.2',
  node: '8.16.2',
  openssl: '1.0.2s',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.23.2',
  v8: '6.2.414.78',
  zlib: '1.2.11' }
```

## Other information
I've also noticed other minor issues with `gulp` that lead me to believe we need a review and cleanup of the entire `gulpfile.js`. For example, I also get module errors when running `gulp test --watch` that never appear when doing individual `gulp test` runs. Happy to provide more details if necessary, but thought I'd start with the most annoying issue first and propose an overhaul before creating separate issues.

Let me know if any more information is needed here. Thanks!

**Comment by sbrosinski** [comment]
I can confirm the above issues and I'm struggling with them as well. In the meantime I'm helping myself by changing my test code from `it('testcase')` to `it.only('testcase')`, which will then only run this single test and not all 5k, but it seems we still have to compile all code, which takes a considerable amount of time anyway.

**Comment by raz-adroll** [comment]
Iit's due the `preprocessors` only works for `'test/test_index.js'` in the `karma.conf.maker.js`

https://github.com/prebid/Prebid.js/blob/334cb01b3753cb9e9c331e52be7f59c59fc01538/karma.conf.maker.js#L138-L140

It should be:
```
preprocessors: {
  [file ? file : 'test/test_index.js']: ['webpack', 'sourcemap']
},
```

I make a PR to fix this, but not sure how to add testing or coverage for this.

**Comment by pm-harshad-mane** [comment]
This bug is fixed now, closing the issue.
