### ISSUE TITLE
IX Video Requires the size array to match the video ad unit's or it will error & warn

### ISSUE THREAD

**Issue by webdevinci** [prebid/Prebid.js#5229]
## Type of issue
Bug with room for enhancement.

## Description
After implementing IX to our display ads, we were able to see the request to their endpoint go through and auction complete successfully. Yet, an error of no bids & warning of malformed IX ad unit showed in the console (with Prebid debug on).

**The current issue** is when implementing IX with prebid video. After much investigation, the video ad unit should match exactly the size array required in the IX parameters.

## Steps to reproduce
1. Have a Prebid video ad unit with size: [640, 480] (4:3) and an IX bid param with size [640, 480] (16:9). You will see the error & warning with ?pbjs_debug_mode=true

## Test page
https://www.comicbookmovie.com/news/#zeusdebug;prebiddebug for instance, you will see display errors here, yet the network request works. If dimensions don't align in video (on a local test page of mine) the same error & warning will show in the console, but the network request will not show, hence it has no chance to return a bid since the bid wasn't executed.

### Expected results
It should just work if the numbers don't match the main ad unit's size.

If it were up to me, I would have a size array in each partner's module be optional, and be the one that overrides the main video prebid ad unit. And if size isn't in the module's params, **use the ad unit's size.**

### Actual results
If size arrays don't match, no bid responds. 

## Platform details
Prebid 3.10.0 (All client side)
Chrome 81
Mac OSx Sierra

## Other information
**My ultimate suggestion** is to do what many did with the Prebid 2 upgrade, remove any 'size' property from modules and use the main one from the ad unit using the module to avoid confusion and time-consuming-debugging for errors like this one.

Thanks in advance!
@ix-prebid-support  @ix-prebid-development

**Comment by kizzard** [comment]
hi @webdevinci , we are determining what the future of multi-size support will look like in the IX adapter. This may alter the current behavior. We will update this ticket with more information soon.
