### ISSUE TITLE
Keywords Issue with appnexusAst

### ISSUE THREAD

**Issue by Midgorn** [prebid/Prebid.js#523]
Hello,

I use appnexusAst adapter (in order to have no iframe creative), but it seems when i pass keywords (in order to add query string targeting), query param targeting doesn't work .

**Comment by mkendall07** [comment]
@Midgorn 
Can you show the bidder configuration you are using? You most likely need to add the `'keyword` object into the params for it to work.

**Comment by Midgorn** [comment]
For example  : 

`{
        			code: 'pave_passback',
        			sizes: [[300,250], [300, 600],[300,1000]],
        			bids: [{
            			bidder: 'appnexusAst',
            			params: {
               				placementId: '5687329',
                            keywords : {'myc':'46025827'}
            			}
        				}]
                }`

**Comment by mkendall07** [comment]
@Midgorn Are you using the latest build from master? We pushed an update yesterday that would have temporally removed this functionality. It should be back in master shortly.

**Comment by Midgorn** [comment]
Yes i use the last from master and i saw that this functionality was removed, so i built my own from master, added 

`tag.keywords = bid.params.keywords;`

In appnexusAst adapter, in callBids function.

I can see the keyword object pass in the post request but it seems that it not work.

with this configuration 

`{ code: 'pave_passback', sizes: [[300,250], [300, 600],[300,1000]], bids: [{ bidder: 'appnexusAst', params: { placementId: '5687329', keywords : {'myc':'46025827'} } }] }`

I should have a creative, but the prebid return nothing :/ 

(you can see that it here : http://ib.adnxs.com/tt?id=5687329&size=300x600&myc=46025827)

**Comment by mkendall07** [comment]
Ok sorry about that. We will fix it in a day or so. If you really want to roll your own implementation - they should be passed like this:
```
"keywords": [{
                    "key": "key1",
                    "value": ["value1", "value2", "value3"]
                }, {
                    "key": "key2",
                    "value":  ["abc123"]
                }]
```

**Comment by Midgorn** [comment]
I try to passed it like it but doesn't  work , even keyword  param passed in request : 
![capture d ecran 2016-08-12 a 16 46 21](https://cloud.githubusercontent.com/assets/1137844/17626076/fcabab6c-60ab-11e6-99c4-17cc5e67794c.png)

**Comment by mkendall07** [comment]
You have to actually pass `key` and `value` - see above example.

**Comment by Midgorn** [comment]
Yes sorry. But didn't work too : 

![capture d ecran 2016-08-12 a 17 07 10](https://cloud.githubusercontent.com/assets/1137844/17626838/4b88c406-60af-11e6-82a3-23b3c0872219.png)

![capture d ecran 2016-08-12 a 17 08 50](https://cloud.githubusercontent.com/assets/1137844/17626874/75ee0576-60af-11e6-9dfa-5b24a31758c7.png)

**Comment by mkendall07** [comment]
This should be working in master now. Usage is:
```
params : {
  keywords : { 
    key : 'value',
    key2 : 'value2'
  }
}
```
