### ISSUE TITLE
TCFv2 loading race condition

### ISSUE THREAD

**Issue by brondsem** [prebid/Prebid.js#5232]
## Type of issue
bug

## Description
When prebid.js is set to load after the CMP loads, then the addEventListener is registered too late and misses the "tcloaded" event.  (TCFv1 proactively calls getVendorConsents, no events).

If prebid.js set up the cmp addEventListener sooner than pbjs.requestBids that could help, but race conditions still could exist in theory.  Calling getTCData proactively at the same time as addEventListener seems like it could work, but then it runs the risk of getting partial/incomplete data before the CMP has consent data ready.

A stop-gap solution I am using is to set `consentManagement.gdpr.cmpApi = 'static'` and provide the consentData directly since in my case I know prebid runs after CMP.  But that is obviously not a good general solution for anyone else.  It also doesn't update consent data if a user changes their consent, and then further auctions run.

The only reliable solution I can think of is for prebid to continue to rely on addEventListener and provide a mechanism for publishers to trigger the internal `v2CmpResponseCallback` as well, so they can be guaranteed to be called.  Something perhaps like this in publishers sites before prebid & cmp start running:
```
// publisher listens for consent events right away
__tcfapi('addEventListener', 2, function(tcData, success) {
    if(success && (tcData.eventStatus === 'tcloaded' || tcData.eventStatus === 'useractioncomplete')) {
        // and then passes them to prebid when prebid is loaded
        pbjs.que.push(function () {
            // prebid.js would have to expose this:
            pbjs.consentManagement_v2CmpResponseCallback(tcData, success);
        });
    }
});
```

## Steps to reproduce
* have a consent manager with TCFv2 set up
* have the page set up to get consent first and **then** run prebid
* visit page, and accept or reject CMP if its your first visit

## Test page
code: https://jsbin.com/leloquj/edit?html,output
output (without iframes): http://output.jsbin.com/leloquj/

### Expected results
* GDPR details in bid requests

### Actual results
* one `Received a response from CMP` log message, but its eventStatus is undefined, so prebid.js does not do anything with it.  Honestly not sure what this event represents, but the "tcloaded" event definitely is already come and gone.
* wait a little while, then:
```
WARNING: CMP workflow exceeded timeout threshold. Resuming auction without consent data as per consentManagement config.
```
* and no GDPR consent string in bid requests

## Platform details
prebid 3.19.0 with consentManagement module

## Other information
#4664 describes a case where prebid needs to load *after* CMP, as an example of why this order of execution is necessary

**Comment by jaiminpanchal27** [comment]
@brondsem Question about the cmp in use here. 
I tested the test page shared by you. So you are starting prebid as soon as the tcloaded event is emitted by cmp. Now when prebid reads the config and see that consent management is configured, it adds the callback on event listener here https://github.com/prebid/Prebid.js/blob/master/modules/consentManagement.js#L155

The callback is executed immediately but the eventStatus is undefined at this stage. I think tcdata.eventStatus should be tcloaded as that is the current state of cmp.

**Comment by brondsem** [comment]
Hi.  I read the [spec about addEventListener](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#addeventlistener) and its not clear to me what should happen when `addEventListener` is called after the load event already happened.  Some CMPs might not even run the callback at all because the spec says:

> The callback will be invoked with the TCData object as an argument whenever the TC String is changed and a new one is available

I could inquire with our CMP provider, but wouldn't be surprised if other CMPs behaved similarly or might not run a callback at all since no changes are occurring.

**Comment by jaiminpanchal27** [comment]
Thanks @brondsem. Let us know what CMP provider say. 

We tested our test page with two cmp's and callback was invoked immediately.
- Test page in this https://github.com/prebid/Prebid.js/issues/5292. 
- https://cmp.sirdata.com/#/. I cannot share the page as it is paid version. We were given the scripts to test internally.

**Comment by brondsem** [comment]
Waiting for response from my CMP still.

I was able to test Quantcast's free CMP it currently fires "tcloaded" right away, which is incorrect when there is no previous consent string.  So can't even accurately test this scenario with that CMP.  https://output.jsbin.com/cicirek/?pbjs_debug=true

So in general may have to deal with varying implementations from different CMPs :/

**Comment by andyblackwell** [comment]
Yeah Quantcast has had several bugs since they deployed their TCF 2.0 version, I’ve been working back and forth with them for a few weeks with issues, it’s not in a usable state yet. Waiting for a fully working version so we can implement. They currently have a feature request open with the IAB to get around some of their issues with the core cmp api.

**Comment by brondsem** [comment]
Response from our CMP:
> unfortunately the TCF spec is not 100% clear in this case what the CMP should return when addEventListener is called. I'll talk to to IAB working group and let you know.

**Comment by EskelCz** [comment]
We're seeing the same issue. Was this somehow resolved?

**Comment by brondsem** [comment]
I am still using the "stop-gap" workaround I mentioned in my original post, no resolution I'm aware of.

**Comment by gglas** [comment]
@jsnellbaker would you mind having a look at this?

**Comment by patmmccann** [comment]
@brondsem could you disclose which cmp you are using? Prebid might have a relationship with them

**Comment by gglas** [comment]
Should we just be opening an issue on the TCF board?  https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/issues 

this doesn't seem like a prebid issue to me

**Comment by patmmccann** [comment]
It appears your cmp might not be performing to spec

 "The addEventListener callback shall be immediately called upon registration with the current TC data,"  

https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#addeventlistener

**Comment by gglas** [comment]
@brondsem based on what we're seeing this seems to be a CMP issue, we'll be closing this issue.  For reopening, we recommend having your CMP reach out and participate.
