### ISSUE TITLE
Few adapters not reading user id data from bidRequest.userId object

### ISSUE THREAD

**Issue by Fawke** [prebid/Prebid.js#5234]
## Description

We added [GDPR Enforcement module](http://prebid.org/dev-docs/modules/gdprEnforcement.html) for TCF v2.0 recently. One of the features of this module states that, if a user doesn't consent to purpose 4, Prebid won't send userId data to the adapter. We request all the adapters listed here to use standard Prebid api/code when available and not add their own custom code to access user id. 
Purpose 4 implementation details are still in discussion and enforcement rules may change.

User Ids include - **user.buyeruid**, **user.id**, **user.ext.eids**, **user.ext.digitrust**  and **device.ifa**, **device.macsha1**, **device.macmd5**, **device.dpidsha1**, **device.dpidmd5**, **device.didsha1**, **device.didmd5**

Find more details about TCF enforcement [here](https://docs.google.com/document/d/1fBRaodKifv1pYsWY3ia-9K96VHUjd8kKvxZlOsozm8E/edit#heading=h.t62kkttx488d)

Prebid.js provides all configured userIds to adapters under the `bidRequest.userId` / `bidRequest.userIdAsEids` object. To enforce purpose 4, these two objects will not be passed to the adapters if consent is not given.

In light of this, all adapters will have to read user id information from either of the two objects mentioned above.

Few adapters have been found populating user id values from other sources. If you are a maintainer of any of the adapters listed below, please submit a PR in which you read the values from `bidRequest.userId` or `bidRequest.userIdsAsEids` object.

###### 1. user.buyeruid
- deepintentBidAdapter.js - Copies this value from `bid.params`. Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/deepintentBidAdapter.js#L122) line. @sourabhg
- luponmediaBidAdapter.js - Copies this value from `bidRequest.crumbs.pubcid`. Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/luponmediaBidAdapter.js#L200) line. @adxpremium @EfdalMustafic
- seedingAllianceBidAdapter.js - Copies this value from `bidRequest.crubms.pubcid`. Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/seedingAllianceBidAdapter.js#L130) line. @SeedingAllianceTech

###### 2. user.id

- deepintentBidAdapter.js - Copies this value from `bid.params`. Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/deepintentBidAdapter.js#L121) line. @sourabhg
- luponmediaBidAdapter.js - Generates a new id on the client side. Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/luponmediaBidAdapter.js#L196) line. @adxpremium @EfdalMustafic

###### 3. digitrust ID

I've few few bid adapters read the value of Digitrust ID from the window object. Should they not read it from `bidRequest[0].bidder[].userId.digitrust` ?

- gumgumBidAdapter.js - Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/gumgumBidAdapter.js#L95) line @mikewilso @jddeleon
- luponBidAdapter.js - Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/luponmediaBidAdapter.js#L322) line @adxpremium @EfdalMustafic
- pubmaticBidAdapter.js - Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/pubmaticBidAdapter.js#L596) line @pm-harshad-mane
- rubiconBidAdapter.js - Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/rubiconBidAdapter.js#L836) line @robertrmartinez
- sonobiBidAdapter.js - Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/sonobiBidAdapter.js#L342) line @JonGoSonobi
- prebidServerBidAdapter - Getting Digitrust Id from the config. Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/prebidServerBidAdapter/index.js#L249) line

###### 4. user.ext.eids

- prebidServerBidAdapter.js - Reads this value from `bids.0.userIdAsEids`. Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/prebidServerBidAdapter/index.js#L593) line

###### 5. user.ext.digitrust

 - Refer to **3 digitrust ID**

###### 6. device.ifa

- platformioBidAdapter.js - Reads this value from `bid[].params`. Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/platformioBidAdapter.js#L245) line @barslev @varashellov
- windtalkerBidAdapter.js - (Almost identical code to platformioBidAdapter.js) Reads this value from `bid[].params`. Check [this](https://github.com/prebid/Prebid.js/blob/3513d38c120072380c0f4a2376b95f50bb957224/modules/windtalkerBidAdapter.js#L245) line @barslev

Related PR - https://github.com/prebid/Prebid.js/pull/5228

**Comment by pm-harshad-mane** [comment]
Thanks @Fawke , we are working on it, code changes are in QA

**Comment by jddeleon** [comment]
Tagging @susyt for GumGum adapter.

**Comment by goosemanjack** [comment]
Hold off on any further DigiTrust integration work. We are evaluating some extensive changes that may be breaking.

**Comment by robertrmartinez** [comment]
I have created an internal ticket for the Rubicon bid adapter changes.

**Comment by patmmccann** [comment]
fyi @ix-prebid-development

**Comment by ix-prebid-support** [comment]
@patmmccann 

While it is correct that the IX Adapter reads Authenticated Signals made available on the page by the IX Identity Library javascript, the IX Identity Library is already fully privacy compliant with GDPR (TCF 1 and 2) as well as CCPA. Therefore, it's our position that:

* When we source IDs from the IX Identity Library - these IDs are subject to consent guidance that is collected and consumed by the IX Identity Library
* When we source IDs from the Prebid user module - these IDs are subject to consent guidance that is collected and consumed by Prebid

This is in alignment with the desire of Publishers who choose to use the IX Identity Library as well as Prebid.
