### ISSUE TITLE
Intent to Implement: Media Type Video OpenRTB Conventions

### ISSUE THREAD

**Issue by ehoch** [prebid/Prebid.js#5237]
Right now most video configurations are being duplicated across Prebid bidders via bidder params. We'd like to standardizing the various OpenRTB video configuration options (minduration, mime types, api, etc) to all be configured at the media type declaration instead of bidder.

While currently some bidders do read this from the media type, it's not a required standard. We first want to update documentation to standardize how everything should be declared and then work with various bidders and possibly make this required for 4.0.

For example, OpenRTB video parameters would be set here:
```
   mediaTypes: {
            video: {
                context: 'instream', // or 'outstream'
                playerSize: [640, 480],
                api: [1],
                mimes: ['video/mp4'],
                ...
            }
  }
```

This has all been discussed as part of the Prebid Video task force, but let's get the discussion open!

My current proposal for OpenRTB configuration options to support would be to support:

`mimes`
`minduration`
`maxduration`
`protocols`
`startdelay`
`placement`
`skip`
`skipafter`
`minbitrate`
`maxbitrate`
`delivery`
`playbackmethod`
`api`
`linearity`

Anything I'm missing? Let me know before we begin to write this up.

**Comment by patmmccann** [comment]
I think this covers what we use at Cafemedia, do you think we should add 'linearity' ?

**Comment by ehoch** [comment]
@patmmccann Not sure what the demand will be for non-linear, but added!

**Comment by jaiminpanchal27** [comment]
@ehoch Would there be any enforcement programmatically in Prebid core for this ? We do not do any kind of checks for bidder params. 
I am understanding that this would just be a recommendation and would come under module rules which will be out very soon.

**Comment by ehoch** [comment]
@jaiminpanchal27 I don't think we should. My suggested plan would be entirely just a change in documentation and rules.

**Comment by robertrmartinez** [comment]
@ehoch @jaiminpanchal27 

Have we decided the result of this?

Do we want to implement some sort of `required` params for video objects like we do with `native`

Or will this be handled with offline documentation?

**Comment by patmmccann** [comment]
I think the plan is to handle through documentation; perhaps with a pr changing http://prebid.org/dev-docs/bidder-adaptor.html#building-the-request

**Comment by mike-chowla** [comment]
@robertrmartinez 

We discussed this on the video task force call this morning and concluded for 4.0 we shouldn't make anything required since adapters may or may not need a parameter even if OpenRTB requires them.  We'll revisit for 5.0. 
 
> Do we want to implement some sort of `required` params for video objects like we do with `native`
> 
> Or will this be handled with offline documentation?
