### ISSUE TITLE
cmpApi: 'static' error CMP returned unexpected value

### ISSUE THREAD

**Issue by Nicola1976** [prebid/Prebid.js#5241]
With prebid version 3.18.0, as described [here](https://github.com/prebid/Prebid.js/issues/3179) I'm trying to use the "static" cmpApi to avoid waiting for the cmp to be ready to make prebid calls after the first user interaction and consent agreement. In practice, if the "euconsent" cookie is already available on the page I switch to cmpApi "static" and pass the cookie value with consent string directly to prebid:

**FIRST ACCESS**
```
consentManagement: {
                                                cmpApi: 'iab',
                                                timeout: 9000,
                                                allowAuctionWithoutConsent: false
                                            }
```

**AFTER CONSENT AGREEMENT**
```
consentManagement: {
                                              gdpr: {
                                                cmpApi: 'static',
                                                allowAuctionWithoutConsent: false,
                                                consentData: {
                                                  getConsentData: {
                                                    'gdprApplies': true,
                                                    'hasGlobalScope': false,
                                                    'consentData': 'BOy7pQTOy7pQTDaABBITDA-AAAAuh7_______9______9uz_Ov_v_f__33e8__9v_l_7_-___u_-33d4u_1vf99yfm1-7etr3tp_87ues2_Xur__79__3z3_9pxP78k89r7337Ew_v-_v-b7BCPN_Y1kyA'
                                                  },
                                                  getVendorConsents: {
                                                    'metadata': 'BOy7pQTOy7pQTDaABBITDA-AAAAuh7_______9______9uz_Ov_v_f__33e8__9v_l_7_-___u_-33d4u_1vf99yfm1-7etr3tp_87ues2_Xur__79__3z3_9pxP78k89r7337Ew_v-_v-b7BCPN_Y1kyA'
                                                  }
                                                }
                                              },
                                              rubicon: {
                                                  singleRequest: dfpTagConf.prebid.sra
                                              }
                                            } 
```

But I have an error in console: "ERROR: CMP returned unexpected value during lookup process. Canceling auction as per consentManagement config." From the [documentation](http://prebid.org/dev-docs/modules/consentManagement.html#tcf-v11-examples), however, it really seems to be passed in this way. Do I have to elaborate it somehow in order not to have the error?

![image](https://user-images.githubusercontent.com/14162566/82028437-ec7b0480-9695-11ea-9214-ae79d6be7d79.png)

thanks a lot
nicola

**Comment by fcurti** [comment]
Set gdprApplies': true, also on getVendorConsents object

**Comment by Nicola1976** [comment]
Ok thanks Fabio! it seems work fine.

So in this way can I call prebid.js immediatly 
without waiting for my cmp  IAB compliant to be ready. 

It is correct?

**Comment by Nicola1976** [comment]
this is what I set now:

```
consentManagement: {
                                              gdpr: {
                                                cmpApi: 'static',
                                                allowAuctionWithoutConsent: false,
                                                consentData: {
                                                  getConsentData: {
                                                    'gdprApplies': true,
                                                    'hasGlobalScope': false,
                                                    'consentData': euconsentStored
                                                  },
                                                  getVendorConsents: {
                                                    **'gdprApplies': true,**
                                                    'metadata': euconsentStored
                                                  }
                                                }
                                              },
                                              rubicon: {
                                                  singleRequest: dfpTagConf.prebid.sra
                                              }
                                            }
```

**Comment by fcurti** [comment]
It is quiete correct i think.
Static cmpApi setup avoid to bidder adapters to call __cmp function to retrieve the user consentData.
consentData is provided by your code.

**Comment by Nicola1976** [comment]
Thanks a lot Fabio.

**Comment by fcurti** [comment]
Welcome Nicola!

**Comment by Nicola1976** [comment]
Hi Fabio! just another perfomance question about thi issue.
With cmpApi configuration actived (in static mode if euconsent already present) the requests tracked by the platforms implemented in prebid recorded a drop between 20% and 30%, slightly less then without cmp object in prebid configuratio.

Have you ever heard of such problems and know if there is a way to optimize latency with cmpApi activated?

Thanks a lot
nicola

**Comment by fcurti** [comment]
Hi Nicola,
using the static cmpApi should reduce the latency inherited of __cmp.
I do not expect a drop as you measured.
It sounds strange,I think you must proceed with more detailed investigations about this drop.

**Comment by Nicola1976** [comment]
Thanks Fabio, yes it is true. With static cmpApi I have less latency then with IAB cmpApi, but the 30% drop is between 

**with cmpApi iab/static in config object** 

```
pbjs.setConfig({
                    bidderSequence: 'random',
                    enableSendAllBids: true,
                    priceGranularity: 'high',
                    "currency": {
                        "adServerCurrency": "EUR",
                        "granularityMultiplier": 1,
                        "defaultRates": {
                            "USD": {
                                "EUR": 0.90
                            }
                        }
                    },
                    consentManagement: {
                      gdpr: {
                        cmpApi: 'static',
                        allowAuctionWithoutConsent: false,
                        consentData: {
                          getConsentData: {
                            'gdprApplies': true,
                            'hasGlobalScope': false,
                            'consentData': euconsentStored
                          },
                          getVendorConsents: {
                            'gdprApplies': true,
                            'metadata': euconsentStored
                          }
                        }
                      },
                      rubicon: {
                          singleRequest: dfpTagConf.prebid.sra
                      }
                    }
                  });
```

**end without cmpApi in config**

```
window.pbjs.setConfig({
            bidderSequence: 'random',
            enableSendAllBids: true,
            priceGranularity: 'high',
            "currency": {
              "adServerCurrency": "EUR",
              "granularityMultiplier": 1,
              "defaultRates": { "USD": { "EUR": 0.90 } }
            },
            rubicon: {
              singleRequest: dfpTagConf.prebid.sra
            },
          })
```
 
I think a good solution to balance could be to anticipate the  prebid.js request, but it is not related to cmp latency.

**Comment by bretg** [comment]
@Nicola1976 - please help us understand what metric you're measuring. It doesn't make sense that the existence of consentManagement in static mode should change the number of outgoing requests.

However, it could easily change the number of bid responses. The Rubicon exchange is quite strict about GDPR, so a dropoff when gdprApplies is expected.

**Comment by Nicola1976** [comment]
Hi,
we analyzed both impression and request data  Rubicon and Pubmatic.

In both cases it seems that the drop is rather linear (drop of request/responses 20-30%) on both bidder when the cmp is activated.

We are currently testing with allowAuctionWithoutConsent: true, to test if could be a cmp error issue that does not allow some request.

you can check our configuration on this site: https://gazzanet.gazzetta.it/

Thanks a lot

**Comment by Nicola1976** [comment]
Hi @bretg 
we verified that with this configuration (allowAuctionWithoutConsent: true) the requests have no drop. Do you confirm that with allowAuctionWithoutConsent: true in any case the consent is still passed (undefined if there is an error [like described in documentation](http://prebid.org/dev-docs/modules/consentManagement.html#tcf-v11-examples)) and we are therefore compliant with respect to the gdpr? Thanks a lot

**Comment by robertrmartinez** [comment]
@Nicola1976 

By setting `allowAuctionWithoutConsent: true` you are allowing a prebid auction to ALWAYS run, regardless if the user has not selected consent yet, or it was not able to be found by prebid (wether that be an error, or timeout). Prebid will, in these cases, pass `undefined` to bid adapters, and it is up to each bidder to do whatever they see fit as "compliant".

Thus "are we therefore compliant with respect to the gdpr" is a tricky question. And I bet if you polled 100 lawyers, you would get different answers.

And then, if you consider TCF 1 vs TCF 2 versions, you get a difference on what exactly "being compliant" is.

I would recommend reaching out to your own legal team. I do not believe it is a Prebid.org stance to comment on wether or not a type of configuration is "compliant" or not, rather we supply the options for you to set it up as you see fit.

@bretg can probably comment more on this.

But from a technical standpoint, the GDPR module seems to be doing exactly what it is designed to do, so I would consider this issue resolved once you determine how you wish to proceed with your settings.

Let us know if you have any further questions.

**Comment by Nicola1976** [comment]
Thank you so much for the detailed clarification @robertrmartinez. 
We can close the ticket.

Nicola Colombo
