### ISSUE TITLE
pbjs.getAllWinningBids() emtpy after GPT slotRenderEnded event

### ISSUE THREAD

**Issue by fcurti** [prebid/Prebid.js#5242]
## Type of issue
I'm using prebid3.16.0.
I have to get the winner bid creative size using pbjs.getAllWinningBids() when GPT slotRenderEnded event fired.

## Description
Even if i have a winning bids, the pbjs.getAllWinningBids() is empty when slotRenderEnded event fired.
Typing pbjs.getAllWinningBids() in console the object is not empty.

### Expected results
In case of winning bids the pbjs.getAllWinningBids() should not be empty when slotRenderEnded event fired.

**Comment by wqi1972** [comment]
@fcurti I believe the reason why you get emtpy pbjs.getAllWinningBids() is: auctionManager.addWinningBid get called inside renderAd() function, and renderAd() happens after slotRenderEnded event.
You can either get hb_size to get winner bid creative size, or move you code inside slotOnload event.
Code as following:
```		
		googletag.pubads().addEventListener('slotRenderEnded', function (event) {
			console.log('Slot has been rendered:', event.slot.getTargeting('hb_size'));
		});
		googletag.pubads().addEventListener('slotOnload', function (event) {
			console.log('Slot has been loaded:', event.slot.getTargeting('hb_size'));
			var bids = pbjs.getAllWinningBids();
			console.log('on load', bids);
		});
```

**Comment by fcurti** [comment]
Thank you Qi Wu,
I'm having experienced that the 'slotOnLoad" event is not so reactive as we expected.
It depends on the creative loading time.
I found the pbjs.onEvent('bidWon', function(e){} ) and i think that this event handler sould be more reactive.

**Comment by wqi1972** [comment]
Yes, you are correct. `slotOnLoad` is fired when ads creative's iframe fires its load event, it suppose to wait for ads html loading complete, but is not guaranteed.
And `pbjs.onEvent('bidWon', function(e){} )` is for sure works for you. Since inside prebid.js, inside renderAd, the code is:
```        // save winning bids
        auctionManager.addWinningBid(bid);

        // emit 'bid won' event here
        events.emit(BID_WON, bid);
```
`bidWon` event triggers after `addWinningBid` function call. Glad you figured it out.

**Comment by robertrmartinez** [comment]
@fcurti 

Has @wqi1972 helped solve your issue, or do you still wish to keep this open?

**Comment by fcurti** [comment]
Hi @robertrmartinez 
I found the solution using pbjs.onEvent('bidWon', function(e){} )

Of course, using previous version of prebid.js, the pbjs.getAllWinningBids() function, was not empty when GTP slotRenderEnded triggered.

In this time i do not have time to rollback the prebid.js version in order to understand starting from which version this issue appear.

Definetely the ticket can be closed
