### ISSUE TITLE
Sovrn bidding on non existing sizes

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#5246]
is there any known issue with sovrn adapter and V 3.19.0,  i'm getting sovrn bidding and taking imps for ad units where there is no size for the bid they have won with,  such as a 336x280 taking in a unit with only [[970, 90],[970, 250],[728, 90],[468, 60],[320, 50],[320, 100],

its def not the id number, i've checked that a dozen times

![Google_Ad_Manager_-_Delivery_tools](https://user-images.githubusercontent.com/8503167/82057616-886b3700-96bb-11ea-96b7-83d86d0e8bc3.png)

**Comment by smenzer** [comment]
@aprakash-sovrn or @sovrnoss could you help out here, please?

**Comment by jrosendahl** [comment]
We are looking into this issue.  @smenzer can you contact me directly so we can get further details? (jrosendahl@sovrn.com)

**Comment by smenzer** [comment]
@jrosendahl the issue was originally submitted by @spormeon, so he is probably who you want to talk to.

**Comment by robertrmartinez** [comment]
@spormeon @jrosendahl Has this been resolved? Assigned to @jrosendahl to confirm.

**Comment by spormeon** [comment]
John was looking into it on email three weeks ago, not heard a thing from him since.

**Comment by spiroskarathanassis** [comment]
does this issue match with this error ?
Is it open yet ?
<img width="371" alt="Screenshot 2021-02-18 at 2 29 12 PM" src="https://user-images.githubusercontent.com/48492788/108357310-ee11c400-71f5-11eb-90ec-c334fc8c8357.png">

**Comment by gglas** [comment]
@jrosendahl any luck here?  Is it possible this is a sovrn internal config overriding declared sizes from PB?  Additionally, after discussing in Issue review, maybe worthwhile opening a new Issue to potentially build a validation module for bid responses.  @gglas to open issue.

**Comment by jrosendahl** [comment]
@spormeon @gglas Sovrn uses the size that is configured in the Sovrn UI when it determines the size of an ad unit.  I would review the zone configuration in the Sovrn UI.  I do not think that this relates to @spiroskarathanassis issue where it looks like the sovrn bid adapter has not been included in the prebid build.  

When you are having adapter setup issues the best thing to do is to reach out to support@sovrn.com which create a support ticket.

**Comment by spormeon** [comment]
7 months for a reply, gotta be a record? lol

**Comment by ChrisHuie** [comment]
closing issue with above response
