### ISSUE TITLE
prebid.org has been suspended.

### ISSUE THREAD

**Issue by mrpbennett** [prebid/Prebid.js#528]
Not sure who to contact about this but I am getting "You have reached a domain that is pending ICANN verification." when going to the domain prebid.org

**Comment by mkendall07** [comment]
Thanks. We are working with the vendor to resolve.

**Comment by mkendall07** [comment]
Should be restored within 24-48hrs. The archived version is available if needed:  http://web.archive.org/web/20160306140734/http://prebid.org/

**Comment by mkendall07** [comment]
This is resolved.
