### ISSUE TITLE
Instream Video and Banner Ads demo page not working

### ISSUE THREAD

**Issue by zhew1118** [prebid/Prebid.js#5280]
## Type of issue
Instream Video and Banner Ads demo page not working

## Description
We want to follow the logic of http://prebid.org/dev-docs/examples/instream-banner-mix.html but we noticed that the preroll ad is not playing. 

## Steps to reproduce
Visit http://prebid.org/dev-docs/examples/instream-banner-mix.html. 

## Test page
http://prebid.org/dev-docs/examples/instream-banner-mix.html

### Expected results
JW Player plays preroll ad then content

### Actual results
JW Player plays only the content without the preroll

## Platform details
Latest Prebid.js version

## Other information
It seems that ad response is returned correctly. So as the URL returns from pbjs.adServers.dfp.buildVideoUrl. But the JW player is not able to play the ad.

**Comment by bretg** [comment]
Fixed - there was an issue on the ad server side.
