### ISSUE TITLE
TCFv2 consent string issue once prebid in an iframe.

### ISSUE THREAD

**Issue by onaydenov** [prebid/Prebid.js#5292]
## Type of issue
Bug

## Description
TCFv2 does not work properly, does not return the consent string, in a case when prebid is in an iframe, loaded from another domain. It worked with TCFv1
Quantcast Choice CMP used

## Test page
http://myguitar.co/tcf2/test_tcf2.html?pbjs_debug=true

### Expected results
consent_str: COzyttOOzyttOAKACAENAnCMAP_AAAAAACKgF-tX-T5eL2vjO2Zdt5JkaYwfZxyzgOwDhgSIsW4NwIeF7BoGL2MwnBW4JCQAGBAEEgKBAQckHGBcCQAAgIgBiTKMYE2MCzNKBJJAikEbM0FQCCVuHkHSmZCY7068O__zP2BezFZkqXg1jQplCTbagRCmECEcQow.......etc."  

### Actual results
consent_str:  empty for test page

**Comment by smenzer** [comment]
@jaiminpanchal27 could you or someone on your team take a look at this, please?

**Comment by jsnellbaker** [comment]
Hi @onaydenov 
Sorry for the delay here.  I took a look at the test page and I was having some trouble trying to interact with the CMP widget/menu.  It would not load/open for me at all.  

When I debugged the prebid auction, I observed the following log messages:
<img width="1680" alt="Screen Shot 2020-06-01 at 11 19 34 AM" src="https://user-images.githubusercontent.com/31102355/83424014-cd040b80-a3f9-11ea-9bca-db15897fb538.png">

While the CMP object does appear to exist on the parent page (I saw the `__tcfapi` object in the console tab when trying to call it directly), the messages here imply that something may not be functioning 100% with the CMP.  Could you verify with your CMP contacts to verify the setup of the CMP for this page?

**Comment by onaydenov** [comment]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/11557435/83425558-2be37800-a42e-11ea-8c60-f424d754a066.png">
Hi @jsnellbaker 
I'm using a VPN to get CMP work. See screen, right bottom corner, blue banner and script in console responds with the cmp id. Is this what you are trying to see?

**Comment by Josh-G** [comment]
I have debugged this as we are experiencing the same issue with Quantcast. It seems that the Quantcast CMP returns `success: false` when `parameter` is set as null in this msg:
https://github.com/prebid/Prebid.js/blob/66d9e77bacf66c42fc67797325154188c19a3f5f/modules/consentManagement.js#L206-L212

In a test, I removed the parameter entirely, and found the Quantcast CMP successfully processed the command.

**Comment by bretg** [comment]
@onaydenov - may we close this issue now that #5505 is in progress?

**Comment by onaydenov** [comment]
Yes, close it please.
