### ISSUE TITLE
Clarify AMP Support

### ISSUE THREAD

**Issue by GLStephen** [prebid/Prebid.js#5300]
## Type of issue
Feature Request

## Description
AMP pages are supported and the delivery is via Prebid Server. However, the list of Prebid server supported bidders is not the same as those that support AMP. This page seems to have a list, but I'm not sure how accurate it is. The current Prebid documentation does not list AMP support. It would be a good thing to list for clarity.

## Steps to reproduce
Go here:

http://prebid.org/dev-docs/prebid-server-bidders.html

Different than here:

https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-publisher-implementation-guide.md

**Comment by bretg** [comment]
@GLStephen - there's a pretty big difference between the bidders supported by Prebid-Server and which companies are hosting Prebid Servers and offering a managed service for AMP.

So the list in rtc-publisher-implementation-guide is host companies. If someone connects their AMP pages to the AppNexus or Rubicon Prebid Servers, they would be able to work with that host company to connect on the back end to any of the bidders listed in prebid-server-bidders.html

That said, I agree the AMP page at http://prebid.org/formats/amp.html could use more detail. We're in a medium-term project to completely revise the Prebid Server documentation -- AMP will be included as part of that.

**Comment by GLStephen** [comment]
@bretg  I see the distinction on the rtc page now that I've reviewed it a bit more, but I was sort of searching for what would make a Prebid client side adapter *not* work with Prebid AMP through server. I have received feedback that the assumption that a Prebid bidder is supported on server is true for web, but not for AMP.  I'll keep an eye out on the update and contribute as able.

**Comment by bretg** [comment]
@GLStephen wrote:
> I have received feedback that the assumption that a Prebid bidder is supported on server
> is true for web, but not for AMP

Would need more details about the specific case you're dealing with. There is one known scenario, which is ix -- PBS isn't currently sending source.tid for AMP, which they require. This is covered by https://github.com/prebid/prebid-server/issues/1337

Going to close this issue - please open another if you find which specific server adapter doesn't like AMP

@mlapeyre3 wrote:
> Is demand partner same as vendor here?

Different.

Anyone can add their own prebid-server the [AMP RTC vendor list.](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/callout-vendors.js)

Those Prebid Servers can have some or all server-side bid adapters active.
