### ISSUE TITLE
Need a way to track in-stream rendering creative in analytics adapter not supporting vasttrack

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#5308]
## Type of issue
Feature Requirement by PubMatic Analytics Adapter

## Problem:
- Not all analytics adapters can support vasttrack approach mentioned on http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-vast-cache
- vasttrack supports limited params 
- vasttrack does not allow analytics adapter to add additional params
- An analytics adapter should be able to add a tracker using bid.vastImpUrl, even if bid is not being cached

## Current setup:
- Instream video bid is pushed into cache before emitting bidResponse event, thus analytics adapters can’t add their tracker in vast created for the bid
- Also, bidResponse event is not triggered if a bid is pushed into cache https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L460 

## Proposed solution:
- Add an event, preCacheVideoBid,  that will trigger before pushing creative in the cache,
- Analytics adapter will listen to preCacheVideoBid event and will add tracker pixel in bid.vastImpUrl using this event
- Let bid.vastImpUrl be optionally handled as an array in https://github.com/prebid/Prebid.js/blob/master/src/videoCache.js#L62
- Analytics adapters will convert bid.vasrImpUrl to an array if required. So that all bidders will not need to change it to an array

**Comment by pm-harshad-mane** [comment]
@jsnellbaker @bretg @mike-chowla please share your suggestions.

**Comment by mike-chowla** [comment]
We should support error trackers as well.  There's a good case that analytics adapters should be able to insert any tracker defined in the VAST spec (quartiles, etc)

**Comment by bretg** [comment]
Closing issue - released this summer.
