### ISSUE TITLE
How do I debug bidmanager.js from bidmanager_spec.js?

### ISSUE THREAD

**Issue by snapwich** [prebid/Prebid.js#532]
I followed the directions on the README using `gulp test --watch` and I can place the `debugger;` statement in the spec  and step through bidmanager_spec.js code just fine, but as soon as I step into calls from bidmanager.js (which is imported directly from the spec) the code is minified.

The karma runner doesn't seem to be serving any file sourcemaps the way it's currently configured.  I attempted to use the instructions at https://github.com/webpack/karma-webpack/blob/master/README.md to configure webpack to generate inline-source-maps (as karma-webpack doesn't seem to currently support file sourcemaps) and wasn't having much success.

Is there a solution in-place already for debugging a non-minified version of the code inside these specs?

**Comment by mkendall07** [comment]
I believe the issue is actually caused by istanbul instrumentation, not minification. As a work around, you can remove the `istanbul` loader from `karma.conf.js` during tests.

**Comment by snapwich** [comment]
Thank you, that was exactly the problem.
