### ISSUE TITLE
Winning bid comes after refresh

### ISSUE THREAD

**Issue by ademozkur** [prebid/Prebid.js#5325]
## Type of issue
I mostly use default codes. I did not make changes to not much. But, the actual winning bid comes after the ad is refreshed. I created a trial banner from Adform SSP. In the first view comes Google. The trial banner comes after it was refreshed. However, I also found out why this problem was caused. This problem occurs if there is another Google ad on the page. No problem when the page there is only prebid codes.

## Test page
**Only prebid codes:**
http://www.thegeyik.com/only-prebid/

**Prebid codes with another Google ad:**
http://www.thegeyik.com/prebid-with-another-google-ad/

**Comment by wqi1972** [comment]
I believe the trouble is:
prebid bidding code is inside `pbjs.que.push` queue, and GAM ad call is inside windows load event `window.addEventListener('load'`, there is no guarantee that windows load event happens after prebid bidding finish.
When there is another google ad, it impacts javascript execution sequence, so gpt ad call for slot1 get triggered before prebid bidding returns.
I believe the page with only prebid codes might also has trouble, if you load it from different browser or with slow network speed.
I suggest you change code to something like:
```
	   function bidSlot1() {
	       pbjs.que.push(function() {
        	   pbjs.requestBids({
            	   bidsBackHandler: sendAdserverRequest,
               	timeout: PREBID_TIMEOUT
           	});
       	});
       }
       function sendAdserverRequest() {
           if (pbjs.adserverRequestSent) return;
           pbjs.adserverRequestSent = true;
           googletag.cmd.push(function() {
               pbjs.que.push(function() {
                   pbjs.setTargetingForGPTAsync();
               });
               googletag.pubads().refresh([slot1]);
           });
       }
```
so that it will make sure gpt make ad call for slot1 after prebid bidding finish.

**Comment by ademozkur** [comment]
1. 

> I believe the trouble is:
> prebid bidding code is inside `pbjs.que.push` queue, and GAM ad call is inside windows load event `window.addEventListener('load'`, there is no guarantee that windows load event happens after prebid bidding finish.
> When there is another google ad, it impacts javascript execution sequence, so gpt ad call for slot1 get triggered before prebid bidding returns.
> I believe the page with only prebid codes might also has trouble, if you load it from different browser or with slow network speed.
> I suggest you change code to something like:
> 
> ```
> 	   function bidSlot1() {
> 	       pbjs.que.push(function() {
>         	   pbjs.requestBids({
>             	   bidsBackHandler: sendAdserverRequest,
>                	timeout: PREBID_TIMEOUT
>            	});
>        	});
>        }
>        function sendAdserverRequest() {
>            if (pbjs.adserverRequestSent) return;
>            pbjs.adserverRequestSent = true;
>            googletag.cmd.push(function() {
>                pbjs.que.push(function() {
>                    pbjs.setTargetingForGPTAsync();
>                });
>                googletag.pubads().refresh([slot1]);
>            });
>        }
> ```
> 
> so that it will make sure gpt make ad call for slot1 after prebid bidding finish.

Thanks.
However, when I changed the codes in this way, it did not run the bidders. Only Google worked. 
Can you share please JSFiddle demo? For your solution.

Although I use the Default Prebid code, if there is another Google code on the page, the winning bid comes after the refreshed. It doesn't come on the first impression.

**Comment by wqi1972** [comment]
Please push your change to http://www.thegeyik.com/prebid-with-another-google-ad/, let me see where possibly goes wrong.

**Comment by ademozkur** [comment]
> Please push your change to http://www.thegeyik.com/prebid-with-another-google-ad/, let me see where possibly goes wrong.

I did. Can you check please?

**Comment by wqi1972** [comment]
A couple of issues in your new code.
1) you need call 
```       pbjs.que.push(function() {
           pbjs.addAdUnits(adUnits);
       });
```
after 
```
googletag.cmd.push(function() {
  googletag.pubads().disableInitialLoad();
});
```
2) change code
```
       if (!document.querySelector('#slot1').parentElement.querySelector('iframe')) {
           googletag.cmd.push(function() {
               googletag.pubads().refresh([slot1]);
           });
       }
```
to
```      if (!document.querySelector('#slot1').parentElement.querySelector('iframe')) {
		bidSlot1();
      }
```
3) I believe you don't need code
```
       setTimeout(function() {
           sendAdserverRequest();
       }, FAILSAFE_TIMEOUT);
```
anymore.

**Comment by ademozkur** [comment]
> A couple of issues in your new code.
> 
> 1. you need call
> 
> ```
>       pbjs.que.push(function() {
>            pbjs.addAdUnits(adUnits);
>        });
> ```
> 
> after
> 
> ```
> googletag.cmd.push(function() {
>   googletag.pubads().disableInitialLoad();
> });
> ```
> 
> 1. change code
> 
> ```
>        if (!document.querySelector('#slot1').parentElement.querySelector('iframe')) {
>            googletag.cmd.push(function() {
>                googletag.pubads().refresh([slot1]);
>            });
>        }
> ```
> 
> to
> 
> ```
>      if (!document.querySelector('#slot1').parentElement.querySelector('iframe')) {
> 		bidSlot1();
>       }
> ```
> 
> 1. I believe you don't need code
> 
> ```
>        setTimeout(function() {
>            sendAdserverRequest();
>        }, FAILSAFE_TIMEOUT);
> ```
> 
> anymore.

Thanks for all.
I did. But the problem still continues. Can you check please?

**Comment by wqi1972** [comment]
I think I figured out.
In the page, it calls `googletag.enableServices();` twice. And call to `googletag.pubads().disableInitialLoad();` is after first `enableServices`.

**Comment by ademozkur** [comment]
> I think I figured out.
> In the page, it calls `googletag.enableServices();` twice. And the page calls `googletag.pubads().disableInitialLoad();` after first `enableServices`. This doesn't work.
> Which means the ad call on http://www.thegeyik.com/prebid-with-another-google-ad/ get triggered by `googletag.display()`, not `googletag.pubads().refresh()`.
> You need call `googletag.pubads().disableInitialLoad();` before first `googletag.enableServices();`
> 
> Another problem, in the page, it has no definition of `slot1`, so code `googletag.pubads().refresh([slot1]);` doesn't work, since you need load both ad slot, so change it to `googletag.pubads().refresh();` will do.

Thanks for all. I made it from scratch with default codes. And as you said, the problem was solved. First googletag.pubads (). DisableInitialLoad (); needs to take place. But there is a problem like this. It is not always possible for my script to work first order on the site. The site can have its own ads. As an agency, we send extra ads or buy banner areas from the site. In this case, what kind of changes should be made in the codes? If my code works on the page later, how can I run it properly?

Default and new codes:
http://www.thegeyik.com/prebid/

**Comment by wqi1972** [comment]
Try wrap up all your code inside an iframe, so that the ads on site and additional prebid ad you provided run on different pages.

**Comment by ademozkur** [comment]
> Try wrap up all your code inside an iframe, so that the ads on site and additional prebid ad you provided run on different pages.

I did. It really worked. 
But, there is a question I can think of. Is it a problem for Google ads to run in an iframe? After all, it's not the original domain. And do we need to have ads.txt ids in the domain where the code comes from?

**Comment by ademozkur** [comment]
> > Try wrap up all your code inside an iframe, so that the ads on site and additional prebid ad you provided run on different pages.
> 
> I did. It really worked.
> But, there is a question I can think of. Is it a problem for Google ads to run in an iframe? After all, it's not the original domain. And do we need to have ads.txt ids in the domain where the code comes from?

and of course the other ssp's. not only google. for example criteo.

**Comment by wqi1972** [comment]
Good question. I believe yes.

**Comment by ademozkur** [comment]
> Good question. I believe yes.

I emailed you.

**Comment by bretg** [comment]
Are we good here? Please close the issue if resolved. Thanks.

**Comment by ademozkur** [comment]
> Are we good here? Please close the issue if resolved. Thanks.

Yes @wqi1972 solved all problems.
