### ISSUE TITLE
GDPR consent Prebid.js

### ISSUE THREAD

**Issue by Elisa004** [prebid/Prebid.js#5332]
Hi, everybody. 

We are having problems with GDPR consent with Prebid.js
We have implemented everything correctly but by debugging we find two errors (I enclose ss).
Suggestions on how to solve the problem? 
Thanks

![Schermata 2020-06-04 alle 13 02 33](https://user-images.githubusercontent.com/66425759/83768560-3cd6f800-a67f-11ea-9f9d-892c440374d9.png)
![Schermata 2020-06-04 alle 13 02 59](https://user-images.githubusercontent.com/66425759/83768562-3d6f8e80-a67f-11ea-87b3-0095f234e16d.png)

**Comment by bretg** [comment]
@Elisa004 - these look like timeouts, which are more-or-less expected on the first page load.

For both GDPR and CCPA, Prebid.js depends on the output of IAB-defined functions. PBJS will wait a certain configurable amount of time, but a response from those functions comes from the CMP (Consent Management Platform), which in turn depends on the user. You've implemented a CMP, yes?

If you're receiving these timeouts even after the user has interacted with the CMP, then we'll need a test page or at least the configuration you're using.

**Comment by bretg** [comment]
@Elisa004 - is your issue resolved?
