### ISSUE TITLE
Our ci/circleci: build always fails. smartclipBidAdapter #5275

### ISSUE THREAD

**Issue by smartclip-adtech** [prebid/Prebid.js#5335]
## Type of issue
Question

## Description
Our ci/circleci: build always fails.
  350:7  error  Identifier 'sc_smartIntxtStart' is not in camel case  camelcase
 
  351:7  error  Identifier 'sc_smartIntxtNoad' is not in camel case   camelcase
 
  352:7  error  Identifier 'sc_smartIntxtEnd' is not in camel case    camelcase

We can't rename the sc_smartIntxt function to camelcase.
This is a function we use for our outstream player.

What can we do here?
Is there a supporter who can give us some help to join prebid.org?
 

## Steps to reproduce
Pull Request smartclipBidAdapter #5275

**Comment by smartclip-adtech** [comment]
Hi,

thanks.
But now we have another issue.
The adapter is still "in review" -  i don't know why.
Is there anything we have to do now?

Best Regards

**Comment by jsnellbaker** [comment]
@smartclip-adtech I'll grab the PR and give it a review today.

**Comment by jsnellbaker** [comment]
I'm going to close this issue for now since it seems the lint errors were addressed in the PR and the review has started.
