### ISSUE TITLE
add pre-built file on npm

### ISSUE THREAD

**Issue by maruilian11** [prebid/Prebid.js#534]
hi, recently we want to add your lib to https://cdnjs.com, could you please consider adding `./build/dist/prebid.js` on npm package so that we can use npm auto-update to update your lib to cdnjs automatically. 
thank you very mush!

https://github.com/cdnjs/cdnjs/issues/8744

**Comment by mkendall07** [comment]
Sounds like a reasonable request. Is this a requirement of cdnjs?

**Comment by maruilian11** [comment]
we will respect the your decision if you don't want. then we can only add very version manually, and it's hard to add later released version immediately. we strongly recommend you add built file on git repo (we also have git auto-update config) or npm package to keep your lib on cdnjs the latest version.
thank you!

**Comment by mkendall07** [comment]
seems like this isn't something we can easily implement due to the custom build nature of the framework. Closing.
