### ISSUE TITLE
Which adapters are instant signup and/or support smaller publishers

### ISSUE THREAD

**Issue by DunnCreativeSS** [prebid/Prebid.js#5340]
## Type of issue
Question

## Description
Most bidder adapters require a signup process that's not full-serve. Which have full-serve, no review? Which promote small publishers? I just introduced some web apps to http://jare.cloud and my viewership has gone from a handful of visitors a day to ~1000/day, and want to integrate prebid,.js, but don't have the time to google each bidder adapter to see which I can sign up for without hassle.

### Expected results
Integrate prebid.js without hassle.

### Actual results
All of the bidder adapters I looked up have a 'contact us for review' step.

### Suggestion
Have a SSO or one-click-signs-up to all partner bidder adapters.

**Comment by bretg** [comment]
This isn't a request that Prebid.org can help with. There's a good reason that most bidders review content before agreeing to monetize -- they don't want to bid on inappropriate or fraudulent traffic.

It would be fine if someone outside the org were to make such a list.
