### ISSUE TITLE
Proposal - Implement a default outstream renderer 

### ISSUE THREAD

**Issue by agammathur** [prebid/Prebid.js#5341]
## Type of issue
Feature Request

## Background
Currently, Prebid doesn't have a default video player which can be used to play out-stream video ads, in case no renderer has been provided by publisher or demand partners.

## Proposal
We should use open source projects like 'video.js' and 'videojs-vast-vpaid' plugin to implement an out-stream video player. If no renderer has been provided by publisher or demand partner than this player will be used  otherwise there own renderer will be used.

### Expected results
Implementing the out-stream video player in Prebid.js, will allow all publishers and demand partners to monetize the out-stream inventory even when they don't have there own implementation of out-stream video players.

**Comment by mike-chowla** [comment]
I've created a new repo for the Oustream project
https://github.com/prebid/prebid-outstream

**Comment by agammathur** [comment]
Provided the PR (https://github.com/prebid/prebid-outstream/pull/1) for the first phase which can be merged to the https://github.com/prebid/prebid-outstream master branch.

We have created a framework to implement outstream video player using any open-source video player.  At present, we have added Fluid player support in the project and are looking forward to the community for adding new open-source video player support.

**Comment by gglas** [comment]
@agammathur @mike-chowla were we able to submit a docs PR for the PR mentioned above?  I think most of our docs still point to the old renderer.

**Comment by gglas** [comment]
@agammathur @mike-chowla can we close this issue?  Looks like we've made good progress!

**Comment by agammathur** [comment]
@gglas 
Yes, we can close this issue now.
