### ISSUE TITLE
IAS: https://dt.adsafeprotected.com/    cert errors!!!

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#5362]
firstly , sorry for putting this here, bit hoping someone from IAS is here and sees,  there have been cert errors on this domain for over a week now,  I believe it is creating havoc with video ads.

Anyone here got contact with them/   know whats going on:  just look at the amount of errors its throwing lol:

![DevTools_-_www_smokingmeatforums_com__and_B3_Performance_by_Media_Type___Domain_-_District_M](https://user-images.githubusercontent.com/8503167/84375298-41e3fc00-abd7-11ea-84ff-95d9d16eae67.png)

**Comment by bretg** [comment]
Adding @raguilar-ias @bengel-ias @katzhang-ias to take a look
