### ISSUE TITLE
Prebid Video Appnexus + ImaSDK+ Admanager + VAST 

### ISSUE THREAD

**Issue by vitorhenrique123** [prebid/Prebid.js#5367]
## Type of issue
Question/Bug

## Description
I'm using the Appnexus bidder with ima sdk from google + VAST URL's. However, for some reason, 
about 60% of the videos even with the skippable object set to false, deliver with the skipp button anyway

IMASDK: https://developers.google.com/interactive-media-ads/docs/sdks/html5

Do I need to use a client-side apdater officially supported by the prebid?

Could this be the problem?

## Steps to reproduce
`{
        code: 'in-article',
        mediaTypes: {
            video: {
                playerSize: [640, 480],
                context: 'instream'
            }
        },
        bids: [{
            bidder: 'appnexus',
            params: {
                placementId: id,
                video: {
                    skippable: false,
                    playback_method: ['auto_play_sound_off']
                }
            }
        }]
`}

### Expected results
Only video delivery without skip button

### Actual results
about 60% of the videos still coming with a skip button

## Platform details
Prebid.js 3.19.0
All Browsers  

## Other information
Question:
I am also working with VPAID's. If XML comes with a skipp button by default. Could it be that this option is being ignored? Or theoretically only videos without a skipp button should be returned?

**Comment by robertrmartinez** [comment]
Adding @jsnellbaker for appnexus support. Assign as needed.

**Comment by jsnellbaker** [comment]
Hi @vitorhenrique123 ,

Is there a test page available that delivers the ads in question?  I'd like to review the setup (as well as the `placementId` to check in the ad-server) to get a better idea here.
