### ISSUE TITLE
pbjs.markWinningBidAsUsed(adId); for outstream video

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#5368]
Hi

Can this be used as following, so as to mark winning outstream bids used as we are getting discrepancies for outstream with appnexus:  I'm also using 
useBidCache: true  , so will the two work together so as bidcache also work propley? 

pbjs.aliasBidder('appnexus','districtm');
    
 // marks winng video bids as used
    pbjs.markWinningBidAsUsed(adId);
    
    
    pbjs.bidderSettings = {.............

UPDATE:  No it doesn't work basically, it blocks ALL prebid bids and also stops some bidders even loading

should also not i have banner, native and outstream competing on each adunit,  so a bit stumped on how to get mark just a winning outstream bid?

**Comment by robertrmartinez** [comment]
Adding @mkendall07 for an appnexus perspective.

**Comment by Caspervw** [comment]
@spormeon  Yes, it should. 

What happens is that you are using a bidCache and video. Video, unlike display, doesn’t tell Prebid it has been shown on your website. Display uses the Prebid `renderAd` function, which can do the internal administration, while for video you use some VAST parser/player/sdk to show the ad. That player doesn’t tell Prebid what happened. 

The discrepancies arise when you play the same video multiple times. If you don’t mark the video as used, it can “win” the next auction and the one after that etc. etc. Your Ad-server will say you played it 10 times, while AppNexus or any other partner will pay you for 1 impression.

More info see: https://github.com/prebid/Prebid.js/issues/2282
