### ISSUE TITLE
Merge quantumdex and valueimpression adapters

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#5370]
## Description
As found in #5356 The valueimpressionBidAdapter is completely identical to quantumdexBidAdapter except, of course, bidder code. 

@thuyhq has expressed a willingness to merge these adapters at some point, though they're not able to do this at the moment as it will affect their business. 

This issue tracks the open item.

**Comment by robertrmartinez** [comment]
Thank you @thuyhq for taking this!

https://github.com/prebid/Prebid.js/pull/5405
