### ISSUE TITLE
Audience Network throwing CORS error

### ISSUE THREAD

**Issue by NCal** [prebid/Prebid.js#5382]
## Type of issue
Audience Network throwing CORS error

## Description
Noticed audienceNetwork adapter giving me a CORS error all of a sudden in prebid 3.6.0
` No 'Access-Control-Allow-Origin' header is present on the requested resource.`
No other adapter is having this issue.
Is audienceNetwork no longer supported? 

## Platform details
prebid 3.6, macOS, node 10.6

**Comment by dlackty** [comment]
According to [Facebook's annoucement](https://www.facebook.com/business/help/645132129564436?id=211412110064838), since Apr 11 2020, Audience Network no longer fills any ad requests to web and in-stream.

**Comment by robertrmartinez** [comment]
@NCal As @dlackty stated facebook has begun or finished the process of deprecating the aduienceNetwork adapter.

We should be removing (or have already) remove it from future Prebid.js releases.

closing this issue.
