### ISSUE TITLE
setting userid for digitrust on page stops all prebid requests

### ISSUE THREAD

**Issue by tiago-snigel** [prebid/Prebid.js#5393]
## Type of issue
bug

## Description
Until at least prebid 3.14.0 it was possible to set the digitrust id on usersync using the pbjs.setConfig on prebid.js, compile it and then if needed it could be overwritten on the script calling the prebid using the pbjs.setConfig once again. But right now with 3.23.0 it's not possible anymore, I've reviewed a couple of old version 3.22.0 and 3.20.0 and they also suffer with the same problem, everything works until we try to set the digitrust id system config directly on the page, exact same configuration as we had before with the 3.14.0 and even the exact same configuration we set on prebid.js.

## Steps to reproduce
Buiding the prebid with or without digitrust id on usersync, and then calling the prebid on the page and setting the digitrust id system there. Without following this step everything will work as intended.

### Expected results
Everything should work from start to finish.

### Actual results
Prebid stops doing requests, after receiving digitrust reply.

## Other information
Here are the digitrust objects that resulted from my tests, they are all pretty much the same, with the exception of the callback which shouldn't make any difference since without it the behaviour is the same.

![a](https://user-images.githubusercontent.com/57620436/85013227-28edc480-b15c-11ea-8788-b2874aa8cb29.png)
prebid 3.23.0 without digitrust id system configuration being overwritten on the page (works)

![b](https://user-images.githubusercontent.com/57620436/85013316-4458cf80-b15c-11ea-803b-d26999586dce.png)
prebid 3.23.0 with digitrust id system configuration being overwritten on the page (doesn’t work)

![c](https://user-images.githubusercontent.com/57620436/85013332-4cb10a80-b15c-11ea-92eb-e583dc30a45a.png)
prebid 3.14.0 with digitrust id system configuration being overwritten on the page (works)

**Comment by smenzer** [comment]
i don't really have any thoughts on what's happening or how to fix it, but just a comment that the IAB Tech Lab formally announced they are sunsetting Digitrust as of July 31, 2020; they also have a PR in to remove digitrust ID module, so I would make a bet that this isn't fixed and instead is just removed going forward. just wanted to share so you don't kill yourself trying to fix this when it won't really matter soon.

**Comment by tiago-snigel** [comment]
> 
> 
> i don't really have any thoughts on what's happening or how to fix it, but just a comment that the IAB Tech Lab formally announced they are sunsetting Digitrust as of July 31, 2020; they also have a PR in to remove digitrust ID module, so I would make a bet that this isn't fixed and instead is just removed going forward. just wanted to share so you don't kill yourself trying to fix this when it won't really matter soon.

Thank you very much, most likely we'll do the same

**Comment by robertrmartinez** [comment]
Assigned to Isaac as he is familiar with the User Id module.

**Comment by tiago-snigel** [comment]
> 
> 
> Assigned to Isaac as he is familiar with the User Id module.

Thank you very much, since Digitrust will be discontinued soon I'm doing some tests without the digiTrustIdSystem module and everything seems to work fine, I'll let you know if I find anything else, otherwise, I'll be closing this to not waste anyone's time.
