### ISSUE TITLE
Only 'Prebid.js Bids' event category coming through to analytics

### ISSUE THREAD

**Issue by davejwnz** [prebid/Prebid.js#542]
It appears that no events are passed to Analytics for 'Prebid.js Load Time Distribution' or 'Prebid.js CPM Distribution' but we do see 'Prebid.js Bids' as an event category.

So for reporting it is not possible to look at the response time ranges or CPM distribution.

**Comment by mkendall07** [comment]
@davejwnz 
No events are passed for distribution, it's up to the analytics provider to collect and report on that data from the events we report on.

**Comment by brondsem** [comment]
If you're using the Google Analytics, make sure you have the `enableDistribution` setting turned on http://prebid.github.io/dev-docs/analytics-ga.html#code-example
