### ISSUE TITLE
Bugs in sendBidsControl.dealPrioritization

### ISSUE THREAD

**Issue by jbartek25** [prebid/Prebid.js#5424]
## Type of issue
Bug

## Description
`sendBidsControl.dealPrioritization` doesn't work.

## Steps to reproduce
Enable `sendBidsControl.dealPrioritization` and run a HB auction as usual. This will lead to a syntax error:

![Screenshot 2020-06-24 at 12 29 06](https://user-images.githubusercontent.com/31618107/85846287-e05e8880-b7a5-11ea-8986-eb82b8eef94e.png)
This can be easily fixed by `bucketBids.sort(sortByDealAndPriceBucketOrCpm(true))` in 
https://github.com/prebid/Prebid.js/blob/master/src/targeting.js#L47. 

However, after applying the fix another error appears:

![Screenshot 2020-06-24 at 12 33 14](https://user-images.githubusercontent.com/31618107/85846760-9d50e500-b7a6-11ea-87b2-78004c104741.png)

The problem is that method [sortByDealAndPriceBucketOrCpm](https://github.com/prebid/Prebid.js/blob/master/src/targeting.js#L77) looks for `hb_deal` inside `adUnitTargeting` object which only exists when `sortByDealAndPriceBucketOrCpm` gets called from within `filterTargetingKeys`. However, when `sortByDealAndPriceBucketOrCpm` is called in `getHighestCpmBidsFromBidPool`, `hb_deal` is in `adserverTargeting` object and `adUnitTargeting` is undefined.

**Comment by jbartek25** [comment]
Test page: https://test-hb.improvedigital.com/tmp/prebid-deal-issue/issue.html

**Comment by ChrisHuie** [comment]
closing out with merge of #5504
