### ISSUE TITLE
AppNexus Meta Data

### ISSUE THREAD

**Issue by Slind14** [prebid/Prebid.js#5456]
@jaiminpanchal27  @jsnellbaker @sumit116 

Would you be so good to add the additional data which is already sent in the bid response to meta?

See: https://github.com/prebid/Prebid.js/issues/3115

![image](https://user-images.githubusercontent.com/3914677/86539230-35637280-befb-11ea-967b-eac5a2135e29.png)

**Comment by jsnellbaker** [comment]
I'll take a look at this request and follow-up.

**Comment by jsnellbaker** [comment]
@Slind14 just to clarify the request here and what's listed on #3115, would you want the following fields from the bid to be set inside the meta field as:
```
advertiser_id           --> buyerId
buyer_member_id   --> networkId
brand_category_id  --> brandId
```

I'm not entirely clear on the mapping given we have terms like 'buyer' and 'advertiser', but they're pointing to the same singular field called `buyerId` in the #3115 issue.

Please let me know your thoughts on this point.  Thanks!

**Comment by Slind14** [comment]
If buyer_member_id is the DSP, then yes.

**Comment by jsnellbaker** [comment]
buyer_member_id is the seat code/id used within the adserver for whoever served the bid (ie it's like the buyer's account).  So it sounds like it shouldn't be used here since it's not an exact match to that (or any) field?  

I did look through that list, but I wasn't sure where this field would exactly fit in the scheme of things.

**Comment by Slind14** [comment]
It looks like your seat code stretches across both DSP and buyer, that makes it tricky. With other exchanges it is clearly separated.

There are multiple seats with the same DSP and different buyer. So I would treat this as buyer. If there is another id for just the DSP that would be nice.

**Comment by jsnellbaker** [comment]
I'm not sure there's a value for the DSP specifically.  

If we then treat the `buyer_member_id` as the `buyerId`, where you do think the `advertiser_id` should go then (since it's ear-marked to the same field in the list)?
