### ISSUE TITLE
Advanced Size Mapping Module bug empties config on refresh

### ISSUE THREAD

**Issue by benjaminclot** [prebid/Prebid.js#5458]
## Type of issue
When a config has an empty `sizeConfig.sizes` property set, `[]` becomes `[[]]` so on the next refresh, this adunit's sizeConfig becomes invalid and it gets "deleted". I have been able to trace the problem back to this test: https://github.com/prebid/Prebid.js/blob/master/modules/sizeMappingV2.js#L109

## Test page
https://jsfiddle.net/Lmw0zrp5/
Have the window below 768px and hit refresh, `pbjs.adUnits[0]` will have its `bids` and `mediaTypes` properties empty.

### Expected results
The `pbjs.adUnits` object should remain untouched or maybe the test should use `utils.isEmpty()`?

**Comment by Fawke** [comment]
Hi @benjaminclot,

Yeah, I see can that I'm getting an error on clicking "REFRESH" on your test page. Thanks for bringing this up, I think I've come up with a fix, and am working on some other optimizations, will raise a PR for this fix shortly.
