### ISSUE TITLE
Prebid not waiting for TCF2.0 consent string from Quantcast CMP

### ISSUE THREAD

**Issue by chrissjhitc** [prebid/Prebid.js#5462]
## Type of issue
Question

## Description

We're trying to set up TCF2.0 with the Quantcast CMP but have ran into an issue with Prebid not waiting for consent and requesting the first set of bids with an undefined consent string. It is our understanding that Prebid should be waiting for consent from the CMP before proceeding with bids, so we're not sure if this is a bug with Prebid, Quantcast or a problem with our implementation.

It appears that Prebid is deciding GDPR does not apply due to gdprApplies=false in the initial 'tcloaded' event data and is proceeding with the auction. We are then receiving another 'useractioncomplete' event from the Quantcast CMP shortly afterwards that contains gdprApplies: true and the consent string, but by that time Prebid has already requested the first set of bids.

Is the above the expected behaviour on Prebid's end, with the events from the Quantcast CMP being issue?

## Test page
https://www.hitc.com/prebid-tcf2-cmp-test.php?pbjs_debug=true

### Expected results
Requested bids to contain consent string from Quantcast CMP

### Actual results
Bids are requested without consent string from Quantcast CMP

## Platform details

Prebid 3.24.0

**Comment by Josh-G** [comment]
We have experienced similar issues in their v1.1 implementation where certain values would not be initially available. We assumed this was a race condition and it was reported to them. They never resolved it and we implemented a workaround to delay calling their CMP until it started returning sane values.

It seems to me that this is a problem with Quantcast again, based on [this snippet from the CMP API document](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#what-does-the-gdprapplies-value-mean):
> However, gdprApplies may not be available until the CMP is finished loading and the value will, therefore, be undefined

**Comment by chrissjhitc** [comment]
We do think this is an issue with the Quantcast CMP. According to our reading of the IAB specs the CMP should not be triggering a tcloaded event until the consent string is available, and gdprApplies should be undefined instead of false while it is pending determination.

We have tried a similar workaround of using a __tcfapi listener to wait for the consent string to be supplied before making the call to requestBids. This does seem to work and get the consents added to all of the bid requests.

We've started a support request with Quantcast as it looks like there's either a bug or a problem with their implementation.

**Comment by PrjAdv** [comment]
> We have tried a similar workaround of using a __tcfapi listener to wait for the consent string to be supplied before making the call to requestBids. This does seem to work and get the consents added to all of the bid requests.
Hi chrissjhitc, would you be kind enough to tell me how you did this workaround? I am not capable of doing something like that :-)
I have a Quantcast "universal tag" and i have the same problem.
Thanks

**Comment by chrissjhitc** [comment]
Hi PrjAdv,

We've used this code were you would normally make the call to pbjs.requestBids. We've not fully tested it yet but it does seem to work. I'd probably want to double check its not possible for the event with the tcData to come in before we add our event listener but you should be able work around that if it is an issue.

`function waitForConsent(tcData,success) {

	if (success && tcData.tcString) {
		__tcfapi('removeEventListener', 2, waitForConsent, tcData.listenerId);
		pbjs.que.push(function() {
			pbjs.addAdUnits(adUnits);
			pbjs.requestBids({
				bidsBackHandler: initAdserver,
				timeout: PREBID_TIMEOUT
			});
		});
	}
}

__tcfapi('addEventListener', 2, waitForConsent);`

These two links were helpful on the subject.

[https://help.quantcast.com/hc/en-us/articles/360047737673-Determining-Executing-Consent-Code-TCF-v2-](url)

[https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#addeventlistener](url)

We're still hoping that this will be addressed by Quantcast but we've only had an initial response from them so far.

**Comment by PrjAdv** [comment]
Thank's chrissjhitc!
Now it work correctly :-)
I'm waiting an answer from quantcast support...

**Comment by dmdabbs** [comment]
I've posted a link to this issue in the TechLab Slack channel that TCF and Quantcast folks frequent.

**Comment by chrissjhitc** [comment]
Thanks for the pointers @chrispaterson. We're hoping that Quantcast will look into it on their side and none of this will be necessary.

The initial tcloaded event from the Quantcast CMP is the source of our problem. It has grdpApplies set to false instead of undefined - which the checkV2Data function in the prebid consentManagement module interprets as being told GDPR does not apply. By the time we get the second event from the Quantcast CMP, prebid has already moved on without consent.

From reading the IAB specs it seems we should be doing exactly what Prebid is doing so I'm not confident that our own fix would be desirable or correct. We would have to assume the gdprApplies value in the tcloaded event isn't really false and that we are definitely going to get another event in shortly afterwards.

**Comment by chrispaterson** [comment]
> The initial tcloaded event from the Quantcast CMP is the source of our problem.

There should be only either a `"tcloaded"`  **_OR_**  a `"useractioncomplete"` event for the entire lifecycle of the CMP – never more than one and never both.  If `gdprApplies=false` then the `tcData.tcString` will not be available.

> We're hoping that Quantcast will look into it on their side and none of this will be necessary.

I wrote the [@iabtcf/cmpapi library](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/cmpapi) that Quantcast (and most CMPs) use and helped write the TCF spec as well.  That `if` statement is absolutely necessary because of the constraints of the CMP.  If Prebid is moving on without those conditions then Prebid is doing it wrong.

**Comment by chrissjhitc** [comment]
This is the behaviour we're seeing on the test page linked above, we're getting both events. We have contacted Quantcast support and are open to the issue being anywhere.

![grab-01](https://user-images.githubusercontent.com/17746536/87074675-1c1e3700-c217-11ea-8e47-7f1a69e0adf8.png)

**Comment by chrissjhitc** [comment]
Good news on this, V6 of the CMP was released yesterday and looks to be giving us the correct behaviour. We're getting one tcloaded event with the consent details now The release notes mention a TCF API fix:

https://help.quantcast.com/hc/en-us/articles/360047357574-Quantcast-Choice-Code-Release-Notes-TCF-v2-0-

And thanks again @chrispaterson , that did narrow down exactly where our problem was. We didn't want to touch the behaviour around the specs because we knew if we changed it we'd be breaking it.

And @PrjAdv you need to make sure you get rid of that code hack and update the CMP to V6.

**Comment by PrjAdv** [comment]
Hi all!
Thanks for the feedback and the good news.
On our side, we only must delete the hack in our prebid code, the cmp code automatically turn to the new version.

**Comment by chrispaterson** [comment]
Glad to hear it is resolved!
