### ISSUE TITLE
Prebid.js 4.x announcement

### ISSUE THREAD

**Issue by mlapeyre3** [prebid/Prebid.js#5469]
## Type of issue
Question

## Description
Hello everyone! I can see there is a prebid-4.0 branch opened on the repository and during the last Prebid.org webinar, there was this announcement that prebid.js 4.x will come soon.

Do you have any approximative ETA when this new 4.X version will come out?

Thank you very much!

**Comment by patmmccann** [comment]
approximately july 14

**Comment by mlapeyre3** [comment]
Solved: https://github.com/prebid/Prebid.js/releases/tag/4.0.0 :)
