### ISSUE TITLE
1x1 Creative size (delivered) with Prebid.js

### ISSUE THREAD

**Issue by salvoaranzulla** [prebid/Prebid.js#5475]
## Type of issue
Bug 

## Description
If I generate a report on Ad Manager about the creative size (delived) by Prebid.js advertiser, I see just 1x1:

<img width="764" alt="Schermata 2020-07-09 alle 15 06 15" src="https://user-images.githubusercontent.com/5984607/87043710-c5543580-c1f5-11ea-8a67-64cb0ea0158c.png">

Prebid.js works fine. We use many sizes on our website (for example: 300x250, etc). I don't understand why Ad Manager shows us just 1x1 as creative size (delivered).

## Steps to reproduce

On Ad Manager, you can generate a report like this:

<img width="1345" alt="Schermata 2020-07-09 alle 15 08 08" src="https://user-images.githubusercontent.com/5984607/87043867-06e4e080-c1f6-11ea-872e-4d9568129d2e.png">

## Test page

https://www.aranzulla.it/come-ricaricare-telefono-1056097.html

### Expected results

The expected result is a report with right sizes.

**Comment by wqi1972** [comment]
That is not a problem of Prebid, but a problem of GAM.
The 1x1 is the size of Prebid creative. Inside Prebid LineItems, it overrides 1x1 size with actual sizes you need, e.g. 300x250, and it works fine.
But GAM's report is only based on the creative size (1x1), not the actual size configured and targeted inside lineitems.

If you really need it, you can consider:
1) group different size into different Orders, and generate GAM report by Order;
2) add key hb_size inside GAM, and select: Include values in reporting & add key as custom dimension, then you can generate GAM report based on that key;
3) export GAM data to big query, and run report from big query, inside which has the actual size used for prebid bidding;
4) report the issue to google, hope they will fix it;

**Comment by patmmccann** [comment]
You may wish to make hb_size one of your gam "custom dimensions"
