### ISSUE TITLE
Do we need to use prebid universal creative?

### ISSUE THREAD

**Issue by salvoaranzulla** [prebid/Prebid.js#5484]
## Type of issue

Question

## Description

We erogate only display banner on our website without AMP and without SafeFrame. We are using right now the legacy rendering code:

`<script>
var w = window;
for (i = 0; i < 10; i++) {
  w = w.parent;
  if (w.pbjs) {
    try {
      w.pbjs.renderAd(document, '%%PATTERN:hb_adid%%');
      break;
    } catch (e) {
      continue;
    }
  }
}
</script>`

If I read the code of https://github.com/prebid/prebid-universal-creative/blob/master/src/renderingManager.js, I see that In my case the script erogates the legacy code:

`    if (environment.isMobileApp(targetingData.env)) {
      renderAmpOrMobileAd(targetingData.cacheHost, targetingData.cachePath, targetingData.uuid, targetingData.size, targetingData.hbPb, true);
    } else if (environment.isAmp(targetingData.uuid)) {
      renderAmpOrMobileAd(targetingData.cacheHost, targetingData.cachePath, targetingData.uuid, targetingData.size, targetingData.hbPb);
    } else if (!environment.canLocatePrebid()) {
      renderCrossDomain(targetingData.adId, targetingData.adServerDomain, targetingData.pubUrl);
    } else {
      renderLegacy(doc, targetingData.adId);
    }`

Do we need to use prebid universal creative? Are there any benefit to use prebid universal creative instead legacy rendering code in our case?

**Comment by patmmccann** [comment]
If you're not having a rendering problem, the universal creative is unlikely to solve it

However, you may wish to look at the integration examples and turn on safe frame, that code sample is deprecated in favor of one supporting safe frames.

**Comment by bretg** [comment]
I'm not sure what you mean by "erogate", but no, you don't need to use the PUC unless you need to:

- load creatives from cache
- support safeframes
- support native

**Comment by salvoaranzulla** [comment]
Hi @bretg, Thanks. What do you mean for "load creatives from cache"?

**Comment by bretg** [comment]
In scenarios like AMP and Moble SDK, the creative stored server-side instead of taking up network and memory space on the client. If it wins in the ad server, PUC retrieves the creative from that server-side cache and then displays it.
