### ISSUE TITLE
AppNexus "invCode"

### ISSUE THREAD

**Issue by digitalthrottle** [prebid/Prebid.js#549]
Anyone know where in AppNexus reporting for the "invCode" field would appear?

For instance, where would "7777777" be logged and reported on?

Thanks-

// Add your bids of the defined size for this ad unit here:
var bids = [{
bidder: 'appnexus',
params: {
placementId: "12345",
member: "8888",
invCode: "7777777",
}
}
];"

**Comment by mjacobsonny** [comment]
@digitalthrottle -- 'invCode' represents the code set on your AppNexus placement.  When setting up your AppNexus adunit, you can either include 'placementId' or 'invCode' and 'member'.  For example:

bids: [
	{
		bidder: 'appnexus',
		params: {
			invCode: '7777777',
			member: '8888'
		}
	}
]

In reporting, this would show up as the placement_code.

**Comment by digitalthrottle** [comment]
Thanks. We've been using both codes as we hoped invCode would write back for reporting.

Any way to include Campaign Code in the post bid tag? Trying to get reporting in line.

Thanks.

Bryan

Bryan Robb
President
Digital Throttle, LLC

"We Fuel Online Advertising"

bryan.robb@digitalthrottle.com<mailto:bryan.robb@digitalthrottle.com> | www.digitalthrottle.com<http://www.digitalthrottle.com/>
Office (949) 713-0944 ext. 101<tel:(949)%20713-0944;101> | Cell (949) 683-6550<tel:(949)%20683-6550> | Fax (949) 544-0465<tel:(949)%20544-0465>
30200 Rancho Viejo Road<x-apple-data-detectors://5/1>, Suite I | San Juan Capistrano, CA 92675<x-apple-data-detectors://5/1>

On Aug 22, 2016, at 8:54 AM, Matt Jacobson <notifications@github.com<mailto:notifications@github.com>> wrote:


@digitalthrottle<https://github.com/digitalthrottle> -- 'invCode' represents the code set on your AppNexus placement. When setting up your AppNexus adunit, you can either include 'placementId' or 'invCode' and 'member'. For example:

bids: [
{
bidder: 'appnexus',
params: {
invCode: '7777777',
member: '8888'
}
}
]

In reporting, this would show up as the placement_code.

-

**Comment by mjacobsonny** [comment]
Bryan,

Not sure I fully understand what you're trying to accomplish.  Are you trying to report on the AppNexus campaign which wins a given impression through Prebid?

--Matt

**Comment by mkendall07** [comment]
Closing. Please contact AppNexus support if you have any further questions.
