### ISSUE TITLE
Key values configuration

### ISSUE THREAD

**Issue by radupanait** [prebid/Prebid.js#550]
Hello, 

Could someone please make an example how to configure the keyvalues + the values to all the agencies and exchanges ?

thanks

**Comment by mkendall07** [comment]
All known bidder params should be documented here: 
http://prebid.github.io/dev-docs/bidders.html

If you have specific questions about bidders, we recommend you contact them directly. If you see that params are not listed, please create an issue so we can add them to that bidders page.
