### ISSUE TITLE
Is appnexus prebid server still working? 

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#5502]
i've gone to 3.25.0 prebid and using prebid server: https://prebid.adnxs.com/ for a video unit,  its making calls etc and getting bids back and displaying some vides, but no stats are being recorded in the suppliers systems, so is this working properly with 3.25.0?

**Comment by mike-chowla** [comment]
@patmmccann sent me your test page.  Your are not getting bid information into the DFP url due to a ad unit name mismatch.  The ad unit is created with the name "video" but it should have have the DFP Ad Unit ID since that is what dfp.buildVideoUrl() will use to find the bids

![Screen Shot 2020-07-20 at 10 48 22 AM](https://user-images.githubusercontent.com/13356910/87969501-1de9c500-ca77-11ea-81

![Screen Shot 2020-07-20 at 10 48 36 AM](https://user-images.githubusercontent.com/13356910/87969530-2d690e00-ca77-11ea-845e-d86c15c7a48b.png)
97-48656cd73995.png)

**Comment by spormeon** [comment]
i'm using a child ad unit

**Comment by mike-chowla** [comment]
The value of "code" which is set to "video" needs to match the iu value of dfp.buildVideoUrl

**Comment by mike-chowla** [comment]
My original diagnosis was incorrect.  

The PubMatic is sending back the ad type was a "banner" which incorrect and causing the cache uuid to be undefined.  I'll look into that.

For the other SSPs, I'm not sure what is happening.

**Comment by bretg** [comment]
@spormeon - by "stats" do you mean video impressions? Are you sure it's PBJS 3.25 related or is it possible that it's just timing -- that when you upgraded to 3.25 it just happens that the PBS at adnxs.com was updated?

There was a change in Prebid.js 3.25 around s2sConfig, but it was around the PBJS cache length -- shouldn't affect rendering videos.

@SyntaxNode - heads-up. Let us know if there were any known changes in Xandr-hosted PBS VAST caching in the past few weeks?

**Comment by spormeon** [comment]
the videos render and i have seen them,  its just that no stats are making it back to backend systems that i use,  as soon as i flip the setup to client side, the stats start making it back to backend systems.  I have no clue if its related to a version number, thats the version number i was using

**Comment by spormeon** [comment]
i've also noticed there is conflicting info on this page and no idea if it makes any difference which is used?

http://prebid.org/adops/setting-up-prebid-video-in-dfp.html

one says:
https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_cache_id%%

then the actual actual picture on the step through shows:
https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_uuid%%


which one is the right one to use on line items that serve all bidders?

i'm actually using:
https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_uuid%%

**Comment by bretg** [comment]
[Sorry, for the delay -- I've been OOO.]

The whole uuid-vs-cache_id thing is one of Prebid's 'original sins'. I went back through the mess and confirrmed:

- hb_uuid is for video. Consistent across PBJS, PBS-Go, and PBS-Java
- hb_cache_id is for AMP and Mobile.
- the Prebid Universal Creative maps hb_cache_id to hb_uuid
- the ad server creative needs to map hb_cache_id_BIDDER to ucTagData.uuid

There's still some docs clarifications that can be made, but I fixed the video page.

But you're using uuid, which is correct. 

Please post a test page -- we'll have to trace through the requests and see what's happening.

**Comment by spormeon** [comment]
@bretg ,  are you on the slack adops groups or anyway to contact you direct, I don't like  putting test pages up live for the world

@mike-chowla i tried this again a couple days ago, pubmatic is still doing the "declare as banner" thing

**Comment by bretg** [comment]
Yes, I'm on redditadops
