### ISSUE TITLE
TCFv2: potential bug - null passed as argument instead of undefined or []

### ISSUE THREAD

**Issue by jbartek25** [prebid/Prebid.js#5510]
## Type of issue
Bug or spec clarification

## Description
The CMP API of our provider Onetrust doesn't work with Prebid when fetching consent inside an iframe. The reason is that Prebid sends parameter=null in the code [here](https://github.com/prebid/Prebid.js/blob/master/modules/consentManagement.js#L223). Onetrust team argues that _null_ is not a valid value and in order to declare no value for _parameter_ it has to be set to either _undefined_ or _[]_. I checked the IAB TCFv2 spec and there's no explicit statement for or against _null_. Which end should be fixed? Prebid or the CMP?

**Comment by jaiminpanchal27** [comment]
@jbartek25 Thanks for opening up issue. Can you share the link of IAB spec as well ? We will look into this and update you.

**Comment by jbartek25** [comment]
@jaiminpanchal27 thank you. 
https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md

**Comment by smenzer** [comment]
This looks to be addressed with https://github.com/prebid/Prebid.js/pull/5505

**Comment by jbartek25** [comment]
Agreed. Closing. Thanks!
