### ISSUE TITLE
emx_digital bidder constantly timing out

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#5512]
emx_digital bidder for video constantly timing out in 3.26.0  with change of global,  i get this error:

![Screenshot_18_07_2020__12_14](https://user-images.githubusercontent.com/8503167/87851423-8b1f1e00-c8f0-11ea-8211-a211dca0ad53.png)

**Comment by sbrosinski** [comment]
Looks like the SSL cert for their endpoint recently expired, @EMXDigital ?

**Comment by EMXDigital** [comment]
@spormeon ,

Thanks for bringing this to our attention. Due to some certificate updates, we had an outage in one of our regions 7/17-7/19. This issue was addressed by our team and should be resolved as of late 7/19 to early 7/20 and should be resolved moving forward.

Thanks,
EMX Team

**Comment by spormeon** [comment]
fair enough but how someone lets a ssl cert run out it beyond me

**Comment by smenzer** [comment]
@sbrosinski / @spormeon is this resolved now?
