### ISSUE TITLE
IE - ES6 - Array.prototype.includes()

### ISSUE THREAD

**Issue by dbabaioff** [prebid/Prebid.js#552]
IE not support the **includes()** function - see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

And it's in use here: https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L515

**Comment by mkendall07** [comment]
We have a polyfill for it. https://github.com/prebid/Prebid.js/blob/master/src/polyfill.js#L30
