### ISSUE TITLE
Master branch history rewritten

### ISSUE THREAD

**Issue by snapwich** [prebid/Prebid.js#553]
Our [fork](https://github.com/rubicon-project/Prebid.js) of Prebid.js has a commit that is missing from the master branch.  It appears that issue/pull-request #483 and the related commit are both now missing from this repository's history.  All the commit hashes in our fork going forward since that point are now out of sync.

I'm hoping this was a mistake that can be fixed and that rewriting master history is not an expected strategy going forward?

If so, can master be fixed?  Perhaps from restoring from reflog and removing the bad commit with a git revert?

**Comment by mkendall07** [comment]
A commit had to be removed from master. We don't intend to do this in the normal course of operations, however, it was required in this case.
