### ISSUE TITLE
Suggestion: call Prebid timeout on If (CPM > 1.00 Or Prebid timeout ms passed)

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#554]
Can you consider adding an option to end actions when 1 or all units have a bid cpm of a  > "value" and ignore the prebid timeout settings if "true"

This can be efficient if you run a lot of bidders so even if not all bids are returned you can chose to end action at a fixed min cpm, this can reduce latency by probably half, reducing ads that dont render fast enough to fire the paid pixel.

For example on test running 2,000,000 requests a day, dfp returns 1,850,000 "code calls) and from that 1,800,000 paid impressions. 
Then if i turn prebid off, i'll get 1,950,000 "code calls" in dfp and 1,900,000 paid impressions" 

So maybe of capping the cpm and not losing 100,000 paid impressions a day will give better value then letting the actions finish at the fixed timeout everytime. 

just a suggestions.

**Comment by mkendall07** [comment]
Interesting idea. Would this CPM be from any bidder?

**Comment by mercuryyy** [comment]
From any bidder, this way we can a/b test for the best cpm cut action value and timeout value

**Comment by diffen** [comment]
This is a great idea and should also be available by bidder. i.e., close auction if current highest bid > "value" OR if bids have been received from bidders A, B and C. 

In other words, set different timeouts for different bidders. If I know some bidders are often slow but have a high win rate, I can cut them some slack and wait longer for their bid before closing the auction. But if in a given auction the delay is being caused not by this bidder but by another bidder (that is usually fast but has low bids), we can close the auction early.

**Comment by terrapop** [comment]
Great idea!

**Comment by thechrise** [comment]
Any idea when this could happen?

**Comment by mkendall07** [comment]
Not currently on our roadmap. We accept PRs though.
