### ISSUE TITLE
TCF v2 logic question

### ISSUE THREAD

**Issue by jdelhommeau** [prebid/Prebid.js#5546]
## Type of issue
question

## Description
in consentManagement.js file, the below logic is used to check if TCF v2 consent string is available:

` else if (tcfData.eventStatus === 'cmpuishown' && tcfData.tcString && tcfData.purposeOneTreatment === true) {
        cmpSuccess(tcfData, hookConfig);
      }`

So it seems like, in case a TCString is already available, but user is currently editing his choices (eventStatus == 'cmpuishown'), the CMP will only be initiated in case existing tcfData.purposeOneTreatment is true. 
I am not sure to undertand the logic behind this.

If a tcString is already available, the CMP should be initiated, despite purposeOneTreatment value I think.

Can you clarify the logic behind this?

**Comment by patmmccann** [comment]
A lot of the discussion on this logic is on #5564 comments

**Comment by bretg** [comment]
Are we good here @jdelhommeau ?

**Comment by jdelhommeau** [comment]
Yes @bretg . Sorry about delay, the comments in #5564 fully answer my question. Thank you

**Comment by jdelhommeau** [comment]
see #5564 for details
