### ISSUE TITLE
Bidding not working as expected

### ISSUE THREAD

**Issue by dfnkdhkhfjkdhkafhk** [prebid/Prebid.js#5548]
## Type of issue
Issue

## Description
CCPA Prebid is not bidding as expected

## Steps to reproduce
1.  CCPA Consent Management module was added to v2.44.0 Prebid. 

2. When we debugged the Prebid, we did notice the Prebid loading but there is no bidresponses or bidrequests. 

## Sites with the issue: 
https://www.hometalk.com/?fc=8643,8856 as well as https://www.hometalk.com

## Platform details
Prebid v2.44.0, Mac , Chrome(Incognito Window v: Version 83.0.4103.116 (Official Build) (64-bit))

**Comment by dfnkdhkhfjkdhkafhk** [comment]
Can I please get an update on this issue.

**Comment by dfnkdhkhfjkdhkafhk** [comment]
> ## Type of issue
> Issue
> 
> ## Description
> CCPA Prebid is not bidding as expected
> 
> ## Steps to reproduce
> 1. CCPA Consent Management module was added to v2.44.0 Prebid.
> 2. When we debugged the Prebid, we did notice the Prebid loading but there is no bidresponses or bidrequests.
> 
> ## Sites with the issue:
> https://www.hometalk.com/?fc=8643,8856 as well as https://www.hometalk.com
> 
> ### Expected results : There should be bid responses as well as requests coming in.
> ### Actual results: There are not bid responses or requests from the CCPA Prebid.
> ## Platform details
> Prebid v2.44.0, Mac , Chrome(Incognito Window v: Version 83.0.4103.116 (Official Build) (64-bit))

**Comment by jsnellbaker** [comment]
@Fawke Can you please investigate into this setup and comment?

**Comment by dfnkdhkhfjkdhkafhk** [comment]
I just wanted to add upon that when I checked the config ( i.e. using pbjs.getConfig() on the Console) . I did not notice any details related to Consent Management related module, should that be in there?

**Comment by Fawke** [comment]
Hi @dfnkdhkhfjkdhkafhk,

I visited the page at https://www.hometalk.com and I can see no auction getting initiated. (essentially, I don't see a call to `pbjs.requestBids()`, that's why we have no bid requests and no bid responses). I also do not see any error messages thrown by Prebid.

Can you provide an unminified version of your Prebid.js setup which can help me identify any potential issues with it? I do not know if `consentManagementUsp.js` module is creating the problem. Also, it should be included in `pbjs.getConfig()` if you've included it in `pbjs.setConfig({consentManagement: {usp: {<<YOUR_USP_CONFIGURATION>>}}})`.

**Comment by dfnkdhkhfjkdhkafhk** [comment]
Hi Fawke, 

Thanks for the update. 

We did noticed the same issue on another Website : https://venturebeat.com/  and they are also using CCPA Prebid but of a different version i.e. 3.22.0. Here the details of the Consent Management have been specified in the pbjs.setConfig().

**Comment by dfnkdhkhfjkdhkafhk** [comment]
Hi Fawke,

Is there anything else that can be checked here in the meantime? because as mentioned I also noticed this issue on another Client site: https://venturebeat.com/

**Comment by Fawke** [comment]
Hi @dfnkdhkhfjkdhkafhk,

I didn't find Prebid.js getting used in https://venturebeat.com. (`pbjs` global object threw an `ReferenceError` on the console). Can you confirm?

**Comment by dfnkdhkhfjkdhkafhk** [comment]
Hi Fawke, 

I have attached the unminified version of the Prebid script shared by Hometalk. 
[prebid.js.unminified.zip](https://github.com/prebid/Prebid.js/files/5021757/prebid.js.unminified.zip)
 
I hope this helps.

**Comment by Fawke** [comment]
Hi @dfnkdhkhfjkdhkafhk,

I saw the unminified file that you shared, but I could not find or make out from it, how / when the publisher is calling, `pbjs.requestBids`.

Perhaps, a you can request specifically for these two pieces of code from them.

Their configuration of `pbjs.setConfig({})` & the part where they're calling `pbjs.requestBids()`

I wanted to see the config object that is getting passed in and how/when they are initiating the auction by calling requestBids function.

Also, will you be able to tell me if they've started facing this issue recently or after upgrading/changing to a particular version of Prebid.js. Was it working earlier? Can they try migrating to a newer version of Prebid.js (v3.0+ or even 4.0) and see if the problem persists? If you suspect `consentManagement.js` module is causing problems, can you create a build without that module, and not include it in setConfig and then check, if we see an auction taking place?

**Comment by bretg** [comment]
@dfnkdhkhfjkdhkafhk - what's the status here? We can't debug without a test page (or a live site) and instructions for how to find the Prebid invocation.
