### ISSUE TITLE
Criteo ID module throws error in unfriend iframe when third-party cookies are blocked

### ISSUE THREAD

**Issue by jbartek25** [prebid/Prebid.js#5555]
## Type of issue
Bug

## Description
When running Prebid inside an unfriendly iframe with Criteo ID module enabled and third-party cookies blocked, Criteo attempts write in local storage. This throws an unhandled exception, the auction won't run and no ads will load.

## Steps to reproduce
Test page: http://test-hb.improvedigital.com/tmp/criteo-id-error.html

In Google Chrome make sure third-party cookies are enabled, open the test page -> ads will show up.

Disable third-party cookies, open the test page -> no ads + errors in the console:
<img width="761" alt="Screenshot 2020-07-30 at 16 27 40" src="https://user-images.githubusercontent.com/31618107/88936126-d509eb80-d282-11ea-94f8-d49e5491aaeb.png">

**Comment by mkendall07** [comment]
@bmwcmw @afewcc for review

**Comment by beljul** [comment]
Hello, thanks for reporting the issue. We will have a look.

**Comment by Swiiip** [comment]
Hello, it seems linked to the fact that the storage access library does not check whether the storage is available before accessing it. I created a PR to fix this issue in the lib: #5616

**Comment by muuki88** [comment]
Unstale :kissing_heart:
