### ISSUE TITLE
Feature Request - Copy meta keywords to fpd.context

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#5571]
## Type of issue
Feature request

## Description
 https://github.com/prebid/Prebid.js/pull/4488 added support for copying meta keyword fields to a bidder's keywords field. It was discussed that this might be desirable for all bidders to have access to via fpd.context, which was defined on https://github.com/prebid/Prebid.js/pull/4472 . This issue is to add that functionality, either via an RTD submodule or perhaps in core. 

Publishers should be able to specify via getConfig if fpd.context is blank, populated by this functionality, or set by them in a more custom way. 

The code in https://github.com/prebid/Prebid.js/pull/4488 would be quite useful for drafting a pull request.

**Comment by patmmccann** [comment]
fyi @sumit116

**Comment by bretg** [comment]
Covered by https://github.com/prebid/Prebid.js/issues/6099 -- closing.
