### ISSUE TITLE
Post-bid issues

### ISSUE THREAD

**Issue by Elisa004** [prebid/Prebid.js#5573]
## Type of issue
Post-bid integration on AMP page

## Description
Hello I've a problem with AMP page integration. I've added the post-bid code in the page but it doesn't works well. Is there a different integration for AMP page? thanks

**Comment by patmmccann** [comment]
http://prebid.org/formats/amp.html

**Comment by Elisa004** [comment]
So, the post-bid integration in AMP page is the same of prebid?

**Comment by bretg** [comment]
If you want to try running postbid in AMP, you would paste the entire Prebid.js package+adunits+invocation code into your ad server creative, not the page itself. 

Note that we don't support this scenario -- don't know if it will work. If it does, you're encouraged to submit a docs PR so others can benefit from your experience. Thanks.
