### ISSUE TITLE
Floors Module: Publisher provided minimum floor

### ISSUE THREAD

**Issue by bszekely1** [prebid/Prebid.js#5580]
## Type of issue

Intent to implement

## Description

When publishers work with Floor Providers using the Prebid Floors Module, publishers give them full trust and control of setting Prebid floors. There may be scenarios where publishers may wish to have floors higher than those provided by the floors provider such as:

- Channel conflict
- Publisher rate minimums
- Using their own floor model as a minimum to help lift CPMs

If a publisher provided minimum CPM is set, the Floors Module will use the higher of the rule floor or min floor when signaling and enforcing.

## Technical requirements

1. Field name for publisher minimum floor should be called `floorMin`
2. `floorMin` should be located at the root level of the `floors` object represented as a float
4. If `floorMin` is a non-zero float and `getFloor( )` is called, `getFloor` will take the higher CPM of the winning rule floor and `floorMin`
5. To prevent a breaking change `bidResponse.floorData.floorValue` will still be the floor enforced, even it the value resolves to `floorMin`
    - A new floor attribute `floorRuleValue` should be created to allow floor providers to understand the context of the rule floor in the event the `floorMin` is the selected floor
    - `floorMin` should be available to be available to analytics adapters as well
    - `floorMin` should be added to `bidResponse.floorData` to let analytics adapters to know context of `floorMin`
6. `floorMin` should follow a similar flow all other rules, regulated by `skipRate` but apply no matter which rule group applies (i.e. fetch, setConfig or adUnit floors)
7. `floorMin` only applies when floors are used (i.e. does not apply when `skipRate` is true or when the floors module does not find rules to attach to)

Example setting a publisher minimum floor with a set config:

```
pbjs.setConfig({
    floors: {
        floorMin: 0.90
        enforcement: {
           floorDeals: true, //default to false
        },
        auctionDelay: 100,   // in milliseconds
        endpoint: {
            url: 'https://floorprovider.com/a1001-mysite.json'
        }
    }
});
```

**Comment by patmmccann** [comment]
On number three, it seems the integer requirement is strange, why not a float?

On number four, this seems like an opportunity to add a an option to the enforcefloors key-value pair in the config.

**Comment by bszekely1** [comment]
> On number three, it seems the integer requirement is strange, why not a float?
> 
> On number four, this seems like an opportunity to add an option to the enforcefloors key-value pair in the config.

Number three was intended to be a float as point 2 referenced. This was a typo.

Regarding number four, I am not sure what you mean by adding an option to enforcement key-value. Are you suggesting to giving an option just to enforce the minFloor but not signal?

**Comment by patmmccann** [comment]
I am suggesting that if you are choosing a behavior to avoid a breaking change, you can also have the preferred behavior available with an opt in config flag.

**Comment by bszekely1** [comment]
> I am suggesting that if you are choosing a behavior to avoid a breaking change, you can also have the preferred behavior available with an opt in config flag.

It was partially to avoid a breaking change but also to keep with a consistent clear behavior of floorValue. It's not an issue to leave the floorValue bahavior as is and provide an additional object for analytics adapters to read the flooRuleValue if present.
