### ISSUE TITLE
Add Adsparc adaptor

### ISSUE THREAD

**Issue by yogeshadsparc** [prebid/Prebid.js#560]
Hello Team,

We would like to add our Adsparc adapter for prebid solution. 

Please find our test example of integration here: http://prebid.adsparc.net/bidding/example.html

For Testing you can use ad slot with id(pubId) 1, 2 and 3
If you would like to notify us about adaptor, contact us at: yogesh.ingale@adsparc.com

Our official website is http://www.adsparc.com/

Thank you,
Yogesh Ingale

**Comment by mkendall07** [comment]
@yogeshadsparc 
Any update on this? Did you submit a PR for your adapter?
