### ISSUE TITLE
 unit tests on dfp video module

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#5607]
https://github.com/prebid/Prebid.js/pull/4821 and https://github.com/prebid/Prebid.js/pull/5487 broke this module without creating any unit test issues. This was later fixed on  https://github.com/prebid/Prebid.js/pull/5591

Perhaps we need better unit testing on this module to prevent future breaks?

**Comment by patmmccann** [comment]
The issue might be contained to https://github.com/prebid/Prebid.js/blob/master/test/spec/modules/dfpAdServerVideo_spec.js#L42 Why did this particular expect not get flagged with the merge of 5487?

**Comment by gglas** [comment]
assigning to @ChrisHuie to explore if there are missing tests for these PRs.
