### ISSUE TITLE
GDPR Enforcement warnings on criteo, id5Id and pubcommonId userSync modules

### ISSUE THREAD

**Issue by ocm-peter** [prebid/Prebid.js#5615]
## Type of issue
user Sync modules behavior through the GDPR Enforcement module

## Description
While the user gives consent for Purpose 1 and the "vendors" (criteo, pubcommon and id5Id) are both accepted in consent and in LI, the prebid debug logs show a warning.

## Steps to reproduce
Use prebid v4.4.0-pre, add criteo, id5Id and pubcommonId user syncs and make sure that criteo (can't find the others) is
accepted through CMP.

## Test page
https://www.whoscored.com/Matches/1481961/Live/Europe-Champions-League-2019-2020-Barcelona-Bayern-Munich?ocmpbjs_debug=true

### Expected results
I suppose that criteo, pubcommonId and id5Id should work as expected?

### Actual results
> WARNING: User denied permission to fetch user id for criteo User id module
> WARNING: User denied permission to fetch user id for pubCommonId User id module
> WARNING: TCF2 denied device access for id5Id
> WARNING: TCF2 denied device access for id5Id

After that, of course, the iframe user syncs are not throwing any errors:
> Prebid MESSAGE: Invoking iframe user sync for bidder: appnexus
> Prebid MESSAGE: Invoking iframe user sync for bidder: pubmatic
> Prebid MESSAGE: Invoking iframe user sync for bidder: openx
> Prebid MESSAGE: Invoking iframe user sync for bidder: rubicon

## Platform details

Prebid v4.4.0-pre / Windows 10 / Chrome + MS Edge

**Comment by dmdabbs** [comment]
Does the module provide any console output indicating what it read from the consent data? Was it v1 or v2, etc.

**Comment by ocm-peter** [comment]
Hello @dmdabbs,

I don't see anything from the modules themselves, but yes it's definitely a TCF2

![image](https://user-images.githubusercontent.com/64111309/90409502-e9871a00-e0b1-11ea-9631-3438f33049b4.png)

**Comment by Fawke** [comment]
Hi @ocm-peter,

Thanks for bringing this up. It's a bug in `gdprEnforcement` module. I'm currently working on a fix, which should be ready in a day or two.

**Comment by muuki88** [comment]
CC @smenzer

**Comment by muuki88** [comment]
As a workaround we tried to configure the `gdpr` module like this

```js
      gdpr: {
        rules: [ {
          purpose: 'storage',
          enforcePurpose: true,
          enforceVendor: true,
          vendorExceptions: [ 'id5Id', 'criteo', 'unifiedId' ]
        }, {
          purpose: 'basicAds',
          enforcePurpose: true,
          enforceVendor: true
        }, {
          purpose: 'measurement',
          enforcePurpose: true,
          enforceVendor: true
        } ]
```

which at least removes the errors. `unifiedId` works now, but `criteo` still seems to have troubles. At least the `pbjs.getUserIds()` doesn't return any criteo ids.
