### ISSUE TITLE
[Ideas] GDPR data exposed by prebid API and maybe bidders should check against consent

### ISSUE THREAD

**Issue by ocm-peter** [prebid/Prebid.js#5646]
## Type of issue
Feature request, I guess :)

## Description
Just a thought to avoid the overkill of rechecking for consent data in the publisher's own script.

Might be a good idea for prebid to expose CMP data, such as cmp version, consentData so publishers can directly use its data (version and tcfData) for decision making and move forward as proposed by the user's consent.

A list of possible cases I've come across are (using GAM as ad server):

1. User's consent is Agree to All -> Run HB and GAM
2. User's consent lacks Purpose 1 -> Run nothing, unless gdprEnforcement module is on and enforces P1
3. User's consent lacks agreement to Google vendor (either consent or legitimate interest) -> Run HB only and render ads using custom renderer

Any thoughts on the above are more than welcome ofc.

Now, on to the bidder part idea. Just like Google does, wouldn't it be proper for bidders to use those prebid exposed cmp data
to decide if they should drop the request? This would make life easier both on the publisher side AND reduce trash requests hitting the bidders' servers.

Thanks for reading,
Peter

**Comment by bretg** [comment]
> Might be a good idea for prebid to expose CMP data, such as cmp version, consentData so publishers can directly use its data (version and tcfData) for decision making and move forward as proposed by the user's consent.

This should be discussed in the Prebid Publisher Taskforce -- as a platform, I'm not crazy about being a passthrough for CMP data when the page could/should have direct access to the CMP. But if Prebid Pubs want this functionality, open to PRs.

> wouldn't it be proper for bidders to use those prebid exposed cmp data to decide if they should drop the request?

Don't understand - this is of course what's happening. The design is:

- If the Publisher turns on enforcement at the Prebid level, enforcement happens
- Whether Prebid enforces or not, all bidders in-scope for GDPR must have an approach for complying with GDPR
- Let me say this another way: **Prebid does not magically make all bidders compliant with GDPR**.

**Comment by gglas** [comment]
@ocm-did Bret's questions make sense // have things changed to address these use cases?

**Comment by ocm-peter** [comment]
@gglas I think we're good after so many changes and actual usage. This can be closed.
