### ISSUE TITLE
Outstream AdUnit - huge discrepancy

### ISSUE THREAD

**Issue by andreykuper** [prebid/Prebid.js#5652]
## Type of issue
question

## Description
Recently we added an out-stream video media type in placements that shows display too (multi-format ad-unit). But we can see that the number of impressions collected by the bidders is almost half of the amount we counted in our tracking system. We think it's because the video player takes a long time to load - and when it's loaded it's not on the screen view post because the user scrolled down. Could be it's an issue in something else?

## Steps to reproduce
add any out-stream bidder to your ad-unit to check it out.

### Expected results
The minimal discrepancy between my tracker and bidder system.

### Actual results
almost 50-60% discrepancy between the number of impressions I counted (winning bids/slot rendered) and bidder system.

## Platform details
We tried app-nexus and unruly out-stream ad unit

**Comment by muuki88** [comment]
In our experience this is depends heavily on the partner

- :+1:  Xandr / AppNexus works fine for us
- :+1: Teads works fine for us
- :-1: Unruly numbers don't match as they measure an impression only if the ad has been visible for a certain amount of time and percentage. This leads to discrepancies around ~30-40% depending on how well the ad slot is placed

**Comment by andreykuper** [comment]
> In our experience this is depends heavily on the partner
> 
> - :+1:  Xandr / AppNexus works fine for us
> - :+1: Teads works fine for us
> - :-1: Unruly numbers don't match as they measure an impression only if the ad has been visible for a certain amount of time and percentage. This leads to discrepancies around ~30-40% depending on how well the ad slot is placed

Did you needed a special implementation for outstream units? Providing renderer or something else?

In addition - maybe it's related or not - what creative code in your GAM are you using for prebid? Are you using universal creative code library?

**Comment by muuki88** [comment]
> Did you needed a special implementation for outstream units? Providing renderer or something else?

Nope. We only integrated partners that ship their own player, which are currently unruly, teads and xandr. Pubmatic has a player now and smartclip just added a prebid adapter.

> In addition - maybe it's related or not - what creative code in your GAM are you using for prebid? Are you using universal creative code library?

We use the universal creative.

Maybe I should state what impression we compare. My numbers are related to GAM ad impressions vs Paid impressions from the partner.

**Comment by jbartek25** [comment]
> Maybe I should state what impression we compare. My numbers are related to GAM ad impressions vs Paid impressions from the partner.

@muuki88 There will always be a significant discrepancy between GAM and SSP imp counts for outstream. The reason is that the GAM outstream creative is the same as display/banner creative meaning that GAM counts impression when the creative code is served but the video ad only fires SSP impression pixel when the player successfully starts playing the video ad. So you end up with Google counting the served code and SSPs counting the played videos. If for whatever reason the video didn't play, like video/vast/vpaid errors or users navigating off the page or users scrolling away from the slot when the player is configured to only play when in view, this will lead to GAM imp but no SSP imp.
For multi-format ad units any lost video imp also means lost revenue there could have been if a banner bid won instead so test your multi-format setup throughly to make sure that there's revenue boost from outstream and outstream is not dragging your multi-format performance down.

**Comment by ehudal22** [comment]
> > Maybe I should state what impression we compare. My numbers are related to GAM ad impressions vs Paid impressions from the partner.
> 
> @muuki88 There will always be a significant discrepancy between GAM and SSP imp counts for outstream. The reason is that the GAM outstream creative is the same as display/banner creative meaning that GAM counts impression when the creative code is served but the video ad only fires SSP impression pixel when the player successfully starts playing the video ad. So you end up with Google counting the served code and SSPs counting the played videos. If for whatever reason the video didn't play, like video/vast/vpaid errors or users navigating off the page or users scrolling away from the slot when the player is configured to only play when in view, this will lead to GAM imp but no SSP imp.
> For multi-format ad units any lost video imp also means lost revenue there could have been if a banner bid won instead so test your multi-format setup throughly to make sure that there's revenue boost from outstream and outstream is not dragging your multi-format performance down.

So how does one go about to best count SSP impressions? can anyone share a good multi format setup?

**Comment by ehudal22** [comment]
> In our experience this is depends heavily on the partner
> 
> * 👍  Xandr / AppNexus works fine for us
> * 👍 Teads works fine for us
> * 👎 Unruly numbers don't match as they measure an impression only if the ad has been visible for a certain amount of time and percentage. This leads to discrepancies around ~30-40% depending on how well the ad slot is placed

Can you share the multi format/out stream implementation? How do you handle Unruly?

**Comment by patmmccann** [comment]
You just set an aggressive bidadjustment cpm for that format, and perhaps
have it contingent on bandwidth or device.

**Comment by muuki88** [comment]
@ehudal22 we use the reported numbers from unruly. And we compare them to the ad manager. 

So in general the discrepancy should stay the same. The discrepancy also let's you monitor improvements to

- your site, e.g. position has a higher viewability
- player improvements
- page speed 

Another thing we haven't tried out yet is to use the `active view impressions` from GAM, which come closer to the impressions measured by unruly.

As @jbartek25 pointed out there are still cases where you can only rely on the impressions of the buyer, e.g.

- VAST errors
- play when only in view

> For multi-format ad units any lost video imp also means lost revenue there could have been if a banner bid won instead so test your multi-format setup throughly to make sure that there's revenue boost from outstream and outstream is not dragging your multi-format performance down

That's a very good advice. And again, by measuring the discrepancy between ad impressions served via GAM and measured by your partner you can estimate how much revenue you may have lost. Usually you fix this by setting floor prices that are high enough so they compensate all the impressions served, but not being paid.
