### ISSUE TITLE
Doesnt work "show all bids" when ads refreshed

### ISSUE THREAD

**Issue by ademozkur** [prebid/Prebid.js#5659]
## Type of issue
The "Show all bids" function works properly when ads are first loaded. However, doesnt working after being ads refreshed. And it only brings bid information of 1 ad unit. It get 3 lines, all ad units are the same. Why is this happening? How do I fix it? I want to get bid informations.

Before Refresh:
https://i.ibb.co/VLzzG8f/before-refresh.jpg

After Refresh:
https://i.ibb.co/CnxhNXK/after-refresh.jpg

**Comment by bretg** [comment]
What do you mean by "show all bids" function -- the troubleshooting javascript that dumps bids to the console?

That function uses `pbjs.getBidResponses()`, which is scoped to the adunits from the most recent auctions.

Options:

1) Rewrite the troubleshooting function to use getBidResponsesForAdUnitCode(code) and call it for each adunit code you care about
2) Use HeaderBid Expert Chrome Plugin
3) Use AdWizard Chrome Plugin

**Comment by ademozkur** [comment]
Actually, I am trying to collect bids informations with websocket with the help of the code in the link below. Isn't this the right method?

https://docs.prebid.org/troubleshoot/troubleshoot-guide.html#see-all-bids-in-the-console

However, this code cannot collect data when the ad is refreshed. What arrangement should I make for this? When an ad unit is renewed, I want to receive the data of the bid's for that ad unit. As soon as the ad unit is renewed, I want to receive its information and send it to the socket.  When the page first loads, there is no problem. It brings the auction infos of all ad units. But when an ad unit is refreshed, it does not return the information correctly.

**Comment by bretg** [comment]
The way `getBidResponses()` works is that it reports only the adunits that participated in the last auction. Think of it like get**Recent**BidResponses. This works for most use cases.

You need to work around that aspect. Four options come to mind, I'm sure there are more:

1) What you're trying to do sounds like an analytics adapter. Build one of them. https://docs.prebid.org/dev-docs/integrate-with-the-prebid-analytics-api.html
2) Loop through all of your adunits and call [getBidResponsesForAdUnitCode](http://docs.prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.getBidResponsesForAdUnitCode)(code) on each
3) [Listen to the auctionEnd event](https://docs.prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.onEvent) and save state for each auction.
4) Make a specific suggestion here for what you'd like to see. Some kind of getMostRecentBidResponsesForAllKnownAdUnits? We can't promise we'll build it for you, but it's open source, so if it's cheap and others like the idea, we'll approve it. However, I suspect one of the above options will give you an idea about how to tackle it.

**Comment by ademozkur** [comment]
Problem is solved.
