### ISSUE TITLE
ActionEnd event called, no ads are rendered but dfp delivery is showing prebid as the winning ad.

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#566]
So console showing bid received but it does not render ads (see attached 1), adsense,adx ads are loaded (confirmed with google publisher tool) [See attached 2] but then going to delivery diagnosis in dfp winning line item is the prebid creative (see attached 3). before it used to say "Adx, adsense won". just updated to the most recent master.
[This seems to be happening randomly, at times it works fine] (see attached 4)

![screen shot 2016-08-24 at 1 52 07 am 1](https://cloud.githubusercontent.com/assets/7463132/17919811/1d7b0662-699e-11e6-9ec1-311def4d9091.png)

![screen shot 2016-08-24 at 2 05 26 am](https://cloud.githubusercontent.com/assets/7463132/17920039/f1708c3e-699f-11e6-89d8-6eb504c57f7f.png)

![screen shot 2016-08-24 at 1 56 58 am](https://cloud.githubusercontent.com/assets/7463132/17919812/1d7e001a-699e-11e6-8e35-b2cb987f152d.png)

**## Then at random it will work and show the delivery like this:**

![screen shot 2016-08-24 at 2 11 59 am](https://cloud.githubusercontent.com/assets/7463132/17920083/2e93de90-69a0-11e6-8e1e-5e6093174b5a.png)

**Comment by mercuryyy** [comment]
I just realized the the dfp delivery diagnosis might return current exchange value, so if you click "return competition" a few times, adx,adsense will randomly win/lose but is the first time the diagnosis page is loaded represents what happened in the action that took place.  ;/

**Comment by mkendall07** [comment]
Not really sure, might e a creative issue. Do you have debug output from prebid when this happens?

**Comment by mercuryyy** [comment]
Debug ends at the row in attachments 1. above it is the standard output nothing out of the ordinary.
I think its just the way dfp delivery diagnosis is, even adx,adsense won, once you click "delivery diagnosis" on the ad unit in google console and it opens dfp delivery diagnosis it will run the competition again and might give a different adx,adsense win lose value. shouldnt be like that tho

**Comment by mercuryyy** [comment]
@mkendall07  closed tnx
