### ISSUE TITLE
Error 2.1.a with Google in EEA

### ISSUE THREAD

**Issue by ehudal22** [prebid/Prebid.js#5675]
Heya,

Since the new TCF 2.0 regulations kicked in on the 15th, we started getting 2.1.a errors from Google, those errors basically say that we are sending requests to Google from EEA countries before receiving consent from users.
Does anyone have an example of prebid setup that forces the showing of no ads to users and no auctions started until consent is received with prebid?

An example of the "correct" ads behavior:
[https://vimeo.com/448116970/4d24c9edc9]((
https://vimeo.com/448116970/4d24c9edc9)
)
Thanks

**Comment by bretg** [comment]
> Does anyone have an example of prebid setup that forces the showing of no ads to users 

Skipping GPT ad calls isn't part of the Prebid setup... we can't help you there.

As for how to set up Prebid.js to enforce the blocking of auctions without consent, we think that's pretty clearly documented in:

https://docs.prebid.org/dev-docs/cmp-best-practices.html
and
https://docs.prebid.org/dev-docs/modules/gdprEnforcement.html

It there's an element not clear, let us know what can be clarified.

> no auctions started until consent is received with prebid

This configuration will turn on enforcement for all purposes:
```
pbjs.setConfig({
  consentManagement: {
    gdpr: {
      cmpApi: 'iab',
      defaultGdprScope: true,
      rules: [{ 
        purpose: "storage",
        enforcePurpose: true,
        enforceVendor: true
      },{
        purpose: "basicAds",
        enforcePurpose: true,
        enforceVendor: true
      },{
        purpose: "measurement",
        enforcePurpose: true,
        enforceVendor: true
      }]
    }
  }
});
```
