### ISSUE TITLE
Pass video.placement through to Prebid Server

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#5687]
## Type of issue
Enhancement

## Description
Prebid Server doesn't get any indication of whether a video request is instream or outstream, and what kind of "placement" it is.

## Proposal

1) We modify the PrebidServerBidAdapter to support setting imp[].video.placement

- if AdUnit.mediaTypes.video.placement is defined send that as imp[].video.placement
- else if AdUnit.mediaTypes.video.context="instream", send imp[].video.placement=1

2) We modify the Prebid.org documentation to suggest defining placement when setting outstream.

https://docs.prebid.org/prebid-video/video-getting-started.html
https://docs.prebid.org/dev-docs/show-outstream-video-ads.html

**Comment by mike-chowla** [comment]
Approach looks to good to me.
