### ISSUE TITLE
Purpose 1 enforcement not respecting (?) config in gdprEnforcement

### ISSUE THREAD

**Issue by ocm-peter** [prebid/Prebid.js#5693]
## Type of issue
Bug

## Description
While gdprEnforcement module is used and purpose: "storage" is set to false in prebid setConfig(), prebid debugging in console reports "WARNING: TCF2: enforcing P1 and P2". I don't know if this is a bug on logging or it actually enforces P1 regardless of configuration.

## Steps to reproduce
Using gdprEnforcement module with the following configuration
                consentManagement: {
                    gdpr: {
                        cmpApi: "iab",
                        timeout: 20000,
                        defaultGdprScope: true,
                        rules: [{
                            purpose: "storage",
                            enforcePurpose: false,
                            enforceVendor: false
                        }]
                    },
                    usp: {
                        cmpApi: "iab",
                        timeout: 100
                    }
                }

## Test page
https://www.gossip-tv.gr/?ocmpbjs_debug=true

### Expected results
I shouldn't get a warning about P1 being enforced

### Actual results
![image](https://user-images.githubusercontent.com/64111309/92106567-43474e00-eded-11ea-9b6a-524b481eed2b.png)

## Platform details
Prebid v4.3.0, Windows 10, Microsoft Edge + Google Chrome

## Other information
Might be related to https://github.com/prebid/Prebid.js/pull/5643 (mentioned by @patmmccann in slack @ #publishers)

**Comment by Fawke** [comment]
Hi @ocm-peter,

I looked into this issue and tried to reproduce the same with a very similar config. It didn't log that warning message for me.

Ideally, when `gdpr.rules` is undefined, from Prebid v4.0 onwards, the default behaviour is to enforce TCF Purpose 1 and Purpose 2. You can turn a purpose enforcement off by explicitly stating it in your config. I don't see any problem with your config as well. It works fine for me.

The test page you've shared use Prebid v3.0, where we don't enforce P1 and P2 by default. Can you share the correct test page so we can debug it at our end?

**Comment by ocm-peter** [comment]
Hello @Fawke,

The page, as I see, loads 2 different prebid instances, ours being the ocmpbjs instance on version 4.3
Try running ocmpbjs.version in the console. That's why the link I supplied uses the ?ocmpbjs_debug=true param,
because that will trigger only our prebid instance to log stuff.

I think I forgot one thing about my configuration.
I also have the old allowAuctionWithoutConsent set in there. Any chance that would cause the issue?

**Comment by Fawke** [comment]
Hi @ocm-peter,

Now, am able to load your prebid at this page: https://www.gossip-tv.gr/?ocmpbjs_debug=true

When I did `pbjs.getConfig()`, I found that you have not stated `gdpr.rules` in the config. Here's the screenshot.

<img width="1680" alt="Screenshot 2020-09-04 at 6 41 53 PM" src="https://user-images.githubusercontent.com/14229985/92243373-078cb100-eedf-11ea-9c42-1b594f6482d0.png">

So, the warning message that you see is the expected behaviour when no rules is specified.

And not a different note, you should not be using `allowAuctionWithoutConsent` with TCF 2. Here are the [docs](https://docs.prebid.org/dev-docs/modules/consentManagement.html#page-integration)

**Comment by ocm-peter** [comment]
Hey @Fawke ,

You are absolutely right. This particular implementation has a fallback for some non-supported browsers
and I missed the rules on the proper configuration script.

Excuse any inconvenience caused.

Thanks again.
