### ISSUE TITLE
Marking used bids for video

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#5696]
## Type of issue
Feature request

## Description
https://github.com/prebid/Prebid.js/pull/5481 adds module support for detecting if a video bid won instead of just set targeting. https://github.com/prebid/Prebid.js/pull/2777 adds a function for publishers to mark bids as used upon set targeting. It seems with the addition of #5481 that a logical extension of #2777 is to add MarkRenderedBidsAsUsed instead of mark winning bids as used. The logic might look very similar to mark winning but with the additional render check from #5481 . However, it isn't obvious how we would make a global function export like this depend on a module.

**Comment by pm-harshad-mane** [comment]
@monis0395 / @monisq would you like to fix this too? It was dependent on your fix #5481

**Comment by monis0395** [comment]
Hi @pm-harshad-mane, I am blocked for my sprint, will check after 9th October

**Comment by gglas** [comment]
@monis0395 did you ever make any headway here?  @karimMourra is this something easily addressed in the new video work we're doing?

**Comment by karimMourra** [comment]
@gglas  I believe so. We would like the Video Module to emit ad rendering events such as `adImpression` which would indicate if the winning bid's ad creative was rendered.

**Comment by patmmccann** [comment]
will be addressed in #6271

**Comment by patmmccann** [comment]
@karimMourra should we re-open this or do we plan to put the video module stuff back up?

**Comment by patmmccann** [comment]
re-opening so i dont forget

**Comment by karimMourra** [comment]
@patmmccann I reopened the PR ; we can keep this issue opened until the PR gets merged https://github.com/prebid/Prebid.js/pull/8858

**Comment by patmmccann** [comment]
thanks!!
