### ISSUE TITLE
How to reset/destroy pbjs.adUnits in a single page web app? Ads stacking up with every new page view.

### ISSUE THREAD

**Issue by terrapop** [prebid/Prebid.js#5712]
## Type of issue
How to reset pbjs.adUnits in a single page web app?

## Description
We try to implement Prebid in a single page web app. Works on the first-page view, but then the pbjs.adUnits array is filled with more and more of the same ad unit with every page view and the call to the server to server bid handler fails:

Invalid request: request.imp[0].id and request.imp[1].id are both "adunit_top". Imp IDs must be unique.
Invalid request: request.imp[1].id and request.imp[2].id are both "adunit_top". Imp IDs must be unique.
Invalid request: request.imp[2].id and request.imp[3].id are both "adunit_top". Imp IDs must be unique.

I tried to clear pbjs.AdUnits = [], and afterwards add the add units for the new page view with pbjs.addAdUnits(adUnitsForPage), but this does not work.

Any other way to destroy/clear pbjs.AdUnits or reset the whole pbjs object between virtual page views?

## Steps to reproduce
Build a single web app and call auctions on subsequent page views.

### Expected results
In addition to pbjs.addAdUnits a function to pbjs.destroyAdUnits or something like pbjs.resetPrebid is required.

**Comment by terrapop** [comment]
Update:

I hacked this code into prebid:

`S.destroyAdUnits=function(){E.logInfo("Destroying pbjs.addAdUnits"),S.adUnits = []}`

after

`S.addAdUnits=function(e){E.logInfo("Invoking pbjs.addAdUnits",arguments),E.isArray(e)?S.adUnits.push.apply(S.adUnits,e):"object"===v(e)&&S.adUnits.push(e),T.emit(j)}`

and call

```
pbjs.destroyAdUnits();
pbjs.addAdUnits(adUnits);
```

on every virtual page view and this works now.

But I would love to have some feedback if this is a valid approach, and if something like this could be added to core prebid in order to support SPA/PWA.

**Comment by pm-harshad-mane** [comment]
you may set adUnits in pbjs.requestBids as an input , please refer https://docs.prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.requestBids. if you use this approach then you do not need to use pbjs.addAdUnits

**Comment by wqi1972** [comment]
@terrapop, I believe you made a small mistake in your original solution:
```
pbjs.AdUnits = [];
```
suppose be:
```
pbjs.adUnits  = [];
```
:)

**Comment by terrapop** [comment]
> @terrapop, I believe you made a small mistake in your original solution:
> 
> ```
> pbjs.AdUnits = [];
> ```
> 
> suppose be:
> 
> ```
> pbjs.adUnits  = [];
> ```
> 
> :)

How stupid of me. This is the correct solution and it works.

**Comment by bretg** [comment]
Good catch @wqi1972 . Closing this issue.
