### ISSUE TITLE
Prebid 4.x adoption rate

### ISSUE THREAD

**Issue by saileshd** [prebid/Prebid.js#5714]
## Type of issue
Question

## Description
What is the adoption rate of prebid 4.x compared to 3.x?

**Comment by bretg** [comment]
Prebid.org does not and cannot track installs of any of its software -- we don't burden the community with any kind of centralized tracking at all.

That said, we do have numbers for how often Prebid.js versions are downloaded from the site -- 75% of the downloads in August were 4.x.
