### ISSUE TITLE
example pages are failing gdpr checks because they are using TCF v1

### ISSUE THREAD

**Issue by smenzer** [prebid/Prebid.js#5718]
## Type of issue
bug

## Description
The example pages that use a CMP are relying on TCF v1 and the original vendor list file originally located here: https://vendorlist.consensu.org/vendorlist.json (which is now a dead link). The TCF v2 vendorlist is https://vendorlist.consensu.org/v2/vendor-list.json and the CMP in the tests need to be updated to support it.

## Steps to reproduce
* `gulp serve`
* open `http://localhost:9999/integrationExamples/gpt/userId_example.html?pbjs_debug=true` and look at the console or network tab to see errors

## Related to
* https://github.com/prebid/Prebid.js/pull/5606

**Comment by smenzer** [comment]
still an issue

**Comment by iamnewton** [comment]
Hey @smenzer, I'm new to the project and going to work on this issue but I was wondering a few things and hoping you could clarify for me.

1. Is this still an issue?  From my testing, all of the references to that URL have been commented out
2. When I uncomment and fix the URL as suggested, I'm getting errors on that URL, but not a 404 as I would expect based on your comment, but more a CORS issue.  Is that what you're seeing as well?

**Comment by gglas** [comment]
We're going to split this up - 

1. We're going to clean up website + github examples and delete any that contain references to a CMP (we currently think there are two).  @ChrisHuie 

2. @giniyat202 @ian-lr would you mind helping us update the CMP examples to include up-to-date information?  Seems like it connects to https://github.com/prebid/Prebid.js/issues/6377 

3. We'll start up a larger "example refresh project" in a separate issue and do a double hceck to make sure all examples (both on github and on the website) are up to date.  @ChrisHuie to connect with @patmmccann on other outstanding updates that we need.

**Comment by gglas** [comment]
@ChrisHuie confirming that prebid examples are complete, @giniyat202 and @ian-lr please feel free to open new issues to enhance the documentation if needed.
