### ISSUE TITLE
Prebid with faster way to load DFP library

### ISSUE THREAD

**Issue by chaqu170** [prebid/Prebid.js#572]
Google is recommending that we make changes to the way we load the DFP library to improve GPT load time.

Essentially, they're saying to change this:
```
<script type='text/javascript'>
   var googletag = googletag || {};
   googletag.cmd = googletag.cmd || [];
   (function() {
     var gads = document.createElement('script');
     gads.async = true;
     gads.type = 'text/javascript';
     var useSSL = 'https:' == document.location.protocol;
     gads.src = (useSSL ? 'https:' : 'http:') + '//www.googletagservices.com/tag/js/gpt.js';
     var node = document.getElementsByTagName('script')[0];
     node.parentNode.insertBefore(gads, node);
   })();
 </script>
```

Into this:
```
  <script async src='https://www.googletagservices.com/tag/js/gpt.js'></script>
  <script type='text/javascript'>
    var googletag = googletag || {};
    googletag.cmd = googletag.cmd || [];
  </script>
 ```

This recommendation would be ideal if we weren't running prebid. Is there a way to leverage this faster way of loading with prebid?

**Comment by mkendall07** [comment]
Sure, see this example:
https://github.com/prebid/Prebid.js/blob/3b0b097b712c88756b7ab2c3068272b610da28ca/integrationExamples/gpt/load_pbjs_dfp_concurrently.html

Replace `loadScript('//www.googletagservices.com/tag/js/gpt.js');` with `<script async src='https://www.googletagservices.com/tag/js/gpt.js'></script>` outside of the script tags of course.

**Comment by mercuryyy** [comment]
They both essentially do the same thing, some older browsers still don't support the async tag I'd stick with loading it thought Javascript through the the Dom
