### ISSUE TITLE
Support arbitrary OpenRTB in s2sConfig

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#5720]
## Type of issue
Enhancement

## Description
There's a desire to pass arbitrary values through the Prebid Server Bid Adapter. Currently there are a couple of piece-meal ways to pass values:

- `setConfig({s2sConfig.extPrebid})` option -- limits items to the `ext.prebid` object.
- `setConfig({site})` -- allows setting of openrtb.site values

## Proposal

1. Support an `openRtb` object on the s2sConfig - deep merge it with the final results of OpenRTB2 JSON prepared for transmitting to Prebid Server. Values here take precedence over everthing else.
2. Support an `openRtbImp` object on the s2sConfig - deep merge it with each imp object in the OpenRTB2 JSON

This is a powerful tool and can be be abused -- documentation should warn users to be cautious.

Example:
```
pbjs.setConfig({
    s2sConfig: {
        ...
        openRtbImp: {
            bidfloor: 1.0,
            bidfloorcur: "EUR"
        },
        openRtb: {
           badv: ["adv1.com", "adv2.com"]
        }
    }
});
```

**Comment by bretg** [comment]
@patmmccann and @bszekely1 - setting `bidfloor` globally across all Imps/AdUnits doesn't seem to be the right thing to do here.

Prebid Server could do this, but it would probably take longer to get both PBS-Java and PBS-Go updated.

Do you want to specify a more surgical way of defining the floor-per-imp here?

**Comment by bszekely1** [comment]
While i get the complexities of obfuscating the nuances of OpenRTB behind some friendly API, certain attributes should be applied at the impression grain and other at the top level grain. Bidfloor is on that should be at the imp level.

I would recommend to just create one object called OpenRTB and let people pass a structured object in. It's the most scalable method available.

**Comment by bretg** [comment]
Closing this issue -- this is now overlapping with #5795 . That issue also covers how to add per-imp attributes.
