### ISSUE TITLE
Include ip address in request to prebid server 

### ISSUE THREAD

**Issue by shainep** [prebid/Prebid.js#5733]
## Type of issue

Feature Request

## Description

Currently, pbjs prebid server adapter does not pass ip information in its request to Prebid Server. Could we have pbjs pass device.ip explicitly in the request to Prebid Server.

**Comment by bretg** [comment]
@shainep - there's no need for explicitly adding IP address -- it happens automatically in the HTTP headers part of the browser making an HTTP request.

Prebid Server makes a fairly valiant effort to find the best address to use from the headers, including parsing X-Forwarded-For. See https://github.com/prebid/prebid-server/issues/1332 for the algorithm.
