### ISSUE TITLE
TCF2 cmpApi: 'static' error CMP

### ISSUE THREAD

**Issue by Nicola1976** [prebid/Prebid.js#5747]
HI!

With prebid version 4.0, **TCF2** framework and IAB compliant CMP, as described here I'm trying to use the "static" cmpApi to avoid waiting for the cmp to be ready to make prebid calls after the first user interaction and consent agreement. If the "euconsent" cookie is already available on the page I switch to cmpApi "static" and pass the cookie value with consent string directly to prebid (without waiting fo cmp):

_consentManagement: {
                                                gdpr: {
                                                    cmpApi: 'static',
                                                    consentData: {
                                                        getTCData: {
                                                            tcString: euconsentStored,
                                                            gdprApplies: true
                                                        }
                                                    }
                                                }
                                            }_

With TCF1 as described [in this topic](https://github.com/prebid/Prebid.js/issues/5241) I had similar problem.

The error with TCF2 is different : _**"Prebid ERROR: Error processing command : Cannot read property 'push' of undefined TypeError: Cannot read property 'push' of undefined"**_
![image](https://user-images.githubusercontent.com/14162566/93190070-34dd2880-f743-11ea-9184-faf53bc83465.png)

**No error If I use standard configuration (call prebid.js when CMP is ready):** 

consentManagement: {
                                                gdpr: {
                                                    cmpApi: 'iab',
                                                    timeout: 8000,
                                                    defaultGdprScope: true
                                                }
                                            },

I noticed that if I set a timeout about 1000ms I dont receive the error. It could be a timing issue?

 With TCF1 the solution was **Set gdprApplies': true, also on getVendorConsents object.** Could be same solution for TCF2. How can I pass gdprApplies on getVendorConsent in TCF2 implementation?

Thanks a lot
nicola

**Comment by bretg** [comment]
@Nicola1976  - the example at https://docs.prebid.org/dev-docs/modules/consentManagement.html shows that it wants the `purpose` and `vendor` parsed versions of the string too. See "Example 2 - Static CMP using custom data passing"

That said, the error is odd. Asking @Fawke to take a look.

**Comment by Nicola1976** [comment]
OK thanks a lot @bretg,
please, can you show me an example to pass a purpose and vendor parsed versions of the string inside te getTCData?

What is the most compact object for purpose and vendors with the consent string?

`getTCData: {
                                                            tcString: euconsentStored,
                                                            gdprApplies: true,
                                                            purpose: {
                                                              consents: {
                                                                0: true,
                                                              },
                                                              legitimateInterests: {
                                                                0: true,
                                                              }
                                                            },
                                                            vendor: {
                                                              consents: {
                                                                0: true,
                                                              },
                                                              legitimateInterests: {
                                                                0: true,
                                                              }
                                                            }
                                                        }`

Thanks a lot

**Comment by bretg** [comment]
Prebid.js uses `purpose` and `vendor` to enforce. The values need to correspond to what's actually in the `tcString`. I would recommend against hardcoding those values unless you're completely turning off Prebid.js enforcement of GDPR. In which case something static like what you've proposed might work?

As for converting the tcString to a parsed JSON representation -- the CMP should be able to provide something. Else https://github.com/InteractiveAdvertisingBureau/iabtcf-es

**Comment by Nicola1976** [comment]
Hi , thanks

we don't use gpr enforcement module (
https://docs.prebid.org/dev-docs/modules/gdprEnforcement.html), the TCF v2
is implemented yet. We have just to use static mode if conset is already in
page.
So is it still necessary to pass the purpose and vendors parameters? Can
you provide a practical example to do it?

Thanks





Il giorno mar 15 set 2020 alle ore 17:50 bretg <notifications@github.com>
ha scritto:

**Comment by Nicola1976** [comment]
Hi again,
I'm sorry if I ask you many questions but actually the behavior of the
static cmp is not very clear to me on v2, while on v1 it seemed more linear.

For example,
in this topic https://github.com/prebid/Prebid.js/issues/4801

I see just basic configuration:

[image: image.png]

the tests we did with the bidders without passing vendor and purpose in
static mode had been successful.
But some bidder (appnexus) told us not to use static mode for some possible
problem on bid request.

What do you think about this?

thanks a lot
nicola



Il giorno mer 16 set 2020 alle ore 08:26 Nicola Colombo <
colombo.nicola@gmail.com> ha scritto:

**Comment by Fawke** [comment]
Hi @Nicola1976,

For some reason, I'm unable to reproduce the error that you're getting. Will it be possible for you to share a test page? As @bretg has pointed out, you will need `vendor` and `purpose` as your consentData object. Prebid.js does not parse the `tcString` and depends on the presence of `vendor` and `purpose` to do tcf2 enforcements.

But I think you stated you're not using the Gdpr Enforcement module, so, this should not matter.

[Here](https://gist.github.com/Fawke/5d7b1bb390e63647a39ba0c5e8644f34) is a sample consent data with static cmpApi.

**Comment by bretg** [comment]
> Cannot read property 'push' of undefined 
> I noticed that if I set a timeout about 1000ms I dont receive the error. It could be a timing issue?

This error sounds like some code isn't loaded. 

Please provide your page code or even better, a link to a test page. I'm thinking maybe you've got a timing issue with the structure of your `pbjs.que.push` code.

**Comment by Nicola1976** [comment]
Thanks a lot @bretg and @Fawke, yes it shoul be a timing issue because I check if cmp is ready before calling prebid, if not I set a listener to be shure that is ready.

But @Fawke so in conclusion we dont use gdpr enforcement module so we could not have to use vendor and purpose object and we can use simple:

consentManagement: {
                        gdpr: {
                            cmpApi: 'static',
                            consentData: {
                                getTCData: {
                                    tcString: euconsentStored,
                                    gdprApplies: true
                                }
                            }
                        }
                    },

Just last clarification.The tech team of Bidder Appnexus confirm that "
_The use of the static setting is not compatible with our prebid call, therefore we suggest not to use it: when the TCF information is used, it may not be processed correctly, resulting in a reduction in the effective ad response resulting in a bid._"

Have you some evidence on this problem?

**Comment by bretg** [comment]
> The use of the static setting is not compatible with our prebid call

Help me understand -- are you using a managed service that sits on top of Prebid.js?  If so, you'll need to work with that managed service provider.

I don't believe there's any issue with vanilla Prebid.js and cmpApi=static

**Comment by Nicola1976** [comment]
Hi, no sorry. The sentence*  "The use of the static setting is not
compatible with our prebid call" *

is a phrase that was said to me by the technical team of the *Appnexus
<https://www.appnexus.com/fr>bidder*.
We are publishers.

Appnexus asked us to NOT set static mode on our side (so on the pusblisher
side) because it is not supported by Appnexus, so I guess from their prebid
adapter

thanks
nicola

Il giorno gio 17 set 2020 alle ore 23:57 bretg <notifications@github.com>
ha scritto:

**Comment by Fawke** [comment]
Hey @Nicola1976,

The Appnexus adapter does support static cmpApi config. There's just an extra requirement with Appnexus. You have to explicitly provide purpose 1 consent. Appnexus requires cookies to fill the request, so, there should be purpose 1 consent.

```(javascript)
pbjs.setConfig({
  consentManagement: {
    gdpr: {
      cmpApi: 'static',
      timeout: 5000,
      consentData: {
        getTCData: {
          "tcString": "COuqj-POu90rDBcBkBENAZCg89ruzAAAPAACiQFwwBAABAA1ADEAbQC4YAYAAgAxAG0A",
          "gdprApplies": true,
          "purpose": {
            "consents": {
              "1": true
            }
          }
        }
      }
    }
  }
});
```

This static config should be fine and should work with Appnexus.

**Comment by bretg** [comment]
@Nicola1976 - Please discuss with your legal team before hardcoding consent for any Purpose.

As for the original issue posted here, we still need to see code or a link to a test page. The timing issue could be part of the way the page is structured -- we're not aware of any timing issues that would cause an error like

```
Cannot read property 'push' of undefined
```

**Comment by Nicola1976** [comment]
Hi @bretg and @Fawke, I dont have errore push of undefined anymore since I have modified timing to check if cmp framework is loaded before calling prebid.js

At this test page you could see last implementation with static mode as you suggested (appnexus compliant with purpose 1 consent):

STATIC MODE ACTIVE: http://www.freesenzaglutine.it/?pbjs_debug=true
STATIC MODE NOT ACTIVE (iab standard mode): http://www.freesenzaglutine.it/

le me know
thanks a lot

nicola

**Comment by Nicola1976** [comment]
HIi!

I definitively confirm that if I wait for the cpmt object to be ready or if not ready I wait for the event the error never occurs in the console.

thanks

**Comment by Fawke** [comment]
Hi @Nicola1976,

This looks to me like a cmp error. The error stack also doesn't show if it's originating somewhere on the prebid.js side.Also, I could not get the error even after multiple refreshes on the page that you shared.

I'm happy to look up a test page where I can clearly see your prebid setup and cmp setup.

**Comment by Nicola1976** [comment]
Hi thanks @Fawke,

are you testing this correct? http://www.freesenzaglutine.it/?pbjs_debug=true

It's strange : I have the error in console after just one refresh, maybe two refresh.

So in your opinion, is it correct that prebid.js has to be called only if cmp is loaded? 

I make this question because if I check if cmp is loaded, and I call prebid.js only when cmp is ready, I dont have the error, but with TCF1 I didn't have the same problem. But maybe the cmp was faster then new tcf.

I'm confused...

**Comment by Fawke** [comment]
Hi @Nicola1976,

I do not think prebid.js has to wait for cmp to load if your cmp setup on the page is correct. Ideally, the CMP would have a stub file, loaded synchronously, then, you can have a the actual cmp script loaded asynchronously, and it should not matter if Prebid.js get called before cmp gets loaded because the stub should take care of it.

So, it some look something like this:

```(javascript)
<!-- Load your cmp sub synchronously -->

<!-- Load actual cmp code asynchronously -->

<!-- Load Prebid.js asynchronously -->

pbjs.setConfig({
  // setup the consent management module
})

pbjs.requestBids()
```

Here's a little more info on the cmp [stub](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#how-does-the-cmp-stub-api-work)

Also, there's [this](https://docs.prebid.org/dev-docs/cmp-best-practices.html) guide which might help.

**Comment by Nicola1976** [comment]
Thanks a lot. Last clarification: 

witch is more correct object configuration (properties as string or not)?

consentData: {
                                  getTCData: {
                                      "tcString": euconsentStored,
                                      "gdprApplies": true,
                                      "purpose": {
                                          "consents": {
                                              "1": true
                                          }
                                      }
                                  }
                              }

or

consentData: {
                                  getTCData: {
                                      tcString: euconsentStored,
                                      gdprApplies: true,
                                      purpose: {
                                          "consents": {
                                              "1": true
                                          }
                                      }
                                  }
                              }

**Comment by Fawke** [comment]
Both are fine and would work, it's mostly a matter of preference. Internally, they are treated same. Generally, try to keep it uniform, use one or the other all the way through.

**Comment by Nicola1976** [comment]
Thanks a lot, everything seems ok: https://www.corriere.it/?pbjs_debug=true

thanks again for support

**Comment by Nicola1976** [comment]
Hi @Fawke ,

as you suggested in previous message for appnexus support I set in prebid config consent data obj purpose.consents 1 : true:

"_The Appnexus adapter does support static cmpApi config. There's just an extra requirement with Appnexus. You have to explicitly provide purpose 1 consent. Appnexus requires cookies to fill the request, so, there should be purpose 1 consent._

_consentData: {
        getTCData: {
          "tcString": "COuqj-POu90rDBcBkBENAZCg89ruzAAAPAACiQFwwBAABAA1ADEAbQC4YAYAAgAxAG0A",
          "gdprApplies": true,
          **"purpose": {
            "consents": {
              "1": true
            }**
          }
        }_

"

Now we have configured amazon parallel implementation for prebid and amazon technical team tell us:

_They’ve seen that requests being passed from domains which have your own custom CMP in place (ID – 218), are currently passing purposeOneTreatment as true (1) when you are actually passing purpose 1 in the consent string.
purposeOneTreament = 1 is for cases where the publisher has decided that in their jurisdiction (country) that they do not need to ask for consent for purpose 1 cookies. Amazon would look for purpose 1, see it is not set and punt. purposeOnetreatment = 1 tells us that the user was never asked for purpose 1, which is different to the user saying no. This is coupled with another variable called publisherCC, which is country code._

So the question is: **purposeOneTreatment depends on _"purpose": {"consents": {"1": true}_ prebid configuration or it is a CMP configuration?** 

You can check our cmp live on **www.corriere.it**

Thanks a lot
nicola
