### ISSUE TITLE
Suggestion: Kill Requests after Prebid Timeout

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#575]
So when prebid timeout is hit only bids within the timeout go to "winning bids" but the others can still return a "bid available" at 3000,4000,5000 ms

Do we have to do it that way? it affects overall pagespeed load time average, affecting SEO and publishers decision to use prebid. 

From a technical stand point is it possible to have all the bids called from a container and then kill that container request at prebid_timeout, I dont think we need to keep requests going after prebid_timeout

**Comment by mkendall07** [comment]
Ideally, we would abort theses request that are pending, but most likely doing so wouldn't save much bandwidth (maybe save some JS cycles though). I'll take a look at `window.stop` and see if that's promising.

**Comment by mercuryyy** [comment]
besides bandwidth, overall pageload time should be lowered significantly since requests keep fetching for bids and ads even after prebid timeout is called, some ads call another 20-50 requests ... and so forth. eliminating that will be GREAT for publishers concerned about prebid increasing their the overall pageload time.

**Comment by mercuryyy** [comment]
@mkendall07 have you tried this yet?

**Comment by BartVB** [comment]
This was also discussed in #145

**Comment by mkendall07** [comment]
this is addressed with https://github.com/prebid/Prebid.js/pull/1172
