### ISSUE TITLE
GPT deal-related keys are not always truncated to 20 characters

### ISSUE THREAD

**Issue by indexexchange** [prebid/Prebid.js#578]
Prebid.js generates deal-related key-values in the format: hb_deal_BIDDERCODE = DEAL_ID.

As mentioned in step 2 on http://prebid.github.io/adops/deals.html:

> Note that due to DFP’s character length limit on keys, Index Exchange’s key is truncated to hb_deal_indexExchang

This is indeed the case for winning bids, as per `getWinningBidTargeting`:

```
        return {
            [winner.adUnitCode]: Object.keys(winner.adserverTargeting, key => key)
                .map(key => {
                    return {
                        [key.substring(0, 20)]: [winner.adserverTargeting[key]] // truncates all keys to 20 characters
                    };
                })
        };
```

However, the `getDealTargeting` function only truncates for non-deal keys, not for deal keys:

```
function getDealTargeting() {
    return $$PREBID_GLOBAL$$._bidsReceived.filter(bid => bid.dealId).map(bid => {
        const dealKey = `hb_deal_${bid.bidderCode}`;
        return {
            [bid.adUnitCode]: CONSTANTS.TARGETING_KEYS.map(key => {
                    return {
                        [`${key}_${bid.bidderCode}`.substring(0, 20)]: [bid.adserverTargeting[key]]
                    };
                })
                .concat({
                    [dealKey]: [bid.adserverTargeting[dealKey]] // 'dealKey' is not truncated
                })
        };
    });
}
```

Since all deal bids have their targeting set, this means that deal bids that don't have the highest CPM will potentially be setting DFP keys that are too long.  In particular, this affects IndexExchange's targets, since `hb_deal_indexExchange` (21 characters) will not always be truncated.

**Comment by mkendall07** [comment]
@indexexchange 
Thanks for reporting. We'll take a look

**Comment by indexexchange** [comment]
@mkendall07  -- we already have a fix ready -- I will be committing it shortly, and then I'll make a PR.
