### ISSUE TITLE
Prebid.js downloads broken

### ISSUE THREAD

**Issue by paulm999** [prebid/Prebid.js#5785]
## Type of issue
Bug

## Description
Trying to download prebid.js (4.9.0) from the prebid website, and the js file I get simply says:
{"error":"Prebid file not built properly","requestId":"75f98b8e-d188-4e13-8d93-821a1a1c1f0d"}

**Comment by paulm999** [comment]
This may be related to the Quantcast user id module, removing that solved the problem for me.

**Comment by bretg** [comment]
Fixed - thanks for the bug report
