### ISSUE TITLE
Prebid cmp static additional consent

### ISSUE THREAD

**Issue by Nicola1976** [prebid/Prebid.js#5801]
Hi, I wanted to know if and how the additional consent is passed in the prebid configuration. 

As described [here ](https://github.com/prebid/Prebid.js/pull/5600 )it should be supported: gdpr.consentData.getTCData.addtlConsent. 

Something like this?:

gdpr: {
    cmpApi: 'static',
    consentData: {
        getTCData: {
            "tcString": euconsentStored,
            **"addtlConsent": "some string",**
            "gdprApplies": true,
            "purpose": {
                "consents": {
                    "1": true
                }
            }
        }
    }
}

But I don't quite understand where I should read the string from.
Here a site on which we have implemented the property addtlConsent: http://www.freesenzaglutine.it/

Thanks a lot
nicola

**Comment by patmmccann** [comment]
I think what you are suggesting for static consent works because of this line (L321 in current master)

      consentObject = consentObject.getTCData;

then line 340 does      storeConsentData(consentObject);

then the function does this (consentObject becomes cmpConsentObject inside the function)

    if (cmpConsentObject.addtlConsent && utils.isStr(cmpConsentObject.addtlConsent)) {
      consentData.addtlConsent = cmpConsentObject.addtlConsent;
    };

however I don't see addtlConsent on your test page getConfig. 

![image](https://user-images.githubusercontent.com/1683175/94708688-dd2de800-0312-11eb-81aa-69560507959f.png)

**Comment by Nicola1976** [comment]
Ok thanks,
you don't see the adconsent in the prebid config just because I don't know where to read the string from. 

In case I didn't use the static mode of the cmp prebid module but the iab mode, would the add allow be passed automatically?

**Comment by patmmccann** [comment]
The goal of the pr was that cmp's like quantcast and liveramp that define
the additional consent string as per google's proposal would have that
string added to the prebid internal object for consent. However, ssp's
still need to make adapter commits to gather it on their endpoint calls.
That has not yet happened afaik, but based on discussions in these forums i
do know openx is planning to consume and magnite is not.

**Comment by patmmccann** [comment]
That being said, since it is passed to prebid server endpoint, you can use that endpoint call to validate it is getting set and passed on a live page.

**Comment by ChrisHuie** [comment]
closing issue. Please refer to the explanation provided for more information on consent
