### ISSUE TITLE
Question about openRTB macros within ad markup

### ISSUE THREAD

**Issue by jstocker76** [prebid/Prebid.js#581]
I'm in the process of coding a prebid.js bidder adapter, and until yesterday I optimistically believed it was code complete.  Then QA tells me none of the ad impressions are logged.  Within the ad's markup I see this:

script src=\" yadda yadda yadda &obid=${AUCTION_PRICE}\" type=\"text/javascript\" /script

(I removed the less than and greater thans because github wasn't encoding them properly)

This "${AUCTION_PRICE}" bit is an openRTB macro representing the second price of the auction (the first loser).  At the point my bid is submitted by my bidder adapter, this information is by definition unavailable.  So my questions are:

Will prebid.js support these macros at some point?

Is there currently some way of getting this info from within a bidder adapter?

Currently I have a very hacky way of getting this data by wrapping the ad markup in yet more scripting that scrutinizes pbjs.getBidResponses() when the ad is placed on the page.  I have little confidence it will work reliably.  Any advice?

Apologies if this is the wrong forum for questions such as this

**Comment by mkendall07** [comment]
@jstocker76 
Isn't `${AUCTION_PRICE}` the clearing price? I can see us implementing that, since right now all bids are 2nd price anyway (AFAIK).

**Comment by mkendall07** [comment]
Sorry I think I misunderstood what you were saying. There is no 2nd price auction happening in prebid.js currently. So if your bid is chosen as the winner, the clearing or settlement price is the bid price. Hopefully that clears it up.

**Comment by jstocker76** [comment]
Got it, thanks for the quick info.  I'll close this then
