### ISSUE TITLE
Problem with single page app implementation

### ISSUE THREAD

**Issue by nikkoi** [prebid/Prebid.js#5811]
## Type of issue
Question

## Description
Trying to implement on single app page, not able to only send key-values for only on ad unit

## Steps to reproduce
Not a bug.

## Test page
I'm trying to implement prebid.js on a single app page, using this as the starting point: https://developers.google.com/doubleclick-gpt/samples/infinite-content

Everything else works fine, but the setTargetingForGPTAsync(); always tries to send the key-values for all available ad units, not just the latest one. This is how my moreContent function looks like:

// Function to add content to page

      `function moreContent() {
        // Define the slot itself, register it and fetch an ad.
        googletag.cmd.push(function() {
          var slot = googletag.defineSlot('/xxx/ad_unit_path', [980, 400])
              .addService(googletag.pubads());

          var div = document.createElement('div');
          div.id = slot.getSlotElementId(); // auto-generated by GPT
         /* document.body.appendChild(div); */
          document.getElementById("demo").appendChild(div);;

          // Call display() to register the slot as ready and fetch an ad.
          googletag.display(slot);
          pbjs.que.push(function() {
                    pbjs.requestBids({
                        timeout: PREBID_TIMEOUT,
                        bidsBackHandler: function() {
                            pbjs.setTargetingForGPTAsync();
                            googletag.pubads().refresh([slot]);
                        }
                    });
                });
        });
      }`

In prebid I'm calling the /xxx/ad_unit_path, as it always stays the same. As said, it works fine, but if I refresh for example 10 times, the setTargetingForGPTAsync(); is trying to set the key-values for all the 10 different iterations, when it should only do it for the latest.

### Expected results
Prebid would only send the key-values for the ad unit in question

### Actual results
Prebid tries to send key-values for all the ad units already created on the page

## Platform details
Prebid.js

**Comment by GgermanCrunchmind** [comment]
Hi, you need to specify adUnits which should play in this specific auction.  
```
 pbjs.que.push(function () {
       pbjs.addAdUnits(adUnitIds);
 })
```
```
bidsBackHandler: function () {
        pbjs.setTargetingForGPTAsync(adUnitIds);
        googletag.pubads().refresh(slots);
},
```

**Comment by ChrisHuie** [comment]
@nikkoi was specifying the adUnits able to help solve your problem here?

**Comment by ChrisHuie** [comment]
Closing issue. Please refer to this solution if a similar issue arises
