### ISSUE TITLE
How to setup GPT SRA codes with lazy loading and prebid?

### ISSUE THREAD

**Issue by modessef1** [prebid/Prebid.js#5812]
## Type of issue
question

## Description
Hello,
I want to have some AdUnits set as Single Request Architecture in order to be able to combine them into roadblocks, and I want to call the remaining AdUnits only after meeting the lazy load conditions. In addition, I want to make all AdUnits, both those in SRA and non-SRA (lazy load) available in prebid. Can you tell me how to do it? It's best if I can preview an example setup

**Comment by bretg** [comment]
@modessef1 - this would just be multiple calls to `[pbjs.requestBids()](https://docs.prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.requestBids)`.

The first call would specify the roadblock adunits, while subsequent calls would cover just the adunits in-scope for the lazy-load. See https://docs.prebid.org/dev-docs/examples/adunit-refresh.html for an example.

**Comment by wqi1972** [comment]
@modessef1, Bret's instruction is correct.
If you are still not clear about how to do it, please set up a test page with your ad units in it (SRA batch load ad units + lazy load ad units), I can help you figure out how to change code to achieve your goals.

**Comment by modessef1** [comment]
@wqi1972 can you please have a look at https://www.parkiet.com/Gielda/310029956-Pozytywny-Trump-ciazy-rynkom.html 
As far as I know usage googletag.pubads().enableSingleRequest(); for selected top AdUnits it isn't possible on our website because AdUnits which are placed in the text of the article are generated on the front end side

**Comment by wqi1972** [comment]
@modessef1 Sorry about the delay, I didn't notice your message.
I just checked that page, and think it is possible to change your code to:
1. add 
```
googletag.pubads().enableSingleRequest();
```
current code load one ad a time, add that code won't make any difference;
2. add two new array
```
var dfpAds = [];
var pbAds = [];
```
3. change code
```
if(window.disableHeaderBinding.includes('div-gpt-ad-1561989549889-0')){
  loadDFP('div-gpt-ad-1561989549889-0');
 } else {
   loadHB('div-gpt-ad-1561989549889-0');
 }
```
to
```
if(window.disableHeaderBinding.includes('div-gpt-ad-1561989549889-0')){
  dfpAds.push('div-gpt-ad-1561989549889-0');
 } else {
   pbAds.push('div-gpt-ad-1561989549889-0');
 }
```
4. change function `loadDFP` and `loadHB` to accept array instead of single div, e.g.
```
    function loadDFP(dfpAds) {
    	if (dfpAds.length) {
	      googletag.cmd.push(function() {
	      	var slots = [];
	      	dfpAds.forEach(function(adId) {
	      		slots.push(window.adSlots[adId]);
	      	});
    	    googletag.pubads().refresh(slots);
    	    );
      	  });
    	}
    }
```
5. at end of front end page code, where it finish loading content, call
```
loadDFP(dfpAds);
loadHB(pbAds);
```
6. adjust lazy loading code a bit for the array interface, so it will be:
```
loadDFP([ad.id]);
```
instead of
```
loadDFP(ad.id);
```

Hope it helps.

**Comment by ChrisHuie** [comment]
Please refer to comments for further explanation on issue.
