### ISSUE TITLE
eids permissioning scheme 

### ISSUE THREAD

**Issue by jdwieland8282** [prebid/Prebid.js#5814]
## Type of issue
feature request

## Description
Do Publishers need additional controls for determining which user ids go to which bid adapters?  Publishers can currently control what User id modules they deploy and which bid adapters they integrate with.  Are their scenarios where a publisher would deploy a user id module but decide NOT to send the resulting user id to a bid adapter they've integrated with? If we believe there are then a permissioning structure in the eids config is needed. 

## Proposed Structure 
```
pbjs.setConfig({
    userSync: {
        userIds: [{
            name: "MODULE NAME",
            **bidders: ['bidderA', 'bidderB'], // new permissions field. This ID can only go to these bidders.**
            params: {
                ...
            }
        }]
    }
});
```

### OpenRTB support
```
{
    ext: {
        prebid: {
            data: {
                bidders: ['bidderA','bidderB']
            }
        }
    }
}
```

**Comment by bretg** [comment]
Implications for PBJS:
- something would need to modify the bidRequest object before going to each bidder.
- unclear whether this is PBJS-core or perhaps its just done through a hook in the UserId module itself

Implications for Prebid Server:
- This proposal treats eids as first party data, using the same permissioning scheme. But if pubs need some eids to be global, while other eids are first party data, we'll need to extend the permissioning scheme. 

**Option 1**:  put eids permissions alongside FPD permissions
```
{
    ext: {
        prebid: {
            data: {
                bidders: ['bidderA','bidderB'], // this is for FPD
                eidPermissions: [
                   {"source": EID_SOURCE, "bidders": ["bidderA"]}
                ]
            }
        }
    }
}
```
One issue is that the PBJS config for user ID sub-modules isn't directly linked to the eids.source field, so the pbsBidAdapter doesn't have all the right info here. Possible solutions include specifically naming the eids.source in the config or retrofitting all the userId modules to support a function confirming whether a given source 

**Option 2**: eids.ext.bidders
- add a routine to the userId module that sub-modules have to use to register their eids. UserId-core adds any bidder config
 




-

**Comment by bretg** [comment]
Updated openrtb spec

**Comment by gglas** [comment]
@jdwieland8282 we think this issue is closed, please let us know if any reason to repon.
