### ISSUE TITLE
Function to check the cached bids from the bid pool

### ISSUE THREAD

**Issue by Deimos01** [prebid/Prebid.js#5817]
## Type of issue
Question about the public API methods

## Description

Hi there, 
I'm looking for a function to get the cached bids from an AdUnit-specific bid pool.
I've checked all the functions from the [API methods](https://docs.prebid.org/dev-docs/publisher-api-reference.html) but none of them is able to retrieve the cached bids.
I'm just wondering if there is a way to get them or more globally, just be able to check the bid pool and get the cached + fresh bids after a refresh.

Thanks

## Platform details
4.6.0 + `useBidCache: true`

**Comment by patmmccann** [comment]
What's your use case? You can use the ttl. If you have the expiration date of the eggs in your fridge,  why does it matter which trip to the grocery store you got them on?

**Comment by gglas** [comment]
Hey there - we think this is addressed using https://docs.prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.getBidResponsesForAdUnitCode .  This pulls in responses for all auctions, not just the latest (or it should) -- the regular getBidResponses, however, does not.  This means that it includes both bids that are "cached" which really just means from another auction and those from the latest auction.  Please let us know if you have any further questions, closing for now!
