### ISSUE TITLE
Should pbjs.refreshUserIds() pass a flag to user id modules that it was refreshed by the publisher?

### ISSUE THREAD

**Issue by smenzer** [prebid/Prebid.js#5818]
## Type of issue
Question / Feature Request

## Description
Per https://github.com/prebid/Prebid.js/pull/5752, publishers now have the ability to force a refresh of all or a subset of user id modules for a variety of reasons (the user logged in / out and they want to get new IDs, for example). We could easily pass a flag to the user id submodules in the `getId()` function to tell them that this was a force refresh rather than a normal call (because the old id in cache expired, consent changed, etc). 

So the question is, would it be useful to user id submodules to receive this flag? Taking it a step further, would it be useful to know the exact reason `getId` was called (there are several reasons it can be called) rather than just if it was a force refresh?

**Comment by gglas** [comment]
@smenzer hey Scott, this has sat idle for awhile -- would this be useful for you guys?  If so happy to collaborate on development, otherwise I think we can close this issue.

**Comment by smenzer** [comment]
We don't have any use for this today, so I'm ok if we close it.
