### ISSUE TITLE
Receive bids which responds before PREBID_TIMEOUT

### ISSUE THREAD

**Issue by tmkdudek** [prebid/Prebid.js#582]
Hi, 

If we set PREBID_TIMEOUT = 1000, and one of bidders take 1.5s to respond, while others responds in 500ms. Handler below ( bidsBack) doesn't fire and i haven't any bid results. Is it possible to fix that,? 

` pbjs.requestBids({

            bidsBackHandler: sendAdserverRequest

        });`

**Comment by protonate** [comment]
Do you have a test page that demonstrates this behavior?

**Comment by tmkdudek** [comment]
Sure,
use example
http://jsfiddle.net/bhn3xk2j/104/

In this example, prebid make 2 requests. Run Fiddler, and delay one of them by e.g 5000ms.
http://ib.adnxs.com/jpt?callback=pbjs.handleAnCB&callback_uid=2639d169b70979&psa=0&id=4799418&size=300x250&promo_sizes=300x600&referrer=http%3A%2F%2Ffiddle.jshell.net%2Fbhn3xk2j%2F101%2Fshow%2F	

http://ib.adnxs.com/jpt?callback=pbjs.handleAnCB&callback_uid=39f06e4a2e55c6&psa=0&id=4799418&size=728x90&promo_sizes=970x90&referrer=http%3A%2F%2Ffiddle.jshell.net%2Fbhn3xk2j%2F101%2Fshow%2F

Then, open dev console in e.g Chrome, and you will see logs:

PREBID TIMEOUT - MUST SEND ADSERVER REQUEST
 BIDS BACK

Timeout happens earlier than bids back, and adserver request don't have access to bid results.

**Comment by mkendall07** [comment]
may be related to #604

**Comment by tmkdudek** [comment]
Thanks, it is related.
