### ISSUE TITLE
User sync - who get the chance ?

### ISSUE THREAD

**Issue by noamtzuberi** [prebid/Prebid.js#5848]
## Type of issue
question

## Description
Hi,
I've a small question that I didn't find any answer in the docs.
Who is getting the chance to make sync? only bidders, that return bid? only the winning bidder? 

Thanks

**Comment by jsnellbaker** [comment]
Hi @noamtzuberi 

For UserSync, it's based on who the publisher gives permission to sync.  As part of their prebid config setup on a webpage, they have to set up the config rules for the `userSync` feature.  Part of this config is setting a list of bidders based on an inclusion/exclusion filter.

The following page has some more details on the setup, with some example configs that give some context as to how the filtering would work:
https://docs.prebid.org/dev-docs/publisher-api-reference.html#setConfig-Configure-User-Syncing

Please let me know if you have any questions on this feature.

**Comment by noamtzuberi** [comment]
Hi @jsnellbaker,

Thanks for the answer.
I'm familiar with this doc and read it again. This section describes how to implement the sync from the publisher side, I'm asking about the behavior of the wrapper himself assuming the publisher has configured to run sync in some method(pixels/iframe).

If I (as a buyer) returned a bid, this means that my sync will run or it will be run only if I won the auction between the bidders?
Thanks.

**Comment by jsnellbaker** [comment]
Hi @noamtzuberi 

Your syncs would trigger regardless if you won the auction or not.

**Comment by noamtzuberi** [comment]
Got it @jsnellbaker.

Last question, in case I don't have a bid to return, can I return an empty vastXml (string empty) **with sync** in order to run the sync to identify the user and have the ability to give a better bid when I meet the user next time?

I don't have a sync module inside my adapter, but my own sync system.

**Comment by jsnellbaker** [comment]
Hi @noamtzuberi 

I believe that should work.  To clarify a point, by `I don't have a sync module inside my adapter, ...` - are you referring to the `getUserSyncs` function in your adapter's spec object?  Or something else?

**Comment by noamtzuberi** [comment]
Hi @jsnellbaker and thanks for your answer.
I've `getUserSyncs` function in my adapter, I don't have sync as a module (TTD, IndexExchange, etc.).

I want to be able to run my sync (getUserSyncs function) **even** if I don't have a bid, in order to be able next time to give a better bid after I'm familiar with the user. It's possible?

**Comment by noamtzuberi** [comment]
Hi @jsnellbaker, a gentle reminder. Thanks

**Comment by jsnellbaker** [comment]
@noamtzuberi Sorry for the delay, that behavior happens by default.  So it sounds like you should be all set.

Are you seeing something different?

**Comment by patmmccann** [comment]
This appears good to close.

Bid adapters don't develop separate sync modules and the op's requested behavior of firing bid adapter syncs without wins happens by default already.

**Comment by noamtzuberi** [comment]
Thanks. works for me.
We can close it!
