### ISSUE TITLE
Issue With Prebid Update

### ISSUE THREAD

**Issue by maxkil123** [prebid/Prebid.js#5865]
## Type of issue
Prebid Script Not Working Upon Prebid Update and Browser Change

## Description

Hello,

Recently, I updated prebid scripts to use a new version and change an adapter along with the parameters.  The old version is working fine; however, the new version is not sending bid responses.  I am only able to see responses when I debug the page and type in the request within the browser console.  I am trying to figure out what changes I need to make to the prebid script (found [here](https://d2zfowlldib7se.cloudfront.net/assets/mcclatchy/js/PrebidConfigAdPerfectMW-new2.js)) to execute prebid successfully.  Any assistance is greatly appreciated.
## Test page

https://classifieds.bnd.com
https://classifieds.bellinghamherald.com
### Expected results
Prebid is supposed to execute successfully and request bids from bidders and send responses (e.g. https://classifieds.kansas.com).
[2020-10-14 -MCI- AdPerfect.txt](https://github.com/prebid/Prebid.js/files/5393376/2020-10-14.-MCI-.AdPerfect.txt)
[2020-10-14 -MCI- MWAdPerfect.txt](https://github.com/prebid/Prebid.js/files/5393377/2020-10-14.-MCI-.MWAdPerfect.txt)

### Actual results
Nothing happens.
## Platform details

Prebid version 4.11.0
OS Windows 10

**Comment by GLStephen** [comment]
I think that you have the Appnexus analytics enableAnalytics call, but your Prebid has only been built with the Appnexus bid adapter, not the Appnexus analytics adapter.

**Comment by maxkil123** [comment]
Thank you @GLStephen.  AppNexus informed me that they no longer use the Analytics adapter, so I will try removing the code and seeing if that works.

**Comment by GLStephen** [comment]
@maxkil123 I'm closing this, please reopen if still an issue
