### ISSUE TITLE
Contribute a Prebid Server adapter while not being a SSP/exchange

### ISSUE THREAD

**Issue by leonhfr** [prebid/Prebid.js#5875]
## Type of issue

Question

## Description

Hi all. In the [help page](https://docs.prebid.org/support/) I read that:

> Each demand adapter should be maintained by the SSPs or exchange behind that adapter.

However, we are in the situation where the bidder we would like to target has a Prebid.js adapter, but no Prebid Server adapter, and we would prefer to use Prebid Server exclusively.

In this event, would there be anything against us contributing a Prebid Server adapter for this bidder?

**Comment by bretg** [comment]
It would be fine to submit a PR over at the [Prebid Server repo](https://github.com/prebid/prebid-server/pulls) - when you do, please add some contact information for the company that actually owns the endpoint so we can verify they're good with the work being done on their behalf.
