### ISSUE TITLE
Console - No bids?

### ISSUE THREAD

**Issue by ktmcc** [prebid/Prebid.js#588]
More often than not, when we load the console on our [test page](http://www.suncycler.com/work_docs/Untitled-4.html?pbjs_debug=true), we fail to see bid activity or ads from our prebid vendors. Why is this happening?

**NO BID ACTIVITY**
![NO BID ACTIVITY](https://cloud.githubusercontent.com/assets/21362995/18131674/b250427a-6f61-11e6-9741-0a822c41ef54.png)

**BID ACTIVITY + ADS RENDERED**
![BID ACTIVITY + ADS RENDERED](https://cloud.githubusercontent.com/assets/21362995/18131726/e5e29994-6f61-11e6-892c-165c09f8b7e0.png)

Also, we're experiencing several other issues with our implementation. Should I submit these as separate threads?

**Comment by mercuryyy** [comment]
that error has nothing to do with no bids remove

"                var targetingParams = pbjs.getAdserverTargeting();
                var container = document.getElementById('container');
                container.innerHTML = JSON.stringify(targetingParams, null, 2);
"

from your implementation

**Comment by ktmcc** [comment]
Thanks for the heads up about the newer version. Otherwise, I'm not worried about the error, so much as I am with seeing no bid activity or ads. In my second screenshot, the same error is still there below the bids, so we've ruled that out as being related.

**Comment by mercuryyy** [comment]
so assuming the second screenshot is a working example, you know not every load you will see bids in console.

if the bid timeout is over your prebid timeout value it will not show in the console debug output, you can use this code snippet to see your bids ms

var responses = pbjs.getBidResponses();
var output = [];
for (var adunit in responses) {
    if (responses.hasOwnProperty(adunit)) {
        var bids = responses[adunit].bids;
        for (var i = 0; i < bids.length; i++) {
            var b = bids[i];
            output.push({
                'adunit': adunit, 'adId': b.adId, 'bidder': b.bidder,
                'time': b.timeToRespond, 'cpm': b.cpm, 'msg': b.statusMessage
            });
        }
    }
}
if (output.length) {
    if (console.table) {
        console.table(output);
    } else {
        for (var j = 0; j < output.length; j++) {
            console.log(output[j]);
        }
    }
} else {
    console.warn('NO prebid responses');
}

**Comment by ktmcc** [comment]
Should the code snippet above be placed in the timeout script or the boilerplate script?

**Comment by mercuryyy** [comment]
no after page load in debug mode echo that code into the console text area and it will display a table with the bids received

**Comment by mkendall07** [comment]
@ktmcc 
You won't always get bids back. If you are seeing things work when bids are back than it's most likely working as expected.

**Comment by ktmcc** [comment]
Understood. So I guess this leads into another issue. We'll see bid data, but a house ad will show instead of the bidder's, which happens in the last ad call. Is this the result of the ad server loading too late?

**Comment by ktmcc** [comment]
Thanks for the snippet. Based on the screenshot below, am I correct in understanding that no bids showed in the console because the time to return bids (shown in the table) was too long? Our timeout is 400. We've been playing with this to see if our results change, but aren't noticing a difference. It was initially set to 800. ([test page](http://www.suncycler.com/work_docs/Untitled-4.html?pbjs_debug=true))

![screen shot 2016-08-31 at 11 21 46 am](https://cloud.githubusercontent.com/assets/21362995/18134763/85e453b4-6f6d-11e6-9270-c04da7cd95c6.png)

**Comment by mercuryyy** [comment]
@ktmcc  exactly, sovrn did not return a bid and rubicon returned a bid response after your prebid timeout set thats why no wining bids showed in your output.

see the issue @mkendall07  referred to. It help me with rubicon response, i'd recommended you set timeout at 1150 and then slowly go down day by day.

**Comment by ktmcc** [comment]
Thank you both for the help! We're making adjustments and will continue to test and iterate from there. Are you running Sovrn by any chance? We rarely get a returned bid from them.

**Comment by ialex** [comment]
We have observed that ad networks bids based on geo sometimes using a US ip returns more result than any other GEO and also ad networks doesn't bid a lot after initial page views 5-6 you have been refreshing a few times and the bid count should be reduced.
