### ISSUE TITLE
bids not requested when using IdentityLink and userSync.auctionDelay with version 4.12

### ISSUE THREAD

**Issue by jarnix** [prebid/Prebid.js#5882]
## Type of issue
Bug

## Description
When setting "auctionDelay" parameter with the module for syncing users "Identity Link", the bids requests are not called on the second time the page is displayed, with a silent error (nothing in the console's debug, no js error...) in versions of prebid > 4.12. Prebid is stuck.

## Steps to reproduce
Instantiate userSync with the Identity Link module enabled on the v 4.12 of Prebid.
Setup the user sync with the userSync.auctionDelay parameter (50 for example). The first call of the page will make the requests correctly.
When we request this page the second time, the Identity Link module seems to block everything, no bids are requested.

- Apparently, the first time the Identity Link module sets a cookie called "_lr_retry_request". Removing the cookie on the subsequent calls makes Prebid act correctly again, with or without the "auctionDelay" parameter in userSync config.

- Removing the "userSync.auctionDelay" parameter also makes Identity Link behave normally.

## Test page
This is our test page with userSync.auctionDelay set :
https://mediaathay.org.uk/jsfiddle_withAuctionDelay.html

=> first time, everything is okay
=> second time, no bids are requested

This is our page without this parameter:
https://mediaathay.org.uk/jsfiddle_withoutAuctionDelay.html

=> always a correct result
 
Don't try to check this issue on jsfiddle since the cookie won't be set (I suppose it's a browser policy), check on a local or full page environment. The first page you can see that the CMP is displayed, then the bids are requested and the ads are displayed. After a refresh of this page, Prebid is stuck and is not making the bids requests. If you remove the cookie "_lr_retry_request" and refresh, then the bids requests are done and the ads are displayed. You can also remove the parameter "auctionDelay" and the code is working fine. In our case, we need the auctionDelay to be set for other user id modules.

### Expected results
The bids should be requested even if auctionDelay is set.

### Actual results
The bids are not requested.

## Platform details
We tried on Linux and Windows, Firefox and Chrome.

## Other information
None

**Comment by FilipStamenkovic** [comment]
@jarnix This should be fixed starting with pbjs 4.16.0.  
Can you double check.

**Comment by jarnix** [comment]
thank you, it's working fine on the 4.16 that we now use in production 👍

**Comment by FilipStamenkovic** [comment]
@jarnix great, you're welcome. Can you, then, please close this issue?

**Comment by jarnix** [comment]
done :)
