### ISSUE TITLE
Header Bidding for Dummies

### ISSUE THREAD

**Issue by sshcli** [prebid/Prebid.js#5897]
Hi Mates,
Congratulations for this beautiful project, I wish you success!

Sorry for my stupid question, but this is my first day trying to implement Header Bidding on my website.

I have completed the Step By Step Guide to Google Ad Manager (Thanks btw) you have posted here:
https://docs.prebid.org/adops/step-by-step.html

But now what?
What additional steps I must do?
I have read a lot of things, but...
I still don't know if I need to upload some files to my server,
I still don't know if I need to build something
I still don't know if I need to approach bidders by my self and what to say
I still don't know if I will need a Header Bidding partner, or this is something I can do it by my self

If anyone can please point me into the right direction, I will really appreciate it.
The ABC of Header Bidding (Header Bidding for Dummies)

Thanks in advance

Regards,

**Comment by bretg** [comment]
@sshcli - we'll put it on our list to generate a high level checklist for a header bidding implementation. In the meantime, you should just search. e.g. "header bidding basics" revealed references that may help you like https://adprofs.co/beginners-guide-to-header-bidding

> I still don't know if I need to upload some files to my server

Yes, you will need to create a Prebid.js build and host it along with your web pages

> I still don't know if I need to build something

Your web pages need to integrate with Prebid.js javascript

> I still don't know if I need to approach bidders by my self and what to say

Yes. You need to have an account with each bidder. 

> I still don't know if I will need a Header Bidding partner, or this is something I can do it by my self

Many pubs do header bidding on their own. Many partner with a [managed service](https://prebid.org/product-suite/managed-services/).

**Comment by sshcli** [comment]
Thanks @bretg for your kind response.
Yesterday after create the issue here, I found on internet this:
https://fidelity-media.com/2017/03/23/prebid-js-step-step-installation-guide

However, I believe that you offer a very great solution for publishers, and that simple information should be included in your website, it will avoid a lot of unnecessary questions.

Thanks again @bretg 
Maybe I will see you later reporting new bugs, creating simple PRs, etc.

**Comment by bretg** [comment]
Will track this documentation request over at https://github.com/prebid/prebid.github.io/issues/2533
