### ISSUE TITLE
Creating alias adapter with AppNexus as Bidder Server

### ISSUE THREAD

**Issue by coedmedia** [prebid/Prebid.js#5901]
## Type of issue
Question

## Description
Disclaimer: Sorry if this is not the right place for this question.
I'm trying to create a new header bidding adapter and use AppNexus as our Bidder Server. 
So it would be a alias bidder for AppnexusBidBidder ( https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js ). I don't find any documentation on how to go about it.

Any help in the right direction is appreciated.

thank you

**Comment by robertrmartinez** [comment]
@coedmedia 

Can you elaborate more on what you are trying to do?

Is it simnply an implementation question?

How to build a prebid wrapper and use the Appnexus module using some other bidderCode?

Or are you actually wanting to create a new module?

Are you a publisher? Or from an SSP?

Please explain in more detail what you are trying to achieve.

**Comment by coedmedia** [comment]
Hi @robertrmartinez 

I'm from an SSP. We monetize inventory on multiple publishers using Prebid.JS while managing inventory through a GAM account.

While for some publishers we issue whole tags with Prebid.JS implementation, for others who are already using Prebid.JS, we issue additional demand through our partnerships with existing header bidding demand partners.

Now, we are wondering if we can create an adapter of our own and use Appnexus AdServer as our bidder ad server to manage our demand.

Having our own adapter might help in allowing our publishers who are already using Prebid.JS to use our adapter directly unlike us modifying their Prebid tags every time to include additional demand we bring in.

thank you

**Comment by robertrmartinez** [comment]
I will pass this off to the Appnexus team since I cannot just make that decision for them.

@jaiminpanchal27 @jsnellbaker Can one of you, or someone from your team work with @coedmedia on what exactly they want to do?

**Comment by gglas** [comment]
Discussing on Issue review today, would the solution just be to add yourselves as an official alias to this ?https://github.com/prebid/Prebid.js/blob/62e2169ec72c17ee3e7eb70e8a1263c961bf5d1a/modules/appnexusBidAdapter.js ? 

@jsnellbaker would there be anything else to it?

**Comment by gglas** [comment]
Hey @jsnellbaker we'd love to close this out and hopefully it's a straightforward solution -- WDYT?

**Comment by jsnellbaker** [comment]
I'm sorry for the delay here.  @coedmedia please just add your name to the object list in a PR.  If you have your own `glvid`, please include that as well.
