### ISSUE TITLE
JSON import warning in webpack 5

### ISSUE THREAD

**Issue by gpoitch** [prebid/Prebid.js#5909]
## Type of issue

bug

## Description

Webpack 5 emits a warning when importing named exports from json files:

```
"WARNING in ../../node_modules/prebid.js/src/secureCreatives.js 15:16-30
Should not import the named export 'EVENTS'.'BID_WON' (imported as 'EVENTS') from default-exporting module (only default export is available soon)"
```

### Expected results
No warnings
### Actual results
A warning coming from src/secureCreatives.js
## Platform details

Prebid 4.13.0, macOS, node 14, webpack 5
## Other information

This is the fix/PR: https://github.com/gpoitch/Prebid.js/pull/1/files
Having some odd trouble with trying to view/PR anything in this repository.

**Comment by GLStephen** [comment]
Duplicatee #5933
