### ISSUE TITLE
Feature request - extend fpd.user object to allow segment registry information

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#5913]
## Type of issue
Feature Request

## Description
Currently, several providers allow for the passing of user segments to prebid adapters. Eg, Permutive enables businessinsider.com to pass Permutive segment ids to AppNexus and Index Exchange endpoints. However, it seems this should be more generic. 

Any publisher should be able to pass a segment identifier to any SSP on the fpd.user object. However, we need a way to specify what a segment means succinctly. Datalabel.org seems to be a good place for that. 

Perhaps fpd.user.data needs a slightly more complicated example structure. 

Potentially:

`pbjs.setConfig({
   fpd: {
       context: {
           keywords: "power tools", // keywords is a standard OpenRTB field
           search: "drill",         // same with search and content
           content: { userrating: 4 },
           data: {
               pageType: "article",
               category: "tools"
           }
        },
        user: {
           keywords: "a,b", // keywords is a standard OpenRTB field
           data: {
              registry: permutive,
              segments: ["123","456"]
           },
           data: {
              registry: datalabel,
              segments: ["789","1011"],
              recency: "20200901"
           }
        }
    }`

##Testpage
Current behavior exemplified at https://www.businessinsider.com/how-ants-escaped-nuclear-weapons-bunker-survived-on-cannibalism-2019-12

**Comment by bretg** [comment]
This is related to https://github.com/prebid/Prebid.js/issues/6057

Perhaps `recency` can go in user.data[].ext and site.content.data[].ext?

**Comment by bretg** [comment]
Covered by #6057
