### ISSUE TITLE
Feature: getNoBidsForAdUnitCode

### ISSUE THREAD

**Issue by r-schweitzer** [prebid/Prebid.js#5931]
## Type of issue
Feature

## Description
Add prebid global function to get noBids by adunit much like getBidResponsesForAdUnitCode

## Other information
https://github.com/prebid/Prebid.js/pull/5932
https://github.com/prebid/prebid.github.io/pull/2498/files

**Comment by bretg** [comment]
Closing -- PR has been merged.
