### ISSUE TITLE
removeComplete() potential bug

### ISSUE THREAD

**Issue by anxobotana** [prebid/Prebid.js#594]
removeComplete() doesn't clear _bidsReceived with empty or error status. The array keeps growing with bids having an empty or error status every time an ad unit is refreshed.

the current code is ( prebid.js line ~270 ):
```javascript
  // also remove bids that have an empty or error status so known as not pending for render
  responses.filter(bid => bid.getStatusCode && bid.getStatusCode() === 2)
    .forEach(bid => responses.slice(responses.indexOf(bid), 1));
```
and it should be **splice** instead of **slice** or am i missing something?

**Comment by protonate** [comment]
Thanks @anxobotana , and please feel free to open a PR if it's taking too long for these quick fixes :)
