### ISSUE TITLE
_gd cookie is created multiple times causing critical 400 error

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#5942]
Prebid 4.15, built with User ID modules are adding a _gdxxxxxx cookie each sessions.
(i only checked with User ID PubCommon ID)

This can cause a 400 error on nginx easily for pages with a lot of pageviews, the session cookie is not behaving right and the _gd cookie is being creating every page view causing multiple _dg cookies being created over and over again.

They are session cookie so once browser is closed they are deleted but if the user goes through enough pages it will cause a global 400 error which will actually block access to the entire website.

I would assume the _gd cookie should be created only once.

I also build prebid without gdpr module and only with User ID PubCommon ID and it will still create the _gd cookies.

**Comment by smenzer** [comment]
It seems that this is not specifically related to PubCommonId module, as I see it happening on a test page with just the ID5 module activated. so likely, it's somewhere in core userId module code or in the way storagemanager works with userid

**Comment by smenzer** [comment]
I take that back...if I build pbjs without PubCommonId module, this doesn't happen. I think I found the offending code here, although it's not immediately clear to me why it's executed when I do not include the PubCommonId Module in my config:
https://github.com/prebid/Prebid.js/blob/master/modules/pubCommonIdSystem.js#L289

We might need to add this before returning on line 299?
```
storage.setCookie(cookieName, '', 'Thu, 01 Jan 1970 00:00:01 GMT', undefined, nextDomain);
```

**Comment by smenzer** [comment]
@jsnellbaker seems to have made the last update to this bit of code and @Fawke reviewed, so maybe one of them could add some more color here?

**Comment by smenzer** [comment]
i think this is because of https://github.com/prebid/Prebid.js/blob/master/modules/pubCommonIdSystem.js#L305 being called every time the module is registered, rather than only when needed by the submodule here https://github.com/prebid/Prebid.js/blob/master/modules/pubCommonIdSystem.js#L40

**Comment by pycnvr** [comment]
@smenzer This pique my interest.  Your PR will definitely alleviate the immediate issue.  I suspect that the root problem is that setCookie is async now, and readCookie will almost always fails.  So the function domainOverride won't correctly find the top-level domain but instead returns undefined most of the time.

**Comment by pycnvr** [comment]
Nope.  I was wrong.  This weird behavior is only true if called during module load.   Scott's PR is correct.
