### ISSUE TITLE
[Question] Create new adapter - Passing multiple creatives to 1 ad slot

### ISSUE THREAD

**Issue by fasenderos** [prebid/Prebid.js#5945]
## Type of issue
Question

## Description
I'm trying to create an adapter (only `NATIVE`) for our SSP (`ourssp`). As I understand,  each `adUnit` corresponds to 1 slot to display 1 creative.

We provide to our publishers a widget that, depending on the widget type, can display from 1 to 9 creatives (grid 1x1 to 3x3), so in our case 1 `ad slot` can have multiple ads. 

In the `bid.params` I can pass the `widgetId` and the server responds with a list of creatives (the number of creatives varies according to the type of widget).

Imagine that the widget with ID 1234 can display 3 creatives and I want to fetch `ourssp` and `appnexus`. Since AppNexus, and I think all other SSP, responds with 1 creative for 1 slot, I assume that I have to create 1 `adUnit` that call both the bidders and 2 `adUnit` (with the same `code` of the first) that call only `appnexus`, something like:

```
var adUnits = [{
    code: 'div_1234',
    bids: [
       {
          bidder: 'appnexus',
          params: {
             placementId: 13232354,
          }
       },
       {
          bidder: 'ourssp',
          params: {
             widgetId: 1234
          }
       }
    ]
  },
  {
    code: 'div_1234',
    bids: [
       {
          bidder: 'appnexus',
          params: {
             placementId: 13232354,
          }
       }
    ]
  },
  {
    code: 'div_1234',
    bids: [
       {
          bidder: 'appnexus',
          params: {
             placementId: 13232354,
          }
       }
    ]
  }
]
```
Is that right or there is a better way to telling other SSP to responds with multipe ads for 1 ad slot?

Is it completely wrong to use 1 ad slot for multiple ads or I am missing something?

Thanks in advance.

**Comment by bretg** [comment]
A model of showing multiple AdUnits within a single ad isn't supported. You need to think of them as multiple AdUnits, meaning multiple AdUnit codes.

```
var adUnits = [{
    code: 'special',
    ...
  },
  {
    code: 'special-2',
    ...
  },
  {
    code: 'special-3',
    ...
  }
]
```

Then you can't rely on renderAd() -- you'll need to implement some rather sophisticated code to scrape the AdUnits together into a 'meta-creative'. Maybe on the AUCTION-END event? Something that scans the auction for AdUnit.codes with the "special-*" prefix, gathers the bids, and resolves some kind of template. And then maybe update the 'main' AdUnit bidresponses to have the desired creative body.

i.e. you're going to have to innovate a set of instructions and in-page code that your publishers would utilize.

**Comment by fasenderos** [comment]
Hi @bretg thanks you, that sound good enough to me. Just to be sure, the same `placement_id` can be used for multiple AdUnits, or I have to create 3 different `placement_id` ? Form [here ](https://docs.prebid.org/dev-docs/examples/multi-format-example.html) it seems possible, but I'm not sure if there will be any drawbacks on this.

**Comment by bretg** [comment]
Prebid.js doesn't validate bidder params, so this would be a question for the specific bidder -- whether they'll return multiple bids on the same set of params.

**Comment by bretg** [comment]
Can we close this one @fasenderos ?

**Comment by fasenderos** [comment]
Yes thanks

Il giorno mar 1 dic 2020 alle 17:06 bretg <notifications@github.com> ha
scritto:

**Comment by fasenderos** [comment]
@bretg yes thanks, I close it.
