### ISSUE TITLE
Utils.isEmpty or Telaria bidder bug?

### ISSUE THREAD

**Issue by grajzer** [prebid/Prebid.js#5958]
## Type of issue
Bug

## Description
utils.isEmpty() function will always return true if integer is passed. isEmpty(1) returns true.

If that's an expected behavior, than there's a bug in telariaBidAdapter and the way it constructs schain string -- hp value 1 will always translate to empty string.

**Comment by bretg** [comment]
The first line of `isEmpty` says that if the argument isn't an object, then it's considered empty.
```
if (!object) return true;
```

What schain are you having trouble with in Telaria? I made a test page and see the chain being passed in the URL:

```
                pbjs.setConfig({
                  "schain": {
                    "validation": "strict",
                    "config": {
                      "ver":"1.0",
                      "complete": 1,
                      "nodes": [
                        {
                          "asi":"indirectseller.com",
                          "sid":"00001",
                          "hp":1
                        }
                      ]
                    }
                  }
```
Winds up as: &schain=1.0,1!indirectseller.com,00001,,,,

**Comment by grajzer** [comment]
Hi @bretg , thanks for taking a look. Looking at this part of the code:

https://github.com/prebid/Prebid.js/blob/678ffdfd69a666570dab4738c8b665b686a16458/modules/telariaBidAdapter.js#L148

I think that expected request should look like this:

&schain=1.0,1!indirectseller.com,00001,1,,,

Some publishers noticed and asked why hp value is not passed...

**Comment by bretg** [comment]
Adding @telariaEng 

This seems odd because node.sid is a string (not an object) and it's showing up.

**Comment by bretg** [comment]
Closing since the PR has been merged.
