### ISSUE TITLE
Lose notification - question 

### ISSUE THREAD

**Issue by Mualemy** [prebid/Prebid.js#5960]
Hi,

I have two questions please - 

1. Is there a way to get a "lose notification" from the wrapper to the adapter (the winning bid in the auction when the adapter loses)?
2. Is it possible to rename the adapter after it's already live and running?

Thanks!

**Comment by wqi1972** [comment]
1. Not as I know of.
2. If I understand your question correctly, you can try pbjs.aliasBidder
e.g. pbjs.aliasBidder('ix', 'indexExchange', { gvlid: 10 }); 
this is the solution we use to use ix but still keep indexExchange key inside GAM.

**Comment by bretg** [comment]
We'll put Loss notification on a roadmap for 2021. The best way to implement it is not obvious.

- We may not want each adapter to do its own thing without publisher control
- Supporting notifications in SDK and AMP would require Prebid Server support
