### ISSUE TITLE
33across seems to be returning "rubicon" as hb_bidder=rubicon for instream

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#5961]
## Type of issue
bug

## Description
33across seems to be returning "rubicon" as hb_bidder=rubicon for instream video

## Steps to reproduce
bidder: '33across',
				params: {
					siteId: 'YOUR33ACROSSID',
					productId: 'instream'
				}
			} /
## Platform details
prebid client 4.15.0

**Comment by bretg** [comment]
Do you have an example page where this happens @spormeon - the code in their adapter hardcodes the bidder_code to "33across". This is either a page issue or a deeper bug.

**Comment by spormeon** [comment]
how do i contact you , so as not to put in open foorum?

**Comment by bretg** [comment]
b g ors line & prebid.org

**Comment by bretg** [comment]
Talked with @spormeon  via email.  Thus far not able to reproduce the issue, apparently the 33across bidder has been turned off. However, I've reviewed both client-side and server-side bid adapters and don't see any obvious problems. Rubicon isn't even in the list of bidders for the page. Will take another look when 33across is re-enabled.

The issues experienced here are related to https://github.com/prebid/prebid-server/issues/1562 -- he's trying to set up video-over-AMP but using Prebid.js. I don't think this will work -- as far as I know, Prebid.js will not operate in the AMP environment, specifically the interaction between GAM and Prebid.js.

I'm interested in the AMP-video-header-bidding scenario, but suspect it will need https://github.com/ampproject/amphtml/issues/30193 -- perhaps we can use <amp-script> tags to get some bids and invoke a video player? Would be great if someone could post a straw design using the upcoming capabilities. Would prefer not to load the AMP page down with prebid.js -- better to use the /amp RTC endpoint if possible, perhaps with an additional parameter to alter the return format if needed. (?)

**Comment by spormeon** [comment]
i can confirm it does work with GAM and prebid.js and prebid.js s2s,  its all working as should , with stats pinging back etc etc

Thats the point Bret on 33across, rubicon is not mentioned anywhere but they are sending back rubicon as the KV on the bid as hb_bidder=rubicon, maybe its a "backend", their end problem, I not sure

**Comment by bretg** [comment]
Adding @curlyblueeagle to comment

**Comment by curlyblueeagle** [comment]
@spormeon not sure why our backend would be a problem, hb_bidder is relevant only the context of Prebid. Do you have a test page? Hard to debug without one.

**Comment by spormeon** [comment]
@curlyblueeagle i think i found, it, some weird dfp bug by looks, will confirm if fixes it

**Comment by curlyblueeagle** [comment]
@spormeon wonderful! If problems still persist, please contact us at headerbidding@33across.com if you do not wish to have a discussion on public forum.

**Comment by ChrisHuie** [comment]
Sounds like this issue self resolved. Closing out but if GAM bug pops up again we can reference
