### ISSUE TITLE
PubCommonId matching type?

### ISSUE THREAD

**Issue by KianGroenen** [prebid/Prebid.js#5962]
## Type of issue
question

## Description
How is the matching of the PubCommonId done?
Via Probabilistic/Deterministic matching? Or is it a simple UUID?
This in regards to Privacy/GDPR.

**Comment by jdwieland8282** [comment]
Hi @KianGroenen its just a UUID I believe. 

@pycnvr fyi

**Comment by pycnvr** [comment]
Yes, it's just a type 4 uuid.  Thanks @jdwieland8282.

**Comment by KianGroenen** [comment]
Thanks for the confirmation
