### ISSUE TITLE
Prebid 5.0

### ISSUE THREAD

**Issue by gglas** [prebid/Prebid.js#5966]
## Type of issue
Prebid 5.0 changes summary.

## Description

Prebid 5.0 is the next major version release of Prebid.js currently scheduled for Q2 of 2021.  Please use this issue to track things earmarked for inclusion in Prebid 5.0 and to discuss what should or shouldn't be included.

Currently, we have the following projects and considerations:

Official Refactor of Default Key-values

 - Now that we have the ability to determine "standard" versus "optional" keys, we'd like to have a discussion regarding reducing the number of standard keys and pushing more to optional in order to reduce the key-value footprint in the default version of Prebid.  Having too many key values flowing into GAM can cause performance issues, so we expect this to reduce inadvertent overloading of GAM key values while streamlining prebid.

Taxonomy Enforcement - adapters that do not conform to standards regarding the communication of the following auction meta data will be removed from the download page, and all adapter modifications and commits will be expected to respect these standards.

- Floors need to be read from the floors module using designated fields
- Video parameters need to be read from the ad unit
- Bidders need to pass adomain and mediaType in the meta object

Adoption of the RTD framework

- Bidders in Prebid 5.0 will be expected to bid, which means that any providers using the bid infrastructure today that could be passed via the RTD framework will be expected to migrate to this framework.

SharedID and pubcommonID

- We are expecting a change that will couple the two userID modules together, which may involve some legal work on behalf of publishers

**Comment by patmmccann** [comment]
In the pub committee meeting today, it was proposed that https://github.com/prebid/Prebid.js/pull/5863 should need double opt in by publishers, where they would both have to install the module and configure it for it to work.

**Comment by Fawke** [comment]
@gglas Just wanted to know if we're gonna include [this](https://github.com/prebid/Prebid.js/issues/4810) in 5.0 ?

**Comment by gglas** [comment]
@Fawke yes I believe so, but we'll be scheduling a follow up meeting in the next few weeks to list out 5.0 more explicitly.

**Comment by gglas** [comment]
need to include https://github.com/prebid/Prebid.js/issues/5986

**Comment by patmmccann** [comment]
#6464 obscure change that should affect no one but it seems technically breaking

**Comment by Denis-Admixer** [comment]
Regarding the **Taxonomy Enforcement**: do we already have a strict list of the required fields? Except the meta.advertiserDomain?

**Comment by patmmccann** [comment]
> Regarding the **Taxonomy Enforcement**: do we already have a strict list of the required fields? Except the meta.advertiserDomain?

That's the only one of the meta fields with an enforcement planned for 5.0. The other three enforcements are: bidders supporting floors should support the floor module as an input, bidders must bid, openrtb video params should be capable of reading from the ad unit.

**Comment by patmmccann** [comment]
Plural, I'll do the docs change today

**Comment by gglas** [comment]
5.0 released
