### ISSUE TITLE
Post-Bid Tag Floor Pricing

### ISSUE THREAD

**Issue by digitalthrottle** [prebid/Prebid.js#597]
We're using just post-bid tag. Rather than setting up the floor price within each of the network's we're calling, is there any method to pass our floor CPM through the tag or somehow interface with our DFP line item?

Thank you,

**Comment by mkendall07** [comment]
@digitalthrottle 
Have you tried changing the configuration to send a custom price bucket? This could be modified to create a floor bid. See http://prebid.github.io/dev-docs/examples/custom-price-bucket.html

**Comment by digitalthrottle** [comment]
Thanks for the direction. We worked on something where we push a bidRespone to "0.00" if the CPM is less than the desired floor. I'm assuming the JS won't allow a "0.00" bid to win?

Does this seem in the correct direction if our hard floor min CPM was $1.35?

` key: "custom_bid_price_key",
          val: function(bidResponse) {
            var cpm = bidResponse.cpm;
            if (cpm < 1.35) {
              return 0.00;`

Thanks again,

**Comment by mkendall07** [comment]
Well the adjustment actually happens post auction, but it will force the value to `0.00` in the key/value pair in DFP, so as long as you don't have line items targeting a 0 value (you shouldn't) it should work fine.

**Comment by digitalthrottle** [comment]
Ah - so this is actually using key/value pair. I was thinking it impacted the bid decisioning.

**Comment by mkendall07** [comment]
You can actually adjust the price pre auction using `bidCpmAdjustment` - which might be more appropriate for your situation. 
Search `bidCpmAdjustment` in this doc:
http://prebid.github.io/dev-docs/publisher-api-reference.html

```
bidCpmAdjustment: function (bidCpm) {
                        if(bidCpm < floor){
                          return 0;
                        }
                        return bidCpm; 
                    },
```

**Comment by digitalthrottle** [comment]
Awesome - that is right on the money. We'll give it a test and post back.

Best-

**Comment by ericsson66** [comment]
Oooh that's something I will look into!
