### ISSUE TITLE
Winning bid has CPM 0

### ISSUE THREAD

**Issue by Laffrenz** [prebid/Prebid.js#5971]
On multiple winning bids for this SSP, the CPM appears as "0". There is a bug somewhere at the SSP, which is Adform - but in the bid chain I am not able to locate the root cause here. Is anyone able to help with any input here?

https://www.boligsiden.dk/

{
    "ad": "<script type='text/javascript' src='https://track.adform.net/adfscript/?bn=40347408;rtbwp=dKNDgX7kJXAW8xzVXjX0yMN4iOtIBxgX0;rtbdata=wbHK8mCfxHrWTGSivTKERd69ACZeECLdKrIQCw9rJKhgsH2n4AN4bJDyZqjPQ1L_nItlFOEsknWZipbwoqL4qxqKPnMmlD0yW7-5ew0155IwAS1HwgKgB4xkDR_3fQImhykdfbofuaMEHxrM2mZFEvGQMVS5hY4ymWR_JyHiFkiSQE1yAPJVvmluknFyBurqI2Kqeqv1Rwi2HNiG40Y0vzQdwZsWIafzrx6bJcbvNQ-Ll2aNQYWHdEmtbkRCw2LiTJQAKJP2SejxzVdYwj1utT8BboaIMGP27-XuaYUYz_dhygNJk9ILMGdyk5qAmJJaHJ4ijtxTCwnKJJKIlwSnwHsra61gS7zKdmmZg-mkJnSs7MqBktED1Oz03E6oli1vmw0X1ylXWm5zXNgTVkWhCKERPiGXdB7GPd2Q-KvoAZ7c-EGlS36CsXHim5H9RHEqbwB0aE565Z2y-ujZ5-gNK4Of5pn31L8GQ04cc7wkLyfrwhltmMfAP0DZaY0lb8lOrA0qKnoLBRriNV_aY2BaHviUeLo6XjluJIWN5UP-p5HIcPctl8JsHbC5e5exPvc6oYZb3udReC4KjLyOWz1F_ErcBbBIFO4FnRw844qAp1AFS-CL_zgBXC5M7yGYniLLvozVmRbXiN8yokkDGaN5l_CcXbb4A1cB4ZOjfDQJ5Y8_A4gxvVyL9CEB3r6J_MHun7hLRNoRfgGsDdxg5Y7vQDNd6o_S3qHD0;csid=114810;adxcmd=QTwuOIuaMWxxWXp_eBE_5w2;adxvars=s0mTgp4x45Z42u1ywTJ-2ouXZo1BhYd0BYbGVzibpeAuNTOAQ_HDSIRzIdDUJiB6VBc_tZfR_9JenXaZ5hXmdrlxGoDP90cvduotVQsUZAidpl4Mt8gKVm0Sp8TAWzgHnItlFOEsknWZipbwoqL4qxqKPnMmlD0y0RRCe9YhkmdlErroK8wkiuzOpWpg_LY6gyoU_Y669E_C2GuR0ddtmgpVj9dbaSBc0;icid=4470405761678472325;icidt=637408654514335411;'></script><script src=\"https://s1.adform.net/banners/scripts/adx.js\"></script><i style=\"display: none\" id=\"f2e54d90ad074c2180efa7474209c46f\"></i><script>(_fscope = window._fscope || []).push(function (fscope) {fscope.register({\"AdSlotId\":\"f2e54d90ad074c2180efa7474209c46f\",\"CookieId\":\"4470405761678472325\",\"Width\":300,\"Height\":600,\"TestId\":null,\"SerializedAdxVars\":\"s0mTgp4x45Z42u1ywTJ-2ouXZo1BhYd0BYbGVzibpeAuNTOAQ_HDSIRzIdDUJiB6VBc_tZfR_9JenXaZ5hXmdrlxGoDP90cvduotVQsUZAidpl4Mt8gKVm0Sp8TAWzgHnItlFOEsknWZipbwoqL4qxqKPnMmlD0y0RRCe9YhkmdlErroK8wkiuzOpWpg_LY6gyoU_Y669E_C2GuR0ddtmgpVj9dbaSBc0\",\"PublisherVisibilityTime\":1,\"PublisherVisibilityArea\":50,\"UnloadHandlerUrl\":\"https://adx.adform.net/adx/unload/?\",\"Gdpr\":true,\"GdprConsent\":\"CO4in2FO4in2FAcABBENBACsAP_AAH_AAAYgGYtf_X9fb2vj-_5999t0eY1f9_63v2wzjgeNs-8NyZ_X_L4XomMyvB34pq4KmR4Eu3LBAQdlHGHcTQmQwIkVqTLsak2Mq7NKJ7JEilMbM2dYGG1vn8XTuZCY70_sf__z_3-_-v__67YGXgEmGpfAQJCWMBJNGlUKIEIVxIVACACihGFoksICRwU7K4CPUACABAYgIwIgQYgoxZBAAAAAElEQAgAwIBEARAIAAQAqQEIACJAEFgBIGAQACgGhYARQBCBIQZHBUcogQESLRQTyRgAA.YAAAAAAAAAAA\",\"IsMobile\":false});});</script>",
    "adId": "28e2a6a9ae7f456",
    "adUnitCode": "div-gpt-ad-rectangle_1",
    "adserverTargeting": {},
    "auctionId": "7963da2f-4a30-4ce6-a73b-56833e9a4da3",
    "bidder": "omgz",
    "bidderCode": "omgz",
    "cpm": 0,
    "creativeId": "12077a736a39faa",
    "currency": "USD",
    "dealId": null,
    "gdpr": true,
    "gdpr_consent": "CO4in2FO4in2FAcABBENBACsAP_AAH_AAAYgGYtf_X9fb2vj-_5999t0eY1f9_63v2wzjgeNs-8NyZ_X_L4XomMyvB34pq4KmR4Eu3LBAQdlHGHcTQmQwIkVqTLsak2Mq7NKJ7JEilMbM2dYGG1vn8XTuZCY70_sf__z_3-_-v__67YGXgEmGpfAQJCWMBJNGlUKIEIVxIVACACihGFoksICRwU7K4CPUACABAYgIwIgQYgoxZBAAAAAElEQAgAwIBEARAIAAQAqQEIACJAEFgBIGAQACgGhYARQBCBIQZHBUcogQESLRQTyRgAA.YAAAAAAAAAAA",
    "height": 600,
    "mediaType": "banner",
    "netRevenue": true,
    "originalCpm": 0,
    "originalCurrency": "USD",
    "pbAg": "0.00",
    "pbCg": "0.00",
    "pbDg": "0.00",
    "pbHg": "0.00",
    "pbLg": "0.00",
    "pbMg": "0.00",
    "requestId": "12077a736a39faa",
    "requestTimestamp": 1605268651317,
    "responseTimestamp": 1605268651545,
    "source": "client",
    "statusMessage": "Bid available",
    "timeToRespond": 228,
    "transactionId": "c2e7bd36-f93d-442b-87be-d99098c3641f",
    "ttl": 360,
    "width": 300
}

**Comment by ChrisHuie** [comment]
@Laffrenz is this still an issue you are experiencing? I can dig into it

**Comment by Laffrenz** [comment]
Hi,

No, thanks – the issue was caused by Adform.

Alle the best,
Bjørn Laffrenz Bukholt

Bjørn Laffrenz Bukholt
Director, Advertising Technology

M: +45 20494015

**Comment by ChrisHuie** [comment]
Issued resolved on its own
