### ISSUE TITLE
Adform / Deals

### ISSUE THREAD

**Issue by popmedia** [prebid/Prebid.js#598]
Is there any news on when Adform will activate deals for their adaptor, or has anyone managed to get it working? Would love to have it.

**Comment by mkendall07** [comment]
@prebid/adform  any comment?

**Comment by LaimonasN** [comment]
Hi @popmedia,

It's not prioritized yet - will update you once ETA will is clear.

Best wishes,
PO of HB @Adform

**Comment by ptomasroos** [comment]
@mkendall07 was this resolved or just outdated?

**Comment by mkendall07** [comment]
just outdated. I prefer to only keep tickets around that are actionable by the core team. This is a feature request to a specific SSP so it really doesn't belong open here.

**Comment by ptomasroos** [comment]
Saw in the adapter code deal's are supported now, will just leave a comment here for future searches!
