### ISSUE TITLE
defaultGdprScope = undefined - what will happen ?  

### ISSUE THREAD

**Issue by nimrodraz9** [prebid/Prebid.js#5984]
Hello,

Sometime in the project we see that we have for defaultGdprScope  the value of undefined 

I know in general it should have a bool value of true or false, and I want to know what will happen if it is undefined 

Any idea?

Thanks!

**Comment by bretg** [comment]
This the line of code in question -- https://github.com/prebid/Prebid.js/blob/9d37b25e9b36852761edc5f650803396112525cb/modules/consentManagement.js#L479

```
  gdprScope = config.defaultGdprScope === true;
```
If defaultGdprScope is undefined, the overall expression becomes false.

**Comment by bretg** [comment]
I updated https://docs.prebid.org/dev-docs/modules/consentManagement.html to note that the default defaultGdprScope is false.
