### ISSUE TITLE
pbjs_debug and Prebid Server

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#5986]
## Type of issue
Change

## Description
Right now adding `pbjs_debug=true` to the query string will cause the pbsBidAdapter to add test:1 to the OpenRTB. 

The OpenRTB `test` parameter can cause different behavior in bidders. So it may be reasonable to change this behavior to add ext.prebid.debug:1 instead.

If we do decide to change:
- should it be 5.0? Is this a "breaking change"? Kind of -- it's a different behavior in a debug scenario.
- should we also add a pbjs_test=true query string?

## Reference

https://github.com/prebid/prebid-server/issues/1562

**Comment by patmmccann** [comment]
The second question is still open

**Comment by patmmccann** [comment]
@bretg could this be solved with doc now? Could a publisher do a setConfig call on the ortb2 object to set test=1?

**Comment by bretg** [comment]
> Could a publisher do a setConfig call on the ortb2 object to set test=1?

Definitely.

Given that no one's asked for pbjs_test=true, this seems like a good way to close out the issue.

**Comment by bretg** [comment]
Done. A request for pbjs_test query string flag should come in as a new issue. Thanks.
