### ISSUE TITLE
document.write() issue in potentially malformed ads

### ISSUE THREAD

**Issue by joyofdata** [prebid/Prebid.js#599]
Has somebody also stumbled upon winning bid ad tags leading to display of something similar to:

```
'
document.write(''); '
```

The precise output varies but it is always a document.write call which is not evaluated but instead displayed as text.

We could narrow down the issue to a specific network and ad server and could improvise a solution by filtering those out - but I would like to learn if this problem is known and maybe caused by an incompatibility or a bug.

Actually though I am quite sure it's an issue caused by the ad tag due to containing substings like `<script>` and/or `</script>` in the string provided to `document.write()`.

**Comment by kasparsd** [comment]
@joyofdata Can you please post the JS in the ad creative? Is it the one [suggested here](http://prebid.github.io/adops/step-by-step.html#step-2-add-a-creative)? I think you're right about the broken ad tag.

**Comment by mkendall07** [comment]
@joyofdata 
I haven't seen this issue reported but that doesn't mean it's not happening. I'm not crazy about trying to parse responses and sanitizing the output but that would be one solution. Are you able to post an example that is reproducible?

**Comment by joyofdata** [comment]
@kasparsd: I have no idea how your link relates to my proposed issue

@mkendall07: Sure, here you go:

- https://jsfiddle.net/qm3qb22L/
- https://jsfiddle.net/0voo6ptz/

**Comment by kasparsd** [comment]
@joyofdata Indeed, the ad contains invalid HTML which causes the output you're seeing:

![invalid-html](https://cloud.githubusercontent.com/assets/169055/18307648/f72206e8-74f9-11e6-9b04-c67d6581d608.png)

I'm not sure there is anything Prebid.js can do about invalid ad HTML.

**Comment by mkendall07** [comment]
@joyofdata 
I agree with @kasparsd, not sure what Prebid.js can do about this. Do you have any suggestions?

**Comment by joyofdata** [comment]
true, I just wanted to confirm it's not a compatibility issue - it came up many times over a longer period - but I guess, I answered the question myself :D thanks anyway
