### ISSUE TITLE
Should UserId module use getStorageManager instead of getCoreStorageManager?

### ISSUE THREAD

**Issue by smenzer** [prebid/Prebid.js#5990]
# Background
Currently, the User ID module only uses the [core storage manager](https://github.com/prebid/Prebid.js/blob/master/modules/userId/index.js#L137). This is used when user id modules use the [standard cookie/html5 storage configuration](https://github.com/prebid/Prebid.js/blob/master/modules/userId/index.js#L185,L195) to cache their ID in the user's browser.

Core storage does not do any GDPR checks as it is [considered core to prebid software](https://github.com/prebid/Prebid.js/blob/master/src/storageManager.js#L292). While this is certainly true in some cases, I would question whether this is true for storing user id module IDs, especially since if an ID module does any storage directly in their module, it must pass GDPR checks.

# Proposal / Question
I would propose that the User ID module is updated to use the normal storage manager for storing/reading cached IDs. I think we should still use core storage for things like [caching consent to monitor for changes](https://github.com/prebid/Prebid.js/blob/master/modules/userId/index.js#L263), though.

**Comment by jdwieland8282** [comment]
I agree, it seems like using core storage offers a loophole for storing a user id even if the loophole is used unintentionally. 

@SKOCHERI Is Sharedid using Core storage manager to store a user id?

**Comment by SKOCHERI** [comment]
@jdwieland8282 SharedId is not caching id hence not using core storage manager within sharedIdSystem

**Comment by smenzer** [comment]
@SKOCHERI I don't think that's entirely true... within the sharedIdSystem.js file you're right, you are not directly accessing any storage manager methods. However, you do utilize the User ID module itself to cache IDs (based on the publisher's configuration, which you highlight in your docs: https://github.com/prebid/Prebid.js/blob/master/modules/sharedIdSystem.md), so indirectly you are using core storage manager.

**Comment by SKOCHERI** [comment]
@smenzer True. I meant to say we are not directly using storage management within SharedId submodule but rather rely on user id module (index.js) to store the id based on the configuration.

**Comment by smenzer** [comment]
@SKOCHERI yep i see your point, I interpreted @jdwieland8282's question as if sharedid was using core storage _at all_ even if indirectly...although now he has all the details he needs I suppose :)

i suppose this is a good topic for the PBJS PMC next week, so @gglas do you want to take note? that gives time for anyone else to weigh in here before we make a decision

**Comment by gglas** [comment]
Sounds good to me! i will make sure it's on our agenda

**Comment by smenzer** [comment]
@gglas iirc from the meeting where this was discussed, i think we agreed it would make sense to migrate the userId module to `getStorageManager` ... so we just need someone to pick this up.

**Comment by gglas** [comment]
hey @smenzer we discussed in issue review today, would you mind syncing up with @ChrisHuie to discuss implementing the change and walk through the infrastructure?  Thanks!

**Comment by smenzer** [comment]
@gglas - @ChrisHuie and I have some time booked next week to go through this.

**Comment by gglas** [comment]
@ChrisHuie doing a final check on this, hopefully not an ongoing issue
