### ISSUE TITLE
Why is pubcommon optout blocking entire User ID Module?

### ISSUE THREAD

**Issue by smenzer** [prebid/Prebid.js#5991]
## Question

In the User ID module, during the initialization process, there are checks to see if a prebid user id optout cookie/localstorage key is set ([here](https://github.com/prebid/Prebid.js/blob/master/modules/userId/index.js#L704) and [here](https://github.com/prebid/Prebid.js/blob/master/modules/userId/index.js#L709)).

This is completely logical...however, the checks on both lines also check for a pub common opt out cookie/local storage key, citing compatibility with pub common. But I don't understand why all of the user id modules would be blocked because pubcommon is turned off.  Can someone provide any context here? If not, I would propose we remove the checks for pub common in the user Id module and instead make sure they're covered in the pub common submodule.

**Comment by jdwieland8282** [comment]
I'm just guessing here but could it be because pubcommon was originally part of pb core, and included automatically when the user id module was added?

**Comment by smenzer** [comment]
that was my assumption, too. @pycnvr any idea from your side?

**Comment by pycnvr** [comment]
Yes, it was a carry-over from way back.  It should be moved.

**Comment by smenzer** [comment]
ok, thanks @pycnvr and @jdwieland8282. I'm putting up a PR to remove it and will link it here in a few minutes.

**Comment by bretg** [comment]
Thanks for the issue and PR @smenzer - closing this issue since the PR will track the resolution.
