### ISSUE TITLE
Bidders order on PB auction. Does it matter, and why? (No Async?)

### ISSUE THREAD

**Issue by nimrodraz9** [prebid/Prebid.js#5997]
Hello,

Is it matter the order of the bidder we set when doing the PB auction request?

For example, our timeout is 3000 ms and we have 15 bidders, but I assume that all PB inside make Async call for all bidders, so its not really matter who is the first and who is the last.

Is it true?

Or maybe PB is not doing the calls Async (or do it by group?) and it is matter who is the first and who is the last.

I would like to ask if someone know how it works inside and what is the optimal solution.  (PB version = 3.X) 

Thanks !

**Comment by wqi1972** [comment]
PBJS makes Async calls for all bidders, the bidder order doesn't matter.

btw, want to confirm: all your bidders are client side, no prebidServer configured using s2sConfig, right?

**Comment by nimrodraz9** [comment]
Yes (there is no prebidServer configured using s2sConfig)

But, if what you said it true (and it is also what I was thinking) than why do I see on this document on page 10:
https://www.appnexus.com/sites/default/files/whitepapers/HB-Setup-5Tips-final-121517.pdf
The they recommended to "SHUFFLE THE ORDER IN WHICH BIDDERS ARE CALLED" 
Why is it? they are wrong?

And also, why do PG give the option to have fixed position and random. I mean, if it doesnet matter, why we have this option? 

So. I think I might miss something here?

Thanks !

**Comment by bretg** [comment]
Nothing is truly async in javascript -- the browser will call the endpoints one-by-one. On a slow connection, that could give an advantage to the first bidder in a long list. That few milliseconds difference is why PBJS supports randomizing the order. Milliseconds matter.
