### ISSUE TITLE
Triplelift setBidderConfig spec 

### ISSUE THREAD

**Issue by r-schweitzer** [prebid/Prebid.js#6000]
## Type of issue
Possible spec issue

## Description
It appears that TripleLift may not have followed the spec for first-party data. It looks like they are expecting all first-party data to be passed on fpd.context but arbitrary values for FPD data should be passed in fpd.context.data. 

## Other information
https://docs.prebid.org/features/firstPartyData.html#in-page-examples

Bret makes mention of this in this issue
https://github.com/prebid/Prebid.js/issues/5795

**Comment by bretg** [comment]
Adding recent contributors to the Triplelift adapter: @kzhouTL , @blingster7, @davidwoodsandersen, @sdao-tl , @colbertk

**Comment by blingster7** [comment]
Hi @bretg and @r-schweitzer, thanks for bringing this up to our attention. We'll get some resources on this and submit a fix

**Comment by bretg** [comment]
Thanks @blingster7 - now that there's a PR, will close the issue.
