### ISSUE TITLE
Request for example page with back/forward cache

### ISSUE THREAD

**Issue by KenjiBaheux** [prebid/Prebid.js#6007]
## Type of issue
Question about prebid + recommendation if applicable

## Description
Hi, this is Kenji Baheux, product manager for Chrome at Google.

We recently [announced](https://blog.chromium.org/2020/11/tab-throttling-and-more-performance.html#Blog1:~:text=Back%2Fforward%20cache,5%20navigations%20are%20a%20back%2Fforward%20navigation.) the launch of a back/forward cache for Chrome (starting with Android).

We've heard reports of partners (or ad solutions used by partners) opting-out of back/forward caches in order to ensure that a new set of ads would be shown on back navigations. This is a big hammer which makes the user experience significantly worse. 

A better option would be to use the pageshow event with the persisted property (i.e. a back/forward navigation from cache) in the following manner:

```
addEventListener('pageshow', (event) => {
  if (event.persisted) {
    // call to a function that would rerun the auction and obtain a new set of ads, etc.
    ...
  }
});
```
_Note: this should work on all browsers._

Would this be relevant to prebid?
Thanks in advance!

**Comment by wqi1972** [comment]
I think this is relevant to Publishers, not Prebid.
The function to re-run auctions suppose be controlled by Publishers, and inside that function, it triggers Prebid auction.

**Comment by KenjiBaheux** [comment]
Thanks @wqi1972 for the reply!

Glad to hear that prebid would not, on its own, opt-out pages from BFCache.
In terms of examples, I think it would be best to caveat the practice by saying that:
 1. It's best to make sure that one isn't inadvertently opting-out of BFCache.
 2. It's preferable to keep the back/forward navigations unchanged (as this is what users would most likely expect to see).
 3. If one really feels strongly about refreshing the ads on back/forwards navigations, then using the snippet is recommended (as opposed to opting-out completely of BFCache).

Happy to help with reviewing an example / article.

**Comment by bretg** [comment]
Looking for a volunteer to make an example page.

**Comment by wqi1972** [comment]
I volunteer for it. :)

@KenjiBaheux, would you please guild me through how to get back/forward cache for Chrome feature work? 
I did some quick test, and this feature doesn't seem work on my Chrome. (Version 87.0.4280.67 (Official Build) (x86_64)) (I tried it on desktop and use it simulates Android phone, neither of them seems use this new feature)

**Comment by KenjiBaheux** [comment]
Sure.

The feature is gradually launching on Chrome for Android.
That said, there is a flag to enable it by default (should also work on desktop platforms).
 
1. Open a new tab
2. Copy paste `chrome://flags/#back-forward-cache` in the address bar and hit enter
3. Select `Enabled` (or `Enabled force caching all pages (experimental)`)
4. Click the `Relaunch`button at the bottom right.

Let me know if you are still stuck.

**Comment by wqi1972** [comment]
@KenjiBaheux I followed your instructions on Chrome on MacBook, then I opened a bunch of websites, and back/forward on these websites. For all of them, the cache doesn't work. These pages still load all content (js, img, css, media, etc) as if the page is first time load. And I confirmed all the ads get reloaded when I back/forward between pages.

Would you please confirm this new feature works on MacBook?

**Comment by KenjiBaheux** [comment]
Sorry for the issues. I'm checking with the team in case there are extra conditions for desktop platforms.

**Comment by KenjiBaheux** [comment]
The flag might be gone in the latest Chrome Canary.
It's still there on Chrome stable.
Probably best to use the `Enabled force caching all pages (experimental)` option.

Here is a scenario that I confirmed to be working:

1. Go to a wikipedia page (e.g. [Switzerland](https://en.m.wikipedia.org/wiki/Switzerland))
2. Open DevTools (make sure to uncheck "disable cache" for good measure).
3. Click on one of the links in the article (e.g. [Western](https://en.m.wikipedia.org/wiki/Western_Europe)
4. Hit back.
5. If the BFCache triggers, then you should see a single **new entry** in the Network tab for Switzerland. If the BFCache didn't work, then there should be multiple **new entries** for the main and sub-resources of that page.

Note: there might be practical limits in place despite what the option seems to imply (e.g. only 1 back navigation).

**Comment by KenjiBaheux** [comment]
Here is a page to help you test BFCache: https://back-forward-cache-tester.glitch.me/?persistent_logs=1&timer=1
There are links at the bottom which you can use to test different scenarios. The events at the bottom should tell you when it worked vs. not.

**Comment by wqi1972** [comment]
@KenjiBaheux I did some test on Switzerland, and found:
this feature only works when I follow steps:
1. open https://en.m.wikipedia.org/wiki/Switzerland
2. click on one of the links
3. hit back -- cache doesn't work
4. hit forward -- now the feature start working
5. hit back -- still works
6. hit forward -- still works

Another scenario the feature works:
1. open https://en.m.wikipedia.org/wiki/Switzerland
2. hit link#2
3. hit link#3
4. hit link#4
5. hit back to link#3 -- cache doesn't work
6. hit back to link#2 -- cache doesn't work
7. hit forward to link#3 -- cache works
8. hit back to link#2 -- cache work

This is different from your description, the feature only works after user hit forward & back or back & forward together, single back or single forward doesn't trigger the feature. Please confirm my findings are correct.

Also, this feature doesn't work on other websites, does it mean to apply this feature, the websites need to make some change on front end code?

**Comment by gglas** [comment]
@KenjiBaheux Are there any further updates on working on building the example, or should we close out the issue?

**Comment by KenjiBaheux** [comment]
We are still ramping up for the same-origin case. I think we can close for now. We might come back if we hear some partner requests for this and when we have the feature a bit more stable. Thanks!
