### ISSUE TITLE
Question: can we perform http request in `buildRequests`

### ISSUE THREAD

**Issue by sebbes-at-missena** [prebid/Prebid.js#6009]
## Type of issue
Question

## Description
We, at Missena, are trying to build a Prebid adapter. We have multiple providers and some of them need multiple requests to actually have an ad proposal (e.g. with criteo, we have to first perform a call to `https://gum.criteo.sync/....`  to first get the user).

Is it possible to perform those kind of requests in the `buildRequests` function to make this workflow working?

**Comment by bretg** [comment]
> Is it possible to perform those kind of requests in the buildRequests function to make this workflow working?

Definitely not. The [Prebid Module Rules](https://docs.prebid.org/dev-docs/module-rules.html) preclude bid adapters from doing anything other than bidding. We will look very closely at any bid adapter making multiple HTTP calls. 

> e.g. with criteo, we have to first perform a call to https://gum.criteo.sync/.... to first get the user

In this example, the publisher must retain control over what's happening on their page -- they will have to include the criteo user ID module to make this happen.
