### ISSUE TITLE
US Privacy string in buildVideoUrl

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/Prebid.js#6012]
## Type of issue

This is a feature request:

Google expects that the ccpa privacy string is added to their ads url ( see [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/ccpa) ).

Ideally, prebid would use the privacy string provided by the usp module and insert it automatically.

**Comment by spormeon** [comment]
adding to this one, GDPR needs to be added as well?

**Comment by ReinoutStevens** [comment]
gdpr consent is read by the IMA sdk, google just doesnt do it for the us_privacy

**Comment by spormeon** [comment]
its not working for me as still getting google 2.1a errors and only on Video, same cmp used for display, which works fine

**Comment by bretg** [comment]
@spormeon - what's not working for you - US Privacy or GDPR?

**Comment by spormeon** [comment]
i think its juts GDPR now, there was a fix sent out in last release for the CCPA element?

**Comment by ReinoutStevens** [comment]
@spormeon for GDPR the IMA SDK reads out consent from the CMP itself, and there is no need to provide the string yourself

**Comment by spormeon** [comment]
but we are talking about sending on prebid video request?

**Comment by bretg** [comment]
Closing this issue, went out with 4.19
