### ISSUE TITLE
Add entry of fabrickId in Eids

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#6021]
## Type of issue
 fabrickId is not registered in Eids implementation. Please add fabrickId entry in Eids.

## Description
Most of the userId sub-modules are registered in eids, https://github.com/prebid/Prebid.js/blob/master/modules/userId/eids.js it is an easier way for bidders to support userId sub-modules. fabrickId is not registered in Eids implementation. Please add fabrickId entry in Eids.

**Comment by pm-harshad-mane** [comment]
Hello @andersonbd1 , 
I assume you are the right person to help here since you maintain the fabrickId sub-module.
Can you please look into this issue? 
PubMatic supports all of the userId sub-modules by consuming Eids object, we want to support fabrickId as well.

**Comment by andersonbd1** [comment]
@pm-harshad-mane - yes, you've got the right person.  I'll take a look.  Thanks for opening this issue and pinging me.

**Comment by pm-harshad-mane** [comment]
Hello @harpere ,
I see Rubicon is mentioned to be supporting fabrickId here https://docs.prebid.org/dev-docs/modules/userId.html#adapters-supporting-the-user-id-sub-modules but I couldn't find the respective code at https://github.com/prebid/Prebid.js/blob/master/modules/rubiconBidAdapter.js 
Can you help?

**Comment by pm-harshad-mane** [comment]
@andersonbd1 great,  we will need to add entry for fabrickId in USER_IDS_CONFIG 
 object at https://github.com/prebid/Prebid.js/blob/master/modules/userId/eids.js#L4 
Here is an example of eids array-object https://github.com/prebid/Prebid.js/blob/master/modules/userId/eids.md
Let me know if you need anything.

**Comment by andersonbd1** [comment]
@pm-harshad-mane https://github.com/neustar/Prebid.js/commit/a427455b736f0b0ff5c8cdfbff28fe8fd9e06ede
I didn't submit a PR yet.  I'm afraid I'm not entirely sure I've got it right.  The source I used is the TLD of our endpoint url, which is not the same as our marketing domain name.  Is it just a semantic thing or does it need to be correspond to the endpoint url?  I'm also not sure about the property name.  I put 'fabrickId', which is the name of our module.  Would you be able to tell me if this is correct?  Or point me to a way I can verify?  Thanks, much.

**Comment by jdwieland8282** [comment]
You can use your TLD or a marketing domain, but it should be in the format of something.com|org|net etc..I recommend maintainers make it something a buyer or DSP will recognize, when this id arrives in a bid request to them, they should have some way to know who set the id.

**Comment by pm-harshad-mane** [comment]
The name 'fabrickId' is correct as the same is mentioned here https://github.com/prebid/Prebid.js/blob/master/modules/fabrickIdSystem.js#L19

As @jdwieland8282 mentioned the TLD domain used here will help DSP and SSPs recognize the FabrickId in array of EIDs

The changes look good to me.

**Comment by andersonbd1** [comment]
Thanks, @pm-harshad-mane and @jdwieland8282 .  I update the src to be our main TLD - home.neustar and submitted a PR - https://github.com/prebid/Prebid.js/pull/6022

**Comment by bretg** [comment]
Closing the issue since the PR has been submitted. Thanks all.
