### ISSUE TITLE
Price Floors Module: Add timestamp of model

### ISSUE THREAD

**Issue by bszekely1** [prebid/Prebid.js#6034]
## Type of issue

Intent to implement

## Description

When a floor provider supplies floor data to the browser, the fetched data can be cached in various location, for example in the browser, the CDN or even further upstream in the origin server. With a goal of ensuring accurate pricing rules are implemented in the browser, floor providers can seek value in knowing when the floors file was produced and when it was used. By default floor providers know when floors are used, however they lack the understanding of the delta between when it's generated and when they are used. This ticket is to add an additional field to track the model generation epoch timestamp.

## Requirements

1. Field name should be `modelTimestamp`
2. Field should be an integer representing an epoch timestamp
3. Field should be located at the top level of the data object found in both schemas since the model timestamp should apply to all models in schema 2 and the one model in schema 1:
    -  In `floors.data.modelTimestamp`
4. Field should be recorded in the bid request of each bid object to allow analytics adapters to record the timestamp:
    - In `bidRequest.floorData.modelTimestamp`

**Comment by ChrisHuie** [comment]
#6061 merge closes this issue out.
