### ISSUE TITLE
Transfer data from rtd provider to s2s adapter

### ISSUE THREAD

**Issue by Niksok** [prebid/Prebid.js#6049]
## Type of issue
Question

## Description

Is it possible to transfer some data from any rtd provider via prebidServerBidAdapter to s2s adapter?
If on current time it is not possible may i make some pull request with changes in prebidServerBidAdapter to support this case?

**Comment by bretg** [comment]
It is recommended that RTD adapters pass data to bid adapters using [first party data](/features/firstPartyData.html) conventions. See https://docs.prebid.org/dev-docs/add-rtd-submodule.html#getbidrequestdata

If they do, the data will be passed to Prebid Server and server-side adapters automatically. I don't think we need to support the "bidrequest.rtd.MODULECODE" scenario in the Prebid Server world because it requires adapter changes.

What specifically is your use case @Niksok ? Will First Party Data work?

**Comment by Niksok** [comment]
I would be happy with the option with fpd, but it seems that rtd providers set fpd in adUnit.bids, while prebidServerBideAdapter try to get fpd datafrom config or from bidderConfig but not from adUnit.bids. This concerns jwplayerRtdProvider and haloRtdProvider, other rtdAdapters do not use fpd as i see.

**Comment by bretg** [comment]
Adding @karimMourra and @anthonylauzon to re-consider how their RTD modules are passing data.

If an RTD module wants to get data to Prebid Server adapters, it needs to be first party data. Unless someone can articulate a reason it makes sense to establish yet another path for data to get server side.

**Comment by karimMourra** [comment]
Hi @Niksok and @bretg there seems to be some confusion. The JW Player RTD module doesn't write to `fpd`. The publisher writes to `fpd` and we read from it. We read from both the adUnit's fpd and the config's fpd, and use the config fpd as a fallback (see https://github.com/prebid/Prebid.js/blob/master/modules/jwplayerRtdProvider.js#L147)

With regards to setting targeting data, we set our results to `bid.rtd`. https://github.com/prebid/Prebid.js/blob/master/modules/jwplayerRtdProvider.js#L257

I am not familiar with s2s adapter, but given the information I've provided, are you still blocked by JW Player ?

**Comment by bretg** [comment]
> we set our results to bid.rtd

Right - no confusion. This is the problem for server-side adapters. They don't get 'rtd' data. They only get 'fpd'.

The only way to get data to a server-side adapter is to set it as fpd. I'm not going to approve yet-another-parallel-openrtb-data-path unless someone has a killer-good reason. I can't think of any.

So basically, I think the Prebid-Server angle here makes the existence of bidRequest.rtd rather questionable. At this point I'm thinking we should just make all RTD modules set FPD.

**Comment by Niksok** [comment]
So, @karimMourra , it will be great, if you update the JW Player RTD module so, that it will be write its result into FPD as well.

**Comment by karimMourra** [comment]
@bretg and @Niksok i disagree, our data is not first party data, and I suspect that most Real Time Data does not qualify as first party data. First party Data is data supplied by the publisher. We are not the publisher, we are a 3rd party service used by the publisher. I think the proper solution would be to add server side support for RTD. Using variables in a way that is misleading can cause problems further down the line and it's best to address ASAP.
Given the urgency to support prebid server I am willing to also support FPD in the short term, but suggest adding server side support for RTD in the mid term. The easy solution is not always the right solution.

**Comment by bretg** [comment]
The good news is that this semantic labeling issue is going away. See https://github.com/prebid/Prebid.js/issues/5795

We're going to stop calling it "first party data" and just lump it into the "ortb2" object. Cool?

**Comment by Niksok** [comment]
Cool, but I have one more question - as I see there is currently no support on the s2s side for fields (ext.prebid.bidderconfig) where the prebidServer module passes fpd data to the auction endpoint. Is this a known issue or is this standard behavior?

**Comment by TheMediaGrid** [comment]
@bretg , can you help me in this question?

**Comment by Niksok** [comment]
@bretg , can you help me in this question?

**Comment by bretg** [comment]
> as I see there is currently no support on the s2s side for fields (ext.prebid.bidderconfig) where the prebidServer module passes fpd data to the auction endpoint

There is support for FPD in PBS-Java, but you're right, PBS-Go is currently missing:

- bidder permissions
- bidder-specific FPD
- merging site.data to site.ext.data
- alternate data types

This means that to get FPD through PBS-Go, it needs to be global:
- {site, user, app}.ATTR
- {site, user, app}.ext.data.ATTR

No bidder permissions or bidder-specific data. Adding @SyntaxNode to confirm whether there's a timeline on this support.

**Comment by SyntaxNode** [comment]
@bretg Correct. The Xandr team is currently working on implementing these FPD features for PBS-Go at the start of 2021.

**Comment by bretg** [comment]
Closing this with reference to https://github.com/prebid/prebid-server/issues/879

**Comment by patmmccann** [comment]
Tracked in https://github.com/prebid/prebid-server/issues/879
