### ISSUE TITLE
Prebid 12 and Selenium Automation

### ISSUE THREAD

**Issue by pbasin** [prebid/Prebid.js#605]
We added Prebid 12 header bidding and now Selenium scripts we use for automated testing timeout on some page loads in FF.  It looks like page is loaded with all ads,  but Selenium thinks it isn't and timeouts on default 3000ms settings.  On browser I can see connecting to ad.afy11.net usually before timeout.  After page loads, rest of scripts run normally.

**Comment by mkendall07** [comment]
@pbasin 
Are you saying that loading prebid causes your own Selenium scripts to fail?

**Comment by pbasin** [comment]
Yes,   selenium scripts error on browser opening by timing out since it takes more than 30 seconds(default timeout for Selenium) to complete a page load, after  timeout for initial browser opening the rest of script completes Ok. Our websites that do not have Prebid loaded, open browser without any timeout issues. I did not see an issue when version 8 was loaded but when we went to V12 I started to have issues but we also increased bidders for Senobi and AOL.

**Comment by mkendall07** [comment]
I would try to isolate the behavior to a particular bidder and see what is causing the issue. I'm not sure which bidder  `ad.afy11.net` belongs to (might also be a creative). Prebid should not be causing a 30 second hang on the page.

**Comment by pbasin** [comment]
I agree it is probably a new bidder and not the new version of Prebid.

**Comment by ialex** [comment]
Some bidders may not return a response if server is localhost and that may be causing the page load forever, try to check bid responses to see if all are there.
