### ISSUE TITLE
USP api locator improvement

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/Prebid.js#6051]
## Type of issue

This is a proposal for a small improvement in locating the `__uspapi` function:

Currently, the consentmanagentUsp module looks for `window.__uspapi` on the current window. If that fails, it looks for a `uspapiFrame` frame.

On the other, the consentmanagent module loops through the different parent windows, first checks whether the consent module is available directly, and if not checks for a locator frame. This has the benefit that setups where the parent is accessible ( ie. on same-domain iframes ), the api is used directly instead of using postMessage.

The proposed solution is to mimick the behavior of `consentManagement.js` in `consentManagementUsp.js` to locate the `__uspapi`

**Comment by patmmccann** [comment]
seems related to https://github.com/prebid/Prebid.js/pull/4755
