### ISSUE TITLE
User sync not allowed richaudience bidder

### ISSUE THREAD

**Issue by richaudience** [prebid/Prebid.js#6059]
## Type of issue

Type BUG

## Description

We want to launch the cookie sync with the current settings.
The following warning is displayed "WARNING: User sync not allowed for richaudience"

![image](https://user-images.githubusercontent.com/26602871/100737941-295ddd00-33d5-11eb-8de7-a3c9affb2462.png)

## Steps to reproduce

load the page and check the console

## Test page

[TEST PAGE](https://paris.onvasortir.com/#debug-ads-for-richaudience-1442977200&debug-test-mode&ignore-cpm?pbjs_debug=true )

### Expected results
That on the network we see a cookie sync similar to this:  
https://sync.richaudience.com/dcf3528a0b8aa83634892d50e91c306e/?ord=5255481557510&pubconsent=&euconsent=&euconsentv2=CO9vd3SO9vd3SAHABBENBCCgAAAAAH_AAAAAAAAORAJMNS-AizEscCSaNKoUQIQriQ6AEAFFCMLRNYQErgp2VwEfoIGACA1ARgRAgxBRiyCAAAAAJKIgJADwQCIAiAQAAgBUgIQAEaAILACQMAgAFANCwAigCECQgyOCo5TAgIkWignkrAEou9jDCEMooAaBBwAA.YAAAD_gAAAAA&hasConsent=

### Actual results
the richaudience cookie sync is not launched

## Platform details

Prebid version: 4.17. 
Chorme

**Comment by bretg** [comment]
User Sync isn't allowed when the GDPR enforcement module is active and an adapter hasn't provided an IAB Global Vendor List ID. 

Search for GVLID in the modules directory and submit a PR to define yours.
