### ISSUE TITLE
Prebid.js and combined ads

### ISSUE THREAD

**Issue by pflenker** [prebid/Prebid.js#608]
We are trying to implement prebid.js on our portals (onthesnow.com). However, given the sample code, it seems that it's required for us to call `googletag.pubads().disableInitialLoad();` . If we do this, our big campaigns where a leaderboard ad is combined with a skyscraper aren't delivered properly. How would we solve that issue?

**Comment by mkendall07** [comment]
@pflenker 
I'm not sure why `disableInitialLoad()` would prevent companion ads, but you can load prebid without it using the following method: 
https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/load_pbjs_before_dfp_example.html

This example loads DFP after all prebid units are back or timed out.

**Comment by mkendall07** [comment]
Closing this out. Please re-open if you have additional feedback.
