### ISSUE TITLE
Page url setting doesnt work

### ISSUE THREAD

**Issue by ademozkur** [prebid/Prebid.js#6087]
I have prebid code running in iframe. Google Ad Manager can't recognize origin domain because script it's running inside iframe. Therefore,

googletag.pubads().set('page_url', 'origindomain.com');

I'm using this line. However, when I use this code, other bidders do not work this time because this line is effecting to Prebid Universal Creative like this;

ucTagData.pubUrl = "origindomain.com";

 But when I do not set page_url, it prints the url where iframe is running into ucTagData.pubUrl.

To avoid this

pageUrl: "https://iframeurl.com/iframeurl.html",
publisherDomain: "https://www.iframeurl.com",

I used. However, it didn't work.

What should I do?

**Comment by ChrisHuie** [comment]
@ademozkur is this still a problem you are having? I can do some research and see if others in the community have come across this as well and how they addressed it.

**Comment by ChrisHuie** [comment]
issue appears to have self resolved
