### ISSUE TITLE
canBidderRegisterSync returning true when no iframe filterSetting defined

### ISSUE THREAD

**Issue by JonGoSonobi** [prebid/Prebid.js#6094]
## Type of issue
Bug

## Description
When there is no usersync filterSetting defined for iframes, canBidderRegisterSync('iframe', 'BIDDER') returns with true. Since iframe user syncs are disabled by default. This should return false.

## Steps to reproduce
Using the default user sync config. Execute canBidderRegisterSync('iframe', 'sonobi').

### Expected results
Using the default user sync config. Execute canBidderRegisterSync('iframe', 'sonobi').
Should return false.

### Actual results
Using the default user sync config. Execute canBidderRegisterSync('iframe', 'sonobi').
Should return true.

## Platform details
Latest

## Other information
https://github.com/prebid/Prebid.js/pull/6093

**Comment by bretg** [comment]
Closing this issue, as it's tracked by the PR #6093
