### ISSUE TITLE
Prebid Publisher-Provided User IDs - Invalid 

### ISSUE THREAD

**Issue by gloeffelholz** [prebid/Prebid.js#6104]
## Type of issue

Possible Documentation Bug - Prebid PubProvidedID listed "Prebid.js Attr" on https://docs.prebid.org/dev-docs/modules/userId.html#prebidjs-adapters.

## Description

Based on proposal discussed here https://github.com/prebid/Prebid.js/issues/5690 we would expect the pubProvidedId to be found here:  "bidRequest.userId.ppuid".  The Prebid page here lists this as "bidRequest.userId.pubcid".  Is this correct?  It does not make a lot of sense if so.  If the event the publisher wants to provide a Loyalty ID or other site-specific User ID they need to be able to do this and also separately pass a PubCommon ID if desired.  If they both come in this same field they cannot be differentiated.

## Steps to reproduce
See PubProvided ID - https://docs.prebid.org/dev-docs/modules/userId.html#prebidjs-adapters  

## Test page
See PubProvided ID - https://docs.prebid.org/dev-docs/modules/userId.html#prebidjs-adapters

**Comment by jdwieland8282** [comment]
good catch @gloeffelholz fixed in https://github.com/prebid/prebid.github.io/pull/2567 if you want to review and merge.

**Comment by gloeffelholz** [comment]
Validated live on https://github.com/prebid/Prebid.js/issues/6104
