### ISSUE TITLE
No prebid response from AppNexus... Seems to break the auction

### ISSUE THREAD

**Issue by ericsson66** [prebid/Prebid.js#611]
Hi,
I have a very basic implementation > prebid chooses the winner and sends to DFP.

However, I noticed that when Appnexus returns no bid, it seems that it totally breaks the auction for the placement... No ad is displayed. It could have been a coincidence since other partners can also return no bid at all... but this is systematic. The other bidders are getting ridden off, or prebid.js simply breaks;

[Log] MESSAGE: No prebid response from AppNexus for placement code div-gpt-ad-1472271255756-1 (prebid_20160826214326.js, line 3)

Is there any setting that could solve this issue? Because I feel I'm losing a lot of value... Next step would be to remove Appnexus, but I prefer getting some insight first if possible...

Thanks

**Comment by mkendall07** [comment]
@ericsson66 
Please provide a sample page if you can. 

Prebid should not break anything if there is no demand, the idea is that DFP will return a different campaign.

**Comment by ericsson66** [comment]
Thanks for your prompt reply
http://www.eatwell101.com/frozen-cantaloupe-margarita-recipe?pbjs_debug=true

We implemented progressively toward more complexity, but this issue is recurring since the beginning... Lots of blank spots, DFP console tools unable to get the winner...
Indeed, I think Prebid does its job well, as other bidders skip the auction without any problem. Maybe something in the Appnexus code...

Thought it was me... but after a while I recognized this pattern. Indeed, other bidders don't look like breaking the auction.

**Comment by mkendall07** [comment]
One thing I noticed is that you are calling `pbjs.setTargetingForGPTAsync()` twice. It should only be called once. You can remove it inside the DFP code:
```
  googletag.enableServices();
            pbjs.que.push(function() {
                        pbjs.setTargetingForGPTAsync();  // remove
```

**Comment by ericsson66** [comment]
Thanks @mkendall07 for having a look. I will check it out!

**Comment by mkendall07** [comment]
@ericsson66 
I'm also seeing bid responses consistently. 

after you see the log message `[Log] MESSAGE: No prebid response from AppNexus ` what is the exact symptom?

**Comment by ericsson66** [comment]
@mkendall07  I guess I've made a wrong correlation. There's no other symptom associated... So it might rather be a latency issue. I'm so new to all of this;)

**Comment by mkendall07** [comment]
Oh, the message isn't an error, it simply indicates there was no demand. If your not seeing any other symptom it's working as expected.

**Comment by ericsson66** [comment]
Ok, thanks a lot... I feel more confident now
