### ISSUE TITLE
Include all modules included in the prebid build in comments

### ISSUE THREAD

**Issue by smenzer** [prebid/Prebid.js#6117]
## Type of issue
Feature Request

## Description
When debugging publisher websites to see why something isn't working properly (for example, why GDPR consent strings are being picked up; or why an identity module is not providing IDs even though they're configured to), it's challenging to determine if it's simply because the module was not properly included during the build/download process.

I'd like to propose that we add comments to the top of the build that list the individual modules that were included in the build. 

## Steps to reproduce
Build prebid and look at the production version:
![image](https://user-images.githubusercontent.com/624392/101902966-d42f8180-3bb3-11eb-8dec-13803f9b57f5.png)

### Expected results
From the example above, if we assume the build only included the `pubmaticBidAdapter`, `userId`, and `id5IdSystem`, then the comment at the top could look like this:

```javascript
/* prebid.js v4.17.0
Updated : 2020-11-27 
Modules : pubmaticBidAdapter, userId, id5IdSystem */
!function(u){var s=window...
```

If we go this route, we should do the same for the [Downloads page](https://docs.prebid.org/download.html)

Thoughts?

**Comment by pm-harshad-mane** [comment]
Good suggestion.

**Comment by ChrisHuie** [comment]
#6297 merge closes out this issue
