### ISSUE TITLE
BidAdjustment and price granularity

### ISSUE THREAD

**Issue by ericsson66** [prebid/Prebid.js#613]
Hi everyone!

For now, my price granularity is set to "medium", so 0.10 increments... Unfortunately, when i want to adjust the bid price from partners that return a gross cpm, the net bid returned falls out of the 0.10 increment.

I don't want to set up a custom granularity for now, so my question:

Is there a way that I can adjust the Bidder Net CPM **before** Prebid processes the bids with the granularity setup?

or am I just missing something?

Thanks

**Comment by mkendall07** [comment]
@ericsson66 
How are you adjusting the cpm now? Are you using `bidCpmAdjustment`  ?

**Comment by ericsson66** [comment]
For now I leave it like this, gross CPM...

With bidCpmAdjustment, the adjusted bid couldn't match the line item anymore.

I don't have a lot of partners yet so there's generally a big chunk of difference among the bids. I don't think a lot of bids are "stolen" from that, but for further implementation I would be glad to have some insight, before spreading out a thinner granularity.

**Comment by mkendall07** [comment]
@ericsson66 
We'll check into this. It might not be working properly.

**Comment by ericsson66** [comment]
Ok, thanks for that!

I now I might be that type a publisher that try to catch the wagon, and solutions I'm asking for might look like overshooting for skilled developers...

**Comment by matthewlane** [comment]
Hi @ericsson66, I'm checking into this. From what I can tell looking at the source code, cpm adjustments are made before Prebid processes any bids. Would you mind posting any example data you are seeing, such as gross cpm returned from a bidder, and the price granularities after the the bid is adjusted? I'd like to make sure I'm understanding this issue correctly, thank you

**Comment by ericsson66** [comment]
Hi @matthewlane 
I simply cannot reproduce the situation anymore! I noticed this when I started to implement HB with prebid.js, with version 0.11.

We are since using v0.12 and after testing I found out that everything works fine. The gross CPM is adjusted, then all bids are processed through granularity settings... no lost line-item anymore.

**Comment by matthewlane** [comment]
Ok, thanks for letting me know, glad it's working as as you expect.
