### ISSUE TITLE
sspBC adapter name.

### ISSUE THREAD

**Issue by onaydenov** [prebid/Prebid.js#6132]
## Type of issue
Minor issue. Request for the module name change.

## Description
Minor change. Request for the module name change.
Instead of standard ..xx..BidAdapter it uses sspBCAdapter.js and sspBCAdapter.md. It makes third-party wrappers to use unnecessary extra logic.

**Comment by bretg** [comment]
Thanks for the report. This was fixed with https://github.com/prebid/Prebid.js/pull/6118
