### ISSUE TITLE
Prebid player sizes for video bidding

### ISSUE THREAD

**Issue by Sovica** [prebid/Prebid.js#6138]
## Type of issue
Question

## Description
I have a question regarding how the player size is being passed to prebid from a page and back to DFP as an ad server.
By default, all adapters (I'm talking about video prebidding here) need a param that defines the player size. As you probably know, a single/unique player size is not really possible having in mind the responsive nature of today's sites so even though a video player has a size of 630x360, on mobile it will be responsive and probably smaller etc. 

From what I see, this specific size that we set for prebid which is the player size can differ depending on the environment and once a bid comes through, prebid returns a DFP GPT tag which has its sz param set to the size of the player. 
The main problem here is that for us to match this request to a DFP line item we need to use some kind of targeting size which by default is 640x480, 400x300 and 300x250 for video ad units. If we send over a size of a player that is **not** any of the three mentioned, there will never be a match with DFP and thus the appnexus cache URL or any other won't ever get called and DFP will return an empty VAST response.

This specific setup does make sense for display banners but for video does not. What is the expected workflow here having this in mind? Should we be hardcoding the player size to a specific targeting value that we have set inside DFP or is something else here I am missing?

## Platform details
Desktop and mobile, latest PrebidJS implemented.

**Comment by wqi1972** [comment]
@Sovica do you have a test page for this?
We use one single size: 400x300 for video ads on all devices, and the video player automatically adjust that size to video player size on different devices.

**Comment by mike-chowla** [comment]
Due to GAM / DFP's handling of size, expected workflow is to set the playerSize to 640x480 (desktop), 400x300 (mobile) or 300x250 (in-banner).  Setting this size like this will also cause the bid adapter to use those sizes in their bid requests.  My experience is GAM / DFP's convention of expecting video sizes to be a platform signal and not the actual player size has trickled through the entire RTB ecosystem with most DSPs expecting one of the platform sizes and not the actual size.  When I've seen the actual player size in bid requests, bid & fill rates are poor since most DSPs w.on't on the non-standard actual size

If bidders want the actual size, we can figure out a way for the bidders to get actual size.  I'll raise the topic at the next Prebid Video Taskforce meeting.

**Comment by Sovica** [comment]
@mike-chowla 

I understand what you say completely here. What we currently do is always send the proper (current) size of the player to bidders and when a bid returns we kind of hardcode the size to match our DFP setup. We were thinking this was a clear way to always say to the bidders "hey this is the exact player size" so we don't fraud them if this can even be interpreted like that.

I'm going to ask my team to change the current behavior to what you said so we send 640x480 (desktop), 400x300 (mobile) or 300x250 (in-banner) and see what happens but please do update this thread if you get any further info on this matter.

Maybe this could also be a good entry in Prebid docs so people know how to implement this part of the process correctly?

Thanks!

**Comment by bretg** [comment]
@mike-chowla - any docs PRs forthcoming here?

**Comment by gglas** [comment]
To be discussed in the next Prebid Video PMC -- should be an update then

**Comment by patmmccann** [comment]
This issue is ongoing and we think we'll have to coordinate with IAB on this. In the meantime, we plan to add some documentation addressing this issue and potentially add to a new video module logic choosing the 'best' standard size for a given player size.

**Comment by patmmccann** [comment]
We plan to add this blurb to the documentation at https://github.com/prebid/prebid.github.io/blob/master/dev-docs/show-video-with-a-dfp-video-tag.md#1-create-a-video-ad-unit

` Publishers are encouraged to select a player size near the actual player size from mediaTypes.video.playerSize that is on this list: 640x480, 400x300, 300x250, 640x360, 400x255, 1280×720, 300x400, 250x300, 720x1280, 360x640, 480x640, 255x400, 320x180, 180x320.  Currently GAM and many DSPs will not bid based on actual player size. The Prebid community is actively engaging demand to enable them to better understand the real player size in bid requests. Please see https://support.google.com/admanager/answer/9606829 for GAM rules on video sizes. `

**Comment by Sovica** [comment]
@patmmccann I think this makes sense. Having that said I do know from my contacts that you have DSP's like DistrictM that for some reason require sending a 1x1 size and work with that. So I guess here it is more of a question for the DSP's what they expect to get and if the above can be standardized across the board. 

In regards to DFP/GAM setup, we and others usually set the targeting size to the standard that GAM provides by default which is 640x480v, 400x300v and 300x250v but as you know, these sizes do not matter that much as GAM's sole purpose is to just serve the redirect cache URL and pass the required key-value pairs from Prebid.

**Comment by gglas** [comment]
@patmmccann any more work to be done here?

**Comment by patmmccann** [comment]
no
