### ISSUE TITLE
Mediatypepricegranularity not applied correctly with different mediatypes in same request

### ISSUE THREAD

**Issue by KianGroenen** [prebid/Prebid.js#6146]
## Type of issue
bug

## Description
mediaTypePriceGranularity isn't properly applied when requesting different mediaTypes in the same request.

## Steps to reproduce
- banner & instream video in 1 request
- mediatypepricegranularity high for banner, bucket for video with increment medium
- video bid with high granularity in response
- pbjs.getHighestCpmBids('video')[0].adserverTargeting doesn't properly apply mediatypepricegranularity

## Test page
https://jsfiddle.net/pd57ecw4/14/

### Expected results
pbjs.getHighestCpmBids('video')[0].adserverTargeting.hb_pb = 12.10

### Actual results
pbjs.getHighestCpmBids('video')[0].adserverTargeting.hb_pb = 12.15

## Platform details
Prebid version: 4.20.0
Browser: Chrome
OS: Windows

**Comment by KianGroenen** [comment]
Appears to be timing issue with implementation

**Comment by ChrisHuie** [comment]
@KianGroenen I have dug a bit through the code and haven't seen anything. I tried to use your jsfiddle above to better understand this but seems like it is returning errors. Is this still a problem you are having?

**Comment by ChrisHuie** [comment]
I wasn't able to reproduce this issue in the provided JSFiddle and have reviewed the tests but not found anything. (https://github.com/prebid/Prebid.js/blob/master/test/spec/utils_spec.js). HighestCPM tests start on line 540
