### ISSUE TITLE
Update PBJS to use modern JS features and reduce dependencies

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#6154]
## Type of issue
PBJS project need to be updated to use Modern JavaScript as it helps to improve publisher page performance.

## Description
Web.dev released a new blog and a video explaining benefits of using Modern JavaScript and its impact on page performance speed.
Blog: https://web.dev/publish-modern-javascript/ 
YouTube Video:  https://youtu.be/cLxNdLK--yI 

Tried PBJS basic example with only appnexus adapter ( https://pm-harshad-mane.github.io/PBJS/basic.html ) on the tool provided in blog, https://estimator.dev/#pm-harshad-mane.github.io/PBJS/basic.html 
Result: 
We can improve page performance by whopping 13% !!!!
<img width="1661" alt="PBJS_Estimator" src="https://user-images.githubusercontent.com/8835908/103315507-a2535300-49da-11eb-8199-bc0ffbf17eac.png">

**Comment by patmmccann** [comment]
duplicated in #3058 and a couple other places, good to close @pm-harshad-mane ?
