### ISSUE TITLE
uspConsent value

### ISSUE THREAD

**Issue by soman** [prebid/Prebid.js#6156]
## Type of issue
question

## Description
I'm getting uspConsent value like 1NNN/1YNN/1NYN etc. 
I would like to know meaning of the following:
1. 1NNN
2. 1NYN
3. 1YNN
4. 1YYY

Also which is correct for uspConsent.

Thanks

**Comment by wqi1972** [comment]
Please check: https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/US%20Privacy%20String.md

**Comment by bretg** [comment]
Thanks for answering the question @wqi1972.

@soman - probably the most important field of the USP string from a header-bidding perspective is the 3rd one "Opt-Out Sale". However, Prebid cannot recommend what behaviors each publisher should take when a CA-user opts out. 

The Prebid infrastructure simply obtains the USP values and passes them through the ecosystem for bidders to utilize.
