### ISSUE TITLE
Suggestion: Option to include GA tracking in download package

### ISSUE THREAD

**Issue by troels-jakobsen** [prebid/Prebid.js#616]
The prebid.js file you receive from the download page does not include the code for GA tracking of prebid statistics. It would be nice to be able to download a GA-enabled version of the file, rather than having to build it on my own client via node.js.

I suggest adding a checkbox on the download page to include/exclude GA tracking.

**Comment by ericsson66** [comment]
I agree... 
The optional feature will be welcomed.

**Comment by CLKeenan** [comment]
Yes please! If someone has rebuilt 0.12, could you post here? That would be greatly appreciated!

**Comment by headerbidding** [comment]
Yes please! If someone has rebuilt 0.13, could you post here? That would be greatly appreciated! 
(I have not been able to create my own build.  I installed node.js, but am getting syntax errors.)

**Comment by headerbidding** [comment]
Please bring back GA tracking!

**Comment by CLKeenan** [comment]
Just checking to see if this is still be considered for a release.

**Comment by mkendall07** [comment]
We are going to work on this shortly

**Comment by matthewlane** [comment]
The download page now includes a section to include analytics adapters, including GA
