### ISSUE TITLE
Multiple Aliases for same adapter

### ISSUE THREAD

**Issue by ericsson66** [prebid/Prebid.js#617]
Just to make sure I'm not making any mistake...
Can I use multiple aliases for the same AppNexus adapter without any conflict?

pbjs.aliasBidder('appnexus', 'districtm');
pbjs.aliasBidder('appnexus', 'gourmet');

Thanks

**Comment by mkendall07** [comment]
@ericsson66 
Yes you can.

**Comment by ericsson66** [comment]
Ok great!

BTW, I also receive a hb_deal_PARTNER ID with each of the winning bid on a specific ad slot from a recently added partner. I didn't set up deals on my end... and the winning hp_pb value is constant (and fairly high)... what does that mean? Am I missing something?
