### ISSUE TITLE
New CMP (Quantcast) - Huge drop in imps sold trough prebid

### ISSUE THREAD

**Issue by Langkaia** [prebid/Prebid.js#6172]
## Description
Hi,
New to github, but we have an issue we haven't been able to solve, so hopefullt someone here could give some insight.

Nordic (EU) medium-sized publisher, running prebid v4.7.0 trough Adform.

We implemented QuantCast CMP 4th of Dec 2020, and from the 5th we saw a huge drop in impressions sold trough prebid (previously we were using a more or less non-functional popup that defaultet all consent to true).
Bid rates stays more or less the same, but win rates are way down (winrate was around 2 % per SSP pre-QuantCast, now somewhere around 0.0-0.5 %).
Our consent-rate is decent in the QC-dashboard, so that shouldnt be an issue.
About a week later we updated to the newest version of Prebid in case that would solve some of it, but no effect.
We are passbacking inventory from Adform to Google AdManager, and here we sell inventory as usual.

I am no developer, but from what I can see we are sending correct GDPR-strings, and I have also been informed by SSPs that consent seems fine.

Would anybody be able to tell me if there are some obvious errors on our end? Thanks in advance for all help.

Saw someone had a similar issue with LiveRamp #5529 but it does not seem the solution was the same.

## Test page
Live on our site:
https://www.proff.no/selskap/proffhund-as/trondheim/sports-og-fritidsutstyr/IF7GBUY07RA/?pbjs_debug=true
From debugging I can see an issue with Widespace, but the issue is more or less consistent across all SSPs we are using.

## Platform details
Prebid v4.7.0 trough Adform
Quantcast CMP v23

## Other information
Prebid-script: https://hb.adx.adform.net/hb/4395.js

**Comment by spormeon** [comment]
i'm in the Uk and no CMP even comes up for me, so i'd look into that to start with

**Comment by Langkaia** [comment]
Thanks for checking. Hmm thats strange. I've only used a VPN for other countries, but it seems I am getting the CMP-popup.

**Comment by spormeon** [comment]
have you actually got the gdpr module included in the prebid build?

![DevTools_-_www_proff_no_selskap_proffhund-as_trondheim_sports-og-fritidsutstyr_IF7GBUY07RA__pbjs_debug_true](https://user-images.githubusercontent.com/8503167/104033010-df7fc800-51c6-11eb-809b-f9edb90a7ae1.png)

**Comment by Langkaia** [comment]
It was my impression that we had the GDPR included (see below from the prebid-script), but looking at your screenshots I might be wrong.

` pbjs.setConfig({
                consentManagement: {
                                gdpr: {
                    cmpApi: 'iab',
                    timeout: 5000,
                }
                }`

**Comment by spormeon** [comment]
but its actually included in the prebid versionX file build?

**Comment by Langkaia** [comment]
Good question. I will look into that

**Comment by Langkaia** [comment]
AFAIK it is included in the build: https://s1.adform.net/banners/scripts/prebid.4.latest.js

**Comment by bretg** [comment]
You're using the default GDPR config, which means auctions will be blocked without consent from the user. I would expect that every publisher in the EEA enforcing GDPR will take a hit in header bidding when using the default settings -- it's unlikely users are accepting CMP consent before auction timeouts. You've set a 5 second timeout for the CMP, but only 750ms for the auction. The impact of missing the first auction for every visitor will vary per site -- some sites may have a lot of first time visitors, while others have a higher percent of repeat visitors.

This is where you need to have the conversation with your lawyers and go through the configuration options. You need to understand what Prebid does and can do, and consider whether the bidders you utilize can bid on contextual data signals when user ID isn't available.

- https://docs.prebid.org/dev-docs/modules/gdprEnforcement.html
- [Prebid TCF2 whitepaper](https://docs.google.com/document/d/1fBRaodKifv1pYsWY3ia-9K96VHUjd8kKvxZlOsozm8E/edit#heading=h.hlpacpauqwkx)


> Bid rates stays more or less the same

What about bid volumes? Bid rate might be the same, but there may be a lower number of bid requests going out.

> win rates are way down

Win rates are related to the bid CPMs which are affected by the existence of user IDs. 

You have 3 analytics adapters running on that test page... hopefully one of them can give you an indication of user ID match rate and CPM values. If you've seen bid CPM go down for some bidders, work with them to find out why.

**Comment by Langkaia** [comment]
Thanks bretg, that brings me more insight! I was not aware that the default config blocks user without consent.

**Comment by bretg** [comment]
Closing this out. Re-open if it didn't solve your problem @Langkaia
