### ISSUE TITLE
[Question] can userId submodule use iframe

### ISSUE THREAD

**Issue by Galphimbl** [prebid/Prebid.js#6173]
## Type of issue

Question

## Description

can userId submodule use iframe to get id instead of ajax ?
can  userId submodule use both iframe and ajax ?
any helpers/utils exists ?

**Comment by bretg** [comment]
> can userId submodule use iframe to get id instead of ajax ?

I would say no. The point of the user ID subsystem is to make those IDs available for bid adapters.

In order for the results of an iframe to get routed to bid adapters you would have to have special code in the result of the iframe that would drop a cookie or local storage. We don't want to allow new sources of proprietary source code like this.

> any helpers/utils exists ?

for what?

**Comment by Galphimbl** [comment]
ID's would be available.
Maybe we have some misunderstanding.

I want to create userId submodule, and in our solution we have hybrid system that use safe frame and ajax to identify user. i looked over other submodules and can't find that someone use iframes. so i decided to ask if we can use iframes in our submodule or we must leave just ajax solution?

**Comment by bretg** [comment]
Please read the module rules at https://docs.prebid.org/dev-docs/module-rules.html - specifically the Global rules and the User ID-specific rules. 

If you can make it work without breaking **the spirit** of any of those rules, we'll approve it. The ones people have the most trouble with are the "no external code" rule and the privacy regulations. Nail those and you've got a good headstart.
