### ISSUE TITLE
Price Floors module should apply pbjs.bidderSettings.standard.bidCpmAdjustment

### ISSUE THREAD

**Issue by aaroniniguez** [prebid/Prebid.js#6175]
## Type of issue
Bug
## Description

The Price Floors module should apply the pbjs.bidderSettings.standard.bidCpmAdjustment function if it exists, to the bid floor. 

## Steps to reproduce
1. Set a bidCpmAdjustment function in standard (and ensure there is no bidder specific bid cpm adjustment function): 
```
pbjs.bidderSettings.standard.bidCpmAdjustment =  function(bidCpm, bid) {
      return bidCpm * .5;
    }
```
2. Ensure that bidAdjustment is set to true: 
```
pbjs.setConfig({
    floors: {
        enforcement: {
            bidAdjustment: true
        }
```
3. Send bid requests with the rubicon bid adapter, (bidder that uses the getFloor function) 
4. When theres a floor match, the bid floor will not be adjusted and **should** be adjusted.

Possible solution is to set this line in priceFloors.js in the getBiddersCpmAdjustment function:
```
const adjustmentFunction = utils.deepAccess(getGlobal(), `bidderSettings.${bidderName}.bidCpmAdjustment`) || utils.deepAccess(getGlobal(), `bidderSettings.standard.bidCpmAdjustment`);
```

**Comment by bszekely1** [comment]
Hi @aaroniniguez, I just testing the bid adjustment feature and it is working on my side. Can you provide a page where you see it incorrectly functioning?

**Comment by aaroniniguez** [comment]
@bszekely1 sure, I"ll provide one. 

Curious though, When testing on your end what does your pbjs.bidderSettings contain?

**Comment by bszekely1** [comment]
```
pbjs.bidderSettings = {
          rubicon: {
            bidCpmAdjustment : function(bidCpm){
              // adjust the bid in real time before the auction takes place
              return bidCpm * 0.50;
            }
          }
        };
```

**Comment by aaroniniguez** [comment]
thats incorrect, it should be: 
```
pbjs.bidderSettings = {
          standard: {
            bidCpmAdjustment : function(bidCpm){
              // adjust the bid in real time before the auction takes place
              return bidCpm * 0.50;
            }
          }
        };
```

**Comment by bszekely1** [comment]
I was making a Rubicon specific one. The one you supplied is a general one. Are you suggesting the standard one does not work?

**Comment by aaroniniguez** [comment]
Yes, using standard won't work

**Comment by bszekely1** [comment]
Yes, we can validate this is an oversight in the implementation of the Floors Module. Should be an easy fix. It will probably be released in the next release.

**Comment by aaroniniguez** [comment]
awesome, glad to hear it

**Comment by robertrmartinez** [comment]
@aaroniniguez This PR has been made.

Didn't even notice your proposed "fix" was exactly what I ended up doing! haha.

Thanks for bringing this to our attention.

**Comment by aaroniniguez** [comment]
haha I debated making it myself or not, figured you guys would know more , thanks!
