### ISSUE TITLE
Proposal to reduce ad server keys when sending multiple or all bids

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#6176]
## Type of issue
Feature Request

## Description
Prebid sets a lot of ad server keys if one is sending multiple bids. For example, if someone has 30 bidders they might call in various scenarios and hb_size_bidder, hb_pb_bidder, and hb_adid_bidder as ad server keys, that is 90 keys against a hard 200 key limit in gam. Deal / Format / Adomain / Source would increase that to 210, making the current setup difficult to maintain long term and forcing publishers to drop information. 

Proposal:

A set config option converts keys (by key) to ad server vectors like so:

hb_size_rubicon = 300x600 and hb_size_openx = 300x250 would become hb_size_smb = rubicon:300x600,openx:300x250
hb_pb_appnexus = 3.1 and hb_pb_pubmatic = 3.2 would become hb_pb_smb = appnexus:3.1,pubmatic:3.2

In this example, the publisher would be able to reduce the number of additional keys to support from 90 to 3 (hb_adid_smb being the third).

Publishers would need to be savvy enough to modify their creatives to support this as well, or a future PUC PR could add support for this feature, which requires creatives be gam order aware (maintain a map of gam order id to bidder). The one exception is the price key, which would just need targeting updates. Instead of targeting hb_pb_3xlift = 3.3, a publisher could change the targeting to hb_pb_smb = 3xlift:3.3

Other useful keys like hb_deal, hb_format, and hb_source could follow similar patterns.

**Comment by AskRupert-DM** [comment]
one issue I see with this proposal is the DFP Key-Value - Value limit is 40 characters. The example key for hb_pb_smb would exceed that limit if you have 3/4 bidders all returning bids & you have a low granularity price bucket setting on page.

**Comment by AskRupert-DM** [comment]
> one issue I see with this proposal is the DFP Key-Value - Value limit is 40 characters. The example key for hb_pb_smb would exceed that limit if you have 3/4 bidders all returning bids & you have a low granularity price bucket setting on page.

Per chat on the prebid slack channel and response from @patmmccann this isn't valid / an issue as values will be passed as an array so work around the issue I raised in my comment.

**Comment by patmmccann** [comment]
Closing as an unpopular proposal and difficult to generalize the creative changes required
