### ISSUE TITLE
pbsBidAdapter: add cooperative syncing flag

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#6186]
## Type of issue
enhancement

## Description
Some versions of Prebid Server support a "cooperative sync" mode which helps publishers raise PBS match rates by proactively doing a cookie match with bidders that aren't in that particular pub's page. In this way, a given user may have a sync done on pubA that isn't used until they visit pubB.

Users have control over syncing and setting of cookie through GDPR and USP. However, some publishers would prefer that cooperative syncing not happen on their site.

This feature is to add a "coopSync" attribute to Prebid Server bid adapter `s2sConfig` 

```
pbjs.setConfig({
    s2sConfig:
        accountId: '1',
        bidders: ['bidderA', 'bidderB'],
        ...
        coopSync: false  // turn off cooperative syncing
});
```

The result of this setting will update the POST body to /cookie_sync, adding "coopSync": VALUE

If coopSync isn't specified, the pbsBidAdapter shouldn't add it to the POST body. Let PBS default.

**Comment by bretg** [comment]
Closing this issue as covered by the PR.

**Comment by ChrisHuie** [comment]
#6213 closes out this issue
