### ISSUE TITLE
No arguments from bidsBackHandler

### ISSUE THREAD

**Issue by JuanCaicedo** [prebid/Prebid.js#62]
Even when I get a bid response, [this callback](https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/pbjs_example_gpt.html#L156) gets called with no arguments.
```
bidsBackHandler: function(bidResponses) {
    console.log(bidResponses); // undefined
    console.log(arguments); // []
    initAdserver();
},
```

Is this an error in the documentation? Does that callback never get called with arguments?

**Comment by mkendall07** [comment]
Hi @JuanCaicedo,

This is an issue we found (#54) and will be fixed in the next release. Thanks
