### ISSUE TITLE
adding new event for adapters -onImpressionViewable 

### ISSUE THREAD

**Issue by josepowera** [prebid/Prebid.js#6205]
## Type of issue
Feature request

## Description
prebid.js adapters already have onBidWon events enabled. Idea is to have additional event, that bidder could receive - reason is we would like to have same trigger as in DFP... therefore we suggest to make available new event that gets triggeres when DFP triggers impressionviewableevent

Bid adapters can add bUrl or similar into bidResponse and use that in new event - onImpressionViewable 

## Other information
https://docs.prebid.org/dev-docs/bidder-adaptor.html#registering-on-bid-won
https://developers.google.com/publisher-tag/reference#googletag.events.impressionviewableevent

**Comment by pm-harshad-mane** [comment]
Interesting idea, i will code a module for this and share a PR soon.

**Comment by josepowera** [comment]
That was FAAST!

**Comment by bretg** [comment]
Closing this issue as covered by the PR.
