### ISSUE TITLE
Dynamic Loading the Bid Adapters via a URL

### ISSUE THREAD

**Issue by jsonUK** [prebid/Prebid.js#6221]
## Type of issue
Question

## Description
So we currently have multiple sites and they use different combinations of Bid Adapters. My question is that the current approach is to bundle the bid adapters with gulp to be a single file, but is there any way the bid adapters can be dynamically loaded individually so that we can have a wider range of setups without having to compile a new version each time.

I noticed if you gulp compile you get the minified versions of every adapter and they all sit in the "build/dist" folder. It would be handy if each release could be compiled and then reference the adapter as we need via a URL. This would make testing and upgrading the latest version of Prebid easier for our network. Have you tested this approach at all and is it in your roadmap?

**Comment by gglas** [comment]
Hey Json,

To make sure I understand, are you talking about auction inclusion or are you talking about adapter inclusion?  I'm not sure how we could alter the contents of a given PB build dynamically based on a querystring, but definitely building expanded logic around reading urls to inform sounds like it could potentially be useful.  How are you thinking about the architecture here?

**Comment by patmmccann** [comment]
seems related to https://github.com/prebid/Prebid.js/issues/5287#issuecomment-733039758

**Comment by gglas** [comment]
@jsonUK we discussed extensively in the context of #5287 -- and we believe that these two are duplicates.  Going to close this issue, please follow along there as we update NPM (probably on the heels of the 6.0 release)
