### ISSUE TITLE
Question: GDPR based

### ISSUE THREAD

**Issue by ErikMHummel** [prebid/Prebid.js#6226]
## Type of issue

Question

## Description

I'm with Lotame and we recently started supporting the GLV ID in https://github.com/prebid/Prebid.js/pull/6185. 

Can you confirm that the following is true?

1 - Setting the GLV ID on the user id module will have 0 effect in the case where GDPR enforcement module is not present

2 - If GDPR enforcement module is present and we don't have consent based on their rules, execution will stop inside getStorageManager and the rest of our code won't run

**Comment by bretg** [comment]
> 1 - Setting the GLV ID on the user id module will have 0 effect in the case where GDPR enforcement module is not present

Correct.

> 2 - If GDPR enforcement module is present and we don't have consent based on their rules, execution will stop inside getStorageManager and the rest of our code won't run

The specific consent needed inside getStorageManager is Purpose 1.

The User ID core module requires the User ID module to have P1 consent or it will be skipped.

https://github.com/prebid/Prebid.js/blob/7970f51b51c7a359eeb88e84900eca1d55f476df/modules/userId/index.js#L317

**Comment by ErikMHummel** [comment]
Much appreciated @bretg.
