### ISSUE TITLE
Shared Id endpoint does not seem to work?

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/Prebid.js#6235]
## Type of issue
Shared Id endpoint does not seem to work

## Description
I'm not sure if this is the right place to ask, but I've had an issue open in the sharedid repo (https://github.com/prebid/shared-id/issues/20)  for more than a week without any response so I will try here.

I cannot get id.sharedid.org/id to return an id, it just returns 204.

I've tried several devices and browsers.

I can't see that any TCF information is passed (or anything else for that matter) so I wonder if anyone knows if there is an issue with the endpoint or what might be causing it to deny giving an id in return?

The call is being made from Sweden (EU) if that would matter.

## Steps to reproduce
Activate sharedId in a Prebid.js setup or call https://id.sharedid.org/id

## Test page
https://id.sharedid.org/id

### Expected results
An Id in the response body.

### Actual results
Empty

## Platform details
Chrome/Firefox/Edge
Windows 10 + Mac OS

**Comment by jdwieland8282** [comment]
thanks will take a look and comment in prebid/shared-id#20

**Comment by ChrisHuie** [comment]
Please refer to [prebid/shared-id#20](https://github.com/prebid/shared-id/issues/20) for further conversation around this issue
