### ISSUE TITLE
[QUESTION] Create admanager line items for all prebid bidders

### ISSUE THREAD

**Issue by vegagame** [prebid/Prebid.js#6237]
I tried various applications to generate line items in admanager, but none of them worked. My goal is to create the line items for all header bidding bids (instead of seeing only the winning bids in each auction). see: https://docs.prebid.org/adops/send-all-bids-adops.html 

Is there any working online tool or service?

**Comment by vegagame** [comment]
This tool works: [https://github.com/Insideall/dfp-prebid-lineitems](url)

**Comment by bretg** [comment]
Sounds like you covered this yourself. For the record, we've debated the merits of collecting 3rd party tools into a page, but we cannot thoroughly review such tools periodically to actually "recommend" any to users of the Prebid platform. We may make such a page in the future, but it will have a large legal disclaimer that top.

FYI - Prebid recently released a command-line tool for creating line items in GAM -- https://docs.prebid.org/tools/line-item-manager.html
