### ISSUE TITLE
Implementing a floor price with bidCpmAdjustment

### ISSUE THREAD

**Issue by AnthonyGraceffa** [prebid/Prebid.js#624]
I'm trying to set bids to 0 that are under the set floor price but with this setup:
`pbjs.bidderSettings = {

    standard: {
      bidCpmAdjustment: function (bidCpm) {
        if(bidCpm < floor) {
          return 0;
        } 
        return bidCpm; 
      }
    },
    rubicon: { 
      bidCpmAdjustment : function(bidCpm){
        console.log("rubicon cpm: " + bidCpm); 
        if(bidCpm * 0.85 < floor) {
          return 0;
        } 
        return bidCpm; 
      }
    }
}`

Impressions are being counted but no one is winning the bids as if every bid is being set to 0. The log messages report that in most cases the bidCpm is higher than the floor too. Help would be appreciated.

**Comment by mercuryyy** [comment]
simply do it like this

rubicon: { 
  bidCpmAdjustment : function(bidCpm){
if (bidCpm > 0) {
    if(bidCpm * 0.85 < floor) {
      return 0;
    } else {
return bidCpm; 
}
}

this way it wont touch it if there is no bid returned

**Comment by mkendall07** [comment]
@AnthonyGraceffa 
I don't see anything wrong with your logic. Are you still having issues?

**Comment by dugwood** [comment]
@mkendall07 I'm facing an issue with such a code:
https://github.com/prebid/Prebid.js/blob/master/src/bidmanager.js#L327

If it's zero, then the price is not adjusted. As a consequence, the bid is not ignored... How can I set a floor as @AnthonyGraceffa asked?

I can return 0.01, but if all bids are 0.01, one of these will won, isn't it?

**Comment by mkendall07** [comment]
@dugwood 
Yes that's true. I hadn't noticed the 0 check. We can remove that I suppose. Feel free to submit a PR.

**Comment by dugwood** [comment]
Shouldn't it a «not a negative number» test? I mean:

      if (bidPriceAdjusted >= 0) {

Does that make sense to you?

**Comment by mkendall07** [comment]
Yep that makes sense.
