### ISSUE TITLE
Prebid Floor Module not following rules defined in floors object

### ISSUE THREAD

**Issue by joelt-system1** [prebid/Prebid.js#6243]
## Question
Prebid Floor Module not following rules defined in floors object

## Description
I am building Prebid.js with the currency module and priceFloor module. 
I am defining the price floor via package level floors using pbjs.setConfig. Inside the floors object I set the schema fields to adUnitCode and in the values object I am defining the adUnitCodes.

When I load my page, I can see that the floor module is being initialized (using debug mode) 
![image](https://user-images.githubusercontent.com/58273248/106332221-59e6b980-6254-11eb-97c1-aa3e53c87a49.png)

However, it appears that the rules are ignored completely and it goes straight to using the default floor price. If I do not include default then I get warnings that bidders are unable to determine a matching price floor for bid Response
![image](https://user-images.githubusercontent.com/58273248/106332500-f610c080-6254-11eb-8e76-13cc9ea9fb29.png)

I have checked that the adUnitCode supplied in the rules matches exactly with the adUnitCode available in pbjs.adUnits. (See below)
![image](https://user-images.githubusercontent.com/58273248/106333354-7ab00e80-6256-11eb-85ce-2922b001bee1.png)

I am unsure why the rules are not being followed as set. It seems everything will just go to default (if default is present).

### Expected results

Expect that bidders will follow the rules set in the floors object.

### Actual results

Bidders use the default floor price, or if default floor price is not set then they give a warning "unable to determine a matching price floor for bid Response"

## Platform details
Prebid.js 4.23.0

**Comment by bszekely1** [comment]
Would you be able to put this setup on an external page to debug? I have tested adUnitCode myself last week and it had worked. Given your error it almost does not seem like an issue with the Price Floors Module but rather some other external issue going on with Prebid. It's a bit unclear given the description what is occurring.

**Comment by joelt-system1** [comment]
There may be something going on, as it doesn't matter what rule I use. Even if I just set "*" for adUnitCode it still is unable to determine a matching price floor. It is only able to if I set it to default.

I also tried just defining the price floor inside each adUnit itself, with

`
floors: {
  default: 1.00 
}
`

And for some reason the floors module is not even initialized at all when I do that. It only seems to turn on when I use the pbjs.setConfig method. However as I mentioned if default is not present then no matter what schema I use it is unable to determine a matching price floor.

**Comment by bszekely1** [comment]
Can you please provide a test page? The floors module does indeed work. There must be something wrong with your setup.

**Comment by joelt-system1** [comment]
I have solved it. When I added quotes to the keys in "values" it was unable to match them. I removed the quotes from the keys (even though in the documentation there are quotes) and it started to work. Turns out that was the issue for me.

**Comment by bszekely1** [comment]
The rules (values) should be strings. The Floors Module will split on the string values to find the correct enforcement. Not sure what your setup is like but glad you got it working correctly. I am closing out this issue.
