### ISSUE TITLE
Canceling auction whereas allowAuctionWithoutConsent: true

### ISSUE THREAD

**Issue by mlapeyre3** [prebid/Prebid.js#6267]
## Type of issue
Unwanted behavior related to GDPR

## Description
Hi there! On the page https://www.rp.pl/?pbjs_debug=true we can see that, if we don't answer to the CMP popup after 8 seconds, then prebid generates the following log:
```
ERROR: CMP workflow exceeded timeout threshold. Canceling auction as per consentManagement config.
```
However, the configuration of the page is:
```
consentManagement:
  allowAuctionWithoutConsent: true
  cmpApi: "iab"
  timeout: 8000
```
I would expect the bidRequests to be sent even if we don't answer/provide any consent-string to prebid.

## Steps to reproduce
* Open https://www.rp.pl/?pbjs_debug=true
* Do not answer to the CMP
* Wait for the error log

## Test page
https://www.rp.pl/?pbjs_debug=true

### Expected results
The bidRequests are sent, even without the consent-string, as per the consentMangement config.

### Actual results
The bidRequests are not sent, even without the consent-string.

## Platform details
Desktop, Chrome

**Comment by bretg** [comment]
allowAuctionWithoutConsent was deprecated with TCF2 support.

Sounds like you've discussed with your lawyers that you don't want to enforce Purpose 2. See https://docs.prebid.org/dev-docs/modules/gdprEnforcement.html

```
pbjs.setConfig({
  consentManagement: {
    gdpr: {
      cmpApi: 'iab',   // activates the enforcement module
      defaultGdprScope: true,
      rules: [{        // these are the default values
        purpose: "storage",
        enforcePurpose: true,
        enforceVendor: true
      },{
        purpose: "basicAds",
        enforcePurpose: true,       // this is the equivalent of the long-deprecated allowAuctionWithoutConsent
        enforceVendor: true
      },{
        purpose: "measurement",
        enforcePurpose: true,
        enforceVendor: true
      }]
    }
  }
});
```
