### ISSUE TITLE
Creative IDs

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#627]
It would be great if ALL bidders could support at minimum `creative_id` in the bid response object. We are working with a number of publishers who have users actively report inappropriate ads that slip through the net [porn, bad install ads etc]. AppNexus and few others provide this and we can very quickly check and determine how best to proceed. Rubicon for example have this information in their response, but never pass it back into Prebid.js.

```
{
  "status": "ok",
  "account_id": 13762,
  "site_id": 65512,
  "zone_id": 308542,
  "size_id": 2,
  "tracking": "",
  "inventory": {

  },
  "ads": [
    {
      "status": "ok",
      "impression_id": "c99f7bb6-e8ad-48d3-8ee1-86b749b3b167",
      "size_id": "2",
      "ad_id": "3236011",
      "advertiser": 44087,
      "network": 2307,
      "creative_id": 3266747,
      "type": "script",
      "script": "./removed/.",
      "cpm": 2.993524,
      "campaign_id": 79987,
      "rtb_rule_id": 1362470
    }
  ]
}
```

This is what we have collected on just one of our large publishers.

![screen shot 2016-09-14 at 11 15 59](https://cloud.githubusercontent.com/assets/425262/18508619/c4d78b36-7a6c-11e6-933d-622360f0194e.png)

![screen shot 2016-09-14 at 11 16 10](https://cloud.githubusercontent.com/assets/425262/18508632/d16e0384-7a6c-11e6-81a2-9e9db4fd817c.png)

![screen shot 2016-09-14 at 11 39 17](https://cloud.githubusercontent.com/assets/425262/18509351/0310ac36-7a70-11e6-8d12-bf747fe75333.png)

We have the technology to automatically monitor this in real-time and block the worst offending creatives, but only a small percentage of adapters support the required fields in the bid response.

@mkendall07 - Keen to know your thoughts on this?

**Comment by mkendall07** [comment]
I agree, creative_id would be great to have on all bidders. If you have knowledge of which bidders already have it in the response, would you mind opening PRs for them?

**Comment by cwbeck** [comment]
@mkendall07 PRs? Unfortunately this work will have to come from DSPs/SSPs as their JS contains the creative_id, but does not pass it back to the adapter. In the case of Rubicon it would require them to change: http://ads.rubiconproject.com/header/13762.js - They would need to add a single line:

Adding something like:  ```c.creative_id = e.creative_id``` (which already exists in their own response)

```
n.getRawResponseBySizeId = function(a, b) {
    var c = {};
    if (!k.getConfigValue(0, "configuration.exposeRawResponses", !1))
        return c;
    b = b || k.getConfigValue(0, "accountId");
    var d = n.getCreative(b, a);
    if (d && d.hasOwnProperty("oResponse")) {
        var e = d.oResponse;
        c.advertiser = e.advertiser,
        c.cpm = e.cpm,
        c.dimensions = i.convertSizeIdToDimensions(a),
        c.auction_id = e.impression_id,
        e.hasOwnProperty("deal") && (c.deal = e.deal)
    }
    return c
}
```

Other than AppNexus, Sovrn and AOL already provide this, and there is no work to be done here as it already exists and passed back to the adapter.

<img width="447" alt="screen shot 2016-09-15 at 10 46 56" src="https://cloud.githubusercontent.com/assets/425262/18545865/f6de7c36-7b32-11e6-91fe-88fa7f1154de.png">

<img width="484" alt="screen shot 2016-09-15 at 10 45 45" src="https://cloud.githubusercontent.com/assets/425262/18545870/fa97cdc8-7b32-11e6-8ffb-d2494a53f5a4.png">

**Comment by bretg** [comment]
The creative ID that exists in the Rubicon response is a high level grouping that applies to all bids from a particular DSP. Blocking it would cover all bids from a given DSP, not just an offending creative.

Will back to you on a solution here... I think there may be one.

**Comment by cwbeck** [comment]
Hi @bretg, thanks for your input. That is useful to know, I imagine others might have done something similar. Hopefully there is a solution.

**Comment by BartVB** [comment]
Really good to hear, @bretg! Curious what you'll come up with.

Header bidding is shaking things up quite a bit, would be fantastic if HB would also have an effect on ad quality.

**Comment by bretg** [comment]
Followup: the plan is to address this within Rubicon Project as part of supporting Prebid 1.0. If this is sufficient, may we close this issue?

**Comment by BartVB** [comment]
Sounds good, also because this:

> bid response must define an adapter-specific Creative ID for identification and quality purposes.

Is included in the specifications for Prebid 1.0.0: https://github.com/prebid/Prebid.js/issues/891

**Comment by cwbeck** [comment]
@mkendall07 @protonate @bretg - we have been struggling again with bad ads creeping their way in. These include pops, malware, and other intrusive ads. The most reliable sources for ads are AppNexus and Index Exchange and we have had to drop a number of other bidders as a result of this. The creative id has to be a priority as part of this project in order to weed out malicious ads. I know it's part of the spec moving forwards, but this need to be a fixed requirement in order to have a working bidder. We are aware that some partners like Rubicon use a creative id for a whole DSP - this type of thing will have to be stopped to. A collective solution I feel is required now to spot bad players and eliminate them from the ecosystem as quickly as possible. We have ideas moving forwards, but it all hinges on an accurate creative id.

**Comment by BartVB** [comment]
Same problem here.
We are currently building a solution to deal with bad ads. First step is allowing users to report creatives which don't adhere to our ad policies. Second step will be blocking these creatives in the header bidding because blocking specific advertisers and creatives can be a pretty lengthy (and sometimes fruitless) exercise.

**Comment by bretg** [comment]
@cwbeck - The platform may be able to enforce that a creative_id has to be provided on each bid response, but I'm not sure how Prebid Org is going to be able to tell if the creative ID from each adapter is appropriate -- i.e. is something actionable. Any specific ideas in that area? May be unnecessary - adapters that aren't providing appropriate IDs will be affected one way or another - either their bids will be ignored or the publisher will remove them.

And FYI - Rubicon Project is working on providing that appropriate ID for Prebid 1.0.

**Comment by cwbeck** [comment]
@bretg - It can't be fully enforced, but I would hope anyone not complying would be temporarily dropped. In a perfect world, DSPs/SSPs would share information on potentially malicious ads rather than each network having to take action. We've seen AppNexus take action for example and the same ad, with the same structure / endpoints just appear from another provider.
