### ISSUE TITLE
Unable To build PREBID since LiveIntendSystem modification 4.20

### ISSUE THREAD

**Issue by walterdude** [prebid/Prebid.js#6284]
Hi everyone and thanks for your Help.

## Type of issue
Build Issue

## Description
I build Prebid from a CI configured on my side, with my own prebid.js-modules,
I don't use liveIntenIdSystem module
But since there's two mode for building it, my CI throw an Error on build.

      [16:16:21] Error in plugin 'webpack-stream'
      Message:
          ./modules/liveIntentIdSystem.js
      Module not found: Error: Can't resolve 'live-connect-js/esm/initializer.js' in '/builds/adverline/build-and-deploy/Prebid.js/modules'

## Steps to reproduce
Here is my CI code used to build my Prebid Version :

Deploy Prebid.js:
  stage: deploy-prebid.js
  cache:
    paths:
      - Prebid.js/node_modules/
  script:
    - cd Prebid.js
    - npm install --force
    - npx yarn global add gulp-cli
    - gulp clean
    - gulp build-bundle-prod --modules=../prebid.js-modules.json
    - gulp build-bundle-dev --modules=../prebid.js-modules.json

MY prebid.js-modules.json if needed :

[
  "currency",
  "consentManagement",
  "schain",
  "sizeMappingV2",
  "userId",
  "criteoIdSystem",
  "id5IdSystem",
  "adagioBidAdapter",
  "adyoulikeBidAdapter",
  "appnexusBidAdapter",
  "criteoBidAdapter",
  "freewheel-sspBidAdapter",
  "improvedigitalBidAdapter",
  "ixBidAdapter",
  "justpremiumBidAdapter",
  "piximediaBidAdapter",
  "openxBidAdapter",
  "pubmaticBidAdapter",
  "qwarryBidAdapter",
  "rubiconBidAdapter",
  "smartadserverBidAdapter",
  "spotxBidAdapter",
  "teadsBidAdapter",
  "tripleliftBidAdapter",
  "viBidAdapter"
]

## Platform details
Gitlab CI
Error since Prebid JS 4.20

## Other information
No problem to build whith the same CI code on 4.19 version and before

Thanks for your help

**Comment by wqi1972** [comment]
try run
```
npm ci
```
before build Prebid

**Comment by walterdude** [comment]
It works

Thx for your help.
