### ISSUE TITLE
Districtm / districtmdmx duplicate keys; should throw error

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#6294]
## Type of issue
bug

## Description

Hb_cache_id_districtm and Hb_cache_id_districtmdmx result in the same key when truncated to 20 characters. Dmx should support the DMX alias to their bidder https://github.com/prebid/Prebid.js/blob/master/modules/districtmDMXBidAdapter.js 

Prebid should also error catch duplicate keys such as this on configuration.

**Comment by patmmccann** [comment]
@steve-a-districtm @stevealliance fyi

**Comment by stevealliance** [comment]
@patmmccann, for my understanding this is something that occurs when someone use the appnexus alias and our bidder. 
I will make the change!

**Comment by patmmccann** [comment]
Correct, thanks!

**Comment by ChrisHuie** [comment]
#6253 merge addresses this issue
