### ISSUE TITLE
Bump browserstack versions

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#6301]
## Type of issue
Feature request

## Description
https://github.com/prebid/Prebid.js/blob/master/browsers.json seems quite out of date and also appears to be missing Chrome on Android, which according to https://www.browserstack.com/question/476 is 100% the same as real android. Chrome on iOS may present some issues according to the same page.

**Comment by ChrisHuie** [comment]
I have been diving into testing and need to become more familiar with Browserstack so I can follow-up on this.

**Comment by patmmccann** [comment]
I think changing lines 26 and 30 here https://github.com/prebid/Prebid.js/blob/master/browsers.json solves half the problem. Then we would just need to add a small block for chrome on android.

**Comment by ChrisHuie** [comment]
Scheduled to bring up in meeting to determine current versions and browsers we want to test both functionally and compatiability wise

**Comment by ChrisHuie** [comment]
Confirmed browerstack to most recent and currently latest version already included in browerstack

**Comment by ChrisHuie** [comment]
waiting on merge of #6663 and recent IE test fixes to update other versions browsers

**Comment by ChrisHuie** [comment]
closing with pr #6828
