### ISSUE TITLE
Size problems

### ISSUE THREAD

**Issue by bulle-dog** [prebid/Prebid.js#6307]
## Type of issue
Question

## Description
Hello, I'm testing Prebid on mobile devices. In my AdUnit, I have defined dimensions as follows:

![image](https://user-images.githubusercontent.com/7038473/107803028-5ed25f80-6d62-11eb-94dd-b8b990e25f3a.png)

But, I get ads with different dimensions:

![image](https://user-images.githubusercontent.com/7038473/107803235-9e00b080-6d62-11eb-8f22-12d03c7a67bb.png)

It seems to me that advertisers don't understand that the ad is displayed on a mobile device, maybe that's the problem. Maybe there is a parameter I forgot.

I played my auctions in an iFrame, maybe that's the problem.

This is my first post on Github, please tell me if I don't detail my problem enough or if my way of explaining it is incorrect. 

Thank you for your help.

## Platform details
I use 4.25 version.

**Comment by patmmccann** [comment]
@jbartek25 can you comment on why your adapter might return sizes greater adUnits[].mediaType.banner.sizes

**Comment by jbartek25** [comment]
@bulle-dog did you set the `usePrebidSizes ` parameter as described in the [adapter doc](https://docs.prebid.org/dev-docs/bidders/improvedigital.html)?

**Comment by bulle-dog** [comment]
@patmmccann @jbartek25 thank a lot for your answers. I was just preparing an example when I saw your message. Indeed, setting the usePrebidSizes parameter fixed the problem.

I set my example here if someone has the same problem: http://146.59.243.21/test/

My code (without the prebid dll):

The HTML page :

```
<html>
  <head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<script type="text/javascript" src="testmobile.js"></script>
  </head>
  <body>
    <div id="b48fef10-6f72-4f83-9a91-77c42069bd87">
    
    </div>
  </body>
</html>
```

The javascript code : 

```
/** add your prebid dll here or in html file **/

let adUnits = [];

let adUnit =
{
	code: "b48fef10-6f72-4f83-9a91-77c42069bd87",
	mediaTypes: {
		banner: {
		  sizes: [[300,100],[320,100],[320,50],[300,50]]
		}
	},
	bids: [
	{
		bidder:"onetag",
		params:{
		  pubId:"2a897e3f18e6769"
		}
	},
	{
		bidder:"appnexus",
		params:
		{
			placementId:"20946495"
		}
	},
	{
		bidder:"improvedigital",
		params:
		{
			placementId:"22435558"
		}
	}]
};

adUnits.push(adUnit);

pbjs.que.push(function () {
	pbjs.setConfig({
		debug: true,
		improvedigital: {usePrebidSizes: true}
	});

	pbjs.addAdUnits(adUnits);
	pbjs.requestBids({
		bidsBackHandler: function (bidResponses) {
		var winningBids = [];

		let ad = pbjs.getHighestCpmBids("b48fef10-6f72-4f83-9a91-77c42069bd87");

		if (ad && ad.length > 0) {
			let idIFrame = "b48fef10-6f72-4f83-9a91-77c42069bd87frame";

			let iFrame = "<iframe id='" + idIFrame + "'"
			+ " FRAMEBORDER=\"0\""
			+ " SCROLLING=\"no\""
			+ " MARGINHEIGHT=\"0\""
			+ " MARGINWIDTH=\"0\""
			+ " TOPMARGIN=\"0\""
			+ " LEFTMARGIN=\"0\""
			+ " ALLOWTRANSPARENCY=\"true\""
			+ " WIDTH=\"0\""
			+ " HEIGHT=\"0\">."
			+ " </iframe>"

			document.body.innerHTML += '<div id=b48fef10-6f72-4f83-9a91-77c42069bd87>' + iFrame + '</div>';

			var iframe = document.getElementById(idIFrame);
			var iframeDoc = iframe.contentWindow.document;

			try {
				pbjs.renderAd(iframeDoc, ad[0]['adId']);
			} catch (e) {
				console.log(e);
			}

			winningBids = pbjs.getAllWinningBids();
			console.log(winningBids);
		} 
		else 
		{
		  console.log("No bids");
		};
	},
		timeout: 2000
	});
});
```

However, I see for some time now in my development environment and in my sample an AppNexus error that I havn't before, I have not changed my Prebid version or my code logic, should I create a new post?

![image](https://user-images.githubusercontent.com/7038473/108075624-dce87c00-706a-11eb-8446-e63cceb0bd32.png)

**Comment by wqi1972** [comment]
@bulle-dog , http://146.59.243.21/test/ is not accessible, browser complains about the in secure url.  
The error looks like relates with Appnexus doesn't like the domain 146.59.243.21, please deploy the code to a proper domain, and check if the issue still exists.

**Comment by bulle-dog** [comment]
@wqi1972 thanks for the response, I checked that on other domains in my production environnent and test but I had the same message if I activate the pbjs_debug in my js file. I'll do domain modification on domain 146.59.243.21 tomorrow. Thanks for help.

**Comment by ChrisHuie** [comment]
Sounds like this issue self resolved. Please refer to the issue comments for further explanation
