### ISSUE TITLE
Prebid getConfig subscribe doesn't function as expected

### ISSUE THREAD

**Issue by davinsoftware** [prebid/Prebid.js#6335]
## Type of issue
Bug

## Description
Prebid API docs say you can attach a subscribe function to getConfig: https://docs.prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.getConfig

But this subscribe function doesn't get called for all types of config changes, only for some (it appears?). Is the implementation buggy?

## Steps to reproduce
- Load cnn.com while VPN'd to UK or other EU country that has consent management.
- Attach a subscribe function to pbjs.getConfig before consent management has loaded: 

		pbjs.getConfig((config) => {
			console.log('got config', config);
		}); 
		pbjs.getConfig(); // see what current config is. 

## Test page
Sorry I don't have one - is there a canonical pbjs integration example on jsfiddle that uses consentManagement that I could start from?

### Expected results
Expect getConfig subscription to log a notice when 'consentManagement' section is added to the pbjs config, but this notification never happens.  Other config sections like 'adpod' do notify, but not all. 

### Actual results
got config {adpod: {…}}
Prebid INFO: consentManagement module has been activated...

## Platform details
Prebid INFO: Prebid.js v3.13.0-pre loaded

**Comment by ChrisHuie** [comment]
@ChrisHuie to check whether this is related to listening or specific to consent management listening

**Comment by robertrmartinez** [comment]
Hi @davinsoftware 

You are using an old prebid version, but I am assuming it should still work.

The "Subscribe" functionality expects you to pass it a certain config to listen for.

For example, if you want to listen to anytime setconfig is called with consentManagement, you would execute the following code:

```js
pbjs.getConfig('consentManagement', config => console.log('The config is: ', config));
```

Doing this in my test page I can see the following:

![image](https://user-images.githubusercontent.com/13972794/119369167-b8eb9680-bc68-11eb-8581-5c3581bc65b0.png)


Let me know if this resolves your question.

**Comment by robertrmartinez** [comment]
This example will only run your callback function if `consentManagement` was included in the setconfig call.

**Comment by robertrmartinez** [comment]
@davinsoftware 

Going to close this.

Please let me know if you have anymore questions.
