### ISSUE TITLE
Collision of Permanent Aliases vs Pub-Specific Aliases

### ISSUE THREAD

**Issue by r-schweitzer** [prebid/Prebid.js#6336]
## Type of issue
Bug and Feature Question

## Description
Wanted to inquire about the purpose of https://github.com/prebid/Prebid.js/pull/6150 as it affects my original approach taken to fix some bugs I found in Prebid. Firstly, the bugs I found were in modules/prebidServerBidAdapter/index.js. Two things seemed to be occurring. 

When I attempted to alias a bidder in the s2s config (eg. alias pubm_ss: "pubmatic") and I’m also running districtM, which is aliased in the appnexus bidder, alias pubm_ss gets overwritten and only districtM is then aliased.

The next issue was when I attempted to use bidAdjustmentFactors. Bidadjustment factors are set in the s2sConfig and are set on all adunits regardless of whether that bidder is actually set up for the adunit but aliasing for s2s is done on the adunit level. This causes Prebid Server to throw the following error when you do not have an aliased bidder on all adunits: “**Invalid request format: request.ext.prebid.bidadjustmentfactors.tripleliftvideo is not a known bidder or alias**”. This is the fix I intended https://github.com/prebid/Prebid.js/tree/bugfix/s2saliasbug

I had questions as to whether the anti-alias feature is really needed. Unless I’m misunderstanding something it seems like we could just instead remove the alias mediafuse from the adapter and if anyone needs to alias it they can add it to aliases like any other alias. If we do need this anti-alias feature I think another easier way to accomplish this would be to add a s2sConfig options alias: [‘mediafuse’]. In index.js we could easily check this array and filter out the alias. And if we want to keep this feature I would just need to  filter bidadjustment factors by adunit and make sure not to send it for adunits where aliases don’t exist but I wanted to open this issue before taking this route to come up with the best path moving forward.

## Steps to reproduce

1. Set up a page with two aliased bidders, one is a built in alias (districtM aliased in appnexus) and the other is aliased using pbjs.aliasBidder function. If both are in the same s2s request only districtM will be aliased.
2. For the second bug only call an aliased bidder on one adunit and set bidadjustment factors which will set for all.

## Platform details
Prebid Feature https://github.com/prebid/Prebid.js/pull/6150 was released in 4.23.0
Bugs have prob always existed.

**Comment by bretg** [comment]
Thanks for reporting this @r-schweitzer . 

The first item is a PBJS bug, but I think the second item may be related to the first.

1) The collision of Permanent Aliases vs Pub-Specific Aliases. This is a PBJS bug and your code fix would be most welcome.
2) Unknown bidders in ext.prebid.bidadjustmentfactors: there is a minor PBS bug in this area, possibly just PBS-Java. But I think your case may be different. (?)

PBS-Java validates that each BIDDER in ext.prebid.bidadjustmentfactors.BIDDER must be recognized as one of:

a) a standalone bidder
b) configured as a hard-coded alias in the YAML file  // this is the current scenario PBS-Java is missing
c) defined as an alias in ext.prebid.aliases

In this case, `tripleliftvideo` is not one of a) or b), so needs to be c).

Once the "Collision of Permanent Aliases vs Pub-Specific Aliases" bug is solved then the pbsBidAdapter should be passing the appropriate mapping on ext.prebid.aliases and the bidadjustmentfactors error will go away.

As for the skipPbsAlias feature... went back through and found this is just kind of a weird edge case. MediaFuse is an alias of Adtelligent on the client side, but has its own server-side adapter. Another possible fix for #6150 would have been to make an update on the server side -- ignore aliases when the bidder is standalone. But they chose to fix it in PBJS instead. I'm open to the idea that we open a PBS issue to discuss the server-side behavior. And once both PBS-Java and PBS-Go adhere to it, then we could drop skipPbsAlias -- mediafuse is the only one using this workaround.

**Comment by GeneGenie** [comment]
I'd like to step into, MediaFuse isn't  "standalone adapter in PBS" it is an alias to Adtelligent PBS bidder adapter, but PBS isn't fully "alias friendly"

**Comment by patmmccann** [comment]
fyi #6379 only fixes the js half of this issue, the bid adjustment factor issue seems to persist

**Comment by bretg** [comment]
PBS-Java v 1.61 fixed the bidadjustmentfactor issue. I tried various test requests to PBS-Go and don't see the problem there.

@r-schweitzer - please confirm you see the same results and then we can close this issue,

**Comment by bretg** [comment]
Working more with Ryan on this.

1) The page or stored request entry defines a static ext.prebid.bidadjustmentfactors that contains all bidders. The s2sConfig is global to all auctions, even though the bidder set for banner and video auctions may be quite different.

e.g. 
```
pbjs.aliasBidder('bidderA','aliasA');

pbjs.setConfig({
    s2sConfig: {
        bidders: ['aliasA', 'bidderB'],
        extPrebid: {
            bidadjustmentfactors: { 
                'aliasA': 0.9,
                'bidderB': 0.9
            }
        }
    }
})
```
The  pbsBidAdapter automatically adds ext.prebid.aliases.aliasA, but only when that bidder is present on an adunit.

2) When an auction occurs that doesn't include aliasA on the adunit, the request to PBS goes out with  
the bidadjustmentfactor for aliasA but not the alias.



My proposed solution is to update the pbsBidAdapter to be more careful about which ext.prebid.aliases are added:

1) add all aliases defined by pbjs.aliasBidder... these are ones that the publisher has explicitly defined.
2) add hard-coded aliases for all aliases defined in the adunits except those that are flagged skipPbsAliasing

**Comment by patmmccann** [comment]
@r-schweitzer can we close this out? it appears you opened two issues as one. As of today, I know we succeeded in  upgrading, so do we have a change to commit back or has this issue (these issues) gone away?

**Comment by r-schweitzer** [comment]
@patmmccann I think we can close this

**Comment by patmmccann** [comment]
thanks so much!
