### ISSUE TITLE
Impression Discrepancy with Prebid 12

### ISSUE THREAD

**Issue by klinde-inuvo** [prebid/Prebid.js#634]
We implemented version 12 on 8/29. Since then we have seen a dramatic increase in the difference in impressions between DFP and several of our bidders. For one of our bidders it went from <5% to >30%. Interestingly, impression volume between DFP and Appnexus remained the same, ~5-6%.  Has anyone seen anything similar?

**Comment by mkendall07** [comment]
Hi @klinde-inuvo 
I haven't heard of this yet. Can you give some more details? Which version where you running previously? Any customizations? Are the discrepancies consistent? Which bidders are showing the highest % for you?

**Comment by klinde-inuvo** [comment]
Hi Matt,
Thanks for reaching out. I have attached a spreadsheet of our bidders that we had onboard prior to upgrading v12. We were running v8 prior to the update. Our developer thinks it was 8.1.1. We didn’t do any customization other than adding the standard GA events.
The discrepancies are fairly consistent across Sovrn, Pulsepoint and AOL. You can see the increase in discrepancy that started on 8/29 when we upgraded. Appnexus and bRT were not affected. We also added Sonobi on 8/29. Sonobi has had a <10% difference in impressions since coming on board. Let me know if you need any additional information.

Regards

**Comment by mkendall07** [comment]
@klinde-inuvo 
Sorry didn't get the spreadsheet. Can you email it to me (check my profile for email). Thanks

**Comment by protonate** [comment]
I've had a chance to analyze the spreadsheet and notice that the adapters with increased discrepancies starting with version 12 were not matching bid request / response IDs as recommended in #509. At least two (AOL and Sovrn) now are doing so in master, and Sovrn is also doing so as of current release Prebid 0.13.1. I recommend upgrading to version 0.13.1 and then as soon as possible moving to the upcoming 0.14.0 release. You should see these discrepancies fall off. Note that Pulsepoint is not yet implementing #509.

Closing as answered. Please reopen with any new info.

**Comment by protonate** [comment]
Update: with #706 Pulsepoint is syncing bid request / response IDs.

**Comment by headerbidding** [comment]
I also experience a discrepancy of >  20% with Sonobi.
Sonobi tech support says "There isn't anything my team can do for you especially since we are implemented via another wrapper (prebid). "

**Comment by mkendall07** [comment]
@headerbidding please open a new ticket with details of your setup.
