### ISSUE TITLE
how to add dfpAdserverVideo to the prebidJs build

### ISSUE THREAD

**Issue by nem95** [prebid/Prebid.js#6340]
Hello 

## Type of issue
Question

## Description
I would like to build the prebid js with some changes on one of the adaptors and I want to include the dfpAdserverVideo module in it.

## Steps to reproduce
I've tried to build ith this command : 
```bash
gulp build --modules=qwarryBidAdapter,dfpAdServerVideo
```
but I have an error

```prebid_buil_naim.js:1 Uncaught ReferenceError: pbjsChunk is not defined```

## Platform details

latest prebidjs version, node version 14.15.5

Thanks

**Comment by bretg** [comment]
Works for me. Did you update your environment with `npm install`?

Looks like you have a build system on top? prebid_buil_naim.js isn't one of ours and pbjsChunk isn't a thing either.

**Comment by nem95** [comment]
Hello, It works well finally, I was using the adapter.js instead of the prebid file.
