### ISSUE TITLE
Type checking on FirstPartyData

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#6346]
## Type of issue
Feature request

## Description
As mentioned on https://docs.prebid.org/features/firstPartyData.html#how-bid-adapters-should-read-first-party-data 
```
The Prebid First Party Data JSON structure reflects the OpenRTB standard. 
Arbitrary values should go in fpd.context.data or fpd.user.data. 
Fields that are meant to be standard OpenRTB 2.5 values should be in fpd.context or fpd.user. 
Specfically, the standard values for site are: name, domain, cat, sectioncat, pagecat, page, ref, search, keywords. 
For user these are: yob, gender, keywords.
```
FPD follows ORTB spec. Many bidders will like to add the type-checking logic on FPD before passing it to server side.
Rather than bidders implementing type-checking logic on their own can prebid-core add the same and eliminate type-mismatching fields before passing to bidders?

Also the doc suggests to put Arbitrary values in `data` like `fpd.context.data or fpd.user.data`, it will be great if prebid-core puts these fields in respective ext blocks like `fpd.context.data.customKey` is moved to `fpd.context.ext.customKey`, same for `fpd.user.data`.

Better if we standardize it before mass adoption.

**Comment by bretg** [comment]
@pm-harshad-mane - this will be covered by the soon-to-be-developed First Party Data Module. https://github.com/prebid/Prebid.js/issues/6099

We cannot afford to add non-essential bytes to core PBJS so type checking will be in a module for pubs who utilize FPD. Bidder endpoints will have to check anyhow, so pubs that don't implement the FPD module will get failures when data types are wrong.
