### ISSUE TITLE
Question - $$REPO_AND_VERSION$$ is not defined

### ISSUE THREAD

**Issue by DiogoBatista** [prebid/Prebid.js#6347]
## Type of issue
Question

## Description
I'm having some issues with the pubmatic adapter. We already have the pubmatic account and everything is configured properly by the account manager.

My issue is with the prebid.js v4.22.0. When I try to use it using the pubmatic adapter it just throws the following error:
```
$$REPO_AND_VERSION$$ is not defined
```

My suspicion is that something is wrong in my configuration with the build process.
Im using the rails webpacker `https://github.com/rails/webpacker`

Is this a known issue? Can I get some help on this? 

## Platform details
v4.22.0
any browser

**Comment by ChrisHuie** [comment]
I'm not too familiar with the Webpacker process of working with rails and JavaScript. However, could this possibly be some kind of collision issue with webpack in prebid and webpack in webpacker?

**Comment by DiogoBatista** [comment]
hello @ChrisHuie thank you for your answer, yeah I got pass that issue with configuring the wepacker this way


```
environment.loaders.append('prebid', {
  test: /.js$/,
  include: new RegExp(`\\${path.sep}prebid\\.js`),
  use: {
    loader: 'babel-loader',
    // presets and plugins for Prebid.js must be manually specified separate from your other babel rule.
    // this can be accomplished by requiring prebid's .babelrc.js file (requires Babel 7 and Node v8.9.0+)
    options: require('prebid.js/.babelrc.js'),
  },
});
```

This fixed for me but Im having issues with an actual build process, seeing a lot this errors 


```
TS2300: Duplicate identifier 'LibraryManagedAttributes'.
```
```
TS2320: Interface 'ElementClass' cannot simultaneously extend types 'Component<any, {}, any>' and 'Component<any, {}, any>'.
      Named property 'props' of types 'Component<any, {}, any>' and 'Component<any, {}, any>' are not identical.
```

Once I install prebid.js v4.22.2 I have this typing problems and many others... 

Anyone knows what this could be? Im using react and this appears to collide with react typings

**Comment by DiogoBatista** [comment]
I fixed my issue by setting 

```
 "resolutions": {
  "@types/react": "17.0.0"
}
```

Going to close this :) thanks for your help
