### ISSUE TITLE
CDN for adapters

### ISSUE THREAD

**Issue by GustavoGomesRibeiro** [prebid/Prebid.js#6349]
## Type of issue
Question

## Description

Guys, How can I get an CDN for my custom adapters?

## Platform details
v4.22
browser

**Comment by bretg** [comment]
Sorry, what does this mean @GustavoGomesRibeiro ? Prebid.org doesn't support adapters that aren't open source. It's certainly possible to create a build system where you download Prebid.js, download proprietary adapters, and run `gulp build` to mix the two. In fact, I believe the old PBJS packager at https://github.com/prebid/Prebid.js-packager even supported this scenario.

However, you're on your own when it comes to picking a CDN vendor to host your Prebid.js package.

**Comment by ChrisHuie** [comment]
@GustavoGomesRibeiro did Bret's answer help you on this?

**Comment by GustavoGomesRibeiro** [comment]
@ChrisHuie yes answered. I'm sorry for not replying.
