### ISSUE TITLE
"pbjs is not defined" error from appnexus adapter on recent commits

### ISSUE THREAD

**Issue by brondsem** [prebid/Prebid.js#635]
Starting with commit 6931d45, when the appnexus adapter is enabled, this error is thrown: `Uncaught ReferenceError: pbjs is not defined`

It's on this line: `pbjs.handleAnCB = function (jptResponseObj) {`

And the previous part of the call stack is: 
```
	exports.createNew = function () {
	  return new AppNexusAdapter();
	};
```

**Comment by mkendall07** [comment]
I'm not seeing this error. Do you have more details you can provide to replicate the issue?

**Comment by mkendall07** [comment]
Also, the commit referenced doesn't actually touch `appnexus.js` file. Is that the adapter you are working with or are you using `appnexusAst.js` ?

**Comment by brondsem** [comment]
Yea, we are using appnexus (and brealtime).  I don't get why the commit would cause the error either.  We are running with several adapters and a customized ga.js.  When I have a chance, I will simplify the build configuration to narrow things down, and will post an update or jsfiddle

**Comment by brondsem** [comment]
The error occurs with just the appnexus adapter included and nothing else.  Or with the standard default set of adapters, in which case you get a similar error for aardvark: `Uncaught TypeError: Cannot set property 'aardvarkResponse' of undefined`

The key is if have `var pbjs = pbjs || {};` before prebid.js or not.  If you do, that protects from the error (although I wonder even if you have that, do the callbacks added to pbjs work if it pbjs object isn't the right one yet?).  In our case we put our prebid.js script tag before everything else on the page so it can start being loaded as soon as possible.

**Comment by mkendall07** [comment]
@brondsem 
Thanks for the additional info. We actually do have a line that should protect against this:
https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L9

It may be possible that webpack is re-ordering the compiled JS so that adapters are parsed before prebid.js.

**Comment by mkendall07** [comment]
I figured this out, the global definition needs to come before the imports in prebid.js. I'll add a PR for fix. Thanks!

(this happened because of nested dependencies in `video.js` - which ends up loading adapters first)
