### ISSUE TITLE
Video playing for 1 sec, then cuts/ goes to next video

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#6372]
this seems to have started happening in last couple of weeks,  If i have 3 pre-rolls,  I'm seeing the first pre load, play for about 1-2 secs then "cut" and the next 2 of 3 pre roll plays, usually it plays ok if a 15, 30 sec video.   I think this might have something to do with the DFP setting of "duration" X seconds.  I have 1 second set and that seems to be what happens on the 1st pre-roll (1 sec , cut)

How can this be "got around"/ fixed , if this is the case, as most are going to have a min e.g 5, max e.g 30 set, so you can't ever know what the video "duration" is going to be.  1 sec was working fine but its def "cutting" more now on that 1st pre-roll

![Google_Ad_Manager_-_Line_items](https://user-images.githubusercontent.com/8503167/109528526-ac620280-7aac-11eb-8d31-d6b6f1bc3ee3.png)

**Comment by ChrisHuie** [comment]
@spormeon is this still a unique issue you are dealing with or is this related to another open issue

**Comment by spormeon** [comment]
i believe its unique, as of now i've not been able to track down any more info on why it might be doing it etc but its still doing it

**Comment by patmmccann** [comment]
Are you using ad podding in gam?

**Comment by spormeon** [comment]
in effect no, we are building a vmap on the fly

**Comment by patmmccann** [comment]
We have confirmed at least one other user case where the documentation to set this to one should change.  Hopefully this is a docs fix. Did you change anything or do you suspect gam did?

**Comment by spormeon** [comment]
I haven't changed anything, I just have the duration set at 1 for the prebid video line items

**Comment by spormeon** [comment]
actually, another observation.  Amazon actually has this set at 5, when my "amazon" slots in their Ui are set at 5-30 secs

**Comment by spormeon** [comment]
i'm also not sure if this might be having an effect.  I'm pretty sure this has changed to now be 

(Video and audio only) "**Max duration (seconds)" is a required setting** for video and audio that is used for forecasting optimized pods. This duration is also used to enforce the maximum duration of video or audio that buyers can upload, **regardless of request type.** If buyers upload video or audio that exceed this maximum, ad serving could fail.

I think it used to only be relevant for "forecasting", its always been set to  (zero)

![Google_Ad_Manager_-_Line_items-2](https://user-images.githubusercontent.com/8503167/113483693-ae005b00-949c-11eb-809b-f0b21239c0d9.png)

**Comment by spormeon** [comment]
UPDATE, we have changed the duration to 5 secs and almost instantly there seems to be less of this 1-2 secs and then cutting, how this plays out though with different duration videos coming through, no clue at present

**Comment by patmmccann** [comment]
does it go 5 seconds and cut?

**Comment by ChrisHuie** [comment]
@mike-chowla this is an item for the video task force. Can you please review

**Comment by spormeon** [comment]
it actually seems to be better at "not cutting" now we moved it to 5 secs, when the first vid is 10-15 secs, if its a longer first vid of say 30, it still does it sometimes

**Comment by patmmccann** [comment]
Gam product team is aware of this issue, but still has not engaged. We are now recommending the maxduration that you run in the slot.

**Comment by spormeon** [comment]
@patmmccann Its not really in their interest to, is it, they have had a "looK' and decided want/ don't want, if it screws up anything else, oh well its not ours?

**Comment by bretg** [comment]
Docs.prebid.org updated. https://docs.prebid.org/adops/setting-up-prebid-video-in-dfp.html

**Comment by bretg** [comment]
Closing this issue as a docs change. Will leave it up to the video taskforce (@mike-chowla) as to whether we should announce this change in an email or blog post.
