### ISSUE TITLE
Pre-defined native types: Image not replaced before adapters are called

### ISSUE THREAD

**Issue by guiann** [prebid/Prebid.js#6389]
Hello everyone, 

Our bidder supports native ads for a few weeks now and we can  see some native bid format with 

```
native: {
    type: "image"
}
```

I would expect this native configuration to be replaced by the full format config specified in:
[pre-defined-native-types](https://docs.prebid.org/dev-docs/show-native-ads.html#pre-defined-native-types)

```
{
    image: { required: true },
    title: { required: true },
    sponsoredBy: { required: true },
    clickUrl: { required: true },
    body: { required: false },
    icon: { required: false },
    cta: { required: false }
}
```

Is it expected that bidder adapters receive the short hand format?
That would mean every bidder has to expand every pre-defined types. Duplicating the same code for every bidder and breaking futur integrations when new pre-formated types will be added.

**Comment by guiann** [comment]
Our publisher is sending this config:
```
native: {
    size: [1, 1],
    type: "image"
}
```
Can the useless 'size' field be the source of this issue? 
Were trying to make them remove it...

**Comment by gglas** [comment]
@aleksatr @robertrmartinez We discussed this on issue review today, and this seems like a good place to introduce the concept of prebid Native templates with predefined requirements that are then accessed via Shorthand.  Aleksa I tagged you until we can add Chris N to prebid, I think he'd find this interesting.

**Comment by patmmccann** [comment]
@guiann this expansion of the shorthand inside of core seems like a great utils for all adapters; is there any chance you could take a stab at it?

**Comment by guiann** [comment]
No I've no time to handle it sorry.

**Comment by patmmccann** [comment]
Seems to
