### ISSUE TITLE
How do you set a key/value to be sent to GAM based on an auction result in Prebid.js ? 

### ISSUE THREAD

**Issue by pnhegde** [prebid/Prebid.js#6397]
## Type of issue
Question

## Description
Is it possible to capture `skipped` status from `floorData` and send it to GAM after every `auctionEnd` event? 

Thanks

**Comment by patmmccann** [comment]
you should be able to do it like this https://github.com/prebid/Prebid.js/blob/24114d136537ff9f2f162f85adc45ef2e4a41433/modules/rubiconAnalyticsAdapter.js#L250 and set gam targeting, yeah. tagging @robertrmartinez for thoughts

**Comment by bretg** [comment]
Really this request is "How can I send a random thing to GAM?"

See https://docs.prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.bidderSettings

```
pbjs.bidderSettings = {
    standard: {
        adserverTargeting: [{
            key: "random-thing",
            val: function(bidResponse) {
                ... grab arbitrary stuff ...
                return desired-value;
            }
```
Once you head down this path though, you have to take responsibility for all targeting vars. 

```
Note that once standard.adserverTargeting is specified, you’ll need to fully manage the
targeting – the default hb_ targeting variables will not be added.
```

Does this help?

**Comment by pnhegde** [comment]
@bretg Thanks. What happens if I set  `googletag.pubads().setTargeting("key", "value");  ` ? I can see the key value being sent in the `googletag.openConsole();` but not sure if it's the right approach.

**Comment by gglas** [comment]
Adding @ChrisHuie who will collaborate a code example with Bret/team
