### ISSUE TITLE
Geoedge Realtime module error when bundling on download site

### ISSUE THREAD

**Issue by terrapop** [prebid/Prebid.js#6406]
## Type of issue
Bug

## Description
When bundling the Geoedge Realtime module at https://docs.prebid.org/download.html you get the following error in the downloaded file:

{"error":"Prebid file not built properly","requestId":"16a3eb22-8039-441d-8b45-5d2c0285d367"}

## Steps to reproduce
Go to https://docs.prebid.org/download.html

Bundle anything with the Geoedge Realtime module, look at the downloaded file.

## Test page
nA

### Expected results
No error

### Actual results
Error

## Platform details
nA

## Other information
nA

**Comment by ChrisHuie** [comment]
@terrapop I tried a few versions and ran into the same problems with just the AppNexus Bid Adapter and Geoedge. I was able to build the combo from the source but when I tried to deploy their example page I was getting errors. So not entirely sure if this is inside Geoedge or the download page logic/firebase cdn

**Comment by terrapop** [comment]
Unfortunately, I have no idea either and don't know if this is something to raise here or somewhere else. Anyways, it does not work on the official prebid download page. Thus, should be taken care of, or removed from the page.

**Comment by bretg** [comment]
This was an issue with the download page affecting all Real Time Data modules.  Fixed with https://github.com/prebid/prebid.github.io/pull/2785
