### ISSUE TITLE
Getting multiple winning bids with same auctionId and adUnitCode from an analytics adapter's bidWon event.  

### ISSUE THREAD

**Issue by pnhegde** [prebid/Prebid.js#6411]
## Type of issue
Question 

## Description
We're receiving several winning bids with same auctionId, same adUnit but different cpm and different bidders. Status of all these winning bids are `rendered` with a message `Bid available`.    How is it possible to have same auction_id and same adUnitCode for more than one winning bids? 
Note: We're collecting the winning bids from our analytics adapter  - `pubxaiAnalyticsAdapter` https://github.com/prebid/Prebid.js/blob/master/modules/pubxaiAnalyticsAdapter.js 

Thanks

**Comment by bretg** [comment]
This can happen if the publisher has `useBidCache` turned on. https://docs.prebid.org/dev-docs/faq.html#does-prebidjs-cache-bids

Does that fit your scenario?

**Comment by pnhegde** [comment]
@bretg Yes, it looks like the publisher is using `useBidCache`. How do you suggest we can handle it in the analytics adapter ? Should we compare the cpm value all the winning bids which share same auctionId  to determine the actual winning bid?

**Comment by bretg** [comment]
> determine the actual winning bid

They both won!

1) Initial auction of AdUnit A, bid from BidderA wins
2) Refresh auction of AdUnit A, cached bid from BidderB wins

If you need to find out which instance of an auction a given bid was in, you may be able to figure out from data in the bidresponse or the adunit:

bidresponse.requestTimestamp: 1616595980878
bidresponse.responseTimestamp: 1616595981028

There's also a 'bidRequestsCount' stat, but I didn't get time to dig into how to get it from the adunit bidrequest.

**Comment by gglas** [comment]
@pnhegde did that answer your question?  Could we close this issue?

**Comment by pnhegde** [comment]
@gglas Yes, we can close this issue now. Thanks a lot everyone !
