### ISSUE TITLE
Prebid.js sends wrong gdpr flags to prebid-server

### ISSUE THREAD

**Issue by rsnigel** [prebid/Prebid.js#6414]
Prebid.js is interpreting `__tcfapi` incorrect and sending wrong flags to prebid-server when GDPR does not apply.

When GDPR applies, the handling is correct.
If GDPR does not apply, https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter/index.js#L192 checks for `if (typeof gdprConsent.consentString !== 'undefined')` which is incorrect.

A certified IAB CMP does not need to return a valid `tcString` outside of GDPR. Typical CMP's only return `gdprApplies = false`.

Example of typical CMP response:
```javascript
__tcfapi('getTCData', 2, (tcData, success) => { console.log(success); console.log(tcData); });

cmpId: 3
cmpVersion: 1
gdprApplies: false
tcfPolicyVersion: 2
```

If there is a `__tcfapi` available, the line `payload.gdpr = (gdprConsent.gdprApplies) ? 1 : 0;` is enough and the if should be removed.

What is the result of this bug. Prebid-server does not get a gdpr=0 flag and if `usersync_if_ambiguous=false`, prebid-server rejects all user syncs which breaks prebid-server completely outside of gdpr. The workaround is to set `usersync_if_ambiguous=true` which is questionable from a legal point of view.

**Comment by bretg** [comment]
Nice analysis @rsnigel - care to open a PR to fix?

**Comment by ChrisHuie** [comment]
closing with merge of #6429

**Comment by patmmccann** [comment]
of note: usersync if ambiguous default is changing with https://github.com/prebid/prebid-server/pull/1786

**Comment by hhhjort** [comment]
prebid/prebid-server#1786 is now on hold as the legality is being called into question. One one hand, all publishers impacted by GDPR should be sending GDPR signals by now, and seems that small publishers with no EU presence should not be forced to send gdpr signals to confirm that the gdpr does not apply. On the other hand, not knowing if a user is in the EU does not absolve us from following the GDPR if the user actually is in the EU.
