### ISSUE TITLE
Add mergeConfig functions for updating ortb2 data

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#6425]
## Type of issue
enhancement

## Description
There are several parties that might want to add to the new First Party Data structure. Currently, Real Time Data modules need to getConfig({ortb2}), modify it, then setConfig({ortb2}). This is awkward.

This issue proposes two convenience functions to make it easier for RTD modules (and page code) to manage important data structures. So while the main use case is `ortb2`, the proposal is that these new functions would apply to all setConfig entries.

1) mergeConfig({CONFIG})

```
pbjs.mergeConfig({
  ortb2: {
    user: {
      data: [
         {
          "name": "www.dataprovider1.com",
          "ext": { "taxonomyname": "iab_audience_taxonomy" },
          "segment": [{ "id": "687" }, { "id": "123" }]
         }
      ]
    }
  }
});
```
This command would add the specified ortb2.user.data array element to the existing ortb2 data structure or create if it doesn't already exist.

Requirements:
1. mergeConfig should create the object if it doesn't already exist
2. mergeConfig should add entries to the end of the following arrays: ortb2.site.keywords, ortb2.user.keywords, ortb2.user.data and ortb2.site.content.data arrays rather than overwriting them. The function does not have to check for duplicate array entries. [Are there other arrays we want to add to rather than overwriting?]
3. Otherwise mergeConfig should give precedence to the new values over existing values. [I believe this is the current convention given regular JavaScript Object.assign() semantics]

2) mergeBidderConfig({bidder: [BIDDERS], config: CONFIG})

```
pbjs.mergeBidderConfig({
  bidders: ["bidderA", "bidderB"],
  config: {
    ortb2: {
      user: {
        data: [
           {
            "name": "www.dataprovider1.com",
            "ext": { "taxonomyname": "iab_audience_taxonomy" },
            "segment": [{ "id": "687" }, { "id": "123" }]
           }
        ]
      }
    }
  }
});
```
This command would add the specified ortb2.user.data array element to the existing ortb2 data structure for bidderA and bidderB or create if it doesn't already exist.

Same requirements as `mergeConfig` noted above.

**Comment by ncolletti** [comment]
Would the intention be to merge the rest of the config properties as well outside of ortb? 

`mergeConfig({
    'ortb2': { 'site': { 'keywords': 'a,b' }},
    'deviceAccess': false
})`

In the example above, the ortb2 obj would follow the logic proposed but any additional properties would merge/overwrite to existing config obj values.

I started work on this and should be able to submit a PR for review by end of week.

**Comment by gglas** [comment]
@bretg is there a connected PR for this?  Seems fine to me

**Comment by bretg** [comment]
@patmmccann - the proposal is that this is a new utils function generally available to everyone.

@gglas - Magnite jira ticket open. There will be PR soon
