### ISSUE TITLE
Sync pubcommonid or other ids to ad server

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#6430]
## Type of issue
Feature Request

## Description
Recently at https://blog.google/products/admanager/helping-publishers-thrive-todays-privacy-environment/ Google announced their intention to "enable publishers to further increase their inventory’s value, [by] working to help them expand the use of their PPIDs to more programmatic campaign types, including the Open Auction"

The ppid is described at https://support.google.com/admanager/answer/2880055?hl=en and has historically been used for "frequency capping, audience segmentation and targeting, sequential ad rotation" and analysis on the data transfer files, in which they appear. 

Setting the ppid is rather straightforward, eg `       googletag.pubads().setPublisherProvidedId('12JD92JD8078S8J29SDOAKC0EF230337');
`

I would like the User Id module to sync the pubcommonid or the https://github.com/prebid/Prebid.js/blob/master/modules/pubProvidedIdSystem.js id [and potentially other ids] to gam ppid if the publisher has designated it would like this in config.  The pubcommonid feels like a natural choice for many publishers, as it is simply the id in the first party publisher cookie.

**Comment by dmdabbs** [comment]
Agree, seems like a Good Thing(tm). Would you imagine some site-controlled preference ranking of which to send, or initially more straightforward conf for which of the supported input IDs to send, if present, to PPID?

It is singular, "an identifier."

>This identifier is used alongside any other identifiers that are available to Google Ad Manager, such as cookies. The identifier must be hashed, anonymous, and must not contain any personal information, third-party identifiers or device IDs.

**Comment by smenzer** [comment]
I agree this should be a feature of the userid module where the publisher can select which ID they'd like to use as the google PPID. And as @dmdabbs said, this is only ONE id, so pubs can't just choose all. 

perhaps something in the `userSync` config with a new option `ppidUserIdModule: 'abcId'` where `abcId` is the same value that would be passed in the `userIds[].name` field in the user id module config.

**Comment by muuki88** [comment]
How will id providers ensure the requirements that google seems to have?

> This identifier is used alongside any other identifiers that are available to Google Ad Manager, such as cookies. The identifier must be hashed, anonymous, and must not contain any personal information, third-party identifiers or device IDs.

From [Google PPID docs|https://support.google.com/admanager/answer/2880055?hl=en]

**Comment by patmmccann** [comment]
> How will id providers ensure the requirements that google seems to have?
> 
> > This identifier is used alongside any other identifiers that are available to Google Ad Manager, such as cookies. The identifier must be hashed, anonymous, and must not contain any personal information, third-party identifiers or device IDs.
> 
> From [Google PPID docs|https://support.google.com/admanager/answer/2880055?hl=en]

It  is up to the publisher to choose an id that meets these requirements, not the id provider. Perhaps we should just allow id providers to add to their doc "meets ppid spec" or something. The pubcommonid appears to meet it from my perspective.

**Comment by robertrmartinez** [comment]
Addressed https://github.com/prebid/Prebid.js/pull/7681
