### ISSUE TITLE
pbjs.enableSendAllBids only returns the winning bid

### ISSUE THREAD

**Issue by mlapeyre3** [prebid/Prebid.js#6431]
## Type of issue
Non expected behavior

## Description
Hello there, I am trying to understand why not all bids are sent to Google Ad Manager whereas `pbjs.getConfig('_sendAllBids') => true`. I did a very simple test page with
[programmatic_guaranteed_prebid.zip](https://github.com/prebid/Prebid.js/files/6158380/programmatic_guaranteed_prebid.zip) and it works properly, but in the production page, I only see the targeting key for the winning bid being sent.

## Steps to reproduce
See the test page below.

## Test page
* https://www.lemonde.fr/idees/article/2021/03/17/l-inquietante-fuite-en-avant-du-royaume-uni_6073448_3232.html
* Run `glmaw.staging(true);` and reload the page
* Run `googletag.openConsole();` to see what the Google Tag Manager is doing

### Expected results
* I have two bids from Criteo and Teads bidders on the adunit "inread-2" which is attached to the Google adunit /128139881/LM_lemonde/idees/idees/article/inread
* `pbjs.getConfig('_sendAllBids') => true` so I expect these two bids to be sent to Google (with the key hb_bidder=teads but also hb_bidder_teads=teads and hb_bidder_criteo=criteo [and all others](https://docs.prebid.org/dev-docs/publisher-api-reference.html#setConfig-Send-All-Bids) ...)

### Actual results
* Only the targeting key related to the winning bid (the one from Teads) is set. I don't see the keys related to Criteo
![Uploading image.png…]()
* It can be easily seen using `googletag.openConsole();` and looking for "Set targeting attribute hb_bidder_" in the console

## Platform details
Prebid.js v4.13.0 on Chrome

**Comment by lambdarho** [comment]
Hi @mlapeyre3 ,

I took a quick look.  It looks like the way you set targeting is not correct in setDfpTargeting.   

You're assuming that each key inside bid.adserverTargeting is hb_bidder_{bidderCode}, but its really just hb_bidder and the tagKeywords loop is overwriting the same key.

**Comment by mlapeyre3** [comment]
Hey @lambdarho ! Thanks for your reply, I will forward this info to the publisher. After discussing with them, they are configuring the adserverTargeting manually while we expected `pbjs.setTargetingForGPTAsync()` to be used.
Thanks for the heads-up, I will close this issue next week if there is no further question from them!

**Comment by gglas** [comment]
@mlapeyre3 were you guys able to resolve, can we close this issue out?

**Comment by ChrisHuie** [comment]
closing issue as sounds like issue is resolved
