### ISSUE TITLE
Rubicon Bidder configuration

### ISSUE THREAD

**Issue by marvinferreira** [prebid/Prebid.js#644]
When I call Prebid and it call Rubicon GET http://ads.rubiconproject.com/header/12460.js I received a 404 from the GET call. Is it some problem with authentication? Do I need to enable Header Biddin at Rubicon?

My snippet:

<script> 
                        var PREBID_TIMEOUT = 700;

                        var adUnits = [{
                            code: 'dfp101',
                            sizes: [[728,90]],
                            bids: [{
                                bidder: 'rubicon',
	                            params: {
		                        accountId: 'XXXXX',
		                        siteId: 'YYYYY',
		                        zoneId: 'WWWWW',
		                        sizes: [2]
	                            }
                            }]
                        }];
    
                        var pbjs = pbjs || {};
                        pbjs.que = pbjs.que || [];

                      </script> 
					<script type='text/javascript'>
						var googletag = googletag || {};
						googletag.cmd = googletag.cmd || [];
                            
                        googletag.cmd.push(function() {
                            googletag.pubads().disableInitialLoad();
                        });
                        
                        pbjs.que.push(function() {
                                pbjs.addAdUnits(adUnits);
                                pbjs.requestBids({
                                    bidsBackHandler: sendAdserverRequest
                                });
                            });

                            function sendAdserverRequest() {
                                if (pbjs.adserverRequestSent) return;
                                pbjs.adserverRequestSent = true;
                                googletag.cmd.push(function() {
                                    pbjs.que.push(function() {
                                        pbjs.setTargetingForGPTAsync();
                                        googletag.pubads().refresh();
                                    });
                                });
                            }

                            setTimeout(function() {
                                sendAdserverRequest();
                            }, PREBID_TIMEOUT);

						(function() {
							var gads = document.createElement('script');
							gads.async = true;
							gads.type = 'text/javascript';
							var usessl = 'https:' == document.location.protocol;
							gads.src = (usessl ? 'https:' : 'http:') + '//www.googletagservices.com/tag/js/gpt.js';
							var node =document.getElementsByTagName('script')[0];
							node.parentNode.insertBefore(gads, node);
						})();
					</script>	

Thanks!!

**Comment by mkendall07** [comment]
@marvinferreira 
yes please contact Rubicon support. 
CC: @bretg

**Comment by marvinferreira** [comment]
Thanks!!
