### ISSUE TITLE
Should AUCTION_PRICE be resolved with bid price?

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#6440]
## Type of issue
question that might lead to an enhancement

## Description
I've been hit a couple of times in the past few months with questions about the AUCTION_PRICE macro.

This is an an old OpenRTB macro that I don't think makes much sense in the Prebid scope, but several bidders still expect it to be resolve somewhere along the path. Currently, that somewhere is in `renderAd` and the PUC. The price used to resolve the value differs based on the scenario:
- Web: PBJS replaces with bid.cpm
- AMP and App: PUC replaces with hb_pb after pulling from cache

When hb_pb is utilized, it's value is rounded down by the price granularity, likely making it less accurate. Looking back in the archives, there are a few issues on this topic, but none stepping back and considering what to do about this thing.

1) Should Prebid take AUCTION_PRICE more seriously - trying to replace the value with the bid price rather than the rounded down price bucket? Why do DSPs even use this thing anymore? Seems like a hangover that ought to go away, IMO. But since that seems unlikely to happen...
2) Since the two scenarios that are the least accurate come from Prebid Server, it could either resolve the macro before putting it into cache or cache the bid price and have the PUC use the cached price rather than `hb_pb`.

Looking forward to thoughts from the community.

**Comment by westerschmal** [comment]
I'd like to add another issue here. It seems Prebid replaces the AUCTION_PRICE macro with bid.cpm. 
This causes issues when using the currency module. DSP's will most likely expect a price in USD, while the bid.cpm is the price after conversion. This causes discrepancies when your adserver is not in USD.

**Comment by bretg** [comment]
There's a PUC change in https://github.com/prebid/prebid-universal-creative/pull/141 to use bid.price if it's available. This has the same problem that @westerschmal notes in that it's still post-currency conversion.

The Prebid Server committee has determined that it's the (server-side) bid adapter's responsibility to resolve AUCTION_PRICE if they want accuracy. I would propose that Prebid.js should mandate the same solution. Not many adapters need AUCTION_PRICE resolved and the only thing that makes sense is for AUCTION_PRICE to be resolved with bid price, and rather than weigh down the browser with reverse price conversions, adapters should do it themselves.

@gglas to host the discussion in a future PBJS committee meeting

**Comment by gglas** [comment]
Fix rolled out to the PUC, documented in the PBS FAQ.  @bretg adding entry to PBJS FAQ, closing this issue.
