### ISSUE TITLE
AMP ad with prebid

### ISSUE THREAD

**Issue by soman** [prebid/Prebid.js#6451]
## Type of issue

question

## Description

We configured prebid-server for AMP ad. Now we are going to create DFP line items but I'm confused about line item.
Previously we created DFP line items for display ad with 0.01 incremental and one creative.
Should we create DFP line items same as display ad but creative will be different for AMP ad?

Also I would like to know about standard ad size for AMP ad? (300x250, 320x100, 320x50)

Thanks,

**Comment by lanceloti** [comment]
@soman You need to configure the price bucket, bidders and sizes inside your Prebid-Server OpenRTB Config.

https://docs.prebid.org/prebid-server/use-cases/pbs-amp.html#prebid-server-resolves-the-stored-request-id

**Comment by ChrisHuie** [comment]
solution and further information with link provided so closing out issue.
