### ISSUE TITLE
Adapter supports adomain but not meta.advertiserDomains

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#6466]
## Type of issue
Some bidders explicitly support adomain in their adapter code but don't set meta.advertiserDomains . Others support it in their Prebid.js/test/spec/modules but not in their adapter js. This issue lists both types. 

Specifically, this adapter has support for adomain but not meta.advertiserDomains: 

https://github.com/patmmccann/Prebid.js/blob/master/modules/ozoneBidAdapter.js @afsheenb @askrupert-dm

These support it in their test but not explicitly in their adapter. 
`~/Prebid.js/modules$ grep dvertiserDomains *BidAdapter.js | awk -F ':' '{print $1}'  | awk -F '.' '{print $1}' > ~/adomains.txt`

`~/Prebid.js/test/spec/modules$ grep -i adomain *BidAdapter_spec.js | awk -F ':' '{print $1}' > ~/adomain_test.txt`

`grep -v ~/adomain_test.txt -f ~/adomains.txt | sort | uniq`

adponeBidAdapter_spec.js @seergiioo6 
advangelistsBidAdapter_spec.js @trchandraprakash 
bidphysicsBidAdapter_spec.js @bidphysics 
bizzclickBidAdapter_spec.js @BizzClick 
cedatoBidAdapter_spec.js @alexkh13 
cleanmedianetBidAdapter_spec.js @sa1omon 
cosmosBidAdapter_spec.js @dev-cosmos 
ebdrBidAdapter_spec.js @jlzhangdev 
gamoshiBidAdapter_spec.js @sa1omon 
lemmaBidAdapter_spec.js @lemmadev 
lkqdBidAdapter_spec.js @david-carver 
lunamediaBidAdapter_spec.js @trchandraprakash 
marsmediaBidAdapter_spec.js @vladi-mmg 
newborntownWebBidAdapter_spec.js @z-sunshine 
pxyzBidAdapter_spec.js @monofonik 
resultsmediaBidAdapter_spec.js @vladi-mmg 
theAdxBidAdapter_spec.js @mustafakemal16 
timBidAdapter_spec.js @borisjaskerovich 
unicornBidAdapter_spec.js @ctylim 
yieldliftBidAdapter_spec.js @yieldlift

**Comment by patmmccann** [comment]
Please see https://github.com/prebid/Prebid.js/pull/6495 for an example of how to make this fix

**Comment by patmmccann** [comment]
Thanks @kanchika-automatad! I removed your adapter from the list above

**Comment by david-carver** [comment]
The issue is acknowledged and will be dealt with next week.
