### ISSUE TITLE
Rubicon Bid Adapter required video params

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/Prebid.js#6502]
## Type of issue
Feature request

## Description
Rubicon's bid adapter expects certain fields to be under `mediaTypes.video`, eg maxduration, linearity.

There are two issues with this:

First, some of the required fields are not officially supported by prebid, or the documentation is lacking  ( https://docs.prebid.org/dev-docs/adunit-reference.html#adunitmediatypesvideo )

Second, more importantly, is that we dont always want to specify the maxduration. For example, we want to request an ad that is skippable, and we dont care what the maxduration is. By requiring it in mediaTypes.video other bid adapters will potentially read that field as well. It also prevents us from requesting multiple bids, eg a non-skippable 15sec ad, or a skippable longer ad, as only one maxduration can be set.

### Proposed Solution

Most bid adapters started supporting a subset of openRTB. Given that rubicon already supports a `video: { ... }` field, the bid adapter should require the maxduration to be specified there. That way, we can still provide one for Rubicon, without affecting other bid adapters, and enabling more complex video requests.

**Comment by ReinoutStevens** [comment]
@bretg I think you're the maintainer of the rubicon adapter, so tagging you. Apologies if that is not the case.

**Comment by bretg** [comment]
Confirmed with the Magnite video team that we can relax this restriction. PR opened.

**Comment by ReinoutStevens** [comment]
thanks for resolving this very quickly
