### ISSUE TITLE
Supports video but does not read video parameters from the ad unit

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#6512]
## Type of issue
Adapter rules

## Description
With Prebid 4.0, https://github.com/prebid/Prebid.js/issues/5237 was adopted, where publishers can expect to be able to set openrtb video params on the ad unit instead of having to repeat the parameter set up with differing requirements for every adapter they install. At that time and again with the #5966 proposal, it was announced that behavior would be enforced. 

This is a rough computer-generated, person edited list of adapters supporting video but not reading many parameters from mediaTypes.video. There are other adapters not on this list only reading some parameters from that location which should also be fixed.

A great example of how to read from the correct place includes https://github.com/prebid/Prebid.js/pull/6177 or https://github.com/stevealliance/Prebid.js/blob/a5ec2587abe94eae75300b52b7ccceaf70e78a41/modules/districtmDMXBidAdapter.js#L157

The following bid adapters read bidder-specific video params instead of using mediatypes, eg for parameter 'mimes'. Note, a more thorough review will be done before any enforcement action. If you don't think you should be on this list please comment:

https://github.com/prebid/Prebid.js/blob/master/modules/advangelistsBidAdapter.md @trchandraprakash 
https://github.com/prebid/Prebid.js/blob/master/modules/dailyhuntBidAdapter.md @montu1996 
https://github.com/prebid/Prebid.js/blob/master/modules/lemmaBidAdapter.md @lemmadev 
https://github.com/prebid/Prebid.js/blob/master/modules/lunamediaBidAdapter.md @trchandraprakash 
https://github.com/prebid/Prebid.js/blob/master/modules/waardexBidAdapter.md @yegorWaardex 

These bid adapters have acknowledged the issue and have pending pr's:
https://github.com/prebid/Prebid.js/blob/master/modules/saambaaBidAdapter.md @trchandraprakash 

Also related:
https://github.com/prebid/prebid.github.io/pull/2158
https://github.com/prebid/Prebid.js/pull/5536

**Comment by jsnellbaker** [comment]
Hi @patmmccann 

Just want to clarify the intent of this change; it is meant to completely discourage bidders from setting **any** video params in the bidder params and they have to read everything from the `mediaTypes.video` field in an ORTB lense?  

Or do bidders have to add more support for reading those values from the `mediatTypes.video` field, but they can continue to read values from the bidder params (preferring one over the other as mentioned in the related docs PR prebid/prebid.github.io#2158).

I ask because in reviewing/comparing the video params we use for our appnexus bidder with the params that are listed/described in the ORTB 2.5 spec for the video object, there's not always a straight transition.  One of our fields `context` doesn't appear to exist at all as an available ORTB param (maybe I missed it), but even if it did - that (and a few other params) have extra values used by our system that are not supported by the ORTB spec.  

If we're expected to go the former option described above, how are we supposed to resolve these differences when bidder-specific things do exist?

**Comment by patmmccann** [comment]
Hi @jsnellbaker ,rereading https://github.com/prebid/Prebid.js/pull/5536/files and https://github.com/prebid/Prebid.js/issues/5237 ; I don't think anything outside of this list is a concern

`mimes
minduration
maxduration
protocols
startdelay
placement
skip
skipafter
minbitrate
maxbitrate
delivery
playbackmethod
api
linearity`

Does that answer your question?

**Comment by jsnellbaker** [comment]
I'm not sure it does...

Does this overall ask in the 5.0 world mean bidders could still read values from their own `bid.params.video` field?  Or no?  Or is it only situational (like for a param that's not defined in the ORTB spec)?  Or is there meant to be a tiered system, eg if a param isn't defined in the bidder.params, then try to check the `mediaTypes.video` to see if it's available there?

**Comment by patmmccann** [comment]
The latter option seems to go with the spirit of the requirement the best.
The chief goal here is to increase publisher usability. If a publisher
wishes to convey for example that playback type is click to play or that
mime types is mp4, the hope is that the publisher could specify that once,
but if the publisher and the ssp in partnership want to override what is
communicated to other ssps and set a different value,  that should be
possible as well. What do you think?

**Comment by jsnellbaker** [comment]
Okay, thanks Patrick.  It sounds like the last suggestion is the way to go.  

I'll start to work on our bidder's updates along these lines.

**Comment by patmmccann** [comment]
@adam-browning you've previously mentioned AOL bid adapter has been replaced for video by onevideo. Can this line be safely deleted? https://github.com/prebid/Prebid.js/blob/6c0142abd4831db5416bedd4a7291dfb7b477bc8/modules/aolBidAdapter.js#L91

**Comment by patmmccann** [comment]
solved for IX on #6691

**Comment by adam-browning** [comment]
Hey @patmmccann, 
> @adam-browning you've previously mentioned AOL bid adapter has been replaced for video by onevideo. Can this line be safely deleted?

This interpretation is not correct since Verizon Media/Yahoo has multiple platforms and different types of adapters that were developed independently by different R&D groups. Could we please postpone any changes at this time until we sync internally? I do not want to break anything without confirming with our stakeholders first.

I apologize in advance as my response time is limited in the next 2-3 weeks.
I appreciate your consideration,
Many thanks
Adam

**Comment by patmmccann** [comment]
Hi Adam,

We're planning on doing the PR to remove all adapters from pbjs 5 still on
the list above on Friday May 21. You have three options for your adapter:

Accept the change I made
Make your own changes
Purge your adapter from pb 5

Thanks!

**Comment by jsalis** [comment]
Hi @patmmccann 

I reviewed the Beachfront adapter and it seems to follow the conventions described above.
See here: https://github.com/prebid/Prebid.js/blob/master/modules/beachfrontBidAdapter.js#L297

The video params are first read from `bid.mediaTypes.video` and then are overridden if the publisher sets bidder-specific params.

If this is not correct, I can make the necessary adapter changes.

**Comment by patmmccann** [comment]
@jsalis great! please update https://github.com/prebid/Prebid.js/blob/master/modules/beachfrontBidAdapter.md and any other doc to reflect.

**Comment by pycnvr** [comment]
Hi @patmmccann,

The Conversant adapter already picks up most of the video properties from mediaTypes.video except for maxduration.  A PR is opened to address that.

**Comment by patmmccann** [comment]
@desidiver

I don't think we're reading your code the same way

You are included in #6807 pr to remove and it isn't just a docs fix you need

**Comment by ybootin** [comment]
@patmmccann should be fixed with this PR for seedtagBidder: 
https://github.com/prebid/Prebid.js/pull/6888

thx for ping us :)

**Comment by Viewtiful** [comment]
Hello,
Just to be sure, do you also enforce that we have to support all the video fields defined above through our adapters (even if we do not use them)? Or we only have to enforce the new logic for the fields that we currently use?

**Comment by patmmccann** [comment]
> Hello,
> Just to be sure, do you also enforce that we have to support all the video fields defined above through our adapters (even if we do not use them)? Or we only have to enforce the new logic for the fields that we currently use?

the latter

**Comment by c3p-0** [comment]
Hi @patmmccann  , medianetBidAdapter is reading video objects from mediaTypes and bidder-specific video params.  
```
const videoInMediaType = utils.deepAccess(bidRequest, 'mediaTypes.video') || {};
const videoInParams = utils.deepAccess(bidRequest, 'params.video') || {};
```
And giving preference to mediaTypes
`const videoCombinedObj = Object.assign({}, videoInParams, videoInMediaType);`

Will it be ok or we will have to stop reading bidder-specific video params?

**Comment by patmmccann** [comment]
@c3p-0 excellent! Can you change your fix to reflect? Your MD file examples all use bidder params

**Comment by c3p-0** [comment]
Sure @patmmccann . I have created this [MR](https://github.com/prebid/Prebid.js/pull/6922) for this.

**Comment by patmmccann** [comment]
Thanks @c3p-0! I removed you from the list above

**Comment by patmmccann** [comment]
Closing with the merge of #6947
