### ISSUE TITLE
Enable GeoIP Awareness to Prebid.js

### ISSUE THREAD

**Issue by ian-lr** [prebid/Prebid.js#6516]
## Type of issue
Feature Request

## Description

Enable standard lookup, storage and availability of an end user's geography, as based on IP. 

LiveRamp, in the context of our userId module, only supports identity lookup for markets that have been reviewed by our data ethics / privacy teams. When we do not believe we have appropriate permission to process data in a given country (or state/province), we will "loudly" state as much in the form of an HTTP 400-level (typically 451) status code. This sends a clear signal to end users and regulators that we do not want to receive such requests from that region and have not further processed the data. 

However, this "error" can be a burden to publishers who want to eliminate any bad requests from their pages. While it would be possible for us to implement geoIP awareness as vendor-specific capability, it strikes me that this might become more useful, especially as varying regulatory regimes take off around the world and service providers want to more clearly indicate their compliance. 

## Strawman
- Create a new module that accepts a required CORS endpoint as a parameter, alongside storage and TTL preferences. 
- By default, check the cache || call the endpoint _before_ an auction begins. 
- Parse and store the result which would have an expected response format of e.g. `{"country_code":"NL","state":"ZE"}` using ISO 3166.
- Make the value available to bidders, userId modules and (potentially) other module types. 
- Modules like ours could decide whether to attempt ID retrieval (or bids) based on the geoIP information before making remote calls.

**Comment by patmmccann** [comment]
Have you considered usinng time zone? https://gist.github.com/rxaviers/8481876 https://stackoverflow.com/questions/38399465/how-to-get-list-of-all-timezones-in-javascript

**Comment by patmmccann** [comment]
It seems the way for this to work is an rtd module or https://github.com/prebid/Prebid.js/pull/6452 might populate device.geo.country in the ortb2 object, but I am not sure I see the use case yet as time zone is an effective alternative.

**Comment by ian-lr** [comment]
@patmmccann That came up in the Privacy and Identity PMC, although I was under the impression that some tzs would be shared across multiple countries. After a review of https://en.wikipedia.org/wiki/List_of_tz_database_time_zones it doesn't appear that's the case. This would be an issue for state-level categorization (e.g. users in Virginia might choose Washington DC or NYC), but that isn't a primary use case for us at the moment. 

Will close this out for the time being!
