### ISSUE TITLE
SharedId: drop 3rd party cookie matching

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#6522]
## Type of issue
Proposal

## Description
Discussions with the Identity Committee have suggested that SharedId 3rd party cookies didn't gain widespread adoption and may not.  Looking for community input on the proposal to drop the 3rd party cookie portion of SharedID in PBJS 5.0

**Comment by patmmccann** [comment]
I support this proposal; we never adopted because the value proposition was always unclear to me. The pubcommonid feels cleaner without the distraction of sharedid. I look forward to the server side pub common id instructions moving to the prebid.org docs.

**Comment by durbanfrazer** [comment]
I also support dropping the third party cookie requirement, would make pubcommonid easier to reason about. I also expect most third party cookie work would stop being useful after chrome removes third party cookies.

**Comment by patmmccann** [comment]
duplicated in #6640
