### ISSUE TITLE
Stale Prebid Currency data

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#6524]
## Type of issue
stale data

## Description
The underlying currency exchange API Prebid.org uses to generate the currency file has implemented an API key as of April 1 2021. We aren't likely to be given an API key because of the way we use the data.

A search for a replacement is underway. In the meantime, the currency exchange file will be updated manually on a weekly basis if needed.

**Comment by bretg** [comment]
Patrick found a replacement -- https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml. And a backup approach, which is to query google to get the currencies we want -- https://github.com/fawazahmed0/currency-api/blob/1/currscript.js

Will open an internal ticket to get the Prebid currency job updated

**Comment by Josh-G** [comment]
Looks like the new currency file is missing EUR. Is this intentional?

**Comment by patmmccann** [comment]
> Looks like the new currency file is missing EUR. Is this intentional?

Euro is the reference currency in the xml from the economy; all these values are relative to 1 euro

**Comment by Josh-G** [comment]
The rates are relative to USD/GBP in the [JSON file](https://cdn.jsdelivr.net/gh/prebid/currency-file@1.0.927/latest.json), without a EUR conversion rate. Files generated with the old currency exchange API contained a EUR rate for both GBP/USD. The last file with a EUR rate was https://cdn.jsdelivr.net/gh/prebid/currency-file@1.0.925/latest.json

**Comment by patmmccann** [comment]
@bjorn-lw reports restored

**Comment by bretg** [comment]
There was an issue during the currency code refactoring that resulted in a missing conversion rate for EUR for several hours on Tues April 6th before being caught and corrected. Note that the issue lasted for longer for anyone using the deprecated currency.prebid.org source. Those using the recommended jsdelivr.com source 

We apologize for the error and will add documentation to future developers to avoid a reoccurrence.

I will update the currency module documentation to highlight that Prebid recommends supplying default conversion rates for critical currencies in case the file cannot be loaded. In this case, publishers who had set up default rates would have experienced no interruption.

```
pbjs.setConfig({
    "currency": {
       "adServerCurrency": "EUR",
       "defaultRates": { "USD": { "EUR": 1.1 }}
    }
});
```

The file is now being updated daily and we're looking for after-the-fact community review.

**Comment by bretg** [comment]
Highlighted the defaultRates param in https://github.com/prebid/prebid.github.io/pull/2845

**Comment by Josh-G** [comment]
Thanks!

**Comment by bretg** [comment]
Going to close this issue, though we still would like to have a community review of the PR https://github.com/prebid/currency-file-generator/pull/21
