### ISSUE TITLE
pbsBidAdapter should pass more ortb2 values through to server

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#6528]
## Type of issue
enhancement

## Description
Part of the intention of the new `ortb2` method of pubs specifying first party data was for this config to be sent straight through to Prebid Server.

However, currently the pbsBidAdapter only looks for site, user, and imp.ext.data

I propose dramatically expanding what gets passed through to PBS to include **everything** in ortb2.

1) read getConfig({ortb2}) and merge it
2) pass bidder-specific config through as ext.prebid.bidderconfig
3) read adunit.ortb2Imp and merge that to the imp[]. This lets them specify imp.ext, imp.pmp, imp.intstl, etc.

**Comment by patmmccann** [comment]
@pm-harshad-mane recently pointed this out as well, that pbs was missing ortb2 device object.

At a minimum we should add device,  but I cannot think of what we wouldn't want to add and this seems like a great proposal.

**Comment by muuki88** [comment]
This extension would also allow to set floor prices via the floor price module on the `ortb2` object. This allows a smoother transition from client side floor settings to server side floor settings.

**Comment by bretg** [comment]
@Fawke noted in #7219 that another use case for this is bcat/badv.

**Comment by bretg** [comment]
Closed with #7315
