### ISSUE TITLE
Create module registry

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#6562]
## Type of issue
enhancement

## Description
We have a new scenario where our bid adapter needs to know whether or not our analytics adapter is in use on the page. There have been other scenarios where groups of modules work together or do something differently based on what other modules are present.

https://github.com/prebid/Prebid.js/issues/6117 innovated a step in this direction. When you run

```
gulp build --modules=uid2IdSystem,rubiconAnalyticsAdapter,rubiconBidAdapter,prebidServerBidAdapter,currency
```
It puts a comment in the resulting prebid.js file:
```
Updated : 2021-04-09
Modules: userId, uid2IdSystem, rubiconAnalyticsAdapter, rubiconBidAdapter, prebidServerBidAdapter, currency */
```

The proposal is that we drop the comments and instead create a machine readable format:

```
GLOBAL.installedModules = [userId, uid2IdSystem, rubiconAnalyticsAdapter, rubiconBidAdapter, prebidServerBidAdapter, currency]
```

Then modules can stop doing hacky things and just check the array of installedModules.

**Comment by smenzer** [comment]
I love the idea. As long as the machine readable array is also easily readable by a human I'm fine dropping the comments...otherwise I'd like to leave them in as they're incredibly useful for debugging.

**Comment by anthonylauzon** [comment]
I like this idea a lot. We might ultimately use this functionality with our id and rtd module at some point in the future.  Another nice to have that is somewhat related would be having place for vendor specific library code to go that might be shared between modules.  For instance, I imagine a scenario where an analytics adapter would need to potentially duplicate library code present in a bid adapter.  If the analytics adapter could check if the bid adapter were present and dynamically load the library code accordingly, that might prove helpful in certain circumstances.  I think I maybe have seen something similar to this in a bid adapter, but I can't recall exactly where.
