### ISSUE TITLE
Prebid setup

### ISSUE THREAD

**Issue by Rubioli** [prebid/Prebid.js#658]
I am interested to implement/setup prebid to my Rails application. I have been reading [prebid.org](http://prebid.org/dev-docs/getting-started.html) but still confused about how to implement it correctly.

Maybe its just me, but could someone explain to me how to implement it and whats needed.

I want to test it out on one spot first (300x250 - 300x600) and on that spot I have 3 advertisers, AOL, UnderdogMedia & Defy Media, I would appreciate if the example could be with them. 

Thanks in advanced!

**Comment by ialex** [comment]
@Rubioli here it is an example:

https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/pbjs_example_gpt.html

make sure you are enabled to run HBS on those advertisers and ask for their information needed to run each one in the example page are the params required, Prebid works on the browsers changes are required just on the client side.

**Comment by Rubioli** [comment]
Thanks a bunch.

I have some questions that hope you can answer me.

1. Do I need to add prebid.js in to my `<head>`
2. Do I need to change parts that has `googletag` since I dont run google adsense.
3. Do I need to change `$$PREBID_GLOBAL$$` if yes to what?
4. Basically I can add that boilerplate and only add my own `adunits` from line *77 - 312*. is it right? Or which lines do I need to change?

Again thanks you so much for help and sorry for many questions :)

**Comment by ialex** [comment]
1.- Prebid is added there in the head so yes you need to include
2.- You can copy and paste the code in the header that includes prebid/gpt
3.- Yes that is correct you just need to add your own ad units with correct parameters shared by ad networks
