### ISSUE TITLE
Add missing adapter documentation to prebid.org

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#659]
We currently have 30 adapters listed in `src/adapters/` however, only 18 have documentation here http://prebid.org/dev-docs/bidders.html.

Please add documentation for your adapter and submit a PR to to [this project](https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders). Once it's submited please check the box for your adapter. 
- [x] AdBlade
- [ ] Adequant
- [ ] Admedia
- [x] Brightcom
- [x] Centro
- [x] Getintent
- [ ] JCM
- [ ] Memeglobal
- [ ] Nginad
- [x] Piximedia
- [x] Triplelift
- [ ] Underdogmedia
- [x] Hiro
- [x] Roxot
- [x] AdButler
- [x] Komoona
- [x] RhythmOne
- [ ] Vertoz
- [ ] AdKernel
- [x] Conversant Media

@prebid/bidder-adaptors 
@christopher-allene-piximedia, @mattjone, @tiffwu, @Niksok, @dmart28, @devmusings, @frazjp65, @naamushka, @nginadfoundation, @JCarterGw, @matan-ybrant, @relegit

Thank you for contributing. 

CC: @rmloveland

**Comment by dmart28** [comment]
prebid/prebid.github.io#103

**Comment by christopher-allene-piximedia** [comment]
Piximedia Bidder:
https://github.com/prebid/prebid.github.io/pull/106

**Comment by nginadofficial** [comment]
I just saw this. I have a full time job in the movie biz + 2 hours commute to work each way from El Monte Station to Beverly Hills via the Silver line bus + 720 each day. So 8 hours work day + 4 hours bus. I will have this done in the little time I have left with my family of 4 by the weekend. Thanks for any comprehension.

Chris Gu

**Comment by matan-ybrant** [comment]
Brightcom documentation added:
[prebid/prebid.github.io#112](https://github.com/prebid/prebid.github.io/pull/112)

**Comment by mkendall07** [comment]
Bump. Still missing a few docs

**Comment by aneuway2** [comment]
Submitted a PR on https://github.com/prebid/prebid.github.io/pull/175 for several missing bidders per documentation in bidder PRs/Issues/Release notes

**Comment by rmloveland** [comment]
Just merged @aneuway2's YUUUUGE PR - this leaves the only 2 remaining bidders from the list (although I may be unaware of them being documented under another alias, so please let me know):

- Admedia
- Vertoz

At this point I'll close out this issue and create issues for those missing bidders specifically.

**Comment by mkendall07** [comment]
w00t!

**Comment by aneuway2** [comment]
@rmloveland I'll submit a separate PR for those as well. Looks like I missed them ;-)

**Comment by rmloveland** [comment]
@aneuway2 thanks for the catch - I'll close out those issues.
