### ISSUE TITLE
Does Prebid.js support cookie sync?

### ISSUE THREAD

**Issue by yegorWaardex** [prebid/Prebid.js#6606]
## Type of issue
question

## Description
1. Does Prebid.js support cookie sync?
2. If Prebid.js support then is it enabled by default or I need to do something to enable it?

## Steps to reproduce
N/A

## Test page
N/A

### Expected results
N/A
### Actual results
N/A

## Platform details
N/A

## Other information
N/A

**Comment by patmmccann** [comment]
yes, yes by default

**Comment by bretg** [comment]
https://docs.prebid.org/dev-docs/publisher-api-reference.html#setConfig-Configure-User-Syncing
