### ISSUE TITLE
How to favor deal bids on flex units?

### ISSUE THREAD

**Issue by Lesters4454** [prebid/Prebid.js#6610]
## Type of issue
Question

## Description
Prebid only sends one bid as targeting into GAM on flex units that support multiple sizes but allows a bid on each size.  If we have a deal bid on a 728x90 @ $4 and an open market bid on a 970x250 @ $7, Prebid will send the $7 bid only.  Is there a way to configure Prebid to favor deal bids on flex units regardless of price?

Note this is not affected by "sendAllBids".  All bidders only send one bid per flex units.  "sendAllBids" simply allows Prebid to send that one bid from all bidders.  What I am looking to do is have a deal bid be the selected bid on the flex unit for any particular bidder even if the price is lower than the OM bid.

**Comment by patmmccann** [comment]
You can use this https://github.com/prebid/Prebid.js/blob/a430753459899c6001b1c8c24926bc6988790e5f/src/targeting.js#L168

**Comment by bretg** [comment]
See alwaysIncludeDeals  in https://docs.prebid.org/dev-docs/publisher-api-reference.html#setConfig-targetingControls
