### ISSUE TITLE
Prebid version in an HTTP header

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#6627]
## Type of issue
Proposed Enhancement

## Description
There's interest from some bidders to be able to cleanly distinguish the source of traffic. Currently it's up to each bidder to read the Prebid.js version and pass it to their endpoint. There aren't any conventions about where bidders should place this version, so they've done it every which way. There are 83 bid adapters that refer to prebid.version, with not much overlap in what they call the attribute: prebidVersion, pbjs, wrapperVersion, wrapper_version, version, pbav, hb_version, pubpbv, prebidJsVersion, pub_pbver, lib_v, tk_flint, etc.

The proposal is to update ajax.js to add a new HTTP header `X-Prebid` which carries the PBJS and PBS versions:

```
X-Prebid: pbjs/4.35
```

Prebid Server would add it's own version on to this header:
```
X-Prebid: pbjs/4.35,pbs-java/1.61
```

It's recognized that it may take a while before the majority of publishers have upgraded to the version of PBJS that contains this header, but you have to start somewhere.

**Comment by patmmccann** [comment]
Where should this be documented?
