### ISSUE TITLE
Merge Pubcommon and SharedId user id sub adapters. 

### ISSUE THREAD

**Issue by jdwieland8282** [prebid/Prebid.js#6640]
## Type of issue
Feature Request

## Description
We have two functionally similar user id sub adapters (PubCommon and SharedID).  We would like to merge the two w/o impacting the DSPs who read "source=pubcid.org" in pb.js 5.0

- We will deprecate the SharedID sub adapter.  
- We will rename the PubCommon sub adapter to "SharedId"
- The PubCommon Source value will remain "pubcid.org"

### Expected results

- We expect publishers who have deployed Pubcommon to not be impacted in any way. 
- We expect publishers who have deployed SharedId to not be impacted but encouraged to remove sharedid from their pb.js build & migrate to the newly renamed Pubcommon sub adapter.  

remove the following sharedid files
 -  modules/sharedIdSystem.js
 - test/spec/modules/sharedIdSystem_spec.js
 - modules/sharedIdSystem.md

remove pubcommon references in
 - test/spec/modules/userId_spec.js
 - modules/userId/userId.md
 - modules/userId/eids.js
 - modules/userId/eids.md

remove sharedid references in:
 - modules/pubCommonIdSystem.js
 - test/spec/modules/eids_spec.js

rename references to sharedid.org to pubcid.org in:
 - test/spec/modules/logicadBidAdapter_spec.js
 - test/spec/modules/betweenBidAdapter_spec.js
 - integrationExamples/gpt/userId_example.html
 - modules/betweenBidAdapter.js
 - integrationExamples/gpt/idImportLibrary_example.html
 - modules/districtmDMXBidAdapter.js
 - test/spec/modules/sharethroughBidAdapter_spec.js
 - test/spec/modules/sonobiBidAdapter_spec.js
 - modules/openxBidAdapter.js
 - test/spec/modules/rubiconBidAdapter_spec.js
 - modules/sharethroughBidAdapter.js
 - test/spec/modules/livewrappedBidAdapter_spec.js
 - modules/ucfunnelBidAdapter.js
 - test/spec/modules/ucfunnelBidAdapter_spec.js
 - test/spec/modules/apacdexBidAdapter_spec.js
 - test/spec/modules/districtmDmxBidAdapter_spec.js
 - modules/rubiconBidAdapter.js
 - test/spec/modules/adagioBidAdapter_spec.js
 - test/spec/modules/openxBidAdapter_spec.js
 - modules/ixBidAdapter.js
 - modules/ozoneBidAdapter.js

rename 
 - modules/pubCommonIdSystem.js to modules/sharedIdSystem.js
 - test/spec/modules/PubcommonIdSystem_spec.js
 
rename
- https://github.com/prebid/pubcommon-wordpress --> https://github.com/prebid/sharedid-wordpress
- https://github.com/prebid/pubcommon-drupal --> https://github.com/prebid/sharedid-drupal

update references to pubcid, pubcommon to sharedid in
- https://github.com/prebid/pubcommon-wordpress/blob/master/README.md
- https://github.com/prebid/pubcommon-drupal/blob/master/readme.md

**Comment by bretg** [comment]
From an external perspective this change is really more like getting rid of pubcommon and making everyone move to sharedid.

Under the covers though it's still pubcommon in two ways:
- the eids.source entry is "pubcid.org". This is because this source has a much higher DSP adoption.
- the module config can still look for the pubcommon cookie name the pub wants

> We expect publishers who have deployed Pubcommon to not be impacted in any way.

actually publishers would have two major impacts in order to upgrade to PBJS 5.0

1) when building their PBJS package, there's no more pubcommon, so they would instead choose sharedid as the module. This module happens to behave exactly like pubcommon but with a new name.
2) when configuring the user ID modules, they refer to the name 'sharedId' instead of 'pubcommon'.

```
pbjs.setConfig({
    userSync: {
        userIds: [{
            name: "sharedId",  // instead of pubCommonId
            storage: {
                type: "cookie",
                name: "_pubcid",         // can keep this as the cookie name if desired
                expires: 365
            }
        }]
    }
});
```

Yes, we recognize that this complicates adoption of 5.0. However, it doesn't make sense for Prebid.org to have two first-party user ID modules that do essentially the same thing after 3rd party cookies go away. So we're biting the bullet to get to a place where we have the best revenue adoption with a name that's considered more catchy.

**Comment by patmmccann** [comment]
I do not like the idea of "We will rename the PubCommon sub adapter to "SharedId" " 

Absent combining pubcid 1st party cookie into sharedid 3rd party cookie, this proposal seems without merit to me. Pubcommonid has no branding problem that changing the name solves I am aware of. We discussed this in the publisher committee today and it was suggested pubcid shares an association with its creator company. I am not sure why that is a problem, anymore than Prebid shares an asssociation with Xandr, but it was suggested that the name change would make the new ownership by prebid of this code apparent. 

It was proposed the Epsilon association could be solved by changing the name to prebid common id or some other third name, and we would lose the negative association some folks have with sharedid as the unsuccessful 3rd party attachment to pubcommonid. This seems better than rebranding to sharedid, but I still don't see the usefulness of rebranding at all.

**Comment by slayser8** [comment]
PubCommon was a project that came out of Conversant and was donated to Prebid.org. Without a rebranding, there is no indication that this is now owned by the community. There was absolutely a Rebranding that occurred from Prebid.js to Prebid.org when we established the standards organization. The intent was to always merge SharedIDs 3rd party namespace for A/B testing purposes to PubcommonID and combine them into one SharedID platform, and I am not sure what negative association with SharedID you're referring too - honestly there is not much talk about it in market up until this moment. Merging did not happen for a miriade of reasons, and as we move forward we realize that SharedIDs 3rd party value is not necessary for A/B testing as most SSPs can use their own seeded 3rd Party identity space. 

I would prefer a rebranding to SharedID but it's up to the wider group and I am happy to bring this to the Prebid Identity group next week for more feedback.

**Comment by smenzer** [comment]
Isn't SharedId tied to Magnite as much as PubCommon is to Conversant/Epsilon or as much as UnifiedID and UID2 are tied to The Trade Desk? 

I'm not arguing for or against a rebranding...I'm just saying that if the reason to do it is that PubCommon is attached to the original company who donated it to Prebid, I would argue SharedId is no different, since it was originally a Rubicon/Magnite initiative before it was donated

**Comment by slayser8** [comment]
PubCommon was Conversant's for years (long enough for it to be donated after they were bought by Epsilon) where as UID 2.0 and SharedId were created with the intent to donate to Prebid

**Comment by patmmccann** [comment]
I'm not sure that's true about uid2, but I remain opposed to making hundreds of publishers change their config because a few people prefer "a name that's considered more catchy."

**Comment by jdwieland8282** [comment]
Our expectation is that hundreds of pubs will **not** have to change their config.  The rebranding from PubCommon to Sharedid is a docs change, we intend to leave the source value for the PC module the same `source=pubcid.org`.  The intention here was to make pub changes as minimal as possible and DPS (that are reading PC) changes non existent since they are helping pubs monetize inventory.  Any DSP looking for an id where `source=pubcid.org` will be unaffected.  

wrt sharedid being tied to Magnite I think that notion obscures the nature of Magnite's intention when we developed the module and donated it to Prebid.org. We (Magnite) were reacting to the path identity was taking, primarily that it was becoming a profit generator for a new class of ad tech companies.  We believe the concept of identity is as a shared resource among participants in the RTB ecosystem, and publishers specifically have a 1st party relationship with their site viewers and as such have a special relationship with them making them the logical owner of a user id. 

I hope that clarifies Magnite's position, we're not seeking credit or notoriety for/with Sharedid.  We've put development, product, and marketing resources behind it at no small cost.  Combining those efforts with Conversants install base gives a publisher 1st party id the best chance at success.

**Comment by patmmccann** [comment]
I agree with @bretg above that @jdwieland8282 is mistaken

**Comment by jdwieland8282** [comment]
Wouldn’t be the first or the last I suspect. I think I see what you mean @patmmccann the config has a ‘name’ change, I missed that, I was expecting the ‘name’ and ‘source’ to remain unchanged. Keeping them as is or config change via alias I don’t have a strong preference, is one more palatable to you/others?

**Comment by patmmccann** [comment]
I have no preference; if we can achieve the rebranding without requiring the installed base to reconfigure in either way, my concerns would disappear.

**Comment by patmmccann** [comment]
Confirmed with @idettman that the alias option is feasible, solving my concern

**Comment by slayser8** [comment]
Does that mean you're happy @patmmccann? :)

**Comment by patmmccann** [comment]
My concerns about breaking things seem to be addressed, but there is an enormous amount of doc to rewite https://github.com/prebid/prebid.github.io/issues/2525 that is easier said than done. I am not sure someone has been identifed to do all this work the rebranding would create.

**Comment by jdwieland8282** [comment]
Handling the docs changes in: 

- Issue: https://github.com/prebid/prebid.github.io/issues/2903
- PR: https://github.com/prebid/prebid.github.io/pull/2904
