### ISSUE TITLE
Adapter does not seem capable of supporting advertiserDomains

### ISSUE THREAD

**Issue by gglas** [prebid/Prebid.js#6650]
In conjunction with https://github.com/prebid/Prebid.js/issues/6466 , there will be an expectation going forward that adapters at least have a method to pass meta.advertiserDomains in their bid responses.  This is because in the future we expect publishers and vendors to use the adomain(s) in service of any number of business cases.

This is not a hard requirement to pass adomain, however, adapters at least need to have a stub to pass adomain in the appropriate field (the meta.advertiserDomains field).  The following adapters have no mention of adomain or advertiserDomains, and while some adapters may be modified with the appropriate stub by other prebid members, any adapters on this list should ensure that they support the relevant field in their adapter or risk not being ported to 5.0.

a4gBidAdapter | devops@ad4game.com | @Junus
aardvarkBidAdapter | chris@rtk.io | @aleksatr
ablidaBidAdapter | d.kuster@ablida.de | @bokos
adbutlerBidAdapter | dan@sparklit.com | @dharton
adfinityBidAdapter | adfinity_prebid@i.ua | @adfinity-prebid
adformBidAdapter | Scope.FL.Scripts@adform.com | @Pupis
adgenerationBidAdapter | ssp-ope@supership.jp | @banakemi
adglareBidAdapter | prebid@adglare.com | @adglare
adkernelAdnBidAdapter | prebid-dev@adkernel.com | @ckbo3hrk
adliveBidAdapter | traffic@adlive.io | @mifanich
admanBidAdapter | traffic@adlive.io | @SmartyAdman
admaticBidAdapter | prebid@admatic.com.tr | @hakanarik
admediaBidAdapter | developers@admedia.com | @Elardzhi
adnowBidAdapter | support@adnow.com | @vingood
adnuntiusBidAdapter | info@adnuntius.com | @mikael-lundin
adoceanBidAdapter | prebid@gemius.com | @mmuras
adpartnerBidAdapter | info@adpartner.pro | @preved-medved
adprimeBidAdapter | tech@adpone.com | @Adprime
adspendBidAdapter | gaffoonster@gmail.com | @loorke
adtargetBidAdapter | kamil@adtarget.com.tr | @GeneGenie
adtelligentBidAdapter | support@adtelligent.com | @GeneGenie
adtrueBidAdapter | ssp@adtrue.com | @haibau 
advenueBidAdapter | dev.advenue@gmail.com | @devadvenue 
advertlyBidAdapter | support@advertly.com | @Advertly
ajaBidAdapter | ssp_support@aja-kk.co.jp | @naoto0822
aniviewBidAdapter | support@aniview.com | @itaynave
appierBidAdapter | apn-dev@appier.com | @justinkuo-appier
apstreamBidAdapter | tech@audienceproject.com | @frstua
astraoneBidAdapter | prebid@astraone.io | @lizakobrazova
atomxBidAdapter | erik@atomx.com | @erikdubbelboer
avocetBidAdapter | developers@avocet.io | @scritchley
bidfluenceBidAdapter | integrations@bidfluence.com | @francescocristallo
bidglassBidAdapter | dliebner@gmail.com | @dliebner
bidlabBidAdapter | dliebner@gmail.com | @bidlab
boldwinBidAdapter | dev+prebid@bluebillywig.com | @Wls-demo
brightcomBidAdapter | vladislavy@brightcom.com | @vyatsun
buzzoolaBidAdapter | devteam@buzzoola.com | @VanCyric
byplayBidAdapter | byplayers@tsumikiinc.com | @daisato-tsumiki
c1xBidAdapter | cathy@c1exchange.com | @CathyHuangtw
clicktripzBidAdapter | integration-support@clicktripz.com | @apmitchell
cointrafficBidAdapter | tech@cointraffic.io | @stsepelin
coinzillaBidAdapter | technical@sevio.com | @arkan303
collectcentBidAdapter | dev.collectcent@gmail.com | @devcollectcent
colombiaBidAdapter | colombiaonline@timesinteret.in | @ColombiaOnline
colossussspBidAdapter | support@colossusmediallc.com | @HuddledMasses
connectadBidAdapter | support@connectad.io | @rtuschkany 
consumableBidAdapter | naffis@consumable.com | @jgrimes
convergeBidAdapter | support@converge-digital.com | @Converge-Digital
cpmstarBidAdapter | josh@cpmstar.com | @JoshuaMGoldstein
craftBidAdapter | system@gacraft.jp | @crumbjp
dailyhuntBidAdapter | @montu1996
decenteradsBidAdapter | publishers@decenterads.com | @vlaktion
djaxBidAdapter | support@djaxtech.com | @djaxbidder
dspxBidAdapter | prebid@dspx.tv | @onlsol
e_volutionBidAdapter | prebid@dspx.tv | @e-volution-tech
edgequeryxBidAdapter | contact@edgequery.com | @Edge Query
emoteevBidAdapter | engineering@emoteev.io | @piotr-yuxuan
engageyaBidAdapter | reem@engageya.com | @reemeng
envivoBidAdapter | adtech@nvivo.tv | @envivoBidder
eplanningBidAdapter | ainsua@e-planning.net | @chino117
etargetBidAdapter | info@etarget.sk | @etargetse
feedadBidAdapter | mail@feedad.com | @couchcrew-thomas
fidelityBidAdapter | on@fidelity-media.com | @onaydenov
fluctBidAdapter | developer@fluct.jp | @shu22203 
freewheel-sspBidAdapter | clientsidesdk@freewheel.tv | @sfloam 
gammaBidAdapter | support@gammassp.com | @gammassp
getintentBidAdapter | server-dev@getintent.com | @andreykud
glimpseBidAdapter | hello@glimpseprotocol.io | @tim-hm
glomexBidAdapter | integration-squad@services.glomex.com | @nerdbeere
gmosspBidAdapter | dev@ml.gmo-am.jp | @KazuakiM
h12mediaBidAdapter | contact@h12-media.com | @h12media
haxmediaBidAdapter | haxmixqk@haxmediapartners.io | @haxmediagithub
hpmdnetworkBidAdapter | a.fominov@hpmdnetwork.ru | @omnifer
hybridBidAdapter | prebid@hybrid.ai | @hybrid-ai
iasBidAdapter | kat@integralads.com | @raguilar-ias
imonomyBidAdapter | support@imonomy.com | @imonomy
improvedigitalBidAdapter | hb@azerion.com | @jbartek25
inmarBidAdapter | oiq_rtb@inmar.com | @zandree-owneriq
innityBidAdapter | engtat@innity.com | @engtat 
inskinBidAdapter | jgrimes@adzerk.com | @cciocov
invibesBidAdapter | system_operations@invibes.com | @invibes
ipromBidAdapter | support@iprom.si | @iprom-adserver
ironsourceBidAdapter | prebid-digital-brands@ironsrc.com | @lasloche
jcmBidAdapter | george@jcartermarketing.com | @dbemiller
jixieBidAdapter | contact@jixie.io | @jxdeveloper1
justpremiumBidAdapter | headerbidding-dev@justpremium.com | @nwlosinski
komoonaBidAdapter | support@komoona.com | @tzafrirb
krushmediaBidAdapter | adapter@krushmedia.com | @Krushmedia
kubientBidAdapter | artem.aleksashkin@kubient.com | @onaydenov
lifestreetBidAdapter | hb.tech@lifestreet.com | @probably-kira
livewrappedBidAdapter | info@livewrapped.com | @bjorn-lw
lockerdomeBidAdapter | bidding@lockerdome.com | @margsliu
loganBidAdapter | support@logan.ai | @WlsLogan
logicadBidAdapter | prebid@so-netmedia.jp | @logicad
loopmeBidAdapter | support@loopme.com | @EpanchinE
lunamediahbBidAdapter | support@lunamedia.io | @trchandraprakash
luponmediaBidAdapter | support@luponmedia.com | @adxpremium
madvertiseBidAdapter | support@madvertise.com | @NLopezMad
mantisBidAdapter | paris@mantisadnetwork.com | @parisholley
meazyBidAdapter | dima@meazy.co | @dimashirokov
mediaforceBidAdapter | little.grey.goblin@gmail.com | @Niksok
mediagoBidAdapter | fangsimin@baidu.com | @SylviaF
medianetBidAdapter | prebid-support@media.net | @monis0395
mediasquareBidAdapter | tech@mediasquare.fr | @matthieularere-msq
mgidBidAdapter | prebid@mgid.com | @Gaudeamus
microadBidAdapter | prebid@microad.co.jp | @strong-zero
missenaBidAdapter | jney@missena.com | @dev-missena
mobfoxBidAdapter | solutions-team@matomy.com | @francoroy
mobfoxpbBidAdapter | platform@mobfox.com | @mobfxoHB
mobsmartBidAdapter | adx@kpis.jp | @kpis-msa
my6senseBidAdapter | adx@kpis.jp | @my6sense
mytargetBidAdapter | support_target@corp.my.com | @vfedoseev
nafdigitalBidAdapter | vyatsun@gmail.com | @vyatsun
nanointeractiveBidAdapter | rade@nanointeractive.com | @nanointeractive
nasmediaAdmixerBidAdapter | prebid@nasmedia.co.kr | @NasmediaWebtech
nextMillenniumBidAdapter | mikhail.ivanchenko@iageengineering.net | @mhlm
nextrollBidAdapter | prebid@nextroll.com | @abijr
nobidBidAdapter | prebid@nextroll.com | @redaguermas
onetagBidAdapter | devops@onetag.com | @onetag-dev
onomagicBidAdapter | vyatsun@gmail.com | @vyatsun
open8BidAdapter | tdd-adtech@open8.com | @hashedhyphen 
optimeraBidAdapter | kcandiotti@optimera.nyc | @mcallari 
orbidderBidAdapter | orbidder@otto.de | @hendrikiseke1979
otmBidAdapter | @fedotxxl
outconBidAdapter | mfolmer@dokkogroup.com.ar | @TinchoF
papyrusBidAdapter | alexander.holodov@papyrus.global | @HolodovAlexander
performaxBidAdapter | development@performax.cz | @VasekProchazka
piximediaBidAdapter | contact@piximedia.fr | @christopher-allene-piximedia
platformioBidAdapter | siarhei.kasukhin@platform.io | @varashellov
projectLimeLightBidAdapter | engineering@project-limelight.com | @imedvedko
proxistoreBidAdapter | engineering@project-limelight.com | @vincentproxistore
pubxBidAdapter | x@pub-x.io | @Pub-X
qwarryBidAdapter | akascheev@asteriosoft.com | @pro-nsk
radsBidAdapter | prebid@recognified.net | @onlsol
readpeakBidAdapter | devteam@readpeak.com | @readpeaktuomo
reklamstoreBidAdapter | it@reklamstore.com | @ReklamStoreIT
reloadBidAdapter | prebid@reload.net | @mafernandez80
revcontentBidAdapter | aziz@revcontent.com | @AzizSaleh
richaudienceBidAdapter | cert@richaudience.com | @richaudience
riseBidAdapter | prebid-rise-engage@risecodes.com | @lasloche
rtbdemandBidAdapter | rtb@rtbdemand.com | @rtbdemand
rtbsapeBidAdapter | sergey@sape.ru | @ne0n
rtbsolutionsBidAdapter | info@rtbsolutions.pro | @rtbsolutions
seedingAllianceBidAdapter | tech@seeding-alliance.de | @SeedingAllianceTech
seedtagBidAdapter | prebid@seedtag.com | @lauramorillo
segmentoBidAdapter | ssp@segmento.ru | @balabanova-segmento
sekindoUMBidAdapter | nissime@sekindo.com | @nissSK
showheroes-bsBidAdapter | tech@showheroes.com | @vadim-mazzherin
slimcutBidAdapter | support@slimcut.com | @mcamustlr
smartadserverBidAdapter | support@smartadserver.com | @lowendavid
smartrtbBidAdapter | evanm@smrtb.com | @evanmsmrtb
smartxBidAdapter | adtech@smartclip.tv | @Skylinar
smartyadsBidAdapter | supply@smartyads.com | @SmartyAdsSSP
smilewantedBidAdapter | maxime@smilewanted.com | @MaxSmileWanted
somoBidAdapter | prebid@somoaudience.com | @travisbeale
sortableBidAdapter | prebid@sortable.com | @karentnarvaez
stroeerCoreBidAdapter | help@cz.stroeer-labs.com | @Kubitini
stvBidAdapter | prebid@dspx.tv | @onlsol
sublimeBidAdapter | pbjs@sublimeskinz.com | @JeremiePat
synacormediaBidAdapter | eng-demand@synacor.com | @pratik-synacor
taphypeBidAdapter | admin@taphype.com | @aeliox
temedyaBidAdapter | prebid@temedya.com | @vidyome
topRTBBidAdapter | karthikeyan.d@djaxtech.com | @Unnamalai57
tpmnBidAdapter | develop@tpmn.co.kr | @tpmn-admin
trendqubeBidAdapter | cary@trafficroots.com | @Trendqube-ssp
tribeosBidAdapter | dev@tribeos.io | @adnanmiljkovic
trionBidAdapter | mgroh@trioninteractive.com | @grohm33
trustxBidAdapter | paul@trustx.org | @PWyrembak
turktelekomBidAdapter | turktelssp@gmail.com | @turktelssp
underdogmediaBidAdapter | jake@underdogmedia.com | @bottomparm
vdoaiBidAdapter | arjit@z1media.com | @cpuBird
viBidAdapter | support@vi.ai | @alexpashkov
vidazooBidAdapter | dev@vidazoo.com | @uditalias
videofyBidAdapter | support1@videofy.ai | @vladi-mmg
videoNowBidAdapter | info@videonow.ru | @sdbaron
videoreachBidAdapter | hello@videoreach.com | @VideoReach
viewdeosDXBidAdapter | hello@videoreach.com | @GeneGenie
visxBidAdapter | service@yoc.com | @mk0x9
vmgBidAdapter | paul@vmgood.com | @pwecker
voxBidAdapter | prebid@hybrid.ai | @hybrid-ai
vrtcalBidAdapter | support@vrtcal.com | @vrtcal-dev
vubleBidAdapter | gv@mediabong.com | @Roffray
vuukleBidAdapter | support@vuukle.com | @Hamper
welectBidAdapter | nick.duitz@9elements.com | @nduitz
widespaceBidAdapter | support@widespace.com | @ahsun-ahmed
windtalkerBidAdapter | corbin@windtalker.io | @degroat
wipesBidAdapter | contact@3-shake.com | @Tosh39
xhbBidAdapter | daniel.hoffmann@xaxis.com | @srinchiera
yieldoneBidAdapter | y1dev@platform-one.co.jp | @kusapan
zedoBidAdapter | prebidsupport@zedo.com | @skazedo

If you believe you have been included in error, please ping the thread and we will remove you from the list.  We expect enforcement to take the form of non-porting to 5.0, which will commence at the end of May.

**Comment by patmmccann** [comment]
See #6495

**Comment by dliebner** [comment]
Is there documentation for this requirement?

**Comment by patmmccann** [comment]
> Is there documentation for this requirement?

https://github.com/prebid/Prebid.js/issues/5966 and https://prebid.org/blog/prebid-js-release-4-0/

**Comment by curlyblueeagle** [comment]
33acrossBidAdapter will address this shortly. Is there a deadline?

**Comment by gglas** [comment]
We expect 5.0 to be released at the end of May.  Updating the issue to reflect this.

**Comment by bjorn-lw** [comment]
@gglas The Livewrapped adapter fills the "meta" field with data from our front end servers, including "advertiserDomains": https://github.com/prebid/Prebid.js/blob/679793586b68692a312034b686d9b48d1f35afbc/modules/livewrappedBidAdapter.js#L130

**Comment by cesarfd** [comment]
@gglas axonixBidAdapter gets the [response](https://github.com/prebid/Prebid.js/blob/master/modules/axonixBidAdapter.js#L142) complete with the meta object from our own servers.

**Comment by bokos** [comment]
@gglas meta.advertiserDomains is included in the server response for ablidaBidAdapter, so it does not need to be assigned in the adapter
https://github.com/prebid/Prebid.js/blob/master/modules/ablidaBidAdapter.js#L70

**Comment by pratik-synacor** [comment]
@gglas SynacorMedia adapter does support meta.advertiserDomains https://github.com/prebid/Prebid.js/blob/master/modules/synacormediaBidAdapter.js#L259-L261 Is it added to the list by mistake?

**Comment by rokostik** [comment]
Hey @gglas, both the Zemanta adapter (scheduled for deletion in prebid 5) and its replacement, the Outbrain adapter support meta.advertiserDomains ([Zemanta code](https://github.com/prebid/Prebid.js/blob/master/modules/zemantaBidAdapter.js#L143-L145), [Outbrain code](https://github.com/prebid/Prebid.js/blob/master/modules/outbrainBidAdapter.js#L140-L142)). This was done in https://github.com/prebid/Prebid.js/pull/6517. Can you confirm that everything is ok from our end?

**Comment by desidiver** [comment]
Hi @gglas , Yieldmo adapter supports this and it seems to be added to this list by mistake. https://github.com/prebid/Prebid.js/blob/master/modules/yieldmoBidAdapter.js#L215
Thank you.

**Comment by sebaperez** [comment]
E-Planning (eplanningBidAdapter) already supports it: https://github.com/prebid/Prebid.js/pull/6832

**Comment by AdmixerTech** [comment]
PR [#6674](https://github.com/prebid/Prebid.js/pull/6674).  Is it still issue for Admixer ?

**Comment by Skylinar** [comment]
smartx Bid Adapter already supports it: #6547
Please confirm.

**Comment by ignat-one** [comment]
Hi! We have supported advertiserDomains in BetweenBidAdapter: #6791

**Comment by patmmccann** [comment]
> Hi @gglas , Yieldmo adapter supports this and it seems to be added to this list by mistake. https://github.com/prebid/Prebid.js/blob/master/modules/yieldmoBidAdapter.js#L215
> Thank you.

@desidiver I see your fix on #6550 and you're not on this running list but you are on #6512

**Comment by readpeaktuomo** [comment]
Hi @gglas! PR https://github.com/prebid/Prebid.js/pull/6548 addressed this for readpeakBidAdapter. Please let us know if more is required.

**Comment by desidiver** [comment]
> > Hi @gglas , Yieldmo adapter supports this and it seems to be added to this list by mistake. https://github.com/prebid/Prebid.js/blob/master/modules/yieldmoBidAdapter.js#L215
> > Thank you.
> 
> @desidiver I see your fix on #6550 and you're not on this running list but you are on #6512

@patmmccann for #6512 We need to update our documentation but as I understand it the code changes are all there. Thank you.

**Comment by matthieularere-msq** [comment]
Hi,

PR #6843 added support of advertiser domains for mediasquareBidAdapter

**Comment by ardit-baloku** [comment]
@gglas gjirafaBidAdapter and malltvBidAdapter are now compliant
#6853 #6854

**Comment by susyt** [comment]
hi, does PR [#6478](https://github.com/prebid/Prebid.js/pull/6478) satisfy the support or are more modifications needed?

**Comment by andrzejgemius** [comment]
Hello. #6872 adds support for advertiserDomains to the Adocean adapter.

**Comment by stsepelin** [comment]
Hi. #6875 adds support for advertiserDomains to the CointrafficBidAdapter.

**Comment by itaynave** [comment]
@gglas  Aniview Bid Adapter: added meta.advertiserDomains to bidResponse and extended cookie sync logic #6858

**Comment by Giudici-a** [comment]
Hi, #6876 adds support for advertiserDOmains to the AdotBidAdapter.

**Comment by ckbo3hrk** [comment]
Hi, #6899 adds support to adkernelAdn adapter

**Comment by hybrid-ai** [comment]
Hi, 
#6885 adds support for advertiserDomains to the hybridBidAdapter.
#6884 adds support for advertiserDomains to the voxBidAdapter.

**Comment by guiann** [comment]
Done forAdYouLike bidder adapter with:
https://github.com/prebid/Prebid.js/pull/6916 

Merged into prebid 4.42.0.

**Comment by rrelict** [comment]
Hi, #6936 adds support for advertiserDomains to visxBidAdapter.

**Comment by VanCyric** [comment]
Hi, adomain support for buzzoolaBidAdapter is implemented on a server side. You can see the demo here: https://demo.buzzoola.com/prebidjs/

**Comment by zcundiffoiq** [comment]
The inmarBidAdapter is passing the advertiserDomains field inside the "meta" object.  This object is set in our adapter [here](https://github.com/prebid/Prebid.js/blob/master/modules/inmarBidAdapter.js#L80).  Rather than set the meta fields individually in the adapter, it made more sense to format the whole object on our servers and pass it in a completed state.
Is this good, or is there anything else we need to pass version 5.0 verification?

**Comment by patmmccann** [comment]
> The inmarBidAdapter is passing the advertiserDomains field inside the "meta" object. This object is set in our adapter [here](https://github.com/prebid/Prebid.js/blob/master/modules/inmarBidAdapter.js#L80). Rather than set the meta fields individually in the adapter, it made more sense to format the whole object on our servers and pass it in a completed state.
> Is this good, or is there anything else we need to pass version 5.0 verification?

You are good,  thanks!!

**Comment by couchcrew-thomas** [comment]
@gglas @ChrisHuie Just got this one forwarded. FeedAd creates the response object on the server side.
https://github.com/prebid/Prebid.js/blob/master/modules/feedadBidAdapter.js#L232

Can you please take us off this list? Thanks.

**Comment by patmmccann** [comment]
Feedad is gtg, thanks!

**Comment by monis0395** [comment]
Hi @patmmccann , hope you are doing good!  

Adomain support for `medianetBidAdapter` is implemented on a server side. Here is a live screenshot  

![image](https://user-images.githubusercontent.com/11406818/121399349-f5f79e80-c973-11eb-8577-4bff58e00aeb.png)

Let me know if you more details. 

Thanks!

**Comment by patmmccann** [comment]
media.net was no longer on the list, #6986 is the official list and this issue will close as it gets merged
