### ISSUE TITLE
Enhanced NPM Instructions for Prebid Packages

### ISSUE THREAD

**Issue by gglas** [prebid/Prebid.js#6661]
Issue 1780 in the docs repo - https://github.com/prebid/prebid.github.io/issues/1780 - alludes to enhanced functionality for the downloads page, making it easier for publishers to save the various versions of Prebid that they've downloaded.  While the reviewer committee doesn't necessarily think this is a good idea, we do think it would be a good idea to have enhanced documentation for using NPM so that even unsophisticated users are comfortable using it to manage their Prebid packages.  This would include very basic instructions on how to use NPM (from start to finish) and potentially an explainer video to help less sophisticated users.

**Comment by khatibda** [comment]
anything pro npm gets my vote!

**Comment by bretg** [comment]
Taking the explainer video out of scope here. This can be resolved with some tweaks to the README.

Please add some context for the options:
- original install + copy
- as an npm dependency
- website build

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/issues/9333#issuecomment-1349287552 @ChrisHuie please add a warning about referencing non-public object
