### ISSUE TITLE
buyeruid only set on very few requests

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#6684]
I've got a bidder that is asking that buyeruid be sent so as they can "work" properly for s2s, they are telling me that currently buyeruid is only being sent on a very few requests.  I'm trying to find out why this is/ or why it could be.  This is the first time i've come across this and i'm baffled at the moment, only doc i can find is this, but means nothing to me in effect:

https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-video.html#buyer-uids

**Comment by patmmccann** [comment]
Requires a test page or a bunch more detail

**Comment by ChrisHuie** [comment]
@spormeon is this still an issue you are having or can I close?

**Comment by spormeon** [comment]
i gave up on them, no clue if they could be a great bidder or not, at the moment they are taking literally a handful of imps a day

**Comment by gglas** [comment]
understood -- if interested in reopening, we recommend following up on this issue directly with the bidder and having them escalate.
