### ISSUE TITLE
New x-prebid header causing CORS error due to preflights

### ISSUE THREAD

**Issue by pycnvr** [prebid/Prebid.js#6698]
## Type of issue
Bug

## Description
PR #6676 is causing CORS preflights.  The x-prebid header disqualifies ajax requests from being treated as simple.  For efficiency reasons, Epsilon rejects preflights and so all requests fails with CORS errors.  Are there alternatives to implement x-prebid header?  

## Steps to reproduce
Load any page running prebid main branch post 4.37.0 after 5/3

## Test page
https://testmyads.xyz/prebid/6676/test.html

Check network tab on dev console.  There are 3 extra options requests.

### Expected results
https://testmyads.xyz/prebid/6676/test-noheader.html

Same code but removed x-prebid header.  

### Actual results
See Test page.

## Platform details
Prebid 4.37.0

**Comment by smenzer** [comment]
I confirm this is causing issues with ID5 user id module as well - you can see this in the `http://localhost:9999/integrationExamples/gpt/userId_example.html` page when running `gulp serve` on the current master branch.

**Comment by patmmccann** [comment]
Are all these test failures related to https://native.sharethrough.com/assets/sfp-set-targeting.js:0:0 bc of this? It seems not if the revert isn't passing

**Comment by pycnvr** [comment]
Seems unlikely that it's related to the failures, and the tests just failed after the revert, too.

**Comment by patmmccann** [comment]
solved with #6702 

other test failures remain
