### ISSUE TITLE
Prebid, two DFP accounts...

### ISSUE THREAD

**Issue by SallyMennen** [prebid/Prebid.js#671]
We've had great success with Prebid this year (so thanks to all the contributors here) but on Friday I was asked whether it could be used to back-fill another company website which uses a different DFP account to manage direct sales.

This seems completely against what Prebid was built for but I wondered if it was technically possible - the real kicker here is that I'm not allowed to move the mass of Prebid line items into this other DFP account - so I have to use both.

I haven't had chance to mess around with this yet, but if I add the header code to the website and define an ad slot (say xyz), would I be able to render the ads from Prebid (connected to the other DFP account) by adding the following in the 'direct sales' DFP account:

&lt;div id='xyz'&gt;
    &lt;script type='text/javascript'&gt;
        googletag.cmd.push(function() { googletag.display('xyz'); });
    &lt;/script&gt;
&lt;/div&gt;

I'm struggling to think of another way, to clarify all I can do is create a single creative per size in the non-Prebid DFP account and change the code on the page.

**Comment by mkendall07** [comment]
@SallyMennen 
I have not seen this setup before. I don't think you can make this work without specific price point son the DFP line items. So there is really no way to know if a prebid item should serve or a direct campaign. I think the only way to make it work is to have line items created in the client DFP account.

**Comment by SallyMennen** [comment]
Thanks Matt, I've had a test and you're absolutely right. I believe Prebid worked successfully (AdX competing against demand sources) but without being able to send the other DFP account the winning bid we're stuck - unless you have any more bright ideas?! ;-)
