### ISSUE TITLE
Remove handler function console logs

### ISSUE THREAD

**Issue by jmhuddle4** [prebid/Prebid.js#6715]
## Type of issue
Question: Could the `Calling handler function` console.log be removed?

## Description
We are using version 4.9.0 but I recently started noticing a lot of console.logs that print `Calling handler function`. I am not sure if it is intentional, but it fills up our logs in our pipeline.

![image](https://user-images.githubusercontent.com/10017751/117314341-a98ce080-ae54-11eb-9567-37331bb50f6f.png)

![image](https://user-images.githubusercontent.com/10017751/117314729-0b4d4a80-ae55-11eb-8cb0-83d0d6476242.png)

**Comment by bretg** [comment]
@jmhuddle4 - are you sure this is in PBJS code? 

1) Prebid messages are prepended with the blue Prebid box.
2) Neither grep nor github search shows the string "Calling handler function" anywhere in the code base.
3) I don't see this message on my test page

I suspect it's in your page.

**Comment by jmhuddle4** [comment]
Okay thank you for checking
I guess it is just a coincidence when I disable prebid these messages go away
I will double check our implementation
