### ISSUE TITLE
Cannot read property 'getSlotElementId' of undefined (in secureCreatives.js)

### ISSUE THREAD

**Issue by jarnix** [prebid/Prebid.js#6750]
## Type of issue
It seems like a bug but difficult to pinpoint because it's not always happening. I cannot even make a test page.

## Description
We get this error, it's coming from the prebid package (including adapters that we use) :
![image](https://user-images.githubusercontent.com/1163073/117990159-2defcf80-b33d-11eb-86ad-de229ca91c82.png)

When using a local build (gulp serve) we get the full error :
![image](https://user-images.githubusercontent.com/1163073/117990037-11ec2e00-b33d-11eb-8a81-a1aa445db8e8.png)

## Steps to reproduce
With some winning bids (apparently from Criteo, maybe others), we get the error message.

## Test page
The problem does not happen all the time so I cannot make a test page that would be useful.

### Expected results
No error

### Actual results
"Cannot read property 'getSlotElementId' of undefined" in the browser's console.

## Platform details
Prebid 4.35

**Comment by erikdubbelboer** [comment]
@jarnix did you find what caused it and how did you fix it?

**Comment by ausminternet** [comment]
Same here. We just implemented an ad-refresh mechanism after 30s. Sometimes I get the new ad, sometimes I get the new ad and one second later, the ad will dissapear and the errormessage from above will appear, and sometimes I don't get any new ad, just the errormessage.
