### ISSUE TITLE
When floors module is enabled but skiprate set to 100, impressions go down by 25%.  

### ISSUE THREAD

**Issue by pnhegde** [prebid/Prebid.js#6769]
## Type of issue
Question 

## Description
When floors module is enabled but skiprate set to 100, we're seeing ~25% fewer  impressions vs control case where no floors config exists. ie., we're splitting the traffic into two buckets where floors config exists (with a skiprate of 100%) in one of them and the other bucket works without any floor config. We're seeing c. 25% drop in the impression count(winning bids) for the floor config bucket even though no floor value is applied anywhere. What could be the explanation for this behaviour? 

Thanks

**Comment by ChrisHuie** [comment]
Question specific to individual implementation and further conversation addressing this issue in prebid.js slack channel
