### ISSUE TITLE
Bid cache for infinite scroll when individual ad units shows only for visible part of page with different slot id 

### ISSUE THREAD

**Issue by Robot72** [prebid/Prebid.js#6785]
## Type of issue

Question

## Description

I used this solution for developing bid cache at infinite scroll https://docs.prebid.org/dev-docs/examples/adunit-refresh.html
This example propose use one html block for refresh one slot into this html block. I used this solution for bid cache at infinite scroll. In our case infinite scroll is page with next structure:

<img width="761" alt="Screenshot 2021-05-19 at 00 03 48" src="https://user-images.githubusercontent.com/5987937/118723786-7c6a0600-b836-11eb-954a-66598f4cdbac.png">

Our users have visible area only for one top ad unit, content and one bottom ad unit. When user scrolls to next part of page our script remove top ad unit and bottom ad unit html block from previous part of page and add them to current visible area. I am using only one div id for all top ad units and one div id for all bottom ad units In this case before add new top ad unit this logic remove previous top ad unit div element. Also it works for bottom ad unit. 

This solution has issue when we had more than 30 part of page. The page starts working with delays. On mobile devices, the page may hang and a white screen appears.

I can resolve this performance issue when I use different ids div elements for all ad units. 

Does Prebid.js give opportunity to use one adUnitCode for different DFP slots id? Can we have opportunity to define different ad slots in DFP but use one adUnitCode in prebid for them?
If it is possible could you provide simple example?

**Comment by maxetise-tech** [comment]
Yes you can use customSlotMatching 
https://docs.prebid.org/dev-docs/publisher-api-reference/setTargetingForGPTAsync.html

**Comment by Robot72** [comment]
@maxetise-tech thank you for your answer! Do I understand correctly it gives opportunity to use one adUnitCode in prebid for store bids in cache and use different div id for top/bottom ad units?

**Comment by patmmccann** [comment]
this is not prohibited by prebid
