### ISSUE TITLE
What happened to DisctrictmDMX adapter on download page?

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#6799]
The DistrictmDMX adapter seems to have gone from the prebid website download page and there is now only a Districtm one.  Or is "districtm" actually districtmDMX and districtm is just using an alias of Apnnexus now, so no separate adapter need to be "installed/ downloaded"?

**Comment by patmmccann** [comment]
@stevealliance fyi

**Comment by stevealliance** [comment]
@spormeon not sure why this was removed from the Prebid.org website. I know we are going to use the Sharethrough adapter in the future, but no indication to remove the districtmDMX. I'll keep you posted !

**Comment by spormeon** [comment]
@stevealliance ok, Up to P4.39.0  you still bid by the looks, but I notived in P4.40.0 that you drop out of bidding by looks, if any use to you

**Comment by bretg** [comment]
I think what happened here was confusion around case-sensitivity. There was, at one point, two copies of this file: districtmdmx and districtmDMX. This causes problems. I don't know why both versions are gone now, but anyhow restored and confirmed.
