### ISSUE TITLE
Verify the md5 sum

### ISSUE THREAD

**Issue by Rubioli** [prebid/Prebid.js#680]
From [Prebid Download](http://prebid.org/download.html) I customized my prebid with partners that I want.

I got a mail that says:
**verify the md5 sum we have computed before using: XXXXc344a0be6fXXXXXXXXXXX**

Where is it I can/need to verify this?

**Comment by matthewlane** [comment]
If you are on a Unix-like system there may be a utility available called `md5` or `md5sum` that will let you verify this. Open a console and navigate to the directory where the compiled prebid file was downloaded. Within that directory, try entering `md5` followed by the name of the downloaded file. If `md5` doesn't work, try `md5sum` followed by the name of the file. If either of these work they will print the md5 sum of the prebid file on your hard drive, and you can compare that to the md5 sum in your email

**Comment by Rubioli** [comment]
Thanks 👍  Im on a Macbook air and tried this:
`md5 /Users/Liveonly-Navid/Downloads/prebid_20161006091354.js` and got this:
`MD5 (/Users/Liveonly-Navid/Downloads/prebid_20161006091354.js) = 965173a11eaec405fba984783XXXXX` and the number is nor equal to what I got in my mail.

In my mail I the number starts with *4e* while here it starts with *96*.

What Do I need to do when the *md5* is not the same?

**Comment by Rubioli** [comment]
I should to `md5` the `.gz` file. not the `.js` file itself

**Comment by mkendall07** [comment]
@Rubioli 
Yes `md5` the `filename.gz` version of the file for checksum.
