### ISSUE TITLE
Custom prebid adapter question

### ISSUE THREAD

**Issue by Sovica** [prebid/Prebid.js#6818]
## Type of issue
Question

## Description
Hey Team,

So I am looking into creating a custom prebid adapter so before I even start creating one, I wanted to make sure that what I create would be accepted in the prebid repo having in mind your rules - [https://docs.prebid.org/dev-docs/bidder-adaptor.html#required-adapter-rules](https://docs.prebid.org/dev-docs/bidder-adaptor.html#required-adapter-rules)

The adapter would have the following functionality:

1) Bid on display/native inventory on a publishers page.
2) Call a prebid server to get a valid bid.
3) In parallel, do a single call to a GAM tag (this would be a call to some direct campaigns set in GAM and a response would be a simple VAST XML)  and compete this bid with the bid from prebid server.
4) Whichever bid wins, we take that VAST XML response, wrap it in a basic video player and return all the required information back to prebid on the publishers page.
5) End result of the adapter is a basic video player with a VAST tag implemented inside of it which will playback a pre roll in a specific ad slot on the publishers page.

Let me know.

**Comment by bretg** [comment]
Yes, it is a rules violation for bid adapters to call GAM.

If you have a privately-forked version of prebid server, you could consider implementing this logic server-side. But calling GAM won't be allowed on the open source version of Prebid Server either.
