### ISSUE TITLE
DFP details for using with prebid.js

### ISSUE THREAD

**Issue by Rubioli** [prebid/Prebid.js#683]
As I understood, *DFP* play a role when showing/loading ads.

And I wonder, do I need to have a DFP account and make the placements there first ([like this video says](https://www.youtube.com/watch?v=-bfI24_hwZ0)) or?

And if yes, how do I connect my DFP to my prebid?

And just to be sure, What is GPT?

_PS: Im going to test with AOL and DefyMedia_

**Comment by dugwood** [comment]
If you currently use DFP, or AdSense, yes, that could be a good idea. Else, you don't need a DFP setup at all, as AOL and DefyMedia will compete against each other.

You can also, if you have a DFP account, serve Prebid first, and if a floor price is not met you redirect on DFP, without price bucket and the whole setup. Depends on what eCPM you currently have with DFP and if you have DFP campaigns that must be sent before the bidders.
