### ISSUE TITLE
karma peerDependencies requirements - error

### ISSUE THREAD

**Issue by haroxy** [prebid/Prebid.js#684]
Hi

During npm install I get the following errors:

ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer gulp-karma@0.0.4 wants karma@>=0.10 <=0.13

Screenshot: http://privatemedia.co/drop/Cloud9-yFGVcpWDdz-RQiqE2bojZ.png

no matter what I do I can't get past this point.

**Comment by matthewlane** [comment]
From the screenshot it looks like you have node v0.10.42 and npm v1.3.6. Prebid requires at least node v4.x (which ships with npm v2.x) or greater to be installed to build properly (noted here https://github.com/prebid/Prebid.js#build). Updating node and npm should allow you to get past these errors. Please reopen if you still run into errors after that

**Comment by haroxy** [comment]
Similar issue as before after upgrading...
a few more errors to boot though.  scratching my head...

http://privatemedia.co/drop/iZLLGcduAe.png

**Comment by matthewlane** [comment]
karma version 1.3.0 is causing the peerDependency error, as several other karma-releated packages rely on karma ^0.13 being installed. I don't understand how 1.3.0 is getting installed here as `package.json` specifies ^0.13.2 [here](https://github.com/prebid/Prebid.js/blob/master/package.json#L50). Was v1.3.0 left over from a previously incomplete installation? Try a fresh install with `rm -rf ./node_modules && npm cache clean && npm install` within the Prebid directory and let me know if that installs the correct version of karma

**Comment by mkendall07** [comment]
@haroxy 
Did you resolve? You might want to also check if you have a global npm module that's causing the issue. `npm list -g --depth=0`

**Comment by protonate** [comment]
Closing this as answered with the above recommendation to do a fresh install and check global npm packages. If the issue persists please reopen with additional information.
