### ISSUE TITLE
ci/circleci: build — Your tests failed on CircleCI

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/Prebid.js#6844]
## Type of issue

Question

## Description

Circle CI tests fail on browser stack for somethings that are not related with my code changes in PR #6843 . But its rerun options are not available. What am I suppose to do to validate these checks ?

## Steps to reproduce

See PR #6843

**Comment by ChrisHuie** [comment]
@matthieularere-msq just reran it. We have a current pr that hopefully helps with some of these flaky tests
