### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by dugwood** [prebid/Prebid.js#686]
I don't know where to put this, but I don't see where I can post it elsewhere.

In the documentation:
http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.bidderSettings
bidCpmAdjustment is presented only with bidCpm as an argument. It should be presented with its second argument (that would have saved me a few hours!):

    bidCpmAdjustment : function(bidCpm, bid){
      // adjust the bid in real time before the auction takes place
      // console.log('Bidder is: ' + bid.bidderCode);
      return bidCpm * .85;
    }

So that we can create a global function, and attach it to handle all bidders in one place (great for placing a common floor price).

Thanks.

**Comment by mkendall07** [comment]
thanks. I created a ticket for you on the docs repo: https://github.com/prebid/prebid.github.io/issues/107
