### ISSUE TITLE
Same code, different pages, prebid isn't adding targeting

### ISSUE THREAD

**Issue by federicojacobi** [prebid/Prebid.js#688]
Hey guys, I have 2 pages with the exact same code, but one works and the other one doesn't. What am I missing? (Uses DFP)

http://s2.moguldom.com/fe28c847d6d0.html  <- Works
http://s2.moguldom.com/324c0d0dcd02.html <- Doesn't work

Thank you so much!

**Comment by mkendall07** [comment]
They both seem to be behaving the same for me. You are not getting a lot of bids, and when I do get bids I don't see them winning

**Comment by federicojacobi** [comment]
Hey Matt, thanks for the quick response, but I'm not sure this is what's going on.

This is what i'm referring to:
Notice on the second link, prebid NEVER sets the dfp targeting (hb_bidder, hb_adid, hb_pb, hb_size) while the first one, does every single time.

DFP does serve everytime, on both links, but the prebid targeting is what's missing.

**Comment by federicojacobi** [comment]
I hate to be a pain but .... any luck with this?

Thanks!

**Comment by protonate** [comment]
I've tested further and can see a correlation between "no bids" and "no targeting", in which case ads are determined by DFP. The code on the two pages differs by `adUnitCode` so not ever getting bids back for the second page could have something to do with DFP config. If there is no bid in the auction the ad calls will not have `hb_` targeting.

**Comment by mkendall07** [comment]
Closing as no update. Please reopen if you find an issue.

**Comment by aneuway2** [comment]
@federicojacobi - agree this looks like an issue within DFP/inadequate demand from YieldBot. When bids are returned, then key values are set. You can have mock Yieldbot ads show with this tool: http://i.yldbt.com/integration/start?image=on&cid=

Within DFP, make sure that you don't have competing bids that will outbid/override the prebid ads
