### ISSUE TITLE
Prebid server: Custom logic for bidder adapter

### ISSUE THREAD

**Issue by osazos** [prebid/Prebid.js#6881]
## Type of issue

- question
- feature request

## Description
This issue is a question / feature request  in order to let bidder adapters to add custom logic during the PrebidServer buildRequest process.

Actually there is only one method which interacts with the adapter: `transformBidParams()` which is fine but just pass the params set in their config (publisher side).

Can we improve the `transformBidParams()` method signature to pass `adUnit` and `bidRequests`? This way bidder adapters could take full advantage of this callback.

https://github.com/prebid/Prebid.js/blob/bf610f6074137a16fa6e1b6131bf9bac1b3f4943/modules/prebidServerBidAdapter/index.js#L643-L645

## Other information
https://github.com/prebid/Prebid.js/pull/2844

**Comment by bretg** [comment]
This is related to https://github.com/prebid/Prebid.js/issues/6361 -- it's another reason why sometimes bidders need some client-side code even when pushed server-side.

**Comment by patmmccann** [comment]
it appears this is now superceded by the plan here https://github.com/prebid/Prebid.js/issues/6361#issuecomment-984069346

@osazos would that solve?

**Comment by patmmccann** [comment]
tracking on #6361
