### ISSUE TITLE
Add zero value bids to ad server targeting

### ISSUE THREAD

**Issue by patrik-eriksson** [prebid/Prebid.js#6887]
## Type of issue
Question

## Description
Hi!

Bid responses with CPM = 0 don't get added to ad server targeting. Is there a flag somewhere that we could add to enable this? I've searched in the documentation but could not find anything regarding this.

The case we are having is that our network backfills campaigns are running in Xandr and the ad server on this particular site is Google.  Maintaining backfill campaigns in two or more ad servers is a mess that we would like to avoid.

Regards,
Patrik

**Comment by gglas** [comment]
Hey there Patrik,

This is a filter that can be modified here https://github.com/prebid/Prebid.js/blob/7251c9165b3d78d1317be1f41fbe81caade54e42/src/targeting.js#L440 - we will explore adding a feature to make this easier.

best
gareth

**Comment by ChrisHuie** [comment]
Closing with above solution

**Comment by jsnellbaker** [comment]
@gglas Was that change added?  IIRC there was talk about adding a publisher controlled option tied to this new logic, was that also implemented?  Please confirm when you have the chance.  We have a customer who was interested in this feature to allow 0 cpm bids as well.

**Comment by patmmccann** [comment]
I don't think we should be closing issues bc we tell OP they could modify the core code and rebuild prebid. This should stay open as a feature request to make that line dependent on config.

**Comment by patmmccann** [comment]
Should L440 be `      .filter(bid => bid.cpm > 0 && !bid.dealId && ![insert config check here])`

**Comment by bretg** [comment]
Looks good to me @jsnellbaker
