### ISSUE TITLE
Support DFP Premium Same Ad Unit Multiple Slots

### ISSUE THREAD

**Issue by prebid** [prebid/Prebid.js#69]
As a publisher, I would like Prebid.js to support the case where I have one ad unit reused across multiple slots. For example:

```
googletag.defineSlot('/1234/Leaderboard', [728, 90], 'div-gpt-ad-5678-2').setTargeting('Position',['bottom']).addService(googletag.pubads());

googletag.defineSlot('/1234/Leaderboard', [[970, 90],[970, 250],[728, 90]], 'div-gpt-ad-5678-3').setTargeting('Position',['top']).addService(googletag.pubads());
```
(In this case, the same ad unit is served into multiple ad slots)

```
googletag.defineSlot('/1234/Leaderboard', [728, 90], 'div-gpt-ad-5678-2').setTargeting('Position',['bottom']).addService(googletag.pubads());

googletag.defineSlot('/1234/MobileMediumRectangle', [[300, 250],[320,100]], 'div-gpt-ad-5678-2').setTargeting('Position',['bottom']).addService(googletag.pubads());
```

(In this case, multiple ad units serve into the same ad slot)

We need to come up with an example to support the above cases.

**Comment by prebid** [comment]
Proposed solution:

Instead of using `ad unit path` ('/10451498/Leaderboard'), we should use the slot element ID ('div-gpt-ad-1369240995336-2') as the `code` for prebid ad units. 

For example: 
```
var adUnits = [{
    code: 'div-gpt-ad-1369240995336-2',
    sizes: [...]
    bids: [...]
}]
```

If 2 prebid ad units for some reason share the same code (DFP slot element ID) in this case, we'll combine the 2 ad units' result bids together.

**Comment by RobertLippens** [comment]
:+1: this feature request, this is currently a blocking item for us.

**Comment by RobertLippens** [comment]
Update: I have been fiddling around with the source code a bit and have been able to get two ads of different sizes using the same slot with the suggested method above.

```
var rightSlot = googletag.defineSlot('12345/slot/name', [[300, 250]], 'div1').addService(googletag.pubads());

        var topSlot = googletag.defineSlot('12345/slot/name', [[728,90]], 'div2').addService(googletag.pubads());
```

with adUnits defined:
```
{
        code: 'div1',
        sizes: [[300, 250]],
        bids: [
          {
              bidder: 'yieldbot',
              params: {
                psn: 'TOADD',
                slot: 'TOADD'
              }
            }]
    }
```
and 
```
{
        code: 'div2',
        sizes: [[728, 90]],
        bids: [
          {
              bidder: 'yieldbot',
              params: {
                psn: 'TOADD',
                slot: 'TOADD'
              }
            }]
    }
```

The necessary code change appears to be in prebid.js at `setTargetingForAdUnitsGPTAsync` (on line 442).  The for-loop contents can be replaced with:

```
			var adUnitCode = slots[i].getSlotElementId();
			if (adUnitCode) {
				placementBids = getBidResponsesByAdUnit(adUnitCode);
				setGPTAsyncTargeting(slots[i].getAdUnitPath(), slots[i], placementBids);
			}
```
where the adUnitCode is now based on the SlotElementId as suggested, though the GPTAsyncTargeting is still based on the adUnitPath as it was previously.

I didn't see a good way to contribute changes to existing files so I am adding it here to the issue directly in hopes that it will get some attention.

**Comment by mkendall07** [comment]
Hi @RobertLippens 

Thanks for the contributing. I will also update the code to reflect a fallback to `getAdUnitPath()` if  `getSlotElementId()` is empty
