### ISSUE TITLE
Is DFP or an adserver required for using Prebid? 

### ISSUE THREAD

**Issue by jakczuhang** [prebid/Prebid.js#690]
Is it required to have DFP or any adserver with all the line items when using Prebid if we do not plan on doing any targeting or having it compete with direct deals?

**Comment by mkendall07** [comment]
@jakczuhang 
It's not required no. You can simply create an iframe for the ad and invoke `renderAd` with the window of the iframe and winning bid id.

**Comment by dugwood** [comment]
See also: https://github.com/prebid/Prebid.js/issues/683

**Comment by mkendall07** [comment]
Postbid example: http://prebid.org/dev-docs/examples/postbid.html
