### ISSUE TITLE
hb_pb values may be incorrect

### ISSUE THREAD

**Issue by sjccoder** [prebid/Prebid.js#691]
Hi,

We are using prebid.js in post-bidding scenario and have seen that for a few exchanges the hb_pb value s are lower than what we are getting paid. Our impression count matches but it seems exchanges pay us higher at the end of the day. Has anyone experienced this issue before?

Any suggestions would be appreciated.

Thanks,
Neil

**Comment by jaiminpanchal27** [comment]
Hi @sjccoder 
hb_pb values are rounded before sending to DFP. So that can be the reason you are seeing the difference in price. 
You can use [Bidder Setttings](http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.bidderSettings) and [Price Granularity](http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.setPriceGranularity) to customize pbjs implementation.

**Comment by sjccoder** [comment]
Hi Jaimin,
Thanks for your update. Unfortunately that cannot be the case as the rounding error can cause only 1 cent of error. We are seeing an error of ~30 cent in CPMs. We use postbid mostly and do not deal with price granularity.
Thanks,
Neil

**Comment by mkendall07** [comment]
@sjccoder 
Do you have an example postbid ad?

**Comment by mkendall07** [comment]
@sjccoder any other information you can provide. The default rounding rounds down on $0.10 increments, so it's not just a 1 cent rounding.

**Comment by sjccoder** [comment]
Hi Matt,

Our discrepancy is about $0.50 (on $2.50 eCPM). It is almost 20%.

I am attaching our PB script. I really appreciate your help.

Thanks,
Neil
[PB SCRIPT.pdf](https://github.com/prebid/Prebid.js/files/527766/PB.SCRIPT.pdf)

**Comment by GLStephen** [comment]
Are you setting your price granularity properly?

**Comment by mkendall07** [comment]
@sjccoder 
I checked your code and it looks fine. I don't see any reason why you would be seeing a discrepancy. Do you have any other data that proves this out?

**Comment by sjccoder** [comment]
My apologies for a delayed response. For some reason, these notifications were sitting in my junk folder. I do not know what the issue was but when migrated the setup to HB from PB, our reporting seems to be correct now. I guess we can close this issue. Thanks again for your support.

**Comment by jaiminpanchal27** [comment]
Glad to hear that issue is solved. Thanks for update.
