### ISSUE TITLE
Bump babel target versions

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#6913]
## Type of issue
Build related

## Description
#6035 bumped IE. Would it be useful to bump safari to 10, ios to 9 or 10, and ff to 78?

**Comment by ChrisHuie** [comment]
This represents essentially the earliest supported so if it isn't a big deal to not support earlier versions then I cool with it. I don't think that things break the same way in other browsers across versions like in ie though. So I don't think supporting a few extra versions is too impactful but that's without seeing the percentage breakdown from user-agent data..

**Comment by patmmccann** [comment]
I picked these version numbers based on traffic stats; would this lower build size much if at all?

**Comment by ChrisHuie** [comment]
Not sure. I can check though.
