### ISSUE TITLE
OpenX adapter does not pass verizonmediaid in bid request.

### ISSUE THREAD

**Issue by nanek** [prebid/Prebid.js#6930]
## Type of issue
Bug

## Description
OpenX adapter does not pass verizonmediaid in bid request.

## Steps to reproduce
Enable verizon media connectid https://docs.prebid.org/dev-docs/modules/userId.html#verizon-media-connectid

pbjs.getUserIds() returns `{ connectid: "tOwehSrOwhAUJc5zgdsmXE3sTbHfJtBseTSwB-tBW2K9ghF6S0LZ1oE1MMwmG5d4MUfE2oRTeO4e33goY-crQA" }` as expected, and the AOL adapter passes the connectid, however OpenX does not include this value in their bid requests.

https://github.com/prebid/Prebid.js/pull/6490/files#diff-1b7b8529cd571697ee8f92b2d0214da8e41c7ab8a4cb1e87be5db4083dc03ab5R34 I believe should be `connectid:'verizonmediaid'`

## Platform details
All

## Other information
https://github.com/prebid/Prebid.js/pull/6490

**Comment by patmmccann** [comment]
@slimkrazy fyi

**Comment by slimkrazy** [comment]
Hey @patmmccann  - I'm not really sure why this bid adapter is attempting to consume the ConnectID as connectID is not designed currently to be used by any other adapter than Verizon Media adapters. The ID is encrypted and can't be used by other DSPs/SSPs.

In short: Verizon Media had no knowledge of this change and there is no benefit to a publisher if this feature works or not for this bid adapter.

**Comment by patmmccann** [comment]
@bwschmidt fyi

**Comment by bwschmidt** [comment]
@patmmccann thanks for the heads up, i'll check internally and likely have a PR to remove shortly
