### ISSUE TITLE
Beachfront video bids missing creativeId

### ISSUE THREAD

**Issue by nanek** [prebid/Prebid.js#6935]
## Type of issue
Bug

## Description
In Prebid 4.41.0, beachfront video bids are not considered valid. Works fine in Prebid 4.10.0.

![Screen Shot 2021-06-03 at 5 38 20 PM](https://user-images.githubusercontent.com/6188/120715861-3a2a0100-c493-11eb-903b-3621242a0b8f.jpg)

bidResponse requires creativeId to be set. Beachfront adapter tries to pull this from the response.body crid, however as shown in the screenshot below it does not exist in the response.
https://github.com/prebid/Prebid.js/blob/master/modules/beachfrontBidAdapter.js#L81

![Screen Shot 2021-06-03 at 5 35 27 PM](https://user-images.githubusercontent.com/6188/120715876-3f874b80-c493-11eb-88a5-355919417351.jpg)

This appears related to the change made in https://github.com/prebid/Prebid.js/pull/6842

## Platform details
All

## Other information

**Comment by patmmccann** [comment]
@jsalis appears to be from removal of ' || response.cmpId,' ?

**Comment by jsalis** [comment]
Thanks for the fix. Seems I moved too fast with this change.
