### ISSUE TITLE
pubProvidedEids bug prebid4.21.1

### ISSUE THREAD

**Issue by yuvalgg** [prebid/Prebid.js#6955]
## Type of issue

bug

## Description

pubProvidedId doesn't seem to get recognized as a submodule and doesn't add its **eids** to the getUserIdAsEids() call

## Steps to reproduce

Implement the demo page:
https://github.com/prebid/Prebid.js/blame/master/integrationExamples/gpt/userId_example.html

## Test page

see below demo pages

### Expected results
static eids to be printed in the eids section
http://danielle-vallance-b8s4.squarespace.com/prebid-pub?pbjs_debug=true

### Actual results
no eids were printed in the eids section
http://danielle-vallance-b8s4.squarespace.com/prebid-pub-2?pbjs_debug=true

## Platform details

Prebid.js google chrome, windows 10
issue occurs on: prebid4.42.1
issue **does not** occur with the same configuration on prebid4.24.0

**Comment by ChrisHuie** [comment]
Issue self resolved per slack message by initial per who opened issue
