### ISSUE TITLE
How to kill GA events we don't want sent?

### ISSUE THREAD

**Issue by brs14ku** [prebid/Prebid.js#696]
I've tried dropping the event listeners I don't want from this [(file](https://github.com/prebid/Prebid.js/blob/master/src/adapters/analytics/ga.js) probably register another adapter? ) but every event that comes standard still fires. We're hitting our event limit and missing bidWon data which currently is the only information we want in GA. Is there a way to shut off certain events that I'm missing here?  Here is what remains in my [ga.js](https://gist.github.com/brs14ku/5e30c8ced30b89b8b4858be79037466d) 

I've also noticed that logging information from this adapter doesn't log anything which led me to believe this is all being run from another location but tracing the include through AnalyticsAdapter.js and analyticsLoader.js isn't turning up any obvious solutions for me. 

I guess this is part troubleshooting, part feature request for a method or possibly some options to pass to our GA loader that would disable unwanted events.

**Comment by brs14ku** [comment]
I should mention that I have enableDistribution: false set up as the docs suggest.

**Comment by matthewlane** [comment]
It seems like dropping the event listeners as you have done should work. When you mention the standard events still firing, does that mean seeing lines like `MESSAGE: Emitting event for: bidRequested` in the console? And then new Requests data is still showing up in your Google Analytics dashboard when using Prebid with your custom ga.js file?

**Comment by brs14ku** [comment]
@matthewlane correct. I am still seeing the Emitting event notification for bidRequested. It was all still going to GA. I've just shut it off for now and rolled my own event listeners.
