### ISSUE TITLE
Using Prebid.js without a supported Ad Server

### ISSUE THREAD

**Issue by fcolella** [prebid/Prebid.js#6985]
## Type of issue
question

## Description
Is it possible to use Prebid.js without Google Ad Manager, AppNexus, Smart Ad Server or FreeWheel?
If it is, is there any documentation regarding such approach client side? or any guidelines?

Thank you!

**Comment by jsut** [comment]
You can use prebid without any ad server at all, it's just unusual.

The [postbid example](https://docs.prebid.org/dev-docs/examples/postbid.html) shows an example that can get you started. My employers integration was built up starting from that example.

**Comment by gglas** [comment]
@ChrisHuie let's open a corresponding docs issue and build the example there?  (ie. the relevant rendering javascript / event listeners)

**Comment by bretg** [comment]
Here's an example I got to work:

```
        pbjs.que.push(function() {
          pbjs.requestBids({
            timeout: 2000,
            bidsBackHandler: renderEverything
          });
        });

    function renderEverything() {
        var winners=pbjs.getHighestCpmBids();
        for (var i = 0; i < winners.length; i++) {
          renderOne(winners[i]);
        }
    }

    function renderOne(winningBid) {
        if (winningBid && winningBid.adId) {
            var div = document.getElementById(winningBid.adUnitCode);
            if (div) {
              let iframe = document.createElement('iframe');
              iframe.frameBorder = '0';
              div.appendChild(iframe);
              var iframeDoc = iframe.contentWindow.document;
              pbjs.renderAd(iframeDoc, winningBid.adId);
            }
        }
    }
```
Will let better coders take a look before we document an approach.

1) It does assume that the AdUnit.code is the div id
2) I don't think we need a failsafe timeout when there's no adserver.
3) Not sure what iframe attributes we ought to recommend
4) Unclear that `getHighestCpmBids` is the best of the many functions to use for this. I tried getAllWinningBids() and getAllPrebidWinningBids() but they require targeting to be set.
    4a) If it's a partial auction, I imagine a better approach would be to use `getHighestCpmBids(adUnitCode)` and be surgical about which adunits will be displayed.

**Comment by jsut** [comment]
1. This seems like a reasonable assumption, and you can just document that that doesn't *have* to be the case
2. sure
3. you could just use the same attributes that are on the iframe in the [postbid example](https://docs.prebid.org/dev-docs/examples/postbid.html) for consistency as a starting point.
4. I think this is reasonable. None of these integration examples claim to be 'best practices' do they?  If there is a desire to go down that road and have more real world-y, best practice-y examples that seems like another task entirely.

**Comment by ChrisHuie** [comment]
https://github.com/prebid/Prebid.js/pull/7308
