### ISSUE TITLE
BidsCube company does not exist in downloads

### ISSUE THREAD

**Issue by vlaktion** [prebid/Prebid.js#7017]
BidsCube adapter was merged in release 4.43.0 but BidsCube company does not exist in https://docs.prebid.org/download.html

Why? Can you add BidsCube?

**Comment by ChrisHuie** [comment]
@vlaktion this is likely due to a naming issue not making it automatically show up in the downloads. Can take a look a get it figured out

**Comment by bretg** [comment]
The docs PR just got merged, which resolved the issue.  https://github.com/prebid/prebid.github.io/pull/2944
