### ISSUE TITLE
Pbs bid adapter: video hb_size not returned properly

### ISSUE THREAD

**Issue by r-schweitzer** [prebid/Prebid.js#7020]
## Type of issue
Bug

## Description
There are sizes that returning on video as "**undefined**x**undefined**" on server to server and potentially client side as well. Some bidders choose to send back the playerWidth and playerHeight since sizes are not always returned in the bidresponse. Seems that may Prebid should determine to either filter hb_size when a size is not returned or return the playerWidth and playerHeight as a standard.
## Steps to reproduce
Reload page enough time with prebid server and you still see hb_size is not defined properly. 

### Expected results
I would expect either no hb_size or the size of the actual video.

### Actual results
undefined x undefined size or 1x1. Sizes may vary depending on the the adapter or prebid server etc.

## Platform details
All version of Prebid.

**Comment by gglas** [comment]
@mike-chowla we discussed in issue review today -- we think the insertion of undefined is a bug that needs fixing (and it should just be left blank, maybe console log that size is undefined), but wanted to make sure that fix corresponds with the needs in video.

**Comment by bretg** [comment]
@r-schweitzer - a test page would be good. Do you see the 'undefinedxundefined' in the PBS response JSON or is from PBJS?

**Comment by r-schweitzer** [comment]
@bretg Seems to be related to PBS. I can recreate it on this page https://cafedelites.com/cheesy-scrambled-eggs-in-avocado/. The PBS response doesn't come back with hb_size at all

**Comment by bretg** [comment]
@r-schweitzer - spent some time with this and can't make it happen. My thought is that PBS targeting variables aren't used by PBJS. They're only used by mobile apps and AMP. So I don't think PBS is the problem here.

There might be some robustness that we can add to the pbsBidAdapter in https://github.com/prebid/Prebid.js/blob/f50b7ec513fd872c7c9410fdc5bbcee4f4128f54/modules/prebidServerBidAdapter/index.js#L924

```
            let sizes = bidRequest.sizes && bidRequest.sizes[0];
            bidObject.playerWidth = sizes[0];
            bidObject.playerHeight = sizes[1];
```
We should check `sizes` before accessing them as an array. @ChrisHuie - please make this update?

**Comment by dgirardi** [comment]
@ChrisHuie the PBS adapter now sets `playerWidth` / `playerHeight` to the size that was in the request. Does that solve this issue?

https://github.com/prebid/Prebid.js/blob/38446e6f81a867b485f28e822dc3af3673367c1e/modules/prebidServerBidAdapter/index.js#L972

**Comment by ChrisHuie** [comment]
Closing this per pr #7885 -> https://github.com/prebid/Prebid.js/blob/38446e6f81a867b485f28e822dc3af3673367c1e/modules/prebidServerBidAdapter/index.js#L972
