### ISSUE TITLE
Original companion size (ciu_szs) overwritten in prebid video adrequest

### ISSUE THREAD

**Issue by Nicola1976** [prebid/Prebid.js#7025]
## Type of issue
Bug

## Description
We have implemented prebid video on our player according to the [documentation](https://docs.prebid.org/prebid-video/video-overview.html), but we have a strange random behavior on the companion sizes of the vast adrequest.

In about 50% of cases we see that the size companions of the vast call should be these:

![correct_cu_size](https://user-images.githubusercontent.com/14162566/122010886-d7eacd80-cdbb-11eb-9940-d6d873867bb1.png)

are overwritten with the only ones:

![wrong_cu_size](https://user-images.githubusercontent.com/14162566/122010911-de794500-cdbb-11eb-8639-5a1c6692436e.png)

Below is an SS:
 
![wrong_cu_size_request](https://user-images.githubusercontent.com/14162566/122010959-eafd9d80-cdbb-11eb-8e94-a43fdfda3c3c.png)

Have you had similar cases?

Could you let us know if it could be a behavior related to prebid video that somehow returns specific ciu_szs overwriting the original ones?

Thanks a lot for any suggestion
Nicola

**Comment by gglas** [comment]
hey @Nicola1976 would it be possible for you to send over a test page or more details of the prebid implementation?  It's hard for us to validate the bug without being able to see everything that's interacting on the page.

**Comment by Nicola1976** [comment]
Hi, thanks a lot. Can you provide an ip to enable it on our internal test page?

**Comment by ChrisHuie** [comment]
@Nicola1976 jsbin or just anyway for me to see your code is fine
