### ISSUE TITLE
Support Prebid Server stored impression scenario

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#7027]
## Type of issue

Bug / Feature Request

## Description

A bidder is not available in the `bidIdMap` if there's no `bid` configure on the client.

https://github.com/prebid/Prebid.js/blob/d649149b181223ba42423fb19a8b569ebbdd97fc/modules/prebidServerBidAdapter/index.js#L865-L872

The `bidRequest` is undefined and throws a error later on when trying to access the `bidId`

https://github.com/prebid/Prebid.js/blob/d649149b181223ba42423fb19a8b569ebbdd97fc/modules/prebidServerBidAdapter/index.js#L1004

## Steps to reproduce

1. Configure an `adUnit` with *Bidder A* for server side and a stored impression id
2. The stored impression server side requests *Bidder B*
3. If a bid is returned an exception will be thrown `cannot access bidId of undefined`

Sample config on client side

```js
const adUnit = {
  mediaType: { banner: { sizes: [[300, 250]] } },
  ortb2Imp: { ext: { prebid: { storedrequest: { id: 'ad-slot-1' } } } },
  bids: [ { bidder: 'Bidder A', params { } }  ]
}

const s2sConfig = {
  // ...
  bidders: [ 'Bidder A', 'Bidder B' ]
}
```

And on server side

```json
    {
      "id": "ad-slot-1",
      "banner": {
        "format": [    ]
      },
      "ext": {
        "prebid": {
          "bidder": {
            "Bidder B": {
              "placement_id": 1234
            }
          }
        }
      }
    }
```

## Test page

None

### Expected results

- No exception is thrown
- *Bidder B* is properly handled

### Actual results

Exception

## Platform details

- prebid.js 4.43.0
- prebid server java 1.66.0

## Other information

- #6494 initial implementation for stored impressions

**Comment by muuki88** [comment]
There is a simple workaround that feels wrong, but works :joy: If you add an "empty"  bid with the corresponding bidder code, it works

```js
const adUnit = {
  mediaType: { banner: { sizes: [[300, 250]] } },
  ortb2Imp: { ext: { prebid: { storedrequest: { id: 'ad-slot-1' } } } },
  bids: [ 
     { bidder: 'Bidder A', params { } },
     // the client adapter is not required to make this work!
     { bidder: 'Bidder B', params { } },
  ]
}

**Comment by muuki88** [comment]
I was thinking about the `bidders` array that is already present in the `s2sConfig`. From a developer perspective this looks like the play to "allow" bidders.

**Comment by gglas** [comment]
Issue review came to exact same conclusion -- just need a volunteer to add the feature.

**Comment by muuki88** [comment]
If you use the workaround mentioned in https://github.com/prebid/Prebid.js/issues/7027#issuecomment-861405428 you also need to make sure that

- if you enable the `gdprEnforcement` module to add the server side bidders to the vendor exceptions, as there's no gvlid if the bid adapter is not imported
- add all vendors to the `bidders` list in the `s2s` config

**Comment by dgirardi** [comment]
related to https://github.com/prebid/Prebid.js/issues/7688

**Comment by bretg** [comment]
The plan is to solve with with #7688.

- Logging: doesn't need to have a special message. Let's just make sure a console log indicates the bid response from the unexpected bidder.
- GDPR:
    - cookie_sync:  I propose letting PBS handle Purpose 1 enforcement. Pass the list of known bidders-in-page on s2sConfig.bidders. Let PBS look up the GVL ID from the biddercode. For custom client-side aliases, the JS /cookie_sync code should map the alias to the actual server-side adapter. e.g. `pbjs.aliasBidder('appnexus', 'newAlias')` would result in the cookie_sync sending appnexus rather than newAlias.
    - For the auction, PBS should look up GVLID for each bidder. It should not need to be enforced client-side, and should not be necessary in the request. We should not have to add a vendor-exception for PBJS to initiate the PBS auction. PBS is expected to handle legal basis for every bidder.

**Comment by muuki88** [comment]
Sounds good to me ☺️

Should we close this issue then as a duplicate?

**Comment by bretg** [comment]
Good progress has been made on #7688, but we've found that the scenario in this issue needs a little more work.

What we'd like to support is 

```
const adUnit = {
  mediaType: { banner: { sizes: [[300, 250]] } },
  ortb2Imp: { ext: { prebid: { storedrequest: { id: 'ad-slot-1' } } } },
  // "look mom, no bids array!"
}
```

PBJS-core would need to be be updated to deal cleanly with the scenario that an adunit doesn't contain bids. It's possible that one adunit in an auction contains bids while another doesn't. I'd suggest:
- if no bids array and no ortb2Imp, log a major warning
- if no bids array but at least ortb2Imp is specified, log an informational entry

The pbsBidAdapter would need to be updated to deal with it: if no bids array is found in the adunit, create the openrtb without imp[].ext.prebid.bidders

**Comment by bretg** [comment]
Discussed with @dgirardi - we agreed that the signal for the pbsBidAdapter to emit a stored-imp-only imp object should be implicit: if an AdUnit contains no bids array and does contain ortb2Imp, it will add the imp object.

We considered having an explicit signal (e.g. s2sConfig.bidders: ["*"]) but realized that could get confusing in a scenario where some adunits are server-only and some are a mix of client and server.

**Comment by bretg** [comment]
Also related to the [Prebid.less](https://github.com/prebid/Prebid.js/issues/5001) proposal
