### ISSUE TITLE
Expected bid.ad content

### ISSUE THREAD

**Issue by asurovenko-zeta** [prebid/Prebid.js#7028]
## Type of issue
Question

## Description
Can I provide in **bid.ad** non HTML content? Instead **<script> ... </script>** set directly script content?
Like **bid.ad: 'any script content without <script> in start and end of the content'**

Thanks!

**Comment by mkendall07** [comment]
@asurovenko-zeta no I believe markup is expected here because it's injected into an iframe which expects markup. Not aware of a script based only solution. Curious why you need that? What's the use case?

**Comment by asurovenko-zeta** [comment]
@mkendall07 one of our partner can send different types of amd, usual markup and raw js code. I believe the solution in this situation might be take js code in **script** tag. How do you think, it will work in all cases?
