### ISSUE TITLE
Outstream video fails with Prebid server because of newly introduced bug

### ISSUE THREAD

**Issue by samuel-palmer-relevant-digital** [prebid/Prebid.js#7037]
## Type of issue
Bug

## Description
_Both_ `adUnit.renderer` and `adUnit.mediaTypes.video.renderer` are required after this change (instead of only one of them):

https://github.com/prebid/Prebid.js/pull/6896/files

So it looks like the `||` should be a `&&`.

## Steps to reproduce

Use PBS with an ad unit with both `renderer` and `mediaTypes.video.context: 'outstream'` set. You'll see console-errors saying:

`Outstream bid without renderer cannot be sent to Prebid Server.`

## Test page
None

### Expected results

It should work, as before.

### Actual results

There's an error and the video-object isn't sent to PBS => Outstream video doesn't work for PBS anymore :(

## Platform details
Prebid 4.42+

## Other information
#6896

**Comment by ChrisHuie** [comment]
closing with #7038
