### ISSUE TITLE
Postbid: Iframe not being rendered on chrome after warning -> [Violation] Avoid using document.write()

### ISSUE THREAD

**Issue by fcolella** [prebid/Prebid.js#7049]
## Type of issue

bug

## Description
Hi! I'm having a problem with postbid. 
After winning a bid it renders perfectly on Firefox, but when trying to do the same on Chrome the iframe is rendered empty and I get the [Violation] Avoid using document.write() warning. 
Is there something I can do to fix this on Chrome?
The problem seems to be on the renderAd function -> e.write(a)
Thank you!

## Steps to reproduce
Using postbid, try to render the winning bid on the latest Chrome (Version 91.0.4472.114)

### Expected results
Render the winning bid's creative

### Actual results
Render empty iframe

## Platform details
prebid.js v4.39.0-pre
Chrome Version 91.0.4472.114

**Comment by gglas** [comment]
@fcolella would you mind providing a test page for us to have a look at this?

**Comment by spormeon** [comment]
for what its worth, chrome started throwing this warning for me also last week but related to a different iframe, actually a google iframe that they we're using doc. write on with AMP

**Comment by bretg** [comment]
I'm not seeing this. Made a test page that calls renderAd and am using Chrome 91.0.4472.114 -- no doc.write warnings.

We discussed in a meeting yesterday and agreed that chrome breaking doc.write would disable the internet. 

@fcolella - we need more detail about the scenario. Maybe it's safeframe?

**Comment by spormeon** [comment]
did you look in "verbose" it lives in there , not warnings or errors:   
![DevTools_-_cheftalk_com_ads_final_-4](https://user-images.githubusercontent.com/8503167/122970971-6811af80-d386-11eb-9a6d-d56c3669d54e.png)

**Comment by bretg** [comment]
Yeah, the verbose warning is there. But it's been there for years...

https://developers.google.com/web/updates/2016/08/removing-document-write

Am throwing this back to Gareth for prioritization with the dev team.

**Comment by bretg** [comment]
However,  @fcolella - this doc.write warning that's been coming out for years is probably not related to your specific issue.

You need to give us more detail. The real problem is most likely something else.

**Comment by spormeon** [comment]
it was in the "real" warnings for me 13 days ago ( just check my moan at the google amp team), then a update to chrome and it moved back to verbose

**Comment by ChrisHuie** [comment]
Came across this article that I thought might help with the issue here but not entirely sure (https://developers.google.com/web/updates/2016/08/removing-document-write). Good read on document.write by the chrome team though

**Comment by patmmccann** [comment]
closing as tracked on #8337
