### ISSUE TITLE
oneVideo partner ads makes request to not exist page of the publisher website. How to fix it? 

### ISSUE THREAD

**Issue by Robot72** [prebid/Prebid.js#7064]
## Type of issue
Question

## Description
Some ad script made request to not exists page. This request made to a page with URL postfix **/undefined**
<img width="1185" alt="Screenshot_2021-06-17_at_17 16 40" src="https://user-images.githubusercontent.com/5987937/122775708-164c2500-d2b3-11eb-9d37-d7d774db4610.png">
vidible.min.js is initiator of this requst
It looks like **oneVideo** partner ads makes this request, if I check initiator chain. 
Do you know how to fix it?

## Steps to reproduce
Open a website from USA Dallas region.

**Comment by gglas** [comment]
@adam-browning @DeepthiNeeladri this seems adapter related -- would you mind having a look?  Also @Robot72 if you could provide a test page that would be great for troubleshooting, i'm not sure this will be enough for them.

**Comment by adam-browning** [comment]
Hi @gglas @Robot72 ,
The vidible endpoint is part of our Outstrem Renderer.
Please send us a test page so I can take a look.

Cheers
Adam

**Comment by Robot72** [comment]
Hi @adam-browning 
I cannot sent this link here (in public). How can I send it to you privately?

**Comment by adam-browning** [comment]
Adam.browning@verizonmedia.com

**Comment by adam-browning** [comment]
Hi @Robot72,
Did this work out in the end?
