### ISSUE TITLE
Optimera RTD targeting values being returned incorrectly

### ISSUE THREAD

**Issue by mcallari** [prebid/Prebid.js#7079]
## Type of issue
Bug

## Description
The targeting values are being passed as a single string with added encoding for each value, instead of a comma-delimited string of values. This is causing only the first key value to be understood by GAM. The rest are ignored since they do not match the actual value.

## Steps to reproduce
When reviewing the ad request, the values look like: value1,%20value2,%20value3,%20value4,%20value5 instead of value1,value2,value3,value4.

### Expected results
In the ad requestion optimera_key=value1,value2,value3,value4

### Actual results
In the ad requestion optimera_key=value1,%20value2,%20value3,%20value4

## Other information
https://github.com/prebid/Prebid.js/pull/7080

**Comment by ChrisHuie** [comment]
#7080

**Comment by ChrisHuie** [comment]
closing with merge of #7080
