### ISSUE TITLE
I have 2 other comments on the issues section and I can't comment or edit them in any way!

### ISSUE THREAD

**Issue by fcolella** [prebid/Prebid.js#7087]
## Type of issue
question

## Description
I opened 2 other issues:
https://github.com/prebid/Prebid.js/issues/7049
https://github.com/prebid/Prebid.js/issues/6985
and I'm not allowed to comment or anything, people must think I'm rude hehe.
Do I need to get permission from someone to be able to comment on the issues?

## Steps to reproduce
Try to comment or modify your own issue

## Test page
https://github.com/prebid/Prebid.js/issues/7049
https://github.com/prebid/Prebid.js/issues/6985

### Expected results
Comment/Modify your own issues

### Actual results
Can't do anything on the issues

**Comment by bretg** [comment]
@fcolella - this is odd. Did you try logging out, clearing github.com cookies and logging back in? There aren't any special permissions needed for community members to comment on threads.

**Comment by gglas** [comment]
@fcolella did bret's advice work?  can we close this issue?
