### ISSUE TITLE
Old bids for removed AdsUnits are being returned

### ISSUE THREAD

**Issue by atchang** [prebid/Prebid.js#709]
Hi, we are in the process of upgrading from v0.8.1 to v0.13.0 and noticed that we were processing a lot of bids for adUnits that were removed from Prebid. It appears under some race conditions (we have multiple calls to requestBids on a single page so my guess is that is is timeout or maybe an adblocker interfering with the page) that not all of the previous bids are cleared. It looks like there is a new data structure holding the bids now _bidsReceived.

This is the code I put on the page to get rid of the issue.

```
// Remove AdUnit from queue (we don't want to make prebid bid requests for that ad unit)
pbjs.removeAdUnit(slotname);
// Clear out old bids
pbjs._bidsReceived = $.grep(pbjs._bidsReceived, function (n, i) { return n.adUnitCode!=slotname});

// Make request now
pbjs.requestBids({ bidsBackHandler: function(bidResponses) { processPrebidResponse(bidResponses); } });

```

**Comment by mkendall07** [comment]
@atchang 
Can you explain the side effects your seeing because of this?

**Comment by atchang** [comment]
Extra bid of info: I confirmed that they are all stale because the requestTimestamp in the bids are all from before my most recent call to requestBids (our site can make multiple call per page as we refresh the ads when new content is AJAX'd onto the page).

I guess the side effects are limited to the fact that you can end up with stale (and potentially used) bids being passed on to DFP since there is no such check at the moment. I guess it isn't a huge issue overall as this isn't probably a common use case. I just found it weird that the bidsBackHandler was returning bids for an adunit that I wasn't making requests for. That combined with the fact that call requestBids for a specific adUnitCode will actually make requests for all adUnitCodes (https://github.com/prebid/Prebid.js/issues/590) made us uncertain about the behavior of prebid in more "surgical" bidRequests where we might want to only make some requests for some Prebid partners on some ad units (and keep the others as is).

Now that you made me think about this more, I guess it isn't much of an issue for most people (even for us now that we know the behavior).

**Comment by atchang** [comment]
Actually, I take that back about it not being that common to most people as originally I thought it was only happening for when you remove an ad unit, but now I realize it is happening on any ad unit (just when there is a potential timeout of prebid).

When I expanded my rollout of upgrading prebid v0.13.1 from roughly 40% to 100% of our traffic. We saw the number of bids per minute (we have a lot of internal logging of bids) spike by like 80%. When I checked to see how many times we were processing an old bid, I found we are doing it roughly 1M time per minute. Now we do have a special case in that we also have a failsafe in case prebid itself doesn't return at all... but still that's a lot of stale bids.

**Comment by mkendall07** [comment]
@atchang 
What API are you using to get bids? 

We'll implement a bid time to live param and have it default to 59 seconds. This will prevent processing older bids. I don't believe clearing them out completely is ideal once they are received, because they might end up going unused.

**Comment by atchang** [comment]
We are processing the bidResponses returned to us via the bidsBackHandler callback. Unfortunately, adding a TTL param of 60 second won't help our specific use case as we typically request a new bid every few seconds (users view slideshows or quizzes on our site - here is an example http://stars.topix.com/slideshow/16642?no_cover=1&layoutmode=prod-active).

Maybe if we had a way to flush all the bids for a particular adslot out of the system (although, I understand this would be adding a new public API endpoint that you would have to maintain in the future).

Another, possibility, would be to be able to flush out a single bid (i.e. the winning bid), then I could just use all the other existing bids without worry about accidentally reusing a bid that was already used (saving the time it would take to make another round of request to all 12 prebid partners we have).

I understand that we are a bit of an outlier in use case. So we are ok if you make no change and we handle it on our own. So far our changes from stock Prebid is about 2-3 lines of code. If it becomes more... we might consider forking Prebid to track our minor changes to stock Prebid (I doubt it will be more than a few dozen lines of code, but it might be easier to keep track of this way each time we upgrade to the latest version).

**Comment by dugwood** [comment]
You may try this fix: https://github.com/prebid/Prebid.js/pull/735

It fixes the fact that the timeout of first auction (if one bidder respond too late) will clear the second auction. Say that the first auction has a timeout of 1500ms, but all bidders respond within 1000ms, then a second auction is launch with same timeout. The timer from the first auction isn't cleared, so it will fire 500ms after that, instead of 1500ms.

**Comment by protonate** [comment]
The timeout fixes @dugwood mentions are merged to master. However you will still see data from the reporting APIs (`pbjs.getBidResponses`, `pbjs.getAdServerTargeting`) from previous auctions if that placement was not included in any subsequent auction. Put another way, the bids arrays will retain data for the most recent auction that a placement participated in. We do this to avoid race conditions when waiting for a response from an ad server. If that response has not yet been received and we initiate another call for request bids, if we were to remove all bids then the ad server response for the first auction will throw an error as the prebid demand data was removed before the ad could render.

Your solution for filtering the response for the most recent auction is the recommended approach. Closing, please reopen with any further info or questions.
