### ISSUE TITLE
Proposal: Add Fledge support

### ISSUE THREAD

**Issue by iamnewton** [prebid/Prebid.js#7092]
## Type of issue

Feature Request/Question

## Description

As some of you may or may not know, Google is deprecating 3rd-party cookies in 2022. With that change, Google has started working alongside the W3C in order to provide a set of APIs to allow a privacy-safe auction.  This new type of auction will run client-side/on-device on a publisher's page.  Google is working on setting up an Origin Trial (called Fledge) in the near future to test this feature as part of the core web APIs, but in the meantime, we, at Magnite, are working on a polyfill to test out the impact of these changes and measure the success of this new type of auction.  And as part of this effort, I’ve created a polyfill for the proposed changes and was hoping to add this to PreBid as a module that a publisher would be able to include to help test out these new features.

After talking with some of the contributors to PreBid, I determined it would be best to do the following and would love some feedback on the approach:

1. Need to create a hook for the `renderAd` function since we want to use Fledge as a “last look” in the case where PreBid auction beat out GAM and right before it renders the PreBid ad, we can check that against a Fledge-based auction to see what happens
2. Was going to add this as a module since this, at this moment, is not meant to be part of the core infrastructure
3. Since this bit of technology (Fledge) will only be available to more modern browsers (Chrome only and greater than v92) is there any way to either exclude this from the larger system since I know PreBid has to support IE11, or at least document that this will not work on anything other than Chrome?

## Platform details

\>=5.x

## Other information

https://github.com/prebid/Prebid.js/pull/7091

**Comment by jsut** [comment]
I would imagine that the module should detect whatever it needs to be able to run at run time, and do nothing if the browser it's running in can't support it. I don't know if prebid itself has any functionality to help you with that detection or not. 

I'd expect that a publisher should be able to include your module in their build of prebid, and have it not break if someone uses a browser that doesn't support fledge or your polyfill. The module documentation should state clearly what it's limitations are.

**Comment by gglas** [comment]
Given the announcement of the delays, we're thinking this becomes a less pressing issue -- but happy to incorporate into the roadmap

**Comment by pm-harshad-mane** [comment]
https://github.com/JoelPM/prebid-td/blob/main/PrebidFledge.md mentioning here for the quick reference

**Comment by gglas** [comment]
We'll be closing this issue and picking the conversation up in https://github.com/prebid/Prebid.js/issues/7634
