### ISSUE TITLE
"Message: latency for placmeent code:" is misspelled

### ISSUE THREAD

**Issue by seichengrun** [prebid/Prebid.js#71]
As you can see in the screenshot below, 'placmeent code' is misspelled and should be spelled 'placement code'

![screen shot 2015-10-20 at 10 37 37 am](https://cloud.githubusercontent.com/assets/15215421/10610623/acbf5448-7716-11e5-8e65-a3d4bf322877.png)

**Comment by hjeong12** [comment]
fixed in #75
