### ISSUE TITLE
Add refferer URL parameter

### ISSUE THREAD

**Issue by Deimos01** [prebid/Prebid.js#710]
Hello,

Is it possible to add an extra parameter to specified the referrer URL in the adcalls ?
Some of my publishers are using multiple iframes so the referrer is not the url of the page for some SSP (Rubicon, AOL ...) so those SSP don't bid a lot ...
I know it's possible to "hardcode" the URL for the ADX tags, for example : 
```

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>  
<ins class="adsbygoogle"  
style="display:inline-block;width:300px;height:250px"  
data-ad-client="ca-pub-XXXXXXXXXXX"  
data-ad-slot="XXXXXXX"  
data-override-format="true"  
data-page-url = "http://www.mywebsite.com"> </ins>  
<script>  
(adsbygoogle=window.adsbygoogle || []).push({});  
</script>
```

Should it be possible to do the same for Prebid.js ?

Thank you

**Comment by mkendall07** [comment]
@Deimos01 
There is no default referrer param, each bidder may or may not implement this differently. You'd have to contact them to see if they support it.
