### ISSUE TITLE
Prebid file not built properly whith 5.2.0 version

### ISSUE THREAD

**Issue by prebidtappx** [prebid/Prebid.js#7102]
## Type of issue
Bug / Question

## Description
I'm trying to build the current version of Pbjs (5.2.0) with the :tappx adapter module, but it doesn't work correctly. When I add the Prebid.js file, I get this message

`{"error": "Prebid file not built properly", "requestId": "4fb188dd-a1a1-4bc3-8188-ad2222deb922"}`

I tried to build another module and got the same.
Maybe I'm doing something wrong?

## Steps to reproduce
Build Prebid.js (5.2.0) from https://docs.prebid.org/download.html selecting any adapter (I've tried with :tappx, AdTrue, RTBHouse...) and try implement in `hello_world.html` file

## Test page
N/A

### Expected results
Prebid.js working properly

### Actual results
`{"error": "Prebid file not built properly", "requestId": "4fb188dd-a1a1-4bc3-8188-ad2222deb922"}`

## Platform details

- Pbjs 5.2.0
- Chrome Browser

**Comment by holms** [comment]
Check issue here: https://github.com/prebid/prebid-js-build-generator/issues/16

Despite my efforts to add needed modifications for Dockerfile.biulder it still fails to get a prebid 5.2.0 bundle. I need attention from someone in there. I'd send pull request but I'm unable to make it work.

**Comment by prebidtappx** [comment]
Hello @ChrisHuie 

we've tried with prebid 5.3.0 release and it's working right.
From our side, you can close the issue.

Thank you!

**Comment by holms** [comment]
But 2.5.0 doesn't work?

**Comment by prebidtappx** [comment]
No, it doesn't work. With 5.2.0 I'm still getting `{"error":"Prebid file not built properly","requestId":"95bc81e4-ba02-485a-a6fc-435e206818ad"}`

**Comment by holms** [comment]
Same here :)

**Comment by ChrisHuie** [comment]
@prebidtappx @holms will look into this. Just now seeing this thread.

**Comment by ChrisHuie** [comment]
closing with 5.3 resolution
