### ISSUE TITLE
getElementIdBasedOnAdServer checks for GAM too naively

### ISSUE THREAD

**Issue by jsut** [prebid/Prebid.js#7109]
## Type of issue

Bug

## Description

If you have a banner and a native unit in the same auction, without using an ad server, the banner is rendered, then removed from the page after the native unit is rendered.

## Steps to reproduce

I've been messing around with native ads in an effort to see if i can support tracking viewability for them without an ad server present (see #6909) While doing that i have run into some strange behaviour trying to make a single page with banner, video and native ads on it, to test the viewabilty code.  I have stripped my integration page down to only a banner and a native unit, which you can see here: https://test.kabob.ca/native

If you throw a breakpoint on the code in the html, on the call to renderNativeAd. You can see that the banner is displayed before the native ad renders, but then it disappears afterwords, with the following in the console.

caught TypeError: window.googletag.pubads is not a function

The culprit seems to be getElementIdBasedOnAdServer, which just looks for window.googletag to be defined (which none of my code does, but adagio.js which is injected by the appnexus adapter apparently does for some reason.  This code should probably use isGptPubadsDefined, from utils.js, rather than just check if window.googletag is defined.

This might not actually fix the problem i'm running into with the banner getting unrendered, but either way this seems like a bug regardless.  I also have no idea if I should be including the universal creative on the page like this.  It feels gross to me, but it seems like I have to do it to get renderNativeAd, since pbjs.renderAd doesn't know how to make sense of the native ad's bid response on it's own, at least all the way's i tried to use it.

## Test page

https://test.kabob.ca/native

### Expected results

both ads visible

### Actual results

only the native ad is visible

## Platform details

tested in firefox on macos

**Comment by gglas** [comment]
@osazos would you mind having a look at this?

**Comment by jsut** [comment]
@gglas I can submit a PR for this narrow issue, yeah. Unfortunately it doesn't actually resolve the larger problem of the banner ads disappearing when the native ad renders. It's entirely possible i'm doing something totally stupid in my example code.  It doesn't seem like native without an ad server is much of a thing.  I haven't spent any time digging in to what's making the ad disappear yet, but maybe I can soon.
