### ISSUE TITLE
RTD Module - Priority submodules exit hook before relevant submodules are called. 

### ISSUE THREAD

**Issue by karimMourra** [prebid/Prebid.js#7117]
## Type of issue
Bug

## Description
Assume a configuration with 2 RTD Modules A and B, where module A is configured with `waitForIt` set to true, and module B is not. If module A's implementation of `getBidRequestData` is synchronous, then Module B will be skipped because the auction will resume before its call to `getBidRequestData` is ever made. 
This is a flaw in the implementation of the Core RTD module. The for loop in which each module's `getBidRequestData` function is called must end before the auction is resumed. 

In fact, if the publisher were to change the order in which the submodules are added in the data providers array, module B's `getBidRequestData` has the chance to be called before the auction is resumed. 

## Actual Result
The data provider that does not have `waitForIt` set to `true` is never called on. 

## Expected Result
Both data providers are called on regardless of `waitForIt`. `waitForIt` should only signal that the auction will wait for the data to be obtained; the provider should be called on regardless of the value of this flag.

## Steps to reproduce
Using a Prebid Config which includes
```
realTimeData: {
     auctionDelay: 100
    dataProviders: [{
        name: "permutive"
        params: {acBidders: []}
        waitForIt: true
    },  {
        name: "jwplayer"
    }]
}
```
and a video ad unit such as 
```
var videoAdUnit = {
    code: 'video1',
    sizes: [640,480],
    mediaTypes: { video: {} },
    bids: [
      {
        bidder: 'appnexusAst',
        params: {
          placementId: '123456',
          video: {
            id: 123,
            skipppable: true,
            playback_method: ['auto_play_sound_off']
          }
        }
      }
    ]
  };
```
Load the ad units and make a bid request:
```
pbjs.addAdUnits(videoAdUnit);
pbjs.requestBids();
```

Observe that in the Core RTD Module (rtdModule/index.js) the `exitHook` function defined on line 286 is called before the 2nd iteration of the `relevantSubModules.forEach` loop defined on line 266. 

## Test page
n/a

### Expected results
The expected behavior is that the `relevantSubModules.forEach` loop defined on line 266 ends before `exitHook` is called. 

### Actual results
`exitHook` is called after the first loop, before the 2nd loop runs causing the auction to resume before the 2nd module is ever called on. 

## Platform details
Chrome
Pb v4.31

## Other information
n/a

**Comment by gglas** [comment]
@karimMourra this seems significant -- would you be able to work on a PR to address this ?

@allanjun this seems like it significantly affects RTD modules, would you mind collaborating with Karim?

**Comment by karimMourra** [comment]
Hi @gglas I don't have capacity at the moment to tackle this. I will be able to address in a month or so when #6271 is finished

**Comment by bretg** [comment]
@karimMourra - we appreciate that you've posited the actual code problem, but I don't understand the app problem. Given this config:

```
realTimeData: {
     auctionDelay: 100
    dataProviders: [{
        name: "permutive"
        params: {acBidders: []}
        waitForIt: true
    },  {
        name: "jwplayer"
    }]
}
```

What should happen is that both permutive and jwplayer should be invoked by RTD core back-to-back. It should return control to core when either of these conditions is true:
- permutive returns
- 100ms has elapsed

**Comment by karimMourra** [comment]
Hi @bretg the app problem is that the data provider that does not have `waitForIt` set to true is never called on. 
The expected behavior would be that both data providers would be called on.

**Comment by karimMourra** [comment]
@bretg I updated the description to describe the application problem. It now has an `expected behavior` and an `actual behavior ` section

**Comment by bretg** [comment]
This was discussed in PBJS committee. We agreed that in the case of all 'waitforit' modules being immediately ready, then RTD modules that did not have the `waitforit` flag could be called but would be given no time whatsoever. They must return immediately or be skipped.
