### ISSUE TITLE
Adapter updates to version 5

### ISSUE THREAD

**Issue by lunamedia** [prebid/Prebid.js#7120]
Our adapter on prebid.org is marked "not in 5.x"
Am I correct in understanding that we have to add the return of the meta object to the responses ? Or should there be some other changes ?

**Comment by ChrisHuie** [comment]
Looks like there are a couple. Adomain #6650 , Floors #6465 , and Video Params #6512 I believe are the needed changes. Think that's it if you haven't already previously addressed any of these.
