### ISSUE TITLE
Console error occurs in Incognito mode when localStorage is unavailable

### ISSUE THREAD

**Issue by mnishihan** [prebid/Prebid.js#7128]
## Type of issue

Bug

## Description

When third party cookies are blocked in Incognito Mode of latest Google Chrome Browser, a console error occurs in Prebid.js while accessing unavailable `localStorage` object.

## Steps to reproduce

1. Open Chrome in Incognito Mode and make sure third party cookies are blocked.

![Screen Shot 2021-07-01 at 5 30 20 PM](https://user-images.githubusercontent.com/1173288/124118390-17d7d300-da93-11eb-8c51-4752b1d5a397.png)

2. Navigate to https://kizi.com/games/moto-x3m?idhbtest & open Console tab in Developer Tools
3. Accept cookies using **I Accept** button when asked.

![Screen Shot 2021-07-01 at 5 35 48 PM](https://user-images.githubusercontent.com/1173288/124118505-3b9b1900-da93-11eb-8a06-11665117e143.png)

4. Find the DOMException error in Console

![Screen Shot 2021-07-01 at 5 22 19 PM](https://user-images.githubusercontent.com/1173288/124118633-5d949b80-da93-11eb-90bb-0f8a2d9835e5.png)

## Test page

https://kizi.com/games/moto-x3m?idhbtest

### Expected results

No error should be thrown when `localStorage` object is unavailable.

### Actual results

`DOMException` error is thrown.

## Platform details

* Prebid.js -> Version 4.20+
* OS -> macOS High Sierra, Version 10.13.6 (17G14042)
* Browser -> Google Chrome, Version 91.0.4472.114 (Official Build) (x86_64)

## Other information

I've been tracked down the code where this error is thrown and that is located [here](https://github.com/prebid/Prebid.js/blob/4.43.x-legacy/modules/adagioBidAdapter.js#L105) in `adagioBidAdapter.js` module of `4.43.x-legacy` branch.

I've also noticed that this issue has been fixed in latest master branch via merge of #7065 

@osazos As we haven't migrated to latest 5.x.x release yet, it would be really helpful for us, if you could fix it in 4.43.x-legacy branch to be included in upcoming 4.43.x release.

**Comment by osazos** [comment]
Hi @mnishihan, I will merge the fix in the legacy branch and pull request for it.

**Comment by mnishihan** [comment]
Thanks a lot @osazos. I'll be looking forward to get this fix merged. (Y)

**Comment by ChrisHuie** [comment]
resolved with merge of #7140
