### ISSUE TITLE
Removing a bid adapter

### ISSUE THREAD

**Issue by slimkrazy** [prebid/Prebid.js#7146]
## Type of issue
Question

## Description
Hi folks,

Just wondering what has been done in the past regarding dropping support for existing adapters? Let's say a supply partner decides that they want a rebrand _and_ they want to totally change up their adapter in a backwards incompatible manner (i.e - config structure). The easiest way to deal with that is to simply start from scratch with a new adapter, but is there some sort of policy that we'd need to adhere to regarding keeping the old one alive for a certain amount of time? Thinking logically about this, it would make sense to have at least a short period of time where both adapters are in the codebase, right? Has anybody ever simply dropped an adapter from the codebase before?

**Comment by patmmccann** [comment]
There are several examples of this, adform and zemanta in pb5 release notes
for example. It is a breaking change and the pr would be labeled for a
major version.

**Comment by slimkrazy** [comment]
Thanks @patmmccann. I'll close this ticket.
