### ISSUE TITLE
Can not set sendStandardTargeting=false when using defaultBidderSettings

### ISSUE THREAD

**Issue by derdeka** [prebid/Prebid.js#715]
When registering defaultBidderSettings from an custom adapter, we can not ommit the standard targeting.

The configuration in the adapter is:
```javascript
const bidderSettings = {
	alwaysUseBid: true,
	sendStandardTargeting: false,
	suppressEmptyKeys: true,
	adserverTargeting: [
		{ key: 'keyXYZ', val: (bidResponse) => bidResponse.keyXYZ }
	]
};
bidmanager.registerDefaultBidderSetting('adapterXYZ', bidderSettings);
```

I guess there is a bug in [bidmanager@L155](https://github.com/prebid/Prebid.js/blob/0.13.1/src/bidmanager.js#L155):
```javascript
if (typeof bidderSettings.sendStandardTargeting !== "undefined" && bidder_settings[bidderCode].sendStandardTargeting === false) {
```
should be
```javascript
if (typeof bidderSettings.sendStandardTargeting !== "undefined" && bidderSettings.sendStandardTargeting === false) {
```

**Comment by snapwich** [comment]
I had this fix as part of another branch that got put on hold for a bit, I've cherry-picked the relevant commit and will open a pull-request for it now.  Sorry for the inconvenience.
