### ISSUE TITLE
New Rhythmone error on S2S

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#7155]
On P5.1.0  this error has started to appear,  is this newly introduced or is something up?  If its purely there for "info" that there is "no bid", don't really see the point of it?

![DevTools_-_cheftalk_com_ads_final_](https://user-images.githubusercontent.com/8503167/124907964-ae028080-dfe0-11eb-847a-8ee7de1e9dd7.png)

**Comment by gglas** [comment]
hey @spormeon would you mind opening an issue on the PBS board instead of the JS board?
