### ISSUE TITLE
Adapter removed in 5.0 release

### ISSUE THREAD

**Issue by parisholley** [prebid/Prebid.js#7159]
We issued a PR against master here for the mantis adapter to adhere to 5.0 changes:

https://github.com/prebid/Prebid.js/pull/6969

though it seems the 5.0 branch removed our changes, is it still not in compliance?

**Comment by ChrisHuie** [comment]
@parisholley Sorry, for this issue. This adapter must have been accidentally removed. I will create a new pr to add back to 5.0 today and update docs. 👍
