### ISSUE TITLE
Adapters for non bidding tags

### ISSUE THREAD

**Issue by johngeorgewright** [prebid/Prebid.js#72]
Hey there,

I was wondering if you could foresee your framework being used, not just for bidding adapters, but also for custom tagging solutions too? IE, we add certain information to DFP calls that are custom to a user/device/journey etc. They *may not* need to make a request anywhere, just simply add some tags to the DFP call. One example would be that we send certain tags dependent on the users' browser resolution.

Do you think that Prebid.js should really be used just for bidder tags, or can you envisage adding other custom tags? It would make sense to me that amongst your code base you are already doing something like this and it would be nice to keep everything in one place. If so, how would you go about it?

**Comment by prebid** [comment]
Hi @johngeorgewright are you referring to a Data provider adaptor type of integration for enriching the ad requests? apologies on the delay.

**Comment by protonate** [comment]
Closing this, please reopen if there is anything to add.
