### ISSUE TITLE
Add-on support

### ISSUE THREAD

**Issue by protonate** [prebid/Prebid.js#721]
## Type of issue

Feature Request
## Description

Members of the Prebid Developer Community may have utility scripts they wish to share with the project. An "Add-on" feature would provide a means of incorporating this code. An example of this surfaced in #496 with [debug tools](https://gist.github.com/cwbeck/bdea9f22ceed8af489fb047f357f77cc) from @cwbeck and @brondsem.

While useful for developer builds, publisher production builds can also benefit from the choice to add optional features or keep the file size down.
### Expected results

An "add-on" script can be placed in a `./addons/` directory and then be incorporated into the build through a simple standardized API. This then provides the "add-on" functionality as an optional feature in the build. Configuration can be kept in an `addons.json` file at project root. Config could also be available through feature flags passed to `gulp build`.
## Other information

See discussion of "render.js" in Issue #496.
See this gist: https://gist.github.com/cwbeck/bdea9f22ceed8af489fb047f357f77cc

**Comment by mkendall07** [comment]
+1. 

Why limit it to debug though? We could add additional functionality too right?

**Comment by protonate** [comment]
Yup, we could open this up for optional features in production builds and provide publishers with the choice of adding a feature or keeping the file size down. I'll update description.

**Comment by mkendall07** [comment]
this will be address with prebid 1.0 modules.
