### ISSUE TITLE
playerSize format on Video bid request

### ISSUE THREAD

**Issue by guiann** [prebid/Prebid.js#7217]
## Type of issue
Question.

## Description
When requesting a video ad, publisher can input a unique video size. But the bid request to bidder adapters is sending an array of arrays, which would mean we can receive multiple sizes. Is that expected? And why would multiple size would be needed?  

## Steps to reproduce
Setup a simple video ad request with a playerSize like [640, 480]. See the bid request sent to bidder adapters.

## Test page
on this page:
https://adyoulike.github.io/Tag/prebid/video_instream

the player size is:
`playerSize: [640, 480],
`
### Actual results
and the video mediatype params in bid request are:
` {playerSize: **[[640, 480]]**, context: "instream"}`

### Expected results
 the video mediatype params should be:
` {playerSize: **[640, 480]**, context: "instream"}`

## Platform details
Tested with Prebid 4.45 and prebid 5.4

**Comment by ChrisHuie** [comment]
closing with #7227
