### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by roablep** [prebid/Prebid.js#722]
## Type of issue
Documentation bug

## Description
In [Publisher API reference - pbjs.bidderSettings](http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.bidderSettings), a link to the Ad Ops documentation is dead. 

It currently links to http://prebid.org/dev-docs/adops.html, but should be http://prebid.org/adops.html

## Steps to reproduce
- Visit [link](http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.bidderSettings)
- Read section 2.2. adserverTargeting
- Click on link "AdOps documentation"

### Expected results
Visit http://prebid.org/adops.html

### Actual results
Visit http://prebid.org/dev-docs/adops.html, a dead page

## Platform details
All

**Comment by dugwood** [comment]
You can also create a PR against https://github.com/prebid/prebid.github.io if you know how to do a PR :-)

**Comment by mkendall07** [comment]
Submitted at the docs site: https://github.com/prebid/prebid.github.io/issues/113
