### ISSUE TITLE
BetweenBidAdapter sharedid support was accidently(?) removed in Prebid 5.0?

### ISSUE THREAD

**Issue by egsk** [prebid/Prebid.js#7221]
## Type of issue

Question
## Description

Hello! We have noticed that one of the last of our pull requests (see https://github.com/prebid/Prebid.js/pull/6531) was excluded from latest release of Prebid (see https://github.com/prebid/Prebid.js/commit/412277f72b97cab72644cb4a009f58067a165899#diff-233e78fe3ed7377b70d8f5dce715c669d72e08e90006af8b33151d35ab1c239f), but description of the realese contains opposite information:

> * BetweenBidAdatper: added sharedid support (#6531)

Was it removed by a reason, or by mistake? What should we do to return sharedid support to BetweenBidAdapter?

**Comment by ChrisHuie** [comment]
@egsk I believe this is related to issue #6640

**Comment by patmmccann** [comment]
discussed in a meeting today, tacked down to @NothingIsMatter commit #6808
