### ISSUE TITLE
IX too large GET requests with Prebid 5.6.0

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#7231]
## Type of issue

Bug

## Description

When `banner.sizes` or the number of ad units requested get too big, then the bid request fails with a 400 HTTP status.
This is the same as #5663 , which got fixed, but somehow introduced again.

My hypothesis is that the GDPR consent string takes up a large portion of the request.

It worked with 4.43.0

## Steps to reproduce

- Create a 5 ad units with 10 sizes each

## Test page

- Go in mobile mode
- Go to https://gutefrage.h5v.eu/460/

### Expected results

Request to casalmedia works

### Actual results

Request to casalmedia returns 400

## Platform details

- prebid.js 5.6.0

## Other information

- Same issue as in #5663

**Comment by muuki88** [comment]
Hopefully @ix-prebid-development can take a look :heart:

**Comment by cd0n0van** [comment]
Hi @muuki88 - thank you for flagging! We are taking a look into this now.

**Comment by gglas** [comment]
@cd0n0van were you guys able to address this?

**Comment by umakajan** [comment]
@gglas this was resolved in https://github.com/prebid/Prebid.js/pull/7805, I will close this issue
