### ISSUE TITLE
make choosing optional targeting keys simpler

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#7249]
## Type of issue

Feature request / question

## Description

In #6485 a few key values were marked as optional inlcluding `hb_source`. This key value was until recently for no use to our pubs as well, because prebid server wasn't used. Prebid server has gained a lot of traction and is now used for more and more publishers. `hb_source` can be used to differentiate in reports between client and server side adapters.

All our publishers and other publishers we know use the Ad Manager (mostly GAM) as the first source for reportings and troubleshootings. Removing `hb_source` from the default keys requires every publisher to add the default keys in their prebid configuration, which is cumbersome and error prone.

An example `allowTargetingKeys` config may look like this

```
targetingControls: {
    allowTargetingKeys: [
      'BIDDER',
      'AD_ID',
      'PRICE_BUCKET',
      'SIZE',
      'DEAL',
      'SOURCE',
      'FORMAT',
      'CACHE_ID',
      'CACHE_HOST'
    ]
}
```

What I'm also unsure about is the other key values, e.g. native key values. Are they needed to be set as well? E.g. making the list even longer.

### Expected results

`hb_source` is again part of the default targeting keys

## Platform details

- Prebid 5.x

## Other information

- #6496
- #6485

**Comment by patmmccann** [comment]
We want publishers to consider the keys they need; hb_source is certainly gaining traction but for many publishers can be inferred from hb_bidder or is always set to 'client'

**Comment by muuki88** [comment]
Inferring from `hb_bidder` may be possible for single publishers or if the setup is the same for _all_ setups. From my experience this is never the case. Neither as a single publisher, nor as a sales house. Usually we run A/B tests and/or roll out features step by step. The `hb_source` is a generic solution that doesn't require any extra work.

My argument is that this is something publishers shouldn't care about and the additional work for all publishers that use prebid server and their ad manager as reporting source doesn't justify this minor savings in ad manager requests. With `enableSendAllBids: false` these are merely a few bytes. ( compared to the horrifying creatives I have seen :stuck_out_tongue: )

**Comment by patmmccann** [comment]
How about if we make it so that you only have to specify the keys that are incremental from the defaults instead of all keys if you don't take the default?

**Comment by muuki88** [comment]
That would be a very nice solution 😻

**Comment by bretg** [comment]
The problem here is that `allowTargetingKeys` overwrites the default set of keys as described in [the docs](https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html#setConfig-targetingControls):

```
When a publisher defines targetingControls.allowTargetingKeys, this replaces the constant CONSTANTS.DEFAULT_TARGETING_KEYS and can include optional keys defined in CONSTANTS.TARGETING_KEYS
```
The proposal here is to add a new option that incrementally adds to the defaults rather than requiring the user to restate all the defaults. So if all they want to add is hb_source, the command would be:
```
pbjs.setConfig({
  targetingControls: {
    addTargetingKeys: [
      'SOURCE'
    ]
  }
});
```
