### ISSUE TITLE
Show warning if bidCpmAdjustment is set for AOL bidder

### ISSUE THREAD

**Issue by marian-r** [prebid/Prebid.js#725]
## Type of issue
Suggestion

## Description
After the recent update of AOL adapter made in #653, the bid price adjustment is not possible on the client side and it has been moved onto backend. In the PR I suggested a note to be included in the release notes, but I expect that can be not enough and some publishers may over look that.

So, I would suggest showing a warning in the console if the publisher has configured `bidCpmAdjustment`, saying something like:

_Warning: bidCpmAdjustment is active for the AOL adapter. As of Prebid 0.14, AOL bids may already be in net – please contact your accounts team to confirm._

This will help publishers to prevent potential issues after the upgrade.

@mkendall07 @matthewlane what do you think?

We are more than happy to create a PR asap for it to be included in 0.14.0, but I just wanted to check first.

**Comment by mkendall07** [comment]
@marian-r 
Feel free to submit the PR. I think you have time to include it into 0.14.0. We are targeting end of the month release. Thanks

**Comment by marian-r** [comment]
Awesome, thanks 👍

**Comment by mkendall07** [comment]
@marian-r 
Can you drop me an email, I have a question that is unrelated to this change. You can find my email in my profile. Thanks!

**Comment by dugwood** [comment]
Seems dangerous to me: this forbids the floor price principle. If you can't set a floor price in AOL backend, then you can't say «I don't want bids under $X.XX» by returning a zero value.

**Comment by mkendall07** [comment]
@dugwood 
It's just a warning displayed. It can still be used.
