### ISSUE TITLE
Prebid.org excluded from DFP GDPR settings

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#7269]
Not really sure what to do with this and not sure if even really effects anything but it seems all the DFP GDPR setting have completely changed and pretty much all "IAB" ones are being "excluded" in the fact that they are not selected ( obvioulsy someone will argue that there is a choose a user can make but seems dirty tricks to me)  

Could effect 000's of people who don't bother looking in there and I'm presuming its stopping "personalised ads" etc?

Its more for info than anything else, but must effect somethings?

"Prebid.org (IAB only)" is on the list of excluded/ not selected:

![Google_Ad_Manager_-_Privacy___messaging_🔊-2](https://user-images.githubusercontent.com/8503167/128349534-fe5a7c36-4b4c-4bb6-a95d-a674abfe594f.png)

**Comment by patmmccann** [comment]
I think this is a question for your cmp

**Comment by bretg** [comment]
GAM just imported the entire GVL list, but it's not relevant for creative validation. There's never any element of any creative that comes from prebid.org. Closing.
