### ISSUE TITLE
Use of Codacy

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#7272]
## Type of issue
Feature request

Circle ci puts linting errors in a difficult to read, time consuming to run report. I made a pr to a diff project and noticed this cool tool called Codacy commenting on my PR with change requests in line. I would love it if we had that

https://github.com/wp-media/wp-rocket/pull/4232/files#diff-1409b3483ac4a5faf550dc0d71115e5d699e66cd3fea8fc6a3e77cca1aa5d1b7

**Comment by ChrisHuie** [comment]
Yeah. Seems like a pretty cool tool. Integrates directly with CircleCI and github actions. Could essentially replace lgtm and add the additional linting/static testing interface. Not sure how pricing would work since its per person though. Could look into this if you think it worth exploring and liked the experience that much.

**Comment by ChrisHuie** [comment]
So followed up on this and apparently the free version for open source does not include the inline comments. That is only in the paid version.

**Comment by patmmccann** [comment]
how much does it cost

**Comment by ChrisHuie** [comment]
$15 a month.

**Comment by patmmccann** [comment]
cool let's buy it

**Comment by bretg** [comment]
I've signed us up for the 14-day trial. If we like it, will pay for it.

**Comment by dgirardi** [comment]
I do not like it. This pr failed checks after this was enabled:

https://github.com/prebid/Prebid.js/pull/7712/checks

The correct "fix" here is to figure out how to trick the linter into not seeing the 'issue'. Problem is that codacy is a pain to run locally (it makes thousands of network calls, it's been running ~20 minutes for me, no ETA). So my best option is to try some obscure syntax, push, see if it passes and retry.

IMO it should either accept what eslint accepts, or it should be run as part of `gulp test` and not take forever to run. I am not looking forward to fighting with a linter after each PR.

**Comment by bretg** [comment]
Ok, I've removed Codacy's access to our repo. Let the debate continue here and we can try again if desired.
