### ISSUE TITLE
bid.timeToRespond ends up being equal to the responseTimestamp value

### ISSUE THREAD

**Issue by cliffliang** [prebid/Prebid.js#729]
## Type of issue
Bug

## Description
In bidmanager.js, addBidResponse function, the bid.requestTimestamp can be set to null if pbjs._bidsRequested doesn't contain the bidder in getBidSetForBidder. This causes bid.timeToRespond to end up as a huge number.

**Comment by dugwood** [comment]
Do you forgot to add the bidder in the call to `pbjs.addAdUnits`? Can you provide a test case?

**Comment by dugwood** [comment]
Also it's a duplicate of #643 IMHO

**Comment by mkendall07** [comment]
@cliffliang closing this as a duplicate of  #643
