### ISSUE TITLE
404 from haso.pubmatic.com with PubMatic adapter

### ISSUE THREAD

**Issue by adamnewsnow** [prebid/Prebid.js#73]
Hi,

We're testing prebid.org and trying to get it set up to integrate with our PubMatic account.

We see a request go off to http://ads.pubmatic.com/AdServer/js/gshowad.js OK, but that generates a request to, eg:

http://haso.pubmatic.com/ads/<pub ID>/GRPBID/index.html?SAVersion=1000&pageURL=<page URL>&inIframe=1&pubId=<pub ID>&kltstamp=2015-10-20%2018%3A55%3A42&timezone=2&screenResolution=2560x1440&ranreq=0.7003979368600994&adslots=<ad slot data>&lmk=1445360142996

...but that results in a 404. Consequently, progKeyValueMap is not populated a JS error results.

Can you suggest what the problem could be here?

**Comment by mkendall07** [comment]
Hi @adamnewsnow,

Can you share your bidder settings that you are using for Rubicon? Feel free to message me privately.

**Comment by prebid** [comment]
@adamnewsnow, we've run into the same problem when running on localhost:xxxx. The `:` in the domain messes things up and there's nothing we can do from our end, because it sits within their ad servers/CDN. But if you try loading it in normal domains it should render fine. Could you let us know if this is the case? Thanks!

**Comment by adamnewsnow** [comment]
Hi - no not running on localhost or with a port specified.

NB we've also discovered that PubMatic's gshowad.js contains a hardcoded list of publisher IDs - maybe they need to whitelist us in order for us to be able to use prebid.org?

**Comment by prebid** [comment]
Sorry on the delay - do you mind emailing us the tag ID setup that's causing the problem? - paul@prebid.org

Thanks!

**Comment by mkendall07** [comment]
I'm going to close this issue, it turns out that PubMatic needs to whitelist the pub before they can use the Adapter. We should add a note in the adapter page for it.
