### ISSUE TITLE
Is SmartRTB not yet supported by Prebid 5?

### ISSUE THREAD

**Issue by slotties** [prebid/Prebid.js#7300]
## Type of issue
Bug Request

## Description
The JS-File is missing for SmartRTB: 
- https://github.com/prebid/Prebid.js/blob/master/modules/smartrtbBidAdapter.md (works)
- https://github.com/prebid/Prebid.js/blob/master/modules/smartrtbBidAdapter.js (missing)

## Steps to reproduce
- Open Download Page for Prebid 5.9.0 (https://docs.prebid.org/download.html)
- Select SmartRTB and a random other module
- Click on the Download Button
-> a broken File is being downloaded

Chosing only SmartRTB works, but the adapter is missing in the file.

## Test page
none 

### Expected results
A note that the bid adapter is not yet supported in prebid 5. Or a working file.

### Actual results
No file :(

## Platform details
Any

## Other information
-

**Comment by patmmccann** [comment]
SmartRTB was removed from prebid 5 for failure to pass advertiser domain.

**Comment by patmmccann** [comment]
fyi @evanmsmrtb
