### ISSUE TITLE
Passing metadata to the adapter

### ISSUE THREAD

**Issue by noamtzu** [prebid/Prebid.js#7306]
## Type of issue
Question

## Description
How I can pass a metadata to the adapter (in my wrapper) and get him back as part of the winning bid response?
For example, I would like to pass metadata to the adapter such as the adapter id in my system and be able to read him as part of the winning bid response.
I could not find any documentation for that.

### Expected results
Chain adapter metadata in winning bid response

### Actual results
None

**Comment by patmmccann** [comment]
Are you a publisher or an adapter writer?

**Comment by noamtzuberi** [comment]
SSP that provide tech (in this case wrapper based on prebid)

**Comment by noamtzu** [comment]
Hi @patmmccann , any new? Thank

**Comment by noamtzu** [comment]
Hi @ChrisHuie ,Can you assist?

**Comment by patmmccann** [comment]
Just write what you want to pass to your bid request object

eg https://github.com/prebid/Prebid.js/pull/7343/files

**Comment by noamtzu** [comment]
Hi @patmmccann ,
Thank you for your answer.
I think I didn't explain myself well, let me to rephrase.

I'm a Wrapper that opening a prebid auction with a several bidders (for this example: riseBidAdapter & openxBidAdapter ).
How can I add to riseBidAdapter & openxBidAdapter their ID in *my system* so when I'll get an events for them (like bid,nobid,win) I'll we able to extract this data from the event object?

**Comment by noamtzu** [comment]
@patmmccann @ChrisHuie , Any new?

**Comment by noamtzu** [comment]
@patmmccann @ChrisHuie , Any new?
