### ISSUE TITLE
Criteo adapter crashes on video bidRequest if skip is 0

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#7307]
## Type of issue

Bug

## Description
When the `skip` property is set to `0` and `params.video` is undefined then the Criteo adapter crashes.

https://github.com/prebid/Prebid.js/blob/6aa63d6a9f941971bd730e4a21026e6ae4d2a32e/modules/criteoBidAdapter.js#L324

is responsible for this as `0` is _falsy_, thus triggering the second statement, which doesn't guard against `undefined` params.

Same goes for `startdelay`

https://github.com/prebid/Prebid.js/blob/6aa63d6a9f941971bd730e4a21026e6ae4d2a32e/modules/criteoBidAdapter.js#L328

## Steps to reproduce

```js
{
  adUnit: {
    mediaTypes: {
      video: {
        context: 'outstream',
        playerSize: [ [300, 250]  ],
        mimes: ['video/mp4', 'video/MPV', 'video/H264', 'video/webm', 'video/ogg'],
        minduration: 1,
        maxduration: 30,
        playbackmethod: [2, 3, 4, 5, 6],
        placement:
        api: [1, 2, 3, 4, 5, 6],
        protocols: [1, 2, 3, 4, 5, 6, 7, 8],
        skip: 0
      }
    }
  }
}
```

### Expected results

Criteo adapter doesn't crash if one bid is misconfigured.
Also `0` is a valid configuration option.

### Actual results

:boom: :fireworks:  :boom: 

## Platform details

* prebid 5.9.0

**Comment by leonardlabat** [comment]
Hello @muuki88 

Thanks for filling the issue, we'll prepare a fix very soon.

**Comment by dzhang-criteo** [comment]
Hello @muuki88 ,

It should now be fixed so maybe we could close this issue?

**Comment by muuki88** [comment]
Thanks for the quick bug fix :kissing_heart:
