### ISSUE TITLE
Prebid Error: no analytics adapter found in registry for ga

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#731]
When I use prebid.js downloaded from http://prebid.org/download.html , the Google Analytics adapter is missiing and I get: 

Prebid Error: no analytics adapter found in registry for ga

**Comment by SallyMennen** [comment]
I don't believe the adapter is currently included in this download.

**Comment by mkendall07** [comment]
Currently we don't build with GA. Closing as dup of #616

**Comment by headerbidding** [comment]
Is there any reason why it is being de-emphasized?

**Comment by mkendall07** [comment]
GA really isn't a great tool for doing this type of analysis, so we haven't focused on it.

**Comment by headerbidding** [comment]
OK

**Comment by bboigienman** [comment]
What tool do you recommend for bid analytics ?

**Comment by rwlaschin** [comment]
Hi, we are looking at doing GA for a first pass setup, what's the alternative?  Do we need to implement our own module?
