### ISSUE TITLE
Download page - strongly recommended modules

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#7318]
Many modules are believed to be strongly recommended and should only be carved out of prebid in special cases. I think we should default check those all to on at the download page. 

This issue is to create a list of them. Tentatively, I suggest

Consent Management
Consent Management USP
GDPR enforcement
Floors
FPD Enrichment
Pre-Auction

Also, Can we move RTD modules to their own section and out of General modules? 

Finally SmartRTB ia missing the not in 5.x flag

**Comment by bretg** [comment]
Ok, merged this PR - we can refine the recommended modules in PBJS and Publisher's forums.
