### ISSUE TITLE
Appnexus ads delivered randomly

### ISSUE THREAD

**Issue by philipWr** [prebid/Prebid.js#7326]
## Type of issue
Question

## Description
In our functional tests we use Appnexus as a bidder and as a placement we use `placementId: 13144370` (based on example from here https://docs.prebid.org/dev-docs/getting-started.html).
Since 28th July we have problems with flaky tests. The issue is that the ads are randomly delivered.
Few weeks back we observed similar issues but then suddenly without any changes in our code, ads were delivered always.

Do you know if recently anything has changed with the configuration of ads?

## Steps to reproduce
Refresh test page and take a look at the bottom of the test page

## Test page
http://dev.testcommon.insideall.com/functests/appnexusads.html

### Expected results
Appnexus prebid.js ads should be displayed at the bottom of the test page.

### Actual results
Appnexus prebid.js ads delivered randomly

**Comment by patmmccann** [comment]
@philipWr by randomly, do you mean sporadically? 

@jsnellbaker what are your thoughts, should we move the example response to a prebid domain?

**Comment by jsnellbaker** [comment]
@patmmccann Just to ensure I understand, can you clarify more what you mean?  Do you mean changing the example pages to not use the appnexus bidder?  Or something else?

**Comment by patmmccann** [comment]
Yes, do you think that would be wise for prebid.org to build out? 

Any thoughts on AppNexus infrastructure not responding all the time? Is it more likely bid request filtering server side or perhaps a problem with the example?

**Comment by jsnellbaker** [comment]
If they're able to do something else, then that's fine.  I'm still having a bit of trouble seeing what they'd do, but they can proceed with removing this type of dependency.

As for the appnexus placement, it's possible there may be some filtering going on if they're frequently reusing the placement with a quick series of tests.  There may be other factors as well, but I'd need to see the debugging results to know for sure - which I don't know if we can retroactively capture given how open this placement is used.  From my own tests, I haven't seen issues with it; it returned a bid each time and subsequently rendered on the page.

**Comment by patmmccann** [comment]
@gglas opened a new feature ticket #7365 identifying the desire to eventually point examples to prebid.org hosted static creatives.

**Comment by philipWr** [comment]
> @philipWr Which prebid versions have you been seeing these issues?

v4.43.3 is on the test page I left in the original post

**Comment by patmmccann** [comment]
Tracking on #7365
