### ISSUE TITLE
PBS Bid Adapter: remove site object when app is present

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#7329]
## Type of issue
enhancement

## Description
Prebid Server chokes when an OpenRTB request contains both site and app sections. Since OpenRTB says this is an invalid scenario, that committee has determined in https://github.com/prebid/prebid-server/issues/1947 that the right solution is to prevent it from happening.

## Steps to reproduce
The instructions at https://docs.prebid.org/faq/prebid-server-faq.html#how-can-i-use-prebid-server-in-a-mobile-app-post-bid-scenario define how to use PBJS for App in a Post-Bid scenario.

But it doesn't actually work because the PBS Bid Adapter also includes site.

So we need to update the PBS Bid adapter to:

- First do all the merging: getConfig({app}), getConfig({site}), getConfig({ortb2})
- Then check the result. If both app and site are present, then remove site with a console warning
- it's up to the page to make sure any common fields (e.g. `cat`) are in the app object

Note: we don't consider this a breaking change because PBS is already failing on this if it's happening. We're just moving the validation to the client side to save everyone the headache.

**Comment by pm-harshad-mane** [comment]
https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter/index.js#L330
Is it already handled?

**Comment by patmmccann** [comment]
might make sense for the validations module to also note this issue

**Comment by ChrisHuie** [comment]
Working on tests and then submitting this pr.

**Comment by patmmccann** [comment]
fix in #9258
