### ISSUE TITLE
Error: Adapter Trying To Be Called Which Does Not Exist

### ISSUE THREAD

**Issue by haroxy** [prebid/Prebid.js#733]
## Type of issue
Error

## Description
"ERROR: Adapter trying to be called which does not exist: prebid adaptermanager.callBids" ""

## Steps to reproduce
Go To This Page And View Source:  http://dailyinspire.com/prebid_test/hb.html?pbjs_debug=true

**Comment by ialex** [comment]
Hello 

You are adding prebid as the bidder name which clearly doesn't exists, by the parameters you added to the bid config seems that you are trying to use appnexus change prebid for appnexus in the prebid config to get the rid of the error:

`bidder:"prebid"`

**Comment by haroxy** [comment]
thank you
