### ISSUE TITLE
Usersync: limit usersyncs to either iframe or pixel but not both

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#7330]
## Type of issue
Enhancement

## Description
The current implementation of the PBJS usersync functionality allows bidders to sync via **both** iframe and pixel methods if the publisher allows both. This is inefficient. The system should just use iframes if they're allowed, or alternately, allow publishers to define a preferred method.

Since I find it hard to imagine that a publisher would choose to prefer pixel over iframe if they support iframes, I'd propose that PBJS-core be updated to avoid injecting pixels if the same bidder already had an iframe usersync fire.

It's arguable whether this is a breaking change or a performance optimization. 

So here's the specific proposal:

1. PBJS first loops through iframe syncs (it currently does pixel syncs first)
2. If a bidder gets an iframe, mark it.
3. Then PBJS should loop through pixel syncs
4. If a bidder is about to get a pixel but already got an iframe sync, skip it.

**Comment by patmmccann** [comment]
This appears to be a bug; not a breaking change.

**Comment by pm-harshad-mane** [comment]
Closing the issue since the PR is merged.
