### ISSUE TITLE
Google Analytics Events.

### ISSUE THREAD

**Issue by haroxy** [prebid/Prebid.js#734]
## Type of issue
Question

## Description
I believe I have everything setup properly here: http://dailyinspire.com/prebid_test/hb.html?pbjs_debug=true

It is using underdogmedia and then falling backing back to DFP/adsense.

As far as I can tell everything is setup properly, however I am only seeing GA events for underdogmedia.  I am not sure how to see events when underdog does not win the bid and adsense is loaded through DFP.

What am I doing wrong?

**Comment by mkendall07** [comment]
@haroxy 
We don't track events if a prebid bidder does not win. We don't have access to DFP/Adsense data.
