### ISSUE TITLE
Bidders with different currencies ???

### ISSUE THREAD

**Issue by umutkirgoz** [prebid/Prebid.js#7379]
## Type of issue
Question

## Description
I have a simple Prebid setup with 2 bidders. I donot use "Send all bids to the ad server" feature. So Prebid works RTB with returning bids and sends the winning bids to Google Ad Manager (GAM) with key/value pairs like:

    hb_bidder=bidder_A
    hb_pb=0.10

    hb_bidder=bidder_B
    hb_pb=0.20

Off course there are line-items defined in GAM with the key/value pairs with those values above.

There is no problem in this setup, if all bidders use same currency.

What if **bidder_A** bids in **USD** and **bidder_B** bid in **TRY**
Line items' currency of  bidder_A were set to USD
Line items' currency of  bidder_B were set to TRY
Note: It's possible to use different currencies in GAM 360)

Scenario:

1 USD = 8 TRY

| Bidder | Bid | Currency |
| ------ | --- | -------- |
| A      | 1   | USD      |
| B      | 5   | TRY      |

In this scenario, bidder B wins which is wrong. Currencies donot affect prebid RTB if I am not wrong. When I checked the GAM request, it verifies me.

When I use **Prebid Currency Module**; it converts USD to TRY (1*8=8) for bidder A, and in this case winner is bidder A which is correct one. 
**Prebid Currency Module** fixes the RTB problem but Prebid sends converted bid.
 
**hb_pb=8** (TRY), **hb_bidder=bidder_A** to GAM. In GAM side, line items of **bidder_A** defined with currency USD not TRY. So bid matches wrong line-item.

**"Send all bids to the ad server"** may be solution?

I know, it's very complicated case, what do you suggest to fix problem?

**GAM 360 accepts different currencies for line-items.**

**Comment by patmmccann** [comment]
It appears send all bids would fix your problem

**Comment by gglas** [comment]
@umutkirgoz does this answer your question?  Looks like send all bids should do the trick -- closing out, feel free to reopen if you have issues.

**Comment by umutkirgoz** [comment]
> @umutkirgoz does this answer your question? Looks like send all bids should do the trick -- closing out, feel free to reopen if you have issues.

The only solution for this problem is using Send All Bids to Ad server. I changed to whole setup to this.
