### ISSUE TITLE
doNotChange - why?

### ISSUE THREAD

**Issue by joyofdata** [prebid/Prebid.js#738]
I have a question regarding the [post bid example code](http://prebid.org/dev-docs/examples/postbid.html).

There is a variable declared named "doNotChange".

`47: var doNotChange = 'doNotChange';`

What I would like to understand is - why was that name chosen? Obviously `var good = 'vibrations';` would have done the trick, too, but I kind assume this is supposed to communicate something - just what? :) 

Wouldn't something like f.x. `var adUnitCode = 'ad-unit-1';` be much more sensible - _especially because_ this variable _**actually should be changed**_ to something like that in a real application? (plus adjusting lines 51 and 63, of course)

**Comment by mkendall07** [comment]
@joyofdata 
You can name it whatever you want, with a value of whatever you want. It's for the `adUnit.code` and it needs to be unique for each adUnit (presumably only one for Post bid.)

If you feel inclined - please open a PR here to update the example: https://github.com/prebid/prebid.github.io
