### ISSUE TITLE
BizzClick not in 5.x

### ISSUE THREAD

**Issue by BizzClick** [prebid/Prebid.js#7388]
Hello! Recently I have made pool request with 5.x version adapter and it was successfully merged. But I still see on official website that BizzClick not in 5.x . What I need to do for resolve this issue and for BizzClick will be add to 5.x versions of Prebid.js?

**Comment by ChrisHuie** [comment]
I can update the docs repo

**Comment by ChrisHuie** [comment]
@BizzClick the above pr updates docs

**Comment by BizzClick** [comment]
@ChrisHuie  Thank you for fast reply!
