### ISSUE TITLE
Endless loop in ixBidAdapter

### ISSUE THREAD

**Issue by tbsmark86** [prebid/Prebid.js#7445]
https://github.com/prebid/Prebid.js/blob/5e2dcbd6a046c1247dc0ffe4fec0910f7a7b8637/modules/ixBidAdapter.js#L641

_remainingRequestSize_ was 7 in my case, which is obviously is always smaller then the empty array after serialization (which is size 38) therefore it loops and loops ...

I've encountered this because reloading the page blocked and I was interested why. Don't know anything about the configuration used.

**Comment by patmmccann** [comment]
@ix-prebid-development fyi

**Comment by punkiller** [comment]
@patmmccann can I help in some way with @ix-prebid-development and @umakajan ?

**Comment by mlb7687** [comment]
Opened a PR to fix, thanks for calling this to our attention.
