### ISSUE TITLE
gulp serve not working

### ISSUE THREAD

**Issue by dhAlcojor** [prebid/Prebid.js#7446]
## Type of issue
bug

## Description
I have cloned the repository and tried to make it run, but `gulp serve` is failing.

## Steps to reproduce
1. Clone the repository
2. Make sure you have gulp-cli installed as a global package. Install it if you don't.
3. Run `npm ci`
4. Run `gulp serve`

### Expected results
The command should finish successfully and run the server.

### Actual results
The command fails due to **a lot** of errors during linting:

Here you can see the end of the log after running `gulp serve` followed by a `gulp -v` so you can see the version of gulp-cli I have installed:

```
✖ 19827 problems (19827 errors, 0 warnings)

[15:51:49] 'lint' errored after 1.08 min
[15:51:49] ESLintError in plugin "gulp-eslint"
Message:
    Failed with 19827 errors
Details:
    domainEmitter: [object Object]
    domainThrown: false

[15:51:49] 'serve' errored after 1.08 min
 ✘ ~/projects/Prebid.js   master ±  gulp -v
CLI version: 2.3.0
Local version: 4.0.2
```

## Platform details
Latest version of Prebid.js in the master branch
Ubuntu 20.04
Node v12.16.1
NPM v7.24.0

**Comment by patmmccann** [comment]
could this be bc e2etests have started running on master? I am not certain why this ran


https://app.circleci.com/pipelines/github/prebid/Prebid.js/8095/workflows/f6bf72d2-3dd2-43cd-8302-8e695150dee7/jobs/17976

**Comment by kodi** [comment]
same, after syncing my fork my local master is unusable, there are thousands of errors on `lint` step.
eg:
```
..
.. thousands lines above
..

/Users/kodi/data/cwire/Prebid.js/plugins/eslint/node_modules/type-check/lib/check.js
    3:3   error  Split initialized 'var' declarations into multiple statements          one-var
    4:3   error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
    4:31  error  Unexpected use of comma operator                                       no-sequences
   91:5   error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
   91:24  error  Unexpected use of comma operator                                       no-sequences
  103:11  error  Expected a conditional expression and instead saw an assignment        no-cond-assign

/Users/kodi/data/cwire/Prebid.js/plugins/eslint/node_modules/type-check/lib/index.js
  5:23  error  Missing file extension "js" for "./parse-type"  import/extensions
  6:29  error  Missing file extension "js" for "./check"       import/extensions

/Users/kodi/data/cwire/Prebid.js/plugins/eslint/node_modules/type-check/lib/parse-type.js
   81:7   error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
   81:34  error  Unexpected use of comma operator                                       no-sequences
  122:37  error  Unexpected use of comma operator                                       no-sequences
  163:7   error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  163:36  error  Unexpected use of comma operator                                       no-sequences
  192:5   error  Split initialized 'var' declarations into multiple statements          one-var

✖ 19827 problems (19827 errors, 0 warnings)

[05:34:37] 'lint' errored after 44 s
[05:34:37] ESLintError in plugin "gulp-eslint"
Message:
    Failed with 19827 errors
Details:
    domainEmitter: [object Object]
    domainThrown: false
```

The only way I can test at the moment is to run with `serve-fast`, or manually removing lint step from gulp tasks

**Comment by kodi** [comment]
Found it:

https://github.com/prebid/Prebid.js/blob/a437b055cefa9c0fa47307da9a7a86de1851dc27/gulpfile.js#L78
was added ~1m ago


and, since `npm ci` creates a `plugins/eslint/node_modules` [1] all of the JS errors are originating from there.



[1]
![image](https://user-images.githubusercontent.com/51153/134282701-cfc87511-463c-4fc8-a40c-d88963eff04d.png)

**Comment by ChrisHuie** [comment]
@kodi It looks like gulp serve is currently working on the master branch. Do you have other adaptations or plugins in your gulpfile?

**Comment by ChrisHuie** [comment]
I believe this issue is from your node_modules being installed under the plugins folder instead of the root

**Comment by ChrisHuie** [comment]
This pr should fix this problem https://github.com/prebid/Prebid.js/commit/8163a23e6c113e5635863efe3fa39622752d7ba7
