### ISSUE TITLE
Utility function getBidIdParamater is misspelled

### ISSUE THREAD

**Issue by atchang** [prebid/Prebid.js#748]
I noticed that util.getBidIdParamater is spelled incorrectly. Not really that important, but I thought you would want to know. I could make the pull request, but I probably should get some consensus first. If you decide not to make the change, I'm fine with that too (sorry for posting these silly issues as I get my feet wet into the code).

**Comment by mkendall07** [comment]
Thanks for the bug report. Feel free to submit a PR. You'll need to make sure you update all the callers with the fixed function name.

**Comment by matthewlane** [comment]
The function is now spelled correctly in master with #835
