### ISSUE TITLE
ShareThrough bid adapter returns HTTP 204.

### ISSUE THREAD

**Issue by dbirkbeck** [prebid/Prebid.js#7510]
## Type of issue

Bug

## Description

Starting in Prebid 5.13, the ShareThrough bid adapter returns an HTTP 400 code with no bid responses. In recent builds it now returns an HTTP 204 with no bid responses.

## Steps to reproduce

Using chrome developer tools, inspect the bid request/response for the ShareThrough bid. 

### Expected results
The bid response should return valid bids with a HTTP 200 code.

### Actual results
The bid response returns no bids with either an HTTP 400 or an HTTP 204 code.

## Platform details

Prebid 5.12 works as expected. Prebid 5.13 exhibits the behaviour above.

**Comment by patmmccann** [comment]
Likely a result of https://github.com/prebid/Prebid.js/pull/7290

Shall we revert @epechuzal ?

**Comment by patmmccann** [comment]
@muuki88 the 204 on a bid response suffers from the same issue you identified on a sync, right, and the auction would not end until timeout? https://github.com/prebid/Prebid.js/issues/6354#issuecomment-785306766

**Comment by patmmccann** [comment]
okay i think it must not be the case, my mistake

**Comment by dbirkbeck** [comment]
@patmmccann,@epechuzal
It appears as though an HTTP 204 response is considered normal for the Sharethrough adapter. While, the original HTTP 400 response code seems to be fixed, versions of Prebid > 5.12.0 are very broken, monetization wise, and Sharethrough doesn't seem to care. Since nothing is likely to be done, there is no point in keeping this issue open. It is surprising to me that clearly untested/unready code can make it into what is supposed to be a "stable" branch.
