### ISSUE TITLE
rivrAnalyticsAdapter is passing refrence of utils to an external function

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#7516]
## Type of issue
rivrAnalyticsAdapter is passing refrence of utils to an external function
Refre: https://github.com/prebid/Prebid.js/blob/master/modules/rivrAnalyticsAdapter.js#L23

## Description
I was working on importing only required function from utils module into each module. 
Then i found that rivrAnalytics is passing reference of utils to an external function.
It will be good if they could import only required functions in their analytics adapter than importing the whole utils module.

**Comment by ChrisHuie** [comment]
closing issue from review over this topic in a prior js meeting. This behavior isn't ideal but haven't committed to enforcing as of yet.
