### ISSUE TITLE
Publink's ID module is broken | Publink key mismatch

### ISSUE THREAD

**Issue by DemonFangs** [prebid/Prebid.js#7523]
### The problem
Publink's ID module encode the decoded object as `prebid` in 
 [line 117](https://github.com/prebid/Prebid.js/blob/80bc6e2b85bbbc57fb2d626375c6b88de8c92c3a/modules/publinkIdSystem.js#L117) but the EID mapper expects a key of `publinkId` in [line 231](https://github.com/prebid/Prebid.js/blob/80bc6e2b85bbbc57fb2d626375c6b88de8c92c3a/modules/userId/eids.js#L231). As a result publink IDs are absent from all bids

### The solution
Either change the `publink` to ``publinkId in the module
OR
change the `publinkId` in `eids.js` to `publink`

**Comment by pycnvr** [comment]
HI @DemonFangs, thanks for the bug report.  I believe that's fixed already as of last release.  Decode function now uses `publinkId` matching eids.js.  Let me know if that hasn't resolved.

**Comment by DemonFangs** [comment]
Great. Yes it's fixed.
