### ISSUE TITLE
Enhance targeting unit tests

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#7538]
## Type of issue
Enhanced tests

## Description

As a followup to issue #7457, we should review the full set of requirements around ad server targeting. i.e. How do each of these features interact with other? 

- sendAllBids
- targetingControls
- sendBidsControl
- prebidServer
- bid-adapter-supplied targeting
- RTD-supplied targeting
- bidderSettings.adserverTargeting config

**Comment by dgirardi** [comment]
Closing this in favor of https://github.com/prebid/Prebid.js/issues/8130
