### ISSUE TITLE
Support for non-numerical/encrypted CPMs

### ISSUE THREAD

**Issue by ninjaboy111** [prebid/Prebid.js#757]
## Type of issue

Question : Non-numerical/encrypted CPMs
## Description

It seems that the default behaviour in prebid.js filters out non-numerical (encrypted) CPM values even when enableSendAllBids() has been called.  Allowing non-numerical CPM bids sounds like a valid/worthwhile feature to have when enableSendAllBids() is set and looks like it is quite simple to implement (Something I'd be happy to do).  Do you see any reason why this should not be supported?

**Comment by matthewlane** [comment]
Can you tell more about this feature with any use cases you have in mind?

**Comment by protonate** [comment]
@ninjaboy111 any update here?

**Comment by mkendall07** [comment]
@ninjaboy111 
This is supported, you just have to use a key other than `hb_pb` for it / not put it into `bid.cpm`. We have support for non-bid cpm if you use `bid.dealId` now. Thanks
