### ISSUE TITLE
Craft Bid adapter: onbidwon doesnt use ajax method

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#7624]
@crumbjp can you fix https://github.com/prebid/Prebid.js/blob/84d28c4c02b94a1bcfad1eb651bd2d34f44c2faf/modules/craftBidAdapter.js#L114 to use the prebid ajax method? 

By way of example: https://github.com/prebid/Prebid.js/blob/7123fa27a7fce0050f2b734493b486a25e72075b/modules/limelightDigitalBidAdapter.js#L73

Thanks!

**Comment by crumbjp** [comment]
Thanks, I confirmed and begin to work on.

**Comment by ChrisHuie** [comment]
closing with #7699 merge
