### ISSUE TITLE
More dynamic floormin

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#7626]
## Type of issue
Feature

## Description
https://github.com/prebid/Prebid.js/pull/5805 allowed for minimums to floors as a page level variable, but we need floorMin at slot, and potentially other granularity, etc level.

**Comment by robertrmartinez** [comment]
So the change is to:

Update the price floors module to look for floorMin at `adunit.ortb2Imp.ext.prebid.floorMin` first, and then do whatever it does now to find it if not?

@bretg @patmmccann

**Comment by patmmccann** [comment]
yes; this would allow for it to vary over ad units, no?

**Comment by robertrmartinez** [comment]
Yep it is a good idea!

I'll try and get this and https://github.com/prebid/Prebid.js/issues/8339 done over the weekend or something!

**Comment by muuki88** [comment]
This looks super useful. Does this also work if there's no floor information at all?

Currently we set our floors something like this

```js
floors: {
  currency: config.currency.adServerCurrency,
  schema: {
    delimiter: '|',
    fields: ['mediaType']
  },
  values: {
    // provided from somewhere else
    '*': priceRule.floorprice
  }
}
```

With this extension would it be possible to leaf the `floors` property undefined and only set

```js
ortb2Imp: {
  ext: {
    prebid: {
      floorMin: priceRules.floorprice
    }
  }
}
```

**Comment by patmmccann** [comment]
I got so excited i merged without docs, apologies :)

we're implementing shortly.

**Comment by patmmccann** [comment]
@muuki88 did you figure out the answer to that in test?

**Comment by muuki88** [comment]
@patmmccann unforunately not. I'll put this on my teams agenda

**Comment by patmmccann** [comment]
I haven't tested, but I suspect that would not work. You might be able to get away with just the currency or something though.
