### ISSUE TITLE
Pubmatic BidAdapter potentially doesn't assign mediaType correctly when referencing a BidResponse's `ext.bidtype`.

### ISSUE THREAD

**Issue by DecayConstant** [prebid/Prebid.js#7645]
## Type of issue
Bug

## Description
When a Pubmatic BidResponse contains `ext.bidtype`, the code in the `_checkMediaType` function incorrectly tries to access it with `ext.BidType` (https://github.com/prebid/Prebid.js/blob/master/modules/pubmaticBidAdapter.js#L869) 

This is causing the BidAdapter to sometimes incorrectly assign `mediaType`s. 

## Steps to reproduce
Get a BidReponse from Pubmatic, and inspect the contents of its `ext`. It will contain `ext.bidtype` instead of `ext.BidType`

### Expected results
I expect the Adapter to correctly access the `ext.bidtype` in the BidResponse.

### Actual results
The bidAdapter is sometimes incorrectly assigning a mediaType of 'banner' to Outstream BidReponses that should have a MediaType of `video`
<img width="932" alt="Caramel_Chicken_-_Vietnamese_Caramel_Chicken_-_Rasa_Malaysia" src="https://user-images.githubusercontent.com/718653/139503282-324b8761-e743-42bd-9a4f-b8cadbdf595b.png">
.

**Comment by pm-harshad-mane** [comment]
Thank you @DecayConstant for reporting. 
i will look into this one.

**Comment by pm-harshad-mane** [comment]
PBS implementation of PubMatic bid adapter also expect `BidType` instead of `bidtype`

**Comment by pm-harshad-mane** [comment]
The bug is fixed in https://github.com/prebid/Prebid.js/pull/7683, closing the issue.
