### ISSUE TITLE
Feature req: restore domainOverride to SharedId

### ISSUE THREAD

**Issue by pycnvr** [prebid/Prebid.js#7663]
## Type of issue
Question

## Description

It looks like when PubCommonId was merged with SharedId in #7149, the combined SharedId module lost the domainOverride function.  That used to return the top level domain for setting cookies.  What was the reason for the removal?  Thanks.

## Steps to reproduce

Any page with prebid.js and sharedid set to cookie.  Check cookie domain in dev console.

**Comment by jdwieland8282** [comment]
Merge is a generous way of describing what we did. We really just retired sharedId and renamed the PC module to sharedid. It kept its existing functionality. We’d be happy to take a look and add that functionality in.

**Comment by pycnvr** [comment]
@jdwieland8282 Thanks!

**Comment by bretg** [comment]
What needs to happen here is:
- look up the 4.x PubCommon module
- port the domainOverride feature and tests to the 6.x SharedID module

**Comment by dgirardi** [comment]
closing this with the merge https://github.com/prebid/Prebid.js/pull/7773
