### ISSUE TITLE
Safari - Blocked a frame with origin..from accessing a frame with origin

### ISSUE THREAD

**Issue by yconoclast** [prebid/Prebid.js#767]
## Type of issue
BUG

## Description
Opening http://prebid.org/ with Safari I'm having this error on console:

**Blocked a frame with origin "http://ams1-ib.adnxs.com" from accessing a frame with origin "http://prebid.org". Protocols, domains, and ports must match.**

**Comment by mkendall07** [comment]
I _think_ this is normal for safari. It complains when trying to inspect the top level domain.

**Comment by yconoclast** [comment]
Even if it's normal, some bids are being blocked from being rendered on Safari.
Shouldn't each bidder/adapter fix it in order to have a fully working version on Safari also since it's a well used browser?

**Comment by mkendall07** [comment]
@yconoclast 
Can you explain why you think this is causing ads to block from rendering? This has to do with top domain level detection in an unfriendly iframe that the AppNexus ad tries to do. This is post ad rendering and will not affect rendering. Additionally this is specific to the AppNexus ad and not the adapter. 

If you have a bug please file it with appropriate replication steps and details of expected outcome and current behavior.

**Comment by mkendall07** [comment]
@yconoclast 
Any update on this?

**Comment by yconoclast** [comment]
@mkendall07 you're right, it's not blocking the ads rendering.

And it isn't related with adapter.

We can close this.
Thanks
