### ISSUE TITLE
Prebid.js Test - All Bidders Took Too Long or No Bid.

### ISSUE THREAD

**Issue by adquery** [prebid/Prebid.js#7673]
## Type of issue
question

## Description
we test libraries prebid.js but we cannot get the effect to win the auction on the test
there are no errors

the server response time is 150 ms and the message is displayed

"All Bidders Took Too Long or No Bid. Try Refresh."

**Comment by gglas** [comment]
@adquery what precisely are you trying to test?  Are you looking at the example page?  We are seeing intermittent timeouts from the example bidder as well, however, we do see wins and that should be all that's necessary to understand the behavior.

**Comment by adquery** [comment]
We are trying to test the Auction Winning to see our render of the ad

**Comment by patmmccann** [comment]
Tracking on #7365
