### ISSUE TITLE
Adform unit test failure in IE9 Win 7

### ISSUE THREAD

**Issue by protonate** [prebid/Prebid.js#769]
## Type of issue
Bug

## Description
The Adform adapter test uses the Mozilla `atob` extension which is 'undefined' in IE9

## Steps to reproduce
1. Run `gulp serve --watch`
1. Load `http://localhost:9876/debug.html` in IE9
1. Wait for tests to complete

### Expected results
Tests should complete without errors.

### Actual results
The Adform test "response should pass multiple bids via single request" fails three times with "ReferenceError: 'atob' is undefined".

## Platform details
IE9 Win 7

**Comment by protonate** [comment]
cc: @prebid/adform

**Comment by jaiminpanchal27** [comment]
@braizhas Please check this test failure
