### ISSUE TITLE
Additional Events for RTD Modules

### ISSUE THREAD

**Issue by gglas** [prebid/Prebid.js#7698]
## Type of issue
Feature

## Description

In the course of executing, Real Time Data modules may want to emit events that notify publishers of various phases in their implementation -- everything from their technology successfully loading, to their technology executing successfully in the course of a given or multiple auctions.  The first flavor of these that we've seen requested is a Billable event, emitted by an RTD module when the module has executed some sort of billable task.

These events would be optionally emitted, but the framework would also ensure that we don't have unique events from each different module signaling similar things with different taxonomies.

**Comment by patmmccann** [comment]
solved in #8119
