### ISSUE TITLE
bug - not sending AD_RENDER_FAILED when using safeFrame 

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#7702]
## Type of issue
Bug

## Description
As pointed out by @patmmccann we currently don't emit the `AD_RENDER_FAILED` event if the safeFrame path is used to render the creative (https://github.com/prebid/Prebid.js/blob/master/src/secureCreatives.js#L81)

### Expected results
We should emit all the same events regardless of the render path (safeFrame or non safeFrame)

**Comment by dgirardi** [comment]
`AD_RENDER_SUCCEEDED` is also not emitted.

**Comment by bretg** [comment]
From a publisher's perspective, the change here would be:

If they have a custom handler listening for the AD_RENDER_SUCCEEDED event:

        pbjs.onEvent('**adRenderSucceeded**', function() {...});

That handler would be need to be able to deal with the scenario where the first "doc" parameter is null. Currently that parameter always has a value, but in the case of safeframes fixed here, the param would be null.

I think this is ok as long as we update the pub API doc https://docs.prebid.org/dev-docs/publisher-api-reference/getEvents.html to note the possibility of this being null.

Adding @patmmccann for a publisher perspective. Basically, I think we can make this change now and not way for 7.0
