### ISSUE TITLE
Endless Loop in ixBidAdapter with gdprEnforcement module and no consent for purpose 1

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#7707]
## Type of issue

Bug

## Description

When upgrading to Prebid 6.1.0 index exchange runs into an endless loop when the `gdprEnforcement` module is enabled. I wasn't able to check if consent for purpose 1 is given or not, but I assume that it's not.

```
utils.js:272 Prebid ix ERROR: Error executing handler: events.js RangeError: Maximum call stack size exceeded
    at assign (<anonymous>)
    at _getConfig (config.js:317)
    at Object.getConfig (config.js:351)
    at debugTurnedOn (utils.js:299)
    at Module.logError (utils.js:271)
    at Module.<anonymous> (events.js:70)
    at Array.forEach (<anonymous>)
    at Module._each (utils.js:399)
    at _dispatch (events.js:65)
    at Object.module.exports._public.emit (events.js:99)
```

![image](https://user-images.githubusercontent.com/647727/141698917-bdbed9c3-3aa9-4687-8af1-0b1b362d090f.png)

## Steps to reproduce

I'm not 100% sure about those

1. Upgrade to prebid 6.1.0
2. Add `gdprEnforcement` module
3. Don't consent to purpose 1

## Test page

None.

### Expected results

ixAdapter doesn't crash the page with an infinite loop.

### Actual results

Chrome crashes

## Platform details

* Prebid 6.1.0
* `gdprEnforcement` module enabled

## Other information

* #7630 - I assume this commit introduced the bug / @umakajan
* #7445

**Comment by umakajan** [comment]
Thanks @muuki88 for flagging this issue, will take it back to the development team and address the issue.

**Comment by muuki88** [comment]
Do you still need a test page?

**Comment by gglas** [comment]
@umakajan Hey guys -- how's progress coming along on this?

**Comment by lksharma** [comment]
Hey @gglas,
I am looking into this issue. @muuki88 would you be able to provide a test page for my reference?

**Comment by muuki88** [comment]
Okay. I'm on it. Will be tomorrow though 😄

**Comment by muuki88** [comment]
Here it is @lksharma

https://frag-muki.de/ix-test/?pbjs_debug=true

Go to privacy settings and remove consent for purpose one. Take a look at the console.

**Comment by muuki88** [comment]
@lksharma anything I can help you with?

**Comment by lksharma** [comment]
Hey @muuki88,

I was able to identify the issue and will be pushing my changes shortly. Once I have the branch ready would you be able to help verify against your test page?

**Comment by muuki88** [comment]
Sure thing

**Comment by lksharma** [comment]
@muuki88 I pushed my changes [here](https://github.com/indexexchange/Prebid.js/tree/Endless_Loop_Auction_Debug_Event). I've verified the fix on my end. Let me know if you have any issues with your tests as well. Thank you.

**Comment by muuki88** [comment]
@lksharma works :tada:
