### ISSUE TITLE
Prebid re-uses old timed-out bids when refreshing ad units also time out

### ISSUE THREAD

**Issue by kizzard** [prebid/Prebid.js#772]
## Type of issue
Bug (perhaps a feature but could be causing discrepancies in current state)

## Description
When utilizing the example refresh code at http://prebid.org/dev-docs/examples/adunit-refresh.html , if a bid times out, then the unit is refreshed and times out again, the bid from the previous request is sent to the ad server, even though it may now be stale. A stale bid may be reflected as a non-win and therefore could cause discrepancies between the bidder reporting and the publisher's DFP reporting.

## Steps to reproduce
1. Using a debug proxy, enable HTTP throttling to emulate greater than 1000ms latency
2. Load test page: http://support.oneadserver.aol.com/jeremy/Prebid-DFP-refresh-bug.html . No ad units should load as the bids timed out. Check proxy to confirm no bids were sent to DFP.
3. Click "refresh 300x250 ad unit" button. An ad will now display, even though the latest bid has timed out. Checking the DFP call with proxy reveals the bid from step 2 was sent to DFP.

### Expected results
Bids from old requests should not be re-used as they may be stale.

### Actual results
Bids from old requests are re-used.

## Platform details
Prebid 0.14.0, Windows, Firefox 49.0.2

**Comment by kizzard** [comment]
If this is an intended feature, I would suggest the ability to disable per-adapter as, for example, AOL bids are only valid for 60s.

**Comment by protonate** [comment]
Thanks for the bug report. The behavior is, perhaps, wanted (long-lived and unused bids can be recycled in subsequent auctions) but requires more thought on how to support it.

With #750 we are clearing bids for a given placement if that placement is included in the current request for bids. This should fix this issue. If you are able to confirm that with the #750 branch let us know.

**Comment by kizzard** [comment]
Awesome, thanks Nate.

I'll test #750 as soon as I can string together a test environment again. In the meantime, the workaround I'm using is:

`pbjs._bidsReceived = [];
pbjs._winningBids = [];`

Executed immediately before pbjs.requestBids during an ad unit refresh. This seems to have the desired effect. Do you have any comments about this - could it cause any problems?

**Comment by protonate** [comment]
Right, the problem with clearing out the bid arrays is if an ad server call is in-flight the ad payload can be removed from the bid array before `renderAd` goes looking for it. This can be particularly an issue in Single Page Apps, or any case where `requestBids` is called frequently without a full page refresh. If these cases aren't an issue for you than resetting the bid arrays shouldn't cause an issue.

The loop you suggest is what `clearPlacements` does in #750: https://github.com/prebid/Prebid.js/pull/750/files#diff-f8e049a1b6d4f9aa96fca41d2f7aa11dR271 

So if you want to use that as a workaround until a merge it should work similarly.

**Comment by kizzard** [comment]
Perfect - thanks for your input. I implemented a filter similar to the clearPlacements function and it's working nicely. Thanks. I'll keep this open until I'm able to test #750.
