### ISSUE TITLE
[QUESTION] Customize the auction behavior

### ISSUE THREAD

**Issue by fasenderos** [prebid/Prebid.js#7726]
Hi, I need take control over the auction, especially I need to get all the bid responses (1st step) and, based on my own criteria, setting the winning bid of each ad unit (2nd step).

So for the 1st step I think to have a listner on the `AUCTION_INIT` event and call the [`getBidResponses`](https://docs.prebid.org/dev-docs/publisher-api-reference/getBidResponses.html). The problem is that the function return an empty object, while the same method on the `AUCTION_END` event return the bid responses, but it's too late for my use case.

For the 2nd step, I didn't found any useful method in the [public API of Prebid.js](https://docs.prebid.org/dev-docs/publisher-api-reference.html) to set the winning bid of each ad unit.

Do you have any suggestions?

Thanks in advance.

**Comment by fasenderos** [comment]
The use case is to optimize the auction. Say I have 3 `adUnits` and 2 `bidders`, this is the normal `Prebid` behavior:
```
bidResponse = {
   ad_unit_1: { bids: [ { bidder: "appnexus", cpm: 0.5}, { bidder: "rubicon", cpm: 0.6} ] }, // Winner 0.6
   ad_unit_2: { bids: [ { bidder: "appnexus", cpm: 0.5}, { bidder: "rubicon", cpm: 0.4} ] }, // Winner 0.5
   ad_unit_3: { bids: [ { bidder: "appnexus", cpm: 0.3}, { bidder: "rubicon", cpm: 0.2} ] }, // Winner 0.3  
}
Total CPM = 1.4
```
An optimized version of the same auction, would have the best compete against the worst bids, so `First vs Last`, `Second vs Second-last`, `Third vs Third-last`
```
// Bid ordered by CPM
orderedBids = [
  { bidder: "rubicon", cpm: 0.6}, { bidder: "appnexus", cpm: 0.5}, { bidder: "appnexus", cpm: 0.5}, // BEST
  { bidder: "rubicon", cpm: 0.4}, { bidder: "appnexus", cpm: 0.3}, { bidder: "rubicon", cpm: 0.2} // WORST
];

optimizedAuction = {
   ad_unit_1: { bids: [ { bidder: "rubicon", cpm: 0.6}, { bidder: "rubicon", cpm: 0.2} ] }, // Winner 0.6
   ad_unit_2: { bids: [ { bidder: "appnexus", cpm: 0.5}, { bidder: "appnexus", cpm: 0.3} ] }, // Winner 0.5
   ad_unit_3: { bids: [ { bidder: "appnexus", cpm: 0.5}, { bidder: "rubicon", cpm: 0.4} ] }, // Winner 0.5
}
Total CPM = 1.6
```

**Comment by patmmccann** [comment]
if those are all the same ad unit from the advertiser's perspective, make the calls sequentially with a common cache, as this user describes https://github.com/prebid/Prebid.js/issues/6785
