### ISSUE TITLE
Remove Nyan Karma reporter as it slows down testing 4x

### ISSUE THREAD

**Issue by marian-r** [prebid/Prebid.js#774]
## Type of issue
Question, build process, performance

## Description
Running unit tests without Nyan Karma reporter takes 1/4 of the time then when the Nyan reporter is enabled. I would advise removing it. To me, it doesn't give much value either.

## Steps to reproduce
Run `$ gulp test`.
- With Nyan: ~ 2mins, 2.5 mins for my colleague
- Without Nyan: ~ 30s

## Platform details
OS X El Capitan, Node.js 5 and 6

**Comment by protonate** [comment]
@jaiminpanchal27 @marian-r for review
