### ISSUE TITLE
Error in bliinkBidAdapter.js

### ISSUE THREAD

**Issue by vlouppe** [prebid/Prebid.js#7757]
## Type of issue
blocking issue

## Description
Wrong path in registerBidder import causes a "Module not found: Error: Can't resolve 'src/adapters/bidderFactory.js'" error

## Steps to reproduce
Build a js app with Prebid.js as a  npm dependency and bliink bid adapter.

## Other information
The good path is ../src/adapters/bidderFactory.js

**Comment by Kola-Kola** [comment]
Hello @vlouppe 

Can I have your current version please ? 

Because this issue was fixed here (#7836)

Have a nice day
