### ISSUE TITLE
Use a strict code style

### ISSUE THREAD

**Issue by gajus** [prebid/Prebid.js#776]
The current code style rules are fairly limited. It makes contributing to the code base quite complex (need guestimate code style requirements on other pieces of code).

Would you consider adapting a more strict code style?

* https://github.com/gajus/eslint-config-canonical Strict. My obvious preference.
* https://www.npmjs.com/package/eslint-config-airbnb Very popular, but a bit loose.

**Comment by mkendall07** [comment]
Agree style is a bit loose. @prebid/core will review and decide on strict style standard.

**Comment by gajus** [comment]
Some examples of my personal code bases using `eslint-config-canonical`:

* https://github.com/gajus/react-css-modules
* https://github.com/gajus/swing
* https://github.com/gajus/redux-immutable (slightly outdated)
* https://github.com/gajus/eslint-plugin-flowtype
* https://github.com/gajus/create-index
* https://github.com/gajus/isomorphic-webpack

`eslint-config-canonical` style guide has been recently adopted by MailOnline organisation ([eslint-config-mailonline](https://github.com/MailOnline/eslint-config-mailonline) extends `eslint-config-canonical` with a few modifications). Therefore, it has been scrutinised quite a bit over the past month.
