### ISSUE TITLE
bidCpmAdjustment for alias bidder?

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#777]
How do I do a bidCpmAdjustment for an alias bidder?

I tried this, but it results in a syntax error:

    pbjs.que.push(function() {
        pbjs.addAdUnits(adUnits);
        pbjs.aliasBidder('appnexus', '152media');
        
        pbjs.bidderSettings = {152media: {
        bidCpmAdjustment : function(bidCpm){
          return bidCpm * .95;}
          }
        }; 

I also have another advertiser who is using appnexus (bRealtime), so I do not want to do a bidCpmAdjustment for appnexus.

**Comment by matthewlane** [comment]
The syntax error is due to `152media` being an invalid JavaScript identifier (it starts with a number) rather than it being an alias bidder. You can still use this as an object key with bracket notation though. Try something like:
```JavaScript
pbjs.bidderSettings = {};
pbjs.bidderSettings['152media'] = {
  bidCpmAdjustment: function(bidCpm) {
    return bidCpm * .95;
  }
};
```

**Comment by headerbidding** [comment]
Yeah!  That works! 

Thank you!
