### ISSUE TITLE
Prebid 7 - a proposed list of breaking changes

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#7796]
## Type of issue
A Proposed and working list of breaking changes to include in Prebid 7 - target release Late May 2022

## Complete:
delete userid targeting module #8226 
delete nextroll https://github.com/prebid/Prebid.js/pull/8150
Remove Appnexus analytics #8330 
delete floc #8225 
https://github.com/prebid/Prebid.js/pull/7522 Confirmation from the Yahoo team indicates to remove onevideo (aol in next version)
Adapters accepting interstitial flag must accept ortb2 instl param https://github.com/prebid/Prebid.js/issues/5917
Remove dmx #8417
change defaults on #8129 
delete halo as per https://github.com/prebid/Prebid.js/pull/7938
https://github.com/prebid/Prebid.js/issues/7651 site.content.data on specific auctions
Fold trustx into Grid #8321 
remove adlive bid adapter
delete sortable adapters #8263 
https://github.com/prebid/Prebid.js/pull/8437  -- delete appnexus aliases
#8279 bid modules will not be able to use storage manager unless whitelisted by pubs in config
Remove akamai id module
fix bcats to read from ortb2 everywhere #7925 
#7853 default usp to iab 
https://github.com/prebid/Prebid.js/pull/8235 remove stored auction response
deprecate getLegacyFpd #8283  

Adapters accepting position must accept it as per conventions defined at https://github.com/prebid/Prebid.js/issues/5578

Adapters known to be using http1 bid endpoints in violation of bidder module rules will get warnings in their adapter documentation; user sync endpoints in http1 will not incur the warning at this time. 

## PR submitted:

Drop tcf1 https://github.com/prebid/Prebid.js/issues/7781

Finish up referrer changes https://github.com/prebid/Prebid.js/issues/5637 #8450 

prevent Prebid from loading twice - https://github.com/prebid/Prebid.js/issues/8374

## To do:
https://github.com/prebid/Prebid.js/pull/7954 update pbsBidAdapter to use imp.ext.prebid.bidder.BIDDER

Update all documentation related to FPD to follow up #8283  and #7651

**Comment by josepowera** [comment]
Proposal
Make universal OpenRTB and ID module that BidAdapters and ID providers can "inherit"


Make a universal  OpenRTB 2.5 bidding module, that minimizes what bidder adapter has to do.... adapter would only define:
-httpEndpoint for bidding,
-httpEndpoint for cookieSyncs
-gvlID
-supported mediatypes (banner, native, video, audio)
-supported browser countries (most smaller bidders are teritory specific) (that would required geoIp module - can be serverside via JSON call)

If most bidders move to this simplified adapter overhead of maintaining (and pull requests) for > adapters would be greatly minimized.


---
Same goes for ID providers... most providers are simple JSON calls to serverside

If provider just defines 
-httpEndpoint for ID resolving
-euid domain
-cookie name
-TTL

while all rest code is "inherited" from universal general ID module.
Most providers could use this general ID module

**Comment by gglas** [comment]
@slimkrazy @adam-browning would you mind reviewing the second item?  We think this would be an opportune time to consolidate, let us know your feedback and if we should expect it.

**Comment by patmmccann** [comment]
@josepowera this is a great idea but not a breaking change; it could be merged with any release.

**Comment by patmmccann** [comment]
delete floc adapter

**Comment by patmmccann** [comment]
delete halo as requested in https://github.com/prebid/Prebid.js/pull/7938

**Comment by dgirardi** [comment]
We may want to include part of https://github.com/prebid/Prebid.js/issues/8130; specifically, redefinition of "bidLimit" and "sendStandardTargeting" to address outstanding bug reports about them.

**Comment by anthonylauzon** [comment]
Please allow additional time for Halo removal.  A formal PR will be submitted.

**Comment by patmmccann** [comment]
@anthonylauzon could you submit the delete halo pr soon? We have double the maintenance surface now.

**Comment by anthonylauzon** [comment]
We are working towards the removal PR and will submit it once we are sure all migrations are complete.  Are there any issues with leaving those modules intact for Prebid 7?

**Comment by anthonylauzon** [comment]
This will likely occur during the lifetime of Prebid 7.  We wanted to make sure to allow at least a major version for migrations to complete.

**Comment by patmmccann** [comment]
@anthonylauzon the purpose of the major release is to notify publishers they might need to make build it configuration changes; we don't need to wait for all publishers to compete that before releasing.

**Comment by anthonylauzon** [comment]
@patmmccann understood that you would like to reduce code surface.  We're targeting Prebid 8 for all partners to have completed migrating. As we iterate on Hadron, we would prefer to leave the Halo modules unmodified until we can submit a formal removal PR.

**Comment by patmmccann** [comment]
Hi @anthonylauzon ; we plan to go ahead and remove halo in 7 in that case. It seems we're just talking past each other.
