### ISSUE TITLE
Help With Implementing OpenX

### ISSUE THREAD

**Issue by premesh** [prebid/Prebid.js#78]
Hey guys just starting in on this. For the bid params i see pgid ( pageId) and unit (ad unit ID) . Not sure i understand what these are exactly. Ad unit ID im assuming is the DFP ID for the ad unit ?

**Comment by nickjacob** [comment]
pgid (page id) is optional/it's a targeting param your rep can set up but
isn't standard afaik. unit is your Openx unit id; you'll need a mapping to
your dfp units from your rep--that should be standard part of
integration/setup process though.

On Oct 21, 2015, at 6:36 PM, premesh <notifications@github.com> wrote:

Hey guys just starting in on this. For the bid params i see pgid ( pageId)
and unit (ad unit ID) . Not sure i understand what these are exactly. Ad
unit ID im assuming is the DFP ID for the ad unit ?

—
Reply to this email directly or view it on GitHub
<https://github.com/prebid/Prebid.js/issues/78>.

**Comment by premesh** [comment]
Awesome!!


*Premesh Purayil*

*Chief Technology Officer | www.ranker.com <http://www.ranker.com>*

*o : (323)782-9800 | c : (858)382-8745*
