### ISSUE TITLE
Need a flag to inform bidders and analytics adapters that an ad-unit is being refreshed

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#7804]
## Type of issue
Need a flag to inform bidders and analytics adapters through `pbjs.requestBids` call that an ad-unit is being refreshed.
is `adUnit.refresh (bool)` a good place to make it a standard?

**Comment by bretg** [comment]
@pm-harshad-mane - we discussed in the PBJS issues review and have two answers:

1) At one level, PBJS already supports something along these lines. The bidRequest object already has a "bidRequestsCount" field which tells you how many times this PBJS Ad Unit has been auctioned on this page.

The code in the adapter manager https://github.com/prebid/Prebid.js/blob/4ae7e1b92364f116fd1f3829582e8bf921526858/src/adapterManager.js
              bidRequestsCount: adunitCounter.getRequestsCounter(adUnit.code),
              bidderRequestsCount: adunitCounter.getBidderRequestsCounter(adUnit.code, bid.bidder),
              bidderWinsCount: adunitCounter.getBidderWinsCounter(adUnit.code, bid.bidder),

2) But in general, PBJS AdUnit auction count may **not** be what you're looking for: the same PBJS AdUnit can be used for multiple different divs, like in the infinite-scroll scenario. That's not really a refresh. 

It was noted in the meeting that this general topic has come up in IAB discussions. It's unclear at the industry level what metadata is needed: "this div **could be** refreshed in the future" or "this div **is being refreshed** right now". 

Prebid will wait for the industry to come to a decision before we establish any formal conventions. In the meantime, we would recommend that one-off FirstPartyData could be utilized when required by a particular analytics adapter.

**Comment by pm-harshad-mane** [comment]
Thank you @bretg for detailed explanation.

**Comment by bretg** [comment]
What would you like to do with this issue @pm-harshad-mane ?  May we close it?

**Comment by pm-harshad-mane** [comment]
Let me check these APIs.
