### ISSUE TITLE
NextMillennium adapter reading gdprConsent undefined

### ISSUE THREAD

**Issue by hnkhandev** [prebid/Prebid.js#7806]
## Type of issue
Accessing property of possible undefined gdprConsent in request.

## Description
Trying to access gdprConsent.gdprApplies and gdprConsent.consentString but not checking if gdprConsent is undefined: https://github.com/prebid/Prebid.js/blob/master/modules/nextMillenniumBidAdapter.js#L41-L55

Solution would look something like this:

```
if (gdprConsent || uspConsent) {
  postBody.regs = { ext: {} }
}

if (uspConsent) {
  postBody.regs.ext.us_privacy = uspConsent;
}

if (typeof gdprConsent !== 'undefined') {
  if (typeof gdprConsent.gdprApplies !== 'undefined') {
    postBody.regs.ext.gdpr = gdprConsent.gdprApplies ? 1 : 0;
  }
  if (typeof gdprConsent.consentString !== 'undefined') {
    postBody.user = {
      ext: { consent: gdprConsent.consentString }
    }
  }
}
```

## Other information
@mifanich

**Comment by ChrisHuie** [comment]
@hnkhandev @mifanich is there expected to be a pr in the future with these changes?

**Comment by mifanich** [comment]
@ChrisHuie @hnkhandev 
https://github.com/prebid/Prebid.js/pull/7817
