### ISSUE TITLE
Rubicon - How to support multiple zoneIDs for one ad unit

### ISSUE THREAD

**Issue by aneuway2** [prebid/Prebid.js#782]
## Type of issue
Documentation / Expected Setup

## Description
There are multiple Rubicon zoneIds for one ad unit that we are trying to implement. Should we make additional calls to Rubicon within the same prebid call or whats the best way to put this in place?

The ad units accept multiple sizes on multiple templates, and the zones are tied to templates (home, channel front, article).

So first example:  the *rightrail_pos1* ad unit, the zoneID values are: *123, 456, 789*

## Steps to reproduce
Within the bidder information; multiple zoneIDs are provided for one ad unit

### Expected results
No errors shown in console from Rubicon

### Actual results
Seeing errors in console from Rubicon when specifying zone ids with a comma like the following:
`"zoneID": "123, 456, 789"`

## Platform details
Prebid 0.13

**Comment by aneuway2** [comment]
@bretg ^

**Comment by bretg** [comment]
You can do this with the new 'rubiconLite' adapter by specifying multiple bids in the AdUnit. e.g.
```
var adUnits = [{
        code: 'div-gpt-ad-1460505748561-0',
        sizes: [[300, 250], [300,600]],
        bids: [{
            bidder: 'rubicon',
            params: {
               [first set of accountId/siteId/zoneId params]
            }
        },
        {
            bidder: 'rubicon',
            params: {
               [second set of accountId/siteId/zoneId params]
            }
        }]
    }
```
Note that we will soon be obsoleting the current 'rubicon' adapter and replacing it with the code currently in 'rubiconLite'.
