### ISSUE TITLE
Optimera RTD Provider: Targeting fix for 4.x legacy branch

### ISSUE THREAD

**Issue by mcallari** [prebid/Prebid.js#7821]
## Type of issue
Bug

## Description
Back porting latest targeting and auction init issues from the latest Prebid 5.x version of the OptimeraRTD module.

## Steps to reproduce
Targeting is not assigned correctly and new data is not fetched on auction init.

**Comment by bretg** [comment]
We are not going to do any more releases on the 4.x branch. It may be ok to merge the code to the branch -- will leave that to others. But we don't need this issue tracking.
