### ISSUE TITLE
OptimeraRTD Module: Make non-ad related data available to the page for ingestion

### ISSUE THREAD

**Issue by mcallari** [prebid/Prebid.js#7849]
## Type of issue
Feature request

## Description
Some of our customers have asked if we can also expose non-ad related data we have to the page via the OptimeraRTD module. They use this data for analytical purposes and this will never interface with the ad server. 

We provide a global variable (window.optimeraInsights) to the page in our library which is on the page independent of Prebid. This change will update this window variable with this extra data, if available.

**Comment by patmmccann** [comment]
What's your question

**Comment by mcallari** [comment]
Hi @patmmccann, just wanted to see if this patch, which will update a global var on the, page was ok to merge.

**Comment by ChrisHuie** [comment]
close with merge of #7850
