### ISSUE TITLE
Why does bidCpmAdjustment not work when aliased publisher name starts with a number?

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#786]
Hi Matt,

Observation:
The bid ajustment for 152media is ignored.
The bid ajustment for brealtime  works fine.

Code:

    pbjs.que.push(function() {
        pbjs.addAdUnits(adUnits);
        pbjs.aliasBidder('appnexus', '152media');

    pbjs.bidderSettings = {};
    pbjs.bidderSettings['152media'] = {
        bidCpmAdjustment: function(bidCpm) {
        return bidCpm * .10;}
    };

    pbjs.bidderSettings = {brealtime: {
        bidCpmAdjustment : function(bidCpm){
          return bidCpm * .10;}
      }
    };

Test page:
http://www.flixxy.com/prebid-brealtime-bidadjustment-test.htm?pbjs_debug=true

**Comment by headerbidding** [comment]
Actually, I just isolated the problem by renaming 152media to one52media.
It has nothing to do with the type.

It lookis like that the bidCpmAdjustment for bRealtime overrides the bidCpmAdjustment for one52media (or 152media)

test pages:
one52media only, bidadjustment works fine
http://www.flixxy.com/prebid-one52media-no-brealtime.htm?pbjs_debug=true 

Here the 0.9 bidadjustment for brealtime overrides the 0.1 bidajustment of one52media:
http://www.flixxy.com/prebid-one52media.htm?pbjs_debug=true

**Comment by headerbidding** [comment]
Another test:
http://www.flixxy.com/prebid-one52media-brt-both-same-bidadjustment.htm?pbjs_debug=true

Both are set to a bidadjustment of 0.1
brealtime respects it - one52media does not and continues to offer high bids:.

INFO: Invoking pbjs.setTargetingForGPTAsync 
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-0 key: hb_bidder value: one52media
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-0 key: hb_adid value: 127a136940b6ce3
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-0 key: hb_pb value: 1.90
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-0 key: hb_size value: 300x250
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-0 key: hb_bidder_brealtime value: brealtime
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-0 key: hb_adid_brealtime value: 97f3920ba221cd
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-0 key: hb_pb_brealtime value: 0.00
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-0 key: hb_size_brealtime value: 300x250
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-0 key: hb_deal_brealtime value: 265476
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-2 key: hb_bidder value: one52media
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-2 key: hb_adid value: 13af4632276f09d
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-2 key: hb_pb value: 0.20
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-2 key: hb_size value: 728x90
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-1 key: hb_bidder value: one52media
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-1 key: hb_adid value: 143f1de832a35d7
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-1 key: hb_pb value: 1.20
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-1 key: hb_size value: 300x250
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-1 key: hb_deal_one52media value: 260557
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-1 key: hb_deal value: 260557
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-1 key: hb_bidder_one52media value: one52media
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-1 key: hb_adid_one52media value: 143f1de832a35d7
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-1 key: hb_pb_one52media value: 1.20
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-1 key: hb_size_one52media value: 300x250
prebid.js:3 MESSAGE: Attempting to set key value for slot: div-gpt-ad-1450127596910-1 key: hb_deal_one52media value: 260557

**Comment by mkendall07** [comment]
I'm not sure if bid adjustment works with aliased bidders. I'll have to look at the code

**Comment by headerbidding** [comment]
Yes, that must be the problem. Even after renaming the bidder to one52media it still does not work.
This restriction should be added to the documentation.
It would be nice to add this functionality in a future release.

**Comment by headerbidding** [comment]
How about if I make a bid adjustment for "appnexus" instead of the alias? 
1) Would it work?
2) Would it also affect brealtime?

**Comment by headerbidding** [comment]
Making a bid cpm bid adjustment for "appnexus" instead of the alias did not work. 
:-(

**Comment by mkendall07** [comment]
I looked at the code earlier and didn't see any reason why it should not work for an aliased bidder. I didn't have time to test it though so I'll do that next.

**Comment by headerbidding** [comment]
It seems that the brealtime price adjustment is blocking the alias price adjustment.

**Comment by yairraz** [comment]
Your pbjs.bidderSettings is being rewritten when you're setting the brealtime bidCpmAdjustment function.
You have 2 options: 
1. Use the object property setting for the second adapter (and all of the following) like this:
```
`pbjs.bidderSettings.brealtime= {
    bidCpmAdjustment: function(bidCpm) {
    return bidCpm * .10;}
};`
```
2. set evertything up in one setting, like this:
```
pbjs.bidderSettings = {
  '152media': {
    bidCpmAdjustment: function( bidCpm ) {
      return bidCpm * .10;
    }
  },
  brealtime: {
    bidCpmAdjustment: function( bidCpm ) {
      return bidCpm * .10;
    }
  }
};
```

This has probably nothing to do with aliased adapters.

**Comment by headerbidding** [comment]
yairraz, you are a genius! 
I think that is it.
I am testing it right now.

**Comment by headerbidding** [comment]
Also - I have the pbjs.bidderSettings code right below 

googletag.pubads().disableInitialLoad();
    });

Is that correct?

This is my current code:
http://www.flixxy.com/prebid.htm?pbjs_debug=true

**Comment by mkendall07** [comment]
@headerbidding 
I checked your code, it looks good to me. 
Good catch @yairraz

**Comment by headerbidding** [comment]
I just checked the reports and the cpm adjustment is still not working for the alias bidder.

**Comment by headerbidding** [comment]
But when I remove the brealtime bid adjustment, the one52media adjustment then seems to work. 
(I have not fully tested it - need to wait 4 hours for the final report results)

**Comment by headerbidding** [comment]
I removed the brealtime bid adjustment and the one52media adjustment now works.
So there is a conflict (bug)?

**Comment by mkendall07** [comment]
@headerbidding 
I tested your example and it works fine. Here is the code: https://jsfiddle.net/u975ypkj/
Note it actually doesn't run on jsfiddle because of a cross domain iframe issue, but it will work if you run it on your own server. 

Here is a screen shot showing the correct adjustments being made (original bid is $1.00):
![image](https://cloud.githubusercontent.com/assets/1870166/20270804/91674858-aa56-11e6-8c40-d414b4e72a0d.png)

**Comment by headerbidding** [comment]
Thank you, Matt! 
I checked the reports this morning, and you are correct - it is indeed working!

Thank you for sending me the jsfiddle link.
I need to familiarize myself with this great tool!
