### ISSUE TITLE
Batch video cache requests 

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#7873]
## Type of issue
enhancement

## Description
Some publisher pages make many calls to the video cache endpoint. The Prebid Cache Server can handle taking multiple cache entries in one request, but PBJS isn't taking advantage of that feature.

I propose enhancing the caching subsystem to support optional aggregation of cache requests. Right now caching is done in a purely event-driven way: bid response comes in, caching needed, do it. The alternative would be to set a timer, wait for more responses to come in, and batch up any additional responses that come in before the timer pops. 

Proposed config:
```
pbjs.setConfig({
        cache: {
            url: 'https://my-pbs.example.com/vtrack',
            vasttrack: true,
            batchSize: 5,
            batchTimeout: 20   // how long in ms to wait for additional responses
        }
});
```
Note: the feature should work with or without vasttrack.

**Comment by spormeon** [comment]
+1 from me, i'm one of the ones that needs it

**Comment by spormeon** [comment]
another potential thought here as well is, maybe only the winning bids could be sent to cache, that would dramatically cut down the cache pushes for me, e.g. if got 30 bids, but 5 slots, only the 5 winning slot bids sent to cache.  Not sure if that feasible though and easier to send all?

**Comment by patmmccann** [comment]
if pbc is on http2, what problem does this solve?

**Comment by spormeon** [comment]
I was getting so many bids seing to PBC that it was meaning the rrsponce times were climbing and thus timeing it out.  Had a chat with Bretg and he though batching these up in less calls would help stop the timeouts  ( i think I got the idea why right)

**Comment by karimMourra** [comment]
The Video Task Force discussed this and approves.

**Comment by spormeon** [comment]
any development on this one, does it move to WIP now?

**Comment by jlquaccia** [comment]
@bretg Just created a PR for this issue: https://github.com/prebid/Prebid.js/pull/8765.

Had a couple of questions as well:

1. Will the response from the POST /cache call preserve the same order as the request to the /cache endpoint?  For example, would the request order like this: `{ puts: [{obj1: “val1”}, {obj2: “val2”}] }` be returned in the same order with the response: `{ responses: [ {mapToObj1: uuidForObj1}, {mapToObj2: uuidForObj2} ] }` ?
2. When making multiple GET requests to the /cache endpoint, is it expected for the `uuid` query param to always be set to the same value?  For example, if details about 3 videos are sent in a POST request to /cache, 3 calls to GET /cache are made with the same `uuid` value.  The `uuid` value looks to be the first `uuid` returned from the POST request to /cache.  Assuming this is expected, but was just wondering.

**Comment by bretg** [comment]
> Will the response from the POST /cache call preserve the same order as the request to the /cache endpoint?

I hope so, but the PBS team will need to confirm

> When making multiple GET requests to the /cache endpoint, is it expected for the uuid query param to always be set to the same value?

Certainly not. The ad server creative should be set up to pass the correct uuid for the winning line item. e.g. https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_uuid_BIDDERCODE%%

This means PBJS has to do the right thing about splitting a bulk cache write across video daunts so the ad server KVPs work out

**Comment by jlquaccia** [comment]
@bretg ok thanks, that makes sense.  also hoping then that point number one about ordering above is true

**Comment by jlquaccia** [comment]
@patmmccann absolutely!  Will open a PR for it soon.

**Comment by jlquaccia** [comment]
@patmmccann @dgirardi just opened a PR to add documentation for the batch feature here: https://github.com/prebid/prebid.github.io/pull/4453
