### ISSUE TITLE
_sendAdToCreative postMessage with invalid origin

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/Prebid.js#7880]
## Type of issue
A bug where a specific banner resulted in a message event without a valid origin.

## Description
We encountered a banner ad that triggered a message event without origin ( `ev.origin` was `null` ).
As a result, the `_sendAdToCreative` in `secureCreatives.js` tries to send a message with `origin` `null`, which throws an error.

## Steps to reproduce
Unfortunately, it's hard to reproduce, I got the banner a couple of times before it disappeared into the void.
The stack trace from the console did point to that method each time.

## Platform details
Prebid v4.43.1, but the code seems unchanged in the code in master

**Comment by ChrisHuie** [comment]
@ReinoutStevens Does this look like a similar issue to https://github.com/prebid/Prebid.js/issues/7870 ?

**Comment by ReinoutStevens** [comment]
@ChrisHuie Yes, the error looks to be the same.

In our case it appeared to be triggered through a specific ad, and could only be reproduced for a couple of minutes on a specific device. No idea how or why the origin would be null though, or what the actual message was.

**Comment by ChrisHuie** [comment]
@ReinoutStevens closing this and consolidating in https://github.com/prebid/Prebid.js/issues/7870.
