### ISSUE TITLE
Feature request: logInfo call of registered submodules from parent module

### ISSUE THREAD

**Issue by ydennisy** [prebid/Prebid.js#7883]
## Type of issue

**Question**

## Description

I would like to understand how to debug an RTD module running on a website. Looking at the code there are just two log messages which are errors or warnings. There seems no way to see if the module has loaded, which sub modules have loaded.

The closest thing to check any functioning of this part of the prebid flow is `pbjs.installedModules` which returns an array of modules, adapters. Past this I have not been able to find any further information on how to check the internals, which makes debugging extremely challenging! 

Hopefully there is a way and I am just missing it :)

Thanks!

**Comment by patmmccann** [comment]
I think parent modules, eg RTD, ID, could do a logInfo call with the submodules they register?

**Comment by ydennisy** [comment]
Thanks @patmmccann I think that would be a great place to start :)

Are there any currently available methods to achieve something along these lines?

**Comment by patmmccann** [comment]
The timeout rules rtd module writes its config to the console as an example, but we're adding having the rtd module write its submodules as well

**Comment by patmmccann** [comment]
@ydennisy please see #7922 which should resolve your problem;  how does that look?

**Comment by ydennisy** [comment]
Thanks @patmmccann I think this looks a great addition!

I will add some logging to our module and that should be a good way to debug installations.
