### ISSUE TITLE
useBidCache function for a bidder

### ISSUE THREAD

**Issue by ademozkur** [prebid/Prebid.js#7887]
Is it possible to set the useBidCache function to false for a bidder? I have set it as below, but I think it's not working.

pbjs.setConfig({
useBidCache: true,
currency: {
    adServerCurrency: "USD",
    bidderCurrencyDefault: {turktelekom: "TRY"},
},
turktelekom: {
    useBidCache: false
  }
});

**Comment by ChrisHuie** [comment]
This currently is not possible. If you want to override the Turktelekon TTL you would need to build Prebid with this modified
https://github.com/prebid/Prebid.js/blob/bba27758f217cb9bf67dd14b920abe9d849e43b1/modules/turktelekomBidAdapter.js#L8
 
Here is the current useBidCache logic.
https://github.com/prebid/Prebid.js/blob/57fc865c61aed1fa6123882de886bfa59a496ef7/src/targeting.js#L439

**Comment by bretg** [comment]
What's the use case @ademozkur . If a given bidder (e.g. turktelecom) doesn't want to ever cache one of their bids, then @ChrisHuie is right, they just need to set the TTL to 0.
