### ISSUE TITLE
Bug: Some adapters get the GDPR flag as True (1), and some as False (0).

### ISSUE THREAD

**Issue by OronW** [prebid/Prebid.js#7889]
## Type of issue
Bug

## Description
While accepting GDPR on this domain: https://hideout.co/watch.php?v=588751&p=5553 
Some adapters get the GDPR flag as True (1), and some as False (0).
This was tested on a few adapters, such as: pubmatic, smart, rise, 33across

Please see attached picture - for example, pubmatic and rise adapters does not get the GDPR flag as true, but smart adapter does get it.
The adapters read the value of GDPR flag in the same way.

## Steps to reproduce
Go to the attached page, from a European country and accept the GDPR notification.
Check the values of the GDPR flag of different adapters (not the consent string, only the GDPR flag)

## Test page
https://hideout.co/watch.php?v=588751&p=5553

### Expected results
When accepting GDPR, all adapters will have GDPR flag as True

### Actual results
When accepting GDPR, only some adapters have GDPR flag as True

## Platform details
pbjs.version: v6.2.0,  chrome browser, macOs

## Other information
None.
![image (3)](https://user-images.githubusercontent.com/41260031/147404986-687b1a2a-5a23-4f83-9e7b-d605d4416360.png)
![image (2)](https://user-images.githubusercontent.com/41260031/147404990-228dec86-9f97-422b-813a-2ede66adec0a.png)

**Comment by dgirardi** [comment]
@OronW I am not able to reproduce. Using a German VPN, I don't see any of those requests (and in fact I don't even see Prebid). They do appear if I connect from the US but that doesn't let me debug GDPR issues.

**Comment by OronW** [comment]
@dgirardi Thank you for your response. 
I have tested it again now and I get the same results. Also, I do get prebid with version 6.2.0, as I described.
Please see my new attached photo with the prebid version and config.

Could it be that you were blocked? Would it be possible for you to try again using a different VPN service or a different country?

I would be happy to schedule a meeting to reproduce the issue for you, if that's needed. Please let me know if that's something you'd be interested in.

Thank you.

![Screen Shot 2022-01-09 at 11 52 23](https://user-images.githubusercontent.com/41260031/148677506-0c33f354-e3a6-4827-9484-9ea466e7901a.png)
?

**Comment by dgirardi** [comment]
@OronW I don't know what could be blocking me if not the site itself, over which I have no insight (prebid works normally elsewhere). I tried another vpn exit and I have the same problem. I don't have another VPN vendor to try. 

![thing-no-work](https://user-images.githubusercontent.com/10151381/148812017-e6b68c22-4a1b-481d-a875-172565926279.png)

What would help is a minimal example that contains just enough stuff to reproduce the issue, in the style of the [integration examples](https://github.com/prebid/Prebid.js/tree/master/integrationExamples): just the ad markup, Prebid, and Prebid configuration.

**Comment by patmmccann** [comment]
@OronW please provide a test page that is minimal or works for users in all geographies (set gdpr applies to always true)
