### ISSUE TITLE
Adform - No Handling for "No-Bid" Response

### ISSUE THREAD

**Issue by nickjacob** [prebid/Prebid.js#790]
## Type of issue
Bug in Adform Adapter

## Description
Adform's "adx" header bidding endpoint returns no response body when no bid is present:

<img width="910" alt="screen shot 2016-11-14 at 9 50 50 am" src="https://cloud.githubusercontent.com/assets/1192267/20269147/0185b6e4-aa50-11e6-9664-e4a5c02e3d6b.png">

This means that when no bid is present, prebid cannot call the bidsBackHandler before the timeout, since we aren't aware of the "nobid" response from adform (the bids are missing)

## Steps to reproduce

1. Call adform adapter
2. Receive nobid (eg., on low-value/US traffic, with no cookies)
3. observe no response body

### Expected results

If adform response with no body/callback, we should create status "2" bid responses for each bid that we requested

### Actual results

There is no response so the adform JSONP callback is not called

## Platform details

All versions of adform adapter/all platforms

## Other information

This may have to be solved by setting a timeout after script load, which will be cancelled by succesful execution of the callback, eg:

```javascript
// in callbids, reset "global" variable
adformLoaded = false;

// on line 46 in adform adapter
adloader.loadScript(request.join('&'), () => {
  setTimeout(() => {
    if (adformLoaded) {
      return;
    }
    // create error bid responses
  }, 10); // would probably work if we just used 1ms, eg a JS stack
});

// in handleCallback, eg line 63:
adformLoaded = adItems && adItems.length;

```

**Comment by mkendall07** [comment]
Thanks @nickjacob for the bug report. 
@prebid/adform any thoughts on this?

**Comment by braizhas** [comment]
@nickjacob Could you provide additional information - Adform adapter config and/or request url to Adform ADX?

Blank response is possible only in case of invalid request. Most probably it's setup issue. I don't see a need to somehow workaround this behaviour. If there are some bugs in request url forming or request handling they will be fixed.

**Comment by nickjacob** [comment]
@braizhas sorry for the delay. You're right—it's invalid parameters. I think we can close this. Thanks!
