### ISSUE TITLE
Xaxis bid adapter still listed in docs but is removed/has no alias in AppNexus adapter

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/Prebid.js#7900]
## Type of issue
Xaxis bid adapter was removed (in 5.x?) but documentation is still available. Xaxis should probably be an alias for AppNexus, but it is not listed as such in the AppNexus adapter.

https://docs.prebid.org/dev-docs/bidders/xhb
https://github.com/prebid/Prebid.js/blob/master/modules/xhbBidAdapter.md

@daniel-hoffmann

**Comment by ChrisHuie** [comment]
@bretg can't remember what we decided for the download page and adapters that can no longer be downloaded since we have moved past 5.x. Currently, we are on 5.9 as the oldest available

**Comment by patmmccann** [comment]
The new plan is: Bidders that have been removed will still have documentation for publishers' reference, with an added indication that the bidder is no  longer in current versions.
