### ISSUE TITLE
Kargo Bid Adapter: meta.advertiserDomains passing incorrectly

### ISSUE THREAD

**Issue by robertrmartinez** [prebid/Prebid.js#7909]
## Description
We are seeing scenarios where bid adapters are setting invalid `meta.advertiserDomains`

This field should be an array of strings

We noticed at least one adapter sending it as an double array with one string in it like so:

![image](https://user-images.githubusercontent.com/13972794/148279832-05124439-20af-4e44-8e1c-cf65e9a71e43.png)

```
[['nytimes.com']]
```

I am unsure if this is happening ALL of the time for KARGO, or if there are certain scenarions where their server responds with a single adomain or it is always with the array of single element.

They get a bid response from their exchange =>

Notice that it returns `advertiserdomains` as an array of advertisers (which is exactly what it should be)

![image](https://user-images.githubusercontent.com/13972794/148280447-5a5a13db-674d-4306-ad9e-ad73e70ec75d.png)

BUT their code wraps this inside of another array as seen here:

https://github.com/prebid/Prebid.js/blob/master/modules/kargoBidAdapter.js#L77

Which results in ![image](https://user-images.githubusercontent.com/13972794/148279832-05124439-20af-4e44-8e1c-cf65e9a71e43.png)

which is technically not correct!

We found this in our Analytics aggregations so I added a PR for us to handle this for now: https://github.com/prebid/Prebid.js/pull/7908

But want to let Kargo know just in case!

**Comment by robertrmartinez** [comment]
@jsadwith As you were the last person to update the `kargoBidAdapter` I wanted to let you know this issue we uncovered.

Let me know what you think!

**Comment by jsadwith** [comment]
@robertrmartinez Thanks for the note. This is definitely an issue from our end, so I created a PR to remove the extra array - #7910
