### ISSUE TITLE
Aliasing Appnexus 

### ISSUE THREAD

**Issue by tedrand** [prebid/Prebid.js#791]
## Type of issue

Question

## Description

I am helping someone who is trying to use the Appnexus adapter for District M and Sekindo bidders. I am using both of the following:

pbjs.aliasBidder('appnexus','districtm');
pbjs.aliasBidder('appnexus','sekindo');

Will this create an issue, and is it possible to do this? 

### Expected results
Expected both District M and Sekindo to record impressions.

### Actual results
Sekindo is not recording impressions.

## Platform details

Prebid 0.14.0

**Comment by mkendall07** [comment]
@tedrand 
It should work fine. What reporting are you looking at that shows Sekindo not recording impressions?

**Comment by tedrand** [comment]
Thanks for getting back, it sounds like we are hearing this from Sekindo's reporting but I will confirm.

**Comment by tedrand** [comment]
It seems like my issue stems from the 'sekindo' alias still being in the bidderRegistry even though the official adapter was recently pulled. I've tried changing the alias to 'skindo', and it has at least suppressed the warning that the alias already exists. Pub should be pushing fix live in the next couple of days so we'll see.
