### ISSUE TITLE
PBS s2s request with bidder level ortb2.user.data but no request level user data fails Prebid Server validation

### ISSUE THREAD

**Issue by wqi1972** [prebid/Prebid.js#7918]
## Type of issue
Most likely it is a bug, but it might be a feature change for either PBJS or PBS.

## Description

If bidder level ortb2.user.data is set, but there is no request level user data, the s2s bidding will get `Invalid request` response from Prebid Server.

## Steps to reproduce
Inside our prebid library, we enable Permutive RTD, and configure Prebid Server (s2s) bidding. And it doesn't enable any user id module.
The Prebid Server version we use is v0.185.0

Inside function `mergeOrtbConfig` in https://github.com/prebid/Prebid.js/blob/master/modules/permutiveRtdProvider.js, Permutive RTD set bidder level ortb2.user.data for Rubicon and AppNexus.
And inside function `addBidderFirstPartyDataToRequest` in  https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter/index.js, it injects that ortb2 data into bidder level PBS bidding request, in format of
 ```ortb2: {user: {data: [{name: "permutive.com", segment: []}]}} ```
Since we don't enable any user Id module, the request doesn't have request level user data.
When Prebid Server (v0.185) receives the request, it raises exception:
```
Invalid request: incorrect First Party Data for bidder appnexus: User object is not defined in request, but defined in FPD config
Invalid request: incorrect First Party Data for bidder rubicon: User object is not defined in request, but defined in FPD config
```
(older PBS version doesn't have that issue, this is a new feature comes in PBS v0.183, from PR: https://github.com/prebid/prebid-server/pull/1906)

And if I enable user id module, say Criteo, then inside the PBS s2s call, it will add request level user data, e.g.:
```user: {ext: {eids: [{source: "criteo.com", uids: [{,…}]}]}}```
With that extra data, the Prebid Server request works fine.

## Test page
Here is a test page with Permutive RTD + Prebid Server s2s, but no user Id module:
https://www.realtor.com/realestateandhomes-search/Las-Vegas_NV?prebid_stage=1&abTest=noId
Filter network call with `prebid.realtor.prod.newsiq.net/openrtb2/auction` (this is our PBS endpoint), 
You will find that request get response
```
Invalid request: incorrect First Party Data for bidder appnexus: User object is not defined in request, but defined in FPD config
Invalid request: incorrect First Party Data for bidder rubicon: User object is not defined in request, but defined in FPD config
```

Here is a test page with Permutive RTB + Perbid Server s2s + Criteo User ID module
https://www.realtor.com/realestateandhomes-search/Las-Vegas_NV?prebid_stage=1&abTest=criteoId
Filter network call with `prebid.realtor.prod.newsiq.net/openrtb2/auction`
You will find for the first s2s request, it may or may not work, since Criteo user ID loads into Prebid async. But for 2+ s2s request, they work as expected.

More specifically, when pbjs.getUserIdsAsEids() is empty, the s2s request with bidder level ortb2.user.data can't pass Prebid Server validation after v0.183; when pbjs.getUserIdsAsEids() is not empty, that issue doesn't exist.

The payload of s2s request with bidder level ortb2.user.data is something like this:
![Screen Shot 2022-01-06 at 4 01 58 PM](https://user-images.githubusercontent.com/4923189/148469484-2a8fa328-a53c-4133-98b9-87ef1fbcc7e3.png)
If following user data exists in the s2s request,
![Screen Shot 2022-01-06 at 4 03 18 PM](https://user-images.githubusercontent.com/4923189/148469573-2eb6b752-907b-4c43-89d4-603b9a5d9aee.png)
then it works fine, if it doesn't, it fails.

### Expected results
Not sure what are the expected results. 
If Prebid Server can accept bidder level ortb2.user.data without request level user data, then the change need to happen on PBS side. But I believe there is reason for https://github.com/prebid/prebid-server/pull/1906 to add that restriction.

Overall, I think it needs a review on how to pass first party data to Prebid Server. Then find out what expected results are.

## Other information

For this issue, I first contacted Permutive engineer team, they want us to check with Org to get more information on why a user ID (or the user id module) would be a requirement to pass FPD to a bidder.  The idea is that you should still be able to pass user data via ortb2 in the absence of a user ID (or the user id module).  e.g. when the user has 3p cookies disabled.
I think this point makes sense. 

Besides, as it shows in https://www.realtor.com/realestateandhomes-search/Las-Vegas_NV?prebid_stage=1&abTest=criteoId, even user id module enables, and 3p cookies enables, because user ids assignment is async, it still causes first s2s bidding may fail on the page.

**Comment by ChrisHuie** [comment]
@wqi1972 my apologies for not responding to this issue sooner. We have a biweekly meeting to review all new issues and this one seems to may have slipped through in the new year. I will make sure and bring this up Monday with the team :)

**Comment by bretg** [comment]
Thanks for the report @wqi1972 - sorry for the delay. Opened the PBS issue over at https://github.com/prebid/prebid-server/issues/2234. Closing this one.
