### ISSUE TITLE
How to support multiple size Sovrn tags for a single adUnit?

### ISSUE THREAD

**Issue by pribeh** [prebid/Prebid.js#792]
This is a support question. Is the following the correct way of adding (overriding) multiple sizes for sovrn tags? I tried the approach of adding multiple tags each with a distinct size but I received an unexpected token in console.

Thanks!

`bids: [{
            bidder: 'sovrn',
            params: {
                tagid: '409703',
                sizes: [[728, 90], [300, 250]]
            }
        }]
`

**Comment by mkendall07** [comment]
I believe you need to specify multiple bidders for Sovrn, @protonate can confirm.

**Comment by pribeh** [comment]
Thanks @mkendall07 for responding. I originally had the following setup but I kept getting an "unexpected token in console". As you can see from the complete ad unit code (below), I'm using the responsive coding. I've since switched to what I have in my original post above. 

 ` {
        code: 'div-gpt-ad-1476717642092-6',
        sizes: [[728, 90], [234, 60], [468, 60], [300, 100]],
        sizeMapping: [ 
            {
                minWidth : 1050,  //if device screen width is < 1024 && > 480, use these sizes
                sizes : [728, 90]
            },
            {
                minWidth : 760,  //if device screen width is < 1024 && > 480, use these sizes
                sizes : [[728, 90], [468, 60], [300, 100]]
            },
            {
                minWidth : 468,  //if device screen width is < 480 && > 0, use these sizes
                sizes : [[468, 60], [300, 100]]
            },
            {
                minWidth : 300,  //if device screen width is < 480 && > 0, use these sizes
                sizes : [[300, 100], [234, 60]]
            },
            {
                minWidth : 234,  //if device screen width is < 480 && > 0, use these sizes
                sizes : [234, 60]
            }
            
        ],
        bids: [{
            bidder: 'sovrn',
            params: {
                tagid: '409702',
            },
            {
            bidder: 'sovrn',
            params: {
                tagid: '409703',
            }
        }]
    },`

**Comment by mkendall07** [comment]
You need to remove the comma after `tagId`. 

```
{
	code: 'div-gpt-ad-1476717642092-6',
	sizes: [
		[728, 90],
		[234, 60],
		[468, 60],
		[300, 100]
	],
	sizeMapping: [{
			minWidth: 1050,
			sizes: [728, 90]
		}, {
			minWidth: 760,
			sizes: [
				[728, 90],
				[468, 60],
				[300, 100]
			]
		}, {
			minWidth: 468,
			sizes: [
				[468, 60],
				[300, 100]
			]
		}, {
			minWidth: 300,
			sizes: [
				[300, 100],
				[234, 60]
			]
		}, {
			minWidth: 234,
			sizes: [234, 60]
		}

	],
	bids: [{
			bidder: 'sovrn',
			params: {
				tagid: '409702',  //HERE
			},
			{
				bidder: 'sovrn',
				params: {
					tagid: '409703',    //HERE
				}
			}]
	},
```

**Comment by pribeh** [comment]
I get the same "unexpected token" when using multiple bidders without the comma. Check out the [link](http://www.pomofo.com/article/dues-ex?pbjs_debug=true). When I use the other combination (from my original post) the bid process appears to happen but I'm not seeing any ads from sovrn yet.

**Comment by mkendall07** [comment]
You didn't close the bidder object:
```
bids: [{
	bidder: 'sovrn',
	params: {
		tagid: '409706'
	}
  }, //add
	{
		bidder: 'sovrn',
		params: {
			tagid: '409704'
		}
	}]
```

**Comment by pribeh** [comment]
Thanks @mkendall07. I feel dumb. If you check back at the link I think everything appears to be working.

**Comment by mkendall07** [comment]
It happens. Whenever you see an error of this type, it generally means bad syntax in JS.
