### ISSUE TITLE
Ability to alter the VAST XML to include impression tracker

### ISSUE THREAD

**Issue by gpolaert** [prebid/Prebid.js#7921]
## Type of issue
Feature Request 

### Why?

The goal is to improve the measurement of the video ads in the context of the in-stream.

The display and the out stream formats have they own dedicated event (bidWon), allowing publishers and prebid analytics adpaters to track the impressions.

In the context of the in-stream, there is no such event due to the fact that the vast chain is executed by a third party (video player, ima sdk3, ...) and Prebid has no grip on it. 

Usually, impressions are tracked by a dedicated section "tracker" in the VAST XML.
See 2.3.4 of the [VAST specs](https://iabtechlab.com/wp-content/uploads/2019/06/VAST_4.2_final_june26.pdf)

### What?
I would like to add in Prebid the ability for the publishers to add their own tracker in the VAST XML built during the auction. 

IMO, one way to do that id to alter the vast xml file just before is sent to the cache server. 

It could be by adding a new event like `beforeRequestsBids` or a new property in the video config where we can specify a function.

### Next steps
What do you think? 
How do you want to build that feature (event, custom function ...)
Can I suggest a PR?

**Comment by gpolaert** [comment]
https://github.com/prebid/Prebid.js/issues/7873 is not directly related, but in the same scope

**Comment by spormeon** [comment]
wouldnt this imp tracker fall under GDPR?  If your using DFP, its already tracking imps?

**Comment by gpolaert** [comment]
Hello,

I think it serves different purposes, 

GAM is perfect for reporting, but if you want to troubleshoot what's going on with the instream chain you need to have access to the full granularity (like the analytics part of Prebid).

Allowing the ability to fire events will help to debug.

About the GDPR, I'm not an expert, so we have to check, but this data is owned by the publisher, for the publisher needs and this data is technical, that means you can rely only on technical fields (impressionId, ...)  and exclude all user related information to be compliant.

**Comment by spormeon** [comment]
might want to check out this in the mean time, think does what yourt after: https://chrome.google.com/webstore/detail/quadruplex/mbbjgfpchjfillohcbpgljakajipagbc

**Comment by gpolaert** [comment]
Thanks @spormeon,

The plugin helps for local troubleshooting. The goal here is to track and gather all events (real monitoring) into an analytics tool.

**Comment by gpolaert** [comment]
![Uploading image.png…]()
