### ISSUE TITLE
webpack complaining about babelrc missing present-env config for corejs

### ISSUE THREAD

**Issue by khatibda** [prebid/Prebid.js#7943]
## Type of issue
it's a webpack warning, not a bug per se, but should be heeded and fixed.

## Description
we recently updated babelrc to include "useBuiltIns" in babel/preset-env. #7641 
as a result, when we do a webpack build in our own pipeline, we get the following new webpack warning:

`web-frontend-1                  | WARNING (@babel/preset-env): We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
web-frontend-1                  | 
web-frontend-1                  | You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:
web-frontend-1                  | 
web-frontend-1                  |   npm install --save core-js@2    npm install --save core-js@3
web-frontend-1                  |   yarn add core-js@2              yarn add core-js@3
web-frontend-1                  | More info about useBuiltIns: https://babeljs.io/docs/en/babel-preset-env#usebuiltins
web-frontend-1                  | More info about core-js: https://babeljs.io/docs/en/babel-preset-env#corejs
`

As per babel details, we need to specify the core-js version used.
https://babeljs.io/docs/en/babel-preset-env#corejs

something like this:
` 
"useBuiltIns": "entry", // or "usage"
`
`
"corejs": { "version": "3.13.0"}, // or whatever version used in package.json, e.g. currently "3.13.0"
`

## Steps to reproduce
run a webpack build, assuming you're building prebid.js in your own pipeline

## Other information
looks like this fix was included in v6.1

**Comment by khatibda** [comment]
tagging @ChrisHuie and @patmmccann for visibility re #7641

**Comment by ChrisHuie** [comment]
#7942 - I think should solve this when it is merged.

**Comment by ChrisHuie** [comment]
@khatibda planning to address this shortly. Likely with the next release
