### ISSUE TITLE
AppNexus 1st party data support not working?

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/Prebid.js#7952]
## Type of issue
Missing feature/wrong documentation/misunderstanding by me

## Description
The docs for the Appnexus bid adapter states that 1st party data is supported but it doesn't seem to work (and there is no evidence in the adapter code for it to work):
https://docs.prebid.org/dev-docs/bidders/appnexus

## Steps to reproduce
Use the ortb2 or ortb2impl structure with key values, as described in https://docs.prebid.org/features/firstPartyData.html#first-party-data---prebidjs

All adapters tested (Rubicon etc) handles the 1st party data and send it to their endpoints respectively, but the AppNexus adapter doesn't read the data.

**Comment by peczenyj** [comment]
there are some RTD submodules such as sirdata and weborama (since next version) that use a custom code to convert the data to appnexus structure. Can work as a workaround

**Comment by bjorn-lw** [comment]
> there are some RTD submodules such as sirdata and weborama (since next version) that use a custom code to convert the data to appnexus structure. Can work as a workaround

Thank you, but my main issue is that the documentation is wrong and misleading unless I miss something.

**Comment by gglas** [comment]
We are documenting this and working on fixing it here - https://github.com/prebid/prebid.github.io/issues/3444 - notifications to go to affected bidders sortly

**Comment by bjorn-lw** [comment]
@gglas thank you very much! I will close this issue then.
