### ISSUE TITLE
Prebid.js 7: update pbsBidAdapter to use imp.ext.prebid.bidder.BIDDER

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#7954]
## Type of issue
refactoring

## Description
Some time back, the Prebid Server committee moved the ortb2 location of bidder parameters from imp[].ext.BIDDER to imp[].ext.prebid.bidder.BIDDER. This was covered in https://github.com/prebid/prebid-server/issues/1478

We would like to move Prebid.js to utilize this new location in version 7 in the pbsBidAdapter

**Comment by dgirardi** [comment]
This does not look like a breaking change to me; it should be entirely invisible to everything except the PBS adapter. But, does the server advertise support for the new location? Or can we assume that every PBS instance now understands it?

**Comment by patmmccann** [comment]
> Or can we assume that every PBS instance now understands it?

Known host companies now understand it, but old version of PBS may not, and we're not sure how many exist.

**Comment by patmmccann** [comment]
Code to fix appears to be here

https://github.com/prebid/Prebid.js/blob/2f33e7d3b2b0a62c9890f93cb7b8835d360471bc/modules/prebidServerBidAdapter/index.js#L713
