### ISSUE TITLE
Potential of refactoring adapters into separate webpack entry points

### ISSUE THREAD

**Issue by snapwich** [prebid/Prebid.js#796]
This issue is to have discussion around the feasibility and willingness of Prebid.js collaborators to standardize encapsulation for the adapters and have them be built as individual files separate from the primary Prebid.js codebase.  Inclusion into Prebid.js would then universally happen through the external API for all adapters. Having adapters as separate files would provide for the prebid bundle to either be created through regular concatenation and included on the page (which could be at build or runtime since concatenation is much more performant than webpack), or through being included as multiple script tags (main bundle + adapters).

Some advantages this could possibly have over the current implementation:
- Allowing the resolution of adapter dependencies at runtime or during building as opposed to only during a build step.
- Allow publishers to quickly add/remove bidders without the requirement of rebuilding or redownloading prebid.
- Minimizing and simplifying the touch points that an adapter currently has within the main codebase.  Currently an adapter "reaches" into Prebid.js grabbing the parts it needs creating a mesh of dependencies.
- Strictly defining shared dependencies to minimize code bloat and create a solid interface to Prebid.js, while still allowing adapters to bloat individually (if they need/want).

One possible way to facilitate this would be through the use of multiple webpack entry points and constructor dependency injection (or some other means of dependency injection) to accommodate the dependencies needed for an adapter to communicate with Prebid.  This would deviate from the current implementation of importing directly from Prebid.js code (imports could still be used for non-Prebid concerns).

Possible complications:
- This could create issues around load-order that would need to be addressed, for instance: when the command queue is executed vs when adapters are registered.
- While dependency injection is usually considered friendlier for testing, due to the spec change some mocks might require updates.
- Currently there are some different methods of registering adapters (createNew vs regular "new").  We would need to account for this or standardize.

Considerations:
- Would we want the individual adapter files to auto-register themselves when included on page or does that change to a manual process?
- Some inter-dependencies between files might need to be solidified, like the pbjs global (a dynamic prebid global, which is currently allowed, could cause mismatches between files).

**Comment by mkendall07** [comment]
@snapwich 
Thanks for the detailed write up. Lots of stuff to unpack here... 
Initial question, what's your thought on how publisher "prebid package" would be delivered? I think loading each adapter source from a file is an anti-pattern. I suppose you are thinking about integration into a publisher's build / deployment process to do the bundling? or something prebid.js would handle?

**Comment by snapwich** [comment]
> Initial question, what's your thought on how publisher "prebid package" would be delivered? 

It could be both as it is now Prebid.js code + adapters bundled together into a single file (but in this case it would be Prebid.js codebase with adapters concatenated to the end of `prebid.js` instead of being intermingled), or it could be multiple files included on the page (i.e. non-concatenated).

> I think loading each adapter source from a file is an anti-pattern.

In what way?  With the upcoming HTTP/2 [some consider bundling soon to be an anti-pattern](http://stackoverflow.com/questions/30861591/why-bundle-optimizations-are-no-longer-a-concern-in-http-2).  Either way, it'd just be more options for the publisher to utilize, they don't have to be loaded as separate files.

> I suppose you are thinking about integration into a publisher's build / deployment process to do the bundling? or something prebid.js would handle?

Either-or.  Prebid.js could still produce a prebid.js + adapters bundle.

One possibility I envision is the main output of an `npm run build` being `prebid.js` and additional adapter files like `rubicon.adapter.js`, `appnexus.adapter.js` etc.  Then an additional `npm run combine` when supplemented with a list of adapters could bundle them together for download from the site or regular usage; but it would effectively just be concatenating the files together; so practicality wise it'd be no different than including the files individually in the page.

**Comment by snapwich** [comment]
Also, something I forgot to mention.  This would also allow the ability for the adapters to be removed from this repository if wanted for individual access, controls, issues, pull-requests for each.  They would also have the ability to be separated in npm and versioned appropriately and updated separately from a full Prebid.js release.

**Comment by mkendall07** [comment]
>>I think loading each adapter source from a file is an anti-pattern.

>In what way? With the upcoming HTTP/2 some consider bundling soon to be an anti-pattern. Either way, it'd just be more options for the publisher to utilize, they don't have to be loaded as separate files.

I should say it's an anti-pattern for our project. We've seen that loading external files is a huge hit to prebid performance as it drags out the auction unnecessarily. Of course it wouldn't have to be loaded that way, and we could continue to provide a bundling service as you mentioned. 

>Also, something I forgot to mention. This would also allow the ability for the adapters to be removed from this repository if wanted for individual access, controls, issues, pull-requests for each. ...
That's a huge plus.

**Comment by snapwich** [comment]
@mkendall07  Do we want to close this issue since it sounds like it's part of the 1.0 proposal in #891 or is it worth keeping open to discuss specific solutions of how the project will be broken up?

**Comment by mkendall07** [comment]
Let's keep this open to discuss technical approaches here. What do you think about the mono repo structure? https://github.com/babel/babel/blob/master/doc/design/monorepo.md

**Comment by snapwich** [comment]
I guess I don't have a huge preference one way or the other.  As long as the individual components are packaged separately for individual use outside of the build-step then we've accomplished my biggest goal with this proposal.  I don't have a lot of experience with a mono repo design, but it looks like they use https://www.npmjs.com/package/lerna to manage the linking and publishing of the packages, and other than that treat it as one big project.

Earlier when I mentioned the idea of having the adapters "removed from this repository ... for individual access, controls, issues, pull-requests for each." you mentioned it would be a "huge plus."  Do you still feel that way?  Or do you feel that the mono repo pluses outweigh any advantage there?

**Comment by mkendall07** [comment]
I haven't looked into all the details as of yet, but my hope was that a mono structure would give us a good compromise between single and multi repo structure. I feel like having separate repos for each adapter as a big overhead to manage.

**Comment by snapwich** [comment]
@mkendall07, I think the mono repo structure could work well for Prebid.js.  I think we need to restructure how adapters and other modules are included into the Prebid.js framework to make such a structure more feasible, however.

Currently such modules (only adapters currently) are included using webpack loaders and specified through config files (package.json and adapters.json) to be included at build time.  I think it would be beneficial to start defining a more standardized way of extending Prebid.js at runtime.  Some advantages of having runtime extensibility would be things like allowing separate modules to have different build requirements (or not requiring a build step at all) and making reconfiguration as simple as dropping in various pieces.

I would like to make a proposal of how to accomplish the above with minimal change to the current API.  An adapter module would look similar to the following:

```javascript
/* globals pbjs */
pbjs.que.push(function({
	bidFactory,
	bidManager,
	adapterManager,
	utils,
	ajax,
	// ... and possibly more dependencies
}) {
	function Adapter() {

		// ... other methods

		this.callBids(bidRequest) {
			// ... build request
			ajax(SOME_ENDPOINT, function(response) {
				// ... build bid
				var bid = this._buildBid(
					bidFactory(1, bidRequest),
					response
				);
				bidManager.addBidResponse(bidRequest.placementCode, bid);
			});
		}
	}
	adapterManager.registerBidAdapter(new Adapter());
});
```
The main difference, as you can see, is that we would now be handling dependencies through dependency injection.  This is very similar to how the AMD or angular module systems work.  However, we could reduce some of the bloat of building a dependency management system by having Prebid.js send ALL the dependencies any module could need as an object, and still have the niceness of explicit dependencies by using object destructuring (for modules that have a babel built-step), or just picking the dependencies off the object parameter.

Some new conventions would need to be enacted.  For instance, no more renaming the `pbjs` global (which I think is a good thing).  Also, this module would be required to be included after the Prebid.js core (so that `pbjs` is defined) or a requirement would need to be added that each module be expected to create the global if it doesn't exist (less ideal, IMO).  All required modules would need to be included before any que blocks initiate an auction; or any modules that initiated auctions (which would be a possibility) would be required to included last.

Following this convention, and structuring modules as such would result in the ability to build modules individually across the mono-repo (or outside the repo).   The only change to Prebid.js core would be the passing of dependencies to functions in the callback que.  Modules could be tested (passing in stubbed dependencies) individually, or tested without stubbing the dependencies across the mono repo to perform integration tests.

Inclusion of modules could now be done in a fashion similar to 

```html
<script src="prebid.js"></script>
<script src="prebid-appnexus-adapter.js"></script>
<script>
pbjs.que.push(function() {
  pbjs.requestBids(...);
});
</script>
```

Or if desired, modules could be concatenated to the Prebid.js core and included as a single script include.

Thoughts?

**Comment by snapwich** [comment]
Another option is to do the above with an additional API endpoint very similar to the command que.  One uncommon use-case missing above is module configuration.  So if we had an endpoint like `pbjs.registerModule("module", function({dependencies}, {configuration}){` you could use another endpoint to configure a module by name before it is run.

There's possibly other ways to configure a module that don't require API changes that I'm not thinking of...

**Comment by mkendall07** [comment]
Cool stuff. Let me simmer on this a bit.

**Comment by snapwich** [comment]
Here's an expansion on this conceptual module system:

```Javascript
// prebid.js code at top.  build can concatenate these files together.

// ./modules/module1.js
pbjs.module("module1", ["module2"], function({
	utils,
	config,
	dependency: {
		module2
	}
}) {
	utils.logMessage([
		config.thing,
		module2.stuff
	].join(",")); // prints "1, 2"
});

// ./modules/module2.js
pbjs.module("module2", function({
	config
}) {
	return {
		stuff: config.thing
	}
})

// this bootstrap + config snippet either included automatically by build or manually included based on build configuration
pbjs.enableModules({
	"module1": {
		"thing": 1
	},
	"module2": {
		"thing": 2
	}
})
```

# Features
- Prebid.js internals (bidManager, bidFactory, utils, etc) provided through dependency injection
- dependency resolution to be part of Prebid.js core for proper module load order
- configuration and dependent modules provided through injected objects: `config` and `dependency` _should we allow modules to view/edit other module's configs?  Probably not, but we could._
- automatic module bundling and bootstrapping or manual module bundling and bootstrapping based on build-time configuration
  - in automatic mode, configuration can be provided through build-time config file and `enableModules` snippet auto-concatenated to end of Prebid package
  - in manual mode, additional modules can be included at runtime and configuration is provided as param to `enableModules` which starts modules loading.  This allows the inclusion of closed-source modules (not part of build or source tree).
- concatenation of modules or not depending on build configuration (maybe separate from above configuration)
- build-steps: babel for modern code, $$PREBID_GLOBAL$$ replacement, optional concatenation step for automatic bundling.  _do we want to use webpack and allow modules to include other libraries...? or do we handle all through dependency injection from Prebid.js?  Maybe the later for efficiency sake_

# Intended exclusions
- async dependency loading.  _(For performance reasons.  However could still be accomplished using manual mode above.)_
- version management _(adds a lot of complexity and mostly unnecessary with mono-repo build)_
- optimized loading (dependency deduping, etc)

Feel free to ask for clarifications below or provide any feedback.  Thanks!

**Comment by mkendall07** [comment]
@snapwich do we lose the ability to use `class` it will work with this pattern (+ babel)?

**Comment by snapwich** [comment]
Since each of the modules would be compiled with babel, you could still use the `class` keyword.

**Comment by snapwich** [comment]
Closing this issue in-favor of the newly created #1086
