### ISSUE TITLE
Richaudience Bid Adapter: uncaught error on non-gdpr locations

### ISSUE THREAD

**Issue by michae1** [prebid/Prebid.js#7960]
## Type of issue
Bug

## Description
Richaudience causes errors on non-gdpr locations:
`Cannot read properties of undefined (reading 'gdprApplies')`
because bidderRequest.gdprConsent is undefined

## Steps to reproduce
Open page to use at least prebid 6.6.0 from non-gdpr location

### Expected results
No errors, bid request sent

### Actual results
Error in console
`Cannot read properties of undefined (reading 'gdprApplies')`
Bid request is not sent

## Platform details
Prebid.js 6.6.0+

## Other information
Fix: https://github.com/prebid/Prebid.js/pull/7955
Related comment: https://github.com/prebid/Prebid.js/commit/fb0a73aab7a366a80db92cd06b94ff71fa24652c#r61200506

**Comment by ChrisHuie** [comment]
Closing with pr #7962
