### ISSUE TITLE
Post-bid issues with event emit order (BID_WON before AUCTION_END)

### ISSUE THREAD

**Issue by mpereira96** [prebid/Prebid.js#797]
## Type of issue
Question

## Description
It seems in a post-bid scenario:

![image](https://cloud.githubusercontent.com/assets/16920897/20315301/4fb5a044-ab55-11e6-92c5-fdf5843a6c00.png)

The standard is to call `pbjs.renderAd` inside the `pbjs.requestBids` handler. The problem with this is that the `AUCTION_END` event is only dispatched after the `pbjs.requestBids` handler is executed so the `BID_WON`  event will be dispatched first from `pbjs.renderAd`. This can lead to some issues if we are to assume the correct order is to have `AUCTION_END` before `BID_WON`.

Potentially there could be a better way to implement postbid on the frontend and avoid this.

Is this something you were aware? We would like to know your thoughts. We are happy to contribute to fix this issue.

**Comment by mkendall07** [comment]
It's an interesting callout, not really intentional, it's just the way it works with postbid. Is this causing any issues? I suppose we could move `AUCTION_END` up before executing the callback, not sure what side effects (if any) that would cause.

**Comment by marian-r** [comment]
@mkendall07 moving `AUCTION_END` up before executing the callback would be a perfect solution for us. We are happy to contribute a PR. Are we good to go?

**Comment by mkendall07** [comment]
@matthewlane @protonate any objections?

**Comment by protonate** [comment]
Makes sense to me.

**Comment by mkendall07** [comment]
@marian-r 
Feel free to submit a PR. Thanks

**Comment by marian-r** [comment]
Thank you. It might take a while as it's lower in our priorities, but me and @mpereira96 wanted to know your opinions first.

**Comment by protonate** [comment]
AUCTION_END is intended as the final event of the auction, just prior to starting the next, if there is one. However BID_WON events are not tied to the AUCTION_END event in that the `renderAd` event is called in the response from the ad server, and these could begin before and continue after AUCTION_END. Closing and see comment on #852 about possibly adding another event.
