### ISSUE TITLE
Bid adapters exposing vendor ID

### ISSUE THREAD

**Issue by slimkrazy** [prebid/Prebid.js#7977]
## Type of issue
Question

## Description
Hey folks - here's the scenario: One publisher in Europe was running Prebid with our latest bid adapter enabled and Prebid was not including it in auctions because of consent under GDPR. This was happening for everybody who visited the test page, and I can tell you that nobody here has _not_ provided the relevant consent for our company to serve ads.

I did some digging around in the source code and I noticed that the Prebid core is checking the exposed vendor ID from the bid adapter, so we made a change to our bid adapter to ensure this was exposed and it fixed the issue. Our old bid adapter never exposed this and this issue has never been flagged before. Additionally, the documentation doesn't appear to reference the importance of the gvlid property.

https://docs.prebid.org/dev-docs/bidder-adaptor.html

Is this property required, if so - how long has this behaviour been in place for?

**Comment by patmmccann** [comment]
Just to clarify for readers 'us' is Yahoo, 'our old bid adpater' is AOl, 'our new bid adapter' is Yahoo

**Comment by gglas** [comment]
This has always been a requirement -- in order to be GDPR eligible bidders must have vendor IDs exposed for prebid -- but you're right that documentation doesn't indicate this as a required field -- we will go in to  fix.

**Comment by patmmccann** [comment]
GVL Id's are needed to prevent the gdpr enforcement module from filtering non-consented adapters. Publishers can override bidder enforcements with 'vendorExceptions'

**Comment by bretg** [comment]
PR to update the bid adapter doc to make this clear. https://github.com/prebid/prebid.github.io/pull/3539

> how long has this behaviour been in place for?

Years. Since the beginning of Prebid.js support for enforcing TCF2, it filtered out adapters that didn't supply GVLID when in GDPR scope. My guess would be v3.12.

**Comment by bretg** [comment]
@slimkrazy - may we close this with the improved documentation ?
