### ISSUE TITLE
Prebid.js 6.10.0 webpack build fails with module not found errors related to "prebidjs-polyfill"

### ISSUE THREAD

**Issue by jxlarrea** [prebid/Prebid.js#8021]
## Type of issue
Bug

## Description
Since version 6.10.0 using Prebid.js as an NPM import, every build fails with this:

```
ERROR in ./node_modules/prebid.js/modules/ixBidAdapter.js 32:0-53
Module not found: Error: Can't resolve 'prebidjs-polyfill/includes.js' in 'D:\Visual Studio Projects\ITSD\src\ITSD.Web.CDN.Static\node_modules\prebid.js\modules'
```

## Steps to reproduce
Webpack build 

### Expected results
Successful build.

### Actual results
All prebid modules throw errors complaining about js modules not found related to "prebidjs-polyfill".

## Platform details
All platforms, node, NPM.

**Comment by dgirardi** [comment]
The interesting bit is that it tested OK before release using `"prebid.js": "file:<local repo>"` from a test consumer package. But it does fail when the released prebid.js is pulled from npm. https://github.com/prebid/Prebid.js/pull/8028 reverts the change until I figure out a better testing strategy.
