### ISSUE TITLE
Prebid server adapter incompatible with sizeMappingV2?

### ISSUE THREAD

**Issue by WalterT** [prebid/Prebid.js#8032]
## Type of issue
Bug

## Description
The Prebid server adapter seems to be incompatible with the advanced size mapping module. Whenever ad units have a mediaTypes.banner.sizeConfig element rather than mediaTypes.banner.sizes, this error is raised when calling bids: 

_TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at G.e.callBids (prebid-6.2.0.js:27)
    at prebid-6.2.0.js:9
    at Array.forEach (<anonymous>)
    at Object.w.callBids (prebid-6.2.0.js:9)
    at Object.run (prebid-6.2.0.js:9)
    at d (prebid-6.2.0.js:9)
    at Object.$ (prebid-6.2.0.js:9)
    at Object.<anonymous> (prebid-6.2.0.js:9)
    at Object.callBids (prebid-6.2.0.js:9)_

 referring to this function in the Prebid server adapter: https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter/index.js#:~:text=out%20bid%20requests%20*/-,baseAdapter.callBids,-%3D%20function(s2sBidRequest%2C%20bidRequests

All validAdUnits seem to be filtered out because of that.

Am I analyzing this correctly?

## Steps to reproduce

- Build Prebid.js with prebidServerBidAdapter & sizeMappingV2 modules
- Configure one ad unit as follows:
```
  var adUnits = [
    {
      code: 'test1',
      mediaTypes: {
        banner: {
          sizeConfig: [
          { minViewPort: [0, 0], sizes: [[300, 250], [300, 100]] },
          { minViewPort: [768, 0], sizes: [[728, 90], [300, 250]] }
        ]
        }
      },
      bids: [{
        bidder: 'appnexus',
        params: {
          placementId: 13144370
        }
      }]
    }
  ];
```
- Add an s2s config:
pbjs.setConfig({
    s2sConfig: [{
        accountId: '10',
        bidders: ['appnexus'],
        adapter: 'prebidServer',
        enabled: true,
        endpoint: 'https://prebid.adnxs.com/pbs/v1/openrtb2/auction',
        syncEndpoint: 'https://prebid.adnxs.com/pbs/v1/cookie_sync',
        timeout: 500
    }]
})

## Platform details
Prebid.js 6.2

**Comment by bretg** [comment]
Makes sense. I suppose if the long term goal is Prebid.less, then PBS will eventually need to understand these things. Very well, will add it to the list to define new extensions. It will be some time before they're supported though.

**Comment by bretg** [comment]
This is the related PBS issue tracking the enhancement https://github.com/prebid/prebid-server/issues/2168
