### ISSUE TITLE
bidLimit setting in setConfig ignores adserverTargeting in bidderSettings

### ISSUE THREAD

**Issue by ACannuniRP** [prebid/Prebid.js#8052]
## Type of issue
The keys defined in adserverTargeting for a particular bidder are sent to the ad server even when the bid of a particular bidder should be excluded because of bidLimit.

## Description
The following setting should allow only the key/values of bid with the highest CPM to be sent to the ad server:
```
pbjs.setConfig({
  sendBidsControl: {
    bidLimit: 1
  }
});
```

If we set the following:
```
pbjs.bidderSettings = {
    rubicon: {
         sendStandardTargeting: true,
         adserverTargeting: [
            {
               key: "hb_pb_rubicon",
               val: function(bidResponse) {
                   return bidResponse.pbMg;
               }
            }
         ]
     }
}
```
we should expect that:
* if `rubicon` bid has the highest CPM among the bidders then the key `hb_pb_rubicon` is sent to the ad server with the value corresponding to `bidResponse.pbMg`;
* if `rubicon` bid is not the bid with the highest CPM then the key/value should not be sent to the ad server.

## Steps to reproduce
Add the following settings in the in-page configuration:
```
pbjs.setConfig({
  sendBidsControl: {
    bidLimit: 1
  }
});

pbjs.bidderSettings = {
    rubicon: {
         sendStandardTargeting: true,
         adserverTargeting: [
            {
               key: "hb_pb_rubicon",
               val: function(bidResponse) {
                   return bidResponse.pbMg;
               }
            }
         ]
     }
}
```

### Expected results
* If `rubicon` bid has the highest CPM among the bidders then the key `hb_pb_rubicon` is sent to the ad server with the value corresponding to `bidResponse.pbMg`;
* If `rubicon` bid is not the bid with the highest CPM then the key/value should not be sent to the ad server.

### Actual results
The key/value `hb_pb_rubicon` is always sent to the ad server.

## Platform details
Tested in Prebid.js 5.x. The issue is not version-specific.

**Comment by ChrisHuie** [comment]
@r-schweitzer can you please take a look at this issue?

**Comment by r-schweitzer** [comment]
This does seem to be an issue with bid limit if you want to send custom keys for a specific. In this case since you're looking to adjust the price bucket can you instead just do this? 

` rubicon: {
        sendStandardTargeting: true,
        adserverTargeting: [
            {
                 key: "hb_pb",
                 val: function(bidResponse) {
                         return bidResponse.pbMg;
                 }
            }
        ]
}`

I think with hb_pb_rubicon you're overriding prebid setting that key and its always there. Again this would be an issue if someone wants custom keys for a specific bidder and doesn't want them sent when they do not make the cut from bidLimit.

**Comment by ACannuniRP** [comment]
Hi @r-schweitzer ,
thanks for having a look in this issue. Effectively, it is not the best example I could give but, yes, it is an issue as publishers would like to use custom key names (e.g. `hb_pb_rp`) instead of the default key names (e.g. `hb_pb_rubicon`) for a specific bidder: if `rubicon` is not the bidder with the highest bid response CPM then both keys (`hb_pb_rp` nor `hb_pb_rubicon`) should not be sent to the ad server.

**Comment by dgirardi** [comment]
Related: https://github.com/prebid/Prebid.js/issues/8130. 
Since publishers are potentially relying on the current behavior, it's best to fix this in a major version - @ACannuniRP, is this an annoyance that can wait, or should we try to get in a fix earlier?

**Comment by ACannuniRP** [comment]
Hi @dgirardi , I completely understand. We can wait for it to be included in the next major version.
Thanks!
