### ISSUE TITLE
Feature Request for Google Analytics Adapter to send Price Floors

### ISSUE THREAD

**Issue by rachelrj** [prebid/Prebid.js#8053]
## Type of issue
Question

## Description
Does the Google Analytics Adapter send Price Floors? https://docs.prebid.org/dev-docs/modules/floors.html#analytics-adapter-interface

## Steps to reproduce
I am using the Google Analytics Adapter and can view the events in GA for Requests, Bids, Bid Load Time, Wins, & Timeouts. But, I cannot find how to see Bids by Bid Floor data.

## Other information
(https://github.com/prebid/Prebid.js/blob/master/modules/googleAnalyticsAdapter.js)
@muuki88

Does anyone know? If not, maybe I can add that price floor support for GA.

**Comment by muuki88** [comment]
Hi @rachelrj 

We never used the GA adapter in production as it has several draw backs

- sends tons of tracking requests, which affects mobile clients really badly
- the free GA version will probably sample your data, which makes it basically useless. The main purpose of Prebid analytics is to get a detailed insight
- you can't connect auctions IIRC . Every event stands on its own. A lot of analysis can't be made without such a link


Shameless plug. We are very happy with pubstack. It's probably way cheaper than GA 360. And if you already have GA 360 then you can afford a proper Prebid analytics solution I assume. 😁
