### ISSUE TITLE
Feature Request: New configuration convention to interplay with ESP scripts

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8067]
## Type of issue
Feature Request

## Description
Some public signal collector scripts including https://github.com/prebid/shared-id/blob/main/pubcid.js/src/index.js ( deployed per https://github.com/prebid/shared-id/tree/main/pubcid.js ) seem to make redundant endpoint calls ( as in they are duplicated in the signal collection script and the prebid submodule) or worse, generate a different identifier, than what is used by the user id module and its various submodules to form the results of pbjs.getUserIdsAsEids()
A public signal collector I am defining as a signal collection script that broadcasts its signal to all listening signal receivers in GAM. 

I would like to define a config convention such that publishers can indicate to one or more signal collectors to use the pbjs eid rather than generate it or regenerate it independently. The deployed scripts of public signal collectors, such as Id5, Criteo, SharedId, would then simply check config before looking anywhere else for the ID. I believe the Criteo script already operates this way, as it is sourced from its adapter, rather than deployed independently. 

Finally, I would like to also propose that the deployed sharedid signal collection script has the capability of pulling and writing all the eids a publisher would designate in this config.

**Comment by bretg** [comment]
Pull request at https://github.com/prebid/Prebid.js/pull/8117

**Comment by patmmccann** [comment]
Closing this in favor of the push architecture in 8117
