### ISSUE TITLE
prebid.js adUnit sizes per bidders

### ISSUE THREAD

**Issue by nicoUnify** [prebid/Prebid.js#8077]
When creating an adUnit for a given ad slot, I figure out that each bidders set in `bid` Array inherit from the sizes set in `mediaTypes` property.

```javascript
pbjs.addAdUnits({
    code: 'adslotCode1',
    mediaTypes: {
        banner: {
            sizes: [[300, 250], [300, 600], ... ]
        }
    },
    bids: [{ BIDDER_1 }, { BIDDER_2 }, { BIDDER_3 }, ....]
});
```

I wish to set different sizes per bidder for the same ad slot.

Is the ["twin AdUnit Codes"](https://docs.prebid.org/dev-docs/adunit-reference.html#twin-adunit-codes) method the only way to do this ? (= one adUnit per bidder with the same code and corresponding sizes).
With this method, if an ad slot require 15 bidders, I will potentially push 15 adUnits for 1 ad slot.
Depending on the number of slots in the page, the number of adunits sent will be huge.

```javascript
pbjs.addAdUnits({
    code: 'adslotCode1',
    mediaTypes: {
        banner: {
            sizes: [[300, 250]]
        }
    },
    bids: [{ BIDDER_1 }]
}, {
    code: 'adslotCode1',
    mediaTypes: {
        banner: {
            sizes: [[300, 600]]
        }
    },
    bids: [{ BIDDER_2 }]
}, { 
...
});
```

Or is there another way to setup sizes per bidder ?

**Comment by bretg** [comment]
Please describe the use case @nicoUnify . Why can't the bidders just not bid on sizes they're not interested in? Some bid adapters still support bidder-level overrides, but many no longer do. We generally consider this a good thing.

But assuming there is an edge case here, yes, 'twin' adunits is the only answer at this time.

The last time we had a community member who required a level of complexity like this, the [Advanced Size Mapping module](https://docs.prebid.org/dev-docs/modules/sizeMappingV2.html) was developed.

We would consider community contributions that extend the existing module to add 'sizes' to the bidder-level sizeConfig.

```
      bidder: 'bidderB',
      params: {
        accountId: 14062,
      },
      sizeConfig: [
        { minViewPort: [0, 0], relevantMediaTypes: ['none'], sizes: [SIZEARRAY] },
        { minViewPort: [800, 0], relevantMediaTypes: ['banner'], sizes: [SIZEARRAY] },
        { minViewPort: [1200, 0], relevantMediaTypes: ['none'], sizes: [SIZEARRAY] }
      ]
```

**Comment by bretg** [comment]
Discussed in committee: 
- one use case we're aware of is that a custom size can be used as a signal to deliver a special kind of creative. Is this your use case?
- overall, we recommend that bid adapters that require custom sizes should document how to do that for their adapter.

**Comment by patmmccann** [comment]
closing as stale; if you want to pass special information to a bidder, it generally seems best to do it via a bidder parameter instead of hacking it onto the size array with an indicator size. Even if the bidder doesnt take any parameters, you can now do this for a specific auction in the ortb2 object if they take that https://github.com/prebid/Prebid.js/pull/8338
