### ISSUE TITLE
Sourcemaps for production builds

### ISSUE THREAD

**Issue by sergunich** [prebid/Prebid.js#8079]
## Type of issue
Feature request

## Description
Currently, it's possible to have sourcemaps only for development builds but it would be helpful to have the option to generate sourcemaps for production build too.
https://github.com/prebid/Prebid.js/blob/master/gulpfile.js#L205

## Other information
The end goal of this is to submit generated sourcemaps to the Sentry to have proper stackframes for the errors:
https://docs.sentry.io/platforms/javascript/sourcemaps/

**Comment by dgirardi** [comment]
@sergunich are you asking for the option to generate sourcemaps just when building Prebid directly from source? it would have no effect on for example the bundles generated by the Prebid.org download page or projects that pull Prebid from npm.

**Comment by sergunich** [comment]
> option to generate sourcemaps just when building Prebid directly from source

Yeah, that's what I meant :+1:

**Comment by dgirardi** [comment]
Understood; I'm going to put this on hold until we upgrade Webpack (which should happen soon - https://github.com/prebid/Prebid.js/pull/7935) as that changes a few things about the build.
