### ISSUE TITLE
Feature request: es2020 transpilation

### ISSUE THREAD

**Issue by EskelCz** [prebid/Prebid.js#8081]
Any plans for adding es2020 support for babel?
I'm mainly interested in conditional chaining.
Thanks

**Comment by patmmccann** [comment]
https://babeljs.io/blog/2020/01/11/7.8.0 suggests no changes needed for this?

**Comment by EskelCz** [comment]
It was throwing this error, until I removed the chained conditional.
```
[14:10:46] Error in plugin 'webpack-stream'
Message:
    /Users/eskel/Code/cpex/cpex-analytics/cpexAnalyticsAdapter.js
Module parse failed: Unexpected token (88:20)
You may need an appropriate loader to handle this file type.
```
@patmmccann Just tried it again and it compiled fine. Weird, closing the issue. Thank you
