### ISSUE TITLE
Getting the advertiser domain/landing page for the winning auction

### ISSUE THREAD

**Issue by devgits** [prebid/Prebid.js#8090]
## Type of issue
Feature Request / Question

## Description
When running prebid.js auction is it possible to get the landing page/advertiser domain for the auction winner. For example if we assume the below call flow -

page load >> prebid.js called >> bid request generated >> auction happens >> bid response received >> auction completes >> winning bid chosen >> (now the SSP or advertiser who won the bid, can we also get to receive his advertiser/landing page for which he won the auction)

It will be of more clarity as in when the auction happens which all SSP is bidding for which advertiser/landing page and if they wins which advertiser/landing page is going to render and if this data can be received before hand the creative originally renders?

**Comment by bretg** [comment]
@devgits - it's already possible to get the domain from a bidWon handler -- it's stored in bidresponse.meta.advertiserDomains[0]

Also note that you can send hb_adomain through to the ad server. See the ADOMAIN docs in https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html

**Comment by patmmccann** [comment]
@devgits does the above solve your concern?

**Comment by bretg** [comment]
Considering this closed. Please re-open as needed.
