### ISSUE TITLE
Delete UserIdTargeting Module

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8091]
## Type of issue

https://github.com/prebid/Prebid.js/blob/0fbbcb4dc929ac26ec1167f2a1331d12f0affe3b/modules/userIdTargeting.js seems to have no value since google moved these signals out of OB and Authorized buyers. I propose we delete it. 

@lyubomirshishkov what are your thoughts? 
@pm-harshad-mane you originally committed in #4140

**Comment by lyubomirshishkov** [comment]
@patmmccann I can't think of a good reason to keep it. I asked around for other use cases, but there weren't any, so deleteing it is fine in my opinion.

**Comment by pm-harshad-mane** [comment]
We should delete the module for the mentioned reasons.
