### ISSUE TITLE
Bulk Creation of DFP line items via API

### ISSUE THREAD

**Issue by premesh** [prebid/Prebid.js#81]
Im pretty sure when i first started looking at prebid i came across a link to a repo where someone created a script to use the DFP APIs to create all the line items for you. Any idea where this is?

**Comment by thehumanpuck** [comment]
Was it this issue thread - https://github.com/prebid/Prebid.js/issues/46

https://github.com/spanishdict/example-dfp-line-item-generator

**Comment by premesh** [comment]
YES thanks!!

**Comment by JuanCaicedo** [comment]
@premesh Don't know if you ended up using it, but I'm the main author of that repo, feel free to reach out with any questions you have!

**Comment by kmjennison** [comment]
I also created an automated DFP Prebid setup tool because the one listed above is no longer maintained:
https://github.com/kmjennison/dfp-prebid-setup

Hope this helps!

**Comment by gchicoye** [comment]
Hello,
I've created a tool in PHP available here.
https://github.com/Insideall/dfp-prebid-lineitems

I hope it will help you!

**Comment by xavierleune** [comment]
Hi,

Did anyone created a tool for generating line items in DFP/AdManager for video ?

Thanks,

**Comment by AmerSharif** [comment]
Have you found anything @xavierleune ? I need the same

**Comment by xavierleune** [comment]
Hi @AmerSharif I worked around @gchicoye tool, to support video line items. I'll consider to create a pull request on insideall/dfp-prebid-lineitems to support video li in the coming weeks, I need to do some clean up before to push that update

**Comment by romanych** [comment]
@xavierleune, have you succeeded with this?

**Comment by xavierleune** [comment]
Hi @romanych 
Sure, I did it for outstream. This was pretty easy after all. I never shared it but I will. I'll try to do it next week, please ping me again if you don't hear back from me :)
