### ISSUE TITLE
Do ad sizes have to match in Mediatypes and googletag.defineSlot?

### ISSUE THREAD

**Issue by kumasauce** [prebid/Prebid.js#8116]
## Type of issue
Question

## Description
This seems like it would be an easy question but I'm not having a lot of luck testing. Do the ad sizes in the Prebid mediaTypes.sizes have to exactly match the one's declared in googletag.defineSlot()?

For example: can we do something like: 

Prebid:
code: 'div1',   mediaTypes: { banner: {sizes: [[300, 250]}},  bids: [....].}

with the corresponding:

GAM: googletag.defineSlot('/4444444/ad', [[300, 250], [300, 600], [160, 600], [336, 280]], 'div1')....

Or will the mismatch in the number of sizes cause unfilled impressions or a bad auction?

Thanks so much for your help!

**Comment by bretg** [comment]
Put a note in the adunit reference. 

Is this answer sufficent @kumasauce ?

**Comment by kumasauce** [comment]
Thanks that helps a lot! I just wanted to make sure I wasn't losing impressions by keeping mediaTypes.banner.sizes as a subset of the GPT slot sizes. I really appreciate it!
