### ISSUE TITLE
Bower.json

### ISSUE THREAD

**Issue by buley** [prebid/Prebid.js#812]
## Type of issue
Feature request

## Description
A pre-built /build directory and bower.json pointing to it may make it easier for people to get up and running with this library. One idea would be for this to integrate with the Travis build checks #24

**Comment by buley** [comment]
I guess this wouldn't be possible because of the adaptors that have to be built. Seems like sort of a modernizr situation. I don't love having to build Prebid.js every time I want to build a container -- it would be a lot easier to import built versions and have it read the adaptors.json at compile time -- but I understand the choices made.

**Comment by mkendall07** [comment]
@buley 
Yes, that is the problem. We are considering breaking up the project, if interested follow along here: 
https://github.com/prebid/Prebid.js/issues/796
