### ISSUE TITLE
App support?

### ISSUE THREAD

**Issue by ADgitated** [prebid/Prebid.js#813]
Aware of s2s capabilities by openx and appnexus in header bidding. Assuming they are abiding by some core of prebid.js but appnexus integration guide is extremely brief. Is there a s2s implementation available for prebid.js at current? 

Do I need to build something proprietary?

**Comment by mkendall07** [comment]
@ADgitated 
Prebid.js wasn't built to run s2s. We don't have any guide on that. Please reach to each company for information.
