### ISSUE TITLE
Rationalize KVP controls

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#8130]
## Type of issue
breaking change

## Description
Controlling PBJS ad server KVPs (aka "targeting") is quite complex. There are 12 different options publishers can define to refine what's sent. There are often edge-cases discovered where the interaction of several of these options don't work properly. This isn't surprising because we've never sat down to rationalize the whole mess of control options and how they're supposed to work together. Instead, people have just organically added yet another control randomly into the code to meet their specific use case.

The range of controls is documented at https://docs.prebid.org/features/adServerKvps.html

I've drafted a [Prebid.js Ad Server KVP Control doc](https://docs.google.com/document/d/1byRsrPwOhgpfpTyLUGD0wYCQHH-epc6TxYxASEcXDlA/edit#heading=h.1erunzjjwcpv) with a first cut at a coherent description of how the 12 controls work together. I'm certain that the current code doesn't work this way, and suspect that there will be some interesting debates about semantics. 

I'd like to discuss as a community:

1. Do people agree that the fringes of KVP control is a somewhat mysterious and idiosyncratic ritual?
2. Are we willing to take a breaking change in this part of the system conform to some agreed-upon algorithm?

**Comment by bretg** [comment]
Discussed in committee last week. We agreed that spending time in this area would be worthwhile, but it would more of a project for PBJS 8.0.

**Comment by dgirardi** [comment]
Here's some related bug reports:

https://github.com/prebid/Prebid.js/issues/6734
https://github.com/prebid/Prebid.js/issues/8052

Their fix requires either modifying the effect of some of the current controls (which is a breaking change), or introducing more controls. The first route is obviously preferable, but are we OK to push it forward to 8.0?

**Comment by patmmccann** [comment]
Work is not currently planned; people interested in this work are invited to express support and we may plan the work.
