### ISSUE TITLE
prebid.js browser caching question

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#814]
Is it necessary to give a uniquely different file name to my customized prebid.js file, to prevent a different version of prebid.js from a different site being loaded from the browser cache?

(In case the visitor has previously visited another site using Prebid and cached a different version of prebid.js with different adapters.)

**Comment by mrpbennett** [comment]
I would always have the standard prebid.js file as it is and the file where I host my wrapped named differently. I have my wrapper / bidders in a file called pbfile.js not sure if this is what you meant? 

but yes id call the files differently, you could always rename the prebid.js file to prebid_(version number).js

**Comment by mkendall07** [comment]
@headerbidding 
The browser HTTP cache should be based on the full URL, not just the filename. So as long as you are hosting for your own server you should be fine.

**Comment by headerbidding** [comment]
Cool
