### ISSUE TITLE
Feature Request: add option to bidderSettings.storageAllowed

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8141]
## Type of issue
We'd like to see an option for a bidder to only have access to local storage and not cookies instead of just true and false. 
This shouldn't affect the 7.0 plan to default to no access.

**Comment by dgirardi** [comment]
This could be specified as:
```javascript
pbjs.bidderSettings = {
     standard: {
          storageAllowed: false
     },
     bidderA: {
          storageAllowed: ['localStorage']
     },
     bidderB: {
          storageAllowed: ['localStorage', 'cookies']  // equivalent to `true` until some other storage option comes up
     }
}
```

**Comment by jdcauley** [comment]
IndexedDB would be another storage option that could/should probably be supported on the outset.

**Comment by jdcauley** [comment]
@patmmccann I think this should more global across module types. (perhaps there is already this concept elsewhere)

Even if it exists elsewhere would be nice to be able to set these rules in one place.

**Comment by patmmccann** [comment]
@jdcauley feel free to open another issue for generalizing this control; I'd prefer to keep this issue of more limited scope

**Comment by jdcauley** [comment]
why would you elect to implement something twice rather than implementing one thing that does the whole job
