### ISSUE TITLE
Feature Request: Prebid video module reads from userid module's id for ppid configuration

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#8151]
having spoke to @patmmccann on slack, it seems that passing the PPID with the method show in docs doesnt work with the prebid video moudule.  Patrick said open an issue , so can look into it

**Comment by patmmccann** [comment]
@mike-chowla Tagging this for the video meeting agenda

**Comment by bretg** [comment]
Patrick and I believe this is a player issue.

Patrick found that GAM PPID can be set in the IMA SDK -- https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.ImaSdkSettings . But Prebid can't do this -- the player does. The only thing the Prebid video module does is create the GAM URL.

Patrick's offered to update the user ID module doc to clarify that GAM-PPID in video scenario is a player-specific thing.

**Comment by spormeon** [comment]
Ok, so say you got this, how do you get it in there?  Or am i completely mising something here?
var imaOptions = '{ "ppid": HOWDOIGETTHEPPIDHERE, "enableOmidBeta": true, "preventLateAdStart": false, "disableFlashAds": true, "prerollTimeout": 18000, "autoPlayAdBreaks": true, "vastLoadTimeout": 18000

**Comment by bretg** [comment]
the page would just call [pbjs.getUserIdsAsEids()](https://docs.prebid.org/dev-docs/publisher-api-reference/getUserIdsAsEids.html), parse the results, pick whatever ID it wants to use as the GAM PPID, and pass it to the player in the player-specific way

**Comment by bretg** [comment]
@patmmccann - David points out that ppid could be placed on the GAM URL. But maybe this already works. @spormeon , could you just try it?

```
            var videoUrl = pbjs.adServers.dfp.buildVideoUrl({
                adUnit: videoAdUnit,
                params: {
                    iu: '/19968336/prebid_cache_video_adunit',
                    ppid: ADDYOURPPIDHERE
                }
            });
```

Based on a quick look in the code, seems like everything in params is tacked onto the GAM URL

**Comment by spormeon** [comment]
Ye that works, thats what I was alluding to above and have it built into the video module to "auto" pick it up, with ppid: true or something in the params being as its being "tied" to SharedID
![https___ads_vmapurl_com_vidads_vmap_env_vp_gdfp_req_1_output_vast_unviewed_position_start_1_correlator_1647548415522_257C1647548415526_257C1647548415528_257C1647548415530_257C1647548415531_257C1647548415533_257C1647548415534_url_https_25253](https://user-images.githubusercontent.com/8503167/158889023-fc2eeea9-c5c6-47e2-a05d-06d9705ce691.png)

![prebidVideo4_29_0_js_—_Prebid_Publishers__Workspace_](https://user-images.githubusercontent.com/8503167/158889116-509abef6-b754-49f3-82a5-f9953e76aff4.png)

**Comment by patmmccann** [comment]
I added the feature tag so that we can prioritize having the video module pick this up from the user id module

**Comment by patmmccann** [comment]
@karimMourra i dont follow why this needs to go to the id committee, it is just a feature to sync ima to what is being sent to gpt; what feedback or question do you expect from them?

**Comment by karimMourra** [comment]
@patmmccann we discussed this a month ago in the Video Committee sync and the consensus was that we believe the ID committee should have a say on the interface and implementation for automatically obtaining a ppid for the dfp module. 
Our assumption was that the solution should work for all Ids and any client module, not just DFP.

**Comment by spormeon** [comment]
Uhh, consent has already been gain at "video module" point by the cmp, its just "passing it along"? why would anyone uisng "header bidding" without a adserver need to pass a PPID any way, its tied to DFP/ GAM ?

**Comment by patmmccann** [comment]
I think this is ready for dev; buildVideoUrl in the dfp video module should be modified to automatically check if a ppid is configured in the userid sync and grab it just like https://github.com/prebid/Prebid.js/blob/d1a0f09cc2a605c19982dc7a8325c437c8dc0491/modules/userId/index.js#L664 does

**Comment by spormeon** [comment]
did this #8365 go out in p6.23.0 a few hours ago?  If so, I'm no sure this is working , as just tried it with setting ppid source in userSync but nothing is getting built in the video urls?
![prebidVideo4_29_0_js_—_Prebid_Publishers__Workspace_](https://user-images.githubusercontent.com/8503167/168168717-a5b33100-cec6-4461-a46a-f16ec0ae7dd0.png)

or does ppid:''  aslo have to be set on the params of the videomodule?


![prebidVideo4_29_0_js_—_Prebid_Publishers__Workspace_](https://user-images.githubusercontent.com/8503167/168169128-207d520b-769f-4531-87a5-5fdb3a729b6e.png)

**Comment by patmmccann** [comment]
looks like it is in the 6.25 draft

https://github.com/prebid/Prebid.js/releases

**Comment by patmmccann** [comment]
i'll release a 6.24.1 and can you test it then?

**Comment by spormeon** [comment]
Ok, I see 6.25.0, does that one go to: https://docs.prebid.org/download.html   as I always build off of that

**Comment by patmmccann** [comment]
It is in 6.24.1, along with a bug fix for webpack

**Comment by spormeon** [comment]
Got it, seems to work fine, cheers
