### ISSUE TITLE
OptimeraRTD Module: Restructure available data for page ingestion

### ISSUE THREAD

**Issue by mcallari** [prebid/Prebid.js#8152]
## Type of issue
Feature request

## Description
Clients have been asking to make score data and insights data available to a global window variable. This is an updated to the original request to just expose insights data. 

## Other information
https://github.com/prebid/Prebid.js/issues/7849

**Comment by patmmccann** [comment]
Can you clarify what is "score data and insights data"

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/pull/7850/files appears to solve?

**Comment by patmmccann** [comment]
@mcallari could you please make this request to your Optimera account representative?

**Comment by mcallari** [comment]
> https://github.com/prebid/Prebid.js/pull/7850/files appears to solve?

@patmmccann Yes, https://github.com/prebid/Prebid.js/pull/7850/files solves this issue. To clarify, score data refers to the ad request-specific data and key values. Insights data refers to other data collected about the the page that publishers can use to act on or ingest for BI purposes.

**Comment by patmmccann** [comment]
@mcallari it appears you work for optimera. We're very confused. Are you asking the prebid core team to improve your product for you? You're responsible for maintaining your own adapter.
