### ISSUE TITLE
Value CPM Question

### ISSUE THREAD

**Issue by tedrand** [prebid/Prebid.js#819]
## Type of issue

Question

## Description

A publisher that I am doing support for wants to set  a 'Value CPM' on their line items in DFP. I have been having issues doing this programmatically, and I want make sure that this would actually affect their revenue when using Prebid. This is the explanation of Value CPM in DFP:
**Set the price at which non-guaranteed inventory competes. This will help DFP rank your non-guaranteed inventory by CPM.**  

To me, this step seems pointless because with Prebid a separate line item would be competing at the Value CPM anyway.

I am not asking how to set the vCPM programmatically, rather I am just wondering if it worth investing more time in, based on your knowledge of Prebid. Thanks!

**Comment by mjacobsonny** [comment]
@tedrand --

Unless you want to set the Prebid line item's "value CPM" to a value other than it's "CPM", there should not be any reason to do this.  From https://support.google.com/dfp_premium/answer/177279?hl=en:
 > If there is no value CPM, DFP uses the line item CPM rate instead.

**Comment by tedrand** [comment]
Thanks so much man, needed that confirmation.
