### ISSUE TITLE
[Feature Request] New Module for `device` from User-Agent

### ISSUE THREAD

**Issue by maphe** [prebid/Prebid.js#8217]
## Type of issue
Feature Request

## Description
Is there any chance for a new Prebid Module that would generate a populated `device` open RTB object (as much as possible)? As of now we can get the User Agent string from the adapter but we cannot use a third party library that would parse the UA and make a comprehensive open RTB `device` object (things like `devicetype`, `make`, `model`, `h` and `w`, etc). Also doing some sort of custom parsing in the adapter would make maintenance a bit painful.

I imagine something similar to the User module that centralizes the generation of user ids.

I know it is doable server side from the UA string but having it client side could make the bids respond faster.

**Comment by patmmccann** [comment]
Part of your request (h&w) is done: https://github.com/prebid/Prebid.js/pull/6452/commits/11492e99860fa5351a46702ed52cd8bab9dbb1de

**Comment by patmmccann** [comment]
It is a huge file https://github.com/ua-parser/uap-core/blob/master/regexes.yaml ; mobile / not mobile seems easy to achieve but make and model seems unlikely, especially as the world moves to making these things less detailed, not more.

**Comment by maphe** [comment]
Yeah we had some back and forth internally to figure out where we wanna do it, obviously doing it within the adapter is not realistic so we might end up with some server side processing but it's a trade off too as we're delaying the bid. Having some stuff provided by the prebid core would be nice, but I understand some are trickier to obtain.

For context, buyers seem to be pretty inconsistent on what they do themselves with the User-Agent, and the ones that don't parse it on their own seem to expect a more complete `device` object. I know device type, make and model have be mentioned lately. I can probably come back with a more detailed list of valuable attributes if you think there's a chance they get managed by the prebid core.

**Comment by patmmccann** [comment]
I can't see this being in core, but a module to enrich the first party data in the ortb2 object is already a thing; this could be part of that module if it is pretty terse, or its own module if the parsing is expensive with regards to the number of regex's

**Comment by maphe** [comment]
Ok great, I'll keep an eye out for it. Thank you

**Comment by patmmccann** [comment]
Timeout RTD provider has this functionality, but appears wrong

function getDeviceType() {
  const userAgent = window.navigator.userAgent.toLowerCase();
  if ((/ipad|android 3.0|xoom|sch-i800|playbook|tablet|kindle/i.test(userAgent))) {
    return 5; // tablet
  }
  if ((/iphone|ipod|android|blackberry|opera|mini|windows\sce|palm|smartphone|iemobile/i.test(userAgent))) {
    return 4; // mobile
  }
  return 2; // personal computer
}

I propose:

'Windows NT' - Desktop
Macintosh - Desktop
tablet|ipad - Tablet
Mobi|Phone & !tablet- Phone

with no fallback to type 2, just leave it blank for devicetype.

**Comment by patmmccann** [comment]
Closing as partially solved in #11414 ; and that @dgirardi 's feedback is quite accurate, any client side parsing will inevitably become stale
