### ISSUE TITLE
Rubicon adapter Question

### ISSUE THREAD

**Issue by littlecuteflower** [prebid/Prebid.js#822]
## Type of issue
rubicontag.renderCreative is undefined in Prebid v15

## Description
We are in the process of upgrading to Prebid v15 and found out that Rubicon adapter is no longer supporting rubicontag variable. We use rubicontag.renderCreative function in creative script to render ads from Rubicon. We also noticed that original Rubicon adapter is replaced with RubiconLite in v15. Is there any way we can just enable original Rubicon adapter instead of RubiconLite? Thanks.

**Comment by mkendall07** [comment]
@bretg

**Comment by bretg** [comment]
We recommend migrating to the 'lite' version of the adapter -- without a library load, a number of sites have gotten significant performance boosts. However, if you need a temporary translation to make renderCreative work until the line items can be migrated to the Prebid approach, we may be able to come up with something. Will contact our Solutions Engineering team.

**Comment by bretg** [comment]
How many line item/creatives are you working with? The preference is to spend the time helping convert the creatives to Prebid render. You can contact your Rubicon Project Solutions Engineer, or I can put them in touch with you.

**Comment by littlecuteflower** [comment]
Thanks for the reply. We have about 416 line items and 50 creative tags. We can update the creatives for all line items but if there's any issue with Prebid v15, we need to roll back to previous version 13. Will prebid render work with the original Rubicon adapter? Thanks.

**Comment by bretg** [comment]
> Will prebid render work with the original Rubicon adapter

Yes - in fact am curious to know how you're passing the rpfl_* variables, which isn't standard with Prebid installations.

**Comment by littlecuteflower** [comment]
Thanks, We'll try prebid creative and let you know how it goes.
For rpfl_*, we converted ad sizes to rubicon sizes before sending to DFP as key-value targeting so that Rubicon creative can render properly.

**Comment by bretg** [comment]
I see - you must have converted from a fastlane 'direct' integration so re-used the ad server line items and bridged the gap.

Let us know if we can help or this is working out for you.

**Comment by littlecuteflower** [comment]
Yes, we have a lot of line items so didn't want to change key-value targeting for all of them. 

We've replaced Rubicon creative with Prebid creative and it's working well. Thanks.
