### ISSUE TITLE
[QUESTION] How to execute /cookie_sync firstly before request for bids?

### ISSUE THREAD

**Issue by wiedaw** [prebid/Prebid.js#8232]
## Type of issue
Question

## Description
Is it possible and if yes, how can I execute `cookie_sync` endpoint before request for bids?
Now in network console, I see that first is executed request for bids and then after response is sent request to `cookie_sync`.
I work with bidder adapter.

**Comment by bretg** [comment]
Doing a full cookie-sync handshake for all bidders before the auction would destroy it. In header bidding, timing is everything -- the page gives Prebid about 1 second (depending on pub settings) to get bids before it calls the ad server. Say a pubs puts 10 bidders on their page -- initiating 10 cookie-syncs before the auction would certainly cause all bidders to miss the auction entirely.

A single sync handshake can easily take 200ms in a busy page environment -- browser javascript processing is single-threaded and there's a lot more than Prebid happening on most real pages, waiting for 10 handshakes to be sent and return means more than half of the auction window would be gone and many bidders will not have enough time to respond, again in a naturally busy single-threaded page environment, 500ms is not a lot of time.

Not only that, but with all the extra sync HTTP requests happening during the peak of page load, users and publishers may notice a slow down of content and other important requests. So early on in Prebid, it was decided to make sure that syncing always took place late in the page lifecycle -- much less impact on user experience.
