### ISSUE TITLE
How to install prebid and build

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#824]
I need to be able to track timeouts by bidder.
I used to use GA tacking to do that, but it is no longer available in the direct download, unless I compile my own prebid.js
I have never used node.js and gulp.
Questions:
1) Are there step-by step instructions on how to set up and use node.js and gulp?
2) Is there another way to use GA (or other anaylytics) without having to learn node.js and gulp?

**Comment by tedrand** [comment]
`brew install node && npm install gulp` on Mac

then just use the build commands on Github.

**Comment by mkendall07** [comment]
@headerbidding did the above work for you?

**Comment by headerbidding** [comment]
I don't know what "brew install node && npm install gulp" is  and I do not have a Mac.  I use Windows 7.

**Comment by mkendall07** [comment]
1. download and run the node installer for windows: https://nodejs.org/en/download/
2. Download and run the git installer: https://git-scm.com/download/win
3. Open a terminal window and run `npm install -g gulp`
4. Checkout the project using git. Open a terminal and run `git clone https://github.com/prebid/Prebid.js.git`
5. Move into the directory of `${local_path}/Prebid.js` created by git clone and run `gulp build`

**Comment by headerbidding** [comment]
1-2-3-4 worked perfectly. When I did 5 npm install I got error messages:


Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Hubert>npm install -g gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\Hubert\AppData\Roaming\npm\gulp -> C:\Users\Hubert\AppData\Roaming\npm\
node_modules\gulp\bin\gulp.js
gulp@3.9.1 C:\Users\Hubert\AppData\Roaming\npm\node_modules\gulp
├── interpret@1.0.1
├── pretty-hrtime@1.0.3
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.2.0 (os-homedir@1.0.2)
├── v8flags@2.0.11 (user-home@1.1.1)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2
.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── orchestrator@0.3.8 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.
1.5)
├── vinyl-fs@0.3.14 (strip-bom@1.0.0, defaults@1.0.3, graceful-fs@3.0.11, vinyl@
0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
├── liftoff@2.3.0 (lodash.isstring@4.0.1, lodash.isplainobject@4.0.6, lodash.map
values@4.6.0, rechoir@0.6.2, extend@3.0.0, flagged-respawn@0.3.2, resolve@1.1.7,
 fined@1.0.2, findup-sync@0.4.3)
└── gulp-util@3.0.7 (array-differ@1.0.0, lodash._reinterpolate@3.0.0, lodash._re
evaluate@3.0.0, array-uniq@1.0.3, beeper@1.1.1, object-assign@3.0.0, lodash._ree
scape@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3,
 gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.2, multipipe@0.1.2, dateform
at@1.0.12)

C:\Users\Hubert>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path C:\Users\Hubert\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\Users\Hubert\p
ackage.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directo
ry.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Hubert\npm-debug.log

**Comment by mkendall07** [comment]
It looks like you have an older version of node installed. 
>npm ERR! node v4.5.0
You should have a 6.x.x version. 
See here to update: 
http://stackoverflow.com/questions/18412129/how-do-i-update-node-and-npm-on-windows

**Comment by headerbidding** [comment]
Actually, Git CMD generated errors first:

C:\Users\Hubert>git clone https://github.com/prebid/Prebid.js.git
Cloning into 'Prebid.js'...
remote: Counting objects: 4173, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 4173 (delta 19), reused 0 (delta 0), pack-reused 4127R
Receiving objects: 100% (4173/4173), 1.67 MiB | 0 bytes/s, done.

Resolving deltas: 100% (2710/2710), done.

C:\Users\Hubert>cd ${local_path}/Prebid.js
The system cannot find the path specified.

C:\Users\Hubert>${local_path}/Prebid.js
'${local_path}' is not recognized as an internal or external command,
operable program or batch file.

ert>

**Comment by headerbidding** [comment]
The instructions were too complex. I went ahead and just installed from your link https://nodejs.org/en/download/ and I now have version 6

**Comment by headerbidding** [comment]
STEP 3: 

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\windows\system32>npm install -g gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\Hubert\AppData\Roaming\npm\gulp -> C:\Users\Hubert\AppData\Roaming\npm\
node_modules\gulp\bin\gulp.js
C:\Users\Hubert\AppData\Roaming\npm
`-- gulp@3.9.1


C:\windows\system32>

**Comment by headerbidding** [comment]
STEP 4:
C:\Users\Hubert>git clone https://github.com/prebid/Prebid.js.git
Cloning into 'Prebid.js'...
remote: Counting objects: 4173, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 4173 (delta 19), reused 0 (delta 0), pack-reused 4127 eceiving obj
Receiving objects: 100% (4173/4173), 1.67 MiB | 1.14 MiB/s, done.

Resolving deltas: 100% (2710/2710), done.

C:\Users\Hubert>

**Comment by headerbidding** [comment]
Step 5: 
| |   | `-- graceful-fs@3.0.11
| |   +-- match-stream@0.0.2
| |   | `-- readable-stream@1.0.34
| |   |   `-- isarray@0.0.1
| |   +-- pullstream@0.4.1
| |   | +-- over@0.0.5
| |   | +-- readable-stream@1.0.34
| |   | | `-- isarray@0.0.1
| |   | `-- slice-stream@1.0.0
| |   |   `-- readable-stream@1.0.34
| |   |     `-- isarray@0.0.1
| |   +-- readable-stream@1.0.34
| |   | `-- isarray@0.0.1
| |   `-- setimmediate@1.0.5
| `-- q@1.4.1
+-- karma-chai@0.1.0
+-- karma-chrome-launcher@0.2.3
| `-- fs-access@1.0.1
|   `-- null-check@1.0.0
+-- karma-coverage@0.2.7
| +-- ibrik@2.0.0
| | +-- coffee-script@1.8.0
| | | `-- mkdirp@0.3.5
| | +-- esprima@1.2.5
| | +-- estraverse@1.8.0
| | +-- fileset@0.1.8
| | | +-- glob@3.2.11
| | | | `-- minimatch@0.3.0
| | | `-- minimatch@0.4.0
| | +-- lodash@2.4.2
| | `-- which@1.0.9
| `-- minimatch@0.3.0
|   +-- lru-cache@2.7.3
|   `-- sigmund@1.0.1
+-- karma-es5-shim@2.1.0
+-- karma-expect@1.1.3
| `-- expect.js@0.3.1
+-- karma-firefox-launcher@0.1.7
+-- karma-html-reporter@0.2.7
| +-- lodash@2.2.1
| `-- mu2@0.5.21
+-- karma-ie-launcher@0.1.5
+-- karma-junit-reporter@0.3.8
| `-- xmlbuilder@3.1.0
|   `-- lodash@3.10.1
+-- karma-mocha@0.2.2
+-- karma-opera-launcher@0.1.0
+-- karma-phantomjs-launcher@0.2.3
| `-- lodash@3.10.1
+-- karma-requirejs@0.2.6
+-- karma-safari-launcher@0.1.1
+-- karma-sauce-launcher@0.2.14
| +-- q@0.9.7
| +-- sauce-connect-launcher@0.11.1
| | +-- adm-zip@0.4.7
| | +-- async@0.9.0
| | +-- lodash@3.5.0
| | `-- rimraf@2.2.6
| +-- saucelabs@0.1.1
| `-- wd@0.3.12
|   +-- async@1.0.0
|   +-- lodash@3.9.3
|   +-- request@2.55.0
|   | +-- aws-sign2@0.5.0
|   | +-- bl@0.9.5
|   | | `-- readable-stream@1.0.34
|   | |   `-- isarray@0.0.1
|   | +-- caseless@0.9.0
|   | +-- combined-stream@0.0.7
|   | | `-- delayed-stream@0.0.5
|   | +-- form-data@0.2.0
|   | | `-- async@0.9.2
|   | +-- har-validator@1.8.0
|   | +-- hawk@2.3.1
|   | +-- http-signature@0.10.1
|   | | +-- asn1@0.1.11
|   | | `-- assert-plus@0.1.5
|   | +-- mime-types@2.0.14
|   | | `-- mime-db@1.12.0
|   | +-- oauth-sign@0.6.0
|   | `-- qs@2.4.2
|   +-- underscore.string@3.0.3
|   `-- vargs@0.1.0
+-- karma-script-launcher@0.1.0
+-- karma-sinon-ie@2.0.0
+-- karma-webpack@1.8.0
| +-- async@0.9.2
| +-- lodash@3.10.1
| +-- source-map@0.1.43
| | `-- amdefine@1.0.1
| `-- webpack-dev-middleware@1.8.4
|   `-- range-parser@1.0.3
+-- localtunnel@1.8.2
| +-- debug@2.2.0
| | `-- ms@0.7.1
| +-- openurl@1.1.0
| +-- request@2.78.0
| | +-- form-data@2.1.2
| | `-- qs@6.3.0
| `-- yargs@3.29.0
|   +-- camelcase@1.2.1
|   +-- cliui@3.2.0
|   | +-- string-width@1.0.2
|   | | +-- code-point-at@1.1.0
|   | | `-- is-fullwidth-code-point@1.0.0
|   | `-- wrap-ansi@2.0.0
|   +-- decamelize@1.2.0
|   +-- os-locale@1.4.0
|   | `-- lcid@1.0.0
|   |   `-- invert-kv@1.0.0
|   +-- window-size@0.1.4
|   `-- y18n@3.2.1
+-- mkpath@1.0.0
+-- mocha@1.21.5
| +-- commander@2.3.0
| +-- debug@2.0.0
| | `-- ms@0.6.2
| +-- diff@1.0.8
| +-- escape-string-regexp@1.0.2
| +-- glob@3.2.3
| | +-- graceful-fs@2.0.3
| | `-- minimatch@0.2.14
| +-- growl@1.8.1
| +-- jade@0.26.3
| | +-- commander@0.6.1
| | `-- mkdirp@0.3.0
| `-- mkdirp@0.5.0
+-- mock-fs@3.12.1
| +-- rewire@2.5.2
| `-- semver@5.3.0
+-- nightwatch@0.9.9
| +-- chai-nightwatch@0.1.1
| | `-- assertion-error@1.0.0
| +-- ejs@0.8.8
| +-- lodash.clone@3.0.3
| | +-- lodash._baseclone@3.3.0
| | | +-- lodash._arraycopy@3.0.0
| | | +-- lodash._arrayeach@3.0.0
| | | +-- lodash._baseassign@3.2.0
| | | `-- lodash._basefor@3.0.3
| | `-- lodash._bindcallback@3.0.1
| +-- lodash.defaultsdeep@4.6.0
| +-- minimatch@0.2.14
| +-- mocha-nightwatch@2.2.9
| | +-- commander@2.3.0
| | +-- debug@2.2.0
| | | `-- ms@0.7.1
| | +-- escape-string-regexp@1.0.2
| | +-- glob@3.2.3
| | | +-- graceful-fs@2.0.3
| | | `-- minimatch@0.2.14
| | +-- growl@1.8.1
| | +-- lodash.create@3.1.1
| | | `-- lodash._basecreate@3.0.3
| | +-- mkdirp@0.5.0
| | `-- supports-color@1.2.0
| `-- proxy-agent@2.0.0
|   +-- agent-base@2.0.1
|   | `-- semver@5.0.3
|   +-- http-proxy-agent@1.0.0
|   +-- lru-cache@2.6.5
|   +-- pac-proxy-agent@1.0.0
|   | +-- get-uri@1.1.0
|   | | +-- data-uri-to-buffer@0.0.4
|   | | +-- file-uri-to-path@0.0.2
|   | | `-- ftp@0.3.10
|   | |   +-- readable-stream@1.1.14
|   | |   | `-- isarray@0.0.1
|   | |   `-- xregexp@2.0.0
|   | +-- pac-resolver@1.2.6
|   | | +-- co@3.0.6
|   | | +-- degenerator@1.0.4
|   | | | +-- ast-types@0.9.2
|   | | | `-- esprima@3.1.2
|   | | +-- netmask@1.0.6
|   | | `-- thunkify@2.1.2
|   | `-- stream-to-buffer@0.1.0
|   |   `-- stream-to@0.2.2
|   `-- socks-proxy-agent@2.0.0
|     `-- socks@1.1.9
|       +-- ip@1.1.4
|       `-- smart-buffer@1.0.11
+-- open@0.0.5
+-- phantomjs@1.9.20
| +-- extract-zip@1.5.0
| | +-- concat-stream@1.5.0
| | +-- debug@0.7.4
| | +-- mkdirp@0.5.0
| | `-- yauzl@2.4.1
| |   `-- fd-slicer@1.0.1
| |     `-- pend@1.2.0
| +-- fs-extra@0.26.7
| | +-- jsonfile@2.4.0
| | `-- klaw@1.3.1
| +-- hasha@2.2.0
| +-- kew@0.7.0
| +-- progress@1.1.8
| +-- request@2.67.0
| | +-- bl@1.0.3
| | +-- form-data@1.0.1
| | | `-- async@2.1.4
| | +-- qs@5.2.1
| | `-- tough-cookie@2.2.2
| `-- request-progress@2.0.1
|   `-- throttleit@1.0.0
+-- proxyquire@1.7.10
| +-- fill-keys@1.0.2
| | +-- is-object@1.0.1
| | `-- merge-descriptors@1.0.1
| `-- module-not-found-error@1.0.1
+-- querystringify@0.0.3
+-- requirejs@2.3.2
+-- sinon@1.17.6
| +-- formatio@1.1.1
| +-- lolex@1.3.2
| +-- samsam@1.1.2
| `-- util@0.10.3
|   `-- inherits@2.0.1
+-- string-replace-webpack-plugin@0.0.3
| +-- async@0.2.10
| +-- css-loader@0.9.1
| | +-- csso@1.3.12
| | `-- source-map@0.1.43
| +-- file-loader@0.8.5
| `-- style-loader@0.8.3
+-- uglify-js@2.7.4
| +-- uglify-to-browserify@1.0.2
| `-- yargs@3.10.0
|   +-- camelcase@1.2.1
|   +-- cliui@2.1.0
|   | +-- center-align@0.1.3
|   | | +-- align-text@0.1.4
|   | | | +-- longest@1.0.1
|   | | | `-- repeat-string@1.6.1
|   | | `-- lazy-cache@1.0.4
|   | `-- right-align@0.1.3
|   `-- window-size@0.1.0
+-- url-parse@1.1.7
| `-- requires-port@1.0.0
+-- webpack@1.13.3
| +-- acorn@3.3.0
| +-- async@1.5.2
| +-- clone@1.0.2
| +-- enhanced-resolve@0.9.1
| | `-- memory-fs@0.2.0
| +-- interpret@0.6.6
| +-- memory-fs@0.3.0
| | `-- errno@0.1.4
| |   `-- prr@0.0.0
| +-- node-libs-browser@0.6.0
| | +-- assert@1.4.1
| | +-- browserify-zlib@0.1.4
| | | `-- pako@0.2.9
| | +-- buffer@4.9.1
| | | +-- base64-js@1.2.0
| | | `-- ieee754@1.1.8
| | +-- constants-browserify@0.0.1
| | +-- crypto-browserify@3.2.8
| | | +-- pbkdf2-compat@2.0.1
| | | +-- ripemd160@0.2.0
| | | `-- sha.js@2.2.6
| | +-- domain-browser@1.1.7
| | +-- events@1.1.1
| | +-- http-browserify@1.7.0
| | | `-- Base64@0.2.1
| | +-- https-browserify@0.0.0
| | +-- os-browserify@0.1.2
| | +-- path-browserify@0.0.0
| | +-- process@0.11.9
| | +-- punycode@1.4.1
| | +-- querystring-es3@0.2.1
| | +-- readable-stream@1.1.14
| | | `-- isarray@0.0.1
| | +-- stream-browserify@1.0.0
| | | `-- readable-stream@1.1.14
| | |   `-- isarray@0.0.1
| | +-- string_decoder@0.10.31
| | +-- timers-browserify@1.4.2
| | +-- tty-browserify@0.0.0
| | `-- vm-browserify@0.0.4
| +-- supports-color@3.1.2
| +-- tapable@0.1.10
| +-- watchpack@0.2.9
| | `-- async@0.9.2
| `-- webpack-core@0.6.8
|   +-- source-list-map@0.1.6
|   `-- source-map@0.4.4
+-- webpack-stream@3.2.0
| +-- lodash.clone@4.5.0
| +-- lodash.some@4.6.0
| `-- vinyl@1.2.0
`-- yargs@1.3.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})

C:\Users\Hubert\Prebid.js>

**Comment by headerbidding** [comment]
Wow! I assume I now have a prebid.js with all the adapters! 
Cool!
Now I have to figure out how to make on with selected adapters...

**Comment by headerbidding** [comment]
Hmm. the prebid.js file generated is only 30kb.
When I donload it with the selected adapters it is 50kb.

**Comment by mkendall07** [comment]
Modify `Prebid.js/adapters.json` to list only the adapters you want to be built with and then run `gulp build`

**Comment by headerbidding** [comment]
Wow. It worked! I made my own 0.15.3-pre version !!!

But: I still get the Error:
Object {} "ERROR: Prebid Error: no analytics adapter found in registry for
        ga." ""

Example:
http://www.flixxy.com/come-together-4-minute-christmas-short-film-by-wes-anderson.htm?pbjs_debug=true

**Comment by headerbidding** [comment]
So I changed   "analytics": [], to  "analytics": "ga", 
but got an error when doing another gulp build:

C:\Users\Hubert\Prebid.js>gulp build
[14:44:17] Using gulpfile ~\Prebid.js\gulpfile.js
[14:44:17] Starting 'clean'...
[14:44:17] Starting 'hint'...
[14:44:17] Starting 'jscs'...
[14:44:18] Starting 'webpack'...
[14:44:18] Starting 'devpack'...
[14:44:18] Finished 'clean' after 1.33 s
{ [Error: ./src/adaptermanager.js
Module build failed: TypeError: analyticsAdapters.map is not a function
  at insertAnalytics (C:\Users\Hubert\Prebid.js\loaders\analyticsLoader.js:16:38
)
  at processData (C:\Users\Hubert\Prebid.js\node_modules\block-loader\index.js:3
1:20)
  at Object.<anonymous> (C:\Users\Hubert\Prebid.js\node_modules\block-loader\ind
ex.js:51:12)
 @ ./src/prebid.js 25:21-48]
  message: './src/adaptermanager.js\nModule build failed: TypeError: analyticsAd
apters.map is not a function\n  at insertAnalytics (C:\\Users\\Hubert\\Prebid.js
\\loaders\\analyticsLoader.js:16:38)\n  at processData (C:\\Users\\Hubert\\Prebi
d.js\\node_modules\\block-loader\\index.js:31:20)\n  at Object.<anonymous> (C:\\
Users\\Hubert\\Prebid.js\\node_modules\\block-loader\\index.js:51:12)\n @ ./src/
prebid.js 25:21-48',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }
{ [Error: ./src/adaptermanager.js
Module build failed: TypeError: analyticsAdapters.map is not a function
  at insertAnalytics (C:\Users\Hubert\Prebid.js\loaders\analyticsLoader.js:16:38
)
  at processData (C:\Users\Hubert\Prebid.js\node_modules\block-loader\index.js:3
1:20)
  at Object.<anonymous> (C:\Users\Hubert\Prebid.js\node_modules\block-loader\ind
ex.js:51:12)
 @ ./src/prebid.js 25:21-48]
  message: './src/adaptermanager.js\nModule build failed: TypeError: analyticsAd
apters.map is not a function\n  at insertAnalytics (C:\\Users\\Hubert\\Prebid.js
\\loaders\\analyticsLoader.js:16:38)\n  at processData (C:\\Users\\Hubert\\Prebi
d.js\\node_modules\\block-loader\\index.js:31:20)\n  at Object.<anonymous> (C:\\
Users\\Hubert\\Prebid.js\\node_modules\\block-loader\\index.js:51:12)\n @ ./src/
prebid.js 25:21-48',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }
[14:44:26] Finished 'hint' after 9.44 s
[14:44:26] Finished 'jscs' after 9.41 s
[14:44:26] Starting 'quality'...
[14:44:26] Finished 'quality' after 5.99 µs

C:\Users\Hubert\Prebid.js>

**Comment by protonate** [comment]
An array is expected, try `"analytics": ["ga"]`

**Comment by headerbidding** [comment]
Thank you! It works now! Thanks to all for your help!

**Comment by mkendall07** [comment]
@headerbidding Glad it's working. 

@prebid/docs this ticket could be used as a starting point for more verbose dev help docs / getting starting with dev

**Comment by headerbidding** [comment]
Yes. Your instructions were great. I have never used npm or git and it was easy to follow!
