### ISSUE TITLE
Adding userId ad-hoc

### ISSUE THREAD

**Issue by EskelCz** [prebid/Prebid.js#8241]
## Type of issue
question

## Description
Is it possible to add a userId without it having it's own module? The goal is to have a private id system, only for our publishers, and be able to simply register it into any prebid build, or inject it into the bid requests - into the userId object, which is passed by bid adapters automatically.

I'm now trying to do it by altering bidRequests with a RTD submodule, but so far no luck. No changes to the userId object stick. Is there a writable "source of truth" object to alter? How to get the reference?

If not, having something like registerIdModule (akin to registerBidAdapter) would be nice. That would be a feature request.
Thanks for any advice.

**Comment by patmmccann** [comment]
Why not just the publisher provided id submodule?

**Comment by EskelCz** [comment]
@patmmccann I don't follow. We're building a custom id system, but don't want to add it to prebid, since it's only for local publishers we support.

**Comment by EskelCz** [comment]
@patmmccann I think you're right. I was under the impression that id systems have to be added to registered with prebid, not sure why :) Thanks
