### ISSUE TITLE
adUnit code based refresh times out without setting targets

### ISSUE THREAD

**Issue by indexexchange** [prebid/Prebid.js#825]
## Type of issue
Bug

## Description
Prebid key-value targets are always empty on the ad-unit code based refreshes.

## Steps to reproduce
* have multiple slots
* refresh just a single slot, e.g. 
```
  pbjs.requestBids({
    adUnitCodes: ['div-gpt-ad-1438287399331-0'],
    bidsBackHandler: function() {
      pbjs.setTargetingForGPTAsync(['div-gpt-ad-1438287399331-0']);
      googletag.pubads().refresh([rightSlot]);
    }
  });
```

### Expected results

Targets on adUnit code based refresh:

```
> hb_bidder: indexExchange
> hb_adid: 1548157f46ea2e3
> hb_pb: 8.00
> hb_size: 300x250
```

### Actual results

Targets on adUnit code based refresh:

```
> hb_bidder: 
> hb_adid: 
> hb_pb: 
> hb_size: 
```
## Platform details
Versions 0.15.0, 0.15.1, 0.15.2 are all affected; v0.14.0 is not affected.

## Other information

`bid.requestTimestamp` is not necessarily the timestamp of the slot being refreshed.  Because the previous request's timestamp is older than request timestamp of the refresh, the auction always times out as soon as the first response is processed and therefore none of the bids participate in auctions:

```
exports.addBidResponse = function (adUnitCode, bid) {
  if (bid) {
    ...
 
    bid.timeToRespond = bid.responseTimestamp - bid.requestTimestamp;
 
    if (bid.timeToRespond > pbjs.cbTimeout + pbjs.timeoutBuffer) {
      var timedOut = true;
 
      exports.executeCallback(timedOut);
    }
    ...
    pbjs._bidsReceived.push(bid);
```

**Comment by mkendall07** [comment]
@indexexchange 
Does #828 solve your issue?

**Comment by indexexchange** [comment]
>  Does #828 solve your issue?

Yes... with this fix, ad unit based refresh works as expected.
