### ISSUE TITLE
Rubicon Analytics Adapter: Bump ajv json validation library dependency

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8253]
## Type of issue
Bug

## Description
Magnite team: Please bump versions or remove your dependency on AJV. Potentially solved by #8049, but that seemed to have excessive package lock changes. 

Also, curious why the build time dependency decision was made? Does it have a material effect on build size?

**Comment by robertrmartinez** [comment]
https://github.com/prebid/Prebid.js/pull/8268

**Comment by robertrmartinez** [comment]
https://github.com/prebid/Prebid.js/pull/8268 was merged
