### ISSUE TITLE
Losing `user.data` after getLegacyFpd

### ISSUE THREAD

**Issue by nllerandi3lift** [prebid/Prebid.js#8264]
## Type of issue

Question / Possible bug

## Description
`user.data` is getting dropped when the result of `getConfig('ortb2')` is passed into `getLegacyFpd`. A few bid adapters are still using this method so posting here first to see if this is desired behavior. 

It looks like this may have been intentional at some point - https://github.com/prebid/Prebid.js/pull/6293#pullrequestreview-602990861
As the method is filtering out `data` keys - https://github.com/prebid/Prebid.js/blob/3fd3b5dca5dcc3fcd9f3c949e8e1a3238ea6b836/src/config.js#L371

But `user.data` is an increasingly more relevant field - https://github.com/prebid/Prebid.js/issues/6057

Is this intentional?

## Steps to reproduce
<img width="646" alt="Screen Shot 2022-04-07 at 1 22 51 PM" src="https://user-images.githubusercontent.com/75995508/162261877-2c307044-0a01-4c72-b2ea-8c9989e11703.png">

## Platform details
Testing on v6.19.0-pre, but I would think this some functionality can be found from when `getLegacyFpd` was introduced.

**Comment by patmmccann** [comment]
This appears to be a significant bug

**Comment by patmmccann** [comment]
@nllerandi3lift on further review, only two adapters still use this function; perhaps you can deprecate your use of it?

**Comment by nllerandi3lift** [comment]
I figured that might be the case. The usage of `fpd` is pretty old at this point. I'll take a look at deprecating.

**Comment by nllerandi3lift** [comment]
We can close this if there are no other concerns. I'm fine with deprecating.

**Comment by bretg** [comment]
Thanks @nllerandi3lift - apparently we neglected to get rid of getLegacyFPD in 5, but will do so in 7.
