### ISSUE TITLE
Appnexus: ANOutstreamVideo renderer - inline style

### ISSUE THREAD

**Issue by mikemangas** [prebid/Prebid.js#8271]
## Description
Appnexus: When i call in outstream: ANOutstreamVideo renderer...
Everything works fine, but the div that is beeing created with "_apn_expandable_" has a height of 0.1px... Therefore the outstream video is not beeing displayed. If i remove manually the property height, i get the video displayed.

Where from are the "height" and all the other inline styles from the "_apn_expandable_" div dependent?

### Expected results

Outstream is getting displayed without manipulating the inline style of the "_apn_expandable_" element

### Actual results

"_apn_expandable_" div doesnt the video, since the height is set to 0.1px  

## Platform details
All web platforms

**Comment by mikemangas** [comment]
![image](https://user-images.githubusercontent.com/85886271/162698149-f34fee5b-509a-441e-bb91-b76a1fb41706.png)

It happens in that line of code in your video player

@mkendall07

**Comment by muuki88** [comment]
@mikemangas what was the issue?

**Comment by mikemangas** [comment]
Heyy @muuki88 , sorry for replying so late:
The behavior of the video player is correct. In case you use non-friendly iframes, it does not open the video player until you provide some informations about the scrollposition via a cb function.
:-)
