### ISSUE TITLE
Prebid 7: remove support for legacy FPD

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#8283]
## Description

Remove support for `setConfig('fpd')`, `config.getLegacyFpd`, `config.convertAdUnitFpd` and related relics of legacy fpd

Related: https://github.com/prebid/Prebid.js/issues/8264

**Comment by patmmccann** [comment]
#7796 for linkage

**Comment by dgirardi** [comment]
going through adapters for an unrelated issue, I noticed some uses of legacy fpd that are not trivial to remove. For example:

https://github.com/prebid/Prebid.js/blob/2c0518f38d505a8749eafba0b34932b26b4685eb/modules/adrelevantisBidAdapter.js#L138-L145

depending on how many more like these there are, it may be better to reduce the scope of this change to removing just the portion that is public in the publisher API.

**Comment by patmmccann** [comment]
taxonomy committee indicates support to include this in 7
