### ISSUE TITLE
Don't enforce mediaTypes for pbsBidAdapter

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#8291]
## Type of issue
enhancement

## Description
@patmmccann reported a scenario where the colossusssp doesn't match the server-side colossus adapter name. This would be fine except in when the mediaType is video, the pbsBidAdapter is removing the colossus bidder

In discussing this, we don't see why the PBS bid adapter should be filtering bidders for mediatypes. The server knows which bidders can support which mediatypes, and this can change any time.

We think it would be best for the pbsBidAdapter to not worry about enforcing this. In most cases, it doesn't save more than a few bytes in the outgoing request to let the server make the decision.

## Steps to reproduce

```
    var adUnits = [
           {
               code: 'test-div',
                mediaTypes: {
                    video: { ... }
               },
               bids: [{
                       bidder: 'colossus',
                       params: { ... }
               }]
          }
     ];

pbjs.setConfig({
        s2sConfig: {
                    accountId: '7780',
                    bidders: ['colossus'],
                    defaultVendor: 'rubicon'
        }
});
```

### Expected results

Call to PBS with colossus bidder

### Actual results

Colossus is filtered because it's a video request and there's no client-side adapter declaring that it supports video

**Comment by patmmccann** [comment]
@mmoschovas fyi
