### ISSUE TITLE
Static GDPR-Consent 

### ISSUE THREAD

**Issue by arneschulz1984** [prebid/Prebid.js#8303]
## Type of issue
Bug / Question

## Description
Until version 6.18.0 it was possible to set a static GDPR Consent like documentated here (https://docs.prebid.org/dev-docs/modules/consentManagement.html -> Example 2: Static CMP using custom data passing.) and the Prebid.JS requests includes the provided consentString. With Version >= 6.19.0 this behavior changed.

Until 6.18.0 setting the static GDPR Consent like this:

let tcStr = 'CO4EXq8O4EYOWADABCDEAxCsAP_AAH_AAAAAGStV_T9fb2vj-_599_t0eY1f9_63t-wzhheMs-8NyZeX_J4Wv2MyvB34JqQKGRgkunLBAQdtHGncTQgBwIlViTLMYk2MjzNKJrJEmlsbO2dYGH9Pn8XT_ZKZ70-vv__7v3___33_4GSEEmCpfAQJCWMBJNmlUKIEIVxIVAOASghGEg0sNCRQU7I4CPUACABAYAIQIAQAgohJBAAIAAElEQAgAwIBEARAIAAQAjQEIACJAEFgBIGAQACoGhYARRBKBIQYHBUcogQFSLRQTwCQgAAMAAEAABQAAYAAHAACAAAkAAKAAA.YAAAAAAAAAA'

var pbjs = pbjs || {};
pbjs.que = pbjs.que || [];
pbjs.que.push(function() {
    pbjs.setConfig({
        priceGranularity: "high", 
        consentManagement: {
            gdpr: {
                cmpApi: 'static',
                consentData: {
                    getTCData: {
                        tcString: tcStr,
                        gdprApplies: true,
                        purpose: {
                            consents: {
                                1: true,
                                2: true,
                                3: true,
                                4: true,
                                5: true,
                                6: true,
                                7: true,
                                8: true,
                                9: true,
                                10: true
                            }
                        }
                    }
                }
            }
        }
    });
});

has the impact that a Prebid.JS bid requests includes:

`{
  ......
  "gdprConsent": {
    "consentString": "CO4EXq8O4EYOWADABCDEAxCsAP_AAH_AAAAAGStV_T9fb2vj-_599_t0eY1f9_63t-wzhheMs-8NyZeX_J4Wv2MyvB34JqQKGRgkunLBAQdtHGncTQgBwIlViTLMYk2MjzNKJrJEmlsbO2dYGH9Pn8XT_ZKZ70-vv__7v3___33_4GSEEmCpfAQJCWMBJNmlUKIEIVxIVAOASghGEg0sNCRQU7I4CPUACABAYAIQIAQAgohJBAAIAAElEQAgAwIBEARAIAAQAjQEIACJAEFgBIGAQACoGhYARRBKBIQYHBUcogQFSLRQTwCQgAAMAAEAABQAAYAAHAACAAAkAAKAAA.YAAAAAAAAAA",
    "consentRequired": true
  },
  ......
}`

After updating to a version >= 6.19.0 the Prebid.JS request do not include the consentString any more.
The request looks now like this:
`{
  ......
  "gdprConsent": {
    "consentRequired": false
  },
  ......
}`

Up to now i do not find a way to fix this. Would be cool if you can help me to get it work again.
Because we need it for our automatic tests.

**Comment by patmmccann** [comment]
Somewhat related 

https://github.com/prebid/Prebid.js/issues/6377

is a proposal for us to use in tests as well
