### ISSUE TITLE
Extract installed modules from a Prebid.js file.

### ISSUE THREAD

**Issue by michelangelo246** [prebid/Prebid.js#8308]
## Type of issue
Question

## Description
I am currently able to extract the installed modules from Prebid.js files of version 6.3.0 and above with the following regex: /installedModules\.push\("(.*?)"/g

But this doesn't seem to work for earlier versions. Is there a way I could get them from these versions?

**Comment by dgirardi** [comment]
I don't think there's an easy way to do that - before 6.3.0, the bundle should contain a statement of the kind `installedModules = ['module1', 'module2', ...];` - but that was broken at some point which is the reason it eventually was changed. (If you go back far enough, you should find that statement).

Depending on how many resources you want to sink into this, you could build the specific version and compare the output modules with the contents of your bundle - which is little more than a concatenation of the files generated under `build/dist`.

**Comment by michelangelo246** [comment]
I see.

Thanks anyway :)
