### ISSUE TITLE
Does userID take too long to initialize by default?

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#8311]
## Type of issue
Question / feature request

## Description
https://github.com/prebid/Prebid.js/pull/8201 introduced `getUserIdsAsync()`, which gives publishers a way to wait for all userIDs to complete initialization.

The time it takes for userID calls to complete is controlled through [`syncDelay` and/or `auctionDelay`](https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html#setConfig-ConfigureUserSyncing-UserSyncProperties) configuration. By default, if neither is specified, userID modules will not start making their network calls until the first auction has completed.

This results in `getUserIdsAsync()` taking a surprisingly long time, as the discussion in https://github.com/prebid/Prebid.js/issues/5447 shows. It can be made quicker by setting `auctionDelay: 1` (or greater), which does not seem very intuitive.

Should we change the default behavior, or give a more explicit configuration option to start userID init early?

**Comment by patmmccann** [comment]
tagging https://github.com/prebid/Prebid.js/issues/8295 as related

**Comment by premesh-freestar** [comment]
Config/Setup around this is certainly not straight forward. I think the config option would be ideal (with perhaps some cleanup/refactor of what is there now to address the confusion). 
Understand this would imply larger changes but feels like we should be able to provide an timeout to get userIds similar to how we handle getting consent data ?

Would a `timeout` and `target` options work where `target` would be `PRE-AUCTION` `POST-AUCTION` or `MANUAL` (to allow only manual triggers for custom logic)

**Comment by patmmccann** [comment]
The proposed requirement for the fix is that:

 auctionDelay: 1 should delay longer than auctionDelay: 0; and hence, that if someone explicitly sets 0, it will fire one ms before auctionDelay 1. If the value is not explicitly set, the default should be the existing behavior, initiating after the end of the first auction.

**Comment by patmmccann** [comment]
Tagging this as 7 to make sure we include in release notes, people should be well aware of behavior changes on this

**Comment by EskelCz** [comment]
@dgirardi I still feel it would be beneficial to make the getUserIdsAsync work better. We don't particularly need it anymore though, that's correct.

**Comment by patmmccann** [comment]
It seems like a new configuration option is preferred to changing the behavior of auction delay zero; still assessing publisher demand.

**Comment by patmmccann** [comment]
@dgirardi dumb q here: if a pub also has enableOverride set to true, does triggerUsersyncs fire the user module syncs or are those governed by the other params?

**Comment by dgirardi** [comment]
enableOverride has no effect on userId, only on user syncs as defined by bid adapters.

**Comment by patmmccann** [comment]
500 is a reasonable default
