### ISSUE TITLE
SharedId User Config since v6

### ISSUE THREAD

**Issue by johngeorgewright** [prebid/Prebid.js#8325]
## Type of issue

Question / Bug

## Description

We have been trying, for a while, to upgrade our prebid implementation from v4 to v6. One of our biggest problems has been SharedId. We understand that PubCommonId & SharedId have merged and we've read all the documentation you have made available, however, we haven't managed to get it working successfully since the upgrade.

We have also noticed that one can use a "backwards compatible" version of SharedId which uses an old "pubCommonId" version. This works a charm, however, it's bugging me why we can't use the newer SharedId cookie sync.

## Steps to reproduce

We added the sharedId config, just as you have documented. The only difference is the cookie name doesn't have an underscore. When using this in v4 all bidders receive the `sharedid` cookie value in the auction payload (usually something like: `user.edis[x].uids[x].id`)
 
```javascript
pbjs.setConfig({
    userSync: {
        userIds: [{
            name: 'sharedId',
            storage: {
                type: 'cookie',
                name: 'sharedid',
                expires: 28
            }
        }]
    }
});
```

However, since upgrading to v6, and removing any previous references to `PubCommonId` the above configuration seems not to do anything until replaced with:

```javascript
pbjs.setConfig({
    userSync: {
      userIds: [{
        name: 'pubCommonId',
        storage: {
          name: '_pubcid',
          type: 'cookie',
          expires: 28
        }
      }]
    }
})
```

### Expected results
Bidders should receive the `sharedid` cookie value as in the auction payload (usually something like: `user.edis[x].uids[x].id`)

### Actual results
Nothing is sent unless we revert to `pubCommonId`.

## Platform details

| Platform | Version |
| --- | --- |
| prebid.js | 6.21.1 |
| browser | Chrome 100.0.4896.127 |
| OS | MacOS 12.3.1 |
| Node | 16.14.0 |
| NPM | 8.3.1 |

**Comment by patmmccann** [comment]
what happens if you try 

pbjs.setConfig({
    userSync: {
        userIds: [{
            name: 'sharedId',
            storage: {
                type: 'cookie',
                name: '_pubcid',
                expires: 28
            }
        }]
    }
});

**Comment by johngeorgewright** [comment]
@patmmccann that does seem to do something. It adds a sync cookie on the "pubcid.org" source. Is that what we should expect?

**Comment by patmmccann** [comment]
@johngeorgewright when you set the config as I suggested, does it end up in payloads?

**Comment by patmmccann** [comment]
@jdwieland8282 of note, I think shared id is not in eids.js
