### ISSUE TITLE
Cwire Adapter missing from download page

### ISSUE THREAD

**Issue by espen-j** [prebid/Prebid.js#8331]
## Type of issue
Bug

## Description

The cwire adaptor is missing from the download page, we tried getting some help here prebid/prebid.github.io#3673 and we also filed a PR that didn't do the trick: https://github.com/prebid/prebid.github.io/pull/3676

This is a regression, we used to be listed. And we're trying for over a month now to get back in on that page.

## Steps to reproduce

Step by step according to your guidelines:

1. Your adapter code is merged into Prebid.js - Merged in [/modules/cwireBidAdapter.js|md](https://github.com/prebid/Prebid.js/blob/master/modules/cwireBidAdapter.js)
2. Your bidder docs PR is submitted over here to the docs site - Merged in [dev-docs/bidders/cwire.md](https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/cwire.md)
3. Your adapter code is included with a release - Yes [1]
4. Once your adapter code is actually released, we merge the adapter docs PR, and the Downloads page is automagically updated with a checkbox to include your adapter.

[1] 
```
$ ll Prebid.js-6.21.1/modules/cwireBidAdapter.*
-rw-rw-r--@ 1 espen  staff  8807 Apr 20 20:24 Prebid.js-6.21.1/modules/cwireBidAdapter.js
-rw-rw-r--@ 1 espen  staff  1213 Apr 20 20:24 Prebid.js-6.21.1/modules/cwireBidAdapter.md
``` 

## Test page

The adapter should be listed here:
https://docs.prebid.org/download.html

### Expected results

The adapter should be listed here:
https://docs.prebid.org/download.html

### Actual results

It's not.

## Platform details

I'm assuming this is related to your build pipelines and some of our resources not being picked up, or not processed.

## Other information

prebid/prebid.github.io#3673
https://github.com/prebid/prebid.github.io/pull/3676

**Comment by bretg** [comment]
Confirmed fixed.
