### ISSUE TITLE
Skipped conflated with nomatch in floors module

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8339]
## Type of issue

We pass skip and model version to gam, and we're seeing extremely high incidence of skip, when skip is set to 50%, we're seeing skiprates of 80% in data.

https://github.com/prebid/Prebid.js/blob/061eb3c9c295d1e9bb9af62e1ba2370781f0ad17/modules/priceFloors.js#L365 seems to be the problem. 

It sets 'skipped' to true when no match occurs, which makes it impossible or difficult to calculate model lift, which would just be (revenue(noskip)/(1-skiprate))/(revenue(skip)/skiprate). 

The rubicon analytics module seems to be able to calculate lift anyways somehow, but we're trying to verify as a pub by setting targeting with model version.

Instead of skipped, these should have some other status, eg nomatch, that we could identify.

cc: @robertrmartinez

**Comment by robertrmartinez** [comment]
@patmmccann 

I think if no floor rules are resolved, then the module passes through location: `noData`

if rule json came from adUnits => 'adUnit'
if rule json came from setConfig => 'setConfig'
if rule json came from setConfig => 'fetch'

if NO rule json was resolved => 'noData'

This is what the Rubicon Analytics Adapter looks for I believe.

Perhaps we can add a more descriptive `status` field?

What do you think?

**Comment by robertrmartinez** [comment]
If the existing 'noData' works then maybe best to not add another field, but I can be persuaded either way!

**Comment by robertrmartinez** [comment]
@patmmccann 

Does the `location: noData` satisfy your use case?

Or should we add a new `status` enum or something?

**Comment by patmmccann** [comment]
This is moot for us because we ensured full rule coverage (making sure a *|* rule always exists). I think we can hook to nodata instead of testing for skipped. I'll reopen if a need arises or someone else encounters. 

Thanks!!
