### ISSUE TITLE
Index id parameter

### ISSUE THREAD

**Issue by deanned2012** [prebid/Prebid.js#834]
Our setup is as follows

bidder: 'indexExchange',
params: {
    "id": "1",
    "siteID": 179755,
}

For id we have been using a number that corresponds with the unit number, so in the script multiple sizes are using the same ID.
For example Unit 3 can be a 120x600 and a 160x600, we would use id: "3" for both.

However, we noticed that some of these ids aren't buying. We have tested with unique ids which seems to resolve the problem, but if there are more than a few ids we are seeing the following error.

bidders.js:3 Object {} "INDEXEXCHANGE: Too many unique sizes on slots, will use the first 20." ""

**Comment by indexexchange** [comment]
Hello @deanned2012,

Can you share you full configuration so that we can comment further?
