### ISSUE TITLE
Error while downloading Prebid.js with ATS Analytics

### ISSUE THREAD

**Issue by me-bhavya** [prebid/Prebid.js#8376]
## Type of issue
Bug

## Description
On downloading prebid.js file from https://docs.prebid.org/download.html and adding ATS Anaytics adapter, we  are getting an error :
`{"error" : "Prebid file not built properly","requestId":"4d31571f-42fb-4623-8233-0b2a3ebbf903"}`

## Steps to reproduce
If you try downloading prebid.js from  the above link with ATS Analytics adapter selected, it isn't downloading the file instead this error message is coming up.

### Expected results
Prebid.js file

### Actual results
![image](https://user-images.githubusercontent.com/48640551/166936829-b34883dc-43a9-474e-a02e-e744053e3c25.png)

**Comment by dgirardi** [comment]
Thanks for the report - https://github.com/prebid/prebid.github.io/pull/3756 should fix it.

**Comment by bretg** [comment]
confirmed ATS Analytics is on the download page now
