### ISSUE TITLE
Flow of creating adUnits

### ISSUE THREAD

**Issue by Optad360** [prebid/Prebid.js#8387]
## Type of issue
Question

## Description
Hello!

We have a question about the recommended adUnit creation flow.
From version 6.19.0 we have a problem because requests are not coming out and we get a message about undefined adUnits.
![prebid](https://user-images.githubusercontent.com/99328550/167354938-6ab8a295-aee6-4e23-979a-257806774ea0.PNG)

So far, we've done this by adding adUnits to the array, sending the request, and then deleting it from that array. Up to version 6.18.0 it worked fine. Hence our question - how should this process be properly carried out now?

**Comment by dgirardi** [comment]
@Optad360 can you provide a test page, or steps to reproduce? How/when are you calling `addAdUnits`, `removeAdUnits`, `requestBids`; what is your expected behavior / how is it different between versions?

**Comment by dgirardi** [comment]
If I had to guess, you're doing something like:

```
pbjs.addAdUnits(adUnit);
pbjs.requestBids();
pbjs.removeAdUnit(adUnit.code);
```

If so, I suggest replacing that with `pbjs.requestBids({adUnits: [adUnit]})`.

**Comment by patmmccann** [comment]
@Optad360 if that doesn't solve your problem, please let us know

**Comment by Optad360** [comment]
Hi @patmmccann, your tips have solved our problem. 
Thank you for your help. 
You can mark this question as solved.
