### ISSUE TITLE
USP string not set on multiple bidders at live page

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8393]
## Type of issue
Bug?

## Description
USP string missing from payloads

## Steps to reproduce

typing:
__uspapi('getUSPData', 1 , function(uspData, success) {console.log(uspData, success);}) results in a string '1YNN' on my browser in NJ.

No payload contains this, eg Sharethrough

![image](https://user-images.githubusercontent.com/1683175/167460221-d2afde5a-014d-4896-b206-beb59d233818.png)

## Test page
https://allthatsinteresting.com/this-week-in-history-news-may-1-7

generates a USP string

### Expected results
USP string attached to bidder payloads

### Actual results
USP string missing from payloads

## Platform details
Prebid 6.20

**Comment by patmmccann** [comment]
this console command also generates an error, perhaps prebid should recover from this error more greacefully?

**Comment by dgirardi** [comment]
The copy of Prebid running on that page does not seem to have `consentManagementUSP` installed? 

https://allthatsinteresting.com/wordpress/wp-content/plugins/bwp-minify/min/?f=wordpress/wp-content/plugins/pbh-common/pbh-pb.js,wordpress/wp-content/plugins/pbh-common/pbh-pau-bundle.js,wordpress/wp-content/themes/ati-2018/footer-scripts.js,wordpress/wp-content/themes/ati-2018/assets/js/bootstrap.min.js,wordpress/wp-content/plugins/wp-smushit/app/assets/js/smush-lazy-load.min.js,wordpress/wp-content/plugins/social-networks-auto-poster-facebook-twitter-g/js-css/jquery.modal.min.js&ver=1646149868

text search for `consentManagementUsp` returns 0 results, unlike `consentManagement` (gdpr).

**Comment by dgirardi** [comment]
Actually, that page does not have `__uspapi` for me - even if I use a VPN that exits in Los Angeles. I do not have access to a NJ VPN.
