### ISSUE TITLE
Takeovers..

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#84]
For premium sites we would like to road-block, whereby a response from AppNexus with priority level 10 would prevent other bids from networks like Rubicon, Criteo etc. from being considered. For this to work I believe the only way is for AppNexus to return priority within their bid response?

**Comment by prebid** [comment]
Hi @cwbeck, don't think the AppNexus bidder adaptor today can run roadblocking, because it sends out individual requests for each ad unit (not a single request mode). Maybe work with your AM there to figure things out?

**Comment by Heray** [comment]
@cwbeck the AppNexus adaptor will go through an update in Q1 next year to support road blocking. Closing this ticket for now as we do not have immediate action.
