### ISSUE TITLE
Renaming GA global seems to stop events from firing

### ISSUE THREAD

**Issue by samburdge** [prebid/Prebid.js#841]
## Type of issue
bug

## Description
After changing the name to something other than 'ga' the events are not registered in google analytics

## Steps to reproduce
In the analytics options rename 'ga' to something else, for example:

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','custom_ga');

pbjs.enableAnalytics({
            provider: 'ga',
            options: {
                global: 'custom_ga', // <string> name of GA global. Default is 'ga'
                enableDistribution: false, 
            }
        });

### Expected results
Would expect to see events reporting in GA

### Actual results
Events are not reported

**Comment by matthewlane** [comment]
#832 is in the queue for review and may fix this

**Comment by matthewlane** [comment]
Renaming ga global with `options.global` should now be possible with #832 in master
