### ISSUE TITLE
Multiple adapters: use our tag insertion methods

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8421]
## Type of issue
Bug

## Description
Several adapters appear to not be using our methods to append scripts or tags to the DOM. Please switch them over

https://github.com/prebid/Prebid.js/blob/747f1430f33f69ca683198ae7ca8c10473ff7ce9/modules/cleanioRtdProvider.js#L58
@nick-clean 

https://github.com/prebid/Prebid.js/blob/3ef3cf4d1a62a43ae314edb21b1f054ace8a764a/modules/airgridRtdProvider.js#L47 @ydennisy 

https://github.com/prebid/Prebid.js/blob/78e1bdb2dd921930e24ef1b494a7e89f84e862a3/modules/realvuAnalyticsAdapter.js#L172 @tchibirev

**Comment by ftxmoJason** [comment]
Thanks @patmmccann for pointing this out. Can you direct us to the correct method definition in the docs? Thanks

**Comment by patmmccann** [comment]
> Thanks @patmmccann for pointing this out. Can you direct us to the correct method definition in the docs? Thanks

https://github.com/prebid/Prebid.js/commit/2a05213fb73d88ac939c0b0dd4b5750649446372 is an example; using the loadExternalScript utility

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/pull/7699 is an example of a fix to a tag

**Comment by parisholley** [comment]
@patmmccann we only use that to write image pixels for measuring viewability when the browser does not support the IntersectionObserver API. is there a recommended way to drop non-tracking pixels? loadExternalScript does not seem to be relevant in this case.

**Comment by anthonylauzon** [comment]
@patmmccann we have a fix for this that you should expect to be submitted as a PR soon.  Please direct future bugfix requests to @abhibond or @jlaso.

**Comment by jimdigriz** [comment]
What is the official method to preload a script here?

I cannot find anything obvious:

```alex@aineko:~/src/adloox/Prebid.js$ git grep "'preload'" modules/ src/
modules/adlooxAnalyticsAdapter.js:  link.setAttribute('rel', 'preload');
modules/cleanioRtdProvider.js:  linkElement.rel = 'preload';
modules/geoedgeRtdProvider.js:  link.rel = 'preload';
alex@aineko:~/src/adloox/Prebid.js$ git grep '"preload"' modules/ src/
alex@aineko:~/src/adloox/Prebid.js$ ```

The Adloox analytics adapter does use `loadExternalScript`, we just want a preload option for it.

**Comment by ftxmoJason** [comment]
Thanks @patmmccann our fix PR has been merged and closed. We should be all good on this thread, please let us know if we missed anything.

**Comment by patmmccann** [comment]
@ftxmoJason thanks!

**Comment by patmmccann** [comment]
@jimdigriz we don't have a preload method. Is it providing some advantage to you to preload the script a couple js dozen lines before you load it? It would seem your preload doesnt run until a couple millisecond before your run.

**Comment by jimdigriz** [comment]
> @jimdigriz we don't have a preload method. Is it providing some advantage to you to preload the script a couple js dozen lines before you load it? It would seem your preload doesn't run until a couple millisecond before your run.

Only in which we know the JS will be injected anyway so to have our impression event line up much more closely to when the ad slot populates we preload.

Happy to have someone (or did you want me to?) remove it if Prebid.js prefer to punt JS injection to after the auction process rather than before/during it.

**Comment by patmmccann** [comment]
We're curious if the preload is effective at loading your script any
sooner? Our reading of the code suggests it isn't, as the preload might not
occur until the module is loaded.

**Comment by jimdigriz** [comment]
> Our reading of the code suggests it isn't, as the preload might not occur until the module is loaded.

At the time I was looking for a suitable preload, and felt that `auctionInit` was too aggressive plus negatively impacted publishers that wished to load Prebid.js early but did not need to auction to kick off.

I *supposed* that maybe there could be a substantial time between `auctionEnd` and `bidWon` (as close as I could get to `ad request`/`impression`) so lumped for it.

Completely unscientific and unproven to of been any benefit to us...

**Comment by patmmccann** [comment]
I'm gonna take the three preload examples out of this issue; we might circle back some later date.

**Comment by cciocov** [comment]
Hey @patmmccann. This is fixed by PR #8490

**Comment by patmmccann** [comment]
@cciocov thanks!

**Comment by patmmccann** [comment]
@parisholley tyvm!

**Comment by jlaso** [comment]
Hi @patmmccann, I've have submitted a PR for adapting loadExternalScript in our code, any feedback will be very much appreciated https://github.com/prebid/Prebid.js/pull/8496  Thanks in advance!

**Comment by patmmccann** [comment]
@kakikei Are you able to comment on adgeneration intention to fix this issue?

**Comment by naripok** [comment]
@patmmccann, I've updated the loading method to use `loadExternalScript` in this [PR](https://github.com/prebid/Prebid.js/pull/9901).
The changes were contained and only replacing the loading method.
However, it looks like somehow it is affecting an unrelated module (mass), making one of its tests fail.
I've tried to make sense of it, but I'm really unable to understand how changing our load method could affect this other module.
Maybe you have a tip that could help me out?
I've [commented in the PR with the test error message](https://github.com/prebid/Prebid.js/pull/9901#issuecomment-1536339344), and there is also the CI run with the failed test [here](https://app.circleci.com/pipelines/github/prebid/Prebid.js/15748/workflows/eed25973-5c7f-4433-bf2d-764e7af329f5/jobs/28716).
We much appreciate the help!

**Comment by banakemi** [comment]
Hi, @patmmccann 
I fixed the code.
https://github.com/prebid/Prebid.js/pull/9911

**Comment by eugen-tikhonov** [comment]
Hello @patmmccann 
I've have submitted a PR with a changes - now we are using the `loadExternalScript` function to load our script. Thank you in advance! 
https://github.com/prebid/Prebid.js/pull/9991

**Comment by patmmccann** [comment]
Excellent, this can close with #9901 in that case!
