### ISSUE TITLE
pbjs_example_gpt.html not making any bid requests

### ISSUE THREAD

**Issue by rmertens** [prebid/Prebid.js#843]
## Question / Bug
Not sure if I'm doing something wrong or if there is a bug, so this is probably a question, but might be a bug.

## pbjs_example_gpt.html not making any bid requests
The problem is that I'm not getting pbjs_example_gpt.html to make any bid requests. I might be doing something stupid, but I've been trying for a couple of hours.

## Steps to reproduce
I downloaded pbjs_example_gpt.html, and made the following changes:
- put in my parameters for 1 ad unit for PulsePoint and AOL
- put in the DFP code snippet for that 1 ad unit
- pointed the prebid.js file src to the 'not for production' version that includes all adapters (I've previously tried with a prebid.js version from 
- commented out the Analytics section
- removed all bidderSettings except the Standard one

### Expected results
Bids are requested, processed, and all the rest.

### Actual results
Console only shows:
`INFO: Prebid.js v0.15.2 loaded`
No network requests happen.

## Platform details
Tried in Chrome, FF, and Safari on Macbook.
Prebid 15.0.2.

## Other information
Live example:
http://bloomsbury.crazygames.com/assets/experimental/pbjs_example_gpt.html?pbjs_debug=true

**Comment by mkendall07** [comment]
@rmertens 
Replace `$$PREBID_GLOBAL$$` with `pbjs` globally in your file.

**Comment by rmertens** [comment]
Thank you very much @mkendall07. How silly of me.
