### ISSUE TITLE
Issue on Colossusssp - pbjs 6.23.0

### ISSUE THREAD

**Issue by arupdebnath31** [prebid/Prebid.js#8433]
## Type of issue
Colossusssp throwing an error we tested on the site with ?pbjs_debug=true 
## Description
ERROR: colossusssp Bid Adapter emitted an uncaught error when parsing their bidRequest 
{e: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

## Platform details
We have currently trying with pbjs 6.23.0 . We also tried with 6.22.0 also. 

## Screenshot 
![Screenshot 2022-05-19 at 1 08 06 AM](https://user-images.githubusercontent.com/36239709/169226221-1e3000dc-3577-49ec-bae0-d41696ef72d6.png)

**Comment by dgirardi** [comment]
Are you using the floors module? (better still,  could you provide a test page)?

Going purely on that error message and the code, I believe it's this line failing:

https://github.com/prebid/Prebid.js/blob/b2c496c5e1a09a8f0e031c83071f1d1e292064bb/modules/colossussspBidAdapter.js#L121

Tagging @HuddledMasses
