### ISSUE TITLE
Add requestId and unit id to the timeout event.

### ISSUE THREAD

**Issue by thomaslsimpson** [prebid/Prebid.js#844]
## Description
Add requestId and unit id to the timeout event?

## Steps to reproduce
The timeout event only sends back for bidder(s) without including any additional information.

### Expected results
Timeout events should pass along information like the other events.

### Actual results
A list of bidders which have timed out.

**Comment by mkendall07** [comment]
Seems like a straight forward PR. Feel free to submit

**Comment by mkendall07** [comment]
@matthewlane does https://github.com/prebid/Prebid.js/pull/1824 satisfy this?

**Comment by matthewlane** [comment]
@mkendall07 It will, yes. @thomaslsimpson I'll update that PR to reference this issue.
