### ISSUE TITLE
Which example is recommended for a basic setup

### ISSUE THREAD

**Issue by rmertens** [prebid/Prebid.js#848]
## Question
Which example is recommended to use as a starting point for a regular DFP GPT setup?

## Description
As someone who is getting started with Prebid, it is not clear to me what the recommended starting point is. The natural place to look would be the basic example on the website:
- http://prebid.org/dev-docs/examples/basic-example.html

But it seems as if this was last updated 7 months ago, and indeed my account manager at one of the partners told me this was outdated.

Then there are other examples in the examples folder in the github repo:
https://github.com/prebid/Prebid.js/tree/master/integrationExamples/gpt

These seem to be updated more recently. But there are multiple. In particular,
pbjs_example_gpt.html, load_pbjs_dfp_concurrently.html, and load_pbjs_before_dfp_example.html.

Which is the recommended one to use?

**Comment by mkendall07** [comment]
@rmertens 
The basic setup above is good. nothing outdated there as far as I know. What was the specific concern by the partner?

**Comment by rmertens** [comment]
OK thanks! The partner seems concerned about speed (and thinks it is better to load pbjs before DFP).

**Comment by mkendall07** [comment]
@rmertens 
This example loads both prebid and DFP concurrently. If you don't want to do that you can use the example here instead: https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/load_pbjs_before_dfp_example.html

**Comment by headerbidding** [comment]
re: This is the legacy method of loading prebid.js. It only loads DFP library after bids are received or a timeout is reached.
* Publishers may wish to use this method to ensure DFP is not invoked early before prebid is returned.
https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/load_pbjs_before_dfp_example.html

Why would a publisher want to ensure DFP is not invoked early?
