### ISSUE TITLE
How to setup prebid for openx?

### ISSUE THREAD

**Issue by StrangerBRZ** [prebid/Prebid.js#849]
## Type of issue
Question

## Description
I recently decide to try out header bidding with prebid.js. But after setting up with this test page:
http://indigodaily.com/prebid.html

I don't think it is been implemented properly.

### Actual results
prebid_all.js:3 INFO: Prebid.js v0.15.0 loaded 
prebid_all.js:3 INFO: Invoking pbjs.setPriceGranularity : params :  Arguments[1]
prebid_all.js:3 INFO: Invoking pbjs.addAdUnits : params :  Arguments[1]
prebid_all.js:3 INFO: Invoking pbjs.requestBids : params :  Arguments[1]
prebid_all.js:3 INFO: Invoking pbjs.requestBids : params :  Arguments[1]
prebid_all.js:3 MESSAGE: Emitting event for: auctionInit
prebid_all.js:3 MESSAGE: CALLING BIDDER ======= openx
prebid_all.js:3 MESSAGE: Emitting event for: bidRequested
prebid_all.js:3 MESSAGE: Emitting event for: bidAdjustment
prebid_all.js:3 MESSAGE: Emitting event for: bidResponse
prebid_all.js:3 MESSAGE: Prebid auction cleared
prebid_all.js:3 MESSAGE: Emitting event for: auctionEnd

**Comment by combs** [comment]
try working off of the basic example here,
http://prebid.org/dev-docs/examples/basic-example.html

I think your loadScript call is misplaced--it looks like it is requesting the gpt js for the first time inside `initAdserver` instead of asking dfp to actually load the ads

**Comment by mkendall07** [comment]
@StrangerBRZ 
It looks like your prebid is setup correctly, but the line item creative that is winning doesn't contain the proper prebid creative. See https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/creative_rendering.html for the creative examples.
