### ISSUE TITLE
Application/json connection concerns

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8500]
https://github.com/prebid/Prebid.js/pull/8498 indicates ajax type application/json causes performance issues. A quick search indicates it is used widely in the project. Should this be remedied?

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/blob/62da3ac62fe12e09db0c8bd69996186889bd1846/modules/yahoosspBidAdapter.js#L544 as an example

**Comment by patmmccann** [comment]
@ChrisHuie could you add a pr to the bidder page to https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests to raise awareness?

**Comment by patmmccann** [comment]
@dgirardi by way of example, this fastlane request contained no preflight 

![image](https://user-images.githubusercontent.com/1683175/172201256-6c9ac798-2fe4-4f38-9ae1-ceb2ceb3b29e.png)

while these yahoo ones do

![image](https://user-images.githubusercontent.com/1683175/172201395-020cd89e-ad3d-4e4e-ae85-74c5f3425a6f.png)

**Comment by patmmccann** [comment]
@ChrisHuie any update? would love to close this out

**Comment by ChrisHuie** [comment]
> @ChrisHuie any update? would love to close this out

I will get this in this week

**Comment by bretg** [comment]
closing this - tracked now by the docs PR
