### ISSUE TITLE
Bug in integration of Google ESP and Prebid.js User ID Module

### ISSUE THREAD

**Issue by salvoaranzulla** [prebid/Prebid.js#8532]
## Type of issue

Bug

## Description

I have tried to implement the integration of Google ESP and Prebid.js User ID Module, but it doesn't work. I have created a debug page https://www.aranzulla.it/DEBUG-prebid-esp.html with this configuration:

            encryptedSignalSources: {
                "sources": [{
                    source: ['criteo.com', 'id5-sync.com', 'pubcid.org'],
                    encrypt: false
                }]
            }
            
I think that problem is here:

https://github.com/prebid/Prebid.js/blob/e6b70c9a43c5f3723ab09ae9fc14664d827032ba/modules/userId/index.js#L734

The problem is in these following lines:

  if (!isGptPubadsDefined()) {
    return;
  }

Because Prebid.js and GAM are loaded in async way, I think that condition is always false:

export function isGptPubadsDefined() {
  if (window.googletag && isFn(window.googletag.pubads) && isFn(window.googletag.pubads().getSlots)) {
    return true;
  }
}
           

## Steps to reproduce

 https://www.aranzulla.it/DEBUG-prebid-esp.html
 
## Test page

 https://www.aranzulla.it/DEBUG-prebid-esp.html

**Comment by salvoaranzulla** [comment]
@dgirardi You are right. I have found this:

https://webcache.googleusercontent.com/search?q=cache:XTA_tI-IjdMJ:https://githubmemory.com/index.php/%40smenzer+&cd=3&hl=it&ct=clnk&gl=it

I need to add pbjs.registerSignalSources(). I have also found an example: https://nitin0610.github.io/prebidtest/esp/esp.html

I think Prebid.js must update https://docs.prebid.org/dev-docs/modules/userId.html to specify it

**Comment by dgirardi** [comment]
@salvoaranzulla you are correct, that API is not documented. Opened https://github.com/prebid/prebid.github.io/issues/3830 to track.

**Comment by patmmccann** [comment]
@vkimcm fyi
