### ISSUE TITLE
Invalid builds for 7.0.0

### ISSUE THREAD

**Issue by pdamoc** [prebid/Prebid.js#8553]
## Type of issue
bug

## Description

The build system appears to produce invalid builds for 7.0.0 (and later). 

## Steps to reproduce
Download the default `prebid7.0.0.js` from https://docs.prebid.org/download.html, copy its contents and paste them in any fresh console.  You should get: 

```
Uncaught ReferenceError: pbjs is not defined
```

Alternatively, you could build the  master with the `rubiconBidAdapter` and load the resulting `prebid.js` in some test page.

## Test page

https://jsfiddle.net/h0mfgyoL/
(see console for error) 

## Platform details
My builds were done on macos `12.4` with `node` `v16.15.0` and `npm` `8.9.0`  

## Other information

I have stumbled upon this bug after doing a build where I change `globalVarName` and thought that it might have been related to that but it looks like all the builds are broken. I have tested `6.29.0` and it works fine both the default download from the website and the custom builds .

**Comment by dgirardi** [comment]
This was fixed in https://github.com/prebid/Prebid.js/pull/8549 which should release this week.
A workaround is to define `pbjs` beforehand - which will usually also happen if you load the script with `async`.
