### ISSUE TITLE
Track clicks using prebid.js

### ISSUE THREAD

**Issue by nyfer** [prebid/Prebid.js#856]
Type of issue
Track clicks using prebid.js

 Description
How can i track clicks using prebid.js for different adapters using our ad server

Steps to reproduce
--

Expected results
--

Actual results
--

Platform details
--

Other information
--

**Comment by mkendall07** [comment]
Today click tracking is not supported. 

Tracking clicks in prebid is problematic because the eventual ad is controlled by the prebid partner. Thinking about this a little bit, it might be possible to pass through the click tracking macro from the adserver to prebid and the framework could substitute a macro. This macro would need to be used by every partner to insert click tracking properly.

**Comment by mkendall07** [comment]
this a potential candidate for prebid 1.0 adapter requirements. @bretg @mjacobsonny thoughts?

**Comment by mjacobsonny** [comment]
For banner, do any Prebid demand partners want to decouple click-tracking pixels from the actual HTML creative tag?

For video, VAST provides built-in support for ClickTracking events.

I think the main use-case we need to think through here is for Prebid Native in which the click-trackers are always decoupled from the structured native assets.

**Comment by bretg** [comment]
This is a nice idea, but not seeing how it would work. My understanding of how creatives are normally entered is that there's not a way to subscribe to click events.

Instead, when the creative is entered into a DSP, the aproach is probably a simple HREF or onclick(). When the user clicks on the ad, the href/onclick would have to be correctly formatted to insert a outside click URL with the proper level of URL encoding.

Maybe there's a way to wrap the creative in an iframe, hijack clicks, log what's needed, then pass the click to the creative? Would such an approach work cross-browser with reasonable user impact and not affect access to referrer?

**Comment by mkendall07** [comment]
closing as we don't have a plan to support this
