### ISSUE TITLE
Transparent adapter and alias codes in auctionEnd events

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8568]
## Type of issue
Feature request

## Description
Third party entities using the prebid public apis eg browser extensions, publisher analytics tools, debuggers, web scrapers, and rendering libraries may often wish to know all three of the response bidder code, the adapter code, and the adapter code the adapter was aliased from. We should provide a way for these other entities to delineate all three in the auctionEnd event. One possibility is to put them in a vector where bidderCode would be of length one for normal requests, but up to length 3. Another possiblity is to bidderCode, adapterCode, origAdapterCode places in object structure. 

One alternative is we could make adapterRegistry accessible via api? 

## related
#8129

**Comment by patmmccann** [comment]
Perhaps this could be of length 4 if the publisher aliases a known alias, eg suppose bidder code in the response is 'someentity' which is a alternative code for 'tx' which is a configured alias of 'trustx' which is a known alias of 'grid' ?

**Comment by dgirardi** [comment]
I'm curious about why / how this would with `auctionEnd`? those three are properties of each bid - and `adapterCode` is already available. Only the alias resolution is missing.

Currently it's possible to do 

```
pbjs.onEvent('bidResponse', (bid) => {
   const {bidderCode, adapterCode} = bid;
})
pbjs.onEvent('auctionEnd', (auction) => {
   auction.bidsReceived.map(({bidderCode, adapterCode}) => ...)
   auction.winningBids.map(({bidderCode, adapterCode}) => ...)
})
```

is this about adding the alias resolution, or changing the arguments to the auctionEnd event?

**Comment by patmmccann** [comment]
On further inspection, analytics adapters already have this info, eg https://github.com/prebid/Prebid.js/blob/6f4fb5b78a4bc31a1f84b59ec5b98d4e3bcf0179/modules/pubmaticAnalyticsAdapter.js#L201

**Comment by patmmccann** [comment]
result of committee discussion is we plan to make adapterRegistry accessible via api; allow publishers to suppress this public api via configuration

**Comment by jlquaccia** [comment]
Hey @patmmccann, I was thinking of taking this gh issue on next.  To clarify, it sounds like the req's for this ticket would be something like the following (let me know if im off, which i might be):

- create an adapterRegistry (just like bidderRegistry & aliasRegistry here: https://github.com/prebid/Prebid.js/blob/master/src/adapterManager.js#L47)
- as the pbjs init logic runs, keep track of/populate the adapterRegistry obj like so.. { adapter1: { bidderCode, adapterCode, alias }, adapter2: { bidderCode, adapterCode, alias } }
- create a global config option to enable/disable the adapterRegistry feature. ex: pbjs.setConfig({ adapterRegistry: true })
- if adapterRegistry is set to true, then allow this info to be available within the getProperties func during the auctionEnd event (https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L159)

**Comment by patmmccann** [comment]
@jlquaccia I think it is much simpler than that; I think we might just need to make the existing aliasRegistry public? The auctionEnd event seemed to be an alternative to it being public and committee discussion seemed to favor not messing with auctionEnd.

**Comment by patmmccann** [comment]
Very excited you might take this one on, thanks!

**Comment by jlquaccia** [comment]
@patmmccann ah, ok gotcha, that does sounds a bit more simple!  Will create a new PR shortly around this one.
