### ISSUE TITLE
Emit event when targeting is sent to DFP (setTargetingForGPTAsync)

### ISSUE THREAD

**Issue by itayo155** [prebid/Prebid.js#858]
## Type of issue
feature request

## Description
Currently, there's no reliable way to know when an auction has actually ended, i.e. the point after which no bids would participate in the auction.
The existing AUCTION_END event is, in many cases, unreliable for this use because most setups do not use prebid's timeout field for ending the auction - they use external setTimeout instead, and/or are calling setTargetingForGPTAsync directly.

The suggestion is to emit a new event ("SET_TARGETING_CALLED") when setTargetingForGPTAsync is called. This indicates that all bids have been collected and actually sent away.
Of course, there are some implementations in which this function is never called/ is not a reliable indicator, however it should work in the vast majority of cases.

This event would be useful for bidders, allowing them to optimize response times, which in turn would maximize bid-rate for publishers. 
Since the event would contain no sensitive information regarding the auction itself or its result, it should be ok for access by bidders.

## Other information
Related: 
https://github.com/prebid/Prebid.js/issues/494 - details the current conditions for emitting AUCTION_END

**Comment by itayo155** [comment]
Following up - any comments here? would be happy to submit a PR if this makes sense.

**Comment by protonate** [comment]
@itayo155 PRs are always welcome, thanks.

**Comment by matthewlane** [comment]
Closing with #873 now in master
