### ISSUE TITLE
gulp build/test failing on Mac OS

### ISSUE THREAD

**Issue by shahinrahbariasl** [prebid/Prebid.js#8588]
## Type of issue
bug

## Description
Have been running into issues with gulp build/test after rebasing on latest master branch:
```
shahinrahbariasl-MacBook-Pro:prebid.js shahin.rahbariasl$ gulp test
Error: Cannot find module './index.js'
Require stack:
- /Users/shahin.rahbariasl/Desktop/IX/prebid.js/gulpHelpers.js
- /Users/shahin.rahbariasl/Desktop/IX/prebid.js/webpack.conf.js
- /Users/shahin.rahbariasl/Desktop/IX/prebid.js/gulpfile.js
- /usr/local/lib/node_modules/gulp-cli/lib/shared/require-or-import.js
- /usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
- /usr/local/lib/node_modules/gulp-cli/index.js
- /usr/local/lib/node_modules/gulp-cli/bin/gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.resolve (internal/modules/cjs/helpers.js:21:19)
    at /Users/shahin.rahbariasl/Desktop/IX/prebid.js/gulpHelpers.js:94:53
    at Array.map (<anonymous>)
    at Object.getLibraryFiles (/Users/shahin.rahbariasl/Desktop/IX/prebid.js/gulpHelpers.js:94:33)
    at /Users/shahin.rahbariasl/Desktop/IX/prebid.js/webpack.conf.js:48:40
    at Array.forEach (<anonymous>)
    at /Users/shahin.rahbariasl/Desktop/IX/prebid.js/webpack.conf.js:40:42
    at Object.<anonymous> (/Users/shahin.rahbariasl/Desktop/IX/prebid.js/webpack.conf.js:61:5)
    at Module._compile (internal/modules/cjs/loader.js:759:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/shahin.rahbariasl/Desktop/IX/prebid.js/gulpHelpers.js',
    '/Users/shahin.rahbariasl/Desktop/IX/prebid.js/webpack.conf.js',
    '/Users/shahin.rahbariasl/Desktop/IX/prebid.js/gulpfile.js',
    '/usr/local/lib/node_modules/gulp-cli/lib/shared/require-or-import.js',
    '/usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js',
    '/usr/local/lib/node_modules/gulp-cli/index.js',
    '/usr/local/lib/node_modules/gulp-cli/bin/gulp.js'
  ]
}
```
Looks like the error is coming from [gulpHelpers](https://github.com/prebid/Prebid.js/blob/master/gulpHelpers.js#L111). Not sure if there's a conflict with other index.js files or not but might be related to recent changes in #8527 ?

## Steps to reproduce
On Mac OS:
1. clone master branch
2. run `gulp build` or `gulp test`3. 

Workaround was to change `index.js` in line [111](https://github.com/prebid/Prebid.js/blob/master/gulpHelpers.js#L111) to anything other than `index`.

## Test page

![Screen Shot 2022-06-20 at 7 21 22 PM](https://user-images.githubusercontent.com/56240400/174688182-72929ac1-407e-4238-b888-e98f3c5f2b86.png)
.

![Screen Shot 2022-06-20 at 7 24 24 PM](https://user-images.githubusercontent.com/56240400/174688373-acbc3d8d-0b84-46a4-871e-e98ad16ffdc2.png)

### Expected results
gulp build/test should work after npm install regardless of OS.

### Actual results
gulp buld/test fails in Mac OS.

## Platform details
- Mac OS Monterey
- Latest Prebid.js

**Comment by ChrisHuie** [comment]
@shahinrahbariasl  Both seemed to work for me on Mac OS. What version of Node are you running? I know we had a similar issue with an older node version on packages being installed in the wrong place because of a similar situation and update. I'm on v16.13

**Comment by shahinrahbariasl** [comment]
Hey @ChrisHuie , hmm interesting, I'm on `v12.0.0`. I can try upgrading but didn't have this issue till yesterday that I rebased. My guess is also that some naming conflicting is happening.

**Comment by ChrisHuie** [comment]
> Hey @ChrisHuie , hmm interesting, I'm on `v12.0.0`. I can try upgrading but didn't have this issue till yesterday that I rebased. My guess is also that some naming conflict is happening.

Yeah. Let me dig into a bit more because the issue I was talking about I don't think it applies here. It had been a while sincee it popped up (https://github.com/prebid/Prebid.js/pull/7689)

**Comment by shahinrahbariasl** [comment]
@dgirardi yup, that works!
