### ISSUE TITLE
setTargetingForGPTAsync is missing adUnitCodes parameter

### ISSUE THREAD

**Issue by mthazin** [prebid/Prebid.js#860]
## Type of issue
setTargetingForGPTAsync function is setting key-values for all slots on the page instead of specific adUnitCodes that were passed into the function as parameter

## Description
We are currently running prebid v0.15.2 and i believe this issue has been existed since v0.9.1. 

We have infinite scrolling and we append ad unit to the page as user scrolls down. We call setTargetingForGPTAsync to set targeting to DFP for the new slot.

But, setTargetingForGPTAsync function is no longer accepting AdUnitCodes parameter and it caused setting targeting for all slots to DFP on ad refreshes.

Prebid API documentation mentioned that setTargeingForGPTAsync can be used as follows:    pbjs.setTargetingForGPTAsync([codeArr])

But in the actual implementation in prebid.js, setTargetingForGPTAsync is missing codeArr parameters. 
$$PREBID_GLOBAL$$.setTargetingForGPTAsync = function () {}

The actual issues is coming from adUnitCodes parameter missing in getWinningBidTargeting() and getDealTargeting() functions. 

## Steps to reproduce
e.g., 

make a function call: pbjs.setTargetingForGPTAsync(['div-gpt-ad-13']);

### Expected results
Expected to set Targeting key values to DFP only for div-gpt-ad-13

### Actual results
![image](https://cloud.githubusercontent.com/assets/14005076/20935354/5c9bcd26-bbac-11e6-9e34-5530fe8abc3a.png)

**Comment by littlecuteflower** [comment]
Any status on this? Thanks.

**Comment by mthazin** [comment]
Just wanted to follow up on this to see if there's anyone looking into this issue. Thanks.

**Comment by protonate** [comment]
Yes I'll be looking at this today, thanks for your patience.

**Comment by mthazin** [comment]
Thank you!

**Comment by dmitriyshashkin** [comment]
I'm having the same issue

**Comment by mkendall07** [comment]
This does appear still to be an issue. We accept PRs :)

**Comment by matthewlane** [comment]
`setTargetingForGPTAsync` now takes an `adUnitCodes` parameter with #1158
