### ISSUE TITLE
Question - Prebid v6 to v7 

### ISSUE THREAD

**Issue by nicosapp** [prebid/Prebid.js#8628]
## Type of issue
Question

## Description
We update the prebid script from 6.X to 7.X and we notice a different behaviour in the execution of our script. We had to modify it to make it works as before.

### Code version 6
```js
let ads = [...]
pbjs.setConfig(config);
pbjs.bidderSettings = settings;
pbjs.addAdUnits(getAdUnits(ads));

pbjs.requestBids({
        bidsBackHandler: () => {
            googletag.cmd.push(() => {
                pbjs.que.push(() => {
                    pbjs.setTargetingForGPTAsync();
                    this.loadAds(ads);
                });
            });
        }
    });

ads.forEach((ad) => {
      pbjs.removeAdUnit(ad.tagId);
  });
```
We use this code with version 6 and `requestBids` was executing before `removeAdUnits`
In version 7 `removeAdUnits` is executing before `requestBids`, so no bids are sent. I had to wrap the `removeAdUnit` with a `setTimeout` to make the `requestBids` call before the `removeAdUnits` call.

### Code version 7
```js
let ads = [...]
pbjs.setConfig(config);
pbjs.bidderSettings = settings;
pbjs.addAdUnits(getAdUnits(ads));

pbjs.requestBids({
        bidsBackHandler: () => {
            googletag.cmd.push(() => {
                pbjs.que.push(() => {
                    pbjs.setTargetingForGPTAsync();
                    this.loadAds(ads);
                });
            });
        }
    });
setTimeout(() => {
  ads.forEach((ad) => {
        pbjs.removeAdUnit(ad.tagId);
    });
}, 0)
```

## Platform details
Prebid version (old: 'v6.16.0', new v7.3.0)
Node version: v16.14.2
Npm version: 8.5
Linux, Ubuntu 20.04

**Comment by dgirardi** [comment]
My suggestion is to use `requestBids`' [`adUnits` parameter](https://docs.prebid.org/dev-docs/publisher-api-reference/requestBids.html), which will sidestep this problem entirely:

```
pbjs.requestBids({
  adUnits: getAdUnits(ads)
})
```

I don't believe this was a change in 7, but rather one of the several updates to GDPR and/or userId that were brought in after 6.16. [this PR](https://github.com/prebid/Prebid.js/pull/8626) will _probably_ bring the old behavior back. But I agree with @bovidiu that in general it's better to not call `addAdUnits` / `removeAdUnits` while an auction is running; even in 6.16, that could behave differently depending on configuration (if you set for example a  `userSync.auctionDelay` greater than zero, or I believe even just including some RTD modules).

We should update documentation about this. It may be worth it to also change requestBids to "freeze" the adUnits at the time it's called.
