### ISSUE TITLE
Feature Request: Send bidRequested event when unknown Bidder responses occur

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#8629]
## Type of issue: feature request

Sent `bidRequest` events for unknown bidder codes returned by prebid server so analytics adapters like Pubstack keep working on client-side.

## Description

#8154 introduced the `allowUnknownBidderCodes`´setting, which makes the workaround described in #7027 obsolete. However this initial implementation comes [with some drawbacks](https://docs.prebid.org/dev-docs/modules/prebidServer.html#allowUnknownBidderCodes) most importantly that there is no `bidRequest` event sent.

This makes sense as there's no information on the client side which bidders may have been requested on the server side. Maybe there is a possibility to sent those events at a later point. The wokraround from #7027 is sufficient enough to make the our analytics adapter function properly again. 

Two options could be

- sent `bidRequest` events for all bidders defined in the `s2sCfonfig.bidders` array
- prebid server respondes with a list of bidders that have been requested for each `imp`, wich the will be turned into `bidRequest` events

## Platform details

Prebid 6.x & 7.x

## Other information

- [prebidServer docs](https://docs.prebid.org/dev-docs/modules/prebidServer.html)

**Comment by dgirardi** [comment]
I think I disagree - generating fake bidRequest events might work for some scenarios, but it's bound to break others. After all the bid was _not_ requested. To me this sounds like your analytics should be looking at bidResponse instead.

A better workaround, IMO, would be a mechanism that generate fake events for particular analytics adapters only, maybe as a flag in `enableAnalytics`.

**Comment by muuki88** [comment]
Thanks @dgirardi . I agree with your statement. IMHO this should be handled via a server side analytics adapter. With #7585 this should be possible through the `auctionId` being available server and client side.

I opened this issue as server side analytics is still in a very early stage and server side adoption is slowly growing. We still need to configure our ad tags if we want to add new adapters server-side, which is one huge benefits of doing server-side at all.

**Comment by gpolaert** [comment]
Hello @muuki88 and @dgirardi 

Thanks for raising this issue. 

I completely agree with the fact that the adapters (and the Pubstack one) need to handle the new option `allowUnknownBidderCodes` and stored impressions without generating fake bidRequested events. 

@muuki88 I still have no ETA regarding the support of this issue in Pubstack, I will keep you informed as soon as I have any news

**Comment by patmmccann** [comment]
It seems we should add extra information to the response rather than create 'fake' events. This should allow analytics adapters to generate things like bid rate and timeout rate for these unknown bidders.

**Comment by robertrmartinez** [comment]
I believe we can close this. We decided adding a bid request event in these sort of scenarios is too hairy and not worth the lift. Instead, where applicable extra info will be added onto the bidResponse so analytics adapters can do what they wish

Please reopen if I am mistaken
