### ISSUE TITLE
gulp build doesn't build the devpack

### ISSUE THREAD

**Issue by kasparsd** [prebid/Prebid.js#863]
The [README mentions](https://github.com/prebid/Prebid.js/blame/31b6fbe302db5f69f025a00f19bb69ffeac41bc4/README.md#L42) that running `gulp build` should create both the dev and dist version of the script. However, only the dist version is created because `devpack` task was removed from the `build` task https://github.com/prebid/Prebid.js/commit/5f5e9411657534715d310d17dc4ce8427a0dde1c.

**Comment by mkendall07** [comment]
We'll update the readme. Thanks for pointing it out.
