### ISSUE TITLE
Shared Id Module not working with GDPR Enforcement module and prebid 7.

### ISSUE THREAD

**Issue by newspassid-prebid** [prebid/Prebid.js#8647]
## Type of issue
Bug 

## Description
Shared Id Module not working with GDPR Enforcement module and prebid 7.

I'm working on some adapter updates for the ozone project and was reviewing some tests page I had created when I noticed the shared ID module isn't working / being set when used in conjunction with the GDPR Enforcement module and prebid 7 within the EU.

It looks like the GVLID for the sharedId module has been removed from its code in the 

## Steps to reproduce
(1) I've tried to use the shared ID and user ID modules with the latest prebid 7 code, GDPR Module and GDPR Enforcement module.
(2) Hit a page from within the EU using these modules - you'll notice shared ID isn't getting set.

## Test page
Below are test pages that use the GDPR module and don't use the GDPR module.
Also makes no difference if you use local storage or cookie - but wanted to confirm that.

https://www.ardm.io/ozone/2.7.2/3-adslots-ozone-testpage-20220629-localstorage.html?pbjs_debug=true
https://www.ardm.io/ozone/2.7.2/3-adslots-ozone-testpage-20220629-cookie.html?pbjs_debug=true
https://www.ardm.io/ozone/2.7.2/3-adslots-ozone-testpage-20220629-localstorage-nogdpr.html?pbjs_debug=true
https://www.ardm.io/ozone/2.7.2/3-adslots-ozone-testpage-20220629-cookie-nogdpr.html?pbjs_debug=true

### Expected results

Expect to see pubcid/shared ID in user object on all 4 pages. 

### Actual results

Expect to see pubcid/shared ID in user object on all 4 pages. You'll notice the first 2 pages which use GDPR enforcement fail.

## Platform details
All

## Other information
Pre-prebid 7 - the shared ID module included this snippet/line of code with the GVLID:
![image](https://user-images.githubusercontent.com/107485317/177377166-fb59930e-9a74-4920-94d5-44eddcd5eaa6.png)

post prebid7 - this looks to have been updated/removed:
![image](https://user-images.githubusercontent.com/107485317/177377125-2df61d86-3f34-42b2-bfc1-b3973208458f.png)

I don't know if the removal of `const GVLID = 887` was intentional or not as part of prebid 7 but the GDPR enforcement module us trying to check the sharedIDs consent and look for a GVLID and doesn't find one so omits using it.

**Comment by patmmccann** [comment]
This was intentional in #8448 

Shared id is set by the pub, not prebid.org

**Comment by newspassid-prebid** [comment]
thanks - if you check out the test page I put - I believe that has the latest code pulled last Tuesday - the enforcement module seems to be checking / looking for a GVLID still ?

Am I missing something on my side or is this a bug then as it doesn't sound like its intended behaviour ?

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/pull/8661
