### ISSUE TITLE
Error in PulsePoint adapter if third party window.pp defined

### ISSUE THREAD

**Issue by PsychodelEKS** [prebid/Prebid.js#866]
## Type of issue
Bug

## Description
If global variable window.pp is defined on page, PulsePoint adapter thinks it's their object and try to use, that causes error, that blocks working of other adapters also (bids not sent).

## Steps to reproduce
1. build prebid with puslepoint support
2. configure placement and pulsepoint bidder for it
3. create global variable ```window.pp = {myMethod: function(){}};``` on page
4. try to bid placement in pulsepoint

### Expected results
Bid request is sent

### Actual results
Error happens:
prebid.js: Error processing command :" TypeError: Cannot read property 'BID' of undefined

## Platform details
latest pulsepoint adapter, prebid version does not matter

## Other information
Code which causes error:
```
if (typeof window.pp === 'undefined') {
      adloader.loadScript(getJsStaticUrl, function () { bid(params); }, true);
    } else {
      bid(params);
    }
```

Live problem was observed with WordPress Press+ plugin (in s.ppjol.net/pp.js), which initializes window.pp
There must be some protection to catch the issue and use different variable name, as `pp` may be quite common.

**Comment by anand-venkatraman** [comment]
Thank you for bringing up this issue. 
I am a developer with PulsePoint.
We will provide you with a fix shortly.

**Comment by anand-venkatraman** [comment]
Submitted a [PR](https://github.com/prebid/Prebid.js/pull/867) for gracefully handling error when a call is made to our Adapter and it fails. 
However, I understand this fix does not fully address your problem.
We will submit a "lite" PulsePoint adapter next week, that will not rely on any library loads or global scoped variables.

**Comment by PsychodelEKS** [comment]
I think your primary code (that creates and manages pp variable) can create shadow copy of it in global namespace with random name, in case rewritten, and respond with this global name to some specially formed postMessage, so you can always get your global even if its rewritten and not available as window.pp

Or just use some more unique global name =)

**Comment by PsychodelEKS** [comment]
Anand, the issue still persists in the latest version I compiled =( I tried reaching you on facebook for additional info and realtime communication.

**Comment by anand-venkatraman** [comment]
Can you setup a test page and let me know. You can reach me at avenkatraman@pulsepoint.com

**Comment by PsychodelEKS** [comment]
Graceful behavior confirmed on the latest pb build - auction is not stopped if the error occurs.
