### ISSUE TITLE
bid adapters: support standard first party data keywords

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#8660]
## Type of issue
conforming to standards

## Description
While reviewing a documentation PR from (@gchicoye), I noticed that the nexx360 is accepting a 'keywords' parameter and doesn't look for them in ortb2.site.keywords.

It's not acceptable for publishers to have to pass adapters special first party data -- rather, they should be able to set [standard FPD keywords](https://docs.prebid.org/features/firstPartyData.html) and all adapters must read from that conventional location. It's acceptable to support **both** custom params as well as the conventional location.

Adapters that need to be checked and possibly updated:

- [x] Nexx360
- [x] Appnexus

@ChrisHuie found these additional bidders that need to look into this:

- [ ] Craft Bid Adapter
- [ ] Winr Bid Adapter
- [ ] Pixfuture Bid Adapter
- [ ] Mediafuse Bid Adapter
- [ ] Beop Bid Adapter
- [ ] Displayio Bid Adapter
- [ ] Prisma Bid Adapter
- [ ] Ras Bid Adapter
- [ ] Goldbach Bid Adapter
- [ ] Deepintent Bid Adapter
- [ ] Sonobi Bid Adapter

**Comment by patmmccann** [comment]
@bretg does this apply to Xandr adapter?

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/blob/15b688c9a4f15a7669fd1fa579f9c76e1a917949/modules/appnexusBidAdapter.js#L846

**Comment by bretg** [comment]
It applies to all bidders. @jsnellbaker - please take a look at the appnexus bid adapter to make sure keywords can come from ortb2 and not just bidder-specific params. Thanks!

**Comment by jsnellbaker** [comment]
To clarify the intent/context, when a publisher specifies ortb2 keywords - they intend to have them apply to all adUnits that were part of the setup?  It's not a selective thing per adUnit?

I figure it's the former, but I just want to check in case there are other possible use-cases within the ortb2 setup.

**Comment by bretg** [comment]
Not clear imp-level keywords is a real use-case, but if it is, seems like AdUnit.ortb2Imp.ext.data.keywords would be the right location.

ORTB specifies site.keywords, app.keywords, user.keywords, and site.content.keywords -- those should be set with setConfig({ortb2}).

**Comment by jsnellbaker** [comment]
Hi @bretg 

Thanks for the feedback.  We will take a look into these changes for our next sprint.

**Comment by patmmccann** [comment]
@jsnellbaker this is complete on your side right?

**Comment by jsnellbaker** [comment]
There are some gaps in the bidViewability and dfpAdServerVideo.js files on how to pass the GPP data over query params.  I was also hoping to get confirmation/sign-off on how I put together the data for the PBS userSync.  

These areas could be updated later when information is confirmed for all of the respective endpoints.  Otherwise, it should be ready to go from my end.

**Comment by jsnellbaker** [comment]
Yes from what I understand, this should be complete from our end.

**Comment by ChrisHuie** [comment]
**_Bid Adapters that don't currently support passing keywords to ortb2.site or ortb2.user_**

Craft Bid Adapter
Winr Bid Adapter
Pixfuture Bid Adapter
Mediafuse Bid Adapter
Beop Bid Adapter
Displayio Bid Adapter
Prisma Bid Adapter
Ras Bid Adapter
Goldbach Bid Adapter
Deepintent Bid Adapter



_**Bid Adapters that support passing meta keywords but not first party data keywords**_

Biink Bid Adapter
Adkernel Adn Bid Adapter
The Adx Bid Adapter
Jixie Bid Adapter
Datablocks Bid Adapter

**Comment by bretg** [comment]
This is a possible item for PBJS 8.

> Bid Adapters that support passing meta keywords but not first party data keywords

Agree with this. Now that the FPD enrichment is part of core, these adapters should be retrieving meta keywords from core.
