### ISSUE TITLE
a problem about npm build failed

### ISSUE THREAD

**Issue by fengsuxing** [prebid/Prebid.js#868]
when npm build, below happens:
(i guess:wrong karma version?bigger then gulp-karma@0.0.4 needed)

Writing location.js file
Done. Phantomjs binary available at /home/fengsu/Prebid.js/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer gulp-karma@0.0.4 wants karma@>=0.10 <=0.13
npm ERR! peerinvalid Peer karma-browserstack-launcher@1.1.1 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-chai@0.1.0 wants karma@>=0.10.9
npm ERR! peerinvalid Peer karma-coverage@0.2.7 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-html-reporter@0.2.7 wants karma@>=0.11
npm ERR! peerinvalid Peer karma-ie-launcher@0.1.5 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-junit-reporter@0.3.8 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-opera-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.2.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.6 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-safari-launcher@0.1.1 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-sinon-ie@2.0.0 wants karma@>=0.10

npm ERR! System Linux 2.6.32-431.11.15.el6.ucloud.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/fengsu/Prebid.js
npm ERR! node -v v7.2.1
npm ERR! npm -v 1.3.6
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/fengsu/Prebid.js/npm-debug.log
npm ERR! not ok code 0

**Comment by fengsuxing** [comment]
i change the karma version in package.json to 0.12,and npm build successed,but when  gulp build,still have problem.
is it right to change verison to fix the npm build problem?

**Comment by protonate** [comment]
Yes that should be fine. Did you run `npm install` before `gulp build`? And what errors do you get now?

**Comment by fengsuxing** [comment]
thanks  for answering me.someone helped me solved this problem offline
