### ISSUE TITLE
ix bidder issues a false warning for all display units

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#8687]
## Type of issue
Bug

## Description
When ix bid adapter tries to validate the bid params for a display unit it issues a false warning about an improper placement of the video params.

The problem is as I see it is that the bidToVideoImp function is being called regardless of the actual media type. https://github.com/prebid/Prebid.js/blob/master/modules/ixBidAdapter.js#L1622

## Steps to reproduce
1. Create a display unit with ix bidder
2. request bids

## Test page
https://notsy.io/ix_demo.html

### Expected results
No warnings are issued

### Actual results
The following warning is issued: IX Bid Adapter: mediaTypes.video is the preferred location for video params in ad unit

## Platform details
Prebid 7.5.0, npm 15

**Comment by lksharma** [comment]
@dmitriyshashkin this issue has been addressed in [https://github.com/prebid/Prebid.js/pull/8698](8698)
