### ISSUE TITLE
Facebook Instant Articles Support

### ISSUE THREAD

**Issue by pribeh** [prebid/Prebid.js#869]
Thanks for your wonderful work on prebid – it really is amazing. I was the guy to originally bug you about Google AMP support which is now amazingly included in prebid and well documented - thank you again! I was wondering if any of you would know if it would be at all possible to modify the same process to support Facebook Instant Articles(?).

https://developers.facebook.com/docs/instant-articles

Thanks!

**Comment by protonate** [comment]
Glad to hear it, thanks. 

Facebook Instant Articles are on the roadmap, and we'll use this as the tracking Issue for the feature.

**Comment by pribeh** [comment]
Thanks @protonate !

**Comment by mkendall07** [comment]
Not on the roadmap.
