### ISSUE TITLE
Question: Auctions being canceled as per consentManagement

### ISSUE THREAD

**Issue by tiago-snigel** [prebid/Prebid.js#8692]
## Type of issue
Bug

## Description
If we we have the consent management module and a timeout occurs in the consent or we only have a stub, the auction proceeds with no consent defined. 
But if we have no __tcfapi(), the auctions are canceled, which is not the ideal scenario.

## Steps to reproduce
Having the consent management module in prebid.js and not having a valid __tcfapi() in place results in the cancellment of all auctions.
This can be fixed if the module is not available, or if a timeout occurs in the consent, or if we use a stub.

### Expected results
If there is no consent in place and the enforcement module is not part of prebid, the auctions should occur even without any consent.

### Actual results
The auctions are canceled.
![image-20220712-142353](https://user-images.githubusercontent.com/57620436/179204345-e4662d02-1d19-4ada-aed0-9e4c75739662.png)

**Comment by dgirardi** [comment]
Relevant excerpts from the [TCF spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#details-for-vendors):

> A CMP-provided synchronous "stub" script must be added by the publisher to their page before any other scripts that rely on __tcfapi (this usually means between the `<head></head>` tags of the HTML document).

> Scripts can check for the presence of a function named __tcfapi [...] If a CMP is not present, or if the CMP fails to respond, vendors should assume "no consent" and “no legitimate interest transparency established” in contexts where GDPR applies

Prebid could decide to continue the auction assuming no consent, but that should result in either gdprEnforcement stopping it (if configured) or downstream SSPs refusing to bid without consent.

**Comment by tiago-snigel** [comment]
> Why would you ever have no __tcfapi ? If the answer is gdpr does not apply, you don't need to configure the module. If gdpr does apply, you are on dangerous ground not including a stub.


This can happen when we have someone detecting on their end if it's a gdpr zone or not and doesn't deploy the stub when oustide of EEA. And since we don't have this information beforehand the moduleis part of prebid.js.



> Relevant excerpts from the [TCF spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#details-for-vendors):
> 
> > A CMP-provided synchronous "stub" script must be added by the publisher to their page before any other scripts that rely on __tcfapi (this usually means between the `<head></head>` tags of the HTML document).
> 
> > Scripts can check for the presence of a function named __tcfapi [...] If a CMP is not present, or if the CMP fails to respond, vendors should assume "no consent" and “no legitimate interest transparency established” in contexts where GDPR applies
> 
> Prebid could decide to continue the auction assuming no consent, but that should result in either gdprEnforcement stopping it (if configured) or downstream SSPs refusing to bid without consent.


Totally agree with this, when there is a gdprEnforcement which we are using in certain situations, the auction should be stopped, but otherwise it should be the SSPs decision if they want to bid or not.

**Comment by patmmccann** [comment]
>This can happen when we have someone detecting on their end if it's a gdpr zone or not and doesn't deploy the stub when oustide of EEA. And since we don't have this information beforehand the moduleis part of prebid.js.

I don't understand how you can conditionally deploy the stub but not be capable of conditionally deploying the module configuration.

**Comment by tiago-snigel** [comment]
> I don't understand how you can conditionally deploy the stub but not be capable of conditionally deploying the module configuration.

Thank you very much @patmmccann but I  believe that there is a misunderstand as we can't compare both.
The module is part of prebid build, it's not dynamic, the only way to make it dynamic is by using different builds, while the stub can easily be loaded or not, and on this case not even by us but another company hired by the pulisher, it's a dependency but not dependent of anything, and having external companies handling the CMP solution is something very common nowadays.

When working with multiple products and companies, synchronizing all the product is almost near impossible, some of the CMP products in the market like cookiepro by OneTrust are actually doing this, and that’s not something we can force to change in any way.

Finally there is also the fact that there is something odd in the current way of working, having no stub forces the auction to be canceled, but if a timeout occurs everything proceeds as if nothing. Canceling the auction when there is no stub in place should be optional.

**Comment by patmmccann** [comment]
>  the only way to make it dynamic is by using different builds,

you can build with it everywhere but only configure it in eurozone

**Comment by patmmccann** [comment]
If you are out of the eurozone but it is in your build, all this config governs, you can disable enforcement

![image](https://user-images.githubusercontent.com/1683175/180466956-443f4638-d70a-4787-8259-11d971a414c1.png)
