### ISSUE TITLE
Yieldbot adaptive behavior

### ISSUE THREAD

**Issue by combs** [prebid/Prebid.js#872]
## Type of issue

Feature request for Yieldbot adapter

## Description

hello! I am told by Yieldbot that they require adaptive behavior for desktop vs mobile ad units. We have a responsive site and use Prebid size mapping, but they say that we should only define bids for desktop or for mobile:

> It looks like you are defining all of the slots all at once. It's recommended that you have a function determine whether the page is being loaded from desktop or mobile and define the appropriate ad slot accordingly. At the moment, when I view your test page I only see our bid being returned to the `mobile_REC` slot, but it should be a desktop slot.

Could this trickery be handled in the Prebid adapter for Yieldbot instead?
 
## Steps to reproduce

Define Yieldbot units for desktop and mobile. Define Prebid responsive size mapping. 

### Expected results

Client should, according to Yieldbot, only submit bids for desktop or mobile ad units, not both (as determined by slot IDs, `mobile_X` or `desktop_X`

### Actual results

Prebid is submitting `mobile_X` or `desktop_X` bid requests based on browser width in size mapping

## Platform details

0.16.1-pre

## Other information

Maybe this should just be handled on Yieldbot's side. I don't understand why it needs to be adaptive—we should be able to just request a size.

**Comment by mkendall07** [comment]
Sounds like a nice feature. We accept PRs :) 
I would say ideally it would be implemented in the core, so any adapter could utilize it.

**Comment by mkendall07** [comment]
I think our new sizemapping and labels feature will support this now:
http://prebid.org/dev-docs/prebid-1.0-API.html#size-mapping-changes
