### ISSUE TITLE
Single Request Architecture

### ISSUE THREAD

**Issue by sinuhepop** [prebid/Prebid.js#874]
## Type of issue
Feature request

## Description
Is there any plan for implementing SRA (Single Request Architecture)? At the moment, if a page contains 6 slots and we want to auction them between 4 bidders, we need to make 24 concurrent requests. With SRA, only 4 calls will be needed. 

This has two main advantatges:

- Optimization. Not only header bidding should be faster, but the rest of elements in the page could be downloaded faster, as more download threads would be free.
- Tandem ads. So, a provider could bid for a slot group in order to show related ads

And some complications:
- Obviously, bidders must agree accepting SRA. But it's not mandatory. prebid.js could use SRA when available and multi request when not. Publishers may decide to work only with ones implementing SRA.
- Algorithm for maximizing profit must be more complicated, taking into account slot group bids.

I always thought that SRA should be the default option, and I supposed that there were some important reasons why it isn't. But it seems that other wrappers [are already doing this](https://www.admonsters.com/blog/how-wrapper-won-header-conversation-index-exchange), so I'm wondering if it will be available on prebid.js in the future.

**Comment by mkendall07** [comment]
@sinuhepop 
Yes ideally everyone would support this, but some do not. I don't have the data readily available but I would guess more than 50% of demand partners do not support SRA. 

We have plans on building an optimized version of prebid (prebid 1.0.0) that will have a requirement to be SRA. We should have an intent to implement before the end of the year. Thanks

**Comment by sinuhepop** [comment]
Sounds good. Thanks.

**Comment by bboigienman** [comment]
Happy new year !
@mkendall07 end of year is now behind us, do you have any news about SRA availability ?

Thx
