### ISSUE TITLE
ORTB Native refinements

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#8764]
## Type of issue
enhancement

## Description
While updating the ORTB native docs, generated a list of proposed changes/enhancements:

### 1. Validate Asset IDs

ORTB requires asset IDs, but this is mainly for linking response assets to the request assets. At one point we discussed having PBJS fill in missing asset IDs, but this has been considered problematic. Instead, PBJs should validate the asset ID:

If the asset ID doesn't exist or the assetID is negative, console log an error and remove this adunit from the auction.

### 2. Remove the sendTargetingKeys flag

This is the old option that tells Prebid to send all the hb_native KVPs to the adserver. That shouldn't happen anymore now that we have better ways to transmit the asset data at render time.

Proposal:
1. if both sendTargetingKeys and ortb are specified in adunit.mediatypes.native, it's a major error. (do we cancel the whole auction or just the adunit when there's an error like this?)
2. when ortb is specified, treat sendTargetingKeys as false.

### 3. Error if Native "types" are specified

'Type' is a sort of 'macro' introduced in an early version of PBJS that expands to a set of assets. This is Prebid-only behavior meant to be friendly, but doesn't fit well with the ORTB approach. A “type” is like a macro that defines a group of assets. The only value supported is ‘image’, which implies the following assets: image, title, sponsoredBy, clickUrl, body, icon, and cta. The first 4 are required attributes.

Proposal:
if both 'types' and 'ortb' are specified in adunit.mediatypes.native, console log an error and remove this adunit from the auction.

Heads up @muuki88 , @patmmccann , @dgirardi

**Comment by patmmccann** [comment]
I think it is fair to sever 4 from this and continue to track on #6695

**Comment by bretg** [comment]
Ok, removed the 4th item.

**Comment by musikele** [comment]
Hi @bretg ,
regarding point n.1, Asset IDs are also used in templates to specify the assets (for example, `##hb_native_asset_id_1##`). When using ORTB assets, only the publisher knows what ID is associated with titles, images, or data. So, if we auto-generate them, or if we make this link implicit, we'll loose this connection between the request assets and the template. 

No problem in checking that it's a positive number.

**Comment by lcorrigall** [comment]
PMC: Agree on 1, implement it. for 2 and 3, mark these features as deprecated and log a message to the console if they are used.

**Comment by dgirardi** [comment]
closed with [11481](https://github.com/prebid/Prebid.js/pull/11481)
