### ISSUE TITLE
Need to generate unique impression ID

### ISSUE THREAD

**Issue by pierre-nicolas** [prebid/Prebid.js#877]
## Type of issue
Feature request

## Description
As a buyer integrated with several adaptors, I want to be able to know when the same impression is being offered by two or more of them. This can be done by generating a unique impression ID in prebid.js and then distributing it through adaptors and their own integrations.

Note that OpenRTB has already introduced the notion of "source" in [its 2.5 version](https://www.iab.com/guidelines/real-time-bidding-rtb-project/), and in particular a "tid" field to relay this impression identifier.

**Comment by cotarmanach** [comment]
+1

**Comment by pieroxy** [comment]
+1

**Comment by BenjaminCh** [comment]
+1

**Comment by mkendall07** [comment]
We do have an impression ID already, I don't think anyone is actively using to to present to the buyer. (it might be included in some of the OpenRTB complaint bidders). Your best bet would be to initiate conversations with those demand partners to see how they can include it. 

For reference, this would be the `bid.bidId` that gets passed through when `callBids()` function is invoked on each adapter. Here's an example of Sovrn using it: https://github.com/prebid/Prebid.js/blob/master/src/adapters/sovrn.js#L47

**Comment by Swiiip** [comment]
The bidRequest.requestId is shared accross all bidRequests on all adUnits Is there a unique ID shared between all bidRequests for a given adUnit ?

**Comment by mkendall07** [comment]
> Is there a unique ID shared between all bidRequests for a given adUnit ?
Currently no. We can add one though. This should be added into the [1.0.0 proposal ](https://github.com/prebid/Prebid.js/issues/891)

**Comment by mkendall07** [comment]
Will implement as part of https://github.com/prebid/Prebid.js/issues/891
