### ISSUE TITLE
Increase of timeouts when using userId modules, since 6.20.0

### ISSUE THREAD

**Issue by JulieLorin** [prebid/Prebid.js#8770]
## Type of issue
This is a bug/regression

## Description
We have noticed that we have an increase of timeouts when using a userID module (like criteoIdSystem), since 6.20.0 
I think this is linked to : https://github.com/prebid/Prebid.js/pull/8201/files
It was working fine on 6.19.0
What we consider a timeout the event `CONSTANTS.EVENTS.BID_TIMEOUT`

## Steps to reproduce
The example is made with Criteo but it seems to be global for user ID module. We have the same issue with ID5 for example.
Building with userId + criteoIdSystem is fine, as long as we do not add criteo in pbjsconfig.userSync.userIds.
We go from 3-4% timeout rate to 10% just by enabling criteo user sync in config.userSync.userIds

user Sync settings :
```
userSync: {
  userIds: [{
    name: 'criteo',
    storage: {
      type: 'html5',
      name: 'criteoid',
      expires: 365
    }
  }],
  syncDelay: 1000
},
```

All browsers are affected
Environment with and without GDPR consent are affected
We have tried to upgrade to Prebid 7.8.0 to see if things gets better but it does not (no change). 
I also tried to set the auctionDelay to 1, but this didn't have any impact

**Comment by patmmccann** [comment]
we noticed as well, our hope was https://github.com/prebid/Prebid.js/pull/8626/files#diff-381b65d4141bd216f9021175532d712ce87a9c4a55985c0cf1226f03421b6014 fixed

**Comment by patmmccann** [comment]
@jlustig11 confirms Rubicon DM oberved as well

**Comment by JulieLorin** [comment]
Thanks, it's good to confirm it's not just us. 

I also tried to twitch the auctionDelay parameter to check if it could improve performances (but it did not). 
Let me know if you need a second set of hands to test/check things, I am available to help with that if there's anything I can do.

**Comment by dgirardi** [comment]
@JulieLorin (and also @patmmccann ), are you able to see if using cookies vs local storage makes any difference?

**Comment by dgirardi** [comment]
I also realized that there might be multiple issues going on - 6.20.0 had [this bug](https://github.com/prebid/Prebid.js/pull/8362) which would conceivable explain the increase in timeout. That was fixed in 6.23.0. Is that also something you could try?

**Comment by JulieLorin** [comment]
> I also realized that there might be multiple issues going on - 6.20.0 had [this bug](https://github.com/prebid/Prebid.js/pull/8362) which would conceivably explain the increase in timeouts. That was fixed in 6.23.0. Is that also something you could try?

I tried upgrading to latest Prebid version (7.8.0 at the time), so this fix was present, but didn't change anything

**Comment by dgirardi** [comment]
@JulieLorin - are you calling any of the userId apis directly (`getUserIds``refreshUserIds` etc), or just `requestBids`? Would it be possible to set up a page with this issue for me to look at?

**Comment by bretg** [comment]
Magnite data does not show a rise in bidder timeouts. We upgraded from 6.11 to 6.24 on June 30th. I checked 3 accounts in different regions and did not see any appreciable change in bidder timeout rate.

**Comment by patmmccann** [comment]
@jlustig11 could you add some detail about the nature of the performance issue you have observed?

**Comment by JulieLorin** [comment]
> @JulieLorin - are you calling any of the userId apis directly (`getUserIds` `refreshUserIds` etc), or just `requestBids`? Would it be possible to set up a page with this issue for me to look at?

We are not calling any of those methods directly (only requestBids). You can use this page on which the issue is present : 
https://www.parents.fr/
(If you need to enable prebid logging, please use `#hbv-pbjs` in the URL or `localStorage.setItem('hbv:pbjs', 'true')` in the console instead of the usual `?pbjs_debug=true`)

We have just updated to prebid.js 7.11.0 but no changes have been noticed.

**Comment by JulieLorin** [comment]
The timeouts returned to their normal value since (at least) 7.17.0 (I didn't test versions between 7.11.0 et 7.17.0), so I think this issue should be closed

**Comment by patmmccann** [comment]
Phew!
