### ISSUE TITLE
Feature request: collect granular performance data on auctions

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#8776]
## Type of issue
Feature request

## Description

Prebid should collect granular performance data (e.g. time spent creating bid requests, resolving GDPR, collecting user IDs, running adapter code etc) and attach it to bid requests for analytics adapters to use. It would help troubleshoot performance issues of the type in https://github.com/prebid/Prebid.js/issues/8770.

**Comment by patmmccann** [comment]
This attaches additional data to the events analytics adapters currently listen to, there is some performance information already. We should allow for sampling of sending this over the wire.
