### ISSUE TITLE
Deprecate adserver.js?

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8779]
[adserver.js ](https://github.com/prebid/Prebid.js/blob/master/src/adserver.js) appears to be completely replaced by https://github.com/prebid/Prebid.js/blob/master/modules/dfpAdServerVideo.js and also has really poor coverage (https://coveralls.io/builds/51056221/source?filename=src%2Fadserver.js ). Should it just be deleted?

**Comment by patmmccann** [comment]
@spormeon are you using this?

**Comment by spormeon** [comment]
ye

**Comment by spormeon** [comment]
oh, this is/ was the PPID "add on" in effect?, so ye on that as well

**Comment by patmmccann** [comment]
This is distinct from that, it appears to be how dfp video was done before the dfp video module

**Comment by spormeon** [comment]
negative then, i use the module
