### ISSUE TITLE
Criteo Bid Adapter: incorrect request ids in interpreted response

### ISSUE THREAD

**Issue by GeneGenie** [prebid/Prebid.js#8780]
## Type of issue
criteoBidAdapter.js bug

## Description
And the goal of any analytics - to track down performance of each individual bidder config. Which is impossible right now. 

When adunit bid list has several criteo bidders and one of them doesn't have zoneId, e.g only networkId param
or several bidders that have only networkId param, and at least 2 of bidders gave bid response, than all bid responses return 
Which is especially critical since Criteo is deprecating [zoneId](https://docs.prebid.org/dev-docs/bidders/criteo.html)

Expected problem is here (taking in account that criteo external publishertag.js has the same logic) 
`const bidRequest = find(request.bidRequests, b => b.adUnitCode === slot.impid && (!b.params.zoneId || parseInt(b.params.zoneId) === slot.zoneid));`

## Steps to reproduce
Consider following config 

```
adunits: [{
                'code': 'hb_unit',
                'bids': [
                    {
                        'bidder': 'criteo',
                        'params': {networkId: **REPLACE_ME**},
                    },{
                        'bidder': 'criteo',
                        'params': {networkId: **REPLACE_ME**},
                    },

                ],
                'mediaTypes': {
                    banner: {sizes:[[300,250]]},
                }
}]
```

## Test page
https://jsfiddle.net/yq2d9g8p/ 
Insert network id that will respond

### Expected results 
**See log:**
RequestedId: 2ceb03cc4b3851
RequestedId: 379112e5626bff
Responded requestId: 2ceb03cc4b3851
Responded requestId: 379112e5626bff

### Actual results
RequestedId: 2ceb03cc4b3851
RequestedId: 379112e5626bff
Responded requestId: 2ceb03cc4b3851
Responded requestId: 2ceb03cc4b3851

## Other information
This is adapter-server issue coz server do not return requestId reference, so bidAdapter doesn't do exact bidId-requestId matching

**Comment by GeneGenie** [comment]
As a workaround for now we'll use individual aliasing of each "networkId" criteo bid adapter, ofcourse it will produce additional request to criteo server.

**Comment by patmmccann** [comment]
@leonardlabat could you comment?

**Comment by allanjun** [comment]
hi @GeneGenie I dont fully understand what you are trying to achieve with this setup, the Criteo bidder should be initiated only once per adunit. I advise you to reach out to your Criteo representative to discuss what you are trying to solve and find a solution.

**Comment by GeneGenie** [comment]
@allanjun  i'm not into publisher  staff. I am a technician =) 
I know that one criteo bidder is configured for native ads, and the other for banner, one have zoneId the other doesn't 
example shows the simplest way to reproduce technical issue. Thank you

**Comment by patmmccann** [comment]
@GeneGenie why don't you just alias criteo on the second call? Cafemedia for example, aliases Index as Roundel for this exact reason, to pass a second account level id param.
