### ISSUE TITLE
Colossus Bid Adapter: user sync type 'html' not supported

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8787]
## Type of issue
bug

@HuddledMasses fyi

## Description

(https://github.com/prebid/Prebid.js/blob/cdb290c501d626d9020e2c0d5ce03b1edc4785bd/modules/colossussspBidAdapter.js#L233) appears to return type 'html' and this warning always fires
https://github.com/prebid/Prebid.js/blob/cdb290c501d626d9020e2c0d5ce03b1edc4785bd/src/userSync.js#L196

## Test page
firstquarterfinance.com?pbjs_debug=true

**Comment by HuddledMasses** [comment]
@patmmccann thx. Fix - #9327
