### ISSUE TITLE
Two Prebid Auctions on the Same Page

### ISSUE THREAD

**Issue by tedrand** [prebid/Prebid.js#879]
## Type of issue

Question

## Description

Obviously adapters are the correct method to integrate multiple partners, but is it possible to run two separate Prebid auctions on the same page?

**Comment by ialex** [comment]
On the package.json file you can specify the global variable name so the two instances can be used with different names, also make sure the initAdServer func is renamed to something else on one of the instances, i havent tested it but it should be posible.

**Comment by mkendall07** [comment]
It's possible, although not recommended. What's the reason to run two instances?

**Comment by tedrand** [comment]
The publisher didn't want to switch header code, and the original provider didn't know how to add adapters, but it sounds like they are going to figure it out. @ialex that makes sense, I figured the global variable would get destroyed on instantiation of second auction.
