### ISSUE TITLE
AMP canonical URL

### ISSUE THREAD

**Issue by oliverfernandez** [prebid/Prebid.js#880]
This is question, related with AMP support for header bidding.

Since the bid is happening inside the 3P Iframe, are bidders receiving the URL of this iframe, instead of the canonical one?

If this is the case, and since inside the 3P iframe, you have access to global.context.canonicalUrl, is there a way to send this URL when performing the bid?

**Comment by mkendall07** [comment]
@oliverfernandez 
Today, no. It would be up to each bidder adapter to send this through (assuming we provide the mechanism to do it).
