### ISSUE TITLE
Set Alias doesn't work unless adapter exists

### ISSUE THREAD

**Issue by r-schweitzer** [prebid/Prebid.js#8831]
a## Type of issue
bug?

## Description
Seems when we attempt to use aliasBidder function for our bidders that are server side only and do not have an adapter the aliases aren't recognized and we're forced to instead set aliases in the s2sConfig. Seems like this was a change made in the anti-alias feature PR #6150 within modules/prebidServerBidAdapter/index.js around line 558. Was the idea to now only use the s2sConfig when aliasing s2s?

<img width="654" alt="image" src="https://user-images.githubusercontent.com/50628828/184642018-e7f4be6c-0fbb-4a68-b4df-965a5c70538e.png">

## Steps to reproduce
Set an alias without the adapter in a Prebid build for a s2s bidder using the following function 
` pbjs.aliasBidder(adapterName, aliasName);`

### Expected results
Would expect the alias to be registered

### Actual results
Aliases are not getting registered

**Comment by dgirardi** [comment]
Technically reverting this behavior is also a breaking change (sending aliases server side if no client side adapter exists): because if people are currently setting up aliases for other purposes, they could suddenly get picked up by server. 

The documentation, as far as I can tell, does say that server-side aliases must be set up through s2sConfig: https://docs.prebid.org/dev-docs/modules/prebidServer.html#server-side-aliases

**Comment by r-schweitzer** [comment]
Prior to that PR getting added we were always able to set aliases either way. The documentation doesn't seem to say you have to set an alias one way or another.  I'm not sure I understand the breaking change you're talking about. Why would someone call for a bidder without an adapter and also not want them server side? Also in order to set a bidder server-side you also have to add them to the list of bidders in the s2sConfig, aliasing them will not automatically send them server-side.

Either way if this is the expected behavior then I think we can clean up some code within adapterManager.aliasBidAdapter where we attempt to set aliases when adapters aren't available.
