### ISSUE TITLE
Unable to render the test ad on hello_world.html

### ISSUE THREAD

**Issue by sireeshaAdmedia** [prebid/Prebid.js#8840]
## Question
I want my test ad to render on the html test page as per the documentation at 
http://localhost:9999/integrationExamples/gpt/hello_world.html

## Description

To test my adapter, I am returning a test ad in bid response to check if the adapter can consume the object. What am I doing incorrectly ?
My return object is 

[{"requestId":"782332","cpm":0.56,"width":300,"height":250,"ad":"<img src=\"https://dummyimage.com/3x0/000150/fff.jpg&text=Admedia\">","ttl":200,"creativeId":125,"netRevenue":true,"currency":"USD"}]

### Expected results
- Render the Test ad

### Actual results
- No Ad is rendered

## Other information

[hello_world_test.csv](https://github.com/prebid/Prebid.js/files/9347693/hello_world_test.csv)

**Comment by dgirardi** [comment]
I think we need some more information - this is for a new adapter I assume? what do you see in the logs (with debug enabled)? could you post a minimal version of your adapter that shows the problem?

**Comment by sireeshaAdmedia** [comment]
<img width="1580" alt="Screen Shot 2022-08-15 at 10 17 12 PM" src="https://user-images.githubusercontent.com/73852384/184931747-9ee20bd6-9d4e-42b3-9084-59b69ac4fc94.png">

**Comment by sireeshaAdmedia** [comment]
hi @dgirardi just attached the screenshot of debug logs

**Comment by dgirardi** [comment]
That warning means that, most likely, the bid response returned by your adapter has a `requestId` that does not match any of the requests' `bidId`s (see [docs](https://docs.prebid.org/dev-docs/bidder-adaptor.html#interpreting-the-response)). Prebid discards your bid and the auction has no winner (and  nothing is rendered).

`bidId` is a random identifier, so you need to echo it back from the request - using a canned response won't work.

**Comment by bretg** [comment]
Closing this out. Let us know if there's still an open question.
