### ISSUE TITLE
Ad units with Prebid auctions have 10% less impressions in GAM

### ISSUE THREAD

**Issue by jeanniek1** [prebid/Prebid.js#8859]
## Type of issue
we see almost 10% difference of ad requests and impressions between non-prebid integrated ad unit (300x600) and prebid integrated ad units (336x280) in the GAM report.  I wonder if 10% difference is normal and acceptable.

## Description
Our site has 3 banners, [336x280(1), 336x280(2), 300x600] in article pages.  Those 3 banners are served via Google Ad Manager(GAM) and two 336x280 banners are prebid integrated and 300x600 is not integrated with prebid.  

From our understanding, those 3 banners should have similar ad requests and impressions in GAM because they are placed in the same pages and similar banner location.  However, we see almost 10% difference of ad requests and impressions between non-prebid integrated ad unit (300x600) and prebid integrated ad units (336x280) in the GAM report.    

I understand that there may be a data difference between prebid and non-prebid ad units due to the nature of the prebid header bidding (latency).  However, 10% difference is a quite big.  I wonder if 10% difference is normal and acceptable.  

This issue causes the impression loss and also drives revenue loss.  Please help...

Appreciate your help in advance.

**Comment by patmmccann** [comment]
Please provide an example page

**Comment by jeanniek1** [comment]
Hello patmmccann,

Thank you for replying!

Please see a live page below.  There are two 336x280 banners side by side and 300x600 banner on the right side.  Also, attached please find a data (ad requests & impressions) retrieved from GAM.

[****](https://www.joongang.co.kr/article/25095256)

![gam](https://user-images.githubusercontent.com/109597143/185448788-827c2d3f-a067-476a-8968-2140de7926c9.jpg)

Thank you very much for your help. :)

**Comment by patmmccann** [comment]
that's very interesting. before studying this in depth, why are you calling apstag.js twice?

**Comment by jeanniek1** [comment]
We fixed it and there's only one apstag.js calling for now.  Do you think 10% less ad requests and impressions are normal?

**Comment by patmmccann** [comment]
I see the first gam call at .8s and the second at 1.2s on my browser now. This is much improved already. Maybe report to see how the metrics change after your fix.

**Comment by jeanniek1** [comment]
I think it's not the reason.  With only one apstag.js call before, we had a same issue. :(

**Comment by dgirardi** [comment]
Which Prebid version is this on? If between 6.17 and 6.24, would you be able to test on a more recent one?

**Comment by jeanniek1** [comment]
I wonder if the first gam call at 0.8s is for non-prebid auction and the second at 1.2s is for prebid auction.

If so, there's 4s delays.  Is it normal? :)  And, is there any way to improve it?

**Comment by dgirardi** [comment]
0.4s you mean? considering that you need at least a network roundtrip to run the prebid auction, that's pretty good in my opinion. Not sure if that explains a 10% difference though.

**Comment by patmmccann** [comment]
@jeanniek1 after your latest round of changes, what is the impression differential?

**Comment by jeanniek1** [comment]
@patmmccann Thank you for following up!  We had a very interesting finding since our last conversation.  We found that 5% less impressions in the US for ad units with Prebid auctions and 10% less impressions in South Korea.  The Prebid setup is exactly the same in both countries.  Do you have any insight what causes the difference? :)

**Comment by dgirardi** [comment]
That is interesting, and most likely means that the drop is indeed due to latency, with the SSPs being slower to reach from SK.  If you are collecting analytics on it, bids' `timeToRespond` should be higher from SK (if this theory is correct).

I wonder if that is "real" traffic though (as opposed to bots/scrapers)? Unless the difference is in the order of seconds, where the user has time to navigate away, I would expect the impression to still happen.

**Comment by dgirardi** [comment]
You could try to lower Prebid's `bidderTimeout` to see if that makes a difference - the default is 3s; if one SSP is particularly hard to reach from SK that would cause everyone else to wait for the timeout and that might be enough time to lose the impression.

**Comment by jeanniek1** [comment]
Let me check the timeToRespond and bidderTimeout.  Thank you for all your help. :)
