### ISSUE TITLE
Error Calling Index Adapter

### ISSUE THREAD

**Issue by tedrand** [prebid/Prebid.js#886]
## Type of issue

Question

## Description

Publisher is underperforming in reporting, and I am seeing the following error in the pbjs_debug output:
`"INDEXEXCHANGE: Error calling index adapter" TypeError: Cannot set property 'bidderCode' of null`

Is the Index Exchange adapter compatible with 0.12.0? Has anyone else experienced this issue?

## Platform details

Publisher is using Prebid v0.12.0. Their partners are just Sovrn and IX.

**Comment by indexexchange** [comment]
Hi @tedrand, can you provide a test page where we can see this error happening?
