### ISSUE TITLE
Taboola bidder not working in Prebid v7.8.0

### ISSUE THREAD

**Issue by ahmadlob** [prebid/Prebid.js#8875]
## Type of issue
We are not been being called or getting traffic from sites that updated their Prebid version to 7.8.0 and above. 

## Description
As we noticed in one site, this error is being raised:
`ERROR: Trying to make a request for bidder that does not exist: taboola`

## Test page
[https://www.footballfancast.com/leeds-united-news/lufc-latest-news-updates-tyler-adams-statistics-ratings-marsch-chelsea-win-premier-league-report-opinion](https://www.footballfancast.com/leeds-united-news/lufc-latest-news-updates-tyler-adams-statistics-ratings-marsch-chelsea-win-premier-league-report-opinion)

**Comment by dgirardi** [comment]
I do not see the issue on that test page. There are several errors like that logged for other bidders, I believe because they are not included in the Prebid bundle. But no error about Taboola and as far as I can tell no bids requested for Taboola.

**Comment by ahmadlob** [comment]
Thanks for the response. Indeed looks like it's just a bundle issue.
