### ISSUE TITLE
Feature: limit /throttle cookie dropping

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#890]
Are header bidders able to drop cookies - even if they do not win the bid?

**Comment by mkendall07** [comment]
Currently we allow it. We might restrict it somewhat in the future.

**Comment by headerbidding** [comment]
It would be good to restrict it.

**Comment by mercuryyy** [comment]
i assume one of the reasons this was allowed was to push more networks to adapt prebid.
If all the bidders can drop cookies on bids they dont win isnt that kind of giving networks free access? 
maybe in the future 1.0.0 release adopt a global prebid cookie that networks can use globally to simple tracking nothing more. that seems fair to both side.

**Comment by dustinbigham** [comment]
An advantage to allowing non winners to drop cookies is it allows the network who dropped the cookie to be able to identify whether the user is valuable to them from their behavior. Networks who don't recognize a user generally bid much less even if it is on a premium site.

**Comment by mkendall07** [comment]
My idea for this would be to allow bidders to register their cookie drop calls and then prebid would handle / throttle as required. Basically, no cookies would drop until after the auction closes and then only would be requested once per some defined interval (24 hours for example) or worst case 1 per page load.
