### ISSUE TITLE
Pr #8626 breaks prebid when publisher is using the bluebirdjs module

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/Prebid.js#8903]
## Type of issue
Pr #8626 breaks prebid when publisher is using the bluebirdjs module. (https://github.com/petkaantonov/bluebird/)

## Description
The bluebirdjs doesn¨t allow "promise" to be subclassed, throwing an error and halting prebid. http://bluebirdjs.com/docs/error-explanations.html#2.-you-are-trying-to-subclass-promise

## Steps to reproduce
The easiest way would probably be to use a proxy to redirect https://content.lwadm.com/lw/6.26.0/prebid.js to a version of prebid.js >= 7.7.0 on the site https://www.gp.se.

## Test page
See above

## Other information
Unfortunately, the publisher using this module cannot remove it or fix the problem easily. I also realize it may not be in the interest of Prebid.org to fix issues specific to a publisher, but I could imagine this might be a problem for more publishers out there + there might be other modules causing similar issues. Also, the publisher is not a small one and not being able to upgrade beyond 7.6.0 will be a major issue. Though we can create a custom branch removing the new functionality, it's not really sustainable in the long run.

One suggestion is to add a config setting to control whether this extended version of promise should be used or not if the problem can't be fixed on the Prebid end?

**Comment by patmmccann** [comment]
The first link says not to user bluebird on modern browsers. Prebid 6.x+ is only for modern browsers.

**Comment by patmmccann** [comment]
Apologies closed by pressing the wrong button, but i don't expect we will be fixing this

**Comment by dgirardi** [comment]
I believe the error wouldn't happen if Prebid is loaded before bluebird. Would that be a viable fix? 

If not, another option could be to have Prebid look for say `window.pbjsPromise` and use that if it's defined, so that you could do 

```html
<script>
window.pbjsPromise  = Promise;
</script>
<!-- load bluebird, prebid, etc -->
```

**Comment by bjorn-lw** [comment]
Thank you very much for replying!

Unfortunately, the chances that the publisher can make such changes that bluebird is removed from their sites is not a possibility right now as it would requite to large rewrites (which is planned, but won't be ready for a pretty long while).

Also, sticking with older versions of Prebid is not an option either and fact is that it has worked flawlessly up until this change so if this one could be solved it would help a lot.

The suggestion to ensure that Prebid is loaded before bluebird: Unfortunately I don't think that's possible since the actual loading of the site would be delayed by the loading of Prebid.js (which would in that case need to be loaded synchronously I believe).

Your other suggestion, defining "window.pbjs.Promise = Promise" may be a solution that's possible to implement. Let me check that!

**Comment by dgirardi** [comment]
After trying some trickery to redirect and inject scripts on https://www.gp.se/ I think the approach will work - if you are able to preprend that snippet before both Prebid and Bluebird, using [this pr](https://github.com/prebid/Prebid.js/pull/8915).

**Comment by bjorn-lw** [comment]
@dgirardi great, thank you very much! The update is on it's way, we'll try it out but it looks like it should work. Thanks again!
