### ISSUE TITLE
Defining the compatibility chart of 1plusX RTD module

### ISSUE THREAD

**Issue by bwhisp** [prebid/Prebid.js#8910]
## Type of issue
Question

## Description
The 1plusX RTD Module (PR: #8614 ) has been released with Prebid 7.7.0 Release 
7.7.0 Release notes: https://github.com/prebid/Prebid.js/releases/tag/7.7.0

We would like to communicate to our customers that 1plusX provides a RTD submodule.
However, some of our customers that are already using Prebid.js were concerned about the compatibility of the version they currently run. 

My question is the following:
How to determine whether a customer can safely upgrade from their current Prebid.js version to the 7.7.0 that includes 1plusX RTD module?

## Platform details
From a lower release of Prebid.js to Prebid.js 7.7.0

## Other information
PR: #8614
Release: https://github.com/prebid/Prebid.js/releases/tag/7.7.0

**Comment by patmmccann** [comment]
If the clients are on 6.x, they should examine the 7.0 release notes for a list of breaking changes to their configuration or api calls. In this particular release, the publisher-facing changes were minimal.

**Comment by patmmccann** [comment]
@nllerandi3lift can you provide any guidance to your colleague on this?
