### ISSUE TITLE
Price Foors: support imp-level floorMin

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#8938]
## Type of issue
Enhancement

## Description
Turns out that the client-side floors module already supports imp-level floorMin, but we found two problems:

1) The ORTB path used client and server-side is different. It was implemented client-side as ext.prebid.floorMin, while server-side it's ext.prebid.floors.floorMin. Server-side is correct. This has been discussed in committee and we agreed that client-side should be updated to prefer ext.prebid.floors.floorMin while still accepting ext.prebid.floorMin for a transition period.
2) The client-side module isn't supporting floorMinCur.

## Original Description
Prebid Server recently released an imp-level floorMin feature. The [client-side floors module](https://docs.prebid.org/dev-docs/modules/floors.html) would benefit from this as well.

The server-side interface is imp[].ext.prebid.floors.floorMin, so the proposed client-side interface is
```
pbjs.addAdUnits({
    code: "mycode",
    ...
    ortb2Imp: {
      ext: {
        prebid: {
          floors: {
            floorMin: 1.0,
            floorMinCur: "USD"
          }
        }
      }
    }
});
```

The behavior would be as defined in the [Prebid Server Price Floor PRD section 4.3.1.2](https://docs.google.com/document/d/1YAt00RfQaU2Ugciqw1LnirLgjyUz9ibfyjfxWUHR_P0/edit#heading=h.y7ns3vee7tuq).

1. After a rule (and thus floor value) is selected for each imp, the Floors feature must validate the chosen floorRuleValue against any provided floorMin:
    1. Look for a floorMin. First check for imp[].ext.prebid.floors.floorMin. If that doesn't exist, check ext.prebid.floors.floorMin.
    1. If a floorMin was found, next, find the floorMin currency: First check for imp[].ext.prebid.floors.floorMinCur. If that doesn't exist, check for ext.prebid.floors.floorMinCur. If that doesn't exist, check the floors data for data.currency or  data.modelGroups[].currency
        1. If both imp[].ext.prebid.floors.floorMinCur and ext.prebid.floors.floorMinCur exist and they're different, emit a warning in debug mode.
    1. If the floorMinCur is different from the floor currency, convert the floorMin value.
    1. If a currency conversion is required but not available, the system should not override imp.bidfloor. It should log a warning in debug mode and to the error log at N% sampling.
    1. If the floorRuleValue is less than the floorMin, then floorValue is set to the converted floorMin. Else floorValue is set to floorRuleValue.
    1. Floor values should be rounded to 4 digits of precision.

**Comment by dgirardi** [comment]
If floorMin comes with a floorMinCur, does that mean that https://github.com/prebid/Prebid.js/pull/8865 needs to be revised? It's currently ignoring currency.

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/pull/8396 ; the solution to the suspected dupe, also doesn't consider currency

**Comment by patmmccann** [comment]
Also it looks at adunit.ortb2Imp.ext.prebid.floorMin not adunit.ortb2Imp.ext.prebid.floors.floorMin

**Comment by jlquaccia** [comment]
@dgirardi regarding currency, are further changes required for https://github.com/prebid/Prebid.js/pull/8865 or are things ok as is?

**Comment by dgirardi** [comment]
Closing since https://github.com/prebid/Prebid.js/pull/8865 was merged.
