### ISSUE TITLE
Is there any way to manually set bidderRequest.refererInfo ?

### ISSUE THREAD

**Issue by elllipse** [prebid/Prebid.js#8940]
## Type of issue
Question

## Description
Hi! I use Prebid.js in SPA and found that while transition between routes `site.page` parameter from payload of every new request to ‘medianet’ are always the same, no matter which route is active.

As far as i can see ‘medianet’ use [bidderRequest.refererInfo.page](https://github.com/prebid/Prebid.js/blob/7.13.0/modules/medianetBidAdapter.js#L65) for populate their `payload.site.page` request parameter. But looks like `refererInfo` function [fires only once](https://github.com/prebid/Prebid.js/blob/7.13.0/src/refererDetection.js#L259) and on every new call it will return the same values.

**Question:** Is there any way to manually set bidderRequest.refererInfo after location change? Or it is expected behaviour that site.page parameter is still the same on different locations while navigate in SPA?   

Also, i have tried [react-advertising](https://github.com/eBayClassifiedsGroup/react-advertising) package but behaviour is the same, site.page always used from page we load initially.

Thanks!

## Examples
route: `http://localhost:3000/`
site.page: `http://localhost:3000/`
<img width="1317" alt="main-route" src="https://user-images.githubusercontent.com/12847991/188008844-738f7ecb-c007-4982-84ab-88b7eb0f0271.png">

route: `http://localhost:3000/article`
site.page: `http://localhost:3000/`
<img width="1291" alt="article-route" src="https://user-images.githubusercontent.com/12847991/188009553-8c87a36e-b580-4969-949e-0deedcd23095.png">

**Comment by elllipse** [comment]
@dgirardi Thanks for your response!
> Are you able to test in 7.11 (or earlier)?

Just checked on 7.11 - it works

> I believe the fix here is to compare location.href and returned the cached value only if that has not changed.

You are right, it works as expected after this checks. I can try to make a PR, but can you please give an advice [which exact cases](https://github.com/prebid/Prebid.js/blob/master/test/spec/refererDetection_spec.js) is better to cover

<img width="1408" alt="Screenshot 2022-09-02 at 11 13 12" src="https://user-images.githubusercontent.com/12847991/188095538-b84eb3f6-9c07-4e34-92c5-913ceae45181.png">

**Comment by dgirardi** [comment]
Change of plans - I think it's best to revert that change for now (https://github.com/prebid/Prebid.js/pull/8954). I completely missed the single page app case there, and there may be other ways pubs update the page URL that are not trivial to detect when deciding if refererInfo needs to be recalculated.
