### ISSUE TITLE
Bug - Integration of Google ESP and Prebid.js User ID Module is not working.

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#8942]
## Type of issue
This is in reference to this closed bug report - https://github.com/prebid/Prebid.js/issues/8532

## Description
Everything is setup per 
https://docs.prebid.org/dev-docs/modules/userId.html#esp-configurations
and
https://docs.prebid.org/dev-docs/publisher-api-reference/registerSignalSources.html

In the test pest here - https://nitin0610.github.io/prebidtest/esp/esp.html?pbjs_debug=true

Prebid debug is firing - 

Prebid INFO: User ID - Registering signal provider: id5-sync.com
prebid.js:516 Prebid INFO: User ID - Registering signal provider: pubcid.org
prebid.js:516 Prebid INFO: User ID - Registering signal provider: criteo.com
prebid.js:516 Prebid INFO: User ID - Registering signal provider: pubmatic.com
prebid.js:516 Prebid INFO: User ID - Registering signal provider: mysegments.com

## Steps to reproduce

Setup like here -  https://nitin0610.github.io/prebidtest/esp/esp.html?pbjs_debug=true
with liveramp, ID5 and SharedID

we also tried the new setup like here - 
https://docs.prebid.org/dev-docs/modules/userId.html#esp-configurations
https://docs.prebid.org/dev-docs/publisher-api-reference/registerSignalSources.html

Also with liveramp, ID5 and SharedID

We do net get prebid debug to output User ID - Registering signal provider: ****

We also are not sure how to check if a single was actually encrypted and sent to GAM since googletag.encryptedSignalProviders=
resets after ad load. 

We  tried with prebid 7.12 then 7.13 and also 6.29.pree

**Comment by patmmccann** [comment]
Try base64 decoding what you see in the gam a3p parameter

**Comment by mercuryyy** [comment]
Were is the gam a3p parameter? The only reference is see to ESP on gam is. googletag.encryptedSignalProviders
I looked in the entire googletag. and have not seen anything with a3p ?

**Comment by mercuryyy** [comment]
Is everything with _GESPSK in local storage the google ESP ?

_GESPSK-id5-sync.com
_GESPSK-sharedid.org
_GESPSK-liveramp.com

...

**Comment by muuki88** [comment]
Did you find the issue in your config? I would like to extend the docs on this if there are some helpful insights. Especially on debugging and validating.
