### ISSUE TITLE
Question: How many header bidders should I have?

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#897]
I currently have 6 active header bidders.

Does adding more header bidding partners increase latency, even when a specific timeout is set?

**Comment by ialex** [comment]
There is an analysis here from the Prebid team, every pub is different so make some tests and gather the data to decide what works for you 

http://prebid.org/blog/how-many-bidders-for-header-bidding

**Comment by tedrand** [comment]
Yeah from what I know it really depends on your set-up, but if a simple Prebid script is your only Ad code then you could probably go up to 8-10.

**Comment by ialex** [comment]
I have seen pubs implementing 8-10 bidders without problems. but i try to minimize the numbers of bids per ad unit no more than 10 since some give you a tag for each size.

**Comment by mkendall07** [comment]
42... j/k.

>Does adding more header bidding partners increase latency, even when a specific timeout is set?

Yes it does increase latency. What @ialex said is the best - a/b test and see what works for your site / performance combination. 

We need a FAQ section on prebid.org... this would be a great starter question.
