### ISSUE TITLE
Timeout on page is different to the config. 

### ISSUE THREAD

**Issue by Jordanjscott** [prebid/Prebid.js#8973]
## Type of issue
I have the Prebid timeout set in the config to 1500, the failsafe at 2000, and consent manager at 8000. When implemented on page however, the timeout is showing as 3000ms. There is no reference of 3000 anywhere in the code.

## Steps to reproduce
View config on the test page below.

## Test page

https://www.thelondoneconomic.com/politics/ben-jerrys-send-pointed-message-to-new-home-secretary-334534/?pbjs_debug=true

<img width="721" alt="Screenshot 2022-09-08 at 20 43 39" src="https://user-images.githubusercontent.com/111888244/189212131-b17107ea-e76a-45b7-a06e-e149b5a040e0.png">
<img width="467" alt="Screenshot 2022-09-08 at 20 29 35" src="https://user-images.githubusercontent.com/111888244/189212127-b9630f84-b160-40b6-b652-bba0ad8e95f2.png">

**Comment by dgirardi** [comment]
How are you using `PREBID_TIMEOUT` in your example? I can't find it in the test page config. To set bidder timeout to 1500 you want do `setConfig({bidderTimeout: 1500})`. 

I see that some of our examples (like [this one](https://docs.prebid.org/dev-docs/examples/basic-example.html)) use `timeout` (instead of `bidderTimeout`) which I think is incorrect. But I don't see that in your test page either.

**Comment by dgirardi** [comment]
And I should add - 3000 is the default for `bidderTimeout`, so it's behaving as if the timeout was not configured.

**Comment by dgirardi** [comment]
Correction: if you are using the `timeout` argument of `requestBids`, it seems to be working as intended:

![image](https://user-images.githubusercontent.com/10151381/189226355-6fd4466e-19bc-4712-b973-e4f1cd0ef880.png)

in your case the timeout is only for that specific auction, so `getConfig()` returns the default value.

**Comment by Jordanjscott** [comment]
> Correction: if you are using the `timeout` argument of `requestBids`, it seems to be working as intended:
> 
> ![image](https://user-images.githubusercontent.com/10151381/189226355-6fd4466e-19bc-4712-b973-e4f1cd0ef880.png)
> 
> in your case the timeout is only for that specific auction, so `getConfig()` returns the default value.

Thanks for the info @dgirardi. That's correct, i'm using requestBids function as I'm running parallel auctions with A9. 

Could you explain what you mean by the timeout running only on the specific auction? The timeouts set should be running on every auction here. Or is it a case of the 1500ms being respected on page, but debugging not picking it up as it's handled via the requestBids function?

**Comment by dgirardi** [comment]
if you call `requestBids({timeout: ...})`, the `timeout` applies only to that call/auction, and overrides the global `setConfig({bidderTimeout: ...})`. Conversely, the `timeout` argument is optional, and if omitted that auction will use the global `bidderTimeout` config. If you are only calling `requestBids` once they are redundant.

Auction-specific arguments are not accessible via `getConfig`, but if you are looking for a confirmation you should be able to see them set correctly in auction events like [auctionInit or auctionEnd](https://docs.prebid.org/dev-docs/publisher-api-reference/getEvents.html).
