### ISSUE TITLE
Issue with pbjs.adUnits values being duplicated after a unit has requested a bid

### ISSUE THREAD

**Issue by Austinb** [prebid/Prebid.js#8980]
## Type of issue
Question (Bug?)

## Description
When moving from Prebid v4 to v5 latest release and then to v6 latest release we have noticed an odd issue where ad units defined in the `pbjs.adUnits` are being duplicated upon an ad unit refresh and calls to `pbjs.requestBids()`.  The issue is the `pbjs.adUnits` becomes so large it causes the browser to crash.  Also this cascades and starts sending massive number of calls to prebid partners. 

We did not see any changes required to the invocation code when upgrading from v4 latest. 

## Steps to reproduce
You can use the test site https://tipsybartender.com/?tms_debug=1 and use the console to see the information coming back.  You can also type `tmspb` into the console after a set of refreshes and you will see the number of elements in the `adUnits` array has increased.  All of the new entries have transactionId properties and replicate the information for the "base" ad unit but continually get added.  Is this expected behavior now that we need to account for?

## Test page
This is a current test site with the issue - https://tipsybartender.com/?tms_debug=1

### Expected results
Ad units are not duplicated in the `pbjs.adUnits` array. 

![Screenshot 2022-09-09 182627](https://user-images.githubusercontent.com/273921/189458541-71c090d1-0445-4c47-8ae0-df3e28bb9080.png)

### Actual results
After each subsequent call to `pbjs.requestBids()` the entires in `pbjs.adUnits` increases. 

![Screenshot 2022-09-09 182636](https://user-images.githubusercontent.com/273921/189458560-17fca9ea-158e-40b7-a449-e1034911f7d9.png)

## Platform details
Prebid.js built on Ubuntu 18.04, Node 14.20.0, NPM ~~6.14.17~~ Updated and rebuilt using 8.19.1 to remove this as a possible issue. 
Viewing on Windows 10 - Chrome Latest & Firefox Latest

## Other information
This is a custom library that has not changed internally in how ad units are prepared for prebid or how they are displayed.

**Comment by dgirardi** [comment]
Could you provide steps to reproduce? I am unable to on that test page (calling `tmspb.requestBids` does not duplicate adUnits for me, and I'm not sure how to trigger "a set of refreshes").

**Comment by Austinb** [comment]
The refreshes happen on their own via a set interval timer (i.e 30 seconds after the first call to the ad unit loads).  You can also invoke a page reload via `TAS.reload()` in the console which is used by SPA's to reload the ad units for changes in the DOM. 

We noticed the issue is happening on any set of bid requests. Even the items were being duplicated even on the first calls out of the gate before any refreshes occur. The result after the initial page load would be 2x the number of items in the `pbjs.adUnits` array as was originally added for the initial call on page load. If you look at the console using the link above with the query param `tms_debug` you should see the console entries `Ad units after` with an array of the ad units from the `pbjs.adUnits` param in pbjs. 
 
![Screenshot 2022-09-12 102248](https://user-images.githubusercontent.com/273921/189693030-804ed876-57f2-46aa-846a-bc5c1ffa3167.png)

You will see the count go up until all the auctions come back and start to complete where we add a work around (hooking into the `auctionEnd` callback) to remove any items from the list that had the `transactionId` property as not empty. This so we could fix the issue for our clients as the issue was causing browser crashes among other kinds of issues.  Upon ad unit refresh you can see in the logging the count for the `pbjs.adUnits` will go up from 15 to 16 or 17 and then back down.  The back down part is the script removing the "duplicate" entries after the auction ends for the specific ad unit.  This is a hack/quick fix just to resolve the issue in the interim.

I guess the main question is what changed between v4 and v5/v6 that could be causing this issue?  Also, where in the prebid library are the values of `pbjs.adUnits` manipulated outside of a direct call to `addAdUnits()`. We added a callback for the `addAdUnits` event but it never fired.  Even an output of all the events doesn't show that event being fired at any point. 

`tmspb.getEvents().forEach(event => {
   console.log("event: "+event.eventType, event)
})`


Our library is on the older side in terms of package.json dependencies and we are in the process of updating but it will be slow as to not affect stability.  So we have been trying to track down if there is an incompatibility issue between coreJS versions (which we use internally) or something related causing the `pbjs.adUnits` array to be manipulated incorrectly. Any information or direction as to where to look in the Prebid.js library and add some breakpoints/logging would be helpful as to try to track this issue down.

**Comment by dgirardi** [comment]
Also - the `addAdUnits` event seems to be working normally:

![image](https://user-images.githubusercontent.com/10151381/189714080-e1a1b6ac-6775-4a1a-887f-9efb1d947ff9.png)

for reference, it's triggered [at the end of a `tmspb.addAdUnits` call](https://github.com/prebid/Prebid.js/blob/56941e187ae054b6927ae8aebf6ee3f07d04d14a/src/prebid.js#L715-L720).

**Comment by Austinb** [comment]
The aax.js is an ad blocker work around (yea I know...) by A9 (Amazon's Ad Marketplace - https://aps.amazon.com/aps/unified-ad-marketplace/) which serves lightweight creatives (i.e. images) when ad blocking is detected.  We are reaching out to them directly.  Thank you for the help.  I am glad it was not an issue with Prebid.js directly. 

For now we will have to keep our work around in place until A9 fixes the issue. 

As for your other reply:
> Also - the `addAdUnits` event seems to be working normally:
> 
> for reference, it's triggered [at the end of a `tmspb.addAdUnits` call](https://github.com/prebid/Prebid.js/blob/56941e187ae054b6927ae8aebf6ee3f07d04d14a/src/prebid.js#L715-L720).

I never meant to imply that the callback for the `addAdUnits` event was not working, it was just not being fired and ad units were being added to the array.  Since you found the offending call we can see they are manipulating the array directly rather than doing it via the provided functions in Prebid.js.  They are lacking some basic checks as well or at the very least some cleanup after the fact.

**Comment by dgirardi** [comment]
Is it possible that what changed is the timing of when aax is loaded compared to Prebid? Its logic seems to be, if aax is initialized _after_ the first `addAdUnits` call, duplicate the adUnits; otherwise it keeps its own separate copy:

![image](https://user-images.githubusercontent.com/10151381/189721522-68cced17-04bc-46d1-a121-d899b9bad339.png)

**Comment by dgirardi** [comment]
In fact, you may be able to work around it by using `requestBids({adUnits: ...})` instead of `addAdUnits(...); requestBids(...)`. The former would not trigger the `addAdUnits` event which - from the looks of it - would "trick" aax into not polluting Prebid's `adUnits` array.

**Comment by Austinb** [comment]
I saw that as well and will be asking them about it.  They may need to change their logic to make sure Prebid.js is loaded before doing any work or at least queue it up in the Prebid.js' `que` so that their calls make it in time for the first set of auctions on page load.  This is just a guess though until we hear back from APS. 

We may have to change our logic to use `requestBids` but the current hacky fix is working in the mean time to keep our clients happy. We are going to stick with it until we get some feedback from Amazon directly and then make a permanent fix on our end.  They should probably not be manipulating the `adUnits` directly anyway and do a better job to make sure they are not cloning existing units.   Thanks again for your help.

**Comment by dgirardi** [comment]
If you want to refer them to this issue, I believe their `case s.a.ADD_AD_UNITS` can be removed entirely - if the goal is to keep track of all impressions that are auctioned through Prebid, it's already covered by the other case (on `s.a.BEFORE_REQUEST_BIDS`). Even after correcting for the (probably unintentional) direct reference to Prebid's array, listening to both can only result in duplication.
