### ISSUE TITLE
Question: Ad render was prevented from writing to the main document

### ISSUE THREAD

**Issue by jdalia001** [prebid/Prebid.js#8985]
Hi,

I got a problem with my Prebid Configuration.
I am using a PrebidJS on my website and a PrebidServer for S2S calls.

I have an oustream placement from which I got a vastXml in return.
The problem is that the vastXml is a "script" who already embed a player with the ad inside.

I am trying to render it directly in the body from the bidsBackHandler but I got this error message : 
_ERROR: Error trying to write ad. Ad render call ad id 460d352280603d was prevented from writing to the main document._

Someone already facing this issue ?

Thanks a lot !

**Comment by dgirardi** [comment]
Could you provide a test page? That error message normally would not apply to an outstream video bid: it means that you should not try to render on the top level document directly, but outstream rendering is outsourced to a separate renderer script, which is a different code path. I would have expected you to see an error about missing the required renderer configuration before you could even get to that error message.

[This is an example](https://docs.prebid.org/examples/video/outstream/pb-ve-outstream-no-server-specify-renderer.html) of how to specify a renderer for outstream video.

**Comment by patmmccann** [comment]
Appears the isRendererRequired check failed, which is strange, and then you got to this path, which checked if you were in a frame 

https://github.com/prebid/Prebid.js/blob/f0282eed1e653cfa21a6b69531d30effd6829b2d/src/prebid.js#L531

**Comment by patmmccann** [comment]
@fowler446 fyi
