### ISSUE TITLE
Proposal: upgrade fpd enrichment module to core

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#8990]
## Type of issue
Feature request

## Description
In committee and https://github.com/prebid/Prebid.js/pull/8738 there is much discussion of the Ortb2 object, and how much of the direction of the project from a bid adapter perspective will be on improving this object and minimizing the need for duplicate code across many adapters to form an Ortb request. Some of the enrichments we plan to add are in the enrichment module, and more are planned on being added there. So that adapters can rely on these fields existing, my proposal is to upgrade enrichment to core.

**Comment by bretg** [comment]
This would add about ~2KB to core, which is about a 1.3% increase.

The tradeoff is that a number of adapters are doing this enrichment independently, which means that depending on which adapters a pub includes, moving FPD enrichment to core could potentially even out the net byte count.
