### ISSUE TITLE
Why the current version does not support DiscoveryDsp adapter?

### ISSUE THREAD

**Issue by cuihua111** [prebid/Prebid.js#8993]
## Description
The note in the documentation says: This adapter is not available in current versions of Prebid.js, but no reason is given, so I would like to know what the specific reason is。

link :https://docs.prebid.org/dev-docs/bidders/discovery

**Comment by patmmccann** [comment]
becuase https://github.com/prebid/prebid.github.io/blob/b526c9f619860e55f4495c3fb4680f026b183a11/_layouts/bidder.html#L38

and 

https://github.com/cuihua111/prebid.github.io/blob/66d2718f1b3078f2946e8b708685f64a5d69a302/dev-docs/bidders/discovery.md?plain=1#L8


In other words, your PR to the docs repo set enable download to false and triggered this automatic message.
