### ISSUE TITLE
Multiple ad units on the same page

### ISSUE THREAD

**Issue by dresource** [prebid/Prebid.js#901]
## Type of issue
Question

## Description
I have multiple ad units on my site. I would like to pass the ad unit id when GA events fire so I check the performance of each ad unit. 

While reviewing the code, I noticed that individual events (one event for each ad unit/bidder combo)  are fired only for Bids, Bid Load Time & Wins. Within these events, I can set a custom dimension so on GA I can use a custom reports to check the performance on ad unit wise.

For Requests and Timeouts, only 1 event is fired for each bidder, with an event value of 1 and 0 respectively. 

Questions:
1) Is there a reason only 1 event is fire for each bidder for Requests and Timeouts?

2) Why is the event value hard-coded to 1 and 0 even though for each bidder we are sending requests and getting timeouts for every ad unit? 

3) I can write code that will fire individual Request and Timeout events for each Ad Unit/bidder combo but at a certain point, it will likely hit the GA cap for number of hits. Is there a workaround solution already available for this issue? 

4) If not, is there any known method of bypassing the GA limit?

Thanks,

**Comment by mkendall07** [comment]
These are current limitations of GA. No plans to update the adapter at this time.

**Comment by bretg** [comment]
> Is there a reason only 1 event is fire for each bidder for Requests and Timeouts?

Many bidders support sending all of the AdUnit requests at the same time - in that case there really is only request and timeout.

> I can write code that will fire individual Request and Timeout events for each Ad Unit/bidder combo but at a certain point, it will likely hit the GA cap for number of hits. Is there a workaround solution already available for this issue?

We did recently implement a sampling feature in the GA adapter that may be useful.

BTW - your pointer about custom dimensions is a good one... thanks. Will add that note the Prebid.org GA page at some point.
