### ISSUE TITLE
rhythmone adapter does not `bidManager.addBidResponse` if no bid is returned

### ISSUE THREAD

**Issue by nanek** [prebid/Prebid.js#903]
## Type of issue
Bug

## Description
rhythmone adapter does not `bidManager.addBidResponse` if no bid is returned for an adSlot. Impact, pbjs.allBidsAvailable() returns false and auction waits for the prebid timeout when this occurs.

## Steps to reproduce
Setup Prebid/rhythmone with three ads on a page. If rhythmone only bids on two of these, but not the third, prebid timeout will be hit.

## Platform details
Prebid 15

## Other information
Looks like there is some `noBids` logic in the adapter, but it is only called in certain conditions instead of always.

**Comment by jstocker76** [comment]
I see the bug- looks like no bids are not registered when 1+ bids are returned by our API.  Fixing...

**Comment by protonate** [comment]
This has been addressed with #913, closing.
