### ISSUE TITLE
Prebid file not built properly

### ISSUE THREAD

**Issue by AndBeyondMediaHB** [prebid/Prebid.js#9037]
## Type of issue
bug

## Description
When I try to download PrebidJs with the selected Compass adapter, I get an error:
`{"error":"Prebid file not built properly","requestId":"e9179e40-85cb-4ba1-a0bd-4f03152ec8c0"}`

## Steps to reproduce
1. Go to https://docs.prebid.org/download.html
2. Select Compass adapter (biddercode - `beyondmedia`)
3. Download Prebid.js

**Comment by dgirardi** [comment]
@AndBeyondMediaHB, what's the relationship between Compass and AndBeyondMedia? 

There are two conflicting documentation files (which are used for the download page): both [andBeyondMedia](https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/andBeyondMedia.md) and [compass](https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/compass.md) declare a title of "Compass", so only one of them will show up - I'm not sure if the precedence is well defined. AndBeyond media also has an incorrect `biddercode`, it should be `andBeyondMedia`, this is what's causing the error.

**Comment by bretg** [comment]
Docs issue https://github.com/prebid/prebid.github.io/pull/4018

**Comment by AndBeyondMediaHB** [comment]
> @AndBeyondMediaHB, what's the relationship between Compass and AndBeyondMedia?
> 
> There are two conflicting documentation files (which are used for the download page): both [andBeyondMedia](https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/andBeyondMedia.md) and [compass](https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/compass.md) declare a title of "Compass", so only one of them will show up - I'm not sure if the precedence is well defined. AndBeyondMedia also has an incorrect `biddercode`, it should be `andBeyondMedia`, this is what's causing the error.

@dgirardi thanks for the answer. @bretg attached a pull request to change the title from Compass to AndBeyondMedia. Did I understand correctly that the biddercode must be the same as the adapter title in lower case? Or am I confusing with the adapter's .js file name?

**Comment by dgirardi** [comment]
@AndBeyondMediaHB, for the website and download page, `biddercode` is just the file name minus `bidAdapter`. I think we recommend naming them the same as `spec.code`, hence the confusion.

**Comment by AndBeyondMediaHB** [comment]
@dgirardi thanks, it's all clear now

**Comment by bretg** [comment]
fixed in referenced PRs
