### ISSUE TITLE
migrate currency.prebid.org to jsdelivr

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#9046]
## Type of issue
cost containment

## Description
There are a few publishers who have ignored repeated requests to stop using currency.prebid.org/latest.json. Prebid spends a lot of money on AWS CloudFront fees for these holdouts.

What are some ways to reduce our AWS fees? We can't just use DNS because the URL paths are different as well. Perhaps a Lambda function that does a redirect?

currency.prebid.org/latest.json should redirect to https://cdn.jsdelivr.net/gh/prebid/currency-file@1/latest.json

**Comment by bretg** [comment]
Background: I have attempted to reach out to the top 2 Japanese publishers using the old currency.prebid.org and they didn't respond. Here's the list of the domains utilizing our CloudFront:

- ameblo.jp - 32%
- trilltrill.jp - 23%
- www.yomiuri.co.jp - 5%
- merkur.de - 5%
- lequipe.fr - 5%
- tz.de - 3%
- markt.de - 3%
- delishkitchen.tv - 2%
- epark.jp - 2%

The options here:
- disable the CloudFront distribution. This is pretty rude. Though it should be said that it's sorta rude these websites aren't following instructions, are costing us a good deal of money, and aren't even prebid.org members. 
- set up an EC2 instance to do a 302 redirect. This will probably save quite a bit of money, but may take some time to spin up and test. Right now the currency.prebid.org DNS alias points to d24v0qfgxmmkdg.cloudfront.net. That would be moved to the redirect ec2 instance.

**Comment by patmmccann** [comment]
One option is to stop updating the file; that might encourage migration. Another option might be to remove the cloudfront cdn layer so that the file hits s3 directly. Also cloudfront could do the 302 which would dramatically reduce fees

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/example-function-redirect-url.html

**Comment by bretg** [comment]
I didn't know CloudFront could do that. Good find @patmmccann .

So I set up a function to redirect, but before switching, have a question -- when I hit https://currency.prebid.org/latest.json, the Content-Type is application/octet-stream, but for https://cdn.jsdelivr.net/gh/prebid/currency-file@1/latest.json, the Content-Type is application/json; charset=utf-8

PBJS doesn't seem to care what the Content-Type is -- tried both in a test page.

But before I publish this function to CloudWatch, wanted to see if anyone had any concerns about impact to pubs by changing the Content-Type?

**Comment by patmmccann** [comment]
I'm not aware of a potential issue from this mismatch

**Comment by bretg** [comment]
We tried a number of different approaches to make this work, but are stuck... CORS stops us from doing what we'd hoped. So we're left with two more options:

- spin up an EC2 box that redirects with a CORS header
- see if the jsdelivr team would be willing to set up a special prebid environment

there are tradeoffs with both approaches

**Comment by muuki88** [comment]
We'll try to contact the German sites.

**Comment by allanjun** [comment]
Those domains have a direct line with us, I will try to reach out

**Comment by Traffective** [comment]
The following domains were updated:
merkur.de - 5%
tz.de - 3%
markt.de - 3%
You should not get traffic from these sites anymore.
Thanks for the notifying.

**Comment by bretg** [comment]
No more to change. You could just drop the conversionRateFile and let Prebid default to jsdelivr. The conversionRateFile parameter was meant for publishers that want to host their own file.

**Comment by bretg** [comment]
To any of the affected publishers, Prebid's recommendation to fix this is to simply remove the `conversionRateFile` parameter from the call to pbjs.setConfig(). The module will default to the file hosted by Prebid.

**Comment by flux-dev** [comment]
@bretg 
We are currently fixing this problem with Japanese publishers and will report further progress when they're ready!

**Comment by patmmccann** [comment]
@bretg could you post a traffic list for a recent day?

**Comment by bretg** [comment]
Looks like another of the Japanese pubs made a change within the past few days. Will wait another day and post a report tomorrow

**Comment by patmmccann** [comment]
Closing as won't do
