### ISSUE TITLE
Some bidders (e.g. 33across) does not support aliasing

### ISSUE THREAD

**Issue by takenorim** [prebid/Prebid.js#9047]
## Type of issue
A bug

## Description
Some bidders use the hard-coded `bidderCode` attribute. As some examples,
- 33across (https://github.com/prebid/Prebid.js/blob/master/modules/33acrossBidAdapter.js#L673)
- fluct (https://github.com/prebid/Prebid.js/blob/master/modules/fluctBidAdapter.js#L108)

I found there is mismatch between `adapterCode` and `hb_bidder` key-value passing to GAM XHR for such bidder's alias setup.

## Steps to reproduce
As of PBJS v7, those bidders needs the bidderSettings config like below to use the alising.
```
pbjs.aliasBidder("33across", "33across_test");
pbjs.bidderSettings = {
  "33across_test": {
    allowAlternateBidderCodes: true
  }
}
```

Without the bidderSettings code, the following warning is shown and no XHR is sending to this aliased bidder.
```
Prebid 33across_test WARNING: 33across is not a registered partner or known bidder of 33across_test, hence continuing without bid. If you wish to support this bidder, please mark allowAlternateBidderCodes as true in bidderSettings.
```

### Expected results
For this setup, we expect the key-value `hb_bidder=33across_test` is passing to GAM. 

### Actual results
However, `hb_bidder=33across` is passing in stead. Actually, the `pbjs.getBidResponses()` method shows like below.

```
...(snip)...

"adapterCode": "33across_test",
"bidderCode": "33across",
"bidder": "33across",
"adserverTargeting": {
    "hb_bidder": "33across",
    ...(snip)...

}
...(snip)...
```

**Comment by takenorim** [comment]
This is untested, but I assume the fix would be either of the followings.
a) Remove the hard-coded `bidderCode` attribute from such bidders.
b) Change the PBJS core logic to use `adapterCode` instead of `bidderCode` for `hb_bidder` GAM key-value, like below. But, this may have a bad side effect.

- https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L756
```
    createKeyVal(TARGETING_KEYS.BIDDER, 'bidderCode'),
```
=>
```
    createKeyVal(TARGETING_KEYS.BIDDER, 'adapterCode'),
```

**Comment by dgirardi** [comment]
I believe there are two issues here:

 1. publisher defined aliases should not require `allowAlternateBidderCodes`;
 2. adapters should not override `bidderCode`  (and `hb_bidder`) if they don't have a reason to.

1 is relatively straightforward to fix, but 2 is harder to address without breaking people that rely on how `hb_bidder` is currently set. 

We could introduce a new setting, `pbjs.bidderSettings[bidder].targetingOverride`, with the same syntax as [adserverTargeting](https://docs.prebid.org/dev-docs/publisher-api-reference/bidderSettings.html), to allow overriding of just `hb_bidder`.

**Comment by patmmccann** [comment]
It seems we should do 1a in 8.0

**Comment by curlyblueeagle** [comment]
Hey All, maintainer from 33Across here. Just to give you context...when we developed the adapter during (pre) Prebid 1.0 days the [docs had us set](https://github.com/prebid/prebid.github.io/blob/bb600ca44511e0f49be8f38d90b7788e05481dcd/dev-docs/bidder-adaptor.md) the `bidderCode` in our response. I guess we never got around changing this. 

Should we remove this override?

**Comment by dgirardi** [comment]
@curlyblueeagle, we agreed in the last PMC that this should be fixed in a major version, because it's likely to break existing setups.

**Comment by curlyblueeagle** [comment]
@dgirardi okay, do I understand correctly that Prebid will remove the bidder code as part of 8.0? Or do you expect a PR from us?

**Comment by takenorim** [comment]
@dgirardi @curlyblueeagle - Thanks for your feedback. 

I agree this idea toward v8.0 release as long-term goal. However, as short-term solution, I want (as many) bidders to remove `bidderCode` from their code if they agree.

**Comment by dgirardi** [comment]
@takenorim, our concern is that at least some publishers are likely to have set up aliases for reasons other than targeting, and set up the ad server to expect `hb_bidder=33across`, since that's what gets sent. Fixing it now (vs waiting for a major release) would not give them notice or time to check and update their line item setup.
