### ISSUE TITLE
RubiconBidAdapter singleRequest bidder config is not working

### ISSUE THREAD

**Issue by elad-yosifon** [prebid/Prebid.js#9049]
## Type of issue
A bug

## Description
RubiconBidAdapter singleRequest config is not working anymore due to caching the "initial" config in a module scope, instead of dynamically using it.

## Steps to reproduce
adding this configuration with `pbjs.que.push` will not be memoized by the `rubiconBidAdapter` current code:
```javascript
pbjs.que.push(() => {
  pbjs.setConfig({
    rubicon: {
      singleRequest: true
    }
  });
});
```

### Expected results
setting `singleRequest: true` should trigger only one request per auction

### Actual results
setting `singleRequest: true` is ignored

## Platform details
- since Prebid.js version 4.10.0

## Other information
This is a regression, it used to work before this commit 92e234c4.
https://github.com/prebid/Prebid.js/pull/5780

**Comment by dgirardi** [comment]
Closing since https://github.com/prebid/Prebid.js/pull/9050 was merged.
