### ISSUE TITLE
How to make analytics module able to track instream bidwon event

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/Prebid.js#9055]
## Type of issue
Feature request

## Description
Analytics modules are able to track bidwon events for banner, native and outstream mediatypes, but when it comes to instream there seem to be unable to track this event.

I guess this is related to the vast creative format which is simply called by the video player without involving prebid.js anymore after the winning bid is selected.

From an analytic module point of view, it would be interesting to find a way to make some pixel to be call when the vast video is loaded. I think the easiest way to do so would be to add an impression pixel inside the vast creative itself. This could be option in prebid.js config to allow which analytics modules would be allowed to get their insteal pixel inserted in the vast. 

I this something doable ? 

Thanks,
Matthieu

**Comment by patmmccann** [comment]
might be useful if this had the adid in it https://github.com/prebid/Prebid.js/blob/73c13cde704ef396a152ed9dcb8596779473107d/src/videoCache.js#L53

**Comment by patmmccann** [comment]
it seems like this one also occurs, https://github.com/prebid/prebid-server/blob/4dfe9e35d7b7cc0ad851e9530f1d5f00287fbed8/exchange/auction.go#L299   so a commit to add uuid or adid would be needed in both places
