### ISSUE TITLE
Question: sizes property - single size array or multi size array?

### ISSUE THREAD

**Issue by dbabaioff** [prebid/Prebid.js#906]
## Type of issue
question

## Description
Hi,
When I register bidder tag IDs and I have only one size, let's say for example 300x250  - Is required the sizes property to be an **multi size** array? like [[300,250]] or a single size array is ok (like [300,250])?

```javascript
var adUnits = [{
            code: 'div-gpt-ad-1438287399331-0',
            sizes: [300, 250], // <==== THIS SHOULD BE A SINGLE SIZE [300,250] ARRAY OR MULTI SIZE ARRAY [[300,250]]
            bids: [{
                bidder: 'appnexus',
                params: { placementId: '4799418' }
            }
            // Add other bidders here
            ]
        }];
```

**Comment by mkendall07** [comment]
Either way is fine.

**Comment by qrilka** [comment]
What about documenting allowed variants? E.g. if dimensions shoud always be integers?
