### ISSUE TITLE
`${CLICKTHROUGH}` macro is not documented, and does not work with safeframe

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#9060]
## Type of issue
bug?

## Description

https://github.com/prebid/Prebid.js/pull/5796 introduced the `${CLICKTROUGH}` macro for ad markup, to be substituted with the value passed as an option to `renderAd`. Both the macro and the option are undocumented, and it appears that there is no way to make it work with safeframe (since it does not go through `renderAd`).

**Comment by patmmccann** [comment]
partial dupe of #6130

**Comment by jlquaccia** [comment]
Created a PR for this to prebid.github.io here: https://github.com/prebid/prebid.github.io/pull/4176
