### ISSUE TITLE
User-agent client hints: Publishers that cannot upgrade their Prebid version + User-agent reduction deprecation trial

### ISSUE THREAD

**Issue by github-baptiste-haudegand** [prebid/Prebid.js#9094]
## Type of issue
Feature request/Questions

## Description

Hello, as you know Chrome is rolling out soon the user agent client hints instead of having access to the full user agent.
An [implementation](https://github.com/prebid/Prebid.js/pull/8826) was done in the core of Prebid.js recently and we plan to take advantage of it to forward the information to our SSP.

Two questions based on that:
* Is it planned to support the [User-agent reduction deprecation trial](https://developer.chrome.com/blog/user-agent-reduction-deprecation-trial/) ?
* For publishers that cannot upgrade their Prebid version. Is there a way in that case to support user agent client hints (and user-agent reduction deprecation trial) in a retrocompatible way?

Thanks in advance,

**Comment by patmmccann** [comment]
> For publishers that cannot upgrade their Prebid version. Is there a way in that case to support user agent client hints (and user-agent reduction deprecation trial) in a retrocompatible way?

You are welcome to pr old major version legacy branches, but we don't release them, the publisher would need to build and deploy from the legacy branch instead of a release. 

> Is it planned to support the [User-agent reduction deprecation trial](https://developer.chrome.com/blog/user-agent-reduction-deprecation-trial/) ?

We don't plan to get an origin trial token and force publishers into the delayed deprecation as part of prebid software, but for publishers who have, it seems things would just work seemlessly?


We should likely expedite upgrading fpd enrichment to core; but we're still working to merge a predicate ticket

**Comment by github-baptiste-haudegand** [comment]
> We don't plan to get an origin trial token and force publishers into the delayed deprecation as part of prebid software, but for publishers who have, it seems things would just work seemlessly?
Ok, we will have to test if indeed it would work as expected

> You are welcome to pr old major version legacy branches, but we don't release them past the inital 60 day period, the publisher would need to build and deploy from the legacy branch instead of a release.
Thanks for the info, ideally we should target upgrading their Prebid.js version then

**Comment by github-baptiste-haudegand** [comment]
misscliked `as completed`

**Comment by github-baptiste-haudegand** [comment]
misclicked `as completed`
