### ISSUE TITLE
Feature request: make analytics non-blocking

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9110]
###Description

Analytics adapters listening to events may occasionally block the auction; we'd like to rearchitect that in a better way. 
Reported by @robertrmartinez ; feel free to expand.

**Comment by dgirardi** [comment]
@robertrmartinez , if you don't mind, I plan to do this together with the changes needed for https://github.com/prebid/Prebid.js/issues/9014

**Comment by robertrmartinez** [comment]
Of course not! Be my guest!
