### ISSUE TITLE
rubicon response

### ISSUE THREAD

**Issue by leonardoligas** [prebid/Prebid.js#912]
## Type of issue
question

## Description
Hi,

From Rubicon Response is it possible get the field "network"? How can i set a custom response?

Many thanks

Leonardo 

## Platform details
v0.16.0

**Comment by bretg** [comment]
Hello Leonardo - can you help us understand what problem you're aiming to solve? The network ID is in the full response, but not sure there's a 'normal' place to register it with Prebid's bidResponse.

**Comment by leonardoligas** [comment]
Hi bretg,

i need to get network id in Prebid bidResponse, is it possible? how can i custom the bidResponse?


Many thanks

**Comment by bretg** [comment]
Why do you need network ID -- what problem are you trying to solve?

**Comment by protonate** [comment]
@leonardoligas please let us know the status of this, thanks.
