### ISSUE TITLE
Version issues

### ISSUE THREAD

**Issue by cuihua111** [prebid/Prebid.js#9129]
I have a question: our bidder adapter is in a higher version of Prebid.js, and the publisher is using a lower version of Prebid.js. If the publisher wants to choose our bidder, is it the only way for the publisher to upgrade the Prebid.js? In addition, if our bidder adapter needs to be modified later, should the publisher also be upgraded together? Thank you, looking forward to your reply.

**Comment by patmmccann** [comment]
Yes and yes
