### ISSUE TITLE
requestBids() - Parallel requests

### ISSUE THREAD

**Issue by dbabaioff** [prebid/Prebid.js#914]
## Type of issue
question

## Description
Is it possible to call the function requestBids() multiple times and hove those requests happening on parallel?
The idea is to call requestBids multiple times and pass different values for the "adUnitCodes" param
This will involve to keep track for each request a separate timeout and different combination of adUnitCodes.
If yes, which version this feature is fully supported (including different timeout/adUnitCodes)?

**Comment by mkendall07** [comment]
It's currently not supported, and we don't have a easy way to implement it for the time being.

**Comment by pm-harshad-mane** [comment]
Hello @mkendall07 ,

Any plan/update about resolving this issue ?

**Comment by snapwich** [comment]
#1421 is working on solving this problem

**Comment by pm-harshad-mane** [comment]
@snapwich thank you for the update.
