### ISSUE TITLE
Prebid js with s2s 

### ISSUE THREAD

**Issue by rumanali123** [prebid/Prebid.js#9145]
We are trying to run s2s java ad locally.but we are facing some issues. when we host our PBS on aws our server is working fine but when we run PBS locally then our ad doesn't display.
we tried some solutions
https://stackoverflow.com/questions/49831824/prebid-example-does-not-work-when-running-on-local-dev-server/49971455#49971455
but nothing happens.
This is our Bidrequest

{"id":"2b9baa3f-25c6-4a96-9924-637c08bf7245","source":{"tid":"9f2bfeaf-6845-4ed3-8041-6fe5ad10c5d5"},"tmax":3000,"imp":[{"ext":{"data":{"pbadslot":"/22696859215/id"},"improvedigital":{"placementId":12334}},"id":"/22696859215/id","banner":{"format":[{"w":300,"h":250}]}}],"test":1,"ext":{"prebid":{"auctiontimestamp":1666614144937,"targeting":{"includewinners":true,"includebidderkeys":false},"channel":{"name":"pbjs","version":"v6.29.0"},"debug":true,"cache":{"vastxml":{"returnCreative":false}}}},"site":{"publisher":{"id":"333"},"page":"http://ruman.com/prebid_server_test.html","ref":"http://ruman.com/prebid_server_test.html"},"device":{"w":1384,"h":128},"regs":{"ext":{"gdpr":0}}}

This is our response come from server

{
	"id": "cc017d99-4193-4ba5-8bef-f1cdd941549f",
	"seatbid": [],
	"cur": "USD",
	"nbr": 0,
	"ext": {
		"debug": {
			"httpcalls": {
				"improvedigital": [
					{
						"uri": "http://ad.360yield.com/pbs",
						"requestbody": "{\"id\":\"cc017d99-4193-4ba5-8bef-f1cdd941549f\",\"imp\":[{\"id\":\"/22696859215/Adzspectestad1\",\"banner\":{\"format\":[{\"w\":300,\"h\":250}]},\"ext\":{\"data\":{\"pbadslot\":\"/22696859215/Adzspectestad1\"},\"bidder\":{\"placementId\":22747501}}}],\"site\":{\"domain\":\"ruman.com\",\"page\":\"http://ruman.com/prebid_server_test.html\",\"ref\":\"http://ruman.com/prebid_server_test.html\",\"publisher\":{\"id\":\"333\",\"domain\":\"ruman.com\"},\"ext\":{\"amp\":0}},\"device\":{\"ua\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0\",\"h\":128,\"w\":1384},\"test\":1,\"at\":1,\"tmax\":3000,\"cur\":[\"USD\"],\"source\":{\"tid\":\"2b1cfea5-dca8-40c9-a183-8137b24f510f\"},\"regs\":{\"ext\":{\"gdpr\":0}},\"ext\":{\"prebid\":{\"debug\":1,\"targeting\":{\"pricegranularity\":{\"precision\":2,\"ranges\":[{\"max\":20,\"increment\":0.1}]},\"includewinners\":true,\"includebidderkeys\":false},\"cache\":{\"vastxml\":{\"returnCreative\":false}},\"auctiontimestamp\":1666615320454,\"channel\":{\"name\":\"pbjs\",\"version\":\"v6.29.0\"},\"pbs\":{\"endpoint\":\"/openrtb2/auction\"},\"server\":{\"externalurl\":\"http://localhost:8080\",\"datacenter\":\"local\"}}}}",
						"responsebody": "",
						"requestheaders": {
							"Accept": [
								"application/json"
							],
							"x-prebid": [
								"pbjs/v6.29.0",
								"pbs-java/1.102.0"
							],
							"Content-Encoding": [
								"gzip"
							],
							"Content-Type": [
								"application/json;charset=utf-8"
							]
						},
						"status": 204
					}
				]
			},
			"resolvedrequest": {
				"id": "cc017d99-4193-4ba5-8bef-f1cdd941549f",
				"imp": [
					{
						"id": "/22696859215/Adzspectestad1",
						"banner": {
							"format": [
								{
									"w": 300,
									"h": 250
								}
							]
						},
						"ext": {
							"data": {
								"pbadslot": "/22696859215/id"
							},
							"prebid": {
								"bidder": {
									"improvedigital": {
										"placementId": 12345
									}
								}
							}
						}
					}
				],
				"site": {
					"domain": "ruman.com",
					"page": "http://ruman.com/prebid_server_test.html",
					"ref": "http://ruman.com/prebid_server_test.html",
					"publisher": {
						"id": "333",
						"domain": "ruman.com"
					},
					"ext": {
						"amp": 0
					}
				},
				"device": {
					"ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0",
					"h": 128,
					"w": 1384
				},
				"test": 1,
				"at": 1,
				"tmax": 3000,
				"cur": [
					"USD"
				],
				"source": {
					"tid": "2b1cfea5-dca8-40c9-a183-8137b24f510f"
				},
				"regs": {
					"gdpr": 0
				},
				"ext": {
					"prebid": {
						"debug": 1,
						"targeting": {
							"pricegranularity": {
								"precision": 2,
								"ranges": [
									{
										"max": 20,
										"increment": 0.1
									}
								]
							},
							"includewinners": true,
							"includebidderkeys": false
						},
						"cache": {
							"vastxml": {
								"returnCreative": false
							}
						},
						"auctiontimestamp": 1666615320454,
						"channel": {
							"name": "pbjs",
							"version": "v6.29.0"
						},
						"pbs": {
							"endpoint": "/openrtb2/auction"
						},
						"server": {
							"externalurl": "http://localhost:8080",
							"datacenter": "local"
						}
					}
				}
			}
		},
		"responsetimemillis": {
			"improvedigital": 1292
		},
		"tmaxrequest": 3000,
		"prebid": {
			"auctiontimestamp": 1666615320454
		}
	}
}

Anyone setup the localhost then please help us.
<img width="1440" alt="Screenshot 2022-10-24 at 5 36 33 PM" src="https://user-images.githubusercontent.com/108808183/197527244-c82c50b7-c0cb-4427-bbba-d608581e1286.png">

**Comment by bretg** [comment]
@rumanali123 - this is not a Prebid Server problem... improvedigital isn't bidding on the test request.  Please notice the request went to their endpoint and they returned with HTTP 204. I recommend using debug mode in [Professor Prebid](https://docs.prebid.org/tools/professor-prebid.html) to fake a bid.

**Comment by rumanali123** [comment]
Thank you for your response
we understand your answer but now we are using appnexus bidder and we enable the adapter in java server.

![Screenshot 2022-10-25 at 3 50 06 PM (2)](https://user-images.githubusercontent.com/108808183/197755378-d44c55aa-755f-4fe7-b4bc-2bf273da3105.png)

but we getting same issue we enable the test and debugging true but didn't solve this.Here is our s2s config:
         pbjs.setConfig({
                "ortb2": {
                    "test": 1,
                    "regs": {
                        "ext": {
                            "gdpr": 0
                        }
                    },
                },
                debug: true,
                s2sConfig: {
                    adapter: 'prebidServer',
                    testing: true,
                    // endpoint: "https://prebidserver.adzspec.com/openrtb2/auction",
                    endpoint: "http://ruman.com:5000/openrtb2/auction",
                    enabled: true,
                    accountId: '333',
                    bidders: ['appnexus'],
                    timeout: 3000,
                    extPrebid: {
                        cache: {
                            vastxml: { returnCreative: false }
                        },
                    }

                }
            });
            
![Screenshot 2022-10-25 at 3 53 34 PM (2)](https://user-images.githubusercontent.com/108808183/197755612-bfd5e399-a241-43d7-ba79-2ba4eaac080c.png)

**Comment by rumanali123** [comment]
locally ad is working now
Thank you for your help
