### ISSUE TITLE
Ftrack eid object incorrectly formatted

### ISSUE THREAD

**Issue by mmoschovas** [prebid/Prebid.js#9159]
## Type of issue
Bug

## Description
createEidsArray method should return an array of objects with the format:
```
[{
    source: 'IDSYSTEM_SOURCE_NAME',
    uids: [...]
}]
```
where uids is an array of id data. Currently, the ftrack module returns the id data only without source/uids properties as seen below:

```
[{
    atype: 1,
    ext: {
        HHID: 'HHID', 
        DeviceID: 'DEVICEID', 
    },
    id: 'VALUE'
}]
```

## Steps to reproduce
  Run `pbjs.getUserIdsAsEids()` with ftrackIdSystem configured

**Comment by mmoschovas** [comment]
@ftxmoJason can you review the above issue please when you have a moment

**Comment by ftxmoJason** [comment]
Thanks @mmoschovas . Please see: https://github.com/prebid/Prebid.js/pull/9174 and let us know if we missed the mark, thanks.
