### ISSUE TITLE
Console error for rejected bids due to allowAlternateBidders functionality

### ISSUE THREAD

**Issue by pm-azhar-mulla** [prebid/Prebid.js#9161]
## Type of issue

Bug
## Description

With the latest upgrade of Prebid i.e: 7.23, we have observed that when a bid is rejected due to allowAlternateBidders functionality, an error is displayed on the console.
I am attaching a screenshot for the same.
And similar error is displayed for unknown bidder request too.

<img width="629" alt="Screenshot 2022-10-28 at 3 47 32 PM" src="https://user-images.githubusercontent.com/75726247/198564742-6c4a0906-e112-4303-a5d3-65451a2cf32c.png">

@dgirardi @patmmccann 
This error could be due to the [new bid rejected change](https://github.com/prebid/Prebid.js/commit/5e18b2dce96549b9d340d1380d048561e780de61#diff-19e083f295429e0a1c8f60f4a92c2025a5ef578cb674e108ef80c0426d99543c)

Possible stack trace for the issue : 

- [allowAlternateBidder scenario](https://github.com/prebid/Prebid.js/blob/master/src/adapters/bidderFactory.js#L267)
- [unknown bidder request scenario](https://github.com/prebid/Prebid.js/blob/master/src/adapters/bidderFactory.js#L278) 

## Steps to reproduce

- A test page with allowedAlternateBidders configured
- A test bid for extra bid, where this extra bid will be rejected.

### Expected results
A bid should be rejected without any error message.
### Actual results
An error message is displayed on console.

**Comment by dgirardi** [comment]
The issue does not seem related to alternate bidders; rather, the exception happens if the adapter replies with an invalid `requestId`. I'm posting a fix for that, if it sounds like I missed some of the problem, please provide a test page and steps to reproduce.
