### ISSUE TITLE
Receiving empty requests on the GumGum adapter endpoint

### ISSUE THREAD

**Issue by davidmh** [prebid/Prebid.js#917]
## Type of issue
Question/possible bug?

## Description
We've been receiving a considerable amount of requests without populated query parameters. On the past 24 hours, it was around 17k.

### Expected results
Since the only entry point for that request is bound to our adapter, we shouldn't receive empty requests.

### Actual results
Empty parameters on some requests

## Other information
The only thing I can think of is a scenario where `utils.parseQueryStringParameters` is not returning the correct string.

**Comment by davidmh** [comment]
CC: @anirban-roy

**Comment by mkendall07** [comment]
Can you add more detail please? Are you talking about DFP requests, adapter requests? Which adapter?

**Comment by davidmh** [comment]
My bad, adapter requests for GumGum, I'll update the description.

**Comment by mkendall07** [comment]
@davidmh 
Are you validating correct bid params in the adapter?

**Comment by davidmh** [comment]
@mkendall07 [yes](https://github.com/prebid/Prebid.js/blob/master/src/adapters/gumgum.js#L51), we should receive at least `pi && (t || ni)`

**Comment by davidmh** [comment]
Any ideas about this?

We've gathered a few user agents from the logs, Other than most of them coming from Windows 10, I can't see a real pattern.

- Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
- Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
- Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
- Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
- Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
- Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by mkendall07** [comment]
Not really sure what we can do for you on this. Anyone could hit that enpdoint, doesn't have to be from prebid.js. Please verify there isn't any issues with the validation in your adapter in prebid.js

**Comment by davidmh** [comment]
@mkendall07 understandable, we're just trying to exhaust all the possibilities. I doubt it's validation issue, not only because we don't do the request [if the product parameter](https://github.com/prebid/Prebid.js/blob/master/src/adapters/gumgum.js#L50) is missing, but also because we're expecting values that don't depend on user input, like [window properties](https://github.com/prebid/Prebid.js/blob/master/src/adapters/gumgum.js#L25).

For the time being, we're going to consider those empty requests as crawler hits, and ignore them. I'll close this issue.

Thank you for looking into it.
