### ISSUE TITLE
window.pbNativeTag.renderNativeAd(pbNativeTagData) method corrupts sizes of GPT div and iframe

### ISSUE THREAD

**Issue by opskn** [prebid/Prebid.js#9171]
## Type of issue
Bug

## Description
Hello, When I try to render native ad with custom rendering code, GPT ad dvi and Ad Iframe sizes changing and corrupts ad view.
Native style&format I used to show prebid campaigns is very similar to other styles which I used to show standadrd and Adx campaigns. 

My Prebid Native Format as follows;
![image](https://user-images.githubusercontent.com/24359653/198856223-2a2b3692-e25d-4a7c-88e5-147f6b276e33.png)

My Prebid Native linked to Native Format As Follows;
![image](https://user-images.githubusercontent.com/24359653/198856263-1c445510-2426-454c-aa59-5a1e1274a8c7.png)
Also has a css;
body {
  background-color: #fff;
  font-family: 'Roboto' , sans-serif;
  font-size: 12px;
}

.attribution {
  background-color: #FFF;
  border-radius: 2px;
  box-shadow: 0px 1px 2px rgba(0,0,0,.5);
  font-size: 13px;
  left: 4px;
  padding-left: 3px;
  padding-right: 3px;
  position: absolute;
  top: 4px;
}

.title {
  padding-bottom: 4px;
  padding-left: 8px;
  padding-right: 8px;
  padding-top: 6px;
}

.title a {
  color: #212121;
  font-size: 17px;
  font-weight: 500;
  text-decoration: none;
}

.body {
  border-bottom: 1px solid #ddd;
  padding-bottom: 6px;
  padding-left: 8px;
  padding-right: 8px;
}

.body a {
  color: #777;
  font-size: 11px;
  line-height: 1.4;
  text-decoration: none;
}

.image {
  display: flex;
  width: 100%;
}

.image img {
  width: 100%;
}

.image .image-link {
  height: 100%;
  width: 100%;
}

.call-to-action {
  float: right;
  border: 1px solid #4285F4;
  border-radius: 5px;
  padding:5px;
  right:5px;
	bottom:10px;
  position:relative;
}

.call-to-action a {
  color: #4285F4;
  font-size: 14px;
  font-weight: 500;
  text-decoration: none;
  text-transform: normal;

}

.logo {
  display: flex;
  float: left;
  height: 22px;
  padding-bottom: 8px;
  padding-left: 8px;
  padding-right: 7px;
  padding-top: 8px;
  width: 22px;
}

.logo img {
  height: 100%;
  width: 100%;
}

.logo .logo-link {
  height: 100%;
  width: 100%;
}

.advertiser {
  float: left;
  padding-bottom: 4px;
  padding-left: 8px;
  padding-right: 8px;
}

.advertiser a {
  color: #777;
  font-size: 11px;
  letter-spacing: .2px;
  text-decoration: none;
}

Custom Render Script also as follows,
![image](https://user-images.githubusercontent.com/24359653/198856332-adc00dd2-d4b6-4548-88b5-07d8ab615ee9.png)

Adx&Standard Native Style is as follows with same css with Prebid Native Style;
![image](https://user-images.githubusercontent.com/24359653/198856304-587685cc-757c-476b-bbb0-3fdeaef20298.png)

## Steps to reproduce
  When prebid campaign wins auction and starts I see, very big or very small GPT ad div and GPT ad iframe sizes such as width2000px, or width 23px.

But when I change the creative and remove  window.pbNativeTag.renderNativeAd(pbNativeTagData) method, GPT divs and iframes sizes seems properly. Of course in this case creative doesn't render properly. 

When I change creative to as follows for only testing purposes, every GPT div and iframe sizes seems ok. (As can you can see in this sample creative, title, image, etc. params replaced hardcoded for only testing purposes.) 
![image](https://user-images.githubusercontent.com/24359653/198856719-bb30182f-3d8b-4bea-a0bb-8120ef9405d0.png)
![image](https://user-images.githubusercontent.com/24359653/198856827-6d418618-7d5e-4754-aa96-2580e56b1a96.png)

## Test page
You can see sample ad unit to check this problem.
https://predatasrv.com/works/native_desktop2.html?mobile=1

Why native-render.js changes size of google ad divs/iframes sizes?

Note:Sorry for bad explanation, first time to ask a question :(

**Comment by dgirardi** [comment]
@opskn, I am having some trouble reproducing. First, could you confirm that this issue happens on version 1.13 of [PUC](https://github.com/prebid/prebid-universal-creative)? There was a recent release that I'd like to rule out as the cause. I believe you are currently using a custom build of 1.14:

![image](https://user-images.githubusercontent.com/10151381/199042892-4947ee4d-6d6d-40b9-b3d5-05b7611f9631.png)

Then, if try https://predatasrv.com/works/native_desktop2.html?mobile=1 , every ad looks correct to me, but I don't think it's actually going through the "normal" rendering and using AMP instead. if I remove `mobile=1` I see this:

![image](https://user-images.githubusercontent.com/10151381/199043420-6be7ced0-85c0-4d8e-b3eb-58642a26974b.png)

I am not sure that's the issue you describe in the OP, it looks like a test that does not call `renderNativeAd`.

Is there a test page that shows the incorrectly sized creatives? Or did I miss it?

**Comment by ChrisHuie** [comment]
@musikele tagging you so you are aware of this issue.

**Comment by musikele** [comment]
@opskn I can't even open the test links, they return 404. 

@dgirardi even though I can't see the bug in effect, I think it's related with a line of code that I thought it was "smart" and was released in 1.14. Ideally that code should resize the ad to expand to the size of the container. In reality, it doesn't.  

in separate_puc MR we corrected this behavior to not happen with safe frames (the scenario of the OP), so the fix is merged, but not yet released I guess. 

The line of code i believe is causing the issue: 
https://github.com/prebid/prebid-universal-creative/commit/0d0ef0466cda24a6db14f18255da7c2d77b5c22e#diff-8938ddbc8ffb985e7aeb3744e592068ea58501c022a222cb7507aabef70f8080L379 

file nativeAssetManager.js , line 378-379

**Comment by opskn** [comment]
Hello everyone,
Sorry about late response.
As you mentioned, 1.13 version solves the problem. :)
Currently, I get correct iframe width and heights.
Thank you so much for your help
Bests,Osman 
    On Monday, November 7, 2022 at 07:20:07 PM GMT+3, Chris Huie ***@***.***> wrote:  
 
 


@musikele tagging you so you are aware of this issue.

**Comment by opskn** [comment]
Hello @dgirardi, 1.13 works for me.
Thanks
