### ISSUE TITLE
Feature request: option to timeout CMP interaction and readiness independently

### ISSUE THREAD

**Issue by EskelCz** [prebid/Prebid.js#9176]
## Type of issue
Feature request, probably

## Description
Some of our publishers would like to run auction as soon as possible, without waiting for user interaction with the CMP banner. We do this by setting `consentManagement.gdpr.timeout: 0`.
This works fine if the CMP manages to load in time to provide stored consent. If it doesn't, prebid sends tcString `undefined`.
I think the issue is that the timeout intermingles two time intervals relevant for different use cases.

1. The CMP being ready (to provide stored tcString from cookie, if available)
2. The user`s action (to provide new consent)

We would like to propose separating it into these two distinct timeouts. Something like `cmpTimeout` and `actionTimeout`.

We can work around this by checking the CMP readiness ourselves before calling pbjs.requestBids but I think it would be cleaner if this was supported by Prebid configuration itself. Possibly also helpful to others.

## Platform details
Latest Prebid 7.23.0

## Other information
The behavior might have been caused by this change: https://github.com/prebid/Prebid.js/pull/8524

**Comment by patmmccann** [comment]
Your proposal sounds reasonable to me. So by default we would have the current behavior, but if actionTimeout exists, we would have the new behavior. Sound right?

**Comment by EskelCz** [comment]
@patmmccann Might be a bit confusing but I understand that you need to retain backward compatibility. So I guess it's reasonable.
