### ISSUE TITLE
How to configure Prebid server-side (s2sConfig) to pass keywords to the auction server

### ISSUE THREAD

**Issue by jon-caines-idward** [prebid/Prebid.js#9188]
## Type of issue
question

## Description
I wish to pass keywords through to the auction server for the SSP bid adapter(s)to use, but cannot see this in the existing documentation. An example of a similar working approach but which is client-side is supplied below.

## Steps to reproduce
None known

## Test page
Example of the client-side configuration (pbjs.setConfig) that achieves this:
pbjs.setConfig({
  appnexusAuctionKeywords: {
    genre: ['classical', 'jazz'],
    instrument: 'piano'
  }
});

### Expected results
Ability to send keywords to the auction server in order to pass through to SSP bid adapter(s)

## Platform details
Server - s2sConfig

**Comment by dgirardi** [comment]
`appnexusAuctionKeywords` seems to be an appnexus-specfic name for various ortb2 `keywords` properties:

https://github.com/prebid/Prebid.js/blob/b762241b59a4f9850d40f1f249608bddc490d1d7/modules/appnexusBidAdapter.js#L251-L260

Using your example, it seems to be equivalent to setting:

```
pbjs.setConfig({
   ortb2: {
      site: {
          keywords: 'genre=classical, genre=jazz, instrument=piano'
      }
   }
})
```

(or alternatively, `pbjs.requestBids({ortb2: {...}})`)

ORTB2 properties are sent over to PBS, so if the server-side appnexus logic does the same `key=value` interpretation it should have the same effect. (@jsnellbaker does that sound right?)

**Comment by jsnellbaker** [comment]
@dgirardi I believe that sounds right, but they should consult with the team prebid server team(s) maintaining appnexus adapter (depending on which hosting company they're planning to use).  They can confirm which ortb2 field best matches what they want to pass.

**Comment by bretg** [comment]
@jon-caines-idward - thank you. This is an excellent advertisement for publishers switching to the [standard First Party Data representation](https://docs.prebid.org/features/firstPartyData.html) that we've been working on for the past two years. In the old days, each bidder had specific parameters for passing data and publishers had to convert their data to a myriad of formats for their various bidders. Now, pubs can expect that every bidder will accept the standard `ortb2`-style data definition.

For your specific case, I would suggest
```
pbjs.setConfig({
   ortb2: {
      site: {
         ext: {
             data: {
                 genre: ['classical', 'jazz'],
                 instrument: 'piano'
              }
           }
       }
   }
});
```
Or, if you only want appnexus to receive this data, then the bidder-specific way would be:
```
pbjs.setBidderConfig({
   bidders: ["appnexus"],
   config: {
       ortb2: {
          site: {
             ext: {
                 data: {
                     genre: ['classical', 'jazz'],
                     instrument: 'piano'
                  }
              }
           }
       }
   }
});
```

Looping in @SyntaxNode to confirm that the appnexus PBS adapter (both Go and Java) support passing site.ext.data as equivalent to this old client-side 'appnexusAuctionKeywords' feature.

**Comment by jon-caines-idward** [comment]
Thank you for the feedback and apologies that I may have inadvertently posted this in prebid.js instead of prebid server. I am seeking examples of keywords being passed using s2sConfig. We are a madtech vendor supplying privacy-compliant cookie-less anonymised cohorts into the bid-stream as keywords. We have the prebid.js config clear, we are now exploring Server Side integration for some of our clients. Documentation on keyword support server side is sparse.

**Comment by bretg** [comment]
@jon-caines-idward - if you're gathering the parameters with Prebid.js, then this isn't the wrong forum.

I'm not sure we're on the same page about what "keywords" means.

There's the OpenRTB sense of 'keyword' which is simply a comma-separated string.

```
site.keywords: "technology, news"
```

And then there's what Prebid calls "First Party Data", which is key-value pairs. See https://docs.prebid.org/features/firstPartyData.html

Based on the example you posted, I think you're more interested in FPD than in "keywords". 

But in any case, Prebid Server does not support weird bidder-specific ways of passing first party data. Unfortunately, what it means is that each of the ~150 server-side adapters has to fully support reading First Party Data and passing it to their endpoint appropriately. 

This is where @SyntaxNode can confirm... Scott, does the app nexus server-side adapter support First Party Data in the same way as the old client-side "appnexusAuctionKeywords" so that Jon's use case will work end-to-end? Apparently he's been given some documentation that needs to be updated to a tandard first party data approach.

**Comment by jon-caines-idward** [comment]
@bretg Thank you for your continued interest and support. By keywords, I mean key-values. Our solution passes anonymised cohort ids as a string array. An example of passing these, using prebid.js, to the appnexus bidder is:
`           var cohortIds = localStorage.getItem('<defined key>');
            pbjs.que.push(function() {
            pbjs.setConfig({
                debugging: {
                    enabled: true
                },
                appnexusAuctionKeywords: {
                    perid: 
                        cohortIds ? JSON.parse(cohortIds) : []
                }
            });
                pbjs.addAdUnits(adUnits);
                pbjs.requestBids({
                    bidsBackHandler: initAdserver,
                    timeout: PREBID_TIMEOUT
                });
            });
`
I am exploring how this can be replicated across other configurations including Prebid Server whilst exploring bidder support from SSP's. Whether this is RTD, FPD etc remains to be seen/discovered. Any assistance or advice would be welcome.

**Comment by patmmccann** [comment]
cohort ids about users should be passed on user.data; cohort ids on content should pass on site.content.data with the same link above as an example https://docs.prebid.org/features/firstPartyData.html

**Comment by jon-caines-idward** [comment]
Thanks @patmmccann, just a note, our cohort ids are about cohorts not users, part of the anonymisation.

**Comment by patmmccann** [comment]
Closing as complete, OP: pls open and explain if there's remaining questions
