### ISSUE TITLE
Why is 0.17.0 still not available on the download page?

### ISSUE THREAD

**Issue by joyofdata** [prebid/Prebid.js#922]
Is there a reason for why 0.17.0 is tagged already since 4 weeks but not yet available on the download page?

Is 0.17.0 ready for production?

**Comment by mkendall07** [comment]
We just got behind on updating. No particular reason. We'll update directly to 0.18.0 which will be released in a few days.

**Comment by matthewlane** [comment]
0.18.0 is now available on the [download page](http://prebid.org/download.html)
