### ISSUE TITLE
can i get the value price of all loosing bidds? (except the price of the winner bid)

### ISSUE THREAD

**Issue by sinairofe** [prebid/Prebid.js#924]

**Comment by matthewlane** [comment]
You can use [`pbjs.getBidResponses()`](http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.getBidResponses), and then from this, remove any bid objects returned by [`pbjs.getHighestCpmBids()`](http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.getHighestCpmBids). The remaining set will be all bids except the wining bids.

**Comment by protonate** [comment]
Closing as answered, please reopen if further questions.
