### ISSUE TITLE
Prebid Version Issues

### ISSUE THREAD

**Issue by mmprebid** [prebid/Prebid.js#9269]
I have a question: our bidder adapter is in a higher version of Prebid.js, and the publisher is using a lower version of Prebid.js. Can we upgrade our bidder adapter into legacy branches? if yes then where we can see legacy release? Thank you, looking forward to your reply.

**Comment by patmmccann** [comment]
You can commit to legacy branches, but we don't plan to release them. A publisher would then need to build from the unreleased legacy branch.

**Comment by patmmccann** [comment]
as fyi, the legacy branch for 6.x is https://github.com/prebid/Prebid.js/tree/6.29.x-legacy
