### ISSUE TITLE
Prebid returns different types of CPM after 7.20.0 update

### ISSUE THREAD

**Issue by LukaszSawicki** [prebid/Prebid.js#9271]
## Type of issue
bug

## Description
After update 7.20.0, more specifically after https://github.com/prebid/Prebid.js/pull/9013 change value of returned cpm in bid object is sometimes string, sometimes float. Before update value was always returned as float. It can cause errors in code.

The code responsible for this is in the file: https://github.com/dgirardi/Prebid.js/blob/master/src/auction.js.

Line before change:
`cpm: parseFloat(bid.cpm) || 0,`

Line after change:
`cpm: bidResponse.cpm || parseFloat(bidResponse.cpm) || 0,`

## Platform details
Prebid 7.20.0

**Comment by dgirardi** [comment]
Thanks for catching this! Fix is in https://github.com/prebid/Prebid.js/pull/9273, and this is a workaround in the meanwhile:

```
pbjs.onEvent('bidResponse', (bid) => {
    bid.cpm = parseFloat(bid.cpm) || 0;
})
```
