### ISSUE TITLE
Bid Adapters not using the floors convention

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#9275]
## Type of issue
enforcing a convention

## Description
The following bid adapters are accepting a floor as a bidder-specific parameter without calling the getFloors() function:

- [x] alkimi @kalidas-alkimi 
- [x] cleanmedianet @sa1omon 
- [x] datawrkz @vishal-dw 
- [x] ebdr @jlzhangdev 
- [x] impactify @thomasdseao 
- [x] iqm @Params10 
- [x] lkqd @david-carver 
- [x] madvertise @NLopezMad 
- [x] mytarget @Denislavrov 
- [x] nexx360 @gchicoye 
- [x] quantcast @SleimanJneidi 
- [x] taboola @ahmadlob 
- [x] truereach @mmprebid 
- [x] vdoai @cpuBird 
- [x] vidoomy @sasanfarokh 

Please look in other bid adapters for how the `bidrequest.getFloor()` function is utilized.

**Comment by gchicoye** [comment]
Hi @bretg , I've submitted 2 weeks ago a pull request (https://github.com/prebid/Prebid.js/pull/9229) which fixes that, I'm waiting for the approval!

**Comment by patmmccann** [comment]
tagging 9.0 to boot non-compliant adapters

**Comment by kalidas-alkimi** [comment]
@bretg    Alkimi Bid Adapter : We have fixed this issue long before and the changes merged. Please check the below pull request. Please let me know if we still missing anything.

https://github.com/prebid/Prebid.js/pull/9368

**Comment by patmmccann** [comment]
vidoomy and cleanmedia are fine
