### ISSUE TITLE
How to tell if a bid won the Prebid auction, but lost the dfp/gpt one.

### ISSUE THREAD

**Issue by michelangelo246** [prebid/Prebid.js#9276]
## Type of issue
Question.

## Description
What is the most **reliable** way to tell if a bid has won the Prebid auction but lost the ad server (e.g. dfp/gpt) auction afterward?
In that case, the bid simply keeps the "targetingSet" status instead of changing it to "rendered"?

I am registering to googletag's slotRenderEnded event and looking if there are any bids with the "targetingSet" status. If a bid has this status after the slotRenderEnded event, is it correct to assume it did win the Prebid's auction but lost the dfp/gpt one?

Does the provided answer take into account different gpt integration examples (e.g. https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/x-domain/creative.html) regarding reliability?

Best regards,

**Comment by dgirardi** [comment]
I suspect this could be calculated within GAM, which would undoubtedly be the most reliable method - but I am not knowledgeable enough to suggest how (@patmccann?)

> If a bid has this status after the slotRenderEnded event, is it correct to assume it did win the Prebid's auction but lost the dfp/gpt one?

When a safeframe renders a Prebid bid, it sends a `postMessage` to mark it as `'rendered'` in Prebid - which I think may happen _after_ GPT fires `slotRender`. So my strategy would be to use the [slotOnLoad GPT event](https://developers.google.com/publisher-tag/reference#googletag.events.SlotOnloadEvent) instead, and add some time buffer - say 500ms - before checking the bid status. 

Unfortunately I don't think `postMessage` makes any guarantee on how quickly the browser will move the messages, but 500ms is glacial speed, so if the bid is still not 'rendered' after that it should be safe enough to assume it wasn't.

**Comment by michelangelo246** [comment]
I see.

Thanks for the quick reply. I believe I will stick with the timeout approach then, 500ms seems good to me too.

**Comment by patmmccann** [comment]
Most simple way is to know a list of prebid orders and compare the order id from slot render ended to that list.

**Comment by patmmccann** [comment]
closing based on the thumbs up, reopen if anything else to discuss, thanks!
