### ISSUE TITLE
Various adapters: tmax bug 

### ISSUE THREAD

**Issue by ilapshyn** [prebid/Prebid.js#9287]
## Type of issue
Question

## Description
If timeout is set on auction level instead of global 'bidderTimeout' and it's lower than default value then some bidders (IX, Sharethrough and others) still send global value as 'tmax'. 
Could it affect bidder performance?

## Steps to reproduce
global 'bidderTimeout' not set (prebid uses default value 3000)
auction timeout is set to 2500
some bidders still send 3000 in tmax field

## Platform details
Version: 7.21

## Other information
https://github.com/prebid/Prebid.js/issues/8973 - partially mentioned here

**Comment by patmmccann** [comment]
Each of those adapters has a bug

**Comment by patmmccann** [comment]
Axonix, beyond, many others

**Comment by patmmccann** [comment]
Also @TheMediaGrid has this bug, doing incorrect math to find the tmax

**Comment by TheMediaGrid** [comment]
> Also @TheMediaGrid has this bug, doing incorrect math to find the tmax

Hello! Please specify where this bug is? There is a line in our gridBidAdapter where we only use a lower value of timeout.

**Comment by patmmccann** [comment]
> > Also @TheMediaGrid has this bug, doing incorrect math to find the tmax
> 
> Hello! @patmmccann Please specify where this bug is? There is a line in our gridBidAdapter where we only use a lower value of timeout. https://github.com/prebid/Prebid.js/blob/master/modules/gridBidAdapter.js#L98

You should only use the value from the bidRequest, not the lower of the two.

**Comment by TheMediaGrid** [comment]
> > > Also @TheMediaGrid has this bug, doing incorrect math to find the tmax
> > 
> > 
> > Hello! @patmmccann Please specify where this bug is? There is a line in our gridBidAdapter where we only use a lower value of timeout. https://github.com/prebid/Prebid.js/blob/master/modules/gridBidAdapter.js#L98
> 
> You should only use the value from the bidRequest, not the lower of the two.

Thank you, fixed - https://github.com/prebid/Prebid.js/pull/9339

**Comment by patmmccann** [comment]
Closing in favor of #9705
