### ISSUE TITLE
priceFloor does not pass bid to bidCpmAdjustment

### ISSUE THREAD

**Issue by renebaudisch** [prebid/Prebid.js#9312]
## Type of issue
Object in parameter 2 passed to user-defined bidCpmAdjustment has insuffient parameters

## Description
E.G. bid.bidder ist therefore undefined, but should be accessible regarding the [doc](https://docs.prebid.org/dev-docs/publisher-api-reference/bidderSettings.html#22-bidcpmadjustment)

![image](https://user-images.githubusercontent.com/15980546/205307029-4ffc6faa-abd1-4dfe-96e8-d042dbd526a2.png)

`function getFloor` does not pass the bid as third parameter like `addBidResponseHook` does,
so it falls back to `{}` only holding the `cpm`.

## Steps to reproduce
to trigger `getFloor` and `bidCpmAdjustment` you need to configure a custom floor price schema and bidderSettings per bidder. Then just `console.log(arguments)` in your `bidCpmAdjustment` function.

## Test page
https://www.wieistmeineip.de/

### Expected results
get the hole bid data

### Actual results
only get property `cpm`

## Platform details
independent

**Comment by patmmccann** [comment]
@robertrmartinez could you take a look?

**Comment by dgirardi** [comment]
This is a tricky one. The issue is that the floors module attempts to adjust the _request_ floor, when there is no bid yet. I believe the idea is that if you set a given floor, but we know that some bidders will get their cpm adjusted, then the floor should be adjusted as well before it's sent out to SSPs, or you risk asking them to bid too low.

As a workaround, in your case specifically, you could use `bidder` from the outer scope instead of looking into the second argument.

**Comment by renebaudisch** [comment]
But the problem only occurs by using custom floors schema, so the bidders need to call getFloor. If you use a standard schema different arguments will be passed. To be exact, then you get the data as described in the [documentation](https://docs.prebid.org/dev-docs/publisher-api-reference/bidderSettings.html#22-bidcpmadjustment)...

Looking at the example I should get bidCpm and bid, which is true for standard schema, but not for custom scheme.

**Comment by dgirardi** [comment]
the adjustment is also calculated later on the actual bid cpm, to make sure it's satisfied - I believe that's why you may see the second parameter filled out sometimes. I don't think it's related to the schema unless you mean the `enforcement.bidAdjustment` flag. If not, could you provide steps to reproduce - what should I look for in the page you linked in the OP?

**Comment by renebaudisch** [comment]
There is a `prebid.{HASHVALUE}.js` on the testpage.
Here we use a custom scheme as shown in the second screenshot at the left side.
Right now there I only get the property "cpm" inside the bid object:

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/15980546/207944924-4773157b-13db-4492-b858-8ff839a6ea08.png">

If I do this change in my setup:

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/15980546/207944048-0647fabc-5a98-4cd2-8084-f981fb361aab.png">

I get a full bid object with all properties instead:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/15980546/207944229-f9b72acb-6e80-4865-8ffa-9cd670e51654.png">

<img width="387" alt="image" src="https://user-images.githubusercontent.com/15980546/207945428-1ca7227f-28d4-4c29-a348-0066875a1983.png">

**Comment by dgirardi** [comment]
As it turns out, specifying `adUnit.floors` without `schema` silently disables the floors module (I am a bit surprised by this, I think we should issue a warning). So in that sense it's true that the schema is the culprit - but only because that's how you turn on floors. You should see that the bid you get, when you get it, does not have a "floorData" property, and no floor was set in the request.

The call to `bidCpmAdjustment` you see is the "normal" one done at the end of the auction; it's not related to floors.

**Comment by renebaudisch** [comment]
Ah, I see, I get a lot more calls to `bidCPMAdjustment` when using my floors schema then without.
But it is called `bidCPMAdjustment`, why is it called for floors?
It is not `generalCPMAdjustment` or `bidAndFloorCPMAdjustment`...

**Comment by dgirardi** [comment]
I don't mind the name so much, after all, cpm and a cpm floor are not that wildly different... but I think it is a problem that we can't always pass the second argument.

I think the actions here are:

- update the floors module to warn when schema fails validation (or is missing)
- update the documentation to make it clear that the second arg is not always complete
- we can fill that argument a bit more when it's called without a bid. `bidderCode` for example is known even without it. I'm not sure what else would make sense in it - what is typically of interest when doing cpm adjustment?

**Comment by renebaudisch** [comment]
About the naming. I do not want to adjust the floorprice by bidder, but I want to adjust the bidCPM per bidder, so I do not want the function to be called for floors. Right now, I can assume, when there is only a `cpm` in `bid` it's coming from floorprice module, so I will do nothing.

But as I want to adjust bidCPMs only I think the better way would be adding an extra option for floors if this feature really is needed, so if someone wants to modify floors by bidder, he can define a `floorCPMadjustment` function, but as bidder isn't a regular field for floorprices, I do not think this is needed.

So while I now understood that the regular calls aren't affected and I just get additional cals, I think it's just wrong calling `bidCPMadjusment` in the floorprice module.

**Comment by dgirardi** [comment]
You can disable that feature by setting the  [`enforcement.bidAdjustment`](https://docs.prebid.org/dev-docs/modules/floors.html#schema-1) floors config flag to false. However, I think that means you would have to replicate that logic when you choose your floor values - the reason it's there is that if a cpm is to be adjusted, we attempt to make sure that the floor will be met after the adjustment.

**Comment by renebaudisch** [comment]
OK, that works. But then still the passed information is not good enough as the docs also state "per bidder" but if you don't pass the bidder the floorprice will be assigned to, one cannot separate a floor per bidder, like it is at the moment...

And, I also do not know what I'm I adjusting here. Is it the floor cpm the called the function or the bidResponse? What do I modify I do not know right know.

**Comment by dgirardi** [comment]
You'd have to define a custom schema field for the bidder code (using the `additionalSchemaFields` config), and provide for each bidder a floor value adjusted in the same way that bidder's cpm will be adjusted...

or you could just let the floors module do it. I don't think I understand why that is not an option for you; the logic in the OP would work if you replace `bid.bidderCode` with `bidder`.

**Comment by renebaudisch** [comment]
But I have defined a field `bidder` and therefore i'm setting floor per bidder, so I will set enforcement to false, because it is fine in my scenario. But 

But thinking of another scenario, using the same function for two different values and do not label it can be a problem.
Right know I do not know if the call to `bidCPMadjustment` is passing a floorprice or a bidResponses cpm value to decide if I need to adjust or not.

**Comment by dgirardi** [comment]
it is defined, you are referencing it on line 689. it's optimized away by the VM if you don't use it, so the debugger will not show it in scope; use it and it will work.

I don't think you should care if bidCpmAdjustment is being invoked with a floor or a cpm; if your idea is to adjust one and not the other, you will end up asking bidders for a floor that will, after adjustment, be too high or too low. If that's what you want, set enforcement.bidAdjustment to false and you're guaranteed to get a cpm. I think you're just making things harder for yourself but be my guest.

**Comment by bretg** [comment]
@renebaudisch - I think you're misunderstanding the purpose of floors being adjusted. This is a deliberate feature and, we believe, a requirement. Here's the scenario.

Say that you have a floor of 1.00 and that you want to lower a particular bidder's bid by 10% due to discrepancies.

If you tell this bidder that the floor is 1.00, they might bid 1.00, but then you multiply that bid by 0.9 as an adjustment and suddenly their bid is below the floor. So it gets thrown out.

The floors module on purposes raises the floor for this bidder so that after adjustment, their bid still meets your floor. In this case, it tells the bidder the floor is 1.11 so that if they bid that minimum, the result after adjustment still passes the floor test.

**Comment by renebaudisch** [comment]
I really forgot that when I register a function I will bind the vars from the construction scope o the function and if I do not use it there it will not be accessible, but sure, I can use `bidder` from the outerscope as I scope it while registering the function.

For the rest, I wasn't aware, that the floorprice module automatically recalculates the floor needed from the adjusted minimal bid. I testet the example and I saw, that the floorprice module then uses 1.00 and the returned 0.9 to calculate the adjusted floorprice to 1.11 by itself. That's awesome, I didn't expect that.
I thought I need to do this by myself and therefore differentiate the both calls. 

But even then I was missing the bidder in the second argument as stated in the docs and that was the initial intension to this issue. But also here, the calls from the floorprice module seems to be thought as 'internal calls' so I understand that this is not documented.
And I shouldn't use `enforcement.bidAdjustment` if I do not directly use adjusted floorprices per bidder in my floorprice setup.

So, the points presented by dgirardi are surely the right things to do

> I think the actions here are:
> 
> * update the floors module to warn when schema fails validation (or is missing)
> * update the documentation to make it clear that the second arg is not always complete
> * we can fill that argument a bit more when it's called without a bid. `bidderCode` for example is known even without it. 

Thank you very much for clearing my up!

**Comment by renebaudisch** [comment]
Quite cool. In my case, the lack of `bid.bidderCode` had the effect, that the floor hasn't been adjusted while the bidCPM has been for the bidder with adjustment. 
I also would think that by the call from getFloor there is no need for a bidResponse but the data from the actual bid that is build wouldn't harm and reduce the kind of misconfiguration I had.

One last thing, you mentioned
> As it turns out, specifying adUnit.floors without schema silently disables the floors module
As I use a schema I don't really care, but does that also need a further investigation?
