### ISSUE TITLE
Increase page load & some ad units hided after removing Prebid.js v6.11.0

### ISSUE THREAD

**Issue by indosport-admin** [prebid/Prebid.js#9315]
## Type of issue
Issue:
1. Increase page load that affect core web vital score
2. Some ad units undisplayed when I remove prebid.js

## Description
Desc:
As long as prebid.js installed in my code, it caused page load being longer and bad score for core web vital, then when I remove prebid.js code, it cause some ad units being hided from the web.

Prebid.js v6.11.0
![image](https://user-images.githubusercontent.com/82170150/205536550-7fb30d86-0c6d-4624-b46b-f92fc6061656.png)

## Steps to reproduce
I haven't found documentation about how to compress the source size, and also not hide any ad units after removing the script.
https://docs.prebid.org/prebid/prebidjs.html

**Comment by patmmccann** [comment]
You should not be using that script; 'not-for-prod.js'

Build prebid with only the modules you need

**Comment by indosport-admin** [comment]
So, I need to rebuild it for my own from this site https://docs.prebid.org/download.html ? 
and load the source locally. or where can I get cdn link of the production source?

**Comment by patmmccann** [comment]
That's correct, prebid does not provide a cdn, you should build or download with the modules you need, or use npm.
