### ISSUE TITLE
Is use of var MAX_RETRIES = 20; the optimal way to use Prebid ?

### ISSUE THREAD

**Issue by millieone** [prebid/Prebid.js#933]
## Type of issue
I submitted a documentation ticket as well but wanted to know what is the optimal way to implement Prebid. The prebid.org site says nothing about using 
var MAX_RETRIES = 20;

yet all the examples with the source code do. Up until now I had used the old method of prebid and want to update if possible.

**Comment by mercuryyy** [comment]
As far as i can tell, you have

var MAX_RETRIES = 20;
setTimeout(initAdserver, 50);

What this means is that every 50 seconds prebid will check if all bid are in and try to send it to dfp, it will loop that function for 20 times.  so in theory your on a 2000ms timeout but it will fire as soon as it has bid in. 

And i would leave it like that.

**Comment by mkendall07** [comment]
That's right. There is no "right" answer here, it's up to each publisher to figure out what works best for their sites. Unfortunately, that can differ quite a bit.

**Comment by millieone** [comment]
Thanks for the answers. They've been helpful.

I didn't phrase my initial question properly.

What I really was trying to say is that the basic example in the documentation http://prebid.org/dev-docs/examples/basic-example.html has nothing on "var MAX_RETRIES" at all.

Yet the suggested code on github implements the usage of "var MAX_RETRIES".

Regardless of what the value of "var MAX_RETRIES" is, I was trying to ask if this is a superior implementation than just using Instant Load example that doesn't use MAX_RETRIES at all. http://prebid.org/dev-docs/examples/basic-example.html

From what I can tell it is superior. I'm assuming without var MAX_RETRIES" and  "setTimeout(initAdserver, 50);" the setup just waits for the TIMEOUT to reach before sending anything to DFP. Is that correct?

**Comment by mkendall07** [comment]
On some pages that are slow to load inline content, we noticed a race condition against prebid refresh calls. So we added the `MAX_RETRIES` param to mitigate the issue. It's a safeguard against that issue, and we need to update the prebid.org examples.
