### ISSUE TITLE
Prebid Server Adapter Only Passes One Bid per Bidder

### ISSUE THREAD

**Issue by mmoschovas** [prebid/Prebid.js#9336]
## Type of issue

Bug - Prebid Server Bid Adapter

## Description

For some bidders, we need to define multiple bids on an ad unit to account for various cases like multiple mediatypes, sizes, high value, etc. For client side bidders, all valid bids are run at auction time, however, if the bidder is enabled to run via s2s, only the last defined bid in the bid array will be used for that bidder. The reason being that the PBS call constructs each bidder's bid as a single object, as opposed to an array of objects. So for a given bidder, the PBS adapter will keep overwriting the object until the last bid for said bidder, which will be the only bid for them sent in the request. 

## Steps to reproduce

1) Define multiple bids for a server side bidder on a given ad unit. 
2) Enable the bidder to run s2s
3) Initiate the auction and review the PBS auction call - only the last defined bid for the bidder will be sent to PBS

### Expected results
All valid bids on a single ad unit for a given bidder are sent to PBS

### Actual results
Only the last defined bid on a single ad unit for a given bidder is sent to PBS

**Comment by dgirardi** [comment]
I don't think this is supported by server; in the protocol bidders are unique within an ad unit (@bretg can you confirm)?
Possible workarounds are:

 - aliases (this should work now)
 - multiple requests - I'm not sure if this would cause issues downstream.
 
I don't like the discrepancy between client and s2s, but I'm not sure we want to do "clever" things like automatically aliasing duplicates from the adapter. I'm actually not seeing the use case clearly enough; aren't mediatypes and sizes are properties of the adunit? more in general wouldn't it be better to make it so you don't need to request multiple bids from the same SSP for the same adUnit?

**Comment by bretg** [comment]
PBS will ignore multiple duplicate entries in imp.ext.prebid.bidder, and that would be invalid ORTB.

Another workaround besides the ones dgirardi notes above is to utilize "twin ad units" - duplicate the ad unit with different entries for the bidder

The real solution is to put pressure on the bid adapters in question to fix the behavior. If they need to split out separate requests for sizes or formats, **they can do that on their own**. IMO, publishers should be irritated at having to cater to unnecessary technical limitations.

**Comment by patmmccann** [comment]
assigning to mmoschovas to hash out with more detailed example

**Comment by lcorrigall** [comment]
Is this still something we need to solve?

**Comment by patmmccann** [comment]
yes; we're hoping @mmoschovas will post an example of the actual and expected behavior

**Comment by dgirardi** [comment]
Asking again - does this need to be addressed?

**Comment by bretg** [comment]
@ix-prebid-development, @slimkrazy - Prebid Server does not accept multiple instances of the same bidder in the same imp. We view this as an abuse of OpenRTB and JSON as it would be the same attribute repeated more than once per object.

e.g. 

```json
imp.ext.prebid.bidder:{
   "bidderA": { first set of args },
   "bidderA": { second set of args}
}
```

This screws up our JSON schema validation, which will only take the first entry.

Coming up with a way of allowing your bidders to do this could be expensive for the community. Honestly I can't even think of a good way of doing it without a fairly comprehensive re-factoring. 

If you need this to happen, I need IX and/or Yahoo to show up at a Prebid Server meeting with an explanation of the use case and, even better, ideas and engineering time to help enhancement.

**Comment by bretg** [comment]
Still want to be convinced by the use case here, but in the spirit of trying to move the ball forward:

- this is really a Prebid Server limitation, not so much the pbsBidAdapter. Even if the adapter were to send all the bidrequests from duplicate bidders, PBS would not understand them.
- the limitation is in the JSON structure. To support this scenario, we could change imp.ext.prebid.bidder to be an array of objects. e.g.

```
imp.ext.prebid.bidder:[{
   "bidderA": { first set of args },
},{
   "bidderA": { second set of args}
}]
```

This is a pretty dramatic change and would require some rather ugly backwards-compatibility work in PBS.

Somewhat better might be a new syntax that leaves imp.ext.prebid.bidder alone:

```
imp.ext.prebid.bidderarray:[{
   "bidderA": { first set of args },
},{
   "bidderA": { second set of args}
}]
```

This competely alternate syntax would minimize any transition period problems, but would probably require a fair amount of rework in PBS-core. 

Could we just require bid adapters to deal with this?

```
imp.ext.prebid.bidder:{
   "bidderA": {
       video: { ... params ... }
       banner: { ... params ... }
       native: { ... params ... }
   }
}
```
