### ISSUE TITLE
AdRender issue with Appnexus BidAdapter

### ISSUE THREAD

**Issue by HardikPat21** [prebid/Prebid.js#9341]
## Type of issue

Question: AdRender issue with Appnexus BidAdapter
## Description

We are facing issue with Appnexus BidAdapter. We have upgraded the prebid from version v6.27.0 to v7.20.0 in our application. 
When we test for AppNexus Bidder for one of the publisher (after upgrading prebid version to 7.20.0) then we are not getting any impression (adrenders) count even if the Bid is won and Ad is rendered for AppNexus Bidder.
But when we check with previous version (prebid v6.27.0) then it is working fine.

Could you please help us and provide some insights why this would happen and could not serve any impressions/adrenders for AppNexus Bidder with prebid 7.20.0 version.

Also, we have attached some prebid logs for the reference.
[PreBid-AppNexus.log](https://github.com/prebid/Prebid.js/files/10228872/PreBid-AppNexus.log)

Thanks.

## Platform details

Prebid - 7.20.0

**Comment by dgirardi** [comment]
Could you clarify what you mean by "adrender count"? I'm probably missing something obvious but I don't understand what you are looking at or what the issue is.

**Comment by HardikPat21** [comment]
AdRender count means impressions that we are not receiving for AppNexus Bidders even if the Bid won by AppNexus and Ad was rendered with Prebid version 7.20.0. 
So we want to know the cause of why it's not getting received after upgrading Prebid to version 7.20.0 and it's working with previous prebid version 6.27.0. It would be great help if you could provide some insights on this.Thanks.

**Comment by jsnellbaker** [comment]
Can you share a working test page that uses 7.20 and doesn't track the impressions so we can take a look in real time?  For our bidder (for banner), we attach the .adnxs.com/it? impression URL to the end of the creative html code (I can see it there in the log lines of the attached file.

I'm not aware of any tracking issues off-hand, but there's been a number of changes between versions.  Seeing a page with the issue would be a great help.

CC: @Fawke as well
