### ISSUE TITLE
Enabling local storage in unit tests via the getStorageManager()

### ISSUE THREAD

**Issue by antosarho** [prebid/Prebid.js#9348]
## Type of issue
Testing local storage in unit tests does not appear to be possible.

## Description

I want to test that our use of `getStorageManager()` with `gvlid` and `bidderCode` specified is working correctly. Nevertheless, whenever I run my unit test, `isValid(cb)` within `storageManager.js` always returns undefined because the callback in `validateStorageEnforcement` is never executed.

## Steps to reproduce

In any unit test, set up the following:
```
    const storage = getStorageManager({gvlid: 855, bidderCode: 'adnuntius'});
     storage.localStorageIsEnabled(); // always returned undefined
```
You will then find that the callback in `validateStorageEnforcement` via `isValid(cb)` is never executed.

### Expected results
There should be a way to enable local storage in unit tests.

## Other information

This is what I use to run the tests: `gulp test --file ./test/spec/modules/adnuntiusBidAdapter_spec.js`

**Comment by dgirardi** [comment]
First, I recommend using `serve-and-test` instead of `test` during development - it's quite a bit faster (it skips linting and doesn't need to recompile the world on each test run).

To solve your issue, add this at the top of your `_spec.js` file:

```
import {hook} from 'src/hook.js';

before(() => {
  hook.ready();
});
```

**Comment by patmmccann** [comment]
> Testing local storage in unit tests does not appear to be possible.

Fwiw, it does work when you run all the tests, the problem at hand is that it doesnt work when you only run this subset of the tests.

**Comment by antosarho** [comment]
That does the trick!

Thanks muchly. And thanks muchly for merging the change to master to enable this by default.
