### ISSUE TITLE
Integration with Next.js

### ISSUE THREAD

**Issue by aktoriukas** [prebid/Prebid.js#9349]
## Type of issue
Set-up with Next.js

## Description
Facing issue with Nextjs integration with Prebid.js. Following example from ( https://www.npmjs.com/package/prebid.js ) by extending webpack config in `next.config.js`:

```
let path = require("path")

module.exports = {
  reactStrictMode: true,
  webpack: (config, { buildId, dev, isServer, defaultLoaders, nextRuntime, webpack }) => {

    config.module.rules.push({
      test: /.js$/,
      include: new RegExp(`\\${path.sep}prebid\\.js`),
      use: [
        {
          loader: "babel-loader",
          options: require("prebid.js/.babelrc.js"),
        },
      ],
    })

    return config
  },
}
```

after this while trying to import `prebid.js` facing this error:

```
import {getGlobal} from './prebidGlobal.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

## Steps to reproduce
Fresh install of Nextjs

## Platform details
Nextjs "12.2.2"
React "^17.0.2"

**Comment by aktoriukas** [comment]
here is a code sample: [codesandbox](https://codesandbox.io/p/sandbox/cranky-shannon-4po3y9?file=%2Fnext.config.js&selection=%5B%7B%22endColumn%22%3A6%2C%22endLineNumber%22%3A17%2C%22startColumn%22%3A6%2C%22startLineNumber%22%3A17%7D%5D)

**Comment by ChrisHuie** [comment]
@aktoriukas do you need the server side rendering from Next? I am able to get working with create-react-app but Next's build process is a bit more complex?

**Comment by aktoriukas** [comment]
@ChrisHuie it can be client or server side , it does not really matter that much for now. Can you share process that you follow integrating with React and also Next.js if you manage?

I have managed integrate it by downloading generated file from [prebid](https://docs.prebid.org/download.html) .
But that's not what i'm after. I would like import them from library ( NPM ). As codesandbox example above.

**Comment by ChrisHuie** [comment]
We think this pr will fix your current issue with Next -> https://github.com/prebid/Prebid.js/pull/9558
