### ISSUE TITLE
Canada TCF & Canadian vendor list ids

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9360]
## Description

Gvlid is quite central to adapters; we need to write a spec for the Canadian vendor list identifiers 

<!--
  If this is a bug, please provide a list of steps to reproduce the issue
--
<!--
Include a link to a test page or minimal demo of the problem via
  https://jsfiddle.net, http://jsbin.com or similar.
--

**Comment by bretg** [comment]
Responses from the IAB

> 1. We see that current Canadian GVL entries have the same numbers as the EU GVL. This is very good. Can we rely on this going forward? i.e. will the IAB guarantee that when new number is added to one list, that it's not added to the other with the same number?
 
Yes, TL has a vendor id issuing service that will ensure that vendors participating will have a single unique id regardless of which frameworks they’ve registered to participate in.

 

> 2. Will Canada-only entries be added to the EU list? We don't want to make Prebid Server read from two lists. It's already painful enough loading hundreds of versions of the EU GVL list.
 
No, there is a unique list for Canada here: https://vendor-list.consensu.org/v2/ca/vendor-list.json. The Global Privacy WG members were asked about the need for a single list last year and indicated that it was a nice to have. That being said, we can re-open that conversation and have kicked around designs for a singular list at TL some time ago.


> 3. Is there a CMP vendor who has started implementing TCF-CA? We may be interested in trading notes and timelines.

Consentmanager.net has started implementation

**Comment by bretg** [comment]
This means Prebid Server will need to load an alternate GVL list. Not ideal, but hopefully it won't have to load both EU and CA lists on the same request.

**Comment by patmmccann** [comment]
We'll rely on the cmp to express consent for any particular vendor and validate those vendor ids are on the right list. A bidder is welcome to add its gvl id even if it isn't registered in europe if it is only registered in Canada.
