### ISSUE TITLE
Modules that may be removed in 8.0

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#9362]
## Type of issue
Cleanup

## Description
We did a broken-link check on docs.prebid.org and found that links provided with several bid adapters no longer have an active website. Would like to give these entities a chance to respond with an updated website link before we consider removing their bid/analytics adapter or module:

- [x]  LiveYield (analytics adapter) - https://www.pubocean.com/liveyield no longer exists - @tomek-jedro 
- [x]  Glimpse (bid adapter) - https://docs.glimpseportal.io/en/latest - @eddieyu1998 
- [x]  Truereach (bid adapter) - http://doc.truereach.co.in/docs/prebid/js-bidder-adapter.html - looks like this is owned by Momagic now - @mmprebid 
- [x] #9888

**Comment by patmmccann** [comment]
The mass module is a generic module for deals rendering and not just a vendor module

**Comment by bretg** [comment]
> The mass module is a generic module for deals rendering

Could we consider renaming it in a future release?

**Comment by patmmccann** [comment]
linking with #8539

**Comment by dgirardi** [comment]
Also see https://github.com/prebid/prebid.github.io/issues/4093

**Comment by patmmccann** [comment]
Let's rename mass to Deal Rendering and delete all branding

**Comment by patmmccann** [comment]
LiveYield was part of PubOceon, acquired by Perion

**Comment by patmmccann** [comment]
Glimpse reports commercial activity shutdown at https://glimpseprotocol.io/


 Glimpse’s commercial activities are currently paused until the market is ready to shift to a more private model. Regulators globally are beginning to enforce the law, which will force the adoption of such technologies. We welcome interest in our technology at hello@glimpseprotocol.io.

**Comment by patmmccann** [comment]
@bretg I don't see truemagic link as broken any longer; seems to be working?

**Comment by patmmccann** [comment]
Made a new issue for MASS
