### ISSUE TITLE
[Video Module] Update for new Instream & Outstream definition

### ISSUE THREAD

**Issue by karimMourra** [prebid/Prebid.js#9373]
## Type of issue
Update

## Description

Per the IAB's new definition, an ad with default sound off must be considered outstream. 
As a result, the JW Player and Video.js submodules must be updated.

IAB definition:

> To be considered In-Stream (pre-roll, mid-roll, and post-roll), video placements/impressions
> must be set to “sound on” by default at start.
> o “Sound On” by default must be signaled in OpenRTB v2.5 and above within the
> field for Playback Method (Section 5.10). Values of 1, 3, 4, and 5 all qualify.
> • All impressions with Default Sound Off (Playback Method of 2, 6, or null) must signal, in
> OpenRTB v2.5 and above, an out-stream Placement of type of 2, 3, 4, or 5 (section 5.9).
> o Additional signals such as Player Size, Placement Type, Linearity, etc. can be used
> to differentiate between these various out-stream placements.

### Expected results
When a player is muted, `imp.video.placement` must not be set to 1.

### Actual results
When a player is muted, `imp.video.placement` is set to 1.

**Comment by patmmccann** [comment]
This was in the video format guide and not the openrtb spec; the guidance has leg to much subsequent debate and expected revisions to come. I recommend closing as won't do.
