### ISSUE TITLE
Add GPP support flag

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9390]
## Type of issue
Documentation

## Description
We should identify adapters with support for GPP strings, and potentially Canadian vendor list id's. 

Known adapters with GPP Support:
Appnexus
Improve
OpenXOrtb
Taboola
The TradeDesk
Prebid Server Adapter

Of note, this could (maybe should) be on the docs board. Posting here for wider visibility

**Comment by bretg** [comment]
GPP flag doc support merged.
