### ISSUE TITLE
Floors module: cannot handle complex bid adjustment functions

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9391]
## Type of issue
Feature Request or bug, not sure

## Description
https://github.com/prebid/Prebid.js/blame/master/modules/priceFloors.js#L194 seems to try to reverse engineer a bid adjustment function by plugging the floor into a bidder's bid adjustment function and seeing how far the result is below the input. This assumes adjustment functions can be reflected in the form bid = multiplier * adjusted bid

This method only works if the only adjustment is a multiplier. 

The solution appears to be: allow the publisher to set a inverse bid adjustment function and apply that instead of the psuedo-inverse calculated here when it exists. 

## Steps to reproduce
Set the bid  adjustment function to adj_cpm = max(0,0.95*bid_cpm - .05)
Set the floor to 0.01
Observe the outcome adjusted floor sent to endpoints, eg the rubicon fastlane endpoint on the floor query string parameter

### Expected results
adjusted floor = 6 cents/ 0.95

### Actual results
adjusted floor infinity

![image](https://user-images.githubusercontent.com/1683175/210412870-61046adb-d224-4214-ac50-95cf125ff5fd.png)

**Comment by patmmccann** [comment]
![image](https://user-images.githubusercontent.com/1683175/210413764-1b19f3ad-4b65-4e99-b447-c731fed9f1f1.png)
Looks like I can come up with a scenario where the floor should be 20 cents but is calculated at 72 dollars

![image](https://user-images.githubusercontent.com/1683175/210413837-9800c03f-a046-4490-8d4d-e8778e112213.png)

**Comment by robertrmartinez** [comment]
We decided to first go with a new `inverseBidAdjustment` function which can be set on bidderSettings just how `bidCpmAdjustment` is.

https://github.com/prebid/Prebid.js/pull/9395
