### ISSUE TITLE
Question: How can I be informed via email of new releases?

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#940]
How can I be informed via email of new releases?
Is there a thread I can subscribe to that tells me when a new release is available on the http://prebid.org/download.html download page?

**Comment by mkendall07** [comment]
@rmloveland any thoughts on this?

**Comment by nanek** [comment]
There is an ATOM/RSS feed of github releases at https://github.com/prebid/prebid.js/releases.atom

There are RSS to Email services such as https://blogtrottr.com/ that can email you when they update.

**Comment by matthewlane** [comment]
Prebid has a Twitter account which tweets out new releases: https://twitter.com/prebidjs

You could potentially use a service like [IFTT](https://ifttt.com/) to get [email notifications about new tweets](https://ifttt.com/applets/234075p-new-tweet-by-specific-user-send-me-an-email).

**Comment by headerbidding** [comment]
I was looking for a real simple "solution." I don't use Twitter and RSS. 
It would be nice it there was a thread I could just simply subscribe to (as I can with theis thread for example).

**Comment by matthewlane** [comment]
Another solution may be [Sibbell](https://sibbell.com), which notifies you of any new releases for repos that you've starred on GitHub

**Comment by headerbidding** [comment]
I actually want to be notified when a new download release is available on the http://prebid.org/download.html download page, which is not part of Github.

Suggestion: If there was a thread (like this one) that announced new releases, I could just simply subscribe to it with one click.

**Comment by mkendall07** [comment]
We send out emails of new releases now.
