### ISSUE TITLE
Error for pbjs.getHighestCpmBids method

### ISSUE THREAD

**Issue by soman** [prebid/Prebid.js#9402]
## Type of issue
Bug

## Description
It's worked for Prebid version 7.19.0 but from 7.20.0 getting the provided error.
Can someone help me about this error.

## Steps to reproduce
![image](https://user-images.githubusercontent.com/2465685/211346014-b35a3ef1-5988-449c-956f-d6916dac5577.png)

**Comment by patmmccann** [comment]
Potentially fixed in 7.27; can you confirm still exists?

**Comment by dgirardi** [comment]
Is this the same issue as in https://github.com/prebid/Prebid.js/issues/9245 ? Does it persist if you disable browser extensions?

**Comment by patmmccann** [comment]
closing as a likely duplicate; p[lease reopen if not.
