### ISSUE TITLE
Video Module: Refactor setup errors

### ISSUE THREAD

**Issue by karimMourra** [prebid/Prebid.js#9406]
## Type of issue
Tech debt

## Description
The JW Player and Video.js video submodules have nearly identical setup error cases. This should be refactored.
Solution should be opt in for video submodules, since it may not apply for all.

**Comment by patmmccann** [comment]
@karimMourra did 9407 close this?

**Comment by karimMourra** [comment]
No but I am closing this since we will not want to proceed with it.
