### ISSUE TITLE
net::ERR_BLOCKED_BY_CLIENT causing blank ad loads

### ISSUE THREAD

**Issue by CLKeenan** [prebid/Prebid.js#941]
## Type of issue
Question

## Steps to reproduce
Open new tab
Open dev console
Visit http://www.course-notes.org (will likely see "net::ERR_BLOCKED_BY_CLIENT" on first page load causing ad units to be blanks)
Refresh page (ads will now load)

### Expected results
Ad units to load

### Actual results
net::ERR_BLOCKED_BY_CLIENT causes ad units to be blanks

## Platform details
Prebid.js: 0.17 (http://60025cc55a0190b7358f-da14a1bf5776249a5e7003413c798758.r88.cf5.rackcdn.com/0.17.0/pb_ga_v17-2.js)
Chrome: Version 55.0.2883.87 m (64-bit)

Adapters include:
AppnexusAST
PulsePoint
IndexExchange
Sovrn
bRealtime (alised to AppnexusAST)
Defy Media (alised to AppnexusAST)
Sekindo (alised to AppnexusAST)
District M (alised to AppnexusAST)
Conversant
YieldBot
AOL

6 ad units in total

## Other information
![image](https://cloud.githubusercontent.com/assets/2414280/22154923/773cb42a-defb-11e6-923a-a43ce5ff1d93.png)

**Comment by mkendall07** [comment]
Turn off your adblocker? ;)

**Comment by CLKeenan** [comment]
@mkendall07 ha! I wish the solution was that simple. Ad blocker has domain whitelisted and ads do display on 2nd page load.

**Comment by mkendall07** [comment]
Well it works fine for me and I don't have adblock installed. 

`ERR_BLOCKED_BY_CLIENT` should give you a hint - it's a client (read browser) issue. You are blocking the request.

**Comment by CLKeenan** [comment]
That's what I assumed and figured it was just a "me" issue, but had a few other people tell me they were seeing blanks recently so thought I'd ask if anyone had any suggestions.

**Comment by mkendall07** [comment]
Did you try loading an incognito window? Might isolate issues on your machine vs your network. I do think it's related to one of those things.

**Comment by mkendall07** [comment]
@CLKeenan 
any luck figuring this out?

**Comment by hrgui** [comment]
did you try using a different browser?
