### ISSUE TITLE
trk.diamondminebubble.com

### ISSUE THREAD

**Issue by ah0lland** [prebid/Prebid.js#942]
Hello,

Recently we have been noticing suspicious events in our AV and firewall logs related to the trk.diamondminebubble.com domain. I have been unable to find any references to that domain, besides in this github project. Would you mine providing some more information on the domain so I can try to determine the cause of the events?

Thanks,
AH

**Comment by mkendall07** [comment]
@ah0lland 
It looks like it's part of a test fixture, which means it was captured during an integration test. We are not associated with that domain.
