### ISSUE TITLE
"file not built properly" with User ID modules

### ISSUE THREAD

**Issue by dermick12** [prebid/Prebid.js#9424]
Hi,

whenever I try to download prebid.js from https://docs.prebid.org/download.html and add one of the following User ID Modules the download shows an "file not built properly" error.
This happens  when chosing ID5 OR Unified ID OR netID and a lot of other ID modules. Some other modules are working (eg Criteo ID, Unified ID 2.0).

I tried different versions, different bidders, recommended modules. Is this a bug or am I doing something wrong?

Thanks!!

Michael

**Comment by patmmccann** [comment]
Can you list all the modules you are selecting and which version so we can attempt to reproduce

**Comment by dermick12** [comment]
You can just try it with: bidder: criteo and ID 5 Universal ID, latest version.
Or any of the mentioned ID modules. Or any other bidder. Or any other version.

**Comment by ChrisHuie** [comment]
I just tried Criteo and ID 5 ID and didn't have any download problems on 7.31. Will check in a few hours when 7.32 is added to the download page.

**Comment by dermick12** [comment]
@ChrisHuie Fascinating. I just retried it again with 7.31, bidder: criteo, module ID 5.
(recommended modules all checked, no other bidders or modules selected)
{"error":"Prebid file not built properly","requestId":"8f6361b7-fc03-4f4b-a5d2-d5b4bf8ee1d1"}

I user chrome and then firefox. The result is the same.

**Comment by ChrisHuie** [comment]
@dermick12 @markpygas looking into this. Seems the request name of the id modules changed with an extra ID added to the the name making the name mismatch.

**Comment by dermick12** [comment]
Thanks, it's working now for me!

**Comment by markpygas** [comment]
Works for me too, thanks!
