### ISSUE TITLE
Unite rendering examples

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9435]
## Type of issue
Feature request

## Description
https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/x-domain/creative.html and https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/creative_rendering.html
are prebid creatives respectively. We should publish one creative that detects it is in a safeframe and does the former logic if not, the latter if so.

**Comment by dgirardi** [comment]
Related: https://github.com/prebid/Prebid.js/pull/9647

The cross-domain should work in both cases, and especially after that PR, there should be very little difference - and no reason to have the `pbjs.renderAd` example.

**Comment by patmmccann** [comment]
delete https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/creative_rendering.html will solve this
