### ISSUE TITLE
How can i use "bidCpmAdjustment for specific ad units. 

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#945]
Im trying to use bidCpmAdjustment to make floor prices for each ad unit global 

So i was trying

pbjs.bidderSettings = {
  indexExchange: {
    bidCpmAdjustment : function(bidCpm, bidObj){

if (bidObj.adUnitCode = 'div-gpt-ad-1469661347126-0' && bidCpm >= 0.50) {
 return 0;
}
...

But this isnt working. Is there a simple way to set a floor price for adapters that dont support floor using bidCpmAdjustment that will target specific ad units.

I know i can use the custom targeting to change the hb_pb value but i dont want to send dfp 0 cpm line items if there is a way to use that but then emit the bid all together please do tell 

I can also use:

    pbjs.bidderSettings = {
      standard: {
        adserverTargeting: [{
          key: "hb_pb",
          val: function(bidResponse) {
            var cpm = bidResponse.cpm;
            if (cpm < 13.00) {
return 0;
            }
          }
        }]
      }
    };

but i dont want to send 0 cpm line items to dfp 
i tried to use               pbjs.removeAdUnit('div-gpt-ad-343444444-0'); 
instead of "return 0" but that does not work

**Comment by mrpbennett** [comment]
Looks like you're not using the right equal operators? 

    if (bidObj.adUnitCode === 'div-gpt-ad-1469661347126-0' && bidCpm >= 0.50) {
        return 0;
     }

try using the strict equal operator `===` instead of just =

**Comment by mercuryyy** [comment]
Oh wow that did the trick, i thought the pbjs.bidderSettings function might be functions in a way that makes it impossible.

Much appreciated!

**Comment by mrpbennett** [comment]
👍  You're welcome. Good reading [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators) on operators in JS :grinning:
