### ISSUE TITLE
Is there a command to "pause" all bidders of a certain Advertiser?

### ISSUE THREAD

**Issue by tedrand** [prebid/Prebid.js#946]
## Type of issue

Question

## Description

Is there a command to effectively pause an Advertiser whose adapter has been registered by the library?

I know that this can be done by removing that Advertiser's bidders, but is there an easier method to just stop the bidders from participating?

**Comment by matthewlane** [comment]
If you remove a bidder from the bid parameters array when defining an adUnit, it won't participate even if it's registered by the library

**Comment by tedrand** [comment]
Yeah I think they were looking for more of a one-liner just because they don't know much about the Prebid code. Essentially my solution was to add this array:

```
var activeBidders=[
  "skindo",
  "sovrn",
  "brealtime",
  "sonobi",
  "districtm",
  "aol",
  "pulsepoint",
  "indexExchange",
  "conversant"
];
```

And then running this code on the object with all of the bidders:

```
for (var ad of adUnits) {
        var bids = ad.bids,
            active = [];
        for (var bid of bids) {
            if (activeBidders.indexOf(bid.bidder) !== -1) {
                active.push(bid)
            }
        }
        ad.bids = active
    }
```
