### ISSUE TITLE
Schain [object Object] when passing object through buildRequests

### ISSUE THREAD

**Issue by sfloam** [prebid/Prebid.js#9471]
## Type of issue

Bug
## Description

We would like to request clarification on the implementation of schain. The [freewheel-sspBidAdapter.js](https://github.com/prebid/Prebid.js/blob/master/modules/freewheel-sspBidAdapter.js) supports schain, however, a client has indicated the the payload produces schain:[object Object].

adUnit example below:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/9473833/214935488-e7e62372-78a9-4155-959a-5ff4eed5b0c6.png">

## Steps to reproduce

This file can also be used to test:
1. Change the file type to html.
2. Build prebid.js
3. Host prebid.js at http://localhost:8000/prebid.js (or change the host/port in the file).
[prebid.txt](https://github.com/prebid/Prebid.js/files/10512798/prebid.txt)

## Platform details

v7.34.0
Desktop

## Other information

Currently, our `schain` logic is implemented as follows:
https://github.com/prebid/Prebid.js/blob/ba7d0d0026484396d3098da5dfc96586ca68568b/modules/freewheel-sspBidAdapter.js#L348-L352

Using this logic, we noticed that the payload returns this:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/9473833/214931565-9b4af380-52b0-48b7-be6f-46682c080d02.png">

<img width="704" alt="image" src="https://user-images.githubusercontent.com/9473833/214931627-c58d123c-9905-4f49-93ff-b21e4f3df302.png">

If we change line 351 from `requestParams.schain = schain` to `requestParams.schain = JSON.stringify(schain)`, the encoded object is found in the payload of the request with its contents.

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/9473833/214929156-34b2a308-4092-4648-b327-b79466b62617.png">

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/9473833/214929212-44917020-7fc7-4126-98c6-ecebd31e3681.png">

However, the documentation found here: https://docs.prebid.org/dev-docs/modules/schain.html#schain-config-syntax seems to indicate that the actual schain object should be passed. Should we be converting the object ot a string or is there a bug in Prebid.js causing this issue? I did not see any reference to making the schain object a string here.

**Comment by dgirardi** [comment]
Because you are using a GET request: 

https://github.com/prebid/Prebid.js/blob/9a83c0307f7d18e5f6a495c4681e098909eb9d96/modules/freewheel-sspBidAdapter.js#L388-L393

the `requestParams` are sent out as query parameters, which can only be strings. How to fix this will depend on what your endpoint can understand; the easiest method would probably be to serialize the schain object (through JSON or otherwise) before tagging it onto the URL.

**Comment by sfloam** [comment]
@dgirardi, thanks for your reply. Just for confirmation, the encoded output of 
{"validation":"relaxed","config":{"ver":"1.0","complete":1,"nodes":[{"asi":"bidderA.com","sid":"00001","hp":1}]}}
would be the expected schain value/format:

`%7B%22validation%22%3A%22relaxed%22%2C%22config%22%3A%7B%22ver%22%3A%221.0%22%2C%22complete%22%3A1%2C%22nodes%22%3A%5B%7B%22asi%22%3A%22bidderA.com%22%2C%22sid%22%3A%2200001%22%2C%22hp%22%3A1%7D%5D%7D%7D`

**Comment by dgirardi** [comment]
how to encode it is up to you and your backend team :) to get that result you'd want to replace `requestParams.schain = schain` with `requestParams.schain = encodeURIComponent(JSON.stringify(schain))`.

**Comment by sfloam** [comment]
@patmmccann we made a PR to address this issue. Thanks!
