### ISSUE TITLE
ESP secure signals with Video, even possible?

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#9473]
I had a chat with @bretg on slack and I'm trying to get ESP secure signals working with video (not even sure its posible)
basically when i try to add ESP’s in, its sort of gets somewhere but throws “WARNING: User ID - ESP : encryptedSignalSources config not defined under userSync Object” and at the same time strips the userID out of being sent on the bids.  I’m loading GPT in my scripts etc. I’m not even sure if this is possible when using only video and maybe i’m bashing my head against a brick wall?

![Bret_Gorsline_-_AdOps_-_Slack](https://user-images.githubusercontent.com/8503167/215141036-3e403e69-f126-436c-bc8c-943e0671ca95.png)
![Bret_Gorsline_-_AdOps_-_Slack](https://user-images.githubusercontent.com/8503167/215141117-c1a30d60-a6c2-46ce-a658-031110e62211.png)

bretg has test pages you can look at internally, i i hate putting my test pages in public.

**Comment by jdwieland8282** [comment]
Are you using Google OB?  ESP now [Secure Signals](https://support.google.com/admanager/answer/10488752?hl=en) is a google product, Prebid.js doesn't have any hooks into Secure signals that I know of.

**Comment by spormeon** [comment]
i do use some OB, but its these that I'm following, prebid creates the sigansls from the userid's
https://docs.prebid.org/dev-docs/modules/userId.html#esp-configurations
https://docs.prebid.org/dev-docs/publisher-api-reference/registerSignalSources.html

**Comment by patmmccann** [comment]
Fwiw, esp in general works with gam, you can see the vasts that gam returns looking for the signals

**Comment by spormeon** [comment]
i found this, so does the prebid method do it in the same way (at the bottom, I cant implement it the "direct" way)
https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/securesignals
@patmmccann did @bretg show you the test pages?

I just cant get any to "pass through to gam" no matter what i do yet

**Comment by patmmccann** [comment]
![image](https://user-images.githubusercontent.com/1683175/215549663-ac14559b-ab9e-4117-a519-1ab882ee9cfc.png)
shows gam is redoing the workflow on this. I suggest you re-implement at that time. 

If you really want to implement now though, could you please re-state the question? I am not sure I understand it. ESP set by Prebid works fine on Cafemedia sites.

**Comment by spormeon** [comment]
I have implemented it on the test pages which @bretg has, but its throwing warnings saying the“WARNING: User ID - ESP : encryptedSignalSources config not defined under userSync Object”  when it is, its also stopping userids being sent on the bid requests.  No "secure signal" seems to make it to GAM , as reporting says secure signal presence: missing

i used these to implement it:
https://docs.prebid.org/dev-docs/modules/userId.html#esp-configurations
https://docs.prebid.org/dev-docs/publisher-api-reference/registerSignalSources.html

that GAM inventory > Secure Signals, is alreay in our GAM, they have all been turned on manually

**Comment by patmmccann** [comment]
when you add pbjs.getConfig().userSync.encryptedSignalSources what do you put there

**Comment by patmmccann** [comment]
okay i see that you wrote this in that feild now
![image](https://user-images.githubusercontent.com/1683175/215591662-308065b1-8681-4bf4-88ee-5c89e51ca41f.png)

**Comment by bretg** [comment]
@patmmccann - I shared spormeon's test page in the slack channel with you and Jeff.

**Comment by spormeon** [comment]
na, not sorted it yet.  I think the problem is reloving around GPT tag, Patricks has both banner and video.  Mine only has video.  Patrick are you not deploying the secure signals scripts automatically with GPT?

**Comment by spormeon** [comment]
does: encryptedSignalSources.sources.customFunc  have to be included, as it says "required" in the docs but i'm only trying this at the moment, or is that a docs mistake?
encryptedSignalSources: {
                        'sources': [{
                            source: ['criteo.com', 'id5-sync.com', 'pubcid.org', 'adserver.org', 'quantcast.com', 'crwdcntrl.net', 'flashtalking.com', 'trustpid.com', 'amxdt.net'],
                            encrypt: false
                        }
                        // {
                        //     source: ['pubmatic.com'],
                        //     customFunc: () => {
                        //         return '{"keywords":["tech","auto"]}';
                        //     },
                        //     encrypt: true
                        // }, 
                        // {
                        //     source: ['segment.com'],
                        //     customFunc: () => {
                        //         return '[{ "id": "1", "value": "seg1" },{ "id": "2", "value": "seg2" }]';
                        //     },
                        //     encrypt: true
                        // }
                    ],
                        'registerDelay': 3000
                    },

**Comment by patmmccann** [comment]
They work now if you are using gpt.js, and the GAM release notes allude to the fact that secure signals will no longer be pushed, but instead will be pulled by GAM. Are you not using gpt.js on page at all? If not, I am not sure how one might use secure signals.

**Comment by spormeon** [comment]
i've since sort of done a "hack around", which is add a adunit and inlude GPT, but the adunit is "doing nothing" in effect.  I'm looking for a "pure" video way with no GPT but not found it yet.

**Comment by patmmccann** [comment]
Secure signals are a feature of gpt. You cannot use them without it unfortunately. There is a new feature, secure signals that you'll find supported soon, it is in the release notes as coming soon and you might be able to get in the beta. Otherwise, closing as not a feature of gam libraries.
