### ISSUE TITLE
GPP module: update to support 1.1 including callback compatability, ready status, deprecation getGPPDATA

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9483]
## Type of issue
Mirroring https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/issues/51 it appears at https://github.com/prebid/Prebid.js/blob/aa033bdf1f5092e0083303b7cd36da94bebe9fb0/modules/consentManagementGpp.js#L168 we call the cmp after hearing a change event. Could we instead rely on the data in the callback to have the section change data?

 https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/606b99efc16b649c5c1f8f1d2eb0d0d3258c4a2d/Core/CMP%20API%20Specification.md?plain=1#L273 

Since we invoke the cmp getgppdata command after the event, does our solution work in a frame or if the cmp is in a frame as TCF does? 

How should we give feedback to the IABTL on our preference for the outcome of their issue 51? Assuming they go with solution 1, I assume we need to change our invoke cmp call to expect different behavior.

**Comment by brondsem** [comment]
Looks like there are API changes coming to support this: https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/pull/55

The changes would also remove `getGPPData` and instead the `ping` command would return the full GPP string. So `consentManagementGpp.js` will need changes

**Comment by patmmccann** [comment]
In the IABTL meeting now, instead of double calling the cmp, the event listener return should have the data and we dont need to call ping, gppdata, nor getsection

**Comment by dgirardi** [comment]
This does not appear ready for development. The only GPP aware CMP that I know (from [this test](https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/gpp_us_hello_world.html)) does not provide GPP consent data from the event payload, the call to `getGPPData` is required as far as I can tell.
