### ISSUE TITLE
no NURL field in bidResponse 

### ISSUE THREAD

**Issue by ahmadlob** [prebid/Prebid.js#9486]
## Type of issue
There is no dedicated field for passing the `nurl` in the `bidResponse` Object. 
I passed it anyway although no documentation or guide mentioning it and I need to use it in the `onBidWon` function.

This is the PR 

https://github.com/prebid/Prebid.js/pull/9482

**Comment by dgirardi** [comment]
Prebid does not have a dedicated field for `nurl`. The PBS adapter and the ORTB conversion library treat nurl as either `bidResponse.adUrl`, or as something to be appended to the markup: 

https://github.com/prebid/Prebid.js/blob/b1de163ef0171ae2f72f2791ced3a1312601d8d4/libraries/ortbConverter/processors/banner.js#L29-L38

This does not look like great practice, but I am not sure if there's a practical difference between it and what you do in your PR; I believe you would still get the link fetched once your bid wins. @patmmccann ?

**Comment by patmmccann** [comment]
It's not apparent to me everyone wants to be notified on either of prebid winner vs ad server win with a nurl field. I would assume the former as line 32 does

**Comment by dgirardi** [comment]
Actually, it looks like we are following the [spec](https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf): 

> For each bid, the nurl attribute contains the win notice URL. If the bidder wins the impression, the
exchange calls this notice URL to inform the bidder of the win [...] The win notice return or the adm
attribute can be used to serve markup (see Section 4.3). 
> 4.3.1 Markup Served on the Win Notice
In this method, ad markup is returned to the exchange is via the win notice. In this case, the response
body of the win notice call (i.e., invoking the bid.nurl attribute) contains the ad markup and only the
ad markup; there must be no other structured data in the response body.

For banner at least, it looks to me like appending `nurl` to the markup would be equivalent to triggering it from `onBidWon`. native has its own separate impression tracking mechanism. There's a gap for video (we [treat nurl as `vastUrl`](https://github.com/prebid/Prebid.js/blob/b1de163ef0171ae2f72f2791ced3a1312601d8d4/libraries/ortbConverter/processors/video.js#L64), which does not sound quite correct), but have more trouble figuring out video bid winners in general.

**Comment by dgirardi** [comment]
If your adapter never uses `nurl` to serve the ad markup, they should be equivalent. I personally would prefer putting it in the markup (like the conversion library does)  because there's fewer steps it has to go through for you to get the notice: as soon as the ad is rendered you should see the hit; while with onBidWon the creative frame has to notify Prebid which has to call your adapter, it's more likely for something to go wrong along the way.
