### ISSUE TITLE
Add an option for Price Floors module to wait for currency

### ISSUE THREAD

**Issue by piotrj-rtbh** [prebid/Prebid.js#9493]
## Type of issue
Bug: the Price Floors module is not able to properly use the Currency module for converting currencies in bid floors if the exchange rates are taken from an external file (eg. the default one on jsdelivr)

## Description
Currency conversion should take place after the currency rate file is loaded so to safely apply the actual rates. Only in certain cases (eg. file could not be loaded or a timeout) the rates should be taken from the currency.defaultRates property. 
We have noticed that once the currency file is cached then the exchange rates are taken from the file. It happens to load quickly right before the bidRequests are to be processed.
Without caching the file is loaded but too late and the floors are calculated with the use of defaultRates only.

## Steps to reproduce

1. Build the bundle using your bidder adapter which is able to use Price Floors module (calls `bidRequest.getFloor()` method somewhere) and the bidder should accept USD; add also: currency and priceFloors modules
2. Add it as your prebid.js file
3. Setup standard prebid environment with one ad unit and one ad size (should be enough)
4. Add the following to your ad unit:
```
floors: {
      currency: "EUR",
      schema: {
        fields: ["mediaType"]
      },
      values: {
        banner: 0.3
      }
    },
```
5. Make a setConfig call with params:
```
pbjs.setConfig({
    currency: {
      adServerCurrency: "EUR",
      defaultRates: { EUR: { USD: 10 } }
    },
    floors: {}
  });
```

## Test page
Codesandbox test page: https://efo8ku.csb.app/?pbjs_debug=true

### Expected results
With caching turned on it works as expected. The messages are in that order:
```
MESSAGE: Emitting event for: requestBids
INFO: currencyRates set to {"dataAsOf":....
...
MESSAGE: Emitting event for: beforeRequestBids
...
MESSAGE: CALLING BIDDER
MESSAGE: Emitting event for: bidRequested
INFO: getCurrencyConversion using reciprocal EUR to USD conversionRate 1.0894
MESSAGE: Adding conversionCache value 1.0894 for EUR->USD
MESSAGE: Emitting event for: beforeBidderHttp
```

### Actual results
With caching turned off the messages are in that order:
```
MESSAGE: Emitting event for: requestBids
...
MESSAGE: Emitting event for: beforeRequestBids
...
MESSAGE: CALLING BIDDER
MESSAGE: Emitting event for: bidRequested
INFO: getCurrencyConversion using direct EUR to USD conversionRate 10
MESSAGE: Adding conversionCache value 10 for EUR->USD
MESSAGE: Emitting event for: beforeBidderHttp
INFO: currencyRates set to {"dataAsOf":...
```

## Platform details
Prebid 7.34.0, Chrome 109.0.5414.120, Windows 10, Node 14.20.0, npm 6.14.17

**Comment by dgirardi** [comment]
I believe this is intentional, with the assumption that waiting to load conversion rates will have more of an impact on revenue than using an inaccurate rate for floors. 

The floors module has a setting, [`auctionDelay`[(https://docs.prebid.org/dev-docs/modules/floors.html), that currently works as a timeout only for the case when floor data is loaded from the network. We could expand this to mean "wait up to this much for currencies to be loaded" as well. 

Alternatively we could introduce a similar settings for the currency module - which would be more appropriate if there are other use cases for currency conversion immediately after page load, which I am not aware of.

**Comment by patmmccann** [comment]
It seems OP is indeed proposing a currency file timeout. I suggest a default of 0 ms.

**Comment by dgirardi** [comment]
Are you suggesting something like this @patmmccann? 

```
pbjs.setConfig({
   currency: {
       auctionDelay: [...]
   }
})
```

AFAIK right now it's only floors that needs currencies before the first auction, and the currency module never delays it, so this setting would only make sense for this particular situation (using both currency and floors with the delay for the latter). For this reason I am not sure that this is preferable to `setConfig({floors: {auctionDelay}})`

**Comment by patmmccann** [comment]
Goog point, but should `setConfig({floors: {auctionDelay}})` control two dependencies, or should they each have their own timeout, eg `setConfig({floors: {auctionDelay}})` and `setConfig({floors: {auctionCurrencyFileDelay}})`

**Comment by dgirardi** [comment]
I don't see a point in having two separate controls; if you are delaying the auction anyway, why would you give up on one or the other halfway?

**Comment by dgirardi** [comment]
Agreed to go this route:

```
pbjs.setConfig({
   currency: {
       auctionDelay: [...]
   }
})
```
