### ISSUE TITLE
Circle CI Error

### ISSUE THREAD

**Issue by sfloam** [prebid/Prebid.js#9494]
## Type of issue

Question
## Description

When attempting to make a PR to Prebid.js, I receive the following error:
Could not find a usable config.yml, you may have revoked the CircleCI OAuth app. Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.

Do I need to be added to the organization for this to run? When running on my fork, I get the following error:

![image](https://user-images.githubusercontent.com/9473833/216103015-af4576b4-28e3-4dd5-a19e-8724c951739e.png)

This is related to https://github.com/prebid/Prebid.js/pull/9492

**Comment by ChrisHuie** [comment]
@sfloam in CircleCI are you following your fork of the project instead of the main Prebid.js project? Unfollowing your fork usually fixes these types of issues.
