### ISSUE TITLE
`onBidWon` sometimes runs on s2s bids

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#9515]
## Type of issue

Bug / Improvement

## Description

An adapter's `onBidWon` handler will run on s2s bids if it's included in the bundle, but obviously not if it isn't. Besides the difference in behavior in itself, it's likely that not all adapters can actually accept an s2s bid in their `onBidWon` handler: they may expect it to be one that they generated. For example:

https://github.com/prebid/Prebid.js/blob/ec182d0e974c6b745855b259e9655fb23a7be044/modules/adpartnerBidAdapter.js#L124-L138

## Proposal

The new `onBidBillable` method to be introduced for https://github.com/prebid/Prebid.js/issues/4494 will be invoked _only for client side bids_.
Starting from version 8, `onBidWon` will also be invoked only for client-side bids.

**Comment by patmmccann** [comment]
#8539
