### ISSUE TITLE
Fix for empty targeting key hb_acat being sent in DFP call

### ISSUE THREAD

**Issue by jlquaccia** [prebid/Prebid.js#9529]
## Type of issue
Bug

## Description
https://github.com/prebid/Prebid.js/issues/9217 setup the logic pass along acat, if present with dfp calls.  However, the default for hb_acat is being set to an empty string and being sent, `hb_acat=`.  If acat doesn't exist on a page, hb_acat= should not be sent at all.

## Other information
Relates to https://github.com/prebid/Prebid.js/issues/9217

**Comment by bretg** [comment]
@jlquaccia - thanks for reporting this, but can we close this issue since there's a PR open already?

**Comment by jlquaccia** [comment]
@bretg, sure, if the PR for this ticket looks good we can close this one.
