### ISSUE TITLE
New Module to Detect Ad Slot Visibility for Billing w/ Gpt

### ISSUE THREAD

**Issue by jlquaccia** [prebid/Prebid.js#9531]
## Type of issue
Feature Request

## Description
https://github.com/prebid/Prebid.js/issues/4494 describes adding support for loading an ad and optionally not firing billing notifications.  The current proposal to achieve this is outlined in 4494 here: https://github.com/prebid/Prebid.js/issues/4494#issuecomment-1412487621

The feature request for this ticket would be to create a new module (called something like "visibilityForBillingGpt"), and enable it behind a setConfig option.  The module would perform the following logic:

1. Keep track of winnings bids.
2. Keep track of whether or not the associated ad unit of the winning bid is flagged with deferBilling or not.
3. Monitor if the associated ad unit of the winning bid has become visible in the viewport (Visibility detection can be utilized via an event listener provided by the gpt.js api since GAM is so widely used).
4. If the criteria for points 1-3 above are met, then core will be informed of this and emit the billable event.
5. Lastly, a publisher could listen for this billable event and proceed accordingly.

## Other information
https://github.com/prebid/Prebid.js/issues/4494

**Comment by bretg** [comment]
@jlquaccia - this overlaps with several other items that in progress: nurl, burl, loss notifications.

As for viewability, we just had to drop a module that was considered insecure. 

We would like to see a comprehensive approach for this issue that fits these disparate threads. Are you willing to take lead on the requirements here?

**Comment by jlquaccia** [comment]
Thanks @bretg,

Sure, I would be happy to take on the req's for this one!  (Will also be sure to compare against the other proposed tickets as well as I go).

Was thinking I could also take on the implementation of the proposal outlined here: https://github.com/prebid/Prebid.js/issues/4494#issuecomment-1412487621.  Would be a separate GH Issue ticket to take on of course, but definitely relates to the intent of this ticket (step 5 on the proposal).

Lastly, as for the viewability module that was deemed insecure, was it this one? https://github.com/prebid/Prebid.js/blob/master/modules/viewability.js Was just curious so that I could learn from what may have gone wrong.

**Comment by jlquaccia** [comment]
Hey @bretg, sync'd up with some other people at PubMatic today, we were thinking we could combine the logic in the description of this ticket with the [bidViewability.js](https://github.com/prebid/Prebid.js/blob/master/modules/bidViewability.js) module behind an extra config setting.  Since bidViewability is already using gpt and the same gpt event that would be needed.

**Comment by jlquaccia** [comment]
Had gotten swept up in work for other tickets in the past couple weeks, but this week I will be able to resume work on https://github.com/prebid/Prebid.js/issues/4494#issuecomment-1412487621 and the work for this ticket.

**Comment by patmmccann** [comment]
closing as complete https://github.com/prebid/Prebid.js/pull/10326
