### ISSUE TITLE
seatbid.bid.mtype is erroneously required in ortb response

### ISSUE THREAD

**Issue by ShortRoundDev** [prebid/Prebid.js#9536]
## Type of issue
Bug

## Description
If an OpenRTB bidder response does not include the `mtype` attribute on the bid object, an error is thrown and the bid response is discarded. This does not conform to OpenRTB 2.6. [According to the specification](https://iabtechlab.com/wp-content/uploads/2022/04/OpenRTB-2-6_FINAL.pdf):

> As that term is used herein, “required” attributes are designated as such if their omission would technically break the protocol. This means that it is technically possible for two implementers to conduct a minimally viable transaction if all required attributes are included, and impossible without them

`mtype` is listed only as `integer` on page 41 of 85, and not explicitly required. 

The error is thrown at https://github.com/prebid/Prebid.js/blob/master/libraries/ortbConverter/processors/mediaType.js#L18

## Steps to reproduce
1. Make a bid request against an OpenRTB bidder which does not return `mtype` in the bid response.
2. Bid response is discarded

### Expected results
Bid response should not be discarded because an optional attribute is not implemented

### Actual results
Bid response is discarded because an optional attribute is not implemented

## Platform details
Encountered on prebidjs version `7.36.0-pre`

## Other information
Error screenshot with `?pbjs_debug=true`:

![image](https://user-images.githubusercontent.com/8528613/218522781-0335559b-3c86-4da3-9522-a5704aa8a121.png)

**Comment by dgirardi** [comment]
I'm assuming you are implementing a new bid adapter using the ORTB conversion library; one of the things it needs is a way to tell a bid's mediatype. `mtype` is the default, but if it's not provided you'll see that error. See the [README](https://github.com/prebid/Prebid.js/blob/master/libraries/ortbConverter/README.md#-example-setting-response-mediatype).

If that's _not_ the case, please expand on steps to reproduce - this should not be happening with any of the bidders in master.

**Comment by ChrisHuie** [comment]
Closing if provided comment didn't assist please feel free to reopen
