### ISSUE TITLE
Vidoomy is missing floor module support despite supporting floors

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#9541]
## Type of issue

Bid adapter not conforming to prebid.js standards

## Description

Vidoomy supports floors:

https://github.com/prebid/Prebid.js/blob/3a9d4cafccc1da31fdd34cae4db33a1078ccca20/modules/vidoomyBidAdapter.js#L41-L44

but is missing the floor modules integration.

**Comment by ChrisHuie** [comment]
@mario-orle can you please assist in updating Vidoomy adapter in using floors module over passing a parameter

**Comment by nisart007** [comment]
Please close this issue, floor module integrated into vidoomy adapter.
