### ISSUE TITLE
New Video module MediaTypes:{ Video { ,  wont take values

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#9560]
The new video module doesnt seem to take multiple values in the mediaTypes{ video.  Its only sending the first value
![Screenshot_18_02_2023__18_38](https://user-images.githubusercontent.com/8503167/219882713-26aa9611-15dd-4447-ae2e-48a8152acda9.png)

when i have multiple value set in some:
playbackmethod: [2, 6],
protocols: [1, 2, 3, 4, 5, 6, 7, 8]
api: [1, 2, 3, 4, 5, 6],

there also seems to be some "constants" such as mimes, boxingallowed, playbackend

I presume its @karimMourra that will look?

**Comment by spormeon** [comment]
I can see where these are coming from now, the videojs module": videojsVideoProvidor.js,  its setting them there but shouldnt we be allowed to override these in the usual "prebid way" of anything we put in the prebid scripts direct in the mediaTypes{ video {  ,takes precedent.  Gives a harmony across all banner, native, video etc then?

![videojsVideoProvider_js_—_Prebid_js](https://user-images.githubusercontent.com/8503167/219939673-0c7e34f1-0571-4872-9db5-8168310bcf0a.png)

its also automatically setting context: outstream, but i cant for the life of me find where that is in the newvideomodule scripts and thats when i set mediaTypes{ video {} }
![Screenshot_19_02_2023__09_28](https://user-images.githubusercontent.com/8503167/219940027-2a34dfe2-248d-4641-9898-0a225b1312f8.png)

**Comment by spormeon** [comment]
videojs mdule, is also missing the ability to set the ima options such as:enableOmidBeta: true, 
                  preventLateAdStart: false, 
                  disableFlashAds: true, 
                  prerollTimeout: 18000, 
                  autoPlayAdBreaks: true, 
                  vastLoadTimeout: 8000, 
                  numRedirects: 6, 
                  disableCustomPlaybackForIOS10Plus: true, 
                  vpaidMode: 'ENABLED', 
                  cookiesEnabled: true,

setting in the adPluginConfig: {} does nothing:
![playlist_html_—_Prebid_js](https://user-images.githubusercontent.com/8503167/220188900-0685ac17-d342-42a1-a4ae-354039f51093.png)

**Comment by karimMourra** [comment]
Hi @spormeon if i understand correctly, you are reporting 2 issues:
1) the video params reported by the video player submodule is overriding the publisher's settings
2) Params passed in the `adPluginConfig` for video.js are not being applied.

Please let me know if this is correct, in the meantime I will investigate, thanks!

**Comment by karimMourra** [comment]
Hey @spormeon I am making changes so that existing video params defined by the publisher take precedence, but I must point out that the idea of having the videojs submodule define the params comes from the fact that the videojs submodule should be the source of truth for everything video.js related. In the case for example of playback method, if the video.js instance is configured to autostart, then i think the value should only be 1. I think it would be misleading for it to include other values like 3 (click-to-play). 
The idea of this is to make it easier for publishers, since they no longer have to worry about the values being set, they can trust that the video.js submodule will set the accurate values, and at the same time SSPs can trust that the values are accurate because they come from the video player which is the source of truth. 
If the video.js submodule is wrong, then that is a bug needed to be fixed in the submodule.

**Comment by karimMourra** [comment]
@spormeon regarding the IMA configuration, i don't see some of those params in the doc https://github.com/googleads/videojs-ima, are you sure they are supported ? 
In your test environment, if you add a breakpoint at the following line https://github.com/prebid/Prebid.js/blob/master/modules/videojsVideoProvider.js#L525, could you please confirm that the object is as expected ?

**Comment by spormeon** [comment]
To reply 1. Yes, to reply 2. Yes. On ima settings there all in additional settings on videojs Ima GitHub. As there are settings for contrib ads and ima settings it's not clear what adPluginSettings will actually set, one of, both of but non work at moment . I'll try line 525 but I'm away in Poland at mo, not back until next week

**Comment by karimMourra** [comment]
@spormeon the `adPluginConfig` is being passed directly into `player.ima` similar to the example in the videojs-ima gh readme
```
var player = videojs('content_video');

var options = {
  adTagUrl: 'YOUR_AD_TAG'
};

player.ima(options);
```

**Comment by karimMourra** [comment]
In fact, this works in our demo in https://github.com/prebid/Prebid.js/blob/master/integrationExamples/videoModule/videojs/gamAdServerMediation.html#L55

**Comment by spormeon** [comment]
@karimMourra I've tried these ima options in following but def dont work.  i.e you can see the adLabel: 'Ad' is not set, these are pretty much all the videojs ima "options"
adPluginConfig: {
                  debug: true,
                  ppid: true,  
                  enableOmidBeta: true, 
                  preventLateAdStart: false, 
                  disableFlashAds: true, 
                  prerollTimeout: 10000, 
                  autoPlayAdBreaks: true, 
                  vastLoadTimeout: 8000, 
                  numRedirects: 8, 
                  disableCustomPlaybackForIOS10Plus: true, 
                  vpaidMode: 'ENABLED', 
                  cookiesEnabled: true,
                  adLabel: 'Ad',
                  AdsRenderingSettings: {
                  autoAlign: false,
                  bitrate: 1800,
                  useStyledNonLinearAds: true,
                  },
                  omidVendorAccess: {
                  OmidAccessMode: 'FULL',
                  OmidVerificationVendor: 'OTHER'
                  },
                  contribAdsSettings: {
                    timeout: 5000,
                    prerollTimeout: 10000,
                    allowVjsAutoplay: true,
                    debug: true
                  },
                },
                vendorConfig: {
![Adysis_Video_Demo](https://user-images.githubusercontent.com/8503167/222896189-25587921-bddb-4afd-8fa1-d600be7ddb04.png)

**Comment by spormeon** [comment]
update, seems to now work in prebid V 7.39.0, so all good on IMA "options" & contrib Ads options by looks
