### ISSUE TITLE
Remove Inskin bid adapter

### ISSUE THREAD

**Issue by cciocov** [prebid/Prebid.js#9567]
## Type of issue

Remove the Inskin bid adapter

## Description

We would like to remove the Inskin bid adapter, as it should no longer be used by publishers. Can you please advise on what's the best way to do this? Thank you.

**Comment by patmmccann** [comment]
Please see #9358

**Comment by patmmccann** [comment]
tagging #8539

**Comment by patmmccann** [comment]
Completed
