### ISSUE TITLE
JW RTD Adapter: endpoint responds in an unexpected way

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9569]
## Type of issue

https://github.com/prebid/Prebid.js/pull/9153#issuecomment-1434827414 @TheMediaGrid flags the JW RTD module as not responding consistently over repeated calls. I'm opening this issue to move the discussion off the closed PR.

**Comment by karimMourra** [comment]
@patmmccann this is related to the playlist shuffling and is being discussed in our cross team channel. If you're not aware I can link you the discussion
