### ISSUE TITLE
Placement Refresh Auction & removeAdUnit() 

### ISSUE THREAD

**Issue by jarrettabello** [prebid/Prebid.js#958]
## Type of issue
Question/Bug

## Description
I am running a modified version of the post-bid using prebid.js v14.0 - One of our partners asked that they be removed from any refresh auction while still being involved in the initial on page load.

Prior to my refresh auction I attempted a number of steps to exclude that partner. I attempted to set a flag on the client and detect in my bidderSetting and adjust their cpm down to 0. 

I tested .clearAuction() (but I really don't understand its functionality)

I also attempted to remove all ad units using .removeAdUnit() - which did empty the .adUnits array, I then attempted to rebuild the adUnits without the partner included at all. I confirmed that the partner was not listed in the .bids array of adUnits themselves. 

However, despite all above attempts the partners first bid was still winning the refresh auction. After much fiddling I cleared the pbjs._bidsReceived array and ran the refresh auction without the partner included in the adUnits and it worked as expected. 

In my opinion, using removeAdUnit(), rebuilding the adUnits using.addAdUnits() without the new partner should have given me my desired result.  

My suggestion is to clear the matching entries in _bidsReceived to the value passed in removeAdUnit() as to completely remove any reference to that adUnit. 

Another possibility would be to add an additional cleaner function such as removeBidder() that takes the Bidder out of contention. 

I am open to suggestion of best practices as well. 

Thank you!

**Comment by matthewlane** [comment]
This does sound like a bug. After removing the ad unit, then rebuilding and the ad unit without a bidder and using `addAdUnits`, you should be getting the results you've described. I'll link to this issue when we have an update, though feel free to open a PR in the meantime if you'd like. Thanks for reporting this

**Comment by mkendall07** [comment]
please retest once prebid-1.0 is released. If still an issue - feel free to reopen
