### ISSUE TITLE
Consent Management: make getTCData container object on static consent optional

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9581]
## Type of issue
Bug

## Description
IABTL Action Plan likely will deprecate getTCData. Whether or not this happens, it is recommended not to use it. Let's immediately remove all references to it from the project. Luckily most references are just in unit tests, as consentManagement.js only uses it in the case of static consent

**Comment by patmmccann** [comment]
Tagging #8539 as this change is breaking

https://docs.prebid.org/dev-docs/modules/consentManagement.html example 3 will need to change

**Comment by dgirardi** [comment]
I am not sure this is worth the breaking change. `getTCData` appears to be a remnant from TCFv1, it's not useful anymore, but forcing a rename to something else seems to me like pure friction with no advantage.

**Comment by dgirardi** [comment]
Agreed offline that we should make the  `getTCData` configuration "container" optional, e.g. support both `gdpr: {consentData: {tcData: {...}}}` and `gdpr: {consentData: {...}}`

**Comment by patmmccann** [comment]
just for notetaking, we took care of https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/334/files here
