### ISSUE TITLE
Prebid 8 - Move md file information for adapters to docs and remove from repo

### ISSUE THREAD

**Issue by ChrisHuie** [prebid/Prebid.js#9593]
To my knowledge the JS repo is the only one that includes supplemental documentation on all adapters and modules in the form of identically named markdown files. This proposes merging that documentation with the already existing docs in the docs repo and removing from the Prebd.js repo.

**Comment by patmmccann** [comment]
no longer require md submission, encourage deletion and migration to docs site

**Comment by patmmccann** [comment]
we also need to move maintainers into comments

**Comment by dgirardi** [comment]
My approach would be:

1. Move some .md file into docs, to use as an example and figure out the structure. There are some items (such as maintainer) that we want to keep but we may not want to show in the public website.
2. Update the new bid adapter guide to stop asking for an .md
3. At every docs PR submission, reviewers should ask to move the .md over.

Also, this is not a breaking change - does not need to tied to 8.

**Comment by patmmccann** [comment]
Resolution: reviewers will ask for information that isnt extremely technical to be removed from md files. Md files will continue to live with technical utility, eg test params.
