### ISSUE TITLE
Prebid 8 - No longer storing the currency file in s3

### ISSUE THREAD

**Issue by ChrisHuie** [prebid/Prebid.js#9596]
We have previously requested the few remaining publishers pulling the currency file from s3 to migrate. There still seems to be a few straggling requests so this issue is to propose removing the file from s3.

**Comment by patmmccann** [comment]
if it turns out the money we spend is minimal, opportunity to close without implementing

**Comment by bretg** [comment]
Things are much better than they were a few months ago. Here the current top domains still hitting currency.prebid.org
- ilsole24ore.com
- treccani.it
- minkara.carview.co.jp
- www.dagospia.com
- inews.co.uk
- www.weekendhk.com
- www.greenme.it
- www.ilpost.it
- pubads.g.doubleclick.net
- www.gazzetta.it
- www.orientalsunday.hk
- bestof.dailymail.com
- tuttojuve.co

**Comment by patmmccann** [comment]
Closing as not needed due to low budget impact
