### ISSUE TITLE
Prebid 8 - Consolidate size mapping logic

### ISSUE THREAD

**Issue by ChrisHuie** [prebid/Prebid.js#9597]
This issue is to propose and track the consolidation the logic around size mapping for individual bidders

**Comment by dgirardi** [comment]
Tentative proposal:

 - move the v1 logic into a module (the same sizeMappingV2 module)? and expand it to work on video/native as well
 - from prebid 8, people interested in mediaQuery mapping and labels should include the module.

**Comment by dgirardi** [comment]
Related: https://github.com/prebid/Prebid.js/issues/4135  (sizeMapping V1 does not work for video/native). This is an opportunity to consolidate v1 and v2.

**Comment by patmmccann** [comment]
Inclusion dependent on minimal configuration impact to publishers using existing module(s)
