### ISSUE TITLE
Latest example loading but nothing more...

### ISSUE THREAD

**Issue by mrpbennett** [prebid/Prebid.js#960]
## Latest example not working.

I have the following [page](http://medialondon.io/pbjs.html?pbjs_debug=true) set up using the [this example](https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/pbjs_example_gpt.html)

I can never get this to work, I have tried to implement it a few times but since ever `$$PREBID_GLOBAL$$` was introduced I cant see to get an ad.

## Working example.

I can however use one of the legacy examples mainly this [one](https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/load_pbjs_before_dfp_example.html) to work every time I have an example [here](http://medialondon.io/index.html)

## Advice

Does anyone have any pointers in what I am doing incorrectly with the latest example, i feel as this one is regularly updated this is the one publishers will be seeking out

**Comment by mkendall07** [comment]
Rename `$$PREBID_GLOBAL$$` to `pbjs` in your code.
