### ISSUE TITLE
New advertisers for Headerbid Expert

### ISSUE THREAD

**Issue by tedrand** [prebid/Prebid.js#961]
## Type of issue

Feature Request

## Description

Hi guys, I'm not sure if you maintain the Chrome Extension called headerbid expert, but in the details for it, it redirected me to this repo. Just wondering if you could add these bidder patterns for convenience:

```
'Roxot': [
		'r.rxthdr.com'
	], 

	'Komoona': [
		's.komoona.com'
	]

```

Please let me know if there is a better stream for this. Thanks.

**Comment by mkendall07** [comment]
@tedrand 
Apologies on the delay. Yes we maintain it. We'll update it soon. Thanks.

**Comment by ptomasroos** [comment]
Can you please add Widespace as well @mkendall07 
'Widespace': [
		'engine.widespace.com'
	],

**Comment by eliyastein** [comment]
Has there been any talk of open sourcing the extension? I think the community could really benefit from that instead of creating in-house solutions for troubleshooting.

**Comment by matthewlane** [comment]
Roxot, Komoona, and Widespace patterns have been added to Headerbid Expert 1.5.10, just published to Chrome web store.

@eliyastein Yes, we have plans to work on open sourcing the extension

**Comment by parisholley** [comment]
@matthewlane could we get mantis included as well? :)

```
'MANTIS':['mantodea.mantisadnetwork.com']
```

**Comment by matthewlane** [comment]
@parisholley Yep, Mantis is now in 1.5.11
