### ISSUE TITLE
Ortb requests and legacy native responses

### ISSUE THREAD

**Issue by Hamper** [prebid/Prebid.js#9622]
## Type of issue
I think this is a bug

## Description
I trying to use native examples from documentation but get some errors when trying to use adTemplates with appnexus native placement from https://docs.prebid.org/dev-docs/adunit-reference.html#adUnit-native-example with template from https://docs.prebid.org/prebid/native-implementation.html#421-prebidjs-adunit-setup

## Steps to reproduce

```js
"mediaTypes": {
    "native": {
        sendTargetingKeys: false,
        adTemplate: `<div class="sponsored-post">
                <div class="thumbnail" style="background-image: url(##hb_native_asset_id_1##);"></div>
                <div class="content">
                    <h1>
                        <a href="%%CLICK_URL_UNESC%%##hb_native_linkurl##" target="_blank" class="pb-click" hb_native_asset_id="2">##hb_native_asset_id_2##</a>
                    </h1>
                    <p>##hb_native_asset_id_4##</p>
                    <div class="attribution">##hb_native_asset_id_3##</div>
                </div>
            </div>`,
        ortb: {
            ver: "1.2",
            assets: [{
                id: 1,
                required: 1,
                img: {
                    type: 1,
                    hmin: 50,
                    wmin: 1
                },
            }, {
                id: 2,
                //required: 1,
                title: {
                    len: 80
                },
            }, {
                id: 3,
                //required: 1,
                data: {
                    type: 1,
                    len: 30
                },
            }, {
                id: 4,
                //required: 1,
                data: {
                    type: 2,
                    len: 100
                },
            }, {
                id: 5,
                //required: 1,
                img: {
                    type: 3,
                    hmin: 200,
                    wmin: 267
                }
            }]
        }
    }
},
"bids": [{
    bidder: 'appnexus',
    params: {
        placementId: 13232354
    }
}]
```

### Expected results
Valid ad rendering

### Actual results
Error in console:
![Screenshot_20230303_223859](https://user-images.githubusercontent.com/1700097/222811815-e3ba2b2d-7596-42fe-af57-7cf48aeeae7a.png)

Only legacy assets in response (don't see hb_native_asset_id_[X])
![Screenshot_20230303_224017](https://user-images.githubusercontent.com/1700097/222811863-81371157-be90-4514-bdfa-7f6283093bbe.png)

hb_native_asset_id_[X] placeholders not replaced
![Screenshot_20230303_224415](https://user-images.githubusercontent.com/1700097/222812406-5d1f3279-544a-42db-81ff-336f43be9d0a.png)

## Platform details

prebid.js v7.39.0
PUC v1.16.0-pre (my build because I use custom prebid global object)

**Comment by patmmccann** [comment]
@Hamper are you able to provide a test page?
