### ISSUE TITLE
Is pbjs.mergeConfig(options) available to all?

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#9654]
we are trying to use pbjs.mergeConfig(options)  to push some cust_params into:
adyjs.mergeConfig({
	video: {
		providers: {
			adServer: {
				params: {
					cust_params: custParams
				}
			}
		}
	}
});

but its not working and the video adTagUrl is getting built with the cust_params, should this method work?

**Comment by spormeon** [comment]
basically we are calling Amazon, collecting the cust_params from the bid, decoding them and trying to push them to setConfig
video: {
providers: {
adServer: {
params: {
cust_params: custParams
}
}
}
}
});




let custParams = {};
function handleVideoBids(bids) {
  if (bids.length > 0) {
		let bidData = decodeURIComponent(bids[0].encodedQsParams);

		custParams = bidData.split("&").reduce(function(obj, str, index) {
			let strParts = str.split("=");
			if (strParts[0] != '') {
				obj[strParts[0]] = strParts[1];
			}
			return obj;
		}, {});
    adyjs.mergeConfig({
	video: {
		providers: {
			adServer: {
				params: {
					cust_params: custParams
				}
			}
		}
	}
});
		console.log('adysis', custParams);
  } 
};


the cust_params log out to consule, but never make it/ dont get built on the adTagUrl

**Comment by patmmccann** [comment]
Please provide steps to reproduce; we cannot reproduce.
