### ISSUE TITLE
ortb.user.keywords getting filtered out 

### ISSUE THREAD

**Issue by pm-manasi-moghe** [prebid/Prebid.js#9669]
## Type of issue
bug

## Description
ortb.user.keywords data configured through setConfig method are getting filtered out and not getting sent to SSP calls in user.keywords object. This was working as expected in prebid version 7.25.0, but we have noticed this change from version 7.37 onwards.

## Steps to reproduce
Call the following function on page: 
pbjs.setConfig({
      ortb2: {
          user: {
            yob: 1985,
            gender: "m",
            keywords: "a,b",
            data: [{
              name: "dataprovider.com",
              ext: { taxonomyname: "iab_audience_taxonomy" },
              segment: [ {id: "4"} ]
            }],
            ext: {
              data: {
                registered: true,
                interests: ["cars"]
              }
            }
          }
      }
}
);
user.keywords value is seen as "" in PubMatic's /translator call. Whereas it should have the values "a,b" in it.

### Expected results
user.keywords = "a,b"

### Actual results
user.keywords = ""

## Platform details
First seen in prebid version 7.37

**Comment by dgirardi** [comment]
I am unable to reproduce (tried on both master and 7.37):

![image](https://user-images.githubusercontent.com/10151381/225338554-09e8d3ac-494d-4035-812f-1ee96101457c.png)


You may have some other configuration / modules that are causing this - would you be able to reproduce the issue in a test page?

**Comment by patmmccann** [comment]
closing as stale; cannot reach @pm-manasi-moghe
