### ISSUE TITLE
Adapters that accept geolocation data from bid parameters should also accept it from `ortb2.(device|user).geo`

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#9676]
## Type of issue

Improvement

## Description

Several adapters accept location data as, for example, `bid.params.(lat|long)`, but not from ORTB2 first-party data. With [GPP phase 3](https://github.com/prebid/Prebid.js/issues/9546), we plan to give publishers centralized controls over what happens to location data in different regulatory environments; that can only work if the communication channel is also centralized through `setConfig({ortb2})`.

## Other information

List of affected adapters (at least those that are amenable to grep):

* [apacdex](https://github.com/prebid/Prebid.js/blob/06df26e8d8b3ea4206b08388462a3936323e9191/modules/apacdexBidAdapter.js#L310) - @thuyhq 
* [ebdr](https://github.com/prebid/Prebid.js/blob/06df26e8d8b3ea4206b08388462a3936323e9191/modules/ebdrBidAdapter.js#L39) -  @jlzhangdev 
* [mediafuse](https://github.com/prebid/Prebid.js/blob/06df26e8d8b3ea4206b08388462a3936323e9191/modules/mediafuseBidAdapter.js#L21) - @balajimediafuse 
* [microad](https://github.com/prebid/Prebid.js/blob/06df26e8d8b3ea4206b08388462a3936323e9191/modules/microadBidAdapter.js#L97) - @azuryo 
* [pubmatic](https://github.com/prebid/Prebid.js/blob/06df26e8d8b3ea4206b08388462a3936323e9191/modules/pubmaticBidAdapter.js#L207) - @pm-harshad-mane 
* [pubwise](https://github.com/prebid/Prebid.js/blob/06df26e8d8b3ea4206b08388462a3936323e9191/modules/pubwiseBidAdapter.js#L227) - @GLStephen 

* [zeta](https://github.com/prebid/Prebid.js/blob/06df26e8d8b3ea4206b08388462a3936323e9191/modules/zetaBidAdapter.js#L43) -  @mwehr-zeta

**Comment by pm-harshad-mane** [comment]
@pm-azhar-mulla, @kapil-tuptewar please look into this.
