### ISSUE TITLE
Video module:  rendered status failing in gamadservermediation demo

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#9686]
there seems to be a problem in the video module GAM demo, If i test the bidrequestscheduling demo, the bids get marked as rendered, but if i test the gamadservermediation demo, the bids dont get marked as rendered.  This replicates in a live test as well.  It is possible to mark bids as rendered with gam, as we do it with our VMAP setup.  So i'm guessing there is some problem in the video module somewhere:

bidrequestscheduling:
![DevTools_-_127_0_0_1_5500_integrationExamples_videoModule_videojs_bidRequestScheduling_html_and_bidRequestScheduling_html_—_Prebid_js](https://user-images.githubusercontent.com/8503167/226106963-d5e33c93-0e3e-44af-a42e-9ab096d6cb85.png)

gam demo:
![DevTools_-_127_0_0_1_5500_integrationExamples_videoModule_videojs_gamAdServerMediation_html](https://user-images.githubusercontent.com/8503167/226106999-a79fcabb-ab92-418a-b5c2-04cf9a766b1d.png)

from our VMAP setup:

![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_IncontentDemo_html](https://user-images.githubusercontent.com/8503167/226107028-5e841df8-179b-4956-b148-fa2efe387d07.png)

we use the following:

![PrebidVideoIncontent_js_—_Prebid_Publishers__Workspace_](https://user-images.githubusercontent.com/8503167/226107113-fe8adcd0-2b68-4592-b42d-9412b7ed130b.png)

**Comment by karimMourra** [comment]
this should be addressed in https://github.com/prebid/Prebid.js/pull/9612

**Comment by karimMourra** [comment]
@spormeon it appears that this was fixed in #9612. Could you please reopen if the issue persists ?
