### ISSUE TITLE
Will Bidder Service API be inspected during review?

### ISSUE THREAD

**Issue by czarpino** [prebid/Prebid.js#9688]
## Type of issue
Question

## Description
We are preparing a new BidAdapter for review. One concern is whether the bidder service API will be hit/inspected during review because the server is in Japan and it may need some preparation to serve a request from outside.

**Comment by ChrisHuie** [comment]
Yes. The reviewers test new bid adapters. If this is a special situation we can discuss though.

**Comment by czarpino** [comment]
Hi @ChrisHuie. Thanks for the quick response 🙏  Sorry, just to confirm, I guess the bidder service API also only needs to be available for the duration of the review? Target publishers are mainly from Japan only so the service API is usually made available only locally as well.
