### ISSUE TITLE
pbMg incorrectly capped at $10

### ISSUE THREAD

**Issue by prebid** [prebid/Prebid.js#97]
When a bid is at $11, and the ad server targeting setting is default (which should be using pbMg), prebid.js incorrectly caps it at $10, which is different from the documentation: http://prebid.org/publisher-api.html#available-bidresponse-values

**Comment by mkendall07** [comment]
Already resolved: https://github.com/prebid/Prebid.js/commit/b26632581f0f7e0f367e0bf726ff20dd13c85a99
