### ISSUE TITLE
Prebid.js with AdX floors

### ISSUE THREAD

**Issue by carsonmc** [prebid/Prebid.js#970]
## Type of issue
question

## Description
We are currently running prebid.js with AdX as backfill. AdX was winning the lion's share of the bids so I decided to play with the floor on one of our placements and raise it to a value in between the average closing price of the auction and the average winning bid price (according to AdX reporting) to try and get more value out of AdX.
We have a lot of partners in the header so we figured if AdX gets outpriced by the floor, we will still fill the impression with one of our other demand partners.
After the price floor implementation, we started receiving a lot of unfilled impressions - even though we were still receiving bids from our other partners below the floor. So in theory, the winning bidder should get passed to DFP, then AdX should get last look and determine if it can beat the $1.00 price floor, if it can't then the winning bid should serve. Instead, we're just getting a blank.
Any ideas??
Our initial thought was AdX can beat the winning bid, so the line item is allocated to AdX, but then it can't serve because the bid isn't above the floor - is that feasible?
Any help or similar experience is appreciated.

## Platform details
prebid 0.16.0

**Comment by mkendall07** [comment]
@mjacobsonny any thoughts?

**Comment by mjacobsonny** [comment]
@carsonmc -- Sounds like a reasonable theory, but I don't think we have enough visibility into DFP dynamic allocation auction mechanics to know for sure.  I'd guess it depends on where AdX floors are evaluated in the auction (i.e. whether they are evaluated before or after the AdX Line Item is chosen as the winner over other eligible Prebid price priority LIs).

Are you able to use DFP troubleshooting tools to investigate further (for example, seeing which LI is chosen through the DFP "Ad Request Simulator" or something similar)?

**Comment by BartVB** [comment]
We are using a comparable setup, but I don't recognise this behaviour?

I must say that we haven't tested this extensively, we have been using floors before implementing Prebid.org so it's hard to compare fillrates before/after.

@carsonmc ; Just like @mjacobsonny I'm very curious what debugging through the DFP tools tells you. I would start with checking out the delivery details from the GPT console:
https://support.google.com/dfp_premium/answer/2462712

This would tell you what exact line-items are considered/rejected when Prebid competes with AdX.

**Comment by ptomasroos** [comment]
How about booking a House campaign @carsonmc ? Pretty sure that would work if you target the same adunit in DFP.

See section House here.
https://support.google.com/dfp_premium/answer/177279?hl=en

You could then call back to pbjs with the same parameters as the usual winning creative.
Should work. That would mean if no line items with higher priority can take the item it will fall down to this.
