### ISSUE TITLE
Bid Adapters pulling tmax from config instead of bidderRequest object

### ISSUE THREAD

**Issue by Justin-Quinn51** [prebid/Prebid.js#9705]
## Type of issue
Enforcement

## Description
The following bid adapters are pulling tmax from config.getConfig('bidderTimeout'):

- [ ] acuityAds
- [ ] amx
- [ ] appush
- [ ] beyondMedia
- [ ] brave
- [ ] brightcom
- [ ] brightcomSSP
- [ ] coinzilla
- [ ] compass
- [ ] contextexchange
- [ ] glimpse
- [ ] globalsun
- [ ] grid
- [ ] gridNM
- [ ] gumgum
- [ ] iqzone
- [ ] kobler
- [ ] kueez
- [ ] luponmedia
- [ ] mathildeads
- [ ] medianet
- [ ] minutemedia
- [ ] nexx360
- [ ] onomagic
- [ ] operaads
- [ ] pubmatic
- [ ] rise
- [ ] sharethrough
- [ ] shinez
- [ ] smarthub
- [ ] synacormedia
- [ ] truereach
- [ ] videoheroes
- [ ] visiblemeasures
- [ ] vrtcal

## Other information
References #9287

**Comment by patmmccann** [comment]
A bunch of these remain 
https://github.com/prebid/Prebid.js/blob/56292c4672a0b19bee34840dca93bd3e1e5b8afe/modules/visxBidAdapter.js#L115
https://github.com/prebid/Prebid.js/blob/56292c4672a0b19bee34840dca93bd3e1e5b8afe/modules/visxBidAdapter.js#L115
