### ISSUE TITLE
Need advice for Bidder Service API availability during review

### ISSUE THREAD

**Issue by czarpino** [prebid/Prebid.js#9712]
## Type of issue
Question

## Description

This is related to https://github.com/prebid/Prebid.js/issues/9688. Our Bidder Service is originally IP restricted. Is it possible to do the review on a certain IP (we can allow on this particular IP) or does it make more sense to make the Bidder Service API publicly available for the duration of review. Sorry to ask far in advance but this helps us prepare. Thank you.

**Comment by patmmccann** [comment]
Can you make it honor a certain IP in an x-forwarded-for header that can be set with curl, or perhaps a certain user agent token?

**Comment by czarpino** [comment]
@patmmccann Thank you very much for the quick confirmation! We will try to prepare accordingly with your advice.

**Comment by czarpino** [comment]
Hi @patmmccann. Thanks for not closing this conversation yet. It seems using the X-Forwarded-For header might not be viable. We are considering maybe a different header but another idea is whether it would be acceptable to prepare a mock server outside Japan (maybe in US) and use that for BidAdapter testing? 

Another concern is whether we need to meet the timeout settings for a bid response on the hello_world.html sample for review. I.e. 

```
var FAILSAFE_TIMEOUT = 3300;
var PREBID_TIMEOUT = 1000;
```

Thank you very much for your time.

**Comment by czarpino** [comment]
Hello, is anyone able advice about this? 👇 

> Hi @patmmccann. Thanks for not closing this conversation yet. It seems using the X-Forwarded-For header might not be viable. We are considering maybe a different header but another idea is whether it would be acceptable to prepare a mock server outside Japan (maybe in US) and use that for BidAdapter testing?
> 
> Another concern is whether we need to meet the timeout settings for a bid response on the hello_world.html sample for review. I.e.
> 
> ```
> var FAILSAFE_TIMEOUT = 3300;
> var PREBID_TIMEOUT = 1000;
> ```
> 
> Thank you very much for your time.

**Comment by patmmccann** [comment]
No you do not need to meet the timeout settings on hello world. Why is your bidder not able to understand X-Forwarded-For?
