### ISSUE TITLE
Update Unit Test Suite

### ISSUE THREAD

**Issue by spotxslagle** [prebid/Prebid.js#9715]
## Type of issue
Maintenance 

## Description
The unit test suite is lacking basic features like fdescribe or xit that would be useful for development. Update the appropriate packages so that these features are supported.

**Comment by dgirardi** [comment]
I do not recognize those; from a quick search they seem to be Jasmine features whose mocha equivalents are `it.skip` and `describe.skip`. Do those work for you? Btw, those features look like very obvious code smell enablers, I'm positive there's a better way to do whatever you need them for. I suggest

`gulp serve-and-test --file [spec_file]`

or we can think about passing more filters to the test runners if a single file is still too large.

**Comment by spotxslagle** [comment]
Interesting. Yeah, .skip and .only will work. Every test suite I've used must have been using Jasmine, because I hadn't realized that was mocha/jasmine difference. I've only ever seen the fdescribe/xit calls. It's the feature I want, not the syntax, so your suggestion is enough I tend to iterate a lot while writing/fixing unit tests, so being unable to isolate one or two tests has been frustrating. I wish I'd realized I just needed to take a closer look at the docs.

Thanks for your help!

**Comment by dgirardi** [comment]
@spotxslagle be aware that with https://github.com/prebid/Prebid.js/pull/9693 you'll still need to pass a file - which I think makes the feature as a whole not that useful. What happened is that someone forgot to remove their `.only`, the reviewers didn't notice, and the pipeline started skipping all tests without telling anyone. 

This is why I say it's a code smell; IMO the correct way to do that is to tell your test runner, not your test code, which subset of tests to run for fast iteration. So far `--file` has been enough for me.
