### ISSUE TITLE
Stop generating "NO_BID" bids for rejected bids

### ISSUE THREAD

**Issue by ChrisHuie** [prebid/Prebid.js#9722]
In reference to different way Prebid rejected bids. That main issue was addressed here https://github.com/prebid/Prebid.js/issues/8956. This is the final bullet point that needed to be done in a major version. Since `auction.bidsReceived` only contains valid bids we should stop generating NO_BID for rejected bids.

**Comment by patmmccann** [comment]
Adding @robertrmartinez as assignee so Rubicon analytics can fix tests to clear the way for this PR

**Comment by robertrmartinez** [comment]
Rubicon Analytics has been removed from Prebid 8 branch as it is replaced by the Magnite Analytics Adapter.

Here is the PR in magnite analytics prebid-8 branch to not rely on this 0 cpm bid response stuff! https://github.com/prebid/Prebid.js/pull/9933
