### ISSUE TITLE
Don't allow NPM to access private methods

### ISSUE THREAD

**Issue by ChrisHuie** [prebid/Prebid.js#9723]
Using Prebid as a dependency allows access to private methods such as `gdprDataHandler` in this case https://github.com/prebid/Prebid.js/issues/9333#issuecomment-1349287552. Proposal to no longer allow this behavior in Prebid 8. Still reviewing the bandwidth that would be needed for this issue.

**Comment by patmmccann** [comment]
perhaps cut for time ? tbd, to discuss with pubs?

**Comment by patmmccann** [comment]
@JulieLorin @khatibda @muuki88 do you have projects that import prebid as an npm? can you provide any feedback here?

**Comment by muuki88** [comment]
We use Prebid as an NPM dependency and only use the `processQueue()` ( or something like that ) to init Prebid.

All other access happens through public APIs.

**Comment by olafbuitelaar** [comment]
we're also using the `registerBidder`, in fact it would be nice it was a public method, like; `pbjs.registerBidder` . We also use other internal functions like; `filters` from `prebid.js/src/targeting` or `createBid` from `prebid.js/src/bidfactory`
