### ISSUE TITLE
Concerns with multiple ids coming from one id submodule response

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9730]
## Type of issue
feature request

## Description

conflicts handled alphabetically - we need to make, as an example, uid2 conflicts default to the uid2 module

unexpected behavior might happen - we should make extra returns (eg liveintent returning bidswitch and uid2 id, or 33across id returning rubicon id) as must be config opt in -- is this breaking? [update, it is not breaking]

## Requirements:

modules that "own" an id should win in case of conflict, eg uid2 module should beat liveintent on the uid2. Modules that don't "own" an id should declare as such and always lose in case of conflict

docs / rules commit that extra ids must all be opt in

**Comment by 3link** [comment]
@patmmccann  Providing a way to express priorities in case of collisions will make reasoning about the final result a lot easier. I think it is the right step. Having an opt-in configuration for extra returns seems like a good idea too. LiveIntent's module follows that approach already via the module specific configuration - by default, only a single id is returned. Lifting this to a general concept in Prebid and thus unifying handling of multiple ids is a good thing. These changes would be breaking, but we talked to our customers and it should not be an issue. Also, we will adjust LiveIntent's userId module as part of this effort when required.

A couple of thoughts/questions that might help to think about a solution:
- In the case of two providers for the same id type: How would the mechanism for determining who is the primary provider for that type look like?
- In case of modules returning multiple ids: When going with the opt-in solution for multiple identifiers, will it be required to define what id is exposed by default? Will additional ids be enabled one by one or will it be a flag enabling all of them?

**Comment by patmmccann** [comment]
[https://docs.google.com/document/d/1oOe8cA8NsT4JmEFs095faJpe8QxktfvGGnF9uBsKqzA/edit?usp=sharing](https://docs.google.com/document/d/1oOe8cA8NsT4JmEFs095faJpe8QxktfvGGnF9uBsKqzA/edit?usp=sharing&authuser=1)

Proposal on potential config; proposer also likes the idea of modules can declare which id's they do not 'own'

**Comment by patmmccann** [comment]
solved with #9896
