### ISSUE TITLE
sizeMapping and DFP

### ISSUE THREAD

**Issue by SallyMennen** [prebid/Prebid.js#975]
I've setup Prebid with sizeMapping as per the example on the website. However, non-Prebid DFP line items (like AdX) are ignoring minWidth (so I see 320x50 on desktop and 728x90 on mobile). Is this the expected behaviour? If so do I have to use googletag.sizeMapping() too in order to keep DFP in check?

`var adUnits = [{code: 'banner-h1', 
sizes: [728, 90],
sizeMapping: [  
                             {
                                 minWidth : 800,
                                 sizes : [[728,90]]
                             },
                             {
                                 minWidth : 550,
                                 sizes : [[468,60]]
                             },
                             {
                                 minWidth : 0,
                                 sizes : [320,50]
                             }
             ],
bids: [...]},`

**Comment by mkendall07** [comment]
@SallyMennen 
That's correct, you need to use the google.sizeMapping() feature as well if you want them to honor the sizes.
