### ISSUE TITLE
ORTB converter strips video from multiformat units

### ISSUE THREAD

**Issue by mmoschovas** [prebid/Prebid.js#9788]
## Type of issue

Bug

## Description

We noticed after testing the new openx ortb adapter that an error was being thrown during the buildImp stage. It seems that the openx adapter is passing the bidRequest, context to buildImp which only responds with banner data, even though banner and video were both defined. The OpenX adapter checks the bidRequest for video (specifically outstream) and attempts to set the placement value on the imp; however, since video was not being returned, it throws an error and an empty imp is sent to their endpoint.

ERROR:
<img width="1182" alt="Screen Shot 2023-04-10 at 12 21 54 PM" src="https://user-images.githubusercontent.com/63253416/230951800-74e7b682-9945-489e-9f82-7681a4b5fa3a.png">

BIDREQUEST TO BUILT IMP COMPARISON:
<img width="839" alt="Screen Shot 2023-04-10 at 12 44 16 PM" src="https://user-images.githubusercontent.com/63253416/230951972-0d6929c2-bb5d-48b1-a37a-a936ff94843b.png">

REQUEST SENT
<img width="546" alt="Screen Shot 2023-04-10 at 12 23 01 PM" src="https://user-images.githubusercontent.com/63253416/230952418-3d6f2e68-72ac-4791-9a09-38b019c88b24.png">

## Steps to reproduce

1. Go to this site: https://damndelicious.net/2013/12/07/olive-garden-zuppa-toscana-copycat-recipe on desktop
2. If the adunit does not have video mediatype on load, scroll the Adthrive_Content_1_desktop into view and wait for a refresh
3. When both mediatypes are defined, you should see the corresponding error mentioned above

## Test page

https://damndelicious.net/2013/12/07/olive-garden-zuppa-toscana-copycat-recipe on desktop

### Expected results
Request is built/sent successfully

**Comment by dgirardi** [comment]
Fix is in https://github.com/prebid/Prebid.js/pull/9790. The bug is that since [openx creates separate requests for banner and video](https://github.com/prebid/Prebid.js/blob/f270145ac91121e76171a560b53d808156728604/modules/openxOrtbBidAdapter.js#L169-L177), it's not true that `imp.video` is defined if `bidRequest.context.outstream` exists - there's a banner-only imp where video got ignored, therefore the exception.
