### ISSUE TITLE
bidsBackHandler doesn't fire correctly

### ISSUE THREAD

**Issue by adamnewsnow** [prebid/Prebid.js#98]
I have a test setup with prebid.org using a subset of the available adapters.

I'm finding that bidsBackHandler doesn't ever fire. Stepping into the code, it seems to me that checkAllBidsResponseReceived iterates over bidResponseReceivedCount, which contains keys for things such as 'rubicon', which isn't an adapter I'm using. Consequently, 'available' is always false. If I disable the adapters I'm not using, I get the opposite problem: if I have multiple bid requests active for a given adapter, the function returns true when at least one is ready but not all of them.

**Comment by mkendall07** [comment]
Thanks for the bug report @adamnewsnow . It looks like this was broken when we renamed Casale adapter. We'll fix it ASAP.
