### ISSUE TITLE
setBidderConfig not "overriding" setConfig "Global" ortb2

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#9801]
## Type of issue
potential bug

## Description
it seems that setting the setBidderConfig ortb2 variables are not overwriting the setConfig ortb2 "global" config,  I think the video module might be doing something funky in the background to stop it, not sure

## Steps to reproduce
set: ortb2
![NewVideoModuleNeuwoGolf1_html_—_Prebid_Publishers__Workspace_](https://user-images.githubusercontent.com/8503167/231735068-92fdd028-3eac-49b7-b691-ac129ec13df9.png)

setConfig:
ortb2: {
                        at: 1,
                        allimps: 1,
                        bcat: ['IAB23'],
                        fd: 0,
                        cur: ['GBP'],
                        site: {
                          ext: {
                            inventorypartnerdomain: 'adysis.com'
                          },
                          cat: ['IAB17'],
                          sectioncat: ['IAB17-15'],
                          // pagecat: ["IAB2-2"],
                          content: {
                            // id: 'some_id',
                            name: "example",
                            episode: '1',
                            title: 'some title',
                            series: 'some series',
                            season: 's1',
                            artist: 'John Doe',
                            genre: 'some genre',
                            isrc: 'CC-XXX-YY-NNNNN',
                            // url: 'http://foo_url.de',
                            cat: ['IAB17-15', 'IAB17'],
                            context: '7',
                            keywords: 'sports,golf',
                            live: '0'
                          },
                          keywords: 'sports, golf',
                          privacypolicy: 1,
                          mobile: 1,
                          publisher: {
                            // domain: 'adysis.com',
                            name: 'adysis',
                            cat: 'IAB17'
                          }
                        },
                        user: {
                          yob: 1985,
                          gender: "m",
                          keywords: "sports,golf",
	                        data: [{
	                          name: "dataprovider.com",
	                        ext: { segtax: 4 },
                            segment: [
		                          { id: "1" }
                            ]
	                        }],
	                        ext: {
                            data: {
                              registered: true,
                              interests: ["sports"]
	                          }
                          }
                        }
                      },

setbidderconfig: trying to reduce the amount of variables sent to IX bidder

adyjs.setBidderConfig({
        bidders: ['ix'],
        config: {
            ortb2: {
              at: 1,
              allimps: 1,
              bcat: ['IAB23'],
              fd: 0,
              cur: ['GBP'],
              site: {
                ext: {
                  inventorypartnerdomain: 'adysis.com'
                },
                cat: ['IAB17'],
                sectioncat: ['IAB17-15'],
                // pagecat: ["IAB2-2"],
                content: {
                  // id: 'some_id',
                  // name: "example",
                  // episode: '1',
                  // title: 'some title',
                  // series: 'some series',
                  // season: 's1',
                  // artist: 'John Doe',
                  // genre: 'some genre',
                  // isrc: 'CC-XXX-YY-NNNNN',
                  // url: 'http://foo_url.de',
                  cat: ['IAB17-15', 'IAB17'],
                  context: '7',
                  keywords: 'sports,golf',
                  live: '0'
                },
                keywords: 'sports, golf',
                privacypolicy: 1,
                mobile: 1,
                publisher: {
                  // domain: 'adysis.com',
                  name: 'adysis',
                  cat: 'IAB17'
                }
              },
              user: {
                yob: 1985,
                gender: "m",
                keywords: "sports,golf",
                data: [{
                  name: "dataprovider.com",
                ext: { segtax: 4 },
                  segment: [
                    { id: "1" }
                  ]
                }],
                ext: {
                  data: {
                    registered: true,
                    interests: ["sports"]
                  }
                }
              }
            },
          }
      });

request still sends the setConfig "global" ortb2 variables:
![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_NewVideoModuleNeuwoGolf1_html](https://user-images.githubusercontent.com/8503167/231735804-ff61fe8f-ec75-4277-9d3b-b95c78bae49c.png)

## Test page
@ChrisHuie has the test page and @karimMourra has it I think

### Expected results
setBidderConfig variables to be sent to IX, over riding setConfig variables

### Actual results
setConfig variables being sent for IX

## Platform details
P7.44.0, mac, chrome

## Other information
might be related to something similar as #9710 which is the floors stopping auction ID change, but no clue if related. at a complete guess the "video module" is over riding in back ground or something, maybe

**Comment by spormeon** [comment]
bidderB as in the docs here (bottom of page), https://docs.prebid.org/dev-docs/publisher-api-reference/setBidderConfig.html . Says "it will receive this override definition rather than whatever else might have been defined globally."  thats reads as "take these variables, instead of the setConfig ones" to me.  Use case is IX throws error when the ortb2 variables are too long in effect, so want to "reduce" the amount sent:
![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_NewVideoModuleNeuwoGolf1_html](https://user-images.githubusercontent.com/8503167/231778088-bc4a7b52-6760-4213-bf94-ac6681517942.png)

**Comment by spormeon** [comment]
@dgirardi ok, thnaks, the onEvent method seems to work.  Not sure its the "simplest" way though, when the "video module" is ment to make things simpler/ easier for people?
![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_NewVideoModuleNeuwoGolf1_html](https://user-images.githubusercontent.com/8503167/231879823-8af169b5-604a-47d9-8859-0cb19ce55ab5.png)

**Comment by spormeon** [comment]
Ah, hang on, it gives a"knock on" effect, that i'm using the neuwo mdule which decorates the ortb2 with "contant category" info, this onEvent method then also stops the neuwo mdule from decorating ortb2

**Comment by dgirardi** [comment]
This doesn't seem like a video issue to me, but I agree that it's not great. We can try to think of a nicer way - but I'm not clear on the use case; as far as I understand things like `cat` shouldn't depend on the bidder.

Another option is to switch your setup so that you only `setConfig` when the setting is truly global and use `setBidderConfig` to add (rather than subtract). For example,

```
setConfig({
   ortb2: {
      content: {
         cat: ['IAB17']
      }
   }
});

setBidderConfig({
    bidders: [
       // whoever else is supposed to get 'IAB17-5'
    ],
    config: {
        ortb2: {
            content: {
                 cat: ['IAB17-5']                
            }
        }
    }
})
```

> onEvent method then also stops the neuwo mdule from decorating ortb2

Thats a good demonstration of why it's not trivial to provide a "replace" version, it's not that clear what is being replaced.

**Comment by spormeon** [comment]
can setBidderConfig take multiple values, as this dont work, its only decorates for the second one with the "multiple bidders", the IX one dont send the values/ decorate:
`
adyjs.setBidderConfig({
          bidders: ['ix'],
          config: {
            ortb2: {
              at: 1,
              allimps: 1,
              bcat: ['IAB23'],
              fd: 0,
              cur: ['GBP'],
              site: {
                ext: {
                  inventorypartnerdomain: 'adysis.com'
                },
                cat: ['IAB17'],
                sectioncat: ['IAB17-15'],
                // pagecat: ["IAB2-2"],
                content: {
                  // id: 'some_id',
                  // name: "example",
                  // episode: '1',
                  // title: 'some title',
                  // series: 'some series',
                  // season: 's1',
                  // artist: 'John Doe',
                  // genre: 'some genre',
                  // isrc: 'CC-XXX-YY-NNNNN',
                  // url: 'http://foo_url.de',
                  cat: ['IAB17-15', 'IAB17'],
                  context: '7',
                  keywords: 'sports,golf',
                  live: '0'
                },
                keywords: 'sports, golf',
                privacypolicy: 1,
                mobile: 1,
                publisher: {
                  // domain: 'adysis.com',
                  name: 'adysis',
                  cat: 'IAB17'
                }
              },
              user: {
                yob: 1985,
                gender: "m",
                keywords: "sports,golf",
                data: [{
                  name: "dataprovider.com",
                  ext: {
                    segtax: 4
                  },
                  segment: [{
                    id: "1"
                  }]
                }],
                ext: {
                  data: {
                    registered: true,
                    interests: ["sports"]
                  }
                }
              }
            }
          },
          bidders: ['smaato','amx','sharethrough','pubmatic','pwbid','adform','rhythmone','minutemedia','smartadserver','sovrn','33across','openx','gumgum'],
          config: {
            ortb2: {
            at: 1,
            allimps: 1,
            bcat: ['IAB23'],
            fd: 0,
            cur: ['GBP'],
            site: {
              ext: {
                inventorypartnerdomain: 'adysis.com'
              },
              cat: ['IAB17'],
              sectioncat: ['IAB17-15'],
              // pagecat: ["IAB2-2"],
              content: {
                // id: 'some_id',
                name: "example",
                episode: '1',
                title: 'some title',
                series: 'some series',
                season: 's1',
                artist: 'John Doe',
                genre: 'some genre',
                isrc: 'CC-XXX-YY-NNNNN',
                // url: 'http://foo_url.de',
                cat: ['IAB17-15', 'IAB17'],
                context: '7',
                keywords: 'sports,golf',
                live: '0'
              },
              keywords: 'sports, golf',
              privacypolicy: 1,
              mobile: 1,
              publisher: {
                // domain: 'adysis.com',
                name: 'adysis',
                cat: 'IAB17'
              }
            },
            user: {
              yob: 1985,
              gender: "m",
              keywords: "sports,golf",
              data: [{
                name: "dataprovider.com",
                ext: {
                  segtax: 4
                },
                segment: [{
                  id: "1"
                }]
              }],
              ext: {
                data: {
                  registered: true,
                  interests: ["sports"]
                }
              }
            }
           }
          }
      });`

**Comment by spormeon** [comment]
ok, I have this part sorted out now, with a load of "wangling" but I got a follow on,  IX wont take the ortb2.imp which is set on the adunit,  I have it set on the adunit and that seems to "contribute" towards the IX error 8 of too much FPD being sent.  I tried adding ortb2.imp to the setBidderConfig for "all bidders except IX" but that dont work.  Is there a way to add ortb2.imp to setBidderConfig?  or is there another way to "limit" which bidders get ortb2.imp varaibles?

**Comment by dgirardi** [comment]
I am not sure I'm following (I don't know what it means to have "too much FPD" for just one bidder, that sounds odd to me, is IX returning errors?), but we did recently add the option to use `adUnits[].bids[].ortb2Imp` to set bidder-specific imp-level FPD:

https://docs.prebid.org/dev-docs/adunit-reference.html#adunitbids

e.g. 

```
addAdUnits({
   // ...
   bids: [
       {
           bidder: 'ix',
           ortb2Imp: {
                // ...
           }        
       }
   ]
})
```

**Comment by spormeon** [comment]
ye, they return an error 8, what ever that is

![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_NewVideoModuleNeuwoGolf1_html](https://user-images.githubusercontent.com/8503167/232119842-50e48742-a578-42c7-8028-a3ec6889351f.png)

**Comment by dgirardi** [comment]
My reaction is that validation is clearly overzealous, and I think the IX devs might agree since it appears that it's no longer an error condition in master - I think it will go away if you update the IX adapter, although I can't find the version where that check was removed (@ix-peiyuan ?)

**Comment by dgirardi** [comment]
actually it was very recent - that error check was [just removed](#9793 ).

**Comment by spormeon** [comment]
im on V7.44.0 alreadybids: 
[
       {
           bidder: 'ix',
           ortb2Imp: {
                // ...
           }        
       }
   ]


dont take an array of bidders, as follows, as notjing gets sent?
bids: [
          { 
            bidder: ['smaato','amx','sharethrough','pubmatic','pwbid','adform','rhythmone','minutemedia','smaradserver','sovrn','33across','openx','gumgum'],
            ortb2Imp: {
              ext: {
                gpid: adysisSlot,
                data: {
                  pbadslot: adysisSlot,
                  adserver: {
                    name: "gam",
                    adslot: adysisSlot
                  }
                }
              }
            }
          }
        ],
        mediaTypes: {

**Comment by spormeon** [comment]
ok, i'll move to v7.45.0 to get rid of the darn thing, cheers
