### ISSUE TITLE
BidderFactory test fail

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9805]
## Type of issue
Bug

## Description
https://github.com/prebid/Prebid.js/blob/78c1dd30a8e646d3d1e49a890578b885960ab887/test/spec/unit/core/bidderFactory_spec.js#L1013 indicates bids with no size when an ad unit only has a single size should succeed, but all circleci runs giving output `"ERROR LOG: '%cPrebid%csampleBidder1', 'display: inline-block; color: #fff; background: #3b88c3; padding: 1px 4px; border-radius: 3px;', 'display: inline-block; color: #fff; background: #aaa; padding: 1px 4px; border-radius: 3px;', 'ERROR:', 'Invalid bid from sampleBidder1. Ignoring bid: Banner bids require a width and height'"
`

## Steps to reproduce
Any recent circleci run eg https://app.circleci.com/pipelines/github/prebid/Prebid.js/15411/workflows/32fc53b7-1f9b-4808-a98b-e88c6e54d4d3/jobs/28127

## Test page
[
](https://app.circleci.com/pipelines/github/prebid/Prebid.js/15411/workflows/32fc53b7-1f9b-4808-a98b-e88c6e54d4d3/jobs/28127)
### Expected results
Cicleci doesnt have an error

### Actual results
Circleci output has `ERROR LOG: '%cPrebid%csampleBidder1', 'display: inline-block; color: #fff; background: #3b88c3; padding: 1px 4px; border-radius: 3px;', 'display: inline-block; color: #fff; background: #aaa; padding: 1px 4px; border-radius: 3px;', 'ERROR:', 'Invalid bid from sampleBidder1. Ignoring bid: Banner bids require a width and height'`

**Comment by dgirardi** [comment]
objections: 

 - the test is not failing.
 - that error message is not coming from the test you quoted in the OP. In fact, it's not even coming from that spec file.

Again, it's very normal for tests to generate errors, and I do not think it's reasonable or useful to verify that every line in the output doesn't somehow means that a test is incorrect.

**Comment by patmmccann** [comment]
There are only five examples of tests causing errors of this nature in the circleci output. there are many errors generated intentionally in the test suite that don't cause this kind of output in the file. What's special about this error?
