### ISSUE TITLE
Various adapters unit tests fail

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9806]
## Type of issue
Bug

## Description
 unit tests generate an error for the following adapters:

[ ] smartyads
[ ] Krushmedia
[ ] gothamads
[ ] e_volution

## Steps to reproduce
Examine https://app.circleci.com/pipelines/github/prebid/Prebid.js/15411/workflows/32fc53b7-1f9b-4808-a98b-e88c6e54d4d3/jobs/28127

### Expected results
No errors logged from the tests

### Actual results
Error: `TypeError: undefined is not an object (evaluating 'bidderRequest.refererInfo')
buildRequests@http://localhost:9876/absolute/tmp/_karma_webpack_918587/commons.js?35434d6d8ac99fb1d4ae583e0d5323ee717e1ccf:139787:39
http://localhost:9876/absolute/tmp/_karma_webpack_918587/commons.js?35434d6d8ac99fb1d4ae583e0d5323ee717e1ccf:386923:64
create@http://localhost:9876/base/node_modules/mocha/mocha.js?30c344542158d251b5da4fdc29b9813ffef496d9:18559:25
http://localhost:9876/absolute/tmp/_karma_webpack_918587/commons.js?35434d6d8ac99fb1d4ae583e0d5323ee717e1ccf:386922:11
create@http://localhost:9876/base/node_modules/mocha/mocha.js?30c344542158d251b5da4fdc29b9813ffef496d9:18559:25
./test/spec/modules/smartyadsBidAdapter_spec.js@http://localhost:9876/absolute/tmp/_karma_webpack_918587/commons.js?35434d6d8ac99fb1d4ae583e0d5323ee717e1ccf:386902:9`

`TypeError: Type error
[native code]
buildRequests@http://localhost:9876/absolute/tmp/_karma_webpack_918587/commons.js?35434d6d8ac99fb1d4ae583e0d5323ee717e1ccf:87788:25
http://localhost:9876/absolute/tmp/_karma_webpack_918587/commons.js?35434d6d8ac99fb1d4ae583e0d5323ee717e1ccf:295122:65
create@http://localhost:9876/base/node_modules/mocha/mocha.js?30c344542158d251b5da4fdc29b9813ffef496d9:18559:25
http://localhost:9876/absolute/tmp/_karma_webpack_918587/commons.js?35434d6d8ac99fb1d4ae583e0d5323ee717e1ccf:295121:11
create@http://localhost:9876/base/node_modules/mocha/mocha.js?30c344542158d251b5da4fdc29b9813ffef496d9:18559:25
./test/spec/modules/krushmediaBidAdapter_spec.js@http://localhost:9876/absolute/tmp/_karma_webpack_918587/commons.js?35434d6d8ac99fb1d4ae583e0d5323ee717e1ccf:295095:9`

etc

**Comment by dgirardi** [comment]
many tests produce errors, for example every test on an error scenario. It's possible that some of them are passing when they shouldn't but the output log is not any indication that's the case.

**Comment by patmmccann** [comment]
not in these four cases I am reasonably confident

**Comment by patmmccann** [comment]
@dgirardi as example, this one https://github.com/prebid/Prebid.js/blob/d3b108f0d35cc44cd27a509ace2168fe6075efef/test/spec/modules/e_volutionBidAdapter_spec.js#L85 is the only reference to page in the spec file and there is no error condition test

**Comment by patmmccann** [comment]
Closing as not impactful
