### ISSUE TITLE
Discrepancies with Appnexus (>10%) and Sonobi (>20%)

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#985]
I have >20% revenue discrepancies with Sonobi and >10% revenue discrepancies with Appnexus (brealtime and oftmedia aliases).

AOL, Conversant, Sovrn and Sekindo show no major discrepancies (less than 2.3%). 

I am currently running version 0.18.0 and the discrepancies persist.

Sonobi and bRealtime were unable to help me.

For now I have applied  a bidCpmAdjustment of 22.5% for Sonobi and 11% for bRealtime.
Despite this adjustment, Brealtime still shows a 14% impression discrepancy and Sonobi shows a 5% impression discrepancy and still a 10% revenue discrepancy. (I will need to increase the Sonobi bidCpmAdjustment to 33%)

This test page shows my implementation:
http://www.flixxy.com/prebid.htm 
And here is a sample live page:
http://www.flixxy.com/the-incredible-flyboard-air.htm

**Comment by protonate** [comment]
Changes made with #989 and #990 address some issues that may have caused an auction to end early or a "bids back" callback to not fire. Prebid 0.19.0 is released now and can be tested to see if discrepancies are reduced.

**Comment by headerbidding** [comment]
Great! Thank you for such a quick response!
I will test it as soon as 0.19.0 is available on the "easy download" page ( http://prebid.org/download.html )

**Comment by headerbidding** [comment]
The discrepancies with Appnexus and Sonobi persist, even with Version 0-19-0, and a bidCpmAdjustment of 0.9 !      Example: 
BRT (Appnexus) Report:  2,249  	        $5.06	$2.25
DFP Report:                     2622	        $5.20 	$1.98

**Comment by dmitriyshashkin** [comment]
@headerbidding do you have discrepancy with Sonobi only in terms of revenue or impression do not match too? We have major discrepancy with them, but strangely enough impressions differ only by 2% while revenue is off almost by 30%.

**Comment by headerbidding** [comment]
We see discrepancies both in impressions and revenue.

**Comment by headerbidding** [comment]
Changing the timeout from 500ms to 1200ms fixed the discrepancy with Sonobi (both revenue and impressions) on a test page.
Why would that be?
