### ISSUE TITLE
MergeConfig fix breaks dspx bid adapter

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#9876]
## Type of issue

bug

## Description

The `dspx` bid adapter is not working in prebid 7.46.0 . I assume the offending line is

https://github.com/prebid/Prebid.js/blob/1ac35727e2220c4afd36807d73e6ab6f55a7ea4c/modules/dspxBidAdapter.js#L186

because the error we see is this

![image](https://user-images.githubusercontent.com/647727/235293825-c509adb2-f837-4c27-8665-3bd3a6f3c3d0.png)

which I tracked down to this line

https://github.com/prebid/Prebid.js/blob/4f45f15bbd2e2319e93c9dca501256cf10a04449/src/adapters/bidderFactory.js#L156

and there were no changes on adapter or server response. The only this is the access to the prebid config.

## Steps to reproduce

1. use prebid `7.46.0` 
2. use `dspx` bid adapter

## Test page

Welp.. we fixed it in production by rolling back.

### Expected results

dspx works

## Platform details

- prebid `7.46.0`

## Other information

- https://github.com/prebid/Prebid.js/pull/9704

**Comment by patmmccann** [comment]
Bad idea to pull ttl for a bid out of user config.

**Comment by muuki88** [comment]
Yeah. It doesn't make any sense. I'll open a PR next week to set this to a static value.

Anything recommend for bidders that don't provide those server side?

**Comment by patmmccann** [comment]
300

**Comment by patmmccann** [comment]
300 is pretty common I'd say, but maybe set it to 60 or something and let them raise it?

**Comment by muuki88** [comment]
We have a good connection to them and make them aware of the issue. 👍

**Comment by dgirardi** [comment]
That pattern is wrong in two different ways - it should be `bidderTimeout` and not `_bidderTimeout`, but also, bidder timeout has nothing to do with TTL. 
Of course, it was copy-pasted into a bunch of other adapters, it's not limited to dspx. @patmmccann - should we fix them all to some arbitrary value like 300?

**Comment by patmmccann** [comment]
Yes, let's choose 60 and let them increase if they desire.

**Comment by muuki88** [comment]
Sounds good to me ❤️👍
