### ISSUE TITLE
Prebid 8 - Convert Mass module to generic deal rendering module

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9888]
https://github.com/prebid/Prebid.js/blob/master/modules/mass.js has lost its maintaining company but still has useful functionality; applying a renderer when the deal code meets a regex pattern. We want to strip all the branding and require the regex to be configurable instead of having a default

**Comment by dgirardi** [comment]
This can work as an  alternative:

```

pbjs.onEvent('bidResponse', (bid) => {
    if (bid.dealId /* or any other condition */) {
        bid.renderer = {
            renderNow: true,
            render(bid, doc) {
                // do your own rendering
                doc.body.innerHTML = bid.ad;
            }
        }
    }
})

```

**Comment by patmmccann** [comment]
opened as https://github.com/prebid/prebid.github.io/issues/4535
