### ISSUE TITLE
Question about the best way to measure lift brought about by a user id module

### ISSUE THREAD

**Issue by deepthivenkat** [prebid/Prebid.js#9935]
## Type of issue
Question

## Description
The problem LiveIntent is running into is: Right now we populate uid2 tokens, ssp identifiers. SSPs do A/B testing to determine the value of / lift brought about by specific identifier as opposed to measuring the value brought about by user id modules as a whole. This gets particularly tricky if we start populating identifiers from our competitors for the solution (like yahoo connect ID) - though LI is populating the identifier, the lift in CPM could be attributed to them

## Steps to reproduce
For context, here is how the user->ext->eids array will look like from LI user id module
[
		{
      		source: 'liveintent.com',
      		uids: [
      			{
      				id: 'some-random-id-value', 
      				atype: 3
      			}
			]
    	},
    	{
	      source: 'bidswitch.net',
	      uids: [
	      	{
	      		id: 'some-random-bidswitch-value', 
	      		atype: 3, 
	      		ext: {provider: 'liveintent.com'}
      		}
	      ]
	    },
	    {
	      source: 'uidapi.com',
	      uids: [
	      	{
	      		id: 'some-random-uid2-value', 
	      		atype: 3, 
	      		ext: {provider: 'liveintent.com'}
      		}
  		  ]
	    },
           {
	      source: 'yahooConnectId',
	      uids: [
	      	{
	      		id: 'some-random-yahoo-id-value', 
	      		atype: 3, 
	      		ext: {provider: 'liveintent.com'}
      		}
  		  ]
	    },
		{
	      source: 'media.net',
	      uids: [
	      	{
	      		id: 'some-random-medianet-value', 
	      		atype: 3, 
	      		ext: {provider: 'liveintent.com'}
      		}
  		  ]
	    }
	]

## Test page
snopes.com

## Platform details
Prebid.js version v7.45.0+

## Other information
There are several ways for SSPs to measure this. Is there a preference in terms of implementation effort and what is considered fair for everyone:

1) We could randomly pick about 5% of requests we are able to resolve for and intentionally suppress and add that info to bidstream 
with a flag like {'supressed': true}
to communicate to SSPs that those are suppressed requests and to calculate difference in average cpms between the following two buckets:
requests enriched with identifiers
vs 
requests intentionally suppressed. 

**Pros**
This eliminates taking credit for bad traffic since bad traffic does not fall into either buckets
The distribution of traffic amongst different browsers should be similar across both the buckets
The distribution of other identifiers/ deal ids a publisher is working with is roughly similar across two buckets since the requests are chosen randomly 

**Cons**
Getting SSPs to adopt this as an additional implementation for reporting purposes

2) We could ask the ssp bidder adapters to use the provider field to determine who populated the identifiers to attribute accordingly - this is assuming that the provider made available within the source will stay in SSP logs during attribution.

We have an analytics adapter that can do sampling but it is too much of an ask to require pubs to enable it. So we will have to rely on SSP’s analytics adapter. I would love to understand a lil bit more about how events from analytics adapter can help here
Other suggestions / approaches welcome!

**Comment by dgirardi** [comment]
I am not following how user ID modules come into the picture if the A/B testing is done by SSPs; can't an SSP bucket the incoming EIDs to compare their performance?

If I misunderstood and the test is done by a publisher, I think the same technique can be implemented using events - but it would be quite cumbersome and we may want to make it a feature. The idea is to do something like

```
pbjs.onEvent('bidRequested', (bidderRequest) => {
   bidderRequest.bids.forEach(bidRequest => {
         bidRequest.userIdAsEids = bidRequest.userIdAsEids.filter(/* remove some EIDS some of the time*/)
   })
})
```

the issue is that not every adapter looks at EIDs and the same should be applied to the older `userId` objects.

**Comment by deepthivenkat** [comment]
You did not misunderstand. The A/B test is being done by the SSPs. But typically it is done for a specific identifier - for eg: what is the impact of passing vs not passing yahoo connected id in the bid requests for a specific domain. I like the idea of bucketing EIDs from a module based on the provider field. We work with the SSPs to ensure that we populate identifiers relevant to them at a path their bidder adapter picks them from.

If there is any other way through which we can make it easier for them to measure this, I would love to learn more. But this will be our recommendation for now. Thanks!
