### ISSUE TITLE
AppNexus (appnexus or appnexusAst adaptors) requests calls not passing IP information.

### ISSUE THREAD

**Issue by vishalgarale** [prebid/Prebid.js#995]
Appnexus is not able to identify geography of the impressions through Prebid script. 

We raised a ticket to AppNexus regarding no fill, they reverted back saying without IP information AppNexus is not able to fill the impressions and they shared the reports of IP missing data.

We are using appnexus and appnexusAst adaptors in prebid.js for both post bid and prebid tags. However, we don't face issues with other platforms. Is this issue known or witnessed by anyone else?

![country_issue](https://cloud.githubusercontent.com/assets/9536053/23054484/2d120564-f506-11e6-81f5-bfb1c4fbb808.png)

**Comment by mkendall07** [comment]
The IP should be contained in the request, unless it's non-human traffic. Can you offer any other details that point to no IP being sent?

**Comment by magirtopcu** [comment]
Should publisher pass ip information as param in prebid request ?
