### ISSUE TITLE
Remove / Unset floors on following auctions is not respected

### ISSUE THREAD

**Issue by natanavra** [prebid/Prebid.js#9956]
## EDIT 1
Seems that setting floor values works, e.g. `pbjs.setConfig({ floors: { data: { values: { '*': 0.01 } } } })`
So the sentence 
> Every call to setConfig overwrites supplied values at the top level 

from the `setConfig` [docs](https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html) is not actually true in this case?

----

## Type of issue
bug

## Description
removing / unsetting floors with `pbjs.setConfig({ floors: {} })` has no effect, "old" floors from previous configuration are still used.

## Steps to reproduce
1. run an auction with a default price floors e.g. `pbjs.setConfig({ floors: { config: { default: 0.1, floorMin: 0.1 } } })`
2. after several seconds unset/remove floors `pbjs.setConfig({ floors: {} })`
3. run another auction, default floor is still enforced

## Test page
N/A

### Expected results
unsetting floors from config should stop floor enforcement on subsequent auctions

### Actual results
removing floors does nothing?

## Platform details
- prebid.js 7.39.0
- chrome 113

## Other information
N/A

**Comment by robertrmartinez** [comment]
This was intentionally done as to safeguard against an endpoint returning garbage objects or anything, always fall back to what was saved before.

The way to stop floors is as Demetrio says, turn off the module with `enabled = false`

But if this does not satisfy a legit use case we can alter.

**Comment by dgirardi** [comment]
Plan is to fix this - as in not persisting previous floor data when it's omitted or invalid - for version 8

**Comment by natanavra** [comment]
Let's say we don't want to disable it but want to lower the default and remove the `values`
e.g. `setConfig({ floors: { data: { default: 0.01 } } })` would that work?
Not sure if I tried that and it didn't work...?

At any rate, I guess it's worth adding a section to price floors module docs stating what happens if you want to discard or lower the default on the next auction.
