### ISSUE TITLE
Additional Params in PubMatic

### ISSUE THREAD

**Issue by mohsink4u** [prebid/Prebid.js#998]
## Type of issue

Allowing Publishers to send key value pairs into PubMatic

## Description

We would like to explore additional params from PubMatic. We want to pass categories into PubMatic which can then be used for targetting inside PubMatic. PubMatic has a param to achieve this: 
var kaddctr="key1=val1,val2val3|key2=val12";

## Steps to reproduce

Structure of PubMatic tag is like this: 
`<script type="text/javascript">
// Specify multiple slot names over here
var pm_optimize_adslots = ['site2_section2@300x250','site3_section3@300x250'];
// PubMatic platform specific publisher identifier
var pm_pub_id = 7777;
// pm_custom is an optional parameter. Pass the key-values applicable for the impression in it to
the ad server. anything inside "" will need to be encoded. key1 has multiple params separated by commas(**OR**) and pipes(**AND**)
**var kaddctr="key1=val1,val,val3|key2=val12";**
var pm_async_callback_fn= 'pm_async_callback'; // Optional callback function name
</script>
<script type="text/javascript" src="http://ads.pubmatic.com/AdServer/js/gshowad.js">
</script>
`

### Expected results
PubMatic will need to see this param:
**dctr**:key1=val,val2,val3|key2=val12
//kaddctr converts into dctr

### Actual results
Tag needs to fire like this: 
`<script type="text/javascript">
var pm_optimize_adslots = ['site2_section2@300x250','site3_section3@300x250'];
var pm_pub_id = 77777;
var kaddctr="key1%3Dval%2Cval2%2Cval3%7Ckey2%3Dval12";
// key values"key1=val,val2,val3|key2=val12" will need to be encoded before they are sent to PubMatic
//var pm_async_callback_fn= 'pm_async_callback'; // Optional callback function name
</script>
<script type="text/javascript" src="http://ads.pubmatic.com/AdServer/js/gshowad.js">
</script>`

**Comment by boolean4** [comment]
@mkendall07

**Comment by mkendall07** [comment]
We accpet PRs. Otherwise will add to the backlog to do at some point.
