### ISSUE TITLE
Proposal: Recode ajax.js to use fetch

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9980]
## Type of issue
Feature request

## Description

Utilization of the fetch api for bidders instead of XHR would provide bidder access to Sec-Browsing-Topics headers (provided consent, publisher opt in, etc)

See: https://developer.chrome.com/docs/privacy-sandbox/topics/#use-headers-to-access-and-observe-topics

Are there any disadvantages to transitioning from xhr to fetch? Are there any implications to plans to use a web worker to offload the requests off the main thread? 

## Other information
Related: #3058

**Comment by dgirardi** [comment]
From what I understand the header is filled in by the browser, using different values depending on the origin of the destination.

If that's true, it means that requests through Prebid Server will see different topics compared to requests coming directly from JS. What's our plan to deal with this - if we need to work around the concept (like we are doing now with iframes) then I don't see the value in also adding the header; if we don't work around it, and topics takes off, it will be an incentive to move off Prebid Server.
