### ISSUE TITLE
Various adapters: PlayerSize type and Format bug

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/Prebid.js#9988]
## Type of issue
Both a bug and potentially a docs issue

## Description
According to the docs, playerSize should be an array with width and height ( see https://docs.prebid.org/dev-docs/adunit-reference.html#video ).
When you do this Prebid itself will complain and turn it into an array of arrays

```
if (tarPlayerSizeLen === 2) {
  logInfo('Transforming video.playerSize from [640,480] to [[640,480]] so it\'s in the proper format.');
}
```

So far manageable, but you then have bid adapters that assume it should be an array with width and height, eg ShareThrough

```
let [w, h] = [640, 360];
if (videoRequest.playerSize && videoRequest.playerSize[0] && videoRequest.playerSize[1]) {
  [w, h] = videoRequest.playerSize;
}
```

Where we cant work around it anymore.

A quick ctrl+f through prebid shows that other adapters may be affected as well.

Quantcast does

```
if (video.playerSize) {
  video.w = video.playerSize[0];
  video.h = video.playerSize[1];
}
```

Mobfox and Logan do:

```
placement.wPlayer = mediaType[VIDEO].playerSize[0];
placement.hPlayer = mediaType[VIDEO].playerSize[1];
```

And you can probably find some other adapters with the same problem.

**Comment by patmmccann** [comment]
@ReinoutStevens right next to your linked code, I found this advice https://github.com/prebid/Prebid.js/blob/8e3c263c3374040e27fb96073ddd35d5f7b7c334/src/prebid.js#LL147C37-L147C37

Did you try that?

**Comment by ReinoutStevens** [comment]
I just fixed the one adapter that we use that is affected.
I can open a PR for that if you want, but dont know if adapter maintainers prefer to manage their adapter themselves or not.

**Comment by patmmccann** [comment]
@ReinoutStevens please do, we'll tag them to review

**Comment by karimMourra** [comment]
Unfortunately it appears that our interface for `playerSize` is poorly designed; It can either be an array of integers, or an array of arrays. Working with loose types is cumbersome. For now unfortunately i think the safest option is to check for both types. I've seen the following type of logic in several adapters: 
```
if (isArray(playerSize[0])) {
     videoImp.video.w = playerSize[0][0];
     videoImp.video.h = playerSize[0][1];
} else if (isNumber(playerSize[0])) {
     videoImp.video.w = playerSize[0];
     videoImp.video.h = playerSize[1];
}
```
Hopefully for the next major release we can deprecate one type and only support the other. Or possibly remove the entire concept of `playerSize` and stick to `w` and `h` as defined in ortb.

**Comment by fowler446** [comment]
Closing issue. Moved discussion here to standardization ticket:
https://github.com/prebid/Prebid.js/issues/11095#issuecomment-2083241563
